
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.animation
import android.content
import android.graphics
import android.util
import android.view
import java.lang
import java.util
import typing



class Animation(java.lang.Cloneable):
    ABSOLUTE: typing.ClassVar[int] = ...
    INFINITE: typing.ClassVar[int] = ...
    RELATIVE_TO_PARENT: typing.ClassVar[int] = ...
    RELATIVE_TO_SELF: typing.ClassVar[int] = ...
    RESTART: typing.ClassVar[int] = ...
    REVERSE: typing.ClassVar[int] = ...
    START_ON_FIRST_FRAME: typing.ClassVar[int] = ...
    ZORDER_BOTTOM: typing.ClassVar[int] = ...
    ZORDER_NORMAL: typing.ClassVar[int] = ...
    ZORDER_TOP: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def cancel(self) -> None: ...
    def computeDurationHint(self) -> int: ...
    def getBackdropColor(self) -> int: ...
    def getBackgroundColor(self) -> int: ...
    def getDetachWallpaper(self) -> bool: ...
    def getDuration(self) -> int: ...
    def getFillAfter(self) -> bool: ...
    def getFillBefore(self) -> bool: ...
    def getInterpolator(self) -> 'Interpolator': ...
    def getRepeatCount(self) -> int: ...
    def getRepeatMode(self) -> int: ...
    def getShowBackdrop(self) -> bool: ...
    def getStartOffset(self) -> int: ...
    def getStartTime(self) -> int: ...
    @typing.overload
    def getTransformation(self, long: int, transformation: 'Transformation') -> bool: ...
    @typing.overload
    def getTransformation(self, long: int, transformation: 'Transformation', float: float) -> bool: ...
    def getZAdjustment(self) -> int: ...
    def hasEnded(self) -> bool: ...
    def hasStarted(self) -> bool: ...
    def initialize(self, int: int, int2: int, int3: int, int4: int) -> None: ...
    def isFillEnabled(self) -> bool: ...
    def isInitialized(self) -> bool: ...
    def reset(self) -> None: ...
    def restrictDuration(self, long: int) -> None: ...
    def scaleCurrentDuration(self, float: float) -> None: ...
    def setAnimationListener(self, animationListener: 'Animation.AnimationListener') -> None: ...
    def setBackdropColor(self, int: int) -> None: ...
    def setBackgroundColor(self, int: int) -> None: ...
    def setDetachWallpaper(self, boolean: bool) -> None: ...
    def setDuration(self, long: int) -> None: ...
    def setFillAfter(self, boolean: bool) -> None: ...
    def setFillBefore(self, boolean: bool) -> None: ...
    def setFillEnabled(self, boolean: bool) -> None: ...
    @typing.overload
    def setInterpolator(self, context: android.content.Context, int: int) -> None: ...
    @typing.overload
    def setInterpolator(self, interpolator: typing.Union['Interpolator', typing.Callable]) -> None: ...
    def setRepeatCount(self, int: int) -> None: ...
    def setRepeatMode(self, int: int) -> None: ...
    def setShowBackdrop(self, boolean: bool) -> None: ...
    def setStartOffset(self, long: int) -> None: ...
    def setStartTime(self, long: int) -> None: ...
    def setZAdjustment(self, int: int) -> None: ...
    def start(self) -> None: ...
    def startNow(self) -> None: ...
    def willChangeBounds(self) -> bool: ...
    def willChangeTransformationMatrix(self) -> bool: ...
    class AnimationListener:
        def onAnimationEnd(self, animation: 'Animation') -> None: ...
        def onAnimationRepeat(self, animation: 'Animation') -> None: ...
        def onAnimationStart(self, animation: 'Animation') -> None: ...

class AnimationUtils:
    def __init__(self): ...
    @staticmethod
    def currentAnimationTimeMillis() -> int: ...
    @staticmethod
    def loadAnimation(context: android.content.Context, int: int) -> Animation: ...
    @staticmethod
    def loadInterpolator(context: android.content.Context, int: int) -> 'Interpolator': ...
    @staticmethod
    def loadLayoutAnimation(context: android.content.Context, int: int) -> 'LayoutAnimationController': ...
    @staticmethod
    def makeInAnimation(context: android.content.Context, boolean: bool) -> Animation: ...
    @staticmethod
    def makeInChildBottomAnimation(context: android.content.Context) -> Animation: ...
    @staticmethod
    def makeOutAnimation(context: android.content.Context, boolean: bool) -> Animation: ...

class Interpolator(android.animation.TimeInterpolator): ...

class LayoutAnimationController:
    ORDER_NORMAL: typing.ClassVar[int] = ...
    ORDER_RANDOM: typing.ClassVar[int] = ...
    ORDER_REVERSE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, animation: Animation): ...
    @typing.overload
    def __init__(self, animation: Animation, float: float): ...
    def getAnimation(self) -> Animation: ...
    def getAnimationForView(self, view: android.view.View) -> Animation: ...
    def getDelay(self) -> float: ...
    def getInterpolator(self) -> Interpolator: ...
    def getOrder(self) -> int: ...
    def isDone(self) -> bool: ...
    @typing.overload
    def setAnimation(self, context: android.content.Context, int: int) -> None: ...
    @typing.overload
    def setAnimation(self, animation: Animation) -> None: ...
    def setDelay(self, float: float) -> None: ...
    @typing.overload
    def setInterpolator(self, context: android.content.Context, int: int) -> None: ...
    @typing.overload
    def setInterpolator(self, interpolator: typing.Union[Interpolator, typing.Callable]) -> None: ...
    def setOrder(self, int: int) -> None: ...
    def start(self) -> None: ...
    def willOverlap(self) -> bool: ...
    class AnimationParameters:
        count: int = ...
        index: int = ...
        def __init__(self): ...

class Transformation:
    TYPE_ALPHA: typing.ClassVar[int] = ...
    TYPE_BOTH: typing.ClassVar[int] = ...
    TYPE_IDENTITY: typing.ClassVar[int] = ...
    TYPE_MATRIX: typing.ClassVar[int] = ...
    def __init__(self): ...
    def clear(self) -> None: ...
    def compose(self, transformation: 'Transformation') -> None: ...
    def getAlpha(self) -> float: ...
    def getMatrix(self) -> android.graphics.Matrix: ...
    def getTransformationType(self) -> int: ...
    def set(self, transformation: 'Transformation') -> None: ...
    def setAlpha(self, float: float) -> None: ...
    def setTransformationType(self, int: int) -> None: ...
    def toShortString(self) -> str: ...
    def toString(self) -> str: ...

class AlphaAnimation(Animation):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float, float2: float): ...
    def willChangeBounds(self) -> bool: ...
    def willChangeTransformationMatrix(self) -> bool: ...

class AnimationSet(Animation):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, boolean: bool): ...
    def addAnimation(self, animation: Animation) -> None: ...
    def computeDurationHint(self) -> int: ...
    def getAnimations(self) -> java.util.List[Animation]: ...
    def getDuration(self) -> int: ...
    def getStartTime(self) -> int: ...
    @typing.overload
    def getTransformation(self, long: int, transformation: Transformation, float: float) -> bool: ...
    @typing.overload
    def getTransformation(self, long: int, transformation: Transformation) -> bool: ...
    def initialize(self, int: int, int2: int, int3: int, int4: int) -> None: ...
    def reset(self) -> None: ...
    def restrictDuration(self, long: int) -> None: ...
    def scaleCurrentDuration(self, float: float) -> None: ...
    def setDuration(self, long: int) -> None: ...
    def setFillAfter(self, boolean: bool) -> None: ...
    def setFillBefore(self, boolean: bool) -> None: ...
    def setRepeatMode(self, int: int) -> None: ...
    def setStartOffset(self, long: int) -> None: ...
    def setStartTime(self, long: int) -> None: ...
    def willChangeBounds(self) -> bool: ...
    def willChangeTransformationMatrix(self) -> bool: ...

class BaseInterpolator(Interpolator):
    def __init__(self): ...

class GridLayoutAnimationController(LayoutAnimationController):
    DIRECTION_BOTTOM_TO_TOP: typing.ClassVar[int] = ...
    DIRECTION_HORIZONTAL_MASK: typing.ClassVar[int] = ...
    DIRECTION_LEFT_TO_RIGHT: typing.ClassVar[int] = ...
    DIRECTION_RIGHT_TO_LEFT: typing.ClassVar[int] = ...
    DIRECTION_TOP_TO_BOTTOM: typing.ClassVar[int] = ...
    DIRECTION_VERTICAL_MASK: typing.ClassVar[int] = ...
    PRIORITY_COLUMN: typing.ClassVar[int] = ...
    PRIORITY_NONE: typing.ClassVar[int] = ...
    PRIORITY_ROW: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, animation: Animation): ...
    @typing.overload
    def __init__(self, animation: Animation, float: float, float2: float): ...
    def getColumnDelay(self) -> float: ...
    def getDirection(self) -> int: ...
    def getDirectionPriority(self) -> int: ...
    def getRowDelay(self) -> float: ...
    def setColumnDelay(self, float: float) -> None: ...
    def setDirection(self, int: int) -> None: ...
    def setDirectionPriority(self, int: int) -> None: ...
    def setRowDelay(self, float: float) -> None: ...
    def willOverlap(self) -> bool: ...
    class AnimationParameters(LayoutAnimationController.AnimationParameters):
        column: int = ...
        columnsCount: int = ...
        row: int = ...
        rowsCount: int = ...
        def __init__(self): ...

class RotateAnimation(Animation):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float, float2: float): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float): ...
    @typing.overload
    def __init__(self, float: float, float2: float, int: int, float3: float, int2: int, float4: float): ...
    def initialize(self, int: int, int2: int, int3: int, int4: int) -> None: ...

class ScaleAnimation(Animation):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float, float5: float, float6: float): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float, int: int, float5: float, int2: int, float6: float): ...
    def initialize(self, int: int, int2: int, int3: int, int4: int) -> None: ...

class TranslateAnimation(Animation):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float): ...
    @typing.overload
    def __init__(self, int: int, float: float, int2: int, float2: float, int3: int, float3: float, int4: int, float4: float): ...
    def initialize(self, int: int, int2: int, int3: int, int4: int) -> None: ...

class AccelerateDecelerateInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def getInterpolation(self, float: float) -> float: ...

class AccelerateInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float): ...
    def getInterpolation(self, float: float) -> float: ...

class AnticipateInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float): ...
    def getInterpolation(self, float: float) -> float: ...

class AnticipateOvershootInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float): ...
    @typing.overload
    def __init__(self, float: float, float2: float): ...
    def getInterpolation(self, float: float) -> float: ...

class BounceInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def getInterpolation(self, float: float) -> float: ...

class CycleInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float): ...
    def getInterpolation(self, float: float) -> float: ...

class DecelerateInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float): ...
    def getInterpolation(self, float: float) -> float: ...

class LinearInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def getInterpolation(self, float: float) -> float: ...

class OvershootInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, float: float): ...
    def getInterpolation(self, float: float) -> float: ...

class PathInterpolator(BaseInterpolator):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, path: android.graphics.Path): ...
    @typing.overload
    def __init__(self, float: float, float2: float): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float): ...
    def getInterpolation(self, float: float) -> float: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.animation")``.

    AccelerateDecelerateInterpolator: typing.Type[AccelerateDecelerateInterpolator]
    AccelerateInterpolator: typing.Type[AccelerateInterpolator]
    AlphaAnimation: typing.Type[AlphaAnimation]
    Animation: typing.Type[Animation]
    AnimationSet: typing.Type[AnimationSet]
    AnimationUtils: typing.Type[AnimationUtils]
    AnticipateInterpolator: typing.Type[AnticipateInterpolator]
    AnticipateOvershootInterpolator: typing.Type[AnticipateOvershootInterpolator]
    BaseInterpolator: typing.Type[BaseInterpolator]
    BounceInterpolator: typing.Type[BounceInterpolator]
    CycleInterpolator: typing.Type[CycleInterpolator]
    DecelerateInterpolator: typing.Type[DecelerateInterpolator]
    GridLayoutAnimationController: typing.Type[GridLayoutAnimationController]
    Interpolator: typing.Type[Interpolator]
    LayoutAnimationController: typing.Type[LayoutAnimationController]
    LinearInterpolator: typing.Type[LinearInterpolator]
    OvershootInterpolator: typing.Type[OvershootInterpolator]
    PathInterpolator: typing.Type[PathInterpolator]
    RotateAnimation: typing.Type[RotateAnimation]
    ScaleAnimation: typing.Type[ScaleAnimation]
    Transformation: typing.Type[Transformation]
    TranslateAnimation: typing.Type[TranslateAnimation]
