
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.lang
import java.util
import java.util.concurrent
import typing



class VirtualDevice(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDeviceId(self) -> int: ...
    def getDisplayIds(self) -> typing.MutableSequence[int]: ...
    def getDisplayName(self) -> java.lang.CharSequence: ...
    def getName(self) -> str: ...
    def getPersistentDeviceId(self) -> str: ...
    def hasCustomSensorSupport(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class VirtualDeviceManager:
    def getVirtualDevice(self, int: int) -> VirtualDevice: ...
    def getVirtualDevices(self) -> java.util.List[VirtualDevice]: ...
    def registerVirtualDeviceListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], virtualDeviceListener: 'VirtualDeviceManager.VirtualDeviceListener') -> None: ...
    def unregisterVirtualDeviceListener(self, virtualDeviceListener: 'VirtualDeviceManager.VirtualDeviceListener') -> None: ...
    class VirtualDeviceListener:
        def onVirtualDeviceClosed(self, int: int) -> None: ...
        def onVirtualDeviceCreated(self, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.companion.virtual")``.

    VirtualDevice: typing.Type[VirtualDevice]
    VirtualDeviceManager: typing.Type[VirtualDeviceManager]
