
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.media
import android.media.session
import android.os
import java.util
import typing



class MediaBrowser:
    EXTRA_PAGE: typing.ClassVar[str] = ...
    EXTRA_PAGE_SIZE: typing.ClassVar[str] = ...
    def __init__(self, context: android.content.Context, componentName: android.content.ComponentName, connectionCallback: 'MediaBrowser.ConnectionCallback', bundle: android.os.Bundle): ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getItem(self, string: str, itemCallback: 'MediaBrowser.ItemCallback') -> None: ...
    def getRoot(self) -> str: ...
    def getServiceComponent(self) -> android.content.ComponentName: ...
    def getSessionToken(self) -> android.media.session.MediaSession.Token: ...
    def isConnected(self) -> bool: ...
    @typing.overload
    def subscribe(self, string: str, subscriptionCallback: 'MediaBrowser.SubscriptionCallback') -> None: ...
    @typing.overload
    def subscribe(self, string: str, bundle: android.os.Bundle, subscriptionCallback: 'MediaBrowser.SubscriptionCallback') -> None: ...
    @typing.overload
    def unsubscribe(self, string: str) -> None: ...
    @typing.overload
    def unsubscribe(self, string: str, subscriptionCallback: 'MediaBrowser.SubscriptionCallback') -> None: ...
    class ConnectionCallback:
        def __init__(self): ...
        def onConnected(self) -> None: ...
        def onConnectionFailed(self) -> None: ...
        def onConnectionSuspended(self) -> None: ...
    class ItemCallback:
        def __init__(self): ...
        def onError(self, string: str) -> None: ...
        def onItemLoaded(self, mediaItem: 'MediaBrowser.MediaItem') -> None: ...
    class MediaItem(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        FLAG_BROWSABLE: typing.ClassVar[int] = ...
        FLAG_PLAYABLE: typing.ClassVar[int] = ...
        def __init__(self, mediaDescription: android.media.MediaDescription, int: int): ...
        def describeContents(self) -> int: ...
        def getDescription(self) -> android.media.MediaDescription: ...
        def getFlags(self) -> int: ...
        def getMediaId(self) -> str: ...
        def isBrowsable(self) -> bool: ...
        def isPlayable(self) -> bool: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class SubscriptionCallback:
        def __init__(self): ...
        @typing.overload
        def onChildrenLoaded(self, string: str, list: java.util.List['MediaBrowser.MediaItem']) -> None: ...
        @typing.overload
        def onChildrenLoaded(self, string: str, list: java.util.List['MediaBrowser.MediaItem'], bundle: android.os.Bundle) -> None: ...
        @typing.overload
        def onError(self, string: str) -> None: ...
        @typing.overload
        def onError(self, string: str, bundle: android.os.Bundle) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.browse")``.

    MediaBrowser: typing.Type[MediaBrowser]
