
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.net
import android.os
import java.io
import java.util
import java.util.concurrent
import jpype.protocol
import typing



class OnObbStateChangeListener:
    ERROR_ALREADY_MOUNTED: typing.ClassVar[int] = ...
    ERROR_COULD_NOT_MOUNT: typing.ClassVar[int] = ...
    ERROR_COULD_NOT_UNMOUNT: typing.ClassVar[int] = ...
    ERROR_INTERNAL: typing.ClassVar[int] = ...
    ERROR_NOT_MOUNTED: typing.ClassVar[int] = ...
    ERROR_PERMISSION_DENIED: typing.ClassVar[int] = ...
    MOUNTED: typing.ClassVar[int] = ...
    UNMOUNTED: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onObbStateChange(self, string: str, int: int) -> None: ...

class StorageManager:
    ACTION_CLEAR_APP_CACHE: typing.ClassVar[str] = ...
    ACTION_MANAGE_STORAGE: typing.ClassVar[str] = ...
    EXTRA_REQUESTED_BYTES: typing.ClassVar[str] = ...
    EXTRA_UUID: typing.ClassVar[str] = ...
    UUID_DEFAULT: typing.ClassVar[java.util.UUID] = ...
    @typing.overload
    def allocateBytes(self, fileDescriptor: java.io.FileDescriptor, long: int) -> None: ...
    @typing.overload
    def allocateBytes(self, uUID: java.util.UUID, long: int) -> None: ...
    def getAllocatableBytes(self, uUID: java.util.UUID) -> int: ...
    def getCacheQuotaBytes(self, uUID: java.util.UUID) -> int: ...
    def getCacheSizeBytes(self, uUID: java.util.UUID) -> int: ...
    def getManageSpaceActivityIntent(self, string: str, int: int) -> android.app.PendingIntent: ...
    def getMountedObbPath(self, string: str) -> str: ...
    def getPrimaryStorageVolume(self) -> 'StorageVolume': ...
    def getRecentStorageVolumes(self) -> java.util.List['StorageVolume']: ...
    @typing.overload
    def getStorageVolume(self, uri: android.net.Uri) -> 'StorageVolume': ...
    @typing.overload
    def getStorageVolume(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> 'StorageVolume': ...
    def getStorageVolumes(self) -> java.util.List['StorageVolume']: ...
    def getStorageVolumesIncludingSharedProfiles(self) -> java.util.List['StorageVolume']: ...
    def getUuidForPath(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> java.util.UUID: ...
    def isAllocationSupported(self, fileDescriptor: java.io.FileDescriptor) -> bool: ...
    def isCacheBehaviorGroup(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> bool: ...
    def isCacheBehaviorTombstone(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> bool: ...
    def isCheckpointSupported(self) -> bool: ...
    def isEncrypted(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> bool: ...
    def isObbMounted(self, string: str) -> bool: ...
    def mountObb(self, string: str, string2: str, onObbStateChangeListener: OnObbStateChangeListener) -> bool: ...
    def openProxyFileDescriptor(self, int: int, proxyFileDescriptorCallback: android.os.ProxyFileDescriptorCallback, handler: android.os.Handler) -> android.os.ParcelFileDescriptor: ...
    def registerStorageVolumeCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], storageVolumeCallback: 'StorageManager.StorageVolumeCallback') -> None: ...
    def setCacheBehaviorGroup(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], boolean: bool) -> None: ...
    def setCacheBehaviorTombstone(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], boolean: bool) -> None: ...
    def unmountObb(self, string: str, boolean: bool, onObbStateChangeListener: OnObbStateChangeListener) -> bool: ...
    def unregisterStorageVolumeCallback(self, storageVolumeCallback: 'StorageManager.StorageVolumeCallback') -> None: ...
    class StorageVolumeCallback:
        def __init__(self): ...
        def onStateChanged(self, storageVolume: 'StorageVolume') -> None: ...

class StorageVolume(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EXTRA_STORAGE_VOLUME: typing.ClassVar[str] = ...
    def createAccessIntent(self, string: str) -> android.content.Intent: ...
    def createOpenDocumentTreeIntent(self) -> android.content.Intent: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDescription(self, context: android.content.Context) -> str: ...
    def getDirectory(self) -> java.io.File: ...
    def getMediaStoreVolumeName(self) -> str: ...
    def getOwner(self) -> android.os.UserHandle: ...
    def getState(self) -> str: ...
    def getStorageUuid(self) -> java.util.UUID: ...
    def getUuid(self) -> str: ...
    def hashCode(self) -> int: ...
    def isEmulated(self) -> bool: ...
    def isPrimary(self) -> bool: ...
    def isRemovable(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.os.storage")``.

    OnObbStateChangeListener: typing.Type[OnObbStateChangeListener]
    StorageManager: typing.Type[StorageManager]
    StorageVolume: typing.Type[StorageVolume]
