
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.hardware.camera2
import android.os
import android.util
import android.view
import java.lang
import java.util
import java.util.concurrent
import jpype
import typing



class BlackLevelPattern:
    COUNT: typing.ClassVar[int] = ...
    def __init__(self, intArray: typing.Union[typing.List[int], jpype.JArray]): ...
    def copyTo(self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOffsetForIndex(self, int: int, int2: int) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Capability:
    def __init__(self, int: int, size: android.util.Size, range: android.util.Range[float]): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMaxStreamingSize(self) -> android.util.Size: ...
    def getMode(self) -> int: ...
    def getZoomRatioRange(self) -> android.util.Range[float]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ColorSpaceProfiles:
    UNSPECIFIED: typing.ClassVar[int] = ...
    def __init__(self, longArray: typing.Union[typing.List[int], jpype.JArray]): ...
    def getSupportedColorSpaces(self, int: int) -> java.util.Set[android.graphics.ColorSpace.Named]: ...
    def getSupportedColorSpacesForDynamicRange(self, int: int, long: int) -> java.util.Set[android.graphics.ColorSpace.Named]: ...
    def getSupportedDynamicRangeProfiles(self, named: android.graphics.ColorSpace.Named, int: int) -> java.util.Set[int]: ...
    def getSupportedImageFormatsForColorSpace(self, named: android.graphics.ColorSpace.Named) -> java.util.Set[int]: ...

class ColorSpaceTransform:
    @typing.overload
    def __init__(self, rationalArray: typing.Union[typing.List[android.util.Rational], jpype.JArray]): ...
    @typing.overload
    def __init__(self, intArray: typing.Union[typing.List[int], jpype.JArray]): ...
    @typing.overload
    def copyElements(self, rationalArray: typing.Union[typing.List[android.util.Rational], jpype.JArray], int: int) -> None: ...
    @typing.overload
    def copyElements(self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getElement(self, int: int, int2: int) -> android.util.Rational: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class DeviceStateSensorOrientationMap:
    FOLDED: typing.ClassVar[int] = ...
    NORMAL: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSensorOrientation(self, long: int) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addOrientationForState(self, long: int, long2: int) -> 'DeviceStateSensorOrientationMap.Builder': ...
        def build(self) -> 'DeviceStateSensorOrientationMap': ...

class DynamicRangeProfiles:
    DOLBY_VISION_10B_HDR_OEM: typing.ClassVar[int] = ...
    DOLBY_VISION_10B_HDR_OEM_PO: typing.ClassVar[int] = ...
    DOLBY_VISION_10B_HDR_REF: typing.ClassVar[int] = ...
    DOLBY_VISION_10B_HDR_REF_PO: typing.ClassVar[int] = ...
    DOLBY_VISION_8B_HDR_OEM: typing.ClassVar[int] = ...
    DOLBY_VISION_8B_HDR_OEM_PO: typing.ClassVar[int] = ...
    DOLBY_VISION_8B_HDR_REF: typing.ClassVar[int] = ...
    DOLBY_VISION_8B_HDR_REF_PO: typing.ClassVar[int] = ...
    HDR10: typing.ClassVar[int] = ...
    HDR10_PLUS: typing.ClassVar[int] = ...
    HLG10: typing.ClassVar[int] = ...
    PUBLIC_MAX: typing.ClassVar[int] = ...
    STANDARD: typing.ClassVar[int] = ...
    def __init__(self, longArray: typing.Union[typing.List[int], jpype.JArray]): ...
    def getProfileCaptureRequestConstraints(self, long: int) -> java.util.Set[int]: ...
    def getSupportedProfiles(self) -> java.util.Set[int]: ...
    def isExtraLatencyPresent(self, long: int) -> bool: ...

class ExtensionSessionConfiguration:
    def __init__(self, int: int, list: java.util.List['OutputConfiguration'], executor: typing.Union[java.util.concurrent.Executor, typing.Callable], stateCallback: android.hardware.camera2.CameraExtensionSession.StateCallback): ...
    def clearColorSpace(self) -> None: ...
    def getColorSpace(self) -> android.graphics.ColorSpace: ...
    def getExecutor(self) -> java.util.concurrent.Executor: ...
    def getExtension(self) -> int: ...
    def getOutputConfigurations(self) -> java.util.List['OutputConfiguration']: ...
    def getPostviewOutputConfiguration(self) -> 'OutputConfiguration': ...
    def getStateCallback(self) -> android.hardware.camera2.CameraExtensionSession.StateCallback: ...
    def setColorSpace(self, named: android.graphics.ColorSpace.Named) -> None: ...
    def setPostviewOutputConfiguration(self, outputConfiguration: 'OutputConfiguration') -> None: ...

class Face:
    ID_UNSUPPORTED: typing.ClassVar[int] = ...
    SCORE_MAX: typing.ClassVar[int] = ...
    SCORE_MIN: typing.ClassVar[int] = ...
    def getBounds(self) -> android.graphics.Rect: ...
    def getId(self) -> int: ...
    def getLeftEyePosition(self) -> android.graphics.Point: ...
    def getMouthPosition(self) -> android.graphics.Point: ...
    def getRightEyePosition(self) -> android.graphics.Point: ...
    def getScore(self) -> int: ...
    def toString(self) -> str: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, face: 'Face'): ...
        def build(self) -> 'Face': ...
        def setBounds(self, rect: android.graphics.Rect) -> 'Face.Builder': ...
        def setId(self, int: int) -> 'Face.Builder': ...
        def setLeftEyePosition(self, point: android.graphics.Point) -> 'Face.Builder': ...
        def setMouthPosition(self, point: android.graphics.Point) -> 'Face.Builder': ...
        def setRightEyePosition(self, point: android.graphics.Point) -> 'Face.Builder': ...
        def setScore(self, int: int) -> 'Face.Builder': ...

class InputConfiguration:
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, collection: typing.Union[java.util.Collection['MultiResolutionStreamInfo'], typing.Sequence['MultiResolutionStreamInfo'], typing.Set['MultiResolutionStreamInfo']], int: int): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFormat(self) -> int: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def hashCode(self) -> int: ...
    def isMultiResolution(self) -> bool: ...
    def toString(self) -> str: ...

class LensIntrinsicsSample:
    def __init__(self, long: int, floatArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLensIntrinsics(self) -> typing.MutableSequence[float]: ...
    def getTimestampNanos(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class LensShadingMap:
    MINIMUM_GAIN_FACTOR: typing.ClassVar[float] = ...
    def copyGainFactors(self, floatArray: typing.Union[typing.List[float], jpype.JArray], int: int) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getColumnCount(self) -> int: ...
    def getGainFactor(self, int: int, int2: int, int3: int) -> float: ...
    def getGainFactorCount(self) -> int: ...
    def getGainFactorVector(self, int: int, int2: int) -> 'RggbChannelVector': ...
    def getRowCount(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class MandatoryStreamCombination:
    def equals(self, object: typing.Any) -> bool: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getStreamsInformation(self) -> java.util.List['MandatoryStreamCombination.MandatoryStreamInformation']: ...
    def hashCode(self) -> int: ...
    def isReprocessable(self) -> bool: ...
    class MandatoryStreamInformation:
        def equals(self, object: typing.Any) -> bool: ...
        def get10BitFormat(self) -> int: ...
        def getAvailableSizes(self) -> java.util.List[android.util.Size]: ...
        def getFormat(self) -> int: ...
        def getStreamUseCase(self) -> int: ...
        def hashCode(self) -> int: ...
        def is10BitCapable(self) -> bool: ...
        def isInput(self) -> bool: ...
        def isMaximumSize(self) -> bool: ...
        def isUltraHighResolution(self) -> bool: ...

class MeteringRectangle:
    METERING_WEIGHT_DONT_CARE: typing.ClassVar[int] = ...
    METERING_WEIGHT_MAX: typing.ClassVar[int] = ...
    METERING_WEIGHT_MIN: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, point: android.graphics.Point, size: android.util.Size, int: int): ...
    @typing.overload
    def __init__(self, rect: android.graphics.Rect, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int): ...
    @typing.overload
    def equals(self, meteringRectangle: 'MeteringRectangle') -> bool: ...
    @typing.overload
    def equals(self, object: typing.Any) -> bool: ...
    def getHeight(self) -> int: ...
    def getMeteringWeight(self) -> int: ...
    def getRect(self) -> android.graphics.Rect: ...
    def getSize(self) -> android.util.Size: ...
    def getUpperLeftPoint(self) -> android.graphics.Point: ...
    def getWidth(self) -> int: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class MultiResolutionStreamConfigurationMap:
    def equals(self, object: typing.Any) -> bool: ...
    def getInputFormats(self) -> typing.MutableSequence[int]: ...
    def getInputInfo(self, int: int) -> java.util.Collection['MultiResolutionStreamInfo']: ...
    def getOutputFormats(self) -> typing.MutableSequence[int]: ...
    def getOutputInfo(self, int: int) -> java.util.Collection['MultiResolutionStreamInfo']: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class MultiResolutionStreamInfo:
    def __init__(self, int: int, int2: int, string: str): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHeight(self) -> int: ...
    def getPhysicalCameraId(self) -> str: ...
    def getWidth(self) -> int: ...
    def hashCode(self) -> int: ...

class OisSample:
    def __init__(self, long: int, float: float, float2: float): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getTimestamp(self) -> int: ...
    def getXshift(self) -> float: ...
    def getYshift(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class OutputConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    MIRROR_MODE_AUTO: typing.ClassVar[int] = ...
    MIRROR_MODE_H: typing.ClassVar[int] = ...
    MIRROR_MODE_NONE: typing.ClassVar[int] = ...
    MIRROR_MODE_V: typing.ClassVar[int] = ...
    SURFACE_GROUP_ID_NONE: typing.ClassVar[int] = ...
    TIMESTAMP_BASE_CHOREOGRAPHER_SYNCED: typing.ClassVar[int] = ...
    TIMESTAMP_BASE_DEFAULT: typing.ClassVar[int] = ...
    TIMESTAMP_BASE_MONOTONIC: typing.ClassVar[int] = ...
    TIMESTAMP_BASE_REALTIME: typing.ClassVar[int] = ...
    TIMESTAMP_BASE_SENSOR: typing.ClassVar[int] = ...
    ___init___0__T = typing.TypeVar('___init___0__T')  # <T>
    @typing.overload
    def __init__(self, size: android.util.Size, class_: typing.Type[___init___0__T]): ...
    @typing.overload
    def __init__(self, surface: android.view.Surface): ...
    @typing.overload
    def __init__(self, int: int, size: android.util.Size): ...
    @typing.overload
    def __init__(self, int: int, size: android.util.Size, long: int): ...
    @typing.overload
    def __init__(self, int: int, surface: android.view.Surface): ...
    @typing.overload
    def __init__(self, int: int, int2: int, size: android.util.Size): ...
    @typing.overload
    def __init__(self, int: int, int2: int, size: android.util.Size, long: int): ...
    def addSensorPixelModeUsed(self, int: int) -> None: ...
    def addSurface(self, surface: android.view.Surface) -> None: ...
    @typing.overload
    @staticmethod
    def createInstancesForMultiResolutionOutput(multiResolutionImageReader: android.hardware.camera2.MultiResolutionImageReader) -> java.util.Collection['OutputConfiguration']: ...
    @typing.overload
    @staticmethod
    def createInstancesForMultiResolutionOutput(collection: typing.Union[java.util.Collection[MultiResolutionStreamInfo], typing.Sequence[MultiResolutionStreamInfo], typing.Set[MultiResolutionStreamInfo]], int: int) -> java.util.List['OutputConfiguration']: ...
    def describeContents(self) -> int: ...
    def enableSurfaceSharing(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDynamicRangeProfile(self) -> int: ...
    def getMaxSharedSurfaceCount(self) -> int: ...
    def getMirrorMode(self) -> int: ...
    def getStreamUseCase(self) -> int: ...
    def getSurface(self) -> android.view.Surface: ...
    def getSurfaceGroupId(self) -> int: ...
    def getSurfaces(self) -> java.util.List[android.view.Surface]: ...
    def getTimestampBase(self) -> int: ...
    def hashCode(self) -> int: ...
    def isReadoutTimestampEnabled(self) -> bool: ...
    def removeSensorPixelModeUsed(self, int: int) -> None: ...
    def removeSurface(self, surface: android.view.Surface) -> None: ...
    def setDynamicRangeProfile(self, long: int) -> None: ...
    def setMirrorMode(self, int: int) -> None: ...
    def setPhysicalCameraId(self, string: str) -> None: ...
    def setReadoutTimestampEnabled(self, boolean: bool) -> None: ...
    def setStreamUseCase(self, long: int) -> None: ...
    @staticmethod
    def setSurfacesForMultiResolutionOutput(collection: typing.Union[java.util.Collection['OutputConfiguration'], typing.Sequence['OutputConfiguration'], typing.Set['OutputConfiguration']], multiResolutionImageReader: android.hardware.camera2.MultiResolutionImageReader) -> None: ...
    def setTimestampBase(self, int: int) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class RecommendedStreamConfigurationMap:
    USECASE_10BIT_OUTPUT: typing.ClassVar[int] = ...
    USECASE_LOW_LATENCY_SNAPSHOT: typing.ClassVar[int] = ...
    USECASE_PREVIEW: typing.ClassVar[int] = ...
    USECASE_RAW: typing.ClassVar[int] = ...
    USECASE_RECORD: typing.ClassVar[int] = ...
    USECASE_SNAPSHOT: typing.ClassVar[int] = ...
    USECASE_VIDEO_SNAPSHOT: typing.ClassVar[int] = ...
    USECASE_ZSL: typing.ClassVar[int] = ...
    def getHighResolutionOutputSizes(self, int: int) -> java.util.Set[android.util.Size]: ...
    def getHighSpeedVideoFpsRanges(self) -> java.util.Set[android.util.Range[int]]: ...
    def getHighSpeedVideoFpsRangesFor(self, size: android.util.Size) -> java.util.Set[android.util.Range[int]]: ...
    def getHighSpeedVideoSizes(self) -> java.util.Set[android.util.Size]: ...
    def getHighSpeedVideoSizesFor(self, range: android.util.Range[int]) -> java.util.Set[android.util.Size]: ...
    def getInputFormats(self) -> java.util.Set[int]: ...
    def getInputSizes(self, int: int) -> java.util.Set[android.util.Size]: ...
    def getOutputFormats(self) -> java.util.Set[int]: ...
    _getOutputMinFrameDuration_1__T = typing.TypeVar('_getOutputMinFrameDuration_1__T')  # <T>
    @typing.overload
    def getOutputMinFrameDuration(self, int: int, size: android.util.Size) -> int: ...
    @typing.overload
    def getOutputMinFrameDuration(self, class_: typing.Type[_getOutputMinFrameDuration_1__T], size: android.util.Size) -> int: ...
    _getOutputSizes_1__T = typing.TypeVar('_getOutputSizes_1__T')  # <T>
    @typing.overload
    def getOutputSizes(self, int: int) -> java.util.Set[android.util.Size]: ...
    @typing.overload
    def getOutputSizes(self, class_: typing.Type[_getOutputSizes_1__T]) -> java.util.Set[android.util.Size]: ...
    _getOutputStallDuration_1__T = typing.TypeVar('_getOutputStallDuration_1__T')  # <T>
    @typing.overload
    def getOutputStallDuration(self, int: int, size: android.util.Size) -> int: ...
    @typing.overload
    def getOutputStallDuration(self, class_: typing.Type[_getOutputStallDuration_1__T], size: android.util.Size) -> int: ...
    def getRecommendedUseCase(self) -> int: ...
    def getValidOutputFormatsForInput(self, int: int) -> java.util.Set[int]: ...
    @typing.overload
    def isOutputSupportedFor(self, surface: android.view.Surface) -> bool: ...
    @typing.overload
    def isOutputSupportedFor(self, int: int) -> bool: ...

class RggbChannelVector:
    BLUE: typing.ClassVar[int] = ...
    COUNT: typing.ClassVar[int] = ...
    GREEN_EVEN: typing.ClassVar[int] = ...
    GREEN_ODD: typing.ClassVar[int] = ...
    RED: typing.ClassVar[int] = ...
    def __init__(self, float: float, float2: float, float3: float, float4: float): ...
    def copyTo(self, floatArray: typing.Union[typing.List[float], jpype.JArray], int: int) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBlue(self) -> float: ...
    def getComponent(self, int: int) -> float: ...
    def getGreenEven(self) -> float: ...
    def getGreenOdd(self) -> float: ...
    def getRed(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class SessionConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SESSION_HIGH_SPEED: typing.ClassVar[int] = ...
    SESSION_REGULAR: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int, list: java.util.List[OutputConfiguration]): ...
    @typing.overload
    def __init__(self, int: int, list: java.util.List[OutputConfiguration], executor: typing.Union[java.util.concurrent.Executor, typing.Callable], stateCallback: android.hardware.camera2.CameraCaptureSession.StateCallback): ...
    def clearColorSpace(self) -> None: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getColorSpace(self) -> android.graphics.ColorSpace: ...
    def getExecutor(self) -> java.util.concurrent.Executor: ...
    def getInputConfiguration(self) -> InputConfiguration: ...
    def getOutputConfigurations(self) -> java.util.List[OutputConfiguration]: ...
    def getSessionParameters(self) -> android.hardware.camera2.CaptureRequest: ...
    def getSessionType(self) -> int: ...
    def getStateCallback(self) -> android.hardware.camera2.CameraCaptureSession.StateCallback: ...
    def hashCode(self) -> int: ...
    def setColorSpace(self, named: android.graphics.ColorSpace.Named) -> None: ...
    def setInputConfiguration(self, inputConfiguration: InputConfiguration) -> None: ...
    def setSessionParameters(self, captureRequest: android.hardware.camera2.CaptureRequest) -> None: ...
    def setStateCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], stateCallback: android.hardware.camera2.CameraCaptureSession.StateCallback) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StreamConfigurationMap:
    def equals(self, object: typing.Any) -> bool: ...
    def getHighResolutionOutputSizes(self, int: int) -> typing.MutableSequence[android.util.Size]: ...
    def getHighSpeedVideoFpsRanges(self) -> typing.MutableSequence[android.util.Range[int]]: ...
    def getHighSpeedVideoFpsRangesFor(self, size: android.util.Size) -> typing.MutableSequence[android.util.Range[int]]: ...
    def getHighSpeedVideoSizes(self) -> typing.MutableSequence[android.util.Size]: ...
    def getHighSpeedVideoSizesFor(self, range: android.util.Range[int]) -> typing.MutableSequence[android.util.Size]: ...
    def getInputFormats(self) -> typing.MutableSequence[int]: ...
    def getInputSizes(self, int: int) -> typing.MutableSequence[android.util.Size]: ...
    def getOutputFormats(self) -> typing.MutableSequence[int]: ...
    _getOutputMinFrameDuration_1__T = typing.TypeVar('_getOutputMinFrameDuration_1__T')  # <T>
    @typing.overload
    def getOutputMinFrameDuration(self, int: int, size: android.util.Size) -> int: ...
    @typing.overload
    def getOutputMinFrameDuration(self, class_: typing.Type[_getOutputMinFrameDuration_1__T], size: android.util.Size) -> int: ...
    _getOutputSizes_1__T = typing.TypeVar('_getOutputSizes_1__T')  # <T>
    @typing.overload
    def getOutputSizes(self, int: int) -> typing.MutableSequence[android.util.Size]: ...
    @typing.overload
    def getOutputSizes(self, class_: typing.Type[_getOutputSizes_1__T]) -> typing.MutableSequence[android.util.Size]: ...
    _getOutputStallDuration_1__T = typing.TypeVar('_getOutputStallDuration_1__T')  # <T>
    @typing.overload
    def getOutputStallDuration(self, int: int, size: android.util.Size) -> int: ...
    @typing.overload
    def getOutputStallDuration(self, class_: typing.Type[_getOutputStallDuration_1__T], size: android.util.Size) -> int: ...
    def getValidOutputFormatsForInput(self, int: int) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    _isOutputSupportedFor_2__T = typing.TypeVar('_isOutputSupportedFor_2__T')  # <T>
    @typing.overload
    def isOutputSupportedFor(self, surface: android.view.Surface) -> bool: ...
    @typing.overload
    def isOutputSupportedFor(self, int: int) -> bool: ...
    @typing.overload
    @staticmethod
    def isOutputSupportedFor(class_: typing.Type[_isOutputSupportedFor_2__T]) -> bool: ...
    def toString(self) -> str: ...

class TonemapCurve:
    CHANNEL_BLUE: typing.ClassVar[int] = ...
    CHANNEL_GREEN: typing.ClassVar[int] = ...
    CHANNEL_RED: typing.ClassVar[int] = ...
    LEVEL_BLACK: typing.ClassVar[float] = ...
    LEVEL_WHITE: typing.ClassVar[float] = ...
    POINT_SIZE: typing.ClassVar[int] = ...
    def __init__(self, floatArray: typing.Union[typing.List[float], jpype.JArray], floatArray2: typing.Union[typing.List[float], jpype.JArray], floatArray3: typing.Union[typing.List[float], jpype.JArray]): ...
    def copyColorCurve(self, int: int, floatArray: typing.Union[typing.List[float], jpype.JArray], int2: int) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPoint(self, int: int, int2: int) -> android.graphics.PointF: ...
    def getPointCount(self, int: int) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.hardware.camera2.params")``.

    BlackLevelPattern: typing.Type[BlackLevelPattern]
    Capability: typing.Type[Capability]
    ColorSpaceProfiles: typing.Type[ColorSpaceProfiles]
    ColorSpaceTransform: typing.Type[ColorSpaceTransform]
    DeviceStateSensorOrientationMap: typing.Type[DeviceStateSensorOrientationMap]
    DynamicRangeProfiles: typing.Type[DynamicRangeProfiles]
    ExtensionSessionConfiguration: typing.Type[ExtensionSessionConfiguration]
    Face: typing.Type[Face]
    InputConfiguration: typing.Type[InputConfiguration]
    LensIntrinsicsSample: typing.Type[LensIntrinsicsSample]
    LensShadingMap: typing.Type[LensShadingMap]
    MandatoryStreamCombination: typing.Type[MandatoryStreamCombination]
    MeteringRectangle: typing.Type[MeteringRectangle]
    MultiResolutionStreamConfigurationMap: typing.Type[MultiResolutionStreamConfigurationMap]
    MultiResolutionStreamInfo: typing.Type[MultiResolutionStreamInfo]
    OisSample: typing.Type[OisSample]
    OutputConfiguration: typing.Type[OutputConfiguration]
    RecommendedStreamConfigurationMap: typing.Type[RecommendedStreamConfigurationMap]
    RggbChannelVector: typing.Type[RggbChannelVector]
    SessionConfiguration: typing.Type[SessionConfiguration]
    StreamConfigurationMap: typing.Type[StreamConfigurationMap]
    TonemapCurve: typing.Type[TonemapCurve]
