
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.net
import android.os
import java.util
import jpype
import typing



class CarrierIdentifier(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], string: str, string2: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str, string4: str, string5: str, string6: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str, string4: str, string5: str, string6: str, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCarrierId(self) -> int: ...
    def getGid1(self) -> str: ...
    def getGid2(self) -> str: ...
    def getImsi(self) -> str: ...
    def getMcc(self) -> str: ...
    def getMnc(self) -> str: ...
    def getSpecificCarrierId(self) -> int: ...
    def getSpn(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CarrierMessagingClientService(android.app.Service):
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...

_CarrierMessagingService__ResultCallback__T = typing.TypeVar('_CarrierMessagingService__ResultCallback__T')  # <T>
class CarrierMessagingService(android.app.Service):
    DOWNLOAD_STATUS_ERROR: typing.ClassVar[int] = ...
    DOWNLOAD_STATUS_OK: typing.ClassVar[int] = ...
    DOWNLOAD_STATUS_RETRY_ON_CARRIER_NETWORK: typing.ClassVar[int] = ...
    RECEIVE_OPTIONS_DEFAULT: typing.ClassVar[int] = ...
    RECEIVE_OPTIONS_DROP: typing.ClassVar[int] = ...
    RECEIVE_OPTIONS_SKIP_NOTIFY_WHEN_CREDENTIAL_PROTECTED_STORAGE_UNAVAILABLE: typing.ClassVar[int] = ...
    SEND_FLAG_REQUEST_DELIVERY_STATUS: typing.ClassVar[int] = ...
    SEND_STATUS_ERROR: typing.ClassVar[int] = ...
    SEND_STATUS_OK: typing.ClassVar[int] = ...
    SEND_STATUS_RETRY_ON_CARRIER_NETWORK: typing.ClassVar[int] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onDownloadMms(self, uri: android.net.Uri, int: int, uri2: android.net.Uri, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'[int], typing.Callable[[int], None]]) -> None: ...
    def onFilterSms(self, messagePdu: 'MessagePdu', string: str, int: int, int2: int, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'[bool], typing.Callable[[bool], None]]) -> None: ...
    def onReceiveTextSms(self, messagePdu: 'MessagePdu', string: str, int: int, int2: int, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'[int], typing.Callable[[int], None]]) -> None: ...
    @typing.overload
    def onSendDataSms(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, string: str, int2: int, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendSmsResult'], typing.Callable[['CarrierMessagingService.SendSmsResult'], None]]) -> None: ...
    @typing.overload
    def onSendDataSms(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, string: str, int2: int, int3: int, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendSmsResult'], typing.Callable[['CarrierMessagingService.SendSmsResult'], None]]) -> None: ...
    def onSendMms(self, uri: android.net.Uri, int: int, uri2: android.net.Uri, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendMmsResult'], typing.Callable[['CarrierMessagingService.SendMmsResult'], None]]) -> None: ...
    @typing.overload
    def onSendMultipartTextSms(self, list: java.util.List[str], int: int, string: str, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendMultipartSmsResult'], typing.Callable[['CarrierMessagingService.SendMultipartSmsResult'], None]]) -> None: ...
    @typing.overload
    def onSendMultipartTextSms(self, list: java.util.List[str], int: int, string: str, int2: int, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendMultipartSmsResult'], typing.Callable[['CarrierMessagingService.SendMultipartSmsResult'], None]]) -> None: ...
    @typing.overload
    def onSendTextSms(self, string: str, int: int, string2: str, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendSmsResult'], typing.Callable[['CarrierMessagingService.SendSmsResult'], None]]) -> None: ...
    @typing.overload
    def onSendTextSms(self, string: str, int: int, string2: str, int2: int, resultCallback: typing.Union['CarrierMessagingService.ResultCallback'['CarrierMessagingService.SendSmsResult'], typing.Callable[['CarrierMessagingService.SendSmsResult'], None]]) -> None: ...
    class ResultCallback(typing.Generic[_CarrierMessagingService__ResultCallback__T]):
        def onReceiveResult(self, t: _CarrierMessagingService__ResultCallback__T) -> None: ...
    class SendMmsResult:
        def __init__(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
        def getSendConfPdu(self) -> typing.MutableSequence[int]: ...
        def getSendStatus(self) -> int: ...
    class SendMultipartSmsResult:
        def __init__(self, int: int, intArray: typing.Union[typing.List[int], jpype.JArray]): ...
        def getMessageRefs(self) -> typing.MutableSequence[int]: ...
        def getSendStatus(self) -> int: ...
    class SendSmsResult:
        def __init__(self, int: int, int2: int): ...
        def getMessageRef(self) -> int: ...
        def getSendStatus(self) -> int: ...

class CarrierService(android.app.Service):
    CARRIER_SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    @typing.overload
    def notifyCarrierNetworkChange(self, boolean: bool) -> None: ...
    @typing.overload
    def notifyCarrierNetworkChange(self, int: int, boolean: bool) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    @typing.overload
    def onLoadConfig(self, carrierIdentifier: CarrierIdentifier) -> android.os.PersistableBundle: ...
    @typing.overload
    def onLoadConfig(self, int: int, carrierIdentifier: CarrierIdentifier) -> android.os.PersistableBundle: ...

class MessagePdu(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List[typing.Union[typing.List[int], jpype.JArray, bytes]]): ...
    def describeContents(self) -> int: ...
    def getPdus(self) -> java.util.List[typing.MutableSequence[int]]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.carrier")``.

    CarrierIdentifier: typing.Type[CarrierIdentifier]
    CarrierMessagingClientService: typing.Type[CarrierMessagingClientService]
    CarrierMessagingService: typing.Type[CarrierMessagingService]
    CarrierService: typing.Type[CarrierService]
    MessagePdu: typing.Type[MessagePdu]
