
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content.res
import android.os
import java.lang
import java.util
import typing



class ConfigurationStats(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, configurationStats: 'ConfigurationStats'): ...
    def describeContents(self) -> int: ...
    def getActivationCount(self) -> int: ...
    def getConfiguration(self) -> android.content.res.Configuration: ...
    def getFirstTimeStamp(self) -> int: ...
    def getLastTimeActive(self) -> int: ...
    def getLastTimeStamp(self) -> int: ...
    def getTotalTimeActive(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class EventStats(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, eventStats: 'EventStats'): ...
    def add(self, eventStats: 'EventStats') -> None: ...
    def describeContents(self) -> int: ...
    def getCount(self) -> int: ...
    def getEventType(self) -> int: ...
    def getFirstTimeStamp(self) -> int: ...
    def getLastEventTime(self) -> int: ...
    def getLastTimeStamp(self) -> int: ...
    def getTotalTime(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ExternalStorageStats(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAppBytes(self) -> int: ...
    def getAudioBytes(self) -> int: ...
    def getImageBytes(self) -> int: ...
    def getTotalBytes(self) -> int: ...
    def getVideoBytes(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NetworkStats(java.lang.AutoCloseable):
    def close(self) -> None: ...
    def getNextBucket(self, bucket: 'NetworkStats.Bucket') -> bool: ...
    def hasNextBucket(self) -> bool: ...
    class Bucket:
        DEFAULT_NETWORK_ALL: typing.ClassVar[int] = ...
        DEFAULT_NETWORK_NO: typing.ClassVar[int] = ...
        DEFAULT_NETWORK_YES: typing.ClassVar[int] = ...
        METERED_ALL: typing.ClassVar[int] = ...
        METERED_NO: typing.ClassVar[int] = ...
        METERED_YES: typing.ClassVar[int] = ...
        ROAMING_ALL: typing.ClassVar[int] = ...
        ROAMING_NO: typing.ClassVar[int] = ...
        ROAMING_YES: typing.ClassVar[int] = ...
        STATE_ALL: typing.ClassVar[int] = ...
        STATE_DEFAULT: typing.ClassVar[int] = ...
        STATE_FOREGROUND: typing.ClassVar[int] = ...
        TAG_NONE: typing.ClassVar[int] = ...
        UID_ALL: typing.ClassVar[int] = ...
        UID_REMOVED: typing.ClassVar[int] = ...
        UID_TETHERING: typing.ClassVar[int] = ...
        def __init__(self): ...
        def getDefaultNetworkStatus(self) -> int: ...
        def getEndTimeStamp(self) -> int: ...
        def getMetered(self) -> int: ...
        def getRoaming(self) -> int: ...
        def getRxBytes(self) -> int: ...
        def getRxPackets(self) -> int: ...
        def getStartTimeStamp(self) -> int: ...
        def getState(self) -> int: ...
        def getTag(self) -> int: ...
        def getTxBytes(self) -> int: ...
        def getTxPackets(self) -> int: ...
        def getUid(self) -> int: ...

class NetworkStatsManager:
    def queryDetails(self, int: int, string: str, long: int, long2: int) -> NetworkStats: ...
    def queryDetailsForUid(self, int: int, string: str, long: int, long2: int, int2: int) -> NetworkStats: ...
    def queryDetailsForUidTag(self, int: int, string: str, long: int, long2: int, int2: int, int3: int) -> NetworkStats: ...
    def queryDetailsForUidTagState(self, int: int, string: str, long: int, long2: int, int2: int, int3: int, int4: int) -> NetworkStats: ...
    def querySummary(self, int: int, string: str, long: int, long2: int) -> NetworkStats: ...
    def querySummaryForDevice(self, int: int, string: str, long: int, long2: int) -> NetworkStats.Bucket: ...
    def querySummaryForUser(self, int: int, string: str, long: int, long2: int) -> NetworkStats.Bucket: ...
    @typing.overload
    def registerUsageCallback(self, int: int, string: str, long: int, usageCallback: 'NetworkStatsManager.UsageCallback') -> None: ...
    @typing.overload
    def registerUsageCallback(self, int: int, string: str, long: int, usageCallback: 'NetworkStatsManager.UsageCallback', handler: android.os.Handler) -> None: ...
    def unregisterUsageCallback(self, usageCallback: 'NetworkStatsManager.UsageCallback') -> None: ...
    class UsageCallback:
        def __init__(self): ...
        def onThresholdReached(self, int: int, string: str) -> None: ...

class StorageStats(android.os.Parcelable):
    APP_DATA_TYPE_FILE_TYPE_APK: typing.ClassVar[int] = ...
    APP_DATA_TYPE_FILE_TYPE_CURRENT_PROFILE: typing.ClassVar[int] = ...
    APP_DATA_TYPE_FILE_TYPE_DEXOPT_ARTIFACT: typing.ClassVar[int] = ...
    APP_DATA_TYPE_FILE_TYPE_DM: typing.ClassVar[int] = ...
    APP_DATA_TYPE_FILE_TYPE_REFERENCE_PROFILE: typing.ClassVar[int] = ...
    APP_DATA_TYPE_LIB: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAppBytes(self) -> int: ...
    def getAppBytesByDataType(self, int: int) -> int: ...
    def getCacheBytes(self) -> int: ...
    def getDataBytes(self) -> int: ...
    def getExternalCacheBytes(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StorageStatsManager:
    def getFreeBytes(self, uUID: java.util.UUID) -> int: ...
    def getTotalBytes(self, uUID: java.util.UUID) -> int: ...
    def queryExternalStatsForUser(self, uUID: java.util.UUID, userHandle: android.os.UserHandle) -> ExternalStorageStats: ...
    def queryStatsForPackage(self, uUID: java.util.UUID, string: str, userHandle: android.os.UserHandle) -> StorageStats: ...
    def queryStatsForUid(self, uUID: java.util.UUID, int: int) -> StorageStats: ...
    def queryStatsForUser(self, uUID: java.util.UUID, userHandle: android.os.UserHandle) -> StorageStats: ...

class UsageEvents(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getNextEvent(self, event: 'UsageEvents.Event') -> bool: ...
    def hasNextEvent(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Event:
        ACTIVITY_PAUSED: typing.ClassVar[int] = ...
        ACTIVITY_RESUMED: typing.ClassVar[int] = ...
        ACTIVITY_STOPPED: typing.ClassVar[int] = ...
        CONFIGURATION_CHANGE: typing.ClassVar[int] = ...
        DEVICE_SHUTDOWN: typing.ClassVar[int] = ...
        DEVICE_STARTUP: typing.ClassVar[int] = ...
        FOREGROUND_SERVICE_START: typing.ClassVar[int] = ...
        FOREGROUND_SERVICE_STOP: typing.ClassVar[int] = ...
        KEYGUARD_HIDDEN: typing.ClassVar[int] = ...
        KEYGUARD_SHOWN: typing.ClassVar[int] = ...
        MOVE_TO_BACKGROUND: typing.ClassVar[int] = ...
        MOVE_TO_FOREGROUND: typing.ClassVar[int] = ...
        NONE: typing.ClassVar[int] = ...
        SCREEN_INTERACTIVE: typing.ClassVar[int] = ...
        SCREEN_NON_INTERACTIVE: typing.ClassVar[int] = ...
        SHORTCUT_INVOCATION: typing.ClassVar[int] = ...
        STANDBY_BUCKET_CHANGED: typing.ClassVar[int] = ...
        USER_INTERACTION: typing.ClassVar[int] = ...
        def __init__(self): ...
        def getAppStandbyBucket(self) -> int: ...
        def getClassName(self) -> str: ...
        def getConfiguration(self) -> android.content.res.Configuration: ...
        def getEventType(self) -> int: ...
        def getExtras(self) -> android.os.PersistableBundle: ...
        def getPackageName(self) -> str: ...
        def getShortcutId(self) -> str: ...
        def getTimeStamp(self) -> int: ...

class UsageEventsQuery(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getBeginTimeMillis(self) -> int: ...
    def getEndTimeMillis(self) -> int: ...
    def getEventTypes(self) -> typing.MutableSequence[int]: ...
    def getPackageNames(self) -> java.util.Set[str]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, long: int, long2: int): ...
        def build(self) -> 'UsageEventsQuery': ...
        def setEventTypes(self, *int: int) -> 'UsageEventsQuery.Builder': ...
        def setPackageNames(self, *string: str) -> 'UsageEventsQuery.Builder': ...

class UsageStats(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, usageStats: 'UsageStats'): ...
    def add(self, usageStats: 'UsageStats') -> None: ...
    def describeContents(self) -> int: ...
    def getFirstTimeStamp(self) -> int: ...
    def getLastTimeForegroundServiceUsed(self) -> int: ...
    def getLastTimeStamp(self) -> int: ...
    def getLastTimeUsed(self) -> int: ...
    def getLastTimeVisible(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getTotalTimeForegroundServiceUsed(self) -> int: ...
    def getTotalTimeInForeground(self) -> int: ...
    def getTotalTimeVisible(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UsageStatsManager:
    EXTRA_EVENT_ACTION: typing.ClassVar[str] = ...
    EXTRA_EVENT_CATEGORY: typing.ClassVar[str] = ...
    INTERVAL_BEST: typing.ClassVar[int] = ...
    INTERVAL_DAILY: typing.ClassVar[int] = ...
    INTERVAL_MONTHLY: typing.ClassVar[int] = ...
    INTERVAL_WEEKLY: typing.ClassVar[int] = ...
    INTERVAL_YEARLY: typing.ClassVar[int] = ...
    STANDBY_BUCKET_ACTIVE: typing.ClassVar[int] = ...
    STANDBY_BUCKET_FREQUENT: typing.ClassVar[int] = ...
    STANDBY_BUCKET_RARE: typing.ClassVar[int] = ...
    STANDBY_BUCKET_RESTRICTED: typing.ClassVar[int] = ...
    STANDBY_BUCKET_WORKING_SET: typing.ClassVar[int] = ...
    def getAppStandbyBucket(self) -> int: ...
    def isAppInactive(self, string: str) -> bool: ...
    def queryAndAggregateUsageStats(self, long: int, long2: int) -> java.util.Map[str, UsageStats]: ...
    def queryConfigurations(self, int: int, long: int, long2: int) -> java.util.List[ConfigurationStats]: ...
    def queryEventStats(self, int: int, long: int, long2: int) -> java.util.List[EventStats]: ...
    @typing.overload
    def queryEvents(self, usageEventsQuery: UsageEventsQuery) -> UsageEvents: ...
    @typing.overload
    def queryEvents(self, long: int, long2: int) -> UsageEvents: ...
    def queryEventsForSelf(self, long: int, long2: int) -> UsageEvents: ...
    def queryUsageStats(self, int: int, long: int, long2: int) -> java.util.List[UsageStats]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.usage")``.

    ConfigurationStats: typing.Type[ConfigurationStats]
    EventStats: typing.Type[EventStats]
    ExternalStorageStats: typing.Type[ExternalStorageStats]
    NetworkStats: typing.Type[NetworkStats]
    NetworkStatsManager: typing.Type[NetworkStatsManager]
    StorageStats: typing.Type[StorageStats]
    StorageStatsManager: typing.Type[StorageStatsManager]
    UsageEvents: typing.Type[UsageEvents]
    UsageEventsQuery: typing.Type[UsageEventsQuery]
    UsageStats: typing.Type[UsageStats]
    UsageStatsManager: typing.Type[UsageStatsManager]
