
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.lang
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class HealthStats:
    def getDataType(self) -> str: ...
    def getMeasurement(self, int: int) -> int: ...
    def getMeasurementKeyAt(self, int: int) -> int: ...
    def getMeasurementKeyCount(self) -> int: ...
    def getMeasurements(self, int: int) -> java.util.Map[str, int]: ...
    def getMeasurementsKeyAt(self, int: int) -> int: ...
    def getMeasurementsKeyCount(self) -> int: ...
    def getStats(self, int: int) -> java.util.Map[str, 'HealthStats']: ...
    def getStatsKeyAt(self, int: int) -> int: ...
    def getStatsKeyCount(self) -> int: ...
    def getTimer(self, int: int) -> 'TimerStat': ...
    def getTimerCount(self, int: int) -> int: ...
    def getTimerKeyAt(self, int: int) -> int: ...
    def getTimerKeyCount(self) -> int: ...
    def getTimerTime(self, int: int) -> int: ...
    def getTimers(self, int: int) -> java.util.Map[str, 'TimerStat']: ...
    def getTimersKeyAt(self, int: int) -> int: ...
    def getTimersKeyCount(self) -> int: ...
    def hasMeasurement(self, int: int) -> bool: ...
    def hasMeasurements(self, int: int) -> bool: ...
    def hasStats(self, int: int) -> bool: ...
    def hasTimer(self, int: int) -> bool: ...
    def hasTimers(self, int: int) -> bool: ...

class PackageHealthStats:
    MEASUREMENTS_WAKEUP_ALARMS_COUNT: typing.ClassVar[int] = ...
    STATS_SERVICES: typing.ClassVar[int] = ...

class PidHealthStats:
    MEASUREMENT_WAKE_NESTING_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_WAKE_START_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WAKE_SUM_MS: typing.ClassVar[int] = ...

class ProcessHealthStats:
    MEASUREMENT_ANR_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_CRASHES_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_FOREGROUND_MS: typing.ClassVar[int] = ...
    MEASUREMENT_STARTS_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_SYSTEM_TIME_MS: typing.ClassVar[int] = ...
    MEASUREMENT_USER_TIME_MS: typing.ClassVar[int] = ...

class ServiceHealthStats:
    MEASUREMENT_LAUNCH_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_START_SERVICE_COUNT: typing.ClassVar[int] = ...

class SystemHealthManager:
    def getPowerMonitorReadings(self, list: java.util.List[android.os.PowerMonitor], executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[android.os.PowerMonitorReadings, java.lang.RuntimeException], typing.Callable[[android.os.PowerMonitorReadings], None]]) -> None: ...
    def getSupportedPowerMonitors(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[java.util.List[android.os.PowerMonitor]], typing.Callable[[java.util.List[android.os.PowerMonitor]], None]]) -> None: ...
    def takeMyUidSnapshot(self) -> HealthStats: ...
    def takeUidSnapshot(self, int: int) -> HealthStats: ...
    def takeUidSnapshots(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> typing.MutableSequence[HealthStats]: ...

class TimerStat(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int, long: int): ...
    def describeContents(self) -> int: ...
    def getCount(self) -> int: ...
    def getTime(self) -> int: ...
    def setCount(self, int: int) -> None: ...
    def setTime(self, long: int) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UidHealthStats:
    MEASUREMENT_BLUETOOTH_IDLE_MS: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_POWER_MAMS: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_RX_BYTES: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_RX_MS: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_RX_PACKETS: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_TX_BYTES: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_TX_MS: typing.ClassVar[int] = ...
    MEASUREMENT_BLUETOOTH_TX_PACKETS: typing.ClassVar[int] = ...
    MEASUREMENT_BUTTON_USER_ACTIVITY_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_CPU_POWER_MAMS: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_IDLE_MS: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_POWER_MAMS: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_RX_BYTES: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_RX_MS: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_RX_PACKETS: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_TX_BYTES: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_TX_MS: typing.ClassVar[int] = ...
    MEASUREMENT_MOBILE_TX_PACKETS: typing.ClassVar[int] = ...
    MEASUREMENT_OTHER_USER_ACTIVITY_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_REALTIME_BATTERY_MS: typing.ClassVar[int] = ...
    MEASUREMENT_REALTIME_SCREEN_OFF_BATTERY_MS: typing.ClassVar[int] = ...
    MEASUREMENT_SYSTEM_CPU_TIME_MS: typing.ClassVar[int] = ...
    MEASUREMENT_TOUCH_USER_ACTIVITY_COUNT: typing.ClassVar[int] = ...
    MEASUREMENT_UPTIME_BATTERY_MS: typing.ClassVar[int] = ...
    MEASUREMENT_UPTIME_SCREEN_OFF_BATTERY_MS: typing.ClassVar[int] = ...
    MEASUREMENT_USER_CPU_TIME_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_FULL_LOCK_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_IDLE_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_MULTICAST_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_POWER_MAMS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_RUNNING_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_RX_BYTES: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_RX_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_RX_PACKETS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_TX_BYTES: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_TX_MS: typing.ClassVar[int] = ...
    MEASUREMENT_WIFI_TX_PACKETS: typing.ClassVar[int] = ...
    STATS_PACKAGES: typing.ClassVar[int] = ...
    STATS_PIDS: typing.ClassVar[int] = ...
    STATS_PROCESSES: typing.ClassVar[int] = ...
    TIMERS_JOBS: typing.ClassVar[int] = ...
    TIMERS_SENSORS: typing.ClassVar[int] = ...
    TIMERS_SYNCS: typing.ClassVar[int] = ...
    TIMERS_WAKELOCKS_DRAW: typing.ClassVar[int] = ...
    TIMERS_WAKELOCKS_FULL: typing.ClassVar[int] = ...
    TIMERS_WAKELOCKS_PARTIAL: typing.ClassVar[int] = ...
    TIMERS_WAKELOCKS_WINDOW: typing.ClassVar[int] = ...
    TIMER_AUDIO: typing.ClassVar[int] = ...
    TIMER_BLUETOOTH_SCAN: typing.ClassVar[int] = ...
    TIMER_CAMERA: typing.ClassVar[int] = ...
    TIMER_FLASHLIGHT: typing.ClassVar[int] = ...
    TIMER_FOREGROUND_ACTIVITY: typing.ClassVar[int] = ...
    TIMER_GPS_SENSOR: typing.ClassVar[int] = ...
    TIMER_MOBILE_RADIO_ACTIVE: typing.ClassVar[int] = ...
    TIMER_PROCESS_STATE_BACKGROUND_MS: typing.ClassVar[int] = ...
    TIMER_PROCESS_STATE_CACHED_MS: typing.ClassVar[int] = ...
    TIMER_PROCESS_STATE_FOREGROUND_MS: typing.ClassVar[int] = ...
    TIMER_PROCESS_STATE_FOREGROUND_SERVICE_MS: typing.ClassVar[int] = ...
    TIMER_PROCESS_STATE_TOP_MS: typing.ClassVar[int] = ...
    TIMER_PROCESS_STATE_TOP_SLEEPING_MS: typing.ClassVar[int] = ...
    TIMER_VIBRATOR: typing.ClassVar[int] = ...
    TIMER_VIDEO: typing.ClassVar[int] = ...
    TIMER_WIFI_SCAN: typing.ClassVar[int] = ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.os.health")``.

    HealthStats: typing.Type[HealthStats]
    PackageHealthStats: typing.Type[PackageHealthStats]
    PidHealthStats: typing.Type[PidHealthStats]
    ProcessHealthStats: typing.Type[ProcessHealthStats]
    ServiceHealthStats: typing.Type[ServiceHealthStats]
    SystemHealthManager: typing.Type[SystemHealthManager]
    TimerStat: typing.Type[TimerStat]
    UidHealthStats: typing.Type[UidHealthStats]
