
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.net
import android.nfc.cardemulation
import android.nfc.tech
import android.os
import java.io
import java.lang
import java.util
import jpype
import typing



class AvailableNfcAntenna(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLocationX(self) -> int: ...
    def getLocationY(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class FormatException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class NdefMessage(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, ndefRecord: 'NdefRecord', *ndefRecord2: 'NdefRecord'): ...
    @typing.overload
    def __init__(self, ndefRecordArray: typing.Union[typing.List['NdefRecord'], jpype.JArray]): ...
    @typing.overload
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getByteArrayLength(self) -> int: ...
    def getRecords(self) -> typing.MutableSequence['NdefRecord']: ...
    def hashCode(self) -> int: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NdefRecord(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RTD_ALTERNATIVE_CARRIER: typing.ClassVar[typing.MutableSequence[int]] = ...
    RTD_HANDOVER_CARRIER: typing.ClassVar[typing.MutableSequence[int]] = ...
    RTD_HANDOVER_REQUEST: typing.ClassVar[typing.MutableSequence[int]] = ...
    RTD_HANDOVER_SELECT: typing.ClassVar[typing.MutableSequence[int]] = ...
    RTD_SMART_POSTER: typing.ClassVar[typing.MutableSequence[int]] = ...
    RTD_TEXT: typing.ClassVar[typing.MutableSequence[int]] = ...
    RTD_URI: typing.ClassVar[typing.MutableSequence[int]] = ...
    TNF_ABSOLUTE_URI: typing.ClassVar[int] = ...
    TNF_EMPTY: typing.ClassVar[int] = ...
    TNF_EXTERNAL_TYPE: typing.ClassVar[int] = ...
    TNF_MIME_MEDIA: typing.ClassVar[int] = ...
    TNF_UNCHANGED: typing.ClassVar[int] = ...
    TNF_UNKNOWN: typing.ClassVar[int] = ...
    TNF_WELL_KNOWN: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    @typing.overload
    def __init__(self, short: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray2: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray3: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    @staticmethod
    def createApplicationRecord(string: str) -> 'NdefRecord': ...
    @staticmethod
    def createExternal(string: str, string2: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'NdefRecord': ...
    @staticmethod
    def createMime(string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'NdefRecord': ...
    @staticmethod
    def createTextRecord(string: str, string2: str) -> 'NdefRecord': ...
    @typing.overload
    @staticmethod
    def createUri(uri: android.net.Uri) -> 'NdefRecord': ...
    @typing.overload
    @staticmethod
    def createUri(string: str) -> 'NdefRecord': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getId(self) -> typing.MutableSequence[int]: ...
    def getPayload(self) -> typing.MutableSequence[int]: ...
    def getTnf(self) -> int: ...
    def getType(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    def toMimeType(self) -> str: ...
    def toString(self) -> str: ...
    def toUri(self) -> android.net.Uri: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NfcAdapter:
    ACTION_ADAPTER_STATE_CHANGED: typing.ClassVar[str] = ...
    ACTION_NDEF_DISCOVERED: typing.ClassVar[str] = ...
    ACTION_PREFERRED_PAYMENT_CHANGED: typing.ClassVar[str] = ...
    ACTION_TAG_DISCOVERED: typing.ClassVar[str] = ...
    ACTION_TECH_DISCOVERED: typing.ClassVar[str] = ...
    ACTION_TRANSACTION_DETECTED: typing.ClassVar[str] = ...
    EXTRA_ADAPTER_STATE: typing.ClassVar[str] = ...
    EXTRA_AID: typing.ClassVar[str] = ...
    EXTRA_DATA: typing.ClassVar[str] = ...
    EXTRA_ID: typing.ClassVar[str] = ...
    EXTRA_NDEF_MESSAGES: typing.ClassVar[str] = ...
    EXTRA_PREFERRED_PAYMENT_CHANGED_REASON: typing.ClassVar[str] = ...
    EXTRA_READER_PRESENCE_CHECK_DELAY: typing.ClassVar[str] = ...
    EXTRA_SECURE_ELEMENT_NAME: typing.ClassVar[str] = ...
    EXTRA_TAG: typing.ClassVar[str] = ...
    FLAG_LISTEN_DISABLE: typing.ClassVar[int] = ...
    FLAG_LISTEN_KEEP: typing.ClassVar[int] = ...
    FLAG_LISTEN_NFC_PASSIVE_A: typing.ClassVar[int] = ...
    FLAG_LISTEN_NFC_PASSIVE_B: typing.ClassVar[int] = ...
    FLAG_LISTEN_NFC_PASSIVE_F: typing.ClassVar[int] = ...
    FLAG_READER_DISABLE: typing.ClassVar[int] = ...
    FLAG_READER_KEEP: typing.ClassVar[int] = ...
    FLAG_READER_NFC_A: typing.ClassVar[int] = ...
    FLAG_READER_NFC_B: typing.ClassVar[int] = ...
    FLAG_READER_NFC_BARCODE: typing.ClassVar[int] = ...
    FLAG_READER_NFC_F: typing.ClassVar[int] = ...
    FLAG_READER_NFC_V: typing.ClassVar[int] = ...
    FLAG_READER_NO_PLATFORM_SOUNDS: typing.ClassVar[int] = ...
    FLAG_READER_SKIP_NDEF_CHECK: typing.ClassVar[int] = ...
    PREFERRED_PAYMENT_CHANGED: typing.ClassVar[int] = ...
    PREFERRED_PAYMENT_LOADED: typing.ClassVar[int] = ...
    PREFERRED_PAYMENT_UPDATED: typing.ClassVar[int] = ...
    STATE_OFF: typing.ClassVar[int] = ...
    STATE_ON: typing.ClassVar[int] = ...
    STATE_TURNING_OFF: typing.ClassVar[int] = ...
    STATE_TURNING_ON: typing.ClassVar[int] = ...
    def disableForegroundDispatch(self, activity: android.app.Activity) -> None: ...
    def disableReaderMode(self, activity: android.app.Activity) -> None: ...
    def enableForegroundDispatch(self, activity: android.app.Activity, pendingIntent: android.app.PendingIntent, intentFilterArray: typing.Union[typing.List[android.content.IntentFilter], jpype.JArray], stringArray: typing.Union[typing.List[typing.MutableSequence[str]], jpype.JArray]) -> None: ...
    def enableReaderMode(self, activity: android.app.Activity, readerCallback: typing.Union['NfcAdapter.ReaderCallback', typing.Callable], int: int, bundle: android.os.Bundle) -> None: ...
    @staticmethod
    def getDefaultAdapter(context: android.content.Context) -> 'NfcAdapter': ...
    def getNfcAntennaInfo(self) -> 'NfcAntennaInfo': ...
    def ignore(self, tag: 'Tag', int: int, onTagRemovedListener: typing.Union['NfcAdapter.OnTagRemovedListener', typing.Callable], handler: android.os.Handler) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isObserveModeEnabled(self) -> bool: ...
    def isObserveModeSupported(self) -> bool: ...
    def isReaderOptionEnabled(self) -> bool: ...
    def isReaderOptionSupported(self) -> bool: ...
    def isSecureNfcEnabled(self) -> bool: ...
    def isSecureNfcSupported(self) -> bool: ...
    def resetDiscoveryTechnology(self, activity: android.app.Activity) -> None: ...
    def setDiscoveryTechnology(self, activity: android.app.Activity, int: int, int2: int) -> None: ...
    def setObserveModeEnabled(self, boolean: bool) -> bool: ...
    class CreateBeamUrisCallback:
        def createBeamUris(self, nfcEvent: 'NfcEvent') -> typing.MutableSequence[android.net.Uri]: ...
    class CreateNdefMessageCallback:
        def createNdefMessage(self, nfcEvent: 'NfcEvent') -> NdefMessage: ...
    class OnNdefPushCompleteCallback:
        def onNdefPushComplete(self, nfcEvent: 'NfcEvent') -> None: ...
    class OnTagRemovedListener:
        def onTagRemoved(self) -> None: ...
    class ReaderCallback:
        def onTagDiscovered(self, tag: 'Tag') -> None: ...

class NfcAntennaInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, boolean: bool, list: java.util.List[AvailableNfcAntenna]): ...
    def describeContents(self) -> int: ...
    def getAvailableNfcAntennas(self) -> java.util.List[AvailableNfcAntenna]: ...
    def getDeviceHeight(self) -> int: ...
    def getDeviceWidth(self) -> int: ...
    def isDeviceFoldable(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NfcEvent:
    nfcAdapter: NfcAdapter = ...
    peerLlcpMajorVersion: int = ...
    peerLlcpMinorVersion: int = ...

class NfcManager:
    def getDefaultAdapter(self) -> NfcAdapter: ...

class Tag(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getId(self) -> typing.MutableSequence[int]: ...
    def getTechList(self) -> typing.MutableSequence[str]: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TagLostException(java.io.IOException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.nfc")``.

    AvailableNfcAntenna: typing.Type[AvailableNfcAntenna]
    FormatException: typing.Type[FormatException]
    NdefMessage: typing.Type[NdefMessage]
    NdefRecord: typing.Type[NdefRecord]
    NfcAdapter: typing.Type[NfcAdapter]
    NfcAntennaInfo: typing.Type[NfcAntennaInfo]
    NfcEvent: typing.Type[NfcEvent]
    NfcManager: typing.Type[NfcManager]
    Tag: typing.Type[Tag]
    TagLostException: typing.Type[TagLostException]
    cardemulation: android.nfc.cardemulation.__module_protocol__
    tech: android.nfc.tech.__module_protocol__
