
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.lang
import java.security
import javax.crypto
import typing



class FingerprintManager:
    FINGERPRINT_ACQUIRED_GOOD: typing.ClassVar[int] = ...
    FINGERPRINT_ACQUIRED_IMAGER_DIRTY: typing.ClassVar[int] = ...
    FINGERPRINT_ACQUIRED_INSUFFICIENT: typing.ClassVar[int] = ...
    FINGERPRINT_ACQUIRED_PARTIAL: typing.ClassVar[int] = ...
    FINGERPRINT_ACQUIRED_TOO_FAST: typing.ClassVar[int] = ...
    FINGERPRINT_ACQUIRED_TOO_SLOW: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_CANCELED: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_HW_NOT_PRESENT: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_HW_UNAVAILABLE: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_LOCKOUT: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_LOCKOUT_PERMANENT: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_NO_FINGERPRINTS: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_NO_SPACE: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_TIMEOUT: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_UNABLE_TO_PROCESS: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_USER_CANCELED: typing.ClassVar[int] = ...
    FINGERPRINT_ERROR_VENDOR: typing.ClassVar[int] = ...
    def authenticate(self, cryptoObject: 'FingerprintManager.CryptoObject', cancellationSignal: android.os.CancellationSignal, int: int, authenticationCallback: 'FingerprintManager.AuthenticationCallback', handler: android.os.Handler) -> None: ...
    def hasEnrolledFingerprints(self) -> bool: ...
    def isHardwareDetected(self) -> bool: ...
    class AuthenticationCallback:
        def __init__(self): ...
        def onAuthenticationError(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
        def onAuthenticationFailed(self) -> None: ...
        def onAuthenticationHelp(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
        def onAuthenticationSucceeded(self, authenticationResult: 'FingerprintManager.AuthenticationResult') -> None: ...
    class AuthenticationResult:
        def getCryptoObject(self) -> 'FingerprintManager.CryptoObject': ...
    class CryptoObject:
        @typing.overload
        def __init__(self, signature: java.security.Signature): ...
        @typing.overload
        def __init__(self, cipher: javax.crypto.Cipher): ...
        @typing.overload
        def __init__(self, mac: javax.crypto.Mac): ...
        def getCipher(self) -> javax.crypto.Cipher: ...
        def getMac(self) -> javax.crypto.Mac: ...
        def getSignature(self) -> java.security.Signature: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.hardware.fingerprint")``.

    FingerprintManager: typing.Type[FingerprintManager]
