
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.database.sqlite
import android.net
import android.os
import java.io
import java.lang
import java.util
import jpype
import typing



class CharArrayBuffer:
    data: typing.MutableSequence[str] = ...
    sizeCopied: int = ...
    @typing.overload
    def __init__(self, charArray: typing.Union[typing.List[str], jpype.JArray]): ...
    @typing.overload
    def __init__(self, int: int): ...

class ContentObserver:
    def __init__(self, handler: android.os.Handler): ...
    def deliverSelfNotifications(self) -> bool: ...
    @typing.overload
    def dispatchChange(self, boolean: bool) -> None: ...
    @typing.overload
    def dispatchChange(self, boolean: bool, uri: android.net.Uri) -> None: ...
    @typing.overload
    def dispatchChange(self, boolean: bool, uri: android.net.Uri, int: int) -> None: ...
    @typing.overload
    def dispatchChange(self, boolean: bool, collection: typing.Union[java.util.Collection[android.net.Uri], typing.Sequence[android.net.Uri], typing.Set[android.net.Uri]], int: int) -> None: ...
    @typing.overload
    def onChange(self, boolean: bool) -> None: ...
    @typing.overload
    def onChange(self, boolean: bool, uri: android.net.Uri) -> None: ...
    @typing.overload
    def onChange(self, boolean: bool, uri: android.net.Uri, int: int) -> None: ...
    @typing.overload
    def onChange(self, boolean: bool, collection: typing.Union[java.util.Collection[android.net.Uri], typing.Sequence[android.net.Uri], typing.Set[android.net.Uri]], int: int) -> None: ...

class Cursor(java.io.Closeable):
    FIELD_TYPE_BLOB: typing.ClassVar[int] = ...
    FIELD_TYPE_FLOAT: typing.ClassVar[int] = ...
    FIELD_TYPE_INTEGER: typing.ClassVar[int] = ...
    FIELD_TYPE_NULL: typing.ClassVar[int] = ...
    FIELD_TYPE_STRING: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def copyStringToBuffer(self, int: int, charArrayBuffer: CharArrayBuffer) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getColumnCount(self) -> int: ...
    def getColumnIndex(self, string: str) -> int: ...
    def getColumnIndexOrThrow(self, string: str) -> int: ...
    def getColumnName(self, int: int) -> str: ...
    def getColumnNames(self) -> typing.MutableSequence[str]: ...
    def getCount(self) -> int: ...
    def getDouble(self, int: int) -> float: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFloat(self, int: int) -> float: ...
    def getInt(self, int: int) -> int: ...
    def getLong(self, int: int) -> int: ...
    def getNotificationUri(self) -> android.net.Uri: ...
    def getNotificationUris(self) -> java.util.List[android.net.Uri]: ...
    def getPosition(self) -> int: ...
    def getShort(self, int: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getType(self, int: int) -> int: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def isLast(self) -> bool: ...
    def isNull(self, int: int) -> bool: ...
    def move(self, int: int) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPosition(self, int: int) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def registerContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def registerDataSetObserver(self, dataSetObserver: 'DataSetObserver') -> None: ...
    def requery(self) -> bool: ...
    def respond(self, bundle: android.os.Bundle) -> android.os.Bundle: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setNotificationUri(self, contentResolver: android.content.ContentResolver, uri: android.net.Uri) -> None: ...
    def setNotificationUris(self, contentResolver: android.content.ContentResolver, list: java.util.List[android.net.Uri]) -> None: ...
    def unregisterContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def unregisterDataSetObserver(self, dataSetObserver: 'DataSetObserver') -> None: ...

class CursorIndexOutOfBoundsException(java.lang.IndexOutOfBoundsException):
    @typing.overload
    def __init__(self, int: int, int2: int): ...
    @typing.overload
    def __init__(self, string: str): ...

class CursorJoiner(java.util.Iterator['CursorJoiner.Result'], java.lang.Iterable['CursorJoiner.Result']):
    def __init__(self, cursor: Cursor, stringArray: typing.Union[typing.List[str], jpype.JArray], cursor2: Cursor, stringArray2: typing.Union[typing.List[str], jpype.JArray]): ...
    def hasNext(self) -> bool: ...
    def iterator(self) -> java.util.Iterator['CursorJoiner.Result']: ...
    def next(self) -> 'CursorJoiner.Result': ...
    def remove(self) -> None: ...
    class Result(java.lang.Enum['CursorJoiner.Result']):
        RIGHT: typing.ClassVar['CursorJoiner.Result'] = ...
        LEFT: typing.ClassVar['CursorJoiner.Result'] = ...
        BOTH: typing.ClassVar['CursorJoiner.Result'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'CursorJoiner.Result': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['CursorJoiner.Result']: ...

class CursorWindow(android.database.sqlite.SQLiteClosable, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, boolean: bool): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, long: int): ...
    def allocRow(self) -> bool: ...
    def clear(self) -> None: ...
    def copyStringToBuffer(self, int: int, int2: int, charArrayBuffer: CharArrayBuffer) -> None: ...
    def describeContents(self) -> int: ...
    def freeLastRow(self) -> None: ...
    def getBlob(self, int: int, int2: int) -> typing.MutableSequence[int]: ...
    def getDouble(self, int: int, int2: int) -> float: ...
    def getFloat(self, int: int, int2: int) -> float: ...
    def getInt(self, int: int, int2: int) -> int: ...
    def getLong(self, int: int, int2: int) -> int: ...
    def getNumRows(self) -> int: ...
    def getShort(self, int: int, int2: int) -> int: ...
    def getStartPosition(self) -> int: ...
    def getString(self, int: int, int2: int) -> str: ...
    def getType(self, int: int, int2: int) -> int: ...
    def isBlob(self, int: int, int2: int) -> bool: ...
    def isFloat(self, int: int, int2: int) -> bool: ...
    def isLong(self, int: int, int2: int) -> bool: ...
    def isNull(self, int: int, int2: int) -> bool: ...
    def isString(self, int: int, int2: int) -> bool: ...
    @staticmethod
    def newFromParcel(parcel: android.os.Parcel) -> 'CursorWindow': ...
    def putBlob(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> bool: ...
    def putDouble(self, double: float, int: int, int2: int) -> bool: ...
    def putLong(self, long: int, int: int, int2: int) -> bool: ...
    def putNull(self, int: int, int2: int) -> bool: ...
    def putString(self, string: str, int: int, int2: int) -> bool: ...
    def setNumColumns(self, int: int) -> bool: ...
    def setStartPosition(self, int: int) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CursorWindowAllocationException(java.lang.RuntimeException):
    def __init__(self, string: str): ...

class DataSetObserver:
    def __init__(self): ...
    def onChanged(self) -> None: ...
    def onInvalidated(self) -> None: ...

class DatabaseErrorHandler:
    def onCorruption(self, sQLiteDatabase: android.database.sqlite.SQLiteDatabase) -> None: ...

class DatabaseUtils:
    STATEMENT_ABORT: typing.ClassVar[int] = ...
    STATEMENT_ATTACH: typing.ClassVar[int] = ...
    STATEMENT_BEGIN: typing.ClassVar[int] = ...
    STATEMENT_COMMIT: typing.ClassVar[int] = ...
    STATEMENT_DDL: typing.ClassVar[int] = ...
    STATEMENT_OTHER: typing.ClassVar[int] = ...
    STATEMENT_PRAGMA: typing.ClassVar[int] = ...
    STATEMENT_SELECT: typing.ClassVar[int] = ...
    STATEMENT_UNPREPARED: typing.ClassVar[int] = ...
    STATEMENT_UPDATE: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def appendEscapedSQLString(stringBuilder: java.lang.StringBuilder, string2: str) -> None: ...
    @staticmethod
    def appendSelectionArgs(stringArray: typing.Union[typing.List[str], jpype.JArray], stringArray2: typing.Union[typing.List[str], jpype.JArray]) -> typing.MutableSequence[str]: ...
    @staticmethod
    def appendValueToSql(stringBuilder: java.lang.StringBuilder, object: typing.Any) -> None: ...
    @staticmethod
    def bindObjectToProgram(sQLiteProgram: android.database.sqlite.SQLiteProgram, int: int, object: typing.Any) -> None: ...
    @typing.overload
    @staticmethod
    def blobFileDescriptorForQuery(sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> android.os.ParcelFileDescriptor: ...
    @typing.overload
    @staticmethod
    def blobFileDescriptorForQuery(sQLiteStatement: android.database.sqlite.SQLiteStatement, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> android.os.ParcelFileDescriptor: ...
    @staticmethod
    def concatenateWhere(string: str, string2: str) -> str: ...
    @staticmethod
    def createDbFromSqlStatements(context: android.content.Context, string: str, int: int, string2: str) -> None: ...
    @staticmethod
    def cursorDoubleToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues, string2: str) -> None: ...
    @staticmethod
    def cursorDoubleToContentValuesIfPresent(cursor: Cursor, contentValues: android.content.ContentValues, string: str) -> None: ...
    @staticmethod
    def cursorDoubleToCursorValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues) -> None: ...
    @staticmethod
    def cursorFloatToContentValuesIfPresent(cursor: Cursor, contentValues: android.content.ContentValues, string: str) -> None: ...
    @typing.overload
    @staticmethod
    def cursorIntToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues) -> None: ...
    @typing.overload
    @staticmethod
    def cursorIntToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues, string2: str) -> None: ...
    @staticmethod
    def cursorIntToContentValuesIfPresent(cursor: Cursor, contentValues: android.content.ContentValues, string: str) -> None: ...
    @typing.overload
    @staticmethod
    def cursorLongToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues) -> None: ...
    @typing.overload
    @staticmethod
    def cursorLongToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues, string2: str) -> None: ...
    @staticmethod
    def cursorLongToContentValuesIfPresent(cursor: Cursor, contentValues: android.content.ContentValues, string: str) -> None: ...
    @staticmethod
    def cursorRowToContentValues(cursor: Cursor, contentValues: android.content.ContentValues) -> None: ...
    @staticmethod
    def cursorShortToContentValuesIfPresent(cursor: Cursor, contentValues: android.content.ContentValues, string: str) -> None: ...
    @typing.overload
    @staticmethod
    def cursorStringToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues) -> None: ...
    @typing.overload
    @staticmethod
    def cursorStringToContentValues(cursor: Cursor, string: str, contentValues: android.content.ContentValues, string2: str) -> None: ...
    @staticmethod
    def cursorStringToContentValuesIfPresent(cursor: Cursor, contentValues: android.content.ContentValues, string: str) -> None: ...
    @staticmethod
    def cursorStringToInsertHelper(cursor: Cursor, string: str, insertHelper: 'DatabaseUtils.InsertHelper', int: int) -> None: ...
    @typing.overload
    @staticmethod
    def dumpCurrentRow(cursor: Cursor) -> None: ...
    @typing.overload
    @staticmethod
    def dumpCurrentRow(cursor: Cursor, printStream: java.io.PrintStream) -> None: ...
    @typing.overload
    @staticmethod
    def dumpCurrentRow(cursor: Cursor, stringBuilder: java.lang.StringBuilder) -> None: ...
    @staticmethod
    def dumpCurrentRowToString(cursor: Cursor) -> str: ...
    @typing.overload
    @staticmethod
    def dumpCursor(cursor: Cursor) -> None: ...
    @typing.overload
    @staticmethod
    def dumpCursor(cursor: Cursor, printStream: java.io.PrintStream) -> None: ...
    @typing.overload
    @staticmethod
    def dumpCursor(cursor: Cursor, stringBuilder: java.lang.StringBuilder) -> None: ...
    @staticmethod
    def dumpCursorToString(cursor: Cursor) -> str: ...
    @staticmethod
    def getCollationKey(string: str) -> str: ...
    @staticmethod
    def getHexCollationKey(string: str) -> str: ...
    @staticmethod
    def getSqlStatementType(string: str) -> int: ...
    @typing.overload
    @staticmethod
    def longForQuery(sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    @typing.overload
    @staticmethod
    def longForQuery(sQLiteStatement: android.database.sqlite.SQLiteStatement, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    @typing.overload
    @staticmethod
    def queryNumEntries(sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str) -> int: ...
    @typing.overload
    @staticmethod
    def queryNumEntries(sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str, string2: str) -> int: ...
    @typing.overload
    @staticmethod
    def queryNumEntries(sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str, string2: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    @staticmethod
    def readExceptionFromParcel(parcel: android.os.Parcel) -> None: ...
    @staticmethod
    def readExceptionWithFileNotFoundExceptionFromParcel(parcel: android.os.Parcel) -> None: ...
    @staticmethod
    def readExceptionWithOperationApplicationExceptionFromParcel(parcel: android.os.Parcel) -> None: ...
    @staticmethod
    def sqlEscapeString(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def stringForQuery(sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> str: ...
    @typing.overload
    @staticmethod
    def stringForQuery(sQLiteStatement: android.database.sqlite.SQLiteStatement, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> str: ...
    @staticmethod
    def writeExceptionToParcel(parcel: android.os.Parcel, exception: java.lang.Exception) -> None: ...
    class InsertHelper:
        def __init__(self, sQLiteDatabase: android.database.sqlite.SQLiteDatabase, string: str): ...
        @typing.overload
        def bind(self, int: int, boolean: bool) -> None: ...
        @typing.overload
        def bind(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
        @typing.overload
        def bind(self, int: int, double: float) -> None: ...
        @typing.overload
        def bind(self, int: int, float: float) -> None: ...
        @typing.overload
        def bind(self, int: int, int2: int) -> None: ...
        @typing.overload
        def bind(self, int: int, string: str) -> None: ...
        @typing.overload
        def bind(self, int: int, long: int) -> None: ...
        def bindNull(self, int: int) -> None: ...
        def close(self) -> None: ...
        def execute(self) -> int: ...
        def getColumnIndex(self, string: str) -> int: ...
        def insert(self, contentValues: android.content.ContentValues) -> int: ...
        def prepareForInsert(self) -> None: ...
        def prepareForReplace(self) -> None: ...
        def replace(self, contentValues: android.content.ContentValues) -> int: ...

_Observable__T = typing.TypeVar('_Observable__T')  # <T>
class Observable(typing.Generic[_Observable__T]):
    def __init__(self): ...
    def registerObserver(self, t: _Observable__T) -> None: ...
    def unregisterAll(self) -> None: ...
    def unregisterObserver(self, t: _Observable__T) -> None: ...

class SQLException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class StaleDataException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class ContentObservable(Observable[ContentObserver]):
    def __init__(self): ...
    @typing.overload
    def dispatchChange(self, boolean: bool) -> None: ...
    @typing.overload
    def dispatchChange(self, boolean: bool, uri: android.net.Uri) -> None: ...
    def notifyChange(self, boolean: bool) -> None: ...
    def registerObserver(self, contentObserver: ContentObserver) -> None: ...

class CrossProcessCursor(Cursor):
    def fillWindow(self, int: int, cursorWindow: CursorWindow) -> None: ...
    def getWindow(self) -> CursorWindow: ...
    def onMove(self, int: int, int2: int) -> bool: ...

class CursorWrapper(Cursor):
    def __init__(self, cursor: Cursor): ...
    def close(self) -> None: ...
    def copyStringToBuffer(self, int: int, charArrayBuffer: CharArrayBuffer) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getColumnCount(self) -> int: ...
    def getColumnIndex(self, string: str) -> int: ...
    def getColumnIndexOrThrow(self, string: str) -> int: ...
    def getColumnName(self, int: int) -> str: ...
    def getColumnNames(self) -> typing.MutableSequence[str]: ...
    def getCount(self) -> int: ...
    def getDouble(self, int: int) -> float: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFloat(self, int: int) -> float: ...
    def getInt(self, int: int) -> int: ...
    def getLong(self, int: int) -> int: ...
    def getNotificationUri(self) -> android.net.Uri: ...
    def getNotificationUris(self) -> java.util.List[android.net.Uri]: ...
    def getPosition(self) -> int: ...
    def getShort(self, int: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getType(self, int: int) -> int: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def getWrappedCursor(self) -> Cursor: ...
    def isAfterLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def isLast(self) -> bool: ...
    def isNull(self, int: int) -> bool: ...
    def move(self, int: int) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPosition(self, int: int) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def registerContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def registerDataSetObserver(self, dataSetObserver: DataSetObserver) -> None: ...
    def requery(self) -> bool: ...
    def respond(self, bundle: android.os.Bundle) -> android.os.Bundle: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setNotificationUri(self, contentResolver: android.content.ContentResolver, uri: android.net.Uri) -> None: ...
    def setNotificationUris(self, contentResolver: android.content.ContentResolver, list: java.util.List[android.net.Uri]) -> None: ...
    def unregisterContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def unregisterDataSetObserver(self, dataSetObserver: DataSetObserver) -> None: ...

class DataSetObservable(Observable[DataSetObserver]):
    def __init__(self): ...
    def notifyChanged(self) -> None: ...
    def notifyInvalidated(self) -> None: ...

class DefaultDatabaseErrorHandler(DatabaseErrorHandler):
    def __init__(self): ...
    def onCorruption(self, sQLiteDatabase: android.database.sqlite.SQLiteDatabase) -> None: ...

class AbstractCursor(CrossProcessCursor):
    def __init__(self): ...
    def close(self) -> None: ...
    def copyStringToBuffer(self, int: int, charArrayBuffer: CharArrayBuffer) -> None: ...
    def deactivate(self) -> None: ...
    def fillWindow(self, int: int, cursorWindow: CursorWindow) -> None: ...
    def getBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getColumnCount(self) -> int: ...
    def getColumnIndex(self, string: str) -> int: ...
    def getColumnIndexOrThrow(self, string: str) -> int: ...
    def getColumnName(self, int: int) -> str: ...
    def getColumnNames(self) -> typing.MutableSequence[str]: ...
    def getCount(self) -> int: ...
    def getDouble(self, int: int) -> float: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFloat(self, int: int) -> float: ...
    def getInt(self, int: int) -> int: ...
    def getLong(self, int: int) -> int: ...
    def getNotificationUri(self) -> android.net.Uri: ...
    def getNotificationUris(self) -> java.util.List[android.net.Uri]: ...
    def getPosition(self) -> int: ...
    def getShort(self, int: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getType(self, int: int) -> int: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def getWindow(self) -> CursorWindow: ...
    def isAfterLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def isLast(self) -> bool: ...
    def isNull(self, int: int) -> bool: ...
    def move(self, int: int) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPosition(self, int: int) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def onMove(self, int: int, int2: int) -> bool: ...
    def registerContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def registerDataSetObserver(self, dataSetObserver: DataSetObserver) -> None: ...
    def requery(self) -> bool: ...
    def respond(self, bundle: android.os.Bundle) -> android.os.Bundle: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setNotificationUri(self, contentResolver: android.content.ContentResolver, uri: android.net.Uri) -> None: ...
    def setNotificationUris(self, contentResolver: android.content.ContentResolver, list: java.util.List[android.net.Uri]) -> None: ...
    def unregisterContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def unregisterDataSetObserver(self, dataSetObserver: DataSetObserver) -> None: ...

class CrossProcessCursorWrapper(CursorWrapper, CrossProcessCursor):
    def __init__(self, cursor: Cursor): ...
    def fillWindow(self, int: int, cursorWindow: CursorWindow) -> None: ...
    def getWindow(self) -> CursorWindow: ...
    def onMove(self, int: int, int2: int) -> bool: ...

class AbstractWindowedCursor(AbstractCursor):
    def __init__(self): ...
    def copyStringToBuffer(self, int: int, charArrayBuffer: CharArrayBuffer) -> None: ...
    def getBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getDouble(self, int: int) -> float: ...
    def getFloat(self, int: int) -> float: ...
    def getInt(self, int: int) -> int: ...
    def getLong(self, int: int) -> int: ...
    def getShort(self, int: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getType(self, int: int) -> int: ...
    def getWindow(self) -> CursorWindow: ...
    def hasWindow(self) -> bool: ...
    def isBlob(self, int: int) -> bool: ...
    def isFloat(self, int: int) -> bool: ...
    def isLong(self, int: int) -> bool: ...
    def isNull(self, int: int) -> bool: ...
    def isString(self, int: int) -> bool: ...
    def setWindow(self, cursorWindow: CursorWindow) -> None: ...

class MatrixCursor(AbstractCursor):
    @typing.overload
    def __init__(self, stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    @typing.overload
    def __init__(self, stringArray: typing.Union[typing.List[str], jpype.JArray], int: int): ...
    @typing.overload
    def addRow(self, iterable: typing.Union[java.lang.Iterable[typing.Any], typing.Sequence[typing.Any], typing.Set[typing.Any], typing.Callable[[], java.util.Iterator[typing.Any]]]) -> None: ...
    @typing.overload
    def addRow(self, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> None: ...
    def getBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getColumnNames(self) -> typing.MutableSequence[str]: ...
    def getCount(self) -> int: ...
    def getDouble(self, int: int) -> float: ...
    def getFloat(self, int: int) -> float: ...
    def getInt(self, int: int) -> int: ...
    def getLong(self, int: int) -> int: ...
    def getShort(self, int: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getType(self, int: int) -> int: ...
    def isNull(self, int: int) -> bool: ...
    def newRow(self) -> 'MatrixCursor.RowBuilder': ...
    class RowBuilder:
        @typing.overload
        def add(self, object: typing.Any) -> 'MatrixCursor.RowBuilder': ...
        @typing.overload
        def add(self, string: str, object: typing.Any) -> 'MatrixCursor.RowBuilder': ...

class MergeCursor(AbstractCursor):
    def __init__(self, cursorArray: typing.Union[typing.List[Cursor], jpype.JArray]): ...
    def close(self) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getColumnNames(self) -> typing.MutableSequence[str]: ...
    def getCount(self) -> int: ...
    def getDouble(self, int: int) -> float: ...
    def getFloat(self, int: int) -> float: ...
    def getInt(self, int: int) -> int: ...
    def getLong(self, int: int) -> int: ...
    def getShort(self, int: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getType(self, int: int) -> int: ...
    def isNull(self, int: int) -> bool: ...
    def onMove(self, int: int, int2: int) -> bool: ...
    def registerContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def registerDataSetObserver(self, dataSetObserver: DataSetObserver) -> None: ...
    def requery(self) -> bool: ...
    def unregisterContentObserver(self, contentObserver: ContentObserver) -> None: ...
    def unregisterDataSetObserver(self, dataSetObserver: DataSetObserver) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.database")``.

    AbstractCursor: typing.Type[AbstractCursor]
    AbstractWindowedCursor: typing.Type[AbstractWindowedCursor]
    CharArrayBuffer: typing.Type[CharArrayBuffer]
    ContentObservable: typing.Type[ContentObservable]
    ContentObserver: typing.Type[ContentObserver]
    CrossProcessCursor: typing.Type[CrossProcessCursor]
    CrossProcessCursorWrapper: typing.Type[CrossProcessCursorWrapper]
    Cursor: typing.Type[Cursor]
    CursorIndexOutOfBoundsException: typing.Type[CursorIndexOutOfBoundsException]
    CursorJoiner: typing.Type[CursorJoiner]
    CursorWindow: typing.Type[CursorWindow]
    CursorWindowAllocationException: typing.Type[CursorWindowAllocationException]
    CursorWrapper: typing.Type[CursorWrapper]
    DataSetObservable: typing.Type[DataSetObservable]
    DataSetObserver: typing.Type[DataSetObserver]
    DatabaseErrorHandler: typing.Type[DatabaseErrorHandler]
    DatabaseUtils: typing.Type[DatabaseUtils]
    DefaultDatabaseErrorHandler: typing.Type[DefaultDatabaseErrorHandler]
    MatrixCursor: typing.Type[MatrixCursor]
    MergeCursor: typing.Type[MergeCursor]
    Observable: typing.Type[Observable]
    SQLException: typing.Type[SQLException]
    StaleDataException: typing.Type[StaleDataException]
    sqlite: android.database.sqlite.__module_protocol__
