
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.os
import android.view.textservice
import jpype
import typing



class SpellCheckerService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def createSession(self) -> 'SpellCheckerService.Session': ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    class Session:
        def __init__(self): ...
        def getBundle(self) -> android.os.Bundle: ...
        def getLocale(self) -> str: ...
        def getSupportedAttributes(self) -> int: ...
        def onCancel(self) -> None: ...
        def onClose(self) -> None: ...
        def onCreate(self) -> None: ...
        def onGetSentenceSuggestionsMultiple(self, textInfoArray: typing.Union[typing.List[android.view.textservice.TextInfo], jpype.JArray], int: int) -> typing.MutableSequence[android.view.textservice.SentenceSuggestionsInfo]: ...
        def onGetSuggestions(self, textInfo: android.view.textservice.TextInfo, int: int) -> android.view.textservice.SuggestionsInfo: ...
        def onGetSuggestionsMultiple(self, textInfoArray: typing.Union[typing.List[android.view.textservice.TextInfo], jpype.JArray], int: int, boolean: bool) -> typing.MutableSequence[android.view.textservice.SuggestionsInfo]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.textservice")``.

    SpellCheckerService: typing.Type[SpellCheckerService]
