
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import java.lang
import java.util
import jpype
import typing



class AudioEffect:
    ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION: typing.ClassVar[str] = ...
    ACTION_DISPLAY_AUDIO_EFFECT_CONTROL_PANEL: typing.ClassVar[str] = ...
    ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION: typing.ClassVar[str] = ...
    ALREADY_EXISTS: typing.ClassVar[int] = ...
    CONTENT_TYPE_GAME: typing.ClassVar[int] = ...
    CONTENT_TYPE_MOVIE: typing.ClassVar[int] = ...
    CONTENT_TYPE_MUSIC: typing.ClassVar[int] = ...
    CONTENT_TYPE_VOICE: typing.ClassVar[int] = ...
    EFFECT_AUXILIARY: typing.ClassVar[str] = ...
    EFFECT_INSERT: typing.ClassVar[str] = ...
    EFFECT_POST_PROCESSING: typing.ClassVar[str] = ...
    EFFECT_PRE_PROCESSING: typing.ClassVar[str] = ...
    EFFECT_TYPE_AEC: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_AGC: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_BASS_BOOST: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_DYNAMICS_PROCESSING: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_ENV_REVERB: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_EQUALIZER: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_HAPTIC_GENERATOR: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_LOUDNESS_ENHANCER: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_NS: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_PRESET_REVERB: typing.ClassVar[java.util.UUID] = ...
    EFFECT_TYPE_VIRTUALIZER: typing.ClassVar[java.util.UUID] = ...
    ERROR: typing.ClassVar[int] = ...
    ERROR_BAD_VALUE: typing.ClassVar[int] = ...
    ERROR_DEAD_OBJECT: typing.ClassVar[int] = ...
    ERROR_INVALID_OPERATION: typing.ClassVar[int] = ...
    ERROR_NO_INIT: typing.ClassVar[int] = ...
    ERROR_NO_MEMORY: typing.ClassVar[int] = ...
    EXTRA_AUDIO_SESSION: typing.ClassVar[str] = ...
    EXTRA_CONTENT_TYPE: typing.ClassVar[str] = ...
    EXTRA_PACKAGE_NAME: typing.ClassVar[str] = ...
    SUCCESS: typing.ClassVar[int] = ...
    def getDescriptor(self) -> 'AudioEffect.Descriptor': ...
    def getEnabled(self) -> bool: ...
    def getId(self) -> int: ...
    def hasControl(self) -> bool: ...
    @staticmethod
    def queryEffects() -> typing.MutableSequence['AudioEffect.Descriptor']: ...
    def release(self) -> None: ...
    def setControlStatusListener(self, onControlStatusChangeListener: typing.Union['AudioEffect.OnControlStatusChangeListener', typing.Callable]) -> None: ...
    def setEnableStatusListener(self, onEnableStatusChangeListener: typing.Union['AudioEffect.OnEnableStatusChangeListener', typing.Callable]) -> None: ...
    def setEnabled(self, boolean: bool) -> int: ...
    class Descriptor:
        connectMode: str = ...
        implementor: str = ...
        name: str = ...
        type: java.util.UUID = ...
        uuid: java.util.UUID = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str, string2: str, string3: str, string4: str, string5: str): ...
        def equals(self, object: typing.Any) -> bool: ...
        def hashCode(self) -> int: ...
    class OnControlStatusChangeListener:
        def onControlStatusChange(self, audioEffect: 'AudioEffect', boolean: bool) -> None: ...
    class OnEnableStatusChangeListener:
        def onEnableStatusChange(self, audioEffect: 'AudioEffect', boolean: bool) -> None: ...

class Visualizer:
    ALREADY_EXISTS: typing.ClassVar[int] = ...
    ERROR: typing.ClassVar[int] = ...
    ERROR_BAD_VALUE: typing.ClassVar[int] = ...
    ERROR_DEAD_OBJECT: typing.ClassVar[int] = ...
    ERROR_INVALID_OPERATION: typing.ClassVar[int] = ...
    ERROR_NO_INIT: typing.ClassVar[int] = ...
    ERROR_NO_MEMORY: typing.ClassVar[int] = ...
    MEASUREMENT_MODE_NONE: typing.ClassVar[int] = ...
    MEASUREMENT_MODE_PEAK_RMS: typing.ClassVar[int] = ...
    SCALING_MODE_AS_PLAYED: typing.ClassVar[int] = ...
    SCALING_MODE_NORMALIZED: typing.ClassVar[int] = ...
    STATE_ENABLED: typing.ClassVar[int] = ...
    STATE_INITIALIZED: typing.ClassVar[int] = ...
    STATE_UNINITIALIZED: typing.ClassVar[int] = ...
    SUCCESS: typing.ClassVar[int] = ...
    def __init__(self, int: int): ...
    def getCaptureSize(self) -> int: ...
    @staticmethod
    def getCaptureSizeRange() -> typing.MutableSequence[int]: ...
    def getEnabled(self) -> bool: ...
    def getFft(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> int: ...
    @staticmethod
    def getMaxCaptureRate() -> int: ...
    def getMeasurementMode(self) -> int: ...
    def getMeasurementPeakRms(self, measurementPeakRms: 'Visualizer.MeasurementPeakRms') -> int: ...
    def getSamplingRate(self) -> int: ...
    def getScalingMode(self) -> int: ...
    def getWaveForm(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> int: ...
    def release(self) -> None: ...
    def setCaptureSize(self, int: int) -> int: ...
    def setDataCaptureListener(self, onDataCaptureListener: 'Visualizer.OnDataCaptureListener', int: int, boolean: bool, boolean2: bool) -> int: ...
    def setEnabled(self, boolean: bool) -> int: ...
    def setMeasurementMode(self, int: int) -> int: ...
    def setScalingMode(self, int: int) -> int: ...
    class MeasurementPeakRms:
        mPeak: int = ...
        mRms: int = ...
        def __init__(self): ...
    class OnDataCaptureListener:
        def onFftDataCapture(self, visualizer: 'Visualizer', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int) -> None: ...
        def onWaveFormDataCapture(self, visualizer: 'Visualizer', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int) -> None: ...

class AcousticEchoCanceler(AudioEffect):
    @staticmethod
    def create(int: int) -> 'AcousticEchoCanceler': ...
    @staticmethod
    def isAvailable() -> bool: ...

class AutomaticGainControl(AudioEffect):
    @staticmethod
    def create(int: int) -> 'AutomaticGainControl': ...
    @staticmethod
    def isAvailable() -> bool: ...

class BassBoost(AudioEffect):
    PARAM_STRENGTH: typing.ClassVar[int] = ...
    PARAM_STRENGTH_SUPPORTED: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int): ...
    def getProperties(self) -> 'BassBoost.Settings': ...
    def getRoundedStrength(self) -> int: ...
    def getStrengthSupported(self) -> bool: ...
    def setParameterListener(self, onParameterChangeListener: typing.Union['BassBoost.OnParameterChangeListener', typing.Callable]) -> None: ...
    def setProperties(self, settings: 'BassBoost.Settings') -> None: ...
    def setStrength(self, short: int) -> None: ...
    class OnParameterChangeListener:
        def onParameterChange(self, bassBoost: 'BassBoost', int: int, int2: int, short: int) -> None: ...
    class Settings:
        strength: int = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def toString(self) -> str: ...

class EnvironmentalReverb(AudioEffect):
    PARAM_DECAY_HF_RATIO: typing.ClassVar[int] = ...
    PARAM_DECAY_TIME: typing.ClassVar[int] = ...
    PARAM_DENSITY: typing.ClassVar[int] = ...
    PARAM_DIFFUSION: typing.ClassVar[int] = ...
    PARAM_REFLECTIONS_DELAY: typing.ClassVar[int] = ...
    PARAM_REFLECTIONS_LEVEL: typing.ClassVar[int] = ...
    PARAM_REVERB_DELAY: typing.ClassVar[int] = ...
    PARAM_REVERB_LEVEL: typing.ClassVar[int] = ...
    PARAM_ROOM_HF_LEVEL: typing.ClassVar[int] = ...
    PARAM_ROOM_LEVEL: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int): ...
    def getDecayHFRatio(self) -> int: ...
    def getDecayTime(self) -> int: ...
    def getDensity(self) -> int: ...
    def getDiffusion(self) -> int: ...
    def getProperties(self) -> 'EnvironmentalReverb.Settings': ...
    def getReflectionsDelay(self) -> int: ...
    def getReflectionsLevel(self) -> int: ...
    def getReverbDelay(self) -> int: ...
    def getReverbLevel(self) -> int: ...
    def getRoomHFLevel(self) -> int: ...
    def getRoomLevel(self) -> int: ...
    def setDecayHFRatio(self, short: int) -> None: ...
    def setDecayTime(self, int: int) -> None: ...
    def setDensity(self, short: int) -> None: ...
    def setDiffusion(self, short: int) -> None: ...
    def setParameterListener(self, onParameterChangeListener: typing.Union['EnvironmentalReverb.OnParameterChangeListener', typing.Callable]) -> None: ...
    def setProperties(self, settings: 'EnvironmentalReverb.Settings') -> None: ...
    def setReflectionsDelay(self, int: int) -> None: ...
    def setReflectionsLevel(self, short: int) -> None: ...
    def setReverbDelay(self, int: int) -> None: ...
    def setReverbLevel(self, short: int) -> None: ...
    def setRoomHFLevel(self, short: int) -> None: ...
    def setRoomLevel(self, short: int) -> None: ...
    class OnParameterChangeListener:
        def onParameterChange(self, environmentalReverb: 'EnvironmentalReverb', int: int, int2: int, int3: int) -> None: ...
    class Settings:
        decayHFRatio: int = ...
        decayTime: int = ...
        density: int = ...
        diffusion: int = ...
        reflectionsDelay: int = ...
        reflectionsLevel: int = ...
        reverbDelay: int = ...
        reverbLevel: int = ...
        roomHFLevel: int = ...
        roomLevel: int = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def toString(self) -> str: ...

class Equalizer(AudioEffect):
    PARAM_BAND_FREQ_RANGE: typing.ClassVar[int] = ...
    PARAM_BAND_LEVEL: typing.ClassVar[int] = ...
    PARAM_CENTER_FREQ: typing.ClassVar[int] = ...
    PARAM_CURRENT_PRESET: typing.ClassVar[int] = ...
    PARAM_GET_BAND: typing.ClassVar[int] = ...
    PARAM_GET_NUM_OF_PRESETS: typing.ClassVar[int] = ...
    PARAM_GET_PRESET_NAME: typing.ClassVar[int] = ...
    PARAM_LEVEL_RANGE: typing.ClassVar[int] = ...
    PARAM_NUM_BANDS: typing.ClassVar[int] = ...
    PARAM_STRING_SIZE_MAX: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int): ...
    def getBand(self, int: int) -> int: ...
    def getBandFreqRange(self, short: int) -> typing.MutableSequence[int]: ...
    def getBandLevel(self, short: int) -> int: ...
    def getBandLevelRange(self) -> typing.MutableSequence[int]: ...
    def getCenterFreq(self, short: int) -> int: ...
    def getCurrentPreset(self) -> int: ...
    def getNumberOfBands(self) -> int: ...
    def getNumberOfPresets(self) -> int: ...
    def getPresetName(self, short: int) -> str: ...
    def getProperties(self) -> 'Equalizer.Settings': ...
    def setBandLevel(self, short: int, short2: int) -> None: ...
    def setParameterListener(self, onParameterChangeListener: typing.Union['Equalizer.OnParameterChangeListener', typing.Callable]) -> None: ...
    def setProperties(self, settings: 'Equalizer.Settings') -> None: ...
    def usePreset(self, short: int) -> None: ...
    class OnParameterChangeListener:
        def onParameterChange(self, equalizer: 'Equalizer', int: int, int2: int, int3: int, int4: int) -> None: ...
    class Settings:
        bandLevels: typing.MutableSequence[int] = ...
        curPreset: int = ...
        numBands: int = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def toString(self) -> str: ...

class HapticGenerator(AudioEffect, java.lang.AutoCloseable):
    def close(self) -> None: ...
    @staticmethod
    def create(int: int) -> 'HapticGenerator': ...
    @staticmethod
    def isAvailable() -> bool: ...
    def release(self) -> None: ...
    def setEnabled(self, boolean: bool) -> int: ...

class LoudnessEnhancer(AudioEffect):
    PARAM_TARGET_GAIN_MB: typing.ClassVar[int] = ...
    def __init__(self, int: int): ...
    def getTargetGain(self) -> float: ...
    def setTargetGain(self, int: int) -> None: ...

class NoiseSuppressor(AudioEffect):
    @staticmethod
    def create(int: int) -> 'NoiseSuppressor': ...
    @staticmethod
    def isAvailable() -> bool: ...

class PresetReverb(AudioEffect):
    PARAM_PRESET: typing.ClassVar[int] = ...
    PRESET_LARGEHALL: typing.ClassVar[int] = ...
    PRESET_LARGEROOM: typing.ClassVar[int] = ...
    PRESET_MEDIUMHALL: typing.ClassVar[int] = ...
    PRESET_MEDIUMROOM: typing.ClassVar[int] = ...
    PRESET_NONE: typing.ClassVar[int] = ...
    PRESET_PLATE: typing.ClassVar[int] = ...
    PRESET_SMALLROOM: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int): ...
    def getPreset(self) -> int: ...
    def getProperties(self) -> 'PresetReverb.Settings': ...
    def setParameterListener(self, onParameterChangeListener: typing.Union['PresetReverb.OnParameterChangeListener', typing.Callable]) -> None: ...
    def setPreset(self, short: int) -> None: ...
    def setProperties(self, settings: 'PresetReverb.Settings') -> None: ...
    class OnParameterChangeListener:
        def onParameterChange(self, presetReverb: 'PresetReverb', int: int, int2: int, short: int) -> None: ...
    class Settings:
        preset: int = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def toString(self) -> str: ...

class Virtualizer(AudioEffect):
    PARAM_STRENGTH: typing.ClassVar[int] = ...
    PARAM_STRENGTH_SUPPORTED: typing.ClassVar[int] = ...
    VIRTUALIZATION_MODE_AUTO: typing.ClassVar[int] = ...
    VIRTUALIZATION_MODE_BINAURAL: typing.ClassVar[int] = ...
    VIRTUALIZATION_MODE_OFF: typing.ClassVar[int] = ...
    VIRTUALIZATION_MODE_TRANSAURAL: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int): ...
    def canVirtualize(self, int: int, int2: int) -> bool: ...
    def forceVirtualizationMode(self, int: int) -> bool: ...
    def getProperties(self) -> 'Virtualizer.Settings': ...
    def getRoundedStrength(self) -> int: ...
    def getSpeakerAngles(self, int: int, int2: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> bool: ...
    def getStrengthSupported(self) -> bool: ...
    def getVirtualizationMode(self) -> int: ...
    def setParameterListener(self, onParameterChangeListener: typing.Union['Virtualizer.OnParameterChangeListener', typing.Callable]) -> None: ...
    def setProperties(self, settings: 'Virtualizer.Settings') -> None: ...
    def setStrength(self, short: int) -> None: ...
    class OnParameterChangeListener:
        def onParameterChange(self, virtualizer: 'Virtualizer', int: int, int2: int, short: int) -> None: ...
    class Settings:
        strength: int = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def toString(self) -> str: ...

class DynamicsProcessing(AudioEffect):
    VARIANT_FAVOR_FREQUENCY_RESOLUTION: typing.ClassVar[int] = ...
    VARIANT_FAVOR_TIME_RESOLUTION: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, config: 'DynamicsProcessing.Config'): ...
    def getChannelByChannelIndex(self, int: int) -> 'DynamicsProcessing.Channel': ...
    def getChannelCount(self) -> int: ...
    def getConfig(self) -> 'DynamicsProcessing.Config': ...
    def getInputGainByChannelIndex(self, int: int) -> float: ...
    def getLimiterByChannelIndex(self, int: int) -> 'DynamicsProcessing.Limiter': ...
    def getMbcBandByChannelIndex(self, int: int, int2: int) -> 'DynamicsProcessing.MbcBand': ...
    def getMbcByChannelIndex(self, int: int) -> 'DynamicsProcessing.Mbc': ...
    def getPostEqBandByChannelIndex(self, int: int, int2: int) -> 'DynamicsProcessing.EqBand': ...
    def getPostEqByChannelIndex(self, int: int) -> 'DynamicsProcessing.Eq': ...
    def getPreEqBandByChannelIndex(self, int: int, int2: int) -> 'DynamicsProcessing.EqBand': ...
    def getPreEqByChannelIndex(self, int: int) -> 'DynamicsProcessing.Eq': ...
    def setAllChannelsTo(self, channel: 'DynamicsProcessing.Channel') -> None: ...
    def setChannelTo(self, int: int, channel: 'DynamicsProcessing.Channel') -> None: ...
    def setInputGainAllChannelsTo(self, float: float) -> None: ...
    def setInputGainbyChannel(self, int: int, float: float) -> None: ...
    def setLimiterAllChannelsTo(self, limiter: 'DynamicsProcessing.Limiter') -> None: ...
    def setLimiterByChannelIndex(self, int: int, limiter: 'DynamicsProcessing.Limiter') -> None: ...
    def setMbcAllChannelsTo(self, mbc: 'DynamicsProcessing.Mbc') -> None: ...
    def setMbcBandAllChannelsTo(self, int: int, mbcBand: 'DynamicsProcessing.MbcBand') -> None: ...
    def setMbcBandByChannelIndex(self, int: int, int2: int, mbcBand: 'DynamicsProcessing.MbcBand') -> None: ...
    def setMbcByChannelIndex(self, int: int, mbc: 'DynamicsProcessing.Mbc') -> None: ...
    def setPostEqAllChannelsTo(self, eq: 'DynamicsProcessing.Eq') -> None: ...
    def setPostEqBandAllChannelsTo(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
    def setPostEqBandByChannelIndex(self, int: int, int2: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
    def setPostEqByChannelIndex(self, int: int, eq: 'DynamicsProcessing.Eq') -> None: ...
    def setPreEqAllChannelsTo(self, eq: 'DynamicsProcessing.Eq') -> None: ...
    def setPreEqBandAllChannelsTo(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
    def setPreEqBandByChannelIndex(self, int: int, int2: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
    def setPreEqByChannelIndex(self, int: int, eq: 'DynamicsProcessing.Eq') -> None: ...
    class BandBase:
        def __init__(self, boolean: bool, float: float): ...
        def getCutoffFrequency(self) -> float: ...
        def isEnabled(self) -> bool: ...
        def setCutoffFrequency(self, float: float) -> None: ...
        def setEnabled(self, boolean: bool) -> None: ...
        def toString(self) -> str: ...
    class BandStage(android.media.audiofx.DynamicsProcessing.Stage):
        def __init__(self, boolean: bool, boolean2: bool, int: int): ...
        def getBandCount(self) -> int: ...
        def toString(self) -> str: ...
    class Channel:
        @typing.overload
        def __init__(self, channel: 'DynamicsProcessing.Channel'): ...
        @typing.overload
        def __init__(self, float: float, boolean: bool, int: int, boolean2: bool, int2: int, boolean3: bool, int3: int, boolean4: bool): ...
        def getInputGain(self) -> float: ...
        def getLimiter(self) -> 'DynamicsProcessing.Limiter': ...
        def getMbc(self) -> 'DynamicsProcessing.Mbc': ...
        def getMbcBand(self, int: int) -> 'DynamicsProcessing.MbcBand': ...
        def getPostEq(self) -> 'DynamicsProcessing.Eq': ...
        def getPostEqBand(self, int: int) -> 'DynamicsProcessing.EqBand': ...
        def getPreEq(self) -> 'DynamicsProcessing.Eq': ...
        def getPreEqBand(self, int: int) -> 'DynamicsProcessing.EqBand': ...
        def setInputGain(self, float: float) -> None: ...
        def setLimiter(self, limiter: 'DynamicsProcessing.Limiter') -> None: ...
        def setMbc(self, mbc: 'DynamicsProcessing.Mbc') -> None: ...
        def setMbcBand(self, int: int, mbcBand: 'DynamicsProcessing.MbcBand') -> None: ...
        def setPostEq(self, eq: 'DynamicsProcessing.Eq') -> None: ...
        def setPostEqBand(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def setPreEq(self, eq: 'DynamicsProcessing.Eq') -> None: ...
        def setPreEqBand(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def toString(self) -> str: ...
    class Config:
        def getChannelByChannelIndex(self, int: int) -> 'DynamicsProcessing.Channel': ...
        def getInputGainByChannelIndex(self, int: int) -> float: ...
        def getLimiterByChannelIndex(self, int: int) -> 'DynamicsProcessing.Limiter': ...
        def getMbcBandByChannelIndex(self, int: int, int2: int) -> 'DynamicsProcessing.MbcBand': ...
        def getMbcBandCount(self) -> int: ...
        def getMbcByChannelIndex(self, int: int) -> 'DynamicsProcessing.Mbc': ...
        def getPostEqBandByChannelIndex(self, int: int, int2: int) -> 'DynamicsProcessing.EqBand': ...
        def getPostEqBandCount(self) -> int: ...
        def getPostEqByChannelIndex(self, int: int) -> 'DynamicsProcessing.Eq': ...
        def getPreEqBandByChannelIndex(self, int: int, int2: int) -> 'DynamicsProcessing.EqBand': ...
        def getPreEqBandCount(self) -> int: ...
        def getPreEqByChannelIndex(self, int: int) -> 'DynamicsProcessing.Eq': ...
        def getPreferredFrameDuration(self) -> float: ...
        def getVariant(self) -> int: ...
        def isLimiterInUse(self) -> bool: ...
        def isMbcInUse(self) -> bool: ...
        def isPostEqInUse(self) -> bool: ...
        def isPreEqInUse(self) -> bool: ...
        def setAllChannelsTo(self, channel: 'DynamicsProcessing.Channel') -> None: ...
        def setChannelTo(self, int: int, channel: 'DynamicsProcessing.Channel') -> None: ...
        def setInputGainAllChannelsTo(self, float: float) -> None: ...
        def setInputGainByChannelIndex(self, int: int, float: float) -> None: ...
        def setLimiterAllChannelsTo(self, limiter: 'DynamicsProcessing.Limiter') -> None: ...
        def setLimiterByChannelIndex(self, int: int, limiter: 'DynamicsProcessing.Limiter') -> None: ...
        def setMbcAllChannelsTo(self, mbc: 'DynamicsProcessing.Mbc') -> None: ...
        def setMbcBandAllChannelsTo(self, int: int, mbcBand: 'DynamicsProcessing.MbcBand') -> None: ...
        def setMbcBandByChannelIndex(self, int: int, int2: int, mbcBand: 'DynamicsProcessing.MbcBand') -> None: ...
        def setMbcByChannelIndex(self, int: int, mbc: 'DynamicsProcessing.Mbc') -> None: ...
        def setPostEqAllChannelsTo(self, eq: 'DynamicsProcessing.Eq') -> None: ...
        def setPostEqBandAllChannelsTo(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def setPostEqBandByChannelIndex(self, int: int, int2: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def setPostEqByChannelIndex(self, int: int, eq: 'DynamicsProcessing.Eq') -> None: ...
        def setPreEqAllChannelsTo(self, eq: 'DynamicsProcessing.Eq') -> None: ...
        def setPreEqBandAllChannelsTo(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def setPreEqBandByChannelIndex(self, int: int, int2: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def setPreEqByChannelIndex(self, int: int, eq: 'DynamicsProcessing.Eq') -> None: ...
        def toString(self) -> str: ...
        class Builder:
            def __init__(self, int: int, int2: int, boolean: bool, int3: int, boolean2: bool, int4: int, boolean3: bool, int5: int, boolean4: bool): ...
            def build(self) -> 'DynamicsProcessing.Config': ...
            def setAllChannelsTo(self, channel: 'DynamicsProcessing.Channel') -> 'DynamicsProcessing.Config.Builder': ...
            def setChannelTo(self, int: int, channel: 'DynamicsProcessing.Channel') -> 'DynamicsProcessing.Config.Builder': ...
            def setInputGainAllChannelsTo(self, float: float) -> 'DynamicsProcessing.Config.Builder': ...
            def setInputGainByChannelIndex(self, int: int, float: float) -> 'DynamicsProcessing.Config.Builder': ...
            def setLimiterAllChannelsTo(self, limiter: 'DynamicsProcessing.Limiter') -> 'DynamicsProcessing.Config.Builder': ...
            def setLimiterByChannelIndex(self, int: int, limiter: 'DynamicsProcessing.Limiter') -> 'DynamicsProcessing.Config.Builder': ...
            def setMbcAllChannelsTo(self, mbc: 'DynamicsProcessing.Mbc') -> 'DynamicsProcessing.Config.Builder': ...
            def setMbcByChannelIndex(self, int: int, mbc: 'DynamicsProcessing.Mbc') -> 'DynamicsProcessing.Config.Builder': ...
            def setPostEqAllChannelsTo(self, eq: 'DynamicsProcessing.Eq') -> 'DynamicsProcessing.Config.Builder': ...
            def setPostEqByChannelIndex(self, int: int, eq: 'DynamicsProcessing.Eq') -> 'DynamicsProcessing.Config.Builder': ...
            def setPreEqAllChannelsTo(self, eq: 'DynamicsProcessing.Eq') -> 'DynamicsProcessing.Config.Builder': ...
            def setPreEqByChannelIndex(self, int: int, eq: 'DynamicsProcessing.Eq') -> 'DynamicsProcessing.Config.Builder': ...
            def setPreferredFrameDuration(self, float: float) -> 'DynamicsProcessing.Config.Builder': ...
    class Eq(android.media.audiofx.DynamicsProcessing.BandStage):
        @typing.overload
        def __init__(self, eq: 'DynamicsProcessing.Eq'): ...
        @typing.overload
        def __init__(self, boolean: bool, boolean2: bool, int: int): ...
        def getBand(self, int: int) -> 'DynamicsProcessing.EqBand': ...
        def setBand(self, int: int, eqBand: 'DynamicsProcessing.EqBand') -> None: ...
        def toString(self) -> str: ...
    class EqBand(android.media.audiofx.DynamicsProcessing.BandBase):
        @typing.overload
        def __init__(self, eqBand: 'DynamicsProcessing.EqBand'): ...
        @typing.overload
        def __init__(self, boolean: bool, float: float, float2: float): ...
        def getGain(self) -> float: ...
        def setGain(self, float: float) -> None: ...
        def toString(self) -> str: ...
    class Limiter(android.media.audiofx.DynamicsProcessing.Stage):
        @typing.overload
        def __init__(self, limiter: 'DynamicsProcessing.Limiter'): ...
        @typing.overload
        def __init__(self, boolean: bool, boolean2: bool, int: int, float: float, float2: float, float3: float, float4: float, float5: float): ...
        def getAttackTime(self) -> float: ...
        def getLinkGroup(self) -> int: ...
        def getPostGain(self) -> float: ...
        def getRatio(self) -> float: ...
        def getReleaseTime(self) -> float: ...
        def getThreshold(self) -> float: ...
        def setAttackTime(self, float: float) -> None: ...
        def setLinkGroup(self, int: int) -> None: ...
        def setPostGain(self, float: float) -> None: ...
        def setRatio(self, float: float) -> None: ...
        def setReleaseTime(self, float: float) -> None: ...
        def setThreshold(self, float: float) -> None: ...
        def toString(self) -> str: ...
    class Mbc(android.media.audiofx.DynamicsProcessing.BandStage):
        @typing.overload
        def __init__(self, mbc: 'DynamicsProcessing.Mbc'): ...
        @typing.overload
        def __init__(self, boolean: bool, boolean2: bool, int: int): ...
        def getBand(self, int: int) -> 'DynamicsProcessing.MbcBand': ...
        def setBand(self, int: int, mbcBand: 'DynamicsProcessing.MbcBand') -> None: ...
        def toString(self) -> str: ...
    class MbcBand(android.media.audiofx.DynamicsProcessing.BandBase):
        @typing.overload
        def __init__(self, mbcBand: 'DynamicsProcessing.MbcBand'): ...
        @typing.overload
        def __init__(self, boolean: bool, float: float, float2: float, float3: float, float4: float, float5: float, float6: float, float7: float, float8: float, float9: float, float10: float): ...
        def getAttackTime(self) -> float: ...
        def getExpanderRatio(self) -> float: ...
        def getKneeWidth(self) -> float: ...
        def getNoiseGateThreshold(self) -> float: ...
        def getPostGain(self) -> float: ...
        def getPreGain(self) -> float: ...
        def getRatio(self) -> float: ...
        def getReleaseTime(self) -> float: ...
        def getThreshold(self) -> float: ...
        def setAttackTime(self, float: float) -> None: ...
        def setExpanderRatio(self, float: float) -> None: ...
        def setKneeWidth(self, float: float) -> None: ...
        def setNoiseGateThreshold(self, float: float) -> None: ...
        def setPostGain(self, float: float) -> None: ...
        def setPreGain(self, float: float) -> None: ...
        def setRatio(self, float: float) -> None: ...
        def setReleaseTime(self, float: float) -> None: ...
        def setThreshold(self, float: float) -> None: ...
        def toString(self) -> str: ...
    class Stage:
        def __init__(self, boolean: bool, boolean2: bool): ...
        def isEnabled(self) -> bool: ...
        def isInUse(self) -> bool: ...
        def setEnabled(self, boolean: bool) -> None: ...
        def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.audiofx")``.

    AcousticEchoCanceler: typing.Type[AcousticEchoCanceler]
    AudioEffect: typing.Type[AudioEffect]
    AutomaticGainControl: typing.Type[AutomaticGainControl]
    BassBoost: typing.Type[BassBoost]
    DynamicsProcessing: typing.Type[DynamicsProcessing]
    EnvironmentalReverb: typing.Type[EnvironmentalReverb]
    Equalizer: typing.Type[Equalizer]
    HapticGenerator: typing.Type[HapticGenerator]
    LoudnessEnhancer: typing.Type[LoudnessEnhancer]
    NoiseSuppressor: typing.Type[NoiseSuppressor]
    PresetReverb: typing.Type[PresetReverb]
    Virtualizer: typing.Type[Virtualizer]
    Visualizer: typing.Type[Visualizer]
