
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.hardware.display
import android.os
import android.view
import typing



class MediaProjection:
    def createVirtualDisplay(self, string: str, int: int, int2: int, int3: int, int4: int, surface: android.view.Surface, callback: android.hardware.display.VirtualDisplay.Callback, handler: android.os.Handler) -> android.hardware.display.VirtualDisplay: ...
    def registerCallback(self, callback: 'MediaProjection.Callback', handler: android.os.Handler) -> None: ...
    def stop(self) -> None: ...
    def unregisterCallback(self, callback: 'MediaProjection.Callback') -> None: ...
    class Callback:
        def __init__(self): ...
        def onCapturedContentResize(self, int: int, int2: int) -> None: ...
        def onCapturedContentVisibilityChanged(self, boolean: bool) -> None: ...
        def onStop(self) -> None: ...

class MediaProjectionConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @staticmethod
    def createConfigForDefaultDisplay() -> 'MediaProjectionConfig': ...
    @staticmethod
    def createConfigForUserChoice() -> 'MediaProjectionConfig': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class MediaProjectionManager:
    @typing.overload
    def createScreenCaptureIntent(self) -> android.content.Intent: ...
    @typing.overload
    def createScreenCaptureIntent(self, mediaProjectionConfig: MediaProjectionConfig) -> android.content.Intent: ...
    def getMediaProjection(self, int: int, intent: android.content.Intent) -> MediaProjection: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.projection")``.

    MediaProjection: typing.Type[MediaProjection]
    MediaProjectionConfig: typing.Type[MediaProjectionConfig]
    MediaProjectionManager: typing.Type[MediaProjectionManager]
