
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.graphics
import android.os
import android.view
import android.view.autofill
import java.lang
import java.util
import java.util.concurrent
import jpype
import typing



class ContentCaptureCondition(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FLAG_IS_REGEX: typing.ClassVar[int] = ...
    def __init__(self, locusId: android.content.LocusId, int: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFlags(self) -> int: ...
    def getLocusId(self) -> android.content.LocusId: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ContentCaptureContext(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    @staticmethod
    def forLocusId(string: str) -> 'ContentCaptureContext': ...
    def getExtras(self) -> android.os.Bundle: ...
    def getLocusId(self) -> android.content.LocusId: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, locusId: android.content.LocusId): ...
        def build(self) -> 'ContentCaptureContext': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'ContentCaptureContext.Builder': ...

class ContentCaptureManager:
    DATA_SHARE_ERROR_CONCURRENT_REQUEST: typing.ClassVar[int] = ...
    DATA_SHARE_ERROR_TIMEOUT_INTERRUPTED: typing.ClassVar[int] = ...
    DATA_SHARE_ERROR_UNKNOWN: typing.ClassVar[int] = ...
    def getContentCaptureConditions(self) -> java.util.Set[ContentCaptureCondition]: ...
    def getServiceComponentName(self) -> android.content.ComponentName: ...
    def isContentCaptureEnabled(self) -> bool: ...
    def removeData(self, dataRemovalRequest: 'DataRemovalRequest') -> None: ...
    def setContentCaptureEnabled(self, boolean: bool) -> None: ...
    def shareData(self, dataShareRequest: 'DataShareRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], dataShareWriteAdapter: 'DataShareWriteAdapter') -> None: ...

class ContentCaptureSession(java.lang.AutoCloseable):
    def close(self) -> None: ...
    def createContentCaptureSession(self, contentCaptureContext: ContentCaptureContext) -> 'ContentCaptureSession': ...
    def destroy(self) -> None: ...
    def getContentCaptureContext(self) -> ContentCaptureContext: ...
    def getContentCaptureSessionId(self) -> 'ContentCaptureSessionId': ...
    def newAutofillId(self, autofillId: android.view.autofill.AutofillId, long: int) -> android.view.autofill.AutofillId: ...
    def newViewStructure(self, view: android.view.View) -> android.view.ViewStructure: ...
    def newVirtualViewStructure(self, autofillId: android.view.autofill.AutofillId, long: int) -> android.view.ViewStructure: ...
    def notifySessionPaused(self) -> None: ...
    def notifySessionResumed(self) -> None: ...
    def notifyViewAppeared(self, viewStructure: android.view.ViewStructure) -> None: ...
    def notifyViewDisappeared(self, autofillId: android.view.autofill.AutofillId) -> None: ...
    def notifyViewInsetsChanged(self, insets: android.graphics.Insets) -> None: ...
    def notifyViewTextChanged(self, autofillId: android.view.autofill.AutofillId, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def notifyViewsAppeared(self, list: java.util.List[android.view.ViewStructure]) -> None: ...
    def notifyViewsDisappeared(self, autofillId: android.view.autofill.AutofillId, longArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def setContentCaptureContext(self, contentCaptureContext: ContentCaptureContext) -> None: ...
    def toString(self) -> str: ...

class ContentCaptureSessionId(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DataRemovalRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FLAG_IS_PREFIX: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getLocusIdRequests(self) -> java.util.List['DataRemovalRequest.LocusIdRequest']: ...
    def getPackageName(self) -> str: ...
    def isForEverything(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addLocusId(self, locusId: android.content.LocusId, int: int) -> 'DataRemovalRequest.Builder': ...
        def build(self) -> 'DataRemovalRequest': ...
        def forEverything(self) -> 'DataRemovalRequest.Builder': ...
    class LocusIdRequest:
        def getFlags(self) -> int: ...
        def getLocusId(self) -> android.content.LocusId: ...

class DataShareRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, locusId: android.content.LocusId, string: str): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLocusId(self) -> android.content.LocusId: ...
    def getMimeType(self) -> str: ...
    def getPackageName(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DataShareWriteAdapter:
    def onError(self, int: int) -> None: ...
    def onRejected(self) -> None: ...
    def onWrite(self, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.contentcapture")``.

    ContentCaptureCondition: typing.Type[ContentCaptureCondition]
    ContentCaptureContext: typing.Type[ContentCaptureContext]
    ContentCaptureManager: typing.Type[ContentCaptureManager]
    ContentCaptureSession: typing.Type[ContentCaptureSession]
    ContentCaptureSessionId: typing.Type[ContentCaptureSessionId]
    DataRemovalRequest: typing.Type[DataRemovalRequest]
    DataShareRequest: typing.Type[DataShareRequest]
    DataShareWriteAdapter: typing.Type[DataShareWriteAdapter]
