
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.net.wifi.hotspot2.omadm
import android.net.wifi.hotspot2.pps
import android.os
import jpype
import typing



class ConfigParser:
    @staticmethod
    def parsePasspointConfig(string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'PasspointConfiguration': ...

class PasspointConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, passpointConfiguration: 'PasspointConfiguration'): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCredential(self) -> android.net.wifi.hotspot2.pps.Credential: ...
    def getDecoratedIdentityPrefix(self) -> str: ...
    def getHomeSp(self) -> android.net.wifi.hotspot2.pps.HomeSp: ...
    def getSubscriptionExpirationTimeMillis(self) -> int: ...
    def getUniqueId(self) -> str: ...
    def hashCode(self) -> int: ...
    def isOsuProvisioned(self) -> bool: ...
    def setCredential(self, credential: android.net.wifi.hotspot2.pps.Credential) -> None: ...
    def setDecoratedIdentityPrefix(self, string: str) -> None: ...
    def setHomeSp(self, homeSp: android.net.wifi.hotspot2.pps.HomeSp) -> None: ...
    def setSubscriptionExpirationTimeInMillis(self, long: int) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.wifi.hotspot2")``.

    ConfigParser: typing.Type[ConfigParser]
    PasspointConfiguration: typing.Type[PasspointConfiguration]
    omadm: android.net.wifi.hotspot2.omadm.__module_protocol__
    pps: android.net.wifi.hotspot2.pps.__module_protocol__
