
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.os
import android.view
import android.view.accessibility
import typing



class DreamService(android.app.Service, android.view.Window.Callback):
    DREAM_META_DATA: typing.ClassVar[str] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def addContentView(self, view: android.view.View, layoutParams: android.view.ViewGroup.LayoutParams) -> None: ...
    def dispatchGenericMotionEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def dispatchKeyEvent(self, keyEvent: android.view.KeyEvent) -> bool: ...
    def dispatchKeyShortcutEvent(self, keyEvent: android.view.KeyEvent) -> bool: ...
    def dispatchPopulateAccessibilityEvent(self, accessibilityEvent: android.view.accessibility.AccessibilityEvent) -> bool: ...
    def dispatchTouchEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def dispatchTrackballEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    _findViewById__T = typing.TypeVar('_findViewById__T', bound=android.view.View)  # <T>
    def findViewById(self, int: int) -> _findViewById__T: ...
    def finish(self) -> None: ...
    def getWindow(self) -> android.view.Window: ...
    def getWindowManager(self) -> android.view.WindowManager: ...
    def isFullscreen(self) -> bool: ...
    def isInteractive(self) -> bool: ...
    def isScreenBright(self) -> bool: ...
    def onActionModeFinished(self, actionMode: android.view.ActionMode) -> None: ...
    def onActionModeStarted(self, actionMode: android.view.ActionMode) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onContentChanged(self) -> None: ...
    def onCreate(self) -> None: ...
    def onCreatePanelMenu(self, int: int, menu: android.view.Menu) -> bool: ...
    def onCreatePanelView(self, int: int) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDreamingStarted(self) -> None: ...
    def onDreamingStopped(self) -> None: ...
    def onMenuItemSelected(self, int: int, menuItem: android.view.MenuItem) -> bool: ...
    def onMenuOpened(self, int: int, menu: android.view.Menu) -> bool: ...
    def onPanelClosed(self, int: int, menu: android.view.Menu) -> None: ...
    def onPreparePanel(self, int: int, view: android.view.View, menu: android.view.Menu) -> bool: ...
    @typing.overload
    def onSearchRequested(self) -> bool: ...
    @typing.overload
    def onSearchRequested(self, searchEvent: android.view.SearchEvent) -> bool: ...
    def onUnbind(self, intent: android.content.Intent) -> bool: ...
    def onWakeUp(self) -> None: ...
    def onWindowAttributesChanged(self, layoutParams: android.view.WindowManager.LayoutParams) -> None: ...
    def onWindowFocusChanged(self, boolean: bool) -> None: ...
    @typing.overload
    def onWindowStartingActionMode(self, callback: android.view.ActionMode.Callback) -> android.view.ActionMode: ...
    @typing.overload
    def onWindowStartingActionMode(self, callback: android.view.ActionMode.Callback, int: int) -> android.view.ActionMode: ...
    _requireViewById__T = typing.TypeVar('_requireViewById__T', bound=android.view.View)  # <T>
    def requireViewById(self, int: int) -> _requireViewById__T: ...
    @typing.overload
    def setContentView(self, view: android.view.View) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, layoutParams: android.view.ViewGroup.LayoutParams) -> None: ...
    @typing.overload
    def setContentView(self, int: int) -> None: ...
    def setFullscreen(self, boolean: bool) -> None: ...
    def setInteractive(self, boolean: bool) -> None: ...
    def setScreenBright(self, boolean: bool) -> None: ...
    def wakeUp(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.dreams")``.

    DreamService: typing.Type[DreamService]
