
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import _jpype
import android.icu.text
import android.icu.util
import decimal
import java.lang
import java.math
import java.text
import java.util
import typing



class FormattedNumber(android.icu.text.FormattedValue):
    _appendTo__A = typing.TypeVar('_appendTo__A', bound=java.lang.Appendable)  # <A>
    def appendTo(self, a: _appendTo__A) -> _appendTo__A: ...
    def charAt(self, int: int) -> str: ...
    def getNounClass(self) -> android.icu.text.DisplayOptions.NounClass: ...
    def getOutputUnit(self) -> android.icu.util.MeasureUnit: ...
    def length(self) -> int: ...
    def nextPosition(self, constrainedFieldPosition: android.icu.text.ConstrainedFieldPosition) -> bool: ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toBigDecimal(self) -> java.math.BigDecimal: ...
    def toCharacterIterator(self) -> java.text.AttributedCharacterIterator: ...
    def toString(self) -> str: ...

class FormattedNumberRange(android.icu.text.FormattedValue):
    _appendTo__A = typing.TypeVar('_appendTo__A', bound=java.lang.Appendable)  # <A>
    def appendTo(self, a: _appendTo__A) -> _appendTo__A: ...
    def charAt(self, int: int) -> str: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFirstBigDecimal(self) -> java.math.BigDecimal: ...
    def getIdentityResult(self) -> 'NumberRangeFormatter.RangeIdentityResult': ...
    def getSecondBigDecimal(self) -> java.math.BigDecimal: ...
    def hashCode(self) -> int: ...
    def length(self) -> int: ...
    def nextPosition(self, constrainedFieldPosition: android.icu.text.ConstrainedFieldPosition) -> bool: ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toCharacterIterator(self) -> java.text.AttributedCharacterIterator: ...
    def toString(self) -> str: ...

class IntegerWidth:
    def truncateAt(self, int: int) -> 'IntegerWidth': ...
    @staticmethod
    def zeroFillTo(int: int) -> 'IntegerWidth': ...

class Notation:
    @staticmethod
    def compactLong() -> 'CompactNotation': ...
    @staticmethod
    def compactShort() -> 'CompactNotation': ...
    @staticmethod
    def engineering() -> 'ScientificNotation': ...
    @staticmethod
    def scientific() -> 'ScientificNotation': ...
    @staticmethod
    def simple() -> 'SimpleNotation': ...

class NumberFormatter:
    @typing.overload
    @staticmethod
    def withLocale(uLocale: android.icu.util.ULocale) -> 'LocalizedNumberFormatter': ...
    @typing.overload
    @staticmethod
    def withLocale(locale: java.util.Locale) -> 'LocalizedNumberFormatter': ...
    @staticmethod
    def with_() -> 'UnlocalizedNumberFormatter': ...
    class DecimalSeparatorDisplay(java.lang.Enum['NumberFormatter.DecimalSeparatorDisplay']):
        AUTO: typing.ClassVar['NumberFormatter.DecimalSeparatorDisplay'] = ...
        ALWAYS: typing.ClassVar['NumberFormatter.DecimalSeparatorDisplay'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberFormatter.DecimalSeparatorDisplay': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberFormatter.DecimalSeparatorDisplay']: ...
    class GroupingStrategy(java.lang.Enum['NumberFormatter.GroupingStrategy']):
        OFF: typing.ClassVar['NumberFormatter.GroupingStrategy'] = ...
        MIN2: typing.ClassVar['NumberFormatter.GroupingStrategy'] = ...
        AUTO: typing.ClassVar['NumberFormatter.GroupingStrategy'] = ...
        ON_ALIGNED: typing.ClassVar['NumberFormatter.GroupingStrategy'] = ...
        THOUSANDS: typing.ClassVar['NumberFormatter.GroupingStrategy'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberFormatter.GroupingStrategy': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberFormatter.GroupingStrategy']: ...
    class RoundingPriority(java.lang.Enum['NumberFormatter.RoundingPriority']):
        RELAXED: typing.ClassVar['NumberFormatter.RoundingPriority'] = ...
        STRICT: typing.ClassVar['NumberFormatter.RoundingPriority'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberFormatter.RoundingPriority': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberFormatter.RoundingPriority']: ...
    class SignDisplay(java.lang.Enum['NumberFormatter.SignDisplay']):
        AUTO: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        ALWAYS: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        NEVER: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        ACCOUNTING: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        ACCOUNTING_ALWAYS: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        EXCEPT_ZERO: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        ACCOUNTING_EXCEPT_ZERO: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        NEGATIVE: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        ACCOUNTING_NEGATIVE: typing.ClassVar['NumberFormatter.SignDisplay'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberFormatter.SignDisplay': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberFormatter.SignDisplay']: ...
    class TrailingZeroDisplay(java.lang.Enum['NumberFormatter.TrailingZeroDisplay']):
        AUTO: typing.ClassVar['NumberFormatter.TrailingZeroDisplay'] = ...
        HIDE_IF_WHOLE: typing.ClassVar['NumberFormatter.TrailingZeroDisplay'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberFormatter.TrailingZeroDisplay': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberFormatter.TrailingZeroDisplay']: ...
    class UnitWidth(java.lang.Enum['NumberFormatter.UnitWidth']):
        NARROW: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        SHORT: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        FULL_NAME: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        ISO_CODE: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        FORMAL: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        VARIANT: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        HIDDEN: typing.ClassVar['NumberFormatter.UnitWidth'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberFormatter.UnitWidth': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberFormatter.UnitWidth']: ...

_NumberFormatterSettings__T = typing.TypeVar('_NumberFormatterSettings__T', bound='NumberFormatterSettings')  # <T>
class NumberFormatterSettings(typing.Generic[_NumberFormatterSettings__T]):
    def decimal(self, decimalSeparatorDisplay: NumberFormatter.DecimalSeparatorDisplay) -> _NumberFormatterSettings__T: ...
    def displayOptions(self, displayOptions: android.icu.text.DisplayOptions) -> _NumberFormatterSettings__T: ...
    def equals(self, object: typing.Any) -> bool: ...
    def grouping(self, groupingStrategy: NumberFormatter.GroupingStrategy) -> _NumberFormatterSettings__T: ...
    def hashCode(self) -> int: ...
    def integerWidth(self, integerWidth: IntegerWidth) -> _NumberFormatterSettings__T: ...
    def notation(self, notation: Notation) -> _NumberFormatterSettings__T: ...
    def perUnit(self, measureUnit: android.icu.util.MeasureUnit) -> _NumberFormatterSettings__T: ...
    def precision(self, precision: 'Precision') -> _NumberFormatterSettings__T: ...
    def roundingMode(self, roundingMode: java.math.RoundingMode) -> _NumberFormatterSettings__T: ...
    def scale(self, scale: 'Scale') -> _NumberFormatterSettings__T: ...
    def sign(self, signDisplay: NumberFormatter.SignDisplay) -> _NumberFormatterSettings__T: ...
    @typing.overload
    def symbols(self, decimalFormatSymbols: android.icu.text.DecimalFormatSymbols) -> _NumberFormatterSettings__T: ...
    @typing.overload
    def symbols(self, numberingSystem: android.icu.text.NumberingSystem) -> _NumberFormatterSettings__T: ...
    def unit(self, measureUnit: android.icu.util.MeasureUnit) -> _NumberFormatterSettings__T: ...
    def unitWidth(self, unitWidth: NumberFormatter.UnitWidth) -> _NumberFormatterSettings__T: ...
    def usage(self, string: str) -> _NumberFormatterSettings__T: ...

class NumberRangeFormatter:
    @typing.overload
    @staticmethod
    def withLocale(uLocale: android.icu.util.ULocale) -> 'LocalizedNumberRangeFormatter': ...
    @typing.overload
    @staticmethod
    def withLocale(locale: java.util.Locale) -> 'LocalizedNumberRangeFormatter': ...
    @staticmethod
    def with_() -> 'UnlocalizedNumberRangeFormatter': ...
    class RangeCollapse(java.lang.Enum['NumberRangeFormatter.RangeCollapse']):
        AUTO: typing.ClassVar['NumberRangeFormatter.RangeCollapse'] = ...
        NONE: typing.ClassVar['NumberRangeFormatter.RangeCollapse'] = ...
        UNIT: typing.ClassVar['NumberRangeFormatter.RangeCollapse'] = ...
        ALL: typing.ClassVar['NumberRangeFormatter.RangeCollapse'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberRangeFormatter.RangeCollapse': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberRangeFormatter.RangeCollapse']: ...
    class RangeIdentityFallback(java.lang.Enum['NumberRangeFormatter.RangeIdentityFallback']):
        SINGLE_VALUE: typing.ClassVar['NumberRangeFormatter.RangeIdentityFallback'] = ...
        APPROXIMATELY_OR_SINGLE_VALUE: typing.ClassVar['NumberRangeFormatter.RangeIdentityFallback'] = ...
        APPROXIMATELY: typing.ClassVar['NumberRangeFormatter.RangeIdentityFallback'] = ...
        RANGE: typing.ClassVar['NumberRangeFormatter.RangeIdentityFallback'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberRangeFormatter.RangeIdentityFallback': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberRangeFormatter.RangeIdentityFallback']: ...
    class RangeIdentityResult(java.lang.Enum['NumberRangeFormatter.RangeIdentityResult']):
        EQUAL_BEFORE_ROUNDING: typing.ClassVar['NumberRangeFormatter.RangeIdentityResult'] = ...
        EQUAL_AFTER_ROUNDING: typing.ClassVar['NumberRangeFormatter.RangeIdentityResult'] = ...
        NOT_EQUAL: typing.ClassVar['NumberRangeFormatter.RangeIdentityResult'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NumberRangeFormatter.RangeIdentityResult': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NumberRangeFormatter.RangeIdentityResult']: ...

_NumberRangeFormatterSettings__T = typing.TypeVar('_NumberRangeFormatterSettings__T', bound='NumberRangeFormatterSettings')  # <T>
class NumberRangeFormatterSettings(typing.Generic[_NumberRangeFormatterSettings__T]):
    def collapse(self, rangeCollapse: NumberRangeFormatter.RangeCollapse) -> _NumberRangeFormatterSettings__T: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def identityFallback(self, rangeIdentityFallback: NumberRangeFormatter.RangeIdentityFallback) -> _NumberRangeFormatterSettings__T: ...
    def numberFormatterBoth(self, unlocalizedNumberFormatter: 'UnlocalizedNumberFormatter') -> _NumberRangeFormatterSettings__T: ...
    def numberFormatterFirst(self, unlocalizedNumberFormatter: 'UnlocalizedNumberFormatter') -> _NumberRangeFormatterSettings__T: ...
    def numberFormatterSecond(self, unlocalizedNumberFormatter: 'UnlocalizedNumberFormatter') -> _NumberRangeFormatterSettings__T: ...

class Precision:
    @staticmethod
    def currency(currencyUsage: android.icu.util.Currency.CurrencyUsage) -> 'CurrencyPrecision': ...
    @staticmethod
    def fixedFraction(int: int) -> 'FractionPrecision': ...
    @staticmethod
    def fixedSignificantDigits(int: int) -> 'Precision': ...
    @staticmethod
    def increment(bigDecimal: typing.Union[java.math.BigDecimal, decimal.Decimal]) -> 'Precision': ...
    @staticmethod
    def integer() -> 'FractionPrecision': ...
    @staticmethod
    def maxFraction(int: int) -> 'FractionPrecision': ...
    @staticmethod
    def maxSignificantDigits(int: int) -> 'Precision': ...
    @staticmethod
    def minFraction(int: int) -> 'FractionPrecision': ...
    @staticmethod
    def minMaxFraction(int: int, int2: int) -> 'FractionPrecision': ...
    @staticmethod
    def minMaxSignificantDigits(int: int, int2: int) -> 'Precision': ...
    @staticmethod
    def minSignificantDigits(int: int) -> 'Precision': ...
    def trailingZeroDisplay(self, trailingZeroDisplay: NumberFormatter.TrailingZeroDisplay) -> 'Precision': ...
    @staticmethod
    def unlimited() -> 'Precision': ...

class Scale:
    @staticmethod
    def byBigDecimal(bigDecimal: typing.Union[java.math.BigDecimal, decimal.Decimal]) -> 'Scale': ...
    @staticmethod
    def byDouble(double: float) -> 'Scale': ...
    @staticmethod
    def byDoubleAndPowerOfTen(double: float, int: int) -> 'Scale': ...
    @staticmethod
    def none() -> 'Scale': ...
    @staticmethod
    def powerOfTen(int: int) -> 'Scale': ...

class CompactNotation(Notation): ...

class CurrencyPrecision(Precision):
    def withCurrency(self, currency: android.icu.util.Currency) -> Precision: ...

class FractionPrecision(Precision):
    def withMaxDigits(self, int: int) -> Precision: ...
    def withMinDigits(self, int: int) -> Precision: ...
    def withSignificantDigits(self, int: int, int2: int, roundingPriority: NumberFormatter.RoundingPriority) -> Precision: ...

class LocalizedNumberFormatter(NumberFormatterSettings['LocalizedNumberFormatter']):
    @typing.overload
    def format(self, measure: android.icu.util.Measure) -> FormattedNumber: ...
    @typing.overload
    def format(self, double: float) -> FormattedNumber: ...
    @typing.overload
    def format(self, number: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat]) -> FormattedNumber: ...
    @typing.overload
    def format(self, long: int) -> FormattedNumber: ...
    def toFormat(self) -> java.text.Format: ...

class LocalizedNumberRangeFormatter(NumberRangeFormatterSettings['LocalizedNumberRangeFormatter']):
    @typing.overload
    def formatRange(self, double: float, double2: float) -> FormattedNumberRange: ...
    @typing.overload
    def formatRange(self, int: int, int2: int) -> FormattedNumberRange: ...
    @typing.overload
    def formatRange(self, number: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat], number2: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat]) -> FormattedNumberRange: ...

class ScientificNotation(Notation):
    def withExponentSignDisplay(self, signDisplay: NumberFormatter.SignDisplay) -> 'ScientificNotation': ...
    def withMinExponentDigits(self, int: int) -> 'ScientificNotation': ...

class SimpleNotation(Notation): ...

class UnlocalizedNumberFormatter(NumberFormatterSettings['UnlocalizedNumberFormatter']):
    @typing.overload
    def locale(self, uLocale: android.icu.util.ULocale) -> LocalizedNumberFormatter: ...
    @typing.overload
    def locale(self, locale: java.util.Locale) -> LocalizedNumberFormatter: ...

class UnlocalizedNumberRangeFormatter(NumberRangeFormatterSettings['UnlocalizedNumberRangeFormatter']):
    @typing.overload
    def locale(self, uLocale: android.icu.util.ULocale) -> LocalizedNumberRangeFormatter: ...
    @typing.overload
    def locale(self, locale: java.util.Locale) -> LocalizedNumberRangeFormatter: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.icu.number")``.

    CompactNotation: typing.Type[CompactNotation]
    CurrencyPrecision: typing.Type[CurrencyPrecision]
    FormattedNumber: typing.Type[FormattedNumber]
    FormattedNumberRange: typing.Type[FormattedNumberRange]
    FractionPrecision: typing.Type[FractionPrecision]
    IntegerWidth: typing.Type[IntegerWidth]
    LocalizedNumberFormatter: typing.Type[LocalizedNumberFormatter]
    LocalizedNumberRangeFormatter: typing.Type[LocalizedNumberRangeFormatter]
    Notation: typing.Type[Notation]
    NumberFormatter: typing.Type[NumberFormatter]
    NumberFormatterSettings: typing.Type[NumberFormatterSettings]
    NumberRangeFormatter: typing.Type[NumberRangeFormatter]
    NumberRangeFormatterSettings: typing.Type[NumberRangeFormatterSettings]
    Precision: typing.Type[Precision]
    Scale: typing.Type[Scale]
    ScientificNotation: typing.Type[ScientificNotation]
    SimpleNotation: typing.Type[SimpleNotation]
    UnlocalizedNumberFormatter: typing.Type[UnlocalizedNumberFormatter]
    UnlocalizedNumberRangeFormatter: typing.Type[UnlocalizedNumberRangeFormatter]
