
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.nfc
import java.io
import jpype
import typing



class TagTechnology(java.io.Closeable):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    def getTag(self) -> android.nfc.Tag: ...
    def isConnected(self) -> bool: ...

class IsoDep(TagTechnology):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'IsoDep': ...
    def getHiLayerResponse(self) -> typing.MutableSequence[int]: ...
    def getHistoricalBytes(self) -> typing.MutableSequence[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getTimeout(self) -> int: ...
    def isConnected(self) -> bool: ...
    def isExtendedLengthApduSupported(self) -> bool: ...
    def setTimeout(self, int: int) -> None: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...

class MifareClassic(TagTechnology):
    BLOCK_SIZE: typing.ClassVar[int] = ...
    KEY_DEFAULT: typing.ClassVar[typing.MutableSequence[int]] = ...
    KEY_MIFARE_APPLICATION_DIRECTORY: typing.ClassVar[typing.MutableSequence[int]] = ...
    KEY_NFC_FORUM: typing.ClassVar[typing.MutableSequence[int]] = ...
    SIZE_1K: typing.ClassVar[int] = ...
    SIZE_2K: typing.ClassVar[int] = ...
    SIZE_4K: typing.ClassVar[int] = ...
    SIZE_MINI: typing.ClassVar[int] = ...
    TYPE_CLASSIC: typing.ClassVar[int] = ...
    TYPE_PLUS: typing.ClassVar[int] = ...
    TYPE_PRO: typing.ClassVar[int] = ...
    TYPE_UNKNOWN: typing.ClassVar[int] = ...
    def authenticateSectorWithKeyA(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> bool: ...
    def authenticateSectorWithKeyB(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> bool: ...
    def blockToSector(self, int: int) -> int: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
    def decrement(self, int: int, int2: int) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'MifareClassic': ...
    def getBlockCount(self) -> int: ...
    def getBlockCountInSector(self, int: int) -> int: ...
    def getMaxTransceiveLength(self) -> int: ...
    def getSectorCount(self) -> int: ...
    def getSize(self) -> int: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getTimeout(self) -> int: ...
    def getType(self) -> int: ...
    def increment(self, int: int, int2: int) -> None: ...
    def isConnected(self) -> bool: ...
    def readBlock(self, int: int) -> typing.MutableSequence[int]: ...
    def restore(self, int: int) -> None: ...
    def sectorToBlock(self, int: int) -> int: ...
    def setTimeout(self, int: int) -> None: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def transfer(self, int: int) -> None: ...
    def writeBlock(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class MifareUltralight(TagTechnology):
    PAGE_SIZE: typing.ClassVar[int] = ...
    TYPE_ULTRALIGHT: typing.ClassVar[int] = ...
    TYPE_ULTRALIGHT_C: typing.ClassVar[int] = ...
    TYPE_UNKNOWN: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'MifareUltralight': ...
    def getMaxTransceiveLength(self) -> int: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getTimeout(self) -> int: ...
    def getType(self) -> int: ...
    def isConnected(self) -> bool: ...
    def readPages(self, int: int) -> typing.MutableSequence[int]: ...
    def setTimeout(self, int: int) -> None: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def writePage(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class Ndef(TagTechnology):
    MIFARE_CLASSIC: typing.ClassVar[str] = ...
    NFC_FORUM_TYPE_1: typing.ClassVar[str] = ...
    NFC_FORUM_TYPE_2: typing.ClassVar[str] = ...
    NFC_FORUM_TYPE_3: typing.ClassVar[str] = ...
    NFC_FORUM_TYPE_4: typing.ClassVar[str] = ...
    def canMakeReadOnly(self) -> bool: ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'Ndef': ...
    def getCachedNdefMessage(self) -> android.nfc.NdefMessage: ...
    def getMaxSize(self) -> int: ...
    def getNdefMessage(self) -> android.nfc.NdefMessage: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getType(self) -> str: ...
    def isConnected(self) -> bool: ...
    def isWritable(self) -> bool: ...
    def makeReadOnly(self) -> bool: ...
    def writeNdefMessage(self, ndefMessage: android.nfc.NdefMessage) -> None: ...

class NdefFormatable(TagTechnology):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    def format(self, ndefMessage: android.nfc.NdefMessage) -> None: ...
    def formatReadOnly(self, ndefMessage: android.nfc.NdefMessage) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'NdefFormatable': ...
    def getTag(self) -> android.nfc.Tag: ...
    def isConnected(self) -> bool: ...

class NfcA(TagTechnology):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'NfcA': ...
    def getAtqa(self) -> typing.MutableSequence[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def getSak(self) -> int: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getTimeout(self) -> int: ...
    def isConnected(self) -> bool: ...
    def setTimeout(self, int: int) -> None: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...

class NfcB(TagTechnology):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'NfcB': ...
    def getApplicationData(self) -> typing.MutableSequence[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def getProtocolInfo(self) -> typing.MutableSequence[int]: ...
    def getTag(self) -> android.nfc.Tag: ...
    def isConnected(self) -> bool: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...

class NfcBarcode(TagTechnology):
    TYPE_KOVIO: typing.ClassVar[int] = ...
    TYPE_UNKNOWN: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'NfcBarcode': ...
    def getBarcode(self) -> typing.MutableSequence[int]: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getType(self) -> int: ...
    def isConnected(self) -> bool: ...

class NfcF(TagTechnology):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'NfcF': ...
    def getManufacturer(self) -> typing.MutableSequence[int]: ...
    def getMaxTransceiveLength(self) -> int: ...
    def getSystemCode(self) -> typing.MutableSequence[int]: ...
    def getTag(self) -> android.nfc.Tag: ...
    def getTimeout(self) -> int: ...
    def isConnected(self) -> bool: ...
    def setTimeout(self, int: int) -> None: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...

class NfcV(TagTechnology):
    def close(self) -> None: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(tag: android.nfc.Tag) -> 'NfcV': ...
    def getDsfId(self) -> int: ...
    def getMaxTransceiveLength(self) -> int: ...
    def getResponseFlags(self) -> int: ...
    def getTag(self) -> android.nfc.Tag: ...
    def isConnected(self) -> bool: ...
    def transceive(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.nfc.tech")``.

    IsoDep: typing.Type[IsoDep]
    MifareClassic: typing.Type[MifareClassic]
    MifareUltralight: typing.Type[MifareUltralight]
    Ndef: typing.Type[Ndef]
    NdefFormatable: typing.Type[NdefFormatable]
    NfcA: typing.Type[NfcA]
    NfcB: typing.Type[NfcB]
    NfcBarcode: typing.Type[NfcBarcode]
    NfcF: typing.Type[NfcF]
    NfcV: typing.Type[NfcV]
    TagTechnology: typing.Type[TagTechnology]
