
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.view
import java.lang
import java.util
import java.util.function
import typing



_InspectionCompanion__T = typing.TypeVar('_InspectionCompanion__T')  # <T>
class InspectionCompanion(typing.Generic[_InspectionCompanion__T]):
    def mapProperties(self, propertyMapper: 'PropertyMapper') -> None: ...
    def readProperties(self, t: _InspectionCompanion__T, propertyReader: 'PropertyReader') -> None: ...
    class UninitializedPropertyMapException(java.lang.RuntimeException):
        def __init__(self): ...

class InspectionCompanionProvider:
    _provide__T = typing.TypeVar('_provide__T')  # <T>
    def provide(self, class_: typing.Type[_provide__T]) -> InspectionCompanion[_provide__T]: ...

class IntFlagMapping:
    def __init__(self): ...
    def add(self, int: int, int2: int, string: str) -> None: ...
    def get(self, int: int) -> java.util.Set[str]: ...

class PropertyMapper:
    def mapBoolean(self, string: str, int: int) -> int: ...
    def mapByte(self, string: str, int: int) -> int: ...
    def mapChar(self, string: str, int: int) -> int: ...
    def mapColor(self, string: str, int: int) -> int: ...
    def mapDouble(self, string: str, int: int) -> int: ...
    def mapFloat(self, string: str, int: int) -> int: ...
    def mapGravity(self, string: str, int: int) -> int: ...
    def mapInt(self, string: str, int: int) -> int: ...
    def mapIntEnum(self, string: str, int: int, intFunction: typing.Union[java.util.function.IntFunction[str], typing.Callable[[int], str]]) -> int: ...
    def mapIntFlag(self, string: str, int: int, intFunction: typing.Union[java.util.function.IntFunction[java.util.Set[str]], typing.Callable[[int], java.util.Set[str]]]) -> int: ...
    def mapLong(self, string: str, int: int) -> int: ...
    def mapObject(self, string: str, int: int) -> int: ...
    def mapResourceId(self, string: str, int: int) -> int: ...
    def mapShort(self, string: str, int: int) -> int: ...
    class PropertyConflictException(java.lang.RuntimeException):
        def __init__(self, string: str, string2: str, string3: str): ...

class PropertyReader:
    def readBoolean(self, int: int, boolean: bool) -> None: ...
    def readByte(self, int: int, byte: int) -> None: ...
    def readChar(self, int: int, char: str) -> None: ...
    @typing.overload
    def readColor(self, int: int, color: android.graphics.Color) -> None: ...
    @typing.overload
    def readColor(self, int: int, int2: int) -> None: ...
    @typing.overload
    def readColor(self, int: int, long: int) -> None: ...
    def readDouble(self, int: int, double: float) -> None: ...
    def readFloat(self, int: int, float: float) -> None: ...
    def readGravity(self, int: int, int2: int) -> None: ...
    def readInt(self, int: int, int2: int) -> None: ...
    def readIntEnum(self, int: int, int2: int) -> None: ...
    def readIntFlag(self, int: int, int2: int) -> None: ...
    def readLong(self, int: int, long: int) -> None: ...
    def readObject(self, int: int, object: typing.Any) -> None: ...
    def readResourceId(self, int: int, int2: int) -> None: ...
    def readShort(self, int: int, short: int) -> None: ...
    class PropertyTypeMismatchException(java.lang.RuntimeException):
        @typing.overload
        def __init__(self, int: int, string: str, string2: str): ...
        @typing.overload
        def __init__(self, int: int, string: str, string2: str, string3: str): ...

class WindowInspector:
    @staticmethod
    def getGlobalWindowViews() -> java.util.List[android.view.View]: ...

class StaticInspectionCompanionProvider(InspectionCompanionProvider):
    def __init__(self): ...
    _provide__T = typing.TypeVar('_provide__T')  # <T>
    def provide(self, class_: typing.Type[_provide__T]) -> InspectionCompanion[_provide__T]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.inspector")``.

    InspectionCompanion: typing.Type[InspectionCompanion]
    InspectionCompanionProvider: typing.Type[InspectionCompanionProvider]
    IntFlagMapping: typing.Type[IntFlagMapping]
    PropertyMapper: typing.Type[PropertyMapper]
    PropertyReader: typing.Type[PropertyReader]
    StaticInspectionCompanionProvider: typing.Type[StaticInspectionCompanionProvider]
    WindowInspector: typing.Type[WindowInspector]
