
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.adservices.common
import android.content
import android.net
import android.os
import android.view
import java.lang
import java.util
import java.util.concurrent
import jpype
import typing



class AdSelectionConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdSelectionSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    def getCustomAudienceBuyers(self) -> java.util.List[android.adservices.common.AdTechIdentifier]: ...
    def getDecisionLogicUri(self) -> android.net.Uri: ...
    def getPerBuyerSignals(self) -> java.util.Map[android.adservices.common.AdTechIdentifier, android.adservices.common.AdSelectionSignals]: ...
    def getPerBuyerSignedContextualAds(self) -> java.util.Map[android.adservices.common.AdTechIdentifier, 'SignedContextualAds']: ...
    def getSeller(self) -> android.adservices.common.AdTechIdentifier: ...
    def getSellerSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    def getTrustedScoringSignalsUri(self) -> android.net.Uri: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdSelectionConfig': ...
        def setAdSelectionSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'AdSelectionConfig.Builder': ...
        def setCustomAudienceBuyers(self, list: java.util.List[android.adservices.common.AdTechIdentifier]) -> 'AdSelectionConfig.Builder': ...
        def setDecisionLogicUri(self, uri: android.net.Uri) -> 'AdSelectionConfig.Builder': ...
        def setPerBuyerSignals(self, map: typing.Union[java.util.Map[android.adservices.common.AdTechIdentifier, android.adservices.common.AdSelectionSignals], typing.Mapping[android.adservices.common.AdTechIdentifier, android.adservices.common.AdSelectionSignals]]) -> 'AdSelectionConfig.Builder': ...
        def setPerBuyerSignedContextualAds(self, map: typing.Union[java.util.Map[android.adservices.common.AdTechIdentifier, 'SignedContextualAds'], typing.Mapping[android.adservices.common.AdTechIdentifier, 'SignedContextualAds']]) -> 'AdSelectionConfig.Builder': ...
        def setSeller(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'AdSelectionConfig.Builder': ...
        def setSellerSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'AdSelectionConfig.Builder': ...
        def setTrustedScoringSignalsUri(self, uri: android.net.Uri) -> 'AdSelectionConfig.Builder': ...

class AdSelectionFromOutcomesConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdSelectionIds(self) -> java.util.List[int]: ...
    def getSelectionLogicUri(self) -> android.net.Uri: ...
    def getSelectionSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    def getSeller(self) -> android.adservices.common.AdTechIdentifier: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdSelectionFromOutcomesConfig': ...
        def setAdSelectionIds(self, list: java.util.List[int]) -> 'AdSelectionFromOutcomesConfig.Builder': ...
        def setSelectionLogicUri(self, uri: android.net.Uri) -> 'AdSelectionFromOutcomesConfig.Builder': ...
        def setSelectionSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'AdSelectionFromOutcomesConfig.Builder': ...
        def setSeller(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'AdSelectionFromOutcomesConfig.Builder': ...

class AdSelectionManager:
    @staticmethod
    def get(context: android.content.Context) -> 'AdSelectionManager': ...
    def getAdSelectionData(self, getAdSelectionDataRequest: 'GetAdSelectionDataRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['GetAdSelectionDataOutcome', java.lang.Exception], typing.Callable[['GetAdSelectionDataOutcome'], None]]) -> None: ...
    def getTestAdSelectionManager(self) -> 'TestAdSelectionManager': ...
    def persistAdSelectionResult(self, persistAdSelectionResultRequest: 'PersistAdSelectionResultRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['AdSelectionOutcome', java.lang.Exception], typing.Callable[['AdSelectionOutcome'], None]]) -> None: ...
    def reportEvent(self, reportEventRequest: 'ReportEventRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def reportImpression(self, reportImpressionRequest: 'ReportImpressionRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    @typing.overload
    def selectAds(self, adSelectionConfig: AdSelectionConfig, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['AdSelectionOutcome', java.lang.Exception], typing.Callable[['AdSelectionOutcome'], None]]) -> None: ...
    @typing.overload
    def selectAds(self, adSelectionFromOutcomesConfig: AdSelectionFromOutcomesConfig, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['AdSelectionOutcome', java.lang.Exception], typing.Callable[['AdSelectionOutcome'], None]]) -> None: ...
    def setAppInstallAdvertisers(self, setAppInstallAdvertisersRequest: 'SetAppInstallAdvertisersRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def updateAdCounterHistogram(self, updateAdCounterHistogramRequest: 'UpdateAdCounterHistogramRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...

class AdSelectionOutcome:
    NO_OUTCOME: typing.ClassVar['AdSelectionOutcome'] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdSelectionId(self) -> int: ...
    def getRenderUri(self) -> android.net.Uri: ...
    def hasOutcome(self) -> bool: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdSelectionOutcome': ...
        def setAdSelectionId(self, long: int) -> 'AdSelectionOutcome.Builder': ...
        def setRenderUri(self, uri: android.net.Uri) -> 'AdSelectionOutcome.Builder': ...

class AdWithBid(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, adData: android.adservices.common.AdData, double: float): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdData(self) -> android.adservices.common.AdData: ...
    def getBid(self) -> float: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AddAdSelectionFromOutcomesOverrideRequest:
    def __init__(self, adSelectionFromOutcomesConfig: AdSelectionFromOutcomesConfig, string: str, adSelectionSignals: android.adservices.common.AdSelectionSignals): ...
    def getAdSelectionFromOutcomesConfig(self) -> AdSelectionFromOutcomesConfig: ...
    def getOutcomeSelectionLogicJs(self) -> str: ...
    def getOutcomeSelectionTrustedSignals(self) -> android.adservices.common.AdSelectionSignals: ...

class AddAdSelectionOverrideRequest:
    @typing.overload
    def __init__(self, adSelectionConfig: AdSelectionConfig, string: str, adSelectionSignals: android.adservices.common.AdSelectionSignals): ...
    @typing.overload
    def __init__(self, adSelectionConfig: AdSelectionConfig, string: str, adSelectionSignals: android.adservices.common.AdSelectionSignals, perBuyerDecisionLogic: 'PerBuyerDecisionLogic'): ...
    def getAdSelectionConfig(self) -> AdSelectionConfig: ...
    def getDecisionLogicJs(self) -> str: ...
    def getPerBuyerDecisionLogic(self) -> 'PerBuyerDecisionLogic': ...
    def getTrustedScoringSignals(self) -> android.adservices.common.AdSelectionSignals: ...

class DecisionLogic(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLogic(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GetAdSelectionDataOutcome:
    def getAdSelectionData(self) -> typing.MutableSequence[int]: ...
    def getAdSelectionDataId(self) -> int: ...
    def getAdSelectionId(self) -> int: ...

class GetAdSelectionDataRequest:
    def getCoordinatorOriginUri(self) -> android.net.Uri: ...
    def getSeller(self) -> android.adservices.common.AdTechIdentifier: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'GetAdSelectionDataRequest': ...
        def setCoordinatorOriginUri(self, uri: android.net.Uri) -> 'GetAdSelectionDataRequest.Builder': ...
        def setSeller(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'GetAdSelectionDataRequest.Builder': ...

class PerBuyerDecisionLogic(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EMPTY: typing.ClassVar['PerBuyerDecisionLogic'] = ...
    def __init__(self, map: typing.Union[java.util.Map[android.adservices.common.AdTechIdentifier, DecisionLogic], typing.Mapping[android.adservices.common.AdTechIdentifier, DecisionLogic]]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPerBuyerLogicMap(self) -> java.util.Map[android.adservices.common.AdTechIdentifier, DecisionLogic]: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PersistAdSelectionResultRequest:
    def getAdSelectionDataId(self) -> int: ...
    def getAdSelectionId(self) -> int: ...
    def getAdSelectionResult(self) -> typing.MutableSequence[int]: ...
    def getSeller(self) -> android.adservices.common.AdTechIdentifier: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'PersistAdSelectionResultRequest': ...
        def setAdSelectionDataId(self, long: int) -> 'PersistAdSelectionResultRequest.Builder': ...
        def setAdSelectionId(self, long: int) -> 'PersistAdSelectionResultRequest.Builder': ...
        def setAdSelectionResult(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'PersistAdSelectionResultRequest.Builder': ...
        def setSeller(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'PersistAdSelectionResultRequest.Builder': ...

class RemoveAdSelectionFromOutcomesOverrideRequest:
    def __init__(self, adSelectionFromOutcomesConfig: AdSelectionFromOutcomesConfig): ...
    def getAdSelectionFromOutcomesConfig(self) -> AdSelectionFromOutcomesConfig: ...

class RemoveAdSelectionOverrideRequest:
    def __init__(self, adSelectionConfig: AdSelectionConfig): ...
    def getAdSelectionConfig(self) -> AdSelectionConfig: ...

class ReportEventRequest:
    FLAG_REPORTING_DESTINATION_BUYER: typing.ClassVar[int] = ...
    FLAG_REPORTING_DESTINATION_SELLER: typing.ClassVar[int] = ...
    def getAdSelectionId(self) -> int: ...
    def getData(self) -> str: ...
    def getInputEvent(self) -> android.view.InputEvent: ...
    def getKey(self) -> str: ...
    def getReportingDestinations(self) -> int: ...
    class Builder:
        def __init__(self, long: int, string: str, string2: str, int: int): ...
        def build(self) -> 'ReportEventRequest': ...
        def setAdSelectionId(self, long: int) -> 'ReportEventRequest.Builder': ...
        def setData(self, string: str) -> 'ReportEventRequest.Builder': ...
        def setInputEvent(self, inputEvent: android.view.InputEvent) -> 'ReportEventRequest.Builder': ...
        def setKey(self, string: str) -> 'ReportEventRequest.Builder': ...
        def setReportingDestinations(self, int: int) -> 'ReportEventRequest.Builder': ...

class ReportImpressionRequest:
    @typing.overload
    def __init__(self, long: int): ...
    @typing.overload
    def __init__(self, long: int, adSelectionConfig: AdSelectionConfig): ...
    def getAdSelectionConfig(self) -> AdSelectionConfig: ...
    def getAdSelectionId(self) -> int: ...

class SetAppInstallAdvertisersRequest:
    def getAdvertisers(self) -> java.util.Set[android.adservices.common.AdTechIdentifier]: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'SetAppInstallAdvertisersRequest': ...
        def setAdvertisers(self, set: java.util.Set[android.adservices.common.AdTechIdentifier]) -> 'SetAppInstallAdvertisersRequest.Builder': ...

class SignedContextualAds(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdsWithBid(self) -> java.util.List[AdWithBid]: ...
    def getBuyer(self) -> android.adservices.common.AdTechIdentifier: ...
    def getDecisionLogicUri(self) -> android.net.Uri: ...
    def getSignature(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, signedContextualAds: 'SignedContextualAds'): ...
        def build(self) -> 'SignedContextualAds': ...
        def setAdsWithBid(self, list: java.util.List[AdWithBid]) -> 'SignedContextualAds.Builder': ...
        def setBuyer(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'SignedContextualAds.Builder': ...
        def setDecisionLogicUri(self, uri: android.net.Uri) -> 'SignedContextualAds.Builder': ...
        def setSignature(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'SignedContextualAds.Builder': ...

class TestAdSelectionManager:
    def overrideAdSelectionConfigRemoteInfo(self, addAdSelectionOverrideRequest: AddAdSelectionOverrideRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def overrideAdSelectionFromOutcomesConfigRemoteInfo(self, addAdSelectionFromOutcomesOverrideRequest: AddAdSelectionFromOutcomesOverrideRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def removeAdSelectionConfigRemoteInfoOverride(self, removeAdSelectionOverrideRequest: RemoveAdSelectionOverrideRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def removeAdSelectionFromOutcomesConfigRemoteInfoOverride(self, removeAdSelectionFromOutcomesOverrideRequest: RemoveAdSelectionFromOutcomesOverrideRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def resetAllAdSelectionConfigRemoteOverrides(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def resetAllAdSelectionFromOutcomesConfigRemoteOverrides(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...

class UpdateAdCounterHistogramRequest:
    def equals(self, object: typing.Any) -> bool: ...
    def getAdEventType(self) -> int: ...
    def getAdSelectionId(self) -> int: ...
    def getCallerAdTech(self) -> android.adservices.common.AdTechIdentifier: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    class Builder:
        def __init__(self, long: int, int: int, adTechIdentifier: android.adservices.common.AdTechIdentifier): ...
        def build(self) -> 'UpdateAdCounterHistogramRequest': ...
        def setAdEventType(self, int: int) -> 'UpdateAdCounterHistogramRequest.Builder': ...
        def setAdSelectionId(self, long: int) -> 'UpdateAdCounterHistogramRequest.Builder': ...
        def setCallerAdTech(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'UpdateAdCounterHistogramRequest.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.adservices.adselection")``.

    AdSelectionConfig: typing.Type[AdSelectionConfig]
    AdSelectionFromOutcomesConfig: typing.Type[AdSelectionFromOutcomesConfig]
    AdSelectionManager: typing.Type[AdSelectionManager]
    AdSelectionOutcome: typing.Type[AdSelectionOutcome]
    AdWithBid: typing.Type[AdWithBid]
    AddAdSelectionFromOutcomesOverrideRequest: typing.Type[AddAdSelectionFromOutcomesOverrideRequest]
    AddAdSelectionOverrideRequest: typing.Type[AddAdSelectionOverrideRequest]
    DecisionLogic: typing.Type[DecisionLogic]
    GetAdSelectionDataOutcome: typing.Type[GetAdSelectionDataOutcome]
    GetAdSelectionDataRequest: typing.Type[GetAdSelectionDataRequest]
    PerBuyerDecisionLogic: typing.Type[PerBuyerDecisionLogic]
    PersistAdSelectionResultRequest: typing.Type[PersistAdSelectionResultRequest]
    RemoveAdSelectionFromOutcomesOverrideRequest: typing.Type[RemoveAdSelectionFromOutcomesOverrideRequest]
    RemoveAdSelectionOverrideRequest: typing.Type[RemoveAdSelectionOverrideRequest]
    ReportEventRequest: typing.Type[ReportEventRequest]
    ReportImpressionRequest: typing.Type[ReportImpressionRequest]
    SetAppInstallAdvertisersRequest: typing.Type[SetAppInstallAdvertisersRequest]
    SignedContextualAds: typing.Type[SignedContextualAds]
    TestAdSelectionManager: typing.Type[TestAdSelectionManager]
    UpdateAdCounterHistogramRequest: typing.Type[UpdateAdCounterHistogramRequest]
