
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.bluetooth
import android.bluetooth.le
import android.companion.virtual
import android.content
import android.net
import android.net.wifi
import android.os
import java.io
import java.lang
import java.nio
import java.util
import java.util.concurrent
import java.util.regex
import jpype
import typing



class AssociatedDevice(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBleDevice(self) -> android.bluetooth.le.ScanResult: ...
    def getBluetoothDevice(self) -> android.bluetooth.BluetoothDevice: ...
    def getWifiDevice(self) -> android.net.wifi.ScanResult: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AssociationInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAssociatedDevice(self) -> AssociatedDevice: ...
    def getDeviceMacAddress(self) -> android.net.MacAddress: ...
    def getDeviceProfile(self) -> str: ...
    def getDisplayName(self) -> java.lang.CharSequence: ...
    def getId(self) -> int: ...
    def getSystemDataSyncFlags(self) -> int: ...
    def hashCode(self) -> int: ...
    def isSelfManaged(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AssociationRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DEVICE_PROFILE_APP_STREAMING: typing.ClassVar[str] = ...
    DEVICE_PROFILE_AUTOMOTIVE_PROJECTION: typing.ClassVar[str] = ...
    DEVICE_PROFILE_COMPUTER: typing.ClassVar[str] = ...
    DEVICE_PROFILE_GLASSES: typing.ClassVar[str] = ...
    DEVICE_PROFILE_NEARBY_DEVICE_STREAMING: typing.ClassVar[str] = ...
    DEVICE_PROFILE_WATCH: typing.ClassVar[str] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDeviceProfile(self) -> str: ...
    def getDisplayName(self) -> java.lang.CharSequence: ...
    def hashCode(self) -> int: ...
    def isForceConfirmation(self) -> bool: ...
    def isSelfManaged(self) -> bool: ...
    def isSingleDevice(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addDeviceFilter(self, deviceFilter: 'DeviceFilter'[typing.Any]) -> 'AssociationRequest.Builder': ...
        def build(self) -> 'AssociationRequest': ...
        def setDeviceProfile(self, string: str) -> 'AssociationRequest.Builder': ...
        def setDisplayName(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'AssociationRequest.Builder': ...
        def setForceConfirmation(self, boolean: bool) -> 'AssociationRequest.Builder': ...
        def setSelfManaged(self, boolean: bool) -> 'AssociationRequest.Builder': ...
        def setSingleDevice(self, boolean: bool) -> 'AssociationRequest.Builder': ...

class CompanionDeviceManager:
    EXTRA_ASSOCIATION: typing.ClassVar[str] = ...
    EXTRA_DEVICE: typing.ClassVar[str] = ...
    FLAG_CALL_METADATA: typing.ClassVar[int] = ...
    RESULT_CANCELED: typing.ClassVar[int] = ...
    RESULT_DISCOVERY_TIMEOUT: typing.ClassVar[int] = ...
    RESULT_INTERNAL_ERROR: typing.ClassVar[int] = ...
    RESULT_OK: typing.ClassVar[int] = ...
    RESULT_USER_REJECTED: typing.ClassVar[int] = ...
    @typing.overload
    def associate(self, associationRequest: AssociationRequest, callback: 'CompanionDeviceManager.Callback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def associate(self, associationRequest: AssociationRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: 'CompanionDeviceManager.Callback') -> None: ...
    def attachSystemDataTransport(self, int: int, inputStream: java.io.InputStream, outputStream: java.io.OutputStream) -> None: ...
    def buildAssociationCancellationIntent(self) -> android.content.IntentSender: ...
    def buildPermissionTransferUserConsentIntent(self, int: int) -> android.content.IntentSender: ...
    def detachSystemDataTransport(self, int: int) -> None: ...
    def disableSystemDataSyncForTypes(self, int: int, int2: int) -> None: ...
    @typing.overload
    def disassociate(self, int: int) -> None: ...
    @typing.overload
    def disassociate(self, string: str) -> None: ...
    def enableSystemDataSyncForTypes(self, int: int, int2: int) -> None: ...
    def getAssociations(self) -> java.util.List[str]: ...
    def getMyAssociations(self) -> java.util.List[AssociationInfo]: ...
    def hasNotificationAccess(self, componentName: android.content.ComponentName) -> bool: ...
    def isPermissionTransferUserConsented(self, int: int) -> bool: ...
    def requestNotificationAccess(self, componentName: android.content.ComponentName) -> None: ...
    def startObservingDevicePresence(self, string: str) -> None: ...
    def startSystemDataTransfer(self, int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CompanionException'], typing.Callable[[None], None]]) -> None: ...
    def stopObservingDevicePresence(self, string: str) -> None: ...
    class Callback:
        def __init__(self): ...
        def onAssociationCreated(self, associationInfo: AssociationInfo) -> None: ...
        def onAssociationPending(self, intentSender: android.content.IntentSender) -> None: ...
        def onDeviceFound(self, intentSender: android.content.IntentSender) -> None: ...
        def onFailure(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...

class CompanionDeviceService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def attachSystemDataTransport(self, int: int, inputStream: java.io.InputStream, outputStream: java.io.OutputStream) -> None: ...
    def detachSystemDataTransport(self, int: int) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    @typing.overload
    def onDeviceAppeared(self, associationInfo: AssociationInfo) -> None: ...
    @typing.overload
    def onDeviceAppeared(self, string: str) -> None: ...
    @typing.overload
    def onDeviceDisappeared(self, associationInfo: AssociationInfo) -> None: ...
    @typing.overload
    def onDeviceDisappeared(self, string: str) -> None: ...

class CompanionException(java.lang.RuntimeException): ...

_DeviceFilter__D = typing.TypeVar('_DeviceFilter__D', bound=android.os.Parcelable)  # <D>
class DeviceFilter(android.os.Parcelable, typing.Generic[_DeviceFilter__D]): ...

class DeviceNotAssociatedException(java.lang.RuntimeException): ...

class BluetoothDeviceFilter(DeviceFilter[android.bluetooth.BluetoothDevice]):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addServiceUuid(self, parcelUuid: android.os.ParcelUuid, parcelUuid2: android.os.ParcelUuid) -> 'BluetoothDeviceFilter.Builder': ...
        def build(self) -> 'BluetoothDeviceFilter': ...
        def setAddress(self, string: str) -> 'BluetoothDeviceFilter.Builder': ...
        def setNamePattern(self, pattern: java.util.regex.Pattern) -> 'BluetoothDeviceFilter.Builder': ...

class BluetoothLeDeviceFilter(DeviceFilter[android.bluetooth.le.ScanResult]):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def getRenamePrefixLengthLimit() -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'BluetoothLeDeviceFilter': ...
        def setNamePattern(self, pattern: java.util.regex.Pattern) -> 'BluetoothLeDeviceFilter.Builder': ...
        def setRawDataFilter(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray2: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'BluetoothLeDeviceFilter.Builder': ...
        def setRenameFromBytes(self, string: str, string2: str, int: int, int2: int, byteOrder: java.nio.ByteOrder) -> 'BluetoothLeDeviceFilter.Builder': ...
        def setRenameFromName(self, string: str, string2: str, int: int, int2: int) -> 'BluetoothLeDeviceFilter.Builder': ...
        def setScanFilter(self, scanFilter: android.bluetooth.le.ScanFilter) -> 'BluetoothLeDeviceFilter.Builder': ...

class WifiDeviceFilter(DeviceFilter[android.net.wifi.ScanResult]):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'WifiDeviceFilter': ...
        def setBssid(self, macAddress: android.net.MacAddress) -> 'WifiDeviceFilter.Builder': ...
        def setBssidMask(self, macAddress: android.net.MacAddress) -> 'WifiDeviceFilter.Builder': ...
        def setNamePattern(self, pattern: java.util.regex.Pattern) -> 'WifiDeviceFilter.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.companion")``.

    AssociatedDevice: typing.Type[AssociatedDevice]
    AssociationInfo: typing.Type[AssociationInfo]
    AssociationRequest: typing.Type[AssociationRequest]
    BluetoothDeviceFilter: typing.Type[BluetoothDeviceFilter]
    BluetoothLeDeviceFilter: typing.Type[BluetoothLeDeviceFilter]
    CompanionDeviceManager: typing.Type[CompanionDeviceManager]
    CompanionDeviceService: typing.Type[CompanionDeviceService]
    CompanionException: typing.Type[CompanionException]
    DeviceFilter: typing.Type[DeviceFilter]
    DeviceNotAssociatedException: typing.Type[DeviceNotAssociatedException]
    WifiDeviceFilter: typing.Type[WifiDeviceFilter]
    virtual: android.companion.virtual.__module_protocol__
