
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.app.appsearch.exceptions
import android.app.appsearch.observer
import android.app.appsearch.util
import android.os
import java.io
import java.lang
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



_AppSearchBatchResult__Builder__KeyType = typing.TypeVar('_AppSearchBatchResult__Builder__KeyType')  # <KeyType>
_AppSearchBatchResult__Builder__ValueType = typing.TypeVar('_AppSearchBatchResult__Builder__ValueType')  # <ValueType>
_AppSearchBatchResult__KeyType = typing.TypeVar('_AppSearchBatchResult__KeyType')  # <KeyType>
_AppSearchBatchResult__ValueType = typing.TypeVar('_AppSearchBatchResult__ValueType')  # <ValueType>
class AppSearchBatchResult(typing.Generic[_AppSearchBatchResult__KeyType, _AppSearchBatchResult__ValueType]):
    def getAll(self) -> java.util.Map[_AppSearchBatchResult__KeyType, 'AppSearchResult'[_AppSearchBatchResult__ValueType]]: ...
    def getFailures(self) -> java.util.Map[_AppSearchBatchResult__KeyType, 'AppSearchResult'[_AppSearchBatchResult__ValueType]]: ...
    def getSuccesses(self) -> java.util.Map[_AppSearchBatchResult__KeyType, _AppSearchBatchResult__ValueType]: ...
    def isSuccess(self) -> bool: ...
    def toString(self) -> str: ...
    class Builder(typing.Generic[_AppSearchBatchResult__Builder__KeyType, _AppSearchBatchResult__Builder__ValueType]):
        def __init__(self): ...
        def build(self) -> 'AppSearchBatchResult'[_AppSearchBatchResult__Builder__KeyType, _AppSearchBatchResult__Builder__ValueType]: ...
        def setFailure(self, keyType: _AppSearchBatchResult__Builder__KeyType, int: int, string: str) -> 'AppSearchBatchResult.Builder'[_AppSearchBatchResult__Builder__KeyType, _AppSearchBatchResult__Builder__ValueType]: ...
        def setResult(self, keyType: _AppSearchBatchResult__Builder__KeyType, appSearchResult: 'AppSearchResult'[_AppSearchBatchResult__Builder__ValueType]) -> 'AppSearchBatchResult.Builder'[_AppSearchBatchResult__Builder__KeyType, _AppSearchBatchResult__Builder__ValueType]: ...
        def setSuccess(self, keyType: _AppSearchBatchResult__Builder__KeyType, valueType: _AppSearchBatchResult__Builder__ValueType) -> 'AppSearchBatchResult.Builder'[_AppSearchBatchResult__Builder__KeyType, _AppSearchBatchResult__Builder__ValueType]: ...

class AppSearchManager:
    def createEnterpriseGlobalSearchSession(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer['AppSearchResult'['EnterpriseGlobalSearchSession']], typing.Callable[['AppSearchResult'['EnterpriseGlobalSearchSession']], None]]) -> None: ...
    def createGlobalSearchSession(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer['AppSearchResult'['GlobalSearchSession']], typing.Callable[['AppSearchResult'['GlobalSearchSession']], None]]) -> None: ...
    def createSearchSession(self, searchContext: 'AppSearchManager.SearchContext', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer['AppSearchResult'['AppSearchSession']], typing.Callable[['AppSearchResult'['AppSearchSession']], None]]) -> None: ...
    class SearchContext:
        def getDatabaseName(self) -> str: ...
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'AppSearchManager.SearchContext': ...

_AppSearchResult__ValueType = typing.TypeVar('_AppSearchResult__ValueType')  # <ValueType>
class AppSearchResult(typing.Generic[_AppSearchResult__ValueType]):
    RESULT_DENIED: typing.ClassVar[int] = ...
    RESULT_INTERNAL_ERROR: typing.ClassVar[int] = ...
    RESULT_INVALID_ARGUMENT: typing.ClassVar[int] = ...
    RESULT_INVALID_SCHEMA: typing.ClassVar[int] = ...
    RESULT_IO_ERROR: typing.ClassVar[int] = ...
    RESULT_NOT_FOUND: typing.ClassVar[int] = ...
    RESULT_OK: typing.ClassVar[int] = ...
    RESULT_OUT_OF_SPACE: typing.ClassVar[int] = ...
    RESULT_RATE_LIMITED: typing.ClassVar[int] = ...
    RESULT_SECURITY_ERROR: typing.ClassVar[int] = ...
    RESULT_UNKNOWN_ERROR: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getErrorMessage(self) -> str: ...
    def getResultCode(self) -> int: ...
    def getResultValue(self) -> _AppSearchResult__ValueType: ...
    def hashCode(self) -> int: ...
    def isSuccess(self) -> bool: ...
    _newFailedResult__ValueType = typing.TypeVar('_newFailedResult__ValueType')  # <ValueType>
    @staticmethod
    def newFailedResult(int: int, string: str) -> 'AppSearchResult'[_newFailedResult__ValueType]: ...
    _newSuccessfulResult__ValueType = typing.TypeVar('_newSuccessfulResult__ValueType')  # <ValueType>
    @staticmethod
    def newSuccessfulResult(valueType: _newSuccessfulResult__ValueType) -> 'AppSearchResult'[_newSuccessfulResult__ValueType]: ...
    def toString(self) -> str: ...

class AppSearchSession(java.io.Closeable):
    def close(self) -> None: ...
    def getByDocumentId(self, getByDocumentIdRequest: 'GetByDocumentIdRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], batchResultCallback: typing.Union['BatchResultCallback'[str, 'GenericDocument'], typing.Callable[[AppSearchBatchResult[typing.Any, typing.Any]], None]]) -> None: ...
    def getNamespaces(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[java.util.Set[str]]], typing.Callable[[AppSearchResult[java.util.Set[str]]], None]]) -> None: ...
    def getSchema(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult['GetSchemaResponse']], typing.Callable[[AppSearchResult['GetSchemaResponse']], None]]) -> None: ...
    def getStorageInfo(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult['StorageInfo']], typing.Callable[[AppSearchResult['StorageInfo']], None]]) -> None: ...
    def put(self, putDocumentsRequest: 'PutDocumentsRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], batchResultCallback: typing.Union['BatchResultCallback'[str, None], typing.Callable[[AppSearchBatchResult[typing.Any, typing.Any]], None]]) -> None: ...
    @typing.overload
    def remove(self, removeByDocumentIdRequest: 'RemoveByDocumentIdRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], batchResultCallback: typing.Union['BatchResultCallback'[str, None], typing.Callable[[AppSearchBatchResult[typing.Any, typing.Any]], None]]) -> None: ...
    @typing.overload
    def remove(self, string: str, searchSpec: 'SearchSpec', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[None]], typing.Callable[[AppSearchResult[None]], None]]) -> None: ...
    def reportUsage(self, reportUsageRequest: 'ReportUsageRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[None]], typing.Callable[[AppSearchResult[None]], None]]) -> None: ...
    def search(self, string: str, searchSpec: 'SearchSpec') -> 'SearchResults': ...
    def searchSuggestion(self, string: str, searchSuggestionSpec: 'SearchSuggestionSpec', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[java.util.List['SearchSuggestionResult']]], typing.Callable[[AppSearchResult[java.util.List['SearchSuggestionResult']]], None]]) -> None: ...
    def setSchema(self, setSchemaRequest: 'SetSchemaRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], executor2: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult['SetSchemaResponse']], typing.Callable[[AppSearchResult['SetSchemaResponse']], None]]) -> None: ...

_BatchResultCallback__KeyType = typing.TypeVar('_BatchResultCallback__KeyType')  # <KeyType>
_BatchResultCallback__ValueType = typing.TypeVar('_BatchResultCallback__ValueType')  # <ValueType>
class BatchResultCallback(typing.Generic[_BatchResultCallback__KeyType, _BatchResultCallback__ValueType]):
    def onResult(self, appSearchBatchResult: AppSearchBatchResult[_BatchResultCallback__KeyType, _BatchResultCallback__ValueType]) -> None: ...
    def onSystemError(self, throwable: java.lang.Throwable) -> None: ...

class EnterpriseGlobalSearchSession:
    def getByDocumentId(self, string: str, string2: str, getByDocumentIdRequest: 'GetByDocumentIdRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], batchResultCallback: typing.Union[BatchResultCallback[str, 'GenericDocument'], typing.Callable[[AppSearchBatchResult[typing.Any, typing.Any]], None]]) -> None: ...
    def getSchema(self, string: str, string2: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult['GetSchemaResponse']], typing.Callable[[AppSearchResult['GetSchemaResponse']], None]]) -> None: ...
    def search(self, string: str, searchSpec: 'SearchSpec') -> 'SearchResults': ...

_GenericDocument__Builder__BuilderType = typing.TypeVar('_GenericDocument__Builder__BuilderType', bound='GenericDocument.Builder')  # <BuilderType>
class GenericDocument:
    def equals(self, object: typing.Any) -> bool: ...
    def getCreationTimestampMillis(self) -> int: ...
    def getId(self) -> str: ...
    @staticmethod
    def getMaxIndexedProperties() -> int: ...
    def getNamespace(self) -> str: ...
    def getProperty(self, string: str) -> typing.Any: ...
    def getPropertyBoolean(self, string: str) -> bool: ...
    def getPropertyBooleanArray(self, string: str) -> typing.MutableSequence[bool]: ...
    def getPropertyBytes(self, string: str) -> typing.MutableSequence[int]: ...
    def getPropertyBytesArray(self, string: str) -> typing.MutableSequence[typing.MutableSequence[int]]: ...
    def getPropertyDocument(self, string: str) -> 'GenericDocument': ...
    def getPropertyDocumentArray(self, string: str) -> typing.MutableSequence['GenericDocument']: ...
    def getPropertyDouble(self, string: str) -> float: ...
    def getPropertyDoubleArray(self, string: str) -> typing.MutableSequence[float]: ...
    def getPropertyLong(self, string: str) -> int: ...
    def getPropertyLongArray(self, string: str) -> typing.MutableSequence[int]: ...
    def getPropertyNames(self) -> java.util.Set[str]: ...
    def getPropertyString(self, string: str) -> str: ...
    def getPropertyStringArray(self, string: str) -> typing.MutableSequence[str]: ...
    def getSchemaType(self) -> str: ...
    def getScore(self) -> int: ...
    def getTtlMillis(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    class Builder(typing.Generic[_GenericDocument__Builder__BuilderType]):
        @typing.overload
        def __init__(self, genericDocument: 'GenericDocument'): ...
        @typing.overload
        def __init__(self, string: str, string2: str, string3: str): ...
        def build(self) -> 'GenericDocument': ...
        def clearProperty(self, string: str) -> _GenericDocument__Builder__BuilderType: ...
        def setCreationTimestampMillis(self, long: int) -> _GenericDocument__Builder__BuilderType: ...
        def setId(self, string: str) -> _GenericDocument__Builder__BuilderType: ...
        def setNamespace(self, string: str) -> _GenericDocument__Builder__BuilderType: ...
        def setPropertyBoolean(self, string: str, *boolean: bool) -> _GenericDocument__Builder__BuilderType: ...
        def setPropertyBytes(self, string: str, *byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> _GenericDocument__Builder__BuilderType: ...
        def setPropertyDocument(self, string: str, *genericDocument: 'GenericDocument') -> _GenericDocument__Builder__BuilderType: ...
        def setPropertyDouble(self, string: str, *double: float) -> _GenericDocument__Builder__BuilderType: ...
        def setPropertyLong(self, string: str, *long: int) -> _GenericDocument__Builder__BuilderType: ...
        def setPropertyString(self, string: str, *string2: str) -> _GenericDocument__Builder__BuilderType: ...
        def setSchemaType(self, string: str) -> _GenericDocument__Builder__BuilderType: ...
        def setScore(self, int: int) -> _GenericDocument__Builder__BuilderType: ...
        def setTtlMillis(self, long: int) -> _GenericDocument__Builder__BuilderType: ...

class GetByDocumentIdRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PROJECTION_SCHEMA_TYPE_WILDCARD: typing.ClassVar[str] = ...
    def describeContents(self) -> int: ...
    def getIds(self) -> java.util.Set[str]: ...
    def getNamespace(self) -> str: ...
    def getProjectionPaths(self) -> java.util.Map[str, java.util.List['PropertyPath']]: ...
    def getProjections(self) -> java.util.Map[str, java.util.List[str]]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        @typing.overload
        def addIds(self, *string: str) -> 'GetByDocumentIdRequest.Builder': ...
        @typing.overload
        def addIds(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'GetByDocumentIdRequest.Builder': ...
        def addProjection(self, string: str, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'GetByDocumentIdRequest.Builder': ...
        def addProjectionPaths(self, string: str, collection: typing.Union[java.util.Collection['PropertyPath'], typing.Sequence['PropertyPath'], typing.Set['PropertyPath']]) -> 'GetByDocumentIdRequest.Builder': ...
        def build(self) -> 'GetByDocumentIdRequest': ...

class GetSchemaResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getPubliclyVisibleSchemas(self) -> java.util.Map[str, 'PackageIdentifier']: ...
    def getRequiredPermissionsForSchemaTypeVisibility(self) -> java.util.Map[str, java.util.Set[java.util.Set[int]]]: ...
    def getSchemaTypesNotDisplayedBySystem(self) -> java.util.Set[str]: ...
    def getSchemaTypesVisibleToConfigs(self) -> java.util.Map[str, java.util.Set['SchemaVisibilityConfig']]: ...
    def getSchemaTypesVisibleToPackages(self) -> java.util.Map[str, java.util.Set['PackageIdentifier']]: ...
    def getSchemas(self) -> java.util.Set['AppSearchSchema']: ...
    def getVersion(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addSchema(self, appSearchSchema: 'AppSearchSchema') -> 'GetSchemaResponse.Builder': ...
        def addSchemaTypeNotDisplayedBySystem(self, string: str) -> 'GetSchemaResponse.Builder': ...
        def build(self) -> 'GetSchemaResponse': ...
        def setPubliclyVisibleSchema(self, string: str, packageIdentifier: 'PackageIdentifier') -> 'GetSchemaResponse.Builder': ...
        def setRequiredPermissionsForSchemaTypeVisibility(self, string: str, set: java.util.Set[java.util.Set[int]]) -> 'GetSchemaResponse.Builder': ...
        def setSchemaTypeVisibleToConfigs(self, string: str, set: java.util.Set['SchemaVisibilityConfig']) -> 'GetSchemaResponse.Builder': ...
        def setSchemaTypeVisibleToPackages(self, string: str, set: java.util.Set['PackageIdentifier']) -> 'GetSchemaResponse.Builder': ...
        def setVersion(self, int: int) -> 'GetSchemaResponse.Builder': ...

class GlobalSearchSession(java.io.Closeable):
    def close(self) -> None: ...
    def getByDocumentId(self, string: str, string2: str, getByDocumentIdRequest: GetByDocumentIdRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], batchResultCallback: typing.Union[BatchResultCallback[str, GenericDocument], typing.Callable[[AppSearchBatchResult[typing.Any, typing.Any]], None]]) -> None: ...
    def getSchema(self, string: str, string2: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[GetSchemaResponse]], typing.Callable[[AppSearchResult[GetSchemaResponse]], None]]) -> None: ...
    def registerObserverCallback(self, string: str, observerSpec: android.app.appsearch.observer.ObserverSpec, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], observerCallback: android.app.appsearch.observer.ObserverCallback) -> None: ...
    def reportSystemUsage(self, reportSystemUsageRequest: 'ReportSystemUsageRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[None]], typing.Callable[[AppSearchResult[None]], None]]) -> None: ...
    def search(self, string: str, searchSpec: 'SearchSpec') -> 'SearchResults': ...
    def unregisterObserverCallback(self, string: str, observerCallback: android.app.appsearch.observer.ObserverCallback) -> None: ...

class JoinSpec(android.os.Parcelable):
    AGGREGATION_SCORING_AVG_RANKING_SIGNAL: typing.ClassVar[int] = ...
    AGGREGATION_SCORING_MAX_RANKING_SIGNAL: typing.ClassVar[int] = ...
    AGGREGATION_SCORING_MIN_RANKING_SIGNAL: typing.ClassVar[int] = ...
    AGGREGATION_SCORING_OUTER_RESULT_RANKING_SIGNAL: typing.ClassVar[int] = ...
    AGGREGATION_SCORING_RESULT_COUNT: typing.ClassVar[int] = ...
    AGGREGATION_SCORING_SUM_RANKING_SIGNAL: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAggregationScoringStrategy(self) -> int: ...
    def getChildPropertyExpression(self) -> str: ...
    def getMaxJoinedResultCount(self) -> int: ...
    def getNestedQuery(self) -> str: ...
    def getNestedSearchSpec(self) -> 'SearchSpec': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        def build(self) -> 'JoinSpec': ...
        def setAggregationScoringStrategy(self, int: int) -> 'JoinSpec.Builder': ...
        def setMaxJoinedResultCount(self, int: int) -> 'JoinSpec.Builder': ...
        def setNestedSearch(self, string: str, searchSpec: 'SearchSpec') -> 'JoinSpec.Builder': ...

class Migrator:
    def __init__(self): ...
    def onDowngrade(self, int: int, int2: int, genericDocument: GenericDocument) -> GenericDocument: ...
    def onUpgrade(self, int: int, int2: int, genericDocument: GenericDocument) -> GenericDocument: ...
    def shouldMigrate(self, int: int, int2: int) -> bool: ...

class PackageIdentifier:
    def __init__(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPackageName(self) -> str: ...
    def getSha256Certificate(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...

class PropertyPath(java.lang.Iterable['PropertyPath.PathSegment']):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, list: java.util.List['PropertyPath.PathSegment']): ...
    def equals(self, object: typing.Any) -> bool: ...
    def get(self, int: int) -> 'PropertyPath.PathSegment': ...
    def hashCode(self) -> int: ...
    def iterator(self) -> java.util.Iterator['PropertyPath.PathSegment']: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    class PathSegment:
        NON_REPEATED_CARDINALITY: typing.ClassVar[int] = ...
        @typing.overload
        @staticmethod
        def create(string: str) -> 'PropertyPath.PathSegment': ...
        @typing.overload
        @staticmethod
        def create(string: str, int: int) -> 'PropertyPath.PathSegment': ...
        def equals(self, object: typing.Any) -> bool: ...
        def getPropertyIndex(self) -> int: ...
        def getPropertyName(self) -> str: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class PutDocumentsRequest:
    def getGenericDocuments(self) -> java.util.List[GenericDocument]: ...
    def getTakenActionGenericDocuments(self) -> java.util.List[GenericDocument]: ...
    class Builder:
        def __init__(self): ...
        @typing.overload
        def addGenericDocuments(self, *genericDocument: GenericDocument) -> 'PutDocumentsRequest.Builder': ...
        @typing.overload
        def addGenericDocuments(self, collection: typing.Union[java.util.Collection[GenericDocument], typing.Sequence[GenericDocument], typing.Set[GenericDocument]]) -> 'PutDocumentsRequest.Builder': ...
        @typing.overload
        def addTakenActionGenericDocuments(self, *genericDocument: GenericDocument) -> 'PutDocumentsRequest.Builder': ...
        @typing.overload
        def addTakenActionGenericDocuments(self, collection: typing.Union[java.util.Collection[GenericDocument], typing.Sequence[GenericDocument], typing.Set[GenericDocument]]) -> 'PutDocumentsRequest.Builder': ...
        def build(self) -> 'PutDocumentsRequest': ...

class RemoveByDocumentIdRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getIds(self) -> java.util.Set[str]: ...
    def getNamespace(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        @typing.overload
        def addIds(self, *string: str) -> 'RemoveByDocumentIdRequest.Builder': ...
        @typing.overload
        def addIds(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'RemoveByDocumentIdRequest.Builder': ...
        def build(self) -> 'RemoveByDocumentIdRequest': ...

class ReportSystemUsageRequest:
    def getDatabaseName(self) -> str: ...
    def getDocumentId(self) -> str: ...
    def getNamespace(self) -> str: ...
    def getPackageName(self) -> str: ...
    def getUsageTimestampMillis(self) -> int: ...
    class Builder:
        def __init__(self, string: str, string2: str, string3: str, string4: str): ...
        def build(self) -> 'ReportSystemUsageRequest': ...
        def setUsageTimestampMillis(self, long: int) -> 'ReportSystemUsageRequest.Builder': ...

class ReportUsageRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDocumentId(self) -> str: ...
    def getNamespace(self) -> str: ...
    def getUsageTimestampMillis(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str, string2: str): ...
        def build(self) -> 'ReportUsageRequest': ...
        def setUsageTimestampMillis(self, long: int) -> 'ReportUsageRequest.Builder': ...

class SchemaVisibilityConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAllowedPackages(self) -> java.util.List[PackageIdentifier]: ...
    def getPubliclyVisibleTargetPackage(self) -> PackageIdentifier: ...
    def getRequiredPermissions(self) -> java.util.Set[java.util.Set[int]]: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addAllowedPackage(self, packageIdentifier: PackageIdentifier) -> 'SchemaVisibilityConfig.Builder': ...
        def addRequiredPermissions(self, set: java.util.Set[int]) -> 'SchemaVisibilityConfig.Builder': ...
        def build(self) -> 'SchemaVisibilityConfig': ...
        def clearAllowedPackages(self) -> 'SchemaVisibilityConfig.Builder': ...
        def clearRequiredPermissions(self) -> 'SchemaVisibilityConfig.Builder': ...
        def setPubliclyVisibleTargetPackage(self, packageIdentifier: PackageIdentifier) -> 'SchemaVisibilityConfig.Builder': ...

class SearchResult(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDatabaseName(self) -> str: ...
    def getGenericDocument(self) -> GenericDocument: ...
    def getJoinedResults(self) -> java.util.List['SearchResult']: ...
    def getMatchInfos(self) -> java.util.List['SearchResult.MatchInfo']: ...
    def getPackageName(self) -> str: ...
    def getRankingSignal(self) -> float: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str, string2: str): ...
        def addJoinedResult(self, searchResult: 'SearchResult') -> 'SearchResult.Builder': ...
        def addMatchInfo(self, matchInfo: 'SearchResult.MatchInfo') -> 'SearchResult.Builder': ...
        def build(self) -> 'SearchResult': ...
        def setGenericDocument(self, genericDocument: GenericDocument) -> 'SearchResult.Builder': ...
        def setRankingSignal(self, double: float) -> 'SearchResult.Builder': ...
    class MatchInfo(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getExactMatch(self) -> java.lang.CharSequence: ...
        def getExactMatchRange(self) -> 'SearchResult.MatchRange': ...
        def getFullText(self) -> str: ...
        def getPropertyPath(self) -> str: ...
        def getPropertyPathObject(self) -> PropertyPath: ...
        def getSnippet(self) -> java.lang.CharSequence: ...
        def getSnippetRange(self) -> 'SearchResult.MatchRange': ...
        def getSubmatch(self) -> java.lang.CharSequence: ...
        def getSubmatchRange(self) -> 'SearchResult.MatchRange': ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'SearchResult.MatchInfo': ...
            def setExactMatchRange(self, matchRange: 'SearchResult.MatchRange') -> 'SearchResult.MatchInfo.Builder': ...
            def setSnippetRange(self, matchRange: 'SearchResult.MatchRange') -> 'SearchResult.MatchInfo.Builder': ...
            def setSubmatchRange(self, matchRange: 'SearchResult.MatchRange') -> 'SearchResult.MatchInfo.Builder': ...
    class MatchRange:
        def __init__(self, int: int, int2: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getEnd(self) -> int: ...
        def getStart(self) -> int: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class SearchResults(java.io.Closeable):
    def close(self) -> None: ...
    def getNextPage(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[AppSearchResult[java.util.List[SearchResult]]], typing.Callable[[AppSearchResult[java.util.List[SearchResult]]], None]]) -> None: ...

class SearchSpec(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    GROUPING_TYPE_PER_NAMESPACE: typing.ClassVar[int] = ...
    GROUPING_TYPE_PER_PACKAGE: typing.ClassVar[int] = ...
    GROUPING_TYPE_PER_SCHEMA: typing.ClassVar[int] = ...
    ORDER_ASCENDING: typing.ClassVar[int] = ...
    ORDER_DESCENDING: typing.ClassVar[int] = ...
    PROJECTION_SCHEMA_TYPE_WILDCARD: typing.ClassVar[str] = ...
    RANKING_STRATEGY_ADVANCED_RANKING_EXPRESSION: typing.ClassVar[int] = ...
    RANKING_STRATEGY_CREATION_TIMESTAMP: typing.ClassVar[int] = ...
    RANKING_STRATEGY_DOCUMENT_SCORE: typing.ClassVar[int] = ...
    RANKING_STRATEGY_JOIN_AGGREGATE_SCORE: typing.ClassVar[int] = ...
    RANKING_STRATEGY_NONE: typing.ClassVar[int] = ...
    RANKING_STRATEGY_RELEVANCE_SCORE: typing.ClassVar[int] = ...
    RANKING_STRATEGY_SYSTEM_USAGE_COUNT: typing.ClassVar[int] = ...
    RANKING_STRATEGY_SYSTEM_USAGE_LAST_USED_TIMESTAMP: typing.ClassVar[int] = ...
    RANKING_STRATEGY_USAGE_COUNT: typing.ClassVar[int] = ...
    RANKING_STRATEGY_USAGE_LAST_USED_TIMESTAMP: typing.ClassVar[int] = ...
    SCHEMA_TYPE_WILDCARD: typing.ClassVar[str] = ...
    TERM_MATCH_EXACT_ONLY: typing.ClassVar[int] = ...
    TERM_MATCH_PREFIX: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getAdvancedRankingExpression(self) -> str: ...
    def getFilterNamespaces(self) -> java.util.List[str]: ...
    def getFilterPackageNames(self) -> java.util.List[str]: ...
    def getFilterProperties(self) -> java.util.Map[str, java.util.List[str]]: ...
    def getFilterSchemas(self) -> java.util.List[str]: ...
    def getJoinSpec(self) -> JoinSpec: ...
    def getMaxSnippetSize(self) -> int: ...
    def getOrder(self) -> int: ...
    def getProjectionPaths(self) -> java.util.Map[str, java.util.List[PropertyPath]]: ...
    def getProjections(self) -> java.util.Map[str, java.util.List[str]]: ...
    def getPropertyWeightPaths(self) -> java.util.Map[str, java.util.Map[PropertyPath, float]]: ...
    def getPropertyWeights(self) -> java.util.Map[str, java.util.Map[str, float]]: ...
    def getRankingStrategy(self) -> int: ...
    def getResultCountPerPage(self) -> int: ...
    def getResultGroupingLimit(self) -> int: ...
    def getResultGroupingTypeFlags(self) -> int: ...
    def getSearchSourceLogTag(self) -> str: ...
    def getSnippetCount(self) -> int: ...
    def getSnippetCountPerProperty(self) -> int: ...
    def getTermMatch(self) -> int: ...
    def isListFilterHasPropertyFunctionEnabled(self) -> bool: ...
    def isListFilterQueryLanguageEnabled(self) -> bool: ...
    def isNumericSearchEnabled(self) -> bool: ...
    def isVerbatimSearchEnabled(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        @typing.overload
        def addFilterNamespaces(self, *string: str) -> 'SearchSpec.Builder': ...
        @typing.overload
        def addFilterNamespaces(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSpec.Builder': ...
        @typing.overload
        def addFilterPackageNames(self, *string: str) -> 'SearchSpec.Builder': ...
        @typing.overload
        def addFilterPackageNames(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSpec.Builder': ...
        def addFilterProperties(self, string: str, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSpec.Builder': ...
        def addFilterPropertyPaths(self, string: str, collection: typing.Union[java.util.Collection[PropertyPath], typing.Sequence[PropertyPath], typing.Set[PropertyPath]]) -> 'SearchSpec.Builder': ...
        @typing.overload
        def addFilterSchemas(self, *string: str) -> 'SearchSpec.Builder': ...
        @typing.overload
        def addFilterSchemas(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSpec.Builder': ...
        def addProjection(self, string: str, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSpec.Builder': ...
        def addProjectionPaths(self, string: str, collection: typing.Union[java.util.Collection[PropertyPath], typing.Sequence[PropertyPath], typing.Set[PropertyPath]]) -> 'SearchSpec.Builder': ...
        def build(self) -> 'SearchSpec': ...
        def setJoinSpec(self, joinSpec: JoinSpec) -> 'SearchSpec.Builder': ...
        def setListFilterHasPropertyFunctionEnabled(self, boolean: bool) -> 'SearchSpec.Builder': ...
        def setListFilterQueryLanguageEnabled(self, boolean: bool) -> 'SearchSpec.Builder': ...
        def setMaxSnippetSize(self, int: int) -> 'SearchSpec.Builder': ...
        def setNumericSearchEnabled(self, boolean: bool) -> 'SearchSpec.Builder': ...
        def setOrder(self, int: int) -> 'SearchSpec.Builder': ...
        def setPropertyWeightPaths(self, string: str, map: typing.Union[java.util.Map[PropertyPath, float], typing.Mapping[PropertyPath, float]]) -> 'SearchSpec.Builder': ...
        def setPropertyWeights(self, string: str, map: typing.Union[java.util.Map[str, float], typing.Mapping[str, float]]) -> 'SearchSpec.Builder': ...
        @typing.overload
        def setRankingStrategy(self, int: int) -> 'SearchSpec.Builder': ...
        @typing.overload
        def setRankingStrategy(self, string: str) -> 'SearchSpec.Builder': ...
        def setResultCountPerPage(self, int: int) -> 'SearchSpec.Builder': ...
        def setResultGrouping(self, int: int, int2: int) -> 'SearchSpec.Builder': ...
        def setSearchSourceLogTag(self, string: str) -> 'SearchSpec.Builder': ...
        def setSnippetCount(self, int: int) -> 'SearchSpec.Builder': ...
        def setSnippetCountPerProperty(self, int: int) -> 'SearchSpec.Builder': ...
        def setTermMatch(self, int: int) -> 'SearchSpec.Builder': ...
        def setVerbatimSearchEnabled(self, boolean: bool) -> 'SearchSpec.Builder': ...

class SearchSuggestionResult(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSuggestedResult(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'SearchSuggestionResult': ...
        def setSuggestedResult(self, string: str) -> 'SearchSuggestionResult.Builder': ...

class SearchSuggestionSpec(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SUGGESTION_RANKING_STRATEGY_DOCUMENT_COUNT: typing.ClassVar[int] = ...
    SUGGESTION_RANKING_STRATEGY_NONE: typing.ClassVar[int] = ...
    SUGGESTION_RANKING_STRATEGY_TERM_FREQUENCY: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getFilterDocumentIds(self) -> java.util.Map[str, java.util.List[str]]: ...
    def getFilterNamespaces(self) -> java.util.List[str]: ...
    def getFilterProperties(self) -> java.util.Map[str, java.util.List[str]]: ...
    def getFilterSchemas(self) -> java.util.List[str]: ...
    def getMaximumResultCount(self) -> int: ...
    def getRankingStrategy(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int): ...
        @typing.overload
        def addFilterDocumentIds(self, string: str, *string2: str) -> 'SearchSuggestionSpec.Builder': ...
        @typing.overload
        def addFilterDocumentIds(self, string: str, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSuggestionSpec.Builder': ...
        @typing.overload
        def addFilterNamespaces(self, *string: str) -> 'SearchSuggestionSpec.Builder': ...
        @typing.overload
        def addFilterNamespaces(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSuggestionSpec.Builder': ...
        def addFilterProperties(self, string: str, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSuggestionSpec.Builder': ...
        def addFilterPropertyPaths(self, string: str, collection: typing.Union[java.util.Collection[PropertyPath], typing.Sequence[PropertyPath], typing.Set[PropertyPath]]) -> 'SearchSuggestionSpec.Builder': ...
        @typing.overload
        def addFilterSchemas(self, *string: str) -> 'SearchSuggestionSpec.Builder': ...
        @typing.overload
        def addFilterSchemas(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SearchSuggestionSpec.Builder': ...
        def build(self) -> 'SearchSuggestionSpec': ...
        def setRankingStrategy(self, int: int) -> 'SearchSuggestionSpec.Builder': ...

class SetSchemaRequest:
    READ_ASSISTANT_APP_SEARCH_DATA: typing.ClassVar[int] = ...
    READ_CALENDAR: typing.ClassVar[int] = ...
    READ_CONTACTS: typing.ClassVar[int] = ...
    READ_EXTERNAL_STORAGE: typing.ClassVar[int] = ...
    READ_HOME_APP_SEARCH_DATA: typing.ClassVar[int] = ...
    READ_SMS: typing.ClassVar[int] = ...
    def getMigrators(self) -> java.util.Map[str, Migrator]: ...
    def getPubliclyVisibleSchemas(self) -> java.util.Map[str, PackageIdentifier]: ...
    def getRequiredPermissionsForSchemaTypeVisibility(self) -> java.util.Map[str, java.util.Set[java.util.Set[int]]]: ...
    def getSchemas(self) -> java.util.Set['AppSearchSchema']: ...
    def getSchemasNotDisplayedBySystem(self) -> java.util.Set[str]: ...
    def getSchemasVisibleToConfigs(self) -> java.util.Map[str, java.util.Set[SchemaVisibilityConfig]]: ...
    def getSchemasVisibleToPackages(self) -> java.util.Map[str, java.util.Set[PackageIdentifier]]: ...
    def getVersion(self) -> int: ...
    def isForceOverride(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def addRequiredPermissionsForSchemaTypeVisibility(self, string: str, set: java.util.Set[int]) -> 'SetSchemaRequest.Builder': ...
        def addSchemaTypeVisibleToConfig(self, string: str, schemaVisibilityConfig: SchemaVisibilityConfig) -> 'SetSchemaRequest.Builder': ...
        @typing.overload
        def addSchemas(self, *appSearchSchema: 'AppSearchSchema') -> 'SetSchemaRequest.Builder': ...
        @typing.overload
        def addSchemas(self, collection: typing.Union[java.util.Collection['AppSearchSchema'], typing.Sequence['AppSearchSchema'], typing.Set['AppSearchSchema']]) -> 'SetSchemaRequest.Builder': ...
        def build(self) -> 'SetSchemaRequest': ...
        def clearRequiredPermissionsForSchemaTypeVisibility(self, string: str) -> 'SetSchemaRequest.Builder': ...
        def clearSchemaTypeVisibleToConfigs(self, string: str) -> 'SetSchemaRequest.Builder': ...
        def setForceOverride(self, boolean: bool) -> 'SetSchemaRequest.Builder': ...
        def setMigrator(self, string: str, migrator: Migrator) -> 'SetSchemaRequest.Builder': ...
        def setMigrators(self, map: typing.Union[java.util.Map[str, Migrator], typing.Mapping[str, Migrator]]) -> 'SetSchemaRequest.Builder': ...
        def setPubliclyVisibleSchema(self, string: str, packageIdentifier: PackageIdentifier) -> 'SetSchemaRequest.Builder': ...
        def setSchemaTypeDisplayedBySystem(self, string: str, boolean: bool) -> 'SetSchemaRequest.Builder': ...
        def setSchemaTypeVisibilityForPackage(self, string: str, boolean: bool, packageIdentifier: PackageIdentifier) -> 'SetSchemaRequest.Builder': ...
        def setVersion(self, int: int) -> 'SetSchemaRequest.Builder': ...

class SetSchemaResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDeletedTypes(self) -> java.util.Set[str]: ...
    def getIncompatibleTypes(self) -> java.util.Set[str]: ...
    def getMigratedTypes(self) -> java.util.Set[str]: ...
    def getMigrationFailures(self) -> java.util.List['SetSchemaResponse.MigrationFailure']: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addDeletedType(self, string: str) -> 'SetSchemaResponse.Builder': ...
        def addDeletedTypes(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SetSchemaResponse.Builder': ...
        def addIncompatibleType(self, string: str) -> 'SetSchemaResponse.Builder': ...
        def addIncompatibleTypes(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SetSchemaResponse.Builder': ...
        def addMigratedType(self, string: str) -> 'SetSchemaResponse.Builder': ...
        def addMigratedTypes(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'SetSchemaResponse.Builder': ...
        def addMigrationFailure(self, migrationFailure: 'SetSchemaResponse.MigrationFailure') -> 'SetSchemaResponse.Builder': ...
        def addMigrationFailures(self, collection: typing.Union[java.util.Collection['SetSchemaResponse.MigrationFailure'], typing.Sequence['SetSchemaResponse.MigrationFailure'], typing.Set['SetSchemaResponse.MigrationFailure']]) -> 'SetSchemaResponse.Builder': ...
        def build(self) -> 'SetSchemaResponse': ...
    class MigrationFailure(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def __init__(self, string: str, string2: str, string3: str, appSearchResult: AppSearchResult[typing.Any]): ...
        def describeContents(self) -> int: ...
        def getAppSearchResult(self) -> AppSearchResult[None]: ...
        def getDocumentId(self) -> str: ...
        def getNamespace(self) -> str: ...
        def getSchemaType(self) -> str: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StorageInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAliveDocumentsCount(self) -> int: ...
    def getAliveNamespacesCount(self) -> int: ...
    def getSizeBytes(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'StorageInfo': ...
        def setAliveDocumentsCount(self, int: int) -> 'StorageInfo.Builder': ...
        def setAliveNamespacesCount(self, int: int) -> 'StorageInfo.Builder': ...
        def setSizeBytes(self, long: int) -> 'StorageInfo.Builder': ...

class AppSearchSchema(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getParentTypes(self) -> java.util.List[str]: ...
    def getProperties(self) -> java.util.List['AppSearchSchema.PropertyConfig']: ...
    def getSchemaType(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class BooleanPropertyConfig(android.app.appsearch.AppSearchSchema.PropertyConfig):
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'AppSearchSchema.BooleanPropertyConfig': ...
            def setCardinality(self, int: int) -> 'AppSearchSchema.BooleanPropertyConfig.Builder': ...
    class Builder:
        def __init__(self, string: str): ...
        def addParentType(self, string: str) -> 'AppSearchSchema.Builder': ...
        def addProperty(self, propertyConfig: 'AppSearchSchema.PropertyConfig') -> 'AppSearchSchema.Builder': ...
        def build(self) -> 'AppSearchSchema': ...
    class BytesPropertyConfig(android.app.appsearch.AppSearchSchema.PropertyConfig):
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'AppSearchSchema.BytesPropertyConfig': ...
            def setCardinality(self, int: int) -> 'AppSearchSchema.BytesPropertyConfig.Builder': ...
    class DocumentPropertyConfig(android.app.appsearch.AppSearchSchema.PropertyConfig):
        def getIndexableNestedProperties(self) -> java.util.List[str]: ...
        def getSchemaType(self) -> str: ...
        def shouldIndexNestedProperties(self) -> bool: ...
        class Builder:
            def __init__(self, string: str, string2: str): ...
            @typing.overload
            def addIndexableNestedProperties(self, *string: str) -> 'AppSearchSchema.DocumentPropertyConfig.Builder': ...
            @typing.overload
            def addIndexableNestedProperties(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'AppSearchSchema.DocumentPropertyConfig.Builder': ...
            @typing.overload
            def addIndexableNestedPropertyPaths(self, *propertyPath: PropertyPath) -> 'AppSearchSchema.DocumentPropertyConfig.Builder': ...
            @typing.overload
            def addIndexableNestedPropertyPaths(self, collection: typing.Union[java.util.Collection[PropertyPath], typing.Sequence[PropertyPath], typing.Set[PropertyPath]]) -> 'AppSearchSchema.DocumentPropertyConfig.Builder': ...
            def build(self) -> 'AppSearchSchema.DocumentPropertyConfig': ...
            def setCardinality(self, int: int) -> 'AppSearchSchema.DocumentPropertyConfig.Builder': ...
            def setShouldIndexNestedProperties(self, boolean: bool) -> 'AppSearchSchema.DocumentPropertyConfig.Builder': ...
    class DoublePropertyConfig(android.app.appsearch.AppSearchSchema.PropertyConfig):
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'AppSearchSchema.DoublePropertyConfig': ...
            def setCardinality(self, int: int) -> 'AppSearchSchema.DoublePropertyConfig.Builder': ...
    class LongPropertyConfig(android.app.appsearch.AppSearchSchema.PropertyConfig):
        INDEXING_TYPE_NONE: typing.ClassVar[int] = ...
        INDEXING_TYPE_RANGE: typing.ClassVar[int] = ...
        def getIndexingType(self) -> int: ...
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'AppSearchSchema.LongPropertyConfig': ...
            def setCardinality(self, int: int) -> 'AppSearchSchema.LongPropertyConfig.Builder': ...
            def setIndexingType(self, int: int) -> 'AppSearchSchema.LongPropertyConfig.Builder': ...
    class PropertyConfig:
        CARDINALITY_OPTIONAL: typing.ClassVar[int] = ...
        CARDINALITY_REPEATED: typing.ClassVar[int] = ...
        CARDINALITY_REQUIRED: typing.ClassVar[int] = ...
        def equals(self, object: typing.Any) -> bool: ...
        def getCardinality(self) -> int: ...
        def getName(self) -> str: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
    class StringPropertyConfig(android.app.appsearch.AppSearchSchema.PropertyConfig):
        INDEXING_TYPE_EXACT_TERMS: typing.ClassVar[int] = ...
        INDEXING_TYPE_NONE: typing.ClassVar[int] = ...
        INDEXING_TYPE_PREFIXES: typing.ClassVar[int] = ...
        JOINABLE_VALUE_TYPE_NONE: typing.ClassVar[int] = ...
        JOINABLE_VALUE_TYPE_QUALIFIED_ID: typing.ClassVar[int] = ...
        TOKENIZER_TYPE_NONE: typing.ClassVar[int] = ...
        TOKENIZER_TYPE_PLAIN: typing.ClassVar[int] = ...
        TOKENIZER_TYPE_RFC822: typing.ClassVar[int] = ...
        TOKENIZER_TYPE_VERBATIM: typing.ClassVar[int] = ...
        def getIndexingType(self) -> int: ...
        def getJoinableValueType(self) -> int: ...
        def getTokenizerType(self) -> int: ...
        class Builder:
            def __init__(self, string: str): ...
            def build(self) -> 'AppSearchSchema.StringPropertyConfig': ...
            def setCardinality(self, int: int) -> 'AppSearchSchema.StringPropertyConfig.Builder': ...
            def setIndexingType(self, int: int) -> 'AppSearchSchema.StringPropertyConfig.Builder': ...
            def setJoinableValueType(self, int: int) -> 'AppSearchSchema.StringPropertyConfig.Builder': ...
            def setTokenizerType(self, int: int) -> 'AppSearchSchema.StringPropertyConfig.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.appsearch")``.

    AppSearchBatchResult: typing.Type[AppSearchBatchResult]
    AppSearchManager: typing.Type[AppSearchManager]
    AppSearchResult: typing.Type[AppSearchResult]
    AppSearchSchema: typing.Type[AppSearchSchema]
    AppSearchSession: typing.Type[AppSearchSession]
    BatchResultCallback: typing.Type[BatchResultCallback]
    EnterpriseGlobalSearchSession: typing.Type[EnterpriseGlobalSearchSession]
    GenericDocument: typing.Type[GenericDocument]
    GetByDocumentIdRequest: typing.Type[GetByDocumentIdRequest]
    GetSchemaResponse: typing.Type[GetSchemaResponse]
    GlobalSearchSession: typing.Type[GlobalSearchSession]
    JoinSpec: typing.Type[JoinSpec]
    Migrator: typing.Type[Migrator]
    PackageIdentifier: typing.Type[PackageIdentifier]
    PropertyPath: typing.Type[PropertyPath]
    PutDocumentsRequest: typing.Type[PutDocumentsRequest]
    RemoveByDocumentIdRequest: typing.Type[RemoveByDocumentIdRequest]
    ReportSystemUsageRequest: typing.Type[ReportSystemUsageRequest]
    ReportUsageRequest: typing.Type[ReportUsageRequest]
    SchemaVisibilityConfig: typing.Type[SchemaVisibilityConfig]
    SearchResult: typing.Type[SearchResult]
    SearchResults: typing.Type[SearchResults]
    SearchSpec: typing.Type[SearchSpec]
    SearchSuggestionResult: typing.Type[SearchSuggestionResult]
    SearchSuggestionSpec: typing.Type[SearchSuggestionSpec]
    SetSchemaRequest: typing.Type[SetSchemaRequest]
    SetSchemaResponse: typing.Type[SetSchemaResponse]
    StorageInfo: typing.Type[StorageInfo]
    exceptions: android.app.appsearch.exceptions.__module_protocol__
    observer: android.app.appsearch.observer.__module_protocol__
    util: android.app.appsearch.util.__module_protocol__
