
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import typing



class Effect:
    def __init__(self): ...
    def apply(self, int: int, int2: int, int3: int, int4: int) -> None: ...
    def getName(self) -> str: ...
    def release(self) -> None: ...
    def setParameter(self, string: str, object: typing.Any) -> None: ...
    def setUpdateListener(self, effectUpdateListener: typing.Union['EffectUpdateListener', typing.Callable]) -> None: ...

class EffectContext:
    @staticmethod
    def createWithCurrentGlContext() -> 'EffectContext': ...
    def getFactory(self) -> 'EffectFactory': ...
    def release(self) -> None: ...

class EffectFactory:
    EFFECT_AUTOFIX: typing.ClassVar[str] = ...
    EFFECT_BACKDROPPER: typing.ClassVar[str] = ...
    EFFECT_BITMAPOVERLAY: typing.ClassVar[str] = ...
    EFFECT_BLACKWHITE: typing.ClassVar[str] = ...
    EFFECT_BRIGHTNESS: typing.ClassVar[str] = ...
    EFFECT_CONTRAST: typing.ClassVar[str] = ...
    EFFECT_CROP: typing.ClassVar[str] = ...
    EFFECT_CROSSPROCESS: typing.ClassVar[str] = ...
    EFFECT_DOCUMENTARY: typing.ClassVar[str] = ...
    EFFECT_DUOTONE: typing.ClassVar[str] = ...
    EFFECT_FILLLIGHT: typing.ClassVar[str] = ...
    EFFECT_FISHEYE: typing.ClassVar[str] = ...
    EFFECT_FLIP: typing.ClassVar[str] = ...
    EFFECT_GRAIN: typing.ClassVar[str] = ...
    EFFECT_GRAYSCALE: typing.ClassVar[str] = ...
    EFFECT_LOMOISH: typing.ClassVar[str] = ...
    EFFECT_NEGATIVE: typing.ClassVar[str] = ...
    EFFECT_POSTERIZE: typing.ClassVar[str] = ...
    EFFECT_REDEYE: typing.ClassVar[str] = ...
    EFFECT_ROTATE: typing.ClassVar[str] = ...
    EFFECT_SATURATE: typing.ClassVar[str] = ...
    EFFECT_SEPIA: typing.ClassVar[str] = ...
    EFFECT_SHARPEN: typing.ClassVar[str] = ...
    EFFECT_STRAIGHTEN: typing.ClassVar[str] = ...
    EFFECT_TEMPERATURE: typing.ClassVar[str] = ...
    EFFECT_TINT: typing.ClassVar[str] = ...
    EFFECT_VIGNETTE: typing.ClassVar[str] = ...
    def createEffect(self, string: str) -> Effect: ...
    @staticmethod
    def isEffectSupported(string: str) -> bool: ...

class EffectUpdateListener:
    def onEffectUpdated(self, effect: Effect, object: typing.Any) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.effect")``.

    Effect: typing.Type[Effect]
    EffectContext: typing.Type[EffectContext]
    EffectFactory: typing.Type[EffectFactory]
    EffectUpdateListener: typing.Type[EffectUpdateListener]
