
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.graphics.fonts
import android.os
import java.lang
import jpype
import typing



class LineBreakConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    HYPHENATION_DISABLED: typing.ClassVar[int] = ...
    HYPHENATION_ENABLED: typing.ClassVar[int] = ...
    HYPHENATION_UNSPECIFIED: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_AUTO: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_LOOSE: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_NONE: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_NORMAL: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_NO_BREAK: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_STRICT: typing.ClassVar[int] = ...
    LINE_BREAK_STYLE_UNSPECIFIED: typing.ClassVar[int] = ...
    LINE_BREAK_WORD_STYLE_AUTO: typing.ClassVar[int] = ...
    LINE_BREAK_WORD_STYLE_NONE: typing.ClassVar[int] = ...
    LINE_BREAK_WORD_STYLE_PHRASE: typing.ClassVar[int] = ...
    LINE_BREAK_WORD_STYLE_UNSPECIFIED: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHyphenation(self) -> int: ...
    def getLineBreakStyle(self) -> int: ...
    def getLineBreakWordStyle(self) -> int: ...
    def hashCode(self) -> int: ...
    def merge(self, lineBreakConfig: 'LineBreakConfig') -> 'LineBreakConfig': ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'LineBreakConfig': ...
        def merge(self, lineBreakConfig: 'LineBreakConfig') -> 'LineBreakConfig.Builder': ...
        def setHyphenation(self, int: int) -> 'LineBreakConfig.Builder': ...
        def setLineBreakStyle(self, int: int) -> 'LineBreakConfig.Builder': ...
        def setLineBreakWordStyle(self, int: int) -> 'LineBreakConfig.Builder': ...

class LineBreaker:
    BREAK_STRATEGY_BALANCED: typing.ClassVar[int] = ...
    BREAK_STRATEGY_HIGH_QUALITY: typing.ClassVar[int] = ...
    BREAK_STRATEGY_SIMPLE: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_FULL: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_NONE: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_NORMAL: typing.ClassVar[int] = ...
    JUSTIFICATION_MODE_INTER_CHARACTER: typing.ClassVar[int] = ...
    JUSTIFICATION_MODE_INTER_WORD: typing.ClassVar[int] = ...
    JUSTIFICATION_MODE_NONE: typing.ClassVar[int] = ...
    def computeLineBreaks(self, measuredText: 'MeasuredText', paragraphConstraints: 'LineBreaker.ParagraphConstraints', int: int) -> 'LineBreaker.Result': ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'LineBreaker': ...
        def setBreakStrategy(self, int: int) -> 'LineBreaker.Builder': ...
        def setHyphenationFrequency(self, int: int) -> 'LineBreaker.Builder': ...
        def setIndents(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'LineBreaker.Builder': ...
        def setJustificationMode(self, int: int) -> 'LineBreaker.Builder': ...
        def setUseBoundsForWidth(self, boolean: bool) -> 'LineBreaker.Builder': ...
    class ParagraphConstraints:
        def __init__(self): ...
        def getDefaultTabStop(self) -> float: ...
        def getFirstWidth(self) -> float: ...
        def getFirstWidthLineCount(self) -> int: ...
        def getTabStops(self) -> typing.MutableSequence[float]: ...
        def getWidth(self) -> float: ...
        def setIndent(self, float: float, int: int) -> None: ...
        def setTabStops(self, floatArray: typing.Union[typing.List[float], jpype.JArray], float2: float) -> None: ...
        def setWidth(self, float: float) -> None: ...
    class Result:
        def getEndLineHyphenEdit(self, int: int) -> int: ...
        def getLineAscent(self, int: int) -> float: ...
        def getLineBreakOffset(self, int: int) -> int: ...
        def getLineCount(self) -> int: ...
        def getLineDescent(self, int: int) -> float: ...
        def getLineWidth(self, int: int) -> float: ...
        def getStartLineHyphenEdit(self, int: int) -> int: ...
        def hasLineTab(self, int: int) -> bool: ...

class MeasuredText:
    def getBounds(self, int: int, int2: int, rect: android.graphics.Rect) -> None: ...
    def getCharWidthAt(self, int: int) -> float: ...
    def getFontMetricsInt(self, int: int, int2: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...
    def getWidth(self, int: int, int2: int) -> float: ...
    class Builder:
        HYPHENATION_MODE_FAST: typing.ClassVar[int] = ...
        HYPHENATION_MODE_NONE: typing.ClassVar[int] = ...
        HYPHENATION_MODE_NORMAL: typing.ClassVar[int] = ...
        @typing.overload
        def __init__(self, measuredText: 'MeasuredText'): ...
        @typing.overload
        def __init__(self, charArray: typing.Union[typing.List[str], jpype.JArray]): ...
        def appendReplacementRun(self, paint: android.graphics.Paint, int: int, float: float) -> 'MeasuredText.Builder': ...
        @typing.overload
        def appendStyleRun(self, paint: android.graphics.Paint, lineBreakConfig: LineBreakConfig, int: int, boolean: bool) -> 'MeasuredText.Builder': ...
        @typing.overload
        def appendStyleRun(self, paint: android.graphics.Paint, int: int, boolean: bool) -> 'MeasuredText.Builder': ...
        def build(self) -> 'MeasuredText': ...
        @typing.overload
        def setComputeHyphenation(self, boolean: bool) -> 'MeasuredText.Builder': ...
        @typing.overload
        def setComputeHyphenation(self, int: int) -> 'MeasuredText.Builder': ...
        def setComputeLayout(self, boolean: bool) -> 'MeasuredText.Builder': ...

class PositionedGlyphs:
    NO_OVERRIDE: typing.ClassVar[float] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdvance(self) -> float: ...
    def getAscent(self) -> float: ...
    def getDescent(self) -> float: ...
    def getFakeBold(self, int: int) -> bool: ...
    def getFakeItalic(self, int: int) -> bool: ...
    def getFont(self, int: int) -> android.graphics.fonts.Font: ...
    def getGlyphId(self, int: int) -> int: ...
    def getGlyphX(self, int: int) -> float: ...
    def getGlyphY(self, int: int) -> float: ...
    def getItalicOverride(self, int: int) -> float: ...
    def getOffsetX(self) -> float: ...
    def getOffsetY(self) -> float: ...
    def getWeightOverride(self, int: int) -> float: ...
    def glyphCount(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TextRunShaper:
    @typing.overload
    @staticmethod
    def shapeTextRun(charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int, int3: int, int4: int, float: float, float2: float, boolean: bool, paint: android.graphics.Paint) -> PositionedGlyphs: ...
    @typing.overload
    @staticmethod
    def shapeTextRun(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, float: float, float2: float, boolean: bool, paint: android.graphics.Paint) -> PositionedGlyphs: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.graphics.text")``.

    LineBreakConfig: typing.Type[LineBreakConfig]
    LineBreaker: typing.Type[LineBreaker]
    MeasuredText: typing.Type[MeasuredText]
    PositionedGlyphs: typing.Type[PositionedGlyphs]
    TextRunShaper: typing.Type[TextRunShaper]
