
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.content.pm
import android.graphics.drawable
import android.os
import java.lang
import java.util
import java.util.concurrent
import jpype
import typing



class SentenceSuggestionsInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, suggestionsInfoArray: typing.Union[typing.List['SuggestionsInfo'], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]): ...
    def describeContents(self) -> int: ...
    def getLengthAt(self, int: int) -> int: ...
    def getOffsetAt(self, int: int) -> int: ...
    def getSuggestionsCount(self) -> int: ...
    def getSuggestionsInfoAt(self, int: int) -> 'SuggestionsInfo': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SpellCheckerInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getComponent(self) -> android.content.ComponentName: ...
    def getId(self) -> str: ...
    def getPackageName(self) -> str: ...
    def getServiceInfo(self) -> android.content.pm.ServiceInfo: ...
    def getSettingsActivity(self) -> str: ...
    def getSubtypeAt(self, int: int) -> 'SpellCheckerSubtype': ...
    def getSubtypeCount(self) -> int: ...
    def loadIcon(self, packageManager: android.content.pm.PackageManager) -> android.graphics.drawable.Drawable: ...
    def loadLabel(self, packageManager: android.content.pm.PackageManager) -> java.lang.CharSequence: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SpellCheckerSession:
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
    def getSentenceSuggestions(self, textInfoArray: typing.Union[typing.List['TextInfo'], jpype.JArray], int: int) -> None: ...
    def getSpellChecker(self) -> SpellCheckerInfo: ...
    @typing.overload
    def getSuggestions(self, textInfo: 'TextInfo', int: int) -> None: ...
    @typing.overload
    def getSuggestions(self, textInfoArray: typing.Union[typing.List['TextInfo'], jpype.JArray], int: int, boolean: bool) -> None: ...
    def isSessionDisconnected(self) -> bool: ...
    class SpellCheckerSessionListener:
        def onGetSentenceSuggestions(self, sentenceSuggestionsInfoArray: typing.Union[typing.List[SentenceSuggestionsInfo], jpype.JArray]) -> None: ...
        def onGetSuggestions(self, suggestionsInfoArray: typing.Union[typing.List['SuggestionsInfo'], jpype.JArray]) -> None: ...
    class SpellCheckerSessionParams:
        def getExtras(self) -> android.os.Bundle: ...
        def getLocale(self) -> java.util.Locale: ...
        def getSupportedAttributes(self) -> int: ...
        def shouldReferToSpellCheckerLanguageSettings(self) -> bool: ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'SpellCheckerSession.SpellCheckerSessionParams': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'SpellCheckerSession.SpellCheckerSessionParams.Builder': ...
            def setLocale(self, locale: java.util.Locale) -> 'SpellCheckerSession.SpellCheckerSessionParams.Builder': ...
            def setShouldReferToSpellCheckerLanguageSettings(self, boolean: bool) -> 'SpellCheckerSession.SpellCheckerSessionParams.Builder': ...
            def setSupportedAttributes(self, int: int) -> 'SpellCheckerSession.SpellCheckerSessionParams.Builder': ...

class SpellCheckerSubtype(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, string: str, string2: str): ...
    def containsExtraValueKey(self, string: str) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDisplayName(self, context: android.content.Context, string: str, applicationInfo: android.content.pm.ApplicationInfo) -> java.lang.CharSequence: ...
    def getExtraValue(self) -> str: ...
    def getExtraValueOf(self, string: str) -> str: ...
    def getLanguageTag(self) -> str: ...
    def getLocale(self) -> str: ...
    def getNameResId(self) -> int: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SuggestionsInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RESULT_ATTR_DONT_SHOW_UI_FOR_SUGGESTIONS: typing.ClassVar[int] = ...
    RESULT_ATTR_HAS_RECOMMENDED_SUGGESTIONS: typing.ClassVar[int] = ...
    RESULT_ATTR_IN_THE_DICTIONARY: typing.ClassVar[int] = ...
    RESULT_ATTR_LOOKS_LIKE_GRAMMAR_ERROR: typing.ClassVar[int] = ...
    RESULT_ATTR_LOOKS_LIKE_TYPO: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int, stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    @typing.overload
    def __init__(self, int: int, stringArray: typing.Union[typing.List[str], jpype.JArray], int2: int, int3: int): ...
    def describeContents(self) -> int: ...
    def getCookie(self) -> int: ...
    def getSequence(self) -> int: ...
    def getSuggestionAt(self, int: int) -> str: ...
    def getSuggestionsAttributes(self) -> int: ...
    def getSuggestionsCount(self) -> int: ...
    def setCookieAndSequence(self, int: int, int2: int) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TextInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def getCharSequence(self) -> java.lang.CharSequence: ...
    def getCookie(self) -> int: ...
    def getSequence(self) -> int: ...
    def getText(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TextServicesManager:
    def getCurrentSpellCheckerInfo(self) -> SpellCheckerInfo: ...
    def getEnabledSpellCheckerInfos(self) -> java.util.List[SpellCheckerInfo]: ...
    def isSpellCheckerEnabled(self) -> bool: ...
    @typing.overload
    def newSpellCheckerSession(self, bundle: android.os.Bundle, locale: java.util.Locale, spellCheckerSessionListener: SpellCheckerSession.SpellCheckerSessionListener, boolean: bool) -> SpellCheckerSession: ...
    @typing.overload
    def newSpellCheckerSession(self, spellCheckerSessionParams: SpellCheckerSession.SpellCheckerSessionParams, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], spellCheckerSessionListener: SpellCheckerSession.SpellCheckerSessionListener) -> SpellCheckerSession: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.textservice")``.

    SentenceSuggestionsInfo: typing.Type[SentenceSuggestionsInfo]
    SpellCheckerInfo: typing.Type[SpellCheckerInfo]
    SpellCheckerSession: typing.Type[SpellCheckerSession]
    SpellCheckerSubtype: typing.Type[SpellCheckerSubtype]
    SuggestionsInfo: typing.Type[SuggestionsInfo]
    TextInfo: typing.Type[TextInfo]
    TextServicesManager: typing.Type[TextServicesManager]
