
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import _jpype
import android.content
import android.graphics
import android.util
import android.view
import java.lang
import java.util
import jpype
import typing



class Animator(java.lang.Cloneable):
    DURATION_INFINITE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addListener(self, animatorListener: 'Animator.AnimatorListener') -> None: ...
    def addPauseListener(self, animatorPauseListener: 'Animator.AnimatorPauseListener') -> None: ...
    def cancel(self) -> None: ...
    def clone(self) -> 'Animator': ...
    def end(self) -> None: ...
    def getDuration(self) -> int: ...
    def getInterpolator(self) -> 'TimeInterpolator': ...
    def getListeners(self) -> java.util.ArrayList['Animator.AnimatorListener']: ...
    def getStartDelay(self) -> int: ...
    def getTotalDuration(self) -> int: ...
    def isPaused(self) -> bool: ...
    def isRunning(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def pause(self) -> None: ...
    def removeAllListeners(self) -> None: ...
    def removeListener(self, animatorListener: 'Animator.AnimatorListener') -> None: ...
    def removePauseListener(self, animatorPauseListener: 'Animator.AnimatorPauseListener') -> None: ...
    def resume(self) -> None: ...
    def setDuration(self, long: int) -> 'Animator': ...
    def setInterpolator(self, timeInterpolator: typing.Union['TimeInterpolator', typing.Callable]) -> None: ...
    def setStartDelay(self, long: int) -> None: ...
    def setTarget(self, object: typing.Any) -> None: ...
    def setupEndValues(self) -> None: ...
    def setupStartValues(self) -> None: ...
    def start(self) -> None: ...
    class AnimatorListener:
        def onAnimationCancel(self, animator: 'Animator') -> None: ...
        @typing.overload
        def onAnimationEnd(self, animator: 'Animator') -> None: ...
        @typing.overload
        def onAnimationEnd(self, animator: 'Animator', boolean: bool) -> None: ...
        def onAnimationRepeat(self, animator: 'Animator') -> None: ...
        @typing.overload
        def onAnimationStart(self, animator: 'Animator') -> None: ...
        @typing.overload
        def onAnimationStart(self, animator: 'Animator', boolean: bool) -> None: ...
    class AnimatorPauseListener:
        def onAnimationPause(self, animator: 'Animator') -> None: ...
        def onAnimationResume(self, animator: 'Animator') -> None: ...

class AnimatorInflater:
    def __init__(self): ...
    @staticmethod
    def loadAnimator(context: android.content.Context, int: int) -> Animator: ...
    @staticmethod
    def loadStateListAnimator(context: android.content.Context, int: int) -> 'StateListAnimator': ...

class Keyframe(java.lang.Cloneable):
    def __init__(self): ...
    def clone(self) -> 'Keyframe': ...
    def getFraction(self) -> float: ...
    def getInterpolator(self) -> 'TimeInterpolator': ...
    def getType(self) -> typing.Type: ...
    def getValue(self) -> typing.Any: ...
    def hasValue(self) -> bool: ...
    @typing.overload
    @staticmethod
    def ofFloat(float: float) -> 'Keyframe': ...
    @typing.overload
    @staticmethod
    def ofFloat(float: float, float2: float) -> 'Keyframe': ...
    @typing.overload
    @staticmethod
    def ofInt(float: float) -> 'Keyframe': ...
    @typing.overload
    @staticmethod
    def ofInt(float: float, int: int) -> 'Keyframe': ...
    @typing.overload
    @staticmethod
    def ofObject(float: float) -> 'Keyframe': ...
    @typing.overload
    @staticmethod
    def ofObject(float: float, object: typing.Any) -> 'Keyframe': ...
    def setFraction(self, float: float) -> None: ...
    def setInterpolator(self, timeInterpolator: typing.Union['TimeInterpolator', typing.Callable]) -> None: ...
    def setValue(self, object: typing.Any) -> None: ...

class LayoutTransition:
    APPEARING: typing.ClassVar[int] = ...
    CHANGE_APPEARING: typing.ClassVar[int] = ...
    CHANGE_DISAPPEARING: typing.ClassVar[int] = ...
    CHANGING: typing.ClassVar[int] = ...
    DISAPPEARING: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addChild(self, viewGroup: android.view.ViewGroup, view2: android.view.View) -> None: ...
    def addTransitionListener(self, transitionListener: 'LayoutTransition.TransitionListener') -> None: ...
    def disableTransitionType(self, int: int) -> None: ...
    def enableTransitionType(self, int: int) -> None: ...
    def getAnimator(self, int: int) -> Animator: ...
    def getDuration(self, int: int) -> int: ...
    def getInterpolator(self, int: int) -> 'TimeInterpolator': ...
    def getStagger(self, int: int) -> int: ...
    def getStartDelay(self, int: int) -> int: ...
    def getTransitionListeners(self) -> java.util.List['LayoutTransition.TransitionListener']: ...
    @typing.overload
    def hideChild(self, viewGroup: android.view.ViewGroup, view2: android.view.View) -> None: ...
    @typing.overload
    def hideChild(self, viewGroup: android.view.ViewGroup, view2: android.view.View, int: int) -> None: ...
    def isChangingLayout(self) -> bool: ...
    def isRunning(self) -> bool: ...
    def isTransitionTypeEnabled(self, int: int) -> bool: ...
    def removeChild(self, viewGroup: android.view.ViewGroup, view2: android.view.View) -> None: ...
    def removeTransitionListener(self, transitionListener: 'LayoutTransition.TransitionListener') -> None: ...
    def setAnimateParentHierarchy(self, boolean: bool) -> None: ...
    def setAnimator(self, int: int, animator: Animator) -> None: ...
    @typing.overload
    def setDuration(self, int: int, long: int) -> None: ...
    @typing.overload
    def setDuration(self, long: int) -> None: ...
    def setInterpolator(self, int: int, timeInterpolator: typing.Union['TimeInterpolator', typing.Callable]) -> None: ...
    def setStagger(self, int: int, long: int) -> None: ...
    def setStartDelay(self, int: int, long: int) -> None: ...
    @typing.overload
    def showChild(self, viewGroup: android.view.ViewGroup, view2: android.view.View) -> None: ...
    @typing.overload
    def showChild(self, viewGroup: android.view.ViewGroup, view2: android.view.View, int: int) -> None: ...
    class TransitionListener:
        def endTransition(self, layoutTransition: 'LayoutTransition', viewGroup: android.view.ViewGroup, view2: android.view.View, int: int) -> None: ...
        def startTransition(self, layoutTransition: 'LayoutTransition', viewGroup: android.view.ViewGroup, view2: android.view.View, int: int) -> None: ...

class PropertyValuesHolder(java.lang.Cloneable):
    def clone(self) -> 'PropertyValuesHolder': ...
    def getPropertyName(self) -> str: ...
    @typing.overload
    @staticmethod
    def ofFloat(property: android.util.Property[typing.Any, float], *float: float) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofFloat(string: str, *float: float) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofInt(property: android.util.Property[typing.Any, int], *int: int) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofInt(string: str, *int: int) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofKeyframe(property: android.util.Property, *keyframe: Keyframe) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofKeyframe(string: str, *keyframe: Keyframe) -> 'PropertyValuesHolder': ...
    _ofMultiFloat_0__T = typing.TypeVar('_ofMultiFloat_0__T')  # <T>
    _ofMultiFloat_1__V = typing.TypeVar('_ofMultiFloat_1__V')  # <V>
    @typing.overload
    @staticmethod
    def ofMultiFloat(string: str, typeConverter: 'TypeConverter'[_ofMultiFloat_0__T, typing.Union[typing.List[float], jpype.JArray]], typeEvaluator: typing.Union['TypeEvaluator'[_ofMultiFloat_0__T], typing.Callable[[float, _ofMultiFloat_0__T, _ofMultiFloat_0__T], _ofMultiFloat_0__T]], *keyframe: Keyframe) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofMultiFloat(string: str, typeConverter: 'TypeConverter'[_ofMultiFloat_1__V, typing.Union[typing.List[float], jpype.JArray]], typeEvaluator: typing.Union['TypeEvaluator'[_ofMultiFloat_1__V], typing.Callable[[float, _ofMultiFloat_1__V, _ofMultiFloat_1__V], _ofMultiFloat_1__V]], *v: _ofMultiFloat_1__V) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofMultiFloat(string: str, path: android.graphics.Path) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofMultiFloat(string: str, floatArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> 'PropertyValuesHolder': ...
    _ofMultiInt_0__T = typing.TypeVar('_ofMultiInt_0__T')  # <T>
    _ofMultiInt_1__V = typing.TypeVar('_ofMultiInt_1__V')  # <V>
    @typing.overload
    @staticmethod
    def ofMultiInt(string: str, typeConverter: 'TypeConverter'[_ofMultiInt_0__T, typing.Union[typing.List[int], jpype.JArray]], typeEvaluator: typing.Union['TypeEvaluator'[_ofMultiInt_0__T], typing.Callable[[float, _ofMultiInt_0__T, _ofMultiInt_0__T], _ofMultiInt_0__T]], *keyframe: Keyframe) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofMultiInt(string: str, typeConverter: 'TypeConverter'[_ofMultiInt_1__V, typing.Union[typing.List[int], jpype.JArray]], typeEvaluator: typing.Union['TypeEvaluator'[_ofMultiInt_1__V], typing.Callable[[float, _ofMultiInt_1__V, _ofMultiInt_1__V], _ofMultiInt_1__V]], *v: _ofMultiInt_1__V) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofMultiInt(string: str, path: android.graphics.Path) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofMultiInt(string: str, intArray: typing.Union[typing.List[typing.MutableSequence[int]], jpype.JArray]) -> 'PropertyValuesHolder': ...
    _ofObject_0__T = typing.TypeVar('_ofObject_0__T')  # <T>
    _ofObject_0__V = typing.TypeVar('_ofObject_0__V')  # <V>
    _ofObject_1__V = typing.TypeVar('_ofObject_1__V')  # <V>
    _ofObject_2__V = typing.TypeVar('_ofObject_2__V')  # <V>
    @typing.overload
    @staticmethod
    def ofObject(property: android.util.Property[typing.Any, _ofObject_0__V], typeConverter: 'TypeConverter'[_ofObject_0__T, _ofObject_0__V], typeEvaluator: typing.Union['TypeEvaluator'[_ofObject_0__T], typing.Callable[[float, _ofObject_0__T, _ofObject_0__T], _ofObject_0__T]], *t3: _ofObject_0__T) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofObject(property: android.util.Property[typing.Any, _ofObject_1__V], typeConverter: 'TypeConverter'[android.graphics.PointF, _ofObject_1__V], path: android.graphics.Path) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofObject(property: android.util.Property, typeEvaluator: typing.Union['TypeEvaluator'[_ofObject_2__V], typing.Callable[[float, _ofObject_2__V, _ofObject_2__V], _ofObject_2__V]], *v: _ofObject_2__V) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofObject(string: str, typeConverter: 'TypeConverter'[android.graphics.PointF, typing.Any], path: android.graphics.Path) -> 'PropertyValuesHolder': ...
    @typing.overload
    @staticmethod
    def ofObject(string: str, typeEvaluator: typing.Union['TypeEvaluator', typing.Callable], *object: typing.Any) -> 'PropertyValuesHolder': ...
    def setConverter(self, typeConverter: 'TypeConverter') -> None: ...
    def setEvaluator(self, typeEvaluator: typing.Union['TypeEvaluator', typing.Callable]) -> None: ...
    def setFloatValues(self, *float: float) -> None: ...
    def setIntValues(self, *int: int) -> None: ...
    def setKeyframes(self, *keyframe: Keyframe) -> None: ...
    def setObjectValues(self, *object: typing.Any) -> None: ...
    def setProperty(self, property: android.util.Property) -> None: ...
    def setPropertyName(self, string: str) -> None: ...
    def toString(self) -> str: ...

class StateListAnimator(java.lang.Cloneable):
    def __init__(self): ...
    def addState(self, intArray: typing.Union[typing.List[int], jpype.JArray], animator: Animator) -> None: ...
    def clone(self) -> 'StateListAnimator': ...
    def jumpToCurrentState(self) -> None: ...

class TimeInterpolator:
    def getInterpolation(self, float: float) -> float: ...

_TypeConverter__T = typing.TypeVar('_TypeConverter__T')  # <T>
_TypeConverter__V = typing.TypeVar('_TypeConverter__V')  # <V>
class TypeConverter(typing.Generic[_TypeConverter__T, _TypeConverter__V]):
    def __init__(self, class_: typing.Type[_TypeConverter__T], class2: typing.Type[_TypeConverter__V]): ...
    def convert(self, t: _TypeConverter__T) -> _TypeConverter__V: ...

_TypeEvaluator__T = typing.TypeVar('_TypeEvaluator__T')  # <T>
class TypeEvaluator(typing.Generic[_TypeEvaluator__T]):
    def evaluate(self, float: float, t: _TypeEvaluator__T, t2: _TypeEvaluator__T) -> _TypeEvaluator__T: ...

class AnimatorListenerAdapter(Animator.AnimatorListener, Animator.AnimatorPauseListener):
    def __init__(self): ...
    def onAnimationCancel(self, animator: Animator) -> None: ...
    @typing.overload
    def onAnimationEnd(self, animator: Animator, boolean: bool) -> None: ...
    @typing.overload
    def onAnimationEnd(self, animator: Animator) -> None: ...
    def onAnimationPause(self, animator: Animator) -> None: ...
    def onAnimationRepeat(self, animator: Animator) -> None: ...
    def onAnimationResume(self, animator: Animator) -> None: ...
    @typing.overload
    def onAnimationStart(self, animator: Animator, boolean: bool) -> None: ...
    @typing.overload
    def onAnimationStart(self, animator: Animator) -> None: ...

class AnimatorSet(Animator):
    def __init__(self): ...
    def cancel(self) -> None: ...
    def clone(self) -> 'AnimatorSet': ...
    def end(self) -> None: ...
    def getChildAnimations(self) -> java.util.ArrayList[Animator]: ...
    def getCurrentPlayTime(self) -> int: ...
    def getDuration(self) -> int: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def getStartDelay(self) -> int: ...
    def getTotalDuration(self) -> int: ...
    def isRunning(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def pause(self) -> None: ...
    def play(self, animator: Animator) -> 'AnimatorSet.Builder': ...
    @typing.overload
    def playSequentially(self, *animator: Animator) -> None: ...
    @typing.overload
    def playSequentially(self, list: java.util.List[Animator]) -> None: ...
    @typing.overload
    def playTogether(self, *animator: Animator) -> None: ...
    @typing.overload
    def playTogether(self, collection: typing.Union[java.util.Collection[Animator], typing.Sequence[Animator], typing.Set[Animator]]) -> None: ...
    def resume(self) -> None: ...
    def reverse(self) -> None: ...
    def setCurrentPlayTime(self, long: int) -> None: ...
    def setDuration(self, long: int) -> 'AnimatorSet': ...
    def setInterpolator(self, timeInterpolator: typing.Union[TimeInterpolator, typing.Callable]) -> None: ...
    def setStartDelay(self, long: int) -> None: ...
    def setTarget(self, object: typing.Any) -> None: ...
    def setupEndValues(self) -> None: ...
    def setupStartValues(self) -> None: ...
    def start(self) -> None: ...
    def toString(self) -> str: ...
    class Builder:
        @typing.overload
        def after(self, animator: Animator) -> 'AnimatorSet.Builder': ...
        @typing.overload
        def after(self, long: int) -> 'AnimatorSet.Builder': ...
        def before(self, animator: Animator) -> 'AnimatorSet.Builder': ...
        def with_(self, animator: Animator) -> 'AnimatorSet.Builder': ...

class ArgbEvaluator(TypeEvaluator):
    def __init__(self): ...
    def evaluate(self, float: float, object: typing.Any, object2: typing.Any) -> typing.Any: ...

_BidirectionalTypeConverter__T = typing.TypeVar('_BidirectionalTypeConverter__T')  # <T>
_BidirectionalTypeConverter__V = typing.TypeVar('_BidirectionalTypeConverter__V')  # <V>
class BidirectionalTypeConverter(TypeConverter[_BidirectionalTypeConverter__T, _BidirectionalTypeConverter__V], typing.Generic[_BidirectionalTypeConverter__T, _BidirectionalTypeConverter__V]):
    def __init__(self, class_: typing.Type[_BidirectionalTypeConverter__T], class2: typing.Type[_BidirectionalTypeConverter__V]): ...
    def convertBack(self, v: _BidirectionalTypeConverter__V) -> _BidirectionalTypeConverter__T: ...
    def invert(self) -> 'BidirectionalTypeConverter'[_BidirectionalTypeConverter__V, _BidirectionalTypeConverter__T]: ...

class FloatArrayEvaluator(TypeEvaluator[typing.MutableSequence[float]]):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, floatArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, float: float, floatArray: typing.Union[typing.List[float], jpype.JArray], floatArray2: typing.Union[typing.List[float], jpype.JArray]) -> typing.MutableSequence[float]: ...

class FloatEvaluator(TypeEvaluator[java.lang.Number]):
    def __init__(self): ...
    def evaluate(self, float: float, number: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat], number2: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat]) -> float: ...

class IntArrayEvaluator(TypeEvaluator[typing.MutableSequence[int]]):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, intArray: typing.Union[typing.List[int], jpype.JArray]): ...
    def evaluate(self, float: float, intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]) -> typing.MutableSequence[int]: ...

class IntEvaluator(TypeEvaluator[int]):
    def __init__(self): ...
    def evaluate(self, float: float, integer: int, integer2: int) -> int: ...

class PointFEvaluator(TypeEvaluator[android.graphics.PointF]):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pointF: android.graphics.PointF): ...
    def evaluate(self, float: float, pointF: android.graphics.PointF, pointF2: android.graphics.PointF) -> android.graphics.PointF: ...

class RectEvaluator(TypeEvaluator[android.graphics.Rect]):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, rect: android.graphics.Rect): ...
    def evaluate(self, float: float, rect: android.graphics.Rect, rect2: android.graphics.Rect) -> android.graphics.Rect: ...

class ValueAnimator(Animator):
    INFINITE: typing.ClassVar[int] = ...
    RESTART: typing.ClassVar[int] = ...
    REVERSE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addUpdateListener(self, animatorUpdateListener: typing.Union['ValueAnimator.AnimatorUpdateListener', typing.Callable]) -> None: ...
    @staticmethod
    def areAnimatorsEnabled() -> bool: ...
    def cancel(self) -> None: ...
    def clone(self) -> 'ValueAnimator': ...
    def end(self) -> None: ...
    def getAnimatedFraction(self) -> float: ...
    @typing.overload
    def getAnimatedValue(self) -> typing.Any: ...
    @typing.overload
    def getAnimatedValue(self, string: str) -> typing.Any: ...
    def getCurrentPlayTime(self) -> int: ...
    def getDuration(self) -> int: ...
    @staticmethod
    def getDurationScale() -> float: ...
    @staticmethod
    def getFrameDelay() -> int: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def getRepeatCount(self) -> int: ...
    def getRepeatMode(self) -> int: ...
    def getStartDelay(self) -> int: ...
    def getTotalDuration(self) -> int: ...
    def getValues(self) -> typing.MutableSequence[PropertyValuesHolder]: ...
    def isRunning(self) -> bool: ...
    def isStarted(self) -> bool: ...
    @staticmethod
    def ofArgb(*int: int) -> 'ValueAnimator': ...
    @staticmethod
    def ofFloat(*float: float) -> 'ValueAnimator': ...
    @staticmethod
    def ofInt(*int: int) -> 'ValueAnimator': ...
    @staticmethod
    def ofObject(typeEvaluator: typing.Union[TypeEvaluator, typing.Callable], *object: typing.Any) -> 'ValueAnimator': ...
    @staticmethod
    def ofPropertyValuesHolder(*propertyValuesHolder: PropertyValuesHolder) -> 'ValueAnimator': ...
    def pause(self) -> None: ...
    @staticmethod
    def registerDurationScaleChangeListener(durationScaleChangeListener: typing.Union['ValueAnimator.DurationScaleChangeListener', typing.Callable]) -> bool: ...
    def removeAllUpdateListeners(self) -> None: ...
    def removeUpdateListener(self, animatorUpdateListener: typing.Union['ValueAnimator.AnimatorUpdateListener', typing.Callable]) -> None: ...
    def resume(self) -> None: ...
    def reverse(self) -> None: ...
    def setCurrentFraction(self, float: float) -> None: ...
    def setCurrentPlayTime(self, long: int) -> None: ...
    def setDuration(self, long: int) -> 'ValueAnimator': ...
    def setEvaluator(self, typeEvaluator: typing.Union[TypeEvaluator, typing.Callable]) -> None: ...
    def setFloatValues(self, *float: float) -> None: ...
    @staticmethod
    def setFrameDelay(long: int) -> None: ...
    def setIntValues(self, *int: int) -> None: ...
    def setInterpolator(self, timeInterpolator: typing.Union[TimeInterpolator, typing.Callable]) -> None: ...
    def setObjectValues(self, *object: typing.Any) -> None: ...
    def setRepeatCount(self, int: int) -> None: ...
    def setRepeatMode(self, int: int) -> None: ...
    def setStartDelay(self, long: int) -> None: ...
    def setValues(self, *propertyValuesHolder: PropertyValuesHolder) -> None: ...
    def start(self) -> None: ...
    def toString(self) -> str: ...
    @staticmethod
    def unregisterDurationScaleChangeListener(durationScaleChangeListener: typing.Union['ValueAnimator.DurationScaleChangeListener', typing.Callable]) -> bool: ...
    class AnimatorUpdateListener:
        def onAnimationUpdate(self, valueAnimator: 'ValueAnimator') -> None: ...
    class DurationScaleChangeListener:
        def onChanged(self, float: float) -> None: ...

class ObjectAnimator(ValueAnimator):
    def __init__(self): ...
    def clone(self) -> 'ObjectAnimator': ...
    def getPropertyName(self) -> str: ...
    def getTarget(self) -> typing.Any: ...
    _ofArgb_0__T = typing.TypeVar('_ofArgb_0__T')  # <T>
    @typing.overload
    @staticmethod
    def ofArgb(t: _ofArgb_0__T, property: android.util.Property[_ofArgb_0__T, int], *int: int) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofArgb(object: typing.Any, string: str, *int: int) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofArgb(*int: int) -> ValueAnimator: ...
    _ofFloat_0__T = typing.TypeVar('_ofFloat_0__T')  # <T>
    _ofFloat_1__T = typing.TypeVar('_ofFloat_1__T')  # <T>
    @typing.overload
    @staticmethod
    def ofFloat(t: _ofFloat_0__T, property: android.util.Property[_ofFloat_0__T, float], property2: android.util.Property[_ofFloat_0__T, float], path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofFloat(t: _ofFloat_1__T, property: android.util.Property[_ofFloat_1__T, float], *float: float) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofFloat(object: typing.Any, string: str, *float: float) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofFloat(object: typing.Any, string: str, string2: str, path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofFloat(*float: float) -> ValueAnimator: ...
    _ofInt_0__T = typing.TypeVar('_ofInt_0__T')  # <T>
    _ofInt_1__T = typing.TypeVar('_ofInt_1__T')  # <T>
    @typing.overload
    @staticmethod
    def ofInt(t: _ofInt_0__T, property: android.util.Property[_ofInt_0__T, int], property2: android.util.Property[_ofInt_0__T, int], path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofInt(t: _ofInt_1__T, property: android.util.Property[_ofInt_1__T, int], *int: int) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofInt(object: typing.Any, string: str, *int: int) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofInt(object: typing.Any, string: str, string2: str, path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofInt(*int: int) -> ValueAnimator: ...
    _ofMultiFloat_0__T = typing.TypeVar('_ofMultiFloat_0__T')  # <T>
    @typing.overload
    @staticmethod
    def ofMultiFloat(object: typing.Any, string: str, typeConverter: TypeConverter[_ofMultiFloat_0__T, typing.Union[typing.List[float], jpype.JArray]], typeEvaluator: typing.Union[TypeEvaluator[_ofMultiFloat_0__T], typing.Callable[[float, _ofMultiFloat_0__T, _ofMultiFloat_0__T], _ofMultiFloat_0__T]], *t3: _ofMultiFloat_0__T) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofMultiFloat(object: typing.Any, string: str, path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofMultiFloat(object: typing.Any, string: str, floatArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> 'ObjectAnimator': ...
    _ofMultiInt_0__T = typing.TypeVar('_ofMultiInt_0__T')  # <T>
    @typing.overload
    @staticmethod
    def ofMultiInt(object: typing.Any, string: str, typeConverter: TypeConverter[_ofMultiInt_0__T, typing.Union[typing.List[int], jpype.JArray]], typeEvaluator: typing.Union[TypeEvaluator[_ofMultiInt_0__T], typing.Callable[[float, _ofMultiInt_0__T, _ofMultiInt_0__T], _ofMultiInt_0__T]], *t3: _ofMultiInt_0__T) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofMultiInt(object: typing.Any, string: str, path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofMultiInt(object: typing.Any, string: str, intArray: typing.Union[typing.List[typing.MutableSequence[int]], jpype.JArray]) -> 'ObjectAnimator': ...
    _ofObject_0__T = typing.TypeVar('_ofObject_0__T')  # <T>
    _ofObject_0__V = typing.TypeVar('_ofObject_0__V')  # <V>
    _ofObject_0__P = typing.TypeVar('_ofObject_0__P')  # <P>
    _ofObject_1__T = typing.TypeVar('_ofObject_1__T')  # <T>
    _ofObject_1__V = typing.TypeVar('_ofObject_1__V')  # <V>
    _ofObject_2__T = typing.TypeVar('_ofObject_2__T')  # <T>
    _ofObject_2__V = typing.TypeVar('_ofObject_2__V')  # <V>
    @typing.overload
    @staticmethod
    def ofObject(t: _ofObject_0__T, property: android.util.Property[_ofObject_0__T, _ofObject_0__P], typeConverter: TypeConverter[_ofObject_0__V, _ofObject_0__P], typeEvaluator: typing.Union[TypeEvaluator[_ofObject_0__V], typing.Callable[[float, _ofObject_0__V, _ofObject_0__V], _ofObject_0__V]], *v: _ofObject_0__V) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofObject(t: _ofObject_1__T, property: android.util.Property[_ofObject_1__T, _ofObject_1__V], typeConverter: TypeConverter[android.graphics.PointF, _ofObject_1__V], path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofObject(t: _ofObject_2__T, property: android.util.Property[_ofObject_2__T, _ofObject_2__V], typeEvaluator: typing.Union[TypeEvaluator[_ofObject_2__V], typing.Callable[[float, _ofObject_2__V, _ofObject_2__V], _ofObject_2__V]], *v: _ofObject_2__V) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofObject(object: typing.Any, string: str, typeConverter: TypeConverter[android.graphics.PointF, typing.Any], path: android.graphics.Path) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofObject(object: typing.Any, string: str, typeEvaluator: typing.Union[TypeEvaluator, typing.Callable], *object2: typing.Any) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofObject(typeEvaluator: typing.Union[TypeEvaluator, typing.Callable], *object: typing.Any) -> ValueAnimator: ...
    @typing.overload
    @staticmethod
    def ofPropertyValuesHolder(object: typing.Any, *propertyValuesHolder: PropertyValuesHolder) -> 'ObjectAnimator': ...
    @typing.overload
    @staticmethod
    def ofPropertyValuesHolder(*propertyValuesHolder: PropertyValuesHolder) -> ValueAnimator: ...
    def setAutoCancel(self, boolean: bool) -> None: ...
    def setDuration(self, long: int) -> 'ObjectAnimator': ...
    def setFloatValues(self, *float: float) -> None: ...
    def setIntValues(self, *int: int) -> None: ...
    def setObjectValues(self, *object: typing.Any) -> None: ...
    def setProperty(self, property: android.util.Property) -> None: ...
    def setPropertyName(self, string: str) -> None: ...
    def setTarget(self, object: typing.Any) -> None: ...
    def setupEndValues(self) -> None: ...
    def setupStartValues(self) -> None: ...
    def start(self) -> None: ...
    def toString(self) -> str: ...

class TimeAnimator(ValueAnimator):
    def __init__(self): ...
    def setCurrentPlayTime(self, long: int) -> None: ...
    def setTimeListener(self, timeListener: typing.Union['TimeAnimator.TimeListener', typing.Callable]) -> None: ...
    def start(self) -> None: ...
    class TimeListener:
        def onTimeUpdate(self, timeAnimator: 'TimeAnimator', long: int, long2: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.animation")``.

    Animator: typing.Type[Animator]
    AnimatorInflater: typing.Type[AnimatorInflater]
    AnimatorListenerAdapter: typing.Type[AnimatorListenerAdapter]
    AnimatorSet: typing.Type[AnimatorSet]
    ArgbEvaluator: typing.Type[ArgbEvaluator]
    BidirectionalTypeConverter: typing.Type[BidirectionalTypeConverter]
    FloatArrayEvaluator: typing.Type[FloatArrayEvaluator]
    FloatEvaluator: typing.Type[FloatEvaluator]
    IntArrayEvaluator: typing.Type[IntArrayEvaluator]
    IntEvaluator: typing.Type[IntEvaluator]
    Keyframe: typing.Type[Keyframe]
    LayoutTransition: typing.Type[LayoutTransition]
    ObjectAnimator: typing.Type[ObjectAnimator]
    PointFEvaluator: typing.Type[PointFEvaluator]
    PropertyValuesHolder: typing.Type[PropertyValuesHolder]
    RectEvaluator: typing.Type[RectEvaluator]
    StateListAnimator: typing.Type[StateListAnimator]
    TimeAnimator: typing.Type[TimeAnimator]
    TimeInterpolator: typing.Type[TimeInterpolator]
    TypeConverter: typing.Type[TypeConverter]
    TypeEvaluator: typing.Type[TypeEvaluator]
    ValueAnimator: typing.Type[ValueAnimator]
