
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.database
import android.os
import android.util
import java.io
import java.lang
import java.util
import java.util.function
import java.util.regex
import jpype
import jpype.protocol
import typing



class SQLiteClosable(java.io.Closeable):
    def __init__(self): ...
    def acquireReference(self) -> None: ...
    def close(self) -> None: ...
    def releaseReference(self) -> None: ...
    def releaseReferenceFromContainer(self) -> None: ...

class SQLiteCursor(android.database.AbstractWindowedCursor):
    @typing.overload
    def __init__(self, sQLiteCursorDriver: 'SQLiteCursorDriver', string: str, sQLiteQuery: 'SQLiteQuery'): ...
    @typing.overload
    def __init__(self, sQLiteDatabase: 'SQLiteDatabase', sQLiteCursorDriver: 'SQLiteCursorDriver', string: str, sQLiteQuery: 'SQLiteQuery'): ...
    def close(self) -> None: ...
    def deactivate(self) -> None: ...
    def getColumnIndex(self, string: str) -> int: ...
    def getColumnNames(self) -> typing.MutableSequence[str]: ...
    def getCount(self) -> int: ...
    def getDatabase(self) -> 'SQLiteDatabase': ...
    def onMove(self, int: int, int2: int) -> bool: ...
    def requery(self) -> bool: ...
    def setFillWindowForwardOnly(self, boolean: bool) -> None: ...
    def setSelectionArguments(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def setWindow(self, cursorWindow: android.database.CursorWindow) -> None: ...

class SQLiteCursorDriver:
    def cursorClosed(self) -> None: ...
    def cursorDeactivated(self) -> None: ...
    def cursorRequeried(self, cursor: android.database.Cursor) -> None: ...
    def query(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], stringArray: typing.Union[typing.List[str], jpype.JArray]) -> android.database.Cursor: ...
    def setBindArguments(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...

class SQLiteException(android.database.SQLException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class SQLiteOpenHelper(java.lang.AutoCloseable):
    @typing.overload
    def __init__(self, context: android.content.Context, string: str, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, string: str, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], int: int, databaseErrorHandler: typing.Union[android.database.DatabaseErrorHandler, typing.Callable]): ...
    @typing.overload
    def __init__(self, context: android.content.Context, string: str, int: int, openParams: 'SQLiteDatabase.OpenParams'): ...
    def close(self) -> None: ...
    def getDatabaseName(self) -> str: ...
    def getReadableDatabase(self) -> 'SQLiteDatabase': ...
    def getWritableDatabase(self) -> 'SQLiteDatabase': ...
    def onConfigure(self, sQLiteDatabase: 'SQLiteDatabase') -> None: ...
    def onCreate(self, sQLiteDatabase: 'SQLiteDatabase') -> None: ...
    def onDowngrade(self, sQLiteDatabase: 'SQLiteDatabase', int: int, int2: int) -> None: ...
    def onOpen(self, sQLiteDatabase: 'SQLiteDatabase') -> None: ...
    def onUpgrade(self, sQLiteDatabase: 'SQLiteDatabase', int: int, int2: int) -> None: ...
    def setIdleConnectionTimeout(self, long: int) -> None: ...
    def setLookasideConfig(self, int: int, int2: int) -> None: ...
    def setOpenParams(self, openParams: 'SQLiteDatabase.OpenParams') -> None: ...
    def setWriteAheadLoggingEnabled(self, boolean: bool) -> None: ...

class SQLiteQueryBuilder:
    def __init__(self): ...
    @staticmethod
    def appendColumns(stringBuilder: java.lang.StringBuilder, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def appendWhere(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def appendWhereEscapeString(self, string: str) -> None: ...
    def appendWhereStandalone(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def buildQuery(self, stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, string3: str, string4: str, string5: str, string6: str) -> str: ...
    @typing.overload
    def buildQuery(self, stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string4: str, string5: str, string6: str, string7: str) -> str: ...
    @staticmethod
    def buildQueryString(boolean: bool, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, string4: str, string5: str, string6: str, string7: str) -> str: ...
    def buildUnionQuery(self, stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, string3: str) -> str: ...
    @typing.overload
    def buildUnionSubQuery(self, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], set: java.util.Set[str], int: int, string3: str, string4: str, string5: str, string6: str) -> str: ...
    @typing.overload
    def buildUnionSubQuery(self, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], set: java.util.Set[str], int: int, string3: str, string4: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string6: str, string7: str) -> str: ...
    def delete(self, sQLiteDatabase: 'SQLiteDatabase', string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    def getCursorFactory(self) -> 'SQLiteDatabase.CursorFactory': ...
    def getProjectionGreylist(self) -> java.util.Collection[java.util.regex.Pattern]: ...
    def getProjectionMap(self) -> java.util.Map[str, str]: ...
    def getTables(self) -> str: ...
    def insert(self, sQLiteDatabase: 'SQLiteDatabase', contentValues: android.content.ContentValues) -> int: ...
    def isDistinct(self) -> bool: ...
    def isStrict(self) -> bool: ...
    def isStrictColumns(self) -> bool: ...
    def isStrictGrammar(self) -> bool: ...
    @typing.overload
    def query(self, sQLiteDatabase: 'SQLiteDatabase', stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string4: str, string5: str, string6: str) -> android.database.Cursor: ...
    @typing.overload
    def query(self, sQLiteDatabase: 'SQLiteDatabase', stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string4: str, string5: str, string6: str, string7: str) -> android.database.Cursor: ...
    @typing.overload
    def query(self, sQLiteDatabase: 'SQLiteDatabase', stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string4: str, string5: str, string6: str, string7: str, cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    def setCursorFactory(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable]) -> None: ...
    def setDistinct(self, boolean: bool) -> None: ...
    def setProjectionGreylist(self, collection: typing.Union[java.util.Collection[java.util.regex.Pattern], typing.Sequence[java.util.regex.Pattern], typing.Set[java.util.regex.Pattern]]) -> None: ...
    def setProjectionMap(self, map: typing.Union[java.util.Map[str, str], typing.Mapping[str, str]]) -> None: ...
    def setStrict(self, boolean: bool) -> None: ...
    def setStrictColumns(self, boolean: bool) -> None: ...
    def setStrictGrammar(self, boolean: bool) -> None: ...
    def setTables(self, string: str) -> None: ...
    def update(self, sQLiteDatabase: 'SQLiteDatabase', contentValues: android.content.ContentValues, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...

class SQLiteRawStatement(java.io.Closeable):
    SQLITE_DATA_TYPE_BLOB: typing.ClassVar[int] = ...
    SQLITE_DATA_TYPE_FLOAT: typing.ClassVar[int] = ...
    SQLITE_DATA_TYPE_INTEGER: typing.ClassVar[int] = ...
    SQLITE_DATA_TYPE_NULL: typing.ClassVar[int] = ...
    SQLITE_DATA_TYPE_TEXT: typing.ClassVar[int] = ...
    @typing.overload
    def bindBlob(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def bindBlob(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int2: int, int3: int) -> None: ...
    def bindDouble(self, int: int, double: float) -> None: ...
    def bindInt(self, int: int, int2: int) -> None: ...
    def bindLong(self, int: int, long: int) -> None: ...
    def bindNull(self, int: int) -> None: ...
    def bindText(self, int: int, string: str) -> None: ...
    def clearBindings(self) -> None: ...
    def close(self) -> None: ...
    def getColumnBlob(self, int: int) -> typing.MutableSequence[int]: ...
    def getColumnDouble(self, int: int) -> float: ...
    def getColumnInt(self, int: int) -> int: ...
    def getColumnLength(self, int: int) -> int: ...
    def getColumnLong(self, int: int) -> int: ...
    def getColumnName(self, int: int) -> str: ...
    def getColumnText(self, int: int) -> str: ...
    def getColumnType(self, int: int) -> int: ...
    def getParameterCount(self) -> int: ...
    def getParameterIndex(self, string: str) -> int: ...
    def getParameterName(self, int: int) -> str: ...
    def getResultColumnCount(self) -> int: ...
    def isOpen(self) -> bool: ...
    def readColumnBlob(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int2: int, int3: int, int4: int) -> int: ...
    def reset(self) -> None: ...
    def step(self) -> bool: ...
    def toString(self) -> str: ...

class SQLiteTransactionListener:
    def onBegin(self) -> None: ...
    def onCommit(self) -> None: ...
    def onRollback(self) -> None: ...

class SQLiteAbortException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteAccessPermException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteBindOrColumnIndexOutOfRangeException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteBlobTooBigException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteCantOpenDatabaseException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteConstraintException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteDatabase(SQLiteClosable):
    CONFLICT_ABORT: typing.ClassVar[int] = ...
    CONFLICT_FAIL: typing.ClassVar[int] = ...
    CONFLICT_IGNORE: typing.ClassVar[int] = ...
    CONFLICT_NONE: typing.ClassVar[int] = ...
    CONFLICT_REPLACE: typing.ClassVar[int] = ...
    CONFLICT_ROLLBACK: typing.ClassVar[int] = ...
    CREATE_IF_NECESSARY: typing.ClassVar[int] = ...
    ENABLE_WRITE_AHEAD_LOGGING: typing.ClassVar[int] = ...
    JOURNAL_MODE_DELETE: typing.ClassVar[str] = ...
    JOURNAL_MODE_MEMORY: typing.ClassVar[str] = ...
    JOURNAL_MODE_OFF: typing.ClassVar[str] = ...
    JOURNAL_MODE_PERSIST: typing.ClassVar[str] = ...
    JOURNAL_MODE_TRUNCATE: typing.ClassVar[str] = ...
    JOURNAL_MODE_WAL: typing.ClassVar[str] = ...
    MAX_SQL_CACHE_SIZE: typing.ClassVar[int] = ...
    NO_LOCALIZED_COLLATORS: typing.ClassVar[int] = ...
    OPEN_READONLY: typing.ClassVar[int] = ...
    OPEN_READWRITE: typing.ClassVar[int] = ...
    SQLITE_MAX_LIKE_PATTERN_LENGTH: typing.ClassVar[int] = ...
    SYNC_MODE_EXTRA: typing.ClassVar[str] = ...
    SYNC_MODE_FULL: typing.ClassVar[str] = ...
    SYNC_MODE_NORMAL: typing.ClassVar[str] = ...
    SYNC_MODE_OFF: typing.ClassVar[str] = ...
    def beginTransaction(self) -> None: ...
    def beginTransactionNonExclusive(self) -> None: ...
    def beginTransactionReadOnly(self) -> None: ...
    def beginTransactionWithListener(self, sQLiteTransactionListener: SQLiteTransactionListener) -> None: ...
    def beginTransactionWithListenerNonExclusive(self, sQLiteTransactionListener: SQLiteTransactionListener) -> None: ...
    def beginTransactionWithListenerReadOnly(self, sQLiteTransactionListener: SQLiteTransactionListener) -> None: ...
    def compileStatement(self, string: str) -> 'SQLiteStatement': ...
    @staticmethod
    def create(cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable]) -> 'SQLiteDatabase': ...
    @staticmethod
    def createInMemory(openParams: 'SQLiteDatabase.OpenParams') -> 'SQLiteDatabase': ...
    def createRawStatement(self, string: str) -> SQLiteRawStatement: ...
    def delete(self, string: str, string2: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    @staticmethod
    def deleteDatabase(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> bool: ...
    def disableWriteAheadLogging(self) -> None: ...
    def enableWriteAheadLogging(self) -> bool: ...
    def endTransaction(self) -> None: ...
    def execPerConnectionSQL(self, string: str, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> None: ...
    @typing.overload
    def execSQL(self, string: str) -> None: ...
    @typing.overload
    def execSQL(self, string: str, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> None: ...
    @staticmethod
    def findEditTable(string: str) -> str: ...
    def getAttachedDbs(self) -> java.util.List[android.util.Pair[str, str]]: ...
    def getLastChangedRowCount(self) -> int: ...
    def getLastInsertRowId(self) -> int: ...
    def getMaximumSize(self) -> int: ...
    def getPageSize(self) -> int: ...
    def getPath(self) -> str: ...
    def getSyncedTables(self) -> java.util.Map[str, str]: ...
    def getTotalChangedRowCount(self) -> int: ...
    def getVersion(self) -> int: ...
    def inTransaction(self) -> bool: ...
    def insert(self, string: str, string2: str, contentValues: android.content.ContentValues) -> int: ...
    def insertOrThrow(self, string: str, string2: str, contentValues: android.content.ContentValues) -> int: ...
    def insertWithOnConflict(self, string: str, string2: str, contentValues: android.content.ContentValues, int: int) -> int: ...
    def isDatabaseIntegrityOk(self) -> bool: ...
    def isDbLockedByCurrentThread(self) -> bool: ...
    def isDbLockedByOtherThreads(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def isWriteAheadLoggingEnabled(self) -> bool: ...
    @typing.overload
    def markTableSyncable(self, string: str, string2: str) -> None: ...
    @typing.overload
    def markTableSyncable(self, string: str, string2: str, string3: str) -> None: ...
    def needUpgrade(self, int: int) -> bool: ...
    @typing.overload
    @staticmethod
    def openDatabase(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], openParams: 'SQLiteDatabase.OpenParams') -> 'SQLiteDatabase': ...
    @typing.overload
    @staticmethod
    def openDatabase(string: str, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], int: int) -> 'SQLiteDatabase': ...
    @typing.overload
    @staticmethod
    def openDatabase(string: str, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], int: int, databaseErrorHandler: typing.Union[android.database.DatabaseErrorHandler, typing.Callable]) -> 'SQLiteDatabase': ...
    @typing.overload
    @staticmethod
    def openOrCreateDatabase(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable]) -> 'SQLiteDatabase': ...
    @typing.overload
    @staticmethod
    def openOrCreateDatabase(string: str, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable]) -> 'SQLiteDatabase': ...
    @typing.overload
    @staticmethod
    def openOrCreateDatabase(string: str, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], databaseErrorHandler: typing.Union[android.database.DatabaseErrorHandler, typing.Callable]) -> 'SQLiteDatabase': ...
    @typing.overload
    def query(self, boolean: bool, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string5: str, string6: str, string7: str, string8: str) -> android.database.Cursor: ...
    @typing.overload
    def query(self, boolean: bool, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string5: str, string6: str, string7: str, string8: str, cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    @typing.overload
    def query(self, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string5: str, string6: str, string7: str) -> android.database.Cursor: ...
    @typing.overload
    def query(self, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string5: str, string6: str, string7: str, string8: str) -> android.database.Cursor: ...
    @typing.overload
    def queryWithFactory(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], boolean: bool, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string5: str, string6: str, string7: str, string8: str) -> android.database.Cursor: ...
    @typing.overload
    def queryWithFactory(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], boolean: bool, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string5: str, string6: str, string7: str, string8: str, cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    @typing.overload
    def rawQuery(self, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> android.database.Cursor: ...
    @typing.overload
    def rawQuery(self, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    @typing.overload
    def rawQueryWithFactory(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str) -> android.database.Cursor: ...
    @typing.overload
    def rawQueryWithFactory(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable], string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], string3: str, cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    @staticmethod
    def releaseMemory() -> int: ...
    def replace(self, string: str, string2: str, contentValues: android.content.ContentValues) -> int: ...
    def replaceOrThrow(self, string: str, string2: str, contentValues: android.content.ContentValues) -> int: ...
    def setCustomAggregateFunction(self, string: str, binaryOperator: typing.Union[java.util.function.BinaryOperator[str], typing.Callable]) -> None: ...
    def setCustomScalarFunction(self, string: str, unaryOperator: typing.Union[java.util.function.UnaryOperator[str], typing.Callable]) -> None: ...
    def setForeignKeyConstraintsEnabled(self, boolean: bool) -> None: ...
    def setLocale(self, locale: java.util.Locale) -> None: ...
    def setLockingEnabled(self, boolean: bool) -> None: ...
    def setMaxSqlCacheSize(self, int: int) -> None: ...
    def setMaximumSize(self, long: int) -> int: ...
    def setPageSize(self, long: int) -> None: ...
    def setTransactionSuccessful(self) -> None: ...
    def setVersion(self, int: int) -> None: ...
    def toString(self) -> str: ...
    def update(self, string: str, contentValues: android.content.ContentValues, string2: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    def updateWithOnConflict(self, string: str, contentValues: android.content.ContentValues, string2: str, stringArray: typing.Union[typing.List[str], jpype.JArray], int: int) -> int: ...
    def validateSql(self, string: str, cancellationSignal: android.os.CancellationSignal) -> None: ...
    def yieldIfContended(self) -> bool: ...
    @typing.overload
    def yieldIfContendedSafely(self) -> bool: ...
    @typing.overload
    def yieldIfContendedSafely(self, long: int) -> bool: ...
    class CursorFactory:
        def newCursor(self, sQLiteDatabase: 'SQLiteDatabase', sQLiteCursorDriver: SQLiteCursorDriver, string: str, sQLiteQuery: 'SQLiteQuery') -> android.database.Cursor: ...
    class OpenParams:
        def getCursorFactory(self) -> 'SQLiteDatabase.CursorFactory': ...
        def getErrorHandler(self) -> android.database.DatabaseErrorHandler: ...
        def getIdleConnectionTimeout(self) -> int: ...
        def getJournalMode(self) -> str: ...
        def getLookasideSlotCount(self) -> int: ...
        def getLookasideSlotSize(self) -> int: ...
        def getOpenFlags(self) -> int: ...
        def getSynchronousMode(self) -> str: ...
        class Builder:
            @typing.overload
            def __init__(self): ...
            @typing.overload
            def __init__(self, openParams: 'SQLiteDatabase.OpenParams'): ...
            def addOpenFlags(self, int: int) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def build(self) -> 'SQLiteDatabase.OpenParams': ...
            def removeOpenFlags(self, int: int) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setCursorFactory(self, cursorFactory: typing.Union['SQLiteDatabase.CursorFactory', typing.Callable]) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setErrorHandler(self, databaseErrorHandler: typing.Union[android.database.DatabaseErrorHandler, typing.Callable]) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setIdleConnectionTimeout(self, long: int) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setJournalMode(self, string: str) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setLookasideConfig(self, int: int, int2: int) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setOpenFlags(self, int: int) -> 'SQLiteDatabase.OpenParams.Builder': ...
            def setSynchronousMode(self, string: str) -> 'SQLiteDatabase.OpenParams.Builder': ...

class SQLiteDatabaseCorruptException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteDatabaseLockedException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteDatatypeMismatchException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteDiskIOException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteDoneException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteFullException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteMisuseException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteOutOfMemoryException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteProgram(SQLiteClosable):
    def bindAllArgsAsStrings(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def bindBlob(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def bindDouble(self, int: int, double: float) -> None: ...
    def bindLong(self, int: int, long: int) -> None: ...
    def bindNull(self, int: int) -> None: ...
    def bindString(self, int: int, string: str) -> None: ...
    def clearBindings(self) -> None: ...
    def getUniqueId(self) -> int: ...

class SQLiteReadOnlyDatabaseException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteTableLockedException(SQLiteException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class SQLiteQuery(SQLiteProgram):
    def toString(self) -> str: ...

class SQLiteStatement(SQLiteProgram):
    def execute(self) -> None: ...
    def executeInsert(self) -> int: ...
    def executeUpdateDelete(self) -> int: ...
    def simpleQueryForBlobFileDescriptor(self) -> android.os.ParcelFileDescriptor: ...
    def simpleQueryForLong(self) -> int: ...
    def simpleQueryForString(self) -> str: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.database.sqlite")``.

    SQLiteAbortException: typing.Type[SQLiteAbortException]
    SQLiteAccessPermException: typing.Type[SQLiteAccessPermException]
    SQLiteBindOrColumnIndexOutOfRangeException: typing.Type[SQLiteBindOrColumnIndexOutOfRangeException]
    SQLiteBlobTooBigException: typing.Type[SQLiteBlobTooBigException]
    SQLiteCantOpenDatabaseException: typing.Type[SQLiteCantOpenDatabaseException]
    SQLiteClosable: typing.Type[SQLiteClosable]
    SQLiteConstraintException: typing.Type[SQLiteConstraintException]
    SQLiteCursor: typing.Type[SQLiteCursor]
    SQLiteCursorDriver: typing.Type[SQLiteCursorDriver]
    SQLiteDatabase: typing.Type[SQLiteDatabase]
    SQLiteDatabaseCorruptException: typing.Type[SQLiteDatabaseCorruptException]
    SQLiteDatabaseLockedException: typing.Type[SQLiteDatabaseLockedException]
    SQLiteDatatypeMismatchException: typing.Type[SQLiteDatatypeMismatchException]
    SQLiteDiskIOException: typing.Type[SQLiteDiskIOException]
    SQLiteDoneException: typing.Type[SQLiteDoneException]
    SQLiteException: typing.Type[SQLiteException]
    SQLiteFullException: typing.Type[SQLiteFullException]
    SQLiteMisuseException: typing.Type[SQLiteMisuseException]
    SQLiteOpenHelper: typing.Type[SQLiteOpenHelper]
    SQLiteOutOfMemoryException: typing.Type[SQLiteOutOfMemoryException]
    SQLiteProgram: typing.Type[SQLiteProgram]
    SQLiteQuery: typing.Type[SQLiteQuery]
    SQLiteQueryBuilder: typing.Type[SQLiteQueryBuilder]
    SQLiteRawStatement: typing.Type[SQLiteRawStatement]
    SQLiteReadOnlyDatabaseException: typing.Type[SQLiteReadOnlyDatabaseException]
    SQLiteStatement: typing.Type[SQLiteStatement]
    SQLiteTableLockedException: typing.Type[SQLiteTableLockedException]
    SQLiteTransactionListener: typing.Type[SQLiteTransactionListener]
