
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.media
import android.net
import android.os
import android.view
import java.lang
import java.util
import java.util.concurrent
import typing



class MediaController:
    def __init__(self, context: android.content.Context, token: 'MediaSession.Token'): ...
    def adjustVolume(self, int: int, int2: int) -> None: ...
    def dispatchMediaButtonEvent(self, keyEvent: android.view.KeyEvent) -> bool: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFlags(self) -> int: ...
    def getMetadata(self) -> android.media.MediaMetadata: ...
    def getPackageName(self) -> str: ...
    def getPlaybackInfo(self) -> 'MediaController.PlaybackInfo': ...
    def getPlaybackState(self) -> 'PlaybackState': ...
    def getQueue(self) -> java.util.List['MediaSession.QueueItem']: ...
    def getQueueTitle(self) -> java.lang.CharSequence: ...
    def getRatingType(self) -> int: ...
    def getSessionActivity(self) -> android.app.PendingIntent: ...
    def getSessionInfo(self) -> android.os.Bundle: ...
    def getSessionToken(self) -> 'MediaSession.Token': ...
    def getTag(self) -> str: ...
    def getTransportControls(self) -> 'MediaController.TransportControls': ...
    @typing.overload
    def registerCallback(self, callback: 'MediaController.Callback') -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'MediaController.Callback', handler: android.os.Handler) -> None: ...
    def sendCommand(self, string: str, bundle: android.os.Bundle, resultReceiver: android.os.ResultReceiver) -> None: ...
    def setVolumeTo(self, int: int, int2: int) -> None: ...
    def unregisterCallback(self, callback: 'MediaController.Callback') -> None: ...
    class Callback:
        def __init__(self): ...
        def onAudioInfoChanged(self, playbackInfo: 'MediaController.PlaybackInfo') -> None: ...
        def onExtrasChanged(self, bundle: android.os.Bundle) -> None: ...
        def onMetadataChanged(self, mediaMetadata: android.media.MediaMetadata) -> None: ...
        def onPlaybackStateChanged(self, playbackState: 'PlaybackState') -> None: ...
        def onQueueChanged(self, list: java.util.List['MediaSession.QueueItem']) -> None: ...
        def onQueueTitleChanged(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
        def onSessionDestroyed(self) -> None: ...
        def onSessionEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    class PlaybackInfo(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        PLAYBACK_TYPE_LOCAL: typing.ClassVar[int] = ...
        PLAYBACK_TYPE_REMOTE: typing.ClassVar[int] = ...
        def describeContents(self) -> int: ...
        def getAudioAttributes(self) -> android.media.AudioAttributes: ...
        def getCurrentVolume(self) -> int: ...
        def getMaxVolume(self) -> int: ...
        def getPlaybackType(self) -> int: ...
        def getVolumeControl(self) -> int: ...
        def getVolumeControlId(self) -> str: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class TransportControls:
        def fastForward(self) -> None: ...
        def pause(self) -> None: ...
        def play(self) -> None: ...
        def playFromMediaId(self, string: str, bundle: android.os.Bundle) -> None: ...
        def playFromSearch(self, string: str, bundle: android.os.Bundle) -> None: ...
        def playFromUri(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
        def prepare(self) -> None: ...
        def prepareFromMediaId(self, string: str, bundle: android.os.Bundle) -> None: ...
        def prepareFromSearch(self, string: str, bundle: android.os.Bundle) -> None: ...
        def prepareFromUri(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
        def rewind(self) -> None: ...
        def seekTo(self, long: int) -> None: ...
        @typing.overload
        def sendCustomAction(self, customAction: 'PlaybackState.CustomAction', bundle: android.os.Bundle) -> None: ...
        @typing.overload
        def sendCustomAction(self, string: str, bundle: android.os.Bundle) -> None: ...
        def setPlaybackSpeed(self, float: float) -> None: ...
        def setRating(self, rating: android.media.Rating) -> None: ...
        def skipToNext(self) -> None: ...
        def skipToPrevious(self) -> None: ...
        def skipToQueueItem(self, long: int) -> None: ...
        def stop(self) -> None: ...

class MediaSession:
    FLAG_HANDLES_MEDIA_BUTTONS: typing.ClassVar[int] = ...
    FLAG_HANDLES_TRANSPORT_CONTROLS: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, string: str): ...
    @typing.overload
    def __init__(self, context: android.content.Context, string: str, bundle: android.os.Bundle): ...
    def getController(self) -> MediaController: ...
    def getCurrentControllerInfo(self) -> 'MediaSessionManager.RemoteUserInfo': ...
    def getSessionToken(self) -> 'MediaSession.Token': ...
    def isActive(self) -> bool: ...
    def release(self) -> None: ...
    def sendSessionEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def setActive(self, boolean: bool) -> None: ...
    @typing.overload
    def setCallback(self, callback: 'MediaSession.Callback') -> None: ...
    @typing.overload
    def setCallback(self, callback: 'MediaSession.Callback', handler: android.os.Handler) -> None: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setFlags(self, int: int) -> None: ...
    def setMediaButtonBroadcastReceiver(self, componentName: android.content.ComponentName) -> None: ...
    def setMediaButtonReceiver(self, pendingIntent: android.app.PendingIntent) -> None: ...
    def setMetadata(self, mediaMetadata: android.media.MediaMetadata) -> None: ...
    def setPlaybackState(self, playbackState: 'PlaybackState') -> None: ...
    def setPlaybackToLocal(self, audioAttributes: android.media.AudioAttributes) -> None: ...
    def setPlaybackToRemote(self, volumeProvider: android.media.VolumeProvider) -> None: ...
    def setQueue(self, list: java.util.List['MediaSession.QueueItem']) -> None: ...
    def setQueueTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setRatingType(self, int: int) -> None: ...
    def setSessionActivity(self, pendingIntent: android.app.PendingIntent) -> None: ...
    class Callback:
        def __init__(self): ...
        def onCommand(self, string: str, bundle: android.os.Bundle, resultReceiver: android.os.ResultReceiver) -> None: ...
        def onCustomAction(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onFastForward(self) -> None: ...
        def onMediaButtonEvent(self, intent: android.content.Intent) -> bool: ...
        def onPause(self) -> None: ...
        def onPlay(self) -> None: ...
        def onPlayFromMediaId(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onPlayFromSearch(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onPlayFromUri(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
        def onPrepare(self) -> None: ...
        def onPrepareFromMediaId(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onPrepareFromSearch(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onPrepareFromUri(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
        def onRewind(self) -> None: ...
        def onSeekTo(self, long: int) -> None: ...
        def onSetPlaybackSpeed(self, float: float) -> None: ...
        def onSetRating(self, rating: android.media.Rating) -> None: ...
        def onSkipToNext(self) -> None: ...
        def onSkipToPrevious(self) -> None: ...
        def onSkipToQueueItem(self, long: int) -> None: ...
        def onStop(self) -> None: ...
    class QueueItem(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        UNKNOWN_ID: typing.ClassVar[int] = ...
        def __init__(self, mediaDescription: android.media.MediaDescription, long: int): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDescription(self) -> android.media.MediaDescription: ...
        def getQueueId(self) -> int: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Token(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class MediaSessionManager:
    @typing.overload
    def addOnActiveSessionsChangedListener(self, onActiveSessionsChangedListener: typing.Union['MediaSessionManager.OnActiveSessionsChangedListener', typing.Callable], componentName: android.content.ComponentName) -> None: ...
    @typing.overload
    def addOnActiveSessionsChangedListener(self, onActiveSessionsChangedListener: typing.Union['MediaSessionManager.OnActiveSessionsChangedListener', typing.Callable], componentName: android.content.ComponentName, handler: android.os.Handler) -> None: ...
    def addOnMediaKeyEventSessionChangedListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], onMediaKeyEventSessionChangedListener: typing.Union['MediaSessionManager.OnMediaKeyEventSessionChangedListener', typing.Callable]) -> None: ...
    @typing.overload
    def addOnSession2TokensChangedListener(self, onSession2TokensChangedListener: typing.Union['MediaSessionManager.OnSession2TokensChangedListener', typing.Callable]) -> None: ...
    @typing.overload
    def addOnSession2TokensChangedListener(self, onSession2TokensChangedListener: typing.Union['MediaSessionManager.OnSession2TokensChangedListener', typing.Callable], handler: android.os.Handler) -> None: ...
    def getActiveSessions(self, componentName: android.content.ComponentName) -> java.util.List[MediaController]: ...
    def getMediaKeyEventSession(self) -> MediaSession.Token: ...
    def getMediaKeyEventSessionPackageName(self) -> str: ...
    def getSession2Tokens(self) -> java.util.List[android.media.Session2Token]: ...
    def isTrustedForMediaControl(self, remoteUserInfo: 'MediaSessionManager.RemoteUserInfo') -> bool: ...
    def notifySession2Created(self, session2Token: android.media.Session2Token) -> None: ...
    def removeOnActiveSessionsChangedListener(self, onActiveSessionsChangedListener: typing.Union['MediaSessionManager.OnActiveSessionsChangedListener', typing.Callable]) -> None: ...
    def removeOnMediaKeyEventSessionChangedListener(self, onMediaKeyEventSessionChangedListener: typing.Union['MediaSessionManager.OnMediaKeyEventSessionChangedListener', typing.Callable]) -> None: ...
    def removeOnSession2TokensChangedListener(self, onSession2TokensChangedListener: typing.Union['MediaSessionManager.OnSession2TokensChangedListener', typing.Callable]) -> None: ...
    class OnActiveSessionsChangedListener:
        def onActiveSessionsChanged(self, list: java.util.List[MediaController]) -> None: ...
    class OnMediaKeyEventSessionChangedListener:
        def onMediaKeyEventSessionChanged(self, string: str, token: MediaSession.Token) -> None: ...
    class OnSession2TokensChangedListener:
        def onSession2TokensChanged(self, list: java.util.List[android.media.Session2Token]) -> None: ...
    class RemoteUserInfo:
        def __init__(self, string: str, int: int, int2: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getPackageName(self) -> str: ...
        def getPid(self) -> int: ...
        def getUid(self) -> int: ...
        def hashCode(self) -> int: ...

class PlaybackState(android.os.Parcelable):
    ACTION_FAST_FORWARD: typing.ClassVar[int] = ...
    ACTION_PAUSE: typing.ClassVar[int] = ...
    ACTION_PLAY: typing.ClassVar[int] = ...
    ACTION_PLAY_FROM_MEDIA_ID: typing.ClassVar[int] = ...
    ACTION_PLAY_FROM_SEARCH: typing.ClassVar[int] = ...
    ACTION_PLAY_FROM_URI: typing.ClassVar[int] = ...
    ACTION_PLAY_PAUSE: typing.ClassVar[int] = ...
    ACTION_PREPARE: typing.ClassVar[int] = ...
    ACTION_PREPARE_FROM_MEDIA_ID: typing.ClassVar[int] = ...
    ACTION_PREPARE_FROM_SEARCH: typing.ClassVar[int] = ...
    ACTION_PREPARE_FROM_URI: typing.ClassVar[int] = ...
    ACTION_REWIND: typing.ClassVar[int] = ...
    ACTION_SEEK_TO: typing.ClassVar[int] = ...
    ACTION_SET_PLAYBACK_SPEED: typing.ClassVar[int] = ...
    ACTION_SET_RATING: typing.ClassVar[int] = ...
    ACTION_SKIP_TO_NEXT: typing.ClassVar[int] = ...
    ACTION_SKIP_TO_PREVIOUS: typing.ClassVar[int] = ...
    ACTION_SKIP_TO_QUEUE_ITEM: typing.ClassVar[int] = ...
    ACTION_STOP: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PLAYBACK_POSITION_UNKNOWN: typing.ClassVar[int] = ...
    STATE_BUFFERING: typing.ClassVar[int] = ...
    STATE_CONNECTING: typing.ClassVar[int] = ...
    STATE_ERROR: typing.ClassVar[int] = ...
    STATE_FAST_FORWARDING: typing.ClassVar[int] = ...
    STATE_NONE: typing.ClassVar[int] = ...
    STATE_PAUSED: typing.ClassVar[int] = ...
    STATE_PLAYING: typing.ClassVar[int] = ...
    STATE_REWINDING: typing.ClassVar[int] = ...
    STATE_SKIPPING_TO_NEXT: typing.ClassVar[int] = ...
    STATE_SKIPPING_TO_PREVIOUS: typing.ClassVar[int] = ...
    STATE_SKIPPING_TO_QUEUE_ITEM: typing.ClassVar[int] = ...
    STATE_STOPPED: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getActions(self) -> int: ...
    def getActiveQueueItemId(self) -> int: ...
    def getBufferedPosition(self) -> int: ...
    def getCustomActions(self) -> java.util.List['PlaybackState.CustomAction']: ...
    def getErrorMessage(self) -> java.lang.CharSequence: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getLastPositionUpdateTime(self) -> int: ...
    def getPlaybackSpeed(self) -> float: ...
    def getPosition(self) -> int: ...
    def getState(self) -> int: ...
    def isActive(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, playbackState: 'PlaybackState'): ...
        @typing.overload
        def addCustomAction(self, customAction: 'PlaybackState.CustomAction') -> 'PlaybackState.Builder': ...
        @typing.overload
        def addCustomAction(self, string: str, string2: str, int: int) -> 'PlaybackState.Builder': ...
        def build(self) -> 'PlaybackState': ...
        def setActions(self, long: int) -> 'PlaybackState.Builder': ...
        def setActiveQueueItemId(self, long: int) -> 'PlaybackState.Builder': ...
        def setBufferedPosition(self, long: int) -> 'PlaybackState.Builder': ...
        def setErrorMessage(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PlaybackState.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'PlaybackState.Builder': ...
        @typing.overload
        def setState(self, int: int, long: int, float: float) -> 'PlaybackState.Builder': ...
        @typing.overload
        def setState(self, int: int, long: int, float: float, long2: int) -> 'PlaybackState.Builder': ...
    class CustomAction(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getAction(self) -> str: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getIcon(self) -> int: ...
        def getName(self) -> java.lang.CharSequence: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, string: str, charSequence: typing.Union[java.lang.CharSequence, str], int: int): ...
            def build(self) -> 'PlaybackState.CustomAction': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'PlaybackState.CustomAction.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.session")``.

    MediaController: typing.Type[MediaController]
    MediaSession: typing.Type[MediaSession]
    MediaSessionManager: typing.Type[MediaSessionManager]
    PlaybackState: typing.Type[PlaybackState]
