
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import android.view
import typing



class HostUsiVersion(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMajorVersion(self) -> int: ...
    def getMinorVersion(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class InputManager:
    ACTION_QUERY_KEYBOARD_LAYOUTS: typing.ClassVar[str] = ...
    META_DATA_KEYBOARD_LAYOUTS: typing.ClassVar[str] = ...
    def getHostUsiVersion(self, display: android.view.Display) -> HostUsiVersion: ...
    def getInputDevice(self, int: int) -> android.view.InputDevice: ...
    def getInputDeviceIds(self) -> typing.MutableSequence[int]: ...
    def getInputDeviceViewBehavior(self, int: int) -> android.view.InputDevice.ViewBehavior: ...
    def getMaximumObscuringOpacityForTouch(self) -> float: ...
    def isStylusPointerIconEnabled(self) -> bool: ...
    def registerInputDeviceListener(self, inputDeviceListener: 'InputManager.InputDeviceListener', handler: android.os.Handler) -> None: ...
    def unregisterInputDeviceListener(self, inputDeviceListener: 'InputManager.InputDeviceListener') -> None: ...
    def verifyInputEvent(self, inputEvent: android.view.InputEvent) -> android.view.VerifiedInputEvent: ...
    class InputDeviceListener:
        def onInputDeviceAdded(self, int: int) -> None: ...
        def onInputDeviceChanged(self, int: int) -> None: ...
        def onInputDeviceRemoved(self, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.hardware.input")``.

    HostUsiVersion: typing.Type[HostUsiVersion]
    InputManager: typing.Type[InputManager]
