
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import java.nio.channels
import java.util.concurrent
import jpype
import typing



class Channel(java.nio.channels.Channel):
    def close(self) -> None: ...
    def getSelectResponse(self) -> typing.MutableSequence[int]: ...
    def getSession(self) -> 'Session': ...
    def isBasicChannel(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def selectNext(self) -> bool: ...
    def transmit(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...

class Reader:
    def closeSessions(self) -> None: ...
    def getName(self) -> str: ...
    def getSEService(self) -> 'SEService': ...
    def isSecureElementPresent(self) -> bool: ...
    def openSession(self) -> 'Session': ...

class SEService:
    ACTION_SECURE_ELEMENT_STATE_CHANGED: typing.ClassVar[str] = ...
    EXTRA_READER_NAME: typing.ClassVar[str] = ...
    EXTRA_READER_STATE: typing.ClassVar[str] = ...
    def __init__(self, context: android.content.Context, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], onConnectedListener: typing.Union['SEService.OnConnectedListener', typing.Callable]): ...
    def getReaders(self) -> typing.MutableSequence[Reader]: ...
    def getUiccReader(self, int: int) -> Reader: ...
    def getVersion(self) -> str: ...
    def isConnected(self) -> bool: ...
    def shutdown(self) -> None: ...
    class OnConnectedListener:
        def onConnected(self) -> None: ...

class Session:
    def close(self) -> None: ...
    def closeChannels(self) -> None: ...
    def getATR(self) -> typing.MutableSequence[int]: ...
    def getReader(self) -> Reader: ...
    def isClosed(self) -> bool: ...
    @typing.overload
    def openBasicChannel(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> Channel: ...
    @typing.overload
    def openBasicChannel(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byte2: int) -> Channel: ...
    @typing.overload
    def openLogicalChannel(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> Channel: ...
    @typing.overload
    def openLogicalChannel(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byte2: int) -> Channel: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.se.omapi")``.

    Channel: typing.Type[Channel]
    Reader: typing.Type[Reader]
    SEService: typing.Type[SEService]
    Session: typing.Type[Session]
