
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.graphics
import android.os
import android.service.autofill
import android.util
import android.view
import java.lang
import java.util
import typing



class AutofillId(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @staticmethod
    def create(view: android.view.View, int: int) -> 'AutofillId': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AutofillManager:
    EXTRA_ASSIST_STRUCTURE: typing.ClassVar[str] = ...
    EXTRA_AUTHENTICATION_RESULT: typing.ClassVar[str] = ...
    EXTRA_AUTHENTICATION_RESULT_EPHEMERAL_DATASET: typing.ClassVar[str] = ...
    EXTRA_CLIENT_STATE: typing.ClassVar[str] = ...
    EXTRA_INLINE_SUGGESTIONS_REQUEST: typing.ClassVar[str] = ...
    def cancel(self) -> None: ...
    def commit(self) -> None: ...
    def disableAutofillServices(self) -> None: ...
    def getAutofillServiceComponentName(self) -> android.content.ComponentName: ...
    def getAvailableFieldClassificationAlgorithms(self) -> java.util.List[str]: ...
    def getDefaultFieldClassificationAlgorithm(self) -> str: ...
    def getNextAutofillId(self) -> AutofillId: ...
    def getUserData(self) -> android.service.autofill.UserData: ...
    def getUserDataId(self) -> str: ...
    def hasEnabledAutofillServices(self) -> bool: ...
    def isAutofillSupported(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isFieldClassificationEnabled(self) -> bool: ...
    @typing.overload
    def notifyValueChanged(self, view: android.view.View) -> None: ...
    @typing.overload
    def notifyValueChanged(self, view: android.view.View, int: int, autofillValue: 'AutofillValue') -> None: ...
    @typing.overload
    def notifyViewClicked(self, view: android.view.View) -> None: ...
    @typing.overload
    def notifyViewClicked(self, view: android.view.View, int: int) -> None: ...
    @typing.overload
    def notifyViewEntered(self, view: android.view.View) -> None: ...
    @typing.overload
    def notifyViewEntered(self, view: android.view.View, int: int, rect: android.graphics.Rect) -> None: ...
    @typing.overload
    def notifyViewExited(self, view: android.view.View) -> None: ...
    @typing.overload
    def notifyViewExited(self, view: android.view.View, int: int) -> None: ...
    @typing.overload
    def notifyViewVisibilityChanged(self, view: android.view.View, boolean: bool) -> None: ...
    @typing.overload
    def notifyViewVisibilityChanged(self, view: android.view.View, int: int, boolean: bool) -> None: ...
    def notifyVirtualViewsReady(self, view: android.view.View, sparseArray: android.util.SparseArray['VirtualViewFillInfo']) -> None: ...
    def registerCallback(self, autofillCallback: 'AutofillManager.AutofillCallback') -> None: ...
    @typing.overload
    def requestAutofill(self, view: android.view.View) -> None: ...
    @typing.overload
    def requestAutofill(self, view: android.view.View, int: int, rect: android.graphics.Rect) -> None: ...
    def setUserData(self, userData: android.service.autofill.UserData) -> None: ...
    @typing.overload
    def showAutofillDialog(self, view: android.view.View) -> bool: ...
    @typing.overload
    def showAutofillDialog(self, view: android.view.View, int: int) -> bool: ...
    def unregisterCallback(self, autofillCallback: 'AutofillManager.AutofillCallback') -> None: ...
    class AutofillCallback:
        EVENT_INPUT_HIDDEN: typing.ClassVar[int] = ...
        EVENT_INPUT_SHOWN: typing.ClassVar[int] = ...
        EVENT_INPUT_UNAVAILABLE: typing.ClassVar[int] = ...
        def __init__(self): ...
        @typing.overload
        def onAutofillEvent(self, view: android.view.View, int: int) -> None: ...
        @typing.overload
        def onAutofillEvent(self, view: android.view.View, int: int, int2: int) -> None: ...

class AutofillValue(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def forDate(long: int) -> 'AutofillValue': ...
    @staticmethod
    def forList(int: int) -> 'AutofillValue': ...
    @staticmethod
    def forText(charSequence: typing.Union[java.lang.CharSequence, str]) -> 'AutofillValue': ...
    @staticmethod
    def forToggle(boolean: bool) -> 'AutofillValue': ...
    def getDateValue(self) -> int: ...
    def getListValue(self) -> int: ...
    def getTextValue(self) -> java.lang.CharSequence: ...
    def getToggleValue(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isDate(self) -> bool: ...
    def isList(self) -> bool: ...
    def isText(self) -> bool: ...
    def isToggle(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class VirtualViewFillInfo:
    def getAutofillHints(self) -> typing.MutableSequence[str]: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'VirtualViewFillInfo': ...
        def setAutofillHints(self, *string: str) -> 'VirtualViewFillInfo.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.autofill")``.

    AutofillId: typing.Type[AutofillId]
    AutofillManager: typing.Type[AutofillManager]
    AutofillValue: typing.Type[AutofillValue]
    VirtualViewFillInfo: typing.Type[VirtualViewFillInfo]
