
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.content.res
import android.graphics
import android.view
import java.lang
import java.nio
import jpype
import typing



class BaseObj:
    def destroy(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getName(self) -> str: ...
    def hashCode(self) -> int: ...
    def setName(self, string: str) -> None: ...

class Byte2:
    x: int = ...
    y: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, byte: int, byte2: int): ...

class Byte3:
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, byte: int, byte2: int, byte3: int): ...

class Byte4:
    w: int = ...
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, byte: int, byte2: int, byte3: int, byte4: int): ...

class Double2:
    x: float = ...
    y: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float): ...

class Double3:
    x: float = ...
    y: float = ...
    z: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float): ...

class Double4:
    w: float = ...
    x: float = ...
    y: float = ...
    z: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...

class FieldPacker:
    @typing.overload
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    @typing.overload
    def __init__(self, int: int): ...
    def addBoolean(self, boolean: bool) -> None: ...
    @typing.overload
    def addF32(self, float2: 'Float2') -> None: ...
    @typing.overload
    def addF32(self, float3: 'Float3') -> None: ...
    @typing.overload
    def addF32(self, float4: 'Float4') -> None: ...
    @typing.overload
    def addF32(self, float: float) -> None: ...
    @typing.overload
    def addF64(self, double2: Double2) -> None: ...
    @typing.overload
    def addF64(self, double3: Double3) -> None: ...
    @typing.overload
    def addF64(self, double4: Double4) -> None: ...
    @typing.overload
    def addF64(self, double: float) -> None: ...
    @typing.overload
    def addI16(self, short2: 'Short2') -> None: ...
    @typing.overload
    def addI16(self, short3: 'Short3') -> None: ...
    @typing.overload
    def addI16(self, short4: 'Short4') -> None: ...
    @typing.overload
    def addI16(self, short: int) -> None: ...
    @typing.overload
    def addI32(self, int2: 'Int2') -> None: ...
    @typing.overload
    def addI32(self, int3: 'Int3') -> None: ...
    @typing.overload
    def addI32(self, int4: 'Int4') -> None: ...
    @typing.overload
    def addI32(self, int: int) -> None: ...
    @typing.overload
    def addI64(self, long2: 'Long2') -> None: ...
    @typing.overload
    def addI64(self, long3: 'Long3') -> None: ...
    @typing.overload
    def addI64(self, long4: 'Long4') -> None: ...
    @typing.overload
    def addI64(self, long: int) -> None: ...
    @typing.overload
    def addI8(self, byte2: Byte2) -> None: ...
    @typing.overload
    def addI8(self, byte3: Byte3) -> None: ...
    @typing.overload
    def addI8(self, byte4: Byte4) -> None: ...
    @typing.overload
    def addI8(self, byte: int) -> None: ...
    @typing.overload
    def addMatrix(self, matrix2f: 'Matrix2f') -> None: ...
    @typing.overload
    def addMatrix(self, matrix3f: 'Matrix3f') -> None: ...
    @typing.overload
    def addMatrix(self, matrix4f: 'Matrix4f') -> None: ...
    def addObj(self, baseObj: BaseObj) -> None: ...
    @typing.overload
    def addU16(self, int2: 'Int2') -> None: ...
    @typing.overload
    def addU16(self, int3: 'Int3') -> None: ...
    @typing.overload
    def addU16(self, int4: 'Int4') -> None: ...
    @typing.overload
    def addU16(self, int: int) -> None: ...
    @typing.overload
    def addU32(self, long2: 'Long2') -> None: ...
    @typing.overload
    def addU32(self, long3: 'Long3') -> None: ...
    @typing.overload
    def addU32(self, long4: 'Long4') -> None: ...
    @typing.overload
    def addU32(self, long: int) -> None: ...
    @typing.overload
    def addU64(self, long2: 'Long2') -> None: ...
    @typing.overload
    def addU64(self, long3: 'Long3') -> None: ...
    @typing.overload
    def addU64(self, long4: 'Long4') -> None: ...
    @typing.overload
    def addU64(self, long: int) -> None: ...
    @typing.overload
    def addU8(self, short2: 'Short2') -> None: ...
    @typing.overload
    def addU8(self, short3: 'Short3') -> None: ...
    @typing.overload
    def addU8(self, short4: 'Short4') -> None: ...
    @typing.overload
    def addU8(self, short: int) -> None: ...
    def align(self, int: int) -> None: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def reset(self) -> None: ...
    @typing.overload
    def reset(self, int: int) -> None: ...
    def skip(self, int: int) -> None: ...
    def subBoolean(self) -> bool: ...
    def subByte2(self) -> Byte2: ...
    def subByte3(self) -> Byte3: ...
    def subByte4(self) -> Byte4: ...
    def subDouble2(self) -> Double2: ...
    def subDouble3(self) -> Double3: ...
    def subDouble4(self) -> Double4: ...
    def subF32(self) -> float: ...
    def subF64(self) -> float: ...
    def subFloat2(self) -> 'Float2': ...
    def subFloat3(self) -> 'Float3': ...
    def subFloat4(self) -> 'Float4': ...
    def subI16(self) -> int: ...
    def subI32(self) -> int: ...
    def subI64(self) -> int: ...
    def subI8(self) -> int: ...
    def subInt2(self) -> 'Int2': ...
    def subInt3(self) -> 'Int3': ...
    def subInt4(self) -> 'Int4': ...
    def subLong2(self) -> 'Long2': ...
    def subLong3(self) -> 'Long3': ...
    def subLong4(self) -> 'Long4': ...
    def subMatrix2f(self) -> 'Matrix2f': ...
    def subMatrix3f(self) -> 'Matrix3f': ...
    def subMatrix4f(self) -> 'Matrix4f': ...
    def subShort2(self) -> 'Short2': ...
    def subShort3(self) -> 'Short3': ...
    def subShort4(self) -> 'Short4': ...
    def subalign(self, int: int) -> None: ...

class Float2:
    x: float = ...
    y: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, float: float, float2: float): ...

class Float3:
    x: float = ...
    y: float = ...
    z: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float): ...

class Float4:
    w: float = ...
    x: float = ...
    y: float = ...
    z: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, float: float, float2: float, float3: float, float4: float): ...

class Int2:
    x: int = ...
    y: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int, int2: int): ...

class Int3:
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...

class Int4:
    w: int = ...
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int): ...

class Long2:
    x: int = ...
    y: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, long: int, long2: int): ...

class Long3:
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, long: int, long2: int, long3: int): ...

class Long4:
    w: int = ...
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, long: int, long2: int, long3: int, long4: int): ...

class Matrix2f:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, floatArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def get(self, int: int, int2: int) -> float: ...
    def getArray(self) -> typing.MutableSequence[float]: ...
    def load(self, matrix2f: 'Matrix2f') -> None: ...
    def loadIdentity(self) -> None: ...
    def loadMultiply(self, matrix2f: 'Matrix2f', matrix2f2: 'Matrix2f') -> None: ...
    def loadRotate(self, float: float) -> None: ...
    def loadScale(self, float: float, float2: float) -> None: ...
    def multiply(self, matrix2f: 'Matrix2f') -> None: ...
    def rotate(self, float: float) -> None: ...
    def scale(self, float: float, float2: float) -> None: ...
    def set(self, int: int, int2: int, float: float) -> None: ...
    def transpose(self) -> None: ...

class Matrix3f:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, floatArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def get(self, int: int, int2: int) -> float: ...
    def getArray(self) -> typing.MutableSequence[float]: ...
    def load(self, matrix3f: 'Matrix3f') -> None: ...
    def loadIdentity(self) -> None: ...
    def loadMultiply(self, matrix3f: 'Matrix3f', matrix3f2: 'Matrix3f') -> None: ...
    @typing.overload
    def loadRotate(self, float: float) -> None: ...
    @typing.overload
    def loadRotate(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    @typing.overload
    def loadScale(self, float: float, float2: float) -> None: ...
    @typing.overload
    def loadScale(self, float: float, float2: float, float3: float) -> None: ...
    def loadTranslate(self, float: float, float2: float) -> None: ...
    def multiply(self, matrix3f: 'Matrix3f') -> None: ...
    @typing.overload
    def rotate(self, float: float) -> None: ...
    @typing.overload
    def rotate(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    @typing.overload
    def scale(self, float: float, float2: float) -> None: ...
    @typing.overload
    def scale(self, float: float, float2: float, float3: float) -> None: ...
    def set(self, int: int, int2: int, float: float) -> None: ...
    def translate(self, float: float, float2: float) -> None: ...
    def transpose(self) -> None: ...

class Matrix4f:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, floatArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def get(self, int: int, int2: int) -> float: ...
    def getArray(self) -> typing.MutableSequence[float]: ...
    def inverse(self) -> bool: ...
    def inverseTranspose(self) -> bool: ...
    def load(self, matrix4f: 'Matrix4f') -> None: ...
    def loadFrustum(self, float: float, float2: float, float3: float, float4: float, float5: float, float6: float) -> None: ...
    def loadIdentity(self) -> None: ...
    def loadMultiply(self, matrix4f: 'Matrix4f', matrix4f2: 'Matrix4f') -> None: ...
    def loadOrtho(self, float: float, float2: float, float3: float, float4: float, float5: float, float6: float) -> None: ...
    def loadOrthoWindow(self, int: int, int2: int) -> None: ...
    def loadPerspective(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    def loadProjectionNormalized(self, int: int, int2: int) -> None: ...
    def loadRotate(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    def loadScale(self, float: float, float2: float, float3: float) -> None: ...
    def loadTranslate(self, float: float, float2: float, float3: float) -> None: ...
    def multiply(self, matrix4f: 'Matrix4f') -> None: ...
    def rotate(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    def scale(self, float: float, float2: float, float3: float) -> None: ...
    def set(self, int: int, int2: int, float: float) -> None: ...
    def translate(self, float: float, float2: float, float3: float) -> None: ...
    def transpose(self) -> None: ...

class RSRuntimeException(java.lang.RuntimeException):
    def __init__(self, string: str): ...

class RenderScript:
    CREATE_FLAG_LOW_LATENCY: typing.ClassVar[int] = ...
    CREATE_FLAG_LOW_POWER: typing.ClassVar[int] = ...
    CREATE_FLAG_NONE: typing.ClassVar[int] = ...
    def contextDump(self) -> None: ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context) -> 'RenderScript': ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, contextType: 'RenderScript.ContextType') -> 'RenderScript': ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, contextType: 'RenderScript.ContextType', int: int) -> 'RenderScript': ...
    @staticmethod
    def createMultiContext(context: android.content.Context, contextType: 'RenderScript.ContextType', int: int, int2: int) -> 'RenderScript': ...
    def destroy(self) -> None: ...
    def finish(self) -> None: ...
    def getApplicationContext(self) -> android.content.Context: ...
    def getErrorHandler(self) -> 'RenderScript.RSErrorHandler': ...
    def getMessageHandler(self) -> 'RenderScript.RSMessageHandler': ...
    @staticmethod
    def getMinorVersion() -> int: ...
    @staticmethod
    def releaseAllContexts() -> None: ...
    def sendMessage(self, int: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def setErrorHandler(self, rSErrorHandler: 'RenderScript.RSErrorHandler') -> None: ...
    def setMessageHandler(self, rSMessageHandler: 'RenderScript.RSMessageHandler') -> None: ...
    def setPriority(self, priority: 'RenderScript.Priority') -> None: ...
    class ContextType(java.lang.Enum['RenderScript.ContextType']):
        NORMAL: typing.ClassVar['RenderScript.ContextType'] = ...
        DEBUG: typing.ClassVar['RenderScript.ContextType'] = ...
        PROFILE: typing.ClassVar['RenderScript.ContextType'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'RenderScript.ContextType': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['RenderScript.ContextType']: ...
    class Priority(java.lang.Enum['RenderScript.Priority']):
        LOW: typing.ClassVar['RenderScript.Priority'] = ...
        NORMAL: typing.ClassVar['RenderScript.Priority'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'RenderScript.Priority': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['RenderScript.Priority']: ...
    class RSErrorHandler(java.lang.Runnable):
        def __init__(self): ...
        def run(self) -> None: ...
    class RSMessageHandler(java.lang.Runnable):
        def __init__(self): ...
        def run(self) -> None: ...

class Short2:
    x: int = ...
    y: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, short: int, short2: int): ...

class Short3:
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, short: int, short2: int, short3: int): ...

class Short4:
    w: int = ...
    x: int = ...
    y: int = ...
    z: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, short: int, short2: int, short3: int, short4: int): ...

class Allocation(BaseObj):
    USAGE_GRAPHICS_CONSTANTS: typing.ClassVar[int] = ...
    USAGE_GRAPHICS_RENDER_TARGET: typing.ClassVar[int] = ...
    USAGE_GRAPHICS_TEXTURE: typing.ClassVar[int] = ...
    USAGE_GRAPHICS_VERTEX: typing.ClassVar[int] = ...
    USAGE_IO_INPUT: typing.ClassVar[int] = ...
    USAGE_IO_OUTPUT: typing.ClassVar[int] = ...
    USAGE_SCRIPT: typing.ClassVar[int] = ...
    USAGE_SHARED: typing.ClassVar[int] = ...
    @typing.overload
    def copy1DRangeFrom(self, int: int, int2: int, allocation: 'Allocation', int3: int) -> None: ...
    @typing.overload
    def copy1DRangeFrom(self, int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copy1DRangeFrom(self, int: int, int2: int, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeFrom(self, int: int, int2: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeFrom(self, int: int, int2: int, object: typing.Any) -> None: ...
    @typing.overload
    def copy1DRangeFrom(self, int: int, int2: int, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeFromUnchecked(self, int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copy1DRangeFromUnchecked(self, int: int, int2: int, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeFromUnchecked(self, int: int, int2: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeFromUnchecked(self, int: int, int2: int, object: typing.Any) -> None: ...
    @typing.overload
    def copy1DRangeFromUnchecked(self, int: int, int2: int, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeTo(self, int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copy1DRangeTo(self, int: int, int2: int, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeTo(self, int: int, int2: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeTo(self, int: int, int2: int, object: typing.Any) -> None: ...
    @typing.overload
    def copy1DRangeTo(self, int: int, int2: int, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeToUnchecked(self, int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copy1DRangeToUnchecked(self, int: int, int2: int, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeToUnchecked(self, int: int, int2: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy1DRangeToUnchecked(self, int: int, int2: int, object: typing.Any) -> None: ...
    @typing.overload
    def copy1DRangeToUnchecked(self, int: int, int2: int, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, bitmap: android.graphics.Bitmap) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, int3: int, int4: int, allocation: 'Allocation', int5: int, int6: int) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, int3: int, int4: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, int3: int, int4: int, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, int3: int, int4: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, int3: int, int4: int, object: typing.Any) -> None: ...
    @typing.overload
    def copy2DRangeFrom(self, int: int, int2: int, int3: int, int4: int, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy2DRangeTo(self, int: int, int2: int, int3: int, int4: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copy2DRangeTo(self, int: int, int2: int, int3: int, int4: int, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copy2DRangeTo(self, int: int, int2: int, int3: int, int4: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy2DRangeTo(self, int: int, int2: int, int3: int, int4: int, object: typing.Any) -> None: ...
    @typing.overload
    def copy2DRangeTo(self, int: int, int2: int, int3: int, int4: int, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copy3DRangeFrom(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int, allocation: 'Allocation', int7: int, int8: int, int9: int) -> None: ...
    @typing.overload
    def copy3DRangeFrom(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int, object: typing.Any) -> None: ...
    def copy3DRangeTo(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int, object: typing.Any) -> None: ...
    @typing.overload
    def copyFrom(self, bitmap: android.graphics.Bitmap) -> None: ...
    @typing.overload
    def copyFrom(self, allocation: 'Allocation') -> None: ...
    @typing.overload
    def copyFrom(self, baseObjArray: typing.Union[typing.List[BaseObj], jpype.JArray]) -> None: ...
    @typing.overload
    def copyFrom(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copyFrom(self, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copyFrom(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copyFrom(self, object: typing.Any) -> None: ...
    @typing.overload
    def copyFrom(self, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copyFromUnchecked(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copyFromUnchecked(self, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copyFromUnchecked(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copyFromUnchecked(self, object: typing.Any) -> None: ...
    @typing.overload
    def copyFromUnchecked(self, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copyTo(self, bitmap: android.graphics.Bitmap) -> None: ...
    @typing.overload
    def copyTo(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def copyTo(self, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    @typing.overload
    def copyTo(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def copyTo(self, object: typing.Any) -> None: ...
    @typing.overload
    def copyTo(self, shortArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @staticmethod
    def createAllocations(renderScript: RenderScript, type: 'Type', int: int, int2: int) -> typing.MutableSequence['Allocation']: ...
    @typing.overload
    @staticmethod
    def createCubemapFromBitmap(renderScript: RenderScript, bitmap: android.graphics.Bitmap) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createCubemapFromBitmap(renderScript: RenderScript, bitmap: android.graphics.Bitmap, mipmapControl: 'Allocation.MipmapControl', int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createCubemapFromCubeFaces(renderScript: RenderScript, bitmap: android.graphics.Bitmap, bitmap2: android.graphics.Bitmap, bitmap3: android.graphics.Bitmap, bitmap4: android.graphics.Bitmap, bitmap5: android.graphics.Bitmap, bitmap6: android.graphics.Bitmap) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createCubemapFromCubeFaces(renderScript: RenderScript, bitmap: android.graphics.Bitmap, bitmap2: android.graphics.Bitmap, bitmap3: android.graphics.Bitmap, bitmap4: android.graphics.Bitmap, bitmap5: android.graphics.Bitmap, bitmap6: android.graphics.Bitmap, mipmapControl: 'Allocation.MipmapControl', int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createFromBitmap(renderScript: RenderScript, bitmap: android.graphics.Bitmap) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createFromBitmap(renderScript: RenderScript, bitmap: android.graphics.Bitmap, mipmapControl: 'Allocation.MipmapControl', int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createFromBitmapResource(renderScript: RenderScript, resources: android.content.res.Resources, int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createFromBitmapResource(renderScript: RenderScript, resources: android.content.res.Resources, int: int, mipmapControl: 'Allocation.MipmapControl', int2: int) -> 'Allocation': ...
    @staticmethod
    def createFromString(renderScript: RenderScript, string: str, int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createSized(renderScript: RenderScript, element: 'Element', int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createSized(renderScript: RenderScript, element: 'Element', int: int, int2: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, type: 'Type') -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, type: 'Type', mipmapControl: 'Allocation.MipmapControl', int: int) -> 'Allocation': ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, type: 'Type', int: int) -> 'Allocation': ...
    def destroy(self) -> None: ...
    def generateMipmaps(self) -> None: ...
    def getByteBuffer(self) -> java.nio.ByteBuffer: ...
    def getBytesSize(self) -> int: ...
    def getElement(self) -> 'Element': ...
    def getStride(self) -> int: ...
    def getSurface(self) -> android.view.Surface: ...
    def getTimeStamp(self) -> int: ...
    def getType(self) -> 'Type': ...
    def getUsage(self) -> int: ...
    def ioReceive(self) -> None: ...
    def ioSend(self) -> None: ...
    def resize(self, int: int) -> None: ...
    def setAutoPadding(self, boolean: bool) -> None: ...
    @typing.overload
    def setFromFieldPacker(self, int: int, fieldPacker: FieldPacker) -> None: ...
    @typing.overload
    def setFromFieldPacker(self, int: int, int2: int, fieldPacker: FieldPacker) -> None: ...
    @typing.overload
    def setFromFieldPacker(self, int: int, int2: int, int3: int, int4: int, fieldPacker: FieldPacker) -> None: ...
    def setOnBufferAvailableListener(self, onBufferAvailableListener: typing.Union['Allocation.OnBufferAvailableListener', typing.Callable]) -> None: ...
    def setSurface(self, surface: android.view.Surface) -> None: ...
    def syncAll(self, int: int) -> None: ...
    class MipmapControl(java.lang.Enum['Allocation.MipmapControl']):
        MIPMAP_NONE: typing.ClassVar['Allocation.MipmapControl'] = ...
        MIPMAP_FULL: typing.ClassVar['Allocation.MipmapControl'] = ...
        MIPMAP_ON_SYNC_TO_TEXTURE: typing.ClassVar['Allocation.MipmapControl'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Allocation.MipmapControl': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Allocation.MipmapControl']: ...
    class OnBufferAvailableListener:
        def onBufferAvailable(self, allocation: 'Allocation') -> None: ...

class Element(BaseObj):
    @staticmethod
    def ALLOCATION(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def A_8(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def BOOLEAN(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def ELEMENT(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F16(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F16_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F16_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F16_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F32(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F32_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F32_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F32_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F64(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F64_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F64_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def F64_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def FONT(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I16(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I16_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I16_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I16_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I32(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I32_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I32_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I32_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I64(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I64_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I64_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I64_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I8(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I8_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I8_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def I8_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def MATRIX4X4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def MATRIX_2X2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def MATRIX_3X3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def MATRIX_4X4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def MESH(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def PROGRAM_FRAGMENT(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def PROGRAM_RASTER(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def PROGRAM_STORE(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def PROGRAM_VERTEX(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def RGBA_4444(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def RGBA_5551(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def RGBA_8888(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def RGB_565(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def RGB_888(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def SAMPLER(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def SCRIPT(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def TYPE(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U16(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U16_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U16_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U16_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U32(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U32_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U32_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U32_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U64(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U64_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U64_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U64_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U8(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U8_2(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U8_3(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def U8_4(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def YUV(renderScript: RenderScript) -> 'Element': ...
    @staticmethod
    def createPixel(renderScript: RenderScript, dataType: 'Element.DataType', dataKind: 'Element.DataKind') -> 'Element': ...
    @staticmethod
    def createVector(renderScript: RenderScript, dataType: 'Element.DataType', int: int) -> 'Element': ...
    def getBytesSize(self) -> int: ...
    def getDataKind(self) -> 'Element.DataKind': ...
    def getDataType(self) -> 'Element.DataType': ...
    def getSubElement(self, int: int) -> 'Element': ...
    def getSubElementArraySize(self, int: int) -> int: ...
    def getSubElementCount(self) -> int: ...
    def getSubElementName(self, int: int) -> str: ...
    def getSubElementOffsetBytes(self, int: int) -> int: ...
    def getVectorSize(self) -> int: ...
    def isCompatible(self, element: 'Element') -> bool: ...
    def isComplex(self) -> bool: ...
    class Builder:
        def __init__(self, renderScript: RenderScript): ...
        @typing.overload
        def add(self, element: 'Element', string: str) -> 'Element.Builder': ...
        @typing.overload
        def add(self, element: 'Element', string: str, int: int) -> 'Element.Builder': ...
        def create(self) -> 'Element': ...
    class DataKind(java.lang.Enum['Element.DataKind']):
        USER: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_L: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_A: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_LA: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_RGB: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_RGBA: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_DEPTH: typing.ClassVar['Element.DataKind'] = ...
        PIXEL_YUV: typing.ClassVar['Element.DataKind'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Element.DataKind': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Element.DataKind']: ...
    class DataType(java.lang.Enum['Element.DataType']):
        NONE: typing.ClassVar['Element.DataType'] = ...
        FLOAT_16: typing.ClassVar['Element.DataType'] = ...
        FLOAT_32: typing.ClassVar['Element.DataType'] = ...
        FLOAT_64: typing.ClassVar['Element.DataType'] = ...
        SIGNED_8: typing.ClassVar['Element.DataType'] = ...
        SIGNED_16: typing.ClassVar['Element.DataType'] = ...
        SIGNED_32: typing.ClassVar['Element.DataType'] = ...
        SIGNED_64: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_8: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_16: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_32: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_64: typing.ClassVar['Element.DataType'] = ...
        BOOLEAN: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_5_6_5: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_5_5_5_1: typing.ClassVar['Element.DataType'] = ...
        UNSIGNED_4_4_4_4: typing.ClassVar['Element.DataType'] = ...
        MATRIX_4X4: typing.ClassVar['Element.DataType'] = ...
        MATRIX_3X3: typing.ClassVar['Element.DataType'] = ...
        MATRIX_2X2: typing.ClassVar['Element.DataType'] = ...
        RS_ELEMENT: typing.ClassVar['Element.DataType'] = ...
        RS_TYPE: typing.ClassVar['Element.DataType'] = ...
        RS_ALLOCATION: typing.ClassVar['Element.DataType'] = ...
        RS_SAMPLER: typing.ClassVar['Element.DataType'] = ...
        RS_SCRIPT: typing.ClassVar['Element.DataType'] = ...
        RS_MESH: typing.ClassVar['Element.DataType'] = ...
        RS_PROGRAM_FRAGMENT: typing.ClassVar['Element.DataType'] = ...
        RS_PROGRAM_VERTEX: typing.ClassVar['Element.DataType'] = ...
        RS_PROGRAM_RASTER: typing.ClassVar['Element.DataType'] = ...
        RS_PROGRAM_STORE: typing.ClassVar['Element.DataType'] = ...
        RS_FONT: typing.ClassVar['Element.DataType'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Element.DataType': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Element.DataType']: ...

class RSDriverException(RSRuntimeException):
    def __init__(self, string: str): ...

class RSIllegalArgumentException(RSRuntimeException):
    def __init__(self, string: str): ...

class RSInvalidStateException(RSRuntimeException):
    def __init__(self, string: str): ...

class Sampler(BaseObj):
    @staticmethod
    def CLAMP_LINEAR(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def CLAMP_LINEAR_MIP_LINEAR(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def CLAMP_NEAREST(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def MIRRORED_REPEAT_LINEAR(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def MIRRORED_REPEAT_LINEAR_MIP_LINEAR(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def MIRRORED_REPEAT_NEAREST(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def WRAP_LINEAR(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def WRAP_LINEAR_MIP_LINEAR(renderScript: RenderScript) -> 'Sampler': ...
    @staticmethod
    def WRAP_NEAREST(renderScript: RenderScript) -> 'Sampler': ...
    def getAnisotropy(self) -> float: ...
    def getMagnification(self) -> 'Sampler.Value': ...
    def getMinification(self) -> 'Sampler.Value': ...
    def getWrapS(self) -> 'Sampler.Value': ...
    def getWrapT(self) -> 'Sampler.Value': ...
    class Builder:
        def __init__(self, renderScript: RenderScript): ...
        def create(self) -> 'Sampler': ...
        def setAnisotropy(self, float: float) -> None: ...
        def setMagnification(self, value: 'Sampler.Value') -> None: ...
        def setMinification(self, value: 'Sampler.Value') -> None: ...
        def setWrapS(self, value: 'Sampler.Value') -> None: ...
        def setWrapT(self, value: 'Sampler.Value') -> None: ...
    class Value(java.lang.Enum['Sampler.Value']):
        NEAREST: typing.ClassVar['Sampler.Value'] = ...
        LINEAR: typing.ClassVar['Sampler.Value'] = ...
        LINEAR_MIP_LINEAR: typing.ClassVar['Sampler.Value'] = ...
        LINEAR_MIP_NEAREST: typing.ClassVar['Sampler.Value'] = ...
        WRAP: typing.ClassVar['Sampler.Value'] = ...
        CLAMP: typing.ClassVar['Sampler.Value'] = ...
        MIRRORED_REPEAT: typing.ClassVar['Sampler.Value'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Sampler.Value': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Sampler.Value']: ...

class Script(BaseObj):
    def bindAllocation(self, allocation: Allocation, int: int) -> None: ...
    def getVarB(self, int: int) -> bool: ...
    def getVarD(self, int: int) -> float: ...
    def getVarF(self, int: int) -> float: ...
    def getVarI(self, int: int) -> int: ...
    def getVarJ(self, int: int) -> int: ...
    def getVarV(self, int: int, fieldPacker: FieldPacker) -> None: ...
    def setTimeZone(self, string: str) -> None: ...
    @typing.overload
    def setVar(self, int: int, baseObj: BaseObj) -> None: ...
    @typing.overload
    def setVar(self, int: int, fieldPacker: FieldPacker) -> None: ...
    @typing.overload
    def setVar(self, int: int, fieldPacker: FieldPacker, element: Element, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    @typing.overload
    def setVar(self, int: int, boolean: bool) -> None: ...
    @typing.overload
    def setVar(self, int: int, double: float) -> None: ...
    @typing.overload
    def setVar(self, int: int, float: float) -> None: ...
    @typing.overload
    def setVar(self, int: int, int2: int) -> None: ...
    @typing.overload
    def setVar(self, int: int, long: int) -> None: ...
    class Builder: ...
    class FieldBase:
        def getAllocation(self) -> Allocation: ...
        def getElement(self) -> Element: ...
        def getType(self) -> 'Type': ...
        def updateAllocation(self) -> None: ...
    class FieldID(BaseObj): ...
    class InvokeID(BaseObj): ...
    class KernelID(BaseObj): ...
    class LaunchOptions:
        def __init__(self): ...
        def getXEnd(self) -> int: ...
        def getXStart(self) -> int: ...
        def getYEnd(self) -> int: ...
        def getYStart(self) -> int: ...
        def getZEnd(self) -> int: ...
        def getZStart(self) -> int: ...
        def setX(self, int: int, int2: int) -> 'Script.LaunchOptions': ...
        def setY(self, int: int, int2: int) -> 'Script.LaunchOptions': ...
        def setZ(self, int: int, int2: int) -> 'Script.LaunchOptions': ...

class ScriptGroup(BaseObj):
    def destroy(self) -> None: ...
    @typing.overload
    def execute(self, *object: typing.Any) -> typing.MutableSequence[typing.Any]: ...
    @typing.overload
    def execute(self) -> None: ...
    def setInput(self, kernelID: Script.KernelID, allocation: Allocation) -> None: ...
    def setOutput(self, kernelID: Script.KernelID, allocation: Allocation) -> None: ...
    class Binding:
        def __init__(self, fieldID: Script.FieldID, object: typing.Any): ...
    class Builder:
        def __init__(self, renderScript: RenderScript): ...
        @typing.overload
        def addConnection(self, type: 'Type', kernelID: Script.KernelID, fieldID: Script.FieldID) -> 'ScriptGroup.Builder': ...
        @typing.overload
        def addConnection(self, type: 'Type', kernelID: Script.KernelID, kernelID2: Script.KernelID) -> 'ScriptGroup.Builder': ...
        def addKernel(self, kernelID: Script.KernelID) -> 'ScriptGroup.Builder': ...
        def create(self) -> 'ScriptGroup': ...
    class Builder2:
        def __init__(self, renderScript: RenderScript): ...
        def addInput(self) -> 'ScriptGroup.Input': ...
        def addInvoke(self, invokeID: Script.InvokeID, *object: typing.Any) -> 'ScriptGroup.Closure': ...
        def addKernel(self, kernelID: Script.KernelID, type: 'Type', *object: typing.Any) -> 'ScriptGroup.Closure': ...
        def create(self, string: str, *future: 'ScriptGroup.Future') -> 'ScriptGroup': ...
    class Closure(BaseObj):
        def destroy(self) -> None: ...
        def getGlobal(self, fieldID: Script.FieldID) -> 'ScriptGroup.Future': ...
        def getReturn(self) -> 'ScriptGroup.Future': ...
    class Future: ...
    class Input: ...

class Type(BaseObj):
    @staticmethod
    def createX(renderScript: RenderScript, element: Element, int: int) -> 'Type': ...
    @staticmethod
    def createXY(renderScript: RenderScript, element: Element, int: int, int2: int) -> 'Type': ...
    @staticmethod
    def createXYZ(renderScript: RenderScript, element: Element, int: int, int2: int, int3: int) -> 'Type': ...
    def getCount(self) -> int: ...
    def getElement(self) -> Element: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def getYuv(self) -> int: ...
    def getZ(self) -> int: ...
    def hasFaces(self) -> bool: ...
    def hasMipmaps(self) -> bool: ...
    class Builder:
        def __init__(self, renderScript: RenderScript, element: Element): ...
        def create(self) -> 'Type': ...
        def setFaces(self, boolean: bool) -> 'Type.Builder': ...
        def setMipmaps(self, boolean: bool) -> 'Type.Builder': ...
        def setX(self, int: int) -> 'Type.Builder': ...
        def setY(self, int: int) -> 'Type.Builder': ...
        def setYuvFormat(self, int: int) -> 'Type.Builder': ...
        def setZ(self, int: int) -> 'Type.Builder': ...
    class CubemapFace(java.lang.Enum['Type.CubemapFace']):
        POSITIVE_X: typing.ClassVar['Type.CubemapFace'] = ...
        NEGATIVE_X: typing.ClassVar['Type.CubemapFace'] = ...
        POSITIVE_Y: typing.ClassVar['Type.CubemapFace'] = ...
        NEGATIVE_Y: typing.ClassVar['Type.CubemapFace'] = ...
        POSITIVE_Z: typing.ClassVar['Type.CubemapFace'] = ...
        NEGATIVE_Z: typing.ClassVar['Type.CubemapFace'] = ...
        POSITVE_X: typing.ClassVar['Type.CubemapFace'] = ...
        POSITVE_Y: typing.ClassVar['Type.CubemapFace'] = ...
        POSITVE_Z: typing.ClassVar['Type.CubemapFace'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Type.CubemapFace': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Type.CubemapFace']: ...

class AllocationAdapter(Allocation):
    @staticmethod
    def create1D(renderScript: RenderScript, allocation: Allocation) -> 'AllocationAdapter': ...
    @staticmethod
    def create2D(renderScript: RenderScript, allocation: Allocation) -> 'AllocationAdapter': ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, type: Type) -> Allocation: ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, type: Type, mipmapControl: Allocation.MipmapControl, int: int) -> Allocation: ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, type: Type, int: int) -> Allocation: ...
    @typing.overload
    @staticmethod
    def createTyped(renderScript: RenderScript, allocation: Allocation, type: Type) -> 'AllocationAdapter': ...
    def resize(self, int: int) -> None: ...
    def setFace(self, cubemapFace: Type.CubemapFace) -> None: ...
    def setLOD(self, int: int) -> None: ...
    def setX(self, int: int) -> None: ...
    def setY(self, int: int) -> None: ...
    def setZ(self, int: int) -> None: ...

class ScriptC(Script): ...

class ScriptIntrinsic(Script): ...

class ScriptIntrinsic3DLUT(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsic3DLUT': ...
    @typing.overload
    def forEach(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getKernelID(self) -> Script.KernelID: ...
    def setLUT(self, allocation: Allocation) -> None: ...

class ScriptIntrinsicBLAS(ScriptIntrinsic):
    CONJ_TRANSPOSE: typing.ClassVar[int] = ...
    LEFT: typing.ClassVar[int] = ...
    LOWER: typing.ClassVar[int] = ...
    NON_UNIT: typing.ClassVar[int] = ...
    NO_TRANSPOSE: typing.ClassVar[int] = ...
    RIGHT: typing.ClassVar[int] = ...
    TRANSPOSE: typing.ClassVar[int] = ...
    UNIT: typing.ClassVar[int] = ...
    UPPER: typing.ClassVar[int] = ...
    def BNNM(self, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation, int3: int, int4: int) -> None: ...
    def CGBMV(self, int: int, int2: int, int3: int, float2: Float2, allocation: Allocation, allocation2: Allocation, int4: int, float22: Float2, allocation3: Allocation, int5: int) -> None: ...
    def CGEMM(self, int: int, int2: int, float2: Float2, allocation: Allocation, allocation2: Allocation, float22: Float2, allocation3: Allocation) -> None: ...
    def CGEMV(self, int: int, float2: Float2, allocation: Allocation, allocation2: Allocation, int2: int, float22: Float2, allocation3: Allocation, int3: int) -> None: ...
    def CGERC(self, float2: Float2, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation) -> None: ...
    def CGERU(self, float2: Float2, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation) -> None: ...
    def CHBMV(self, int: int, int2: int, float2: Float2, allocation: Allocation, allocation2: Allocation, int3: int, float22: Float2, allocation3: Allocation, int4: int) -> None: ...
    def CHEMM(self, int: int, int2: int, float2: Float2, allocation: Allocation, allocation2: Allocation, float22: Float2, allocation3: Allocation) -> None: ...
    def CHEMV(self, int: int, float2: Float2, allocation: Allocation, allocation2: Allocation, int2: int, float22: Float2, allocation3: Allocation, int3: int) -> None: ...
    def CHER(self, int: int, float: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def CHER2(self, int: int, float2: Float2, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def CHER2K(self, int: int, int2: int, float2: Float2, allocation: Allocation, allocation2: Allocation, float2: float, allocation3: Allocation) -> None: ...
    def CHERK(self, int: int, int2: int, float: float, allocation: Allocation, float2: float, allocation2: Allocation) -> None: ...
    def CHPMV(self, int: int, float2: Float2, allocation: Allocation, allocation2: Allocation, int2: int, float22: Float2, allocation3: Allocation, int3: int) -> None: ...
    def CHPR(self, int: int, float: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def CHPR2(self, int: int, float2: Float2, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def CSYMM(self, int: int, int2: int, float2: Float2, allocation: Allocation, allocation2: Allocation, float22: Float2, allocation3: Allocation) -> None: ...
    def CSYR2K(self, int: int, int2: int, float2: Float2, allocation: Allocation, allocation2: Allocation, float22: Float2, allocation3: Allocation) -> None: ...
    def CSYRK(self, int: int, int2: int, float2: Float2, allocation: Allocation, float22: Float2, allocation2: Allocation) -> None: ...
    def CTBMV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def CTBSV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def CTPMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def CTPSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def CTRMM(self, int: int, int2: int, int3: int, int4: int, float2: Float2, allocation: Allocation, allocation2: Allocation) -> None: ...
    def CTRMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def CTRSM(self, int: int, int2: int, int3: int, int4: int, float2: Float2, allocation: Allocation, allocation2: Allocation) -> None: ...
    def CTRSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def DGBMV(self, int: int, int2: int, int3: int, double: float, allocation: Allocation, allocation2: Allocation, int4: int, double2: float, allocation3: Allocation, int5: int) -> None: ...
    def DGEMM(self, int: int, int2: int, double: float, allocation: Allocation, allocation2: Allocation, double2: float, allocation3: Allocation) -> None: ...
    def DGEMV(self, int: int, double: float, allocation: Allocation, allocation2: Allocation, int2: int, double2: float, allocation3: Allocation, int3: int) -> None: ...
    def DGER(self, double: float, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation) -> None: ...
    def DSBMV(self, int: int, int2: int, double: float, allocation: Allocation, allocation2: Allocation, int3: int, double2: float, allocation3: Allocation, int4: int) -> None: ...
    def DSPMV(self, int: int, double: float, allocation: Allocation, allocation2: Allocation, int2: int, double2: float, allocation3: Allocation, int3: int) -> None: ...
    def DSPR(self, int: int, double: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def DSPR2(self, int: int, double: float, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def DSYMM(self, int: int, int2: int, double: float, allocation: Allocation, allocation2: Allocation, double2: float, allocation3: Allocation) -> None: ...
    def DSYMV(self, int: int, double: float, allocation: Allocation, allocation2: Allocation, int2: int, double2: float, allocation3: Allocation, int3: int) -> None: ...
    def DSYR(self, int: int, double: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def DSYR2(self, int: int, double: float, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def DSYR2K(self, int: int, int2: int, double: float, allocation: Allocation, allocation2: Allocation, double2: float, allocation3: Allocation) -> None: ...
    def DSYRK(self, int: int, int2: int, double: float, allocation: Allocation, double2: float, allocation2: Allocation) -> None: ...
    def DTBMV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def DTBSV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def DTPMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def DTPSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def DTRMM(self, int: int, int2: int, int3: int, int4: int, double: float, allocation: Allocation, allocation2: Allocation) -> None: ...
    def DTRMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def DTRSM(self, int: int, int2: int, int3: int, int4: int, double: float, allocation: Allocation, allocation2: Allocation) -> None: ...
    def DTRSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def SGBMV(self, int: int, int2: int, int3: int, float: float, allocation: Allocation, allocation2: Allocation, int4: int, float2: float, allocation3: Allocation, int5: int) -> None: ...
    def SGEMM(self, int: int, int2: int, float: float, allocation: Allocation, allocation2: Allocation, float2: float, allocation3: Allocation) -> None: ...
    def SGEMV(self, int: int, float: float, allocation: Allocation, allocation2: Allocation, int2: int, float2: float, allocation3: Allocation, int3: int) -> None: ...
    def SGER(self, float: float, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation) -> None: ...
    def SSBMV(self, int: int, int2: int, float: float, allocation: Allocation, allocation2: Allocation, int3: int, float2: float, allocation3: Allocation, int4: int) -> None: ...
    def SSPMV(self, int: int, float: float, allocation: Allocation, allocation2: Allocation, int2: int, float2: float, allocation3: Allocation, int3: int) -> None: ...
    def SSPR(self, int: int, float: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def SSPR2(self, int: int, float: float, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def SSYMM(self, int: int, int2: int, float: float, allocation: Allocation, allocation2: Allocation, float2: float, allocation3: Allocation) -> None: ...
    def SSYMV(self, int: int, float: float, allocation: Allocation, allocation2: Allocation, int2: int, float2: float, allocation3: Allocation, int3: int) -> None: ...
    def SSYR(self, int: int, float: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def SSYR2(self, int: int, float: float, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def SSYR2K(self, int: int, int2: int, float: float, allocation: Allocation, allocation2: Allocation, float2: float, allocation3: Allocation) -> None: ...
    def SSYRK(self, int: int, int2: int, float: float, allocation: Allocation, float2: float, allocation2: Allocation) -> None: ...
    def STBMV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def STBSV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def STPMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def STPSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def STRMM(self, int: int, int2: int, int3: int, int4: int, float: float, allocation: Allocation, allocation2: Allocation) -> None: ...
    def STRMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def STRSM(self, int: int, int2: int, int3: int, int4: int, float: float, allocation: Allocation, allocation2: Allocation) -> None: ...
    def STRSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def ZGBMV(self, int: int, int2: int, int3: int, double2: Double2, allocation: Allocation, allocation2: Allocation, int4: int, double22: Double2, allocation3: Allocation, int5: int) -> None: ...
    def ZGEMM(self, int: int, int2: int, double2: Double2, allocation: Allocation, allocation2: Allocation, double22: Double2, allocation3: Allocation) -> None: ...
    def ZGEMV(self, int: int, double2: Double2, allocation: Allocation, allocation2: Allocation, int2: int, double22: Double2, allocation3: Allocation, int3: int) -> None: ...
    def ZGERC(self, double2: Double2, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation) -> None: ...
    def ZGERU(self, double2: Double2, allocation: Allocation, int: int, allocation2: Allocation, int2: int, allocation3: Allocation) -> None: ...
    def ZHBMV(self, int: int, int2: int, double2: Double2, allocation: Allocation, allocation2: Allocation, int3: int, double22: Double2, allocation3: Allocation, int4: int) -> None: ...
    def ZHEMM(self, int: int, int2: int, double2: Double2, allocation: Allocation, allocation2: Allocation, double22: Double2, allocation3: Allocation) -> None: ...
    def ZHEMV(self, int: int, double2: Double2, allocation: Allocation, allocation2: Allocation, int2: int, double22: Double2, allocation3: Allocation, int3: int) -> None: ...
    def ZHER(self, int: int, double: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def ZHER2(self, int: int, double2: Double2, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def ZHER2K(self, int: int, int2: int, double2: Double2, allocation: Allocation, allocation2: Allocation, double2: float, allocation3: Allocation) -> None: ...
    def ZHERK(self, int: int, int2: int, double: float, allocation: Allocation, double2: float, allocation2: Allocation) -> None: ...
    def ZHPMV(self, int: int, double2: Double2, allocation: Allocation, allocation2: Allocation, int2: int, double22: Double2, allocation3: Allocation, int3: int) -> None: ...
    def ZHPR(self, int: int, double: float, allocation: Allocation, int2: int, allocation2: Allocation) -> None: ...
    def ZHPR2(self, int: int, double2: Double2, allocation: Allocation, int2: int, allocation2: Allocation, int3: int, allocation3: Allocation) -> None: ...
    def ZSYMM(self, int: int, int2: int, double2: Double2, allocation: Allocation, allocation2: Allocation, double22: Double2, allocation3: Allocation) -> None: ...
    def ZSYR2K(self, int: int, int2: int, double2: Double2, allocation: Allocation, allocation2: Allocation, double22: Double2, allocation3: Allocation) -> None: ...
    def ZSYRK(self, int: int, int2: int, double2: Double2, allocation: Allocation, double22: Double2, allocation2: Allocation) -> None: ...
    def ZTBMV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def ZTBSV(self, int: int, int2: int, int3: int, int4: int, allocation: Allocation, allocation2: Allocation, int5: int) -> None: ...
    def ZTPMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def ZTPSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def ZTRMM(self, int: int, int2: int, int3: int, int4: int, double2: Double2, allocation: Allocation, allocation2: Allocation) -> None: ...
    def ZTRMV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    def ZTRSM(self, int: int, int2: int, int3: int, int4: int, double2: Double2, allocation: Allocation, allocation2: Allocation) -> None: ...
    def ZTRSV(self, int: int, int2: int, int3: int, allocation: Allocation, allocation2: Allocation, int4: int) -> None: ...
    @staticmethod
    def create(renderScript: RenderScript) -> 'ScriptIntrinsicBLAS': ...

class ScriptIntrinsicBlend(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicBlend': ...
    @typing.overload
    def forEachAdd(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachAdd(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachClear(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachClear(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachDst(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachDst(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachDstAtop(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachDstAtop(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachDstIn(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachDstIn(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachDstOut(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachDstOut(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachDstOver(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachDstOver(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachMultiply(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachMultiply(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachSrc(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachSrc(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachSrcAtop(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachSrcAtop(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachSrcIn(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachSrcIn(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachSrcOut(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachSrcOut(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachSrcOver(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachSrcOver(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachSubtract(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachSubtract(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEachXor(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEachXor(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getKernelIDAdd(self) -> Script.KernelID: ...
    def getKernelIDClear(self) -> Script.KernelID: ...
    def getKernelIDDst(self) -> Script.KernelID: ...
    def getKernelIDDstAtop(self) -> Script.KernelID: ...
    def getKernelIDDstIn(self) -> Script.KernelID: ...
    def getKernelIDDstOut(self) -> Script.KernelID: ...
    def getKernelIDDstOver(self) -> Script.KernelID: ...
    def getKernelIDMultiply(self) -> Script.KernelID: ...
    def getKernelIDSrc(self) -> Script.KernelID: ...
    def getKernelIDSrcAtop(self) -> Script.KernelID: ...
    def getKernelIDSrcIn(self) -> Script.KernelID: ...
    def getKernelIDSrcOut(self) -> Script.KernelID: ...
    def getKernelIDSrcOver(self) -> Script.KernelID: ...
    def getKernelIDSubtract(self) -> Script.KernelID: ...
    def getKernelIDXor(self) -> Script.KernelID: ...

class ScriptIntrinsicBlur(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicBlur': ...
    @typing.overload
    def forEach(self, allocation: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getFieldID_Input(self) -> Script.FieldID: ...
    def getKernelID(self) -> Script.KernelID: ...
    def setInput(self, allocation: Allocation) -> None: ...
    def setRadius(self, float: float) -> None: ...

class ScriptIntrinsicColorMatrix(ScriptIntrinsic):
    @typing.overload
    @staticmethod
    def create(renderScript: RenderScript) -> 'ScriptIntrinsicColorMatrix': ...
    @typing.overload
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicColorMatrix': ...
    @typing.overload
    def forEach(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getKernelID(self) -> Script.KernelID: ...
    @typing.overload
    def setAdd(self, float4: Float4) -> None: ...
    @typing.overload
    def setAdd(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    @typing.overload
    def setColorMatrix(self, matrix3f: Matrix3f) -> None: ...
    @typing.overload
    def setColorMatrix(self, matrix4f: Matrix4f) -> None: ...
    def setGreyscale(self) -> None: ...
    def setRGBtoYUV(self) -> None: ...
    def setYUVtoRGB(self) -> None: ...

class ScriptIntrinsicConvolve3x3(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicConvolve3x3': ...
    @typing.overload
    def forEach(self, allocation: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getFieldID_Input(self) -> Script.FieldID: ...
    def getKernelID(self) -> Script.KernelID: ...
    def setCoefficients(self, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setInput(self, allocation: Allocation) -> None: ...

class ScriptIntrinsicConvolve5x5(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicConvolve5x5': ...
    @typing.overload
    def forEach(self, allocation: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getFieldID_Input(self) -> Script.FieldID: ...
    def getKernelID(self) -> Script.KernelID: ...
    def setCoefficients(self, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setInput(self, allocation: Allocation) -> None: ...

class ScriptIntrinsicHistogram(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicHistogram': ...
    @typing.overload
    def forEach(self, allocation: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    @typing.overload
    def forEach_Dot(self, allocation: Allocation) -> None: ...
    @typing.overload
    def forEach_Dot(self, allocation: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getFieldID_Input(self) -> Script.FieldID: ...
    def getKernelID_Separate(self) -> Script.KernelID: ...
    def setDotCoefficients(self, float: float, float2: float, float3: float, float4: float) -> None: ...
    def setOutput(self, allocation: Allocation) -> None: ...

class ScriptIntrinsicLUT(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicLUT': ...
    def destroy(self) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, allocation2: Allocation) -> None: ...
    @typing.overload
    def forEach(self, allocation: Allocation, allocation2: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getKernelID(self) -> Script.KernelID: ...
    def setAlpha(self, int: int, int2: int) -> None: ...
    def setBlue(self, int: int, int2: int) -> None: ...
    def setGreen(self, int: int, int2: int) -> None: ...
    def setRed(self, int: int, int2: int) -> None: ...

class ScriptIntrinsicResize(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript) -> 'ScriptIntrinsicResize': ...
    @typing.overload
    def forEach_bicubic(self, allocation: Allocation) -> None: ...
    @typing.overload
    def forEach_bicubic(self, allocation: Allocation, launchOptions: Script.LaunchOptions) -> None: ...
    def getFieldID_Input(self) -> Script.FieldID: ...
    def getKernelID_bicubic(self) -> Script.KernelID: ...
    def setInput(self, allocation: Allocation) -> None: ...

class ScriptIntrinsicYuvToRGB(ScriptIntrinsic):
    @staticmethod
    def create(renderScript: RenderScript, element: Element) -> 'ScriptIntrinsicYuvToRGB': ...
    def forEach(self, allocation: Allocation) -> None: ...
    def getFieldID_Input(self) -> Script.FieldID: ...
    def getKernelID(self) -> Script.KernelID: ...
    def setInput(self, allocation: Allocation) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.renderscript")``.

    Allocation: typing.Type[Allocation]
    AllocationAdapter: typing.Type[AllocationAdapter]
    BaseObj: typing.Type[BaseObj]
    Byte2: typing.Type[Byte2]
    Byte3: typing.Type[Byte3]
    Byte4: typing.Type[Byte4]
    Double2: typing.Type[Double2]
    Double3: typing.Type[Double3]
    Double4: typing.Type[Double4]
    Element: typing.Type[Element]
    FieldPacker: typing.Type[FieldPacker]
    Float2: typing.Type[Float2]
    Float3: typing.Type[Float3]
    Float4: typing.Type[Float4]
    Int2: typing.Type[Int2]
    Int3: typing.Type[Int3]
    Int4: typing.Type[Int4]
    Long2: typing.Type[Long2]
    Long3: typing.Type[Long3]
    Long4: typing.Type[Long4]
    Matrix2f: typing.Type[Matrix2f]
    Matrix3f: typing.Type[Matrix3f]
    Matrix4f: typing.Type[Matrix4f]
    RSDriverException: typing.Type[RSDriverException]
    RSIllegalArgumentException: typing.Type[RSIllegalArgumentException]
    RSInvalidStateException: typing.Type[RSInvalidStateException]
    RSRuntimeException: typing.Type[RSRuntimeException]
    RenderScript: typing.Type[RenderScript]
    Sampler: typing.Type[Sampler]
    Script: typing.Type[Script]
    ScriptC: typing.Type[ScriptC]
    ScriptGroup: typing.Type[ScriptGroup]
    ScriptIntrinsic: typing.Type[ScriptIntrinsic]
    ScriptIntrinsic3DLUT: typing.Type[ScriptIntrinsic3DLUT]
    ScriptIntrinsicBLAS: typing.Type[ScriptIntrinsicBLAS]
    ScriptIntrinsicBlend: typing.Type[ScriptIntrinsicBlend]
    ScriptIntrinsicBlur: typing.Type[ScriptIntrinsicBlur]
    ScriptIntrinsicColorMatrix: typing.Type[ScriptIntrinsicColorMatrix]
    ScriptIntrinsicConvolve3x3: typing.Type[ScriptIntrinsicConvolve3x3]
    ScriptIntrinsicConvolve5x5: typing.Type[ScriptIntrinsicConvolve5x5]
    ScriptIntrinsicHistogram: typing.Type[ScriptIntrinsicHistogram]
    ScriptIntrinsicLUT: typing.Type[ScriptIntrinsicLUT]
    ScriptIntrinsicResize: typing.Type[ScriptIntrinsicResize]
    ScriptIntrinsicYuvToRGB: typing.Type[ScriptIntrinsicYuvToRGB]
    Short2: typing.Type[Short2]
    Short3: typing.Type[Short3]
    Short4: typing.Type[Short4]
    Type: typing.Type[Type]
