
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.hardware.camera2.params
import android.location
import android.media
import android.os
import android.util
import android.view
import java.io
import java.lang
import java.nio
import java.util
import java.util.concurrent
import typing



class CameraAccessException(android.util.AndroidException):
    CAMERA_DISABLED: typing.ClassVar[int] = ...
    CAMERA_DISCONNECTED: typing.ClassVar[int] = ...
    CAMERA_ERROR: typing.ClassVar[int] = ...
    CAMERA_IN_USE: typing.ClassVar[int] = ...
    MAX_CAMERAS_IN_USE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, string: str): ...
    @typing.overload
    def __init__(self, int: int, string: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, int: int, throwable: java.lang.Throwable): ...
    def getReason(self) -> int: ...

class CameraCaptureSession(java.lang.AutoCloseable):
    def __init__(self): ...
    def abortCaptures(self) -> None: ...
    def capture(self, captureRequest: 'CaptureRequest', captureCallback: 'CameraCaptureSession.CaptureCallback', handler: android.os.Handler) -> int: ...
    def captureBurst(self, list: java.util.List['CaptureRequest'], captureCallback: 'CameraCaptureSession.CaptureCallback', handler: android.os.Handler) -> int: ...
    def captureBurstRequests(self, list: java.util.List['CaptureRequest'], executor: typing.Union[java.util.concurrent.Executor, typing.Callable], captureCallback: 'CameraCaptureSession.CaptureCallback') -> int: ...
    def captureSingleRequest(self, captureRequest: 'CaptureRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], captureCallback: 'CameraCaptureSession.CaptureCallback') -> int: ...
    def close(self) -> None: ...
    def finalizeOutputConfigurations(self, list: java.util.List[android.hardware.camera2.params.OutputConfiguration]) -> None: ...
    def getDevice(self) -> 'CameraDevice': ...
    def getInputSurface(self) -> android.view.Surface: ...
    def isReprocessable(self) -> bool: ...
    def prepare(self, surface: android.view.Surface) -> None: ...
    def setRepeatingBurst(self, list: java.util.List['CaptureRequest'], captureCallback: 'CameraCaptureSession.CaptureCallback', handler: android.os.Handler) -> int: ...
    def setRepeatingBurstRequests(self, list: java.util.List['CaptureRequest'], executor: typing.Union[java.util.concurrent.Executor, typing.Callable], captureCallback: 'CameraCaptureSession.CaptureCallback') -> int: ...
    def setRepeatingRequest(self, captureRequest: 'CaptureRequest', captureCallback: 'CameraCaptureSession.CaptureCallback', handler: android.os.Handler) -> int: ...
    def setSingleRepeatingRequest(self, captureRequest: 'CaptureRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], captureCallback: 'CameraCaptureSession.CaptureCallback') -> int: ...
    def stopRepeating(self) -> None: ...
    def supportsOfflineProcessing(self, surface: android.view.Surface) -> bool: ...
    def switchToOffline(self, collection: typing.Union[java.util.Collection[android.view.Surface], typing.Sequence[android.view.Surface], typing.Set[android.view.Surface]], executor: typing.Union[java.util.concurrent.Executor, typing.Callable], cameraOfflineSessionCallback: 'CameraOfflineSession.CameraOfflineSessionCallback') -> 'CameraOfflineSession': ...
    def updateOutputConfiguration(self, outputConfiguration: android.hardware.camera2.params.OutputConfiguration) -> None: ...
    class CaptureCallback:
        def __init__(self): ...
        def onCaptureBufferLost(self, cameraCaptureSession: 'CameraCaptureSession', captureRequest: 'CaptureRequest', surface: android.view.Surface, long: int) -> None: ...
        def onCaptureCompleted(self, cameraCaptureSession: 'CameraCaptureSession', captureRequest: 'CaptureRequest', totalCaptureResult: 'TotalCaptureResult') -> None: ...
        def onCaptureFailed(self, cameraCaptureSession: 'CameraCaptureSession', captureRequest: 'CaptureRequest', captureFailure: 'CaptureFailure') -> None: ...
        def onCaptureProgressed(self, cameraCaptureSession: 'CameraCaptureSession', captureRequest: 'CaptureRequest', captureResult: 'CaptureResult') -> None: ...
        def onCaptureSequenceAborted(self, cameraCaptureSession: 'CameraCaptureSession', int: int) -> None: ...
        def onCaptureSequenceCompleted(self, cameraCaptureSession: 'CameraCaptureSession', int: int, long: int) -> None: ...
        def onCaptureStarted(self, cameraCaptureSession: 'CameraCaptureSession', captureRequest: 'CaptureRequest', long: int, long2: int) -> None: ...
        def onReadoutStarted(self, cameraCaptureSession: 'CameraCaptureSession', captureRequest: 'CaptureRequest', long: int, long2: int) -> None: ...
    class StateCallback:
        def __init__(self): ...
        def onActive(self, cameraCaptureSession: 'CameraCaptureSession') -> None: ...
        def onCaptureQueueEmpty(self, cameraCaptureSession: 'CameraCaptureSession') -> None: ...
        def onClosed(self, cameraCaptureSession: 'CameraCaptureSession') -> None: ...
        def onConfigureFailed(self, cameraCaptureSession: 'CameraCaptureSession') -> None: ...
        def onConfigured(self, cameraCaptureSession: 'CameraCaptureSession') -> None: ...
        def onReady(self, cameraCaptureSession: 'CameraCaptureSession') -> None: ...
        def onSurfacePrepared(self, cameraCaptureSession: 'CameraCaptureSession', surface: android.view.Surface) -> None: ...

class CameraDevice(java.lang.AutoCloseable):
    AUDIO_RESTRICTION_NONE: typing.ClassVar[int] = ...
    AUDIO_RESTRICTION_VIBRATION: typing.ClassVar[int] = ...
    AUDIO_RESTRICTION_VIBRATION_SOUND: typing.ClassVar[int] = ...
    TEMPLATE_MANUAL: typing.ClassVar[int] = ...
    TEMPLATE_PREVIEW: typing.ClassVar[int] = ...
    TEMPLATE_RECORD: typing.ClassVar[int] = ...
    TEMPLATE_STILL_CAPTURE: typing.ClassVar[int] = ...
    TEMPLATE_VIDEO_SNAPSHOT: typing.ClassVar[int] = ...
    TEMPLATE_ZERO_SHUTTER_LAG: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    @typing.overload
    def createCaptureRequest(self, int: int) -> 'CaptureRequest.Builder': ...
    @typing.overload
    def createCaptureRequest(self, int: int, set: java.util.Set[str]) -> 'CaptureRequest.Builder': ...
    @typing.overload
    def createCaptureSession(self, list: java.util.List[android.view.Surface], stateCallback: CameraCaptureSession.StateCallback, handler: android.os.Handler) -> None: ...
    @typing.overload
    def createCaptureSession(self, sessionConfiguration: android.hardware.camera2.params.SessionConfiguration) -> None: ...
    def createCaptureSessionByOutputConfigurations(self, list: java.util.List[android.hardware.camera2.params.OutputConfiguration], stateCallback: CameraCaptureSession.StateCallback, handler: android.os.Handler) -> None: ...
    def createConstrainedHighSpeedCaptureSession(self, list: java.util.List[android.view.Surface], stateCallback: CameraCaptureSession.StateCallback, handler: android.os.Handler) -> None: ...
    def createExtensionSession(self, extensionSessionConfiguration: android.hardware.camera2.params.ExtensionSessionConfiguration) -> None: ...
    def createReprocessCaptureRequest(self, totalCaptureResult: 'TotalCaptureResult') -> 'CaptureRequest.Builder': ...
    def createReprocessableCaptureSession(self, inputConfiguration: android.hardware.camera2.params.InputConfiguration, list: java.util.List[android.view.Surface], stateCallback: CameraCaptureSession.StateCallback, handler: android.os.Handler) -> None: ...
    def createReprocessableCaptureSessionByConfigurations(self, inputConfiguration: android.hardware.camera2.params.InputConfiguration, list: java.util.List[android.hardware.camera2.params.OutputConfiguration], stateCallback: CameraCaptureSession.StateCallback, handler: android.os.Handler) -> None: ...
    def getCameraAudioRestriction(self) -> int: ...
    def getId(self) -> str: ...
    def isSessionConfigurationSupported(self, sessionConfiguration: android.hardware.camera2.params.SessionConfiguration) -> bool: ...
    def setCameraAudioRestriction(self, int: int) -> None: ...
    class CameraDeviceSetup:
        def createCaptureRequest(self, int: int) -> 'CaptureRequest.Builder': ...
        def getId(self) -> str: ...
        def getSessionCharacteristics(self, sessionConfiguration: android.hardware.camera2.params.SessionConfiguration) -> 'CameraCharacteristics': ...
        def isSessionConfigurationSupported(self, sessionConfiguration: android.hardware.camera2.params.SessionConfiguration) -> bool: ...
        def openCamera(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], stateCallback: 'CameraDevice.StateCallback') -> None: ...
    class StateCallback:
        ERROR_CAMERA_DEVICE: typing.ClassVar[int] = ...
        ERROR_CAMERA_DISABLED: typing.ClassVar[int] = ...
        ERROR_CAMERA_IN_USE: typing.ClassVar[int] = ...
        ERROR_CAMERA_SERVICE: typing.ClassVar[int] = ...
        ERROR_MAX_CAMERAS_IN_USE: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onClosed(self, cameraDevice: 'CameraDevice') -> None: ...
        def onDisconnected(self, cameraDevice: 'CameraDevice') -> None: ...
        def onError(self, cameraDevice: 'CameraDevice', int: int) -> None: ...
        def onOpened(self, cameraDevice: 'CameraDevice') -> None: ...

class CameraExtensionCharacteristics:
    EXTENSION_AUTOMATIC: typing.ClassVar[int] = ...
    EXTENSION_BEAUTY: typing.ClassVar[int] = ...
    EXTENSION_BOKEH: typing.ClassVar[int] = ...
    EXTENSION_FACE_RETOUCH: typing.ClassVar[int] = ...
    EXTENSION_HDR: typing.ClassVar[int] = ...
    EXTENSION_NIGHT: typing.ClassVar[int] = ...
    _get__T = typing.TypeVar('_get__T')  # <T>
    def get(self, int: int, key: 'CameraCharacteristics.Key'[_get__T]) -> _get__T: ...
    def getAvailableCaptureRequestKeys(self, int: int) -> java.util.Set['CaptureRequest.Key']: ...
    def getAvailableCaptureResultKeys(self, int: int) -> java.util.Set['CaptureResult.Key']: ...
    def getEstimatedCaptureLatencyRangeMillis(self, int: int, size: android.util.Size, int2: int) -> android.util.Range[int]: ...
    _getExtensionSupportedSizes_1__T = typing.TypeVar('_getExtensionSupportedSizes_1__T')  # <T>
    @typing.overload
    def getExtensionSupportedSizes(self, int: int, int2: int) -> java.util.List[android.util.Size]: ...
    @typing.overload
    def getExtensionSupportedSizes(self, int: int, class_: typing.Type[_getExtensionSupportedSizes_1__T]) -> java.util.List[android.util.Size]: ...
    def getKeys(self, int: int) -> java.util.Set['CameraCharacteristics.Key']: ...
    def getPostviewSupportedSizes(self, int: int, size: android.util.Size, int2: int) -> java.util.List[android.util.Size]: ...
    def getSupportedExtensions(self) -> java.util.List[int]: ...
    def isCaptureProcessProgressAvailable(self, int: int) -> bool: ...
    def isPostviewAvailable(self, int: int) -> bool: ...

class CameraExtensionSession(java.lang.AutoCloseable):
    def capture(self, captureRequest: 'CaptureRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], extensionCaptureCallback: 'CameraExtensionSession.ExtensionCaptureCallback') -> int: ...
    def close(self) -> None: ...
    def getDevice(self) -> CameraDevice: ...
    def getRealtimeStillCaptureLatency(self) -> 'CameraExtensionSession.StillCaptureLatency': ...
    def setRepeatingRequest(self, captureRequest: 'CaptureRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], extensionCaptureCallback: 'CameraExtensionSession.ExtensionCaptureCallback') -> int: ...
    def stopRepeating(self) -> None: ...
    class ExtensionCaptureCallback:
        def __init__(self): ...
        @typing.overload
        def onCaptureFailed(self, cameraExtensionSession: 'CameraExtensionSession', captureRequest: 'CaptureRequest') -> None: ...
        @typing.overload
        def onCaptureFailed(self, cameraExtensionSession: 'CameraExtensionSession', captureRequest: 'CaptureRequest', int: int) -> None: ...
        def onCaptureProcessProgressed(self, cameraExtensionSession: 'CameraExtensionSession', captureRequest: 'CaptureRequest', int: int) -> None: ...
        def onCaptureProcessStarted(self, cameraExtensionSession: 'CameraExtensionSession', captureRequest: 'CaptureRequest') -> None: ...
        def onCaptureResultAvailable(self, cameraExtensionSession: 'CameraExtensionSession', captureRequest: 'CaptureRequest', totalCaptureResult: 'TotalCaptureResult') -> None: ...
        def onCaptureSequenceAborted(self, cameraExtensionSession: 'CameraExtensionSession', int: int) -> None: ...
        def onCaptureSequenceCompleted(self, cameraExtensionSession: 'CameraExtensionSession', int: int) -> None: ...
        def onCaptureStarted(self, cameraExtensionSession: 'CameraExtensionSession', captureRequest: 'CaptureRequest', long: int) -> None: ...
    class StateCallback:
        def __init__(self): ...
        def onClosed(self, cameraExtensionSession: 'CameraExtensionSession') -> None: ...
        def onConfigureFailed(self, cameraExtensionSession: 'CameraExtensionSession') -> None: ...
        def onConfigured(self, cameraExtensionSession: 'CameraExtensionSession') -> None: ...
    class StillCaptureLatency:
        def __init__(self, long: int, long2: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getCaptureLatency(self) -> int: ...
        def getProcessingLatency(self) -> int: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class CameraManager:
    def getCameraCharacteristics(self, string: str) -> 'CameraCharacteristics': ...
    def getCameraDeviceSetup(self, string: str) -> CameraDevice.CameraDeviceSetup: ...
    def getCameraExtensionCharacteristics(self, string: str) -> CameraExtensionCharacteristics: ...
    def getCameraIdList(self) -> typing.MutableSequence[str]: ...
    def getConcurrentCameraIds(self) -> java.util.Set[java.util.Set[str]]: ...
    def getTorchStrengthLevel(self, string: str) -> int: ...
    def isCameraDeviceSetupSupported(self, string: str) -> bool: ...
    def isConcurrentSessionConfigurationSupported(self, map: typing.Union[java.util.Map[str, android.hardware.camera2.params.SessionConfiguration], typing.Mapping[str, android.hardware.camera2.params.SessionConfiguration]]) -> bool: ...
    @typing.overload
    def openCamera(self, string: str, stateCallback: CameraDevice.StateCallback, handler: android.os.Handler) -> None: ...
    @typing.overload
    def openCamera(self, string: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], stateCallback: CameraDevice.StateCallback) -> None: ...
    @typing.overload
    def registerAvailabilityCallback(self, availabilityCallback: 'CameraManager.AvailabilityCallback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def registerAvailabilityCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], availabilityCallback: 'CameraManager.AvailabilityCallback') -> None: ...
    @typing.overload
    def registerTorchCallback(self, torchCallback: 'CameraManager.TorchCallback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def registerTorchCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], torchCallback: 'CameraManager.TorchCallback') -> None: ...
    def setTorchMode(self, string: str, boolean: bool) -> None: ...
    def turnOnTorchWithStrengthLevel(self, string: str, int: int) -> None: ...
    def unregisterAvailabilityCallback(self, availabilityCallback: 'CameraManager.AvailabilityCallback') -> None: ...
    def unregisterTorchCallback(self, torchCallback: 'CameraManager.TorchCallback') -> None: ...
    class AvailabilityCallback:
        def __init__(self): ...
        def onCameraAccessPrioritiesChanged(self) -> None: ...
        def onCameraAvailable(self, string: str) -> None: ...
        def onCameraUnavailable(self, string: str) -> None: ...
        def onPhysicalCameraAvailable(self, string: str, string2: str) -> None: ...
        def onPhysicalCameraUnavailable(self, string: str, string2: str) -> None: ...
    class TorchCallback:
        def __init__(self): ...
        def onTorchModeChanged(self, string: str, boolean: bool) -> None: ...
        def onTorchModeUnavailable(self, string: str) -> None: ...
        def onTorchStrengthLevelChanged(self, string: str, int: int) -> None: ...

_CameraMetadata__TKey = typing.TypeVar('_CameraMetadata__TKey')  # <TKey>
class CameraMetadata(typing.Generic[_CameraMetadata__TKey]):
    AUTOMOTIVE_LENS_FACING_EXTERIOR_FRONT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_EXTERIOR_LEFT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_EXTERIOR_OTHER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_EXTERIOR_REAR: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_EXTERIOR_RIGHT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_OTHER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_CENTER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_LEFT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_RIGHT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_CENTER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_LEFT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_RIGHT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_CENTER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_LEFT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_RIGHT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTERIOR_FRONT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTERIOR_LEFT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTERIOR_OTHER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTERIOR_REAR: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTERIOR_RIGHT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTRA_FRONT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTRA_LEFT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTRA_OTHER: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTRA_REAR: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_EXTRA_RIGHT: typing.ClassVar[int] = ...
    AUTOMOTIVE_LOCATION_INTERIOR: typing.ClassVar[int] = ...
    COLOR_CORRECTION_ABERRATION_MODE_FAST: typing.ClassVar[int] = ...
    COLOR_CORRECTION_ABERRATION_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    COLOR_CORRECTION_ABERRATION_MODE_OFF: typing.ClassVar[int] = ...
    COLOR_CORRECTION_MODE_FAST: typing.ClassVar[int] = ...
    COLOR_CORRECTION_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    COLOR_CORRECTION_MODE_TRANSFORM_MATRIX: typing.ClassVar[int] = ...
    CONTROL_AE_ANTIBANDING_MODE_50HZ: typing.ClassVar[int] = ...
    CONTROL_AE_ANTIBANDING_MODE_60HZ: typing.ClassVar[int] = ...
    CONTROL_AE_ANTIBANDING_MODE_AUTO: typing.ClassVar[int] = ...
    CONTROL_AE_ANTIBANDING_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_ON: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_ON_ALWAYS_FLASH: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_ON_AUTO_FLASH: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_ON_EXTERNAL_FLASH: typing.ClassVar[int] = ...
    CONTROL_AE_MODE_ON_LOW_LIGHT_BOOST_BRIGHTNESS_PRIORITY: typing.ClassVar[int] = ...
    CONTROL_AE_PRECAPTURE_TRIGGER_CANCEL: typing.ClassVar[int] = ...
    CONTROL_AE_PRECAPTURE_TRIGGER_IDLE: typing.ClassVar[int] = ...
    CONTROL_AE_PRECAPTURE_TRIGGER_START: typing.ClassVar[int] = ...
    CONTROL_AE_STATE_CONVERGED: typing.ClassVar[int] = ...
    CONTROL_AE_STATE_FLASH_REQUIRED: typing.ClassVar[int] = ...
    CONTROL_AE_STATE_INACTIVE: typing.ClassVar[int] = ...
    CONTROL_AE_STATE_LOCKED: typing.ClassVar[int] = ...
    CONTROL_AE_STATE_PRECAPTURE: typing.ClassVar[int] = ...
    CONTROL_AE_STATE_SEARCHING: typing.ClassVar[int] = ...
    CONTROL_AF_MODE_AUTO: typing.ClassVar[int] = ...
    CONTROL_AF_MODE_CONTINUOUS_PICTURE: typing.ClassVar[int] = ...
    CONTROL_AF_MODE_CONTINUOUS_VIDEO: typing.ClassVar[int] = ...
    CONTROL_AF_MODE_EDOF: typing.ClassVar[int] = ...
    CONTROL_AF_MODE_MACRO: typing.ClassVar[int] = ...
    CONTROL_AF_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_AF_SCENE_CHANGE_DETECTED: typing.ClassVar[int] = ...
    CONTROL_AF_SCENE_CHANGE_NOT_DETECTED: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_ACTIVE_SCAN: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_FOCUSED_LOCKED: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_INACTIVE: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_NOT_FOCUSED_LOCKED: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_PASSIVE_FOCUSED: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_PASSIVE_SCAN: typing.ClassVar[int] = ...
    CONTROL_AF_STATE_PASSIVE_UNFOCUSED: typing.ClassVar[int] = ...
    CONTROL_AF_TRIGGER_CANCEL: typing.ClassVar[int] = ...
    CONTROL_AF_TRIGGER_IDLE: typing.ClassVar[int] = ...
    CONTROL_AF_TRIGGER_START: typing.ClassVar[int] = ...
    CONTROL_AUTOFRAMING_OFF: typing.ClassVar[int] = ...
    CONTROL_AUTOFRAMING_ON: typing.ClassVar[int] = ...
    CONTROL_AUTOFRAMING_STATE_CONVERGED: typing.ClassVar[int] = ...
    CONTROL_AUTOFRAMING_STATE_FRAMING: typing.ClassVar[int] = ...
    CONTROL_AUTOFRAMING_STATE_INACTIVE: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_AUTO: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_CLOUDY_DAYLIGHT: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_DAYLIGHT: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_FLUORESCENT: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_INCANDESCENT: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_SHADE: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_TWILIGHT: typing.ClassVar[int] = ...
    CONTROL_AWB_MODE_WARM_FLUORESCENT: typing.ClassVar[int] = ...
    CONTROL_AWB_STATE_CONVERGED: typing.ClassVar[int] = ...
    CONTROL_AWB_STATE_INACTIVE: typing.ClassVar[int] = ...
    CONTROL_AWB_STATE_LOCKED: typing.ClassVar[int] = ...
    CONTROL_AWB_STATE_SEARCHING: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_CUSTOM: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_MANUAL: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_MOTION_TRACKING: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_PREVIEW: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_STILL_CAPTURE: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_VIDEO_RECORD: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_VIDEO_SNAPSHOT: typing.ClassVar[int] = ...
    CONTROL_CAPTURE_INTENT_ZERO_SHUTTER_LAG: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_AQUA: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_BLACKBOARD: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_MONO: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_NEGATIVE: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_POSTERIZE: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_SEPIA: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_SOLARIZE: typing.ClassVar[int] = ...
    CONTROL_EFFECT_MODE_WHITEBOARD: typing.ClassVar[int] = ...
    CONTROL_EXTENDED_SCENE_MODE_BOKEH_CONTINUOUS: typing.ClassVar[int] = ...
    CONTROL_EXTENDED_SCENE_MODE_BOKEH_STILL_CAPTURE: typing.ClassVar[int] = ...
    CONTROL_EXTENDED_SCENE_MODE_DISABLED: typing.ClassVar[int] = ...
    CONTROL_LOW_LIGHT_BOOST_STATE_ACTIVE: typing.ClassVar[int] = ...
    CONTROL_LOW_LIGHT_BOOST_STATE_INACTIVE: typing.ClassVar[int] = ...
    CONTROL_MODE_AUTO: typing.ClassVar[int] = ...
    CONTROL_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_MODE_OFF_KEEP_STATE: typing.ClassVar[int] = ...
    CONTROL_MODE_USE_EXTENDED_SCENE_MODE: typing.ClassVar[int] = ...
    CONTROL_MODE_USE_SCENE_MODE: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_ACTION: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_BARCODE: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_BEACH: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_CANDLELIGHT: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_DISABLED: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_FACE_PRIORITY: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_FIREWORKS: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_HDR: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_HIGH_SPEED_VIDEO: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_LANDSCAPE: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_NIGHT: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_NIGHT_PORTRAIT: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_PARTY: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_PORTRAIT: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_SNOW: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_SPORTS: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_STEADYPHOTO: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_SUNSET: typing.ClassVar[int] = ...
    CONTROL_SCENE_MODE_THEATRE: typing.ClassVar[int] = ...
    CONTROL_SETTINGS_OVERRIDE_OFF: typing.ClassVar[int] = ...
    CONTROL_SETTINGS_OVERRIDE_ZOOM: typing.ClassVar[int] = ...
    CONTROL_VIDEO_STABILIZATION_MODE_OFF: typing.ClassVar[int] = ...
    CONTROL_VIDEO_STABILIZATION_MODE_ON: typing.ClassVar[int] = ...
    CONTROL_VIDEO_STABILIZATION_MODE_PREVIEW_STABILIZATION: typing.ClassVar[int] = ...
    DISTORTION_CORRECTION_MODE_FAST: typing.ClassVar[int] = ...
    DISTORTION_CORRECTION_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    DISTORTION_CORRECTION_MODE_OFF: typing.ClassVar[int] = ...
    EDGE_MODE_FAST: typing.ClassVar[int] = ...
    EDGE_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    EDGE_MODE_OFF: typing.ClassVar[int] = ...
    EDGE_MODE_ZERO_SHUTTER_LAG: typing.ClassVar[int] = ...
    FLASH_MODE_OFF: typing.ClassVar[int] = ...
    FLASH_MODE_SINGLE: typing.ClassVar[int] = ...
    FLASH_MODE_TORCH: typing.ClassVar[int] = ...
    FLASH_STATE_CHARGING: typing.ClassVar[int] = ...
    FLASH_STATE_FIRED: typing.ClassVar[int] = ...
    FLASH_STATE_PARTIAL: typing.ClassVar[int] = ...
    FLASH_STATE_READY: typing.ClassVar[int] = ...
    FLASH_STATE_UNAVAILABLE: typing.ClassVar[int] = ...
    HOT_PIXEL_MODE_FAST: typing.ClassVar[int] = ...
    HOT_PIXEL_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    HOT_PIXEL_MODE_OFF: typing.ClassVar[int] = ...
    INFO_SUPPORTED_HARDWARE_LEVEL_3: typing.ClassVar[int] = ...
    INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL: typing.ClassVar[int] = ...
    INFO_SUPPORTED_HARDWARE_LEVEL_FULL: typing.ClassVar[int] = ...
    INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY: typing.ClassVar[int] = ...
    INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED: typing.ClassVar[int] = ...
    LENS_FACING_BACK: typing.ClassVar[int] = ...
    LENS_FACING_EXTERNAL: typing.ClassVar[int] = ...
    LENS_FACING_FRONT: typing.ClassVar[int] = ...
    LENS_INFO_FOCUS_DISTANCE_CALIBRATION_APPROXIMATE: typing.ClassVar[int] = ...
    LENS_INFO_FOCUS_DISTANCE_CALIBRATION_CALIBRATED: typing.ClassVar[int] = ...
    LENS_INFO_FOCUS_DISTANCE_CALIBRATION_UNCALIBRATED: typing.ClassVar[int] = ...
    LENS_OPTICAL_STABILIZATION_MODE_OFF: typing.ClassVar[int] = ...
    LENS_OPTICAL_STABILIZATION_MODE_ON: typing.ClassVar[int] = ...
    LENS_POSE_REFERENCE_AUTOMOTIVE: typing.ClassVar[int] = ...
    LENS_POSE_REFERENCE_GYROSCOPE: typing.ClassVar[int] = ...
    LENS_POSE_REFERENCE_PRIMARY_CAMERA: typing.ClassVar[int] = ...
    LENS_POSE_REFERENCE_UNDEFINED: typing.ClassVar[int] = ...
    LENS_STATE_MOVING: typing.ClassVar[int] = ...
    LENS_STATE_STATIONARY: typing.ClassVar[int] = ...
    LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE_APPROXIMATE: typing.ClassVar[int] = ...
    LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE_CALIBRATED: typing.ClassVar[int] = ...
    NOISE_REDUCTION_MODE_FAST: typing.ClassVar[int] = ...
    NOISE_REDUCTION_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    NOISE_REDUCTION_MODE_MINIMAL: typing.ClassVar[int] = ...
    NOISE_REDUCTION_MODE_OFF: typing.ClassVar[int] = ...
    NOISE_REDUCTION_MODE_ZERO_SHUTTER_LAG: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_COLOR_SPACE_PROFILES: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_DYNAMIC_RANGE_TEN_BIT: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_LOGICAL_MULTI_CAMERA: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_MANUAL_POST_PROCESSING: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_MANUAL_SENSOR: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_MOTION_TRACKING: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_OFFLINE_PROCESSING: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_PRIVATE_REPROCESSING: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_RAW: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_REMOSAIC_REPROCESSING: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_SECURE_IMAGE_DATA: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_STREAM_USE_CASE: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_SYSTEM_CAMERA: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_ULTRA_HIGH_RESOLUTION_SENSOR: typing.ClassVar[int] = ...
    REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_CROPPED_RAW: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_DEFAULT: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_PREVIEW: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_PREVIEW_VIDEO_STILL: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_STILL_CAPTURE: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_VIDEO_CALL: typing.ClassVar[int] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES_VIDEO_RECORD: typing.ClassVar[int] = ...
    SCALER_CROPPING_TYPE_CENTER_ONLY: typing.ClassVar[int] = ...
    SCALER_CROPPING_TYPE_FREEFORM: typing.ClassVar[int] = ...
    SCALER_ROTATE_AND_CROP_180: typing.ClassVar[int] = ...
    SCALER_ROTATE_AND_CROP_270: typing.ClassVar[int] = ...
    SCALER_ROTATE_AND_CROP_90: typing.ClassVar[int] = ...
    SCALER_ROTATE_AND_CROP_AUTO: typing.ClassVar[int] = ...
    SCALER_ROTATE_AND_CROP_NONE: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_BGGR: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_GBRG: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_GRBG: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_MONO: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_NIR: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_RGB: typing.ClassVar[int] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_RGGB: typing.ClassVar[int] = ...
    SENSOR_INFO_TIMESTAMP_SOURCE_REALTIME: typing.ClassVar[int] = ...
    SENSOR_INFO_TIMESTAMP_SOURCE_UNKNOWN: typing.ClassVar[int] = ...
    SENSOR_PIXEL_MODE_DEFAULT: typing.ClassVar[int] = ...
    SENSOR_PIXEL_MODE_MAXIMUM_RESOLUTION: typing.ClassVar[int] = ...
    SENSOR_READOUT_TIMESTAMP_HARDWARE: typing.ClassVar[int] = ...
    SENSOR_READOUT_TIMESTAMP_NOT_SUPPORTED: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_CLOUDY_WEATHER: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_COOL_WHITE_FLUORESCENT: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_D50: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_D55: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_D65: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_D75: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT_FLUORESCENT: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_DAY_WHITE_FLUORESCENT: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_FINE_WEATHER: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_FLASH: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_FLUORESCENT: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_ISO_STUDIO_TUNGSTEN: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_SHADE: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_STANDARD_A: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_STANDARD_B: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_STANDARD_C: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_TUNGSTEN: typing.ClassVar[int] = ...
    SENSOR_REFERENCE_ILLUMINANT1_WHITE_FLUORESCENT: typing.ClassVar[int] = ...
    SENSOR_TEST_PATTERN_MODE_COLOR_BARS: typing.ClassVar[int] = ...
    SENSOR_TEST_PATTERN_MODE_COLOR_BARS_FADE_TO_GRAY: typing.ClassVar[int] = ...
    SENSOR_TEST_PATTERN_MODE_CUSTOM1: typing.ClassVar[int] = ...
    SENSOR_TEST_PATTERN_MODE_OFF: typing.ClassVar[int] = ...
    SENSOR_TEST_PATTERN_MODE_PN9: typing.ClassVar[int] = ...
    SENSOR_TEST_PATTERN_MODE_SOLID_COLOR: typing.ClassVar[int] = ...
    SHADING_MODE_FAST: typing.ClassVar[int] = ...
    SHADING_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    SHADING_MODE_OFF: typing.ClassVar[int] = ...
    STATISTICS_FACE_DETECT_MODE_FULL: typing.ClassVar[int] = ...
    STATISTICS_FACE_DETECT_MODE_OFF: typing.ClassVar[int] = ...
    STATISTICS_FACE_DETECT_MODE_SIMPLE: typing.ClassVar[int] = ...
    STATISTICS_LENS_SHADING_MAP_MODE_OFF: typing.ClassVar[int] = ...
    STATISTICS_LENS_SHADING_MAP_MODE_ON: typing.ClassVar[int] = ...
    STATISTICS_OIS_DATA_MODE_OFF: typing.ClassVar[int] = ...
    STATISTICS_OIS_DATA_MODE_ON: typing.ClassVar[int] = ...
    STATISTICS_SCENE_FLICKER_50HZ: typing.ClassVar[int] = ...
    STATISTICS_SCENE_FLICKER_60HZ: typing.ClassVar[int] = ...
    STATISTICS_SCENE_FLICKER_NONE: typing.ClassVar[int] = ...
    SYNC_MAX_LATENCY_PER_FRAME_CONTROL: typing.ClassVar[int] = ...
    SYNC_MAX_LATENCY_UNKNOWN: typing.ClassVar[int] = ...
    TONEMAP_MODE_CONTRAST_CURVE: typing.ClassVar[int] = ...
    TONEMAP_MODE_FAST: typing.ClassVar[int] = ...
    TONEMAP_MODE_GAMMA_VALUE: typing.ClassVar[int] = ...
    TONEMAP_MODE_HIGH_QUALITY: typing.ClassVar[int] = ...
    TONEMAP_MODE_PRESET_CURVE: typing.ClassVar[int] = ...
    TONEMAP_PRESET_CURVE_REC709: typing.ClassVar[int] = ...
    TONEMAP_PRESET_CURVE_SRGB: typing.ClassVar[int] = ...
    def getKeys(self) -> java.util.List[_CameraMetadata__TKey]: ...

class CaptureFailure:
    REASON_ERROR: typing.ClassVar[int] = ...
    REASON_FLUSHED: typing.ClassVar[int] = ...
    def getFrameNumber(self) -> int: ...
    def getPhysicalCameraId(self) -> str: ...
    def getReason(self) -> int: ...
    def getRequest(self) -> 'CaptureRequest': ...
    def getSequenceId(self) -> int: ...
    def wasImageCaptured(self) -> bool: ...

class DngCreator(java.lang.AutoCloseable):
    MAX_THUMBNAIL_DIMENSION: typing.ClassVar[int] = ...
    def __init__(self, cameraCharacteristics: 'CameraCharacteristics', captureResult: 'CaptureResult'): ...
    def close(self) -> None: ...
    def setDescription(self, string: str) -> 'DngCreator': ...
    def setLocation(self, location: android.location.Location) -> 'DngCreator': ...
    def setOrientation(self, int: int) -> 'DngCreator': ...
    @typing.overload
    def setThumbnail(self, bitmap: android.graphics.Bitmap) -> 'DngCreator': ...
    @typing.overload
    def setThumbnail(self, image: android.media.Image) -> 'DngCreator': ...
    def writeByteBuffer(self, outputStream: java.io.OutputStream, size: android.util.Size, byteBuffer: java.nio.ByteBuffer, long: int) -> None: ...
    def writeImage(self, outputStream: java.io.OutputStream, image: android.media.Image) -> None: ...
    def writeInputStream(self, outputStream: java.io.OutputStream, size: android.util.Size, inputStream: java.io.InputStream, long: int) -> None: ...

class MultiResolutionImageReader(java.lang.AutoCloseable):
    def __init__(self, collection: typing.Union[java.util.Collection[android.hardware.camera2.params.MultiResolutionStreamInfo], typing.Sequence[android.hardware.camera2.params.MultiResolutionStreamInfo], typing.Set[android.hardware.camera2.params.MultiResolutionStreamInfo]], int: int, int2: int): ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def getStreamInfoForImageReader(self, imageReader: android.media.ImageReader) -> android.hardware.camera2.params.MultiResolutionStreamInfo: ...
    def getSurface(self) -> android.view.Surface: ...
    def setOnImageAvailableListener(self, onImageAvailableListener: typing.Union[android.media.ImageReader.OnImageAvailableListener, typing.Callable], executor: typing.Union[java.util.concurrent.Executor, typing.Callable]) -> None: ...

_CameraCharacteristics__Key__T = typing.TypeVar('_CameraCharacteristics__Key__T')  # <T>
class CameraCharacteristics(CameraMetadata['CameraCharacteristics.Key'[typing.Any]]):
    AUTOMOTIVE_LENS_FACING: typing.ClassVar['CameraCharacteristics.Key'] = ...
    AUTOMOTIVE_LOCATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    COLOR_CORRECTION_AVAILABLE_ABERRATION_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AE_AVAILABLE_ANTIBANDING_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AE_AVAILABLE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AE_COMPENSATION_RANGE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AE_COMPENSATION_STEP: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AE_LOCK_AVAILABLE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AF_AVAILABLE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AUTOFRAMING_AVAILABLE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AVAILABLE_EFFECTS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AVAILABLE_EXTENDED_SCENE_MODE_CAPABILITIES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AVAILABLE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AVAILABLE_SCENE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AVAILABLE_SETTINGS_OVERRIDES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AVAILABLE_VIDEO_STABILIZATION_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AWB_AVAILABLE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_AWB_LOCK_AVAILABLE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_LOW_LIGHT_BOOST_INFO_LUMINANCE_RANGE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_MAX_REGIONS_AE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_MAX_REGIONS_AF: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_MAX_REGIONS_AWB: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_POST_RAW_SENSITIVITY_BOOST_RANGE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    CONTROL_ZOOM_RATIO_RANGE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    DEPTH_DEPTH_IS_EXCLUSIVE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    DISTORTION_CORRECTION_AVAILABLE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    EDGE_AVAILABLE_EDGE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_INFO_AVAILABLE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_INFO_STRENGTH_DEFAULT_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_INFO_STRENGTH_MAXIMUM_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_SINGLE_STRENGTH_DEFAULT_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_SINGLE_STRENGTH_MAX_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_TORCH_STRENGTH_DEFAULT_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    FLASH_TORCH_STRENGTH_MAX_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    HOT_PIXEL_AVAILABLE_HOT_PIXEL_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    INFO_DEVICE_STATE_SENSOR_ORIENTATION_MAP: typing.ClassVar['CameraCharacteristics.Key'] = ...
    INFO_SESSION_CONFIGURATION_QUERY_VERSION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    INFO_SUPPORTED_HARDWARE_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    INFO_VERSION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    JPEG_AVAILABLE_THUMBNAIL_SIZES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_DISTORTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_DISTORTION_MAXIMUM_RESOLUTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_FACING: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_AVAILABLE_APERTURES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_AVAILABLE_FILTER_DENSITIES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_AVAILABLE_FOCAL_LENGTHS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_AVAILABLE_OPTICAL_STABILIZATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_FOCUS_DISTANCE_CALIBRATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_HYPERFOCAL_DISTANCE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INFO_MINIMUM_FOCUS_DISTANCE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INTRINSIC_CALIBRATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_INTRINSIC_CALIBRATION_MAXIMUM_RESOLUTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_POSE_REFERENCE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_POSE_ROTATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_POSE_TRANSLATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LENS_RADIAL_DISTORTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    NOISE_REDUCTION_AVAILABLE_NOISE_REDUCTION_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REPROCESS_MAX_CAPTURE_STALL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_AVAILABLE_CAPABILITIES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_AVAILABLE_COLOR_SPACE_PROFILES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_MAX_NUM_INPUT_STREAMS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_MAX_NUM_OUTPUT_PROC: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_MAX_NUM_OUTPUT_PROC_STALLING: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_MAX_NUM_OUTPUT_RAW: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_PARTIAL_RESULT_COUNT: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_PIPELINE_MAX_DEPTH: typing.ClassVar['CameraCharacteristics.Key'] = ...
    REQUEST_RECOMMENDED_TEN_BIT_DYNAMIC_RANGE_PROFILE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_AVAILABLE_MAX_DIGITAL_ZOOM: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_AVAILABLE_ROTATE_AND_CROP_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_AVAILABLE_STREAM_USE_CASES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_CROPPING_TYPE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_DEFAULT_SECURE_IMAGE_SIZE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MANDATORY_CONCURRENT_STREAM_COMBINATIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MANDATORY_MAXIMUM_RESOLUTION_STREAM_COMBINATIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MANDATORY_PREVIEW_STABILIZATION_OUTPUT_STREAM_COMBINATIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MANDATORY_STREAM_COMBINATIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MANDATORY_TEN_BIT_OUTPUT_STREAM_COMBINATIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MANDATORY_USE_CASE_STREAM_COMBINATIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_MULTI_RESOLUTION_STREAM_CONFIGURATION_MAP: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_STREAM_CONFIGURATION_MAP: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SCALER_STREAM_CONFIGURATION_MAP_MAXIMUM_RESOLUTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_AVAILABLE_TEST_PATTERN_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_BLACK_LEVEL_PATTERN: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_CALIBRATION_TRANSFORM1: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_CALIBRATION_TRANSFORM2: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_COLOR_TRANSFORM1: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_COLOR_TRANSFORM2: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_FORWARD_MATRIX1: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_FORWARD_MATRIX2: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_ACTIVE_ARRAY_SIZE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_ACTIVE_ARRAY_SIZE_MAXIMUM_RESOLUTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_BINNING_FACTOR: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_COLOR_FILTER_ARRANGEMENT: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_EXPOSURE_TIME_RANGE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_LENS_SHADING_APPLIED: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_MAX_FRAME_DURATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_PHYSICAL_SIZE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_PIXEL_ARRAY_SIZE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_PIXEL_ARRAY_SIZE_MAXIMUM_RESOLUTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE_MAXIMUM_RESOLUTION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_SENSITIVITY_RANGE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_TIMESTAMP_SOURCE: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_INFO_WHITE_LEVEL: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_MAX_ANALOG_SENSITIVITY: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_OPTICAL_BLACK_REGIONS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_ORIENTATION: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_READOUT_TIMESTAMP: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_REFERENCE_ILLUMINANT1: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SENSOR_REFERENCE_ILLUMINANT2: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SHADING_AVAILABLE_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    STATISTICS_INFO_AVAILABLE_FACE_DETECT_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    STATISTICS_INFO_AVAILABLE_HOT_PIXEL_MAP_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    STATISTICS_INFO_AVAILABLE_LENS_SHADING_MAP_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    STATISTICS_INFO_AVAILABLE_OIS_DATA_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    STATISTICS_INFO_MAX_FACE_COUNT: typing.ClassVar['CameraCharacteristics.Key'] = ...
    SYNC_MAX_LATENCY: typing.ClassVar['CameraCharacteristics.Key'] = ...
    TONEMAP_AVAILABLE_TONE_MAP_MODES: typing.ClassVar['CameraCharacteristics.Key'] = ...
    TONEMAP_MAX_CURVE_POINTS: typing.ClassVar['CameraCharacteristics.Key'] = ...
    _get__T = typing.TypeVar('_get__T')  # <T>
    def get(self, key: 'CameraCharacteristics.Key'[_get__T]) -> _get__T: ...
    def getAvailableCaptureRequestKeys(self) -> java.util.List['CaptureRequest.Key'[typing.Any]]: ...
    def getAvailableCaptureResultKeys(self) -> java.util.List['CaptureResult.Key'[typing.Any]]: ...
    def getAvailablePhysicalCameraRequestKeys(self) -> java.util.List['CaptureRequest.Key'[typing.Any]]: ...
    def getAvailableSessionCharacteristicsKeys(self) -> java.util.List['CameraCharacteristics.Key'[typing.Any]]: ...
    def getAvailableSessionKeys(self) -> java.util.List['CaptureRequest.Key'[typing.Any]]: ...
    def getKeys(self) -> java.util.List['CameraCharacteristics.Key'[typing.Any]]: ...
    def getKeysNeedingPermission(self) -> java.util.List['CameraCharacteristics.Key'[typing.Any]]: ...
    def getPhysicalCameraIds(self) -> java.util.Set[str]: ...
    def getRecommendedStreamConfigurationMap(self, int: int) -> android.hardware.camera2.params.RecommendedStreamConfigurationMap: ...
    class Key(typing.Generic[_CameraCharacteristics__Key__T]):
        def __init__(self, string: str, class_: typing.Type[_CameraCharacteristics__Key__T]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getName(self) -> str: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class CameraConstrainedHighSpeedCaptureSession(CameraCaptureSession):
    def __init__(self): ...
    def createHighSpeedRequestList(self, captureRequest: 'CaptureRequest') -> java.util.List['CaptureRequest']: ...

class CameraOfflineSession(CameraCaptureSession):
    def __init__(self): ...
    def close(self) -> None: ...
    class CameraOfflineSessionCallback:
        STATUS_INTERNAL_ERROR: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onClosed(self, cameraOfflineSession: 'CameraOfflineSession') -> None: ...
        def onError(self, cameraOfflineSession: 'CameraOfflineSession', int: int) -> None: ...
        def onIdle(self, cameraOfflineSession: 'CameraOfflineSession') -> None: ...
        def onReady(self, cameraOfflineSession: 'CameraOfflineSession') -> None: ...
        def onSwitchFailed(self, cameraOfflineSession: 'CameraOfflineSession') -> None: ...

_CaptureRequest__Key__T = typing.TypeVar('_CaptureRequest__Key__T')  # <T>
class CaptureRequest(CameraMetadata['CaptureRequest.Key'[typing.Any]], android.os.Parcelable):
    BLACK_LEVEL_LOCK: typing.ClassVar['CaptureRequest.Key'] = ...
    COLOR_CORRECTION_ABERRATION_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    COLOR_CORRECTION_GAINS: typing.ClassVar['CaptureRequest.Key'] = ...
    COLOR_CORRECTION_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    COLOR_CORRECTION_TRANSFORM: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_ANTIBANDING_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_EXPOSURE_COMPENSATION: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_LOCK: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_PRECAPTURE_TRIGGER: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_REGIONS: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AE_TARGET_FPS_RANGE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AF_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AF_REGIONS: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AF_TRIGGER: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AUTOFRAMING: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AWB_LOCK: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AWB_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_AWB_REGIONS: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_CAPTURE_INTENT: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_EFFECT_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_ENABLE_ZSL: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_EXTENDED_SCENE_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_POST_RAW_SENSITIVITY_BOOST: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_SCENE_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_SETTINGS_OVERRIDE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_VIDEO_STABILIZATION_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    CONTROL_ZOOM_RATIO: typing.ClassVar['CaptureRequest.Key'] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DISTORTION_CORRECTION_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    EDGE_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    EXTENSION_STRENGTH: typing.ClassVar['CaptureRequest.Key'] = ...
    FLASH_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    FLASH_STRENGTH_LEVEL: typing.ClassVar['CaptureRequest.Key'] = ...
    HOT_PIXEL_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    JPEG_GPS_LOCATION: typing.ClassVar['CaptureRequest.Key'] = ...
    JPEG_ORIENTATION: typing.ClassVar['CaptureRequest.Key'] = ...
    JPEG_QUALITY: typing.ClassVar['CaptureRequest.Key'] = ...
    JPEG_THUMBNAIL_QUALITY: typing.ClassVar['CaptureRequest.Key'] = ...
    JPEG_THUMBNAIL_SIZE: typing.ClassVar['CaptureRequest.Key'] = ...
    LENS_APERTURE: typing.ClassVar['CaptureRequest.Key'] = ...
    LENS_FILTER_DENSITY: typing.ClassVar['CaptureRequest.Key'] = ...
    LENS_FOCAL_LENGTH: typing.ClassVar['CaptureRequest.Key'] = ...
    LENS_FOCUS_DISTANCE: typing.ClassVar['CaptureRequest.Key'] = ...
    LENS_OPTICAL_STABILIZATION_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    NOISE_REDUCTION_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    REPROCESS_EFFECTIVE_EXPOSURE_FACTOR: typing.ClassVar['CaptureRequest.Key'] = ...
    SCALER_CROP_REGION: typing.ClassVar['CaptureRequest.Key'] = ...
    SCALER_ROTATE_AND_CROP: typing.ClassVar['CaptureRequest.Key'] = ...
    SENSOR_EXPOSURE_TIME: typing.ClassVar['CaptureRequest.Key'] = ...
    SENSOR_FRAME_DURATION: typing.ClassVar['CaptureRequest.Key'] = ...
    SENSOR_PIXEL_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    SENSOR_SENSITIVITY: typing.ClassVar['CaptureRequest.Key'] = ...
    SENSOR_TEST_PATTERN_DATA: typing.ClassVar['CaptureRequest.Key'] = ...
    SENSOR_TEST_PATTERN_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    SHADING_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    STATISTICS_FACE_DETECT_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    STATISTICS_HOT_PIXEL_MAP_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    STATISTICS_LENS_SHADING_MAP_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    STATISTICS_OIS_DATA_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    TONEMAP_CURVE: typing.ClassVar['CaptureRequest.Key'] = ...
    TONEMAP_GAMMA: typing.ClassVar['CaptureRequest.Key'] = ...
    TONEMAP_MODE: typing.ClassVar['CaptureRequest.Key'] = ...
    TONEMAP_PRESET_CURVE: typing.ClassVar['CaptureRequest.Key'] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    _get__T = typing.TypeVar('_get__T')  # <T>
    def get(self, key: 'CaptureRequest.Key'[_get__T]) -> _get__T: ...
    def getKeys(self) -> java.util.List['CaptureRequest.Key'[typing.Any]]: ...
    def getTag(self) -> typing.Any: ...
    def hashCode(self) -> int: ...
    def isReprocess(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def addTarget(self, surface: android.view.Surface) -> None: ...
        def build(self) -> 'CaptureRequest': ...
        _get__T = typing.TypeVar('_get__T')  # <T>
        def get(self, key: 'CaptureRequest.Key'[_get__T]) -> _get__T: ...
        _getPhysicalCameraKey__T = typing.TypeVar('_getPhysicalCameraKey__T')  # <T>
        def getPhysicalCameraKey(self, key: 'CaptureRequest.Key'[_getPhysicalCameraKey__T], string: str) -> _getPhysicalCameraKey__T: ...
        def removeTarget(self, surface: android.view.Surface) -> None: ...
        _set__T = typing.TypeVar('_set__T')  # <T>
        def set(self, key: 'CaptureRequest.Key'[_set__T], t: _set__T) -> None: ...
        _setPhysicalCameraKey__T = typing.TypeVar('_setPhysicalCameraKey__T')  # <T>
        def setPhysicalCameraKey(self, key: 'CaptureRequest.Key'[_setPhysicalCameraKey__T], t: _setPhysicalCameraKey__T, string: str) -> 'CaptureRequest.Builder': ...
        def setTag(self, object: typing.Any) -> None: ...
    class Key(typing.Generic[_CaptureRequest__Key__T]):
        def __init__(self, string: str, class_: typing.Type[_CaptureRequest__Key__T]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getName(self) -> str: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

_CaptureResult__Key__T = typing.TypeVar('_CaptureResult__Key__T')  # <T>
class CaptureResult(CameraMetadata['CaptureResult.Key'[typing.Any]]):
    BLACK_LEVEL_LOCK: typing.ClassVar['CaptureResult.Key'] = ...
    COLOR_CORRECTION_ABERRATION_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    COLOR_CORRECTION_GAINS: typing.ClassVar['CaptureResult.Key'] = ...
    COLOR_CORRECTION_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    COLOR_CORRECTION_TRANSFORM: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_ANTIBANDING_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_EXPOSURE_COMPENSATION: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_LOCK: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_PRECAPTURE_TRIGGER: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_REGIONS: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AE_TARGET_FPS_RANGE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AF_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AF_REGIONS: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AF_SCENE_CHANGE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AF_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AF_TRIGGER: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AUTOFRAMING: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AUTOFRAMING_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AWB_LOCK: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AWB_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AWB_REGIONS: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_AWB_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_CAPTURE_INTENT: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_EFFECT_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_ENABLE_ZSL: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_EXTENDED_SCENE_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_LOW_LIGHT_BOOST_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_POST_RAW_SENSITIVITY_BOOST: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_SCENE_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_SETTINGS_OVERRIDE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_VIDEO_STABILIZATION_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    CONTROL_ZOOM_RATIO: typing.ClassVar['CaptureResult.Key'] = ...
    DISTORTION_CORRECTION_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    EDGE_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    EXTENSION_CURRENT_TYPE: typing.ClassVar['CaptureResult.Key'] = ...
    EXTENSION_STRENGTH: typing.ClassVar['CaptureResult.Key'] = ...
    FLASH_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    FLASH_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    FLASH_STRENGTH_LEVEL: typing.ClassVar['CaptureResult.Key'] = ...
    HOT_PIXEL_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    JPEG_GPS_LOCATION: typing.ClassVar['CaptureResult.Key'] = ...
    JPEG_ORIENTATION: typing.ClassVar['CaptureResult.Key'] = ...
    JPEG_QUALITY: typing.ClassVar['CaptureResult.Key'] = ...
    JPEG_THUMBNAIL_QUALITY: typing.ClassVar['CaptureResult.Key'] = ...
    JPEG_THUMBNAIL_SIZE: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_APERTURE: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_DISTORTION: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_FILTER_DENSITY: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_FOCAL_LENGTH: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_FOCUS_DISTANCE: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_FOCUS_RANGE: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_INTRINSIC_CALIBRATION: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_OPTICAL_STABILIZATION_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_POSE_ROTATION: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_POSE_TRANSLATION: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_RADIAL_DISTORTION: typing.ClassVar['CaptureResult.Key'] = ...
    LENS_STATE: typing.ClassVar['CaptureResult.Key'] = ...
    LOGICAL_MULTI_CAMERA_ACTIVE_PHYSICAL_ID: typing.ClassVar['CaptureResult.Key'] = ...
    LOGICAL_MULTI_CAMERA_ACTIVE_PHYSICAL_SENSOR_CROP_REGION: typing.ClassVar['CaptureResult.Key'] = ...
    NOISE_REDUCTION_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    REPROCESS_EFFECTIVE_EXPOSURE_FACTOR: typing.ClassVar['CaptureResult.Key'] = ...
    REQUEST_PIPELINE_DEPTH: typing.ClassVar['CaptureResult.Key'] = ...
    SCALER_CROP_REGION: typing.ClassVar['CaptureResult.Key'] = ...
    SCALER_RAW_CROP_REGION: typing.ClassVar['CaptureResult.Key'] = ...
    SCALER_ROTATE_AND_CROP: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_DYNAMIC_BLACK_LEVEL: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_DYNAMIC_WHITE_LEVEL: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_EXPOSURE_TIME: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_FRAME_DURATION: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_GREEN_SPLIT: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_NEUTRAL_COLOR_POINT: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_NOISE_PROFILE: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_PIXEL_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_RAW_BINNING_FACTOR_USED: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_ROLLING_SHUTTER_SKEW: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_SENSITIVITY: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_TEST_PATTERN_DATA: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_TEST_PATTERN_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    SENSOR_TIMESTAMP: typing.ClassVar['CaptureResult.Key'] = ...
    SHADING_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_FACES: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_FACE_DETECT_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_HOT_PIXEL_MAP: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_HOT_PIXEL_MAP_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_LENS_INTRINSICS_SAMPLES: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_LENS_SHADING_CORRECTION_MAP: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_LENS_SHADING_MAP_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_OIS_DATA_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_OIS_SAMPLES: typing.ClassVar['CaptureResult.Key'] = ...
    STATISTICS_SCENE_FLICKER: typing.ClassVar['CaptureResult.Key'] = ...
    TONEMAP_CURVE: typing.ClassVar['CaptureResult.Key'] = ...
    TONEMAP_GAMMA: typing.ClassVar['CaptureResult.Key'] = ...
    TONEMAP_MODE: typing.ClassVar['CaptureResult.Key'] = ...
    TONEMAP_PRESET_CURVE: typing.ClassVar['CaptureResult.Key'] = ...
    _get__T = typing.TypeVar('_get__T')  # <T>
    def get(self, key: 'CaptureResult.Key'[_get__T]) -> _get__T: ...
    def getCameraId(self) -> str: ...
    def getFrameNumber(self) -> int: ...
    def getKeys(self) -> java.util.List['CaptureResult.Key'[typing.Any]]: ...
    def getRequest(self) -> CaptureRequest: ...
    def getSequenceId(self) -> int: ...
    class Key(typing.Generic[_CaptureResult__Key__T]):
        def __init__(self, string: str, class_: typing.Type[_CaptureResult__Key__T]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getName(self) -> str: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class TotalCaptureResult(CaptureResult):
    def getPartialResults(self) -> java.util.List[CaptureResult]: ...
    def getPhysicalCameraResults(self) -> java.util.Map[str, CaptureResult]: ...
    def getPhysicalCameraTotalResults(self) -> java.util.Map[str, 'TotalCaptureResult']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.hardware.camera2")``.

    CameraAccessException: typing.Type[CameraAccessException]
    CameraCaptureSession: typing.Type[CameraCaptureSession]
    CameraCharacteristics: typing.Type[CameraCharacteristics]
    CameraConstrainedHighSpeedCaptureSession: typing.Type[CameraConstrainedHighSpeedCaptureSession]
    CameraDevice: typing.Type[CameraDevice]
    CameraExtensionCharacteristics: typing.Type[CameraExtensionCharacteristics]
    CameraExtensionSession: typing.Type[CameraExtensionSession]
    CameraManager: typing.Type[CameraManager]
    CameraMetadata: typing.Type[CameraMetadata]
    CameraOfflineSession: typing.Type[CameraOfflineSession]
    CaptureFailure: typing.Type[CaptureFailure]
    CaptureRequest: typing.Type[CaptureRequest]
    CaptureResult: typing.Type[CaptureResult]
    DngCreator: typing.Type[DngCreator]
    MultiResolutionImageReader: typing.Type[MultiResolutionImageReader]
    TotalCaptureResult: typing.Type[TotalCaptureResult]
    params: android.hardware.camera2.params.__module_protocol__
