
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.app.slice
import android.content
import android.content.pm
import android.credentials
import android.os
import java.util
import typing



class Action(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, slice: android.app.slice.Slice): ...
    def describeContents(self) -> int: ...
    def getSlice(self) -> android.app.slice.Slice: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BeginCreateCredentialRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, string: str, bundle: android.os.Bundle): ...
    @typing.overload
    def __init__(self, string: str, bundle: android.os.Bundle, callingAppInfo: 'CallingAppInfo'): ...
    def describeContents(self) -> int: ...
    def getCallingAppInfo(self) -> 'CallingAppInfo': ...
    def getData(self) -> android.os.Bundle: ...
    def getType(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BeginCreateCredentialResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self): ...
    def describeContents(self) -> int: ...
    def getCreateEntries(self) -> java.util.List['CreateEntry']: ...
    def getRemoteCreateEntry(self) -> 'RemoteEntry': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addCreateEntry(self, createEntry: 'CreateEntry') -> 'BeginCreateCredentialResponse.Builder': ...
        def build(self) -> 'BeginCreateCredentialResponse': ...
        def setCreateEntries(self, list: java.util.List['CreateEntry']) -> 'BeginCreateCredentialResponse.Builder': ...
        def setRemoteCreateEntry(self, remoteEntry: 'RemoteEntry') -> 'BeginCreateCredentialResponse.Builder': ...

class BeginGetCredentialOption(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, string2: str, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getCandidateQueryData(self) -> android.os.Bundle: ...
    def getId(self) -> str: ...
    def getType(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BeginGetCredentialRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getBeginGetCredentialOptions(self) -> java.util.List[BeginGetCredentialOption]: ...
    def getCallingAppInfo(self) -> 'CallingAppInfo': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addBeginGetCredentialOption(self, beginGetCredentialOption: BeginGetCredentialOption) -> 'BeginGetCredentialRequest.Builder': ...
        def build(self) -> 'BeginGetCredentialRequest': ...
        def setBeginGetCredentialOptions(self, list: java.util.List[BeginGetCredentialOption]) -> 'BeginGetCredentialRequest.Builder': ...
        def setCallingAppInfo(self, callingAppInfo: 'CallingAppInfo') -> 'BeginGetCredentialRequest.Builder': ...

class BeginGetCredentialResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self): ...
    def describeContents(self) -> int: ...
    def getActions(self) -> java.util.List[Action]: ...
    def getAuthenticationActions(self) -> java.util.List[Action]: ...
    def getCredentialEntries(self) -> java.util.List['CredentialEntry']: ...
    def getRemoteCredentialEntry(self) -> 'RemoteEntry': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addAction(self, action: Action) -> 'BeginGetCredentialResponse.Builder': ...
        def addAuthenticationAction(self, action: Action) -> 'BeginGetCredentialResponse.Builder': ...
        def addCredentialEntry(self, credentialEntry: 'CredentialEntry') -> 'BeginGetCredentialResponse.Builder': ...
        def build(self) -> 'BeginGetCredentialResponse': ...
        def setActions(self, list: java.util.List[Action]) -> 'BeginGetCredentialResponse.Builder': ...
        def setAuthenticationActions(self, list: java.util.List[Action]) -> 'BeginGetCredentialResponse.Builder': ...
        def setCredentialEntries(self, list: java.util.List['CredentialEntry']) -> 'BeginGetCredentialResponse.Builder': ...
        def setRemoteCredentialEntry(self, remoteEntry: 'RemoteEntry') -> 'BeginGetCredentialResponse.Builder': ...

class CallingAppInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, string: str, signingInfo: android.content.pm.SigningInfo): ...
    @typing.overload
    def __init__(self, string: str, signingInfo: android.content.pm.SigningInfo, string2: str): ...
    def describeContents(self) -> int: ...
    def getOrigin(self) -> str: ...
    def getPackageName(self) -> str: ...
    def getSigningInfo(self) -> android.content.pm.SigningInfo: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ClearCredentialStateRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, callingAppInfo: CallingAppInfo, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getCallingAppInfo(self) -> CallingAppInfo: ...
    def getData(self) -> android.os.Bundle: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CreateCredentialRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, callingAppInfo: CallingAppInfo, string: str, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getCallingAppInfo(self) -> CallingAppInfo: ...
    def getData(self) -> android.os.Bundle: ...
    def getType(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CreateEntry(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, slice: android.app.slice.Slice): ...
    def describeContents(self) -> int: ...
    def getSlice(self) -> android.app.slice.Slice: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CredentialEntry(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, beginGetCredentialOption: BeginGetCredentialOption, slice: android.app.slice.Slice): ...
    @typing.overload
    def __init__(self, string: str, slice: android.app.slice.Slice): ...
    @typing.overload
    def __init__(self, string: str, string2: str, slice: android.app.slice.Slice): ...
    def describeContents(self) -> int: ...
    def getBeginGetCredentialOptionId(self) -> str: ...
    def getSlice(self) -> android.app.slice.Slice: ...
    def getType(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CredentialProviderService(android.app.Service):
    EXTRA_BEGIN_GET_CREDENTIAL_REQUEST: typing.ClassVar[str] = ...
    EXTRA_BEGIN_GET_CREDENTIAL_RESPONSE: typing.ClassVar[str] = ...
    EXTRA_CREATE_CREDENTIAL_EXCEPTION: typing.ClassVar[str] = ...
    EXTRA_CREATE_CREDENTIAL_REQUEST: typing.ClassVar[str] = ...
    EXTRA_CREATE_CREDENTIAL_RESPONSE: typing.ClassVar[str] = ...
    EXTRA_GET_CREDENTIAL_EXCEPTION: typing.ClassVar[str] = ...
    EXTRA_GET_CREDENTIAL_REQUEST: typing.ClassVar[str] = ...
    EXTRA_GET_CREDENTIAL_RESPONSE: typing.ClassVar[str] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBeginCreateCredential(self, beginCreateCredentialRequest: BeginCreateCredentialRequest, cancellationSignal: android.os.CancellationSignal, outcomeReceiver: typing.Union[android.os.OutcomeReceiver[BeginCreateCredentialResponse, android.credentials.CreateCredentialException], typing.Callable[[BeginCreateCredentialResponse], None]]) -> None: ...
    def onBeginGetCredential(self, beginGetCredentialRequest: BeginGetCredentialRequest, cancellationSignal: android.os.CancellationSignal, outcomeReceiver: typing.Union[android.os.OutcomeReceiver[BeginGetCredentialResponse, android.credentials.GetCredentialException], typing.Callable[[BeginGetCredentialResponse], None]]) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onClearCredentialState(self, clearCredentialStateRequest: ClearCredentialStateRequest, cancellationSignal: android.os.CancellationSignal, outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, android.credentials.ClearCredentialStateException], typing.Callable[[None], None]]) -> None: ...
    def onCreate(self) -> None: ...

class GetCredentialRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, callingAppInfo: CallingAppInfo, list: java.util.List[android.credentials.CredentialOption]): ...
    def describeContents(self) -> int: ...
    def getCallingAppInfo(self) -> CallingAppInfo: ...
    def getCredentialOptions(self) -> java.util.List[android.credentials.CredentialOption]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class RemoteEntry(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, slice: android.app.slice.Slice): ...
    def describeContents(self) -> int: ...
    def getSlice(self) -> android.app.slice.Slice: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.credentials")``.

    Action: typing.Type[Action]
    BeginCreateCredentialRequest: typing.Type[BeginCreateCredentialRequest]
    BeginCreateCredentialResponse: typing.Type[BeginCreateCredentialResponse]
    BeginGetCredentialOption: typing.Type[BeginGetCredentialOption]
    BeginGetCredentialRequest: typing.Type[BeginGetCredentialRequest]
    BeginGetCredentialResponse: typing.Type[BeginGetCredentialResponse]
    CallingAppInfo: typing.Type[CallingAppInfo]
    ClearCredentialStateRequest: typing.Type[ClearCredentialStateRequest]
    CreateCredentialRequest: typing.Type[CreateCredentialRequest]
    CreateEntry: typing.Type[CreateEntry]
    CredentialEntry: typing.Type[CredentialEntry]
    CredentialProviderService: typing.Type[CredentialProviderService]
    GetCredentialRequest: typing.Type[GetCredentialRequest]
    RemoteEntry: typing.Type[RemoteEntry]
