
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import java.lang
import java.text
import java.util
import typing



class DateFormat:
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def format(charSequence: typing.Union[java.lang.CharSequence, str], calendar: java.util.Calendar) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def format(charSequence: typing.Union[java.lang.CharSequence, str], date: java.util.Date) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def format(charSequence: typing.Union[java.lang.CharSequence, str], long: int) -> java.lang.CharSequence: ...
    @staticmethod
    def getBestDateTimePattern(locale: java.util.Locale, string: str) -> str: ...
    @staticmethod
    def getDateFormat(context: android.content.Context) -> java.text.DateFormat: ...
    @staticmethod
    def getDateFormatOrder(context: android.content.Context) -> typing.MutableSequence[str]: ...
    @staticmethod
    def getLongDateFormat(context: android.content.Context) -> java.text.DateFormat: ...
    @staticmethod
    def getMediumDateFormat(context: android.content.Context) -> java.text.DateFormat: ...
    @staticmethod
    def getTimeFormat(context: android.content.Context) -> java.text.DateFormat: ...
    @staticmethod
    def is24HourFormat(context: android.content.Context) -> bool: ...

class DateUtils:
    ABBREV_MONTH_FORMAT: typing.ClassVar[str] = ...
    ABBREV_WEEKDAY_FORMAT: typing.ClassVar[str] = ...
    DAY_IN_MILLIS: typing.ClassVar[int] = ...
    FORMAT_12HOUR: typing.ClassVar[int] = ...
    FORMAT_24HOUR: typing.ClassVar[int] = ...
    FORMAT_ABBREV_ALL: typing.ClassVar[int] = ...
    FORMAT_ABBREV_MONTH: typing.ClassVar[int] = ...
    FORMAT_ABBREV_RELATIVE: typing.ClassVar[int] = ...
    FORMAT_ABBREV_TIME: typing.ClassVar[int] = ...
    FORMAT_ABBREV_WEEKDAY: typing.ClassVar[int] = ...
    FORMAT_CAP_AMPM: typing.ClassVar[int] = ...
    FORMAT_CAP_MIDNIGHT: typing.ClassVar[int] = ...
    FORMAT_CAP_NOON: typing.ClassVar[int] = ...
    FORMAT_CAP_NOON_MIDNIGHT: typing.ClassVar[int] = ...
    FORMAT_NO_MIDNIGHT: typing.ClassVar[int] = ...
    FORMAT_NO_MONTH_DAY: typing.ClassVar[int] = ...
    FORMAT_NO_NOON: typing.ClassVar[int] = ...
    FORMAT_NO_NOON_MIDNIGHT: typing.ClassVar[int] = ...
    FORMAT_NO_YEAR: typing.ClassVar[int] = ...
    FORMAT_NUMERIC_DATE: typing.ClassVar[int] = ...
    FORMAT_SHOW_DATE: typing.ClassVar[int] = ...
    FORMAT_SHOW_TIME: typing.ClassVar[int] = ...
    FORMAT_SHOW_WEEKDAY: typing.ClassVar[int] = ...
    FORMAT_SHOW_YEAR: typing.ClassVar[int] = ...
    FORMAT_UTC: typing.ClassVar[int] = ...
    HOUR_IN_MILLIS: typing.ClassVar[int] = ...
    HOUR_MINUTE_24: typing.ClassVar[str] = ...
    LENGTH_LONG: typing.ClassVar[int] = ...
    LENGTH_MEDIUM: typing.ClassVar[int] = ...
    LENGTH_SHORT: typing.ClassVar[int] = ...
    LENGTH_SHORTER: typing.ClassVar[int] = ...
    LENGTH_SHORTEST: typing.ClassVar[int] = ...
    MINUTE_IN_MILLIS: typing.ClassVar[int] = ...
    MONTH_DAY_FORMAT: typing.ClassVar[str] = ...
    MONTH_FORMAT: typing.ClassVar[str] = ...
    NUMERIC_MONTH_FORMAT: typing.ClassVar[str] = ...
    SECOND_IN_MILLIS: typing.ClassVar[int] = ...
    WEEKDAY_FORMAT: typing.ClassVar[str] = ...
    WEEK_IN_MILLIS: typing.ClassVar[int] = ...
    YEAR_FORMAT: typing.ClassVar[str] = ...
    YEAR_FORMAT_TWO_DIGITS: typing.ClassVar[str] = ...
    YEAR_IN_MILLIS: typing.ClassVar[int] = ...
    sameMonthTable: typing.ClassVar[typing.MutableSequence[int]] = ...
    sameYearTable: typing.ClassVar[typing.MutableSequence[int]] = ...
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def formatDateRange(context: android.content.Context, long: int, long2: int, int: int) -> str: ...
    @typing.overload
    @staticmethod
    def formatDateRange(context: android.content.Context, formatter: java.util.Formatter, long: int, long2: int, int: int) -> java.util.Formatter: ...
    @typing.overload
    @staticmethod
    def formatDateRange(context: android.content.Context, formatter: java.util.Formatter, long: int, long2: int, int: int, string: str) -> java.util.Formatter: ...
    @staticmethod
    def formatDateTime(context: android.content.Context, long: int, int: int) -> str: ...
    @typing.overload
    @staticmethod
    def formatElapsedTime(stringBuilder: java.lang.StringBuilder, long: int) -> str: ...
    @typing.overload
    @staticmethod
    def formatElapsedTime(long: int) -> str: ...
    @staticmethod
    def formatSameDayTime(long: int, long2: int, int: int, int2: int) -> java.lang.CharSequence: ...
    @staticmethod
    def getAMPMString(int: int) -> str: ...
    @staticmethod
    def getDayOfWeekString(int: int, int2: int) -> str: ...
    @staticmethod
    def getMonthString(int: int, int2: int) -> str: ...
    @staticmethod
    def getRelativeDateTimeString(context: android.content.Context, long: int, long2: int, long3: int, int: int) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def getRelativeTimeSpanString(context: android.content.Context, long: int) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def getRelativeTimeSpanString(context: android.content.Context, long: int, boolean: bool) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def getRelativeTimeSpanString(long: int) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def getRelativeTimeSpanString(long: int, long2: int, long3: int) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def getRelativeTimeSpanString(long: int, long2: int, long3: int, int: int) -> java.lang.CharSequence: ...
    @staticmethod
    def isToday(long: int) -> bool: ...

class Formatter:
    def __init__(self): ...
    @staticmethod
    def formatFileSize(context: android.content.Context, long: int) -> str: ...
    @staticmethod
    def formatIpAddress(int: int) -> str: ...
    @staticmethod
    def formatShortFileSize(context: android.content.Context, long: int) -> str: ...

class Time:
    EPOCH_JULIAN_DAY: typing.ClassVar[int] = ...
    FRIDAY: typing.ClassVar[int] = ...
    HOUR: typing.ClassVar[int] = ...
    MINUTE: typing.ClassVar[int] = ...
    MONDAY: typing.ClassVar[int] = ...
    MONDAY_BEFORE_JULIAN_EPOCH: typing.ClassVar[int] = ...
    MONTH: typing.ClassVar[int] = ...
    MONTH_DAY: typing.ClassVar[int] = ...
    SATURDAY: typing.ClassVar[int] = ...
    SECOND: typing.ClassVar[int] = ...
    SUNDAY: typing.ClassVar[int] = ...
    THURSDAY: typing.ClassVar[int] = ...
    TIMEZONE_UTC: typing.ClassVar[str] = ...
    TUESDAY: typing.ClassVar[int] = ...
    WEDNESDAY: typing.ClassVar[int] = ...
    WEEK_DAY: typing.ClassVar[int] = ...
    WEEK_NUM: typing.ClassVar[int] = ...
    YEAR: typing.ClassVar[int] = ...
    YEAR_DAY: typing.ClassVar[int] = ...
    allDay: bool = ...
    gmtoff: int = ...
    hour: int = ...
    isDst: int = ...
    minute: int = ...
    month: int = ...
    monthDay: int = ...
    second: int = ...
    timezone: str = ...
    weekDay: int = ...
    year: int = ...
    yearDay: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, time: 'Time'): ...
    @typing.overload
    def __init__(self, string: str): ...
    def after(self, time: 'Time') -> bool: ...
    def before(self, time: 'Time') -> bool: ...
    def clear(self, string: str) -> None: ...
    @staticmethod
    def compare(time: 'Time', time2: 'Time') -> int: ...
    def format(self, string: str) -> str: ...
    def format2445(self) -> str: ...
    def format3339(self, boolean: bool) -> str: ...
    def getActualMaximum(self, int: int) -> int: ...
    @staticmethod
    def getCurrentTimezone() -> str: ...
    @staticmethod
    def getJulianDay(long: int, long2: int) -> int: ...
    @staticmethod
    def getJulianMondayFromWeeksSinceEpoch(int: int) -> int: ...
    def getWeekNumber(self) -> int: ...
    @staticmethod
    def getWeeksSinceEpochFromJulianDay(int: int, int2: int) -> int: ...
    @staticmethod
    def isEpoch(time: 'Time') -> bool: ...
    def normalize(self, boolean: bool) -> int: ...
    def parse(self, string: str) -> bool: ...
    def parse3339(self, string: str) -> bool: ...
    @typing.overload
    def set(self, time: 'Time') -> None: ...
    @typing.overload
    def set(self, int: int, int2: int, int3: int) -> None: ...
    @typing.overload
    def set(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int) -> None: ...
    @typing.overload
    def set(self, long: int) -> None: ...
    def setJulianDay(self, int: int) -> int: ...
    def setToNow(self) -> None: ...
    def switchTimezone(self, string: str) -> None: ...
    def toMillis(self, boolean: bool) -> int: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.text.format")``.

    DateFormat: typing.Type[DateFormat]
    DateUtils: typing.Type[DateUtils]
    Formatter: typing.Type[Formatter]
    Time: typing.Type[Time]
