
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content.res
import android.os
import java.util
import typing



class FabricatedOverlay:
    def __init__(self, string: str, string2: str): ...
    def getIdentifier(self) -> 'OverlayIdentifier': ...
    def setNinePatchResourceValue(self, string: str, parcelFileDescriptor: android.os.ParcelFileDescriptor, string2: str) -> None: ...
    @typing.overload
    def setResourceValue(self, string: str, assetFileDescriptor: android.content.res.AssetFileDescriptor, string2: str) -> None: ...
    @typing.overload
    def setResourceValue(self, string: str, parcelFileDescriptor: android.os.ParcelFileDescriptor, string2: str) -> None: ...
    @typing.overload
    def setResourceValue(self, string: str, int: int, int2: int, string2: str) -> None: ...
    @typing.overload
    def setResourceValue(self, string: str, int: int, string2: str, string3: str) -> None: ...
    def setTargetOverlayable(self, string: str) -> None: ...

class OverlayIdentifier(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class OverlayInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOverlayIdentifier(self) -> OverlayIdentifier: ...
    def getOverlayName(self) -> str: ...
    def getTargetOverlayableName(self) -> str: ...
    def getTargetPackageName(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class OverlayManager:
    def commit(self, overlayManagerTransaction: 'OverlayManagerTransaction') -> None: ...
    def getOverlayInfosForTarget(self, string: str) -> java.util.List[OverlayInfo]: ...

class OverlayManagerTransaction(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    @staticmethod
    def newInstance() -> 'OverlayManagerTransaction': ...
    def registerFabricatedOverlay(self, fabricatedOverlay: FabricatedOverlay) -> None: ...
    def toString(self) -> str: ...
    def unregisterFabricatedOverlay(self, overlayIdentifier: OverlayIdentifier) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.content.om")``.

    FabricatedOverlay: typing.Type[FabricatedOverlay]
    OverlayIdentifier: typing.Type[OverlayIdentifier]
    OverlayInfo: typing.Type[OverlayInfo]
    OverlayManager: typing.Type[OverlayManager]
    OverlayManagerTransaction: typing.Type[OverlayManagerTransaction]
