
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.graphics.drawable
import android.location
import android.os
import java.lang
import java.util
import typing



class GetWalletCardsCallback:
    def onFailure(self, getWalletCardsError: 'GetWalletCardsError') -> None: ...
    def onSuccess(self, getWalletCardsResponse: 'GetWalletCardsResponse') -> None: ...

class GetWalletCardsError(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, icon: android.graphics.drawable.Icon, charSequence: typing.Union[java.lang.CharSequence, str]): ...
    def describeContents(self) -> int: ...
    def getIcon(self) -> android.graphics.drawable.Icon: ...
    def getMessage(self) -> java.lang.CharSequence: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GetWalletCardsRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, int4: int): ...
    def describeContents(self) -> int: ...
    def getCardHeightPx(self) -> int: ...
    def getCardWidthPx(self) -> int: ...
    def getIconSizePx(self) -> int: ...
    def getMaxCards(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GetWalletCardsResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List['WalletCard'], int: int): ...
    def describeContents(self) -> int: ...
    def getSelectedIndex(self) -> int: ...
    def getWalletCards(self) -> java.util.List['WalletCard']: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class QuickAccessWalletService(android.app.Service):
    ACTION_VIEW_WALLET: typing.ClassVar[str] = ...
    ACTION_VIEW_WALLET_SETTINGS: typing.ClassVar[str] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def getTargetActivityPendingIntent(self) -> android.app.PendingIntent: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onWalletCardSelected(self, selectWalletCardRequest: 'SelectWalletCardRequest') -> None: ...
    def onWalletCardsRequested(self, getWalletCardsRequest: GetWalletCardsRequest, getWalletCardsCallback: GetWalletCardsCallback) -> None: ...
    def onWalletDismissed(self) -> None: ...
    def sendWalletServiceEvent(self, walletServiceEvent: 'WalletServiceEvent') -> None: ...

class SelectWalletCardRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str): ...
    def describeContents(self) -> int: ...
    def getCardId(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WalletCard(android.os.Parcelable):
    CARD_TYPE_NON_PAYMENT: typing.ClassVar[int] = ...
    CARD_TYPE_PAYMENT: typing.ClassVar[int] = ...
    CARD_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getCardIcon(self) -> android.graphics.drawable.Icon: ...
    def getCardId(self) -> str: ...
    def getCardImage(self) -> android.graphics.drawable.Icon: ...
    def getCardLabel(self) -> java.lang.CharSequence: ...
    def getCardLocations(self) -> java.util.List[android.location.Location]: ...
    def getCardType(self) -> int: ...
    def getContentDescription(self) -> java.lang.CharSequence: ...
    def getNonPaymentCardSecondaryImage(self) -> android.graphics.drawable.Icon: ...
    def getPendingIntent(self) -> android.app.PendingIntent: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, string: str, icon: android.graphics.drawable.Icon, charSequence: typing.Union[java.lang.CharSequence, str], pendingIntent: android.app.PendingIntent): ...
        @typing.overload
        def __init__(self, string: str, int: int, icon: android.graphics.drawable.Icon, charSequence: typing.Union[java.lang.CharSequence, str], pendingIntent: android.app.PendingIntent): ...
        def build(self) -> 'WalletCard': ...
        def setCardIcon(self, icon: android.graphics.drawable.Icon) -> 'WalletCard.Builder': ...
        def setCardLabel(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'WalletCard.Builder': ...
        def setCardLocations(self, list: java.util.List[android.location.Location]) -> 'WalletCard.Builder': ...
        def setNonPaymentCardSecondaryImage(self, icon: android.graphics.drawable.Icon) -> 'WalletCard.Builder': ...

class WalletServiceEvent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_NFC_PAYMENT_STARTED: typing.ClassVar[int] = ...
    def __init__(self, int: int): ...
    def describeContents(self) -> int: ...
    def getEventType(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.quickaccesswallet")``.

    GetWalletCardsCallback: typing.Type[GetWalletCardsCallback]
    GetWalletCardsError: typing.Type[GetWalletCardsError]
    GetWalletCardsRequest: typing.Type[GetWalletCardsRequest]
    GetWalletCardsResponse: typing.Type[GetWalletCardsResponse]
    QuickAccessWalletService: typing.Type[QuickAccessWalletService]
    SelectWalletCardRequest: typing.Type[SelectWalletCardRequest]
    WalletCard: typing.Type[WalletCard]
    WalletServiceEvent: typing.Type[WalletServiceEvent]
