
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.net
import android.os
import android.security.identity
import android.security.keystore
import java.lang
import java.math
import java.security
import java.security.cert
import java.security.spec
import java.util
import java.util.concurrent
import javax.security.auth.x500
import jpype
import typing



class AppUriAuthenticationPolicy(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAppAndUriMappings(self) -> java.util.Map[str, java.util.Map[android.net.Uri, str]]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addAppAndUriMapping(self, string: str, uri: android.net.Uri, string2: str) -> 'AppUriAuthenticationPolicy.Builder': ...
        def build(self) -> 'AppUriAuthenticationPolicy': ...

class AttestedKeyPair:
    def __init__(self, keyPair: java.security.KeyPair, list: java.util.List[java.security.cert.Certificate]): ...
    def getAttestationRecord(self) -> java.util.List[java.security.cert.Certificate]: ...
    def getKeyPair(self) -> java.security.KeyPair: ...

class ConfirmationAlreadyPresentingException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class ConfirmationCallback:
    def __init__(self): ...
    def onCanceled(self) -> None: ...
    def onConfirmed(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def onDismissed(self) -> None: ...
    def onError(self, throwable: java.lang.Throwable) -> None: ...

class ConfirmationNotAvailableException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...

class ConfirmationPrompt:
    def cancelPrompt(self) -> None: ...
    @staticmethod
    def isSupported(context: android.content.Context) -> bool: ...
    def presentPrompt(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], confirmationCallback: ConfirmationCallback) -> None: ...
    class Builder:
        def __init__(self, context: android.content.Context): ...
        def build(self) -> 'ConfirmationPrompt': ...
        def setExtraData(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ConfirmationPrompt.Builder': ...
        def setPromptText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'ConfirmationPrompt.Builder': ...

class FileIntegrityManager:
    def isApkVeritySupported(self) -> bool: ...
    def isAppSourceCertificateTrusted(self, x509Certificate: java.security.cert.X509Certificate) -> bool: ...

class KeyChain:
    ACTION_KEYCHAIN_CHANGED: typing.ClassVar[str] = ...
    ACTION_KEY_ACCESS_CHANGED: typing.ClassVar[str] = ...
    ACTION_STORAGE_CHANGED: typing.ClassVar[str] = ...
    ACTION_TRUST_STORE_CHANGED: typing.ClassVar[str] = ...
    EXTRA_CERTIFICATE: typing.ClassVar[str] = ...
    EXTRA_KEY_ACCESSIBLE: typing.ClassVar[str] = ...
    EXTRA_KEY_ALIAS: typing.ClassVar[str] = ...
    EXTRA_NAME: typing.ClassVar[str] = ...
    EXTRA_PKCS12: typing.ClassVar[str] = ...
    KEY_ALIAS_SELECTION_DENIED: typing.ClassVar[str] = ...
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def choosePrivateKeyAlias(activity: android.app.Activity, keyChainAliasCallback: typing.Union['KeyChainAliasCallback', typing.Callable], stringArray: typing.Union[typing.List[str], jpype.JArray], principalArray: typing.Union[typing.List[java.security.Principal], jpype.JArray], uri: android.net.Uri, string2: str) -> None: ...
    @typing.overload
    @staticmethod
    def choosePrivateKeyAlias(activity: android.app.Activity, keyChainAliasCallback: typing.Union['KeyChainAliasCallback', typing.Callable], stringArray: typing.Union[typing.List[str], jpype.JArray], principalArray: typing.Union[typing.List[java.security.Principal], jpype.JArray], string2: str, int: int, string3: str) -> None: ...
    @staticmethod
    def createInstallIntent() -> android.content.Intent: ...
    @staticmethod
    def createManageCredentialsIntent(appUriAuthenticationPolicy: AppUriAuthenticationPolicy) -> android.content.Intent: ...
    @staticmethod
    def getCertificateChain(context: android.content.Context, string: str) -> typing.MutableSequence[java.security.cert.X509Certificate]: ...
    @staticmethod
    def getCredentialManagementAppPolicy(context: android.content.Context) -> AppUriAuthenticationPolicy: ...
    @staticmethod
    def getPrivateKey(context: android.content.Context, string: str) -> java.security.PrivateKey: ...
    @staticmethod
    def isBoundKeyAlgorithm(string: str) -> bool: ...
    @staticmethod
    def isCredentialManagementApp(context: android.content.Context) -> bool: ...
    @staticmethod
    def isKeyAlgorithmSupported(string: str) -> bool: ...
    @staticmethod
    def removeCredentialManagementApp(context: android.content.Context) -> bool: ...

class KeyChainAliasCallback:
    def alias(self, string: str) -> None: ...

class KeyChainException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class KeyPairGeneratorSpec(java.security.spec.AlgorithmParameterSpec):
    def getAlgorithmParameterSpec(self) -> java.security.spec.AlgorithmParameterSpec: ...
    def getContext(self) -> android.content.Context: ...
    def getEndDate(self) -> java.util.Date: ...
    def getKeySize(self) -> int: ...
    def getKeyType(self) -> str: ...
    def getKeystoreAlias(self) -> str: ...
    def getSerialNumber(self) -> java.math.BigInteger: ...
    def getStartDate(self) -> java.util.Date: ...
    def getSubjectDN(self) -> javax.security.auth.x500.X500Principal: ...
    def isEncryptionRequired(self) -> bool: ...
    class Builder:
        def __init__(self, context: android.content.Context): ...
        def build(self) -> 'KeyPairGeneratorSpec': ...
        def setAlgorithmParameterSpec(self, algorithmParameterSpec: java.security.spec.AlgorithmParameterSpec) -> 'KeyPairGeneratorSpec.Builder': ...
        def setAlias(self, string: str) -> 'KeyPairGeneratorSpec.Builder': ...
        def setEncryptionRequired(self) -> 'KeyPairGeneratorSpec.Builder': ...
        def setEndDate(self, date: java.util.Date) -> 'KeyPairGeneratorSpec.Builder': ...
        def setKeySize(self, int: int) -> 'KeyPairGeneratorSpec.Builder': ...
        def setKeyType(self, string: str) -> 'KeyPairGeneratorSpec.Builder': ...
        def setSerialNumber(self, bigInteger: java.math.BigInteger) -> 'KeyPairGeneratorSpec.Builder': ...
        def setStartDate(self, date: java.util.Date) -> 'KeyPairGeneratorSpec.Builder': ...
        def setSubject(self, x500Principal: javax.security.auth.x500.X500Principal) -> 'KeyPairGeneratorSpec.Builder': ...

class KeyStoreException(java.lang.Exception):
    ERROR_ATTESTATION_CHALLENGE_TOO_LARGE: typing.ClassVar[int] = ...
    ERROR_ATTESTATION_KEYS_UNAVAILABLE: typing.ClassVar[int] = ...
    ERROR_ID_ATTESTATION_FAILURE: typing.ClassVar[int] = ...
    ERROR_INCORRECT_USAGE: typing.ClassVar[int] = ...
    ERROR_INTERNAL_SYSTEM_ERROR: typing.ClassVar[int] = ...
    ERROR_KEYMINT_FAILURE: typing.ClassVar[int] = ...
    ERROR_KEYSTORE_FAILURE: typing.ClassVar[int] = ...
    ERROR_KEYSTORE_UNINITIALIZED: typing.ClassVar[int] = ...
    ERROR_KEY_CORRUPTED: typing.ClassVar[int] = ...
    ERROR_KEY_DOES_NOT_EXIST: typing.ClassVar[int] = ...
    ERROR_KEY_NOT_TEMPORALLY_VALID: typing.ClassVar[int] = ...
    ERROR_KEY_OPERATION_EXPIRED: typing.ClassVar[int] = ...
    ERROR_OTHER: typing.ClassVar[int] = ...
    ERROR_PERMISSION_DENIED: typing.ClassVar[int] = ...
    ERROR_UNIMPLEMENTED: typing.ClassVar[int] = ...
    ERROR_USER_AUTHENTICATION_REQUIRED: typing.ClassVar[int] = ...
    RETRY_AFTER_NEXT_REBOOT: typing.ClassVar[int] = ...
    RETRY_NEVER: typing.ClassVar[int] = ...
    RETRY_WHEN_CONNECTIVITY_AVAILABLE: typing.ClassVar[int] = ...
    RETRY_WITH_EXPONENTIAL_BACKOFF: typing.ClassVar[int] = ...
    def getNumericErrorCode(self) -> int: ...
    def getRetryPolicy(self) -> int: ...
    def isSystemError(self) -> bool: ...
    def isTransientFailure(self) -> bool: ...
    def requiresUserAuthentication(self) -> bool: ...
    def toString(self) -> str: ...

class KeyStoreParameter(java.security.KeyStore.ProtectionParameter):
    def isEncryptionRequired(self) -> bool: ...
    class Builder:
        def __init__(self, context: android.content.Context): ...
        def build(self) -> 'KeyStoreParameter': ...
        def setEncryptionRequired(self, boolean: bool) -> 'KeyStoreParameter.Builder': ...

class NetworkSecurityPolicy:
    @staticmethod
    def getInstance() -> 'NetworkSecurityPolicy': ...
    @typing.overload
    def isCleartextTrafficPermitted(self) -> bool: ...
    @typing.overload
    def isCleartextTrafficPermitted(self, string: str) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.security")``.

    AppUriAuthenticationPolicy: typing.Type[AppUriAuthenticationPolicy]
    AttestedKeyPair: typing.Type[AttestedKeyPair]
    ConfirmationAlreadyPresentingException: typing.Type[ConfirmationAlreadyPresentingException]
    ConfirmationCallback: typing.Type[ConfirmationCallback]
    ConfirmationNotAvailableException: typing.Type[ConfirmationNotAvailableException]
    ConfirmationPrompt: typing.Type[ConfirmationPrompt]
    FileIntegrityManager: typing.Type[FileIntegrityManager]
    KeyChain: typing.Type[KeyChain]
    KeyChainAliasCallback: typing.Type[KeyChainAliasCallback]
    KeyChainException: typing.Type[KeyChainException]
    KeyPairGeneratorSpec: typing.Type[KeyPairGeneratorSpec]
    KeyStoreException: typing.Type[KeyStoreException]
    KeyStoreParameter: typing.Type[KeyStoreParameter]
    NetworkSecurityPolicy: typing.Type[NetworkSecurityPolicy]
    identity: android.security.identity.__module_protocol__
    keystore: android.security.keystore.__module_protocol__
