
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.media.browse
import android.media.session
import android.os
import java.io
import java.util
import jpype
import typing



class CameraPrewarmService(android.app.Service):
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onCooldown(self, boolean: bool) -> None: ...
    def onPrewarm(self) -> None: ...
    def onUnbind(self, intent: android.content.Intent) -> bool: ...

_MediaBrowserService__Result__T = typing.TypeVar('_MediaBrowserService__Result__T')  # <T>
class MediaBrowserService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def dump(self, fileDescriptor: java.io.FileDescriptor, printWriter: java.io.PrintWriter, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def getBrowserRootHints(self) -> android.os.Bundle: ...
    def getCurrentBrowserInfo(self) -> android.media.session.MediaSessionManager.RemoteUserInfo: ...
    def getSessionToken(self) -> android.media.session.MediaSession.Token: ...
    @typing.overload
    def notifyChildrenChanged(self, string: str) -> None: ...
    @typing.overload
    def notifyChildrenChanged(self, string: str, bundle: android.os.Bundle) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onCreate(self) -> None: ...
    def onGetRoot(self, string: str, int: int, bundle: android.os.Bundle) -> 'MediaBrowserService.BrowserRoot': ...
    @typing.overload
    def onLoadChildren(self, string: str, result: 'MediaBrowserService.Result'[java.util.List[android.media.browse.MediaBrowser.MediaItem]]) -> None: ...
    @typing.overload
    def onLoadChildren(self, string: str, result: 'MediaBrowserService.Result'[java.util.List[android.media.browse.MediaBrowser.MediaItem]], bundle: android.os.Bundle) -> None: ...
    def onLoadItem(self, string: str, result: 'MediaBrowserService.Result'[android.media.browse.MediaBrowser.MediaItem]) -> None: ...
    def setSessionToken(self, token: android.media.session.MediaSession.Token) -> None: ...
    class BrowserRoot:
        EXTRA_OFFLINE: typing.ClassVar[str] = ...
        EXTRA_RECENT: typing.ClassVar[str] = ...
        EXTRA_SUGGESTED: typing.ClassVar[str] = ...
        def __init__(self, string: str, bundle: android.os.Bundle): ...
        def getExtras(self) -> android.os.Bundle: ...
        def getRootId(self) -> str: ...
    class Result(typing.Generic[_MediaBrowserService__Result__T]):
        def detach(self) -> None: ...
        def sendResult(self, t: _MediaBrowserService__Result__T) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.media")``.

    CameraPrewarmService: typing.Type[CameraPrewarmService]
    MediaBrowserService: typing.Type[MediaBrowserService]
