
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.text
import android.text.style
import android.widget
import java.lang
import java.util
import java.util.function
import java.util.regex
import jpype
import typing



class Linkify:
    ALL: typing.ClassVar[int] = ...
    EMAIL_ADDRESSES: typing.ClassVar[int] = ...
    MAP_ADDRESSES: typing.ClassVar[int] = ...
    PHONE_NUMBERS: typing.ClassVar[int] = ...
    WEB_URLS: typing.ClassVar[int] = ...
    sPhoneNumberMatchFilter: typing.ClassVar['Linkify.MatchFilter'] = ...
    sPhoneNumberTransformFilter: typing.ClassVar['Linkify.TransformFilter'] = ...
    sUrlMatchFilter: typing.ClassVar['Linkify.MatchFilter'] = ...
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def addLinks(spannable: android.text.Spannable, int: int) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(spannable: android.text.Spannable, int: int, function: typing.Union[java.util.function.Function[str, android.text.style.URLSpan], typing.Callable[[str], android.text.style.URLSpan]]) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(spannable: android.text.Spannable, pattern: java.util.regex.Pattern, string: str) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(spannable: android.text.Spannable, pattern: java.util.regex.Pattern, string: str, matchFilter: typing.Union['Linkify.MatchFilter', typing.Callable], transformFilter: typing.Union['Linkify.TransformFilter', typing.Callable]) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(spannable: android.text.Spannable, pattern: java.util.regex.Pattern, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], matchFilter: typing.Union['Linkify.MatchFilter', typing.Callable], transformFilter: typing.Union['Linkify.TransformFilter', typing.Callable]) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(spannable: android.text.Spannable, pattern: java.util.regex.Pattern, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], matchFilter: typing.Union['Linkify.MatchFilter', typing.Callable], transformFilter: typing.Union['Linkify.TransformFilter', typing.Callable], function: typing.Union[java.util.function.Function[str, android.text.style.URLSpan], typing.Callable[[str], android.text.style.URLSpan]]) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(textView: android.widget.TextView, int: int) -> bool: ...
    @typing.overload
    @staticmethod
    def addLinks(textView: android.widget.TextView, pattern: java.util.regex.Pattern, string: str) -> None: ...
    @typing.overload
    @staticmethod
    def addLinks(textView: android.widget.TextView, pattern: java.util.regex.Pattern, string: str, matchFilter: typing.Union['Linkify.MatchFilter', typing.Callable], transformFilter: typing.Union['Linkify.TransformFilter', typing.Callable]) -> None: ...
    @typing.overload
    @staticmethod
    def addLinks(textView: android.widget.TextView, pattern: java.util.regex.Pattern, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], matchFilter: typing.Union['Linkify.MatchFilter', typing.Callable], transformFilter: typing.Union['Linkify.TransformFilter', typing.Callable]) -> None: ...
    class MatchFilter:
        def acceptMatch(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> bool: ...
    class TransformFilter:
        def transformUrl(self, matcher: java.util.regex.Matcher, string: str) -> str: ...

class Rfc822Token:
    def __init__(self, string: str, string2: str, string3: str): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAddress(self) -> str: ...
    def getComment(self) -> str: ...
    def getName(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def quoteComment(string: str) -> str: ...
    @staticmethod
    def quoteName(string: str) -> str: ...
    @staticmethod
    def quoteNameIfNecessary(string: str) -> str: ...
    def setAddress(self, string: str) -> None: ...
    def setComment(self, string: str) -> None: ...
    def setName(self, string: str) -> None: ...
    def toString(self) -> str: ...

class Rfc822Tokenizer(android.widget.MultiAutoCompleteTextView.Tokenizer):
    def __init__(self): ...
    def findTokenEnd(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int) -> int: ...
    def findTokenStart(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int) -> int: ...
    def terminateToken(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def tokenize(charSequence: typing.Union[java.lang.CharSequence, str]) -> typing.MutableSequence[Rfc822Token]: ...
    @typing.overload
    @staticmethod
    def tokenize(charSequence: typing.Union[java.lang.CharSequence, str], collection: typing.Union[java.util.Collection[Rfc822Token], typing.Sequence[Rfc822Token], typing.Set[Rfc822Token]]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.text.util")``.

    Linkify: typing.Type[Linkify]
    Rfc822Token: typing.Type[Rfc822Token]
    Rfc822Tokenizer: typing.Type[Rfc822Tokenizer]
