
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.pm
import android.graphics
import android.net
import android.net.http
import android.os
import android.print_
import android.util
import android.view
import android.view.accessibility
import android.view.autofill
import android.view.inputmethod
import android.view.textclassifier
import android.view.translation
import android.widget
import java.io
import java.lang
import java.lang.annotation
import java.security
import java.security.cert
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class ClientCertRequest:
    def __init__(self): ...
    def cancel(self) -> None: ...
    def getHost(self) -> str: ...
    def getKeyTypes(self) -> typing.MutableSequence[str]: ...
    def getPort(self) -> int: ...
    def getPrincipals(self) -> typing.MutableSequence[java.security.Principal]: ...
    def ignore(self) -> None: ...
    def proceed(self, privateKey: java.security.PrivateKey, x509CertificateArray: typing.Union[typing.List[java.security.cert.X509Certificate], jpype.JArray]) -> None: ...

class ConsoleMessage:
    def __init__(self, string: str, string2: str, int: int, messageLevel: 'ConsoleMessage.MessageLevel'): ...
    def lineNumber(self) -> int: ...
    def message(self) -> str: ...
    def messageLevel(self) -> 'ConsoleMessage.MessageLevel': ...
    def sourceId(self) -> str: ...
    class MessageLevel(java.lang.Enum['ConsoleMessage.MessageLevel']):
        TIP: typing.ClassVar['ConsoleMessage.MessageLevel'] = ...
        LOG: typing.ClassVar['ConsoleMessage.MessageLevel'] = ...
        WARNING: typing.ClassVar['ConsoleMessage.MessageLevel'] = ...
        ERROR: typing.ClassVar['ConsoleMessage.MessageLevel'] = ...
        DEBUG: typing.ClassVar['ConsoleMessage.MessageLevel'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'ConsoleMessage.MessageLevel': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['ConsoleMessage.MessageLevel']: ...

class CookieManager:
    def __init__(self): ...
    def acceptCookie(self) -> bool: ...
    def acceptThirdPartyCookies(self, webView: 'WebView') -> bool: ...
    @staticmethod
    def allowFileSchemeCookies() -> bool: ...
    def flush(self) -> None: ...
    def getCookie(self, string: str) -> str: ...
    @staticmethod
    def getInstance() -> 'CookieManager': ...
    def hasCookies(self) -> bool: ...
    def removeAllCookie(self) -> None: ...
    def removeAllCookies(self, valueCallback: typing.Union['ValueCallback'[bool], typing.Callable[[bool], None]]) -> None: ...
    def removeExpiredCookie(self) -> None: ...
    def removeSessionCookie(self) -> None: ...
    def removeSessionCookies(self, valueCallback: typing.Union['ValueCallback'[bool], typing.Callable[[bool], None]]) -> None: ...
    def setAcceptCookie(self, boolean: bool) -> None: ...
    @staticmethod
    def setAcceptFileSchemeCookies(boolean: bool) -> None: ...
    def setAcceptThirdPartyCookies(self, webView: 'WebView', boolean: bool) -> None: ...
    @typing.overload
    def setCookie(self, string: str, string2: str) -> None: ...
    @typing.overload
    def setCookie(self, string: str, string2: str, valueCallback: typing.Union['ValueCallback'[bool], typing.Callable[[bool], None]]) -> None: ...

class CookieSyncManager(java.lang.Runnable):
    @staticmethod
    def createInstance(context: android.content.Context) -> 'CookieSyncManager': ...
    @staticmethod
    def getInstance() -> 'CookieSyncManager': ...
    def resetSync(self) -> None: ...
    def run(self) -> None: ...
    def startSync(self) -> None: ...
    def stopSync(self) -> None: ...
    def sync(self) -> None: ...

class DateSorter:
    DAY_COUNT: typing.ClassVar[int] = ...
    def __init__(self, context: android.content.Context): ...
    def getBoundary(self, int: int) -> int: ...
    def getIndex(self, long: int) -> int: ...
    def getLabel(self, int: int) -> str: ...

class DownloadListener:
    def onDownloadStart(self, string: str, string2: str, string3: str, string4: str, long: int) -> None: ...

class GeolocationPermissions:
    def allow(self, string: str) -> None: ...
    def clear(self, string: str) -> None: ...
    def clearAll(self) -> None: ...
    def getAllowed(self, string: str, valueCallback: typing.Union['ValueCallback'[bool], typing.Callable[[bool], None]]) -> None: ...
    @staticmethod
    def getInstance() -> 'GeolocationPermissions': ...
    def getOrigins(self, valueCallback: typing.Union['ValueCallback'[java.util.Set[str]], typing.Callable[[java.util.Set[str]], None]]) -> None: ...
    class Callback:
        def invoke(self, string: str, boolean: bool, boolean2: bool) -> None: ...

class HttpAuthHandler(android.os.Handler):
    def cancel(self) -> None: ...
    def proceed(self, string: str, string2: str) -> None: ...
    def useHttpAuthUsernamePassword(self) -> bool: ...

class JavascriptInterface(java.lang.annotation.Annotation):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class JsResult:
    def cancel(self) -> None: ...
    def confirm(self) -> None: ...

class MimeTypeMap:
    def getExtensionFromMimeType(self, string: str) -> str: ...
    @staticmethod
    def getFileExtensionFromUrl(string: str) -> str: ...
    def getMimeTypeFromExtension(self, string: str) -> str: ...
    @staticmethod
    def getSingleton() -> 'MimeTypeMap': ...
    def hasExtension(self, string: str) -> bool: ...
    def hasMimeType(self, string: str) -> bool: ...

class PermissionRequest:
    RESOURCE_AUDIO_CAPTURE: typing.ClassVar[str] = ...
    RESOURCE_MIDI_SYSEX: typing.ClassVar[str] = ...
    RESOURCE_PROTECTED_MEDIA_ID: typing.ClassVar[str] = ...
    RESOURCE_VIDEO_CAPTURE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def deny(self) -> None: ...
    def getOrigin(self) -> android.net.Uri: ...
    def getResources(self) -> typing.MutableSequence[str]: ...
    def grant(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...

class PluginStub:
    def getEmbeddedView(self, int: int, context: android.content.Context) -> android.view.View: ...
    def getFullScreenView(self, int: int, context: android.content.Context) -> android.view.View: ...

class RenderProcessGoneDetail:
    def __init__(self): ...
    def didCrash(self) -> bool: ...
    def rendererPriorityAtExit(self) -> int: ...

class SafeBrowsingResponse:
    def __init__(self): ...
    def backToSafety(self, boolean: bool) -> None: ...
    def proceed(self, boolean: bool) -> None: ...
    def showInterstitial(self, boolean: bool) -> None: ...

class ServiceWorkerClient:
    def __init__(self): ...
    def shouldInterceptRequest(self, webResourceRequest: 'WebResourceRequest') -> 'WebResourceResponse': ...

class ServiceWorkerController:
    def __init__(self): ...
    @staticmethod
    def getInstance() -> 'ServiceWorkerController': ...
    def getServiceWorkerWebSettings(self) -> 'ServiceWorkerWebSettings': ...
    def setServiceWorkerClient(self, serviceWorkerClient: ServiceWorkerClient) -> None: ...

class ServiceWorkerWebSettings:
    def __init__(self): ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def setAllowContentAccess(self, boolean: bool) -> None: ...
    def setAllowFileAccess(self, boolean: bool) -> None: ...
    def setBlockNetworkLoads(self, boolean: bool) -> None: ...
    def setCacheMode(self, int: int) -> None: ...

class SslErrorHandler(android.os.Handler):
    def cancel(self) -> None: ...
    def proceed(self) -> None: ...

class TracingConfig:
    CATEGORIES_ALL: typing.ClassVar[int] = ...
    CATEGORIES_ANDROID_WEBVIEW: typing.ClassVar[int] = ...
    CATEGORIES_FRAME_VIEWER: typing.ClassVar[int] = ...
    CATEGORIES_INPUT_LATENCY: typing.ClassVar[int] = ...
    CATEGORIES_JAVASCRIPT_AND_RENDERING: typing.ClassVar[int] = ...
    CATEGORIES_NONE: typing.ClassVar[int] = ...
    CATEGORIES_RENDERING: typing.ClassVar[int] = ...
    CATEGORIES_WEB_DEVELOPER: typing.ClassVar[int] = ...
    RECORD_CONTINUOUSLY: typing.ClassVar[int] = ...
    RECORD_UNTIL_FULL: typing.ClassVar[int] = ...
    def getCustomIncludedCategories(self) -> java.util.List[str]: ...
    def getPredefinedCategories(self) -> int: ...
    def getTracingMode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        @typing.overload
        def addCategories(self, *int: int) -> 'TracingConfig.Builder': ...
        @typing.overload
        def addCategories(self, *string: str) -> 'TracingConfig.Builder': ...
        @typing.overload
        def addCategories(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TracingConfig.Builder': ...
        def build(self) -> 'TracingConfig': ...
        def setTracingMode(self, int: int) -> 'TracingConfig.Builder': ...

class TracingController:
    def __init__(self): ...
    @staticmethod
    def getInstance() -> 'TracingController': ...
    def isTracing(self) -> bool: ...
    def start(self, tracingConfig: TracingConfig) -> None: ...
    def stop(self, outputStream: java.io.OutputStream, executor: typing.Union[java.util.concurrent.Executor, typing.Callable]) -> bool: ...

class URLUtil:
    def __init__(self): ...
    @staticmethod
    def composeSearchUrl(string: str, string2: str, string3: str) -> str: ...
    @staticmethod
    def decode(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    @staticmethod
    def guessFileName(string: str, string2: str, string3: str) -> str: ...
    @staticmethod
    def guessUrl(string: str) -> str: ...
    @staticmethod
    def isAboutUrl(string: str) -> bool: ...
    @staticmethod
    def isAssetUrl(string: str) -> bool: ...
    @staticmethod
    def isContentUrl(string: str) -> bool: ...
    @staticmethod
    def isCookielessProxyUrl(string: str) -> bool: ...
    @staticmethod
    def isDataUrl(string: str) -> bool: ...
    @staticmethod
    def isFileUrl(string: str) -> bool: ...
    @staticmethod
    def isHttpUrl(string: str) -> bool: ...
    @staticmethod
    def isHttpsUrl(string: str) -> bool: ...
    @staticmethod
    def isJavaScriptUrl(string: str) -> bool: ...
    @staticmethod
    def isNetworkUrl(string: str) -> bool: ...
    @staticmethod
    def isValidUrl(string: str) -> bool: ...
    @staticmethod
    def stripAnchor(string: str) -> str: ...

_ValueCallback__T = typing.TypeVar('_ValueCallback__T')  # <T>
class ValueCallback(typing.Generic[_ValueCallback__T]):
    def onReceiveValue(self, t: _ValueCallback__T) -> None: ...

class WebBackForwardList(java.lang.Cloneable, java.io.Serializable):
    def __init__(self): ...
    def getCurrentIndex(self) -> int: ...
    def getCurrentItem(self) -> 'WebHistoryItem': ...
    def getItemAtIndex(self, int: int) -> 'WebHistoryItem': ...
    def getSize(self) -> int: ...

class WebChromeClient:
    def __init__(self): ...
    def getDefaultVideoPoster(self) -> android.graphics.Bitmap: ...
    def getVideoLoadingProgressView(self) -> android.view.View: ...
    def getVisitedHistory(self, valueCallback: typing.Union[ValueCallback[typing.Union[typing.List[str], jpype.JArray]], typing.Callable[[typing.Union[typing.List[str], jpype.JArray]], None]]) -> None: ...
    def onCloseWindow(self, webView: 'WebView') -> None: ...
    @typing.overload
    def onConsoleMessage(self, consoleMessage: ConsoleMessage) -> bool: ...
    @typing.overload
    def onConsoleMessage(self, string: str, int: int, string2: str) -> None: ...
    def onCreateWindow(self, webView: 'WebView', boolean: bool, boolean2: bool, message: android.os.Message) -> bool: ...
    def onExceededDatabaseQuota(self, string: str, string2: str, long: int, long2: int, long3: int, quotaUpdater: typing.Union['WebStorage.QuotaUpdater', typing.Callable]) -> None: ...
    def onGeolocationPermissionsHidePrompt(self) -> None: ...
    def onGeolocationPermissionsShowPrompt(self, string: str, callback: typing.Union[GeolocationPermissions.Callback, typing.Callable]) -> None: ...
    def onHideCustomView(self) -> None: ...
    def onJsAlert(self, webView: 'WebView', string: str, string2: str, jsResult: JsResult) -> bool: ...
    def onJsBeforeUnload(self, webView: 'WebView', string: str, string2: str, jsResult: JsResult) -> bool: ...
    def onJsConfirm(self, webView: 'WebView', string: str, string2: str, jsResult: JsResult) -> bool: ...
    def onJsPrompt(self, webView: 'WebView', string: str, string2: str, string3: str, jsPromptResult: 'JsPromptResult') -> bool: ...
    def onJsTimeout(self) -> bool: ...
    def onPermissionRequest(self, permissionRequest: PermissionRequest) -> None: ...
    def onPermissionRequestCanceled(self, permissionRequest: PermissionRequest) -> None: ...
    def onProgressChanged(self, webView: 'WebView', int: int) -> None: ...
    def onReceivedIcon(self, webView: 'WebView', bitmap: android.graphics.Bitmap) -> None: ...
    def onReceivedTitle(self, webView: 'WebView', string: str) -> None: ...
    def onReceivedTouchIconUrl(self, webView: 'WebView', string: str, boolean: bool) -> None: ...
    def onRequestFocus(self, webView: 'WebView') -> None: ...
    @typing.overload
    def onShowCustomView(self, view: android.view.View, customViewCallback: typing.Union['WebChromeClient.CustomViewCallback', typing.Callable]) -> None: ...
    @typing.overload
    def onShowCustomView(self, view: android.view.View, int: int, customViewCallback: typing.Union['WebChromeClient.CustomViewCallback', typing.Callable]) -> None: ...
    def onShowFileChooser(self, webView: 'WebView', valueCallback: typing.Union[ValueCallback[typing.Union[typing.List[android.net.Uri], jpype.JArray]], typing.Callable[[typing.Union[typing.List[android.net.Uri], jpype.JArray]], None]], fileChooserParams: 'WebChromeClient.FileChooserParams') -> bool: ...
    class CustomViewCallback:
        def onCustomViewHidden(self) -> None: ...
    class FileChooserParams:
        MODE_OPEN: typing.ClassVar[int] = ...
        MODE_OPEN_MULTIPLE: typing.ClassVar[int] = ...
        MODE_SAVE: typing.ClassVar[int] = ...
        def __init__(self): ...
        def createIntent(self) -> android.content.Intent: ...
        def getAcceptTypes(self) -> typing.MutableSequence[str]: ...
        def getFilenameHint(self) -> str: ...
        def getMode(self) -> int: ...
        def getTitle(self) -> java.lang.CharSequence: ...
        def isCaptureEnabled(self) -> bool: ...
        @staticmethod
        def parseResult(int: int, intent: android.content.Intent) -> typing.MutableSequence[android.net.Uri]: ...

class WebHistoryItem(java.lang.Cloneable):
    def __init__(self): ...
    def getFavicon(self) -> android.graphics.Bitmap: ...
    def getOriginalUrl(self) -> str: ...
    def getTitle(self) -> str: ...
    def getUrl(self) -> str: ...

class WebIconDatabase:
    def __init__(self): ...
    def close(self) -> None: ...
    @staticmethod
    def getInstance() -> 'WebIconDatabase': ...
    def open(self, string: str) -> None: ...
    def releaseIconForPageUrl(self, string: str) -> None: ...
    def removeAllIcons(self) -> None: ...
    def requestIconForPageUrl(self, string: str, iconListener: typing.Union['WebIconDatabase.IconListener', typing.Callable]) -> None: ...
    def retainIconForPageUrl(self, string: str) -> None: ...
    class IconListener:
        def onReceivedIcon(self, string: str, bitmap: android.graphics.Bitmap) -> None: ...

class WebMessage:
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, webMessagePortArray: typing.Union[typing.List['WebMessagePort'], jpype.JArray]): ...
    def getData(self) -> str: ...
    def getPorts(self) -> typing.MutableSequence['WebMessagePort']: ...

class WebMessagePort:
    def close(self) -> None: ...
    def postMessage(self, webMessage: WebMessage) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, webMessageCallback: 'WebMessagePort.WebMessageCallback') -> None: ...
    @typing.overload
    def setWebMessageCallback(self, webMessageCallback: 'WebMessagePort.WebMessageCallback', handler: android.os.Handler) -> None: ...
    class WebMessageCallback:
        def __init__(self): ...
        def onMessage(self, webMessagePort: 'WebMessagePort', webMessage2: WebMessage) -> None: ...

class WebResourceError:
    def getDescription(self) -> java.lang.CharSequence: ...
    def getErrorCode(self) -> int: ...

class WebResourceRequest:
    def getMethod(self) -> str: ...
    def getRequestHeaders(self) -> java.util.Map[str, str]: ...
    def getUrl(self) -> android.net.Uri: ...
    def hasGesture(self) -> bool: ...
    def isForMainFrame(self) -> bool: ...
    def isRedirect(self) -> bool: ...

class WebResourceResponse:
    @typing.overload
    def __init__(self, string: str, string2: str, int: int, string3: str, map: typing.Union[java.util.Map[str, str], typing.Mapping[str, str]], inputStream: java.io.InputStream): ...
    @typing.overload
    def __init__(self, string: str, string2: str, inputStream: java.io.InputStream): ...
    def getData(self) -> java.io.InputStream: ...
    def getEncoding(self) -> str: ...
    def getMimeType(self) -> str: ...
    def getReasonPhrase(self) -> str: ...
    def getResponseHeaders(self) -> java.util.Map[str, str]: ...
    def getStatusCode(self) -> int: ...
    def setData(self, inputStream: java.io.InputStream) -> None: ...
    def setEncoding(self, string: str) -> None: ...
    def setMimeType(self, string: str) -> None: ...
    def setResponseHeaders(self, map: typing.Union[java.util.Map[str, str], typing.Mapping[str, str]]) -> None: ...
    def setStatusCodeAndReasonPhrase(self, int: int, string: str) -> None: ...

class WebSettings:
    FORCE_DARK_AUTO: typing.ClassVar[int] = ...
    FORCE_DARK_OFF: typing.ClassVar[int] = ...
    FORCE_DARK_ON: typing.ClassVar[int] = ...
    LOAD_CACHE_ELSE_NETWORK: typing.ClassVar[int] = ...
    LOAD_CACHE_ONLY: typing.ClassVar[int] = ...
    LOAD_DEFAULT: typing.ClassVar[int] = ...
    LOAD_NORMAL: typing.ClassVar[int] = ...
    LOAD_NO_CACHE: typing.ClassVar[int] = ...
    MENU_ITEM_NONE: typing.ClassVar[int] = ...
    MENU_ITEM_PROCESS_TEXT: typing.ClassVar[int] = ...
    MENU_ITEM_SHARE: typing.ClassVar[int] = ...
    MENU_ITEM_WEB_SEARCH: typing.ClassVar[int] = ...
    MIXED_CONTENT_ALWAYS_ALLOW: typing.ClassVar[int] = ...
    MIXED_CONTENT_COMPATIBILITY_MODE: typing.ClassVar[int] = ...
    MIXED_CONTENT_NEVER_ALLOW: typing.ClassVar[int] = ...
    def __init__(self): ...
    def enableSmoothTransition(self) -> bool: ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getAllowFileAccessFromFileURLs(self) -> bool: ...
    def getAllowUniversalAccessFromFileURLs(self) -> bool: ...
    def getBlockNetworkImage(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getBuiltInZoomControls(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def getCursiveFontFamily(self) -> str: ...
    def getDatabaseEnabled(self) -> bool: ...
    def getDatabasePath(self) -> str: ...
    def getDefaultFixedFontSize(self) -> int: ...
    def getDefaultFontSize(self) -> int: ...
    def getDefaultTextEncodingName(self) -> str: ...
    @staticmethod
    def getDefaultUserAgent(context: android.content.Context) -> str: ...
    def getDefaultZoom(self) -> 'WebSettings.ZoomDensity': ...
    def getDisabledActionModeMenuItems(self) -> int: ...
    def getDisplayZoomControls(self) -> bool: ...
    def getDomStorageEnabled(self) -> bool: ...
    def getFantasyFontFamily(self) -> str: ...
    def getFixedFontFamily(self) -> str: ...
    def getForceDark(self) -> int: ...
    def getJavaScriptCanOpenWindowsAutomatically(self) -> bool: ...
    def getJavaScriptEnabled(self) -> bool: ...
    def getLayoutAlgorithm(self) -> 'WebSettings.LayoutAlgorithm': ...
    def getLightTouchEnabled(self) -> bool: ...
    def getLoadWithOverviewMode(self) -> bool: ...
    def getLoadsImagesAutomatically(self) -> bool: ...
    def getMediaPlaybackRequiresUserGesture(self) -> bool: ...
    def getMinimumFontSize(self) -> int: ...
    def getMinimumLogicalFontSize(self) -> int: ...
    def getMixedContentMode(self) -> int: ...
    def getOffscreenPreRaster(self) -> bool: ...
    def getPluginState(self) -> 'WebSettings.PluginState': ...
    def getSafeBrowsingEnabled(self) -> bool: ...
    def getSansSerifFontFamily(self) -> str: ...
    def getSaveFormData(self) -> bool: ...
    def getSavePassword(self) -> bool: ...
    def getSerifFontFamily(self) -> str: ...
    def getStandardFontFamily(self) -> str: ...
    def getTextSize(self) -> 'WebSettings.TextSize': ...
    def getTextZoom(self) -> int: ...
    def getUseWideViewPort(self) -> bool: ...
    def getUserAgentString(self) -> str: ...
    def isAlgorithmicDarkeningAllowed(self) -> bool: ...
    def setAlgorithmicDarkeningAllowed(self, boolean: bool) -> None: ...
    def setAllowContentAccess(self, boolean: bool) -> None: ...
    def setAllowFileAccess(self, boolean: bool) -> None: ...
    def setAllowFileAccessFromFileURLs(self, boolean: bool) -> None: ...
    def setAllowUniversalAccessFromFileURLs(self, boolean: bool) -> None: ...
    def setBlockNetworkImage(self, boolean: bool) -> None: ...
    def setBlockNetworkLoads(self, boolean: bool) -> None: ...
    def setBuiltInZoomControls(self, boolean: bool) -> None: ...
    def setCacheMode(self, int: int) -> None: ...
    def setCursiveFontFamily(self, string: str) -> None: ...
    def setDatabaseEnabled(self, boolean: bool) -> None: ...
    def setDatabasePath(self, string: str) -> None: ...
    def setDefaultFixedFontSize(self, int: int) -> None: ...
    def setDefaultFontSize(self, int: int) -> None: ...
    def setDefaultTextEncodingName(self, string: str) -> None: ...
    def setDefaultZoom(self, zoomDensity: 'WebSettings.ZoomDensity') -> None: ...
    def setDisabledActionModeMenuItems(self, int: int) -> None: ...
    def setDisplayZoomControls(self, boolean: bool) -> None: ...
    def setDomStorageEnabled(self, boolean: bool) -> None: ...
    def setEnableSmoothTransition(self, boolean: bool) -> None: ...
    def setFantasyFontFamily(self, string: str) -> None: ...
    def setFixedFontFamily(self, string: str) -> None: ...
    def setForceDark(self, int: int) -> None: ...
    def setGeolocationDatabasePath(self, string: str) -> None: ...
    def setGeolocationEnabled(self, boolean: bool) -> None: ...
    def setJavaScriptCanOpenWindowsAutomatically(self, boolean: bool) -> None: ...
    def setJavaScriptEnabled(self, boolean: bool) -> None: ...
    def setLayoutAlgorithm(self, layoutAlgorithm: 'WebSettings.LayoutAlgorithm') -> None: ...
    def setLightTouchEnabled(self, boolean: bool) -> None: ...
    def setLoadWithOverviewMode(self, boolean: bool) -> None: ...
    def setLoadsImagesAutomatically(self, boolean: bool) -> None: ...
    def setMediaPlaybackRequiresUserGesture(self, boolean: bool) -> None: ...
    def setMinimumFontSize(self, int: int) -> None: ...
    def setMinimumLogicalFontSize(self, int: int) -> None: ...
    def setMixedContentMode(self, int: int) -> None: ...
    def setNeedInitialFocus(self, boolean: bool) -> None: ...
    def setOffscreenPreRaster(self, boolean: bool) -> None: ...
    def setPluginState(self, pluginState: 'WebSettings.PluginState') -> None: ...
    def setRenderPriority(self, renderPriority: 'WebSettings.RenderPriority') -> None: ...
    def setSafeBrowsingEnabled(self, boolean: bool) -> None: ...
    def setSansSerifFontFamily(self, string: str) -> None: ...
    def setSaveFormData(self, boolean: bool) -> None: ...
    def setSavePassword(self, boolean: bool) -> None: ...
    def setSerifFontFamily(self, string: str) -> None: ...
    def setStandardFontFamily(self, string: str) -> None: ...
    def setSupportMultipleWindows(self, boolean: bool) -> None: ...
    def setSupportZoom(self, boolean: bool) -> None: ...
    def setTextSize(self, textSize: 'WebSettings.TextSize') -> None: ...
    def setTextZoom(self, int: int) -> None: ...
    def setUseWideViewPort(self, boolean: bool) -> None: ...
    def setUserAgentString(self, string: str) -> None: ...
    def supportMultipleWindows(self) -> bool: ...
    def supportZoom(self) -> bool: ...
    class LayoutAlgorithm(java.lang.Enum['WebSettings.LayoutAlgorithm']):
        NORMAL: typing.ClassVar['WebSettings.LayoutAlgorithm'] = ...
        SINGLE_COLUMN: typing.ClassVar['WebSettings.LayoutAlgorithm'] = ...
        NARROW_COLUMNS: typing.ClassVar['WebSettings.LayoutAlgorithm'] = ...
        TEXT_AUTOSIZING: typing.ClassVar['WebSettings.LayoutAlgorithm'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'WebSettings.LayoutAlgorithm': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['WebSettings.LayoutAlgorithm']: ...
    class PluginState(java.lang.Enum['WebSettings.PluginState']):
        ON: typing.ClassVar['WebSettings.PluginState'] = ...
        ON_DEMAND: typing.ClassVar['WebSettings.PluginState'] = ...
        OFF: typing.ClassVar['WebSettings.PluginState'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'WebSettings.PluginState': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['WebSettings.PluginState']: ...
    class RenderPriority(java.lang.Enum['WebSettings.RenderPriority']):
        NORMAL: typing.ClassVar['WebSettings.RenderPriority'] = ...
        HIGH: typing.ClassVar['WebSettings.RenderPriority'] = ...
        LOW: typing.ClassVar['WebSettings.RenderPriority'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'WebSettings.RenderPriority': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['WebSettings.RenderPriority']: ...
    class TextSize(java.lang.Enum['WebSettings.TextSize']):
        SMALLEST: typing.ClassVar['WebSettings.TextSize'] = ...
        SMALLER: typing.ClassVar['WebSettings.TextSize'] = ...
        NORMAL: typing.ClassVar['WebSettings.TextSize'] = ...
        LARGER: typing.ClassVar['WebSettings.TextSize'] = ...
        LARGEST: typing.ClassVar['WebSettings.TextSize'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'WebSettings.TextSize': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['WebSettings.TextSize']: ...
    class ZoomDensity(java.lang.Enum['WebSettings.ZoomDensity']):
        FAR: typing.ClassVar['WebSettings.ZoomDensity'] = ...
        MEDIUM: typing.ClassVar['WebSettings.ZoomDensity'] = ...
        CLOSE: typing.ClassVar['WebSettings.ZoomDensity'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'WebSettings.ZoomDensity': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['WebSettings.ZoomDensity']: ...

class WebStorage:
    def deleteAllData(self) -> None: ...
    def deleteOrigin(self, string: str) -> None: ...
    @staticmethod
    def getInstance() -> 'WebStorage': ...
    def getOrigins(self, valueCallback: typing.Union[ValueCallback[typing.Union[java.util.Map, typing.Mapping]], typing.Callable[[typing.Union[java.util.Map, typing.Mapping]], None]]) -> None: ...
    def getQuotaForOrigin(self, string: str, valueCallback: typing.Union[ValueCallback[int], typing.Callable[[int], None]]) -> None: ...
    def getUsageForOrigin(self, string: str, valueCallback: typing.Union[ValueCallback[int], typing.Callable[[int], None]]) -> None: ...
    def setQuotaForOrigin(self, string: str, long: int) -> None: ...
    class Origin:
        def getOrigin(self) -> str: ...
        def getQuota(self) -> int: ...
        def getUsage(self) -> int: ...
    class QuotaUpdater:
        def updateQuota(self, long: int) -> None: ...

class WebView(android.widget.AbsoluteLayout, android.view.ViewTreeObserver.OnGlobalFocusChangeListener, android.view.ViewGroup.OnHierarchyChangeListener):
    RENDERER_PRIORITY_BOUND: typing.ClassVar[int] = ...
    RENDERER_PRIORITY_IMPORTANT: typing.ClassVar[int] = ...
    RENDERER_PRIORITY_WAIVED: typing.ClassVar[int] = ...
    SCHEME_GEO: typing.ClassVar[str] = ...
    SCHEME_MAILTO: typing.ClassVar[str] = ...
    SCHEME_TEL: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, boolean: bool): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def addJavascriptInterface(self, object: typing.Any, string: str) -> None: ...
    @typing.overload
    def autofill(self, autofillValue: android.view.autofill.AutofillValue) -> None: ...
    @typing.overload
    def autofill(self, sparseArray: android.util.SparseArray[android.view.autofill.AutofillValue]) -> None: ...
    def canGoBack(self) -> bool: ...
    def canGoBackOrForward(self, int: int) -> bool: ...
    def canGoForward(self) -> bool: ...
    def canZoomIn(self) -> bool: ...
    def canZoomOut(self) -> bool: ...
    def capturePicture(self) -> android.graphics.Picture: ...
    def clearCache(self, boolean: bool) -> None: ...
    @staticmethod
    def clearClientCertPreferences(runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> None: ...
    def clearFormData(self) -> None: ...
    def clearHistory(self) -> None: ...
    def clearMatches(self) -> None: ...
    def clearSslPreferences(self) -> None: ...
    def clearView(self) -> None: ...
    def computeScroll(self) -> None: ...
    def copyBackForwardList(self) -> WebBackForwardList: ...
    @typing.overload
    def createPrintDocumentAdapter(self) -> android.print_.PrintDocumentAdapter: ...
    @typing.overload
    def createPrintDocumentAdapter(self, string: str) -> android.print_.PrintDocumentAdapter: ...
    def createWebMessageChannel(self) -> typing.MutableSequence[WebMessagePort]: ...
    def destroy(self) -> None: ...
    @staticmethod
    def disableWebView() -> None: ...
    def dispatchCreateViewTranslationRequest(self, map: typing.Union[java.util.Map[android.view.autofill.AutofillId, typing.Union[typing.List[int], jpype.JArray]], typing.Mapping[android.view.autofill.AutofillId, typing.Union[typing.List[int], jpype.JArray]]], intArray: typing.Union[typing.List[int], jpype.JArray], translationCapability: android.view.translation.TranslationCapability, list: java.util.List[android.view.translation.ViewTranslationRequest]) -> None: ...
    def dispatchKeyEvent(self, keyEvent: android.view.KeyEvent) -> bool: ...
    def documentHasImages(self, message: android.os.Message) -> None: ...
    @staticmethod
    def enableSlowWholeDocumentDraw() -> None: ...
    def evaluateJavascript(self, string: str, valueCallback: typing.Union[ValueCallback[str], typing.Callable[[str], None]]) -> None: ...
    @staticmethod
    def findAddress(string: str) -> str: ...
    def findAll(self, string: str) -> int: ...
    def findAllAsync(self, string: str) -> None: ...
    def findFocus(self) -> android.view.View: ...
    def findNext(self, boolean: bool) -> None: ...
    def flingScroll(self, int: int, int2: int) -> None: ...
    def freeMemory(self) -> None: ...
    def getAccessibilityClassName(self) -> java.lang.CharSequence: ...
    def getAccessibilityNodeProvider(self) -> android.view.accessibility.AccessibilityNodeProvider: ...
    def getCertificate(self) -> android.net.http.SslCertificate: ...
    def getContentHeight(self) -> int: ...
    @staticmethod
    def getCurrentWebViewPackage() -> android.content.pm.PackageInfo: ...
    def getFavicon(self) -> android.graphics.Bitmap: ...
    def getHandler(self) -> android.os.Handler: ...
    def getHitTestResult(self) -> 'WebView.HitTestResult': ...
    def getHttpAuthUsernamePassword(self, string: str, string2: str) -> typing.MutableSequence[str]: ...
    def getOriginalUrl(self) -> str: ...
    def getProgress(self) -> int: ...
    def getRendererPriorityWaivedWhenNotVisible(self) -> bool: ...
    def getRendererRequestedPriority(self) -> int: ...
    @staticmethod
    def getSafeBrowsingPrivacyPolicyUrl() -> android.net.Uri: ...
    def getScale(self) -> float: ...
    def getSettings(self) -> WebSettings: ...
    def getTextClassifier(self) -> android.view.textclassifier.TextClassifier: ...
    def getTitle(self) -> str: ...
    def getUrl(self) -> str: ...
    def getWebChromeClient(self) -> WebChromeClient: ...
    @staticmethod
    def getWebViewClassLoader() -> java.lang.ClassLoader: ...
    def getWebViewClient(self) -> 'WebViewClient': ...
    def getWebViewLooper(self) -> android.os.Looper: ...
    def getWebViewRenderProcess(self) -> 'WebViewRenderProcess': ...
    def getWebViewRenderProcessClient(self) -> 'WebViewRenderProcessClient': ...
    def goBack(self) -> None: ...
    def goBackOrForward(self, int: int) -> None: ...
    def goForward(self) -> None: ...
    def invokeZoomPicker(self) -> None: ...
    def isPrivateBrowsingEnabled(self) -> bool: ...
    def isVisibleToUserForAutofill(self, int: int) -> bool: ...
    def loadData(self, string: str, string2: str, string3: str) -> None: ...
    def loadDataWithBaseURL(self, string: str, string2: str, string3: str, string4: str, string5: str) -> None: ...
    @typing.overload
    def loadUrl(self, string: str) -> None: ...
    @typing.overload
    def loadUrl(self, string: str, map: typing.Union[java.util.Map[str, str], typing.Mapping[str, str]]) -> None: ...
    def onApplyWindowInsets(self, windowInsets: android.view.WindowInsets) -> android.view.WindowInsets: ...
    def onCheckIsTextEditor(self) -> bool: ...
    def onChildViewAdded(self, view: android.view.View, view2: android.view.View) -> None: ...
    def onChildViewRemoved(self, view: android.view.View, view2: android.view.View) -> None: ...
    def onCreateInputConnection(self, editorInfo: android.view.inputmethod.EditorInfo) -> android.view.inputmethod.InputConnection: ...
    def onCreateVirtualViewTranslationRequests(self, longArray: typing.Union[typing.List[int], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], consumer: typing.Union[java.util.function.Consumer[android.view.translation.ViewTranslationRequest], typing.Callable[[android.view.translation.ViewTranslationRequest], None]]) -> None: ...
    def onDragEvent(self, dragEvent: android.view.DragEvent) -> bool: ...
    def onFinishTemporaryDetach(self) -> None: ...
    def onGenericMotionEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onGlobalFocusChanged(self, view: android.view.View, view2: android.view.View) -> None: ...
    def onHoverEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onKeyDown(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyMultiple(self, int: int, int2: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onPause(self) -> None: ...
    def onProvideAutofillVirtualStructure(self, viewStructure: android.view.ViewStructure, int: int) -> None: ...
    def onProvideContentCaptureStructure(self, viewStructure: android.view.ViewStructure, int: int) -> None: ...
    def onProvideVirtualStructure(self, viewStructure: android.view.ViewStructure) -> None: ...
    def onResolvePointerIcon(self, motionEvent: android.view.MotionEvent, int: int) -> android.view.PointerIcon: ...
    def onResume(self) -> None: ...
    def onStartTemporaryDetach(self) -> None: ...
    def onTouchEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onTrackballEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onVirtualViewTranslationResponses(self, longSparseArray: android.util.LongSparseArray[android.view.translation.ViewTranslationResponse]) -> None: ...
    def onWindowFocusChanged(self, boolean: bool) -> None: ...
    def overlayHorizontalScrollbar(self) -> bool: ...
    def overlayVerticalScrollbar(self) -> bool: ...
    def pageDown(self, boolean: bool) -> bool: ...
    def pageUp(self, boolean: bool) -> bool: ...
    def pauseTimers(self) -> None: ...
    @typing.overload
    def performLongClick(self, float: float, float2: float) -> bool: ...
    @typing.overload
    def performLongClick(self) -> bool: ...
    def postUrl(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def postVisualStateCallback(self, long: int, visualStateCallback: 'WebView.VisualStateCallback') -> None: ...
    def postWebMessage(self, webMessage: WebMessage, uri: android.net.Uri) -> None: ...
    def reload(self) -> None: ...
    def removeJavascriptInterface(self, string: str) -> None: ...
    def requestChildRectangleOnScreen(self, view: android.view.View, rect: android.graphics.Rect, boolean: bool) -> bool: ...
    @typing.overload
    def requestFocus(self, int: int, rect: android.graphics.Rect) -> bool: ...
    @typing.overload
    def requestFocus(self) -> bool: ...
    @typing.overload
    def requestFocus(self, int: int) -> bool: ...
    def requestFocusNodeHref(self, message: android.os.Message) -> None: ...
    def requestImageRef(self, message: android.os.Message) -> None: ...
    def restoreState(self, bundle: android.os.Bundle) -> WebBackForwardList: ...
    def resumeTimers(self) -> None: ...
    def savePassword(self, string: str, string2: str, string3: str) -> None: ...
    def saveState(self, bundle: android.os.Bundle) -> WebBackForwardList: ...
    @typing.overload
    def saveWebArchive(self, string: str) -> None: ...
    @typing.overload
    def saveWebArchive(self, string: str, boolean: bool, valueCallback: typing.Union[ValueCallback[str], typing.Callable[[str], None]]) -> None: ...
    def setBackgroundColor(self, int: int) -> None: ...
    def setCertificate(self, sslCertificate: android.net.http.SslCertificate) -> None: ...
    @staticmethod
    def setDataDirectorySuffix(string: str) -> None: ...
    def setDownloadListener(self, downloadListener: typing.Union[DownloadListener, typing.Callable]) -> None: ...
    def setFindListener(self, findListener: typing.Union['WebView.FindListener', typing.Callable]) -> None: ...
    def setHorizontalScrollbarOverlay(self, boolean: bool) -> None: ...
    def setHttpAuthUsernamePassword(self, string: str, string2: str, string3: str, string4: str) -> None: ...
    def setInitialScale(self, int: int) -> None: ...
    def setLayerType(self, int: int, paint: android.graphics.Paint) -> None: ...
    def setLayoutParams(self, layoutParams: android.view.ViewGroup.LayoutParams) -> None: ...
    def setMapTrackballToArrowKeys(self, boolean: bool) -> None: ...
    def setNetworkAvailable(self, boolean: bool) -> None: ...
    def setOverScrollMode(self, int: int) -> None: ...
    def setPictureListener(self, pictureListener: typing.Union['WebView.PictureListener', typing.Callable]) -> None: ...
    def setRendererPriorityPolicy(self, int: int, boolean: bool) -> None: ...
    @staticmethod
    def setSafeBrowsingWhitelist(list: java.util.List[str], valueCallback: typing.Union[ValueCallback[bool], typing.Callable[[bool], None]]) -> None: ...
    def setScrollBarStyle(self, int: int) -> None: ...
    def setTextClassifier(self, textClassifier: android.view.textclassifier.TextClassifier) -> None: ...
    def setVerticalScrollbarOverlay(self, boolean: bool) -> None: ...
    def setWebChromeClient(self, webChromeClient: WebChromeClient) -> None: ...
    @staticmethod
    def setWebContentsDebuggingEnabled(boolean: bool) -> None: ...
    def setWebViewClient(self, webViewClient: 'WebViewClient') -> None: ...
    @typing.overload
    def setWebViewRenderProcessClient(self, webViewRenderProcessClient: 'WebViewRenderProcessClient') -> None: ...
    @typing.overload
    def setWebViewRenderProcessClient(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], webViewRenderProcessClient: 'WebViewRenderProcessClient') -> None: ...
    def shouldDelayChildPressedState(self) -> bool: ...
    def showFindDialog(self, string: str, boolean: bool) -> bool: ...
    @staticmethod
    def startSafeBrowsing(context: android.content.Context, valueCallback: typing.Union[ValueCallback[bool], typing.Callable[[bool], None]]) -> None: ...
    def stopLoading(self) -> None: ...
    def zoomBy(self, float: float) -> None: ...
    def zoomIn(self) -> bool: ...
    def zoomOut(self) -> bool: ...
    class FindListener:
        def onFindResultReceived(self, int: int, int2: int, boolean: bool) -> None: ...
    class HitTestResult:
        ANCHOR_TYPE: typing.ClassVar[int] = ...
        EDIT_TEXT_TYPE: typing.ClassVar[int] = ...
        EMAIL_TYPE: typing.ClassVar[int] = ...
        GEO_TYPE: typing.ClassVar[int] = ...
        IMAGE_ANCHOR_TYPE: typing.ClassVar[int] = ...
        IMAGE_TYPE: typing.ClassVar[int] = ...
        PHONE_TYPE: typing.ClassVar[int] = ...
        SRC_ANCHOR_TYPE: typing.ClassVar[int] = ...
        SRC_IMAGE_ANCHOR_TYPE: typing.ClassVar[int] = ...
        UNKNOWN_TYPE: typing.ClassVar[int] = ...
        def getExtra(self) -> str: ...
        def getType(self) -> int: ...
    class PictureListener:
        def onNewPicture(self, webView: 'WebView', picture: android.graphics.Picture) -> None: ...
    class VisualStateCallback:
        def __init__(self): ...
        def onComplete(self, long: int) -> None: ...
    class WebViewTransport:
        def __init__(self, webView: 'WebView'): ...
        def getWebView(self) -> 'WebView': ...
        def setWebView(self, webView: 'WebView') -> None: ...

class WebViewClient:
    ERROR_AUTHENTICATION: typing.ClassVar[int] = ...
    ERROR_BAD_URL: typing.ClassVar[int] = ...
    ERROR_CONNECT: typing.ClassVar[int] = ...
    ERROR_FAILED_SSL_HANDSHAKE: typing.ClassVar[int] = ...
    ERROR_FILE: typing.ClassVar[int] = ...
    ERROR_FILE_NOT_FOUND: typing.ClassVar[int] = ...
    ERROR_HOST_LOOKUP: typing.ClassVar[int] = ...
    ERROR_IO: typing.ClassVar[int] = ...
    ERROR_PROXY_AUTHENTICATION: typing.ClassVar[int] = ...
    ERROR_REDIRECT_LOOP: typing.ClassVar[int] = ...
    ERROR_TIMEOUT: typing.ClassVar[int] = ...
    ERROR_TOO_MANY_REQUESTS: typing.ClassVar[int] = ...
    ERROR_UNKNOWN: typing.ClassVar[int] = ...
    ERROR_UNSAFE_RESOURCE: typing.ClassVar[int] = ...
    ERROR_UNSUPPORTED_AUTH_SCHEME: typing.ClassVar[int] = ...
    ERROR_UNSUPPORTED_SCHEME: typing.ClassVar[int] = ...
    SAFE_BROWSING_THREAT_BILLING: typing.ClassVar[int] = ...
    SAFE_BROWSING_THREAT_MALWARE: typing.ClassVar[int] = ...
    SAFE_BROWSING_THREAT_PHISHING: typing.ClassVar[int] = ...
    SAFE_BROWSING_THREAT_UNKNOWN: typing.ClassVar[int] = ...
    SAFE_BROWSING_THREAT_UNWANTED_SOFTWARE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def doUpdateVisitedHistory(self, webView: WebView, string: str, boolean: bool) -> None: ...
    def onFormResubmission(self, webView: WebView, message: android.os.Message, message2: android.os.Message) -> None: ...
    def onLoadResource(self, webView: WebView, string: str) -> None: ...
    def onPageCommitVisible(self, webView: WebView, string: str) -> None: ...
    def onPageFinished(self, webView: WebView, string: str) -> None: ...
    def onPageStarted(self, webView: WebView, string: str, bitmap: android.graphics.Bitmap) -> None: ...
    def onReceivedClientCertRequest(self, webView: WebView, clientCertRequest: ClientCertRequest) -> None: ...
    @typing.overload
    def onReceivedError(self, webView: WebView, webResourceRequest: WebResourceRequest, webResourceError: WebResourceError) -> None: ...
    @typing.overload
    def onReceivedError(self, webView: WebView, int: int, string: str, string2: str) -> None: ...
    def onReceivedHttpAuthRequest(self, webView: WebView, httpAuthHandler: HttpAuthHandler, string: str, string2: str) -> None: ...
    def onReceivedHttpError(self, webView: WebView, webResourceRequest: WebResourceRequest, webResourceResponse: WebResourceResponse) -> None: ...
    def onReceivedLoginRequest(self, webView: WebView, string: str, string2: str, string3: str) -> None: ...
    def onReceivedSslError(self, webView: WebView, sslErrorHandler: SslErrorHandler, sslError2: android.net.http.SslError) -> None: ...
    def onRenderProcessGone(self, webView: WebView, renderProcessGoneDetail: RenderProcessGoneDetail) -> bool: ...
    def onSafeBrowsingHit(self, webView: WebView, webResourceRequest: WebResourceRequest, int: int, safeBrowsingResponse: SafeBrowsingResponse) -> None: ...
    def onScaleChanged(self, webView: WebView, float: float, float2: float) -> None: ...
    def onTooManyRedirects(self, webView: WebView, message: android.os.Message, message2: android.os.Message) -> None: ...
    def onUnhandledKeyEvent(self, webView: WebView, keyEvent: android.view.KeyEvent) -> None: ...
    @typing.overload
    def shouldInterceptRequest(self, webView: WebView, webResourceRequest: WebResourceRequest) -> WebResourceResponse: ...
    @typing.overload
    def shouldInterceptRequest(self, webView: WebView, string: str) -> WebResourceResponse: ...
    def shouldOverrideKeyEvent(self, webView: WebView, keyEvent: android.view.KeyEvent) -> bool: ...
    @typing.overload
    def shouldOverrideUrlLoading(self, webView: WebView, webResourceRequest: WebResourceRequest) -> bool: ...
    @typing.overload
    def shouldOverrideUrlLoading(self, webView: WebView, string: str) -> bool: ...

class WebViewDatabase:
    def __init__(self): ...
    def clearFormData(self) -> None: ...
    def clearHttpAuthUsernamePassword(self) -> None: ...
    def clearUsernamePassword(self) -> None: ...
    def getHttpAuthUsernamePassword(self, string: str, string2: str) -> typing.MutableSequence[str]: ...
    @staticmethod
    def getInstance(context: android.content.Context) -> 'WebViewDatabase': ...
    def hasFormData(self) -> bool: ...
    def hasHttpAuthUsernamePassword(self) -> bool: ...
    def hasUsernamePassword(self) -> bool: ...
    def setHttpAuthUsernamePassword(self, string: str, string2: str, string3: str, string4: str) -> None: ...

class WebViewFragment(android.app.Fragment):
    def __init__(self): ...
    def getWebView(self) -> WebView: ...
    def onCreateView(self, layoutInflater: android.view.LayoutInflater, viewGroup: android.view.ViewGroup, bundle: android.os.Bundle) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def onPause(self) -> None: ...
    def onResume(self) -> None: ...

class WebViewRenderProcess:
    def __init__(self): ...
    def terminate(self) -> bool: ...

class WebViewRenderProcessClient:
    def __init__(self): ...
    def onRenderProcessResponsive(self, webView: WebView, webViewRenderProcess: WebViewRenderProcess) -> None: ...
    def onRenderProcessUnresponsive(self, webView: WebView, webViewRenderProcess: WebViewRenderProcess) -> None: ...

class JsPromptResult(JsResult):
    @typing.overload
    def confirm(self) -> None: ...
    @typing.overload
    def confirm(self, string: str) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.webkit")``.

    ClientCertRequest: typing.Type[ClientCertRequest]
    ConsoleMessage: typing.Type[ConsoleMessage]
    CookieManager: typing.Type[CookieManager]
    CookieSyncManager: typing.Type[CookieSyncManager]
    DateSorter: typing.Type[DateSorter]
    DownloadListener: typing.Type[DownloadListener]
    GeolocationPermissions: typing.Type[GeolocationPermissions]
    HttpAuthHandler: typing.Type[HttpAuthHandler]
    JavascriptInterface: typing.Type[JavascriptInterface]
    JsPromptResult: typing.Type[JsPromptResult]
    JsResult: typing.Type[JsResult]
    MimeTypeMap: typing.Type[MimeTypeMap]
    PermissionRequest: typing.Type[PermissionRequest]
    PluginStub: typing.Type[PluginStub]
    RenderProcessGoneDetail: typing.Type[RenderProcessGoneDetail]
    SafeBrowsingResponse: typing.Type[SafeBrowsingResponse]
    ServiceWorkerClient: typing.Type[ServiceWorkerClient]
    ServiceWorkerController: typing.Type[ServiceWorkerController]
    ServiceWorkerWebSettings: typing.Type[ServiceWorkerWebSettings]
    SslErrorHandler: typing.Type[SslErrorHandler]
    TracingConfig: typing.Type[TracingConfig]
    TracingController: typing.Type[TracingController]
    URLUtil: typing.Type[URLUtil]
    ValueCallback: typing.Type[ValueCallback]
    WebBackForwardList: typing.Type[WebBackForwardList]
    WebChromeClient: typing.Type[WebChromeClient]
    WebHistoryItem: typing.Type[WebHistoryItem]
    WebIconDatabase: typing.Type[WebIconDatabase]
    WebMessage: typing.Type[WebMessage]
    WebMessagePort: typing.Type[WebMessagePort]
    WebResourceError: typing.Type[WebResourceError]
    WebResourceRequest: typing.Type[WebResourceRequest]
    WebResourceResponse: typing.Type[WebResourceResponse]
    WebSettings: typing.Type[WebSettings]
    WebStorage: typing.Type[WebStorage]
    WebView: typing.Type[WebView]
    WebViewClient: typing.Type[WebViewClient]
    WebViewDatabase: typing.Type[WebViewDatabase]
    WebViewFragment: typing.Type[WebViewFragment]
    WebViewRenderProcess: typing.Type[WebViewRenderProcess]
    WebViewRenderProcessClient: typing.Type[WebViewRenderProcessClient]
