
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.net
import android.os
import java.util
import typing



class JobInfo(android.os.Parcelable):
    BACKOFF_POLICY_EXPONENTIAL: typing.ClassVar[int] = ...
    BACKOFF_POLICY_LINEAR: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DEFAULT_INITIAL_BACKOFF_MILLIS: typing.ClassVar[int] = ...
    MAX_BACKOFF_DELAY_MILLIS: typing.ClassVar[int] = ...
    NETWORK_BYTES_UNKNOWN: typing.ClassVar[int] = ...
    NETWORK_TYPE_ANY: typing.ClassVar[int] = ...
    NETWORK_TYPE_CELLULAR: typing.ClassVar[int] = ...
    NETWORK_TYPE_METERED: typing.ClassVar[int] = ...
    NETWORK_TYPE_NONE: typing.ClassVar[int] = ...
    NETWORK_TYPE_NOT_ROAMING: typing.ClassVar[int] = ...
    NETWORK_TYPE_UNMETERED: typing.ClassVar[int] = ...
    PRIORITY_DEFAULT: typing.ClassVar[int] = ...
    PRIORITY_HIGH: typing.ClassVar[int] = ...
    PRIORITY_LOW: typing.ClassVar[int] = ...
    PRIORITY_MAX: typing.ClassVar[int] = ...
    PRIORITY_MIN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBackoffPolicy(self) -> int: ...
    def getClipData(self) -> android.content.ClipData: ...
    def getClipGrantFlags(self) -> int: ...
    def getDebugTags(self) -> java.util.Set[str]: ...
    def getEstimatedNetworkDownloadBytes(self) -> int: ...
    def getEstimatedNetworkUploadBytes(self) -> int: ...
    def getExtras(self) -> android.os.PersistableBundle: ...
    def getFlexMillis(self) -> int: ...
    def getId(self) -> int: ...
    def getInitialBackoffMillis(self) -> int: ...
    def getIntervalMillis(self) -> int: ...
    def getMaxExecutionDelayMillis(self) -> int: ...
    @staticmethod
    def getMinFlexMillis() -> int: ...
    def getMinLatencyMillis(self) -> int: ...
    @staticmethod
    def getMinPeriodMillis() -> int: ...
    def getMinimumNetworkChunkBytes(self) -> int: ...
    def getNetworkType(self) -> int: ...
    def getPriority(self) -> int: ...
    def getRequiredNetwork(self) -> android.net.NetworkRequest: ...
    def getService(self) -> android.content.ComponentName: ...
    def getTraceTag(self) -> str: ...
    def getTransientExtras(self) -> android.os.Bundle: ...
    def getTriggerContentMaxDelay(self) -> int: ...
    def getTriggerContentUpdateDelay(self) -> int: ...
    def getTriggerContentUris(self) -> typing.MutableSequence['JobInfo.TriggerContentUri']: ...
    def hashCode(self) -> int: ...
    def isExpedited(self) -> bool: ...
    def isImportantWhileForeground(self) -> bool: ...
    def isPeriodic(self) -> bool: ...
    def isPersisted(self) -> bool: ...
    def isPrefetch(self) -> bool: ...
    def isRequireBatteryNotLow(self) -> bool: ...
    def isRequireCharging(self) -> bool: ...
    def isRequireDeviceIdle(self) -> bool: ...
    def isRequireStorageNotLow(self) -> bool: ...
    def isUserInitiated(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, componentName: android.content.ComponentName): ...
        def addDebugTag(self, string: str) -> 'JobInfo.Builder': ...
        def addTriggerContentUri(self, triggerContentUri: 'JobInfo.TriggerContentUri') -> 'JobInfo.Builder': ...
        def build(self) -> 'JobInfo': ...
        def removeDebugTag(self, string: str) -> 'JobInfo.Builder': ...
        def setBackoffCriteria(self, long: int, int: int) -> 'JobInfo.Builder': ...
        def setClipData(self, clipData: android.content.ClipData, int: int) -> 'JobInfo.Builder': ...
        def setEstimatedNetworkBytes(self, long: int, long2: int) -> 'JobInfo.Builder': ...
        def setExpedited(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setExtras(self, persistableBundle: android.os.PersistableBundle) -> 'JobInfo.Builder': ...
        def setImportantWhileForeground(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setMinimumLatency(self, long: int) -> 'JobInfo.Builder': ...
        def setMinimumNetworkChunkBytes(self, long: int) -> 'JobInfo.Builder': ...
        def setOverrideDeadline(self, long: int) -> 'JobInfo.Builder': ...
        @typing.overload
        def setPeriodic(self, long: int) -> 'JobInfo.Builder': ...
        @typing.overload
        def setPeriodic(self, long: int, long2: int) -> 'JobInfo.Builder': ...
        def setPersisted(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setPrefetch(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setPriority(self, int: int) -> 'JobInfo.Builder': ...
        def setRequiredNetwork(self, networkRequest: android.net.NetworkRequest) -> 'JobInfo.Builder': ...
        def setRequiredNetworkType(self, int: int) -> 'JobInfo.Builder': ...
        def setRequiresBatteryNotLow(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setRequiresCharging(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setRequiresDeviceIdle(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setRequiresStorageNotLow(self, boolean: bool) -> 'JobInfo.Builder': ...
        def setTraceTag(self, string: str) -> 'JobInfo.Builder': ...
        def setTransientExtras(self, bundle: android.os.Bundle) -> 'JobInfo.Builder': ...
        def setTriggerContentMaxDelay(self, long: int) -> 'JobInfo.Builder': ...
        def setTriggerContentUpdateDelay(self, long: int) -> 'JobInfo.Builder': ...
        def setUserInitiated(self, boolean: bool) -> 'JobInfo.Builder': ...
    class TriggerContentUri(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        FLAG_NOTIFY_FOR_DESCENDANTS: typing.ClassVar[int] = ...
        def __init__(self, uri: android.net.Uri, int: int): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getFlags(self) -> int: ...
        def getUri(self) -> android.net.Uri: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class JobParameters(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STOP_REASON_APP_STANDBY: typing.ClassVar[int] = ...
    STOP_REASON_BACKGROUND_RESTRICTION: typing.ClassVar[int] = ...
    STOP_REASON_CANCELLED_BY_APP: typing.ClassVar[int] = ...
    STOP_REASON_CONSTRAINT_BATTERY_NOT_LOW: typing.ClassVar[int] = ...
    STOP_REASON_CONSTRAINT_CHARGING: typing.ClassVar[int] = ...
    STOP_REASON_CONSTRAINT_CONNECTIVITY: typing.ClassVar[int] = ...
    STOP_REASON_CONSTRAINT_DEVICE_IDLE: typing.ClassVar[int] = ...
    STOP_REASON_CONSTRAINT_STORAGE_NOT_LOW: typing.ClassVar[int] = ...
    STOP_REASON_DEVICE_STATE: typing.ClassVar[int] = ...
    STOP_REASON_ESTIMATED_APP_LAUNCH_TIME_CHANGED: typing.ClassVar[int] = ...
    STOP_REASON_PREEMPT: typing.ClassVar[int] = ...
    STOP_REASON_QUOTA: typing.ClassVar[int] = ...
    STOP_REASON_SYSTEM_PROCESSING: typing.ClassVar[int] = ...
    STOP_REASON_TIMEOUT: typing.ClassVar[int] = ...
    STOP_REASON_UNDEFINED: typing.ClassVar[int] = ...
    STOP_REASON_USER: typing.ClassVar[int] = ...
    def completeWork(self, jobWorkItem: 'JobWorkItem') -> None: ...
    def dequeueWork(self) -> 'JobWorkItem': ...
    def describeContents(self) -> int: ...
    def getClipData(self) -> android.content.ClipData: ...
    def getClipGrantFlags(self) -> int: ...
    def getExtras(self) -> android.os.PersistableBundle: ...
    def getJobId(self) -> int: ...
    def getJobNamespace(self) -> str: ...
    def getNetwork(self) -> android.net.Network: ...
    def getStopReason(self) -> int: ...
    def getTransientExtras(self) -> android.os.Bundle: ...
    def getTriggeredContentAuthorities(self) -> typing.MutableSequence[str]: ...
    def getTriggeredContentUris(self) -> typing.MutableSequence[android.net.Uri]: ...
    def isExpeditedJob(self) -> bool: ...
    def isOverrideDeadlineExpired(self) -> bool: ...
    def isUserInitiatedJob(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class JobScheduler:
    PENDING_JOB_REASON_APP: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_APP_STANDBY: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_BACKGROUND_RESTRICTION: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_BATTERY_NOT_LOW: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_CHARGING: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_CONNECTIVITY: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_CONTENT_TRIGGER: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_DEVICE_IDLE: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_MINIMUM_LATENCY: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_PREFETCH: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_CONSTRAINT_STORAGE_NOT_LOW: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_DEVICE_STATE: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_EXECUTING: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_INVALID_JOB_ID: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_JOB_SCHEDULER_OPTIMIZATION: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_QUOTA: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_UNDEFINED: typing.ClassVar[int] = ...
    PENDING_JOB_REASON_USER: typing.ClassVar[int] = ...
    RESULT_FAILURE: typing.ClassVar[int] = ...
    RESULT_SUCCESS: typing.ClassVar[int] = ...
    def __init__(self): ...
    def canRunUserInitiatedJobs(self) -> bool: ...
    def cancel(self, int: int) -> None: ...
    def cancelAll(self) -> None: ...
    def cancelInAllNamespaces(self) -> None: ...
    def enqueue(self, jobInfo: JobInfo, jobWorkItem: 'JobWorkItem') -> int: ...
    def forNamespace(self, string: str) -> 'JobScheduler': ...
    def getAllPendingJobs(self) -> java.util.List[JobInfo]: ...
    def getNamespace(self) -> str: ...
    def getPendingJob(self, int: int) -> JobInfo: ...
    def getPendingJobReason(self, int: int) -> int: ...
    def getPendingJobsInAllNamespaces(self) -> java.util.Map[str, java.util.List[JobInfo]]: ...
    def schedule(self, jobInfo: JobInfo) -> int: ...

class JobService(android.app.Service):
    JOB_END_NOTIFICATION_POLICY_DETACH: typing.ClassVar[int] = ...
    JOB_END_NOTIFICATION_POLICY_REMOVE: typing.ClassVar[int] = ...
    PERMISSION_BIND: typing.ClassVar[str] = ...
    def __init__(self): ...
    def jobFinished(self, jobParameters: JobParameters, boolean: bool) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onNetworkChanged(self, jobParameters: JobParameters) -> None: ...
    def onStartJob(self, jobParameters: JobParameters) -> bool: ...
    def onStopJob(self, jobParameters: JobParameters) -> bool: ...
    def setNotification(self, jobParameters: JobParameters, int: int, notification: android.app.Notification, int2: int) -> None: ...
    @typing.overload
    def updateEstimatedNetworkBytes(self, jobParameters: JobParameters, jobWorkItem: 'JobWorkItem', long: int, long2: int) -> None: ...
    @typing.overload
    def updateEstimatedNetworkBytes(self, jobParameters: JobParameters, long: int, long2: int) -> None: ...
    @typing.overload
    def updateTransferredNetworkBytes(self, jobParameters: JobParameters, jobWorkItem: 'JobWorkItem', long: int, long2: int) -> None: ...
    @typing.overload
    def updateTransferredNetworkBytes(self, jobParameters: JobParameters, long: int, long2: int) -> None: ...

class JobServiceEngine:
    def __init__(self, service: android.app.Service): ...
    def getBinder(self) -> android.os.IBinder: ...
    def jobFinished(self, jobParameters: JobParameters, boolean: bool) -> None: ...
    def onNetworkChanged(self, jobParameters: JobParameters) -> None: ...
    def onStartJob(self, jobParameters: JobParameters) -> bool: ...
    def onStopJob(self, jobParameters: JobParameters) -> bool: ...
    def setNotification(self, jobParameters: JobParameters, int: int, notification: android.app.Notification, int2: int) -> None: ...
    def updateEstimatedNetworkBytes(self, jobParameters: JobParameters, jobWorkItem: 'JobWorkItem', long: int, long2: int) -> None: ...
    def updateTransferredNetworkBytes(self, jobParameters: JobParameters, jobWorkItem: 'JobWorkItem', long: int, long2: int) -> None: ...

class JobWorkItem(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, intent: android.content.Intent): ...
    @typing.overload
    def __init__(self, intent: android.content.Intent, long: int, long2: int): ...
    @typing.overload
    def __init__(self, intent: android.content.Intent, long: int, long2: int, long3: int): ...
    def describeContents(self) -> int: ...
    def getDeliveryCount(self) -> int: ...
    def getEstimatedNetworkDownloadBytes(self) -> int: ...
    def getEstimatedNetworkUploadBytes(self) -> int: ...
    def getExtras(self) -> android.os.PersistableBundle: ...
    def getIntent(self) -> android.content.Intent: ...
    def getMinimumNetworkChunkBytes(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'JobWorkItem': ...
        def setEstimatedNetworkBytes(self, long: int, long2: int) -> 'JobWorkItem.Builder': ...
        def setExtras(self, persistableBundle: android.os.PersistableBundle) -> 'JobWorkItem.Builder': ...
        def setIntent(self, intent: android.content.Intent) -> 'JobWorkItem.Builder': ...
        def setMinimumNetworkChunkBytes(self, long: int) -> 'JobWorkItem.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.job")``.

    JobInfo: typing.Type[JobInfo]
    JobParameters: typing.Type[JobParameters]
    JobScheduler: typing.Type[JobScheduler]
    JobService: typing.Type[JobService]
    JobServiceEngine: typing.Type[JobServiceEngine]
    JobWorkItem: typing.Type[JobWorkItem]
