
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import android.telephony
import typing



class CdmaCellLocation(android.telephony.CellLocation):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, bundle: android.os.Bundle): ...
    @staticmethod
    def convertQuartSecToDecDegrees(int: int) -> float: ...
    def equals(self, object: typing.Any) -> bool: ...
    def fillInNotifierBundle(self, bundle: android.os.Bundle) -> None: ...
    def getBaseStationId(self) -> int: ...
    def getBaseStationLatitude(self) -> int: ...
    def getBaseStationLongitude(self) -> int: ...
    def getNetworkId(self) -> int: ...
    def getSystemId(self) -> int: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def setCellLocationData(self, int: int, int2: int, int3: int) -> None: ...
    @typing.overload
    def setCellLocationData(self, int: int, int2: int, int3: int, int4: int, int5: int) -> None: ...
    def setStateInvalid(self) -> None: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.telephony.cdma")``.

    CdmaCellLocation: typing.Type[CdmaCellLocation]
