
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.security
import java.security.cert
import java.util
import jpype
import typing



class Credential(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, credential: 'Credential'): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCaCertificate(self) -> java.security.cert.X509Certificate: ...
    def getCertCredential(self) -> 'Credential.CertificateCredential': ...
    def getClientCertificateChain(self) -> typing.MutableSequence[java.security.cert.X509Certificate]: ...
    def getClientPrivateKey(self) -> java.security.PrivateKey: ...
    def getMinimumTlsVersion(self) -> int: ...
    def getRealm(self) -> str: ...
    def getSimCredential(self) -> 'Credential.SimCredential': ...
    def getUserCredential(self) -> 'Credential.UserCredential': ...
    def hashCode(self) -> int: ...
    def setCaCertificate(self, x509Certificate: java.security.cert.X509Certificate) -> None: ...
    def setCertCredential(self, certificateCredential: 'Credential.CertificateCredential') -> None: ...
    def setClientCertificateChain(self, x509CertificateArray: typing.Union[typing.List[java.security.cert.X509Certificate], jpype.JArray]) -> None: ...
    def setClientPrivateKey(self, privateKey: java.security.PrivateKey) -> None: ...
    def setMinimumTlsVersion(self, int: int) -> None: ...
    def setRealm(self, string: str) -> None: ...
    def setSimCredential(self, simCredential: 'Credential.SimCredential') -> None: ...
    def setUserCredential(self, userCredential: 'Credential.UserCredential') -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class CertificateCredential(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, certificateCredential: 'Credential.CertificateCredential'): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getCertSha256Fingerprint(self) -> typing.MutableSequence[int]: ...
        def getCertType(self) -> str: ...
        def hashCode(self) -> int: ...
        def setCertSha256Fingerprint(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
        def setCertType(self, string: str) -> None: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class SimCredential(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, simCredential: 'Credential.SimCredential'): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getEapType(self) -> int: ...
        def getImsi(self) -> str: ...
        def hashCode(self) -> int: ...
        def setEapType(self, int: int) -> None: ...
        def setImsi(self, string: str) -> None: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class UserCredential(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, userCredential: 'Credential.UserCredential'): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getEapType(self) -> int: ...
        def getNonEapInnerMethod(self) -> str: ...
        def getPassword(self) -> str: ...
        def getUsername(self) -> str: ...
        def hashCode(self) -> int: ...
        def setEapType(self, int: int) -> None: ...
        def setNonEapInnerMethod(self, string: str) -> None: ...
        def setPassword(self, string: str) -> None: ...
        def setUsername(self, string: str) -> None: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class HomeSp(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, homeSp: 'HomeSp'): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFqdn(self) -> str: ...
    def getFriendlyName(self) -> str: ...
    def getMatchAllOis(self) -> typing.MutableSequence[int]: ...
    def getMatchAnyOis(self) -> typing.MutableSequence[int]: ...
    def getOtherHomePartnersList(self) -> java.util.Collection[str]: ...
    def getRoamingConsortiumOis(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    def setFqdn(self, string: str) -> None: ...
    def setFriendlyName(self, string: str) -> None: ...
    def setMatchAllOis(self, longArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def setMatchAnyOis(self, longArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def setOtherHomePartnersList(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> None: ...
    def setRoamingConsortiumOis(self, longArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.wifi.hotspot2.pps")``.

    Credential: typing.Type[Credential]
    HomeSp: typing.Type[HomeSp]
