
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.pm
import android.database
import android.graphics.drawable
import android.net
import android.os
import java.lang
import java.util
import jpype
import typing



class Slice(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EXTRA_RANGE_VALUE: typing.ClassVar[str] = ...
    EXTRA_TOGGLE_STATE: typing.ClassVar[str] = ...
    HINT_ACTIONS: typing.ClassVar[str] = ...
    HINT_ERROR: typing.ClassVar[str] = ...
    HINT_HORIZONTAL: typing.ClassVar[str] = ...
    HINT_KEYWORDS: typing.ClassVar[str] = ...
    HINT_LARGE: typing.ClassVar[str] = ...
    HINT_LAST_UPDATED: typing.ClassVar[str] = ...
    HINT_LIST: typing.ClassVar[str] = ...
    HINT_LIST_ITEM: typing.ClassVar[str] = ...
    HINT_NO_TINT: typing.ClassVar[str] = ...
    HINT_PARTIAL: typing.ClassVar[str] = ...
    HINT_PERMISSION_REQUEST: typing.ClassVar[str] = ...
    HINT_SEE_MORE: typing.ClassVar[str] = ...
    HINT_SELECTED: typing.ClassVar[str] = ...
    HINT_SHORTCUT: typing.ClassVar[str] = ...
    HINT_SUMMARY: typing.ClassVar[str] = ...
    HINT_TITLE: typing.ClassVar[str] = ...
    HINT_TTL: typing.ClassVar[str] = ...
    SUBTYPE_COLOR: typing.ClassVar[str] = ...
    SUBTYPE_CONTENT_DESCRIPTION: typing.ClassVar[str] = ...
    SUBTYPE_LAYOUT_DIRECTION: typing.ClassVar[str] = ...
    SUBTYPE_MAX: typing.ClassVar[str] = ...
    SUBTYPE_MESSAGE: typing.ClassVar[str] = ...
    SUBTYPE_MILLIS: typing.ClassVar[str] = ...
    SUBTYPE_PRIORITY: typing.ClassVar[str] = ...
    SUBTYPE_RANGE: typing.ClassVar[str] = ...
    SUBTYPE_SOURCE: typing.ClassVar[str] = ...
    SUBTYPE_TOGGLE: typing.ClassVar[str] = ...
    SUBTYPE_VALUE: typing.ClassVar[str] = ...
    def describeContents(self) -> int: ...
    def getHints(self) -> java.util.List[str]: ...
    def getItems(self) -> java.util.List['SliceItem']: ...
    def getSpec(self) -> 'SliceSpec': ...
    def getUri(self) -> android.net.Uri: ...
    def isCallerNeeded(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, builder: 'Slice.Builder'): ...
        @typing.overload
        def __init__(self, uri: android.net.Uri, sliceSpec: 'SliceSpec'): ...
        def addAction(self, pendingIntent: android.app.PendingIntent, slice: 'Slice', string: str) -> 'Slice.Builder': ...
        def addBundle(self, bundle: android.os.Bundle, string: str, list: java.util.List[str]) -> 'Slice.Builder': ...
        def addHints(self, list: java.util.List[str]) -> 'Slice.Builder': ...
        def addIcon(self, icon: android.graphics.drawable.Icon, string: str, list: java.util.List[str]) -> 'Slice.Builder': ...
        def addInt(self, int: int, string: str, list: java.util.List[str]) -> 'Slice.Builder': ...
        def addLong(self, long: int, string: str, list: java.util.List[str]) -> 'Slice.Builder': ...
        def addRemoteInput(self, remoteInput: android.app.RemoteInput, string: str, list: java.util.List[str]) -> 'Slice.Builder': ...
        def addSubSlice(self, slice: 'Slice', string: str) -> 'Slice.Builder': ...
        def addText(self, charSequence: typing.Union[java.lang.CharSequence, str], string: str, list: java.util.List[str]) -> 'Slice.Builder': ...
        def build(self) -> 'Slice': ...
        def setCallerNeeded(self, boolean: bool) -> 'Slice.Builder': ...

class SliceItem(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FORMAT_ACTION: typing.ClassVar[str] = ...
    FORMAT_BUNDLE: typing.ClassVar[str] = ...
    FORMAT_IMAGE: typing.ClassVar[str] = ...
    FORMAT_INT: typing.ClassVar[str] = ...
    FORMAT_LONG: typing.ClassVar[str] = ...
    FORMAT_REMOTE_INPUT: typing.ClassVar[str] = ...
    FORMAT_SLICE: typing.ClassVar[str] = ...
    FORMAT_TEXT: typing.ClassVar[str] = ...
    def describeContents(self) -> int: ...
    def getAction(self) -> android.app.PendingIntent: ...
    def getBundle(self) -> android.os.Bundle: ...
    def getFormat(self) -> str: ...
    def getHints(self) -> java.util.List[str]: ...
    def getIcon(self) -> android.graphics.drawable.Icon: ...
    def getInt(self) -> int: ...
    def getLong(self) -> int: ...
    def getRemoteInput(self) -> android.app.RemoteInput: ...
    def getSlice(self) -> Slice: ...
    def getSubType(self) -> str: ...
    def getText(self) -> java.lang.CharSequence: ...
    def hasHint(self, string: str) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SliceManager:
    CATEGORY_SLICE: typing.ClassVar[str] = ...
    SLICE_METADATA_KEY: typing.ClassVar[str] = ...
    @typing.overload
    def bindSlice(self, intent: android.content.Intent, set: java.util.Set['SliceSpec']) -> Slice: ...
    @typing.overload
    def bindSlice(self, uri: android.net.Uri, set: java.util.Set['SliceSpec']) -> Slice: ...
    def checkSlicePermission(self, uri: android.net.Uri, int: int, int2: int) -> int: ...
    def getPinnedSlices(self) -> java.util.List[android.net.Uri]: ...
    def getPinnedSpecs(self, uri: android.net.Uri) -> java.util.Set['SliceSpec']: ...
    def getSliceDescendants(self, uri: android.net.Uri) -> java.util.Collection[android.net.Uri]: ...
    def grantSlicePermission(self, string: str, uri: android.net.Uri) -> None: ...
    def mapIntentToUri(self, intent: android.content.Intent) -> android.net.Uri: ...
    def pinSlice(self, uri: android.net.Uri, set: java.util.Set['SliceSpec']) -> None: ...
    def revokeSlicePermission(self, string: str, uri: android.net.Uri) -> None: ...
    def unpinSlice(self, uri: android.net.Uri) -> None: ...

class SliceMetrics:
    def __init__(self, context: android.content.Context, uri: android.net.Uri): ...
    def logHidden(self) -> None: ...
    def logTouch(self, int: int, uri: android.net.Uri) -> None: ...
    def logVisible(self) -> None: ...

class SliceProvider(android.content.ContentProvider):
    SLICE_TYPE: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, *string: str): ...
    def attachInfo(self, context: android.content.Context, providerInfo: android.content.pm.ProviderInfo) -> None: ...
    @typing.overload
    def call(self, string: str, string2: str, bundle: android.os.Bundle) -> android.os.Bundle: ...
    @typing.overload
    def call(self, string: str, string2: str, string3: str, bundle: android.os.Bundle) -> android.os.Bundle: ...
    @typing.overload
    def delete(self, uri: android.net.Uri, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    @typing.overload
    def delete(self, uri: android.net.Uri, bundle: android.os.Bundle) -> int: ...
    def getType(self, uri: android.net.Uri) -> str: ...
    @typing.overload
    def insert(self, uri: android.net.Uri, contentValues: android.content.ContentValues, bundle: android.os.Bundle) -> android.net.Uri: ...
    @typing.overload
    def insert(self, uri: android.net.Uri, contentValues: android.content.ContentValues) -> android.net.Uri: ...
    def onBindSlice(self, uri: android.net.Uri, set: java.util.Set['SliceSpec']) -> Slice: ...
    def onCreatePermissionRequest(self, uri: android.net.Uri) -> android.app.PendingIntent: ...
    def onGetSliceDescendants(self, uri: android.net.Uri) -> java.util.Collection[android.net.Uri]: ...
    def onMapIntentToUri(self, intent: android.content.Intent) -> android.net.Uri: ...
    def onSlicePinned(self, uri: android.net.Uri) -> None: ...
    def onSliceUnpinned(self, uri: android.net.Uri) -> None: ...
    @typing.overload
    def query(self, uri: android.net.Uri, stringArray: typing.Union[typing.List[str], jpype.JArray], bundle: android.os.Bundle, cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    @typing.overload
    def query(self, uri: android.net.Uri, stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string4: str) -> android.database.Cursor: ...
    @typing.overload
    def query(self, uri: android.net.Uri, stringArray: typing.Union[typing.List[str], jpype.JArray], string2: str, stringArray2: typing.Union[typing.List[str], jpype.JArray], string4: str, cancellationSignal: android.os.CancellationSignal) -> android.database.Cursor: ...
    @typing.overload
    def update(self, uri: android.net.Uri, contentValues: android.content.ContentValues, string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> int: ...
    @typing.overload
    def update(self, uri: android.net.Uri, contentValues: android.content.ContentValues, bundle: android.os.Bundle) -> int: ...

class SliceSpec(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, int: int): ...
    def canRender(self, sliceSpec: 'SliceSpec') -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getRevision(self) -> int: ...
    def getType(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.slice")``.

    Slice: typing.Type[Slice]
    SliceItem: typing.Type[SliceItem]
    SliceManager: typing.Type[SliceManager]
    SliceMetrics: typing.Type[SliceMetrics]
    SliceProvider: typing.Type[SliceProvider]
    SliceSpec: typing.Type[SliceSpec]
