
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.math
import java.security
import java.security.spec
import java.util
import javax.security.auth.x500
import jpype
import typing



class BackendBusyException(java.security.ProviderException):
    @typing.overload
    def __init__(self, long: int): ...
    @typing.overload
    def __init__(self, long: int, string: str): ...
    @typing.overload
    def __init__(self, long: int, string: str, throwable: java.lang.Throwable): ...
    def getBackOffHintMillis(self) -> int: ...

class KeyExpiredException(java.security.InvalidKeyException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class KeyGenParameterSpec(java.security.spec.AlgorithmParameterSpec):
    def getAlgorithmParameterSpec(self) -> java.security.spec.AlgorithmParameterSpec: ...
    def getAttestKeyAlias(self) -> str: ...
    def getAttestationChallenge(self) -> typing.MutableSequence[int]: ...
    def getBlockModes(self) -> typing.MutableSequence[str]: ...
    def getCertificateNotAfter(self) -> java.util.Date: ...
    def getCertificateNotBefore(self) -> java.util.Date: ...
    def getCertificateSerialNumber(self) -> java.math.BigInteger: ...
    def getCertificateSubject(self) -> javax.security.auth.x500.X500Principal: ...
    def getDigests(self) -> typing.MutableSequence[str]: ...
    def getEncryptionPaddings(self) -> typing.MutableSequence[str]: ...
    def getKeySize(self) -> int: ...
    def getKeyValidityForConsumptionEnd(self) -> java.util.Date: ...
    def getKeyValidityForOriginationEnd(self) -> java.util.Date: ...
    def getKeyValidityStart(self) -> java.util.Date: ...
    def getKeystoreAlias(self) -> str: ...
    def getMaxUsageCount(self) -> int: ...
    def getMgf1Digests(self) -> java.util.Set[str]: ...
    def getPurposes(self) -> int: ...
    def getSignaturePaddings(self) -> typing.MutableSequence[str]: ...
    def getUserAuthenticationType(self) -> int: ...
    def getUserAuthenticationValidityDurationSeconds(self) -> int: ...
    def isDevicePropertiesAttestationIncluded(self) -> bool: ...
    def isDigestsSpecified(self) -> bool: ...
    def isInvalidatedByBiometricEnrollment(self) -> bool: ...
    def isMgf1DigestsSpecified(self) -> bool: ...
    def isRandomizedEncryptionRequired(self) -> bool: ...
    def isStrongBoxBacked(self) -> bool: ...
    def isUnlockedDeviceRequired(self) -> bool: ...
    def isUserAuthenticationRequired(self) -> bool: ...
    def isUserAuthenticationValidWhileOnBody(self) -> bool: ...
    def isUserConfirmationRequired(self) -> bool: ...
    def isUserPresenceRequired(self) -> bool: ...
    class Builder:
        def __init__(self, string: str, int: int): ...
        def build(self) -> 'KeyGenParameterSpec': ...
        def setAlgorithmParameterSpec(self, algorithmParameterSpec: java.security.spec.AlgorithmParameterSpec) -> 'KeyGenParameterSpec.Builder': ...
        def setAttestKeyAlias(self, string: str) -> 'KeyGenParameterSpec.Builder': ...
        def setAttestationChallenge(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'KeyGenParameterSpec.Builder': ...
        def setBlockModes(self, *string: str) -> 'KeyGenParameterSpec.Builder': ...
        def setCertificateNotAfter(self, date: java.util.Date) -> 'KeyGenParameterSpec.Builder': ...
        def setCertificateNotBefore(self, date: java.util.Date) -> 'KeyGenParameterSpec.Builder': ...
        def setCertificateSerialNumber(self, bigInteger: java.math.BigInteger) -> 'KeyGenParameterSpec.Builder': ...
        def setCertificateSubject(self, x500Principal: javax.security.auth.x500.X500Principal) -> 'KeyGenParameterSpec.Builder': ...
        def setDevicePropertiesAttestationIncluded(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setDigests(self, *string: str) -> 'KeyGenParameterSpec.Builder': ...
        def setEncryptionPaddings(self, *string: str) -> 'KeyGenParameterSpec.Builder': ...
        def setInvalidatedByBiometricEnrollment(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setIsStrongBoxBacked(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setKeySize(self, int: int) -> 'KeyGenParameterSpec.Builder': ...
        def setKeyValidityEnd(self, date: java.util.Date) -> 'KeyGenParameterSpec.Builder': ...
        def setKeyValidityForConsumptionEnd(self, date: java.util.Date) -> 'KeyGenParameterSpec.Builder': ...
        def setKeyValidityForOriginationEnd(self, date: java.util.Date) -> 'KeyGenParameterSpec.Builder': ...
        def setKeyValidityStart(self, date: java.util.Date) -> 'KeyGenParameterSpec.Builder': ...
        def setMaxUsageCount(self, int: int) -> 'KeyGenParameterSpec.Builder': ...
        def setMgf1Digests(self, *string: str) -> 'KeyGenParameterSpec.Builder': ...
        def setRandomizedEncryptionRequired(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setSignaturePaddings(self, *string: str) -> 'KeyGenParameterSpec.Builder': ...
        def setUnlockedDeviceRequired(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setUserAuthenticationParameters(self, int: int, int2: int) -> 'KeyGenParameterSpec.Builder': ...
        def setUserAuthenticationRequired(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setUserAuthenticationValidWhileOnBody(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setUserAuthenticationValidityDurationSeconds(self, int: int) -> 'KeyGenParameterSpec.Builder': ...
        def setUserConfirmationRequired(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...
        def setUserPresenceRequired(self, boolean: bool) -> 'KeyGenParameterSpec.Builder': ...

class KeyInfo(java.security.spec.KeySpec):
    def getBlockModes(self) -> typing.MutableSequence[str]: ...
    def getDigests(self) -> typing.MutableSequence[str]: ...
    def getEncryptionPaddings(self) -> typing.MutableSequence[str]: ...
    def getKeySize(self) -> int: ...
    def getKeyValidityForConsumptionEnd(self) -> java.util.Date: ...
    def getKeyValidityForOriginationEnd(self) -> java.util.Date: ...
    def getKeyValidityStart(self) -> java.util.Date: ...
    def getKeystoreAlias(self) -> str: ...
    def getOrigin(self) -> int: ...
    def getPurposes(self) -> int: ...
    def getRemainingUsageCount(self) -> int: ...
    def getSecurityLevel(self) -> int: ...
    def getSignaturePaddings(self) -> typing.MutableSequence[str]: ...
    def getUserAuthenticationType(self) -> int: ...
    def getUserAuthenticationValidityDurationSeconds(self) -> int: ...
    def isInsideSecureHardware(self) -> bool: ...
    def isInvalidatedByBiometricEnrollment(self) -> bool: ...
    def isTrustedUserPresenceRequired(self) -> bool: ...
    def isUserAuthenticationRequired(self) -> bool: ...
    def isUserAuthenticationRequirementEnforcedBySecureHardware(self) -> bool: ...
    def isUserAuthenticationValidWhileOnBody(self) -> bool: ...
    def isUserConfirmationRequired(self) -> bool: ...

class KeyNotYetValidException(java.security.InvalidKeyException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class KeyPermanentlyInvalidatedException(java.security.InvalidKeyException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class KeyProperties:
    AUTH_BIOMETRIC_STRONG: typing.ClassVar[int] = ...
    AUTH_DEVICE_CREDENTIAL: typing.ClassVar[int] = ...
    BLOCK_MODE_CBC: typing.ClassVar[str] = ...
    BLOCK_MODE_CTR: typing.ClassVar[str] = ...
    BLOCK_MODE_ECB: typing.ClassVar[str] = ...
    BLOCK_MODE_GCM: typing.ClassVar[str] = ...
    DIGEST_MD5: typing.ClassVar[str] = ...
    DIGEST_NONE: typing.ClassVar[str] = ...
    DIGEST_SHA1: typing.ClassVar[str] = ...
    DIGEST_SHA224: typing.ClassVar[str] = ...
    DIGEST_SHA256: typing.ClassVar[str] = ...
    DIGEST_SHA384: typing.ClassVar[str] = ...
    DIGEST_SHA512: typing.ClassVar[str] = ...
    ENCRYPTION_PADDING_NONE: typing.ClassVar[str] = ...
    ENCRYPTION_PADDING_PKCS7: typing.ClassVar[str] = ...
    ENCRYPTION_PADDING_RSA_OAEP: typing.ClassVar[str] = ...
    ENCRYPTION_PADDING_RSA_PKCS1: typing.ClassVar[str] = ...
    KEY_ALGORITHM_3DES: typing.ClassVar[str] = ...
    KEY_ALGORITHM_AES: typing.ClassVar[str] = ...
    KEY_ALGORITHM_EC: typing.ClassVar[str] = ...
    KEY_ALGORITHM_HMAC_SHA1: typing.ClassVar[str] = ...
    KEY_ALGORITHM_HMAC_SHA224: typing.ClassVar[str] = ...
    KEY_ALGORITHM_HMAC_SHA256: typing.ClassVar[str] = ...
    KEY_ALGORITHM_HMAC_SHA384: typing.ClassVar[str] = ...
    KEY_ALGORITHM_HMAC_SHA512: typing.ClassVar[str] = ...
    KEY_ALGORITHM_RSA: typing.ClassVar[str] = ...
    ORIGIN_GENERATED: typing.ClassVar[int] = ...
    ORIGIN_IMPORTED: typing.ClassVar[int] = ...
    ORIGIN_SECURELY_IMPORTED: typing.ClassVar[int] = ...
    ORIGIN_UNKNOWN: typing.ClassVar[int] = ...
    PURPOSE_AGREE_KEY: typing.ClassVar[int] = ...
    PURPOSE_ATTEST_KEY: typing.ClassVar[int] = ...
    PURPOSE_DECRYPT: typing.ClassVar[int] = ...
    PURPOSE_ENCRYPT: typing.ClassVar[int] = ...
    PURPOSE_SIGN: typing.ClassVar[int] = ...
    PURPOSE_VERIFY: typing.ClassVar[int] = ...
    PURPOSE_WRAP_KEY: typing.ClassVar[int] = ...
    SECURITY_LEVEL_SOFTWARE: typing.ClassVar[int] = ...
    SECURITY_LEVEL_STRONGBOX: typing.ClassVar[int] = ...
    SECURITY_LEVEL_TRUSTED_ENVIRONMENT: typing.ClassVar[int] = ...
    SECURITY_LEVEL_UNKNOWN: typing.ClassVar[int] = ...
    SECURITY_LEVEL_UNKNOWN_SECURE: typing.ClassVar[int] = ...
    SIGNATURE_PADDING_RSA_PKCS1: typing.ClassVar[str] = ...
    SIGNATURE_PADDING_RSA_PSS: typing.ClassVar[str] = ...
    UNRESTRICTED_USAGE_COUNT: typing.ClassVar[int] = ...

class KeyProtection(java.security.KeyStore.ProtectionParameter):
    def getBlockModes(self) -> typing.MutableSequence[str]: ...
    def getDigests(self) -> typing.MutableSequence[str]: ...
    def getEncryptionPaddings(self) -> typing.MutableSequence[str]: ...
    def getKeyValidityForConsumptionEnd(self) -> java.util.Date: ...
    def getKeyValidityForOriginationEnd(self) -> java.util.Date: ...
    def getKeyValidityStart(self) -> java.util.Date: ...
    def getMaxUsageCount(self) -> int: ...
    def getMgf1Digests(self) -> java.util.Set[str]: ...
    def getPurposes(self) -> int: ...
    def getSignaturePaddings(self) -> typing.MutableSequence[str]: ...
    def getUserAuthenticationType(self) -> int: ...
    def getUserAuthenticationValidityDurationSeconds(self) -> int: ...
    def isDigestsSpecified(self) -> bool: ...
    def isInvalidatedByBiometricEnrollment(self) -> bool: ...
    def isMgf1DigestsSpecified(self) -> bool: ...
    def isRandomizedEncryptionRequired(self) -> bool: ...
    def isUnlockedDeviceRequired(self) -> bool: ...
    def isUserAuthenticationRequired(self) -> bool: ...
    def isUserAuthenticationValidWhileOnBody(self) -> bool: ...
    def isUserConfirmationRequired(self) -> bool: ...
    def isUserPresenceRequired(self) -> bool: ...
    class Builder:
        def __init__(self, int: int): ...
        def build(self) -> 'KeyProtection': ...
        def setBlockModes(self, *string: str) -> 'KeyProtection.Builder': ...
        def setDigests(self, *string: str) -> 'KeyProtection.Builder': ...
        def setEncryptionPaddings(self, *string: str) -> 'KeyProtection.Builder': ...
        def setInvalidatedByBiometricEnrollment(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setIsStrongBoxBacked(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setKeyValidityEnd(self, date: java.util.Date) -> 'KeyProtection.Builder': ...
        def setKeyValidityForConsumptionEnd(self, date: java.util.Date) -> 'KeyProtection.Builder': ...
        def setKeyValidityForOriginationEnd(self, date: java.util.Date) -> 'KeyProtection.Builder': ...
        def setKeyValidityStart(self, date: java.util.Date) -> 'KeyProtection.Builder': ...
        def setMaxUsageCount(self, int: int) -> 'KeyProtection.Builder': ...
        def setMgf1Digests(self, *string: str) -> 'KeyProtection.Builder': ...
        def setRandomizedEncryptionRequired(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setSignaturePaddings(self, *string: str) -> 'KeyProtection.Builder': ...
        def setUnlockedDeviceRequired(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setUserAuthenticationParameters(self, int: int, int2: int) -> 'KeyProtection.Builder': ...
        def setUserAuthenticationRequired(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setUserAuthenticationValidWhileOnBody(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setUserAuthenticationValidityDurationSeconds(self, int: int) -> 'KeyProtection.Builder': ...
        def setUserConfirmationRequired(self, boolean: bool) -> 'KeyProtection.Builder': ...
        def setUserPresenceRequired(self, boolean: bool) -> 'KeyProtection.Builder': ...

class SecureKeyImportUnavailableException(java.security.ProviderException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class StrongBoxUnavailableException(java.security.ProviderException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class UserNotAuthenticatedException(java.security.InvalidKeyException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class UserPresenceUnavailableException(java.security.InvalidKeyException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class WrappedKeyEntry(java.security.KeyStore.Entry):
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], string: str, string2: str, algorithmParameterSpec: java.security.spec.AlgorithmParameterSpec): ...
    def getAlgorithmParameterSpec(self) -> java.security.spec.AlgorithmParameterSpec: ...
    def getTransformation(self) -> str: ...
    def getWrappedKeyBytes(self) -> typing.MutableSequence[int]: ...
    def getWrappingKeyAlias(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.security.keystore")``.

    BackendBusyException: typing.Type[BackendBusyException]
    KeyExpiredException: typing.Type[KeyExpiredException]
    KeyGenParameterSpec: typing.Type[KeyGenParameterSpec]
    KeyInfo: typing.Type[KeyInfo]
    KeyNotYetValidException: typing.Type[KeyNotYetValidException]
    KeyPermanentlyInvalidatedException: typing.Type[KeyPermanentlyInvalidatedException]
    KeyProperties: typing.Type[KeyProperties]
    KeyProtection: typing.Type[KeyProtection]
    SecureKeyImportUnavailableException: typing.Type[SecureKeyImportUnavailableException]
    StrongBoxUnavailableException: typing.Type[StrongBoxUnavailableException]
    UserNotAuthenticatedException: typing.Type[UserNotAuthenticatedException]
    UserPresenceUnavailableException: typing.Type[UserPresenceUnavailableException]
    WrappedKeyEntry: typing.Type[WrappedKeyEntry]
