
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.location.altitude
import android.location.provider
import android.os
import android.util
import java.lang
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class Address(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, locale: java.util.Locale): ...
    def clearLatitude(self) -> None: ...
    def clearLongitude(self) -> None: ...
    def describeContents(self) -> int: ...
    def getAddressLine(self, int: int) -> str: ...
    def getAdminArea(self) -> str: ...
    def getCountryCode(self) -> str: ...
    def getCountryName(self) -> str: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFeatureName(self) -> str: ...
    def getLatitude(self) -> float: ...
    def getLocale(self) -> java.util.Locale: ...
    def getLocality(self) -> str: ...
    def getLongitude(self) -> float: ...
    def getMaxAddressLineIndex(self) -> int: ...
    def getPhone(self) -> str: ...
    def getPostalCode(self) -> str: ...
    def getPremises(self) -> str: ...
    def getSubAdminArea(self) -> str: ...
    def getSubLocality(self) -> str: ...
    def getSubThoroughfare(self) -> str: ...
    def getThoroughfare(self) -> str: ...
    def getUrl(self) -> str: ...
    def hasLatitude(self) -> bool: ...
    def hasLongitude(self) -> bool: ...
    def setAddressLine(self, int: int, string: str) -> None: ...
    def setAdminArea(self, string: str) -> None: ...
    def setCountryCode(self, string: str) -> None: ...
    def setCountryName(self, string: str) -> None: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setFeatureName(self, string: str) -> None: ...
    def setLatitude(self, double: float) -> None: ...
    def setLocality(self, string: str) -> None: ...
    def setLongitude(self, double: float) -> None: ...
    def setPhone(self, string: str) -> None: ...
    def setPostalCode(self, string: str) -> None: ...
    def setPremises(self, string: str) -> None: ...
    def setSubAdminArea(self, string: str) -> None: ...
    def setSubLocality(self, string: str) -> None: ...
    def setSubThoroughfare(self, string: str) -> None: ...
    def setThoroughfare(self, string: str) -> None: ...
    def setUrl(self, string: str) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Criteria(android.os.Parcelable):
    ACCURACY_COARSE: typing.ClassVar[int] = ...
    ACCURACY_FINE: typing.ClassVar[int] = ...
    ACCURACY_HIGH: typing.ClassVar[int] = ...
    ACCURACY_LOW: typing.ClassVar[int] = ...
    ACCURACY_MEDIUM: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    NO_REQUIREMENT: typing.ClassVar[int] = ...
    POWER_HIGH: typing.ClassVar[int] = ...
    POWER_LOW: typing.ClassVar[int] = ...
    POWER_MEDIUM: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, criteria: 'Criteria'): ...
    def describeContents(self) -> int: ...
    def getAccuracy(self) -> int: ...
    def getBearingAccuracy(self) -> int: ...
    def getHorizontalAccuracy(self) -> int: ...
    def getPowerRequirement(self) -> int: ...
    def getSpeedAccuracy(self) -> int: ...
    def getVerticalAccuracy(self) -> int: ...
    def isAltitudeRequired(self) -> bool: ...
    def isBearingRequired(self) -> bool: ...
    def isCostAllowed(self) -> bool: ...
    def isSpeedRequired(self) -> bool: ...
    def setAccuracy(self, int: int) -> None: ...
    def setAltitudeRequired(self, boolean: bool) -> None: ...
    def setBearingAccuracy(self, int: int) -> None: ...
    def setBearingRequired(self, boolean: bool) -> None: ...
    def setCostAllowed(self, boolean: bool) -> None: ...
    def setHorizontalAccuracy(self, int: int) -> None: ...
    def setPowerRequirement(self, int: int) -> None: ...
    def setSpeedAccuracy(self, int: int) -> None: ...
    def setSpeedRequired(self, boolean: bool) -> None: ...
    def setVerticalAccuracy(self, int: int) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Geocoder:
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, locale: java.util.Locale): ...
    @typing.overload
    def getFromLocation(self, double: float, double2: float, int: int) -> java.util.List[Address]: ...
    @typing.overload
    def getFromLocation(self, double: float, double2: float, int: int, geocodeListener: typing.Union['Geocoder.GeocodeListener', typing.Callable]) -> None: ...
    @typing.overload
    def getFromLocationName(self, string: str, int: int) -> java.util.List[Address]: ...
    @typing.overload
    def getFromLocationName(self, string: str, int: int, double: float, double2: float, double3: float, double4: float) -> java.util.List[Address]: ...
    @typing.overload
    def getFromLocationName(self, string: str, int: int, geocodeListener: typing.Union['Geocoder.GeocodeListener', typing.Callable]) -> None: ...
    @typing.overload
    def getFromLocationName(self, string: str, int: int, double: float, double2: float, double3: float, double4: float, geocodeListener: typing.Union['Geocoder.GeocodeListener', typing.Callable]) -> None: ...
    @staticmethod
    def isPresent() -> bool: ...
    class GeocodeListener:
        def onError(self, string: str) -> None: ...
        def onGeocode(self, list: java.util.List[Address]) -> None: ...

class GnssAntennaInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCarrierFrequencyMHz(self) -> float: ...
    def getPhaseCenterOffset(self) -> 'GnssAntennaInfo.PhaseCenterOffset': ...
    def getPhaseCenterVariationCorrections(self) -> 'GnssAntennaInfo.SphericalCorrections': ...
    def getSignalGainCorrections(self) -> 'GnssAntennaInfo.SphericalCorrections': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, gnssAntennaInfo: 'GnssAntennaInfo'): ...
        @typing.overload
        def __init__(self, double: float, phaseCenterOffset: 'GnssAntennaInfo.PhaseCenterOffset'): ...
        def build(self) -> 'GnssAntennaInfo': ...
        def setCarrierFrequencyMHz(self, double: float) -> 'GnssAntennaInfo.Builder': ...
        def setPhaseCenterOffset(self, phaseCenterOffset: 'GnssAntennaInfo.PhaseCenterOffset') -> 'GnssAntennaInfo.Builder': ...
        def setPhaseCenterVariationCorrections(self, sphericalCorrections: 'GnssAntennaInfo.SphericalCorrections') -> 'GnssAntennaInfo.Builder': ...
        def setSignalGainCorrections(self, sphericalCorrections: 'GnssAntennaInfo.SphericalCorrections') -> 'GnssAntennaInfo.Builder': ...
    class Listener:
        def onGnssAntennaInfoReceived(self, list: java.util.List['GnssAntennaInfo']) -> None: ...
    class PhaseCenterOffset(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getXOffsetMm(self) -> float: ...
        def getXOffsetUncertaintyMm(self) -> float: ...
        def getYOffsetMm(self) -> float: ...
        def getYOffsetUncertaintyMm(self) -> float: ...
        def getZOffsetMm(self) -> float: ...
        def getZOffsetUncertaintyMm(self) -> float: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class SphericalCorrections(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def __init__(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray], doubleArray2: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getCorrectionUncertaintiesArray(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getCorrectionsArray(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
        def getDeltaPhi(self) -> float: ...
        def getDeltaTheta(self) -> float: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GnssAutomaticGainControl(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCarrierFrequencyHz(self) -> int: ...
    def getConstellationType(self) -> int: ...
    def getLevelDb(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, gnssAutomaticGainControl: 'GnssAutomaticGainControl'): ...
        def build(self) -> 'GnssAutomaticGainControl': ...
        def setCarrierFrequencyHz(self, long: int) -> 'GnssAutomaticGainControl.Builder': ...
        def setConstellationType(self, int: int) -> 'GnssAutomaticGainControl.Builder': ...
        def setLevelDb(self, double: float) -> 'GnssAutomaticGainControl.Builder': ...

class GnssCapabilities(android.os.Parcelable):
    CAPABILITY_SUPPORTED: typing.ClassVar[int] = ...
    CAPABILITY_UNKNOWN: typing.ClassVar[int] = ...
    CAPABILITY_UNSUPPORTED: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getGnssSignalTypes(self) -> java.util.List['GnssSignalType']: ...
    def hasAccumulatedDeltaRange(self) -> int: ...
    def hasAntennaInfo(self) -> bool: ...
    def hasGeofencing(self) -> bool: ...
    def hasGnssAntennaInfo(self) -> bool: ...
    def hasLowPowerMode(self) -> bool: ...
    def hasMeasurementCorrections(self) -> bool: ...
    def hasMeasurementCorrectionsExcessPathLength(self) -> bool: ...
    def hasMeasurementCorrectionsForDriving(self) -> bool: ...
    def hasMeasurementCorrectionsLosSats(self) -> bool: ...
    def hasMeasurementCorrectionsReflectingPlane(self) -> bool: ...
    def hasMeasurementCorrelationVectors(self) -> bool: ...
    def hasMeasurements(self) -> bool: ...
    def hasMsa(self) -> bool: ...
    def hasMsb(self) -> bool: ...
    def hasNavigationMessages(self) -> bool: ...
    def hasOnDemandTime(self) -> bool: ...
    def hasPowerMultibandAcquisition(self) -> bool: ...
    def hasPowerMultibandTracking(self) -> bool: ...
    def hasPowerOtherModes(self) -> bool: ...
    def hasPowerSinglebandAcquisition(self) -> bool: ...
    def hasPowerSinglebandTracking(self) -> bool: ...
    def hasPowerTotal(self) -> bool: ...
    def hasSatelliteBlocklist(self) -> bool: ...
    def hasSatellitePvt(self) -> bool: ...
    def hasScheduling(self) -> bool: ...
    def hasSingleShotFix(self) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, gnssCapabilities: 'GnssCapabilities'): ...
        def build(self) -> 'GnssCapabilities': ...
        def setGnssSignalTypes(self, list: java.util.List['GnssSignalType']) -> 'GnssCapabilities.Builder': ...
        def setHasAccumulatedDeltaRange(self, int: int) -> 'GnssCapabilities.Builder': ...
        def setHasAntennaInfo(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasGeofencing(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasLowPowerMode(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurementCorrections(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurementCorrectionsExcessPathLength(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurementCorrectionsForDriving(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurementCorrectionsLosSats(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurementCorrectionsReflectingPlane(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurementCorrelationVectors(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMeasurements(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMsa(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasMsb(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasNavigationMessages(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasOnDemandTime(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasPowerMultibandAcquisition(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasPowerMultibandTracking(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasPowerOtherModes(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasPowerSinglebandAcquisition(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasPowerSinglebandTracking(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasPowerTotal(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasSatelliteBlocklist(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasSatellitePvt(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasScheduling(self, boolean: bool) -> 'GnssCapabilities.Builder': ...
        def setHasSingleShotFix(self, boolean: bool) -> 'GnssCapabilities.Builder': ...

class GnssClock(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getBiasNanos(self) -> float: ...
    def getBiasUncertaintyNanos(self) -> float: ...
    def getDriftNanosPerSecond(self) -> float: ...
    def getDriftUncertaintyNanosPerSecond(self) -> float: ...
    def getElapsedRealtimeNanos(self) -> int: ...
    def getElapsedRealtimeUncertaintyNanos(self) -> float: ...
    def getFullBiasNanos(self) -> int: ...
    def getHardwareClockDiscontinuityCount(self) -> int: ...
    def getLeapSecond(self) -> int: ...
    def getReferenceCarrierFrequencyHzForIsb(self) -> float: ...
    def getReferenceCodeTypeForIsb(self) -> str: ...
    def getReferenceConstellationTypeForIsb(self) -> int: ...
    def getTimeNanos(self) -> int: ...
    def getTimeUncertaintyNanos(self) -> float: ...
    def hasBiasNanos(self) -> bool: ...
    def hasBiasUncertaintyNanos(self) -> bool: ...
    def hasDriftNanosPerSecond(self) -> bool: ...
    def hasDriftUncertaintyNanosPerSecond(self) -> bool: ...
    def hasElapsedRealtimeNanos(self) -> bool: ...
    def hasElapsedRealtimeUncertaintyNanos(self) -> bool: ...
    def hasFullBiasNanos(self) -> bool: ...
    def hasLeapSecond(self) -> bool: ...
    def hasReferenceCarrierFrequencyHzForIsb(self) -> bool: ...
    def hasReferenceCodeTypeForIsb(self) -> bool: ...
    def hasReferenceConstellationTypeForIsb(self) -> bool: ...
    def hasTimeUncertaintyNanos(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GnssMeasurement(android.os.Parcelable):
    ADR_STATE_CYCLE_SLIP: typing.ClassVar[int] = ...
    ADR_STATE_HALF_CYCLE_REPORTED: typing.ClassVar[int] = ...
    ADR_STATE_HALF_CYCLE_RESOLVED: typing.ClassVar[int] = ...
    ADR_STATE_RESET: typing.ClassVar[int] = ...
    ADR_STATE_UNKNOWN: typing.ClassVar[int] = ...
    ADR_STATE_VALID: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    MULTIPATH_INDICATOR_DETECTED: typing.ClassVar[int] = ...
    MULTIPATH_INDICATOR_NOT_DETECTED: typing.ClassVar[int] = ...
    MULTIPATH_INDICATOR_UNKNOWN: typing.ClassVar[int] = ...
    STATE_2ND_CODE_LOCK: typing.ClassVar[int] = ...
    STATE_BDS_D2_BIT_SYNC: typing.ClassVar[int] = ...
    STATE_BDS_D2_SUBFRAME_SYNC: typing.ClassVar[int] = ...
    STATE_BIT_SYNC: typing.ClassVar[int] = ...
    STATE_CODE_LOCK: typing.ClassVar[int] = ...
    STATE_GAL_E1BC_CODE_LOCK: typing.ClassVar[int] = ...
    STATE_GAL_E1B_PAGE_SYNC: typing.ClassVar[int] = ...
    STATE_GAL_E1C_2ND_CODE_LOCK: typing.ClassVar[int] = ...
    STATE_GLO_STRING_SYNC: typing.ClassVar[int] = ...
    STATE_GLO_TOD_DECODED: typing.ClassVar[int] = ...
    STATE_GLO_TOD_KNOWN: typing.ClassVar[int] = ...
    STATE_MSEC_AMBIGUOUS: typing.ClassVar[int] = ...
    STATE_SBAS_SYNC: typing.ClassVar[int] = ...
    STATE_SUBFRAME_SYNC: typing.ClassVar[int] = ...
    STATE_SYMBOL_SYNC: typing.ClassVar[int] = ...
    STATE_TOW_DECODED: typing.ClassVar[int] = ...
    STATE_TOW_KNOWN: typing.ClassVar[int] = ...
    STATE_UNKNOWN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getAccumulatedDeltaRangeMeters(self) -> float: ...
    def getAccumulatedDeltaRangeState(self) -> int: ...
    def getAccumulatedDeltaRangeUncertaintyMeters(self) -> float: ...
    def getAutomaticGainControlLevelDb(self) -> float: ...
    def getBasebandCn0DbHz(self) -> float: ...
    def getCarrierCycles(self) -> int: ...
    def getCarrierFrequencyHz(self) -> float: ...
    def getCarrierPhase(self) -> float: ...
    def getCarrierPhaseUncertainty(self) -> float: ...
    def getCn0DbHz(self) -> float: ...
    def getCodeType(self) -> str: ...
    def getConstellationType(self) -> int: ...
    def getFullInterSignalBiasNanos(self) -> float: ...
    def getFullInterSignalBiasUncertaintyNanos(self) -> float: ...
    def getMultipathIndicator(self) -> int: ...
    def getPseudorangeRateMetersPerSecond(self) -> float: ...
    def getPseudorangeRateUncertaintyMetersPerSecond(self) -> float: ...
    def getReceivedSvTimeNanos(self) -> int: ...
    def getReceivedSvTimeUncertaintyNanos(self) -> int: ...
    def getSatelliteInterSignalBiasNanos(self) -> float: ...
    def getSatelliteInterSignalBiasUncertaintyNanos(self) -> float: ...
    def getSnrInDb(self) -> float: ...
    def getState(self) -> int: ...
    def getSvid(self) -> int: ...
    def getTimeOffsetNanos(self) -> float: ...
    def hasAutomaticGainControlLevelDb(self) -> bool: ...
    def hasBasebandCn0DbHz(self) -> bool: ...
    def hasCarrierCycles(self) -> bool: ...
    def hasCarrierFrequencyHz(self) -> bool: ...
    def hasCarrierPhase(self) -> bool: ...
    def hasCarrierPhaseUncertainty(self) -> bool: ...
    def hasCodeType(self) -> bool: ...
    def hasFullInterSignalBiasNanos(self) -> bool: ...
    def hasFullInterSignalBiasUncertaintyNanos(self) -> bool: ...
    def hasSatelliteInterSignalBiasNanos(self) -> bool: ...
    def hasSatelliteInterSignalBiasUncertaintyNanos(self) -> bool: ...
    def hasSnrInDb(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GnssMeasurementRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PASSIVE_INTERVAL: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getIntervalMillis(self) -> int: ...
    def hashCode(self) -> int: ...
    def isFullTracking(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, gnssMeasurementRequest: 'GnssMeasurementRequest'): ...
        def build(self) -> 'GnssMeasurementRequest': ...
        def setFullTracking(self, boolean: bool) -> 'GnssMeasurementRequest.Builder': ...
        def setIntervalMillis(self, int: int) -> 'GnssMeasurementRequest.Builder': ...

class GnssMeasurementsEvent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getClock(self) -> GnssClock: ...
    def getGnssAutomaticGainControls(self) -> java.util.Collection[GnssAutomaticGainControl]: ...
    def getMeasurements(self) -> java.util.Collection[GnssMeasurement]: ...
    def hasIsFullTracking(self) -> bool: ...
    def isFullTracking(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, gnssMeasurementsEvent: 'GnssMeasurementsEvent'): ...
        def build(self) -> 'GnssMeasurementsEvent': ...
        def clearIsFullTracking(self) -> 'GnssMeasurementsEvent.Builder': ...
        def setClock(self, gnssClock: GnssClock) -> 'GnssMeasurementsEvent.Builder': ...
        def setGnssAutomaticGainControls(self, collection: typing.Union[java.util.Collection[GnssAutomaticGainControl], typing.Sequence[GnssAutomaticGainControl], typing.Set[GnssAutomaticGainControl]]) -> 'GnssMeasurementsEvent.Builder': ...
        def setIsFullTracking(self, boolean: bool) -> 'GnssMeasurementsEvent.Builder': ...
        def setMeasurements(self, collection: typing.Union[java.util.Collection[GnssMeasurement], typing.Sequence[GnssMeasurement], typing.Set[GnssMeasurement]]) -> 'GnssMeasurementsEvent.Builder': ...
    class Callback:
        STATUS_LOCATION_DISABLED: typing.ClassVar[int] = ...
        STATUS_NOT_ALLOWED: typing.ClassVar[int] = ...
        STATUS_NOT_SUPPORTED: typing.ClassVar[int] = ...
        STATUS_READY: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onGnssMeasurementsReceived(self, gnssMeasurementsEvent: 'GnssMeasurementsEvent') -> None: ...
        def onStatusChanged(self, int: int) -> None: ...

class GnssNavigationMessage(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STATUS_PARITY_PASSED: typing.ClassVar[int] = ...
    STATUS_PARITY_REBUILT: typing.ClassVar[int] = ...
    STATUS_UNKNOWN: typing.ClassVar[int] = ...
    TYPE_BDS_CNAV1: typing.ClassVar[int] = ...
    TYPE_BDS_CNAV2: typing.ClassVar[int] = ...
    TYPE_BDS_D1: typing.ClassVar[int] = ...
    TYPE_BDS_D2: typing.ClassVar[int] = ...
    TYPE_GAL_F: typing.ClassVar[int] = ...
    TYPE_GAL_I: typing.ClassVar[int] = ...
    TYPE_GLO_L1CA: typing.ClassVar[int] = ...
    TYPE_GPS_CNAV2: typing.ClassVar[int] = ...
    TYPE_GPS_L1CA: typing.ClassVar[int] = ...
    TYPE_GPS_L2CNAV: typing.ClassVar[int] = ...
    TYPE_GPS_L5CNAV: typing.ClassVar[int] = ...
    TYPE_IRN_L1: typing.ClassVar[int] = ...
    TYPE_IRN_L5: typing.ClassVar[int] = ...
    TYPE_IRN_L5CA: typing.ClassVar[int] = ...
    TYPE_QZS_L1CA: typing.ClassVar[int] = ...
    TYPE_SBS: typing.ClassVar[int] = ...
    TYPE_UNKNOWN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getMessageId(self) -> int: ...
    def getStatus(self) -> int: ...
    def getSubmessageId(self) -> int: ...
    def getSvid(self) -> int: ...
    def getType(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Callback:
        STATUS_LOCATION_DISABLED: typing.ClassVar[int] = ...
        STATUS_NOT_SUPPORTED: typing.ClassVar[int] = ...
        STATUS_READY: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onGnssNavigationMessageReceived(self, gnssNavigationMessage: 'GnssNavigationMessage') -> None: ...
        def onStatusChanged(self, int: int) -> None: ...

class GnssSignalType(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @staticmethod
    def create(int: int, double: float, string: str) -> 'GnssSignalType': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCarrierFrequencyHz(self) -> float: ...
    def getCodeType(self) -> str: ...
    def getConstellationType(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GnssStatus(android.os.Parcelable):
    CONSTELLATION_BEIDOU: typing.ClassVar[int] = ...
    CONSTELLATION_GALILEO: typing.ClassVar[int] = ...
    CONSTELLATION_GLONASS: typing.ClassVar[int] = ...
    CONSTELLATION_GPS: typing.ClassVar[int] = ...
    CONSTELLATION_IRNSS: typing.ClassVar[int] = ...
    CONSTELLATION_QZSS: typing.ClassVar[int] = ...
    CONSTELLATION_SBAS: typing.ClassVar[int] = ...
    CONSTELLATION_UNKNOWN: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAzimuthDegrees(self, int: int) -> float: ...
    def getBasebandCn0DbHz(self, int: int) -> float: ...
    def getCarrierFrequencyHz(self, int: int) -> float: ...
    def getCn0DbHz(self, int: int) -> float: ...
    def getConstellationType(self, int: int) -> int: ...
    def getElevationDegrees(self, int: int) -> float: ...
    def getSatelliteCount(self) -> int: ...
    def getSvid(self, int: int) -> int: ...
    def hasAlmanacData(self, int: int) -> bool: ...
    def hasBasebandCn0DbHz(self, int: int) -> bool: ...
    def hasCarrierFrequencyHz(self, int: int) -> bool: ...
    def hasEphemerisData(self, int: int) -> bool: ...
    def hashCode(self) -> int: ...
    def usedInFix(self, int: int) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addSatellite(self, int: int, int2: int, float: float, float2: float, float3: float, boolean: bool, boolean2: bool, boolean3: bool, boolean4: bool, float4: float, boolean5: bool, float5: float) -> 'GnssStatus.Builder': ...
        def build(self) -> 'GnssStatus': ...
        def clearSatellites(self) -> 'GnssStatus.Builder': ...
    class Callback:
        def __init__(self): ...
        def onFirstFix(self, int: int) -> None: ...
        def onSatelliteStatusChanged(self, gnssStatus: 'GnssStatus') -> None: ...
        def onStarted(self) -> None: ...
        def onStopped(self) -> None: ...

class GpsSatellite:
    def getAzimuth(self) -> float: ...
    def getElevation(self) -> float: ...
    def getPrn(self) -> int: ...
    def getSnr(self) -> float: ...
    def hasAlmanac(self) -> bool: ...
    def hasEphemeris(self) -> bool: ...
    def usedInFix(self) -> bool: ...

class GpsStatus:
    GPS_EVENT_FIRST_FIX: typing.ClassVar[int] = ...
    GPS_EVENT_SATELLITE_STATUS: typing.ClassVar[int] = ...
    GPS_EVENT_STARTED: typing.ClassVar[int] = ...
    GPS_EVENT_STOPPED: typing.ClassVar[int] = ...
    @staticmethod
    def create(gnssStatus: GnssStatus, int: int) -> 'GpsStatus': ...
    def getMaxSatellites(self) -> int: ...
    def getSatellites(self) -> java.lang.Iterable[GpsSatellite]: ...
    def getTimeToFirstFix(self) -> int: ...
    class Listener:
        def onGpsStatusChanged(self, int: int) -> None: ...
    class NmeaListener:
        def onNmeaReceived(self, long: int, string: str) -> None: ...

class Location(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FORMAT_DEGREES: typing.ClassVar[int] = ...
    FORMAT_MINUTES: typing.ClassVar[int] = ...
    FORMAT_SECONDS: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, location: 'Location'): ...
    @typing.overload
    def __init__(self, string: str): ...
    def bearingTo(self, location: 'Location') -> float: ...
    @typing.overload
    @staticmethod
    def convert(string: str) -> float: ...
    @typing.overload
    @staticmethod
    def convert(double: float, int: int) -> str: ...
    def describeContents(self) -> int: ...
    @staticmethod
    def distanceBetween(double: float, double2: float, double3: float, double4: float, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def distanceTo(self, location: 'Location') -> float: ...
    def dump(self, printer: typing.Union[android.util.Printer, typing.Callable], string: str) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAccuracy(self) -> float: ...
    def getAltitude(self) -> float: ...
    def getBearing(self) -> float: ...
    def getBearingAccuracyDegrees(self) -> float: ...
    @typing.overload
    def getElapsedRealtimeAgeMillis(self) -> int: ...
    @typing.overload
    def getElapsedRealtimeAgeMillis(self, long: int) -> int: ...
    def getElapsedRealtimeMillis(self) -> int: ...
    def getElapsedRealtimeNanos(self) -> int: ...
    def getElapsedRealtimeUncertaintyNanos(self) -> float: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getLatitude(self) -> float: ...
    def getLongitude(self) -> float: ...
    def getMslAltitudeAccuracyMeters(self) -> float: ...
    def getMslAltitudeMeters(self) -> float: ...
    def getProvider(self) -> str: ...
    def getSpeed(self) -> float: ...
    def getSpeedAccuracyMetersPerSecond(self) -> float: ...
    def getTime(self) -> int: ...
    def getVerticalAccuracyMeters(self) -> float: ...
    def hasAccuracy(self) -> bool: ...
    def hasAltitude(self) -> bool: ...
    def hasBearing(self) -> bool: ...
    def hasBearingAccuracy(self) -> bool: ...
    def hasElapsedRealtimeUncertaintyNanos(self) -> bool: ...
    def hasMslAltitude(self) -> bool: ...
    def hasMslAltitudeAccuracy(self) -> bool: ...
    def hasSpeed(self) -> bool: ...
    def hasSpeedAccuracy(self) -> bool: ...
    def hasVerticalAccuracy(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isComplete(self) -> bool: ...
    def isFromMockProvider(self) -> bool: ...
    def isMock(self) -> bool: ...
    def removeAccuracy(self) -> None: ...
    def removeAltitude(self) -> None: ...
    def removeBearing(self) -> None: ...
    def removeBearingAccuracy(self) -> None: ...
    def removeElapsedRealtimeUncertaintyNanos(self) -> None: ...
    def removeMslAltitude(self) -> None: ...
    def removeMslAltitudeAccuracy(self) -> None: ...
    def removeSpeed(self) -> None: ...
    def removeSpeedAccuracy(self) -> None: ...
    def removeVerticalAccuracy(self) -> None: ...
    def reset(self) -> None: ...
    def set(self, location: 'Location') -> None: ...
    def setAccuracy(self, float: float) -> None: ...
    def setAltitude(self, double: float) -> None: ...
    def setBearing(self, float: float) -> None: ...
    def setBearingAccuracyDegrees(self, float: float) -> None: ...
    def setElapsedRealtimeNanos(self, long: int) -> None: ...
    def setElapsedRealtimeUncertaintyNanos(self, double: float) -> None: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setLatitude(self, double: float) -> None: ...
    def setLongitude(self, double: float) -> None: ...
    def setMock(self, boolean: bool) -> None: ...
    def setMslAltitudeAccuracyMeters(self, float: float) -> None: ...
    def setMslAltitudeMeters(self, double: float) -> None: ...
    def setProvider(self, string: str) -> None: ...
    def setSpeed(self, float: float) -> None: ...
    def setSpeedAccuracyMetersPerSecond(self, float: float) -> None: ...
    def setTime(self, long: int) -> None: ...
    def setVerticalAccuracyMeters(self, float: float) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LocationListener:
    def onFlushComplete(self, int: int) -> None: ...
    @typing.overload
    def onLocationChanged(self, location: Location) -> None: ...
    @typing.overload
    def onLocationChanged(self, list: java.util.List[Location]) -> None: ...
    def onProviderDisabled(self, string: str) -> None: ...
    def onProviderEnabled(self, string: str) -> None: ...
    def onStatusChanged(self, string: str, int: int, bundle: android.os.Bundle) -> None: ...

class LocationManager:
    ACTION_GNSS_CAPABILITIES_CHANGED: typing.ClassVar[str] = ...
    EXTRA_GNSS_CAPABILITIES: typing.ClassVar[str] = ...
    EXTRA_LOCATION_ENABLED: typing.ClassVar[str] = ...
    EXTRA_PROVIDER_ENABLED: typing.ClassVar[str] = ...
    EXTRA_PROVIDER_NAME: typing.ClassVar[str] = ...
    FUSED_PROVIDER: typing.ClassVar[str] = ...
    GPS_PROVIDER: typing.ClassVar[str] = ...
    KEY_FLUSH_COMPLETE: typing.ClassVar[str] = ...
    KEY_LOCATIONS: typing.ClassVar[str] = ...
    KEY_LOCATION_CHANGED: typing.ClassVar[str] = ...
    KEY_PROVIDER_ENABLED: typing.ClassVar[str] = ...
    KEY_PROXIMITY_ENTERING: typing.ClassVar[str] = ...
    KEY_STATUS_CHANGED: typing.ClassVar[str] = ...
    MODE_CHANGED_ACTION: typing.ClassVar[str] = ...
    NETWORK_PROVIDER: typing.ClassVar[str] = ...
    PASSIVE_PROVIDER: typing.ClassVar[str] = ...
    PROVIDERS_CHANGED_ACTION: typing.ClassVar[str] = ...
    def addGpsStatusListener(self, listener: typing.Union[GpsStatus.Listener, typing.Callable]) -> bool: ...
    @typing.overload
    def addNmeaListener(self, nmeaListener: typing.Union[GpsStatus.NmeaListener, typing.Callable]) -> bool: ...
    @typing.overload
    def addNmeaListener(self, onNmeaMessageListener: typing.Union['OnNmeaMessageListener', typing.Callable]) -> bool: ...
    @typing.overload
    def addNmeaListener(self, onNmeaMessageListener: typing.Union['OnNmeaMessageListener', typing.Callable], handler: android.os.Handler) -> bool: ...
    @typing.overload
    def addNmeaListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], onNmeaMessageListener: typing.Union['OnNmeaMessageListener', typing.Callable]) -> bool: ...
    def addProximityAlert(self, double: float, double2: float, float: float, long: int, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def addTestProvider(self, string: str, providerProperties: android.location.provider.ProviderProperties) -> None: ...
    @typing.overload
    def addTestProvider(self, string: str, providerProperties: android.location.provider.ProviderProperties, set: java.util.Set[str]) -> None: ...
    @typing.overload
    def addTestProvider(self, string: str, boolean: bool, boolean2: bool, boolean3: bool, boolean4: bool, boolean5: bool, boolean6: bool, boolean7: bool, int: int, int2: int) -> None: ...
    def clearTestProviderEnabled(self, string: str) -> None: ...
    def clearTestProviderLocation(self, string: str) -> None: ...
    def clearTestProviderStatus(self, string: str) -> None: ...
    def getAllProviders(self) -> java.util.List[str]: ...
    def getBestProvider(self, criteria: Criteria, boolean: bool) -> str: ...
    @typing.overload
    def getCurrentLocation(self, string: str, locationRequest: 'LocationRequest', cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[Location], typing.Callable[[Location], None]]) -> None: ...
    @typing.overload
    def getCurrentLocation(self, string: str, cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[Location], typing.Callable[[Location], None]]) -> None: ...
    def getGnssAntennaInfos(self) -> java.util.List[GnssAntennaInfo]: ...
    def getGnssCapabilities(self) -> GnssCapabilities: ...
    def getGnssHardwareModelName(self) -> str: ...
    def getGnssYearOfHardware(self) -> int: ...
    def getGpsStatus(self, gpsStatus: GpsStatus) -> GpsStatus: ...
    def getLastKnownLocation(self, string: str) -> Location: ...
    def getProvider(self, string: str) -> 'LocationProvider': ...
    def getProviderProperties(self, string: str) -> android.location.provider.ProviderProperties: ...
    @typing.overload
    def getProviders(self, criteria: Criteria, boolean: bool) -> java.util.List[str]: ...
    @typing.overload
    def getProviders(self, boolean: bool) -> java.util.List[str]: ...
    def hasProvider(self, string: str) -> bool: ...
    def isLocationEnabled(self) -> bool: ...
    def isProviderEnabled(self, string: str) -> bool: ...
    def registerAntennaInfoListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], listener: typing.Union[GnssAntennaInfo.Listener, typing.Callable]) -> bool: ...
    @typing.overload
    def registerGnssMeasurementsCallback(self, gnssMeasurementRequest: GnssMeasurementRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: GnssMeasurementsEvent.Callback) -> bool: ...
    @typing.overload
    def registerGnssMeasurementsCallback(self, callback: GnssMeasurementsEvent.Callback) -> bool: ...
    @typing.overload
    def registerGnssMeasurementsCallback(self, callback: GnssMeasurementsEvent.Callback, handler: android.os.Handler) -> bool: ...
    @typing.overload
    def registerGnssMeasurementsCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: GnssMeasurementsEvent.Callback) -> bool: ...
    @typing.overload
    def registerGnssNavigationMessageCallback(self, callback: GnssNavigationMessage.Callback) -> bool: ...
    @typing.overload
    def registerGnssNavigationMessageCallback(self, callback: GnssNavigationMessage.Callback, handler: android.os.Handler) -> bool: ...
    @typing.overload
    def registerGnssNavigationMessageCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: GnssNavigationMessage.Callback) -> bool: ...
    @typing.overload
    def registerGnssStatusCallback(self, callback: GnssStatus.Callback) -> bool: ...
    @typing.overload
    def registerGnssStatusCallback(self, callback: GnssStatus.Callback, handler: android.os.Handler) -> bool: ...
    @typing.overload
    def registerGnssStatusCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: GnssStatus.Callback) -> bool: ...
    def removeGpsStatusListener(self, listener: typing.Union[GpsStatus.Listener, typing.Callable]) -> None: ...
    @typing.overload
    def removeNmeaListener(self, nmeaListener: typing.Union[GpsStatus.NmeaListener, typing.Callable]) -> None: ...
    @typing.overload
    def removeNmeaListener(self, onNmeaMessageListener: typing.Union['OnNmeaMessageListener', typing.Callable]) -> None: ...
    def removeProximityAlert(self, pendingIntent: android.app.PendingIntent) -> None: ...
    def removeTestProvider(self, string: str) -> None: ...
    @typing.overload
    def removeUpdates(self, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def removeUpdates(self, locationListener: typing.Union[LocationListener, typing.Callable]) -> None: ...
    @typing.overload
    def requestFlush(self, string: str, pendingIntent: android.app.PendingIntent, int: int) -> None: ...
    @typing.overload
    def requestFlush(self, string: str, locationListener: typing.Union[LocationListener, typing.Callable], int: int) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, string: str, locationRequest: 'LocationRequest', pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, string: str, locationRequest: 'LocationRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], locationListener: typing.Union[LocationListener, typing.Callable]) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, string: str, long: int, float: float, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, string: str, long: int, float: float, locationListener: typing.Union[LocationListener, typing.Callable]) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, string: str, long: int, float: float, locationListener: typing.Union[LocationListener, typing.Callable], looper: android.os.Looper) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, string: str, long: int, float: float, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], locationListener: typing.Union[LocationListener, typing.Callable]) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, long: int, float: float, criteria: Criteria, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, long: int, float: float, criteria: Criteria, locationListener: typing.Union[LocationListener, typing.Callable], looper: android.os.Looper) -> None: ...
    @typing.overload
    def requestLocationUpdates(self, long: int, float: float, criteria: Criteria, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], locationListener: typing.Union[LocationListener, typing.Callable]) -> None: ...
    @typing.overload
    def requestSingleUpdate(self, criteria: Criteria, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestSingleUpdate(self, criteria: Criteria, locationListener: typing.Union[LocationListener, typing.Callable], looper: android.os.Looper) -> None: ...
    @typing.overload
    def requestSingleUpdate(self, string: str, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestSingleUpdate(self, string: str, locationListener: typing.Union[LocationListener, typing.Callable], looper: android.os.Looper) -> None: ...
    def sendExtraCommand(self, string: str, string2: str, bundle: android.os.Bundle) -> bool: ...
    def setTestProviderEnabled(self, string: str, boolean: bool) -> None: ...
    def setTestProviderLocation(self, string: str, location: Location) -> None: ...
    def setTestProviderStatus(self, string: str, int: int, bundle: android.os.Bundle, long: int) -> None: ...
    def unregisterAntennaInfoListener(self, listener: typing.Union[GnssAntennaInfo.Listener, typing.Callable]) -> None: ...
    def unregisterGnssMeasurementsCallback(self, callback: GnssMeasurementsEvent.Callback) -> None: ...
    def unregisterGnssNavigationMessageCallback(self, callback: GnssNavigationMessage.Callback) -> None: ...
    def unregisterGnssStatusCallback(self, callback: GnssStatus.Callback) -> None: ...

class LocationProvider:
    AVAILABLE: typing.ClassVar[int] = ...
    OUT_OF_SERVICE: typing.ClassVar[int] = ...
    TEMPORARILY_UNAVAILABLE: typing.ClassVar[int] = ...
    def getAccuracy(self) -> int: ...
    def getName(self) -> str: ...
    def getPowerRequirement(self) -> int: ...
    def hasMonetaryCost(self) -> bool: ...
    def meetsCriteria(self, criteria: Criteria) -> bool: ...
    def requiresCell(self) -> bool: ...
    def requiresNetwork(self) -> bool: ...
    def requiresSatellite(self) -> bool: ...
    def supportsAltitude(self) -> bool: ...
    def supportsBearing(self) -> bool: ...
    def supportsSpeed(self) -> bool: ...

class LocationRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PASSIVE_INTERVAL: typing.ClassVar[int] = ...
    QUALITY_BALANCED_POWER_ACCURACY: typing.ClassVar[int] = ...
    QUALITY_HIGH_ACCURACY: typing.ClassVar[int] = ...
    QUALITY_LOW_POWER: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDurationMillis(self) -> int: ...
    def getIntervalMillis(self) -> int: ...
    def getMaxUpdateDelayMillis(self) -> int: ...
    def getMaxUpdates(self) -> int: ...
    def getMinUpdateDistanceMeters(self) -> float: ...
    def getMinUpdateIntervalMillis(self) -> int: ...
    def getQuality(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, locationRequest: 'LocationRequest'): ...
        @typing.overload
        def __init__(self, long: int): ...
        def build(self) -> 'LocationRequest': ...
        def clearMinUpdateIntervalMillis(self) -> 'LocationRequest.Builder': ...
        def setDurationMillis(self, long: int) -> 'LocationRequest.Builder': ...
        def setIntervalMillis(self, long: int) -> 'LocationRequest.Builder': ...
        def setMaxUpdateDelayMillis(self, long: int) -> 'LocationRequest.Builder': ...
        def setMaxUpdates(self, int: int) -> 'LocationRequest.Builder': ...
        def setMinUpdateDistanceMeters(self, float: float) -> 'LocationRequest.Builder': ...
        def setMinUpdateIntervalMillis(self, long: int) -> 'LocationRequest.Builder': ...
        def setQuality(self, int: int) -> 'LocationRequest.Builder': ...

class OnNmeaMessageListener:
    def onNmeaMessage(self, string: str, long: int) -> None: ...

class SettingInjectorService(android.app.Service):
    ACTION_INJECTED_SETTING_CHANGED: typing.ClassVar[str] = ...
    ACTION_SERVICE_INTENT: typing.ClassVar[str] = ...
    ATTRIBUTES_NAME: typing.ClassVar[str] = ...
    META_DATA_NAME: typing.ClassVar[str] = ...
    def __init__(self, string: str): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onStart(self, intent: android.content.Intent, int2: int) -> None: ...
    def onStartCommand(self, intent: android.content.Intent, int2: int, int3: int) -> int: ...
    @staticmethod
    def refreshSettings(context: android.content.Context) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.location")``.

    Address: typing.Type[Address]
    Criteria: typing.Type[Criteria]
    Geocoder: typing.Type[Geocoder]
    GnssAntennaInfo: typing.Type[GnssAntennaInfo]
    GnssAutomaticGainControl: typing.Type[GnssAutomaticGainControl]
    GnssCapabilities: typing.Type[GnssCapabilities]
    GnssClock: typing.Type[GnssClock]
    GnssMeasurement: typing.Type[GnssMeasurement]
    GnssMeasurementRequest: typing.Type[GnssMeasurementRequest]
    GnssMeasurementsEvent: typing.Type[GnssMeasurementsEvent]
    GnssNavigationMessage: typing.Type[GnssNavigationMessage]
    GnssSignalType: typing.Type[GnssSignalType]
    GnssStatus: typing.Type[GnssStatus]
    GpsSatellite: typing.Type[GpsSatellite]
    GpsStatus: typing.Type[GpsStatus]
    Location: typing.Type[Location]
    LocationListener: typing.Type[LocationListener]
    LocationManager: typing.Type[LocationManager]
    LocationProvider: typing.Type[LocationProvider]
    LocationRequest: typing.Type[LocationRequest]
    OnNmeaMessageListener: typing.Type[OnNmeaMessageListener]
    SettingInjectorService: typing.Type[SettingInjectorService]
    altitude: android.location.altitude.__module_protocol__
    provider: android.location.provider.__module_protocol__
