
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import jpype
import typing



class ProtoOutputStream:
    FIELD_COUNT_MASK: typing.ClassVar[int] = ...
    FIELD_COUNT_PACKED: typing.ClassVar[int] = ...
    FIELD_COUNT_REPEATED: typing.ClassVar[int] = ...
    FIELD_COUNT_SHIFT: typing.ClassVar[int] = ...
    FIELD_COUNT_SINGLE: typing.ClassVar[int] = ...
    FIELD_COUNT_UNKNOWN: typing.ClassVar[int] = ...
    FIELD_ID_SHIFT: typing.ClassVar[int] = ...
    FIELD_TYPE_BOOL: typing.ClassVar[int] = ...
    FIELD_TYPE_BYTES: typing.ClassVar[int] = ...
    FIELD_TYPE_DOUBLE: typing.ClassVar[int] = ...
    FIELD_TYPE_ENUM: typing.ClassVar[int] = ...
    FIELD_TYPE_FIXED32: typing.ClassVar[int] = ...
    FIELD_TYPE_FIXED64: typing.ClassVar[int] = ...
    FIELD_TYPE_FLOAT: typing.ClassVar[int] = ...
    FIELD_TYPE_INT32: typing.ClassVar[int] = ...
    FIELD_TYPE_INT64: typing.ClassVar[int] = ...
    FIELD_TYPE_MASK: typing.ClassVar[int] = ...
    FIELD_TYPE_MESSAGE: typing.ClassVar[int] = ...
    FIELD_TYPE_SFIXED32: typing.ClassVar[int] = ...
    FIELD_TYPE_SFIXED64: typing.ClassVar[int] = ...
    FIELD_TYPE_SHIFT: typing.ClassVar[int] = ...
    FIELD_TYPE_SINT32: typing.ClassVar[int] = ...
    FIELD_TYPE_SINT64: typing.ClassVar[int] = ...
    FIELD_TYPE_STRING: typing.ClassVar[int] = ...
    FIELD_TYPE_UINT32: typing.ClassVar[int] = ...
    FIELD_TYPE_UINT64: typing.ClassVar[int] = ...
    WIRE_TYPE_END_GROUP: typing.ClassVar[int] = ...
    WIRE_TYPE_FIXED32: typing.ClassVar[int] = ...
    WIRE_TYPE_FIXED64: typing.ClassVar[int] = ...
    WIRE_TYPE_LENGTH_DELIMITED: typing.ClassVar[int] = ...
    WIRE_TYPE_MASK: typing.ClassVar[int] = ...
    WIRE_TYPE_START_GROUP: typing.ClassVar[int] = ...
    WIRE_TYPE_VARINT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, outputStream: java.io.OutputStream): ...
    @staticmethod
    def checkFieldId(long: int, long2: int) -> int: ...
    def dump(self, string: str) -> None: ...
    def end(self, long: int) -> None: ...
    def flush(self) -> None: ...
    def getBytes(self) -> typing.MutableSequence[int]: ...
    @staticmethod
    def getFieldCountString(long: int) -> str: ...
    @staticmethod
    def getFieldIdString(long: int) -> str: ...
    @staticmethod
    def getFieldTypeString(long: int) -> str: ...
    def getRawSize(self) -> int: ...
    @staticmethod
    def getWireTypeString(int: int) -> str: ...
    @staticmethod
    def makeFieldId(int: int, long: int) -> int: ...
    @staticmethod
    def makeToken(int: int, boolean: bool, int2: int, int3: int, int4: int) -> int: ...
    def start(self, long: int) -> int: ...
    @staticmethod
    def token2String(long: int) -> str: ...
    @typing.overload
    def write(self, long: int, boolean: bool) -> None: ...
    @typing.overload
    def write(self, long: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def write(self, long: int, double: float) -> None: ...
    @typing.overload
    def write(self, long: int, float: float) -> None: ...
    @typing.overload
    def write(self, long: int, int: int) -> None: ...
    @typing.overload
    def write(self, long: int, string: str) -> None: ...
    @typing.overload
    def write(self, long: int, long2: int) -> None: ...
    def writeTag(self, int: int, int2: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.util.proto")``.

    ProtoOutputStream: typing.Type[ProtoOutputStream]
