
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.graphics
import android.health.connect.datatypes.units
import android.os
import datetime
import java.lang
import java.time
import java.util
import typing



_AggregationType__T = typing.TypeVar('_AggregationType__T')  # <T>
class AggregationType(typing.Generic[_AggregationType__T]): ...

class AppInfo:
    def getIcon(self) -> android.graphics.Bitmap: ...
    def getName(self) -> str: ...
    def getPackageName(self) -> str: ...

class BodyTemperatureMeasurementLocation:
    MEASUREMENT_LOCATION_ARMPIT: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_EAR: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_FINGER: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_FOREHEAD: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_MOUTH: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_RECTUM: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_TEMPORAL_ARTERY: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_TOE: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_UNKNOWN: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_VAGINA: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_WRIST: typing.ClassVar[int] = ...

class DataOrigin:
    def equals(self, object: typing.Any) -> bool: ...
    def getPackageName(self) -> str: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'DataOrigin': ...
        def setPackageName(self, string: str) -> 'DataOrigin.Builder': ...

class Device:
    DEVICE_TYPE_CHEST_STRAP: typing.ClassVar[int] = ...
    DEVICE_TYPE_FITNESS_BAND: typing.ClassVar[int] = ...
    DEVICE_TYPE_HEAD_MOUNTED: typing.ClassVar[int] = ...
    DEVICE_TYPE_PHONE: typing.ClassVar[int] = ...
    DEVICE_TYPE_RING: typing.ClassVar[int] = ...
    DEVICE_TYPE_SCALE: typing.ClassVar[int] = ...
    DEVICE_TYPE_SMART_DISPLAY: typing.ClassVar[int] = ...
    DEVICE_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    DEVICE_TYPE_WATCH: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getManufacturer(self) -> str: ...
    def getModel(self) -> str: ...
    def getType(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'Device': ...
        def setManufacturer(self, string: str) -> 'Device.Builder': ...
        def setModel(self, string: str) -> 'Device.Builder': ...
        def setType(self, int: int) -> 'Device.Builder': ...

class ExerciseLap:
    def equals(self, object: typing.Any) -> bool: ...
    def getEndTime(self) -> java.time.Instant: ...
    def getLength(self) -> android.health.connect.datatypes.units.Length: ...
    def getStartTime(self) -> java.time.Instant: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]): ...
        def build(self) -> 'ExerciseLap': ...
        def setLength(self, length: android.health.connect.datatypes.units.Length) -> 'ExerciseLap.Builder': ...

class ExerciseRoute(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List['ExerciseRoute.Location']): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getRouteLocations(self) -> java.util.List['ExerciseRoute.Location']: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Location(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getAltitude(self) -> android.health.connect.datatypes.units.Length: ...
        def getHorizontalAccuracy(self) -> android.health.connect.datatypes.units.Length: ...
        def getLatitude(self) -> float: ...
        def getLongitude(self) -> float: ...
        def getTime(self) -> java.time.Instant: ...
        def getVerticalAccuracy(self) -> android.health.connect.datatypes.units.Length: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, instant: typing.Union[java.time.Instant, datetime.datetime], double: float, double2: float): ...
            def build(self) -> 'ExerciseRoute.Location': ...
            def setAltitude(self, length: android.health.connect.datatypes.units.Length) -> 'ExerciseRoute.Location.Builder': ...
            def setHorizontalAccuracy(self, length: android.health.connect.datatypes.units.Length) -> 'ExerciseRoute.Location.Builder': ...
            def setVerticalAccuracy(self, length: android.health.connect.datatypes.units.Length) -> 'ExerciseRoute.Location.Builder': ...

class ExerciseSegment:
    def equals(self, object: typing.Any) -> bool: ...
    def getEndTime(self) -> java.time.Instant: ...
    def getRepetitionsCount(self) -> int: ...
    def getSegmentType(self) -> int: ...
    def getStartTime(self) -> java.time.Instant: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], int: int): ...
        def build(self) -> 'ExerciseSegment': ...
        def setRepetitionsCount(self, int: int) -> 'ExerciseSegment.Builder': ...

class ExerciseSegmentType:
    EXERCISE_SEGMENT_TYPE_ARM_CURL: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BACK_EXTENSION: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BALL_SLAM: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BARBELL_SHOULDER_PRESS: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BENCH_PRESS: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BENCH_SIT_UP: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BIKING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BIKING_STATIONARY: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_BURPEE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_CRUNCH: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DEADLIFT: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DOUBLE_ARM_TRICEPS_EXTENSION: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_LEFT_ARM: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_RIGHT_ARM: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_FRONT_RAISE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_LATERAL_RAISE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_ROW: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_LEFT_ARM: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_RIGHT_ARM: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_TWO_ARM: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_ELLIPTICAL: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_FORWARD_TWIST: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_FRONT_RAISE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_HIP_THRUST: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_HULA_HOOP: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_JUMPING_JACK: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_JUMP_ROPE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_KETTLEBELL_SWING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LATERAL_RAISE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LAT_PULL_DOWN: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LEG_CURL: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LEG_EXTENSION: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LEG_PRESS: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LEG_RAISE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_LUNGE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_MOUNTAIN_CLIMBER: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_OTHER_WORKOUT: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_PAUSE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_PILATES: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_PLANK: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_PULL_UP: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_PUNCH: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_REST: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_ROWING_MACHINE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_RUNNING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_RUNNING_TREADMILL: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SHOULDER_PRESS: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SINGLE_ARM_TRICEPS_EXTENSION: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SIT_UP: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SQUAT: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING_MACHINE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_STRETCHING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_BACKSTROKE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_BREASTSTROKE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_BUTTERFLY: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_FREESTYLE: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_MIXED: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_OPEN_WATER: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_OTHER: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_SWIMMING_POOL: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_UPPER_TWIST: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_WALKING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_WEIGHTLIFTING: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_WHEELCHAIR: typing.ClassVar[int] = ...
    EXERCISE_SEGMENT_TYPE_YOGA: typing.ClassVar[int] = ...

class ExerciseSessionType:
    EXERCISE_SESSION_TYPE_BADMINTON: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_BASEBALL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_BASKETBALL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_BIKING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_BIKING_STATIONARY: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_BOOT_CAMP: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_BOXING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_CALISTHENICS: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_CRICKET: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_DANCING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ELLIPTICAL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_EXERCISE_CLASS: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_FENCING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_FOOTBALL_AMERICAN: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_FOOTBALL_AUSTRALIAN: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_FRISBEE_DISC: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_GOLF: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_GUIDED_BREATHING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_GYMNASTICS: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_HANDBALL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_HIKING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ICE_HOCKEY: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ICE_SKATING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_MARTIAL_ARTS: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_OTHER_WORKOUT: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_PADDLING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_PARAGLIDING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_PILATES: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_RACQUETBALL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ROCK_CLIMBING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ROLLER_HOCKEY: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ROWING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_ROWING_MACHINE: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_RUGBY: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_RUNNING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_RUNNING_TREADMILL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SAILING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SCUBA_DIVING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SKATING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SKIING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SNOWBOARDING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SNOWSHOEING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SOCCER: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SOFTBALL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SQUASH: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_STAIR_CLIMBING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_STAIR_CLIMBING_MACHINE: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_STRENGTH_TRAINING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_STRETCHING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SURFING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SWIMMING_OPEN_WATER: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_SWIMMING_POOL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_TABLE_TENNIS: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_TENNIS: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_VOLLEYBALL: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_WALKING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_WATER_POLO: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_WEIGHTLIFTING: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_WHEELCHAIR: typing.ClassVar[int] = ...
    EXERCISE_SESSION_TYPE_YOGA: typing.ClassVar[int] = ...

class MealType:
    MEAL_TYPE_BREAKFAST: typing.ClassVar[int] = ...
    MEAL_TYPE_DINNER: typing.ClassVar[int] = ...
    MEAL_TYPE_LUNCH: typing.ClassVar[int] = ...
    MEAL_TYPE_SNACK: typing.ClassVar[int] = ...
    MEAL_TYPE_UNKNOWN: typing.ClassVar[int] = ...

class Metadata:
    RECORDING_METHOD_ACTIVELY_RECORDED: typing.ClassVar[int] = ...
    RECORDING_METHOD_AUTOMATICALLY_RECORDED: typing.ClassVar[int] = ...
    RECORDING_METHOD_MANUAL_ENTRY: typing.ClassVar[int] = ...
    RECORDING_METHOD_UNKNOWN: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getClientRecordId(self) -> str: ...
    def getClientRecordVersion(self) -> int: ...
    def getDataOrigin(self) -> DataOrigin: ...
    def getDevice(self) -> Device: ...
    def getId(self) -> str: ...
    def getLastModifiedTime(self) -> java.time.Instant: ...
    def getRecordingMethod(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'Metadata': ...
        def setClientRecordId(self, string: str) -> 'Metadata.Builder': ...
        def setClientRecordVersion(self, long: int) -> 'Metadata.Builder': ...
        def setDataOrigin(self, dataOrigin: DataOrigin) -> 'Metadata.Builder': ...
        def setDevice(self, device: Device) -> 'Metadata.Builder': ...
        def setId(self, string: str) -> 'Metadata.Builder': ...
        def setLastModifiedTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'Metadata.Builder': ...
        def setRecordingMethod(self, int: int) -> 'Metadata.Builder': ...

class PlannedExerciseBlock:
    def equals(self, object: typing.Any) -> bool: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getRepetitions(self) -> int: ...
    def getSteps(self) -> java.util.List['PlannedExerciseStep']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, int: int): ...
        def addStep(self, plannedExerciseStep: 'PlannedExerciseStep') -> 'PlannedExerciseBlock.Builder': ...
        def build(self) -> 'PlannedExerciseBlock': ...
        def clearSteps(self) -> 'PlannedExerciseBlock.Builder': ...
        def setDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PlannedExerciseBlock.Builder': ...
        def setRepetitions(self, int: int) -> 'PlannedExerciseBlock.Builder': ...
        def setSteps(self, list: java.util.List['PlannedExerciseStep']) -> 'PlannedExerciseBlock.Builder': ...

class PlannedExerciseStep:
    EXERCISE_CATEGORY_ACTIVE: typing.ClassVar[int] = ...
    EXERCISE_CATEGORY_COOLDOWN: typing.ClassVar[int] = ...
    EXERCISE_CATEGORY_RECOVERY: typing.ClassVar[int] = ...
    EXERCISE_CATEGORY_REST: typing.ClassVar[int] = ...
    EXERCISE_CATEGORY_UNKNOWN: typing.ClassVar[int] = ...
    EXERCISE_CATEGORY_WARMUP: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCompletionGoal(self) -> 'ExerciseCompletionGoal': ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getExerciseCategory(self) -> int: ...
    def getExerciseType(self) -> int: ...
    def getPerformanceGoals(self) -> java.util.List['ExercisePerformanceGoal']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, int: int, int2: int, exerciseCompletionGoal: 'ExerciseCompletionGoal'): ...
        def addPerformanceGoal(self, exercisePerformanceGoal: 'ExercisePerformanceGoal') -> 'PlannedExerciseStep.Builder': ...
        def build(self) -> 'PlannedExerciseStep': ...
        def clearPerformanceGoals(self) -> 'PlannedExerciseStep.Builder': ...
        def setCompletionGoal(self, exerciseCompletionGoal: 'ExerciseCompletionGoal') -> 'PlannedExerciseStep.Builder': ...
        def setDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PlannedExerciseStep.Builder': ...
        def setExerciseCategory(self, int: int) -> 'PlannedExerciseStep.Builder': ...
        def setExerciseType(self, int: int) -> 'PlannedExerciseStep.Builder': ...
        def setPerformanceGoals(self, list: java.util.List['ExercisePerformanceGoal']) -> 'PlannedExerciseStep.Builder': ...

class Record:
    def equals(self, object: typing.Any) -> bool: ...
    def getMetadata(self) -> Metadata: ...
    def hashCode(self) -> int: ...

class InstantRecord(Record):
    def equals(self, object: typing.Any) -> bool: ...
    def getTime(self) -> java.time.Instant: ...
    def getZoneOffset(self) -> java.time.ZoneOffset: ...
    def hashCode(self) -> int: ...

class IntervalRecord(Record):
    def equals(self, object: typing.Any) -> bool: ...
    def getEndTime(self) -> java.time.Instant: ...
    def getEndZoneOffset(self) -> java.time.ZoneOffset: ...
    def getStartTime(self) -> java.time.Instant: ...
    def getStartZoneOffset(self) -> java.time.ZoneOffset: ...
    def hashCode(self) -> int: ...

class ActiveCaloriesBurnedRecord(IntervalRecord):
    ACTIVE_CALORIES_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getEnergy(self) -> android.health.connect.datatypes.units.Energy: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], energy: android.health.connect.datatypes.units.Energy): ...
        def build(self) -> 'ActiveCaloriesBurnedRecord': ...
        def clearEndZoneOffset(self) -> 'ActiveCaloriesBurnedRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'ActiveCaloriesBurnedRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'ActiveCaloriesBurnedRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'ActiveCaloriesBurnedRecord.Builder': ...

class BasalBodyTemperatureRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getMeasurementLocation(self) -> int: ...
    def getTemperature(self) -> android.health.connect.datatypes.units.Temperature: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int, temperature: android.health.connect.datatypes.units.Temperature): ...
        def build(self) -> 'BasalBodyTemperatureRecord': ...
        def clearZoneOffset(self) -> 'BasalBodyTemperatureRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BasalBodyTemperatureRecord.Builder': ...

class BasalMetabolicRateRecord(InstantRecord):
    BASAL_CALORIES_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBasalMetabolicRate(self) -> android.health.connect.datatypes.units.Power: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], power: android.health.connect.datatypes.units.Power): ...
        def build(self) -> 'BasalMetabolicRateRecord': ...
        def clearZoneOffset(self) -> 'BasalMetabolicRateRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BasalMetabolicRateRecord.Builder': ...

class BloodGlucoseRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getLevel(self) -> android.health.connect.datatypes.units.BloodGlucose: ...
    def getMealType(self) -> int: ...
    def getRelationToMeal(self) -> int: ...
    def getSpecimenSource(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int, bloodGlucose: android.health.connect.datatypes.units.BloodGlucose, int2: int, int3: int): ...
        def build(self) -> 'BloodGlucoseRecord': ...
        def clearZoneOffset(self) -> 'BloodGlucoseRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BloodGlucoseRecord.Builder': ...
    class RelationToMealType:
        RELATION_TO_MEAL_AFTER_MEAL: typing.ClassVar[int] = ...
        RELATION_TO_MEAL_BEFORE_MEAL: typing.ClassVar[int] = ...
        RELATION_TO_MEAL_FASTING: typing.ClassVar[int] = ...
        RELATION_TO_MEAL_GENERAL: typing.ClassVar[int] = ...
        RELATION_TO_MEAL_UNKNOWN: typing.ClassVar[int] = ...
    class SpecimenSource:
        SPECIMEN_SOURCE_CAPILLARY_BLOOD: typing.ClassVar[int] = ...
        SPECIMEN_SOURCE_INTERSTITIAL_FLUID: typing.ClassVar[int] = ...
        SPECIMEN_SOURCE_PLASMA: typing.ClassVar[int] = ...
        SPECIMEN_SOURCE_SERUM: typing.ClassVar[int] = ...
        SPECIMEN_SOURCE_TEARS: typing.ClassVar[int] = ...
        SPECIMEN_SOURCE_UNKNOWN: typing.ClassVar[int] = ...
        SPECIMEN_SOURCE_WHOLE_BLOOD: typing.ClassVar[int] = ...

class BloodPressureRecord(InstantRecord):
    DIASTOLIC_AVG: typing.ClassVar[AggregationType] = ...
    DIASTOLIC_MAX: typing.ClassVar[AggregationType] = ...
    DIASTOLIC_MIN: typing.ClassVar[AggregationType] = ...
    SYSTOLIC_AVG: typing.ClassVar[AggregationType] = ...
    SYSTOLIC_MAX: typing.ClassVar[AggregationType] = ...
    SYSTOLIC_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBodyPosition(self) -> int: ...
    def getDiastolic(self) -> android.health.connect.datatypes.units.Pressure: ...
    def getMeasurementLocation(self) -> int: ...
    def getSystolic(self) -> android.health.connect.datatypes.units.Pressure: ...
    def hashCode(self) -> int: ...
    class BloodPressureMeasurementLocation:
        BLOOD_PRESSURE_MEASUREMENT_LOCATION_LEFT_UPPER_ARM: typing.ClassVar[int] = ...
        BLOOD_PRESSURE_MEASUREMENT_LOCATION_LEFT_WRIST: typing.ClassVar[int] = ...
        BLOOD_PRESSURE_MEASUREMENT_LOCATION_RIGHT_UPPER_ARM: typing.ClassVar[int] = ...
        BLOOD_PRESSURE_MEASUREMENT_LOCATION_RIGHT_WRIST: typing.ClassVar[int] = ...
        BLOOD_PRESSURE_MEASUREMENT_LOCATION_UNKNOWN: typing.ClassVar[int] = ...
    class BodyPosition:
        BODY_POSITION_LYING_DOWN: typing.ClassVar[int] = ...
        BODY_POSITION_RECLINING: typing.ClassVar[int] = ...
        BODY_POSITION_SITTING_DOWN: typing.ClassVar[int] = ...
        BODY_POSITION_STANDING_UP: typing.ClassVar[int] = ...
        BODY_POSITION_UNKNOWN: typing.ClassVar[int] = ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int, pressure: android.health.connect.datatypes.units.Pressure, pressure2: android.health.connect.datatypes.units.Pressure, int2: int): ...
        def build(self) -> 'BloodPressureRecord': ...
        def clearZoneOffset(self) -> 'BloodPressureRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BloodPressureRecord.Builder': ...

class BodyFatRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getPercentage(self) -> android.health.connect.datatypes.units.Percentage: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], percentage: android.health.connect.datatypes.units.Percentage): ...
        def build(self) -> 'BodyFatRecord': ...
        def clearZoneOffset(self) -> 'BodyFatRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BodyFatRecord.Builder': ...

class BodyTemperatureRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getMeasurementLocation(self) -> int: ...
    def getTemperature(self) -> android.health.connect.datatypes.units.Temperature: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int, temperature: android.health.connect.datatypes.units.Temperature): ...
        def build(self) -> 'BodyTemperatureRecord': ...
        def clearZoneOffset(self) -> 'BodyTemperatureRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BodyTemperatureRecord.Builder': ...

class BodyWaterMassRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getBodyWaterMass(self) -> android.health.connect.datatypes.units.Mass: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], mass: android.health.connect.datatypes.units.Mass): ...
        def build(self) -> 'BodyWaterMassRecord': ...
        def clearZoneOffset(self) -> 'BodyWaterMassRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BodyWaterMassRecord.Builder': ...

class BoneMassRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getMass(self) -> android.health.connect.datatypes.units.Mass: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], mass: android.health.connect.datatypes.units.Mass): ...
        def build(self) -> 'BoneMassRecord': ...
        def clearZoneOffset(self) -> 'BoneMassRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'BoneMassRecord.Builder': ...

class CervicalMucusRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getAppearance(self) -> int: ...
    def getSensation(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int, int2: int): ...
        def build(self) -> 'CervicalMucusRecord': ...
        def clearZoneOffset(self) -> 'CervicalMucusRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'CervicalMucusRecord.Builder': ...
    class CervicalMucusAppearance:
        APPEARANCE_CREAMY: typing.ClassVar[int] = ...
        APPEARANCE_DRY: typing.ClassVar[int] = ...
        APPEARANCE_EGG_WHITE: typing.ClassVar[int] = ...
        APPEARANCE_STICKY: typing.ClassVar[int] = ...
        APPEARANCE_UNKNOWN: typing.ClassVar[int] = ...
        APPEARANCE_UNUSUAL: typing.ClassVar[int] = ...
        APPEARANCE_WATERY: typing.ClassVar[int] = ...
    class CervicalMucusSensation:
        SENSATION_HEAVY: typing.ClassVar[int] = ...
        SENSATION_LIGHT: typing.ClassVar[int] = ...
        SENSATION_MEDIUM: typing.ClassVar[int] = ...
        SENSATION_UNKNOWN: typing.ClassVar[int] = ...

class CyclingPedalingCadenceRecord(IntervalRecord):
    RPM_AVG: typing.ClassVar[AggregationType] = ...
    RPM_MAX: typing.ClassVar[AggregationType] = ...
    RPM_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSamples(self) -> java.util.List['CyclingPedalingCadenceRecord.CyclingPedalingCadenceRecordSample']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], list: java.util.List['CyclingPedalingCadenceRecord.CyclingPedalingCadenceRecordSample']): ...
        def build(self) -> 'CyclingPedalingCadenceRecord': ...
        def clearEndZoneOffset(self) -> 'CyclingPedalingCadenceRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'CyclingPedalingCadenceRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'CyclingPedalingCadenceRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'CyclingPedalingCadenceRecord.Builder': ...
    class CyclingPedalingCadenceRecordSample:
        def __init__(self, double: float, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getRevolutionsPerMinute(self) -> float: ...
        def getTime(self) -> java.time.Instant: ...
        def hashCode(self) -> int: ...

class DistanceRecord(IntervalRecord):
    DISTANCE_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDistance(self) -> android.health.connect.datatypes.units.Length: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], length: android.health.connect.datatypes.units.Length): ...
        def build(self) -> 'DistanceRecord': ...
        def clearEndZoneOffset(self) -> 'DistanceRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'DistanceRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'DistanceRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'DistanceRecord.Builder': ...

class ElevationGainedRecord(IntervalRecord):
    ELEVATION_GAINED_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getElevation(self) -> android.health.connect.datatypes.units.Length: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], length: android.health.connect.datatypes.units.Length): ...
        def build(self) -> 'ElevationGainedRecord': ...
        def clearEndZoneOffset(self) -> 'ElevationGainedRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'ElevationGainedRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'ElevationGainedRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'ElevationGainedRecord.Builder': ...

class ExerciseSessionRecord(IntervalRecord):
    EXERCISE_DURATION_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExerciseType(self) -> int: ...
    def getLaps(self) -> java.util.List[ExerciseLap]: ...
    def getNotes(self) -> java.lang.CharSequence: ...
    def getPlannedExerciseSessionId(self) -> str: ...
    def getRoute(self) -> ExerciseRoute: ...
    def getSegments(self) -> java.util.List[ExerciseSegment]: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def hasRoute(self) -> bool: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], int: int): ...
        def build(self) -> 'ExerciseSessionRecord': ...
        def clearEndZoneOffset(self) -> 'ExerciseSessionRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'ExerciseSessionRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'ExerciseSessionRecord.Builder': ...
        def setLaps(self, list: java.util.List[ExerciseLap]) -> 'ExerciseSessionRecord.Builder': ...
        def setNotes(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'ExerciseSessionRecord.Builder': ...
        def setPlannedExerciseSessionId(self, string: str) -> 'ExerciseSessionRecord.Builder': ...
        def setRoute(self, exerciseRoute: ExerciseRoute) -> 'ExerciseSessionRecord.Builder': ...
        def setSegments(self, list: java.util.List[ExerciseSegment]) -> 'ExerciseSessionRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'ExerciseSessionRecord.Builder': ...
        def setTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'ExerciseSessionRecord.Builder': ...

class FloorsClimbedRecord(IntervalRecord):
    FLOORS_CLIMBED_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFloors(self) -> float: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], double: float): ...
        def build(self) -> 'FloorsClimbedRecord': ...
        def clearEndZoneOffset(self) -> 'FloorsClimbedRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'FloorsClimbedRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'FloorsClimbedRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'FloorsClimbedRecord.Builder': ...

class HeartRateRecord(IntervalRecord):
    BPM_AVG: typing.ClassVar[AggregationType] = ...
    BPM_MAX: typing.ClassVar[AggregationType] = ...
    BPM_MIN: typing.ClassVar[AggregationType] = ...
    HEART_MEASUREMENTS_COUNT: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSamples(self) -> java.util.List['HeartRateRecord.HeartRateSample']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], list: java.util.List['HeartRateRecord.HeartRateSample']): ...
        def build(self) -> 'HeartRateRecord': ...
        def clearEndZoneOffset(self) -> 'HeartRateRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'HeartRateRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'HeartRateRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'HeartRateRecord.Builder': ...
    class HeartRateSample:
        def __init__(self, long: int, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getBeatsPerMinute(self) -> int: ...
        def getTime(self) -> java.time.Instant: ...
        def hashCode(self) -> int: ...

class HeartRateVariabilityRmssdRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getHeartRateVariabilityMillis(self) -> float: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], double: float): ...
        def build(self) -> 'HeartRateVariabilityRmssdRecord': ...
        def clearZoneOffset(self) -> 'HeartRateVariabilityRmssdRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'HeartRateVariabilityRmssdRecord.Builder': ...

class HeightRecord(InstantRecord):
    HEIGHT_AVG: typing.ClassVar[AggregationType] = ...
    HEIGHT_MAX: typing.ClassVar[AggregationType] = ...
    HEIGHT_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHeight(self) -> android.health.connect.datatypes.units.Length: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], length: android.health.connect.datatypes.units.Length): ...
        def build(self) -> 'HeightRecord': ...
        def clearZoneOffset(self) -> 'HeightRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'HeightRecord.Builder': ...

class HydrationRecord(IntervalRecord):
    VOLUME_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getVolume(self) -> android.health.connect.datatypes.units.Volume: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], volume: android.health.connect.datatypes.units.Volume): ...
        def build(self) -> 'HydrationRecord': ...
        def clearEndZoneOffset(self) -> 'HydrationRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'HydrationRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'HydrationRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'HydrationRecord.Builder': ...

class IntermenstrualBleedingRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def build(self) -> 'IntermenstrualBleedingRecord': ...
        def clearZoneOffset(self) -> 'IntermenstrualBleedingRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'IntermenstrualBleedingRecord.Builder': ...

class LeanBodyMassRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getMass(self) -> android.health.connect.datatypes.units.Mass: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], mass: android.health.connect.datatypes.units.Mass): ...
        def build(self) -> 'LeanBodyMassRecord': ...
        def clearZoneOffset(self) -> 'LeanBodyMassRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'LeanBodyMassRecord.Builder': ...

class MenstruationFlowRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getFlow(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int): ...
        def build(self) -> 'MenstruationFlowRecord': ...
        def clearZoneOffset(self) -> 'MenstruationFlowRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'MenstruationFlowRecord.Builder': ...
    class MenstruationFlowType:
        FLOW_HEAVY: typing.ClassVar[int] = ...
        FLOW_LIGHT: typing.ClassVar[int] = ...
        FLOW_MEDIUM: typing.ClassVar[int] = ...
        FLOW_UNKNOWN: typing.ClassVar[int] = ...

class MenstruationPeriodRecord(IntervalRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]): ...
        def build(self) -> 'MenstruationPeriodRecord': ...
        def clearEndZoneOffset(self) -> 'MenstruationPeriodRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'MenstruationPeriodRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'MenstruationPeriodRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'MenstruationPeriodRecord.Builder': ...

class NutritionRecord(IntervalRecord):
    BIOTIN_TOTAL: typing.ClassVar[AggregationType] = ...
    CAFFEINE_TOTAL: typing.ClassVar[AggregationType] = ...
    CALCIUM_TOTAL: typing.ClassVar[AggregationType] = ...
    CHLORIDE_TOTAL: typing.ClassVar[AggregationType] = ...
    CHOLESTEROL_TOTAL: typing.ClassVar[AggregationType] = ...
    CHROMIUM_TOTAL: typing.ClassVar[AggregationType] = ...
    COPPER_TOTAL: typing.ClassVar[AggregationType] = ...
    DIETARY_FIBER_TOTAL: typing.ClassVar[AggregationType] = ...
    ENERGY_FROM_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    ENERGY_TOTAL: typing.ClassVar[AggregationType] = ...
    FOLATE_TOTAL: typing.ClassVar[AggregationType] = ...
    FOLIC_ACID_TOTAL: typing.ClassVar[AggregationType] = ...
    IODINE_TOTAL: typing.ClassVar[AggregationType] = ...
    IRON_TOTAL: typing.ClassVar[AggregationType] = ...
    MAGNESIUM_TOTAL: typing.ClassVar[AggregationType] = ...
    MANGANESE_TOTAL: typing.ClassVar[AggregationType] = ...
    MOLYBDENUM_TOTAL: typing.ClassVar[AggregationType] = ...
    MONOUNSATURATED_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    NIACIN_TOTAL: typing.ClassVar[AggregationType] = ...
    PANTOTHENIC_ACID_TOTAL: typing.ClassVar[AggregationType] = ...
    PHOSPHORUS_TOTAL: typing.ClassVar[AggregationType] = ...
    POLYUNSATURATED_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    POTASSIUM_TOTAL: typing.ClassVar[AggregationType] = ...
    PROTEIN_TOTAL: typing.ClassVar[AggregationType] = ...
    RIBOFLAVIN_TOTAL: typing.ClassVar[AggregationType] = ...
    SATURATED_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    SELENIUM_TOTAL: typing.ClassVar[AggregationType] = ...
    SODIUM_TOTAL: typing.ClassVar[AggregationType] = ...
    SUGAR_TOTAL: typing.ClassVar[AggregationType] = ...
    THIAMIN_TOTAL: typing.ClassVar[AggregationType] = ...
    TOTAL_CARBOHYDRATE_TOTAL: typing.ClassVar[AggregationType] = ...
    TOTAL_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    TRANS_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    UNSATURATED_FAT_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_A_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_B12_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_B6_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_C_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_D_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_E_TOTAL: typing.ClassVar[AggregationType] = ...
    VITAMIN_K_TOTAL: typing.ClassVar[AggregationType] = ...
    ZINC_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBiotin(self) -> android.health.connect.datatypes.units.Mass: ...
    def getCaffeine(self) -> android.health.connect.datatypes.units.Mass: ...
    def getCalcium(self) -> android.health.connect.datatypes.units.Mass: ...
    def getChloride(self) -> android.health.connect.datatypes.units.Mass: ...
    def getCholesterol(self) -> android.health.connect.datatypes.units.Mass: ...
    def getChromium(self) -> android.health.connect.datatypes.units.Mass: ...
    def getCopper(self) -> android.health.connect.datatypes.units.Mass: ...
    def getDietaryFiber(self) -> android.health.connect.datatypes.units.Mass: ...
    def getEnergy(self) -> android.health.connect.datatypes.units.Energy: ...
    def getEnergyFromFat(self) -> android.health.connect.datatypes.units.Energy: ...
    def getFolate(self) -> android.health.connect.datatypes.units.Mass: ...
    def getFolicAcid(self) -> android.health.connect.datatypes.units.Mass: ...
    def getIodine(self) -> android.health.connect.datatypes.units.Mass: ...
    def getIron(self) -> android.health.connect.datatypes.units.Mass: ...
    def getMagnesium(self) -> android.health.connect.datatypes.units.Mass: ...
    def getManganese(self) -> android.health.connect.datatypes.units.Mass: ...
    def getMealName(self) -> str: ...
    def getMealType(self) -> int: ...
    def getMolybdenum(self) -> android.health.connect.datatypes.units.Mass: ...
    def getMonounsaturatedFat(self) -> android.health.connect.datatypes.units.Mass: ...
    def getNiacin(self) -> android.health.connect.datatypes.units.Mass: ...
    def getPantothenicAcid(self) -> android.health.connect.datatypes.units.Mass: ...
    def getPhosphorus(self) -> android.health.connect.datatypes.units.Mass: ...
    def getPolyunsaturatedFat(self) -> android.health.connect.datatypes.units.Mass: ...
    def getPotassium(self) -> android.health.connect.datatypes.units.Mass: ...
    def getProtein(self) -> android.health.connect.datatypes.units.Mass: ...
    def getRiboflavin(self) -> android.health.connect.datatypes.units.Mass: ...
    def getSaturatedFat(self) -> android.health.connect.datatypes.units.Mass: ...
    def getSelenium(self) -> android.health.connect.datatypes.units.Mass: ...
    def getSodium(self) -> android.health.connect.datatypes.units.Mass: ...
    def getSugar(self) -> android.health.connect.datatypes.units.Mass: ...
    def getThiamin(self) -> android.health.connect.datatypes.units.Mass: ...
    def getTotalCarbohydrate(self) -> android.health.connect.datatypes.units.Mass: ...
    def getTotalFat(self) -> android.health.connect.datatypes.units.Mass: ...
    def getTransFat(self) -> android.health.connect.datatypes.units.Mass: ...
    def getUnsaturatedFat(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminA(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminB12(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminB6(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminC(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminD(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminE(self) -> android.health.connect.datatypes.units.Mass: ...
    def getVitaminK(self) -> android.health.connect.datatypes.units.Mass: ...
    def getZinc(self) -> android.health.connect.datatypes.units.Mass: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]): ...
        def build(self) -> 'NutritionRecord': ...
        def clearEndZoneOffset(self) -> 'NutritionRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'NutritionRecord.Builder': ...
        def setBiotin(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setCaffeine(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setCalcium(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setChloride(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setCholesterol(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setChromium(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setCopper(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setDietaryFiber(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'NutritionRecord.Builder': ...
        def setEnergy(self, energy: android.health.connect.datatypes.units.Energy) -> 'NutritionRecord.Builder': ...
        def setEnergyFromFat(self, energy: android.health.connect.datatypes.units.Energy) -> 'NutritionRecord.Builder': ...
        def setFolate(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setFolicAcid(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setIodine(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setIron(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setMagnesium(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setManganese(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setMealName(self, string: str) -> 'NutritionRecord.Builder': ...
        def setMealType(self, int: int) -> 'NutritionRecord.Builder': ...
        def setMolybdenum(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setMonounsaturatedFat(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setNiacin(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setPantothenicAcid(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setPhosphorus(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setPolyunsaturatedFat(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setPotassium(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setProtein(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setRiboflavin(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setSaturatedFat(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setSelenium(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setSodium(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'NutritionRecord.Builder': ...
        def setSugar(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setThiamin(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setTotalCarbohydrate(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setTotalFat(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setTransFat(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setUnsaturatedFat(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminA(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminB12(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminB6(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminC(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminD(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminE(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setVitaminK(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...
        def setZinc(self, mass: android.health.connect.datatypes.units.Mass) -> 'NutritionRecord.Builder': ...

class OvulationTestRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getResult(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int): ...
        def build(self) -> 'OvulationTestRecord': ...
        def clearZoneOffset(self) -> 'OvulationTestRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'OvulationTestRecord.Builder': ...
    class OvulationTestResult:
        RESULT_HIGH: typing.ClassVar[int] = ...
        RESULT_INCONCLUSIVE: typing.ClassVar[int] = ...
        RESULT_NEGATIVE: typing.ClassVar[int] = ...
        RESULT_POSITIVE: typing.ClassVar[int] = ...

class OxygenSaturationRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getPercentage(self) -> android.health.connect.datatypes.units.Percentage: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], percentage: android.health.connect.datatypes.units.Percentage): ...
        def build(self) -> 'OxygenSaturationRecord': ...
        def clearZoneOffset(self) -> 'OxygenSaturationRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'OxygenSaturationRecord.Builder': ...

class PlannedExerciseSessionRecord(IntervalRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getBlocks(self) -> java.util.List[PlannedExerciseBlock]: ...
    def getCompletedExerciseSessionId(self) -> str: ...
    def getDuration(self) -> java.time.Duration: ...
    def getExerciseType(self) -> int: ...
    def getNotes(self) -> java.lang.CharSequence: ...
    def getStartDate(self) -> java.time.LocalDate: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def hasExplicitTime(self) -> bool: ...
    def hashCode(self) -> int: ...
    class Builder:
        @typing.overload
        def __init__(self, metadata: Metadata, int: int, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]): ...
        @typing.overload
        def __init__(self, metadata: Metadata, int: int, localDate: java.time.LocalDate, duration: java.time.Duration): ...
        def addBlock(self, plannedExerciseBlock: PlannedExerciseBlock) -> 'PlannedExerciseSessionRecord.Builder': ...
        def build(self) -> 'PlannedExerciseSessionRecord': ...
        def clearBlocks(self) -> 'PlannedExerciseSessionRecord.Builder': ...
        def clearEndZoneOffset(self) -> 'PlannedExerciseSessionRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setBlocks(self, list: java.util.List[PlannedExerciseBlock]) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setEndTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setExerciseType(self, int: int) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setMetadata(self, metadata: Metadata) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setNotes(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setStartTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'PlannedExerciseSessionRecord.Builder': ...
        def setTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PlannedExerciseSessionRecord.Builder': ...

class PowerRecord(IntervalRecord):
    POWER_AVG: typing.ClassVar[AggregationType] = ...
    POWER_MAX: typing.ClassVar[AggregationType] = ...
    POWER_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSamples(self) -> java.util.List['PowerRecord.PowerRecordSample']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], list: java.util.List['PowerRecord.PowerRecordSample']): ...
        def build(self) -> 'PowerRecord': ...
        def clearEndZoneOffset(self) -> 'PowerRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'PowerRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'PowerRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'PowerRecord.Builder': ...
    class PowerRecordSample:
        def __init__(self, power: android.health.connect.datatypes.units.Power, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getPower(self) -> android.health.connect.datatypes.units.Power: ...
        def getTime(self) -> java.time.Instant: ...
        def hashCode(self) -> int: ...

class RespiratoryRateRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getRate(self) -> float: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], double: float): ...
        def build(self) -> 'RespiratoryRateRecord': ...
        def clearZoneOffset(self) -> 'RespiratoryRateRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'RespiratoryRateRecord.Builder': ...

class RestingHeartRateRecord(InstantRecord):
    BPM_AVG: typing.ClassVar[AggregationType] = ...
    BPM_MAX: typing.ClassVar[AggregationType] = ...
    BPM_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBeatsPerMinute(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], long: int): ...
        def build(self) -> 'RestingHeartRateRecord': ...
        def clearZoneOffset(self) -> 'RestingHeartRateRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'RestingHeartRateRecord.Builder': ...

class SexualActivityRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getProtectionUsed(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int): ...
        def build(self) -> 'SexualActivityRecord': ...
        def clearZoneOffset(self) -> 'SexualActivityRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SexualActivityRecord.Builder': ...
    class SexualActivityProtectionUsed:
        PROTECTION_USED_PROTECTED: typing.ClassVar[int] = ...
        PROTECTION_USED_UNKNOWN: typing.ClassVar[int] = ...
        PROTECTION_USED_UNPROTECTED: typing.ClassVar[int] = ...

class SkinTemperatureRecord(IntervalRecord):
    MEASUREMENT_LOCATION_FINGER: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_TOE: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_UNKNOWN: typing.ClassVar[int] = ...
    MEASUREMENT_LOCATION_WRIST: typing.ClassVar[int] = ...
    SKIN_TEMPERATURE_DELTA_AVG: typing.ClassVar[AggregationType] = ...
    SKIN_TEMPERATURE_DELTA_MAX: typing.ClassVar[AggregationType] = ...
    SKIN_TEMPERATURE_DELTA_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBaseline(self) -> android.health.connect.datatypes.units.Temperature: ...
    def getDeltas(self) -> java.util.List['SkinTemperatureRecord.Delta']: ...
    def getMeasurementLocation(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]): ...
        def build(self) -> 'SkinTemperatureRecord': ...
        def clearEndZoneOffset(self) -> 'SkinTemperatureRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'SkinTemperatureRecord.Builder': ...
        def setBaseline(self, temperature: android.health.connect.datatypes.units.Temperature) -> 'SkinTemperatureRecord.Builder': ...
        def setDeltas(self, list: java.util.List['SkinTemperatureRecord.Delta']) -> 'SkinTemperatureRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SkinTemperatureRecord.Builder': ...
        def setMeasurementLocation(self, int: int) -> 'SkinTemperatureRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SkinTemperatureRecord.Builder': ...
    class Delta:
        def __init__(self, temperatureDelta: android.health.connect.datatypes.units.TemperatureDelta, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDelta(self) -> android.health.connect.datatypes.units.TemperatureDelta: ...
        def getTime(self) -> java.time.Instant: ...
        def hashCode(self) -> int: ...

class SleepSessionRecord(IntervalRecord):
    SLEEP_DURATION_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getNotes(self) -> java.lang.CharSequence: ...
    def getStages(self) -> java.util.List['SleepSessionRecord.Stage']: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]): ...
        def build(self) -> 'SleepSessionRecord': ...
        def clearEndZoneOffset(self) -> 'SleepSessionRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'SleepSessionRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SleepSessionRecord.Builder': ...
        def setNotes(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SleepSessionRecord.Builder': ...
        def setStages(self, list: java.util.List['SleepSessionRecord.Stage']) -> 'SleepSessionRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SleepSessionRecord.Builder': ...
        def setTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SleepSessionRecord.Builder': ...
    class Stage:
        def __init__(self, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], int: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getEndTime(self) -> java.time.Instant: ...
        def getStartTime(self) -> java.time.Instant: ...
        def getType(self) -> int: ...
        def hashCode(self) -> int: ...
    class StageType:
        STAGE_TYPE_AWAKE: typing.ClassVar[int] = ...
        STAGE_TYPE_AWAKE_IN_BED: typing.ClassVar[int] = ...
        STAGE_TYPE_AWAKE_OUT_OF_BED: typing.ClassVar[int] = ...
        STAGE_TYPE_SLEEPING: typing.ClassVar[int] = ...
        STAGE_TYPE_SLEEPING_DEEP: typing.ClassVar[int] = ...
        STAGE_TYPE_SLEEPING_LIGHT: typing.ClassVar[int] = ...
        STAGE_TYPE_SLEEPING_REM: typing.ClassVar[int] = ...
        STAGE_TYPE_UNKNOWN: typing.ClassVar[int] = ...

class SpeedRecord(IntervalRecord):
    SPEED_AVG: typing.ClassVar[AggregationType] = ...
    SPEED_MAX: typing.ClassVar[AggregationType] = ...
    SPEED_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSamples(self) -> java.util.List['SpeedRecord.SpeedRecordSample']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], list: java.util.List['SpeedRecord.SpeedRecordSample']): ...
        def build(self) -> 'SpeedRecord': ...
        def clearEndZoneOffset(self) -> 'SpeedRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'SpeedRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SpeedRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'SpeedRecord.Builder': ...
    class SpeedRecordSample:
        def __init__(self, velocity: android.health.connect.datatypes.units.Velocity, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getSpeed(self) -> android.health.connect.datatypes.units.Velocity: ...
        def getTime(self) -> java.time.Instant: ...
        def hashCode(self) -> int: ...

class StepsCadenceRecord(IntervalRecord):
    STEPS_CADENCE_RATE_AVG: typing.ClassVar[AggregationType] = ...
    STEPS_CADENCE_RATE_MAX: typing.ClassVar[AggregationType] = ...
    STEPS_CADENCE_RATE_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSamples(self) -> java.util.List['StepsCadenceRecord.StepsCadenceRecordSample']: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], list: java.util.List['StepsCadenceRecord.StepsCadenceRecordSample']): ...
        def build(self) -> 'StepsCadenceRecord': ...
        def clearEndZoneOffset(self) -> 'StepsCadenceRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'StepsCadenceRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'StepsCadenceRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'StepsCadenceRecord.Builder': ...
    class StepsCadenceRecordSample:
        def __init__(self, double: float, instant: typing.Union[java.time.Instant, datetime.datetime]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getRate(self) -> float: ...
        def getTime(self) -> java.time.Instant: ...
        def hashCode(self) -> int: ...

class StepsRecord(IntervalRecord):
    STEPS_COUNT_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCount(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], long: int): ...
        def build(self) -> 'StepsRecord': ...
        def clearEndZoneOffset(self) -> 'StepsRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'StepsRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'StepsRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'StepsRecord.Builder': ...

class TotalCaloriesBurnedRecord(IntervalRecord):
    ENERGY_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getEnergy(self) -> android.health.connect.datatypes.units.Energy: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], energy: android.health.connect.datatypes.units.Energy): ...
        def build(self) -> 'TotalCaloriesBurnedRecord': ...
        def clearEndZoneOffset(self) -> 'TotalCaloriesBurnedRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'TotalCaloriesBurnedRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'TotalCaloriesBurnedRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'TotalCaloriesBurnedRecord.Builder': ...

class Vo2MaxRecord(InstantRecord):
    def equals(self, object: typing.Any) -> bool: ...
    def getMeasurementMethod(self) -> int: ...
    def getVo2MillilitersPerMinuteKilogram(self) -> float: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], int: int, double: float): ...
        def build(self) -> 'Vo2MaxRecord': ...
        def clearZoneOffset(self) -> 'Vo2MaxRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'Vo2MaxRecord.Builder': ...
    class Vo2MaxMeasurementMethod:
        MEASUREMENT_METHOD_COOPER_TEST: typing.ClassVar[int] = ...
        MEASUREMENT_METHOD_HEART_RATE_RATIO: typing.ClassVar[int] = ...
        MEASUREMENT_METHOD_METABOLIC_CART: typing.ClassVar[int] = ...
        MEASUREMENT_METHOD_MULTISTAGE_FITNESS_TEST: typing.ClassVar[int] = ...
        MEASUREMENT_METHOD_OTHER: typing.ClassVar[int] = ...
        MEASUREMENT_METHOD_ROCKPORT_FITNESS_TEST: typing.ClassVar[int] = ...

class WeightRecord(InstantRecord):
    WEIGHT_AVG: typing.ClassVar[AggregationType] = ...
    WEIGHT_MAX: typing.ClassVar[AggregationType] = ...
    WEIGHT_MIN: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getWeight(self) -> android.health.connect.datatypes.units.Mass: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], mass: android.health.connect.datatypes.units.Mass): ...
        def build(self) -> 'WeightRecord': ...
        def clearZoneOffset(self) -> 'WeightRecord.Builder': ...
        def setZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'WeightRecord.Builder': ...

class WheelchairPushesRecord(IntervalRecord):
    WHEEL_CHAIR_PUSHES_COUNT_TOTAL: typing.ClassVar[AggregationType] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCount(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, metadata: Metadata, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime], long: int): ...
        def build(self) -> 'WheelchairPushesRecord': ...
        def clearEndZoneOffset(self) -> 'WheelchairPushesRecord.Builder': ...
        def clearStartZoneOffset(self) -> 'WheelchairPushesRecord.Builder': ...
        def setEndZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'WheelchairPushesRecord.Builder': ...
        def setStartZoneOffset(self, zoneOffset: java.time.ZoneOffset) -> 'WheelchairPushesRecord.Builder': ...

class ExerciseCompletionGoal:
    class ActiveCaloriesBurnedGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, energy: android.health.connect.datatypes.units.Energy): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getActiveCalories(self) -> android.health.connect.datatypes.units.Energy: ...
        def hashCode(self) -> int: ...
    class DistanceGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, length: android.health.connect.datatypes.units.Length): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDistance(self) -> android.health.connect.datatypes.units.Length: ...
        def hashCode(self) -> int: ...
    class DistanceWithVariableRestGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, length: android.health.connect.datatypes.units.Length, duration: java.time.Duration): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDistance(self) -> android.health.connect.datatypes.units.Length: ...
        def getDuration(self) -> java.time.Duration: ...
        def hashCode(self) -> int: ...
    class DurationGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, duration: java.time.Duration): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDuration(self) -> java.time.Duration: ...
        def hashCode(self) -> int: ...
    class RepetitionsGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, int: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getRepetitions(self) -> int: ...
        def hashCode(self) -> int: ...
    class StepsGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, int: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getSteps(self) -> int: ...
        def hashCode(self) -> int: ...
    class TotalCaloriesBurnedGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        def __init__(self, energy: android.health.connect.datatypes.units.Energy): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getTotalCalories(self) -> android.health.connect.datatypes.units.Energy: ...
        def hashCode(self) -> int: ...
    class UnknownGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        INSTANCE: typing.ClassVar['ExerciseCompletionGoal.UnknownGoal'] = ...
    class UnspecifiedGoal(android.health.connect.datatypes.ExerciseCompletionGoal):
        INSTANCE: typing.ClassVar['ExerciseCompletionGoal.UnspecifiedGoal'] = ...

class ExercisePerformanceGoal:
    class AmrapGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        INSTANCE: typing.ClassVar['ExercisePerformanceGoal.AmrapGoal'] = ...
    class CadenceGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        def __init__(self, double: float, double2: float): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getMaxRpm(self) -> float: ...
        def getMinRpm(self) -> float: ...
        def hashCode(self) -> int: ...
    class HeartRateGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        def __init__(self, int: int, int2: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getMaxBpm(self) -> int: ...
        def getMinBpm(self) -> int: ...
        def hashCode(self) -> int: ...
    class PowerGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        def __init__(self, power: android.health.connect.datatypes.units.Power, power2: android.health.connect.datatypes.units.Power): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getMaxPower(self) -> android.health.connect.datatypes.units.Power: ...
        def getMinPower(self) -> android.health.connect.datatypes.units.Power: ...
        def hashCode(self) -> int: ...
    class RateOfPerceivedExertionGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        def __init__(self, int: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getRpe(self) -> int: ...
        def hashCode(self) -> int: ...
    class SpeedGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        def __init__(self, velocity: android.health.connect.datatypes.units.Velocity, velocity2: android.health.connect.datatypes.units.Velocity): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getMaxSpeed(self) -> android.health.connect.datatypes.units.Velocity: ...
        def getMinSpeed(self) -> android.health.connect.datatypes.units.Velocity: ...
        def hashCode(self) -> int: ...
    class UnknownGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        INSTANCE: typing.ClassVar['ExercisePerformanceGoal.UnknownGoal'] = ...
    class WeightGoal(android.health.connect.datatypes.ExercisePerformanceGoal):
        def __init__(self, mass: android.health.connect.datatypes.units.Mass): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getMass(self) -> android.health.connect.datatypes.units.Mass: ...
        def hashCode(self) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.health.connect.datatypes")``.

    ActiveCaloriesBurnedRecord: typing.Type[ActiveCaloriesBurnedRecord]
    AggregationType: typing.Type[AggregationType]
    AppInfo: typing.Type[AppInfo]
    BasalBodyTemperatureRecord: typing.Type[BasalBodyTemperatureRecord]
    BasalMetabolicRateRecord: typing.Type[BasalMetabolicRateRecord]
    BloodGlucoseRecord: typing.Type[BloodGlucoseRecord]
    BloodPressureRecord: typing.Type[BloodPressureRecord]
    BodyFatRecord: typing.Type[BodyFatRecord]
    BodyTemperatureMeasurementLocation: typing.Type[BodyTemperatureMeasurementLocation]
    BodyTemperatureRecord: typing.Type[BodyTemperatureRecord]
    BodyWaterMassRecord: typing.Type[BodyWaterMassRecord]
    BoneMassRecord: typing.Type[BoneMassRecord]
    CervicalMucusRecord: typing.Type[CervicalMucusRecord]
    CyclingPedalingCadenceRecord: typing.Type[CyclingPedalingCadenceRecord]
    DataOrigin: typing.Type[DataOrigin]
    Device: typing.Type[Device]
    DistanceRecord: typing.Type[DistanceRecord]
    ElevationGainedRecord: typing.Type[ElevationGainedRecord]
    ExerciseCompletionGoal: typing.Type[ExerciseCompletionGoal]
    ExerciseLap: typing.Type[ExerciseLap]
    ExercisePerformanceGoal: typing.Type[ExercisePerformanceGoal]
    ExerciseRoute: typing.Type[ExerciseRoute]
    ExerciseSegment: typing.Type[ExerciseSegment]
    ExerciseSegmentType: typing.Type[ExerciseSegmentType]
    ExerciseSessionRecord: typing.Type[ExerciseSessionRecord]
    ExerciseSessionType: typing.Type[ExerciseSessionType]
    FloorsClimbedRecord: typing.Type[FloorsClimbedRecord]
    HeartRateRecord: typing.Type[HeartRateRecord]
    HeartRateVariabilityRmssdRecord: typing.Type[HeartRateVariabilityRmssdRecord]
    HeightRecord: typing.Type[HeightRecord]
    HydrationRecord: typing.Type[HydrationRecord]
    InstantRecord: typing.Type[InstantRecord]
    IntermenstrualBleedingRecord: typing.Type[IntermenstrualBleedingRecord]
    IntervalRecord: typing.Type[IntervalRecord]
    LeanBodyMassRecord: typing.Type[LeanBodyMassRecord]
    MealType: typing.Type[MealType]
    MenstruationFlowRecord: typing.Type[MenstruationFlowRecord]
    MenstruationPeriodRecord: typing.Type[MenstruationPeriodRecord]
    Metadata: typing.Type[Metadata]
    NutritionRecord: typing.Type[NutritionRecord]
    OvulationTestRecord: typing.Type[OvulationTestRecord]
    OxygenSaturationRecord: typing.Type[OxygenSaturationRecord]
    PlannedExerciseBlock: typing.Type[PlannedExerciseBlock]
    PlannedExerciseSessionRecord: typing.Type[PlannedExerciseSessionRecord]
    PlannedExerciseStep: typing.Type[PlannedExerciseStep]
    PowerRecord: typing.Type[PowerRecord]
    Record: typing.Type[Record]
    RespiratoryRateRecord: typing.Type[RespiratoryRateRecord]
    RestingHeartRateRecord: typing.Type[RestingHeartRateRecord]
    SexualActivityRecord: typing.Type[SexualActivityRecord]
    SkinTemperatureRecord: typing.Type[SkinTemperatureRecord]
    SleepSessionRecord: typing.Type[SleepSessionRecord]
    SpeedRecord: typing.Type[SpeedRecord]
    StepsCadenceRecord: typing.Type[StepsCadenceRecord]
    StepsRecord: typing.Type[StepsRecord]
    TotalCaloriesBurnedRecord: typing.Type[TotalCaloriesBurnedRecord]
    Vo2MaxRecord: typing.Type[Vo2MaxRecord]
    WeightRecord: typing.Type[WeightRecord]
    WheelchairPushesRecord: typing.Type[WheelchairPushesRecord]
    units: android.health.connect.datatypes.units.__module_protocol__
