
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.app
import android.content
import android.net.eap
import android.net.http
import android.net.ipsec
import android.net.ipsec.ike
import android.net.nsd
import android.net.rtp
import android.net.sip
import android.net.ssl
import android.net.vcn
import android.net.wifi
import android.os
import android.util
import java.io
import java.lang
import java.net
import java.security
import java.security.cert
import java.util
import java.util.concurrent
import javax.net
import javax.net.ssl
import jpype
import jpype.protocol
import typing



class CaptivePortal(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def ignoreNetwork(self) -> None: ...
    def reportCaptivePortalDismissed(self) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ConnectivityDiagnosticsManager:
    def registerConnectivityDiagnosticsCallback(self, networkRequest: 'NetworkRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], connectivityDiagnosticsCallback: 'ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback') -> None: ...
    def unregisterConnectivityDiagnosticsCallback(self, connectivityDiagnosticsCallback: 'ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback') -> None: ...
    class ConnectivityDiagnosticsCallback:
        def __init__(self): ...
        def onConnectivityReportAvailable(self, connectivityReport: 'ConnectivityDiagnosticsManager.ConnectivityReport') -> None: ...
        def onDataStallSuspected(self, dataStallReport: 'ConnectivityDiagnosticsManager.DataStallReport') -> None: ...
        def onNetworkConnectivityReported(self, network: 'Network', boolean: bool) -> None: ...
    class ConnectivityReport(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        KEY_NETWORK_PROBES_ATTEMPTED_BITMASK: typing.ClassVar[str] = ...
        KEY_NETWORK_PROBES_SUCCEEDED_BITMASK: typing.ClassVar[str] = ...
        KEY_NETWORK_VALIDATION_RESULT: typing.ClassVar[str] = ...
        NETWORK_PROBE_DNS: typing.ClassVar[int] = ...
        NETWORK_PROBE_FALLBACK: typing.ClassVar[int] = ...
        NETWORK_PROBE_HTTP: typing.ClassVar[int] = ...
        NETWORK_PROBE_HTTPS: typing.ClassVar[int] = ...
        NETWORK_PROBE_PRIVATE_DNS: typing.ClassVar[int] = ...
        NETWORK_VALIDATION_RESULT_INVALID: typing.ClassVar[int] = ...
        NETWORK_VALIDATION_RESULT_PARTIALLY_VALID: typing.ClassVar[int] = ...
        NETWORK_VALIDATION_RESULT_SKIPPED: typing.ClassVar[int] = ...
        NETWORK_VALIDATION_RESULT_VALID: typing.ClassVar[int] = ...
        def __init__(self, network: 'Network', long: int, linkProperties: 'LinkProperties', networkCapabilities: 'NetworkCapabilities', persistableBundle: android.os.PersistableBundle): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getAdditionalInfo(self) -> android.os.PersistableBundle: ...
        def getLinkProperties(self) -> 'LinkProperties': ...
        def getNetwork(self) -> 'Network': ...
        def getNetworkCapabilities(self) -> 'NetworkCapabilities': ...
        def getReportTimestamp(self) -> int: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class DataStallReport(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        DETECTION_METHOD_DNS_EVENTS: typing.ClassVar[int] = ...
        DETECTION_METHOD_TCP_METRICS: typing.ClassVar[int] = ...
        KEY_DNS_CONSECUTIVE_TIMEOUTS: typing.ClassVar[str] = ...
        KEY_TCP_METRICS_COLLECTION_PERIOD_MILLIS: typing.ClassVar[str] = ...
        KEY_TCP_PACKET_FAIL_RATE: typing.ClassVar[str] = ...
        def __init__(self, network: 'Network', long: int, int: int, linkProperties: 'LinkProperties', networkCapabilities: 'NetworkCapabilities', persistableBundle: android.os.PersistableBundle): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDetectionMethod(self) -> int: ...
        def getLinkProperties(self) -> 'LinkProperties': ...
        def getNetwork(self) -> 'Network': ...
        def getNetworkCapabilities(self) -> 'NetworkCapabilities': ...
        def getReportTimestamp(self) -> int: ...
        def getStallDetails(self) -> android.os.PersistableBundle: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ConnectivityManager:
    ACTION_BACKGROUND_DATA_SETTING_CHANGED: typing.ClassVar[str] = ...
    ACTION_CAPTIVE_PORTAL_SIGN_IN: typing.ClassVar[str] = ...
    ACTION_RESTRICT_BACKGROUND_CHANGED: typing.ClassVar[str] = ...
    CONNECTIVITY_ACTION: typing.ClassVar[str] = ...
    DEFAULT_NETWORK_PREFERENCE: typing.ClassVar[int] = ...
    EXTRA_CAPTIVE_PORTAL: typing.ClassVar[str] = ...
    EXTRA_CAPTIVE_PORTAL_URL: typing.ClassVar[str] = ...
    EXTRA_EXTRA_INFO: typing.ClassVar[str] = ...
    EXTRA_IS_FAILOVER: typing.ClassVar[str] = ...
    EXTRA_NETWORK: typing.ClassVar[str] = ...
    EXTRA_NETWORK_INFO: typing.ClassVar[str] = ...
    EXTRA_NETWORK_REQUEST: typing.ClassVar[str] = ...
    EXTRA_NETWORK_TYPE: typing.ClassVar[str] = ...
    EXTRA_NO_CONNECTIVITY: typing.ClassVar[str] = ...
    EXTRA_OTHER_NETWORK_INFO: typing.ClassVar[str] = ...
    EXTRA_REASON: typing.ClassVar[str] = ...
    MULTIPATH_PREFERENCE_HANDOVER: typing.ClassVar[int] = ...
    MULTIPATH_PREFERENCE_PERFORMANCE: typing.ClassVar[int] = ...
    MULTIPATH_PREFERENCE_RELIABILITY: typing.ClassVar[int] = ...
    RESTRICT_BACKGROUND_STATUS_DISABLED: typing.ClassVar[int] = ...
    RESTRICT_BACKGROUND_STATUS_ENABLED: typing.ClassVar[int] = ...
    RESTRICT_BACKGROUND_STATUS_WHITELISTED: typing.ClassVar[int] = ...
    TYPE_BLUETOOTH: typing.ClassVar[int] = ...
    TYPE_DUMMY: typing.ClassVar[int] = ...
    TYPE_ETHERNET: typing.ClassVar[int] = ...
    TYPE_MOBILE: typing.ClassVar[int] = ...
    TYPE_MOBILE_DUN: typing.ClassVar[int] = ...
    TYPE_MOBILE_HIPRI: typing.ClassVar[int] = ...
    TYPE_MOBILE_MMS: typing.ClassVar[int] = ...
    TYPE_MOBILE_SUPL: typing.ClassVar[int] = ...
    TYPE_VPN: typing.ClassVar[int] = ...
    TYPE_WIFI: typing.ClassVar[int] = ...
    TYPE_WIMAX: typing.ClassVar[int] = ...
    def addDefaultNetworkActiveListener(self, onNetworkActiveListener: typing.Union['ConnectivityManager.OnNetworkActiveListener', typing.Callable]) -> None: ...
    def bindProcessToNetwork(self, network: 'Network') -> bool: ...
    def createSocketKeepalive(self, network: 'Network', udpEncapsulationSocket: 'IpSecManager.UdpEncapsulationSocket', inetAddress: java.net.InetAddress, inetAddress2: java.net.InetAddress, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: 'SocketKeepalive.Callback') -> 'SocketKeepalive': ...
    def getActiveNetwork(self) -> 'Network': ...
    def getActiveNetworkInfo(self) -> 'NetworkInfo': ...
    def getAllNetworkInfo(self) -> typing.MutableSequence['NetworkInfo']: ...
    def getAllNetworks(self) -> typing.MutableSequence['Network']: ...
    def getBackgroundDataSetting(self) -> bool: ...
    def getBoundNetworkForProcess(self) -> 'Network': ...
    def getConnectionOwnerUid(self, int: int, inetSocketAddress: java.net.InetSocketAddress, inetSocketAddress2: java.net.InetSocketAddress) -> int: ...
    def getDefaultProxy(self) -> 'ProxyInfo': ...
    def getLinkProperties(self, network: 'Network') -> 'LinkProperties': ...
    def getMultipathPreference(self, network: 'Network') -> int: ...
    def getNetworkCapabilities(self, network: 'Network') -> 'NetworkCapabilities': ...
    @typing.overload
    def getNetworkInfo(self, network: 'Network') -> 'NetworkInfo': ...
    @typing.overload
    def getNetworkInfo(self, int: int) -> 'NetworkInfo': ...
    def getNetworkPreference(self) -> int: ...
    def getNetworkWatchlistConfigHash(self) -> typing.MutableSequence[int]: ...
    @staticmethod
    def getProcessDefaultNetwork() -> 'Network': ...
    def getRestrictBackgroundStatus(self) -> int: ...
    def isActiveNetworkMetered(self) -> bool: ...
    def isDefaultNetworkActive(self) -> bool: ...
    @staticmethod
    def isNetworkTypeValid(int: int) -> bool: ...
    def registerBestMatchingNetworkCallback(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def registerDefaultNetworkCallback(self, networkCallback: 'ConnectivityManager.NetworkCallback') -> None: ...
    @typing.overload
    def registerDefaultNetworkCallback(self, networkCallback: 'ConnectivityManager.NetworkCallback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def registerNetworkCallback(self, networkRequest: 'NetworkRequest', pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def registerNetworkCallback(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback') -> None: ...
    @typing.overload
    def registerNetworkCallback(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback', handler: android.os.Handler) -> None: ...
    def releaseNetworkRequest(self, pendingIntent: android.app.PendingIntent) -> None: ...
    def removeDefaultNetworkActiveListener(self, onNetworkActiveListener: typing.Union['ConnectivityManager.OnNetworkActiveListener', typing.Callable]) -> None: ...
    def reportBadNetwork(self, network: 'Network') -> None: ...
    def reportNetworkConnectivity(self, network: 'Network', boolean: bool) -> None: ...
    def requestBandwidthUpdate(self, network: 'Network') -> bool: ...
    @typing.overload
    def requestNetwork(self, networkRequest: 'NetworkRequest', pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestNetwork(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback') -> None: ...
    @typing.overload
    def requestNetwork(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def requestNetwork(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback', handler: android.os.Handler, int: int) -> None: ...
    @typing.overload
    def requestNetwork(self, networkRequest: 'NetworkRequest', networkCallback: 'ConnectivityManager.NetworkCallback', int: int) -> None: ...
    def setNetworkPreference(self, int: int) -> None: ...
    @staticmethod
    def setProcessDefaultNetwork(network: 'Network') -> bool: ...
    @typing.overload
    def unregisterNetworkCallback(self, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def unregisterNetworkCallback(self, networkCallback: 'ConnectivityManager.NetworkCallback') -> None: ...
    class NetworkCallback:
        FLAG_INCLUDE_LOCATION_INFO: typing.ClassVar[int] = ...
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, int: int): ...
        def onAvailable(self, network: 'Network') -> None: ...
        def onBlockedStatusChanged(self, network: 'Network', boolean: bool) -> None: ...
        def onCapabilitiesChanged(self, network: 'Network', networkCapabilities: 'NetworkCapabilities') -> None: ...
        def onLinkPropertiesChanged(self, network: 'Network', linkProperties: 'LinkProperties') -> None: ...
        def onLosing(self, network: 'Network', int: int) -> None: ...
        def onLost(self, network: 'Network') -> None: ...
        def onUnavailable(self) -> None: ...
    class OnNetworkActiveListener:
        def onNetworkActive(self) -> None: ...

class Credentials:
    def __init__(self, int: int, int2: int, int3: int): ...
    def getGid(self) -> int: ...
    def getPid(self) -> int: ...
    def getUid(self) -> int: ...

class DhcpInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    dns1: int = ...
    dns2: int = ...
    gateway: int = ...
    ipAddress: int = ...
    leaseDuration: int = ...
    netmask: int = ...
    serverAddress: int = ...
    def __init__(self): ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

_DnsResolver__Callback__T = typing.TypeVar('_DnsResolver__Callback__T')  # <T>
class DnsResolver:
    CLASS_IN: typing.ClassVar[int] = ...
    ERROR_PARSE: typing.ClassVar[int] = ...
    ERROR_SYSTEM: typing.ClassVar[int] = ...
    FLAG_EMPTY: typing.ClassVar[int] = ...
    FLAG_NO_CACHE_LOOKUP: typing.ClassVar[int] = ...
    FLAG_NO_CACHE_STORE: typing.ClassVar[int] = ...
    FLAG_NO_RETRY: typing.ClassVar[int] = ...
    TYPE_A: typing.ClassVar[int] = ...
    TYPE_AAAA: typing.ClassVar[int] = ...
    @staticmethod
    def getInstance() -> 'DnsResolver': ...
    @typing.overload
    def query(self, network: 'Network', string: str, int: int, int2: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], cancellationSignal: android.os.CancellationSignal, callback: 'DnsResolver.Callback'[java.util.List[java.net.InetAddress]]) -> None: ...
    @typing.overload
    def query(self, network: 'Network', string: str, int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], cancellationSignal: android.os.CancellationSignal, callback: 'DnsResolver.Callback'[java.util.List[java.net.InetAddress]]) -> None: ...
    @typing.overload
    def rawQuery(self, network: 'Network', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], cancellationSignal: android.os.CancellationSignal, callback: 'DnsResolver.Callback'[typing.MutableSequence[int]]) -> None: ...
    @typing.overload
    def rawQuery(self, network: 'Network', string: str, int: int, int2: int, int3: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], cancellationSignal: android.os.CancellationSignal, callback: 'DnsResolver.Callback'[typing.MutableSequence[int]]) -> None: ...
    class Callback(typing.Generic[_DnsResolver__Callback__T]):
        def onAnswer(self, t: _DnsResolver__Callback__T, int: int) -> None: ...
        def onError(self, dnsException: 'DnsResolver.DnsException') -> None: ...
    class DnsException(java.lang.Exception):
        code: int = ...
        def __init__(self, int: int, throwable: java.lang.Throwable): ...

class InetAddresses:
    @staticmethod
    def isNumericAddress(string: str) -> bool: ...
    @staticmethod
    def parseNumericAddress(string: str) -> java.net.InetAddress: ...

class IpConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHttpProxy(self) -> 'ProxyInfo': ...
    def getStaticIpConfiguration(self) -> 'StaticIpConfiguration': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'IpConfiguration': ...
        def setHttpProxy(self, proxyInfo: 'ProxyInfo') -> 'IpConfiguration.Builder': ...
        def setStaticIpConfiguration(self, staticIpConfiguration: 'StaticIpConfiguration') -> 'IpConfiguration.Builder': ...

class IpPrefix(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, inetAddress: java.net.InetAddress, int: int): ...
    def contains(self, inetAddress: java.net.InetAddress) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAddress(self) -> java.net.InetAddress: ...
    def getPrefixLength(self) -> int: ...
    def getRawAddress(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class IpSecAlgorithm(android.os.Parcelable):
    AUTH_AES_CMAC: typing.ClassVar[str] = ...
    AUTH_AES_XCBC: typing.ClassVar[str] = ...
    AUTH_CRYPT_AES_GCM: typing.ClassVar[str] = ...
    AUTH_CRYPT_CHACHA20_POLY1305: typing.ClassVar[str] = ...
    AUTH_HMAC_MD5: typing.ClassVar[str] = ...
    AUTH_HMAC_SHA1: typing.ClassVar[str] = ...
    AUTH_HMAC_SHA256: typing.ClassVar[str] = ...
    AUTH_HMAC_SHA384: typing.ClassVar[str] = ...
    AUTH_HMAC_SHA512: typing.ClassVar[str] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    CRYPT_AES_CBC: typing.ClassVar[str] = ...
    CRYPT_AES_CTR: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    @typing.overload
    def __init__(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int): ...
    def describeContents(self) -> int: ...
    def getKey(self) -> typing.MutableSequence[int]: ...
    def getName(self) -> str: ...
    @staticmethod
    def getSupportedAlgorithms() -> java.util.Set[str]: ...
    def getTruncationLengthBits(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class IpSecManager:
    DIRECTION_IN: typing.ClassVar[int] = ...
    DIRECTION_OUT: typing.ClassVar[int] = ...
    @typing.overload
    def allocateSecurityParameterIndex(self, inetAddress: java.net.InetAddress) -> 'IpSecManager.SecurityParameterIndex': ...
    @typing.overload
    def allocateSecurityParameterIndex(self, inetAddress: java.net.InetAddress, int: int) -> 'IpSecManager.SecurityParameterIndex': ...
    @typing.overload
    def applyTransportModeTransform(self, fileDescriptor: java.io.FileDescriptor, int: int, ipSecTransform: 'IpSecTransform') -> None: ...
    @typing.overload
    def applyTransportModeTransform(self, datagramSocket: java.net.DatagramSocket, int: int, ipSecTransform: 'IpSecTransform') -> None: ...
    @typing.overload
    def applyTransportModeTransform(self, socket: java.net.Socket, int: int, ipSecTransform: 'IpSecTransform') -> None: ...
    @typing.overload
    def openUdpEncapsulationSocket(self) -> 'IpSecManager.UdpEncapsulationSocket': ...
    @typing.overload
    def openUdpEncapsulationSocket(self, int: int) -> 'IpSecManager.UdpEncapsulationSocket': ...
    @typing.overload
    def removeTransportModeTransforms(self, fileDescriptor: java.io.FileDescriptor) -> None: ...
    @typing.overload
    def removeTransportModeTransforms(self, datagramSocket: java.net.DatagramSocket) -> None: ...
    @typing.overload
    def removeTransportModeTransforms(self, socket: java.net.Socket) -> None: ...
    class ResourceUnavailableException(android.util.AndroidException): ...
    class SecurityParameterIndex(java.lang.AutoCloseable):
        def close(self) -> None: ...
        def getSpi(self) -> int: ...
        def toString(self) -> str: ...
    class SpiUnavailableException(android.util.AndroidException):
        def getSpi(self) -> int: ...
    class UdpEncapsulationSocket(java.lang.AutoCloseable):
        def close(self) -> None: ...
        def getFileDescriptor(self) -> java.io.FileDescriptor: ...
        def getPort(self) -> int: ...
        def toString(self) -> str: ...

class IpSecTransform(java.lang.AutoCloseable):
    def close(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def requestIpSecTransformState(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['IpSecTransformState', java.lang.RuntimeException], typing.Callable[['IpSecTransformState'], None]]) -> None: ...
    def toString(self) -> str: ...
    class Builder:
        def __init__(self, context: android.content.Context): ...
        def buildTransportModeTransform(self, inetAddress: java.net.InetAddress, securityParameterIndex: IpSecManager.SecurityParameterIndex) -> 'IpSecTransform': ...
        def setAuthenticatedEncryption(self, ipSecAlgorithm: IpSecAlgorithm) -> 'IpSecTransform.Builder': ...
        def setAuthentication(self, ipSecAlgorithm: IpSecAlgorithm) -> 'IpSecTransform.Builder': ...
        def setEncryption(self, ipSecAlgorithm: IpSecAlgorithm) -> 'IpSecTransform.Builder': ...
        def setIpv4Encapsulation(self, udpEncapsulationSocket: IpSecManager.UdpEncapsulationSocket, int: int) -> 'IpSecTransform.Builder': ...

class IpSecTransformState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getByteCount(self) -> int: ...
    def getPacketCount(self) -> int: ...
    def getReplayBitmap(self) -> typing.MutableSequence[int]: ...
    def getRxHighestSequenceNumber(self) -> int: ...
    def getTimestampMillis(self) -> int: ...
    def getTxHighestSequenceNumber(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'IpSecTransformState': ...
        def setByteCount(self, long: int) -> 'IpSecTransformState.Builder': ...
        def setPacketCount(self, long: int) -> 'IpSecTransformState.Builder': ...
        def setReplayBitmap(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'IpSecTransformState.Builder': ...
        def setRxHighestSequenceNumber(self, long: int) -> 'IpSecTransformState.Builder': ...
        def setTimestampMillis(self, long: int) -> 'IpSecTransformState.Builder': ...
        def setTxHighestSequenceNumber(self, long: int) -> 'IpSecTransformState.Builder': ...

class LinkAddress(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAddress(self) -> java.net.InetAddress: ...
    def getFlags(self) -> int: ...
    def getPrefixLength(self) -> int: ...
    def getScope(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LinkProperties(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self): ...
    def addRoute(self, routeInfo: 'RouteInfo') -> bool: ...
    def clear(self) -> None: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDhcpServerAddress(self) -> java.net.Inet4Address: ...
    def getDnsServers(self) -> java.util.List[java.net.InetAddress]: ...
    def getDomains(self) -> str: ...
    def getHttpProxy(self) -> 'ProxyInfo': ...
    def getInterfaceName(self) -> str: ...
    def getLinkAddresses(self) -> java.util.List[LinkAddress]: ...
    def getMtu(self) -> int: ...
    def getNat64Prefix(self) -> IpPrefix: ...
    def getPrivateDnsServerName(self) -> str: ...
    def getRoutes(self) -> java.util.List['RouteInfo']: ...
    def hashCode(self) -> int: ...
    def isPrivateDnsActive(self) -> bool: ...
    def isWakeOnLanSupported(self) -> bool: ...
    def setDhcpServerAddress(self, inet4Address: java.net.Inet4Address) -> None: ...
    def setDnsServers(self, collection: typing.Union[java.util.Collection[java.net.InetAddress], typing.Sequence[java.net.InetAddress], typing.Set[java.net.InetAddress]]) -> None: ...
    def setDomains(self, string: str) -> None: ...
    def setHttpProxy(self, proxyInfo: 'ProxyInfo') -> None: ...
    def setInterfaceName(self, string: str) -> None: ...
    def setLinkAddresses(self, collection: typing.Union[java.util.Collection[LinkAddress], typing.Sequence[LinkAddress], typing.Set[LinkAddress]]) -> None: ...
    def setMtu(self, int: int) -> None: ...
    def setNat64Prefix(self, ipPrefix: IpPrefix) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LocalServerSocket(java.io.Closeable):
    @typing.overload
    def __init__(self, fileDescriptor: java.io.FileDescriptor): ...
    @typing.overload
    def __init__(self, string: str): ...
    def accept(self) -> 'LocalSocket': ...
    def close(self) -> None: ...
    def getFileDescriptor(self) -> java.io.FileDescriptor: ...
    def getLocalSocketAddress(self) -> 'LocalSocketAddress': ...

class LocalSocket(java.io.Closeable):
    SOCKET_DGRAM: typing.ClassVar[int] = ...
    SOCKET_SEQPACKET: typing.ClassVar[int] = ...
    SOCKET_STREAM: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def bind(self, localSocketAddress: 'LocalSocketAddress') -> None: ...
    def close(self) -> None: ...
    @typing.overload
    def connect(self, localSocketAddress: 'LocalSocketAddress') -> None: ...
    @typing.overload
    def connect(self, localSocketAddress: 'LocalSocketAddress', int: int) -> None: ...
    def getAncillaryFileDescriptors(self) -> typing.MutableSequence[java.io.FileDescriptor]: ...
    def getFileDescriptor(self) -> java.io.FileDescriptor: ...
    def getInputStream(self) -> java.io.InputStream: ...
    def getLocalSocketAddress(self) -> 'LocalSocketAddress': ...
    def getOutputStream(self) -> java.io.OutputStream: ...
    def getPeerCredentials(self) -> Credentials: ...
    def getReceiveBufferSize(self) -> int: ...
    def getRemoteSocketAddress(self) -> 'LocalSocketAddress': ...
    def getSendBufferSize(self) -> int: ...
    def getSoTimeout(self) -> int: ...
    def isBound(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isConnected(self) -> bool: ...
    def isInputShutdown(self) -> bool: ...
    def isOutputShutdown(self) -> bool: ...
    def setFileDescriptorsForSend(self, fileDescriptorArray: typing.Union[typing.List[java.io.FileDescriptor], jpype.JArray]) -> None: ...
    def setReceiveBufferSize(self, int: int) -> None: ...
    def setSendBufferSize(self, int: int) -> None: ...
    def setSoTimeout(self, int: int) -> None: ...
    def shutdownInput(self) -> None: ...
    def shutdownOutput(self) -> None: ...
    def toString(self) -> str: ...

class LocalSocketAddress:
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, namespace: 'LocalSocketAddress.Namespace'): ...
    def getName(self) -> str: ...
    def getNamespace(self) -> 'LocalSocketAddress.Namespace': ...
    class Namespace(java.lang.Enum['LocalSocketAddress.Namespace']):
        ABSTRACT: typing.ClassVar['LocalSocketAddress.Namespace'] = ...
        RESERVED: typing.ClassVar['LocalSocketAddress.Namespace'] = ...
        FILESYSTEM: typing.ClassVar['LocalSocketAddress.Namespace'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'LocalSocketAddress.Namespace': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['LocalSocketAddress.Namespace']: ...

class MacAddress(android.os.Parcelable):
    BROADCAST_ADDRESS: typing.ClassVar['MacAddress'] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_BROADCAST: typing.ClassVar[int] = ...
    TYPE_MULTICAST: typing.ClassVar[int] = ...
    TYPE_UNICAST: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromBytes(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'MacAddress': ...
    @staticmethod
    def fromString(string: str) -> 'MacAddress': ...
    def getAddressType(self) -> int: ...
    def getLinkLocalIpv6FromEui48Mac(self) -> java.net.Inet6Address: ...
    def hashCode(self) -> int: ...
    def isLocallyAssigned(self) -> bool: ...
    def matches(self, macAddress: 'MacAddress', macAddress2: 'MacAddress') -> bool: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    def toOuiString(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class MailTo:
    MAILTO_SCHEME: typing.ClassVar[str] = ...
    def getBody(self) -> str: ...
    def getCc(self) -> str: ...
    def getHeaders(self) -> java.util.Map[str, str]: ...
    def getSubject(self) -> str: ...
    def getTo(self) -> str: ...
    @staticmethod
    def isMailTo(string: str) -> bool: ...
    @staticmethod
    def parse(string: str) -> 'MailTo': ...
    def toString(self) -> str: ...

class Network(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def bindSocket(self, fileDescriptor: java.io.FileDescriptor) -> None: ...
    @typing.overload
    def bindSocket(self, datagramSocket: java.net.DatagramSocket) -> None: ...
    @typing.overload
    def bindSocket(self, socket: java.net.Socket) -> None: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromNetworkHandle(long: int) -> 'Network': ...
    def getAllByName(self, string: str) -> typing.MutableSequence[java.net.InetAddress]: ...
    def getByName(self, string: str) -> java.net.InetAddress: ...
    def getNetworkHandle(self) -> int: ...
    def getSocketFactory(self) -> javax.net.SocketFactory: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def openConnection(self, uRL: java.net.URL) -> java.net.URLConnection: ...
    @typing.overload
    def openConnection(self, uRL: java.net.URL, proxy: java.net.Proxy) -> java.net.URLConnection: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NetworkCapabilities(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    NET_CAPABILITY_CAPTIVE_PORTAL: typing.ClassVar[int] = ...
    NET_CAPABILITY_CBS: typing.ClassVar[int] = ...
    NET_CAPABILITY_DUN: typing.ClassVar[int] = ...
    NET_CAPABILITY_EIMS: typing.ClassVar[int] = ...
    NET_CAPABILITY_ENTERPRISE: typing.ClassVar[int] = ...
    NET_CAPABILITY_FOREGROUND: typing.ClassVar[int] = ...
    NET_CAPABILITY_FOTA: typing.ClassVar[int] = ...
    NET_CAPABILITY_HEAD_UNIT: typing.ClassVar[int] = ...
    NET_CAPABILITY_IA: typing.ClassVar[int] = ...
    NET_CAPABILITY_IMS: typing.ClassVar[int] = ...
    NET_CAPABILITY_INTERNET: typing.ClassVar[int] = ...
    NET_CAPABILITY_LOCAL_NETWORK: typing.ClassVar[int] = ...
    NET_CAPABILITY_MCX: typing.ClassVar[int] = ...
    NET_CAPABILITY_MMS: typing.ClassVar[int] = ...
    NET_CAPABILITY_MMTEL: typing.ClassVar[int] = ...
    NET_CAPABILITY_NOT_CONGESTED: typing.ClassVar[int] = ...
    NET_CAPABILITY_NOT_METERED: typing.ClassVar[int] = ...
    NET_CAPABILITY_NOT_RESTRICTED: typing.ClassVar[int] = ...
    NET_CAPABILITY_NOT_ROAMING: typing.ClassVar[int] = ...
    NET_CAPABILITY_NOT_SUSPENDED: typing.ClassVar[int] = ...
    NET_CAPABILITY_NOT_VPN: typing.ClassVar[int] = ...
    NET_CAPABILITY_PRIORITIZE_BANDWIDTH: typing.ClassVar[int] = ...
    NET_CAPABILITY_PRIORITIZE_LATENCY: typing.ClassVar[int] = ...
    NET_CAPABILITY_RCS: typing.ClassVar[int] = ...
    NET_CAPABILITY_SUPL: typing.ClassVar[int] = ...
    NET_CAPABILITY_TEMPORARILY_NOT_METERED: typing.ClassVar[int] = ...
    NET_CAPABILITY_TRUSTED: typing.ClassVar[int] = ...
    NET_CAPABILITY_VALIDATED: typing.ClassVar[int] = ...
    NET_CAPABILITY_WIFI_P2P: typing.ClassVar[int] = ...
    NET_CAPABILITY_XCAP: typing.ClassVar[int] = ...
    NET_ENTERPRISE_ID_1: typing.ClassVar[int] = ...
    NET_ENTERPRISE_ID_2: typing.ClassVar[int] = ...
    NET_ENTERPRISE_ID_3: typing.ClassVar[int] = ...
    NET_ENTERPRISE_ID_4: typing.ClassVar[int] = ...
    NET_ENTERPRISE_ID_5: typing.ClassVar[int] = ...
    SIGNAL_STRENGTH_UNSPECIFIED: typing.ClassVar[int] = ...
    TRANSPORT_BLUETOOTH: typing.ClassVar[int] = ...
    TRANSPORT_CELLULAR: typing.ClassVar[int] = ...
    TRANSPORT_ETHERNET: typing.ClassVar[int] = ...
    TRANSPORT_LOWPAN: typing.ClassVar[int] = ...
    TRANSPORT_SATELLITE: typing.ClassVar[int] = ...
    TRANSPORT_THREAD: typing.ClassVar[int] = ...
    TRANSPORT_USB: typing.ClassVar[int] = ...
    TRANSPORT_VPN: typing.ClassVar[int] = ...
    TRANSPORT_WIFI: typing.ClassVar[int] = ...
    TRANSPORT_WIFI_AWARE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, networkCapabilities: 'NetworkCapabilities'): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCapabilities(self) -> typing.MutableSequence[int]: ...
    def getEnterpriseIds(self) -> typing.MutableSequence[int]: ...
    def getLinkDownstreamBandwidthKbps(self) -> int: ...
    def getLinkUpstreamBandwidthKbps(self) -> int: ...
    def getNetworkSpecifier(self) -> 'NetworkSpecifier': ...
    def getOwnerUid(self) -> int: ...
    def getSignalStrength(self) -> int: ...
    def getSubscriptionIds(self) -> java.util.Set[int]: ...
    def getTransportInfo(self) -> 'TransportInfo': ...
    def hasCapability(self, int: int) -> bool: ...
    def hasEnterpriseId(self, int: int) -> bool: ...
    def hasTransport(self, int: int) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NetworkInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, string: str, string2: str): ...
    def describeContents(self) -> int: ...
    def getDetailedState(self) -> 'NetworkInfo.DetailedState': ...
    def getExtraInfo(self) -> str: ...
    def getReason(self) -> str: ...
    def getState(self) -> 'NetworkInfo.State': ...
    def getSubtype(self) -> int: ...
    def getSubtypeName(self) -> str: ...
    def getType(self) -> int: ...
    def getTypeName(self) -> str: ...
    def isAvailable(self) -> bool: ...
    def isConnected(self) -> bool: ...
    def isConnectedOrConnecting(self) -> bool: ...
    def isFailover(self) -> bool: ...
    def isRoaming(self) -> bool: ...
    def setDetailedState(self, detailedState: 'NetworkInfo.DetailedState', string: str, string2: str) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class DetailedState(java.lang.Enum['NetworkInfo.DetailedState']):
        IDLE: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        SCANNING: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        CONNECTING: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        AUTHENTICATING: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        OBTAINING_IPADDR: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        CONNECTED: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        SUSPENDED: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        DISCONNECTING: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        DISCONNECTED: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        FAILED: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        BLOCKED: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        VERIFYING_POOR_LINK: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        CAPTIVE_PORTAL_CHECK: typing.ClassVar['NetworkInfo.DetailedState'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NetworkInfo.DetailedState': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NetworkInfo.DetailedState']: ...
    class State(java.lang.Enum['NetworkInfo.State']):
        CONNECTING: typing.ClassVar['NetworkInfo.State'] = ...
        CONNECTED: typing.ClassVar['NetworkInfo.State'] = ...
        SUSPENDED: typing.ClassVar['NetworkInfo.State'] = ...
        DISCONNECTING: typing.ClassVar['NetworkInfo.State'] = ...
        DISCONNECTED: typing.ClassVar['NetworkInfo.State'] = ...
        UNKNOWN: typing.ClassVar['NetworkInfo.State'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'NetworkInfo.State': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['NetworkInfo.State']: ...

class NetworkRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def canBeSatisfiedBy(self, networkCapabilities: NetworkCapabilities) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCapabilities(self) -> typing.MutableSequence[int]: ...
    def getNetworkSpecifier(self) -> 'NetworkSpecifier': ...
    def getSubscriptionIds(self) -> java.util.Set[int]: ...
    def getTransportTypes(self) -> typing.MutableSequence[int]: ...
    def hasCapability(self, int: int) -> bool: ...
    def hasTransport(self, int: int) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, networkRequest: 'NetworkRequest'): ...
        def addCapability(self, int: int) -> 'NetworkRequest.Builder': ...
        def addTransportType(self, int: int) -> 'NetworkRequest.Builder': ...
        def build(self) -> 'NetworkRequest': ...
        def clearCapabilities(self) -> 'NetworkRequest.Builder': ...
        def removeCapability(self, int: int) -> 'NetworkRequest.Builder': ...
        def removeTransportType(self, int: int) -> 'NetworkRequest.Builder': ...
        def setIncludeOtherUidNetworks(self, boolean: bool) -> 'NetworkRequest.Builder': ...
        @typing.overload
        def setNetworkSpecifier(self, networkSpecifier: 'NetworkSpecifier') -> 'NetworkRequest.Builder': ...
        @typing.overload
        def setNetworkSpecifier(self, string: str) -> 'NetworkRequest.Builder': ...
        def setSubscriptionIds(self, set: java.util.Set[int]) -> 'NetworkRequest.Builder': ...

class NetworkSpecifier:
    def __init__(self): ...

class ParseException(java.lang.RuntimeException):
    response: str = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class PlatformVpnProfile:
    TYPE_IKEV2_IPSEC_PSK: typing.ClassVar[int] = ...
    TYPE_IKEV2_IPSEC_RSA: typing.ClassVar[int] = ...
    TYPE_IKEV2_IPSEC_USER_PASS: typing.ClassVar[int] = ...
    def areLocalRoutesExcluded(self) -> bool: ...
    def getType(self) -> int: ...
    def getTypeString(self) -> str: ...
    def isInternetValidationRequired(self) -> bool: ...

class Proxy:
    PROXY_CHANGE_ACTION: typing.ClassVar[str] = ...
    def __init__(self): ...
    @staticmethod
    def getDefaultHost() -> str: ...
    @staticmethod
    def getDefaultPort() -> int: ...
    @staticmethod
    def getHost(context: android.content.Context) -> str: ...
    @staticmethod
    def getPort(context: android.content.Context) -> int: ...

class ProxyInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, proxyInfo: 'ProxyInfo'): ...
    @typing.overload
    @staticmethod
    def buildDirectProxy(string: str, int: int) -> 'ProxyInfo': ...
    @typing.overload
    @staticmethod
    def buildDirectProxy(string: str, int: int, list: java.util.List[str]) -> 'ProxyInfo': ...
    @typing.overload
    @staticmethod
    def buildPacProxy(uri: 'Uri') -> 'ProxyInfo': ...
    @typing.overload
    @staticmethod
    def buildPacProxy(uri: 'Uri', int: int) -> 'ProxyInfo': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExclusionList(self) -> typing.MutableSequence[str]: ...
    def getHost(self) -> str: ...
    def getPacFileUrl(self) -> 'Uri': ...
    def getPort(self) -> int: ...
    def hashCode(self) -> int: ...
    def isValid(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class RouteInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RTN_THROW: typing.ClassVar[int] = ...
    RTN_UNICAST: typing.ClassVar[int] = ...
    RTN_UNREACHABLE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDestination(self) -> IpPrefix: ...
    def getGateway(self) -> java.net.InetAddress: ...
    def getInterface(self) -> str: ...
    def getType(self) -> int: ...
    def hasGateway(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isDefaultRoute(self) -> bool: ...
    def matches(self, inetAddress: java.net.InetAddress) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SSLCertificateSocketFactory(javax.net.ssl.SSLSocketFactory):
    def __init__(self, int: int): ...
    @typing.overload
    def createSocket(self) -> java.net.Socket: ...
    @typing.overload
    def createSocket(self, string: str, int: int) -> java.net.Socket: ...
    @typing.overload
    def createSocket(self, string: str, int: int, inetAddress: java.net.InetAddress, int2: int) -> java.net.Socket: ...
    @typing.overload
    def createSocket(self, inetAddress: java.net.InetAddress, int: int) -> java.net.Socket: ...
    @typing.overload
    def createSocket(self, inetAddress: java.net.InetAddress, int: int, inetAddress2: java.net.InetAddress, int2: int) -> java.net.Socket: ...
    @typing.overload
    def createSocket(self, socket: java.net.Socket, string: str, int: int, boolean: bool) -> java.net.Socket: ...
    @typing.overload
    def createSocket(self, socket: java.net.Socket, inputStream: java.io.InputStream, boolean: bool) -> java.net.Socket: ...
    @typing.overload
    @staticmethod
    def getDefault(int: int) -> javax.net.SocketFactory: ...
    @typing.overload
    @staticmethod
    def getDefault() -> javax.net.SocketFactory: ...
    @typing.overload
    @staticmethod
    def getDefault(int: int, sSLSessionCache: 'SSLSessionCache') -> javax.net.ssl.SSLSocketFactory: ...
    def getDefaultCipherSuites(self) -> typing.MutableSequence[str]: ...
    @staticmethod
    def getInsecure(int: int, sSLSessionCache: 'SSLSessionCache') -> javax.net.ssl.SSLSocketFactory: ...
    def getNpnSelectedProtocol(self, socket: java.net.Socket) -> typing.MutableSequence[int]: ...
    def getSupportedCipherSuites(self) -> typing.MutableSequence[str]: ...
    def setHostname(self, socket: java.net.Socket, string: str) -> None: ...
    def setKeyManagers(self, keyManagerArray: typing.Union[typing.List[javax.net.ssl.KeyManager], jpype.JArray]) -> None: ...
    def setNpnProtocols(self, byteArray: typing.Union[typing.List[typing.MutableSequence[int]], jpype.JArray]) -> None: ...
    def setTrustManagers(self, trustManagerArray: typing.Union[typing.List[javax.net.ssl.TrustManager], jpype.JArray]) -> None: ...
    def setUseSessionTickets(self, socket: java.net.Socket, boolean: bool) -> None: ...

class SSLSessionCache:
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]): ...

class SocketKeepalive(java.lang.AutoCloseable):
    ERROR_HARDWARE_ERROR: typing.ClassVar[int] = ...
    ERROR_INSUFFICIENT_RESOURCES: typing.ClassVar[int] = ...
    ERROR_INVALID_INTERVAL: typing.ClassVar[int] = ...
    ERROR_INVALID_IP_ADDRESS: typing.ClassVar[int] = ...
    ERROR_INVALID_LENGTH: typing.ClassVar[int] = ...
    ERROR_INVALID_NETWORK: typing.ClassVar[int] = ...
    ERROR_INVALID_PORT: typing.ClassVar[int] = ...
    ERROR_INVALID_SOCKET: typing.ClassVar[int] = ...
    ERROR_SOCKET_NOT_IDLE: typing.ClassVar[int] = ...
    ERROR_UNSUPPORTED: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def start(self, int: int) -> None: ...
    def stop(self) -> None: ...
    class Callback:
        def __init__(self): ...
        def onDataReceived(self) -> None: ...
        def onError(self, int: int) -> None: ...
        def onStarted(self) -> None: ...
        def onStopped(self) -> None: ...

class StaticIpConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDnsServers(self) -> java.util.List[java.net.InetAddress]: ...
    def getDomains(self) -> str: ...
    def getGateway(self) -> java.net.InetAddress: ...
    def getIpAddress(self) -> LinkAddress: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'StaticIpConfiguration': ...
        def setDnsServers(self, iterable: typing.Union[java.lang.Iterable[java.net.InetAddress], typing.Sequence[java.net.InetAddress], typing.Set[java.net.InetAddress], typing.Callable[[], java.util.Iterator[typing.Any]]]) -> 'StaticIpConfiguration.Builder': ...
        def setDomains(self, string: str) -> 'StaticIpConfiguration.Builder': ...
        def setGateway(self, inetAddress: java.net.InetAddress) -> 'StaticIpConfiguration.Builder': ...
        def setIpAddress(self, linkAddress: LinkAddress) -> 'StaticIpConfiguration.Builder': ...

class TrafficStats:
    UNSUPPORTED: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def clearThreadStatsTag() -> None: ...
    @staticmethod
    def clearThreadStatsUid() -> None: ...
    @staticmethod
    def getAndSetThreadStatsTag(int: int) -> int: ...
    @staticmethod
    def getMobileRxBytes() -> int: ...
    @staticmethod
    def getMobileRxPackets() -> int: ...
    @staticmethod
    def getMobileTxBytes() -> int: ...
    @staticmethod
    def getMobileTxPackets() -> int: ...
    @staticmethod
    def getRxBytes(string: str) -> int: ...
    @staticmethod
    def getRxPackets(string: str) -> int: ...
    @staticmethod
    def getThreadStatsTag() -> int: ...
    @staticmethod
    def getThreadStatsUid() -> int: ...
    @staticmethod
    def getTotalRxBytes() -> int: ...
    @staticmethod
    def getTotalRxPackets() -> int: ...
    @staticmethod
    def getTotalTxBytes() -> int: ...
    @staticmethod
    def getTotalTxPackets() -> int: ...
    @staticmethod
    def getTxBytes(string: str) -> int: ...
    @staticmethod
    def getTxPackets(string: str) -> int: ...
    @staticmethod
    def getUidRxBytes(int: int) -> int: ...
    @staticmethod
    def getUidRxPackets(int: int) -> int: ...
    @staticmethod
    def getUidTcpRxBytes(int: int) -> int: ...
    @staticmethod
    def getUidTcpRxSegments(int: int) -> int: ...
    @staticmethod
    def getUidTcpTxBytes(int: int) -> int: ...
    @staticmethod
    def getUidTcpTxSegments(int: int) -> int: ...
    @staticmethod
    def getUidTxBytes(int: int) -> int: ...
    @staticmethod
    def getUidTxPackets(int: int) -> int: ...
    @staticmethod
    def getUidUdpRxBytes(int: int) -> int: ...
    @staticmethod
    def getUidUdpRxPackets(int: int) -> int: ...
    @staticmethod
    def getUidUdpTxBytes(int: int) -> int: ...
    @staticmethod
    def getUidUdpTxPackets(int: int) -> int: ...
    @typing.overload
    @staticmethod
    def incrementOperationCount(int: int) -> None: ...
    @typing.overload
    @staticmethod
    def incrementOperationCount(int: int, int2: int) -> None: ...
    @staticmethod
    def setThreadStatsTag(int: int) -> None: ...
    @staticmethod
    def setThreadStatsUid(int: int) -> None: ...
    @staticmethod
    def tagDatagramSocket(datagramSocket: java.net.DatagramSocket) -> None: ...
    @staticmethod
    def tagFileDescriptor(fileDescriptor: java.io.FileDescriptor) -> None: ...
    @staticmethod
    def tagSocket(socket: java.net.Socket) -> None: ...
    @staticmethod
    def untagDatagramSocket(datagramSocket: java.net.DatagramSocket) -> None: ...
    @staticmethod
    def untagFileDescriptor(fileDescriptor: java.io.FileDescriptor) -> None: ...
    @staticmethod
    def untagSocket(socket: java.net.Socket) -> None: ...

class TransportInfo: ...

class Uri(android.os.Parcelable, java.lang.Comparable['Uri']):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EMPTY: typing.ClassVar['Uri'] = ...
    def buildUpon(self) -> 'Uri.Builder': ...
    def compareTo(self, uri: 'Uri') -> int: ...
    @staticmethod
    def decode(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def encode(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def encode(string: str, string2: str) -> str: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromFile(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> 'Uri': ...
    @staticmethod
    def fromParts(string: str, string2: str, string3: str) -> 'Uri': ...
    def getAuthority(self) -> str: ...
    def getBooleanQueryParameter(self, string: str, boolean: bool) -> bool: ...
    def getEncodedAuthority(self) -> str: ...
    def getEncodedFragment(self) -> str: ...
    def getEncodedPath(self) -> str: ...
    def getEncodedQuery(self) -> str: ...
    def getEncodedSchemeSpecificPart(self) -> str: ...
    def getEncodedUserInfo(self) -> str: ...
    def getFragment(self) -> str: ...
    def getHost(self) -> str: ...
    def getLastPathSegment(self) -> str: ...
    def getPath(self) -> str: ...
    def getPathSegments(self) -> java.util.List[str]: ...
    def getPort(self) -> int: ...
    def getQuery(self) -> str: ...
    def getQueryParameter(self, string: str) -> str: ...
    def getQueryParameterNames(self) -> java.util.Set[str]: ...
    def getQueryParameters(self, string: str) -> java.util.List[str]: ...
    def getScheme(self) -> str: ...
    def getSchemeSpecificPart(self) -> str: ...
    def getUserInfo(self) -> str: ...
    def hashCode(self) -> int: ...
    def isAbsolute(self) -> bool: ...
    def isHierarchical(self) -> bool: ...
    def isOpaque(self) -> bool: ...
    def isRelative(self) -> bool: ...
    def normalizeScheme(self) -> 'Uri': ...
    @staticmethod
    def parse(string: str) -> 'Uri': ...
    def toString(self) -> str: ...
    @staticmethod
    def withAppendedPath(uri: 'Uri', string: str) -> 'Uri': ...
    @typing.overload
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    @typing.overload
    @staticmethod
    def writeToParcel(parcel: android.os.Parcel, uri: 'Uri') -> None: ...
    class Builder:
        def __init__(self): ...
        def appendEncodedPath(self, string: str) -> 'Uri.Builder': ...
        def appendPath(self, string: str) -> 'Uri.Builder': ...
        def appendQueryParameter(self, string: str, string2: str) -> 'Uri.Builder': ...
        def authority(self, string: str) -> 'Uri.Builder': ...
        def build(self) -> 'Uri': ...
        def clearQuery(self) -> 'Uri.Builder': ...
        def encodedAuthority(self, string: str) -> 'Uri.Builder': ...
        def encodedFragment(self, string: str) -> 'Uri.Builder': ...
        def encodedOpaquePart(self, string: str) -> 'Uri.Builder': ...
        def encodedPath(self, string: str) -> 'Uri.Builder': ...
        def encodedQuery(self, string: str) -> 'Uri.Builder': ...
        def fragment(self, string: str) -> 'Uri.Builder': ...
        def opaquePart(self, string: str) -> 'Uri.Builder': ...
        def path(self, string: str) -> 'Uri.Builder': ...
        def query(self, string: str) -> 'Uri.Builder': ...
        def scheme(self, string: str) -> 'Uri.Builder': ...
        def toString(self) -> str: ...

class VpnManager:
    ACTION_VPN_MANAGER_EVENT: typing.ClassVar[str] = ...
    CATEGORY_EVENT_ALWAYS_ON_STATE_CHANGED: typing.ClassVar[str] = ...
    CATEGORY_EVENT_DEACTIVATED_BY_USER: typing.ClassVar[str] = ...
    CATEGORY_EVENT_IKE_ERROR: typing.ClassVar[str] = ...
    CATEGORY_EVENT_NETWORK_ERROR: typing.ClassVar[str] = ...
    ERROR_CLASS_NOT_RECOVERABLE: typing.ClassVar[int] = ...
    ERROR_CLASS_RECOVERABLE: typing.ClassVar[int] = ...
    ERROR_CODE_NETWORK_IO: typing.ClassVar[int] = ...
    ERROR_CODE_NETWORK_LOST: typing.ClassVar[int] = ...
    ERROR_CODE_NETWORK_PROTOCOL_TIMEOUT: typing.ClassVar[int] = ...
    ERROR_CODE_NETWORK_UNKNOWN_HOST: typing.ClassVar[int] = ...
    EXTRA_ERROR_CLASS: typing.ClassVar[str] = ...
    EXTRA_ERROR_CODE: typing.ClassVar[str] = ...
    EXTRA_SESSION_KEY: typing.ClassVar[str] = ...
    EXTRA_TIMESTAMP_MILLIS: typing.ClassVar[str] = ...
    EXTRA_UNDERLYING_LINK_PROPERTIES: typing.ClassVar[str] = ...
    EXTRA_UNDERLYING_NETWORK: typing.ClassVar[str] = ...
    EXTRA_UNDERLYING_NETWORK_CAPABILITIES: typing.ClassVar[str] = ...
    EXTRA_VPN_PROFILE_STATE: typing.ClassVar[str] = ...
    def deleteProvisionedVpnProfile(self) -> None: ...
    def getProvisionedVpnProfileState(self) -> 'VpnProfileState': ...
    def provisionVpnProfile(self, platformVpnProfile: PlatformVpnProfile) -> android.content.Intent: ...
    def startProvisionedVpnProfile(self) -> None: ...
    def startProvisionedVpnProfileSession(self) -> str: ...
    def stopProvisionedVpnProfile(self) -> None: ...

class VpnProfileState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STATE_CONNECTED: typing.ClassVar[int] = ...
    STATE_CONNECTING: typing.ClassVar[int] = ...
    STATE_DISCONNECTED: typing.ClassVar[int] = ...
    STATE_FAILED: typing.ClassVar[int] = ...
    def __init__(self, int: int, string: str, boolean: bool, boolean2: bool): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSessionId(self) -> str: ...
    def getState(self) -> int: ...
    def hashCode(self) -> int: ...
    def isAlwaysOn(self) -> bool: ...
    def isLockdownEnabled(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class VpnService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA_SUPPORTS_ALWAYS_ON: typing.ClassVar[str] = ...
    def __init__(self): ...
    def isAlwaysOn(self) -> bool: ...
    def isLockdownEnabled(self) -> bool: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onRevoke(self) -> None: ...
    @staticmethod
    def prepare(context: android.content.Context) -> android.content.Intent: ...
    @typing.overload
    def protect(self, int: int) -> bool: ...
    @typing.overload
    def protect(self, datagramSocket: java.net.DatagramSocket) -> bool: ...
    @typing.overload
    def protect(self, socket: java.net.Socket) -> bool: ...
    def setUnderlyingNetworks(self, networkArray: typing.Union[typing.List[Network], jpype.JArray]) -> bool: ...
    class Builder:
        def __init__(self, vpnService: 'VpnService'): ...
        @typing.overload
        def addAddress(self, string: str, int: int) -> 'VpnService.Builder': ...
        @typing.overload
        def addAddress(self, inetAddress: java.net.InetAddress, int: int) -> 'VpnService.Builder': ...
        def addAllowedApplication(self, string: str) -> 'VpnService.Builder': ...
        def addDisallowedApplication(self, string: str) -> 'VpnService.Builder': ...
        @typing.overload
        def addDnsServer(self, string: str) -> 'VpnService.Builder': ...
        @typing.overload
        def addDnsServer(self, inetAddress: java.net.InetAddress) -> 'VpnService.Builder': ...
        @typing.overload
        def addRoute(self, ipPrefix: IpPrefix) -> 'VpnService.Builder': ...
        @typing.overload
        def addRoute(self, string: str, int: int) -> 'VpnService.Builder': ...
        @typing.overload
        def addRoute(self, inetAddress: java.net.InetAddress, int: int) -> 'VpnService.Builder': ...
        def addSearchDomain(self, string: str) -> 'VpnService.Builder': ...
        def allowBypass(self) -> 'VpnService.Builder': ...
        def allowFamily(self, int: int) -> 'VpnService.Builder': ...
        def establish(self) -> android.os.ParcelFileDescriptor: ...
        def excludeRoute(self, ipPrefix: IpPrefix) -> 'VpnService.Builder': ...
        def setBlocking(self, boolean: bool) -> 'VpnService.Builder': ...
        def setConfigureIntent(self, pendingIntent: android.app.PendingIntent) -> 'VpnService.Builder': ...
        def setHttpProxy(self, proxyInfo: ProxyInfo) -> 'VpnService.Builder': ...
        def setMetered(self, boolean: bool) -> 'VpnService.Builder': ...
        def setMtu(self, int: int) -> 'VpnService.Builder': ...
        def setSession(self, string: str) -> 'VpnService.Builder': ...
        def setUnderlyingNetworks(self, networkArray: typing.Union[typing.List[Network], jpype.JArray]) -> 'VpnService.Builder': ...

class EthernetNetworkSpecifier(NetworkSpecifier, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str): ...
    def canBeSatisfiedBy(self, networkSpecifier: NetworkSpecifier) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getInterfaceName(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Ikev2VpnProfile(PlatformVpnProfile):
    def equals(self, object: typing.Any) -> bool: ...
    def getAllowedAlgorithms(self) -> java.util.List[str]: ...
    def getIkeTunnelConnectionParams(self) -> android.net.ipsec.ike.IkeTunnelConnectionParams: ...
    def getMaxMtu(self) -> int: ...
    def getPassword(self) -> str: ...
    def getPresharedKey(self) -> typing.MutableSequence[int]: ...
    def getProxyInfo(self) -> ProxyInfo: ...
    def getRsaPrivateKey(self) -> java.security.PrivateKey: ...
    def getServerAddr(self) -> str: ...
    def getServerRootCaCert(self) -> java.security.cert.X509Certificate: ...
    def getUserCert(self) -> java.security.cert.X509Certificate: ...
    def getUserIdentity(self) -> str: ...
    def getUsername(self) -> str: ...
    def hashCode(self) -> int: ...
    def isAutomaticIpVersionSelectionEnabled(self) -> bool: ...
    def isAutomaticNattKeepaliveTimerEnabled(self) -> bool: ...
    def isBypassable(self) -> bool: ...
    def isMetered(self) -> bool: ...
    def toString(self) -> str: ...
    class Builder:
        @typing.overload
        def __init__(self, ikeTunnelConnectionParams: android.net.ipsec.ike.IkeTunnelConnectionParams): ...
        @typing.overload
        def __init__(self, string: str, string2: str): ...
        def build(self) -> 'Ikev2VpnProfile': ...
        def setAllowedAlgorithms(self, list: java.util.List[str]) -> 'Ikev2VpnProfile.Builder': ...
        def setAuthDigitalSignature(self, x509Certificate: java.security.cert.X509Certificate, privateKey: java.security.PrivateKey, x509Certificate2: java.security.cert.X509Certificate) -> 'Ikev2VpnProfile.Builder': ...
        def setAuthPsk(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'Ikev2VpnProfile.Builder': ...
        def setAuthUsernamePassword(self, string: str, string2: str, x509Certificate: java.security.cert.X509Certificate) -> 'Ikev2VpnProfile.Builder': ...
        def setAutomaticIpVersionSelectionEnabled(self, boolean: bool) -> 'Ikev2VpnProfile.Builder': ...
        def setAutomaticNattKeepaliveTimerEnabled(self, boolean: bool) -> 'Ikev2VpnProfile.Builder': ...
        def setBypassable(self, boolean: bool) -> 'Ikev2VpnProfile.Builder': ...
        def setLocalRoutesExcluded(self, boolean: bool) -> 'Ikev2VpnProfile.Builder': ...
        def setMaxMtu(self, int: int) -> 'Ikev2VpnProfile.Builder': ...
        def setMetered(self, boolean: bool) -> 'Ikev2VpnProfile.Builder': ...
        def setProxy(self, proxyInfo: ProxyInfo) -> 'Ikev2VpnProfile.Builder': ...
        def setRequiresInternetValidation(self, boolean: bool) -> 'Ikev2VpnProfile.Builder': ...

class TelephonyNetworkSpecifier(NetworkSpecifier, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSubscriptionId(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'TelephonyNetworkSpecifier': ...
        def setSubscriptionId(self, int: int) -> 'TelephonyNetworkSpecifier.Builder': ...

class UrlQuerySanitizer:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @staticmethod
    def getAllButNulAndAngleBracketsLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    @staticmethod
    def getAllButNulLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    @staticmethod
    def getAllButWhitespaceLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    @staticmethod
    def getAllIllegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    def getAllowUnregisteredParamaters(self) -> bool: ...
    @staticmethod
    def getAmpAndSpaceLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    @staticmethod
    def getAmpLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    def getEffectiveValueSanitizer(self, string: str) -> 'UrlQuerySanitizer.ValueSanitizer': ...
    def getParameterList(self) -> java.util.List['UrlQuerySanitizer.ParameterValuePair']: ...
    def getParameterSet(self) -> java.util.Set[str]: ...
    def getPreferFirstRepeatedParameter(self) -> bool: ...
    @staticmethod
    def getSpaceLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    def getUnregisteredParameterValueSanitizer(self) -> 'UrlQuerySanitizer.ValueSanitizer': ...
    @staticmethod
    def getUrlAndSpaceLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    @staticmethod
    def getUrlLegal() -> 'UrlQuerySanitizer.ValueSanitizer': ...
    def getValue(self, string: str) -> str: ...
    def getValueSanitizer(self, string: str) -> 'UrlQuerySanitizer.ValueSanitizer': ...
    def hasParameter(self, string: str) -> bool: ...
    def parseQuery(self, string: str) -> None: ...
    def parseUrl(self, string: str) -> None: ...
    def registerParameter(self, string: str, valueSanitizer: typing.Union['UrlQuerySanitizer.ValueSanitizer', typing.Callable]) -> None: ...
    def registerParameters(self, stringArray: typing.Union[typing.List[str], jpype.JArray], valueSanitizer: typing.Union['UrlQuerySanitizer.ValueSanitizer', typing.Callable]) -> None: ...
    def setAllowUnregisteredParamaters(self, boolean: bool) -> None: ...
    def setPreferFirstRepeatedParameter(self, boolean: bool) -> None: ...
    def setUnregisteredParameterValueSanitizer(self, valueSanitizer: typing.Union['UrlQuerySanitizer.ValueSanitizer', typing.Callable]) -> None: ...
    def unescape(self, string: str) -> str: ...
    class IllegalCharacterValueSanitizer(android.net.UrlQuerySanitizer.ValueSanitizer):
        ALL_BUT_NUL_AND_ANGLE_BRACKETS_LEGAL: typing.ClassVar[int] = ...
        ALL_BUT_NUL_LEGAL: typing.ClassVar[int] = ...
        ALL_BUT_WHITESPACE_LEGAL: typing.ClassVar[int] = ...
        ALL_ILLEGAL: typing.ClassVar[int] = ...
        ALL_OK: typing.ClassVar[int] = ...
        ALL_WHITESPACE_OK: typing.ClassVar[int] = ...
        AMP_AND_SPACE_LEGAL: typing.ClassVar[int] = ...
        AMP_LEGAL: typing.ClassVar[int] = ...
        AMP_OK: typing.ClassVar[int] = ...
        DQUOTE_OK: typing.ClassVar[int] = ...
        GT_OK: typing.ClassVar[int] = ...
        LT_OK: typing.ClassVar[int] = ...
        NON_7_BIT_ASCII_OK: typing.ClassVar[int] = ...
        NUL_OK: typing.ClassVar[int] = ...
        OTHER_WHITESPACE_OK: typing.ClassVar[int] = ...
        PCT_OK: typing.ClassVar[int] = ...
        SCRIPT_URL_OK: typing.ClassVar[int] = ...
        SPACE_LEGAL: typing.ClassVar[int] = ...
        SPACE_OK: typing.ClassVar[int] = ...
        SQUOTE_OK: typing.ClassVar[int] = ...
        URL_AND_SPACE_LEGAL: typing.ClassVar[int] = ...
        URL_LEGAL: typing.ClassVar[int] = ...
        def __init__(self, int: int): ...
        def sanitize(self, string: str) -> str: ...
    class ParameterValuePair:
        mParameter: str = ...
        mValue: str = ...
        def __init__(self, urlQuerySanitizer: 'UrlQuerySanitizer', string: str, string2: str): ...
    class ValueSanitizer:
        def sanitize(self, string: str) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net")``.

    CaptivePortal: typing.Type[CaptivePortal]
    ConnectivityDiagnosticsManager: typing.Type[ConnectivityDiagnosticsManager]
    ConnectivityManager: typing.Type[ConnectivityManager]
    Credentials: typing.Type[Credentials]
    DhcpInfo: typing.Type[DhcpInfo]
    DnsResolver: typing.Type[DnsResolver]
    EthernetNetworkSpecifier: typing.Type[EthernetNetworkSpecifier]
    Ikev2VpnProfile: typing.Type[Ikev2VpnProfile]
    InetAddresses: typing.Type[InetAddresses]
    IpConfiguration: typing.Type[IpConfiguration]
    IpPrefix: typing.Type[IpPrefix]
    IpSecAlgorithm: typing.Type[IpSecAlgorithm]
    IpSecManager: typing.Type[IpSecManager]
    IpSecTransform: typing.Type[IpSecTransform]
    IpSecTransformState: typing.Type[IpSecTransformState]
    LinkAddress: typing.Type[LinkAddress]
    LinkProperties: typing.Type[LinkProperties]
    LocalServerSocket: typing.Type[LocalServerSocket]
    LocalSocket: typing.Type[LocalSocket]
    LocalSocketAddress: typing.Type[LocalSocketAddress]
    MacAddress: typing.Type[MacAddress]
    MailTo: typing.Type[MailTo]
    Network: typing.Type[Network]
    NetworkCapabilities: typing.Type[NetworkCapabilities]
    NetworkInfo: typing.Type[NetworkInfo]
    NetworkRequest: typing.Type[NetworkRequest]
    NetworkSpecifier: typing.Type[NetworkSpecifier]
    ParseException: typing.Type[ParseException]
    PlatformVpnProfile: typing.Type[PlatformVpnProfile]
    Proxy: typing.Type[Proxy]
    ProxyInfo: typing.Type[ProxyInfo]
    RouteInfo: typing.Type[RouteInfo]
    SSLCertificateSocketFactory: typing.Type[SSLCertificateSocketFactory]
    SSLSessionCache: typing.Type[SSLSessionCache]
    SocketKeepalive: typing.Type[SocketKeepalive]
    StaticIpConfiguration: typing.Type[StaticIpConfiguration]
    TelephonyNetworkSpecifier: typing.Type[TelephonyNetworkSpecifier]
    TrafficStats: typing.Type[TrafficStats]
    TransportInfo: typing.Type[TransportInfo]
    Uri: typing.Type[Uri]
    UrlQuerySanitizer: typing.Type[UrlQuerySanitizer]
    VpnManager: typing.Type[VpnManager]
    VpnProfileState: typing.Type[VpnProfileState]
    VpnService: typing.Type[VpnService]
    eap: android.net.eap.__module_protocol__
    http: android.net.http.__module_protocol__
    ipsec: android.net.ipsec.__module_protocol__
    nsd: android.net.nsd.__module_protocol__
    rtp: android.net.rtp.__module_protocol__
    sip: android.net.sip.__module_protocol__
    ssl: android.net.ssl.__module_protocol__
    vcn: android.net.vcn.__module_protocol__
    wifi: android.net.wifi.__module_protocol__
