
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.lang
import java.util
import typing



class Light(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    LIGHT_CAPABILITY_BRIGHTNESS: typing.ClassVar[int] = ...
    LIGHT_CAPABILITY_COLOR_RGB: typing.ClassVar[int] = ...
    LIGHT_CAPABILITY_RGB: typing.ClassVar[int] = ...
    LIGHT_TYPE_INPUT: typing.ClassVar[int] = ...
    LIGHT_TYPE_KEYBOARD_BACKLIGHT: typing.ClassVar[int] = ...
    LIGHT_TYPE_MICROPHONE: typing.ClassVar[int] = ...
    LIGHT_TYPE_PLAYER_ID: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getId(self) -> int: ...
    def getName(self) -> str: ...
    def getOrdinal(self) -> int: ...
    def getType(self) -> int: ...
    def hasBrightnessControl(self) -> bool: ...
    def hasRgbControl(self) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LightState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getColor(self) -> int: ...
    def getPlayerId(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'LightState': ...
        def setColor(self, int: int) -> 'LightState.Builder': ...
        def setPlayerId(self, int: int) -> 'LightState.Builder': ...

class LightsManager:
    def getLightState(self, light: Light) -> LightState: ...
    def getLights(self) -> java.util.List[Light]: ...
    def openSession(self) -> 'LightsManager.LightsSession': ...
    class LightsSession(java.lang.AutoCloseable):
        def close(self) -> None: ...
        def requestLights(self, lightsRequest: 'LightsRequest') -> None: ...

class LightsRequest:
    def getLightStates(self) -> java.util.List[LightState]: ...
    def getLights(self) -> java.util.List[int]: ...
    def getLightsAndStates(self) -> java.util.Map[Light, LightState]: ...
    class Builder:
        def __init__(self): ...
        def addLight(self, light: Light, lightState: LightState) -> 'LightsRequest.Builder': ...
        def build(self) -> 'LightsRequest': ...
        def clearLight(self, light: Light) -> 'LightsRequest.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.hardware.lights")``.

    Light: typing.Type[Light]
    LightState: typing.Type[LightState]
    LightsManager: typing.Type[LightsManager]
    LightsRequest: typing.Type[LightsRequest]
