
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.os
import java.io
import java.lang
import typing



class SipAudioCall:
    def __init__(self, context: android.content.Context, sipProfile: 'SipProfile'): ...
    def answerCall(self, int: int) -> None: ...
    def attachCall(self, sipSession: 'SipSession', string: str) -> None: ...
    def close(self) -> None: ...
    def continueCall(self, int: int) -> None: ...
    def endCall(self) -> None: ...
    def getLocalProfile(self) -> 'SipProfile': ...
    def getPeerProfile(self) -> 'SipProfile': ...
    def getState(self) -> int: ...
    def holdCall(self, int: int) -> None: ...
    def isInCall(self) -> bool: ...
    def isMuted(self) -> bool: ...
    def isOnHold(self) -> bool: ...
    def makeCall(self, sipProfile: 'SipProfile', sipSession: 'SipSession', int: int) -> None: ...
    @typing.overload
    def sendDtmf(self, int: int) -> None: ...
    @typing.overload
    def sendDtmf(self, int: int, message: android.os.Message) -> None: ...
    @typing.overload
    def setListener(self, listener: 'SipAudioCall.Listener') -> None: ...
    @typing.overload
    def setListener(self, listener: 'SipAudioCall.Listener', boolean: bool) -> None: ...
    def setSpeakerMode(self, boolean: bool) -> None: ...
    def startAudio(self) -> None: ...
    def toggleMute(self) -> None: ...
    class Listener:
        def __init__(self): ...
        def onCallBusy(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onCallEnded(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onCallEstablished(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onCallHeld(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onCalling(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onChanged(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onError(self, sipAudioCall: 'SipAudioCall', int: int, string: str) -> None: ...
        def onReadyToCall(self, sipAudioCall: 'SipAudioCall') -> None: ...
        def onRinging(self, sipAudioCall: 'SipAudioCall', sipProfile: 'SipProfile') -> None: ...
        def onRingingBack(self, sipAudioCall: 'SipAudioCall') -> None: ...

class SipErrorCode:
    CLIENT_ERROR: typing.ClassVar[int] = ...
    CROSS_DOMAIN_AUTHENTICATION: typing.ClassVar[int] = ...
    DATA_CONNECTION_LOST: typing.ClassVar[int] = ...
    INVALID_CREDENTIALS: typing.ClassVar[int] = ...
    INVALID_REMOTE_URI: typing.ClassVar[int] = ...
    IN_PROGRESS: typing.ClassVar[int] = ...
    NO_ERROR: typing.ClassVar[int] = ...
    PEER_NOT_REACHABLE: typing.ClassVar[int] = ...
    SERVER_ERROR: typing.ClassVar[int] = ...
    SERVER_UNREACHABLE: typing.ClassVar[int] = ...
    SOCKET_ERROR: typing.ClassVar[int] = ...
    TIME_OUT: typing.ClassVar[int] = ...
    TRANSACTION_TERMINTED: typing.ClassVar[int] = ...
    @typing.overload
    def toString(self) -> str: ...
    @typing.overload
    @staticmethod
    def toString(int: int) -> str: ...

class SipException(java.lang.Exception):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class SipManager:
    EXTRA_CALL_ID: typing.ClassVar[str] = ...
    EXTRA_OFFER_SD: typing.ClassVar[str] = ...
    INCOMING_CALL_RESULT_CODE: typing.ClassVar[int] = ...
    def close(self, string: str) -> None: ...
    def createSipSession(self, sipProfile: 'SipProfile', listener: 'SipSession.Listener') -> 'SipSession': ...
    @staticmethod
    def getCallId(intent: android.content.Intent) -> str: ...
    @staticmethod
    def getOfferSessionDescription(intent: android.content.Intent) -> str: ...
    def getSessionFor(self, intent: android.content.Intent) -> 'SipSession': ...
    @staticmethod
    def isApiSupported(context: android.content.Context) -> bool: ...
    @staticmethod
    def isIncomingCallIntent(intent: android.content.Intent) -> bool: ...
    def isOpened(self, string: str) -> bool: ...
    def isRegistered(self, string: str) -> bool: ...
    @staticmethod
    def isSipWifiOnly(context: android.content.Context) -> bool: ...
    @staticmethod
    def isVoipSupported(context: android.content.Context) -> bool: ...
    @typing.overload
    def makeAudioCall(self, sipProfile: 'SipProfile', sipProfile2: 'SipProfile', listener: SipAudioCall.Listener, int: int) -> SipAudioCall: ...
    @typing.overload
    def makeAudioCall(self, string: str, string2: str, listener: SipAudioCall.Listener, int: int) -> SipAudioCall: ...
    @staticmethod
    def newInstance(context: android.content.Context) -> 'SipManager': ...
    @typing.overload
    def open(self, sipProfile: 'SipProfile') -> None: ...
    @typing.overload
    def open(self, sipProfile: 'SipProfile', pendingIntent: android.app.PendingIntent, sipRegistrationListener: 'SipRegistrationListener') -> None: ...
    def register(self, sipProfile: 'SipProfile', int: int, sipRegistrationListener: 'SipRegistrationListener') -> None: ...
    def setRegistrationListener(self, string: str, sipRegistrationListener: 'SipRegistrationListener') -> None: ...
    def takeAudioCall(self, intent: android.content.Intent, listener: SipAudioCall.Listener) -> SipAudioCall: ...
    def unregister(self, sipProfile: 'SipProfile', sipRegistrationListener: 'SipRegistrationListener') -> None: ...

class SipProfile(android.os.Parcelable, java.io.Serializable, java.lang.Cloneable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAuthUserName(self) -> str: ...
    def getAutoRegistration(self) -> bool: ...
    def getDisplayName(self) -> str: ...
    def getPassword(self) -> str: ...
    def getPort(self) -> int: ...
    def getProfileName(self) -> str: ...
    def getProtocol(self) -> str: ...
    def getProxyAddress(self) -> str: ...
    def getSendKeepAlive(self) -> bool: ...
    def getSipDomain(self) -> str: ...
    def getUriString(self) -> str: ...
    def getUserName(self) -> str: ...
    def setCallingUid(self, int: int) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, sipProfile: 'SipProfile'): ...
        @typing.overload
        def __init__(self, string: str): ...
        @typing.overload
        def __init__(self, string: str, string2: str): ...
        def build(self) -> 'SipProfile': ...
        def setAuthUserName(self, string: str) -> 'SipProfile.Builder': ...
        def setAutoRegistration(self, boolean: bool) -> 'SipProfile.Builder': ...
        def setDisplayName(self, string: str) -> 'SipProfile.Builder': ...
        def setOutboundProxy(self, string: str) -> 'SipProfile.Builder': ...
        def setPassword(self, string: str) -> 'SipProfile.Builder': ...
        def setPort(self, int: int) -> 'SipProfile.Builder': ...
        def setProfileName(self, string: str) -> 'SipProfile.Builder': ...
        def setProtocol(self, string: str) -> 'SipProfile.Builder': ...
        def setSendKeepAlive(self, boolean: bool) -> 'SipProfile.Builder': ...

class SipRegistrationListener:
    def onRegistering(self, string: str) -> None: ...
    def onRegistrationDone(self, string: str, long: int) -> None: ...
    def onRegistrationFailed(self, string: str, int: int, string2: str) -> None: ...

class SipSession:
    def answerCall(self, string: str, int: int) -> None: ...
    def changeCall(self, string: str, int: int) -> None: ...
    def endCall(self) -> None: ...
    def getCallId(self) -> str: ...
    def getLocalIp(self) -> str: ...
    def getLocalProfile(self) -> SipProfile: ...
    def getPeerProfile(self) -> SipProfile: ...
    def getState(self) -> int: ...
    def isInCall(self) -> bool: ...
    def makeCall(self, sipProfile: SipProfile, string: str, int: int) -> None: ...
    def register(self, int: int) -> None: ...
    def setListener(self, listener: 'SipSession.Listener') -> None: ...
    def unregister(self) -> None: ...
    class Listener:
        def __init__(self): ...
        def onCallBusy(self, sipSession: 'SipSession') -> None: ...
        def onCallChangeFailed(self, sipSession: 'SipSession', int: int, string: str) -> None: ...
        def onCallEnded(self, sipSession: 'SipSession') -> None: ...
        def onCallEstablished(self, sipSession: 'SipSession', string: str) -> None: ...
        def onCalling(self, sipSession: 'SipSession') -> None: ...
        def onError(self, sipSession: 'SipSession', int: int, string: str) -> None: ...
        def onRegistering(self, sipSession: 'SipSession') -> None: ...
        def onRegistrationDone(self, sipSession: 'SipSession', int: int) -> None: ...
        def onRegistrationFailed(self, sipSession: 'SipSession', int: int, string: str) -> None: ...
        def onRegistrationTimeout(self, sipSession: 'SipSession') -> None: ...
        def onRinging(self, sipSession: 'SipSession', sipProfile: SipProfile, string: str) -> None: ...
        def onRingingBack(self, sipSession: 'SipSession') -> None: ...
    class State:
        DEREGISTERING: typing.ClassVar[int] = ...
        INCOMING_CALL: typing.ClassVar[int] = ...
        INCOMING_CALL_ANSWERING: typing.ClassVar[int] = ...
        IN_CALL: typing.ClassVar[int] = ...
        NOT_DEFINED: typing.ClassVar[int] = ...
        OUTGOING_CALL: typing.ClassVar[int] = ...
        OUTGOING_CALL_CANCELING: typing.ClassVar[int] = ...
        OUTGOING_CALL_RING_BACK: typing.ClassVar[int] = ...
        PINGING: typing.ClassVar[int] = ...
        READY_TO_CALL: typing.ClassVar[int] = ...
        REGISTERING: typing.ClassVar[int] = ...
        @typing.overload
        def toString(self) -> str: ...
        @typing.overload
        @staticmethod
        def toString(int: int) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.sip")``.

    SipAudioCall: typing.Type[SipAudioCall]
    SipErrorCode: typing.Type[SipErrorCode]
    SipException: typing.Type[SipException]
    SipManager: typing.Type[SipManager]
    SipProfile: typing.Type[SipProfile]
    SipRegistrationListener: typing.Type[SipRegistrationListener]
    SipSession: typing.Type[SipSession]
