
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.os
import java.io
import jpype
import jpype.protocol
import typing



class BackupAgent(android.content.ContextWrapper):
    FLAG_CLIENT_SIDE_ENCRYPTION_ENABLED: typing.ClassVar[int] = ...
    FLAG_DEVICE_TO_DEVICE_TRANSFER: typing.ClassVar[int] = ...
    TYPE_DIRECTORY: typing.ClassVar[int] = ...
    TYPE_FILE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def fullBackupFile(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], fullBackupDataOutput: 'FullBackupDataOutput') -> None: ...
    def onBackup(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, backupDataOutput: 'BackupDataOutput', parcelFileDescriptor2: android.os.ParcelFileDescriptor) -> None: ...
    def onCreate(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onFullBackup(self, fullBackupDataOutput: 'FullBackupDataOutput') -> None: ...
    def onQuotaExceeded(self, long: int, long2: int) -> None: ...
    @typing.overload
    def onRestore(self, backupDataInput: 'BackupDataInput', int: int, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...
    @typing.overload
    def onRestore(self, backupDataInput: 'BackupDataInput', long: int, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...
    def onRestoreFile(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, long: int, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], int: int, long2: int, long3: int) -> None: ...
    def onRestoreFinished(self) -> None: ...

class BackupDataInput:
    def getDataSize(self) -> int: ...
    def getKey(self) -> str: ...
    def readEntityData(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    def readNextHeader(self) -> bool: ...
    def skipEntityData(self) -> None: ...

class BackupDataInputStream(java.io.InputStream):
    def getKey(self) -> str: ...
    @typing.overload
    def read(self) -> int: ...
    @typing.overload
    def read(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> int: ...
    @typing.overload
    def read(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    def size(self) -> int: ...

class BackupDataOutput:
    def getQuota(self) -> int: ...
    def getTransportFlags(self) -> int: ...
    def writeEntityData(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int) -> int: ...
    def writeEntityHeader(self, string: str, int: int) -> int: ...

class BackupHelper:
    def performBackup(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, backupDataOutput: BackupDataOutput, parcelFileDescriptor2: android.os.ParcelFileDescriptor) -> None: ...
    def restoreEntity(self, backupDataInputStream: BackupDataInputStream) -> None: ...
    def writeNewStateDescription(self, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...

class BackupManager:
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    @staticmethod
    def dataChanged(string: str) -> None: ...
    @typing.overload
    def dataChanged(self) -> None: ...
    def getUserForAncestralSerialNumber(self, long: int) -> android.os.UserHandle: ...
    def requestRestore(self, restoreObserver: 'RestoreObserver') -> int: ...

class FullBackupDataOutput:
    def getQuota(self) -> int: ...
    def getTransportFlags(self) -> int: ...

class RestoreObserver:
    def __init__(self): ...
    def onUpdate(self, int: int, string: str) -> None: ...
    def restoreFinished(self, int: int) -> None: ...
    def restoreStarting(self, int: int) -> None: ...

class BackupAgentHelper(BackupAgent):
    def __init__(self): ...
    def addHelper(self, string: str, backupHelper: BackupHelper) -> None: ...
    def onBackup(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, backupDataOutput: BackupDataOutput, parcelFileDescriptor2: android.os.ParcelFileDescriptor) -> None: ...
    @typing.overload
    def onRestore(self, backupDataInput: BackupDataInput, long: int, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...
    @typing.overload
    def onRestore(self, backupDataInput: BackupDataInput, int: int, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...

class FileBackupHelper(BackupHelper):
    def __init__(self, context: android.content.Context, *string: str): ...
    def performBackup(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, backupDataOutput: BackupDataOutput, parcelFileDescriptor2: android.os.ParcelFileDescriptor) -> None: ...
    def restoreEntity(self, backupDataInputStream: BackupDataInputStream) -> None: ...
    def writeNewStateDescription(self, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...

class SharedPreferencesBackupHelper(BackupHelper):
    def __init__(self, context: android.content.Context, *string: str): ...
    def performBackup(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, backupDataOutput: BackupDataOutput, parcelFileDescriptor2: android.os.ParcelFileDescriptor) -> None: ...
    def restoreEntity(self, backupDataInputStream: BackupDataInputStream) -> None: ...
    def writeNewStateDescription(self, parcelFileDescriptor: android.os.ParcelFileDescriptor) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.backup")``.

    BackupAgent: typing.Type[BackupAgent]
    BackupAgentHelper: typing.Type[BackupAgentHelper]
    BackupDataInput: typing.Type[BackupDataInput]
    BackupDataInputStream: typing.Type[BackupDataInputStream]
    BackupDataOutput: typing.Type[BackupDataOutput]
    BackupHelper: typing.Type[BackupHelper]
    BackupManager: typing.Type[BackupManager]
    FileBackupHelper: typing.Type[FileBackupHelper]
    FullBackupDataOutput: typing.Type[FullBackupDataOutput]
    RestoreObserver: typing.Type[RestoreObserver]
    SharedPreferencesBackupHelper: typing.Type[SharedPreferencesBackupHelper]
