
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import typing



class ProviderProperties(android.os.Parcelable):
    ACCURACY_COARSE: typing.ClassVar[int] = ...
    ACCURACY_FINE: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    POWER_USAGE_HIGH: typing.ClassVar[int] = ...
    POWER_USAGE_LOW: typing.ClassVar[int] = ...
    POWER_USAGE_MEDIUM: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAccuracy(self) -> int: ...
    def getPowerUsage(self) -> int: ...
    def hasAltitudeSupport(self) -> bool: ...
    def hasBearingSupport(self) -> bool: ...
    def hasCellRequirement(self) -> bool: ...
    def hasMonetaryCost(self) -> bool: ...
    def hasNetworkRequirement(self) -> bool: ...
    def hasSatelliteRequirement(self) -> bool: ...
    def hasSpeedSupport(self) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, providerProperties: 'ProviderProperties'): ...
        def build(self) -> 'ProviderProperties': ...
        def setAccuracy(self, int: int) -> 'ProviderProperties.Builder': ...
        def setHasAltitudeSupport(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setHasBearingSupport(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setHasCellRequirement(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setHasMonetaryCost(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setHasNetworkRequirement(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setHasSatelliteRequirement(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setHasSpeedSupport(self, boolean: bool) -> 'ProviderProperties.Builder': ...
        def setPowerUsage(self, int: int) -> 'ProviderProperties.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.location.provider")``.

    ProviderProperties: typing.Type[ProviderProperties]
