
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import typing



class ControlAction:
    RESPONSE_CHALLENGE_ACK: typing.ClassVar[int] = ...
    RESPONSE_CHALLENGE_PASSPHRASE: typing.ClassVar[int] = ...
    RESPONSE_CHALLENGE_PIN: typing.ClassVar[int] = ...
    RESPONSE_FAIL: typing.ClassVar[int] = ...
    RESPONSE_OK: typing.ClassVar[int] = ...
    RESPONSE_UNKNOWN: typing.ClassVar[int] = ...
    TYPE_BOOLEAN: typing.ClassVar[int] = ...
    TYPE_COMMAND: typing.ClassVar[int] = ...
    TYPE_ERROR: typing.ClassVar[int] = ...
    TYPE_FLOAT: typing.ClassVar[int] = ...
    TYPE_MODE: typing.ClassVar[int] = ...
    def getActionType(self) -> int: ...
    def getChallengeValue(self) -> str: ...
    @staticmethod
    def getErrorAction() -> 'ControlAction': ...
    def getTemplateId(self) -> str: ...
    @staticmethod
    def isValidResponse(int: int) -> bool: ...

class BooleanAction(ControlAction):
    @typing.overload
    def __init__(self, string: str, boolean: bool): ...
    @typing.overload
    def __init__(self, string: str, boolean: bool, string2: str): ...
    def getActionType(self) -> int: ...
    def getNewState(self) -> bool: ...

class CommandAction(ControlAction):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    def getActionType(self) -> int: ...

class FloatAction(ControlAction):
    @typing.overload
    def __init__(self, string: str, float: float): ...
    @typing.overload
    def __init__(self, string: str, float: float, string2: str): ...
    def getActionType(self) -> int: ...
    def getNewValue(self) -> float: ...

class ModeAction(ControlAction):
    @typing.overload
    def __init__(self, string: str, int: int): ...
    @typing.overload
    def __init__(self, string: str, int: int, string2: str): ...
    def getActionType(self) -> int: ...
    def getNewMode(self) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.controls.actions")``.

    BooleanAction: typing.Type[BooleanAction]
    CommandAction: typing.Type[CommandAction]
    ControlAction: typing.Type[ControlAction]
    FloatAction: typing.Type[FloatAction]
    ModeAction: typing.Type[ModeAction]
