
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.view.inputmethod
import android.widget
import java.lang
import java.time
import java.util
import jpype
import typing



class AbstractInputMethodService(android.app.Service, android.view.KeyEvent.Callback):
    def __init__(self): ...
    def getKeyDispatcherState(self) -> android.view.KeyEvent.DispatcherState: ...
    _getSystemService_0__T = typing.TypeVar('_getSystemService_0__T')  # <T>
    @typing.overload
    def getSystemService(self, class_: typing.Type[_getSystemService_0__T]) -> _getSystemService_0__T: ...
    @typing.overload
    def getSystemService(self, string: str) -> typing.Any: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onConfigurationChanged(self, configuration: android.content.res.Configuration) -> None: ...
    def onCreateInputMethodInterface(self) -> 'AbstractInputMethodService.AbstractInputMethodImpl': ...
    def onCreateInputMethodSessionInterface(self) -> 'AbstractInputMethodService.AbstractInputMethodSessionImpl': ...
    def onDestroy(self) -> None: ...
    def onGenericMotionEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onLowMemory(self) -> None: ...
    def onTrackballEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onTrimMemory(self, int: int) -> None: ...
    def registerComponentCallbacks(self, componentCallbacks: android.content.ComponentCallbacks) -> None: ...
    def unregisterComponentCallbacks(self, componentCallbacks: android.content.ComponentCallbacks) -> None: ...
    class AbstractInputMethodImpl(android.view.inputmethod.InputMethod):
        def __init__(self, abstractInputMethodService: 'AbstractInputMethodService'): ...
        def createSession(self, sessionCallback: typing.Union[android.view.inputmethod.InputMethod.SessionCallback, typing.Callable]) -> None: ...
        def revokeSession(self, inputMethodSession: android.view.inputmethod.InputMethodSession) -> None: ...
        def setSessionEnabled(self, inputMethodSession: android.view.inputmethod.InputMethodSession, boolean: bool) -> None: ...
    class AbstractInputMethodSessionImpl(android.view.inputmethod.InputMethodSession):
        def __init__(self, abstractInputMethodService: 'AbstractInputMethodService'): ...
        def dispatchGenericMotionEvent(self, int: int, motionEvent: android.view.MotionEvent, eventCallback: typing.Union[android.view.inputmethod.InputMethodSession.EventCallback, typing.Callable]) -> None: ...
        def dispatchKeyEvent(self, int: int, keyEvent: android.view.KeyEvent, eventCallback: typing.Union[android.view.inputmethod.InputMethodSession.EventCallback, typing.Callable]) -> None: ...
        def dispatchTrackballEvent(self, int: int, motionEvent: android.view.MotionEvent, eventCallback: typing.Union[android.view.inputmethod.InputMethodSession.EventCallback, typing.Callable]) -> None: ...
        def isEnabled(self) -> bool: ...
        def isRevoked(self) -> bool: ...
        def revokeSelf(self) -> None: ...
        def setEnabled(self, boolean: bool) -> None: ...

class ExtractEditText(android.widget.EditText):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def finishInternalChanges(self) -> None: ...
    def hasFocus(self) -> bool: ...
    def hasVerticalScrollBar(self) -> bool: ...
    def hasWindowFocus(self) -> bool: ...
    def isFocused(self) -> bool: ...
    def isInputMethodTarget(self) -> bool: ...
    def onTextContextMenuItem(self, int: int) -> bool: ...
    def performClick(self) -> bool: ...
    def setExtractedText(self, extractedText: android.view.inputmethod.ExtractedText) -> None: ...
    def startInternalChanges(self) -> None: ...

class Keyboard:
    EDGE_BOTTOM: typing.ClassVar[int] = ...
    EDGE_LEFT: typing.ClassVar[int] = ...
    EDGE_RIGHT: typing.ClassVar[int] = ...
    EDGE_TOP: typing.ClassVar[int] = ...
    KEYCODE_ALT: typing.ClassVar[int] = ...
    KEYCODE_CANCEL: typing.ClassVar[int] = ...
    KEYCODE_DELETE: typing.ClassVar[int] = ...
    KEYCODE_DONE: typing.ClassVar[int] = ...
    KEYCODE_MODE_CHANGE: typing.ClassVar[int] = ...
    KEYCODE_SHIFT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int, int2: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int, int2: int, int3: int, int4: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int, charSequence: typing.Union[java.lang.CharSequence, str], int2: int, int3: int): ...
    def getHeight(self) -> int: ...
    def getKeys(self) -> java.util.List['Keyboard.Key']: ...
    def getMinWidth(self) -> int: ...
    def getModifierKeys(self) -> java.util.List['Keyboard.Key']: ...
    def getNearestKeys(self, int: int, int2: int) -> typing.MutableSequence[int]: ...
    def getShiftKeyIndex(self) -> int: ...
    def isShifted(self) -> bool: ...
    def setShifted(self, boolean: bool) -> bool: ...
    class Key:
        codes: typing.MutableSequence[int] = ...
        edgeFlags: int = ...
        gap: int = ...
        height: int = ...
        icon: android.graphics.drawable.Drawable = ...
        iconPreview: android.graphics.drawable.Drawable = ...
        label: java.lang.CharSequence = ...
        modifier: bool = ...
        on: bool = ...
        popupCharacters: java.lang.CharSequence = ...
        popupResId: int = ...
        pressed: bool = ...
        repeatable: bool = ...
        sticky: bool = ...
        text: java.lang.CharSequence = ...
        width: int = ...
        x: int = ...
        y: int = ...
        @typing.overload
        def __init__(self, resources: android.content.res.Resources, row: 'Keyboard.Row', int: int, int2: int, xmlResourceParser: android.content.res.XmlResourceParser): ...
        @typing.overload
        def __init__(self, row: 'Keyboard.Row'): ...
        def getCurrentDrawableState(self) -> typing.MutableSequence[int]: ...
        def isInside(self, int: int, int2: int) -> bool: ...
        def onPressed(self) -> None: ...
        def onReleased(self, boolean: bool) -> None: ...
        def squaredDistanceFrom(self, int: int, int2: int) -> int: ...
    class Row:
        defaultHeight: int = ...
        defaultHorizontalGap: int = ...
        defaultWidth: int = ...
        mode: int = ...
        rowEdgeFlags: int = ...
        verticalGap: int = ...
        @typing.overload
        def __init__(self, resources: android.content.res.Resources, keyboard: 'Keyboard', xmlResourceParser: android.content.res.XmlResourceParser): ...
        @typing.overload
        def __init__(self, keyboard: 'Keyboard'): ...

class KeyboardView(android.view.View, android.view.View.OnClickListener):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def closing(self) -> None: ...
    def getKeyboard(self) -> Keyboard: ...
    def handleBack(self) -> bool: ...
    def invalidateAllKeys(self) -> None: ...
    def invalidateKey(self, int: int) -> None: ...
    def isPreviewEnabled(self) -> bool: ...
    def isProximityCorrectionEnabled(self) -> bool: ...
    def isShifted(self) -> bool: ...
    def onClick(self, view: android.view.View) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas) -> None: ...
    def onHoverEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onMeasure(self, int: int, int2: int) -> None: ...
    def onSizeChanged(self, int: int, int2: int, int3: int, int4: int) -> None: ...
    def onTouchEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def setKeyboard(self, keyboard: Keyboard) -> None: ...
    def setOnKeyboardActionListener(self, onKeyboardActionListener: 'KeyboardView.OnKeyboardActionListener') -> None: ...
    def setPopupOffset(self, int: int, int2: int) -> None: ...
    def setPopupParent(self, view: android.view.View) -> None: ...
    def setPreviewEnabled(self, boolean: bool) -> None: ...
    def setProximityCorrectionEnabled(self, boolean: bool) -> None: ...
    def setShifted(self, boolean: bool) -> bool: ...
    def setVerticalCorrection(self, int: int) -> None: ...
    class OnKeyboardActionListener:
        def onKey(self, int: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
        def onPress(self, int: int) -> None: ...
        def onRelease(self, int: int) -> None: ...
        def onText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
        def swipeDown(self) -> None: ...
        def swipeLeft(self) -> None: ...
        def swipeRight(self) -> None: ...
        def swipeUp(self) -> None: ...

class InputMethodService(AbstractInputMethodService):
    BACK_DISPOSITION_ADJUST_NOTHING: typing.ClassVar[int] = ...
    BACK_DISPOSITION_DEFAULT: typing.ClassVar[int] = ...
    BACK_DISPOSITION_WILL_DISMISS: typing.ClassVar[int] = ...
    BACK_DISPOSITION_WILL_NOT_DISMISS: typing.ClassVar[int] = ...
    def __init__(self): ...
    def enableHardwareAcceleration(self) -> bool: ...
    def finishConnectionlessStylusHandwriting(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def finishStylusHandwriting(self) -> None: ...
    def getBackDisposition(self) -> int: ...
    def getCandidatesHiddenVisibility(self) -> int: ...
    def getCurrentInputBinding(self) -> android.view.inputmethod.InputBinding: ...
    def getCurrentInputConnection(self) -> android.view.inputmethod.InputConnection: ...
    def getCurrentInputEditorInfo(self) -> android.view.inputmethod.EditorInfo: ...
    def getCurrentInputStarted(self) -> bool: ...
    def getInputMethodWindowRecommendedHeight(self) -> int: ...
    def getLayoutInflater(self) -> android.view.LayoutInflater: ...
    def getMaxWidth(self) -> int: ...
    @staticmethod
    def getStylusHandwritingIdleTimeoutMax() -> java.time.Duration: ...
    def getStylusHandwritingSessionTimeout(self) -> java.time.Duration: ...
    def getStylusHandwritingWindow(self) -> android.view.Window: ...
    _getSystemService_0__T = typing.TypeVar('_getSystemService_0__T')  # <T>
    @typing.overload
    def getSystemService(self, class_: typing.Type[_getSystemService_0__T]) -> _getSystemService_0__T: ...
    @typing.overload
    def getSystemService(self, string: str) -> typing.Any: ...
    def getTextForImeAction(self, int: int) -> java.lang.CharSequence: ...
    def getWindow(self) -> android.app.Dialog: ...
    def hideStatusIcon(self) -> None: ...
    def hideWindow(self) -> None: ...
    def isExtractViewShown(self) -> bool: ...
    def isFullscreenMode(self) -> bool: ...
    def isInputViewShown(self) -> bool: ...
    def isShowInputRequested(self) -> bool: ...
    def onAppPrivateCommand(self, string: str, bundle: android.os.Bundle) -> None: ...
    def onBindInput(self) -> None: ...
    def onComputeInsets(self, insets: 'InputMethodService.Insets') -> None: ...
    def onConfigurationChanged(self, configuration: android.content.res.Configuration) -> None: ...
    def onConfigureWindow(self, window: android.view.Window, boolean: bool, boolean2: bool) -> None: ...
    def onCreate(self) -> None: ...
    def onCreateCandidatesView(self) -> android.view.View: ...
    def onCreateExtractTextView(self) -> android.view.View: ...
    def onCreateInlineSuggestionsRequest(self, bundle: android.os.Bundle) -> android.view.inputmethod.InlineSuggestionsRequest: ...
    def onCreateInputMethodInterface(self) -> AbstractInputMethodService.AbstractInputMethodImpl: ...
    def onCreateInputMethodSessionInterface(self) -> AbstractInputMethodService.AbstractInputMethodSessionImpl: ...
    def onCreateInputView(self) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onDisplayCompletions(self, completionInfoArray: typing.Union[typing.List[android.view.inputmethod.CompletionInfo], jpype.JArray]) -> None: ...
    def onEvaluateFullscreenMode(self) -> bool: ...
    def onEvaluateInputViewShown(self) -> bool: ...
    def onExtractTextContextMenuItem(self, int: int) -> bool: ...
    def onExtractedCursorMovement(self, int: int, int2: int) -> None: ...
    def onExtractedSelectionChanged(self, int: int, int2: int) -> None: ...
    def onExtractedTextClicked(self) -> None: ...
    def onExtractingInputChanged(self, editorInfo: android.view.inputmethod.EditorInfo) -> None: ...
    def onFinishCandidatesView(self, boolean: bool) -> None: ...
    def onFinishInput(self) -> None: ...
    def onFinishInputView(self, boolean: bool) -> None: ...
    def onFinishStylusHandwriting(self) -> None: ...
    def onGenericMotionEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onInitializeInterface(self) -> None: ...
    def onInlineSuggestionsResponse(self, inlineSuggestionsResponse: android.view.inputmethod.InlineSuggestionsResponse) -> bool: ...
    def onKeyDown(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyLongPress(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyMultiple(self, int: int, int2: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onPrepareStylusHandwriting(self) -> None: ...
    def onShowInputRequested(self, int: int, boolean: bool) -> bool: ...
    def onStartCandidatesView(self, editorInfo: android.view.inputmethod.EditorInfo, boolean: bool) -> None: ...
    def onStartConnectionlessStylusHandwriting(self, int: int, cursorAnchorInfo: android.view.inputmethod.CursorAnchorInfo) -> bool: ...
    def onStartInput(self, editorInfo: android.view.inputmethod.EditorInfo, boolean: bool) -> None: ...
    def onStartInputView(self, editorInfo: android.view.inputmethod.EditorInfo, boolean: bool) -> None: ...
    def onStartStylusHandwriting(self) -> bool: ...
    def onStylusHandwritingMotionEvent(self, motionEvent: android.view.MotionEvent) -> None: ...
    def onTrackballEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def onUnbindInput(self) -> None: ...
    def onUpdateCursor(self, rect: android.graphics.Rect) -> None: ...
    def onUpdateCursorAnchorInfo(self, cursorAnchorInfo: android.view.inputmethod.CursorAnchorInfo) -> None: ...
    def onUpdateEditorToolType(self, int: int) -> None: ...
    def onUpdateExtractedText(self, int: int, extractedText: android.view.inputmethod.ExtractedText) -> None: ...
    def onUpdateExtractingViews(self, editorInfo: android.view.inputmethod.EditorInfo) -> None: ...
    def onUpdateExtractingVisibility(self, editorInfo: android.view.inputmethod.EditorInfo) -> None: ...
    def onUpdateSelection(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int) -> None: ...
    def onViewClicked(self, boolean: bool) -> None: ...
    def onWindowHidden(self) -> None: ...
    def onWindowShown(self) -> None: ...
    def requestHideSelf(self, int: int) -> None: ...
    def requestShowSelf(self, int: int) -> None: ...
    def sendDefaultEditorAction(self, boolean: bool) -> bool: ...
    def sendDownUpKeyEvents(self, int: int) -> None: ...
    def sendKeyChar(self, char: str) -> None: ...
    def setBackDisposition(self, int: int) -> None: ...
    def setCandidatesView(self, view: android.view.View) -> None: ...
    def setCandidatesViewShown(self, boolean: bool) -> None: ...
    def setExtractView(self, view: android.view.View) -> None: ...
    def setExtractViewShown(self, boolean: bool) -> None: ...
    def setInputView(self, view: android.view.View) -> None: ...
    def setStylusHandwritingSessionTimeout(self, duration: java.time.Duration) -> None: ...
    def setTheme(self, int: int) -> None: ...
    def shouldOfferSwitchingToNextInputMethod(self) -> bool: ...
    def showStatusIcon(self, int: int) -> None: ...
    def showWindow(self, boolean: bool) -> None: ...
    @typing.overload
    def switchInputMethod(self, string: str, inputMethodSubtype: android.view.inputmethod.InputMethodSubtype) -> None: ...
    @typing.overload
    def switchInputMethod(self, string: str) -> None: ...
    def switchToNextInputMethod(self, boolean: bool) -> bool: ...
    def switchToPreviousInputMethod(self) -> bool: ...
    def updateFullscreenMode(self) -> None: ...
    def updateInputViewShown(self) -> None: ...
    class InputMethodImpl(AbstractInputMethodService.AbstractInputMethodImpl):
        def __init__(self, inputMethodService: 'InputMethodService'): ...
        def attachToken(self, iBinder: android.os.IBinder) -> None: ...
        def bindInput(self, inputBinding: android.view.inputmethod.InputBinding) -> None: ...
        def changeInputMethodSubtype(self, inputMethodSubtype: android.view.inputmethod.InputMethodSubtype) -> None: ...
        def hideSoftInput(self, int: int, resultReceiver: android.os.ResultReceiver) -> None: ...
        def restartInput(self, inputConnection: android.view.inputmethod.InputConnection, editorInfo: android.view.inputmethod.EditorInfo) -> None: ...
        def showSoftInput(self, int: int, resultReceiver: android.os.ResultReceiver) -> None: ...
        def startInput(self, inputConnection: android.view.inputmethod.InputConnection, editorInfo: android.view.inputmethod.EditorInfo) -> None: ...
        def unbindInput(self) -> None: ...
    class InputMethodSessionImpl(AbstractInputMethodService.AbstractInputMethodSessionImpl):
        def __init__(self, inputMethodService: 'InputMethodService'): ...
        def appPrivateCommand(self, string: str, bundle: android.os.Bundle) -> None: ...
        def displayCompletions(self, completionInfoArray: typing.Union[typing.List[android.view.inputmethod.CompletionInfo], jpype.JArray]) -> None: ...
        def finishInput(self) -> None: ...
        def toggleSoftInput(self, int: int, int2: int) -> None: ...
        def updateCursor(self, rect: android.graphics.Rect) -> None: ...
        def updateCursorAnchorInfo(self, cursorAnchorInfo: android.view.inputmethod.CursorAnchorInfo) -> None: ...
        def updateExtractedText(self, int: int, extractedText: android.view.inputmethod.ExtractedText) -> None: ...
        def updateSelection(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int) -> None: ...
        def viewClicked(self, boolean: bool) -> None: ...
    class Insets:
        TOUCHABLE_INSETS_CONTENT: typing.ClassVar[int] = ...
        TOUCHABLE_INSETS_FRAME: typing.ClassVar[int] = ...
        TOUCHABLE_INSETS_REGION: typing.ClassVar[int] = ...
        TOUCHABLE_INSETS_VISIBLE: typing.ClassVar[int] = ...
        contentTopInsets: int = ...
        touchableInsets: int = ...
        touchableRegion: android.graphics.Region = ...
        visibleTopInsets: int = ...
        def __init__(self): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.inputmethodservice")``.

    AbstractInputMethodService: typing.Type[AbstractInputMethodService]
    ExtractEditText: typing.Type[ExtractEditText]
    InputMethodService: typing.Type[InputMethodService]
    Keyboard: typing.Type[Keyboard]
    KeyboardView: typing.Type[KeyboardView]
