
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.bluetooth
import android.content
import android.os
import java.io
import java.util
import java.util.concurrent
import jpype
import typing



class MidiDevice(java.io.Closeable):
    def close(self) -> None: ...
    def connectPorts(self, midiInputPort: 'MidiInputPort', int: int) -> 'MidiDevice.MidiConnection': ...
    def getInfo(self) -> 'MidiDeviceInfo': ...
    def openInputPort(self, int: int) -> 'MidiInputPort': ...
    def openOutputPort(self, int: int) -> 'MidiOutputPort': ...
    def toString(self) -> str: ...
    class MidiConnection(java.io.Closeable):
        def close(self) -> None: ...

class MidiDeviceInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PROPERTY_BLUETOOTH_DEVICE: typing.ClassVar[str] = ...
    PROPERTY_MANUFACTURER: typing.ClassVar[str] = ...
    PROPERTY_NAME: typing.ClassVar[str] = ...
    PROPERTY_PRODUCT: typing.ClassVar[str] = ...
    PROPERTY_SERIAL_NUMBER: typing.ClassVar[str] = ...
    PROPERTY_USB_DEVICE: typing.ClassVar[str] = ...
    PROPERTY_VERSION: typing.ClassVar[str] = ...
    PROTOCOL_UMP_MIDI_1_0_UP_TO_128_BITS: typing.ClassVar[int] = ...
    PROTOCOL_UMP_MIDI_1_0_UP_TO_128_BITS_AND_JRTS: typing.ClassVar[int] = ...
    PROTOCOL_UMP_MIDI_1_0_UP_TO_64_BITS: typing.ClassVar[int] = ...
    PROTOCOL_UMP_MIDI_1_0_UP_TO_64_BITS_AND_JRTS: typing.ClassVar[int] = ...
    PROTOCOL_UMP_MIDI_2_0: typing.ClassVar[int] = ...
    PROTOCOL_UMP_MIDI_2_0_AND_JRTS: typing.ClassVar[int] = ...
    PROTOCOL_UMP_USE_MIDI_CI: typing.ClassVar[int] = ...
    PROTOCOL_UNKNOWN: typing.ClassVar[int] = ...
    TYPE_BLUETOOTH: typing.ClassVar[int] = ...
    TYPE_USB: typing.ClassVar[int] = ...
    TYPE_VIRTUAL: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDefaultProtocol(self) -> int: ...
    def getId(self) -> int: ...
    def getInputPortCount(self) -> int: ...
    def getOutputPortCount(self) -> int: ...
    def getPorts(self) -> typing.MutableSequence['MidiDeviceInfo.PortInfo']: ...
    def getProperties(self) -> android.os.Bundle: ...
    def getType(self) -> int: ...
    def hashCode(self) -> int: ...
    def isPrivate(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class PortInfo:
        TYPE_INPUT: typing.ClassVar[int] = ...
        TYPE_OUTPUT: typing.ClassVar[int] = ...
        def getName(self) -> str: ...
        def getPortNumber(self) -> int: ...
        def getType(self) -> int: ...

class MidiDeviceService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def getDeviceInfo(self) -> MidiDeviceInfo: ...
    def getOutputPortReceivers(self) -> typing.MutableSequence['MidiReceiver']: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onClose(self) -> None: ...
    def onCreate(self) -> None: ...
    def onDeviceStatusChanged(self, midiDeviceStatus: 'MidiDeviceStatus') -> None: ...
    def onGetInputPortReceivers(self) -> typing.MutableSequence['MidiReceiver']: ...

class MidiDeviceStatus(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDeviceInfo(self) -> MidiDeviceInfo: ...
    def getOutputPortOpenCount(self, int: int) -> int: ...
    def isInputPortOpen(self, int: int) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class MidiManager:
    TRANSPORT_MIDI_BYTE_STREAM: typing.ClassVar[int] = ...
    TRANSPORT_UNIVERSAL_MIDI_PACKETS: typing.ClassVar[int] = ...
    def getDevices(self) -> typing.MutableSequence[MidiDeviceInfo]: ...
    def getDevicesForTransport(self, int: int) -> java.util.Set[MidiDeviceInfo]: ...
    def openBluetoothDevice(self, bluetoothDevice: android.bluetooth.BluetoothDevice, onDeviceOpenedListener: typing.Union['MidiManager.OnDeviceOpenedListener', typing.Callable], handler: android.os.Handler) -> None: ...
    def openDevice(self, midiDeviceInfo: MidiDeviceInfo, onDeviceOpenedListener: typing.Union['MidiManager.OnDeviceOpenedListener', typing.Callable], handler: android.os.Handler) -> None: ...
    @typing.overload
    def registerDeviceCallback(self, deviceCallback: 'MidiManager.DeviceCallback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def registerDeviceCallback(self, int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], deviceCallback: 'MidiManager.DeviceCallback') -> None: ...
    def unregisterDeviceCallback(self, deviceCallback: 'MidiManager.DeviceCallback') -> None: ...
    class DeviceCallback:
        def __init__(self): ...
        def onDeviceAdded(self, midiDeviceInfo: MidiDeviceInfo) -> None: ...
        def onDeviceRemoved(self, midiDeviceInfo: MidiDeviceInfo) -> None: ...
        def onDeviceStatusChanged(self, midiDeviceStatus: MidiDeviceStatus) -> None: ...
    class OnDeviceOpenedListener:
        def onDeviceOpened(self, midiDevice: MidiDevice) -> None: ...

class MidiReceiver:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def flush(self) -> None: ...
    def getMaxMessageSize(self) -> int: ...
    def onFlush(self) -> None: ...
    def onSend(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, long: int) -> None: ...
    @typing.overload
    def send(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> None: ...
    @typing.overload
    def send(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, long: int) -> None: ...

class MidiSender:
    def __init__(self): ...
    def connect(self, midiReceiver: MidiReceiver) -> None: ...
    def disconnect(self, midiReceiver: MidiReceiver) -> None: ...
    def onConnect(self, midiReceiver: MidiReceiver) -> None: ...
    def onDisconnect(self, midiReceiver: MidiReceiver) -> None: ...

class MidiUmpDeviceService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def getDeviceInfo(self) -> MidiDeviceInfo: ...
    def getOutputPortReceivers(self) -> java.util.List[MidiReceiver]: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onClose(self) -> None: ...
    def onCreate(self) -> None: ...
    def onDeviceStatusChanged(self, midiDeviceStatus: MidiDeviceStatus) -> None: ...
    def onGetInputPortReceivers(self) -> java.util.List[MidiReceiver]: ...

class MidiInputPort(MidiReceiver, java.io.Closeable):
    def close(self) -> None: ...
    def getPortNumber(self) -> int: ...
    def onFlush(self) -> None: ...
    def onSend(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, long: int) -> None: ...

class MidiOutputPort(MidiSender, java.io.Closeable):
    def close(self) -> None: ...
    def getPortNumber(self) -> int: ...
    def onConnect(self, midiReceiver: MidiReceiver) -> None: ...
    def onDisconnect(self, midiReceiver: MidiReceiver) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.midi")``.

    MidiDevice: typing.Type[MidiDevice]
    MidiDeviceInfo: typing.Type[MidiDeviceInfo]
    MidiDeviceService: typing.Type[MidiDeviceService]
    MidiDeviceStatus: typing.Type[MidiDeviceStatus]
    MidiInputPort: typing.Type[MidiInputPort]
    MidiManager: typing.Type[MidiManager]
    MidiOutputPort: typing.Type[MidiOutputPort]
    MidiReceiver: typing.Type[MidiReceiver]
    MidiSender: typing.Type[MidiSender]
    MidiUmpDeviceService: typing.Type[MidiUmpDeviceService]
