
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.pm
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.widget
import java.lang
import java.util
import java.util.concurrent
import jpype
import typing



class AppWidgetHost:
    def __init__(self, context: android.content.Context, int: int): ...
    def allocateAppWidgetId(self) -> int: ...
    def createView(self, context: android.content.Context, int: int, appWidgetProviderInfo: 'AppWidgetProviderInfo') -> 'AppWidgetHostView': ...
    @staticmethod
    def deleteAllHosts() -> None: ...
    def deleteAppWidgetId(self, int: int) -> None: ...
    def deleteHost(self) -> None: ...
    def getAppWidgetIds(self) -> typing.MutableSequence[int]: ...
    def onAppWidgetRemoved(self, int: int) -> None: ...
    def startAppWidgetConfigureActivityForResult(self, activity: android.app.Activity, int: int, int2: int, int3: int, bundle: android.os.Bundle) -> None: ...
    def startListening(self) -> None: ...
    def stopListening(self) -> None: ...

class AppWidgetHostView(android.widget.FrameLayout):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int, int2: int): ...
    def generateLayoutParams(self, attributeSet: android.util.AttributeSet) -> android.widget.FrameLayout.LayoutParams: ...
    def getAppWidgetId(self) -> int: ...
    def getAppWidgetInfo(self) -> 'AppWidgetProviderInfo': ...
    @staticmethod
    def getDefaultPaddingForWidget(context: android.content.Context, componentName: android.content.ComponentName, rect: android.graphics.Rect) -> android.graphics.Rect: ...
    def resetColorResources(self) -> None: ...
    def setAppWidget(self, int: int, appWidgetProviderInfo: 'AppWidgetProviderInfo') -> None: ...
    def setColorResources(self, sparseIntArray: android.util.SparseIntArray) -> None: ...
    def setExecutor(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable]) -> None: ...
    def setOnLightBackground(self, boolean: bool) -> None: ...
    def updateAppWidget(self, remoteViews: android.widget.RemoteViews) -> None: ...
    def updateAppWidgetOptions(self, bundle: android.os.Bundle) -> None: ...
    @typing.overload
    def updateAppWidgetSize(self, bundle: android.os.Bundle, int: int, int2: int, int3: int, int4: int) -> None: ...
    @typing.overload
    def updateAppWidgetSize(self, bundle: android.os.Bundle, list: java.util.List[android.util.SizeF]) -> None: ...

class AppWidgetManager:
    ACTION_APPWIDGET_BIND: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_CONFIGURE: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_DELETED: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_DISABLED: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_ENABLED: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_HOST_RESTORED: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_OPTIONS_CHANGED: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_PICK: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_RESTORED: typing.ClassVar[str] = ...
    ACTION_APPWIDGET_UPDATE: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_ID: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_IDS: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_OLD_IDS: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_OPTIONS: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_PREVIEW: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_PROVIDER: typing.ClassVar[str] = ...
    EXTRA_APPWIDGET_PROVIDER_PROFILE: typing.ClassVar[str] = ...
    EXTRA_CUSTOM_EXTRAS: typing.ClassVar[str] = ...
    EXTRA_CUSTOM_INFO: typing.ClassVar[str] = ...
    EXTRA_HOST_ID: typing.ClassVar[str] = ...
    INVALID_APPWIDGET_ID: typing.ClassVar[int] = ...
    META_DATA_APPWIDGET_PROVIDER: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_HOST_CATEGORY: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_MAX_HEIGHT: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_MAX_WIDTH: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_MIN_HEIGHT: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_MIN_WIDTH: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_RESTORE_COMPLETED: typing.ClassVar[str] = ...
    OPTION_APPWIDGET_SIZES: typing.ClassVar[str] = ...
    @typing.overload
    def bindAppWidgetIdIfAllowed(self, int: int, componentName: android.content.ComponentName) -> bool: ...
    @typing.overload
    def bindAppWidgetIdIfAllowed(self, int: int, componentName: android.content.ComponentName, bundle: android.os.Bundle) -> bool: ...
    @typing.overload
    def bindAppWidgetIdIfAllowed(self, int: int, userHandle: android.os.UserHandle, componentName: android.content.ComponentName, bundle: android.os.Bundle) -> bool: ...
    def getAppWidgetIds(self, componentName: android.content.ComponentName) -> typing.MutableSequence[int]: ...
    def getAppWidgetInfo(self, int: int) -> 'AppWidgetProviderInfo': ...
    def getAppWidgetOptions(self, int: int) -> android.os.Bundle: ...
    def getInstalledProviders(self) -> java.util.List['AppWidgetProviderInfo']: ...
    def getInstalledProvidersForPackage(self, string: str, userHandle: android.os.UserHandle) -> java.util.List['AppWidgetProviderInfo']: ...
    def getInstalledProvidersForProfile(self, userHandle: android.os.UserHandle) -> java.util.List['AppWidgetProviderInfo']: ...
    @staticmethod
    def getInstance(context: android.content.Context) -> 'AppWidgetManager': ...
    def getWidgetPreview(self, componentName: android.content.ComponentName, userHandle: android.os.UserHandle, int: int) -> android.widget.RemoteViews: ...
    def isRequestPinAppWidgetSupported(self) -> bool: ...
    @typing.overload
    def notifyAppWidgetViewDataChanged(self, int: int, int2: int) -> None: ...
    @typing.overload
    def notifyAppWidgetViewDataChanged(self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int) -> None: ...
    @typing.overload
    def partiallyUpdateAppWidget(self, int: int, remoteViews: android.widget.RemoteViews) -> None: ...
    @typing.overload
    def partiallyUpdateAppWidget(self, intArray: typing.Union[typing.List[int], jpype.JArray], remoteViews: android.widget.RemoteViews) -> None: ...
    def removeWidgetPreview(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def requestPinAppWidget(self, componentName: android.content.ComponentName, bundle: android.os.Bundle, pendingIntent: android.app.PendingIntent) -> bool: ...
    def setWidgetPreview(self, componentName: android.content.ComponentName, int: int, remoteViews: android.widget.RemoteViews) -> bool: ...
    @typing.overload
    def updateAppWidget(self, componentName: android.content.ComponentName, remoteViews: android.widget.RemoteViews) -> None: ...
    @typing.overload
    def updateAppWidget(self, int: int, remoteViews: android.widget.RemoteViews) -> None: ...
    @typing.overload
    def updateAppWidget(self, intArray: typing.Union[typing.List[int], jpype.JArray], remoteViews: android.widget.RemoteViews) -> None: ...
    def updateAppWidgetOptions(self, int: int, bundle: android.os.Bundle) -> None: ...
    def updateAppWidgetProviderInfo(self, componentName: android.content.ComponentName, string: str) -> None: ...

class AppWidgetProvider(android.content.BroadcastReceiver):
    def __init__(self): ...
    def onAppWidgetOptionsChanged(self, context: android.content.Context, appWidgetManager: AppWidgetManager, int: int, bundle: android.os.Bundle) -> None: ...
    def onDeleted(self, context: android.content.Context, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def onDisabled(self, context: android.content.Context) -> None: ...
    def onEnabled(self, context: android.content.Context) -> None: ...
    def onReceive(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onRestored(self, context: android.content.Context, intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def onUpdate(self, context: android.content.Context, appWidgetManager: AppWidgetManager, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...

class AppWidgetProviderInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RESIZE_BOTH: typing.ClassVar[int] = ...
    RESIZE_HORIZONTAL: typing.ClassVar[int] = ...
    RESIZE_NONE: typing.ClassVar[int] = ...
    RESIZE_VERTICAL: typing.ClassVar[int] = ...
    WIDGET_CATEGORY_HOME_SCREEN: typing.ClassVar[int] = ...
    WIDGET_CATEGORY_KEYGUARD: typing.ClassVar[int] = ...
    WIDGET_CATEGORY_SEARCHBOX: typing.ClassVar[int] = ...
    WIDGET_FEATURE_CONFIGURATION_OPTIONAL: typing.ClassVar[int] = ...
    WIDGET_FEATURE_HIDE_FROM_PICKER: typing.ClassVar[int] = ...
    WIDGET_FEATURE_RECONFIGURABLE: typing.ClassVar[int] = ...
    autoAdvanceViewId: int = ...
    configure: android.content.ComponentName = ...
    descriptionRes: int = ...
    generatedPreviewCategories: int = ...
    icon: int = ...
    initialKeyguardLayout: int = ...
    initialLayout: int = ...
    label: str = ...
    maxResizeHeight: int = ...
    maxResizeWidth: int = ...
    minHeight: int = ...
    minResizeHeight: int = ...
    minResizeWidth: int = ...
    minWidth: int = ...
    previewImage: int = ...
    previewLayout: int = ...
    provider: android.content.ComponentName = ...
    resizeMode: int = ...
    targetCellHeight: int = ...
    targetCellWidth: int = ...
    updatePeriodMillis: int = ...
    widgetCategory: int = ...
    widgetFeatures: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def clone(self) -> 'AppWidgetProviderInfo': ...
    def describeContents(self) -> int: ...
    def getActivityInfo(self) -> android.content.pm.ActivityInfo: ...
    def getProfile(self) -> android.os.UserHandle: ...
    def loadDescription(self, context: android.content.Context) -> java.lang.CharSequence: ...
    def loadIcon(self, context: android.content.Context, int: int) -> android.graphics.drawable.Drawable: ...
    def loadLabel(self, packageManager: android.content.pm.PackageManager) -> str: ...
    def loadPreviewImage(self, context: android.content.Context, int: int) -> android.graphics.drawable.Drawable: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.appwidget")``.

    AppWidgetHost: typing.Type[AppWidgetHost]
    AppWidgetHostView: typing.Type[AppWidgetHostView]
    AppWidgetManager: typing.Type[AppWidgetManager]
    AppWidgetProvider: typing.Type[AppWidgetProvider]
    AppWidgetProviderInfo: typing.Type[AppWidgetProviderInfo]
