
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.net
import java.io
import java.lang
import java.util
import jpype
import jpype.protocol
import typing



class DrmConvertedStatus:
    STATUS_ERROR: typing.ClassVar[int] = ...
    STATUS_INPUTDATA_ERROR: typing.ClassVar[int] = ...
    STATUS_OK: typing.ClassVar[int] = ...
    convertedData: typing.MutableSequence[int] = ...
    offset: int = ...
    statusCode: int = ...
    def __init__(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int2: int): ...

class DrmEvent:
    DRM_INFO_OBJECT: typing.ClassVar[str] = ...
    DRM_INFO_STATUS_OBJECT: typing.ClassVar[str] = ...
    TYPE_ALL_RIGHTS_REMOVED: typing.ClassVar[int] = ...
    TYPE_DRM_INFO_PROCESSED: typing.ClassVar[int] = ...
    def getAttribute(self, string: str) -> typing.Any: ...
    def getMessage(self) -> str: ...
    def getType(self) -> int: ...
    def getUniqueId(self) -> int: ...

class DrmInfo:
    @typing.overload
    def __init__(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], string: str): ...
    @typing.overload
    def __init__(self, int: int, string: str, string2: str): ...
    def get(self, string: str) -> typing.Any: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getInfoType(self) -> int: ...
    def getMimeType(self) -> str: ...
    def iterator(self) -> java.util.Iterator[typing.Any]: ...
    def keyIterator(self) -> java.util.Iterator[str]: ...
    def put(self, string: str, object: typing.Any) -> None: ...

class DrmInfoRequest:
    ACCOUNT_ID: typing.ClassVar[str] = ...
    SUBSCRIPTION_ID: typing.ClassVar[str] = ...
    TYPE_REGISTRATION_INFO: typing.ClassVar[int] = ...
    TYPE_RIGHTS_ACQUISITION_INFO: typing.ClassVar[int] = ...
    TYPE_RIGHTS_ACQUISITION_PROGRESS_INFO: typing.ClassVar[int] = ...
    TYPE_UNREGISTRATION_INFO: typing.ClassVar[int] = ...
    def __init__(self, int: int, string: str): ...
    def get(self, string: str) -> typing.Any: ...
    def getInfoType(self) -> int: ...
    def getMimeType(self) -> str: ...
    def iterator(self) -> java.util.Iterator[typing.Any]: ...
    def keyIterator(self) -> java.util.Iterator[str]: ...
    def put(self, string: str, object: typing.Any) -> None: ...

class DrmInfoStatus:
    STATUS_ERROR: typing.ClassVar[int] = ...
    STATUS_OK: typing.ClassVar[int] = ...
    data: 'ProcessedData' = ...
    infoType: int = ...
    mimeType: str = ...
    statusCode: int = ...
    def __init__(self, int: int, int2: int, processedData: 'ProcessedData', string: str): ...

class DrmManagerClient(java.lang.AutoCloseable):
    ERROR_NONE: typing.ClassVar[int] = ...
    ERROR_UNKNOWN: typing.ClassVar[int] = ...
    def __init__(self, context: android.content.Context): ...
    def acquireDrmInfo(self, drmInfoRequest: DrmInfoRequest) -> DrmInfo: ...
    def acquireRights(self, drmInfoRequest: DrmInfoRequest) -> int: ...
    @typing.overload
    def canHandle(self, uri: android.net.Uri, string: str) -> bool: ...
    @typing.overload
    def canHandle(self, string: str, string2: str) -> bool: ...
    @typing.overload
    def checkRightsStatus(self, uri: android.net.Uri) -> int: ...
    @typing.overload
    def checkRightsStatus(self, uri: android.net.Uri, int: int) -> int: ...
    @typing.overload
    def checkRightsStatus(self, string: str) -> int: ...
    @typing.overload
    def checkRightsStatus(self, string: str, int: int) -> int: ...
    def close(self) -> None: ...
    def closeConvertSession(self, int: int) -> DrmConvertedStatus: ...
    def convertData(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> DrmConvertedStatus: ...
    def getAvailableDrmEngines(self) -> typing.MutableSequence[str]: ...
    def getAvailableDrmSupportInfo(self) -> java.util.Collection['DrmSupportInfo']: ...
    @typing.overload
    def getConstraints(self, uri: android.net.Uri, int: int) -> android.content.ContentValues: ...
    @typing.overload
    def getConstraints(self, string: str, int: int) -> android.content.ContentValues: ...
    @typing.overload
    def getDrmObjectType(self, uri: android.net.Uri, string: str) -> int: ...
    @typing.overload
    def getDrmObjectType(self, string: str, string2: str) -> int: ...
    @typing.overload
    def getMetadata(self, uri: android.net.Uri) -> android.content.ContentValues: ...
    @typing.overload
    def getMetadata(self, string: str) -> android.content.ContentValues: ...
    @typing.overload
    def getOriginalMimeType(self, uri: android.net.Uri) -> str: ...
    @typing.overload
    def getOriginalMimeType(self, string: str) -> str: ...
    def openConvertSession(self, string: str) -> int: ...
    def processDrmInfo(self, drmInfo: DrmInfo) -> int: ...
    def release(self) -> None: ...
    def removeAllRights(self) -> int: ...
    @typing.overload
    def removeRights(self, uri: android.net.Uri) -> int: ...
    @typing.overload
    def removeRights(self, string: str) -> int: ...
    def saveRights(self, drmRights: 'DrmRights', string: str, string2: str) -> int: ...
    def setOnErrorListener(self, onErrorListener: typing.Union['DrmManagerClient.OnErrorListener', typing.Callable]) -> None: ...
    def setOnEventListener(self, onEventListener: typing.Union['DrmManagerClient.OnEventListener', typing.Callable]) -> None: ...
    def setOnInfoListener(self, onInfoListener: typing.Union['DrmManagerClient.OnInfoListener', typing.Callable]) -> None: ...
    class OnErrorListener:
        def onError(self, drmManagerClient: 'DrmManagerClient', drmErrorEvent: 'DrmErrorEvent') -> None: ...
    class OnEventListener:
        def onEvent(self, drmManagerClient: 'DrmManagerClient', drmEvent: DrmEvent) -> None: ...
    class OnInfoListener:
        def onInfo(self, drmManagerClient: 'DrmManagerClient', drmInfoEvent: 'DrmInfoEvent') -> None: ...

class DrmRights:
    @typing.overload
    def __init__(self, processedData: 'ProcessedData', string: str): ...
    @typing.overload
    def __init__(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], string: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str, string4: str): ...
    def getAccountId(self) -> str: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getMimeType(self) -> str: ...
    def getSubscriptionId(self) -> str: ...

class DrmStore:
    def __init__(self): ...
    class Action:
        DEFAULT: typing.ClassVar[int] = ...
        DISPLAY: typing.ClassVar[int] = ...
        EXECUTE: typing.ClassVar[int] = ...
        OUTPUT: typing.ClassVar[int] = ...
        PLAY: typing.ClassVar[int] = ...
        PREVIEW: typing.ClassVar[int] = ...
        RINGTONE: typing.ClassVar[int] = ...
        TRANSFER: typing.ClassVar[int] = ...
        def __init__(self): ...
    class ConstraintsColumns:
        EXTENDED_METADATA: typing.ClassVar[str] = ...
        LICENSE_AVAILABLE_TIME: typing.ClassVar[str] = ...
        LICENSE_EXPIRY_TIME: typing.ClassVar[str] = ...
        LICENSE_START_TIME: typing.ClassVar[str] = ...
        MAX_REPEAT_COUNT: typing.ClassVar[str] = ...
        REMAINING_REPEAT_COUNT: typing.ClassVar[str] = ...
    class DrmObjectType:
        CONTENT: typing.ClassVar[int] = ...
        RIGHTS_OBJECT: typing.ClassVar[int] = ...
        TRIGGER_OBJECT: typing.ClassVar[int] = ...
        UNKNOWN: typing.ClassVar[int] = ...
        def __init__(self): ...
    class Playback:
        PAUSE: typing.ClassVar[int] = ...
        RESUME: typing.ClassVar[int] = ...
        START: typing.ClassVar[int] = ...
        STOP: typing.ClassVar[int] = ...
        def __init__(self): ...
    class RightsStatus:
        RIGHTS_EXPIRED: typing.ClassVar[int] = ...
        RIGHTS_INVALID: typing.ClassVar[int] = ...
        RIGHTS_NOT_ACQUIRED: typing.ClassVar[int] = ...
        RIGHTS_VALID: typing.ClassVar[int] = ...
        def __init__(self): ...

class DrmSupportInfo:
    def __init__(self): ...
    def addFileSuffix(self, string: str) -> None: ...
    def addMimeType(self, string: str) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDescriprition(self) -> str: ...
    def getDescription(self) -> str: ...
    def getFileSuffixIterator(self) -> java.util.Iterator[str]: ...
    def getMimeTypeIterator(self) -> java.util.Iterator[str]: ...
    def hashCode(self) -> int: ...
    def setDescription(self, string: str) -> None: ...

class DrmUtils:
    def __init__(self): ...
    @staticmethod
    def getExtendedMetadataParser(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'DrmUtils.ExtendedMetadataParser': ...
    class ExtendedMetadataParser:
        def get(self, string: str) -> str: ...
        def iterator(self) -> java.util.Iterator[str]: ...
        def keyIterator(self) -> java.util.Iterator[str]: ...

class ProcessedData:
    def getAccountId(self) -> str: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getSubscriptionId(self) -> str: ...

class DrmErrorEvent(DrmEvent):
    TYPE_ACQUIRE_DRM_INFO_FAILED: typing.ClassVar[int] = ...
    TYPE_NOT_SUPPORTED: typing.ClassVar[int] = ...
    TYPE_NO_INTERNET_CONNECTION: typing.ClassVar[int] = ...
    TYPE_OUT_OF_MEMORY: typing.ClassVar[int] = ...
    TYPE_PROCESS_DRM_INFO_FAILED: typing.ClassVar[int] = ...
    TYPE_REMOVE_ALL_RIGHTS_FAILED: typing.ClassVar[int] = ...
    TYPE_RIGHTS_NOT_INSTALLED: typing.ClassVar[int] = ...
    TYPE_RIGHTS_RENEWAL_NOT_ALLOWED: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int, int2: int, string: str): ...
    @typing.overload
    def __init__(self, int: int, int2: int, string: str, hashMap: java.util.HashMap[str, typing.Any]): ...

class DrmInfoEvent(DrmEvent):
    TYPE_ACCOUNT_ALREADY_REGISTERED: typing.ClassVar[int] = ...
    TYPE_ALREADY_REGISTERED_BY_ANOTHER_ACCOUNT: typing.ClassVar[int] = ...
    TYPE_REMOVE_RIGHTS: typing.ClassVar[int] = ...
    TYPE_RIGHTS_INSTALLED: typing.ClassVar[int] = ...
    TYPE_RIGHTS_REMOVED: typing.ClassVar[int] = ...
    TYPE_WAIT_FOR_RIGHTS: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int, int2: int, string: str): ...
    @typing.overload
    def __init__(self, int: int, int2: int, string: str, hashMap: java.util.HashMap[str, typing.Any]): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.drm")``.

    DrmConvertedStatus: typing.Type[DrmConvertedStatus]
    DrmErrorEvent: typing.Type[DrmErrorEvent]
    DrmEvent: typing.Type[DrmEvent]
    DrmInfo: typing.Type[DrmInfo]
    DrmInfoEvent: typing.Type[DrmInfoEvent]
    DrmInfoRequest: typing.Type[DrmInfoRequest]
    DrmInfoStatus: typing.Type[DrmInfoStatus]
    DrmManagerClient: typing.Type[DrmManagerClient]
    DrmRights: typing.Type[DrmRights]
    DrmStore: typing.Type[DrmStore]
    DrmSupportInfo: typing.Type[DrmSupportInfo]
    DrmUtils: typing.Type[DrmUtils]
    ProcessedData: typing.Type[ProcessedData]
