
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.app.sdksandbox.sdkprovider
import android.content
import android.content.pm
import android.os
import android.view
import java.lang
import java.util
import java.util.concurrent
import typing



class AppOwnedSdkSandboxInterface(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, long: int, iBinder: android.os.IBinder): ...
    def describeContents(self) -> int: ...
    def getInterface(self) -> android.os.IBinder: ...
    def getName(self) -> str: ...
    def getVersion(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LoadSdkException(java.lang.Exception, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, throwable: java.lang.Throwable, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getExtraInformation(self) -> android.os.Bundle: ...
    def getLoadSdkErrorCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class RequestSurfacePackageException(java.lang.Exception):
    @typing.overload
    def __init__(self, int: int, string: str): ...
    @typing.overload
    def __init__(self, int: int, string: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, int: int, string: str, throwable: java.lang.Throwable, bundle: android.os.Bundle): ...
    def getExtraErrorInformation(self) -> android.os.Bundle: ...
    def getRequestSurfacePackageErrorCode(self) -> int: ...

class SandboxedSdk(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, iBinder: android.os.IBinder): ...
    def describeContents(self) -> int: ...
    def getInterface(self) -> android.os.IBinder: ...
    def getSharedLibraryInfo(self) -> android.content.pm.SharedLibraryInfo: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SandboxedSdkProvider:
    def __init__(self): ...
    def attachContext(self, context: android.content.Context) -> None: ...
    def beforeUnloadSdk(self) -> None: ...
    def getContext(self) -> android.content.Context: ...
    def getView(self, context: android.content.Context, bundle: android.os.Bundle, int: int, int2: int) -> android.view.View: ...
    def onLoadSdk(self, bundle: android.os.Bundle) -> SandboxedSdk: ...

class SdkSandboxManager:
    EXTRA_DISPLAY_ID: typing.ClassVar[str] = ...
    EXTRA_HEIGHT_IN_PIXELS: typing.ClassVar[str] = ...
    EXTRA_HOST_TOKEN: typing.ClassVar[str] = ...
    EXTRA_SURFACE_PACKAGE: typing.ClassVar[str] = ...
    EXTRA_WIDTH_IN_PIXELS: typing.ClassVar[str] = ...
    LOAD_SDK_ALREADY_LOADED: typing.ClassVar[int] = ...
    LOAD_SDK_INTERNAL_ERROR: typing.ClassVar[int] = ...
    LOAD_SDK_NOT_FOUND: typing.ClassVar[int] = ...
    LOAD_SDK_SDK_DEFINED_ERROR: typing.ClassVar[int] = ...
    LOAD_SDK_SDK_SANDBOX_DISABLED: typing.ClassVar[int] = ...
    REQUEST_SURFACE_PACKAGE_INTERNAL_ERROR: typing.ClassVar[int] = ...
    REQUEST_SURFACE_PACKAGE_SDK_NOT_LOADED: typing.ClassVar[int] = ...
    SDK_SANDBOX_PROCESS_NOT_AVAILABLE: typing.ClassVar[int] = ...
    SDK_SANDBOX_SERVICE: typing.ClassVar[str] = ...
    SDK_SANDBOX_STATE_DISABLED: typing.ClassVar[int] = ...
    SDK_SANDBOX_STATE_ENABLED_PROCESS_ISOLATION: typing.ClassVar[int] = ...
    def addSdkSandboxProcessDeathCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], sdkSandboxProcessDeathCallback: typing.Union['SdkSandboxManager.SdkSandboxProcessDeathCallback', typing.Callable]) -> None: ...
    def addSyncedSharedPreferencesKeys(self, set: java.util.Set[str]) -> None: ...
    def getAppOwnedSdkSandboxInterfaces(self) -> java.util.List[AppOwnedSdkSandboxInterface]: ...
    def getSandboxedSdks(self) -> java.util.List[SandboxedSdk]: ...
    @staticmethod
    def getSdkSandboxState() -> int: ...
    def getSyncedSharedPreferencesKeys(self) -> java.util.Set[str]: ...
    def loadSdk(self, string: str, bundle: android.os.Bundle, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[SandboxedSdk, LoadSdkException], typing.Callable[[SandboxedSdk], None]]) -> None: ...
    def registerAppOwnedSdkSandboxInterface(self, appOwnedSdkSandboxInterface: AppOwnedSdkSandboxInterface) -> None: ...
    def removeSdkSandboxProcessDeathCallback(self, sdkSandboxProcessDeathCallback: typing.Union['SdkSandboxManager.SdkSandboxProcessDeathCallback', typing.Callable]) -> None: ...
    def removeSyncedSharedPreferencesKeys(self, set: java.util.Set[str]) -> None: ...
    def requestSurfacePackage(self, string: str, bundle: android.os.Bundle, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[android.os.Bundle, RequestSurfacePackageException], typing.Callable[[android.os.Bundle], None]]) -> None: ...
    def startSdkSandboxActivity(self, activity: android.app.Activity, iBinder: android.os.IBinder) -> None: ...
    def unloadSdk(self, string: str) -> None: ...
    def unregisterAppOwnedSdkSandboxInterface(self, string: str) -> None: ...
    class SdkSandboxProcessDeathCallback:
        def onSdkSandboxDied(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.sdksandbox")``.

    AppOwnedSdkSandboxInterface: typing.Type[AppOwnedSdkSandboxInterface]
    LoadSdkException: typing.Type[LoadSdkException]
    RequestSurfacePackageException: typing.Type[RequestSurfacePackageException]
    SandboxedSdk: typing.Type[SandboxedSdk]
    SandboxedSdkProvider: typing.Type[SandboxedSdkProvider]
    SdkSandboxManager: typing.Type[SdkSandboxManager]
    sdkprovider: android.app.sdksandbox.sdkprovider.__module_protocol__
