
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.lang
import java.util
import typing



class EmergencyNumber(android.os.Parcelable, java.lang.Comparable['EmergencyNumber']):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EMERGENCY_CALL_ROUTING_EMERGENCY: typing.ClassVar[int] = ...
    EMERGENCY_CALL_ROUTING_NORMAL: typing.ClassVar[int] = ...
    EMERGENCY_CALL_ROUTING_UNKNOWN: typing.ClassVar[int] = ...
    EMERGENCY_NUMBER_SOURCE_DATABASE: typing.ClassVar[int] = ...
    EMERGENCY_NUMBER_SOURCE_DEFAULT: typing.ClassVar[int] = ...
    EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG: typing.ClassVar[int] = ...
    EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING: typing.ClassVar[int] = ...
    EMERGENCY_NUMBER_SOURCE_SIM: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_AIEC: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_AMBULANCE: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_MIEC: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_POLICE: typing.ClassVar[int] = ...
    EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED: typing.ClassVar[int] = ...
    def compareTo(self, emergencyNumber: 'EmergencyNumber') -> int: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCountryIso(self) -> str: ...
    def getEmergencyCallRouting(self) -> int: ...
    def getEmergencyNumberSources(self) -> java.util.List[int]: ...
    def getEmergencyServiceCategories(self) -> java.util.List[int]: ...
    def getEmergencyUrns(self) -> java.util.List[str]: ...
    def getMnc(self) -> str: ...
    def getNumber(self) -> str: ...
    def hashCode(self) -> int: ...
    def isFromSources(self, int: int) -> bool: ...
    def isInEmergencyServiceCategories(self, int: int) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.telephony.emergency")``.

    EmergencyNumber: typing.Type[EmergencyNumber]
