
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.net
import android.os
import datetime
import java.io
import java.lang
import java.net
import java.nio
import java.security.cert
import java.time
import java.util
import java.util.concurrent
import javax.net.ssl
import jpype
import jpype.protocol
import typing



class BidirectionalStream:
    STREAM_PRIORITY_HIGHEST: typing.ClassVar[int] = ...
    STREAM_PRIORITY_IDLE: typing.ClassVar[int] = ...
    STREAM_PRIORITY_LOW: typing.ClassVar[int] = ...
    STREAM_PRIORITY_LOWEST: typing.ClassVar[int] = ...
    STREAM_PRIORITY_MEDIUM: typing.ClassVar[int] = ...
    def __init__(self): ...
    def cancel(self) -> None: ...
    def flush(self) -> None: ...
    def getHeaders(self) -> 'HeaderBlock': ...
    def getHttpMethod(self) -> str: ...
    def getPriority(self) -> int: ...
    def getTrafficStatsTag(self) -> int: ...
    def getTrafficStatsUid(self) -> int: ...
    def hasTrafficStatsTag(self) -> bool: ...
    def hasTrafficStatsUid(self) -> bool: ...
    def isDelayRequestHeadersUntilFirstFlushEnabled(self) -> bool: ...
    def isDone(self) -> bool: ...
    def read(self, byteBuffer: java.nio.ByteBuffer) -> None: ...
    def start(self) -> None: ...
    def write(self, byteBuffer: java.nio.ByteBuffer, boolean: bool) -> None: ...
    class Builder:
        def __init__(self): ...
        def addHeader(self, string: str, string2: str) -> 'BidirectionalStream.Builder': ...
        def build(self) -> 'BidirectionalStream': ...
        def setDelayRequestHeadersUntilFirstFlushEnabled(self, boolean: bool) -> 'BidirectionalStream.Builder': ...
        def setHttpMethod(self, string: str) -> 'BidirectionalStream.Builder': ...
        def setPriority(self, int: int) -> 'BidirectionalStream.Builder': ...
        def setTrafficStatsTag(self, int: int) -> 'BidirectionalStream.Builder': ...
        def setTrafficStatsUid(self, int: int) -> 'BidirectionalStream.Builder': ...
    class Callback:
        def onCanceled(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo') -> None: ...
        def onFailed(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo', httpException: 'HttpException') -> None: ...
        def onReadCompleted(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo', byteBuffer: java.nio.ByteBuffer, boolean: bool) -> None: ...
        def onResponseHeadersReceived(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo') -> None: ...
        def onResponseTrailersReceived(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo', headerBlock: 'HeaderBlock') -> None: ...
        def onStreamReady(self, bidirectionalStream: 'BidirectionalStream') -> None: ...
        def onSucceeded(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo') -> None: ...
        def onWriteCompleted(self, bidirectionalStream: 'BidirectionalStream', urlResponseInfo: 'UrlResponseInfo', byteBuffer: java.nio.ByteBuffer, boolean: bool) -> None: ...

class ConnectionMigrationOptions:
    MIGRATION_OPTION_DISABLED: typing.ClassVar[int] = ...
    MIGRATION_OPTION_ENABLED: typing.ClassVar[int] = ...
    MIGRATION_OPTION_UNSPECIFIED: typing.ClassVar[int] = ...
    def getAllowNonDefaultNetworkUsage(self) -> int: ...
    def getDefaultNetworkMigration(self) -> int: ...
    def getPathDegradationMigration(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'ConnectionMigrationOptions': ...
        def setAllowNonDefaultNetworkUsage(self, int: int) -> 'ConnectionMigrationOptions.Builder': ...
        def setDefaultNetworkMigration(self, int: int) -> 'ConnectionMigrationOptions.Builder': ...
        def setPathDegradationMigration(self, int: int) -> 'ConnectionMigrationOptions.Builder': ...

class DnsOptions:
    DNS_OPTION_DISABLED: typing.ClassVar[int] = ...
    DNS_OPTION_ENABLED: typing.ClassVar[int] = ...
    DNS_OPTION_UNSPECIFIED: typing.ClassVar[int] = ...
    def getPersistHostCache(self) -> int: ...
    def getPersistHostCachePeriod(self) -> java.time.Duration: ...
    def getPreestablishConnectionsToStaleDnsResults(self) -> int: ...
    def getStaleDns(self) -> int: ...
    def getStaleDnsOptions(self) -> 'DnsOptions.StaleDnsOptions': ...
    def getUseHttpStackDnsResolver(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'DnsOptions': ...
        def setPersistHostCache(self, int: int) -> 'DnsOptions.Builder': ...
        def setPersistHostCachePeriod(self, duration: java.time.Duration) -> 'DnsOptions.Builder': ...
        def setPreestablishConnectionsToStaleDnsResults(self, int: int) -> 'DnsOptions.Builder': ...
        def setStaleDns(self, int: int) -> 'DnsOptions.Builder': ...
        def setStaleDnsOptions(self, staleDnsOptions: 'DnsOptions.StaleDnsOptions') -> 'DnsOptions.Builder': ...
        def setUseHttpStackDnsResolver(self, int: int) -> 'DnsOptions.Builder': ...
    class StaleDnsOptions:
        def getAllowCrossNetworkUsage(self) -> int: ...
        def getFreshLookupTimeout(self) -> java.time.Duration: ...
        def getMaxExpiredDelay(self) -> java.time.Duration: ...
        def getUseStaleOnNameNotResolved(self) -> int: ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'DnsOptions.StaleDnsOptions': ...
            def setAllowCrossNetworkUsage(self, int: int) -> 'DnsOptions.StaleDnsOptions.Builder': ...
            def setFreshLookupTimeout(self, duration: java.time.Duration) -> 'DnsOptions.StaleDnsOptions.Builder': ...
            def setMaxExpiredDelay(self, duration: java.time.Duration) -> 'DnsOptions.StaleDnsOptions.Builder': ...
            def setUseStaleOnNameNotResolved(self, int: int) -> 'DnsOptions.StaleDnsOptions.Builder': ...

class HeaderBlock:
    def __init__(self): ...
    def getAsList(self) -> java.util.List[java.util.Map.Entry[str, str]]: ...
    def getAsMap(self) -> java.util.Map[str, java.util.List[str]]: ...

class HttpEngine:
    def bindToNetwork(self, network: android.net.Network) -> None: ...
    def createUrlStreamHandlerFactory(self) -> java.net.URLStreamHandlerFactory: ...
    @staticmethod
    def getVersionString() -> str: ...
    def newBidirectionalStreamBuilder(self, string: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: BidirectionalStream.Callback) -> BidirectionalStream.Builder: ...
    def newUrlRequestBuilder(self, string: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], callback: 'UrlRequest.Callback') -> 'UrlRequest.Builder': ...
    def openConnection(self, uRL: java.net.URL) -> java.net.URLConnection: ...
    def shutdown(self) -> None: ...
    class Builder:
        HTTP_CACHE_DISABLED: typing.ClassVar[int] = ...
        HTTP_CACHE_DISK: typing.ClassVar[int] = ...
        HTTP_CACHE_DISK_NO_HTTP: typing.ClassVar[int] = ...
        HTTP_CACHE_IN_MEMORY: typing.ClassVar[int] = ...
        def __init__(self, context: android.content.Context): ...
        def addPublicKeyPins(self, string: str, set: java.util.Set[typing.Union[typing.List[int], jpype.JArray, bytes]], boolean: bool, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'HttpEngine.Builder': ...
        def addQuicHint(self, string: str, int: int, int2: int) -> 'HttpEngine.Builder': ...
        def build(self) -> 'HttpEngine': ...
        def getDefaultUserAgent(self) -> str: ...
        def setConnectionMigrationOptions(self, connectionMigrationOptions: ConnectionMigrationOptions) -> 'HttpEngine.Builder': ...
        def setDnsOptions(self, dnsOptions: DnsOptions) -> 'HttpEngine.Builder': ...
        def setEnableBrotli(self, boolean: bool) -> 'HttpEngine.Builder': ...
        def setEnableHttp2(self, boolean: bool) -> 'HttpEngine.Builder': ...
        def setEnableHttpCache(self, int: int, long: int) -> 'HttpEngine.Builder': ...
        def setEnablePublicKeyPinningBypassForLocalTrustAnchors(self, boolean: bool) -> 'HttpEngine.Builder': ...
        def setEnableQuic(self, boolean: bool) -> 'HttpEngine.Builder': ...
        def setQuicOptions(self, quicOptions: 'QuicOptions') -> 'HttpEngine.Builder': ...
        def setStoragePath(self, string: str) -> 'HttpEngine.Builder': ...
        def setUserAgent(self, string: str) -> 'HttpEngine.Builder': ...

class HttpException(java.io.IOException):
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class HttpResponseCache(java.net.ResponseCache, java.io.Closeable):
    def close(self) -> None: ...
    def delete(self) -> None: ...
    def flush(self) -> None: ...
    def get(self, uRI: java.net.URI, string: str, map: typing.Union[java.util.Map[str, java.util.List[str]], typing.Mapping[str, java.util.List[str]]]) -> java.net.CacheResponse: ...
    def getHitCount(self) -> int: ...
    @staticmethod
    def getInstalled() -> 'HttpResponseCache': ...
    def getNetworkCount(self) -> int: ...
    def getRequestCount(self) -> int: ...
    @staticmethod
    def install(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], long: int) -> 'HttpResponseCache': ...
    def maxSize(self) -> int: ...
    def put(self, uRI: java.net.URI, uRLConnection: java.net.URLConnection) -> java.net.CacheRequest: ...
    def size(self) -> int: ...

class InlineExecutionProhibitedException(java.util.concurrent.RejectedExecutionException):
    def __init__(self): ...

class QuicOptions:
    def getAllowedQuicHosts(self) -> java.util.Set[str]: ...
    def getHandshakeUserAgent(self) -> str: ...
    def getIdleConnectionTimeout(self) -> java.time.Duration: ...
    def getInMemoryServerConfigsCacheSize(self) -> int: ...
    def hasInMemoryServerConfigsCacheSize(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def addAllowedQuicHost(self, string: str) -> 'QuicOptions.Builder': ...
        def build(self) -> 'QuicOptions': ...
        def setHandshakeUserAgent(self, string: str) -> 'QuicOptions.Builder': ...
        def setIdleConnectionTimeout(self, duration: java.time.Duration) -> 'QuicOptions.Builder': ...
        def setInMemoryServerConfigsCacheSize(self, int: int) -> 'QuicOptions.Builder': ...

class SslCertificate:
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str, string4: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, date: java.util.Date, date2: java.util.Date): ...
    @typing.overload
    def __init__(self, x509Certificate: java.security.cert.X509Certificate): ...
    def getIssuedBy(self) -> 'SslCertificate.DName': ...
    def getIssuedTo(self) -> 'SslCertificate.DName': ...
    def getValidNotAfter(self) -> str: ...
    def getValidNotAfterDate(self) -> java.util.Date: ...
    def getValidNotBefore(self) -> str: ...
    def getValidNotBeforeDate(self) -> java.util.Date: ...
    def getX509Certificate(self) -> java.security.cert.X509Certificate: ...
    @staticmethod
    def restoreState(bundle: android.os.Bundle) -> 'SslCertificate': ...
    @staticmethod
    def saveState(sslCertificate: 'SslCertificate') -> android.os.Bundle: ...
    def toString(self) -> str: ...
    class DName:
        def __init__(self, sslCertificate: 'SslCertificate', string: str): ...
        def getCName(self) -> str: ...
        def getDName(self) -> str: ...
        def getOName(self) -> str: ...
        def getUName(self) -> str: ...

class SslError:
    SSL_DATE_INVALID: typing.ClassVar[int] = ...
    SSL_EXPIRED: typing.ClassVar[int] = ...
    SSL_IDMISMATCH: typing.ClassVar[int] = ...
    SSL_INVALID: typing.ClassVar[int] = ...
    SSL_MAX_ERROR: typing.ClassVar[int] = ...
    SSL_NOTYETVALID: typing.ClassVar[int] = ...
    SSL_UNTRUSTED: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int, sslCertificate: SslCertificate): ...
    @typing.overload
    def __init__(self, int: int, sslCertificate: SslCertificate, string: str): ...
    @typing.overload
    def __init__(self, int: int, x509Certificate: java.security.cert.X509Certificate): ...
    @typing.overload
    def __init__(self, int: int, x509Certificate: java.security.cert.X509Certificate, string: str): ...
    def addError(self, int: int) -> bool: ...
    def getCertificate(self) -> SslCertificate: ...
    def getPrimaryError(self) -> int: ...
    def getUrl(self) -> str: ...
    def hasError(self, int: int) -> bool: ...
    def toString(self) -> str: ...

class UploadDataProvider(java.io.Closeable):
    def __init__(self): ...
    def close(self) -> None: ...
    def getLength(self) -> int: ...
    def read(self, uploadDataSink: 'UploadDataSink', byteBuffer: java.nio.ByteBuffer) -> None: ...
    def rewind(self, uploadDataSink: 'UploadDataSink') -> None: ...

class UploadDataSink:
    def __init__(self): ...
    def onReadError(self, exception: java.lang.Exception) -> None: ...
    def onReadSucceeded(self, boolean: bool) -> None: ...
    def onRewindError(self, exception: java.lang.Exception) -> None: ...
    def onRewindSucceeded(self) -> None: ...

class UrlRequest:
    REQUEST_PRIORITY_HIGHEST: typing.ClassVar[int] = ...
    REQUEST_PRIORITY_IDLE: typing.ClassVar[int] = ...
    REQUEST_PRIORITY_LOW: typing.ClassVar[int] = ...
    REQUEST_PRIORITY_LOWEST: typing.ClassVar[int] = ...
    REQUEST_PRIORITY_MEDIUM: typing.ClassVar[int] = ...
    def cancel(self) -> None: ...
    def followRedirect(self) -> None: ...
    def getHeaders(self) -> HeaderBlock: ...
    def getHttpMethod(self) -> str: ...
    def getPriority(self) -> int: ...
    def getStatus(self, statusListener: typing.Union['UrlRequest.StatusListener', typing.Callable]) -> None: ...
    def getTrafficStatsTag(self) -> int: ...
    def getTrafficStatsUid(self) -> int: ...
    def hasTrafficStatsTag(self) -> bool: ...
    def hasTrafficStatsUid(self) -> bool: ...
    def isCacheDisabled(self) -> bool: ...
    def isDirectExecutorAllowed(self) -> bool: ...
    def isDone(self) -> bool: ...
    def read(self, byteBuffer: java.nio.ByteBuffer) -> None: ...
    def start(self) -> None: ...
    class Builder:
        def addHeader(self, string: str, string2: str) -> 'UrlRequest.Builder': ...
        def bindToNetwork(self, network: android.net.Network) -> 'UrlRequest.Builder': ...
        def build(self) -> 'UrlRequest': ...
        def setCacheDisabled(self, boolean: bool) -> 'UrlRequest.Builder': ...
        def setDirectExecutorAllowed(self, boolean: bool) -> 'UrlRequest.Builder': ...
        def setHttpMethod(self, string: str) -> 'UrlRequest.Builder': ...
        def setPriority(self, int: int) -> 'UrlRequest.Builder': ...
        def setTrafficStatsTag(self, int: int) -> 'UrlRequest.Builder': ...
        def setTrafficStatsUid(self, int: int) -> 'UrlRequest.Builder': ...
        def setUploadDataProvider(self, uploadDataProvider: UploadDataProvider, executor: typing.Union[java.util.concurrent.Executor, typing.Callable]) -> 'UrlRequest.Builder': ...
    class Callback:
        def onCanceled(self, urlRequest: 'UrlRequest', urlResponseInfo: 'UrlResponseInfo') -> None: ...
        def onFailed(self, urlRequest: 'UrlRequest', urlResponseInfo: 'UrlResponseInfo', httpException: HttpException) -> None: ...
        def onReadCompleted(self, urlRequest: 'UrlRequest', urlResponseInfo: 'UrlResponseInfo', byteBuffer: java.nio.ByteBuffer) -> None: ...
        def onRedirectReceived(self, urlRequest: 'UrlRequest', urlResponseInfo: 'UrlResponseInfo', string: str) -> None: ...
        def onResponseStarted(self, urlRequest: 'UrlRequest', urlResponseInfo: 'UrlResponseInfo') -> None: ...
        def onSucceeded(self, urlRequest: 'UrlRequest', urlResponseInfo: 'UrlResponseInfo') -> None: ...
    class Status:
        CONNECTING: typing.ClassVar[int] = ...
        DOWNLOADING_PAC_FILE: typing.ClassVar[int] = ...
        ESTABLISHING_PROXY_TUNNEL: typing.ClassVar[int] = ...
        IDLE: typing.ClassVar[int] = ...
        INVALID: typing.ClassVar[int] = ...
        READING_RESPONSE: typing.ClassVar[int] = ...
        RESOLVING_HOST: typing.ClassVar[int] = ...
        RESOLVING_HOST_IN_PAC_FILE: typing.ClassVar[int] = ...
        RESOLVING_PROXY_FOR_URL: typing.ClassVar[int] = ...
        SENDING_REQUEST: typing.ClassVar[int] = ...
        SSL_HANDSHAKE: typing.ClassVar[int] = ...
        WAITING_FOR_AVAILABLE_SOCKET: typing.ClassVar[int] = ...
        WAITING_FOR_CACHE: typing.ClassVar[int] = ...
        WAITING_FOR_DELEGATE: typing.ClassVar[int] = ...
        WAITING_FOR_RESPONSE: typing.ClassVar[int] = ...
        WAITING_FOR_STALLED_SOCKET_POOL: typing.ClassVar[int] = ...
    class StatusListener:
        def onStatus(self, int: int) -> None: ...

class UrlResponseInfo:
    def __init__(self): ...
    def getHeaders(self) -> HeaderBlock: ...
    def getHttpStatusCode(self) -> int: ...
    def getHttpStatusText(self) -> str: ...
    def getNegotiatedProtocol(self) -> str: ...
    def getReceivedByteCount(self) -> int: ...
    def getUrl(self) -> str: ...
    def getUrlChain(self) -> java.util.List[str]: ...
    def wasCached(self) -> bool: ...

class X509TrustManagerExtensions:
    def __init__(self, x509TrustManager: javax.net.ssl.X509TrustManager): ...
    def checkServerTrusted(self, x509CertificateArray: typing.Union[typing.List[java.security.cert.X509Certificate], jpype.JArray], string: str, string2: str) -> java.util.List[java.security.cert.X509Certificate]: ...
    def isSameTrustConfiguration(self, string: str, string2: str) -> bool: ...
    def isUserAddedCertificate(self, x509Certificate: java.security.cert.X509Certificate) -> bool: ...

class CallbackException(HttpException): ...

class NetworkException(HttpException):
    ERROR_ADDRESS_UNREACHABLE: typing.ClassVar[int] = ...
    ERROR_CONNECTION_CLOSED: typing.ClassVar[int] = ...
    ERROR_CONNECTION_REFUSED: typing.ClassVar[int] = ...
    ERROR_CONNECTION_RESET: typing.ClassVar[int] = ...
    ERROR_CONNECTION_TIMED_OUT: typing.ClassVar[int] = ...
    ERROR_HOSTNAME_NOT_RESOLVED: typing.ClassVar[int] = ...
    ERROR_INTERNET_DISCONNECTED: typing.ClassVar[int] = ...
    ERROR_NETWORK_CHANGED: typing.ClassVar[int] = ...
    ERROR_OTHER: typing.ClassVar[int] = ...
    ERROR_QUIC_PROTOCOL_FAILED: typing.ClassVar[int] = ...
    ERROR_TIMED_OUT: typing.ClassVar[int] = ...
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    def getErrorCode(self) -> int: ...
    def isImmediatelyRetryable(self) -> bool: ...

class QuicException(NetworkException): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.http")``.

    BidirectionalStream: typing.Type[BidirectionalStream]
    CallbackException: typing.Type[CallbackException]
    ConnectionMigrationOptions: typing.Type[ConnectionMigrationOptions]
    DnsOptions: typing.Type[DnsOptions]
    HeaderBlock: typing.Type[HeaderBlock]
    HttpEngine: typing.Type[HttpEngine]
    HttpException: typing.Type[HttpException]
    HttpResponseCache: typing.Type[HttpResponseCache]
    InlineExecutionProhibitedException: typing.Type[InlineExecutionProhibitedException]
    NetworkException: typing.Type[NetworkException]
    QuicException: typing.Type[QuicException]
    QuicOptions: typing.Type[QuicOptions]
    SslCertificate: typing.Type[SslCertificate]
    SslError: typing.Type[SslError]
    UploadDataProvider: typing.Type[UploadDataProvider]
    UploadDataSink: typing.Type[UploadDataSink]
    UrlRequest: typing.Type[UrlRequest]
    UrlResponseInfo: typing.Type[UrlResponseInfo]
    X509TrustManagerExtensions: typing.Type[X509TrustManagerExtensions]
