
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.media
import android.net
import android.os
import java.io
import java.lang
import java.util
import jpype
import jpype.protocol
import typing



class SynthesisCallback:
    def audioAvailable(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    def done(self) -> int: ...
    @typing.overload
    def error(self) -> None: ...
    @typing.overload
    def error(self, int: int) -> None: ...
    def getMaxBufferSize(self) -> int: ...
    def hasFinished(self) -> bool: ...
    def hasStarted(self) -> bool: ...
    def rangeStart(self, int: int, int2: int, int3: int) -> None: ...
    def start(self, int: int, int2: int, int3: int) -> int: ...

class SynthesisRequest:
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], bundle: android.os.Bundle): ...
    @typing.overload
    def __init__(self, string: str, bundle: android.os.Bundle): ...
    def getCallerUid(self) -> int: ...
    def getCharSequenceText(self) -> java.lang.CharSequence: ...
    def getCountry(self) -> str: ...
    def getLanguage(self) -> str: ...
    def getParams(self) -> android.os.Bundle: ...
    def getPitch(self) -> int: ...
    def getSpeechRate(self) -> int: ...
    def getText(self) -> str: ...
    def getVariant(self) -> str: ...
    def getVoiceName(self) -> str: ...

class TextToSpeech:
    ACTION_TTS_QUEUE_PROCESSING_COMPLETED: typing.ClassVar[str] = ...
    ERROR: typing.ClassVar[int] = ...
    ERROR_INVALID_REQUEST: typing.ClassVar[int] = ...
    ERROR_NETWORK: typing.ClassVar[int] = ...
    ERROR_NETWORK_TIMEOUT: typing.ClassVar[int] = ...
    ERROR_NOT_INSTALLED_YET: typing.ClassVar[int] = ...
    ERROR_OUTPUT: typing.ClassVar[int] = ...
    ERROR_SERVICE: typing.ClassVar[int] = ...
    ERROR_SYNTHESIS: typing.ClassVar[int] = ...
    LANG_AVAILABLE: typing.ClassVar[int] = ...
    LANG_COUNTRY_AVAILABLE: typing.ClassVar[int] = ...
    LANG_COUNTRY_VAR_AVAILABLE: typing.ClassVar[int] = ...
    LANG_MISSING_DATA: typing.ClassVar[int] = ...
    LANG_NOT_SUPPORTED: typing.ClassVar[int] = ...
    QUEUE_ADD: typing.ClassVar[int] = ...
    QUEUE_FLUSH: typing.ClassVar[int] = ...
    STOPPED: typing.ClassVar[int] = ...
    SUCCESS: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, onInitListener: typing.Union['TextToSpeech.OnInitListener', typing.Callable]): ...
    @typing.overload
    def __init__(self, context: android.content.Context, onInitListener: typing.Union['TextToSpeech.OnInitListener', typing.Callable], string: str): ...
    @typing.overload
    def addEarcon(self, string: str, uri: android.net.Uri) -> int: ...
    @typing.overload
    def addEarcon(self, string: str, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> int: ...
    @typing.overload
    def addEarcon(self, string: str, string2: str) -> int: ...
    @typing.overload
    def addEarcon(self, string: str, string2: str, int: int) -> int: ...
    @typing.overload
    def addSpeech(self, charSequence: typing.Union[java.lang.CharSequence, str], uri: android.net.Uri) -> int: ...
    @typing.overload
    def addSpeech(self, charSequence: typing.Union[java.lang.CharSequence, str], file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> int: ...
    @typing.overload
    def addSpeech(self, charSequence: typing.Union[java.lang.CharSequence, str], string: str, int: int) -> int: ...
    @typing.overload
    def addSpeech(self, string: str, string2: str) -> int: ...
    @typing.overload
    def addSpeech(self, string: str, string2: str, int: int) -> int: ...
    def areDefaultsEnforced(self) -> bool: ...
    def getAvailableLanguages(self) -> java.util.Set[java.util.Locale]: ...
    def getDefaultEngine(self) -> str: ...
    def getDefaultLanguage(self) -> java.util.Locale: ...
    def getDefaultVoice(self) -> 'Voice': ...
    def getEngines(self) -> java.util.List['TextToSpeech.EngineInfo']: ...
    def getFeatures(self, locale: java.util.Locale) -> java.util.Set[str]: ...
    def getLanguage(self) -> java.util.Locale: ...
    @staticmethod
    def getMaxSpeechInputLength() -> int: ...
    def getVoice(self) -> 'Voice': ...
    def getVoices(self) -> java.util.Set['Voice']: ...
    def isLanguageAvailable(self, locale: java.util.Locale) -> int: ...
    def isSpeaking(self) -> bool: ...
    @typing.overload
    def playEarcon(self, string: str, int: int, bundle: android.os.Bundle, string2: str) -> int: ...
    @typing.overload
    def playEarcon(self, string: str, int: int, hashMap: java.util.HashMap[str, str]) -> int: ...
    def playSilence(self, long: int, int: int, hashMap: java.util.HashMap[str, str]) -> int: ...
    def playSilentUtterance(self, long: int, int: int, string: str) -> int: ...
    def setAudioAttributes(self, audioAttributes: android.media.AudioAttributes) -> int: ...
    def setEngineByPackageName(self, string: str) -> int: ...
    def setLanguage(self, locale: java.util.Locale) -> int: ...
    def setOnUtteranceCompletedListener(self, onUtteranceCompletedListener: typing.Union['TextToSpeech.OnUtteranceCompletedListener', typing.Callable]) -> int: ...
    def setOnUtteranceProgressListener(self, utteranceProgressListener: 'UtteranceProgressListener') -> int: ...
    def setPitch(self, float: float) -> int: ...
    def setSpeechRate(self, float: float) -> int: ...
    def setVoice(self, voice: 'Voice') -> int: ...
    def shutdown(self) -> None: ...
    @typing.overload
    def speak(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, bundle: android.os.Bundle, string: str) -> int: ...
    @typing.overload
    def speak(self, string: str, int: int, hashMap: java.util.HashMap[str, str]) -> int: ...
    def stop(self) -> int: ...
    @typing.overload
    def synthesizeToFile(self, charSequence: typing.Union[java.lang.CharSequence, str], bundle: android.os.Bundle, parcelFileDescriptor: android.os.ParcelFileDescriptor, string: str) -> int: ...
    @typing.overload
    def synthesizeToFile(self, charSequence: typing.Union[java.lang.CharSequence, str], bundle: android.os.Bundle, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], string: str) -> int: ...
    @typing.overload
    def synthesizeToFile(self, string: str, hashMap: java.util.HashMap[str, str], string2: str) -> int: ...
    class Engine:
        ACTION_CHECK_TTS_DATA: typing.ClassVar[str] = ...
        ACTION_GET_SAMPLE_TEXT: typing.ClassVar[str] = ...
        ACTION_INSTALL_TTS_DATA: typing.ClassVar[str] = ...
        ACTION_TTS_DATA_INSTALLED: typing.ClassVar[str] = ...
        CHECK_VOICE_DATA_BAD_DATA: typing.ClassVar[int] = ...
        CHECK_VOICE_DATA_FAIL: typing.ClassVar[int] = ...
        CHECK_VOICE_DATA_MISSING_DATA: typing.ClassVar[int] = ...
        CHECK_VOICE_DATA_MISSING_VOLUME: typing.ClassVar[int] = ...
        CHECK_VOICE_DATA_PASS: typing.ClassVar[int] = ...
        DEFAULT_STREAM: typing.ClassVar[int] = ...
        EXTRA_AVAILABLE_VOICES: typing.ClassVar[str] = ...
        EXTRA_CHECK_VOICE_DATA_FOR: typing.ClassVar[str] = ...
        EXTRA_SAMPLE_TEXT: typing.ClassVar[str] = ...
        EXTRA_TTS_DATA_INSTALLED: typing.ClassVar[str] = ...
        EXTRA_UNAVAILABLE_VOICES: typing.ClassVar[str] = ...
        EXTRA_VOICE_DATA_FILES: typing.ClassVar[str] = ...
        EXTRA_VOICE_DATA_FILES_INFO: typing.ClassVar[str] = ...
        EXTRA_VOICE_DATA_ROOT_DIRECTORY: typing.ClassVar[str] = ...
        INTENT_ACTION_TTS_SERVICE: typing.ClassVar[str] = ...
        KEY_FEATURE_EMBEDDED_SYNTHESIS: typing.ClassVar[str] = ...
        KEY_FEATURE_NETWORK_RETRIES_COUNT: typing.ClassVar[str] = ...
        KEY_FEATURE_NETWORK_SYNTHESIS: typing.ClassVar[str] = ...
        KEY_FEATURE_NETWORK_TIMEOUT_MS: typing.ClassVar[str] = ...
        KEY_FEATURE_NOT_INSTALLED: typing.ClassVar[str] = ...
        KEY_PARAM_PAN: typing.ClassVar[str] = ...
        KEY_PARAM_SESSION_ID: typing.ClassVar[str] = ...
        KEY_PARAM_STREAM: typing.ClassVar[str] = ...
        KEY_PARAM_UTTERANCE_ID: typing.ClassVar[str] = ...
        KEY_PARAM_VOLUME: typing.ClassVar[str] = ...
        SERVICE_META_DATA: typing.ClassVar[str] = ...
        def __init__(self, textToSpeech: 'TextToSpeech'): ...
    class EngineInfo:
        icon: int = ...
        label: str = ...
        name: str = ...
        def __init__(self): ...
        def toString(self) -> str: ...
    class OnInitListener:
        def onInit(self, int: int) -> None: ...
    class OnUtteranceCompletedListener:
        def onUtteranceCompleted(self, string: str) -> None: ...

class TextToSpeechService(android.app.Service):
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onCreate(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onGetDefaultVoiceNameFor(self, string: str, string2: str, string3: str) -> str: ...
    def onGetVoices(self) -> java.util.List['Voice']: ...
    def onIsValidVoiceName(self, string: str) -> int: ...
    def onLoadVoice(self, string: str) -> int: ...

class UtteranceProgressListener:
    def __init__(self): ...
    def onAudioAvailable(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def onBeginSynthesis(self, string: str, int: int, int2: int, int3: int) -> None: ...
    def onDone(self, string: str) -> None: ...
    @typing.overload
    def onError(self, string: str) -> None: ...
    @typing.overload
    def onError(self, string: str, int: int) -> None: ...
    def onRangeStart(self, string: str, int: int, int2: int, int3: int) -> None: ...
    def onStart(self, string: str) -> None: ...
    def onStop(self, string: str, boolean: bool) -> None: ...

class Voice(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    LATENCY_HIGH: typing.ClassVar[int] = ...
    LATENCY_LOW: typing.ClassVar[int] = ...
    LATENCY_NORMAL: typing.ClassVar[int] = ...
    LATENCY_VERY_HIGH: typing.ClassVar[int] = ...
    LATENCY_VERY_LOW: typing.ClassVar[int] = ...
    QUALITY_HIGH: typing.ClassVar[int] = ...
    QUALITY_LOW: typing.ClassVar[int] = ...
    QUALITY_NORMAL: typing.ClassVar[int] = ...
    QUALITY_VERY_HIGH: typing.ClassVar[int] = ...
    QUALITY_VERY_LOW: typing.ClassVar[int] = ...
    def __init__(self, string: str, locale: java.util.Locale, int: int, int2: int, boolean: bool, set: java.util.Set[str]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFeatures(self) -> java.util.Set[str]: ...
    def getLatency(self) -> int: ...
    def getLocale(self) -> java.util.Locale: ...
    def getName(self) -> str: ...
    def getQuality(self) -> int: ...
    def hashCode(self) -> int: ...
    def isNetworkConnectionRequired(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.speech.tts")``.

    SynthesisCallback: typing.Type[SynthesisCallback]
    SynthesisRequest: typing.Type[SynthesisRequest]
    TextToSpeech: typing.Type[TextToSpeech]
    TextToSpeechService: typing.Type[TextToSpeechService]
    UtteranceProgressListener: typing.Type[UtteranceProgressListener]
    Voice: typing.Type[Voice]
