
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import _jpype
import android.icu.math
import android.icu.text
import java.io
import java.lang
import java.util
import jpype
import typing



class Calendar(java.io.Serializable, java.lang.Cloneable, java.lang.Comparable['Calendar']):
    AM: typing.ClassVar[int] = ...
    AM_PM: typing.ClassVar[int] = ...
    APRIL: typing.ClassVar[int] = ...
    AUGUST: typing.ClassVar[int] = ...
    DATE: typing.ClassVar[int] = ...
    DAY_OF_MONTH: typing.ClassVar[int] = ...
    DAY_OF_WEEK: typing.ClassVar[int] = ...
    DAY_OF_WEEK_IN_MONTH: typing.ClassVar[int] = ...
    DAY_OF_YEAR: typing.ClassVar[int] = ...
    DECEMBER: typing.ClassVar[int] = ...
    DOW_LOCAL: typing.ClassVar[int] = ...
    DST_OFFSET: typing.ClassVar[int] = ...
    ERA: typing.ClassVar[int] = ...
    EXTENDED_YEAR: typing.ClassVar[int] = ...
    FEBRUARY: typing.ClassVar[int] = ...
    FRIDAY: typing.ClassVar[int] = ...
    HOUR: typing.ClassVar[int] = ...
    HOUR_OF_DAY: typing.ClassVar[int] = ...
    IS_LEAP_MONTH: typing.ClassVar[int] = ...
    JANUARY: typing.ClassVar[int] = ...
    JULIAN_DAY: typing.ClassVar[int] = ...
    JULY: typing.ClassVar[int] = ...
    JUNE: typing.ClassVar[int] = ...
    MARCH: typing.ClassVar[int] = ...
    MAY: typing.ClassVar[int] = ...
    MILLISECOND: typing.ClassVar[int] = ...
    MILLISECONDS_IN_DAY: typing.ClassVar[int] = ...
    MINUTE: typing.ClassVar[int] = ...
    MONDAY: typing.ClassVar[int] = ...
    MONTH: typing.ClassVar[int] = ...
    NOVEMBER: typing.ClassVar[int] = ...
    OCTOBER: typing.ClassVar[int] = ...
    PM: typing.ClassVar[int] = ...
    SATURDAY: typing.ClassVar[int] = ...
    SECOND: typing.ClassVar[int] = ...
    SEPTEMBER: typing.ClassVar[int] = ...
    SUNDAY: typing.ClassVar[int] = ...
    THURSDAY: typing.ClassVar[int] = ...
    TUESDAY: typing.ClassVar[int] = ...
    UNDECIMBER: typing.ClassVar[int] = ...
    WALLTIME_FIRST: typing.ClassVar[int] = ...
    WALLTIME_LAST: typing.ClassVar[int] = ...
    WALLTIME_NEXT_VALID: typing.ClassVar[int] = ...
    WEDNESDAY: typing.ClassVar[int] = ...
    WEEK_OF_MONTH: typing.ClassVar[int] = ...
    WEEK_OF_YEAR: typing.ClassVar[int] = ...
    YEAR: typing.ClassVar[int] = ...
    YEAR_WOY: typing.ClassVar[int] = ...
    ZONE_OFFSET: typing.ClassVar[int] = ...
    def add(self, int: int, int2: int) -> None: ...
    def after(self, object: typing.Any) -> bool: ...
    def before(self, object: typing.Any) -> bool: ...
    @typing.overload
    def clear(self) -> None: ...
    @typing.overload
    def clear(self, int: int) -> None: ...
    def clone(self) -> typing.Any: ...
    def compareTo(self, calendar: 'Calendar') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def fieldDifference(self, date: java.util.Date, int: int) -> int: ...
    def get(self, int: int) -> int: ...
    def getActualMaximum(self, int: int) -> int: ...
    def getActualMinimum(self, int: int) -> int: ...
    @staticmethod
    def getAvailableLocales() -> typing.MutableSequence[java.util.Locale]: ...
    @typing.overload
    def getDateTimeFormat(self, int: int, int2: int, uLocale: 'ULocale') -> android.icu.text.DateFormat: ...
    @typing.overload
    def getDateTimeFormat(self, int: int, int2: int, locale: java.util.Locale) -> android.icu.text.DateFormat: ...
    @typing.overload
    def getDisplayName(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    def getDisplayName(self, locale: java.util.Locale) -> str: ...
    def getFieldCount(self) -> int: ...
    def getFirstDayOfWeek(self) -> int: ...
    def getGreatestMinimum(self, int: int) -> int: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'Calendar': ...
    @typing.overload
    @staticmethod
    def getInstance(timeZone: 'TimeZone') -> 'Calendar': ...
    @typing.overload
    @staticmethod
    def getInstance(timeZone: 'TimeZone', uLocale: 'ULocale') -> 'Calendar': ...
    @typing.overload
    @staticmethod
    def getInstance(timeZone: 'TimeZone', locale: java.util.Locale) -> 'Calendar': ...
    @typing.overload
    @staticmethod
    def getInstance(uLocale: 'ULocale') -> 'Calendar': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'Calendar': ...
    @staticmethod
    def getKeywordValuesForLocale(string: str, uLocale: 'ULocale', boolean: bool) -> typing.MutableSequence[str]: ...
    def getLeastMaximum(self, int: int) -> int: ...
    def getMaximum(self, int: int) -> int: ...
    def getMinimalDaysInFirstWeek(self) -> int: ...
    def getMinimum(self, int: int) -> int: ...
    def getRepeatedWallTimeOption(self) -> int: ...
    def getSkippedWallTimeOption(self) -> int: ...
    def getTime(self) -> java.util.Date: ...
    def getTimeInMillis(self) -> int: ...
    def getTimeZone(self) -> 'TimeZone': ...
    def getType(self) -> str: ...
    def getWeekData(self) -> 'Calendar.WeekData': ...
    @staticmethod
    def getWeekDataForRegion(string: str) -> 'Calendar.WeekData': ...
    def hashCode(self) -> int: ...
    def isEquivalentTo(self, calendar: 'Calendar') -> bool: ...
    def isLenient(self) -> bool: ...
    def isSet(self, int: int) -> bool: ...
    @typing.overload
    def isWeekend(self) -> bool: ...
    @typing.overload
    def isWeekend(self, date: java.util.Date) -> bool: ...
    @typing.overload
    def roll(self, int: int, boolean: bool) -> None: ...
    @typing.overload
    def roll(self, int: int, int2: int) -> None: ...
    @typing.overload
    def set(self, int: int, int2: int) -> None: ...
    @typing.overload
    def set(self, int: int, int2: int, int3: int) -> None: ...
    @typing.overload
    def set(self, int: int, int2: int, int3: int, int4: int, int5: int) -> None: ...
    @typing.overload
    def set(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int) -> None: ...
    def setFirstDayOfWeek(self, int: int) -> None: ...
    def setLenient(self, boolean: bool) -> None: ...
    def setMinimalDaysInFirstWeek(self, int: int) -> None: ...
    def setRepeatedWallTimeOption(self, int: int) -> None: ...
    def setSkippedWallTimeOption(self, int: int) -> None: ...
    def setTime(self, date: java.util.Date) -> None: ...
    def setTimeInMillis(self, long: int) -> None: ...
    def setTimeZone(self, timeZone: 'TimeZone') -> None: ...
    def setWeekData(self, weekData: 'Calendar.WeekData') -> 'Calendar': ...
    def toString(self) -> str: ...
    class WeekData:
        firstDayOfWeek: int = ...
        minimalDaysInFirstWeek: int = ...
        weekendCease: int = ...
        weekendCeaseMillis: int = ...
        weekendOnset: int = ...
        weekendOnsetMillis: int = ...
        def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class DateInterval(java.io.Serializable):
    def __init__(self, long: int, long2: int): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFromDate(self) -> int: ...
    def getToDate(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

_Freezable__T = typing.TypeVar('_Freezable__T')  # <T>
class Freezable(java.lang.Cloneable, typing.Generic[_Freezable__T]):
    def cloneAsThawed(self) -> _Freezable__T: ...
    def freeze(self) -> _Freezable__T: ...
    def isFrozen(self) -> bool: ...

class ICUUncheckedIOException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, throwable: java.lang.Throwable): ...

class IllformedLocaleException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, int: int): ...
    def getErrorIndex(self) -> int: ...

class LocaleData:
    ALT_QUOTATION_END: typing.ClassVar[int] = ...
    ALT_QUOTATION_START: typing.ClassVar[int] = ...
    QUOTATION_END: typing.ClassVar[int] = ...
    QUOTATION_START: typing.ClassVar[int] = ...
    @staticmethod
    def getCLDRVersion() -> 'VersionInfo': ...
    def getDelimiter(self, int: int) -> str: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'LocaleData': ...
    @typing.overload
    @staticmethod
    def getInstance(uLocale: 'ULocale') -> 'LocaleData': ...
    @staticmethod
    def getMeasurementSystem(uLocale: 'ULocale') -> 'LocaleData.MeasurementSystem': ...
    def getNoSubstitute(self) -> bool: ...
    @staticmethod
    def getPaperSize(uLocale: 'ULocale') -> 'LocaleData.PaperSize': ...
    def setNoSubstitute(self, boolean: bool) -> None: ...
    class MeasurementSystem:
        SI: typing.ClassVar['LocaleData.MeasurementSystem'] = ...
        UK: typing.ClassVar['LocaleData.MeasurementSystem'] = ...
        US: typing.ClassVar['LocaleData.MeasurementSystem'] = ...
    class PaperSize:
        def getHeight(self) -> int: ...
        def getWidth(self) -> int: ...

class Measure:
    def __init__(self, number: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat], measureUnit: 'MeasureUnit'): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getNumber(self) -> java.lang.Number: ...
    def getUnit(self) -> 'MeasureUnit': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class MeasureUnit(java.io.Serializable):
    ACRE: typing.ClassVar['MeasureUnit'] = ...
    ACRE_FOOT: typing.ClassVar['MeasureUnit'] = ...
    AMPERE: typing.ClassVar['MeasureUnit'] = ...
    ARC_MINUTE: typing.ClassVar['MeasureUnit'] = ...
    ARC_SECOND: typing.ClassVar['MeasureUnit'] = ...
    ASTRONOMICAL_UNIT: typing.ClassVar['MeasureUnit'] = ...
    ATMOSPHERE: typing.ClassVar['MeasureUnit'] = ...
    BIT: typing.ClassVar['MeasureUnit'] = ...
    BUSHEL: typing.ClassVar['MeasureUnit'] = ...
    BYTE: typing.ClassVar['MeasureUnit'] = ...
    CALORIE: typing.ClassVar['MeasureUnit'] = ...
    CANDELA: typing.ClassVar['MeasureUnit'] = ...
    CARAT: typing.ClassVar['MeasureUnit'] = ...
    CELSIUS: typing.ClassVar['MeasureUnit'] = ...
    CENTILITER: typing.ClassVar['MeasureUnit'] = ...
    CENTIMETER: typing.ClassVar['MeasureUnit'] = ...
    CENTURY: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_CENTIMETER: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_FOOT: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_INCH: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_KILOMETER: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_METER: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_MILE: typing.ClassVar['MeasureUnit'] = ...
    CUBIC_YARD: typing.ClassVar['MeasureUnit'] = ...
    CUP: typing.ClassVar['MeasureUnit'] = ...
    CUP_METRIC: typing.ClassVar['MeasureUnit'] = ...
    DAY: typing.ClassVar['TimeUnit'] = ...
    DECADE: typing.ClassVar['MeasureUnit'] = ...
    DECILITER: typing.ClassVar['MeasureUnit'] = ...
    DECIMETER: typing.ClassVar['MeasureUnit'] = ...
    DEGREE: typing.ClassVar['MeasureUnit'] = ...
    DOT: typing.ClassVar['MeasureUnit'] = ...
    DOT_PER_CENTIMETER: typing.ClassVar['MeasureUnit'] = ...
    DOT_PER_INCH: typing.ClassVar['MeasureUnit'] = ...
    EM: typing.ClassVar['MeasureUnit'] = ...
    FAHRENHEIT: typing.ClassVar['MeasureUnit'] = ...
    FATHOM: typing.ClassVar['MeasureUnit'] = ...
    FLUID_OUNCE: typing.ClassVar['MeasureUnit'] = ...
    FOODCALORIE: typing.ClassVar['MeasureUnit'] = ...
    FOOT: typing.ClassVar['MeasureUnit'] = ...
    FURLONG: typing.ClassVar['MeasureUnit'] = ...
    GALLON: typing.ClassVar['MeasureUnit'] = ...
    GALLON_IMPERIAL: typing.ClassVar['MeasureUnit'] = ...
    GENERIC_TEMPERATURE: typing.ClassVar['MeasureUnit'] = ...
    GIGABIT: typing.ClassVar['MeasureUnit'] = ...
    GIGABYTE: typing.ClassVar['MeasureUnit'] = ...
    GIGAHERTZ: typing.ClassVar['MeasureUnit'] = ...
    GIGAWATT: typing.ClassVar['MeasureUnit'] = ...
    GRAM: typing.ClassVar['MeasureUnit'] = ...
    G_FORCE: typing.ClassVar['MeasureUnit'] = ...
    HECTARE: typing.ClassVar['MeasureUnit'] = ...
    HECTOLITER: typing.ClassVar['MeasureUnit'] = ...
    HECTOPASCAL: typing.ClassVar['MeasureUnit'] = ...
    HERTZ: typing.ClassVar['MeasureUnit'] = ...
    HORSEPOWER: typing.ClassVar['MeasureUnit'] = ...
    HOUR: typing.ClassVar['TimeUnit'] = ...
    INCH: typing.ClassVar['MeasureUnit'] = ...
    INCH_HG: typing.ClassVar['MeasureUnit'] = ...
    ITEM: typing.ClassVar['MeasureUnit'] = ...
    JOULE: typing.ClassVar['MeasureUnit'] = ...
    KARAT: typing.ClassVar['MeasureUnit'] = ...
    KELVIN: typing.ClassVar['MeasureUnit'] = ...
    KILOBIT: typing.ClassVar['MeasureUnit'] = ...
    KILOBYTE: typing.ClassVar['MeasureUnit'] = ...
    KILOCALORIE: typing.ClassVar['MeasureUnit'] = ...
    KILOGRAM: typing.ClassVar['MeasureUnit'] = ...
    KILOHERTZ: typing.ClassVar['MeasureUnit'] = ...
    KILOJOULE: typing.ClassVar['MeasureUnit'] = ...
    KILOMETER: typing.ClassVar['MeasureUnit'] = ...
    KILOMETER_PER_HOUR: typing.ClassVar['MeasureUnit'] = ...
    KILOWATT: typing.ClassVar['MeasureUnit'] = ...
    KILOWATT_HOUR: typing.ClassVar['MeasureUnit'] = ...
    KILOWATT_HOUR_PER_100_KILOMETER: typing.ClassVar['MeasureUnit'] = ...
    KNOT: typing.ClassVar['MeasureUnit'] = ...
    LIGHT_YEAR: typing.ClassVar['MeasureUnit'] = ...
    LITER: typing.ClassVar['MeasureUnit'] = ...
    LITER_PER_100KILOMETERS: typing.ClassVar['MeasureUnit'] = ...
    LITER_PER_KILOMETER: typing.ClassVar['MeasureUnit'] = ...
    LUMEN: typing.ClassVar['MeasureUnit'] = ...
    LUX: typing.ClassVar['MeasureUnit'] = ...
    MEGABIT: typing.ClassVar['MeasureUnit'] = ...
    MEGABYTE: typing.ClassVar['MeasureUnit'] = ...
    MEGAHERTZ: typing.ClassVar['MeasureUnit'] = ...
    MEGALITER: typing.ClassVar['MeasureUnit'] = ...
    MEGAPIXEL: typing.ClassVar['MeasureUnit'] = ...
    MEGAWATT: typing.ClassVar['MeasureUnit'] = ...
    METER: typing.ClassVar['MeasureUnit'] = ...
    METER_PER_SECOND: typing.ClassVar['MeasureUnit'] = ...
    METER_PER_SECOND_SQUARED: typing.ClassVar['MeasureUnit'] = ...
    METRIC_TON: typing.ClassVar['MeasureUnit'] = ...
    MICROGRAM: typing.ClassVar['MeasureUnit'] = ...
    MICROMETER: typing.ClassVar['MeasureUnit'] = ...
    MICROSECOND: typing.ClassVar['MeasureUnit'] = ...
    MILE: typing.ClassVar['MeasureUnit'] = ...
    MILE_PER_GALLON: typing.ClassVar['MeasureUnit'] = ...
    MILE_PER_GALLON_IMPERIAL: typing.ClassVar['MeasureUnit'] = ...
    MILE_PER_HOUR: typing.ClassVar['MeasureUnit'] = ...
    MILE_SCANDINAVIAN: typing.ClassVar['MeasureUnit'] = ...
    MILLIAMPERE: typing.ClassVar['MeasureUnit'] = ...
    MILLIBAR: typing.ClassVar['MeasureUnit'] = ...
    MILLIGRAM: typing.ClassVar['MeasureUnit'] = ...
    MILLIGRAM_OFGLUCOSE_PER_DECILITER: typing.ClassVar['MeasureUnit'] = ...
    MILLIGRAM_PER_DECILITER: typing.ClassVar['MeasureUnit'] = ...
    MILLILITER: typing.ClassVar['MeasureUnit'] = ...
    MILLIMETER: typing.ClassVar['MeasureUnit'] = ...
    MILLIMETER_OF_MERCURY: typing.ClassVar['MeasureUnit'] = ...
    MILLIMOLE_PER_LITER: typing.ClassVar['MeasureUnit'] = ...
    MILLISECOND: typing.ClassVar['MeasureUnit'] = ...
    MILLIWATT: typing.ClassVar['MeasureUnit'] = ...
    MINUTE: typing.ClassVar['TimeUnit'] = ...
    MONTH: typing.ClassVar['TimeUnit'] = ...
    NANOMETER: typing.ClassVar['MeasureUnit'] = ...
    NANOSECOND: typing.ClassVar['MeasureUnit'] = ...
    NAUTICAL_MILE: typing.ClassVar['MeasureUnit'] = ...
    OHM: typing.ClassVar['MeasureUnit'] = ...
    OUNCE: typing.ClassVar['MeasureUnit'] = ...
    OUNCE_TROY: typing.ClassVar['MeasureUnit'] = ...
    PARSEC: typing.ClassVar['MeasureUnit'] = ...
    PART_PER_MILLION: typing.ClassVar['MeasureUnit'] = ...
    PERCENT: typing.ClassVar['MeasureUnit'] = ...
    PERMILLE: typing.ClassVar['MeasureUnit'] = ...
    PETABYTE: typing.ClassVar['MeasureUnit'] = ...
    PICOMETER: typing.ClassVar['MeasureUnit'] = ...
    PINT: typing.ClassVar['MeasureUnit'] = ...
    PINT_METRIC: typing.ClassVar['MeasureUnit'] = ...
    PIXEL: typing.ClassVar['MeasureUnit'] = ...
    PIXEL_PER_CENTIMETER: typing.ClassVar['MeasureUnit'] = ...
    PIXEL_PER_INCH: typing.ClassVar['MeasureUnit'] = ...
    POINT: typing.ClassVar['MeasureUnit'] = ...
    POUND: typing.ClassVar['MeasureUnit'] = ...
    POUND_PER_SQUARE_INCH: typing.ClassVar['MeasureUnit'] = ...
    QUART: typing.ClassVar['MeasureUnit'] = ...
    QUARTER: typing.ClassVar['MeasureUnit'] = ...
    RADIAN: typing.ClassVar['MeasureUnit'] = ...
    REVOLUTION_ANGLE: typing.ClassVar['MeasureUnit'] = ...
    SECOND: typing.ClassVar['TimeUnit'] = ...
    SQUARE_CENTIMETER: typing.ClassVar['MeasureUnit'] = ...
    SQUARE_FOOT: typing.ClassVar['MeasureUnit'] = ...
    SQUARE_INCH: typing.ClassVar['MeasureUnit'] = ...
    SQUARE_KILOMETER: typing.ClassVar['MeasureUnit'] = ...
    SQUARE_METER: typing.ClassVar['MeasureUnit'] = ...
    SQUARE_MILE: typing.ClassVar['MeasureUnit'] = ...
    SQUARE_YARD: typing.ClassVar['MeasureUnit'] = ...
    STONE: typing.ClassVar['MeasureUnit'] = ...
    TABLESPOON: typing.ClassVar['MeasureUnit'] = ...
    TEASPOON: typing.ClassVar['MeasureUnit'] = ...
    TERABIT: typing.ClassVar['MeasureUnit'] = ...
    TERABYTE: typing.ClassVar['MeasureUnit'] = ...
    TON: typing.ClassVar['MeasureUnit'] = ...
    TONNE: typing.ClassVar['MeasureUnit'] = ...
    VOLT: typing.ClassVar['MeasureUnit'] = ...
    WATT: typing.ClassVar['MeasureUnit'] = ...
    WEEK: typing.ClassVar['TimeUnit'] = ...
    YARD: typing.ClassVar['MeasureUnit'] = ...
    YEAR: typing.ClassVar['TimeUnit'] = ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def forIdentifier(string: str) -> 'MeasureUnit': ...
    @typing.overload
    @staticmethod
    def getAvailable(string: str) -> java.util.Set['MeasureUnit']: ...
    @typing.overload
    @staticmethod
    def getAvailable() -> java.util.Set['MeasureUnit']: ...
    @staticmethod
    def getAvailableTypes() -> java.util.Set[str]: ...
    def getComplexity(self) -> 'MeasureUnit.Complexity': ...
    def getDimensionality(self) -> int: ...
    def getIdentifier(self) -> str: ...
    def getPrefix(self) -> 'MeasureUnit.MeasurePrefix': ...
    def getSubtype(self) -> str: ...
    def getType(self) -> str: ...
    def hashCode(self) -> int: ...
    def product(self, measureUnit: 'MeasureUnit') -> 'MeasureUnit': ...
    def reciprocal(self) -> 'MeasureUnit': ...
    def splitToSingleUnits(self) -> java.util.List['MeasureUnit']: ...
    def toString(self) -> str: ...
    def withDimensionality(self, int: int) -> 'MeasureUnit': ...
    def withPrefix(self, measurePrefix: 'MeasureUnit.MeasurePrefix') -> 'MeasureUnit': ...
    class Complexity(java.lang.Enum['MeasureUnit.Complexity']):
        SINGLE: typing.ClassVar['MeasureUnit.Complexity'] = ...
        COMPOUND: typing.ClassVar['MeasureUnit.Complexity'] = ...
        MIXED: typing.ClassVar['MeasureUnit.Complexity'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'MeasureUnit.Complexity': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['MeasureUnit.Complexity']: ...
    class MeasurePrefix(java.lang.Enum['MeasureUnit.MeasurePrefix']):
        YOTTA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        ZETTA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        EXA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        PETA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        TERA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        GIGA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        MEGA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        KILO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        HECTO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        DEKA: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        ONE: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        DECI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        CENTI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        MILLI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        MICRO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        NANO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        PICO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        FEMTO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        ATTO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        ZEPTO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        YOCTO: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        KIBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        MEBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        GIBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        TEBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        PEBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        EXBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        ZEBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        YOBI: typing.ClassVar['MeasureUnit.MeasurePrefix'] = ...
        def getBase(self) -> int: ...
        def getPower(self) -> int: ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'MeasureUnit.MeasurePrefix': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['MeasureUnit.MeasurePrefix']: ...

_Output__T = typing.TypeVar('_Output__T')  # <T>
class Output(typing.Generic[_Output__T]):
    value: typing.Any = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, t: _Output__T): ...
    def toString(self) -> str: ...

class RangeValueIterator:
    def next(self, element: 'RangeValueIterator.Element') -> bool: ...
    def reset(self) -> None: ...
    class Element:
        limit: int = ...
        start: int = ...
        value: int = ...
        def __init__(self): ...

class ULocale(java.io.Serializable, java.lang.Comparable['ULocale']):
    CANADA: typing.ClassVar['ULocale'] = ...
    CANADA_FRENCH: typing.ClassVar['ULocale'] = ...
    CHINA: typing.ClassVar['ULocale'] = ...
    CHINESE: typing.ClassVar['ULocale'] = ...
    ENGLISH: typing.ClassVar['ULocale'] = ...
    FRANCE: typing.ClassVar['ULocale'] = ...
    FRENCH: typing.ClassVar['ULocale'] = ...
    GERMAN: typing.ClassVar['ULocale'] = ...
    GERMANY: typing.ClassVar['ULocale'] = ...
    ITALIAN: typing.ClassVar['ULocale'] = ...
    ITALY: typing.ClassVar['ULocale'] = ...
    JAPAN: typing.ClassVar['ULocale'] = ...
    JAPANESE: typing.ClassVar['ULocale'] = ...
    KOREA: typing.ClassVar['ULocale'] = ...
    KOREAN: typing.ClassVar['ULocale'] = ...
    PRC: typing.ClassVar['ULocale'] = ...
    PRIVATE_USE_EXTENSION: typing.ClassVar[str] = ...
    ROOT: typing.ClassVar['ULocale'] = ...
    SIMPLIFIED_CHINESE: typing.ClassVar['ULocale'] = ...
    TAIWAN: typing.ClassVar['ULocale'] = ...
    TRADITIONAL_CHINESE: typing.ClassVar['ULocale'] = ...
    UK: typing.ClassVar['ULocale'] = ...
    UNICODE_LOCALE_EXTENSION: typing.ClassVar[str] = ...
    US: typing.ClassVar['ULocale'] = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str): ...
    @typing.overload
    @staticmethod
    def acceptLanguage(uLocaleArray: typing.Union[typing.List['ULocale'], jpype.JArray], uLocaleArray2: typing.Union[typing.List['ULocale'], jpype.JArray], booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def acceptLanguage(uLocaleArray: typing.Union[typing.List['ULocale'], jpype.JArray], booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def acceptLanguage(string: str, uLocaleArray: typing.Union[typing.List['ULocale'], jpype.JArray], booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def acceptLanguage(string: str, booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> 'ULocale': ...
    @staticmethod
    def addLikelySubtags(uLocale: 'ULocale') -> 'ULocale': ...
    @staticmethod
    def canonicalize(string: str) -> str: ...
    def clone(self) -> typing.Any: ...
    def compareTo(self, uLocale: 'ULocale') -> int: ...
    @typing.overload
    @staticmethod
    def createCanonical(uLocale: 'ULocale') -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def createCanonical(string: str) -> 'ULocale': ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def forLanguageTag(string: str) -> 'ULocale': ...
    @staticmethod
    def forLocale(locale: java.util.Locale) -> 'ULocale': ...
    @staticmethod
    def getAvailableLocales() -> typing.MutableSequence['ULocale']: ...
    @staticmethod
    def getAvailableLocalesByType(availableType: 'ULocale.AvailableType') -> java.util.Collection['ULocale']: ...
    @typing.overload
    def getBaseName(self) -> str: ...
    @typing.overload
    @staticmethod
    def getBaseName(string: str) -> str: ...
    def getCharacterOrientation(self) -> str: ...
    @typing.overload
    def getCountry(self) -> str: ...
    @typing.overload
    @staticmethod
    def getCountry(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getDefault() -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def getDefault(category: 'ULocale.Category') -> 'ULocale': ...
    @typing.overload
    def getDisplayCountry(self) -> str: ...
    @typing.overload
    def getDisplayCountry(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayCountry(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayCountry(string: str, string2: str) -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayKeyword(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayKeyword(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayKeyword(string: str, string2: str) -> str: ...
    @typing.overload
    def getDisplayKeywordValue(self, string: str) -> str: ...
    @typing.overload
    def getDisplayKeywordValue(self, string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayKeywordValue(string: str, string2: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayKeywordValue(string: str, string2: str, string3: str) -> str: ...
    @typing.overload
    def getDisplayLanguage(self) -> str: ...
    @typing.overload
    def getDisplayLanguage(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayLanguage(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayLanguage(string: str, string2: str) -> str: ...
    @typing.overload
    def getDisplayLanguageWithDialect(self) -> str: ...
    @typing.overload
    def getDisplayLanguageWithDialect(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayLanguageWithDialect(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayLanguageWithDialect(string: str, string2: str) -> str: ...
    @typing.overload
    def getDisplayName(self) -> str: ...
    @typing.overload
    def getDisplayName(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayName(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayName(string: str, string2: str) -> str: ...
    @typing.overload
    def getDisplayNameWithDialect(self) -> str: ...
    @typing.overload
    def getDisplayNameWithDialect(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayNameWithDialect(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayNameWithDialect(string: str, string2: str) -> str: ...
    @typing.overload
    def getDisplayScript(self) -> str: ...
    @typing.overload
    def getDisplayScript(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayScript(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayScript(string: str, string2: str) -> str: ...
    @typing.overload
    def getDisplayVariant(self) -> str: ...
    @typing.overload
    def getDisplayVariant(self, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayVariant(string: str, uLocale: 'ULocale') -> str: ...
    @typing.overload
    @staticmethod
    def getDisplayVariant(string: str, string2: str) -> str: ...
    def getExtension(self, char: str) -> str: ...
    def getExtensionKeys(self) -> java.util.Set[str]: ...
    @typing.overload
    def getFallback(self) -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def getFallback(string: str) -> str: ...
    @typing.overload
    def getISO3Country(self) -> str: ...
    @typing.overload
    @staticmethod
    def getISO3Country(string: str) -> str: ...
    @typing.overload
    def getISO3Language(self) -> str: ...
    @typing.overload
    @staticmethod
    def getISO3Language(string: str) -> str: ...
    @staticmethod
    def getISOCountries() -> typing.MutableSequence[str]: ...
    @staticmethod
    def getISOLanguages() -> typing.MutableSequence[str]: ...
    @typing.overload
    def getKeywordValue(self, string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getKeywordValue(string: str, string2: str) -> str: ...
    @typing.overload
    def getKeywords(self) -> java.util.Iterator[str]: ...
    @typing.overload
    @staticmethod
    def getKeywords(string: str) -> java.util.Iterator[str]: ...
    @typing.overload
    def getLanguage(self) -> str: ...
    @typing.overload
    @staticmethod
    def getLanguage(string: str) -> str: ...
    def getLineOrientation(self) -> str: ...
    @typing.overload
    def getName(self) -> str: ...
    @typing.overload
    @staticmethod
    def getName(string: str) -> str: ...
    @typing.overload
    def getScript(self) -> str: ...
    @typing.overload
    @staticmethod
    def getScript(string: str) -> str: ...
    def getUnicodeLocaleAttributes(self) -> java.util.Set[str]: ...
    def getUnicodeLocaleKeys(self) -> java.util.Set[str]: ...
    def getUnicodeLocaleType(self, string: str) -> str: ...
    @typing.overload
    def getVariant(self) -> str: ...
    @typing.overload
    @staticmethod
    def getVariant(string: str) -> str: ...
    def hashCode(self) -> int: ...
    def isRightToLeft(self) -> bool: ...
    @staticmethod
    def minimizeSubtags(uLocale: 'ULocale') -> 'ULocale': ...
    @typing.overload
    def setKeywordValue(self, string: str, string2: str) -> 'ULocale': ...
    @typing.overload
    @staticmethod
    def setKeywordValue(string: str, string2: str, string3: str) -> str: ...
    def toLanguageTag(self) -> str: ...
    @staticmethod
    def toLegacyKey(string: str) -> str: ...
    @staticmethod
    def toLegacyType(string: str, string2: str) -> str: ...
    def toLocale(self) -> java.util.Locale: ...
    def toString(self) -> str: ...
    @staticmethod
    def toUnicodeLocaleKey(string: str) -> str: ...
    @staticmethod
    def toUnicodeLocaleType(string: str, string2: str) -> str: ...
    class AvailableType(java.lang.Enum['ULocale.AvailableType']):
        DEFAULT: typing.ClassVar['ULocale.AvailableType'] = ...
        ONLY_LEGACY_ALIASES: typing.ClassVar['ULocale.AvailableType'] = ...
        WITH_LEGACY_ALIASES: typing.ClassVar['ULocale.AvailableType'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'ULocale.AvailableType': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['ULocale.AvailableType']: ...
    class Builder:
        def __init__(self): ...
        def addUnicodeLocaleAttribute(self, string: str) -> 'ULocale.Builder': ...
        def build(self) -> 'ULocale': ...
        def clear(self) -> 'ULocale.Builder': ...
        def clearExtensions(self) -> 'ULocale.Builder': ...
        def removeUnicodeLocaleAttribute(self, string: str) -> 'ULocale.Builder': ...
        def setExtension(self, char: str, string: str) -> 'ULocale.Builder': ...
        def setLanguage(self, string: str) -> 'ULocale.Builder': ...
        def setLanguageTag(self, string: str) -> 'ULocale.Builder': ...
        def setLocale(self, uLocale: 'ULocale') -> 'ULocale.Builder': ...
        def setRegion(self, string: str) -> 'ULocale.Builder': ...
        def setScript(self, string: str) -> 'ULocale.Builder': ...
        def setUnicodeLocaleKeyword(self, string: str, string2: str) -> 'ULocale.Builder': ...
        def setVariant(self, string: str) -> 'ULocale.Builder': ...
    class Category(java.lang.Enum['ULocale.Category']):
        DISPLAY: typing.ClassVar['ULocale.Category'] = ...
        FORMAT: typing.ClassVar['ULocale.Category'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'ULocale.Category': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['ULocale.Category']: ...

class UniversalTimeScale:
    DB2_TIME: typing.ClassVar[int] = ...
    DOTNET_DATE_TIME: typing.ClassVar[int] = ...
    EPOCH_OFFSET_PLUS_1_VALUE: typing.ClassVar[int] = ...
    EPOCH_OFFSET_VALUE: typing.ClassVar[int] = ...
    EXCEL_TIME: typing.ClassVar[int] = ...
    FROM_MAX_VALUE: typing.ClassVar[int] = ...
    FROM_MIN_VALUE: typing.ClassVar[int] = ...
    ICU4C_TIME: typing.ClassVar[int] = ...
    JAVA_TIME: typing.ClassVar[int] = ...
    MAC_OLD_TIME: typing.ClassVar[int] = ...
    MAC_TIME: typing.ClassVar[int] = ...
    MAX_SCALE: typing.ClassVar[int] = ...
    TO_MAX_VALUE: typing.ClassVar[int] = ...
    TO_MIN_VALUE: typing.ClassVar[int] = ...
    UNITS_VALUE: typing.ClassVar[int] = ...
    UNIX_MICROSECONDS_TIME: typing.ClassVar[int] = ...
    UNIX_TIME: typing.ClassVar[int] = ...
    WINDOWS_FILE_TIME: typing.ClassVar[int] = ...
    @typing.overload
    @staticmethod
    def bigDecimalFrom(bigDecimal: android.icu.math.BigDecimal, int: int) -> android.icu.math.BigDecimal: ...
    @typing.overload
    @staticmethod
    def bigDecimalFrom(double: float, int: int) -> android.icu.math.BigDecimal: ...
    @typing.overload
    @staticmethod
    def bigDecimalFrom(long: int, int: int) -> android.icu.math.BigDecimal: ...
    @staticmethod
    def from_(long: int, int: int) -> int: ...
    @staticmethod
    def getTimeScaleValue(int: int, int2: int) -> int: ...
    @typing.overload
    @staticmethod
    def toBigDecimal(bigDecimal: android.icu.math.BigDecimal, int: int) -> android.icu.math.BigDecimal: ...
    @typing.overload
    @staticmethod
    def toBigDecimal(long: int, int: int) -> android.icu.math.BigDecimal: ...
    @staticmethod
    def toLong(long: int, int: int) -> int: ...

class ValueIterator:
    def next(self, element: 'ValueIterator.Element') -> bool: ...
    def reset(self) -> None: ...
    def setRange(self, int: int, int2: int) -> None: ...
    class Element:
        integer: int = ...
        value: typing.Any = ...
        def __init__(self): ...

class VersionInfo(java.lang.Comparable['VersionInfo']):
    ICU_VERSION: typing.ClassVar['VersionInfo'] = ...
    UCOL_BUILDER_VERSION: typing.ClassVar['VersionInfo'] = ...
    UCOL_RUNTIME_VERSION: typing.ClassVar['VersionInfo'] = ...
    UNICODE_10_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_11_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_12_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_12_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_13_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_14_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_15_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_15_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_1_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_1_0_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_1_1_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_1_1_5: typing.ClassVar['VersionInfo'] = ...
    UNICODE_2_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_2_1_2: typing.ClassVar['VersionInfo'] = ...
    UNICODE_2_1_5: typing.ClassVar['VersionInfo'] = ...
    UNICODE_2_1_8: typing.ClassVar['VersionInfo'] = ...
    UNICODE_2_1_9: typing.ClassVar['VersionInfo'] = ...
    UNICODE_3_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_3_0_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_3_1_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_3_1_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_3_2: typing.ClassVar['VersionInfo'] = ...
    UNICODE_4_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_4_0_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_4_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_5_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_5_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_5_2: typing.ClassVar['VersionInfo'] = ...
    UNICODE_6_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_6_1: typing.ClassVar['VersionInfo'] = ...
    UNICODE_6_2: typing.ClassVar['VersionInfo'] = ...
    UNICODE_6_3: typing.ClassVar['VersionInfo'] = ...
    UNICODE_7_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_8_0: typing.ClassVar['VersionInfo'] = ...
    UNICODE_9_0: typing.ClassVar['VersionInfo'] = ...
    def compareTo(self, versionInfo: 'VersionInfo') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @typing.overload
    @staticmethod
    def getInstance(int: int) -> 'VersionInfo': ...
    @typing.overload
    @staticmethod
    def getInstance(int: int, int2: int) -> 'VersionInfo': ...
    @typing.overload
    @staticmethod
    def getInstance(int: int, int2: int, int3: int) -> 'VersionInfo': ...
    @typing.overload
    @staticmethod
    def getInstance(int: int, int2: int, int3: int, int4: int) -> 'VersionInfo': ...
    @typing.overload
    @staticmethod
    def getInstance(string: str) -> 'VersionInfo': ...
    def getMajor(self) -> int: ...
    def getMicro(self) -> int: ...
    def getMilli(self) -> int: ...
    def getMinor(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ChineseCalendar(Calendar):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int, int7: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int, int7: int, int8: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def add(self, int: int, int2: int) -> None: ...
    def getType(self) -> str: ...
    @typing.overload
    def roll(self, int: int, boolean: bool) -> None: ...
    @typing.overload
    def roll(self, int: int, int2: int) -> None: ...

class CopticCalendar(Calendar):
    AMSHIR: typing.ClassVar[int] = ...
    BABA: typing.ClassVar[int] = ...
    BARAMHAT: typing.ClassVar[int] = ...
    BARAMOUDA: typing.ClassVar[int] = ...
    BASHANS: typing.ClassVar[int] = ...
    EPEP: typing.ClassVar[int] = ...
    HATOR: typing.ClassVar[int] = ...
    KIAHK: typing.ClassVar[int] = ...
    MESRA: typing.ClassVar[int] = ...
    NASIE: typing.ClassVar[int] = ...
    PAONA: typing.ClassVar[int] = ...
    TOBA: typing.ClassVar[int] = ...
    TOUT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getType(self) -> str: ...

class Currency(MeasureUnit):
    FORMAL_SYMBOL_NAME: typing.ClassVar[int] = ...
    LONG_NAME: typing.ClassVar[int] = ...
    NARROW_SYMBOL_NAME: typing.ClassVar[int] = ...
    PLURAL_LONG_NAME: typing.ClassVar[int] = ...
    SYMBOL_NAME: typing.ClassVar[int] = ...
    VARIANT_SYMBOL_NAME: typing.ClassVar[int] = ...
    @staticmethod
    def fromJavaCurrency(currency: java.util.Currency) -> 'Currency': ...
    @staticmethod
    def getAvailableCurrencies() -> java.util.Set['Currency']: ...
    @typing.overload
    @staticmethod
    def getAvailableCurrencyCodes(uLocale: ULocale, date: java.util.Date) -> typing.MutableSequence[str]: ...
    @typing.overload
    @staticmethod
    def getAvailableCurrencyCodes(locale: java.util.Locale, date: java.util.Date) -> typing.MutableSequence[str]: ...
    @staticmethod
    def getAvailableLocales() -> typing.MutableSequence[java.util.Locale]: ...
    @staticmethod
    def getAvailableULocales() -> typing.MutableSequence[ULocale]: ...
    def getCurrencyCode(self) -> str: ...
    @typing.overload
    def getDefaultFractionDigits(self) -> int: ...
    @typing.overload
    def getDefaultFractionDigits(self, currencyUsage: 'Currency.CurrencyUsage') -> int: ...
    @typing.overload
    def getDisplayName(self) -> str: ...
    @typing.overload
    def getDisplayName(self, locale: java.util.Locale) -> str: ...
    @typing.overload
    @staticmethod
    def getInstance(uLocale: ULocale) -> 'Currency': ...
    @typing.overload
    @staticmethod
    def getInstance(string: str) -> 'Currency': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'Currency': ...
    @staticmethod
    def getKeywordValuesForLocale(string: str, uLocale: ULocale, boolean: bool) -> typing.MutableSequence[str]: ...
    @typing.overload
    def getName(self, uLocale: ULocale, int: int, booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> str: ...
    @typing.overload
    def getName(self, uLocale: ULocale, int: int, string: str, booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> str: ...
    @typing.overload
    def getName(self, locale: java.util.Locale, int: int, booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> str: ...
    @typing.overload
    def getName(self, locale: java.util.Locale, int: int, string: str, booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> str: ...
    def getNumericCode(self) -> int: ...
    @typing.overload
    def getRoundingIncrement(self) -> float: ...
    @typing.overload
    def getRoundingIncrement(self, currencyUsage: 'Currency.CurrencyUsage') -> float: ...
    @typing.overload
    def getSymbol(self) -> str: ...
    @typing.overload
    def getSymbol(self, uLocale: ULocale) -> str: ...
    @typing.overload
    def getSymbol(self, locale: java.util.Locale) -> str: ...
    @staticmethod
    def isAvailable(string: str, date: java.util.Date, date2: java.util.Date) -> bool: ...
    def toJavaCurrency(self) -> java.util.Currency: ...
    def toString(self) -> str: ...
    class CurrencyUsage(java.lang.Enum['Currency.CurrencyUsage']):
        STANDARD: typing.ClassVar['Currency.CurrencyUsage'] = ...
        CASH: typing.ClassVar['Currency.CurrencyUsage'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Currency.CurrencyUsage': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Currency.CurrencyUsage']: ...

class CurrencyAmount(Measure):
    @typing.overload
    def __init__(self, double: float, currency: Currency): ...
    @typing.overload
    def __init__(self, double: float, currency: java.util.Currency): ...
    @typing.overload
    def __init__(self, number: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat], currency: Currency): ...
    @typing.overload
    def __init__(self, number: typing.Union[_jpype._JNumberLong, _jpype._JNumberFloat, typing.SupportsIndex, typing.SupportsFloat], currency: java.util.Currency): ...
    def getCurrency(self) -> Currency: ...

class EthiopicCalendar(Calendar):
    GENBOT: typing.ClassVar[int] = ...
    HAMLE: typing.ClassVar[int] = ...
    HEDAR: typing.ClassVar[int] = ...
    MEGABIT: typing.ClassVar[int] = ...
    MESKEREM: typing.ClassVar[int] = ...
    MIAZIA: typing.ClassVar[int] = ...
    NEHASSE: typing.ClassVar[int] = ...
    PAGUMEN: typing.ClassVar[int] = ...
    SENE: typing.ClassVar[int] = ...
    TAHSAS: typing.ClassVar[int] = ...
    TEKEMT: typing.ClassVar[int] = ...
    TER: typing.ClassVar[int] = ...
    YEKATIT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getType(self) -> str: ...
    def isAmeteAlemEra(self) -> bool: ...
    def setAmeteAlemEra(self, boolean: bool) -> None: ...

class GregorianCalendar(Calendar):
    AD: typing.ClassVar[int] = ...
    BC: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getActualMaximum(self, int: int) -> int: ...
    def getActualMinimum(self, int: int) -> int: ...
    def getGregorianChange(self) -> java.util.Date: ...
    def getType(self) -> str: ...
    def hashCode(self) -> int: ...
    def isEquivalentTo(self, calendar: Calendar) -> bool: ...
    def isLeapYear(self, int: int) -> bool: ...
    @typing.overload
    def roll(self, int: int, boolean: bool) -> None: ...
    @typing.overload
    def roll(self, int: int, int2: int) -> None: ...
    def setGregorianChange(self, date: java.util.Date) -> None: ...

class HebrewCalendar(Calendar):
    ADAR: typing.ClassVar[int] = ...
    ADAR_1: typing.ClassVar[int] = ...
    AV: typing.ClassVar[int] = ...
    ELUL: typing.ClassVar[int] = ...
    HESHVAN: typing.ClassVar[int] = ...
    IYAR: typing.ClassVar[int] = ...
    KISLEV: typing.ClassVar[int] = ...
    NISAN: typing.ClassVar[int] = ...
    SHEVAT: typing.ClassVar[int] = ...
    SIVAN: typing.ClassVar[int] = ...
    TAMUZ: typing.ClassVar[int] = ...
    TEVET: typing.ClassVar[int] = ...
    TISHRI: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def add(self, int: int, int2: int) -> None: ...
    def getType(self) -> str: ...
    @typing.overload
    def roll(self, int: int, boolean: bool) -> None: ...
    @typing.overload
    def roll(self, int: int, int2: int) -> None: ...

class IndianCalendar(Calendar):
    AGRAHAYANA: typing.ClassVar[int] = ...
    ASADHA: typing.ClassVar[int] = ...
    ASVINA: typing.ClassVar[int] = ...
    BHADRA: typing.ClassVar[int] = ...
    CHAITRA: typing.ClassVar[int] = ...
    IE: typing.ClassVar[int] = ...
    JYAISTHA: typing.ClassVar[int] = ...
    KARTIKA: typing.ClassVar[int] = ...
    MAGHA: typing.ClassVar[int] = ...
    PAUSA: typing.ClassVar[int] = ...
    PHALGUNA: typing.ClassVar[int] = ...
    SRAVANA: typing.ClassVar[int] = ...
    VAISAKHA: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getType(self) -> str: ...

class IslamicCalendar(Calendar):
    DHU_AL_HIJJAH: typing.ClassVar[int] = ...
    DHU_AL_QIDAH: typing.ClassVar[int] = ...
    JUMADA_1: typing.ClassVar[int] = ...
    JUMADA_2: typing.ClassVar[int] = ...
    MUHARRAM: typing.ClassVar[int] = ...
    RABI_1: typing.ClassVar[int] = ...
    RABI_2: typing.ClassVar[int] = ...
    RAJAB: typing.ClassVar[int] = ...
    RAMADAN: typing.ClassVar[int] = ...
    SAFAR: typing.ClassVar[int] = ...
    SHABAN: typing.ClassVar[int] = ...
    SHAWWAL: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone'): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: 'TimeZone', locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getCalculationType(self) -> 'IslamicCalendar.CalculationType': ...
    def getType(self) -> str: ...
    def setCalculationType(self, calculationType: 'IslamicCalendar.CalculationType') -> None: ...
    class CalculationType(java.lang.Enum['IslamicCalendar.CalculationType']):
        ISLAMIC: typing.ClassVar['IslamicCalendar.CalculationType'] = ...
        ISLAMIC_CIVIL: typing.ClassVar['IslamicCalendar.CalculationType'] = ...
        ISLAMIC_UMALQURA: typing.ClassVar['IslamicCalendar.CalculationType'] = ...
        ISLAMIC_TBLA: typing.ClassVar['IslamicCalendar.CalculationType'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'IslamicCalendar.CalculationType': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['IslamicCalendar.CalculationType']: ...

class TimeUnit(MeasureUnit):
    @staticmethod
    def values() -> typing.MutableSequence['TimeUnit']: ...

class TimeZone(java.io.Serializable, java.lang.Cloneable, Freezable['TimeZone']):
    GENERIC_LOCATION: typing.ClassVar[int] = ...
    GMT_ZONE: typing.ClassVar['TimeZone'] = ...
    LONG: typing.ClassVar[int] = ...
    LONG_GENERIC: typing.ClassVar[int] = ...
    LONG_GMT: typing.ClassVar[int] = ...
    SHORT: typing.ClassVar[int] = ...
    SHORT_COMMONLY_USED: typing.ClassVar[int] = ...
    SHORT_GENERIC: typing.ClassVar[int] = ...
    SHORT_GMT: typing.ClassVar[int] = ...
    TIMEZONE_ICU: typing.ClassVar[int] = ...
    TIMEZONE_JDK: typing.ClassVar[int] = ...
    UNKNOWN_ZONE: typing.ClassVar['TimeZone'] = ...
    UNKNOWN_ZONE_ID: typing.ClassVar[str] = ...
    def __init__(self): ...
    def clone(self) -> typing.Any: ...
    def cloneAsThawed(self) -> 'TimeZone': ...
    @staticmethod
    def countEquivalentIDs(string: str) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def freeze(self) -> 'TimeZone': ...
    @typing.overload
    @staticmethod
    def getAvailableIDs() -> typing.MutableSequence[str]: ...
    @typing.overload
    @staticmethod
    def getAvailableIDs(int: int) -> typing.MutableSequence[str]: ...
    @typing.overload
    @staticmethod
    def getAvailableIDs(string: str) -> typing.MutableSequence[str]: ...
    @typing.overload
    @staticmethod
    def getAvailableIDs(systemTimeZoneType: 'TimeZone.SystemTimeZoneType', string: str, integer: int) -> java.util.Set[str]: ...
    @typing.overload
    @staticmethod
    def getCanonicalID(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getCanonicalID(string: str, booleanArray: typing.Union[typing.List[bool], jpype.JArray]) -> str: ...
    def getDSTSavings(self) -> int: ...
    @staticmethod
    def getDefault() -> 'TimeZone': ...
    @typing.overload
    def getDisplayName(self) -> str: ...
    @typing.overload
    def getDisplayName(self, uLocale: ULocale) -> str: ...
    @typing.overload
    def getDisplayName(self, boolean: bool, int: int) -> str: ...
    @typing.overload
    def getDisplayName(self, locale: java.util.Locale) -> str: ...
    @typing.overload
    def getDisplayName(self, boolean: bool, int: int, uLocale: ULocale) -> str: ...
    @typing.overload
    def getDisplayName(self, boolean: bool, int: int, locale: java.util.Locale) -> str: ...
    @staticmethod
    def getEquivalentID(string: str, int: int) -> str: ...
    @staticmethod
    def getFrozenTimeZone(string: str) -> 'TimeZone': ...
    def getID(self) -> str: ...
    @staticmethod
    def getIDForWindowsID(string: str, string2: str) -> str: ...
    @typing.overload
    def getOffset(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int) -> int: ...
    @typing.overload
    def getOffset(self, long: int) -> int: ...
    @typing.overload
    def getOffset(self, long: int, boolean: bool, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def getRawOffset(self) -> int: ...
    @staticmethod
    def getRegion(string: str) -> str: ...
    @staticmethod
    def getTZDataVersion() -> str: ...
    @typing.overload
    @staticmethod
    def getTimeZone(string: str) -> 'TimeZone': ...
    @typing.overload
    @staticmethod
    def getTimeZone(string: str, int: int) -> 'TimeZone': ...
    @staticmethod
    def getWindowsID(string: str) -> str: ...
    def hasSameRules(self, timeZone: 'TimeZone') -> bool: ...
    def hashCode(self) -> int: ...
    def inDaylightTime(self, date: java.util.Date) -> bool: ...
    def isFrozen(self) -> bool: ...
    def observesDaylightTime(self) -> bool: ...
    def setID(self, string: str) -> None: ...
    def setRawOffset(self, int: int) -> None: ...
    def useDaylightTime(self) -> bool: ...
    class SystemTimeZoneType(java.lang.Enum['TimeZone.SystemTimeZoneType']):
        ANY: typing.ClassVar['TimeZone.SystemTimeZoneType'] = ...
        CANONICAL: typing.ClassVar['TimeZone.SystemTimeZoneType'] = ...
        CANONICAL_LOCATION: typing.ClassVar['TimeZone.SystemTimeZoneType'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'TimeZone.SystemTimeZoneType': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['TimeZone.SystemTimeZoneType']: ...

class BuddhistCalendar(GregorianCalendar):
    BE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone, locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getType(self) -> str: ...

class JapaneseCalendar(GregorianCalendar):
    HEISEI: typing.ClassVar[int] = ...
    MEIJI: typing.ClassVar[int] = ...
    REIWA: typing.ClassVar[int] = ...
    SHOWA: typing.ClassVar[int] = ...
    TAISHO: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone, locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getActualMaximum(self, int: int) -> int: ...
    def getType(self) -> str: ...

class TaiwanCalendar(GregorianCalendar):
    BEFORE_MINGUO: typing.ClassVar[int] = ...
    MINGUO: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, timeZone: TimeZone, locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, uLocale: ULocale): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int): ...
    @typing.overload
    def __init__(self, date: java.util.Date): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getType(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.icu.util")``.

    BuddhistCalendar: typing.Type[BuddhistCalendar]
    Calendar: typing.Type[Calendar]
    ChineseCalendar: typing.Type[ChineseCalendar]
    CopticCalendar: typing.Type[CopticCalendar]
    Currency: typing.Type[Currency]
    CurrencyAmount: typing.Type[CurrencyAmount]
    DateInterval: typing.Type[DateInterval]
    EthiopicCalendar: typing.Type[EthiopicCalendar]
    Freezable: typing.Type[Freezable]
    GregorianCalendar: typing.Type[GregorianCalendar]
    HebrewCalendar: typing.Type[HebrewCalendar]
    ICUUncheckedIOException: typing.Type[ICUUncheckedIOException]
    IllformedLocaleException: typing.Type[IllformedLocaleException]
    IndianCalendar: typing.Type[IndianCalendar]
    IslamicCalendar: typing.Type[IslamicCalendar]
    JapaneseCalendar: typing.Type[JapaneseCalendar]
    LocaleData: typing.Type[LocaleData]
    Measure: typing.Type[Measure]
    MeasureUnit: typing.Type[MeasureUnit]
    Output: typing.Type[Output]
    RangeValueIterator: typing.Type[RangeValueIterator]
    TaiwanCalendar: typing.Type[TaiwanCalendar]
    TimeUnit: typing.Type[TimeUnit]
    TimeZone: typing.Type[TimeZone]
    ULocale: typing.Type[ULocale]
    UniversalTimeScale: typing.Type[UniversalTimeScale]
    ValueIterator: typing.Type[ValueIterator]
    VersionInfo: typing.Type[VersionInfo]
