
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content.pm
import android.content.res.loader
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import java.io
import java.lang
import java.nio.channels
import java.util
import jpype
import org.xmlpull.v1
import typing



class AssetFileDescriptor(android.os.Parcelable, java.io.Closeable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    UNKNOWN_LENGTH: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, long: int, long2: int): ...
    @typing.overload
    def __init__(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, long: int, long2: int, bundle: android.os.Bundle): ...
    def close(self) -> None: ...
    def createInputStream(self) -> java.io.FileInputStream: ...
    def createOutputStream(self) -> java.io.FileOutputStream: ...
    def describeContents(self) -> int: ...
    def getDeclaredLength(self) -> int: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFileDescriptor(self) -> java.io.FileDescriptor: ...
    def getLength(self) -> int: ...
    def getParcelFileDescriptor(self) -> android.os.ParcelFileDescriptor: ...
    def getStartOffset(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class AutoCloseInputStream(android.os.ParcelFileDescriptor.AutoCloseInputStream):
        def __init__(self, assetFileDescriptor: 'AssetFileDescriptor'): ...
        def available(self) -> int: ...
        def close(self) -> None: ...
        def getChannel(self) -> java.nio.channels.FileChannel: ...
        def mark(self, int: int) -> None: ...
        def markSupported(self) -> bool: ...
        @typing.overload
        def read(self) -> int: ...
        @typing.overload
        def read(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> int: ...
        @typing.overload
        def read(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
        def reset(self) -> None: ...
        def skip(self, long: int) -> int: ...
    class AutoCloseOutputStream(android.os.ParcelFileDescriptor.AutoCloseOutputStream):
        def __init__(self, assetFileDescriptor: 'AssetFileDescriptor'): ...
        @typing.overload
        def write(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
        @typing.overload
        def write(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> None: ...
        @typing.overload
        def write(self, int: int) -> None: ...

class AssetManager(java.lang.AutoCloseable):
    ACCESS_BUFFER: typing.ClassVar[int] = ...
    ACCESS_RANDOM: typing.ClassVar[int] = ...
    ACCESS_STREAMING: typing.ClassVar[int] = ...
    ACCESS_UNKNOWN: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def getLocales(self) -> typing.MutableSequence[str]: ...
    def list(self, string: str) -> typing.MutableSequence[str]: ...
    @typing.overload
    def open(self, string: str) -> java.io.InputStream: ...
    @typing.overload
    def open(self, string: str, int: int) -> java.io.InputStream: ...
    def openFd(self, string: str) -> AssetFileDescriptor: ...
    @typing.overload
    def openNonAssetFd(self, int: int, string: str) -> AssetFileDescriptor: ...
    @typing.overload
    def openNonAssetFd(self, string: str) -> AssetFileDescriptor: ...
    @typing.overload
    def openXmlResourceParser(self, int: int, string: str) -> 'XmlResourceParser': ...
    @typing.overload
    def openXmlResourceParser(self, string: str) -> 'XmlResourceParser': ...
    class AssetInputStream(java.io.InputStream):
        def available(self) -> int: ...
        def close(self) -> None: ...
        def mark(self, int: int) -> None: ...
        def markSupported(self) -> bool: ...
        @typing.overload
        def read(self) -> int: ...
        @typing.overload
        def read(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> int: ...
        @typing.overload
        def read(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
        def reset(self) -> None: ...
        def skip(self, long: int) -> int: ...

class ColorStateList(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, intArray: typing.Union[typing.List[typing.MutableSequence[int]], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]): ...
    @typing.overload
    @staticmethod
    def createFromXml(resources: 'Resources', xmlPullParser: org.xmlpull.v1.XmlPullParser) -> 'ColorStateList': ...
    @typing.overload
    @staticmethod
    def createFromXml(resources: 'Resources', xmlPullParser: org.xmlpull.v1.XmlPullParser, theme: 'Resources.Theme') -> 'ColorStateList': ...
    def describeContents(self) -> int: ...
    def getChangingConfigurations(self) -> int: ...
    def getColorForState(self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int) -> int: ...
    def getDefaultColor(self) -> int: ...
    def isOpaque(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def valueOf(int: int) -> 'ColorStateList': ...
    def withAlpha(self, int: int) -> 'ColorStateList': ...
    def withLStar(self, float: float) -> 'ColorStateList': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Configuration(android.os.Parcelable, java.lang.Comparable['Configuration']):
    COLOR_MODE_HDR_MASK: typing.ClassVar[int] = ...
    COLOR_MODE_HDR_NO: typing.ClassVar[int] = ...
    COLOR_MODE_HDR_SHIFT: typing.ClassVar[int] = ...
    COLOR_MODE_HDR_UNDEFINED: typing.ClassVar[int] = ...
    COLOR_MODE_HDR_YES: typing.ClassVar[int] = ...
    COLOR_MODE_UNDEFINED: typing.ClassVar[int] = ...
    COLOR_MODE_WIDE_COLOR_GAMUT_MASK: typing.ClassVar[int] = ...
    COLOR_MODE_WIDE_COLOR_GAMUT_NO: typing.ClassVar[int] = ...
    COLOR_MODE_WIDE_COLOR_GAMUT_UNDEFINED: typing.ClassVar[int] = ...
    COLOR_MODE_WIDE_COLOR_GAMUT_YES: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DENSITY_DPI_UNDEFINED: typing.ClassVar[int] = ...
    FONT_WEIGHT_ADJUSTMENT_UNDEFINED: typing.ClassVar[int] = ...
    GRAMMATICAL_GENDER_FEMININE: typing.ClassVar[int] = ...
    GRAMMATICAL_GENDER_MASCULINE: typing.ClassVar[int] = ...
    GRAMMATICAL_GENDER_NEUTRAL: typing.ClassVar[int] = ...
    GRAMMATICAL_GENDER_NOT_SPECIFIED: typing.ClassVar[int] = ...
    HARDKEYBOARDHIDDEN_NO: typing.ClassVar[int] = ...
    HARDKEYBOARDHIDDEN_UNDEFINED: typing.ClassVar[int] = ...
    HARDKEYBOARDHIDDEN_YES: typing.ClassVar[int] = ...
    KEYBOARDHIDDEN_NO: typing.ClassVar[int] = ...
    KEYBOARDHIDDEN_UNDEFINED: typing.ClassVar[int] = ...
    KEYBOARDHIDDEN_YES: typing.ClassVar[int] = ...
    KEYBOARD_12KEY: typing.ClassVar[int] = ...
    KEYBOARD_NOKEYS: typing.ClassVar[int] = ...
    KEYBOARD_QWERTY: typing.ClassVar[int] = ...
    KEYBOARD_UNDEFINED: typing.ClassVar[int] = ...
    MNC_ZERO: typing.ClassVar[int] = ...
    NAVIGATIONHIDDEN_NO: typing.ClassVar[int] = ...
    NAVIGATIONHIDDEN_UNDEFINED: typing.ClassVar[int] = ...
    NAVIGATIONHIDDEN_YES: typing.ClassVar[int] = ...
    NAVIGATION_DPAD: typing.ClassVar[int] = ...
    NAVIGATION_NONAV: typing.ClassVar[int] = ...
    NAVIGATION_TRACKBALL: typing.ClassVar[int] = ...
    NAVIGATION_UNDEFINED: typing.ClassVar[int] = ...
    NAVIGATION_WHEEL: typing.ClassVar[int] = ...
    ORIENTATION_LANDSCAPE: typing.ClassVar[int] = ...
    ORIENTATION_PORTRAIT: typing.ClassVar[int] = ...
    ORIENTATION_SQUARE: typing.ClassVar[int] = ...
    ORIENTATION_UNDEFINED: typing.ClassVar[int] = ...
    SCREENLAYOUT_LAYOUTDIR_LTR: typing.ClassVar[int] = ...
    SCREENLAYOUT_LAYOUTDIR_MASK: typing.ClassVar[int] = ...
    SCREENLAYOUT_LAYOUTDIR_RTL: typing.ClassVar[int] = ...
    SCREENLAYOUT_LAYOUTDIR_SHIFT: typing.ClassVar[int] = ...
    SCREENLAYOUT_LAYOUTDIR_UNDEFINED: typing.ClassVar[int] = ...
    SCREENLAYOUT_LONG_MASK: typing.ClassVar[int] = ...
    SCREENLAYOUT_LONG_NO: typing.ClassVar[int] = ...
    SCREENLAYOUT_LONG_UNDEFINED: typing.ClassVar[int] = ...
    SCREENLAYOUT_LONG_YES: typing.ClassVar[int] = ...
    SCREENLAYOUT_ROUND_MASK: typing.ClassVar[int] = ...
    SCREENLAYOUT_ROUND_NO: typing.ClassVar[int] = ...
    SCREENLAYOUT_ROUND_UNDEFINED: typing.ClassVar[int] = ...
    SCREENLAYOUT_ROUND_YES: typing.ClassVar[int] = ...
    SCREENLAYOUT_SIZE_LARGE: typing.ClassVar[int] = ...
    SCREENLAYOUT_SIZE_MASK: typing.ClassVar[int] = ...
    SCREENLAYOUT_SIZE_NORMAL: typing.ClassVar[int] = ...
    SCREENLAYOUT_SIZE_SMALL: typing.ClassVar[int] = ...
    SCREENLAYOUT_SIZE_UNDEFINED: typing.ClassVar[int] = ...
    SCREENLAYOUT_SIZE_XLARGE: typing.ClassVar[int] = ...
    SCREENLAYOUT_UNDEFINED: typing.ClassVar[int] = ...
    SCREEN_HEIGHT_DP_UNDEFINED: typing.ClassVar[int] = ...
    SCREEN_WIDTH_DP_UNDEFINED: typing.ClassVar[int] = ...
    SMALLEST_SCREEN_WIDTH_DP_UNDEFINED: typing.ClassVar[int] = ...
    TOUCHSCREEN_FINGER: typing.ClassVar[int] = ...
    TOUCHSCREEN_NOTOUCH: typing.ClassVar[int] = ...
    TOUCHSCREEN_STYLUS: typing.ClassVar[int] = ...
    TOUCHSCREEN_UNDEFINED: typing.ClassVar[int] = ...
    UI_MODE_NIGHT_MASK: typing.ClassVar[int] = ...
    UI_MODE_NIGHT_NO: typing.ClassVar[int] = ...
    UI_MODE_NIGHT_UNDEFINED: typing.ClassVar[int] = ...
    UI_MODE_NIGHT_YES: typing.ClassVar[int] = ...
    UI_MODE_TYPE_APPLIANCE: typing.ClassVar[int] = ...
    UI_MODE_TYPE_CAR: typing.ClassVar[int] = ...
    UI_MODE_TYPE_DESK: typing.ClassVar[int] = ...
    UI_MODE_TYPE_MASK: typing.ClassVar[int] = ...
    UI_MODE_TYPE_NORMAL: typing.ClassVar[int] = ...
    UI_MODE_TYPE_TELEVISION: typing.ClassVar[int] = ...
    UI_MODE_TYPE_UNDEFINED: typing.ClassVar[int] = ...
    UI_MODE_TYPE_VR_HEADSET: typing.ClassVar[int] = ...
    UI_MODE_TYPE_WATCH: typing.ClassVar[int] = ...
    colorMode: int = ...
    densityDpi: int = ...
    fontScale: float = ...
    fontWeightAdjustment: int = ...
    hardKeyboardHidden: int = ...
    keyboard: int = ...
    keyboardHidden: int = ...
    locale: java.util.Locale = ...
    mcc: int = ...
    mnc: int = ...
    navigation: int = ...
    navigationHidden: int = ...
    orientation: int = ...
    screenHeightDp: int = ...
    screenLayout: int = ...
    screenWidthDp: int = ...
    smallestScreenWidthDp: int = ...
    touchscreen: int = ...
    uiMode: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, configuration: 'Configuration'): ...
    def compareTo(self, configuration: 'Configuration') -> int: ...
    def describeContents(self) -> int: ...
    def diff(self, configuration: 'Configuration') -> int: ...
    @typing.overload
    def equals(self, configuration: 'Configuration') -> bool: ...
    @typing.overload
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def generateDelta(configuration: 'Configuration', configuration2: 'Configuration') -> 'Configuration': ...
    def getGrammaticalGender(self) -> int: ...
    def getLayoutDirection(self) -> int: ...
    def getLocales(self) -> android.os.LocaleList: ...
    def hashCode(self) -> int: ...
    def isLayoutSizeAtLeast(self, int: int) -> bool: ...
    def isNightModeActive(self) -> bool: ...
    def isScreenHdr(self) -> bool: ...
    def isScreenRound(self) -> bool: ...
    def isScreenWideColorGamut(self) -> bool: ...
    @staticmethod
    def needNewResources(int: int, int2: int) -> bool: ...
    def readFromParcel(self, parcel: android.os.Parcel) -> None: ...
    def setLayoutDirection(self, locale: java.util.Locale) -> None: ...
    def setLocale(self, locale: java.util.Locale) -> None: ...
    def setLocales(self, localeList: android.os.LocaleList) -> None: ...
    def setTo(self, configuration: 'Configuration') -> None: ...
    def setToDefaults(self) -> None: ...
    def toString(self) -> str: ...
    def updateFrom(self, configuration: 'Configuration') -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class FontScaleConverter:
    def convertDpToSp(self, float: float) -> float: ...
    def convertSpToDp(self, float: float) -> float: ...
    @staticmethod
    def forScale(float: float) -> 'FontScaleConverter': ...
    @staticmethod
    def isNonLinearFontScalingActive(float: float) -> bool: ...

class ObbInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    OBB_OVERLAY: typing.ClassVar[int] = ...
    filename: str = ...
    flags: int = ...
    packageName: str = ...
    version: int = ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ObbScanner:
    @staticmethod
    def getObbInfo(string: str) -> ObbInfo: ...

class Resources:
    ID_NULL: typing.ClassVar[int] = ...
    def __init__(self, assetManager: AssetManager, displayMetrics: android.util.DisplayMetrics, configuration: Configuration): ...
    def addLoaders(self, *resourcesLoader: android.content.res.loader.ResourcesLoader) -> None: ...
    def finishPreloading(self) -> None: ...
    def flushLayoutCache(self) -> None: ...
    def getAnimation(self, int: int) -> 'XmlResourceParser': ...
    def getAssets(self) -> AssetManager: ...
    @staticmethod
    def getAttributeSetSourceResId(attributeSet: android.util.AttributeSet) -> int: ...
    def getBoolean(self, int: int) -> bool: ...
    @typing.overload
    def getColor(self, int: int) -> int: ...
    @typing.overload
    def getColor(self, int: int, theme: 'Resources.Theme') -> int: ...
    @typing.overload
    def getColorStateList(self, int: int) -> ColorStateList: ...
    @typing.overload
    def getColorStateList(self, int: int, theme: 'Resources.Theme') -> ColorStateList: ...
    def getConfiguration(self) -> Configuration: ...
    def getDimension(self, int: int) -> float: ...
    def getDimensionPixelOffset(self, int: int) -> int: ...
    def getDimensionPixelSize(self, int: int) -> int: ...
    def getDisplayMetrics(self) -> android.util.DisplayMetrics: ...
    @typing.overload
    def getDrawable(self, int: int) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getDrawable(self, int: int, theme: 'Resources.Theme') -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getDrawableForDensity(self, int: int, int2: int) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getDrawableForDensity(self, int: int, int2: int, theme: 'Resources.Theme') -> android.graphics.drawable.Drawable: ...
    def getFloat(self, int: int) -> float: ...
    def getFont(self, int: int) -> android.graphics.Typeface: ...
    def getFraction(self, int: int, int2: int, int3: int) -> float: ...
    def getIdentifier(self, string: str, string2: str, string3: str) -> int: ...
    def getIntArray(self, int: int) -> typing.MutableSequence[int]: ...
    def getInteger(self, int: int) -> int: ...
    def getLayout(self, int: int) -> 'XmlResourceParser': ...
    def getMovie(self, int: int) -> android.graphics.Movie: ...
    @typing.overload
    def getQuantityString(self, int: int, int2: int) -> str: ...
    @typing.overload
    def getQuantityString(self, int: int, int2: int, *object: typing.Any) -> str: ...
    def getQuantityText(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def getResourceEntryName(self, int: int) -> str: ...
    def getResourceName(self, int: int) -> str: ...
    def getResourcePackageName(self, int: int) -> str: ...
    def getResourceTypeName(self, int: int) -> str: ...
    @typing.overload
    def getString(self, int: int) -> str: ...
    @typing.overload
    def getString(self, int: int, *object: typing.Any) -> str: ...
    def getStringArray(self, int: int) -> typing.MutableSequence[str]: ...
    @staticmethod
    def getSystem() -> 'Resources': ...
    @typing.overload
    def getText(self, int: int) -> java.lang.CharSequence: ...
    @typing.overload
    def getText(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> java.lang.CharSequence: ...
    def getTextArray(self, int: int) -> typing.MutableSequence[java.lang.CharSequence]: ...
    @typing.overload
    def getValue(self, int: int, typedValue: android.util.TypedValue, boolean: bool) -> None: ...
    @typing.overload
    def getValue(self, string: str, typedValue: android.util.TypedValue, boolean: bool) -> None: ...
    def getValueForDensity(self, int: int, int2: int, typedValue: android.util.TypedValue, boolean: bool) -> None: ...
    def getXml(self, int: int) -> 'XmlResourceParser': ...
    def newTheme(self) -> 'Resources.Theme': ...
    def obtainAttributes(self, attributeSet: android.util.AttributeSet, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'TypedArray': ...
    def obtainTypedArray(self, int: int) -> 'TypedArray': ...
    @typing.overload
    def openRawResource(self, int: int) -> java.io.InputStream: ...
    @typing.overload
    def openRawResource(self, int: int, typedValue: android.util.TypedValue) -> java.io.InputStream: ...
    def openRawResourceFd(self, int: int) -> AssetFileDescriptor: ...
    def parseBundleExtra(self, string: str, attributeSet: android.util.AttributeSet, bundle: android.os.Bundle) -> None: ...
    def parseBundleExtras(self, xmlResourceParser: 'XmlResourceParser', bundle: android.os.Bundle) -> None: ...
    @staticmethod
    def registerResourcePaths(string: str, applicationInfo: android.content.pm.ApplicationInfo) -> None: ...
    def removeLoaders(self, *resourcesLoader: android.content.res.loader.ResourcesLoader) -> None: ...
    def updateConfiguration(self, configuration: Configuration, displayMetrics: android.util.DisplayMetrics) -> None: ...
    class NotFoundException(java.lang.RuntimeException):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        @typing.overload
        def __init__(self, string: str, exception: java.lang.Exception): ...
    class Theme:
        def applyStyle(self, int: int, boolean: bool) -> None: ...
        def dump(self, int: int, string: str, string2: str) -> None: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getAttributeResolutionStack(self, int: int, int2: int, int3: int) -> typing.MutableSequence[int]: ...
        def getChangingConfigurations(self) -> int: ...
        def getDrawable(self, int: int) -> android.graphics.drawable.Drawable: ...
        def getExplicitStyle(self, attributeSet: android.util.AttributeSet) -> int: ...
        def getResources(self) -> 'Resources': ...
        def hashCode(self) -> int: ...
        @typing.overload
        def obtainStyledAttributes(self, attributeSet: android.util.AttributeSet, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int, int3: int) -> 'TypedArray': ...
        @typing.overload
        def obtainStyledAttributes(self, int: int, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'TypedArray': ...
        @typing.overload
        def obtainStyledAttributes(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'TypedArray': ...
        def rebase(self) -> None: ...
        def resolveAttribute(self, int: int, typedValue: android.util.TypedValue, boolean: bool) -> bool: ...
        def setTo(self, theme: 'Resources.Theme') -> None: ...
        def toString(self) -> str: ...

class TypedArray(java.lang.AutoCloseable):
    def close(self) -> None: ...
    def getBoolean(self, int: int, boolean: bool) -> bool: ...
    def getChangingConfigurations(self) -> int: ...
    def getColor(self, int: int, int2: int) -> int: ...
    def getColorStateList(self, int: int) -> ColorStateList: ...
    def getDimension(self, int: int, float: float) -> float: ...
    def getDimensionPixelOffset(self, int: int, int2: int) -> int: ...
    def getDimensionPixelSize(self, int: int, int2: int) -> int: ...
    def getDrawable(self, int: int) -> android.graphics.drawable.Drawable: ...
    def getFloat(self, int: int, float: float) -> float: ...
    def getFont(self, int: int) -> android.graphics.Typeface: ...
    def getFraction(self, int: int, int2: int, int3: int, float: float) -> float: ...
    def getIndex(self, int: int) -> int: ...
    def getIndexCount(self) -> int: ...
    def getInt(self, int: int, int2: int) -> int: ...
    def getInteger(self, int: int, int2: int) -> int: ...
    @typing.overload
    def getLayoutDimension(self, int: int, int2: int) -> int: ...
    @typing.overload
    def getLayoutDimension(self, int: int, string: str) -> int: ...
    def getNonResourceString(self, int: int) -> str: ...
    def getPositionDescription(self) -> str: ...
    def getResourceId(self, int: int, int2: int) -> int: ...
    def getResources(self) -> Resources: ...
    def getSourceResourceId(self, int: int, int2: int) -> int: ...
    def getString(self, int: int) -> str: ...
    def getText(self, int: int) -> java.lang.CharSequence: ...
    def getTextArray(self, int: int) -> typing.MutableSequence[java.lang.CharSequence]: ...
    def getType(self, int: int) -> int: ...
    def getValue(self, int: int, typedValue: android.util.TypedValue) -> bool: ...
    def hasValue(self, int: int) -> bool: ...
    def hasValueOrEmpty(self, int: int) -> bool: ...
    def length(self) -> int: ...
    def peekValue(self, int: int) -> android.util.TypedValue: ...
    def recycle(self) -> None: ...
    def toString(self) -> str: ...

class XmlResourceParser(org.xmlpull.v1.XmlPullParser, android.util.AttributeSet, java.lang.AutoCloseable):
    def close(self) -> None: ...
    def getAttributeNamespace(self, int: int) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.content.res")``.

    AssetFileDescriptor: typing.Type[AssetFileDescriptor]
    AssetManager: typing.Type[AssetManager]
    ColorStateList: typing.Type[ColorStateList]
    Configuration: typing.Type[Configuration]
    FontScaleConverter: typing.Type[FontScaleConverter]
    ObbInfo: typing.Type[ObbInfo]
    ObbScanner: typing.Type[ObbScanner]
    Resources: typing.Type[Resources]
    TypedArray: typing.Type[TypedArray]
    XmlResourceParser: typing.Type[XmlResourceParser]
    loader: android.content.res.loader.__module_protocol__
