
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import decimal
import java.io
import java.lang
import java.math
import jpype
import typing



class BigDecimal(java.lang.Number, java.io.Serializable, java.lang.Comparable['BigDecimal']):
    ONE: typing.ClassVar['BigDecimal'] = ...
    ROUND_CEILING: typing.ClassVar[int] = ...
    ROUND_DOWN: typing.ClassVar[int] = ...
    ROUND_FLOOR: typing.ClassVar[int] = ...
    ROUND_HALF_DOWN: typing.ClassVar[int] = ...
    ROUND_HALF_EVEN: typing.ClassVar[int] = ...
    ROUND_HALF_UP: typing.ClassVar[int] = ...
    ROUND_UNNECESSARY: typing.ClassVar[int] = ...
    ROUND_UP: typing.ClassVar[int] = ...
    TEN: typing.ClassVar['BigDecimal'] = ...
    ZERO: typing.ClassVar['BigDecimal'] = ...
    @typing.overload
    def __init__(self, charArray: typing.Union[typing.List[str], jpype.JArray]): ...
    @typing.overload
    def __init__(self, charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int): ...
    @typing.overload
    def __init__(self, double: float): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, bigDecimal: typing.Union[java.math.BigDecimal, decimal.Decimal]): ...
    @typing.overload
    def __init__(self, bigInteger: java.math.BigInteger): ...
    @typing.overload
    def __init__(self, bigInteger: java.math.BigInteger, int: int): ...
    @typing.overload
    def __init__(self, long: int): ...
    @typing.overload
    def abs(self) -> 'BigDecimal': ...
    @typing.overload
    def abs(self, mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def add(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def add(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    def byteValueExact(self) -> int: ...
    @typing.overload
    def compareTo(self, bigDecimal: 'BigDecimal') -> int: ...
    @typing.overload
    def compareTo(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> int: ...
    @typing.overload
    def divide(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def divide(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def divide(self, bigDecimal: 'BigDecimal', int: int) -> 'BigDecimal': ...
    @typing.overload
    def divide(self, bigDecimal: 'BigDecimal', int: int, int2: int) -> 'BigDecimal': ...
    @typing.overload
    def divideInteger(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def divideInteger(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    def doubleValue(self) -> float: ...
    def equals(self, object: typing.Any) -> bool: ...
    def floatValue(self) -> float: ...
    @typing.overload
    def format(self, int: int, int2: int) -> str: ...
    @typing.overload
    def format(self, int: int, int2: int, int3: int, int4: int, int5: int, int6: int) -> str: ...
    def hashCode(self) -> int: ...
    def intValue(self) -> int: ...
    def intValueExact(self) -> int: ...
    def longValue(self) -> int: ...
    def longValueExact(self) -> int: ...
    @typing.overload
    def max(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def max(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def min(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def min(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    def movePointLeft(self, int: int) -> 'BigDecimal': ...
    def movePointRight(self, int: int) -> 'BigDecimal': ...
    @typing.overload
    def multiply(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def multiply(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def negate(self) -> 'BigDecimal': ...
    @typing.overload
    def negate(self, mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def plus(self) -> 'BigDecimal': ...
    @typing.overload
    def plus(self, mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def pow(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def pow(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    @typing.overload
    def remainder(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def remainder(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    def scale(self) -> int: ...
    @typing.overload
    def setScale(self, int: int) -> 'BigDecimal': ...
    @typing.overload
    def setScale(self, int: int, int2: int) -> 'BigDecimal': ...
    def shortValueExact(self) -> int: ...
    def signum(self) -> int: ...
    @typing.overload
    def subtract(self, bigDecimal: 'BigDecimal') -> 'BigDecimal': ...
    @typing.overload
    def subtract(self, bigDecimal: 'BigDecimal', mathContext: 'MathContext') -> 'BigDecimal': ...
    def toBigDecimal(self) -> java.math.BigDecimal: ...
    def toBigInteger(self) -> java.math.BigInteger: ...
    def toBigIntegerExact(self) -> java.math.BigInteger: ...
    def toCharArray(self) -> typing.MutableSequence[str]: ...
    def toString(self) -> str: ...
    def unscaledValue(self) -> java.math.BigInteger: ...
    @typing.overload
    @staticmethod
    def valueOf(double: float) -> 'BigDecimal': ...
    @typing.overload
    @staticmethod
    def valueOf(long: int) -> 'BigDecimal': ...
    @typing.overload
    @staticmethod
    def valueOf(long: int, int: int) -> 'BigDecimal': ...

class MathContext(java.io.Serializable):
    DEFAULT: typing.ClassVar['MathContext'] = ...
    ENGINEERING: typing.ClassVar[int] = ...
    PLAIN: typing.ClassVar[int] = ...
    ROUND_CEILING: typing.ClassVar[int] = ...
    ROUND_DOWN: typing.ClassVar[int] = ...
    ROUND_FLOOR: typing.ClassVar[int] = ...
    ROUND_HALF_DOWN: typing.ClassVar[int] = ...
    ROUND_HALF_EVEN: typing.ClassVar[int] = ...
    ROUND_HALF_UP: typing.ClassVar[int] = ...
    ROUND_UNNECESSARY: typing.ClassVar[int] = ...
    ROUND_UP: typing.ClassVar[int] = ...
    SCIENTIFIC: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, boolean: bool): ...
    @typing.overload
    def __init__(self, int: int, int2: int, boolean: bool, int3: int): ...
    def getDigits(self) -> int: ...
    def getForm(self) -> int: ...
    def getLostDigits(self) -> bool: ...
    def getRoundingMode(self) -> int: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.icu.math")``.

    BigDecimal: typing.Type[BigDecimal]
    MathContext: typing.Type[MathContext]
