
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.graphics
import android.os
import android.util
import android.view
import android.widget
import java.io
import java.util
import jpype
import jpype.protocol
import typing



class Gesture(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self): ...
    def addStroke(self, gestureStroke: 'GestureStroke') -> None: ...
    def clone(self) -> typing.Any: ...
    def describeContents(self) -> int: ...
    def getBoundingBox(self) -> android.graphics.RectF: ...
    def getID(self) -> int: ...
    def getLength(self) -> float: ...
    def getStrokes(self) -> java.util.ArrayList['GestureStroke']: ...
    def getStrokesCount(self) -> int: ...
    @typing.overload
    def toBitmap(self, int: int, int2: int, int3: int, int4: int) -> android.graphics.Bitmap: ...
    @typing.overload
    def toBitmap(self, int: int, int2: int, int3: int, int4: int, int5: int) -> android.graphics.Bitmap: ...
    @typing.overload
    def toPath(self) -> android.graphics.Path: ...
    @typing.overload
    def toPath(self, path: android.graphics.Path) -> android.graphics.Path: ...
    @typing.overload
    def toPath(self, path: android.graphics.Path, int: int, int2: int, int3: int, int4: int) -> android.graphics.Path: ...
    @typing.overload
    def toPath(self, int: int, int2: int, int3: int, int4: int) -> android.graphics.Path: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GestureLibraries:
    @typing.overload
    @staticmethod
    def fromFile(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> 'GestureLibrary': ...
    @typing.overload
    @staticmethod
    def fromFile(string: str) -> 'GestureLibrary': ...
    @staticmethod
    def fromFileDescriptor(parcelFileDescriptor: android.os.ParcelFileDescriptor) -> 'GestureLibrary': ...
    @staticmethod
    def fromPrivateFile(context: android.content.Context, string: str) -> 'GestureLibrary': ...
    @staticmethod
    def fromRawResource(context: android.content.Context, int: int) -> 'GestureLibrary': ...

class GestureLibrary:
    def addGesture(self, string: str, gesture: Gesture) -> None: ...
    def getGestureEntries(self) -> java.util.Set[str]: ...
    def getGestures(self, string: str) -> java.util.ArrayList[Gesture]: ...
    def getOrientationStyle(self) -> int: ...
    def getSequenceType(self) -> int: ...
    def isReadOnly(self) -> bool: ...
    def load(self) -> bool: ...
    def recognize(self, gesture: Gesture) -> java.util.ArrayList['Prediction']: ...
    def removeEntry(self, string: str) -> None: ...
    def removeGesture(self, string: str, gesture: Gesture) -> None: ...
    def save(self) -> bool: ...
    def setOrientationStyle(self, int: int) -> None: ...
    def setSequenceType(self, int: int) -> None: ...

class GestureOverlayView(android.widget.FrameLayout):
    GESTURE_STROKE_TYPE_MULTIPLE: typing.ClassVar[int] = ...
    GESTURE_STROKE_TYPE_SINGLE: typing.ClassVar[int] = ...
    ORIENTATION_HORIZONTAL: typing.ClassVar[int] = ...
    ORIENTATION_VERTICAL: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def addOnGestureListener(self, onGestureListener: 'GestureOverlayView.OnGestureListener') -> None: ...
    def addOnGesturePerformedListener(self, onGesturePerformedListener: typing.Union['GestureOverlayView.OnGesturePerformedListener', typing.Callable]) -> None: ...
    def addOnGesturingListener(self, onGesturingListener: 'GestureOverlayView.OnGesturingListener') -> None: ...
    def cancelClearAnimation(self) -> None: ...
    def cancelGesture(self) -> None: ...
    def clear(self, boolean: bool) -> None: ...
    def dispatchTouchEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def draw(self, canvas: android.graphics.Canvas) -> None: ...
    def getCurrentStroke(self) -> java.util.ArrayList['GesturePoint']: ...
    def getFadeOffset(self) -> int: ...
    def getGesture(self) -> Gesture: ...
    def getGestureColor(self) -> int: ...
    @typing.overload
    def getGesturePath(self) -> android.graphics.Path: ...
    @typing.overload
    def getGesturePath(self, path: android.graphics.Path) -> android.graphics.Path: ...
    def getGestureStrokeAngleThreshold(self) -> float: ...
    def getGestureStrokeLengthThreshold(self) -> float: ...
    def getGestureStrokeSquarenessTreshold(self) -> float: ...
    def getGestureStrokeType(self) -> int: ...
    def getGestureStrokeWidth(self) -> float: ...
    def getOrientation(self) -> int: ...
    def getUncertainGestureColor(self) -> int: ...
    def isEventsInterceptionEnabled(self) -> bool: ...
    def isFadeEnabled(self) -> bool: ...
    def isGestureVisible(self) -> bool: ...
    def isGesturing(self) -> bool: ...
    def removeAllOnGestureListeners(self) -> None: ...
    def removeAllOnGesturePerformedListeners(self) -> None: ...
    def removeAllOnGesturingListeners(self) -> None: ...
    def removeOnGestureListener(self, onGestureListener: 'GestureOverlayView.OnGestureListener') -> None: ...
    def removeOnGesturePerformedListener(self, onGesturePerformedListener: typing.Union['GestureOverlayView.OnGesturePerformedListener', typing.Callable]) -> None: ...
    def removeOnGesturingListener(self, onGesturingListener: 'GestureOverlayView.OnGesturingListener') -> None: ...
    def setEventsInterceptionEnabled(self, boolean: bool) -> None: ...
    def setFadeEnabled(self, boolean: bool) -> None: ...
    def setFadeOffset(self, long: int) -> None: ...
    def setGesture(self, gesture: Gesture) -> None: ...
    def setGestureColor(self, int: int) -> None: ...
    def setGestureStrokeAngleThreshold(self, float: float) -> None: ...
    def setGestureStrokeLengthThreshold(self, float: float) -> None: ...
    def setGestureStrokeSquarenessTreshold(self, float: float) -> None: ...
    def setGestureStrokeType(self, int: int) -> None: ...
    def setGestureStrokeWidth(self, float: float) -> None: ...
    def setGestureVisible(self, boolean: bool) -> None: ...
    def setOrientation(self, int: int) -> None: ...
    def setUncertainGestureColor(self, int: int) -> None: ...
    class OnGestureListener:
        def onGesture(self, gestureOverlayView: 'GestureOverlayView', motionEvent: android.view.MotionEvent) -> None: ...
        def onGestureCancelled(self, gestureOverlayView: 'GestureOverlayView', motionEvent: android.view.MotionEvent) -> None: ...
        def onGestureEnded(self, gestureOverlayView: 'GestureOverlayView', motionEvent: android.view.MotionEvent) -> None: ...
        def onGestureStarted(self, gestureOverlayView: 'GestureOverlayView', motionEvent: android.view.MotionEvent) -> None: ...
    class OnGesturePerformedListener:
        def onGesturePerformed(self, gestureOverlayView: 'GestureOverlayView', gesture2: Gesture) -> None: ...
    class OnGesturingListener:
        def onGesturingEnded(self, gestureOverlayView: 'GestureOverlayView') -> None: ...
        def onGesturingStarted(self, gestureOverlayView: 'GestureOverlayView') -> None: ...

class GesturePoint:
    timestamp: int = ...
    x: float = ...
    y: float = ...
    def __init__(self, float: float, float2: float, long: int): ...
    def clone(self) -> typing.Any: ...

class GestureStore:
    ORIENTATION_INVARIANT: typing.ClassVar[int] = ...
    ORIENTATION_SENSITIVE: typing.ClassVar[int] = ...
    SEQUENCE_INVARIANT: typing.ClassVar[int] = ...
    SEQUENCE_SENSITIVE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addGesture(self, string: str, gesture: Gesture) -> None: ...
    def getGestureEntries(self) -> java.util.Set[str]: ...
    def getGestures(self, string: str) -> java.util.ArrayList[Gesture]: ...
    def getOrientationStyle(self) -> int: ...
    def getSequenceType(self) -> int: ...
    def hasChanged(self) -> bool: ...
    @typing.overload
    def load(self, inputStream: java.io.InputStream) -> None: ...
    @typing.overload
    def load(self, inputStream: java.io.InputStream, boolean: bool) -> None: ...
    def recognize(self, gesture: Gesture) -> java.util.ArrayList['Prediction']: ...
    def removeEntry(self, string: str) -> None: ...
    def removeGesture(self, string: str, gesture: Gesture) -> None: ...
    @typing.overload
    def save(self, outputStream: java.io.OutputStream) -> None: ...
    @typing.overload
    def save(self, outputStream: java.io.OutputStream, boolean: bool) -> None: ...
    def setOrientationStyle(self, int: int) -> None: ...
    def setSequenceType(self, int: int) -> None: ...

class GestureStroke:
    boundingBox: android.graphics.RectF = ...
    length: float = ...
    points: typing.MutableSequence[float] = ...
    def __init__(self, arrayList: java.util.ArrayList[GesturePoint]): ...
    def clearPath(self) -> None: ...
    def clone(self) -> typing.Any: ...
    def computeOrientedBoundingBox(self) -> 'OrientedBoundingBox': ...
    def getPath(self) -> android.graphics.Path: ...
    def toPath(self, float: float, float2: float, int: int) -> android.graphics.Path: ...

class GestureUtils:
    @typing.overload
    @staticmethod
    def computeOrientedBoundingBox(floatArray: typing.Union[typing.List[float], jpype.JArray]) -> 'OrientedBoundingBox': ...
    @typing.overload
    @staticmethod
    def computeOrientedBoundingBox(arrayList: java.util.ArrayList[GesturePoint]) -> 'OrientedBoundingBox': ...
    @typing.overload
    @staticmethod
    def spatialSampling(gesture: Gesture, int: int) -> typing.MutableSequence[float]: ...
    @typing.overload
    @staticmethod
    def spatialSampling(gesture: Gesture, int: int, boolean: bool) -> typing.MutableSequence[float]: ...
    @staticmethod
    def temporalSampling(gestureStroke: GestureStroke, int: int) -> typing.MutableSequence[float]: ...

class OrientedBoundingBox:
    centerX: float = ...
    centerY: float = ...
    height: float = ...
    orientation: float = ...
    squareness: float = ...
    width: float = ...

class Prediction:
    name: str = ...
    score: float = ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.gesture")``.

    Gesture: typing.Type[Gesture]
    GestureLibraries: typing.Type[GestureLibraries]
    GestureLibrary: typing.Type[GestureLibrary]
    GestureOverlayView: typing.Type[GestureOverlayView]
    GesturePoint: typing.Type[GesturePoint]
    GestureStore: typing.Type[GestureStore]
    GestureStroke: typing.Type[GestureStroke]
    GestureUtils: typing.Type[GestureUtils]
    OrientedBoundingBox: typing.Type[OrientedBoundingBox]
    Prediction: typing.Type[Prediction]
