
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.bluetooth
import android.content
import android.graphics.drawable
import android.location
import android.net
import android.os
import android.view
import java.lang
import java.util
import java.util.concurrent
import java.util.function
import typing



class Call:
    AVAILABLE_PHONE_ACCOUNTS: typing.ClassVar[str] = ...
    EVENT_CLEAR_DIAGNOSTIC_MESSAGE: typing.ClassVar[str] = ...
    EVENT_DISPLAY_DIAGNOSTIC_MESSAGE: typing.ClassVar[str] = ...
    EXTRA_ASSERTED_DISPLAY_NAME: typing.ClassVar[str] = ...
    EXTRA_DIAGNOSTIC_MESSAGE: typing.ClassVar[str] = ...
    EXTRA_DIAGNOSTIC_MESSAGE_ID: typing.ClassVar[str] = ...
    EXTRA_IS_BUSINESS_CALL: typing.ClassVar[str] = ...
    EXTRA_IS_SUPPRESSED_BY_DO_NOT_DISTURB: typing.ClassVar[str] = ...
    EXTRA_LAST_EMERGENCY_CALLBACK_TIME_MILLIS: typing.ClassVar[str] = ...
    EXTRA_SILENT_RINGING_REQUESTED: typing.ClassVar[str] = ...
    EXTRA_SUGGESTED_PHONE_ACCOUNTS: typing.ClassVar[str] = ...
    REJECT_REASON_DECLINED: typing.ClassVar[int] = ...
    REJECT_REASON_UNWANTED: typing.ClassVar[int] = ...
    STATE_ACTIVE: typing.ClassVar[int] = ...
    STATE_AUDIO_PROCESSING: typing.ClassVar[int] = ...
    STATE_CONNECTING: typing.ClassVar[int] = ...
    STATE_DIALING: typing.ClassVar[int] = ...
    STATE_DISCONNECTED: typing.ClassVar[int] = ...
    STATE_DISCONNECTING: typing.ClassVar[int] = ...
    STATE_HOLDING: typing.ClassVar[int] = ...
    STATE_NEW: typing.ClassVar[int] = ...
    STATE_PULLING_CALL: typing.ClassVar[int] = ...
    STATE_RINGING: typing.ClassVar[int] = ...
    STATE_SELECT_PHONE_ACCOUNT: typing.ClassVar[int] = ...
    STATE_SIMULATED_RINGING: typing.ClassVar[int] = ...
    def addConferenceParticipants(self, list: java.util.List[android.net.Uri]) -> None: ...
    def answer(self, int: int) -> None: ...
    def conference(self, call: 'Call') -> None: ...
    def deflect(self, uri: android.net.Uri) -> None: ...
    def disconnect(self) -> None: ...
    def getCannedTextResponses(self) -> java.util.List[str]: ...
    def getChildren(self) -> java.util.List['Call']: ...
    def getConferenceableCalls(self) -> java.util.List['Call']: ...
    def getDetails(self) -> 'Call.Details': ...
    def getGenericConferenceActiveChildCall(self) -> 'Call': ...
    def getParent(self) -> 'Call': ...
    def getRemainingPostDialSequence(self) -> str: ...
    def getRttCall(self) -> 'Call.RttCall': ...
    def getState(self) -> int: ...
    def getVideoCall(self) -> 'InCallService.VideoCall': ...
    def handoverTo(self, phoneAccountHandle: 'PhoneAccountHandle', int: int, bundle: android.os.Bundle) -> None: ...
    def hold(self) -> None: ...
    def isRttActive(self) -> bool: ...
    def mergeConference(self) -> None: ...
    def phoneAccountSelected(self, phoneAccountHandle: 'PhoneAccountHandle', boolean: bool) -> None: ...
    def playDtmfTone(self, char: str) -> None: ...
    def postDialContinue(self, boolean: bool) -> None: ...
    def pullExternalCall(self) -> None: ...
    def putExtras(self, bundle: android.os.Bundle) -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'Call.Callback') -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'Call.Callback', handler: android.os.Handler) -> None: ...
    @typing.overload
    def reject(self, boolean: bool, string: str) -> None: ...
    @typing.overload
    def reject(self, int: int) -> None: ...
    @typing.overload
    def removeExtras(self, *string: str) -> None: ...
    @typing.overload
    def removeExtras(self, list: java.util.List[str]) -> None: ...
    def respondToRttRequest(self, int: int, boolean: bool) -> None: ...
    def sendCallEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def sendRttRequest(self) -> None: ...
    def splitFromConference(self) -> None: ...
    def stopDtmfTone(self) -> None: ...
    def stopRtt(self) -> None: ...
    def swapConference(self) -> None: ...
    def toString(self) -> str: ...
    def unhold(self) -> None: ...
    def unregisterCallback(self, callback: 'Call.Callback') -> None: ...
    class Callback:
        HANDOVER_FAILURE_DEST_APP_REJECTED: typing.ClassVar[int] = ...
        HANDOVER_FAILURE_NOT_SUPPORTED: typing.ClassVar[int] = ...
        HANDOVER_FAILURE_ONGOING_EMERGENCY_CALL: typing.ClassVar[int] = ...
        HANDOVER_FAILURE_UNKNOWN: typing.ClassVar[int] = ...
        HANDOVER_FAILURE_USER_REJECTED: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onCallDestroyed(self, call: 'Call') -> None: ...
        def onCannedTextResponsesLoaded(self, call: 'Call', list: java.util.List[str]) -> None: ...
        def onChildrenChanged(self, call: 'Call', list: java.util.List['Call']) -> None: ...
        def onConferenceableCallsChanged(self, call: 'Call', list: java.util.List['Call']) -> None: ...
        def onConnectionEvent(self, call: 'Call', string: str, bundle: android.os.Bundle) -> None: ...
        def onDetailsChanged(self, call: 'Call', details: 'Call.Details') -> None: ...
        def onHandoverComplete(self, call: 'Call') -> None: ...
        def onHandoverFailed(self, call: 'Call', int: int) -> None: ...
        def onParentChanged(self, call: 'Call', call2: 'Call') -> None: ...
        def onPostDialWait(self, call: 'Call', string: str) -> None: ...
        def onRttInitiationFailure(self, call: 'Call', int: int) -> None: ...
        def onRttModeChanged(self, call: 'Call', int: int) -> None: ...
        def onRttRequest(self, call: 'Call', int: int) -> None: ...
        def onRttStatusChanged(self, call: 'Call', boolean: bool, rttCall: 'Call.RttCall') -> None: ...
        def onStateChanged(self, call: 'Call', int: int) -> None: ...
        def onVideoCallChanged(self, call: 'Call', videoCall: 'InCallService.VideoCall') -> None: ...
    class Details:
        CAPABILITY_ADD_PARTICIPANT: typing.ClassVar[int] = ...
        CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO: typing.ClassVar[int] = ...
        CAPABILITY_CAN_PAUSE_VIDEO: typing.ClassVar[int] = ...
        CAPABILITY_CAN_PULL_CALL: typing.ClassVar[int] = ...
        CAPABILITY_DISCONNECT_FROM_CONFERENCE: typing.ClassVar[int] = ...
        CAPABILITY_HOLD: typing.ClassVar[int] = ...
        CAPABILITY_MANAGE_CONFERENCE: typing.ClassVar[int] = ...
        CAPABILITY_MERGE_CONFERENCE: typing.ClassVar[int] = ...
        CAPABILITY_MUTE: typing.ClassVar[int] = ...
        CAPABILITY_REMOTE_PARTY_SUPPORTS_RTT: typing.ClassVar[int] = ...
        CAPABILITY_RESPOND_VIA_TEXT: typing.ClassVar[int] = ...
        CAPABILITY_SEPARATE_FROM_CONFERENCE: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORTS_VT_LOCAL_RX: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORTS_VT_LOCAL_TX: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORTS_VT_REMOTE_BIDIRECTIONAL: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORTS_VT_REMOTE_RX: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORTS_VT_REMOTE_TX: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORT_DEFLECT: typing.ClassVar[int] = ...
        CAPABILITY_SUPPORT_HOLD: typing.ClassVar[int] = ...
        CAPABILITY_SWAP_CONFERENCE: typing.ClassVar[int] = ...
        DIRECTION_INCOMING: typing.ClassVar[int] = ...
        DIRECTION_OUTGOING: typing.ClassVar[int] = ...
        DIRECTION_UNKNOWN: typing.ClassVar[int] = ...
        PROPERTY_ASSISTED_DIALING: typing.ClassVar[int] = ...
        PROPERTY_CONFERENCE: typing.ClassVar[int] = ...
        PROPERTY_CROSS_SIM: typing.ClassVar[int] = ...
        PROPERTY_EMERGENCY_CALLBACK_MODE: typing.ClassVar[int] = ...
        PROPERTY_ENTERPRISE_CALL: typing.ClassVar[int] = ...
        PROPERTY_GENERIC_CONFERENCE: typing.ClassVar[int] = ...
        PROPERTY_HAS_CDMA_VOICE_PRIVACY: typing.ClassVar[int] = ...
        PROPERTY_HIGH_DEF_AUDIO: typing.ClassVar[int] = ...
        PROPERTY_IS_ADHOC_CONFERENCE: typing.ClassVar[int] = ...
        PROPERTY_IS_EXTERNAL_CALL: typing.ClassVar[int] = ...
        PROPERTY_IS_TRANSACTIONAL: typing.ClassVar[int] = ...
        PROPERTY_NETWORK_IDENTIFIED_EMERGENCY_CALL: typing.ClassVar[int] = ...
        PROPERTY_RTT: typing.ClassVar[int] = ...
        PROPERTY_SELF_MANAGED: typing.ClassVar[int] = ...
        PROPERTY_VOIP_AUDIO_MODE: typing.ClassVar[int] = ...
        PROPERTY_WIFI: typing.ClassVar[int] = ...
        @typing.overload
        def can(self, int: int) -> bool: ...
        @typing.overload
        @staticmethod
        def can(int: int, int2: int) -> bool: ...
        @staticmethod
        def capabilitiesToString(int: int) -> str: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getAccountHandle(self) -> 'PhoneAccountHandle': ...
        def getCallCapabilities(self) -> int: ...
        def getCallDirection(self) -> int: ...
        def getCallProperties(self) -> int: ...
        def getCallerDisplayName(self) -> str: ...
        def getCallerDisplayNamePresentation(self) -> int: ...
        def getCallerNumberVerificationStatus(self) -> int: ...
        def getConnectTimeMillis(self) -> int: ...
        def getContactDisplayName(self) -> str: ...
        def getContactPhotoUri(self) -> android.net.Uri: ...
        def getCreationTimeMillis(self) -> int: ...
        def getDisconnectCause(self) -> 'DisconnectCause': ...
        def getExtras(self) -> android.os.Bundle: ...
        def getGatewayInfo(self) -> 'GatewayInfo': ...
        def getHandle(self) -> android.net.Uri: ...
        def getHandlePresentation(self) -> int: ...
        def getId(self) -> str: ...
        def getIntentExtras(self) -> android.os.Bundle: ...
        def getState(self) -> int: ...
        def getStatusHints(self) -> 'StatusHints': ...
        def getVideoState(self) -> int: ...
        @typing.overload
        def hasProperty(self, int: int) -> bool: ...
        @typing.overload
        @staticmethod
        def hasProperty(int: int, int2: int) -> bool: ...
        def hashCode(self) -> int: ...
        @staticmethod
        def propertiesToString(int: int) -> str: ...
        def toString(self) -> str: ...
    class RttCall:
        RTT_MODE_FULL: typing.ClassVar[int] = ...
        RTT_MODE_HCO: typing.ClassVar[int] = ...
        RTT_MODE_VCO: typing.ClassVar[int] = ...
        def getRttAudioMode(self) -> int: ...
        def read(self) -> str: ...
        def readImmediately(self) -> str: ...
        def setRttMode(self, int: int) -> None: ...
        def write(self, string: str) -> None: ...

class CallAttributes(android.os.Parcelable):
    AUDIO_CALL: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DIRECTION_INCOMING: typing.ClassVar[int] = ...
    DIRECTION_OUTGOING: typing.ClassVar[int] = ...
    SUPPORTS_SET_INACTIVE: typing.ClassVar[int] = ...
    SUPPORTS_STREAM: typing.ClassVar[int] = ...
    SUPPORTS_TRANSFER: typing.ClassVar[int] = ...
    SUPPORTS_VIDEO_CALLING: typing.ClassVar[int] = ...
    VIDEO_CALL: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAddress(self) -> android.net.Uri: ...
    def getCallCapabilities(self) -> int: ...
    def getCallType(self) -> int: ...
    def getDirection(self) -> int: ...
    def getDisplayName(self) -> java.lang.CharSequence: ...
    def getPhoneAccountHandle(self) -> 'PhoneAccountHandle': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, phoneAccountHandle: 'PhoneAccountHandle', int: int, charSequence: typing.Union[java.lang.CharSequence, str], uri: android.net.Uri): ...
        def build(self) -> 'CallAttributes': ...
        def setCallCapabilities(self, int: int) -> 'CallAttributes.Builder': ...
        def setCallType(self, int: int) -> 'CallAttributes.Builder': ...

class CallAudioState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    ROUTE_BLUETOOTH: typing.ClassVar[int] = ...
    ROUTE_EARPIECE: typing.ClassVar[int] = ...
    ROUTE_SPEAKER: typing.ClassVar[int] = ...
    ROUTE_STREAMING: typing.ClassVar[int] = ...
    ROUTE_WIRED_HEADSET: typing.ClassVar[int] = ...
    ROUTE_WIRED_OR_EARPIECE: typing.ClassVar[int] = ...
    def __init__(self, boolean: bool, int: int, int2: int): ...
    @staticmethod
    def audioRouteToString(int: int) -> str: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getActiveBluetoothDevice(self) -> android.bluetooth.BluetoothDevice: ...
    def getRoute(self) -> int: ...
    def getSupportedBluetoothDevices(self) -> java.util.Collection[android.bluetooth.BluetoothDevice]: ...
    def getSupportedRouteMask(self) -> int: ...
    def isMuted(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CallControl:
    def answer(self, int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def disconnect(self, disconnectCause: 'DisconnectCause', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def getCallId(self) -> android.os.ParcelUuid: ...
    def requestCallEndpointChange(self, callEndpoint: 'CallEndpoint', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def requestMuteState(self, boolean: bool, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def requestVideoState(self, int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def sendEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def setActive(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def setInactive(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...
    def startCallStreaming(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, 'CallException'], typing.Callable[[None], None]]) -> None: ...

class CallControlCallback:
    def onAnswer(self, int: int, consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def onCallStreamingStarted(self, consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def onDisconnect(self, disconnectCause: 'DisconnectCause', consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def onSetActive(self, consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def onSetInactive(self, consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...

class CallEndpoint(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_BLUETOOTH: typing.ClassVar[int] = ...
    TYPE_EARPIECE: typing.ClassVar[int] = ...
    TYPE_SPEAKER: typing.ClassVar[int] = ...
    TYPE_STREAMING: typing.ClassVar[int] = ...
    TYPE_UNKNOWN: typing.ClassVar[int] = ...
    TYPE_WIRED_HEADSET: typing.ClassVar[int] = ...
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, parcelUuid: android.os.ParcelUuid): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getEndpointName(self) -> java.lang.CharSequence: ...
    def getEndpointType(self) -> int: ...
    def getIdentifier(self) -> android.os.ParcelUuid: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CallEndpointException(java.lang.RuntimeException, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    ERROR_ANOTHER_REQUEST: typing.ClassVar[int] = ...
    ERROR_ENDPOINT_DOES_NOT_EXIST: typing.ClassVar[int] = ...
    ERROR_REQUEST_TIME_OUT: typing.ClassVar[int] = ...
    ERROR_UNSPECIFIED: typing.ClassVar[int] = ...
    def __init__(self, string: str, int: int): ...
    def describeContents(self) -> int: ...
    def getCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CallEventCallback:
    def onAvailableCallEndpointsChanged(self, list: java.util.List[CallEndpoint]) -> None: ...
    def onCallEndpointChanged(self, callEndpoint: CallEndpoint) -> None: ...
    def onCallStreamingFailed(self, int: int) -> None: ...
    def onEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def onMuteStateChanged(self, boolean: bool) -> None: ...
    def onVideoStateChanged(self, int: int) -> None: ...

class CallException(java.lang.RuntimeException, android.os.Parcelable):
    CODE_CALL_CANNOT_BE_SET_TO_ACTIVE: typing.ClassVar[int] = ...
    CODE_CALL_IS_NOT_BEING_TRACKED: typing.ClassVar[int] = ...
    CODE_CALL_NOT_PERMITTED_AT_PRESENT_TIME: typing.ClassVar[int] = ...
    CODE_CANNOT_HOLD_CURRENT_ACTIVE_CALL: typing.ClassVar[int] = ...
    CODE_ERROR_UNKNOWN: typing.ClassVar[int] = ...
    CODE_OPERATION_TIMED_OUT: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, int: int): ...
    def describeContents(self) -> int: ...
    def getCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CallRedirectionService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def cancelCall(self) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onPlaceCall(self, uri: android.net.Uri, phoneAccountHandle: 'PhoneAccountHandle', boolean: bool) -> None: ...
    def onRedirectionTimeout(self) -> None: ...
    def onUnbind(self, intent: android.content.Intent) -> bool: ...
    def placeCallUnmodified(self) -> None: ...
    def redirectCall(self, uri: android.net.Uri, phoneAccountHandle: 'PhoneAccountHandle', boolean: bool) -> None: ...

class CallScreeningService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onScreenCall(self, details: Call.Details) -> None: ...
    def onUnbind(self, intent: android.content.Intent) -> bool: ...
    def respondToCall(self, details: Call.Details, callResponse: 'CallScreeningService.CallResponse') -> None: ...
    class CallResponse:
        CALL_COMPOSER_ATTACHMENT_LOCATION: typing.ClassVar[int] = ...
        CALL_COMPOSER_ATTACHMENT_PICTURE: typing.ClassVar[int] = ...
        CALL_COMPOSER_ATTACHMENT_PRIORITY: typing.ClassVar[int] = ...
        CALL_COMPOSER_ATTACHMENT_SUBJECT: typing.ClassVar[int] = ...
        def equals(self, object: typing.Any) -> bool: ...
        def getCallComposerAttachmentsToShow(self) -> int: ...
        def getDisallowCall(self) -> bool: ...
        def getRejectCall(self) -> bool: ...
        def getSilenceCall(self) -> bool: ...
        def getSkipCallLog(self) -> bool: ...
        def getSkipNotification(self) -> bool: ...
        def hashCode(self) -> int: ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'CallScreeningService.CallResponse': ...
            def setCallComposerAttachmentsToShow(self, int: int) -> 'CallScreeningService.CallResponse.Builder': ...
            def setDisallowCall(self, boolean: bool) -> 'CallScreeningService.CallResponse.Builder': ...
            def setRejectCall(self, boolean: bool) -> 'CallScreeningService.CallResponse.Builder': ...
            def setSilenceCall(self, boolean: bool) -> 'CallScreeningService.CallResponse.Builder': ...
            def setSkipCallLog(self, boolean: bool) -> 'CallScreeningService.CallResponse.Builder': ...
            def setSkipNotification(self, boolean: bool) -> 'CallScreeningService.CallResponse.Builder': ...

class Conferenceable: ...

class ConnectionRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, phoneAccountHandle: 'PhoneAccountHandle', uri: android.net.Uri, bundle: android.os.Bundle): ...
    @typing.overload
    def __init__(self, phoneAccountHandle: 'PhoneAccountHandle', uri: android.net.Uri, bundle: android.os.Bundle, int: int): ...
    def describeContents(self) -> int: ...
    def getAccountHandle(self) -> 'PhoneAccountHandle': ...
    def getAddress(self) -> android.net.Uri: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getParticipants(self) -> java.util.List[android.net.Uri]: ...
    def getRttTextStream(self) -> 'Connection.RttTextStream': ...
    def getVideoState(self) -> int: ...
    def isAdhocConferenceCall(self) -> bool: ...
    def isRequestingRtt(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ConnectionService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def addConference(self, conference: 'Conference') -> None: ...
    def addExistingConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connection: 'Connection') -> None: ...
    def conferenceRemoteConnections(self, remoteConnection: 'RemoteConnection', remoteConnection2: 'RemoteConnection') -> None: ...
    def connectionServiceFocusReleased(self) -> None: ...
    def createRemoteIncomingConference(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'RemoteConference': ...
    def createRemoteIncomingConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'RemoteConnection': ...
    def createRemoteOutgoingConference(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'RemoteConference': ...
    def createRemoteOutgoingConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'RemoteConnection': ...
    def getAllConferences(self) -> java.util.Collection['Conference']: ...
    def getAllConnections(self) -> java.util.Collection['Connection']: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onConference(self, connection: 'Connection', connection2: 'Connection') -> None: ...
    def onConnectionServiceFocusGained(self) -> None: ...
    def onConnectionServiceFocusLost(self) -> None: ...
    def onCreateIncomingConference(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'Conference': ...
    def onCreateIncomingConferenceFailed(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> None: ...
    def onCreateIncomingConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'Connection': ...
    def onCreateIncomingConnectionFailed(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> None: ...
    def onCreateIncomingHandoverConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'Connection': ...
    def onCreateOutgoingConference(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'Conference': ...
    def onCreateOutgoingConferenceFailed(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> None: ...
    def onCreateOutgoingConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'Connection': ...
    def onCreateOutgoingConnectionFailed(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> None: ...
    def onCreateOutgoingHandoverConnection(self, phoneAccountHandle: 'PhoneAccountHandle', connectionRequest: ConnectionRequest) -> 'Connection': ...
    def onHandoverFailed(self, connectionRequest: ConnectionRequest, int: int) -> None: ...
    def onRemoteConferenceAdded(self, remoteConference: 'RemoteConference') -> None: ...
    def onRemoteExistingConnectionAdded(self, remoteConnection: 'RemoteConnection') -> None: ...
    def onUnbind(self, intent: android.content.Intent) -> bool: ...

class DisconnectCause(android.os.Parcelable):
    ANSWERED_ELSEWHERE: typing.ClassVar[int] = ...
    BUSY: typing.ClassVar[int] = ...
    CALL_PULLED: typing.ClassVar[int] = ...
    CANCELED: typing.ClassVar[int] = ...
    CONNECTION_MANAGER_NOT_SUPPORTED: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    ERROR: typing.ClassVar[int] = ...
    LOCAL: typing.ClassVar[int] = ...
    MISSED: typing.ClassVar[int] = ...
    OTHER: typing.ClassVar[int] = ...
    REASON_EMERGENCY_CALL_PLACED: typing.ClassVar[str] = ...
    REASON_EMULATING_SINGLE_CALL: typing.ClassVar[str] = ...
    REASON_IMS_ACCESS_BLOCKED: typing.ClassVar[str] = ...
    REASON_WIFI_ON_BUT_WFC_OFF: typing.ClassVar[str] = ...
    REJECTED: typing.ClassVar[int] = ...
    REMOTE: typing.ClassVar[int] = ...
    RESTRICTED: typing.ClassVar[int] = ...
    UNKNOWN: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], string: str): ...
    @typing.overload
    def __init__(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], string: str, int2: int): ...
    @typing.overload
    def __init__(self, int: int, string: str): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCode(self) -> int: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getLabel(self) -> java.lang.CharSequence: ...
    def getReason(self) -> str: ...
    def getTone(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GatewayInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, uri: android.net.Uri, uri2: android.net.Uri): ...
    def describeContents(self) -> int: ...
    def getGatewayAddress(self) -> android.net.Uri: ...
    def getGatewayProviderPackageName(self) -> str: ...
    def getOriginalAddress(self) -> android.net.Uri: ...
    def isEmpty(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class InCallService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def canAddCall(self) -> bool: ...
    def getCallAudioState(self) -> CallAudioState: ...
    def getCalls(self) -> java.util.List[Call]: ...
    def getCurrentCallEndpoint(self) -> CallEndpoint: ...
    def onAvailableCallEndpointsChanged(self, list: java.util.List[CallEndpoint]) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onBringToForeground(self, boolean: bool) -> None: ...
    def onCallAdded(self, call: Call) -> None: ...
    def onCallAudioStateChanged(self, callAudioState: CallAudioState) -> None: ...
    def onCallEndpointChanged(self, callEndpoint: CallEndpoint) -> None: ...
    def onCallRemoved(self, call: Call) -> None: ...
    def onCanAddCallChanged(self, boolean: bool) -> None: ...
    def onConnectionEvent(self, call: Call, string: str, bundle: android.os.Bundle) -> None: ...
    def onMuteStateChanged(self, boolean: bool) -> None: ...
    def onSilenceRinger(self) -> None: ...
    def onUnbind(self, intent: android.content.Intent) -> bool: ...
    def requestBluetoothAudio(self, bluetoothDevice: android.bluetooth.BluetoothDevice) -> None: ...
    def requestCallEndpointChange(self, callEndpoint: CallEndpoint, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, CallEndpointException], typing.Callable[[None], None]]) -> None: ...
    def setAudioRoute(self, int: int) -> None: ...
    def setMuted(self, boolean: bool) -> None: ...
    class VideoCall:
        def __init__(self): ...
        @typing.overload
        def registerCallback(self, callback: 'InCallService.VideoCall.Callback') -> None: ...
        @typing.overload
        def registerCallback(self, callback: 'InCallService.VideoCall.Callback', handler: android.os.Handler) -> None: ...
        def requestCallDataUsage(self) -> None: ...
        def requestCameraCapabilities(self) -> None: ...
        def sendSessionModifyRequest(self, videoProfile: 'VideoProfile') -> None: ...
        def sendSessionModifyResponse(self, videoProfile: 'VideoProfile') -> None: ...
        def setCamera(self, string: str) -> None: ...
        def setDeviceOrientation(self, int: int) -> None: ...
        def setDisplaySurface(self, surface: android.view.Surface) -> None: ...
        def setPauseImage(self, uri: android.net.Uri) -> None: ...
        def setPreviewSurface(self, surface: android.view.Surface) -> None: ...
        def setZoom(self, float: float) -> None: ...
        def unregisterCallback(self, callback: 'InCallService.VideoCall.Callback') -> None: ...
        class Callback:
            def __init__(self): ...
            def onCallDataUsageChanged(self, long: int) -> None: ...
            def onCallSessionEvent(self, int: int) -> None: ...
            def onCameraCapabilitiesChanged(self, cameraCapabilities: 'VideoProfile.CameraCapabilities') -> None: ...
            def onPeerDimensionsChanged(self, int: int, int2: int) -> None: ...
            def onSessionModifyRequestReceived(self, videoProfile: 'VideoProfile') -> None: ...
            def onSessionModifyResponseReceived(self, int: int, videoProfile: 'VideoProfile', videoProfile2: 'VideoProfile') -> None: ...
            def onVideoQualityChanged(self, int: int) -> None: ...

class PhoneAccount(android.os.Parcelable):
    CAPABILITY_ADHOC_CONFERENCE_CALLING: typing.ClassVar[int] = ...
    CAPABILITY_CALL_COMPOSER: typing.ClassVar[int] = ...
    CAPABILITY_CALL_PROVIDER: typing.ClassVar[int] = ...
    CAPABILITY_CALL_SUBJECT: typing.ClassVar[int] = ...
    CAPABILITY_CONNECTION_MANAGER: typing.ClassVar[int] = ...
    CAPABILITY_PLACE_EMERGENCY_CALLS: typing.ClassVar[int] = ...
    CAPABILITY_RTT: typing.ClassVar[int] = ...
    CAPABILITY_SELF_MANAGED: typing.ClassVar[int] = ...
    CAPABILITY_SIM_SUBSCRIPTION: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_CALL_STREAMING: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_TRANSACTIONAL_OPERATIONS: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VIDEO_CALLING: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VOICE_CALLING_INDICATIONS: typing.ClassVar[int] = ...
    CAPABILITY_VIDEO_CALLING: typing.ClassVar[int] = ...
    CAPABILITY_VIDEO_CALLING_RELIES_ON_PRESENCE: typing.ClassVar[int] = ...
    CAPABILITY_VOICE_CALLING_AVAILABLE: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EXTRA_ADD_SELF_MANAGED_CALLS_TO_INCALLSERVICE: typing.ClassVar[str] = ...
    EXTRA_ALWAYS_USE_VOIP_AUDIO_MODE: typing.ClassVar[str] = ...
    EXTRA_CALL_SUBJECT_CHARACTER_ENCODING: typing.ClassVar[str] = ...
    EXTRA_CALL_SUBJECT_MAX_LENGTH: typing.ClassVar[str] = ...
    EXTRA_LOG_SELF_MANAGED_CALLS: typing.ClassVar[str] = ...
    EXTRA_SUPPORTS_HANDOVER_FROM: typing.ClassVar[str] = ...
    EXTRA_SUPPORTS_HANDOVER_TO: typing.ClassVar[str] = ...
    NO_HIGHLIGHT_COLOR: typing.ClassVar[int] = ...
    NO_RESOURCE_ID: typing.ClassVar[int] = ...
    SCHEME_SIP: typing.ClassVar[str] = ...
    SCHEME_TEL: typing.ClassVar[str] = ...
    SCHEME_VOICEMAIL: typing.ClassVar[str] = ...
    @staticmethod
    def builder(phoneAccountHandle: 'PhoneAccountHandle', charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PhoneAccount.Builder': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAccountHandle(self) -> 'PhoneAccountHandle': ...
    def getAddress(self) -> android.net.Uri: ...
    def getCapabilities(self) -> int: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getHighlightColor(self) -> int: ...
    def getIcon(self) -> android.graphics.drawable.Icon: ...
    def getLabel(self) -> java.lang.CharSequence: ...
    def getShortDescription(self) -> java.lang.CharSequence: ...
    def getSimultaneousCallingRestriction(self) -> java.util.Set['PhoneAccountHandle']: ...
    def getSubscriptionAddress(self) -> android.net.Uri: ...
    def getSupportedUriSchemes(self) -> java.util.List[str]: ...
    def hasCapabilities(self, int: int) -> bool: ...
    def hasSimultaneousCallingRestriction(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isEnabled(self) -> bool: ...
    def supportsUriScheme(self, string: str) -> bool: ...
    def toBuilder(self) -> 'PhoneAccount.Builder': ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, phoneAccount: 'PhoneAccount'): ...
        @typing.overload
        def __init__(self, phoneAccountHandle: 'PhoneAccountHandle', charSequence: typing.Union[java.lang.CharSequence, str]): ...
        def addSupportedUriScheme(self, string: str) -> 'PhoneAccount.Builder': ...
        def build(self) -> 'PhoneAccount': ...
        def clearSimultaneousCallingRestriction(self) -> 'PhoneAccount.Builder': ...
        def setAddress(self, uri: android.net.Uri) -> 'PhoneAccount.Builder': ...
        def setCapabilities(self, int: int) -> 'PhoneAccount.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'PhoneAccount.Builder': ...
        def setHighlightColor(self, int: int) -> 'PhoneAccount.Builder': ...
        def setIcon(self, icon: android.graphics.drawable.Icon) -> 'PhoneAccount.Builder': ...
        def setShortDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'PhoneAccount.Builder': ...
        def setSimultaneousCallingRestriction(self, set: java.util.Set['PhoneAccountHandle']) -> 'PhoneAccount.Builder': ...
        def setSubscriptionAddress(self, uri: android.net.Uri) -> 'PhoneAccount.Builder': ...
        def setSupportedUriSchemes(self, list: java.util.List[str]) -> 'PhoneAccount.Builder': ...

class PhoneAccountHandle(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, componentName: android.content.ComponentName, string: str): ...
    @typing.overload
    def __init__(self, componentName: android.content.ComponentName, string: str, userHandle: android.os.UserHandle): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getComponentName(self) -> android.content.ComponentName: ...
    def getId(self) -> str: ...
    def getUserHandle(self) -> android.os.UserHandle: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PhoneAccountSuggestion(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    REASON_FREQUENT: typing.ClassVar[int] = ...
    REASON_INTRA_CARRIER: typing.ClassVar[int] = ...
    REASON_NONE: typing.ClassVar[int] = ...
    REASON_OTHER: typing.ClassVar[int] = ...
    REASON_USER_SET: typing.ClassVar[int] = ...
    def __init__(self, phoneAccountHandle: PhoneAccountHandle, int: int, boolean: bool): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPhoneAccountHandle(self) -> PhoneAccountHandle: ...
    def getReason(self) -> int: ...
    def hashCode(self) -> int: ...
    def shouldAutoSelect(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class QueryLocationException(java.lang.RuntimeException, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    ERROR_NOT_ALLOWED_FOR_NON_EMERGENCY_CONNECTIONS: typing.ClassVar[int] = ...
    ERROR_NOT_PERMITTED: typing.ClassVar[int] = ...
    ERROR_PREVIOUS_REQUEST_EXISTS: typing.ClassVar[int] = ...
    ERROR_REQUEST_TIME_OUT: typing.ClassVar[int] = ...
    ERROR_SERVICE_UNAVAILABLE: typing.ClassVar[int] = ...
    ERROR_UNSPECIFIED: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, int: int): ...
    @typing.overload
    def __init__(self, string: str, int: int, throwable: java.lang.Throwable): ...
    def describeContents(self) -> int: ...
    def getCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class RemoteConference:
    def disconnect(self) -> None: ...
    def getConferenceableConnections(self) -> java.util.List['RemoteConnection']: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def getConnections(self) -> java.util.List['RemoteConnection']: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getState(self) -> int: ...
    def hold(self) -> None: ...
    def merge(self) -> None: ...
    def playDtmfTone(self, char: str) -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'RemoteConference.Callback') -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'RemoteConference.Callback', handler: android.os.Handler) -> None: ...
    def separate(self, remoteConnection: 'RemoteConnection') -> None: ...
    def setCallAudioState(self, callAudioState: CallAudioState) -> None: ...
    def stopDtmfTone(self) -> None: ...
    def swap(self) -> None: ...
    def unhold(self) -> None: ...
    def unregisterCallback(self, callback: 'RemoteConference.Callback') -> None: ...
    class Callback:
        def __init__(self): ...
        def onConferenceableConnectionsChanged(self, remoteConference: 'RemoteConference', list: java.util.List['RemoteConnection']) -> None: ...
        def onConnectionAdded(self, remoteConference: 'RemoteConference', remoteConnection: 'RemoteConnection') -> None: ...
        def onConnectionCapabilitiesChanged(self, remoteConference: 'RemoteConference', int: int) -> None: ...
        def onConnectionPropertiesChanged(self, remoteConference: 'RemoteConference', int: int) -> None: ...
        def onConnectionRemoved(self, remoteConference: 'RemoteConference', remoteConnection: 'RemoteConnection') -> None: ...
        def onDestroyed(self, remoteConference: 'RemoteConference') -> None: ...
        def onDisconnected(self, remoteConference: 'RemoteConference', disconnectCause: DisconnectCause) -> None: ...
        def onExtrasChanged(self, remoteConference: 'RemoteConference', bundle: android.os.Bundle) -> None: ...
        def onStateChanged(self, remoteConference: 'RemoteConference', int: int, int2: int) -> None: ...

class RemoteConnection:
    def abort(self) -> None: ...
    def addConferenceParticipants(self, list: java.util.List[android.net.Uri]) -> None: ...
    def answer(self) -> None: ...
    def disconnect(self) -> None: ...
    def getAddress(self) -> android.net.Uri: ...
    def getAddressPresentation(self) -> int: ...
    def getCallerDisplayName(self) -> java.lang.CharSequence: ...
    def getCallerDisplayNamePresentation(self) -> int: ...
    def getConference(self) -> RemoteConference: ...
    def getConferenceableConnections(self) -> java.util.List['RemoteConnection']: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getState(self) -> int: ...
    def getStatusHints(self) -> 'StatusHints': ...
    def getVideoProvider(self) -> 'RemoteConnection.VideoProvider': ...
    def getVideoState(self) -> int: ...
    def hold(self) -> None: ...
    def isRingbackRequested(self) -> bool: ...
    def isVoipAudioMode(self) -> bool: ...
    def playDtmfTone(self, char: str) -> None: ...
    def postDialContinue(self, boolean: bool) -> None: ...
    def pullExternalCall(self) -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'RemoteConnection.Callback') -> None: ...
    @typing.overload
    def registerCallback(self, callback: 'RemoteConnection.Callback', handler: android.os.Handler) -> None: ...
    def reject(self) -> None: ...
    def setCallAudioState(self, callAudioState: CallAudioState) -> None: ...
    def stopDtmfTone(self) -> None: ...
    def unhold(self) -> None: ...
    def unregisterCallback(self, callback: 'RemoteConnection.Callback') -> None: ...
    class Callback:
        def __init__(self): ...
        def onAddressChanged(self, remoteConnection: 'RemoteConnection', uri: android.net.Uri, int: int) -> None: ...
        def onCallerDisplayNameChanged(self, remoteConnection: 'RemoteConnection', string: str, int: int) -> None: ...
        def onConferenceChanged(self, remoteConnection: 'RemoteConnection', remoteConference: RemoteConference) -> None: ...
        def onConferenceableConnectionsChanged(self, remoteConnection: 'RemoteConnection', list: java.util.List['RemoteConnection']) -> None: ...
        def onConnectionCapabilitiesChanged(self, remoteConnection: 'RemoteConnection', int: int) -> None: ...
        def onConnectionEvent(self, remoteConnection: 'RemoteConnection', string: str, bundle: android.os.Bundle) -> None: ...
        def onConnectionPropertiesChanged(self, remoteConnection: 'RemoteConnection', int: int) -> None: ...
        def onDestroyed(self, remoteConnection: 'RemoteConnection') -> None: ...
        def onDisconnected(self, remoteConnection: 'RemoteConnection', disconnectCause: DisconnectCause) -> None: ...
        def onExtrasChanged(self, remoteConnection: 'RemoteConnection', bundle: android.os.Bundle) -> None: ...
        def onPostDialChar(self, remoteConnection: 'RemoteConnection', char: str) -> None: ...
        def onPostDialWait(self, remoteConnection: 'RemoteConnection', string: str) -> None: ...
        def onRingbackRequested(self, remoteConnection: 'RemoteConnection', boolean: bool) -> None: ...
        def onStateChanged(self, remoteConnection: 'RemoteConnection', int: int) -> None: ...
        def onStatusHintsChanged(self, remoteConnection: 'RemoteConnection', statusHints: 'StatusHints') -> None: ...
        def onVideoProviderChanged(self, remoteConnection: 'RemoteConnection', videoProvider: 'RemoteConnection.VideoProvider') -> None: ...
        def onVideoStateChanged(self, remoteConnection: 'RemoteConnection', int: int) -> None: ...
        def onVoipAudioChanged(self, remoteConnection: 'RemoteConnection', boolean: bool) -> None: ...
    class VideoProvider:
        def registerCallback(self, callback: 'RemoteConnection.VideoProvider.Callback') -> None: ...
        def requestCallDataUsage(self) -> None: ...
        def requestCameraCapabilities(self) -> None: ...
        def sendSessionModifyRequest(self, videoProfile: 'VideoProfile', videoProfile2: 'VideoProfile') -> None: ...
        def sendSessionModifyResponse(self, videoProfile: 'VideoProfile') -> None: ...
        def setCamera(self, string: str) -> None: ...
        def setDeviceOrientation(self, int: int) -> None: ...
        def setDisplaySurface(self, surface: android.view.Surface) -> None: ...
        def setPauseImage(self, uri: android.net.Uri) -> None: ...
        def setPreviewSurface(self, surface: android.view.Surface) -> None: ...
        def setZoom(self, float: float) -> None: ...
        def unregisterCallback(self, callback: 'RemoteConnection.VideoProvider.Callback') -> None: ...
        class Callback:
            def __init__(self): ...
            def onCallDataUsageChanged(self, videoProvider: 'RemoteConnection.VideoProvider', long: int) -> None: ...
            def onCallSessionEvent(self, videoProvider: 'RemoteConnection.VideoProvider', int: int) -> None: ...
            def onCameraCapabilitiesChanged(self, videoProvider: 'RemoteConnection.VideoProvider', cameraCapabilities: 'VideoProfile.CameraCapabilities') -> None: ...
            def onPeerDimensionsChanged(self, videoProvider: 'RemoteConnection.VideoProvider', int: int, int2: int) -> None: ...
            def onSessionModifyRequestReceived(self, videoProvider: 'RemoteConnection.VideoProvider', videoProfile: 'VideoProfile') -> None: ...
            def onSessionModifyResponseReceived(self, videoProvider: 'RemoteConnection.VideoProvider', int: int, videoProfile: 'VideoProfile', videoProfile2: 'VideoProfile') -> None: ...
            def onVideoQualityChanged(self, videoProvider: 'RemoteConnection.VideoProvider', int: int) -> None: ...

class StatusHints(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], icon: android.graphics.drawable.Icon, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getIcon(self) -> android.graphics.drawable.Icon: ...
    def getLabel(self) -> java.lang.CharSequence: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TelecomManager:
    ACTION_CHANGE_DEFAULT_DIALER: typing.ClassVar[str] = ...
    ACTION_CHANGE_PHONE_ACCOUNTS: typing.ClassVar[str] = ...
    ACTION_CONFIGURE_PHONE_ACCOUNT: typing.ClassVar[str] = ...
    ACTION_DEFAULT_CALL_SCREENING_APP_CHANGED: typing.ClassVar[str] = ...
    ACTION_DEFAULT_DIALER_CHANGED: typing.ClassVar[str] = ...
    ACTION_INCOMING_CALL: typing.ClassVar[str] = ...
    ACTION_PHONE_ACCOUNT_REGISTERED: typing.ClassVar[str] = ...
    ACTION_PHONE_ACCOUNT_UNREGISTERED: typing.ClassVar[str] = ...
    ACTION_POST_CALL: typing.ClassVar[str] = ...
    ACTION_SHOW_CALL_ACCESSIBILITY_SETTINGS: typing.ClassVar[str] = ...
    ACTION_SHOW_CALL_SETTINGS: typing.ClassVar[str] = ...
    ACTION_SHOW_MISSED_CALLS_NOTIFICATION: typing.ClassVar[str] = ...
    ACTION_SHOW_RESPOND_VIA_SMS_SETTINGS: typing.ClassVar[str] = ...
    DTMF_CHARACTER_PAUSE: typing.ClassVar[str] = ...
    DTMF_CHARACTER_WAIT: typing.ClassVar[str] = ...
    DURATION_LONG: typing.ClassVar[int] = ...
    DURATION_MEDIUM: typing.ClassVar[int] = ...
    DURATION_SHORT: typing.ClassVar[int] = ...
    DURATION_VERY_SHORT: typing.ClassVar[int] = ...
    EXTRA_CALL_BACK_NUMBER: typing.ClassVar[str] = ...
    EXTRA_CALL_DISCONNECT_CAUSE: typing.ClassVar[str] = ...
    EXTRA_CALL_DISCONNECT_MESSAGE: typing.ClassVar[str] = ...
    EXTRA_CALL_DURATION: typing.ClassVar[str] = ...
    EXTRA_CALL_LOG_URI: typing.ClassVar[str] = ...
    EXTRA_CALL_NETWORK_TYPE: typing.ClassVar[str] = ...
    EXTRA_CALL_SUBJECT: typing.ClassVar[str] = ...
    EXTRA_CHANGE_DEFAULT_DIALER_PACKAGE_NAME: typing.ClassVar[str] = ...
    EXTRA_DEFAULT_CALL_SCREENING_APP_COMPONENT_NAME: typing.ClassVar[str] = ...
    EXTRA_DISCONNECT_CAUSE: typing.ClassVar[str] = ...
    EXTRA_HANDLE: typing.ClassVar[str] = ...
    EXTRA_HAS_PICTURE: typing.ClassVar[str] = ...
    EXTRA_INCOMING_CALL_ADDRESS: typing.ClassVar[str] = ...
    EXTRA_INCOMING_CALL_EXTRAS: typing.ClassVar[str] = ...
    EXTRA_INCOMING_VIDEO_STATE: typing.ClassVar[str] = ...
    EXTRA_IS_DEFAULT_CALL_SCREENING_APP: typing.ClassVar[str] = ...
    EXTRA_LOCATION: typing.ClassVar[str] = ...
    EXTRA_NOTIFICATION_COUNT: typing.ClassVar[str] = ...
    EXTRA_NOTIFICATION_PHONE_NUMBER: typing.ClassVar[str] = ...
    EXTRA_OUTGOING_CALL_EXTRAS: typing.ClassVar[str] = ...
    EXTRA_OUTGOING_PICTURE: typing.ClassVar[str] = ...
    EXTRA_PHONE_ACCOUNT_HANDLE: typing.ClassVar[str] = ...
    EXTRA_PICTURE_URI: typing.ClassVar[str] = ...
    EXTRA_PRIORITY: typing.ClassVar[str] = ...
    EXTRA_START_CALL_WITH_RTT: typing.ClassVar[str] = ...
    EXTRA_START_CALL_WITH_SPEAKERPHONE: typing.ClassVar[str] = ...
    EXTRA_START_CALL_WITH_VIDEO_STATE: typing.ClassVar[str] = ...
    EXTRA_USE_ASSISTED_DIALING: typing.ClassVar[str] = ...
    GATEWAY_ORIGINAL_ADDRESS: typing.ClassVar[str] = ...
    GATEWAY_PROVIDER_PACKAGE: typing.ClassVar[str] = ...
    METADATA_INCLUDE_EXTERNAL_CALLS: typing.ClassVar[str] = ...
    METADATA_INCLUDE_SELF_MANAGED_CALLS: typing.ClassVar[str] = ...
    METADATA_IN_CALL_SERVICE_CAR_MODE_UI: typing.ClassVar[str] = ...
    METADATA_IN_CALL_SERVICE_RINGING: typing.ClassVar[str] = ...
    METADATA_IN_CALL_SERVICE_UI: typing.ClassVar[str] = ...
    PRESENTATION_ALLOWED: typing.ClassVar[int] = ...
    PRESENTATION_PAYPHONE: typing.ClassVar[int] = ...
    PRESENTATION_RESTRICTED: typing.ClassVar[int] = ...
    PRESENTATION_UNAVAILABLE: typing.ClassVar[int] = ...
    PRESENTATION_UNKNOWN: typing.ClassVar[int] = ...
    PRIORITY_NORMAL: typing.ClassVar[int] = ...
    PRIORITY_URGENT: typing.ClassVar[int] = ...
    def acceptHandover(self, uri: android.net.Uri, int: int, phoneAccountHandle: PhoneAccountHandle) -> None: ...
    @typing.overload
    def acceptRingingCall(self) -> None: ...
    @typing.overload
    def acceptRingingCall(self, int: int) -> None: ...
    def addCall(self, callAttributes: CallAttributes, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[CallControl, CallException], typing.Callable[[CallControl], None]], callControlCallback: CallControlCallback, callEventCallback: CallEventCallback) -> None: ...
    def addNewIncomingCall(self, phoneAccountHandle: PhoneAccountHandle, bundle: android.os.Bundle) -> None: ...
    def addNewIncomingConference(self, phoneAccountHandle: PhoneAccountHandle, bundle: android.os.Bundle) -> None: ...
    def cancelMissedCallsNotification(self) -> None: ...
    def createManageBlockedNumbersIntent(self) -> android.content.Intent: ...
    def endCall(self) -> bool: ...
    def getAdnUriForPhoneAccount(self, phoneAccountHandle: PhoneAccountHandle) -> android.net.Uri: ...
    def getCallCapablePhoneAccounts(self) -> java.util.List[PhoneAccountHandle]: ...
    def getDefaultDialerPackage(self) -> str: ...
    def getDefaultOutgoingPhoneAccount(self, string: str) -> PhoneAccountHandle: ...
    def getLine1Number(self, phoneAccountHandle: PhoneAccountHandle) -> str: ...
    def getOwnSelfManagedPhoneAccounts(self) -> java.util.List[PhoneAccountHandle]: ...
    def getPhoneAccount(self, phoneAccountHandle: PhoneAccountHandle) -> PhoneAccount: ...
    def getRegisteredPhoneAccounts(self) -> java.util.List[PhoneAccount]: ...
    def getSelfManagedPhoneAccounts(self) -> java.util.List[PhoneAccountHandle]: ...
    def getSimCallManager(self) -> PhoneAccountHandle: ...
    def getSimCallManagerForSubscription(self, int: int) -> PhoneAccountHandle: ...
    def getSystemDialerPackage(self) -> str: ...
    def getUserSelectedOutgoingPhoneAccount(self) -> PhoneAccountHandle: ...
    def getVoiceMailNumber(self, phoneAccountHandle: PhoneAccountHandle) -> str: ...
    @typing.overload
    def handleMmi(self, string: str) -> bool: ...
    @typing.overload
    def handleMmi(self, string: str, phoneAccountHandle: PhoneAccountHandle) -> bool: ...
    def hasManageOngoingCallsPermission(self) -> bool: ...
    def isInCall(self) -> bool: ...
    def isInManagedCall(self) -> bool: ...
    def isIncomingCallPermitted(self, phoneAccountHandle: PhoneAccountHandle) -> bool: ...
    def isOutgoingCallPermitted(self, phoneAccountHandle: PhoneAccountHandle) -> bool: ...
    def isTtySupported(self) -> bool: ...
    def isVoiceMailNumber(self, phoneAccountHandle: PhoneAccountHandle, string: str) -> bool: ...
    def placeCall(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
    def registerPhoneAccount(self, phoneAccount: PhoneAccount) -> None: ...
    def showInCallScreen(self, boolean: bool) -> None: ...
    def silenceRinger(self) -> None: ...
    def startConference(self, list: java.util.List[android.net.Uri], bundle: android.os.Bundle) -> None: ...
    def unregisterPhoneAccount(self, phoneAccountHandle: PhoneAccountHandle) -> None: ...

class VideoProfile(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    QUALITY_DEFAULT: typing.ClassVar[int] = ...
    QUALITY_HIGH: typing.ClassVar[int] = ...
    QUALITY_LOW: typing.ClassVar[int] = ...
    QUALITY_MEDIUM: typing.ClassVar[int] = ...
    STATE_AUDIO_ONLY: typing.ClassVar[int] = ...
    STATE_BIDIRECTIONAL: typing.ClassVar[int] = ...
    STATE_PAUSED: typing.ClassVar[int] = ...
    STATE_RX_ENABLED: typing.ClassVar[int] = ...
    STATE_TX_ENABLED: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def getQuality(self) -> int: ...
    def getVideoState(self) -> int: ...
    @staticmethod
    def isAudioOnly(int: int) -> bool: ...
    @staticmethod
    def isBidirectional(int: int) -> bool: ...
    @staticmethod
    def isPaused(int: int) -> bool: ...
    @staticmethod
    def isReceptionEnabled(int: int) -> bool: ...
    @staticmethod
    def isTransmissionEnabled(int: int) -> bool: ...
    @staticmethod
    def isVideo(int: int) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def videoStateToString(int: int) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class CameraCapabilities(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @typing.overload
        def __init__(self, int: int, int2: int): ...
        @typing.overload
        def __init__(self, int: int, int2: int, boolean: bool, float: float): ...
        def describeContents(self) -> int: ...
        def getHeight(self) -> int: ...
        def getMaxZoom(self) -> float: ...
        def getWidth(self) -> int: ...
        def isZoomSupported(self) -> bool: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Conference(Conferenceable):
    CONNECT_TIME_NOT_SPECIFIED: typing.ClassVar[int] = ...
    def __init__(self, phoneAccountHandle: PhoneAccountHandle): ...
    def addConnection(self, connection: 'Connection') -> bool: ...
    @staticmethod
    def createFailedConference(disconnectCause: DisconnectCause, phoneAccountHandle: PhoneAccountHandle) -> 'Conference': ...
    def destroy(self) -> None: ...
    def getCallAudioState(self) -> CallAudioState: ...
    def getConferenceableConnections(self) -> java.util.List['Connection']: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def getConnectionStartElapsedRealtimeMillis(self) -> int: ...
    def getConnectionTime(self) -> int: ...
    def getConnections(self) -> java.util.List['Connection']: ...
    def getCurrentCallEndpoint(self) -> CallEndpoint: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getPhoneAccountHandle(self) -> PhoneAccountHandle: ...
    def getState(self) -> int: ...
    def getStatusHints(self) -> StatusHints: ...
    def getVideoProvider(self) -> 'Connection.VideoProvider': ...
    def getVideoState(self) -> int: ...
    def isRingbackRequested(self) -> bool: ...
    def onAddConferenceParticipants(self, list: java.util.List[android.net.Uri]) -> None: ...
    def onAnswer(self, int: int) -> None: ...
    def onAvailableCallEndpointsChanged(self, list: java.util.List[CallEndpoint]) -> None: ...
    def onCallAudioStateChanged(self, callAudioState: CallAudioState) -> None: ...
    def onCallEndpointChanged(self, callEndpoint: CallEndpoint) -> None: ...
    def onConnectionAdded(self, connection: 'Connection') -> None: ...
    def onDisconnect(self) -> None: ...
    def onExtrasChanged(self, bundle: android.os.Bundle) -> None: ...
    def onHold(self) -> None: ...
    @typing.overload
    def onMerge(self) -> None: ...
    @typing.overload
    def onMerge(self, connection: 'Connection') -> None: ...
    def onMuteStateChanged(self, boolean: bool) -> None: ...
    def onPlayDtmfTone(self, char: str) -> None: ...
    def onReject(self) -> None: ...
    def onSeparate(self, connection: 'Connection') -> None: ...
    def onStopDtmfTone(self) -> None: ...
    def onSwap(self) -> None: ...
    def onUnhold(self) -> None: ...
    def putExtras(self, bundle: android.os.Bundle) -> None: ...
    def removeConnection(self, connection: 'Connection') -> None: ...
    @typing.overload
    def removeExtras(self, *string: str) -> None: ...
    @typing.overload
    def removeExtras(self, list: java.util.List[str]) -> None: ...
    def sendConferenceEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def setActive(self) -> None: ...
    def setConferenceableConnections(self, list: java.util.List['Connection']) -> None: ...
    def setConnectionCapabilities(self, int: int) -> None: ...
    def setConnectionProperties(self, int: int) -> None: ...
    def setConnectionStartElapsedRealTime(self, long: int) -> None: ...
    def setConnectionStartElapsedRealtimeMillis(self, long: int) -> None: ...
    def setConnectionTime(self, long: int) -> None: ...
    def setDialing(self) -> None: ...
    def setDisconnected(self, disconnectCause: DisconnectCause) -> None: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setOnHold(self) -> None: ...
    def setRingbackRequested(self, boolean: bool) -> None: ...
    def setRinging(self) -> None: ...
    def setStatusHints(self, statusHints: StatusHints) -> None: ...
    def setVideoProvider(self, connection: 'Connection', videoProvider: 'Connection.VideoProvider') -> None: ...
    def setVideoState(self, connection: 'Connection', int: int) -> None: ...
    def toString(self) -> str: ...

class Connection(Conferenceable):
    AUDIO_CODEC_AMR: typing.ClassVar[int] = ...
    AUDIO_CODEC_AMR_WB: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVRC: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVRC_B: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVRC_NW: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVRC_WB: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVS_FB: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVS_NB: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVS_SWB: typing.ClassVar[int] = ...
    AUDIO_CODEC_EVS_WB: typing.ClassVar[int] = ...
    AUDIO_CODEC_G711A: typing.ClassVar[int] = ...
    AUDIO_CODEC_G711AB: typing.ClassVar[int] = ...
    AUDIO_CODEC_G711U: typing.ClassVar[int] = ...
    AUDIO_CODEC_G722: typing.ClassVar[int] = ...
    AUDIO_CODEC_G723: typing.ClassVar[int] = ...
    AUDIO_CODEC_G729: typing.ClassVar[int] = ...
    AUDIO_CODEC_GSM_EFR: typing.ClassVar[int] = ...
    AUDIO_CODEC_GSM_FR: typing.ClassVar[int] = ...
    AUDIO_CODEC_GSM_HR: typing.ClassVar[int] = ...
    AUDIO_CODEC_NONE: typing.ClassVar[int] = ...
    AUDIO_CODEC_QCELP13K: typing.ClassVar[int] = ...
    CAPABILITY_ADD_PARTICIPANT: typing.ClassVar[int] = ...
    CAPABILITY_CANNOT_DOWNGRADE_VIDEO_TO_AUDIO: typing.ClassVar[int] = ...
    CAPABILITY_CAN_PAUSE_VIDEO: typing.ClassVar[int] = ...
    CAPABILITY_CAN_PULL_CALL: typing.ClassVar[int] = ...
    CAPABILITY_CAN_SEND_RESPONSE_VIA_CONNECTION: typing.ClassVar[int] = ...
    CAPABILITY_CAN_UPGRADE_TO_VIDEO: typing.ClassVar[int] = ...
    CAPABILITY_DISCONNECT_FROM_CONFERENCE: typing.ClassVar[int] = ...
    CAPABILITY_HOLD: typing.ClassVar[int] = ...
    CAPABILITY_MANAGE_CONFERENCE: typing.ClassVar[int] = ...
    CAPABILITY_MERGE_CONFERENCE: typing.ClassVar[int] = ...
    CAPABILITY_MUTE: typing.ClassVar[int] = ...
    CAPABILITY_REMOTE_PARTY_SUPPORTS_RTT: typing.ClassVar[int] = ...
    CAPABILITY_RESPOND_VIA_TEXT: typing.ClassVar[int] = ...
    CAPABILITY_SEPARATE_FROM_CONFERENCE: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VT_LOCAL_RX: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VT_LOCAL_TX: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VT_REMOTE_BIDIRECTIONAL: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VT_REMOTE_RX: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORTS_VT_REMOTE_TX: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORT_DEFLECT: typing.ClassVar[int] = ...
    CAPABILITY_SUPPORT_HOLD: typing.ClassVar[int] = ...
    CAPABILITY_SWAP_CONFERENCE: typing.ClassVar[int] = ...
    EVENT_CALL_HOLD_FAILED: typing.ClassVar[str] = ...
    EVENT_CALL_MERGE_FAILED: typing.ClassVar[str] = ...
    EVENT_CALL_PULL_FAILED: typing.ClassVar[str] = ...
    EVENT_CALL_REMOTELY_HELD: typing.ClassVar[str] = ...
    EVENT_CALL_REMOTELY_UNHELD: typing.ClassVar[str] = ...
    EVENT_CALL_SWITCH_FAILED: typing.ClassVar[str] = ...
    EVENT_MERGE_COMPLETE: typing.ClassVar[str] = ...
    EVENT_MERGE_START: typing.ClassVar[str] = ...
    EVENT_ON_HOLD_TONE_END: typing.ClassVar[str] = ...
    EVENT_ON_HOLD_TONE_START: typing.ClassVar[str] = ...
    EVENT_RTT_AUDIO_INDICATION_CHANGED: typing.ClassVar[str] = ...
    EXTRA_ANSWERING_DROPS_FG_CALL: typing.ClassVar[str] = ...
    EXTRA_ANSWERING_DROPS_FG_CALL_APP_NAME: typing.ClassVar[str] = ...
    EXTRA_AUDIO_CODEC: typing.ClassVar[str] = ...
    EXTRA_AUDIO_CODEC_BANDWIDTH_KHZ: typing.ClassVar[str] = ...
    EXTRA_AUDIO_CODEC_BITRATE_KBPS: typing.ClassVar[str] = ...
    EXTRA_CALL_SUBJECT: typing.ClassVar[str] = ...
    EXTRA_CHILD_ADDRESS: typing.ClassVar[str] = ...
    EXTRA_IS_RTT_AUDIO_PRESENT: typing.ClassVar[str] = ...
    EXTRA_LAST_FORWARDED_NUMBER: typing.ClassVar[str] = ...
    EXTRA_LAST_KNOWN_CELL_IDENTITY: typing.ClassVar[str] = ...
    EXTRA_SIP_INVITE: typing.ClassVar[str] = ...
    PROPERTY_ASSISTED_DIALING: typing.ClassVar[int] = ...
    PROPERTY_CROSS_SIM: typing.ClassVar[int] = ...
    PROPERTY_HAS_CDMA_VOICE_PRIVACY: typing.ClassVar[int] = ...
    PROPERTY_HIGH_DEF_AUDIO: typing.ClassVar[int] = ...
    PROPERTY_IS_ADHOC_CONFERENCE: typing.ClassVar[int] = ...
    PROPERTY_IS_EXTERNAL_CALL: typing.ClassVar[int] = ...
    PROPERTY_IS_RTT: typing.ClassVar[int] = ...
    PROPERTY_NETWORK_IDENTIFIED_EMERGENCY_CALL: typing.ClassVar[int] = ...
    PROPERTY_SELF_MANAGED: typing.ClassVar[int] = ...
    PROPERTY_WIFI: typing.ClassVar[int] = ...
    STATE_ACTIVE: typing.ClassVar[int] = ...
    STATE_DIALING: typing.ClassVar[int] = ...
    STATE_DISCONNECTED: typing.ClassVar[int] = ...
    STATE_HOLDING: typing.ClassVar[int] = ...
    STATE_INITIALIZING: typing.ClassVar[int] = ...
    STATE_NEW: typing.ClassVar[int] = ...
    STATE_PULLING_CALL: typing.ClassVar[int] = ...
    STATE_RINGING: typing.ClassVar[int] = ...
    VERIFICATION_STATUS_FAILED: typing.ClassVar[int] = ...
    VERIFICATION_STATUS_NOT_VERIFIED: typing.ClassVar[int] = ...
    VERIFICATION_STATUS_PASSED: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def capabilitiesToString(int: int) -> str: ...
    @staticmethod
    def createCanceledConnection() -> 'Connection': ...
    @staticmethod
    def createFailedConnection(disconnectCause: DisconnectCause) -> 'Connection': ...
    def destroy(self) -> None: ...
    def getAddress(self) -> android.net.Uri: ...
    def getAddressPresentation(self) -> int: ...
    def getAudioModeIsVoip(self) -> bool: ...
    def getCallAudioState(self) -> CallAudioState: ...
    def getCallerDisplayName(self) -> str: ...
    def getCallerDisplayNamePresentation(self) -> int: ...
    def getCallerNumberVerificationStatus(self) -> int: ...
    def getConference(self) -> Conference: ...
    def getConferenceables(self) -> java.util.List[Conferenceable]: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def getCurrentCallEndpoint(self) -> CallEndpoint: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getState(self) -> int: ...
    def getStatusHints(self) -> StatusHints: ...
    def getVideoProvider(self) -> 'Connection.VideoProvider': ...
    def getVideoState(self) -> int: ...
    def handleRttUpgradeResponse(self, rttTextStream: 'Connection.RttTextStream') -> None: ...
    def isRingbackRequested(self) -> bool: ...
    def notifyConferenceMergeFailed(self) -> None: ...
    def onAbort(self) -> None: ...
    def onAddConferenceParticipants(self, list: java.util.List[android.net.Uri]) -> None: ...
    @typing.overload
    def onAnswer(self) -> None: ...
    @typing.overload
    def onAnswer(self, int: int) -> None: ...
    def onAvailableCallEndpointsChanged(self, list: java.util.List[CallEndpoint]) -> None: ...
    def onCallAudioStateChanged(self, callAudioState: CallAudioState) -> None: ...
    def onCallEndpointChanged(self, callEndpoint: CallEndpoint) -> None: ...
    def onCallEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def onDeflect(self, uri: android.net.Uri) -> None: ...
    def onDisconnect(self) -> None: ...
    def onExtrasChanged(self, bundle: android.os.Bundle) -> None: ...
    def onHandoverComplete(self) -> None: ...
    def onHold(self) -> None: ...
    def onMuteStateChanged(self, boolean: bool) -> None: ...
    def onPlayDtmfTone(self, char: str) -> None: ...
    def onPostDialContinue(self, boolean: bool) -> None: ...
    def onPullExternalCall(self) -> None: ...
    @typing.overload
    def onReject(self) -> None: ...
    @typing.overload
    def onReject(self, int: int) -> None: ...
    @typing.overload
    def onReject(self, string: str) -> None: ...
    def onSeparate(self) -> None: ...
    def onShowIncomingCallUi(self) -> None: ...
    def onSilence(self) -> None: ...
    def onStartRtt(self, rttTextStream: 'Connection.RttTextStream') -> None: ...
    def onStateChanged(self, int: int) -> None: ...
    def onStopDtmfTone(self) -> None: ...
    def onStopRtt(self) -> None: ...
    def onTrackedByNonUiService(self, boolean: bool) -> None: ...
    def onUnhold(self) -> None: ...
    def onUsingAlternativeUi(self, boolean: bool) -> None: ...
    @staticmethod
    def propertiesToString(int: int) -> str: ...
    def putExtras(self, bundle: android.os.Bundle) -> None: ...
    def queryLocationForEmergency(self, long: int, string: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[android.location.Location, QueryLocationException], typing.Callable[[android.location.Location], None]]) -> None: ...
    @typing.overload
    def removeExtras(self, *string: str) -> None: ...
    @typing.overload
    def removeExtras(self, list: java.util.List[str]) -> None: ...
    def requestBluetoothAudio(self, bluetoothDevice: android.bluetooth.BluetoothDevice) -> None: ...
    def requestCallEndpointChange(self, callEndpoint: CallEndpoint, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, CallEndpointException], typing.Callable[[None], None]]) -> None: ...
    def sendConnectionEvent(self, string: str, bundle: android.os.Bundle) -> None: ...
    def sendRemoteRttRequest(self) -> None: ...
    def sendRttInitiationFailure(self, int: int) -> None: ...
    def sendRttInitiationSuccess(self) -> None: ...
    def sendRttSessionRemotelyTerminated(self) -> None: ...
    def setActive(self) -> None: ...
    def setAddress(self, uri: android.net.Uri, int: int) -> None: ...
    def setAudioModeIsVoip(self, boolean: bool) -> None: ...
    def setAudioRoute(self, int: int) -> None: ...
    def setCallerDisplayName(self, string: str, int: int) -> None: ...
    def setCallerNumberVerificationStatus(self, int: int) -> None: ...
    def setConferenceableConnections(self, list: java.util.List['Connection']) -> None: ...
    def setConferenceables(self, list: java.util.List[Conferenceable]) -> None: ...
    def setConnectionCapabilities(self, int: int) -> None: ...
    def setConnectionProperties(self, int: int) -> None: ...
    def setDialing(self) -> None: ...
    def setDisconnected(self, disconnectCause: DisconnectCause) -> None: ...
    def setExtras(self, bundle: android.os.Bundle) -> None: ...
    def setInitialized(self) -> None: ...
    def setInitializing(self) -> None: ...
    def setNextPostDialChar(self, char: str) -> None: ...
    def setOnHold(self) -> None: ...
    def setPostDialWait(self, string: str) -> None: ...
    def setPulling(self) -> None: ...
    def setRingbackRequested(self, boolean: bool) -> None: ...
    def setRinging(self) -> None: ...
    def setStatusHints(self, statusHints: StatusHints) -> None: ...
    def setVideoProvider(self, videoProvider: 'Connection.VideoProvider') -> None: ...
    def setVideoState(self, int: int) -> None: ...
    @staticmethod
    def stateToString(int: int) -> str: ...
    class RttModifyStatus:
        SESSION_MODIFY_REQUEST_FAIL: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_INVALID: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_REJECTED_BY_REMOTE: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_SUCCESS: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_TIMED_OUT: typing.ClassVar[int] = ...
    class RttTextStream:
        def read(self) -> str: ...
        def readImmediately(self) -> str: ...
        def write(self, string: str) -> None: ...
    class VideoProvider:
        SESSION_EVENT_CAMERA_FAILURE: typing.ClassVar[int] = ...
        SESSION_EVENT_CAMERA_PERMISSION_ERROR: typing.ClassVar[int] = ...
        SESSION_EVENT_CAMERA_READY: typing.ClassVar[int] = ...
        SESSION_EVENT_RX_PAUSE: typing.ClassVar[int] = ...
        SESSION_EVENT_RX_RESUME: typing.ClassVar[int] = ...
        SESSION_EVENT_TX_START: typing.ClassVar[int] = ...
        SESSION_EVENT_TX_STOP: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_FAIL: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_INVALID: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_REJECTED_BY_REMOTE: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_SUCCESS: typing.ClassVar[int] = ...
        SESSION_MODIFY_REQUEST_TIMED_OUT: typing.ClassVar[int] = ...
        def __init__(self): ...
        def changeCameraCapabilities(self, cameraCapabilities: VideoProfile.CameraCapabilities) -> None: ...
        def changePeerDimensions(self, int: int, int2: int) -> None: ...
        def changeVideoQuality(self, int: int) -> None: ...
        def handleCallSessionEvent(self, int: int) -> None: ...
        def onRequestCameraCapabilities(self) -> None: ...
        def onRequestConnectionDataUsage(self) -> None: ...
        def onSendSessionModifyRequest(self, videoProfile: VideoProfile, videoProfile2: VideoProfile) -> None: ...
        def onSendSessionModifyResponse(self, videoProfile: VideoProfile) -> None: ...
        def onSetCamera(self, string: str) -> None: ...
        def onSetDeviceOrientation(self, int: int) -> None: ...
        def onSetDisplaySurface(self, surface: android.view.Surface) -> None: ...
        def onSetPauseImage(self, uri: android.net.Uri) -> None: ...
        def onSetPreviewSurface(self, surface: android.view.Surface) -> None: ...
        def onSetZoom(self, float: float) -> None: ...
        def receiveSessionModifyRequest(self, videoProfile: VideoProfile) -> None: ...
        def receiveSessionModifyResponse(self, int: int, videoProfile: VideoProfile, videoProfile2: VideoProfile) -> None: ...
        def setCallDataUsage(self, long: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.telecom")``.

    Call: typing.Type[Call]
    CallAttributes: typing.Type[CallAttributes]
    CallAudioState: typing.Type[CallAudioState]
    CallControl: typing.Type[CallControl]
    CallControlCallback: typing.Type[CallControlCallback]
    CallEndpoint: typing.Type[CallEndpoint]
    CallEndpointException: typing.Type[CallEndpointException]
    CallEventCallback: typing.Type[CallEventCallback]
    CallException: typing.Type[CallException]
    CallRedirectionService: typing.Type[CallRedirectionService]
    CallScreeningService: typing.Type[CallScreeningService]
    Conference: typing.Type[Conference]
    Conferenceable: typing.Type[Conferenceable]
    Connection: typing.Type[Connection]
    ConnectionRequest: typing.Type[ConnectionRequest]
    ConnectionService: typing.Type[ConnectionService]
    DisconnectCause: typing.Type[DisconnectCause]
    GatewayInfo: typing.Type[GatewayInfo]
    InCallService: typing.Type[InCallService]
    PhoneAccount: typing.Type[PhoneAccount]
    PhoneAccountHandle: typing.Type[PhoneAccountHandle]
    PhoneAccountSuggestion: typing.Type[PhoneAccountSuggestion]
    QueryLocationException: typing.Type[QueryLocationException]
    RemoteConference: typing.Type[RemoteConference]
    RemoteConnection: typing.Type[RemoteConnection]
    StatusHints: typing.Type[StatusHints]
    TelecomManager: typing.Type[TelecomManager]
    VideoProfile: typing.Type[VideoProfile]
