
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.res
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.widget
import java.lang
import java.util
import jpype
import typing



class Preference(java.lang.Comparable['Preference']):
    DEFAULT_ORDER: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def compareTo(self, preference: 'Preference') -> int: ...
    def getContext(self) -> android.content.Context: ...
    def getDependency(self) -> str: ...
    def getEditor(self) -> android.content.SharedPreferences.Editor: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getFragment(self) -> str: ...
    def getIcon(self) -> android.graphics.drawable.Drawable: ...
    def getIntent(self) -> android.content.Intent: ...
    def getKey(self) -> str: ...
    def getLayoutResource(self) -> int: ...
    def getOnPreferenceChangeListener(self) -> 'Preference.OnPreferenceChangeListener': ...
    def getOnPreferenceClickListener(self) -> 'Preference.OnPreferenceClickListener': ...
    def getOrder(self) -> int: ...
    def getParent(self) -> 'PreferenceGroup': ...
    def getPersistedStringSet(self, set: java.util.Set[str]) -> java.util.Set[str]: ...
    def getPreferenceDataStore(self) -> 'PreferenceDataStore': ...
    def getPreferenceManager(self) -> 'PreferenceManager': ...
    def getSharedPreferences(self) -> android.content.SharedPreferences: ...
    def getShouldDisableView(self) -> bool: ...
    def getSummary(self) -> java.lang.CharSequence: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def getTitleRes(self) -> int: ...
    def getView(self, view: android.view.View, viewGroup: android.view.ViewGroup) -> android.view.View: ...
    def getWidgetLayoutResource(self) -> int: ...
    def hasKey(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isIconSpaceReserved(self) -> bool: ...
    def isPersistent(self) -> bool: ...
    def isRecycleEnabled(self) -> bool: ...
    def isSelectable(self) -> bool: ...
    def isSingleLineTitle(self) -> bool: ...
    def notifyDependencyChange(self, boolean: bool) -> None: ...
    def onDependencyChanged(self, preference: 'Preference', boolean: bool) -> None: ...
    def onParentChanged(self, preference: 'Preference', boolean: bool) -> None: ...
    def peekExtras(self) -> android.os.Bundle: ...
    def persistStringSet(self, set: java.util.Set[str]) -> bool: ...
    def restoreHierarchyState(self, bundle: android.os.Bundle) -> None: ...
    def saveHierarchyState(self, bundle: android.os.Bundle) -> None: ...
    def setDefaultValue(self, object: typing.Any) -> None: ...
    def setDependency(self, string: str) -> None: ...
    def setEnabled(self, boolean: bool) -> None: ...
    def setFragment(self, string: str) -> None: ...
    @typing.overload
    def setIcon(self, drawable: android.graphics.drawable.Drawable) -> None: ...
    @typing.overload
    def setIcon(self, int: int) -> None: ...
    def setIconSpaceReserved(self, boolean: bool) -> None: ...
    def setIntent(self, intent: android.content.Intent) -> None: ...
    def setKey(self, string: str) -> None: ...
    def setLayoutResource(self, int: int) -> None: ...
    def setOnPreferenceChangeListener(self, onPreferenceChangeListener: typing.Union['Preference.OnPreferenceChangeListener', typing.Callable]) -> None: ...
    def setOnPreferenceClickListener(self, onPreferenceClickListener: typing.Union['Preference.OnPreferenceClickListener', typing.Callable]) -> None: ...
    def setOrder(self, int: int) -> None: ...
    def setPersistent(self, boolean: bool) -> None: ...
    def setPreferenceDataStore(self, preferenceDataStore: 'PreferenceDataStore') -> None: ...
    def setRecycleEnabled(self, boolean: bool) -> None: ...
    def setSelectable(self, boolean: bool) -> None: ...
    def setShouldDisableView(self, boolean: bool) -> None: ...
    def setSingleLineTitle(self, boolean: bool) -> None: ...
    @typing.overload
    def setSummary(self, int: int) -> None: ...
    @typing.overload
    def setSummary(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setTitle(self, int: int) -> None: ...
    @typing.overload
    def setTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setWidgetLayoutResource(self, int: int) -> None: ...
    def shouldCommit(self) -> bool: ...
    def shouldDisableDependents(self) -> bool: ...
    def toString(self) -> str: ...
    class BaseSavedState(android.view.AbsSavedState):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @typing.overload
        def __init__(self, parcel: android.os.Parcel): ...
        @typing.overload
        def __init__(self, parcelable: android.os.Parcelable): ...
    class OnPreferenceChangeListener:
        def onPreferenceChange(self, preference: 'Preference', object: typing.Any) -> bool: ...
    class OnPreferenceClickListener:
        def onPreferenceClick(self, preference: 'Preference') -> bool: ...

class PreferenceDataStore:
    def getBoolean(self, string: str, boolean: bool) -> bool: ...
    def getFloat(self, string: str, float: float) -> float: ...
    def getInt(self, string: str, int: int) -> int: ...
    def getLong(self, string: str, long: int) -> int: ...
    def getString(self, string: str, string2: str) -> str: ...
    def getStringSet(self, string: str, set: java.util.Set[str]) -> java.util.Set[str]: ...
    def putBoolean(self, string: str, boolean: bool) -> None: ...
    def putFloat(self, string: str, float: float) -> None: ...
    def putInt(self, string: str, int: int) -> None: ...
    def putLong(self, string: str, long: int) -> None: ...
    def putString(self, string: str, string2: str) -> None: ...
    def putStringSet(self, string: str, set: java.util.Set[str]) -> None: ...

class PreferenceFragment(android.app.Fragment):
    def __init__(self): ...
    def addPreferencesFromIntent(self, intent: android.content.Intent) -> None: ...
    def addPreferencesFromResource(self, int: int) -> None: ...
    def findPreference(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> Preference: ...
    def getPreferenceManager(self) -> 'PreferenceManager': ...
    def getPreferenceScreen(self) -> 'PreferenceScreen': ...
    def onActivityCreated(self, bundle: android.os.Bundle) -> None: ...
    def onActivityResult(self, int: int, int2: int, intent: android.content.Intent) -> None: ...
    def onCreate(self, bundle: android.os.Bundle) -> None: ...
    def onCreateView(self, layoutInflater: android.view.LayoutInflater, viewGroup: android.view.ViewGroup, bundle: android.os.Bundle) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def onPreferenceTreeClick(self, preferenceScreen: 'PreferenceScreen', preference2: Preference) -> bool: ...
    def onSaveInstanceState(self, bundle: android.os.Bundle) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def onViewCreated(self, view: android.view.View, bundle: android.os.Bundle) -> None: ...
    def setPreferenceScreen(self, preferenceScreen: 'PreferenceScreen') -> None: ...
    class OnPreferenceStartFragmentCallback:
        def onPreferenceStartFragment(self, preferenceFragment: 'PreferenceFragment', preference2: Preference) -> bool: ...

class PreferenceManager:
    KEY_HAS_SET_DEFAULT_VALUES: typing.ClassVar[str] = ...
    METADATA_KEY_PREFERENCES: typing.ClassVar[str] = ...
    def createPreferenceScreen(self, context: android.content.Context) -> 'PreferenceScreen': ...
    def findPreference(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> Preference: ...
    @staticmethod
    def getDefaultSharedPreferences(context: android.content.Context) -> android.content.SharedPreferences: ...
    @staticmethod
    def getDefaultSharedPreferencesName(context: android.content.Context) -> str: ...
    def getPreferenceDataStore(self) -> PreferenceDataStore: ...
    def getSharedPreferences(self) -> android.content.SharedPreferences: ...
    def getSharedPreferencesMode(self) -> int: ...
    def getSharedPreferencesName(self) -> str: ...
    def isStorageDefault(self) -> bool: ...
    def isStorageDeviceProtected(self) -> bool: ...
    @typing.overload
    @staticmethod
    def setDefaultValues(context: android.content.Context, int: int, boolean: bool) -> None: ...
    @typing.overload
    @staticmethod
    def setDefaultValues(context: android.content.Context, string: str, int: int, int2: int, boolean: bool) -> None: ...
    def setPreferenceDataStore(self, preferenceDataStore: PreferenceDataStore) -> None: ...
    def setSharedPreferencesMode(self, int: int) -> None: ...
    def setSharedPreferencesName(self, string: str) -> None: ...
    def setStorageDefault(self) -> None: ...
    def setStorageDeviceProtected(self) -> None: ...
    class OnActivityDestroyListener:
        def onActivityDestroy(self) -> None: ...
    class OnActivityResultListener:
        def onActivityResult(self, int: int, int2: int, intent: android.content.Intent) -> bool: ...
    class OnActivityStopListener:
        def onActivityStop(self) -> None: ...

class DialogPreference(Preference, android.content.DialogInterface.OnClickListener, android.content.DialogInterface.OnDismissListener, PreferenceManager.OnActivityDestroyListener):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def getDialog(self) -> android.app.Dialog: ...
    def getDialogIcon(self) -> android.graphics.drawable.Drawable: ...
    def getDialogLayoutResource(self) -> int: ...
    def getDialogMessage(self) -> java.lang.CharSequence: ...
    def getDialogTitle(self) -> java.lang.CharSequence: ...
    def getNegativeButtonText(self) -> java.lang.CharSequence: ...
    def getPositiveButtonText(self) -> java.lang.CharSequence: ...
    def onActivityDestroy(self) -> None: ...
    def onClick(self, dialogInterface: android.content.DialogInterface, int: int) -> None: ...
    def onDismiss(self, dialogInterface: android.content.DialogInterface) -> None: ...
    @typing.overload
    def setDialogIcon(self, drawable: android.graphics.drawable.Drawable) -> None: ...
    @typing.overload
    def setDialogIcon(self, int: int) -> None: ...
    def setDialogLayoutResource(self, int: int) -> None: ...
    @typing.overload
    def setDialogMessage(self, int: int) -> None: ...
    @typing.overload
    def setDialogMessage(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setDialogTitle(self, int: int) -> None: ...
    @typing.overload
    def setDialogTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setNegativeButtonText(self, int: int) -> None: ...
    @typing.overload
    def setNegativeButtonText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setPositiveButtonText(self, int: int) -> None: ...
    @typing.overload
    def setPositiveButtonText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...

class PreferenceActivity(android.app.ListActivity, PreferenceFragment.OnPreferenceStartFragmentCallback):
    EXTRA_NO_HEADERS: typing.ClassVar[str] = ...
    EXTRA_SHOW_FRAGMENT: typing.ClassVar[str] = ...
    EXTRA_SHOW_FRAGMENT_ARGUMENTS: typing.ClassVar[str] = ...
    EXTRA_SHOW_FRAGMENT_SHORT_TITLE: typing.ClassVar[str] = ...
    EXTRA_SHOW_FRAGMENT_TITLE: typing.ClassVar[str] = ...
    HEADER_ID_UNDEFINED: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addPreferencesFromIntent(self, intent: android.content.Intent) -> None: ...
    def addPreferencesFromResource(self, int: int) -> None: ...
    def findPreference(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> Preference: ...
    def finishPreferencePanel(self, fragment: android.app.Fragment, int: int, intent: android.content.Intent) -> None: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def getPreferenceScreen(self) -> 'PreferenceScreen': ...
    def hasHeaders(self) -> bool: ...
    def invalidateHeaders(self) -> None: ...
    def isMultiPane(self) -> bool: ...
    def loadHeadersFromResource(self, int: int, list: java.util.List['PreferenceActivity.Header']) -> None: ...
    def onBackPressed(self) -> None: ...
    def onBuildHeaders(self, list: java.util.List['PreferenceActivity.Header']) -> None: ...
    def onBuildStartFragmentIntent(self, string: str, bundle: android.os.Bundle, int: int, int2: int) -> android.content.Intent: ...
    def onContentChanged(self) -> None: ...
    def onGetInitialHeader(self) -> 'PreferenceActivity.Header': ...
    def onGetNewHeader(self) -> 'PreferenceActivity.Header': ...
    def onHeaderClick(self, header: 'PreferenceActivity.Header', int: int) -> None: ...
    def onIsHidingHeaders(self) -> bool: ...
    def onIsMultiPane(self) -> bool: ...
    def onOptionsItemSelected(self, menuItem: android.view.MenuItem) -> bool: ...
    def onPreferenceStartFragment(self, preferenceFragment: PreferenceFragment, preference2: Preference) -> bool: ...
    def onPreferenceTreeClick(self, preferenceScreen: 'PreferenceScreen', preference2: Preference) -> bool: ...
    def setListFooter(self, view: android.view.View) -> None: ...
    def setParentTitle(self, charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], onClickListener: typing.Union[android.view.View.OnClickListener, typing.Callable]) -> None: ...
    def setPreferenceScreen(self, preferenceScreen: 'PreferenceScreen') -> None: ...
    def showBreadCrumbs(self, charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def startPreferenceFragment(self, fragment: android.app.Fragment, boolean: bool) -> None: ...
    def startPreferencePanel(self, string: str, bundle: android.os.Bundle, int: int, charSequence: typing.Union[java.lang.CharSequence, str], fragment: android.app.Fragment, int2: int) -> None: ...
    @typing.overload
    def startWithFragment(self, string: str, bundle: android.os.Bundle, fragment: android.app.Fragment, int: int) -> None: ...
    @typing.overload
    def startWithFragment(self, string: str, bundle: android.os.Bundle, fragment: android.app.Fragment, int: int, int2: int, int3: int) -> None: ...
    @typing.overload
    def switchToHeader(self, header: 'PreferenceActivity.Header') -> None: ...
    @typing.overload
    def switchToHeader(self, string: str, bundle: android.os.Bundle) -> None: ...
    class Header(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        breadCrumbShortTitle: java.lang.CharSequence = ...
        breadCrumbShortTitleRes: int = ...
        breadCrumbTitle: java.lang.CharSequence = ...
        breadCrumbTitleRes: int = ...
        extras: android.os.Bundle = ...
        fragment: str = ...
        fragmentArguments: android.os.Bundle = ...
        iconRes: int = ...
        id: int = ...
        intent: android.content.Intent = ...
        summary: java.lang.CharSequence = ...
        summaryRes: int = ...
        title: java.lang.CharSequence = ...
        titleRes: int = ...
        def __init__(self): ...
        def describeContents(self) -> int: ...
        def getBreadCrumbShortTitle(self, resources: android.content.res.Resources) -> java.lang.CharSequence: ...
        def getBreadCrumbTitle(self, resources: android.content.res.Resources) -> java.lang.CharSequence: ...
        def getSummary(self, resources: android.content.res.Resources) -> java.lang.CharSequence: ...
        def getTitle(self, resources: android.content.res.Resources) -> java.lang.CharSequence: ...
        def readFromParcel(self, parcel: android.os.Parcel) -> None: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PreferenceGroup(Preference):
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def addItemFromInflater(self, preference: Preference) -> None: ...
    def addPreference(self, preference: Preference) -> bool: ...
    def findPreference(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> Preference: ...
    def getPreference(self, int: int) -> Preference: ...
    def getPreferenceCount(self) -> int: ...
    def isOrderingAsAdded(self) -> bool: ...
    def notifyDependencyChange(self, boolean: bool) -> None: ...
    def removeAll(self) -> None: ...
    def removePreference(self, preference: Preference) -> bool: ...
    def setOrderingAsAdded(self, boolean: bool) -> None: ...

class RingtonePreference(Preference, PreferenceManager.OnActivityResultListener):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def getRingtoneType(self) -> int: ...
    def getShowDefault(self) -> bool: ...
    def getShowSilent(self) -> bool: ...
    def onActivityResult(self, int: int, int2: int, intent: android.content.Intent) -> bool: ...
    def setRingtoneType(self, int: int) -> None: ...
    def setShowDefault(self, boolean: bool) -> None: ...
    def setShowSilent(self, boolean: bool) -> None: ...

class TwoStatePreference(Preference):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def getDisableDependentsState(self) -> bool: ...
    def getSummaryOff(self) -> java.lang.CharSequence: ...
    def getSummaryOn(self) -> java.lang.CharSequence: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, boolean: bool) -> None: ...
    def setDisableDependentsState(self, boolean: bool) -> None: ...
    @typing.overload
    def setSummaryOff(self, int: int) -> None: ...
    @typing.overload
    def setSummaryOff(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setSummaryOn(self, int: int) -> None: ...
    @typing.overload
    def setSummaryOn(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def shouldDisableDependents(self) -> bool: ...

class CheckBoxPreference(TwoStatePreference):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...

class EditTextPreference(DialogPreference):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def getEditText(self) -> android.widget.EditText: ...
    def getText(self) -> str: ...
    def setText(self, string: str) -> None: ...
    def shouldDisableDependents(self) -> bool: ...

class ListPreference(DialogPreference):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def findIndexOfValue(self, string: str) -> int: ...
    def getEntries(self) -> typing.MutableSequence[java.lang.CharSequence]: ...
    def getEntry(self) -> java.lang.CharSequence: ...
    def getEntryValues(self) -> typing.MutableSequence[java.lang.CharSequence]: ...
    def getSummary(self) -> java.lang.CharSequence: ...
    def getValue(self) -> str: ...
    @typing.overload
    def setEntries(self, int: int) -> None: ...
    @typing.overload
    def setEntries(self, charSequenceArray: typing.Union[typing.List[java.lang.CharSequence], jpype.JArray]) -> None: ...
    @typing.overload
    def setEntryValues(self, int: int) -> None: ...
    @typing.overload
    def setEntryValues(self, charSequenceArray: typing.Union[typing.List[java.lang.CharSequence], jpype.JArray]) -> None: ...
    @typing.overload
    def setSummary(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setSummary(self, int: int) -> None: ...
    def setValue(self, string: str) -> None: ...
    def setValueIndex(self, int: int) -> None: ...

class MultiSelectListPreference(DialogPreference):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def findIndexOfValue(self, string: str) -> int: ...
    def getEntries(self) -> typing.MutableSequence[java.lang.CharSequence]: ...
    def getEntryValues(self) -> typing.MutableSequence[java.lang.CharSequence]: ...
    def getValues(self) -> java.util.Set[str]: ...
    @typing.overload
    def setEntries(self, int: int) -> None: ...
    @typing.overload
    def setEntries(self, charSequenceArray: typing.Union[typing.List[java.lang.CharSequence], jpype.JArray]) -> None: ...
    @typing.overload
    def setEntryValues(self, int: int) -> None: ...
    @typing.overload
    def setEntryValues(self, charSequenceArray: typing.Union[typing.List[java.lang.CharSequence], jpype.JArray]) -> None: ...
    def setValues(self, set: java.util.Set[str]) -> None: ...

class PreferenceCategory(PreferenceGroup):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def isEnabled(self) -> bool: ...
    def shouldDisableDependents(self) -> bool: ...

class PreferenceScreen(PreferenceGroup, android.widget.AdapterView.OnItemClickListener, android.content.DialogInterface.OnDismissListener):
    def bind(self, listView: android.widget.ListView) -> None: ...
    def getDialog(self) -> android.app.Dialog: ...
    def getRootAdapter(self) -> android.widget.ListAdapter: ...
    def onDismiss(self, dialogInterface: android.content.DialogInterface) -> None: ...
    def onItemClick(self, adapterView: android.widget.AdapterView, view: android.view.View, int: int, long: int) -> None: ...

class SwitchPreference(TwoStatePreference):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int, int2: int): ...
    def getSwitchTextOff(self) -> java.lang.CharSequence: ...
    def getSwitchTextOn(self) -> java.lang.CharSequence: ...
    @typing.overload
    def setSwitchTextOff(self, int: int) -> None: ...
    @typing.overload
    def setSwitchTextOff(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setSwitchTextOn(self, int: int) -> None: ...
    @typing.overload
    def setSwitchTextOn(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.preference")``.

    CheckBoxPreference: typing.Type[CheckBoxPreference]
    DialogPreference: typing.Type[DialogPreference]
    EditTextPreference: typing.Type[EditTextPreference]
    ListPreference: typing.Type[ListPreference]
    MultiSelectListPreference: typing.Type[MultiSelectListPreference]
    Preference: typing.Type[Preference]
    PreferenceActivity: typing.Type[PreferenceActivity]
    PreferenceCategory: typing.Type[PreferenceCategory]
    PreferenceDataStore: typing.Type[PreferenceDataStore]
    PreferenceFragment: typing.Type[PreferenceFragment]
    PreferenceGroup: typing.Type[PreferenceGroup]
    PreferenceManager: typing.Type[PreferenceManager]
    PreferenceScreen: typing.Type[PreferenceScreen]
    RingtonePreference: typing.Type[RingtonePreference]
    SwitchPreference: typing.Type[SwitchPreference]
    TwoStatePreference: typing.Type[TwoStatePreference]
