
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import datetime
import java.lang
import java.security
import java.security.cert
import java.time
import java.util
import jpype
import typing



class AccessControlProfile:
    class Builder:
        def __init__(self, accessControlProfileId: 'AccessControlProfileId'): ...
        def build(self) -> 'AccessControlProfile': ...
        def setReaderCertificate(self, x509Certificate: java.security.cert.X509Certificate) -> 'AccessControlProfile.Builder': ...
        def setUserAuthenticationRequired(self, boolean: bool) -> 'AccessControlProfile.Builder': ...
        def setUserAuthenticationTimeout(self, long: int) -> 'AccessControlProfile.Builder': ...

class AccessControlProfileId:
    def __init__(self, int: int): ...
    def getId(self) -> int: ...

class AuthenticationKeyMetadata:
    def getExpirationDate(self) -> java.time.Instant: ...
    def getUsageCount(self) -> int: ...

class CredentialDataRequest:
    def getDeviceSignedEntriesToRequest(self) -> java.util.Map[str, java.util.Collection[str]]: ...
    def getIssuerSignedEntriesToRequest(self) -> java.util.Map[str, java.util.Collection[str]]: ...
    def getReaderSignature(self) -> typing.MutableSequence[int]: ...
    def getRequestMessage(self) -> typing.MutableSequence[int]: ...
    def isAllowUsingExhaustedKeys(self) -> bool: ...
    def isAllowUsingExpiredKeys(self) -> bool: ...
    def isIncrementUseCount(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'CredentialDataRequest': ...
        def setAllowUsingExhaustedKeys(self, boolean: bool) -> 'CredentialDataRequest.Builder': ...
        def setAllowUsingExpiredKeys(self, boolean: bool) -> 'CredentialDataRequest.Builder': ...
        def setDeviceSignedEntriesToRequest(self, map: typing.Union[java.util.Map[str, typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]], typing.Mapping[str, typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]]]) -> 'CredentialDataRequest.Builder': ...
        def setIncrementUseCount(self, boolean: bool) -> 'CredentialDataRequest.Builder': ...
        def setIssuerSignedEntriesToRequest(self, map: typing.Union[java.util.Map[str, typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]], typing.Mapping[str, typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]]]) -> 'CredentialDataRequest.Builder': ...
        def setReaderSignature(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'CredentialDataRequest.Builder': ...
        def setRequestMessage(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'CredentialDataRequest.Builder': ...

class CredentialDataResult:
    def getDeviceMac(self) -> typing.MutableSequence[int]: ...
    def getDeviceNameSpaces(self) -> typing.MutableSequence[int]: ...
    def getDeviceSignature(self) -> typing.MutableSequence[int]: ...
    def getDeviceSignedEntries(self) -> 'CredentialDataResult.Entries': ...
    def getIssuerSignedEntries(self) -> 'CredentialDataResult.Entries': ...
    def getStaticAuthenticationData(self) -> typing.MutableSequence[int]: ...
    class Entries:
        STATUS_NOT_IN_REQUEST_MESSAGE: typing.ClassVar[int] = ...
        STATUS_NOT_REQUESTED: typing.ClassVar[int] = ...
        STATUS_NO_ACCESS_CONTROL_PROFILES: typing.ClassVar[int] = ...
        STATUS_NO_SUCH_ENTRY: typing.ClassVar[int] = ...
        STATUS_OK: typing.ClassVar[int] = ...
        STATUS_READER_AUTHENTICATION_FAILED: typing.ClassVar[int] = ...
        STATUS_USER_AUTHENTICATION_FAILED: typing.ClassVar[int] = ...
        def getEntry(self, string: str, string2: str) -> typing.MutableSequence[int]: ...
        def getEntryNames(self, string: str) -> java.util.Collection[str]: ...
        def getNamespaces(self) -> java.util.Collection[str]: ...
        def getRetrievedEntryNames(self, string: str) -> java.util.Collection[str]: ...
        def getStatus(self, string: str, string2: str) -> int: ...

class IdentityCredential:
    def createEphemeralKeyPair(self) -> java.security.KeyPair: ...
    def decryptMessageFromReader(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def delete(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def encryptMessageToReader(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def getAuthKeysNeedingCertification(self) -> java.util.Collection[java.security.cert.X509Certificate]: ...
    def getAuthenticationDataUsageCount(self) -> typing.MutableSequence[int]: ...
    def getAuthenticationKeyMetadata(self) -> java.util.List[AuthenticationKeyMetadata]: ...
    def getCredentialKeyCertificateChain(self) -> java.util.Collection[java.security.cert.X509Certificate]: ...
    def getEntries(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], map: typing.Union[java.util.Map[str, typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]], typing.Mapping[str, typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]]], byteArray2: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray3: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ResultData': ...
    def proveOwnership(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def setAllowUsingExhaustedKeys(self, boolean: bool) -> None: ...
    def setAllowUsingExpiredKeys(self, boolean: bool) -> None: ...
    @typing.overload
    def setAvailableAuthenticationKeys(self, int: int, int2: int) -> None: ...
    @typing.overload
    def setAvailableAuthenticationKeys(self, int: int, int2: int, long: int) -> None: ...
    def setReaderEphemeralPublicKey(self, publicKey: java.security.PublicKey) -> None: ...
    @typing.overload
    def storeStaticAuthenticationData(self, x509Certificate: java.security.cert.X509Certificate, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def storeStaticAuthenticationData(self, x509Certificate: java.security.cert.X509Certificate, instant: typing.Union[java.time.Instant, datetime.datetime], byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def update(self, personalizationData: 'PersonalizationData') -> typing.MutableSequence[int]: ...

class IdentityCredentialException(java.lang.Exception):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class IdentityCredentialStore:
    CIPHERSUITE_ECDHE_HKDF_ECDSA_WITH_AES_256_GCM_SHA256: typing.ClassVar[int] = ...
    def createCredential(self, string: str, string2: str) -> 'WritableIdentityCredential': ...
    def createPresentationSession(self, int: int) -> 'PresentationSession': ...
    def deleteCredentialByName(self, string: str) -> typing.MutableSequence[int]: ...
    def getCredentialByName(self, string: str, int: int) -> IdentityCredential: ...
    @staticmethod
    def getDirectAccessInstance(context: android.content.Context) -> 'IdentityCredentialStore': ...
    @staticmethod
    def getInstance(context: android.content.Context) -> 'IdentityCredentialStore': ...
    def getSupportedDocTypes(self) -> typing.MutableSequence[str]: ...

class PersonalizationData:
    class Builder:
        def __init__(self): ...
        def addAccessControlProfile(self, accessControlProfile: AccessControlProfile) -> 'PersonalizationData.Builder': ...
        def build(self) -> 'PersonalizationData': ...
        def putEntry(self, string: str, string2: str, collection: typing.Union[java.util.Collection[AccessControlProfileId], typing.Sequence[AccessControlProfileId], typing.Set[AccessControlProfileId]], byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'PersonalizationData.Builder': ...

class PresentationSession:
    def getCredentialData(self, string: str, credentialDataRequest: CredentialDataRequest) -> CredentialDataResult: ...
    def getEphemeralKeyPair(self) -> java.security.KeyPair: ...
    def setReaderEphemeralPublicKey(self, publicKey: java.security.PublicKey) -> None: ...
    def setSessionTranscript(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class ResultData:
    STATUS_NOT_IN_REQUEST_MESSAGE: typing.ClassVar[int] = ...
    STATUS_NOT_REQUESTED: typing.ClassVar[int] = ...
    STATUS_NO_ACCESS_CONTROL_PROFILES: typing.ClassVar[int] = ...
    STATUS_NO_SUCH_ENTRY: typing.ClassVar[int] = ...
    STATUS_OK: typing.ClassVar[int] = ...
    STATUS_READER_AUTHENTICATION_FAILED: typing.ClassVar[int] = ...
    STATUS_USER_AUTHENTICATION_FAILED: typing.ClassVar[int] = ...
    def getAuthenticatedData(self) -> typing.MutableSequence[int]: ...
    def getEntry(self, string: str, string2: str) -> typing.MutableSequence[int]: ...
    def getEntryNames(self, string: str) -> java.util.Collection[str]: ...
    def getMessageAuthenticationCode(self) -> typing.MutableSequence[int]: ...
    def getNamespaces(self) -> java.util.Collection[str]: ...
    def getRetrievedEntryNames(self, string: str) -> java.util.Collection[str]: ...
    def getStaticAuthenticationData(self) -> typing.MutableSequence[int]: ...
    def getStatus(self, string: str, string2: str) -> int: ...

class WritableIdentityCredential:
    def getCredentialKeyCertificateChain(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> java.util.Collection[java.security.cert.X509Certificate]: ...
    def personalize(self, personalizationData: PersonalizationData) -> typing.MutableSequence[int]: ...

class AlreadyPersonalizedException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class CipherSuiteNotSupportedException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class DocTypeNotSupportedException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class EphemeralPublicKeyNotFoundException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class InvalidReaderSignatureException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class InvalidRequestMessageException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class MessageDecryptionException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class NoAuthenticationKeyAvailableException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class SessionTranscriptMismatchException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...

class UnknownAuthenticationKeyException(IdentityCredentialException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.security.identity")``.

    AccessControlProfile: typing.Type[AccessControlProfile]
    AccessControlProfileId: typing.Type[AccessControlProfileId]
    AlreadyPersonalizedException: typing.Type[AlreadyPersonalizedException]
    AuthenticationKeyMetadata: typing.Type[AuthenticationKeyMetadata]
    CipherSuiteNotSupportedException: typing.Type[CipherSuiteNotSupportedException]
    CredentialDataRequest: typing.Type[CredentialDataRequest]
    CredentialDataResult: typing.Type[CredentialDataResult]
    DocTypeNotSupportedException: typing.Type[DocTypeNotSupportedException]
    EphemeralPublicKeyNotFoundException: typing.Type[EphemeralPublicKeyNotFoundException]
    IdentityCredential: typing.Type[IdentityCredential]
    IdentityCredentialException: typing.Type[IdentityCredentialException]
    IdentityCredentialStore: typing.Type[IdentityCredentialStore]
    InvalidReaderSignatureException: typing.Type[InvalidReaderSignatureException]
    InvalidRequestMessageException: typing.Type[InvalidRequestMessageException]
    MessageDecryptionException: typing.Type[MessageDecryptionException]
    NoAuthenticationKeyAvailableException: typing.Type[NoAuthenticationKeyAvailableException]
    PersonalizationData: typing.Type[PersonalizationData]
    PresentationSession: typing.Type[PresentationSession]
    ResultData: typing.Type[ResultData]
    SessionTranscriptMismatchException: typing.Type[SessionTranscriptMismatchException]
    UnknownAuthenticationKeyException: typing.Type[UnknownAuthenticationKeyException]
    WritableIdentityCredential: typing.Type[WritableIdentityCredential]
