
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.graphics
import android.text
import android.view
import android.widget
import java.lang
import java.util
import typing



class CharacterPickerDialog(android.app.Dialog, android.widget.AdapterView.OnItemClickListener, android.view.View.OnClickListener):
    def __init__(self, context: android.content.Context, view: android.view.View, editable: android.text.Editable, string: str, boolean: bool): ...
    def onClick(self, view: android.view.View) -> None: ...
    def onItemClick(self, adapterView: android.widget.AdapterView, view: android.view.View, int: int, long: int) -> None: ...

class KeyListener:
    def clearMetaKeyState(self, view: android.view.View, editable: android.text.Editable, int: int) -> None: ...
    def getInputType(self) -> int: ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyOther(self, view: android.view.View, editable: android.text.Editable, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...

class MetaKeyKeyListener:
    META_ALT_LOCKED: typing.ClassVar[int] = ...
    META_ALT_ON: typing.ClassVar[int] = ...
    META_CAP_LOCKED: typing.ClassVar[int] = ...
    META_SHIFT_ON: typing.ClassVar[int] = ...
    META_SYM_LOCKED: typing.ClassVar[int] = ...
    META_SYM_ON: typing.ClassVar[int] = ...
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def adjustMetaAfterKeypress(long: int) -> int: ...
    @typing.overload
    @staticmethod
    def adjustMetaAfterKeypress(spannable: android.text.Spannable) -> None: ...
    @typing.overload
    def clearMetaKeyState(self, long: int, int: int) -> int: ...
    @typing.overload
    @staticmethod
    def clearMetaKeyState(editable: android.text.Editable, int: int) -> None: ...
    @typing.overload
    def clearMetaKeyState(self, view: android.view.View, editable: android.text.Editable, int: int) -> None: ...
    @typing.overload
    @staticmethod
    def getMetaState(charSequence: typing.Union[java.lang.CharSequence, str]) -> int: ...
    @typing.overload
    @staticmethod
    def getMetaState(charSequence: typing.Union[java.lang.CharSequence, str], keyEvent: android.view.KeyEvent) -> int: ...
    @typing.overload
    @staticmethod
    def getMetaState(charSequence: typing.Union[java.lang.CharSequence, str], int: int) -> int: ...
    @typing.overload
    @staticmethod
    def getMetaState(charSequence: typing.Union[java.lang.CharSequence, str], int: int, keyEvent: android.view.KeyEvent) -> int: ...
    @typing.overload
    @staticmethod
    def getMetaState(long: int) -> int: ...
    @typing.overload
    @staticmethod
    def getMetaState(long: int, int: int) -> int: ...
    @staticmethod
    def handleKeyDown(long: int, int: int, keyEvent: android.view.KeyEvent) -> int: ...
    @staticmethod
    def handleKeyUp(long: int, int: int, keyEvent: android.view.KeyEvent) -> int: ...
    @staticmethod
    def isMetaTracker(charSequence: typing.Union[java.lang.CharSequence, str], object: typing.Any) -> bool: ...
    @staticmethod
    def isSelectingMetaTracker(charSequence: typing.Union[java.lang.CharSequence, str], object: typing.Any) -> bool: ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    @staticmethod
    def resetLockedMeta(long: int) -> int: ...
    @staticmethod
    def resetMetaState(spannable: android.text.Spannable) -> None: ...

class MovementMethod:
    def canSelectArbitrarily(self) -> bool: ...
    def initialize(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> None: ...
    def onGenericMotionEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    def onKeyDown(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyOther(self, textView: android.widget.TextView, spannable: android.text.Spannable, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onTakeFocus(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int) -> None: ...
    def onTouchEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    def onTrackballEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...

class Touch:
    @staticmethod
    def getInitialScrollX(textView: android.widget.TextView, spannable: android.text.Spannable) -> int: ...
    @staticmethod
    def getInitialScrollY(textView: android.widget.TextView, spannable: android.text.Spannable) -> int: ...
    @staticmethod
    def onTouchEvent(textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    @staticmethod
    def scrollTo(textView: android.widget.TextView, layout: android.text.Layout, int: int, int2: int) -> None: ...

class TransformationMethod:
    def getTransformation(self, charSequence: typing.Union[java.lang.CharSequence, str], view: android.view.View) -> java.lang.CharSequence: ...
    def onFocusChanged(self, view: android.view.View, charSequence: typing.Union[java.lang.CharSequence, str], boolean: bool, int: int, rect: android.graphics.Rect) -> None: ...

class BaseKeyListener(MetaKeyKeyListener, KeyListener):
    def __init__(self): ...
    def backspace(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def forwardDelete(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyOther(self, view: android.view.View, editable: android.text.Editable, keyEvent: android.view.KeyEvent) -> bool: ...

class BaseMovementMethod(MovementMethod):
    def __init__(self): ...
    def canSelectArbitrarily(self) -> bool: ...
    def initialize(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> None: ...
    def nextParagraph(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> bool: ...
    def onGenericMotionEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    def onKeyDown(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyOther(self, textView: android.widget.TextView, spannable: android.text.Spannable, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onTakeFocus(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int) -> None: ...
    def onTouchEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    def onTrackballEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    def previousParagraph(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> bool: ...

class PasswordTransformationMethod(TransformationMethod, android.text.TextWatcher):
    def __init__(self): ...
    def afterTextChanged(self, editable: android.text.Editable) -> None: ...
    def beforeTextChanged(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int) -> None: ...
    @staticmethod
    def getInstance() -> 'PasswordTransformationMethod': ...
    def getTransformation(self, charSequence: typing.Union[java.lang.CharSequence, str], view: android.view.View) -> java.lang.CharSequence: ...
    def onFocusChanged(self, view: android.view.View, charSequence: typing.Union[java.lang.CharSequence, str], boolean: bool, int: int, rect: android.graphics.Rect) -> None: ...
    def onTextChanged(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int) -> None: ...

class ReplacementTransformationMethod(TransformationMethod):
    def __init__(self): ...
    def getTransformation(self, charSequence: typing.Union[java.lang.CharSequence, str], view: android.view.View) -> java.lang.CharSequence: ...
    def onFocusChanged(self, view: android.view.View, charSequence: typing.Union[java.lang.CharSequence, str], boolean: bool, int: int, rect: android.graphics.Rect) -> None: ...

class ArrowKeyMovementMethod(BaseMovementMethod, MovementMethod):
    def __init__(self): ...
    def canSelectArbitrarily(self) -> bool: ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
    def initialize(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> None: ...
    def nextParagraph(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> bool: ...
    def onTakeFocus(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int) -> None: ...
    def onTouchEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...
    def previousParagraph(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> bool: ...

class HideReturnsTransformationMethod(ReplacementTransformationMethod):
    def __init__(self): ...
    @staticmethod
    def getInstance() -> 'HideReturnsTransformationMethod': ...

class MultiTapKeyListener(BaseKeyListener, android.text.SpanWatcher):
    def __init__(self, capitalize: 'TextKeyListener.Capitalize', boolean: bool): ...
    def getInputType(self) -> int: ...
    @staticmethod
    def getInstance(boolean: bool, capitalize: 'TextKeyListener.Capitalize') -> 'MultiTapKeyListener': ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onSpanAdded(self, spannable: android.text.Spannable, object: typing.Any, int: int, int2: int) -> None: ...
    def onSpanChanged(self, spannable: android.text.Spannable, object: typing.Any, int: int, int2: int, int3: int, int4: int) -> None: ...
    def onSpanRemoved(self, spannable: android.text.Spannable, object: typing.Any, int: int, int2: int) -> None: ...

class NumberKeyListener(BaseKeyListener, android.text.InputFilter):
    def __init__(self): ...
    def filter(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, spanned: android.text.Spanned, int3: int, int4: int) -> java.lang.CharSequence: ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...

class QwertyKeyListener(BaseKeyListener):
    def __init__(self, capitalize: 'TextKeyListener.Capitalize', boolean: bool): ...
    def getInputType(self) -> int: ...
    @staticmethod
    def getInstance(boolean: bool, capitalize: 'TextKeyListener.Capitalize') -> 'QwertyKeyListener': ...
    @staticmethod
    def getInstanceForFullKeyboard() -> 'QwertyKeyListener': ...
    @staticmethod
    def markAsReplaced(spannable: android.text.Spannable, int: int, int2: int, string: str) -> None: ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...

class ScrollingMovementMethod(BaseMovementMethod, MovementMethod):
    def __init__(self): ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
    def onTakeFocus(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int) -> None: ...
    def onTouchEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...

class SingleLineTransformationMethod(ReplacementTransformationMethod):
    def __init__(self): ...
    @staticmethod
    def getInstance() -> 'SingleLineTransformationMethod': ...

class TextKeyListener(BaseKeyListener, android.text.SpanWatcher):
    def __init__(self, capitalize: 'TextKeyListener.Capitalize', boolean: bool): ...
    @staticmethod
    def clear(editable: android.text.Editable) -> None: ...
    def getInputType(self) -> int: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'TextKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(boolean: bool, capitalize: 'TextKeyListener.Capitalize') -> 'TextKeyListener': ...
    def onKeyDown(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyOther(self, view: android.view.View, editable: android.text.Editable, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, view: android.view.View, editable: android.text.Editable, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onSpanAdded(self, spannable: android.text.Spannable, object: typing.Any, int: int, int2: int) -> None: ...
    def onSpanChanged(self, spannable: android.text.Spannable, object: typing.Any, int: int, int2: int, int3: int, int4: int) -> None: ...
    def onSpanRemoved(self, spannable: android.text.Spannable, object: typing.Any, int: int, int2: int) -> None: ...
    def release(self) -> None: ...
    @staticmethod
    def shouldCap(capitalize: 'TextKeyListener.Capitalize', charSequence: typing.Union[java.lang.CharSequence, str], int: int) -> bool: ...
    class Capitalize(java.lang.Enum['TextKeyListener.Capitalize']):
        NONE: typing.ClassVar['TextKeyListener.Capitalize'] = ...
        SENTENCES: typing.ClassVar['TextKeyListener.Capitalize'] = ...
        WORDS: typing.ClassVar['TextKeyListener.Capitalize'] = ...
        CHARACTERS: typing.ClassVar['TextKeyListener.Capitalize'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'TextKeyListener.Capitalize': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['TextKeyListener.Capitalize']: ...

class DateKeyListener(NumberKeyListener):
    CHARACTERS: typing.ClassVar[typing.MutableSequence[str]] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getInputType(self) -> int: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'DateKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'DateKeyListener': ...

class DateTimeKeyListener(NumberKeyListener):
    CHARACTERS: typing.ClassVar[typing.MutableSequence[str]] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getInputType(self) -> int: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'DateTimeKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'DateTimeKeyListener': ...

class DialerKeyListener(NumberKeyListener):
    CHARACTERS: typing.ClassVar[typing.MutableSequence[str]] = ...
    def __init__(self): ...
    def getInputType(self) -> int: ...
    @staticmethod
    def getInstance() -> 'DialerKeyListener': ...

class DigitsKeyListener(NumberKeyListener):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, boolean: bool, boolean2: bool): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale, boolean: bool, boolean2: bool): ...
    def filter(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, spanned: android.text.Spanned, int3: int, int4: int) -> java.lang.CharSequence: ...
    def getInputType(self) -> int: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'DigitsKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(boolean: bool, boolean2: bool) -> 'DigitsKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(string: str) -> 'DigitsKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'DigitsKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale, boolean: bool, boolean2: bool) -> 'DigitsKeyListener': ...

class LinkMovementMethod(ScrollingMovementMethod):
    def __init__(self): ...
    def canSelectArbitrarily(self) -> bool: ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
    def initialize(self, textView: android.widget.TextView, spannable: android.text.Spannable) -> None: ...
    def onTakeFocus(self, textView: android.widget.TextView, spannable: android.text.Spannable, int: int) -> None: ...
    def onTouchEvent(self, textView: android.widget.TextView, spannable: android.text.Spannable, motionEvent: android.view.MotionEvent) -> bool: ...

class TimeKeyListener(NumberKeyListener):
    CHARACTERS: typing.ClassVar[typing.MutableSequence[str]] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def getInputType(self) -> int: ...
    @typing.overload
    @staticmethod
    def getInstance() -> 'TimeKeyListener': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'TimeKeyListener': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.text.method")``.

    ArrowKeyMovementMethod: typing.Type[ArrowKeyMovementMethod]
    BaseKeyListener: typing.Type[BaseKeyListener]
    BaseMovementMethod: typing.Type[BaseMovementMethod]
    CharacterPickerDialog: typing.Type[CharacterPickerDialog]
    DateKeyListener: typing.Type[DateKeyListener]
    DateTimeKeyListener: typing.Type[DateTimeKeyListener]
    DialerKeyListener: typing.Type[DialerKeyListener]
    DigitsKeyListener: typing.Type[DigitsKeyListener]
    HideReturnsTransformationMethod: typing.Type[HideReturnsTransformationMethod]
    KeyListener: typing.Type[KeyListener]
    LinkMovementMethod: typing.Type[LinkMovementMethod]
    MetaKeyKeyListener: typing.Type[MetaKeyKeyListener]
    MovementMethod: typing.Type[MovementMethod]
    MultiTapKeyListener: typing.Type[MultiTapKeyListener]
    NumberKeyListener: typing.Type[NumberKeyListener]
    PasswordTransformationMethod: typing.Type[PasswordTransformationMethod]
    QwertyKeyListener: typing.Type[QwertyKeyListener]
    ReplacementTransformationMethod: typing.Type[ReplacementTransformationMethod]
    ScrollingMovementMethod: typing.Type[ScrollingMovementMethod]
    SingleLineTransformationMethod: typing.Type[SingleLineTransformationMethod]
    TextKeyListener: typing.Type[TextKeyListener]
    TimeKeyListener: typing.Type[TimeKeyListener]
    Touch: typing.Type[Touch]
    TransformationMethod: typing.Type[TransformationMethod]
