
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.bluetooth
import android.os
import android.util
import java.util
import jpype
import typing



class AdvertiseCallback:
    ADVERTISE_FAILED_ALREADY_STARTED: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_DATA_TOO_LARGE: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_FEATURE_UNSUPPORTED: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_INTERNAL_ERROR: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_TOO_MANY_ADVERTISERS: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onStartFailure(self, int: int) -> None: ...
    def onStartSuccess(self, advertiseSettings: 'AdvertiseSettings') -> None: ...

class AdvertiseData(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getIncludeDeviceName(self) -> bool: ...
    def getIncludeTxPowerLevel(self) -> bool: ...
    def getManufacturerSpecificData(self) -> android.util.SparseArray[typing.MutableSequence[int]]: ...
    def getServiceData(self) -> java.util.Map[android.os.ParcelUuid, typing.MutableSequence[int]]: ...
    def getServiceSolicitationUuids(self) -> java.util.List[android.os.ParcelUuid]: ...
    def getServiceUuids(self) -> java.util.List[android.os.ParcelUuid]: ...
    def getTransportDiscoveryData(self) -> java.util.List['TransportDiscoveryData']: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addManufacturerData(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'AdvertiseData.Builder': ...
        def addServiceData(self, parcelUuid: android.os.ParcelUuid, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'AdvertiseData.Builder': ...
        def addServiceSolicitationUuid(self, parcelUuid: android.os.ParcelUuid) -> 'AdvertiseData.Builder': ...
        def addServiceUuid(self, parcelUuid: android.os.ParcelUuid) -> 'AdvertiseData.Builder': ...
        def addTransportDiscoveryData(self, transportDiscoveryData: 'TransportDiscoveryData') -> 'AdvertiseData.Builder': ...
        def build(self) -> 'AdvertiseData': ...
        def setIncludeDeviceName(self, boolean: bool) -> 'AdvertiseData.Builder': ...
        def setIncludeTxPowerLevel(self, boolean: bool) -> 'AdvertiseData.Builder': ...

class AdvertiseSettings(android.os.Parcelable):
    ADVERTISE_MODE_BALANCED: typing.ClassVar[int] = ...
    ADVERTISE_MODE_LOW_LATENCY: typing.ClassVar[int] = ...
    ADVERTISE_MODE_LOW_POWER: typing.ClassVar[int] = ...
    ADVERTISE_TX_POWER_HIGH: typing.ClassVar[int] = ...
    ADVERTISE_TX_POWER_LOW: typing.ClassVar[int] = ...
    ADVERTISE_TX_POWER_MEDIUM: typing.ClassVar[int] = ...
    ADVERTISE_TX_POWER_ULTRA_LOW: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getMode(self) -> int: ...
    def getTimeout(self) -> int: ...
    def getTxPowerLevel(self) -> int: ...
    def isConnectable(self) -> bool: ...
    def isDiscoverable(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdvertiseSettings': ...
        def setAdvertiseMode(self, int: int) -> 'AdvertiseSettings.Builder': ...
        def setConnectable(self, boolean: bool) -> 'AdvertiseSettings.Builder': ...
        def setDiscoverable(self, boolean: bool) -> 'AdvertiseSettings.Builder': ...
        def setTimeout(self, int: int) -> 'AdvertiseSettings.Builder': ...
        def setTxPowerLevel(self, int: int) -> 'AdvertiseSettings.Builder': ...

class AdvertisingSet:
    def enableAdvertising(self, boolean: bool, int: int, int2: int) -> None: ...
    def setAdvertisingData(self, advertiseData: AdvertiseData) -> None: ...
    def setAdvertisingParameters(self, advertisingSetParameters: 'AdvertisingSetParameters') -> None: ...
    def setPeriodicAdvertisingData(self, advertiseData: AdvertiseData) -> None: ...
    def setPeriodicAdvertisingEnabled(self, boolean: bool) -> None: ...
    def setPeriodicAdvertisingParameters(self, periodicAdvertisingParameters: 'PeriodicAdvertisingParameters') -> None: ...
    def setScanResponseData(self, advertiseData: AdvertiseData) -> None: ...

class AdvertisingSetCallback:
    ADVERTISE_FAILED_ALREADY_STARTED: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_DATA_TOO_LARGE: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_FEATURE_UNSUPPORTED: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_INTERNAL_ERROR: typing.ClassVar[int] = ...
    ADVERTISE_FAILED_TOO_MANY_ADVERTISERS: typing.ClassVar[int] = ...
    ADVERTISE_SUCCESS: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onAdvertisingDataSet(self, advertisingSet: AdvertisingSet, int: int) -> None: ...
    def onAdvertisingEnabled(self, advertisingSet: AdvertisingSet, boolean: bool, int: int) -> None: ...
    def onAdvertisingParametersUpdated(self, advertisingSet: AdvertisingSet, int: int, int2: int) -> None: ...
    def onAdvertisingSetStarted(self, advertisingSet: AdvertisingSet, int: int, int2: int) -> None: ...
    def onAdvertisingSetStopped(self, advertisingSet: AdvertisingSet) -> None: ...
    def onPeriodicAdvertisingDataSet(self, advertisingSet: AdvertisingSet, int: int) -> None: ...
    def onPeriodicAdvertisingEnabled(self, advertisingSet: AdvertisingSet, boolean: bool, int: int) -> None: ...
    def onPeriodicAdvertisingParametersUpdated(self, advertisingSet: AdvertisingSet, int: int) -> None: ...
    def onScanResponseDataSet(self, advertisingSet: AdvertisingSet, int: int) -> None: ...

class AdvertisingSetParameters(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    INTERVAL_HIGH: typing.ClassVar[int] = ...
    INTERVAL_LOW: typing.ClassVar[int] = ...
    INTERVAL_MAX: typing.ClassVar[int] = ...
    INTERVAL_MEDIUM: typing.ClassVar[int] = ...
    INTERVAL_MIN: typing.ClassVar[int] = ...
    TX_POWER_HIGH: typing.ClassVar[int] = ...
    TX_POWER_LOW: typing.ClassVar[int] = ...
    TX_POWER_MAX: typing.ClassVar[int] = ...
    TX_POWER_MEDIUM: typing.ClassVar[int] = ...
    TX_POWER_MIN: typing.ClassVar[int] = ...
    TX_POWER_ULTRA_LOW: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getInterval(self) -> int: ...
    def getPrimaryPhy(self) -> int: ...
    def getSecondaryPhy(self) -> int: ...
    def getTxPowerLevel(self) -> int: ...
    def includeTxPower(self) -> bool: ...
    def isAnonymous(self) -> bool: ...
    def isConnectable(self) -> bool: ...
    def isDiscoverable(self) -> bool: ...
    def isLegacy(self) -> bool: ...
    def isScannable(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdvertisingSetParameters': ...
        def setAnonymous(self, boolean: bool) -> 'AdvertisingSetParameters.Builder': ...
        def setConnectable(self, boolean: bool) -> 'AdvertisingSetParameters.Builder': ...
        def setDiscoverable(self, boolean: bool) -> 'AdvertisingSetParameters.Builder': ...
        def setIncludeTxPower(self, boolean: bool) -> 'AdvertisingSetParameters.Builder': ...
        def setInterval(self, int: int) -> 'AdvertisingSetParameters.Builder': ...
        def setLegacyMode(self, boolean: bool) -> 'AdvertisingSetParameters.Builder': ...
        def setPrimaryPhy(self, int: int) -> 'AdvertisingSetParameters.Builder': ...
        def setScannable(self, boolean: bool) -> 'AdvertisingSetParameters.Builder': ...
        def setSecondaryPhy(self, int: int) -> 'AdvertisingSetParameters.Builder': ...
        def setTxPowerLevel(self, int: int) -> 'AdvertisingSetParameters.Builder': ...

class BluetoothLeAdvertiser:
    @typing.overload
    def startAdvertising(self, advertiseSettings: AdvertiseSettings, advertiseData: AdvertiseData, advertiseCallback: AdvertiseCallback) -> None: ...
    @typing.overload
    def startAdvertising(self, advertiseSettings: AdvertiseSettings, advertiseData: AdvertiseData, advertiseData2: AdvertiseData, advertiseCallback: AdvertiseCallback) -> None: ...
    @typing.overload
    def startAdvertisingSet(self, advertisingSetParameters: AdvertisingSetParameters, advertiseData: AdvertiseData, advertiseData2: AdvertiseData, periodicAdvertisingParameters: 'PeriodicAdvertisingParameters', advertiseData3: AdvertiseData, advertisingSetCallback: AdvertisingSetCallback) -> None: ...
    @typing.overload
    def startAdvertisingSet(self, advertisingSetParameters: AdvertisingSetParameters, advertiseData: AdvertiseData, advertiseData2: AdvertiseData, periodicAdvertisingParameters: 'PeriodicAdvertisingParameters', advertiseData3: AdvertiseData, advertisingSetCallback: AdvertisingSetCallback, handler: android.os.Handler) -> None: ...
    @typing.overload
    def startAdvertisingSet(self, advertisingSetParameters: AdvertisingSetParameters, advertiseData: AdvertiseData, advertiseData2: AdvertiseData, periodicAdvertisingParameters: 'PeriodicAdvertisingParameters', advertiseData3: AdvertiseData, int: int, int2: int, advertisingSetCallback: AdvertisingSetCallback) -> None: ...
    @typing.overload
    def startAdvertisingSet(self, advertisingSetParameters: AdvertisingSetParameters, advertiseData: AdvertiseData, advertiseData2: AdvertiseData, periodicAdvertisingParameters: 'PeriodicAdvertisingParameters', advertiseData3: AdvertiseData, int: int, int2: int, advertisingSetCallback: AdvertisingSetCallback, handler: android.os.Handler) -> None: ...
    def stopAdvertising(self, advertiseCallback: AdvertiseCallback) -> None: ...
    def stopAdvertisingSet(self, advertisingSetCallback: AdvertisingSetCallback) -> None: ...

class BluetoothLeScanner:
    EXTRA_CALLBACK_TYPE: typing.ClassVar[str] = ...
    EXTRA_ERROR_CODE: typing.ClassVar[str] = ...
    EXTRA_LIST_SCAN_RESULT: typing.ClassVar[str] = ...
    def flushPendingScanResults(self, scanCallback: 'ScanCallback') -> None: ...
    @typing.overload
    def startScan(self, list: java.util.List['ScanFilter'], scanSettings: 'ScanSettings', pendingIntent: android.app.PendingIntent) -> int: ...
    @typing.overload
    def startScan(self, scanCallback: 'ScanCallback') -> None: ...
    @typing.overload
    def startScan(self, list: java.util.List['ScanFilter'], scanSettings: 'ScanSettings', scanCallback: 'ScanCallback') -> None: ...
    @typing.overload
    def stopScan(self, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def stopScan(self, scanCallback: 'ScanCallback') -> None: ...

class PeriodicAdvertisingParameters(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getIncludeTxPower(self) -> bool: ...
    def getInterval(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'PeriodicAdvertisingParameters': ...
        def setIncludeTxPower(self, boolean: bool) -> 'PeriodicAdvertisingParameters.Builder': ...
        def setInterval(self, int: int) -> 'PeriodicAdvertisingParameters.Builder': ...

class ScanCallback:
    SCAN_FAILED_ALREADY_STARTED: typing.ClassVar[int] = ...
    SCAN_FAILED_APPLICATION_REGISTRATION_FAILED: typing.ClassVar[int] = ...
    SCAN_FAILED_FEATURE_UNSUPPORTED: typing.ClassVar[int] = ...
    SCAN_FAILED_INTERNAL_ERROR: typing.ClassVar[int] = ...
    SCAN_FAILED_OUT_OF_HARDWARE_RESOURCES: typing.ClassVar[int] = ...
    SCAN_FAILED_SCANNING_TOO_FREQUENTLY: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onBatchScanResults(self, list: java.util.List['ScanResult']) -> None: ...
    def onScanFailed(self, int: int) -> None: ...
    def onScanResult(self, int: int, scanResult: 'ScanResult') -> None: ...

class ScanFilter(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdvertisingData(self) -> typing.MutableSequence[int]: ...
    def getAdvertisingDataMask(self) -> typing.MutableSequence[int]: ...
    def getAdvertisingDataType(self) -> int: ...
    def getDeviceAddress(self) -> str: ...
    def getDeviceName(self) -> str: ...
    def getManufacturerData(self) -> typing.MutableSequence[int]: ...
    def getManufacturerDataMask(self) -> typing.MutableSequence[int]: ...
    def getManufacturerId(self) -> int: ...
    def getServiceData(self) -> typing.MutableSequence[int]: ...
    def getServiceDataMask(self) -> typing.MutableSequence[int]: ...
    def getServiceDataUuid(self) -> android.os.ParcelUuid: ...
    def getServiceSolicitationUuid(self) -> android.os.ParcelUuid: ...
    def getServiceSolicitationUuidMask(self) -> android.os.ParcelUuid: ...
    def getServiceUuid(self) -> android.os.ParcelUuid: ...
    def getServiceUuidMask(self) -> android.os.ParcelUuid: ...
    def hashCode(self) -> int: ...
    def matches(self, scanResult: 'ScanResult') -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'ScanFilter': ...
        def setAdvertisingDataType(self, int: int) -> 'ScanFilter.Builder': ...
        def setAdvertisingDataTypeWithData(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray2: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ScanFilter.Builder': ...
        def setDeviceAddress(self, string: str) -> 'ScanFilter.Builder': ...
        def setDeviceName(self, string: str) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setManufacturerData(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setManufacturerData(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray2: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setServiceData(self, parcelUuid: android.os.ParcelUuid, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setServiceData(self, parcelUuid: android.os.ParcelUuid, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], byteArray2: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setServiceSolicitationUuid(self, parcelUuid: android.os.ParcelUuid) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setServiceSolicitationUuid(self, parcelUuid: android.os.ParcelUuid, parcelUuid2: android.os.ParcelUuid) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setServiceUuid(self, parcelUuid: android.os.ParcelUuid) -> 'ScanFilter.Builder': ...
        @typing.overload
        def setServiceUuid(self, parcelUuid: android.os.ParcelUuid, parcelUuid2: android.os.ParcelUuid) -> 'ScanFilter.Builder': ...

class ScanRecord:
    DATA_TYPE_3D_INFORMATION_DATA: typing.ClassVar[int] = ...
    DATA_TYPE_ADVERTISING_INTERVAL: typing.ClassVar[int] = ...
    DATA_TYPE_ADVERTISING_INTERVAL_LONG: typing.ClassVar[int] = ...
    DATA_TYPE_APPEARANCE: typing.ClassVar[int] = ...
    DATA_TYPE_BIG_INFO: typing.ClassVar[int] = ...
    DATA_TYPE_BROADCAST_CODE: typing.ClassVar[int] = ...
    DATA_TYPE_CHANNEL_MAP_UPDATE_INDICATION: typing.ClassVar[int] = ...
    DATA_TYPE_CLASS_OF_DEVICE: typing.ClassVar[int] = ...
    DATA_TYPE_DEVICE_ID: typing.ClassVar[int] = ...
    DATA_TYPE_FLAGS: typing.ClassVar[int] = ...
    DATA_TYPE_INDOOR_POSITIONING: typing.ClassVar[int] = ...
    DATA_TYPE_LE_BLUETOOTH_DEVICE_ADDRESS: typing.ClassVar[int] = ...
    DATA_TYPE_LE_ROLE: typing.ClassVar[int] = ...
    DATA_TYPE_LE_SECURE_CONNECTIONS_CONFIRMATION_VALUE: typing.ClassVar[int] = ...
    DATA_TYPE_LE_SECURE_CONNECTIONS_RANDOM_VALUE: typing.ClassVar[int] = ...
    DATA_TYPE_LE_SUPPORTED_FEATURES: typing.ClassVar[int] = ...
    DATA_TYPE_LOCAL_NAME_COMPLETE: typing.ClassVar[int] = ...
    DATA_TYPE_LOCAL_NAME_SHORT: typing.ClassVar[int] = ...
    DATA_TYPE_MANUFACTURER_SPECIFIC_DATA: typing.ClassVar[int] = ...
    DATA_TYPE_MESH_BEACON: typing.ClassVar[int] = ...
    DATA_TYPE_MESH_MESSAGE: typing.ClassVar[int] = ...
    DATA_TYPE_NONE: typing.ClassVar[int] = ...
    DATA_TYPE_PB_ADV: typing.ClassVar[int] = ...
    DATA_TYPE_PUBLIC_TARGET_ADDRESS: typing.ClassVar[int] = ...
    DATA_TYPE_RANDOM_TARGET_ADDRESS: typing.ClassVar[int] = ...
    DATA_TYPE_RESOLVABLE_SET_IDENTIFIER: typing.ClassVar[int] = ...
    DATA_TYPE_SECURITY_MANAGER_OUT_OF_BAND_FLAGS: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_DATA_128_BIT: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_DATA_16_BIT: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_DATA_32_BIT: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_SOLICITATION_UUIDS_128_BIT: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_SOLICITATION_UUIDS_16_BIT: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_SOLICITATION_UUIDS_32_BIT: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_UUIDS_128_BIT_COMPLETE: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_UUIDS_128_BIT_PARTIAL: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_UUIDS_16_BIT_COMPLETE: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_UUIDS_16_BIT_PARTIAL: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_UUIDS_32_BIT_COMPLETE: typing.ClassVar[int] = ...
    DATA_TYPE_SERVICE_UUIDS_32_BIT_PARTIAL: typing.ClassVar[int] = ...
    DATA_TYPE_SIMPLE_PAIRING_HASH_C: typing.ClassVar[int] = ...
    DATA_TYPE_SIMPLE_PAIRING_HASH_C_256: typing.ClassVar[int] = ...
    DATA_TYPE_SIMPLE_PAIRING_RANDOMIZER_R: typing.ClassVar[int] = ...
    DATA_TYPE_SIMPLE_PAIRING_RANDOMIZER_R_256: typing.ClassVar[int] = ...
    DATA_TYPE_SLAVE_CONNECTION_INTERVAL_RANGE: typing.ClassVar[int] = ...
    DATA_TYPE_TRANSPORT_DISCOVERY_DATA: typing.ClassVar[int] = ...
    DATA_TYPE_TX_POWER_LEVEL: typing.ClassVar[int] = ...
    DATA_TYPE_URI: typing.ClassVar[int] = ...
    def getAdvertiseFlags(self) -> int: ...
    def getAdvertisingDataMap(self) -> java.util.Map[int, typing.MutableSequence[int]]: ...
    def getBytes(self) -> typing.MutableSequence[int]: ...
    def getDeviceName(self) -> str: ...
    @typing.overload
    def getManufacturerSpecificData(self) -> android.util.SparseArray[typing.MutableSequence[int]]: ...
    @typing.overload
    def getManufacturerSpecificData(self, int: int) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getServiceData(self, parcelUuid: android.os.ParcelUuid) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getServiceData(self) -> java.util.Map[android.os.ParcelUuid, typing.MutableSequence[int]]: ...
    def getServiceSolicitationUuids(self) -> java.util.List[android.os.ParcelUuid]: ...
    def getServiceUuids(self) -> java.util.List[android.os.ParcelUuid]: ...
    def getTxPowerLevel(self) -> int: ...
    def toString(self) -> str: ...

class ScanResult(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DATA_COMPLETE: typing.ClassVar[int] = ...
    DATA_TRUNCATED: typing.ClassVar[int] = ...
    PERIODIC_INTERVAL_NOT_PRESENT: typing.ClassVar[int] = ...
    PHY_UNUSED: typing.ClassVar[int] = ...
    SID_NOT_PRESENT: typing.ClassVar[int] = ...
    TX_POWER_NOT_PRESENT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, bluetoothDevice: android.bluetooth.BluetoothDevice, scanRecord: ScanRecord, int: int, long: int): ...
    @typing.overload
    def __init__(self, bluetoothDevice: android.bluetooth.BluetoothDevice, int: int, int2: int, int3: int, int4: int, int5: int, int6: int, int7: int, scanRecord: ScanRecord, long: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdvertisingSid(self) -> int: ...
    def getDataStatus(self) -> int: ...
    def getDevice(self) -> android.bluetooth.BluetoothDevice: ...
    def getPeriodicAdvertisingInterval(self) -> int: ...
    def getPrimaryPhy(self) -> int: ...
    def getRssi(self) -> int: ...
    def getScanRecord(self) -> ScanRecord: ...
    def getSecondaryPhy(self) -> int: ...
    def getTimestampNanos(self) -> int: ...
    def getTxPower(self) -> int: ...
    def hashCode(self) -> int: ...
    def isConnectable(self) -> bool: ...
    def isLegacy(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ScanSettings(android.os.Parcelable):
    AUTO_BATCH_MIN_REPORT_DELAY_MILLIS: typing.ClassVar[int] = ...
    CALLBACK_TYPE_ALL_MATCHES: typing.ClassVar[int] = ...
    CALLBACK_TYPE_ALL_MATCHES_AUTO_BATCH: typing.ClassVar[int] = ...
    CALLBACK_TYPE_FIRST_MATCH: typing.ClassVar[int] = ...
    CALLBACK_TYPE_MATCH_LOST: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    MATCH_MODE_AGGRESSIVE: typing.ClassVar[int] = ...
    MATCH_MODE_STICKY: typing.ClassVar[int] = ...
    MATCH_NUM_FEW_ADVERTISEMENT: typing.ClassVar[int] = ...
    MATCH_NUM_MAX_ADVERTISEMENT: typing.ClassVar[int] = ...
    MATCH_NUM_ONE_ADVERTISEMENT: typing.ClassVar[int] = ...
    PHY_LE_ALL_SUPPORTED: typing.ClassVar[int] = ...
    SCAN_MODE_BALANCED: typing.ClassVar[int] = ...
    SCAN_MODE_LOW_LATENCY: typing.ClassVar[int] = ...
    SCAN_MODE_LOW_POWER: typing.ClassVar[int] = ...
    SCAN_MODE_OPPORTUNISTIC: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getCallbackType(self) -> int: ...
    def getLegacy(self) -> bool: ...
    def getPhy(self) -> int: ...
    def getReportDelayMillis(self) -> int: ...
    def getScanMode(self) -> int: ...
    def getScanResultType(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'ScanSettings': ...
        def setCallbackType(self, int: int) -> 'ScanSettings.Builder': ...
        def setLegacy(self, boolean: bool) -> 'ScanSettings.Builder': ...
        def setMatchMode(self, int: int) -> 'ScanSettings.Builder': ...
        def setNumOfMatches(self, int: int) -> 'ScanSettings.Builder': ...
        def setPhy(self, int: int) -> 'ScanSettings.Builder': ...
        def setReportDelay(self, long: int) -> 'ScanSettings.Builder': ...
        def setScanMode(self, int: int) -> 'ScanSettings.Builder': ...

class TransportBlock(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOrgId(self) -> int: ...
    def getTdsFlags(self) -> int: ...
    def getTransportData(self) -> typing.MutableSequence[int]: ...
    def getTransportDataLength(self) -> int: ...
    def hashCode(self) -> int: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    def totalBytes(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TransportDiscoveryData(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    @typing.overload
    def __init__(self, int: int, list: java.util.List[TransportBlock]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getTransportBlocks(self) -> java.util.List[TransportBlock]: ...
    def getTransportDataType(self) -> int: ...
    def hashCode(self) -> int: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    def toString(self) -> str: ...
    def totalBytes(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.bluetooth.le")``.

    AdvertiseCallback: typing.Type[AdvertiseCallback]
    AdvertiseData: typing.Type[AdvertiseData]
    AdvertiseSettings: typing.Type[AdvertiseSettings]
    AdvertisingSet: typing.Type[AdvertisingSet]
    AdvertisingSetCallback: typing.Type[AdvertisingSetCallback]
    AdvertisingSetParameters: typing.Type[AdvertisingSetParameters]
    BluetoothLeAdvertiser: typing.Type[BluetoothLeAdvertiser]
    BluetoothLeScanner: typing.Type[BluetoothLeScanner]
    PeriodicAdvertisingParameters: typing.Type[PeriodicAdvertisingParameters]
    ScanCallback: typing.Type[ScanCallback]
    ScanFilter: typing.Type[ScanFilter]
    ScanRecord: typing.Type[ScanRecord]
    ScanResult: typing.Type[ScanResult]
    ScanSettings: typing.Type[ScanSettings]
    TransportBlock: typing.Type[TransportBlock]
    TransportDiscoveryData: typing.Type[TransportDiscoveryData]
