
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.app
import android.content
import android.graphics.drawable
import android.icu.util
import android.os
import android.text
import android.text.style
import android.view
import java.lang
import java.time
import java.util
import java.util.function
import typing



class ConversationAction(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_CALL_PHONE: typing.ClassVar[str] = ...
    TYPE_CREATE_REMINDER: typing.ClassVar[str] = ...
    TYPE_OPEN_URL: typing.ClassVar[str] = ...
    TYPE_SEND_EMAIL: typing.ClassVar[str] = ...
    TYPE_SEND_SMS: typing.ClassVar[str] = ...
    TYPE_SHARE_LOCATION: typing.ClassVar[str] = ...
    TYPE_TEXT_REPLY: typing.ClassVar[str] = ...
    TYPE_TRACK_FLIGHT: typing.ClassVar[str] = ...
    TYPE_VIEW_CALENDAR: typing.ClassVar[str] = ...
    TYPE_VIEW_MAP: typing.ClassVar[str] = ...
    def describeContents(self) -> int: ...
    def getAction(self) -> android.app.RemoteAction: ...
    def getConfidenceScore(self) -> float: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getTextReply(self) -> java.lang.CharSequence: ...
    def getType(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        def build(self) -> 'ConversationAction': ...
        def setAction(self, remoteAction: android.app.RemoteAction) -> 'ConversationAction.Builder': ...
        def setConfidenceScore(self, float: float) -> 'ConversationAction.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'ConversationAction.Builder': ...
        def setTextReply(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'ConversationAction.Builder': ...

class ConversationActions(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List[ConversationAction], string: str): ...
    def describeContents(self) -> int: ...
    def getConversationActions(self) -> java.util.List[ConversationAction]: ...
    def getId(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Message(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        PERSON_USER_OTHERS: typing.ClassVar[android.app.Person] = ...
        PERSON_USER_SELF: typing.ClassVar[android.app.Person] = ...
        def describeContents(self) -> int: ...
        def getAuthor(self) -> android.app.Person: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getReferenceTime(self) -> java.time.ZonedDateTime: ...
        def getText(self) -> java.lang.CharSequence: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, person: android.app.Person): ...
            def build(self) -> 'ConversationActions.Message': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'ConversationActions.Message.Builder': ...
            def setReferenceTime(self, zonedDateTime: java.time.ZonedDateTime) -> 'ConversationActions.Message.Builder': ...
            def setText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'ConversationActions.Message.Builder': ...
    class Request(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        HINT_FOR_IN_APP: typing.ClassVar[str] = ...
        HINT_FOR_NOTIFICATION: typing.ClassVar[str] = ...
        def describeContents(self) -> int: ...
        def getCallingPackageName(self) -> str: ...
        def getConversation(self) -> java.util.List['ConversationActions.Message']: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getHints(self) -> java.util.List[str]: ...
        def getMaxSuggestions(self) -> int: ...
        def getTypeConfig(self) -> 'TextClassifier.EntityConfig': ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, list: java.util.List['ConversationActions.Message']): ...
            def build(self) -> 'ConversationActions.Request': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'ConversationActions.Request.Builder': ...
            def setHints(self, list: java.util.List[str]) -> 'ConversationActions.Request.Builder': ...
            def setMaxSuggestions(self, int: int) -> 'ConversationActions.Request.Builder': ...
            def setTypeConfig(self, entityConfig: 'TextClassifier.EntityConfig') -> 'ConversationActions.Request.Builder': ...

class SelectionEvent(android.os.Parcelable):
    ACTION_ABANDON: typing.ClassVar[int] = ...
    ACTION_COPY: typing.ClassVar[int] = ...
    ACTION_CUT: typing.ClassVar[int] = ...
    ACTION_DRAG: typing.ClassVar[int] = ...
    ACTION_OTHER: typing.ClassVar[int] = ...
    ACTION_OVERTYPE: typing.ClassVar[int] = ...
    ACTION_PASTE: typing.ClassVar[int] = ...
    ACTION_RESET: typing.ClassVar[int] = ...
    ACTION_SELECT_ALL: typing.ClassVar[int] = ...
    ACTION_SHARE: typing.ClassVar[int] = ...
    ACTION_SMART_SHARE: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EVENT_AUTO_SELECTION: typing.ClassVar[int] = ...
    EVENT_SELECTION_MODIFIED: typing.ClassVar[int] = ...
    EVENT_SELECTION_STARTED: typing.ClassVar[int] = ...
    EVENT_SMART_SELECTION_MULTI: typing.ClassVar[int] = ...
    EVENT_SMART_SELECTION_SINGLE: typing.ClassVar[int] = ...
    INVOCATION_LINK: typing.ClassVar[int] = ...
    INVOCATION_MANUAL: typing.ClassVar[int] = ...
    INVOCATION_UNKNOWN: typing.ClassVar[int] = ...
    @typing.overload
    @staticmethod
    def createSelectionActionEvent(int: int, int2: int, int3: int) -> 'SelectionEvent': ...
    @typing.overload
    @staticmethod
    def createSelectionActionEvent(int: int, int2: int, int3: int, textClassification: 'TextClassification') -> 'SelectionEvent': ...
    @typing.overload
    @staticmethod
    def createSelectionModifiedEvent(int: int, int2: int) -> 'SelectionEvent': ...
    @typing.overload
    @staticmethod
    def createSelectionModifiedEvent(int: int, int2: int, textClassification: 'TextClassification') -> 'SelectionEvent': ...
    @typing.overload
    @staticmethod
    def createSelectionModifiedEvent(int: int, int2: int, textSelection: 'TextSelection') -> 'SelectionEvent': ...
    @staticmethod
    def createSelectionStartedEvent(int: int, int2: int) -> 'SelectionEvent': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDurationSincePreviousEvent(self) -> int: ...
    def getDurationSinceSessionStart(self) -> int: ...
    def getEnd(self) -> int: ...
    def getEntityType(self) -> str: ...
    def getEventIndex(self) -> int: ...
    def getEventTime(self) -> int: ...
    def getEventType(self) -> int: ...
    def getInvocationMethod(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getResultId(self) -> str: ...
    def getSessionId(self) -> 'TextClassificationSessionId': ...
    def getSmartEnd(self) -> int: ...
    def getSmartStart(self) -> int: ...
    def getStart(self) -> int: ...
    def getWidgetType(self) -> str: ...
    def getWidgetVersion(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def isTerminal(int: int) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TextClassification(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getActions(self) -> java.util.List[android.app.RemoteAction]: ...
    def getConfidenceScore(self, string: str) -> float: ...
    def getEntity(self, int: int) -> str: ...
    def getEntityCount(self) -> int: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getIcon(self) -> android.graphics.drawable.Drawable: ...
    def getId(self) -> str: ...
    def getIntent(self) -> android.content.Intent: ...
    def getLabel(self) -> java.lang.CharSequence: ...
    def getOnClickListener(self) -> android.view.View.OnClickListener: ...
    def getText(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addAction(self, remoteAction: android.app.RemoteAction) -> 'TextClassification.Builder': ...
        def build(self) -> 'TextClassification': ...
        def setEntityType(self, string: str, float: float) -> 'TextClassification.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'TextClassification.Builder': ...
        def setIcon(self, drawable: android.graphics.drawable.Drawable) -> 'TextClassification.Builder': ...
        def setId(self, string: str) -> 'TextClassification.Builder': ...
        def setIntent(self, intent: android.content.Intent) -> 'TextClassification.Builder': ...
        def setLabel(self, string: str) -> 'TextClassification.Builder': ...
        def setOnClickListener(self, onClickListener: typing.Union[android.view.View.OnClickListener, typing.Callable]) -> 'TextClassification.Builder': ...
        def setText(self, string: str) -> 'TextClassification.Builder': ...
    class Request(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getCallingPackageName(self) -> str: ...
        def getDefaultLocales(self) -> android.os.LocaleList: ...
        def getEndIndex(self) -> int: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getReferenceTime(self) -> java.time.ZonedDateTime: ...
        def getStartIndex(self) -> int: ...
        def getText(self) -> java.lang.CharSequence: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int): ...
            def build(self) -> 'TextClassification.Request': ...
            def setDefaultLocales(self, localeList: android.os.LocaleList) -> 'TextClassification.Request.Builder': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'TextClassification.Request.Builder': ...
            def setReferenceTime(self, zonedDateTime: java.time.ZonedDateTime) -> 'TextClassification.Request.Builder': ...

class TextClassificationContext(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getWidgetType(self) -> str: ...
    def getWidgetVersion(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str, string2: str): ...
        def build(self) -> 'TextClassificationContext': ...
        def setWidgetVersion(self, string: str) -> 'TextClassificationContext.Builder': ...

class TextClassificationManager:
    def createTextClassificationSession(self, textClassificationContext: TextClassificationContext) -> 'TextClassifier': ...
    def getTextClassifier(self) -> 'TextClassifier': ...
    def setTextClassificationSessionFactory(self, textClassificationSessionFactory: typing.Union['TextClassificationSessionFactory', typing.Callable]) -> None: ...
    def setTextClassifier(self, textClassifier: 'TextClassifier') -> None: ...

class TextClassificationSessionFactory:
    def createTextClassificationSession(self, textClassificationContext: TextClassificationContext) -> 'TextClassifier': ...

class TextClassificationSessionId(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getValue(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TextClassifier:
    EXTRA_FROM_TEXT_CLASSIFIER: typing.ClassVar[str] = ...
    HINT_TEXT_IS_EDITABLE: typing.ClassVar[str] = ...
    HINT_TEXT_IS_NOT_EDITABLE: typing.ClassVar[str] = ...
    NO_OP: typing.ClassVar['TextClassifier'] = ...
    TYPE_ADDRESS: typing.ClassVar[str] = ...
    TYPE_DATE: typing.ClassVar[str] = ...
    TYPE_DATE_TIME: typing.ClassVar[str] = ...
    TYPE_EMAIL: typing.ClassVar[str] = ...
    TYPE_FLIGHT_NUMBER: typing.ClassVar[str] = ...
    TYPE_OTHER: typing.ClassVar[str] = ...
    TYPE_PHONE: typing.ClassVar[str] = ...
    TYPE_UNKNOWN: typing.ClassVar[str] = ...
    TYPE_URL: typing.ClassVar[str] = ...
    WIDGET_TYPE_CLIPBOARD: typing.ClassVar[str] = ...
    WIDGET_TYPE_CUSTOM_EDITTEXT: typing.ClassVar[str] = ...
    WIDGET_TYPE_CUSTOM_TEXTVIEW: typing.ClassVar[str] = ...
    WIDGET_TYPE_CUSTOM_UNSELECTABLE_TEXTVIEW: typing.ClassVar[str] = ...
    WIDGET_TYPE_EDITTEXT: typing.ClassVar[str] = ...
    WIDGET_TYPE_EDIT_WEBVIEW: typing.ClassVar[str] = ...
    WIDGET_TYPE_NOTIFICATION: typing.ClassVar[str] = ...
    WIDGET_TYPE_TEXTVIEW: typing.ClassVar[str] = ...
    WIDGET_TYPE_UNKNOWN: typing.ClassVar[str] = ...
    WIDGET_TYPE_UNSELECTABLE_TEXTVIEW: typing.ClassVar[str] = ...
    WIDGET_TYPE_WEBVIEW: typing.ClassVar[str] = ...
    @typing.overload
    def classifyText(self, request: TextClassification.Request) -> TextClassification: ...
    @typing.overload
    def classifyText(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, localeList: android.os.LocaleList) -> TextClassification: ...
    def destroy(self) -> None: ...
    def detectLanguage(self, request: 'TextLanguage.Request') -> 'TextLanguage': ...
    def generateLinks(self, request: 'TextLinks.Request') -> 'TextLinks': ...
    def getMaxGenerateLinksTextLength(self) -> int: ...
    def isDestroyed(self) -> bool: ...
    def onSelectionEvent(self, selectionEvent: SelectionEvent) -> None: ...
    def onTextClassifierEvent(self, textClassifierEvent: 'TextClassifierEvent') -> None: ...
    def suggestConversationActions(self, request: ConversationActions.Request) -> ConversationActions: ...
    @typing.overload
    def suggestSelection(self, request: 'TextSelection.Request') -> 'TextSelection': ...
    @typing.overload
    def suggestSelection(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, localeList: android.os.LocaleList) -> 'TextSelection': ...
    class EntityConfig(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @staticmethod
        def create(collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]], collection2: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]], collection3: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TextClassifier.EntityConfig': ...
        @staticmethod
        def createWithExplicitEntityList(collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TextClassifier.EntityConfig': ...
        @staticmethod
        def createWithHints(collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TextClassifier.EntityConfig': ...
        def describeContents(self) -> int: ...
        def getHints(self) -> java.util.Collection[str]: ...
        def resolveEntityListModifications(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> java.util.Collection[str]: ...
        def shouldIncludeTypesFromTextClassifier(self) -> bool: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'TextClassifier.EntityConfig': ...
            def includeTypesFromTextClassifier(self, boolean: bool) -> 'TextClassifier.EntityConfig.Builder': ...
            def setExcludedTypes(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TextClassifier.EntityConfig.Builder': ...
            def setHints(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TextClassifier.EntityConfig.Builder': ...
            def setIncludedTypes(self, collection: typing.Union[java.util.Collection[str], typing.Sequence[str], typing.Set[str]]) -> 'TextClassifier.EntityConfig.Builder': ...

class TextLanguage(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getConfidenceScore(self, uLocale: android.icu.util.ULocale) -> float: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getId(self) -> str: ...
    def getLocale(self, int: int) -> android.icu.util.ULocale: ...
    def getLocaleHypothesisCount(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'TextLanguage': ...
        def putLocale(self, uLocale: android.icu.util.ULocale, float: float) -> 'TextLanguage.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'TextLanguage.Builder': ...
        def setId(self, string: str) -> 'TextLanguage.Builder': ...
    class Request(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getCallingPackageName(self) -> str: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getText(self) -> java.lang.CharSequence: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str]): ...
            def build(self) -> 'TextLanguage.Request': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'TextLanguage.Request.Builder': ...

class TextLinks(android.os.Parcelable):
    APPLY_STRATEGY_IGNORE: typing.ClassVar[int] = ...
    APPLY_STRATEGY_REPLACE: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STATUS_DIFFERENT_TEXT: typing.ClassVar[int] = ...
    STATUS_LINKS_APPLIED: typing.ClassVar[int] = ...
    STATUS_NO_LINKS_APPLIED: typing.ClassVar[int] = ...
    STATUS_NO_LINKS_FOUND: typing.ClassVar[int] = ...
    STATUS_UNSUPPORTED_CHARACTER: typing.ClassVar[int] = ...
    def apply(self, spannable: android.text.Spannable, int: int, function: typing.Union[java.util.function.Function['TextLinks.TextLink', 'TextLinks.TextLinkSpan'], typing.Callable[['TextLinks.TextLink'], 'TextLinks.TextLinkSpan']]) -> int: ...
    def describeContents(self) -> int: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getLinks(self) -> java.util.Collection['TextLinks.TextLink']: ...
    def getText(self) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        @typing.overload
        def addLink(self, int: int, int2: int, map: typing.Union[java.util.Map[str, float], typing.Mapping[str, float]]) -> 'TextLinks.Builder': ...
        @typing.overload
        def addLink(self, int: int, int2: int, map: typing.Union[java.util.Map[str, float], typing.Mapping[str, float]], bundle: android.os.Bundle) -> 'TextLinks.Builder': ...
        def build(self) -> 'TextLinks': ...
        def clearTextLinks(self) -> 'TextLinks.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'TextLinks.Builder': ...
    class Request(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getCallingPackageName(self) -> str: ...
        def getDefaultLocales(self) -> android.os.LocaleList: ...
        def getEntityConfig(self) -> TextClassifier.EntityConfig: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getReferenceTime(self) -> java.time.ZonedDateTime: ...
        def getText(self) -> java.lang.CharSequence: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str]): ...
            def build(self) -> 'TextLinks.Request': ...
            def setDefaultLocales(self, localeList: android.os.LocaleList) -> 'TextLinks.Request.Builder': ...
            def setEntityConfig(self, entityConfig: TextClassifier.EntityConfig) -> 'TextLinks.Request.Builder': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'TextLinks.Request.Builder': ...
            def setReferenceTime(self, zonedDateTime: java.time.ZonedDateTime) -> 'TextLinks.Request.Builder': ...
    class TextLink(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getConfidenceScore(self, string: str) -> float: ...
        def getEnd(self) -> int: ...
        def getEntity(self, int: int) -> str: ...
        def getEntityCount(self) -> int: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getStart(self) -> int: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class TextLinkSpan(android.text.style.ClickableSpan):
        def __init__(self, textLink: 'TextLinks.TextLink'): ...
        def getTextLink(self) -> 'TextLinks.TextLink': ...
        def onClick(self, view: android.view.View) -> None: ...

class TextSelection(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getConfidenceScore(self, string: str) -> float: ...
    def getEntity(self, int: int) -> str: ...
    def getEntityCount(self) -> int: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getId(self) -> str: ...
    def getSelectionEndIndex(self) -> int: ...
    def getSelectionStartIndex(self) -> int: ...
    def getTextClassification(self) -> TextClassification: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, int2: int): ...
        def build(self) -> 'TextSelection': ...
        def setEntityType(self, string: str, float: float) -> 'TextSelection.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'TextSelection.Builder': ...
        def setId(self, string: str) -> 'TextSelection.Builder': ...
        def setTextClassification(self, textClassification: TextClassification) -> 'TextSelection.Builder': ...
    class Request(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def getCallingPackageName(self) -> str: ...
        def getDefaultLocales(self) -> android.os.LocaleList: ...
        def getEndIndex(self) -> int: ...
        def getExtras(self) -> android.os.Bundle: ...
        def getStartIndex(self) -> int: ...
        def getText(self) -> java.lang.CharSequence: ...
        def shouldIncludeTextClassification(self) -> bool: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder:
            def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int): ...
            def build(self) -> 'TextSelection.Request': ...
            def setDefaultLocales(self, localeList: android.os.LocaleList) -> 'TextSelection.Request.Builder': ...
            def setExtras(self, bundle: android.os.Bundle) -> 'TextSelection.Request.Builder': ...
            def setIncludeTextClassification(self, boolean: bool) -> 'TextSelection.Request.Builder': ...

_TextClassifierEvent__Builder__T = typing.TypeVar('_TextClassifierEvent__Builder__T', bound='TextClassifierEvent.Builder')  # <T>
class TextClassifierEvent(android.os.Parcelable):
    CATEGORY_CONVERSATION_ACTIONS: typing.ClassVar[int] = ...
    CATEGORY_LANGUAGE_DETECTION: typing.ClassVar[int] = ...
    CATEGORY_LINKIFY: typing.ClassVar[int] = ...
    CATEGORY_SELECTION: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_ACTIONS_GENERATED: typing.ClassVar[int] = ...
    TYPE_ACTIONS_SHOWN: typing.ClassVar[int] = ...
    TYPE_AUTO_SELECTION: typing.ClassVar[int] = ...
    TYPE_COPY_ACTION: typing.ClassVar[int] = ...
    TYPE_CUT_ACTION: typing.ClassVar[int] = ...
    TYPE_LINKS_GENERATED: typing.ClassVar[int] = ...
    TYPE_LINK_CLICKED: typing.ClassVar[int] = ...
    TYPE_MANUAL_REPLY: typing.ClassVar[int] = ...
    TYPE_OTHER_ACTION: typing.ClassVar[int] = ...
    TYPE_OVERTYPE: typing.ClassVar[int] = ...
    TYPE_PASTE_ACTION: typing.ClassVar[int] = ...
    TYPE_SELECTION_DESTROYED: typing.ClassVar[int] = ...
    TYPE_SELECTION_DRAG: typing.ClassVar[int] = ...
    TYPE_SELECTION_MODIFIED: typing.ClassVar[int] = ...
    TYPE_SELECTION_RESET: typing.ClassVar[int] = ...
    TYPE_SELECTION_STARTED: typing.ClassVar[int] = ...
    TYPE_SELECT_ALL: typing.ClassVar[int] = ...
    TYPE_SHARE_ACTION: typing.ClassVar[int] = ...
    TYPE_SMART_ACTION: typing.ClassVar[int] = ...
    TYPE_SMART_SELECTION_MULTI: typing.ClassVar[int] = ...
    TYPE_SMART_SELECTION_SINGLE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getActionIndices(self) -> typing.MutableSequence[int]: ...
    def getEntityTypes(self) -> typing.MutableSequence[str]: ...
    def getEventCategory(self) -> int: ...
    def getEventContext(self) -> TextClassificationContext: ...
    def getEventIndex(self) -> int: ...
    def getEventType(self) -> int: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getLocale(self) -> android.icu.util.ULocale: ...
    def getModelName(self) -> str: ...
    def getResultId(self) -> str: ...
    def getScores(self) -> typing.MutableSequence[float]: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder(typing.Generic[_TextClassifierEvent__Builder__T]):
        def setActionIndices(self, *int: int) -> _TextClassifierEvent__Builder__T: ...
        def setEntityTypes(self, *string: str) -> _TextClassifierEvent__Builder__T: ...
        def setEventContext(self, textClassificationContext: TextClassificationContext) -> _TextClassifierEvent__Builder__T: ...
        def setEventIndex(self, int: int) -> _TextClassifierEvent__Builder__T: ...
        def setExtras(self, bundle: android.os.Bundle) -> _TextClassifierEvent__Builder__T: ...
        def setLocale(self, uLocale: android.icu.util.ULocale) -> _TextClassifierEvent__Builder__T: ...
        def setModelName(self, string: str) -> _TextClassifierEvent__Builder__T: ...
        def setResultId(self, string: str) -> _TextClassifierEvent__Builder__T: ...
        def setScores(self, *float: float) -> _TextClassifierEvent__Builder__T: ...
    class ConversationActionsEvent(android.view.textclassifier.TextClassifierEvent, android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        class Builder(android.view.textclassifier.TextClassifierEvent.Builder['TextClassifierEvent.ConversationActionsEvent.Builder']):
            def __init__(self, int: int): ...
            def build(self) -> 'TextClassifierEvent.ConversationActionsEvent': ...
    class LanguageDetectionEvent(android.view.textclassifier.TextClassifierEvent, android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        class Builder(android.view.textclassifier.TextClassifierEvent.Builder['TextClassifierEvent.LanguageDetectionEvent.Builder']):
            def __init__(self, int: int): ...
            def build(self) -> 'TextClassifierEvent.LanguageDetectionEvent': ...
    class TextLinkifyEvent(android.view.textclassifier.TextClassifierEvent, android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        class Builder(android.view.textclassifier.TextClassifierEvent.Builder['TextClassifierEvent.TextLinkifyEvent.Builder']):
            def __init__(self, int: int): ...
            def build(self) -> 'TextClassifierEvent.TextLinkifyEvent': ...
    class TextSelectionEvent(android.view.textclassifier.TextClassifierEvent, android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def getRelativeSuggestedWordEndIndex(self) -> int: ...
        def getRelativeSuggestedWordStartIndex(self) -> int: ...
        def getRelativeWordEndIndex(self) -> int: ...
        def getRelativeWordStartIndex(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
        class Builder(android.view.textclassifier.TextClassifierEvent.Builder['TextClassifierEvent.TextSelectionEvent.Builder']):
            def __init__(self, int: int): ...
            def build(self) -> 'TextClassifierEvent.TextSelectionEvent': ...
            def setRelativeSuggestedWordEndIndex(self, int: int) -> 'TextClassifierEvent.TextSelectionEvent.Builder': ...
            def setRelativeSuggestedWordStartIndex(self, int: int) -> 'TextClassifierEvent.TextSelectionEvent.Builder': ...
            def setRelativeWordEndIndex(self, int: int) -> 'TextClassifierEvent.TextSelectionEvent.Builder': ...
            def setRelativeWordStartIndex(self, int: int) -> 'TextClassifierEvent.TextSelectionEvent.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.textclassifier")``.

    ConversationAction: typing.Type[ConversationAction]
    ConversationActions: typing.Type[ConversationActions]
    SelectionEvent: typing.Type[SelectionEvent]
    TextClassification: typing.Type[TextClassification]
    TextClassificationContext: typing.Type[TextClassificationContext]
    TextClassificationManager: typing.Type[TextClassificationManager]
    TextClassificationSessionFactory: typing.Type[TextClassificationSessionFactory]
    TextClassificationSessionId: typing.Type[TextClassificationSessionId]
    TextClassifier: typing.Type[TextClassifier]
    TextClassifierEvent: typing.Type[TextClassifierEvent]
    TextLanguage: typing.Type[TextLanguage]
    TextLinks: typing.Type[TextLinks]
    TextSelection: typing.Type[TextSelection]
