
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.graphics.drawable
import android.os
import java.lang
import java.util
import typing



class AdditionalContentContract:
    class Columns:
        URI: typing.ClassVar[str] = ...
    class CursorExtraKeys:
        POSITION: typing.ClassVar[str] = ...
    class MethodNames:
        ON_SELECTION_CHANGED: typing.ClassVar[str] = ...

class ChooserAction(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAction(self) -> android.app.PendingIntent: ...
    def getIcon(self) -> android.graphics.drawable.Icon: ...
    def getLabel(self) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, icon: android.graphics.drawable.Icon, charSequence: typing.Union[java.lang.CharSequence, str], pendingIntent: android.app.PendingIntent): ...
        def build(self) -> 'ChooserAction': ...

class ChooserResult(android.os.Parcelable):
    CHOOSER_RESULT_COPY: typing.ClassVar[int] = ...
    CHOOSER_RESULT_EDIT: typing.ClassVar[int] = ...
    CHOOSER_RESULT_SELECTED_COMPONENT: typing.ClassVar[int] = ...
    CHOOSER_RESULT_UNKNOWN: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getSelectedComponent(self) -> android.content.ComponentName: ...
    def getType(self) -> int: ...
    def hashCode(self) -> int: ...
    def isShortcut(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ChooserTarget(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], icon: android.graphics.drawable.Icon, float: float, componentName: android.content.ComponentName, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getComponentName(self) -> android.content.ComponentName: ...
    def getIcon(self) -> android.graphics.drawable.Icon: ...
    def getIntentExtras(self) -> android.os.Bundle: ...
    def getScore(self) -> float: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ChooserTargetService(android.app.Service):
    BIND_PERMISSION: typing.ClassVar[str] = ...
    META_DATA_NAME: typing.ClassVar[str] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onGetChooserTargets(self, componentName: android.content.ComponentName, intentFilter: android.content.IntentFilter) -> java.util.List[ChooserTarget]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.chooser")``.

    AdditionalContentContract: typing.Type[AdditionalContentContract]
    ChooserAction: typing.Type[ChooserAction]
    ChooserResult: typing.Type[ChooserResult]
    ChooserTarget: typing.Type[ChooserTarget]
    ChooserTargetService: typing.Type[ChooserTargetService]
