
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.adservices.common
import android.content
import android.net
import android.os
import datetime
import java.lang
import java.time
import java.util
import java.util.concurrent
import typing



class AddCustomAudienceOverrideRequest:
    def __init__(self, adTechIdentifier: android.adservices.common.AdTechIdentifier, string: str, string2: str, adSelectionSignals: android.adservices.common.AdSelectionSignals): ...
    def getBiddingLogicJs(self) -> str: ...
    def getBiddingLogicJsVersion(self) -> int: ...
    def getBuyer(self) -> android.adservices.common.AdTechIdentifier: ...
    def getName(self) -> str: ...
    def getTrustedBiddingSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AddCustomAudienceOverrideRequest': ...
        def setBiddingLogicJs(self, string: str) -> 'AddCustomAudienceOverrideRequest.Builder': ...
        def setBiddingLogicJsVersion(self, long: int) -> 'AddCustomAudienceOverrideRequest.Builder': ...
        def setBuyer(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'AddCustomAudienceOverrideRequest.Builder': ...
        def setName(self, string: str) -> 'AddCustomAudienceOverrideRequest.Builder': ...
        def setTrustedBiddingSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'AddCustomAudienceOverrideRequest.Builder': ...

class CustomAudience(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FLAG_AUCTION_SERVER_REQUEST_OMIT_ADS: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getActivationTime(self) -> java.time.Instant: ...
    def getAds(self) -> java.util.List[android.adservices.common.AdData]: ...
    def getAuctionServerRequestFlags(self) -> int: ...
    def getBiddingLogicUri(self) -> android.net.Uri: ...
    def getBuyer(self) -> android.adservices.common.AdTechIdentifier: ...
    def getDailyUpdateUri(self) -> android.net.Uri: ...
    def getExpirationTime(self) -> java.time.Instant: ...
    def getName(self) -> str: ...
    def getTrustedBiddingData(self) -> 'TrustedBiddingData': ...
    def getUserBiddingSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'CustomAudience': ...
        def setActivationTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'CustomAudience.Builder': ...
        def setAds(self, list: java.util.List[android.adservices.common.AdData]) -> 'CustomAudience.Builder': ...
        def setAuctionServerRequestFlags(self, int: int) -> 'CustomAudience.Builder': ...
        def setBiddingLogicUri(self, uri: android.net.Uri) -> 'CustomAudience.Builder': ...
        def setBuyer(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'CustomAudience.Builder': ...
        def setDailyUpdateUri(self, uri: android.net.Uri) -> 'CustomAudience.Builder': ...
        def setExpirationTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'CustomAudience.Builder': ...
        def setName(self, string: str) -> 'CustomAudience.Builder': ...
        def setTrustedBiddingData(self, trustedBiddingData: 'TrustedBiddingData') -> 'CustomAudience.Builder': ...
        def setUserBiddingSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'CustomAudience.Builder': ...

class CustomAudienceManager:
    def fetchAndJoinCustomAudience(self, fetchAndJoinCustomAudienceRequest: 'FetchAndJoinCustomAudienceRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    @staticmethod
    def get(context: android.content.Context) -> 'CustomAudienceManager': ...
    def getTestCustomAudienceManager(self) -> 'TestCustomAudienceManager': ...
    def joinCustomAudience(self, joinCustomAudienceRequest: 'JoinCustomAudienceRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def leaveCustomAudience(self, leaveCustomAudienceRequest: 'LeaveCustomAudienceRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def scheduleCustomAudienceUpdate(self, scheduleCustomAudienceUpdateRequest: 'ScheduleCustomAudienceUpdateRequest', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], adServicesOutcomeReceiver: typing.Union[android.adservices.common.AdServicesOutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...

class FetchAndJoinCustomAudienceRequest:
    def equals(self, object: typing.Any) -> bool: ...
    def getActivationTime(self) -> java.time.Instant: ...
    def getExpirationTime(self) -> java.time.Instant: ...
    def getFetchUri(self) -> android.net.Uri: ...
    def getName(self) -> str: ...
    def getUserBiddingSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    class Builder:
        def __init__(self, uri: android.net.Uri): ...
        def build(self) -> 'FetchAndJoinCustomAudienceRequest': ...
        def setActivationTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'FetchAndJoinCustomAudienceRequest.Builder': ...
        def setExpirationTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'FetchAndJoinCustomAudienceRequest.Builder': ...
        def setFetchUri(self, uri: android.net.Uri) -> 'FetchAndJoinCustomAudienceRequest.Builder': ...
        def setName(self, string: str) -> 'FetchAndJoinCustomAudienceRequest.Builder': ...
        def setUserBiddingSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'FetchAndJoinCustomAudienceRequest.Builder': ...

class JoinCustomAudienceRequest:
    def equals(self, object: typing.Any) -> bool: ...
    def getCustomAudience(self) -> CustomAudience: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'JoinCustomAudienceRequest': ...
        def setCustomAudience(self, customAudience: CustomAudience) -> 'JoinCustomAudienceRequest.Builder': ...

class LeaveCustomAudienceRequest:
    def equals(self, object: typing.Any) -> bool: ...
    def getBuyer(self) -> android.adservices.common.AdTechIdentifier: ...
    def getName(self) -> str: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'LeaveCustomAudienceRequest': ...
        def setBuyer(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'LeaveCustomAudienceRequest.Builder': ...
        def setName(self, string: str) -> 'LeaveCustomAudienceRequest.Builder': ...

class PartialCustomAudience(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getActivationTime(self) -> java.time.Instant: ...
    def getExpirationTime(self) -> java.time.Instant: ...
    def getName(self) -> str: ...
    def getUserBiddingSignals(self) -> android.adservices.common.AdSelectionSignals: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        def build(self) -> 'PartialCustomAudience': ...
        def setActivationTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'PartialCustomAudience.Builder': ...
        def setExpirationTime(self, instant: typing.Union[java.time.Instant, datetime.datetime]) -> 'PartialCustomAudience.Builder': ...
        def setUserBiddingSignals(self, adSelectionSignals: android.adservices.common.AdSelectionSignals) -> 'PartialCustomAudience.Builder': ...

class RemoveCustomAudienceOverrideRequest:
    def __init__(self, adTechIdentifier: android.adservices.common.AdTechIdentifier, string: str): ...
    def getBuyer(self) -> android.adservices.common.AdTechIdentifier: ...
    def getName(self) -> str: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'RemoveCustomAudienceOverrideRequest': ...
        def setBuyer(self, adTechIdentifier: android.adservices.common.AdTechIdentifier) -> 'RemoveCustomAudienceOverrideRequest.Builder': ...
        def setName(self, string: str) -> 'RemoveCustomAudienceOverrideRequest.Builder': ...

class ScheduleCustomAudienceUpdateRequest:
    def equals(self, object: typing.Any) -> bool: ...
    def getMinDelay(self) -> java.time.Duration: ...
    def getPartialCustomAudienceList(self) -> java.util.List[PartialCustomAudience]: ...
    def getUpdateUri(self) -> android.net.Uri: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    class Builder:
        def __init__(self, uri: android.net.Uri, duration: java.time.Duration, list: java.util.List[PartialCustomAudience]): ...
        def build(self) -> 'ScheduleCustomAudienceUpdateRequest': ...
        def setMinDelay(self, duration: java.time.Duration) -> 'ScheduleCustomAudienceUpdateRequest.Builder': ...
        def setPartialCustomAudienceList(self, list: java.util.List[PartialCustomAudience]) -> 'ScheduleCustomAudienceUpdateRequest.Builder': ...
        def setUpdateUri(self, uri: android.net.Uri) -> 'ScheduleCustomAudienceUpdateRequest.Builder': ...

class TestCustomAudienceManager:
    def overrideCustomAudienceRemoteInfo(self, addCustomAudienceOverrideRequest: AddCustomAudienceOverrideRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def removeCustomAudienceRemoteInfoOverride(self, removeCustomAudienceOverrideRequest: RemoveCustomAudienceOverrideRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...
    def resetAllCustomAudienceOverrides(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[typing.Any, java.lang.Exception], typing.Callable[[typing.Any], None]]) -> None: ...

class TrustedBiddingData(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getTrustedBiddingKeys(self) -> java.util.List[str]: ...
    def getTrustedBiddingUri(self) -> android.net.Uri: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'TrustedBiddingData': ...
        def setTrustedBiddingKeys(self, list: java.util.List[str]) -> 'TrustedBiddingData.Builder': ...
        def setTrustedBiddingUri(self, uri: android.net.Uri) -> 'TrustedBiddingData.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.adservices.customaudience")``.

    AddCustomAudienceOverrideRequest: typing.Type[AddCustomAudienceOverrideRequest]
    CustomAudience: typing.Type[CustomAudience]
    CustomAudienceManager: typing.Type[CustomAudienceManager]
    FetchAndJoinCustomAudienceRequest: typing.Type[FetchAndJoinCustomAudienceRequest]
    JoinCustomAudienceRequest: typing.Type[JoinCustomAudienceRequest]
    LeaveCustomAudienceRequest: typing.Type[LeaveCustomAudienceRequest]
    PartialCustomAudience: typing.Type[PartialCustomAudience]
    RemoveCustomAudienceOverrideRequest: typing.Type[RemoveCustomAudienceOverrideRequest]
    ScheduleCustomAudienceUpdateRequest: typing.Type[ScheduleCustomAudienceUpdateRequest]
    TestCustomAudienceManager: typing.Type[TestCustomAudienceManager]
    TrustedBiddingData: typing.Type[TrustedBiddingData]
