
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.os
import typing



class DownloadableSubscription(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    @staticmethod
    def forActivationCode(string: str) -> 'DownloadableSubscription': ...
    def getConfirmationCode(self) -> str: ...
    def getEncodedActivationCode(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, downloadableSubscription: 'DownloadableSubscription'): ...
        @typing.overload
        def __init__(self, string: str): ...
        def build(self) -> 'DownloadableSubscription': ...
        def setConfirmationCode(self, string: str) -> 'DownloadableSubscription.Builder': ...
        def setEncodedActivationCode(self, string: str) -> 'DownloadableSubscription.Builder': ...

class EuiccInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str): ...
    def describeContents(self) -> int: ...
    def getOsVersion(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class EuiccManager:
    ACTION_MANAGE_EMBEDDED_SUBSCRIPTIONS: typing.ClassVar[str] = ...
    ACTION_NOTIFY_CARRIER_SETUP_INCOMPLETE: typing.ClassVar[str] = ...
    ACTION_START_EUICC_ACTIVATION: typing.ClassVar[str] = ...
    EMBEDDED_SUBSCRIPTION_RESULT_ERROR: typing.ClassVar[int] = ...
    EMBEDDED_SUBSCRIPTION_RESULT_OK: typing.ClassVar[int] = ...
    EMBEDDED_SUBSCRIPTION_RESULT_RESOLVABLE_ERROR: typing.ClassVar[int] = ...
    ERROR_ADDRESS_MISSING: typing.ClassVar[int] = ...
    ERROR_CARRIER_LOCKED: typing.ClassVar[int] = ...
    ERROR_CERTIFICATE_ERROR: typing.ClassVar[int] = ...
    ERROR_CONNECTION_ERROR: typing.ClassVar[int] = ...
    ERROR_DISALLOWED_BY_PPR: typing.ClassVar[int] = ...
    ERROR_EUICC_INSUFFICIENT_MEMORY: typing.ClassVar[int] = ...
    ERROR_EUICC_MISSING: typing.ClassVar[int] = ...
    ERROR_INCOMPATIBLE_CARRIER: typing.ClassVar[int] = ...
    ERROR_INSTALL_PROFILE: typing.ClassVar[int] = ...
    ERROR_INVALID_ACTIVATION_CODE: typing.ClassVar[int] = ...
    ERROR_INVALID_CONFIRMATION_CODE: typing.ClassVar[int] = ...
    ERROR_INVALID_PORT: typing.ClassVar[int] = ...
    ERROR_INVALID_RESPONSE: typing.ClassVar[int] = ...
    ERROR_NO_PROFILES_AVAILABLE: typing.ClassVar[int] = ...
    ERROR_OPERATION_BUSY: typing.ClassVar[int] = ...
    ERROR_SIM_MISSING: typing.ClassVar[int] = ...
    ERROR_TIME_OUT: typing.ClassVar[int] = ...
    ERROR_UNSUPPORTED_VERSION: typing.ClassVar[int] = ...
    EUICC_MEMORY_FIELD_UNAVAILABLE: typing.ClassVar[int] = ...
    EXTRA_EMBEDDED_SUBSCRIPTION_DETAILED_CODE: typing.ClassVar[str] = ...
    EXTRA_EMBEDDED_SUBSCRIPTION_DOWNLOADABLE_SUBSCRIPTION: typing.ClassVar[str] = ...
    EXTRA_EMBEDDED_SUBSCRIPTION_ERROR_CODE: typing.ClassVar[str] = ...
    EXTRA_EMBEDDED_SUBSCRIPTION_OPERATION_CODE: typing.ClassVar[str] = ...
    EXTRA_EMBEDDED_SUBSCRIPTION_SMDX_REASON_CODE: typing.ClassVar[str] = ...
    EXTRA_EMBEDDED_SUBSCRIPTION_SMDX_SUBJECT_CODE: typing.ClassVar[str] = ...
    EXTRA_USE_QR_SCANNER: typing.ClassVar[str] = ...
    META_DATA_CARRIER_ICON: typing.ClassVar[str] = ...
    OPERATION_APDU: typing.ClassVar[int] = ...
    OPERATION_DOWNLOAD: typing.ClassVar[int] = ...
    OPERATION_EUICC_CARD: typing.ClassVar[int] = ...
    OPERATION_EUICC_GSMA: typing.ClassVar[int] = ...
    OPERATION_HTTP: typing.ClassVar[int] = ...
    OPERATION_METADATA: typing.ClassVar[int] = ...
    OPERATION_SIM_SLOT: typing.ClassVar[int] = ...
    OPERATION_SMDX: typing.ClassVar[int] = ...
    OPERATION_SMDX_SUBJECT_REASON_CODE: typing.ClassVar[int] = ...
    OPERATION_SWITCH: typing.ClassVar[int] = ...
    OPERATION_SYSTEM: typing.ClassVar[int] = ...
    def createForCardId(self, int: int) -> 'EuiccManager': ...
    def deleteSubscription(self, int: int, pendingIntent: android.app.PendingIntent) -> None: ...
    def downloadSubscription(self, downloadableSubscription: DownloadableSubscription, boolean: bool, pendingIntent: android.app.PendingIntent) -> None: ...
    def getAvailableMemoryInBytes(self) -> int: ...
    def getEid(self) -> str: ...
    def getEuiccInfo(self) -> EuiccInfo: ...
    def isEnabled(self) -> bool: ...
    def isSimPortAvailable(self, int: int) -> bool: ...
    def startResolutionActivity(self, activity: android.app.Activity, int: int, intent: android.content.Intent, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def switchToSubscription(self, int: int, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def switchToSubscription(self, int: int, int2: int, pendingIntent: android.app.PendingIntent) -> None: ...
    def updateSubscriptionNickname(self, int: int, string: str, pendingIntent: android.app.PendingIntent) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.telephony.euicc")``.

    DownloadableSubscription: typing.Type[DownloadableSubscription]
    EuiccInfo: typing.Type[EuiccInfo]
    EuiccManager: typing.Type[EuiccManager]
