
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.health.connect.datatypes
import android.os
import java.time
import java.util
import typing



class ChangeLogTokenRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDataOriginFilters(self) -> java.util.Set[android.health.connect.datatypes.DataOrigin]: ...
    def getRecordTypes(self) -> java.util.Set[typing.Type[android.health.connect.datatypes.Record]]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addDataOriginFilter(self, dataOrigin: android.health.connect.datatypes.DataOrigin) -> 'ChangeLogTokenRequest.Builder': ...
        def addRecordType(self, class_: typing.Type[android.health.connect.datatypes.Record]) -> 'ChangeLogTokenRequest.Builder': ...
        def build(self) -> 'ChangeLogTokenRequest': ...

class ChangeLogTokenResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getToken(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ChangeLogsRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getPageSize(self) -> int: ...
    def getToken(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        def build(self) -> 'ChangeLogsRequest': ...
        def setPageSize(self, int: int) -> 'ChangeLogsRequest.Builder': ...

class ChangeLogsResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getDeletedLogs(self) -> java.util.List['ChangeLogsResponse.DeletedLog']: ...
    def getNextChangesToken(self) -> str: ...
    def getUpsertedRecords(self) -> java.util.List[android.health.connect.datatypes.Record]: ...
    def hasMorePages(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class DeletedLog:
        def __init__(self, string: str, long: int): ...
        def getDeletedRecordId(self) -> str: ...
        def getDeletedTime(self) -> java.time.Instant: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.health.connect.changelog")``.

    ChangeLogTokenRequest: typing.Type[ChangeLogTokenRequest]
    ChangeLogTokenResponse: typing.Type[ChangeLogTokenResponse]
    ChangeLogsRequest: typing.Type[ChangeLogsRequest]
    ChangeLogsResponse: typing.Type[ChangeLogsResponse]
