
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.pm
import android.os
import android.print_.pdf
import java.lang
import java.util
import jpype
import typing



class PageRange(android.os.Parcelable):
    ALL_PAGES: typing.ClassVar['PageRange'] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getEnd(self) -> int: ...
    def getStart(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PrintAttributes(android.os.Parcelable):
    COLOR_MODE_COLOR: typing.ClassVar[int] = ...
    COLOR_MODE_MONOCHROME: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DUPLEX_MODE_LONG_EDGE: typing.ClassVar[int] = ...
    DUPLEX_MODE_NONE: typing.ClassVar[int] = ...
    DUPLEX_MODE_SHORT_EDGE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getColorMode(self) -> int: ...
    def getDuplexMode(self) -> int: ...
    def getMediaSize(self) -> 'PrintAttributes.MediaSize': ...
    def getMinMargins(self) -> 'PrintAttributes.Margins': ...
    def getResolution(self) -> 'PrintAttributes.Resolution': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'PrintAttributes': ...
        def setColorMode(self, int: int) -> 'PrintAttributes.Builder': ...
        def setDuplexMode(self, int: int) -> 'PrintAttributes.Builder': ...
        def setMediaSize(self, mediaSize: 'PrintAttributes.MediaSize') -> 'PrintAttributes.Builder': ...
        def setMinMargins(self, margins: 'PrintAttributes.Margins') -> 'PrintAttributes.Builder': ...
        def setResolution(self, resolution: 'PrintAttributes.Resolution') -> 'PrintAttributes.Builder': ...
    class Margins:
        NO_MARGINS: typing.ClassVar['PrintAttributes.Margins'] = ...
        def __init__(self, int: int, int2: int, int3: int, int4: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getBottomMils(self) -> int: ...
        def getLeftMils(self) -> int: ...
        def getRightMils(self) -> int: ...
        def getTopMils(self) -> int: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
    class MediaSize:
        ANSI_C: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ANSI_D: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ANSI_E: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ANSI_F: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A0: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A1: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A10: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A3: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A5: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A6: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A7: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A8: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_A9: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B0: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B1: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B10: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B3: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B5: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B6: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B7: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B8: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_B9: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C0: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C1: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C10: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C3: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C5: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C6: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C7: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C8: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ISO_C9: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B0: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B1: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B10: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B3: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B5: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B6: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B7: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B8: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_B9: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JIS_EXEC: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_CHOU2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_CHOU3: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_CHOU4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_HAGAKI: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_KAHU: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_KAKU2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_OE_PHOTO_L: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_OUFUKU: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        JPN_YOU4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_ARCH_A: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_ARCH_B: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_ARCH_C: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_ARCH_D: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_ARCH_E: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_ARCH_E1: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_FOOLSCAP: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_GOVT_LETTER: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_INDEX_3X5: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_INDEX_4X6: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_INDEX_5X8: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_JUNIOR_LEGAL: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_LEDGER: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_LEGAL: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_LETTER: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_MONARCH: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_QUARTO: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_SUPER_B: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        NA_TABLOID: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        OM_DAI_PA_KAI: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        OM_JUURO_KU_KAI: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        OM_PA_KAI: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_1: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_10: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_16K: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_2: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_3: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_4: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_5: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_6: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_7: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_8: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        PRC_9: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ROC_16K: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        ROC_8K: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        UNKNOWN_LANDSCAPE: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        UNKNOWN_PORTRAIT: typing.ClassVar['PrintAttributes.MediaSize'] = ...
        def __init__(self, string: str, string2: str, int: int, int2: int): ...
        def asLandscape(self) -> 'PrintAttributes.MediaSize': ...
        def asPortrait(self) -> 'PrintAttributes.MediaSize': ...
        def equals(self, object: typing.Any) -> bool: ...
        def getHeightMils(self) -> int: ...
        def getId(self) -> str: ...
        def getLabel(self, packageManager: android.content.pm.PackageManager) -> str: ...
        def getWidthMils(self) -> int: ...
        def hashCode(self) -> int: ...
        def isPortrait(self) -> bool: ...
        def toString(self) -> str: ...
    class Resolution:
        def __init__(self, string: str, string2: str, int: int, int2: int): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getHorizontalDpi(self) -> int: ...
        def getId(self) -> str: ...
        def getLabel(self) -> str: ...
        def getVerticalDpi(self) -> int: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

class PrintDocumentAdapter:
    EXTRA_PRINT_PREVIEW: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onFinish(self) -> None: ...
    def onLayout(self, printAttributes: PrintAttributes, printAttributes2: PrintAttributes, cancellationSignal: android.os.CancellationSignal, layoutResultCallback: 'PrintDocumentAdapter.LayoutResultCallback', bundle: android.os.Bundle) -> None: ...
    def onStart(self) -> None: ...
    def onWrite(self, pageRangeArray: typing.Union[typing.List[PageRange], jpype.JArray], parcelFileDescriptor: android.os.ParcelFileDescriptor, cancellationSignal: android.os.CancellationSignal, writeResultCallback: 'PrintDocumentAdapter.WriteResultCallback') -> None: ...
    class LayoutResultCallback:
        def onLayoutCancelled(self) -> None: ...
        def onLayoutFailed(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
        def onLayoutFinished(self, printDocumentInfo: 'PrintDocumentInfo', boolean: bool) -> None: ...
    class WriteResultCallback:
        def onWriteCancelled(self) -> None: ...
        def onWriteFailed(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
        def onWriteFinished(self, pageRangeArray: typing.Union[typing.List[PageRange], jpype.JArray]) -> None: ...

class PrintDocumentInfo(android.os.Parcelable):
    CONTENT_TYPE_DOCUMENT: typing.ClassVar[int] = ...
    CONTENT_TYPE_PHOTO: typing.ClassVar[int] = ...
    CONTENT_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PAGE_COUNT_UNKNOWN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getContentType(self) -> int: ...
    def getDataSize(self) -> int: ...
    def getName(self) -> str: ...
    def getPageCount(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        def build(self) -> 'PrintDocumentInfo': ...
        def setContentType(self, int: int) -> 'PrintDocumentInfo.Builder': ...
        def setPageCount(self, int: int) -> 'PrintDocumentInfo.Builder': ...

class PrintJob:
    def cancel(self) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getId(self) -> 'PrintJobId': ...
    def getInfo(self) -> 'PrintJobInfo': ...
    def hashCode(self) -> int: ...
    def isBlocked(self) -> bool: ...
    def isCancelled(self) -> bool: ...
    def isCompleted(self) -> bool: ...
    def isFailed(self) -> bool: ...
    def isQueued(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def restart(self) -> None: ...

class PrintJobId(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PrintJobInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STATE_BLOCKED: typing.ClassVar[int] = ...
    STATE_CANCELED: typing.ClassVar[int] = ...
    STATE_COMPLETED: typing.ClassVar[int] = ...
    STATE_CREATED: typing.ClassVar[int] = ...
    STATE_FAILED: typing.ClassVar[int] = ...
    STATE_QUEUED: typing.ClassVar[int] = ...
    STATE_STARTED: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getAdvancedIntOption(self, string: str) -> int: ...
    def getAdvancedStringOption(self, string: str) -> str: ...
    def getAttributes(self) -> PrintAttributes: ...
    def getCopies(self) -> int: ...
    def getCreationTime(self) -> int: ...
    def getId(self) -> PrintJobId: ...
    def getLabel(self) -> str: ...
    def getPages(self) -> typing.MutableSequence[PageRange]: ...
    def getPrinterId(self) -> 'PrinterId': ...
    def getState(self) -> int: ...
    def hasAdvancedOption(self, string: str) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, printJobInfo: 'PrintJobInfo'): ...
        def build(self) -> 'PrintJobInfo': ...
        @typing.overload
        def putAdvancedOption(self, string: str, int: int) -> None: ...
        @typing.overload
        def putAdvancedOption(self, string: str, string2: str) -> None: ...
        def setAttributes(self, printAttributes: PrintAttributes) -> None: ...
        def setCopies(self, int: int) -> None: ...
        def setPages(self, pageRangeArray: typing.Union[typing.List[PageRange], jpype.JArray]) -> None: ...

class PrintManager:
    def getPrintJobs(self) -> java.util.List[PrintJob]: ...
    def isPrintServiceEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def print_(self, string: str, printDocumentAdapter: PrintDocumentAdapter, printAttributes: PrintAttributes) -> PrintJob: ...

class PrinterCapabilitiesInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getColorModes(self) -> int: ...
    def getDefaults(self) -> PrintAttributes: ...
    def getDuplexModes(self) -> int: ...
    def getMediaSizes(self) -> java.util.List[PrintAttributes.MediaSize]: ...
    def getMinMargins(self) -> PrintAttributes.Margins: ...
    def getResolutions(self) -> java.util.List[PrintAttributes.Resolution]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, printerId: 'PrinterId'): ...
        def addMediaSize(self, mediaSize: PrintAttributes.MediaSize, boolean: bool) -> 'PrinterCapabilitiesInfo.Builder': ...
        def addResolution(self, resolution: PrintAttributes.Resolution, boolean: bool) -> 'PrinterCapabilitiesInfo.Builder': ...
        def build(self) -> 'PrinterCapabilitiesInfo': ...
        def setColorModes(self, int: int, int2: int) -> 'PrinterCapabilitiesInfo.Builder': ...
        def setDuplexModes(self, int: int, int2: int) -> 'PrinterCapabilitiesInfo.Builder': ...
        def setMinMargins(self, margins: PrintAttributes.Margins) -> 'PrinterCapabilitiesInfo.Builder': ...

class PrinterId(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLocalId(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PrinterInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STATUS_BUSY: typing.ClassVar[int] = ...
    STATUS_IDLE: typing.ClassVar[int] = ...
    STATUS_UNAVAILABLE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCapabilities(self) -> PrinterCapabilitiesInfo: ...
    def getDescription(self) -> str: ...
    def getId(self) -> PrinterId: ...
    def getName(self) -> str: ...
    def getStatus(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, printerId: PrinterId, string: str, int: int): ...
        @typing.overload
        def __init__(self, printerInfo: 'PrinterInfo'): ...
        def build(self) -> 'PrinterInfo': ...
        def setCapabilities(self, printerCapabilitiesInfo: PrinterCapabilitiesInfo) -> 'PrinterInfo.Builder': ...
        def setDescription(self, string: str) -> 'PrinterInfo.Builder': ...
        def setHasCustomPrinterIcon(self, boolean: bool) -> 'PrinterInfo.Builder': ...
        def setIconResourceId(self, int: int) -> 'PrinterInfo.Builder': ...
        def setInfoIntent(self, pendingIntent: android.app.PendingIntent) -> 'PrinterInfo.Builder': ...
        def setName(self, string: str) -> 'PrinterInfo.Builder': ...
        def setStatus(self, int: int) -> 'PrinterInfo.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.print_")``.

    PageRange: typing.Type[PageRange]
    PrintAttributes: typing.Type[PrintAttributes]
    PrintDocumentAdapter: typing.Type[PrintDocumentAdapter]
    PrintDocumentInfo: typing.Type[PrintDocumentInfo]
    PrintJob: typing.Type[PrintJob]
    PrintJobId: typing.Type[PrintJobId]
    PrintJobInfo: typing.Type[PrintJobInfo]
    PrintManager: typing.Type[PrintManager]
    PrinterCapabilitiesInfo: typing.Type[PrinterCapabilitiesInfo]
    PrinterId: typing.Type[PrinterId]
    PrinterInfo: typing.Type[PrinterInfo]
    pdf: android.print_.pdf.__module_protocol__
