
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import typing



class BloodGlucose(java.lang.Comparable['BloodGlucose']):
    def compareTo(self, bloodGlucose: 'BloodGlucose') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromMillimolesPerLiter(double: float) -> 'BloodGlucose': ...
    def getInMillimolesPerLiter(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Energy(java.lang.Comparable['Energy']):
    def compareTo(self, energy: 'Energy') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromCalories(double: float) -> 'Energy': ...
    def getInCalories(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Length(java.lang.Comparable['Length']):
    def compareTo(self, length: 'Length') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromMeters(double: float) -> 'Length': ...
    def getInMeters(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Mass(java.lang.Comparable['Mass']):
    def compareTo(self, mass: 'Mass') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromGrams(double: float) -> 'Mass': ...
    def getInGrams(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Percentage(java.lang.Comparable['Percentage']):
    def compareTo(self, percentage: 'Percentage') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromValue(double: float) -> 'Percentage': ...
    def getValue(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Power(java.lang.Comparable['Power']):
    def compareTo(self, power: 'Power') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromWatts(double: float) -> 'Power': ...
    def getInWatts(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Pressure(java.lang.Comparable['Pressure']):
    def compareTo(self, pressure: 'Pressure') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromMillimetersOfMercury(double: float) -> 'Pressure': ...
    def getInMillimetersOfMercury(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Temperature(java.lang.Comparable['Temperature']):
    def compareTo(self, temperature: 'Temperature') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromCelsius(double: float) -> 'Temperature': ...
    def getInCelsius(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TemperatureDelta(java.lang.Comparable['TemperatureDelta']):
    def compareTo(self, temperatureDelta: 'TemperatureDelta') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromCelsius(double: float) -> 'TemperatureDelta': ...
    def getInCelsius(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Velocity(java.lang.Comparable['Velocity']):
    def compareTo(self, velocity: 'Velocity') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromMetersPerSecond(double: float) -> 'Velocity': ...
    def getInMetersPerSecond(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Volume(java.lang.Comparable['Volume']):
    def compareTo(self, volume: 'Volume') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromLiters(double: float) -> 'Volume': ...
    def getInLiters(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.health.connect.datatypes.units")``.

    BloodGlucose: typing.Type[BloodGlucose]
    Energy: typing.Type[Energy]
    Length: typing.Type[Length]
    Mass: typing.Type[Mass]
    Percentage: typing.Type[Percentage]
    Power: typing.Type[Power]
    Pressure: typing.Type[Pressure]
    Temperature: typing.Type[Temperature]
    TemperatureDelta: typing.Type[TemperatureDelta]
    Velocity: typing.Type[Velocity]
    Volume: typing.Type[Volume]
