
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.pm
import android.net
import android.os
import java.lang
import java.util
import jpype
import typing



class Condition(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FLAG_RELEVANT_ALWAYS: typing.ClassVar[int] = ...
    FLAG_RELEVANT_NOW: typing.ClassVar[int] = ...
    SCHEME: typing.ClassVar[str] = ...
    SOURCE_CONTEXT: typing.ClassVar[int] = ...
    SOURCE_SCHEDULE: typing.ClassVar[int] = ...
    SOURCE_UNKNOWN: typing.ClassVar[int] = ...
    SOURCE_USER_ACTION: typing.ClassVar[int] = ...
    STATE_ERROR: typing.ClassVar[int] = ...
    STATE_FALSE: typing.ClassVar[int] = ...
    STATE_TRUE: typing.ClassVar[int] = ...
    STATE_UNKNOWN: typing.ClassVar[int] = ...
    flags: int = ...
    icon: int = ...
    id: android.net.Uri = ...
    line1: str = ...
    line2: str = ...
    source: int = ...
    state: int = ...
    summary: str = ...
    @typing.overload
    def __init__(self, uri: android.net.Uri, string: str, int: int): ...
    @typing.overload
    def __init__(self, uri: android.net.Uri, string: str, int: int, int2: int): ...
    @typing.overload
    def __init__(self, uri: android.net.Uri, string: str, string2: str, string3: str, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, uri: android.net.Uri, string: str, string2: str, string3: str, int: int, int2: int, int3: int, int4: int): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def copy(self) -> 'Condition': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def isValidId(uri: android.net.Uri, string: str) -> bool: ...
    @staticmethod
    def newId(context: android.content.Context) -> android.net.Uri.Builder: ...
    @staticmethod
    def relevanceToString(int: int) -> str: ...
    @staticmethod
    def stateToString(int: int) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ConditionProviderService(android.app.Service):
    EXTRA_RULE_ID: typing.ClassVar[str] = ...
    META_DATA_CONFIGURATION_ACTIVITY: typing.ClassVar[str] = ...
    META_DATA_RULE_INSTANCE_LIMIT: typing.ClassVar[str] = ...
    META_DATA_RULE_TYPE: typing.ClassVar[str] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def notifyCondition(self, condition: Condition) -> None: ...
    def notifyConditions(self, *condition: Condition) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onConnected(self) -> None: ...
    def onRequestConditions(self, int: int) -> None: ...
    def onSubscribe(self, uri: android.net.Uri) -> None: ...
    def onUnsubscribe(self, uri: android.net.Uri) -> None: ...
    @staticmethod
    def requestRebind(componentName: android.content.ComponentName) -> None: ...
    def requestUnbind(self) -> None: ...

class NotificationListenerService(android.app.Service):
    ACTION_SETTINGS_HOME: typing.ClassVar[str] = ...
    FLAG_FILTER_TYPE_ALERTING: typing.ClassVar[int] = ...
    FLAG_FILTER_TYPE_CONVERSATIONS: typing.ClassVar[int] = ...
    FLAG_FILTER_TYPE_ONGOING: typing.ClassVar[int] = ...
    FLAG_FILTER_TYPE_SILENT: typing.ClassVar[int] = ...
    HINT_HOST_DISABLE_CALL_EFFECTS: typing.ClassVar[int] = ...
    HINT_HOST_DISABLE_EFFECTS: typing.ClassVar[int] = ...
    HINT_HOST_DISABLE_NOTIFICATION_EFFECTS: typing.ClassVar[int] = ...
    INTERRUPTION_FILTER_ALARMS: typing.ClassVar[int] = ...
    INTERRUPTION_FILTER_ALL: typing.ClassVar[int] = ...
    INTERRUPTION_FILTER_NONE: typing.ClassVar[int] = ...
    INTERRUPTION_FILTER_PRIORITY: typing.ClassVar[int] = ...
    INTERRUPTION_FILTER_UNKNOWN: typing.ClassVar[int] = ...
    META_DATA_DEFAULT_AUTOBIND: typing.ClassVar[str] = ...
    META_DATA_DEFAULT_FILTER_TYPES: typing.ClassVar[str] = ...
    META_DATA_DISABLED_FILTER_TYPES: typing.ClassVar[str] = ...
    NOTIFICATION_CHANNEL_OR_GROUP_ADDED: typing.ClassVar[int] = ...
    NOTIFICATION_CHANNEL_OR_GROUP_DELETED: typing.ClassVar[int] = ...
    NOTIFICATION_CHANNEL_OR_GROUP_UPDATED: typing.ClassVar[int] = ...
    REASON_APP_CANCEL: typing.ClassVar[int] = ...
    REASON_APP_CANCEL_ALL: typing.ClassVar[int] = ...
    REASON_ASSISTANT_CANCEL: typing.ClassVar[int] = ...
    REASON_CANCEL: typing.ClassVar[int] = ...
    REASON_CANCEL_ALL: typing.ClassVar[int] = ...
    REASON_CHANNEL_BANNED: typing.ClassVar[int] = ...
    REASON_CHANNEL_REMOVED: typing.ClassVar[int] = ...
    REASON_CLEAR_DATA: typing.ClassVar[int] = ...
    REASON_CLICK: typing.ClassVar[int] = ...
    REASON_ERROR: typing.ClassVar[int] = ...
    REASON_GROUP_OPTIMIZATION: typing.ClassVar[int] = ...
    REASON_GROUP_SUMMARY_CANCELED: typing.ClassVar[int] = ...
    REASON_LISTENER_CANCEL: typing.ClassVar[int] = ...
    REASON_LISTENER_CANCEL_ALL: typing.ClassVar[int] = ...
    REASON_LOCKDOWN: typing.ClassVar[int] = ...
    REASON_PACKAGE_BANNED: typing.ClassVar[int] = ...
    REASON_PACKAGE_CHANGED: typing.ClassVar[int] = ...
    REASON_PACKAGE_SUSPENDED: typing.ClassVar[int] = ...
    REASON_PROFILE_TURNED_OFF: typing.ClassVar[int] = ...
    REASON_SNOOZED: typing.ClassVar[int] = ...
    REASON_TIMEOUT: typing.ClassVar[int] = ...
    REASON_UNAUTOBUNDLED: typing.ClassVar[int] = ...
    REASON_USER_STOPPED: typing.ClassVar[int] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SUPPRESSED_EFFECT_SCREEN_OFF: typing.ClassVar[int] = ...
    SUPPRESSED_EFFECT_SCREEN_ON: typing.ClassVar[int] = ...
    def __init__(self): ...
    def cancelAllNotifications(self) -> None: ...
    @typing.overload
    def cancelNotification(self, string: str) -> None: ...
    @typing.overload
    def cancelNotification(self, string: str, string2: str, int: int) -> None: ...
    def cancelNotifications(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def clearRequestedListenerHints(self) -> None: ...
    @typing.overload
    def getActiveNotifications(self) -> typing.MutableSequence['StatusBarNotification']: ...
    @typing.overload
    def getActiveNotifications(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> typing.MutableSequence['StatusBarNotification']: ...
    def getCurrentInterruptionFilter(self) -> int: ...
    def getCurrentListenerHints(self) -> int: ...
    def getCurrentRanking(self) -> 'NotificationListenerService.RankingMap': ...
    def getNotificationChannelGroups(self, string: str, userHandle: android.os.UserHandle) -> java.util.List[android.app.NotificationChannelGroup]: ...
    def getNotificationChannels(self, string: str, userHandle: android.os.UserHandle) -> java.util.List[android.app.NotificationChannel]: ...
    def getSnoozedNotifications(self) -> typing.MutableSequence['StatusBarNotification']: ...
    def migrateNotificationFilter(self, int: int, list: java.util.List[str]) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onDestroy(self) -> None: ...
    def onInterruptionFilterChanged(self, int: int) -> None: ...
    def onListenerConnected(self) -> None: ...
    def onListenerDisconnected(self) -> None: ...
    def onListenerHintsChanged(self, int: int) -> None: ...
    def onNotificationChannelGroupModified(self, string: str, userHandle: android.os.UserHandle, notificationChannelGroup: android.app.NotificationChannelGroup, int: int) -> None: ...
    def onNotificationChannelModified(self, string: str, userHandle: android.os.UserHandle, notificationChannel: android.app.NotificationChannel, int: int) -> None: ...
    @typing.overload
    def onNotificationPosted(self, statusBarNotification: 'StatusBarNotification') -> None: ...
    @typing.overload
    def onNotificationPosted(self, statusBarNotification: 'StatusBarNotification', rankingMap: 'NotificationListenerService.RankingMap') -> None: ...
    def onNotificationRankingUpdate(self, rankingMap: 'NotificationListenerService.RankingMap') -> None: ...
    @typing.overload
    def onNotificationRemoved(self, statusBarNotification: 'StatusBarNotification') -> None: ...
    @typing.overload
    def onNotificationRemoved(self, statusBarNotification: 'StatusBarNotification', rankingMap: 'NotificationListenerService.RankingMap') -> None: ...
    @typing.overload
    def onNotificationRemoved(self, statusBarNotification: 'StatusBarNotification', rankingMap: 'NotificationListenerService.RankingMap', int: int) -> None: ...
    def onSilentStatusBarIconsVisibilityChanged(self, boolean: bool) -> None: ...
    def requestInterruptionFilter(self, int: int) -> None: ...
    def requestListenerHints(self, int: int) -> None: ...
    @staticmethod
    def requestRebind(componentName: android.content.ComponentName) -> None: ...
    @typing.overload
    def requestUnbind(self) -> None: ...
    @typing.overload
    @staticmethod
    def requestUnbind(componentName: android.content.ComponentName) -> None: ...
    def setNotificationsShown(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def snoozeNotification(self, string: str, long: int) -> None: ...
    def updateNotificationChannel(self, string: str, userHandle: android.os.UserHandle, notificationChannel: android.app.NotificationChannel) -> None: ...
    class Ranking:
        USER_SENTIMENT_NEGATIVE: typing.ClassVar[int] = ...
        USER_SENTIMENT_NEUTRAL: typing.ClassVar[int] = ...
        USER_SENTIMENT_POSITIVE: typing.ClassVar[int] = ...
        VISIBILITY_NO_OVERRIDE: typing.ClassVar[int] = ...
        def __init__(self): ...
        def canBubble(self) -> bool: ...
        def canShowBadge(self) -> bool: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getChannel(self) -> android.app.NotificationChannel: ...
        def getConversationShortcutInfo(self) -> android.content.pm.ShortcutInfo: ...
        def getImportance(self) -> int: ...
        def getImportanceExplanation(self) -> java.lang.CharSequence: ...
        def getKey(self) -> str: ...
        def getLastAudiblyAlertedMillis(self) -> int: ...
        def getLockscreenVisibilityOverride(self) -> int: ...
        def getOverrideGroupKey(self) -> str: ...
        def getRank(self) -> int: ...
        def getSmartActions(self) -> java.util.List[android.app.Notification.Action]: ...
        def getSmartReplies(self) -> java.util.List[java.lang.CharSequence]: ...
        def getSuppressedVisualEffects(self) -> int: ...
        def getUserSentiment(self) -> int: ...
        def isAmbient(self) -> bool: ...
        def isConversation(self) -> bool: ...
        def isSuspended(self) -> bool: ...
        def matchesInterruptionFilter(self) -> bool: ...
    class RankingMap(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getOrderedKeys(self) -> typing.MutableSequence[str]: ...
        def getRanking(self, string: str, ranking: 'NotificationListenerService.Ranking') -> bool: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StatusBarNotification(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, string: str, string2: str, int: int, string3: str, int2: int, int3: int, int4: int, notification: android.app.Notification, userHandle: android.os.UserHandle, long: int): ...
    def clone(self) -> 'StatusBarNotification': ...
    def describeContents(self) -> int: ...
    def getGroupKey(self) -> str: ...
    def getId(self) -> int: ...
    def getKey(self) -> str: ...
    def getNotification(self) -> android.app.Notification: ...
    def getOpPkg(self) -> str: ...
    def getOverrideGroupKey(self) -> str: ...
    def getPackageName(self) -> str: ...
    def getPostTime(self) -> int: ...
    def getTag(self) -> str: ...
    def getUid(self) -> int: ...
    def getUser(self) -> android.os.UserHandle: ...
    def getUserId(self) -> int: ...
    def isAppGroup(self) -> bool: ...
    def isClearable(self) -> bool: ...
    def isGroup(self) -> bool: ...
    def isOngoing(self) -> bool: ...
    def setOverrideGroupKey(self, string: str) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ZenDeviceEffects(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def shouldDimWallpaper(self) -> bool: ...
    def shouldDisplayGrayscale(self) -> bool: ...
    def shouldSuppressAmbientDisplay(self) -> bool: ...
    def shouldUseNightMode(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, zenDeviceEffects: 'ZenDeviceEffects'): ...
        def build(self) -> 'ZenDeviceEffects': ...
        def setShouldDimWallpaper(self, boolean: bool) -> 'ZenDeviceEffects.Builder': ...
        def setShouldDisplayGrayscale(self, boolean: bool) -> 'ZenDeviceEffects.Builder': ...
        def setShouldSuppressAmbientDisplay(self, boolean: bool) -> 'ZenDeviceEffects.Builder': ...
        def setShouldUseNightMode(self, boolean: bool) -> 'ZenDeviceEffects.Builder': ...

class ZenPolicy(android.os.Parcelable):
    CONVERSATION_SENDERS_ANYONE: typing.ClassVar[int] = ...
    CONVERSATION_SENDERS_IMPORTANT: typing.ClassVar[int] = ...
    CONVERSATION_SENDERS_NONE: typing.ClassVar[int] = ...
    CONVERSATION_SENDERS_UNSET: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PEOPLE_TYPE_ANYONE: typing.ClassVar[int] = ...
    PEOPLE_TYPE_CONTACTS: typing.ClassVar[int] = ...
    PEOPLE_TYPE_NONE: typing.ClassVar[int] = ...
    PEOPLE_TYPE_STARRED: typing.ClassVar[int] = ...
    PEOPLE_TYPE_UNSET: typing.ClassVar[int] = ...
    STATE_ALLOW: typing.ClassVar[int] = ...
    STATE_DISALLOW: typing.ClassVar[int] = ...
    STATE_UNSET: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPriorityCallSenders(self) -> int: ...
    def getPriorityCategoryAlarms(self) -> int: ...
    def getPriorityCategoryCalls(self) -> int: ...
    def getPriorityCategoryConversations(self) -> int: ...
    def getPriorityCategoryEvents(self) -> int: ...
    def getPriorityCategoryMedia(self) -> int: ...
    def getPriorityCategoryMessages(self) -> int: ...
    def getPriorityCategoryReminders(self) -> int: ...
    def getPriorityCategoryRepeatCallers(self) -> int: ...
    def getPriorityCategorySystem(self) -> int: ...
    def getPriorityChannelsAllowed(self) -> int: ...
    def getPriorityConversationSenders(self) -> int: ...
    def getPriorityMessageSenders(self) -> int: ...
    def getVisualEffectAmbient(self) -> int: ...
    def getVisualEffectBadge(self) -> int: ...
    def getVisualEffectFullScreenIntent(self) -> int: ...
    def getVisualEffectLights(self) -> int: ...
    def getVisualEffectNotificationList(self) -> int: ...
    def getVisualEffectPeek(self) -> int: ...
    def getVisualEffectStatusBar(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def allowAlarms(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def allowAllSounds(self) -> 'ZenPolicy.Builder': ...
        def allowCalls(self, int: int) -> 'ZenPolicy.Builder': ...
        def allowConversations(self, int: int) -> 'ZenPolicy.Builder': ...
        def allowEvents(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def allowMedia(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def allowMessages(self, int: int) -> 'ZenPolicy.Builder': ...
        def allowPriorityChannels(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def allowReminders(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def allowRepeatCallers(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def allowSystem(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def build(self) -> 'ZenPolicy': ...
        def disallowAllSounds(self) -> 'ZenPolicy.Builder': ...
        def hideAllVisualEffects(self) -> 'ZenPolicy.Builder': ...
        def showAllVisualEffects(self) -> 'ZenPolicy.Builder': ...
        def showBadges(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def showFullScreenIntent(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def showInAmbientDisplay(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def showInNotificationList(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def showLights(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def showPeeking(self, boolean: bool) -> 'ZenPolicy.Builder': ...
        def showStatusBarIcons(self, boolean: bool) -> 'ZenPolicy.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.notification")``.

    Condition: typing.Type[Condition]
    ConditionProviderService: typing.Type[ConditionProviderService]
    NotificationListenerService: typing.Type[NotificationListenerService]
    StatusBarNotification: typing.Type[StatusBarNotification]
    ZenDeviceEffects: typing.Type[ZenDeviceEffects]
    ZenPolicy: typing.Type[ZenPolicy]
