
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.net
import android.os
import java.lang
import java.net
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class AttachCallback:
    def __init__(self): ...
    def onAttachFailed(self) -> None: ...
    def onAttached(self, wifiAwareSession: 'WifiAwareSession') -> None: ...
    def onAwareSessionTerminated(self) -> None: ...

class AwarePairingConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PAIRING_BOOTSTRAPPING_NFC_READER: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_NFC_TAG: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_OPPORTUNISTIC: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_PASSPHRASE_DISPLAY: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_PASSPHRASE_KEYPAD: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_PIN_CODE_DISPLAY: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_PIN_CODE_KEYPAD: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_QR_DISPLAY: typing.ClassVar[int] = ...
    PAIRING_BOOTSTRAPPING_QR_SCAN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBootstrappingMethods(self) -> int: ...
    def hashCode(self) -> int: ...
    def isPairingCacheEnabled(self) -> bool: ...
    def isPairingSetupEnabled(self) -> bool: ...
    def isPairingVerificationEnabled(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AwarePairingConfig': ...
        def setBootstrappingMethods(self, int: int) -> 'AwarePairingConfig.Builder': ...
        def setPairingCacheEnabled(self, boolean: bool) -> 'AwarePairingConfig.Builder': ...
        def setPairingSetupEnabled(self, boolean: bool) -> 'AwarePairingConfig.Builder': ...
        def setPairingVerificationEnabled(self, boolean: bool) -> 'AwarePairingConfig.Builder': ...

class AwareResources(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int): ...
    def describeContents(self) -> int: ...
    def getAvailableDataPathsCount(self) -> int: ...
    def getAvailablePublishSessionsCount(self) -> int: ...
    def getAvailableSubscribeSessionsCount(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Characteristics(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_128: typing.ClassVar[int] = ...
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_256: typing.ClassVar[int] = ...
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_PASN_128: typing.ClassVar[int] = ...
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_PASN_256: typing.ClassVar[int] = ...
    WIFI_AWARE_CIPHER_SUITE_NCS_SK_128: typing.ClassVar[int] = ...
    WIFI_AWARE_CIPHER_SUITE_NCS_SK_256: typing.ClassVar[int] = ...
    WIFI_AWARE_CIPHER_SUITE_NONE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getMaxMatchFilterLength(self) -> int: ...
    def getMaxServiceNameLength(self) -> int: ...
    def getMaxServiceSpecificInfoLength(self) -> int: ...
    def getNumberOfSupportedDataInterfaces(self) -> int: ...
    def getNumberOfSupportedDataPaths(self) -> int: ...
    def getNumberOfSupportedPublishSessions(self) -> int: ...
    def getNumberOfSupportedSubscribeSessions(self) -> int: ...
    def getSupportedCipherSuites(self) -> int: ...
    def getSupportedPairingCipherSuites(self) -> int: ...
    def isAwarePairingSupported(self) -> bool: ...
    def isInstantCommunicationModeSupported(self) -> bool: ...
    def isSuspensionSupported(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DiscoverySession(java.lang.AutoCloseable):
    def acceptPairingRequest(self, int: int, peerHandle: 'PeerHandle', string: str, int2: int, string2: str) -> None: ...
    def close(self) -> None: ...
    def createNetworkSpecifierOpen(self, peerHandle: 'PeerHandle') -> android.net.NetworkSpecifier: ...
    def createNetworkSpecifierPassphrase(self, peerHandle: 'PeerHandle', string: str) -> android.net.NetworkSpecifier: ...
    def initiateBootstrappingRequest(self, peerHandle: 'PeerHandle', int: int) -> None: ...
    def initiatePairingRequest(self, peerHandle: 'PeerHandle', string: str, int: int, string2: str) -> None: ...
    def rejectPairingRequest(self, int: int, peerHandle: 'PeerHandle') -> None: ...
    def sendMessage(self, peerHandle: 'PeerHandle', int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class DiscoverySessionCallback:
    def __init__(self): ...
    def onBootstrappingFailed(self, peerHandle: 'PeerHandle') -> None: ...
    def onBootstrappingSucceeded(self, peerHandle: 'PeerHandle', int: int) -> None: ...
    def onMessageReceived(self, peerHandle: 'PeerHandle', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def onMessageSendFailed(self, int: int) -> None: ...
    def onMessageSendSucceeded(self, int: int) -> None: ...
    def onPairingSetupFailed(self, peerHandle: 'PeerHandle') -> None: ...
    def onPairingSetupRequestReceived(self, peerHandle: 'PeerHandle', int: int) -> None: ...
    def onPairingSetupSucceeded(self, peerHandle: 'PeerHandle', string: str) -> None: ...
    def onPairingVerificationFailed(self, peerHandle: 'PeerHandle') -> None: ...
    def onPairingVerificationSucceed(self, peerHandle: 'PeerHandle', string: str) -> None: ...
    def onPublishStarted(self, publishDiscoverySession: 'PublishDiscoverySession') -> None: ...
    @typing.overload
    def onServiceDiscovered(self, peerHandle: 'PeerHandle', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], list: java.util.List[typing.Union[typing.List[int], jpype.JArray, bytes]]) -> None: ...
    @typing.overload
    def onServiceDiscovered(self, serviceDiscoveryInfo: 'ServiceDiscoveryInfo') -> None: ...
    @typing.overload
    def onServiceDiscoveredWithinRange(self, peerHandle: 'PeerHandle', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], list: java.util.List[typing.Union[typing.List[int], jpype.JArray, bytes]], int: int) -> None: ...
    @typing.overload
    def onServiceDiscoveredWithinRange(self, serviceDiscoveryInfo: 'ServiceDiscoveryInfo', int: int) -> None: ...
    def onServiceLost(self, peerHandle: 'PeerHandle', int: int) -> None: ...
    def onSessionConfigFailed(self) -> None: ...
    def onSessionConfigUpdated(self) -> None: ...
    def onSessionTerminated(self) -> None: ...
    def onSubscribeStarted(self, subscribeDiscoverySession: 'SubscribeDiscoverySession') -> None: ...

class IdentityChangedListener:
    CLUSTER_CHANGE_EVENT_JOINED: typing.ClassVar[int] = ...
    CLUSTER_CHANGE_EVENT_STARTED: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onClusterIdChanged(self, int: int, macAddress: android.net.MacAddress) -> None: ...
    def onIdentityChanged(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class PeerHandle:
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class PublishConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PUBLISH_TYPE_SOLICITED: typing.ClassVar[int] = ...
    PUBLISH_TYPE_UNSOLICITED: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getInstantCommunicationBand(self) -> int: ...
    def getPairingConfig(self) -> AwarePairingConfig: ...
    def getSecurityConfig(self) -> 'WifiAwareDataPathSecurityConfig': ...
    def hashCode(self) -> int: ...
    def isInstantCommunicationModeEnabled(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'PublishConfig': ...
        def setDataPathSecurityConfig(self, wifiAwareDataPathSecurityConfig: 'WifiAwareDataPathSecurityConfig') -> 'PublishConfig.Builder': ...
        def setInstantCommunicationModeEnabled(self, boolean: bool, int: int) -> 'PublishConfig.Builder': ...
        def setMatchFilter(self, list: java.util.List[typing.Union[typing.List[int], jpype.JArray, bytes]]) -> 'PublishConfig.Builder': ...
        def setPairingConfig(self, awarePairingConfig: AwarePairingConfig) -> 'PublishConfig.Builder': ...
        def setPublishType(self, int: int) -> 'PublishConfig.Builder': ...
        def setRangingEnabled(self, boolean: bool) -> 'PublishConfig.Builder': ...
        def setServiceName(self, string: str) -> 'PublishConfig.Builder': ...
        def setServiceSpecificInfo(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'PublishConfig.Builder': ...
        def setTerminateNotificationEnabled(self, boolean: bool) -> 'PublishConfig.Builder': ...
        def setTtlSec(self, int: int) -> 'PublishConfig.Builder': ...

class ServiceDiscoveryInfo:
    def getMatchFilters(self) -> java.util.List[typing.MutableSequence[int]]: ...
    def getPairedAlias(self) -> str: ...
    def getPairingConfig(self) -> AwarePairingConfig: ...
    def getPeerCipherSuite(self) -> int: ...
    def getPeerHandle(self) -> PeerHandle: ...
    def getScid(self) -> typing.MutableSequence[int]: ...
    def getServiceSpecificInfo(self) -> typing.MutableSequence[int]: ...

class SubscribeConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SUBSCRIBE_TYPE_ACTIVE: typing.ClassVar[int] = ...
    SUBSCRIBE_TYPE_PASSIVE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getInstantCommunicationBand(self) -> int: ...
    def getPairingConfig(self) -> AwarePairingConfig: ...
    def hashCode(self) -> int: ...
    def isInstantCommunicationModeEnabled(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'SubscribeConfig': ...
        def setInstantCommunicationModeEnabled(self, boolean: bool, int: int) -> 'SubscribeConfig.Builder': ...
        def setMatchFilter(self, list: java.util.List[typing.Union[typing.List[int], jpype.JArray, bytes]]) -> 'SubscribeConfig.Builder': ...
        def setMaxDistanceMm(self, int: int) -> 'SubscribeConfig.Builder': ...
        def setMinDistanceMm(self, int: int) -> 'SubscribeConfig.Builder': ...
        def setPairingConfig(self, awarePairingConfig: AwarePairingConfig) -> 'SubscribeConfig.Builder': ...
        def setServiceName(self, string: str) -> 'SubscribeConfig.Builder': ...
        def setServiceSpecificInfo(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'SubscribeConfig.Builder': ...
        def setSubscribeType(self, int: int) -> 'SubscribeConfig.Builder': ...
        def setTerminateNotificationEnabled(self, boolean: bool) -> 'SubscribeConfig.Builder': ...
        def setTtlSec(self, int: int) -> 'SubscribeConfig.Builder': ...

class WifiAwareChannelInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getChannelBandwidth(self) -> int: ...
    def getChannelFrequencyMhz(self) -> int: ...
    def getSpatialStreamCount(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiAwareDataPathSecurityConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCipherSuite(self) -> int: ...
    def getPmk(self) -> typing.MutableSequence[int]: ...
    def getPmkId(self) -> typing.MutableSequence[int]: ...
    def getPskPassphrase(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int): ...
        def build(self) -> 'WifiAwareDataPathSecurityConfig': ...
        def setPmk(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'WifiAwareDataPathSecurityConfig.Builder': ...
        def setPmkId(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'WifiAwareDataPathSecurityConfig.Builder': ...
        def setPskPassphrase(self, string: str) -> 'WifiAwareDataPathSecurityConfig.Builder': ...

class WifiAwareManager:
    ACTION_WIFI_AWARE_RESOURCE_CHANGED: typing.ClassVar[str] = ...
    ACTION_WIFI_AWARE_STATE_CHANGED: typing.ClassVar[str] = ...
    EXTRA_AWARE_RESOURCES: typing.ClassVar[str] = ...
    WIFI_AWARE_DATA_PATH_ROLE_INITIATOR: typing.ClassVar[int] = ...
    WIFI_AWARE_DATA_PATH_ROLE_RESPONDER: typing.ClassVar[int] = ...
    WIFI_AWARE_DISCOVERY_LOST_REASON_PEER_NOT_VISIBLE: typing.ClassVar[int] = ...
    WIFI_AWARE_DISCOVERY_LOST_REASON_UNKNOWN: typing.ClassVar[int] = ...
    @typing.overload
    def attach(self, attachCallback: AttachCallback, identityChangedListener: IdentityChangedListener, handler: android.os.Handler) -> None: ...
    @typing.overload
    def attach(self, attachCallback: AttachCallback, handler: android.os.Handler) -> None: ...
    def getAvailableAwareResources(self) -> AwareResources: ...
    def getCharacteristics(self) -> Characteristics: ...
    def getPairedDevices(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[java.util.List[str]], typing.Callable[[java.util.List[str]], None]]) -> None: ...
    def isAvailable(self) -> bool: ...
    def isDeviceAttached(self) -> bool: ...
    def isInstantCommunicationModeEnabled(self) -> bool: ...
    def isOpportunisticModeEnabled(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def isSetChannelOnDataPathSupported(self) -> bool: ...
    def removePairedDevice(self, string: str) -> None: ...
    def resetPairedDevices(self) -> None: ...
    def setOpportunisticModeEnabled(self, boolean: bool) -> None: ...

class WifiAwareNetworkInfo(android.net.TransportInfo, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getChannelInfoList(self) -> java.util.List[WifiAwareChannelInfo]: ...
    def getPeerIpv6Addr(self) -> java.net.Inet6Address: ...
    def getPort(self) -> int: ...
    def getTransportProtocol(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiAwareNetworkSpecifier(android.net.NetworkSpecifier, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def canBeSatisfiedBy(self, networkSpecifier: android.net.NetworkSpecifier) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getChannelFrequencyMhz(self) -> int: ...
    def getWifiAwareDataPathSecurityConfig(self) -> WifiAwareDataPathSecurityConfig: ...
    def hashCode(self) -> int: ...
    def isChannelRequired(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        @typing.overload
        def __init__(self, discoverySession: DiscoverySession, peerHandle: PeerHandle): ...
        @typing.overload
        def __init__(self, publishDiscoverySession: 'PublishDiscoverySession'): ...
        def build(self) -> 'WifiAwareNetworkSpecifier': ...
        def setChannelFrequencyMhz(self, int: int, boolean: bool) -> 'WifiAwareNetworkSpecifier.Builder': ...
        def setDataPathSecurityConfig(self, wifiAwareDataPathSecurityConfig: WifiAwareDataPathSecurityConfig) -> 'WifiAwareNetworkSpecifier.Builder': ...
        def setPmk(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'WifiAwareNetworkSpecifier.Builder': ...
        def setPort(self, int: int) -> 'WifiAwareNetworkSpecifier.Builder': ...
        def setPskPassphrase(self, string: str) -> 'WifiAwareNetworkSpecifier.Builder': ...
        def setTransportProtocol(self, int: int) -> 'WifiAwareNetworkSpecifier.Builder': ...

class WifiAwareSession(java.lang.AutoCloseable):
    def close(self) -> None: ...
    def createNetworkSpecifierOpen(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> android.net.NetworkSpecifier: ...
    def createNetworkSpecifierPassphrase(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], string: str) -> android.net.NetworkSpecifier: ...
    def publish(self, publishConfig: PublishConfig, discoverySessionCallback: DiscoverySessionCallback, handler: android.os.Handler) -> None: ...
    def subscribe(self, subscribeConfig: SubscribeConfig, discoverySessionCallback: DiscoverySessionCallback, handler: android.os.Handler) -> None: ...

class ParcelablePeerHandle(PeerHandle, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, peerHandle: PeerHandle): ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PublishDiscoverySession(DiscoverySession):
    def updatePublish(self, publishConfig: PublishConfig) -> None: ...

class SubscribeDiscoverySession(DiscoverySession):
    def updateSubscribe(self, subscribeConfig: SubscribeConfig) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.wifi.aware")``.

    AttachCallback: typing.Type[AttachCallback]
    AwarePairingConfig: typing.Type[AwarePairingConfig]
    AwareResources: typing.Type[AwareResources]
    Characteristics: typing.Type[Characteristics]
    DiscoverySession: typing.Type[DiscoverySession]
    DiscoverySessionCallback: typing.Type[DiscoverySessionCallback]
    IdentityChangedListener: typing.Type[IdentityChangedListener]
    ParcelablePeerHandle: typing.Type[ParcelablePeerHandle]
    PeerHandle: typing.Type[PeerHandle]
    PublishConfig: typing.Type[PublishConfig]
    PublishDiscoverySession: typing.Type[PublishDiscoverySession]
    ServiceDiscoveryInfo: typing.Type[ServiceDiscoveryInfo]
    SubscribeConfig: typing.Type[SubscribeConfig]
    SubscribeDiscoverySession: typing.Type[SubscribeDiscoverySession]
    WifiAwareChannelInfo: typing.Type[WifiAwareChannelInfo]
    WifiAwareDataPathSecurityConfig: typing.Type[WifiAwareDataPathSecurityConfig]
    WifiAwareManager: typing.Type[WifiAwareManager]
    WifiAwareNetworkInfo: typing.Type[WifiAwareNetworkInfo]
    WifiAwareNetworkSpecifier: typing.Type[WifiAwareNetworkSpecifier]
    WifiAwareSession: typing.Type[WifiAwareSession]
