
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.content
import android.net
import android.net.eap
import android.net.ipsec.ike.exceptions
import android.util
import java.io
import java.lang
import java.net
import java.security
import java.security.cert
import java.util
import java.util.concurrent
import javax.security.auth.x500
import jpype
import typing



class ChildSessionCallback:
    def onClosed(self) -> None: ...
    def onClosedWithException(self, ikeException: android.net.ipsec.ike.exceptions.IkeException) -> None: ...
    def onIpSecTransformCreated(self, ipSecTransform: android.net.IpSecTransform, int: int) -> None: ...
    def onIpSecTransformDeleted(self, ipSecTransform: android.net.IpSecTransform, int: int) -> None: ...
    def onOpened(self, childSessionConfiguration: 'ChildSessionConfiguration') -> None: ...

class ChildSessionConfiguration:
    def getInboundTrafficSelectors(self) -> java.util.List['IkeTrafficSelector']: ...
    def getOutboundTrafficSelectors(self) -> java.util.List['IkeTrafficSelector']: ...
    class Builder:
        def __init__(self, list: java.util.List['IkeTrafficSelector'], list2: java.util.List['IkeTrafficSelector']): ...
        def build(self) -> 'ChildSessionConfiguration': ...

class ChildSessionParams:
    def equals(self, object: typing.Any) -> bool: ...
    def getChildSaProposals(self) -> java.util.List['ChildSaProposal']: ...
    def getHardLifetimeSeconds(self) -> int: ...
    def getInboundTrafficSelectors(self) -> java.util.List['IkeTrafficSelector']: ...
    def getOutboundTrafficSelectors(self) -> java.util.List['IkeTrafficSelector']: ...
    def getSoftLifetimeSeconds(self) -> int: ...
    def hashCode(self) -> int: ...

class IkeIdentification: ...

class IkeSession(java.lang.AutoCloseable):
    def __init__(self, context: android.content.Context, ikeSessionParams: 'IkeSessionParams', childSessionParams: ChildSessionParams, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], ikeSessionCallback: 'IkeSessionCallback', childSessionCallback: ChildSessionCallback): ...
    def close(self) -> None: ...
    def closeChildSession(self, childSessionCallback: ChildSessionCallback) -> None: ...
    def dump(self, printWriter: java.io.PrintWriter) -> None: ...
    def finalize(self) -> None: ...
    def kill(self) -> None: ...
    def openChildSession(self, childSessionParams: ChildSessionParams, childSessionCallback: ChildSessionCallback) -> None: ...

class IkeSessionCallback:
    def onClosed(self) -> None: ...
    def onClosedWithException(self, ikeException: android.net.ipsec.ike.exceptions.IkeException) -> None: ...
    def onError(self, ikeException: android.net.ipsec.ike.exceptions.IkeException) -> None: ...
    def onOpened(self, ikeSessionConfiguration: 'IkeSessionConfiguration') -> None: ...

class IkeSessionConfiguration:
    EXTENSION_TYPE_FRAGMENTATION: typing.ClassVar[int] = ...
    EXTENSION_TYPE_MOBIKE: typing.ClassVar[int] = ...
    def getEapInfo(self) -> android.net.eap.EapInfo: ...
    def getIkeSessionConnectionInfo(self) -> 'IkeSessionConnectionInfo': ...
    def getRemoteApplicationVersion(self) -> str: ...
    def getRemoteVendorIds(self) -> java.util.List[typing.MutableSequence[int]]: ...
    def isIkeExtensionEnabled(self, int: int) -> bool: ...
    class Builder:
        def __init__(self, ikeSessionConnectionInfo: 'IkeSessionConnectionInfo'): ...
        def addIkeExtension(self, int: int) -> 'IkeSessionConfiguration.Builder': ...
        def addRemoteVendorId(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'IkeSessionConfiguration.Builder': ...
        def build(self) -> 'IkeSessionConfiguration': ...
        def clearIkeExtensions(self) -> 'IkeSessionConfiguration.Builder': ...
        def clearRemoteApplicationVersion(self) -> 'IkeSessionConfiguration.Builder': ...
        def clearRemoteVendorIds(self) -> 'IkeSessionConfiguration.Builder': ...
        def setEapInfo(self, eapInfo: android.net.eap.EapInfo) -> 'IkeSessionConfiguration.Builder': ...
        def setRemoteApplicationVersion(self, string: str) -> 'IkeSessionConfiguration.Builder': ...

class IkeSessionConnectionInfo:
    def __init__(self, inetAddress: java.net.InetAddress, inetAddress2: java.net.InetAddress, network: android.net.Network): ...
    def getLocalAddress(self) -> java.net.InetAddress: ...
    def getNetwork(self) -> android.net.Network: ...
    def getRemoteAddress(self) -> java.net.InetAddress: ...

class IkeTrafficSelector:
    endPort: int = ...
    endingAddress: java.net.InetAddress = ...
    startPort: int = ...
    startingAddress: java.net.InetAddress = ...
    def __init__(self, int: int, int2: int, inetAddress: java.net.InetAddress, inetAddress2: java.net.InetAddress): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeTunnelConnectionParams:
    def __init__(self, ikeSessionParams: 'IkeSessionParams', tunnelModeChildSessionParams: 'TunnelModeChildSessionParams'): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getIkeSessionParams(self) -> 'IkeSessionParams': ...
    def getTunnelModeChildSessionParams(self) -> 'TunnelModeChildSessionParams': ...
    def hashCode(self) -> int: ...

class SaProposal:
    DH_GROUP_1024_BIT_MODP: typing.ClassVar[int] = ...
    DH_GROUP_1536_BIT_MODP: typing.ClassVar[int] = ...
    DH_GROUP_2048_BIT_MODP: typing.ClassVar[int] = ...
    DH_GROUP_3072_BIT_MODP: typing.ClassVar[int] = ...
    DH_GROUP_4096_BIT_MODP: typing.ClassVar[int] = ...
    DH_GROUP_CURVE_25519: typing.ClassVar[int] = ...
    DH_GROUP_NONE: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_3DES: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_AES_CBC: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_AES_CTR: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_AES_GCM_12: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_AES_GCM_16: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_AES_GCM_8: typing.ClassVar[int] = ...
    ENCRYPTION_ALGORITHM_CHACHA20_POLY1305: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_AES_CMAC_96: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_AES_XCBC_96: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_HMAC_SHA1_96: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_HMAC_SHA2_256_128: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_HMAC_SHA2_384_192: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_HMAC_SHA2_512_256: typing.ClassVar[int] = ...
    INTEGRITY_ALGORITHM_NONE: typing.ClassVar[int] = ...
    KEY_LEN_AES_128: typing.ClassVar[int] = ...
    KEY_LEN_AES_192: typing.ClassVar[int] = ...
    KEY_LEN_AES_256: typing.ClassVar[int] = ...
    KEY_LEN_UNUSED: typing.ClassVar[int] = ...
    PSEUDORANDOM_FUNCTION_AES128_CMAC: typing.ClassVar[int] = ...
    PSEUDORANDOM_FUNCTION_AES128_XCBC: typing.ClassVar[int] = ...
    PSEUDORANDOM_FUNCTION_HMAC_SHA1: typing.ClassVar[int] = ...
    PSEUDORANDOM_FUNCTION_SHA2_256: typing.ClassVar[int] = ...
    PSEUDORANDOM_FUNCTION_SHA2_384: typing.ClassVar[int] = ...
    PSEUDORANDOM_FUNCTION_SHA2_512: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDhGroups(self) -> java.util.List[int]: ...
    def getEncryptionAlgorithms(self) -> java.util.List[android.util.Pair[int, int]]: ...
    def getIntegrityAlgorithms(self) -> java.util.List[int]: ...
    @staticmethod
    def getSupportedDhGroups() -> java.util.Set[int]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ChildSaProposal(SaProposal):
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def getSupportedEncryptionAlgorithms() -> java.util.Set[int]: ...
    @staticmethod
    def getSupportedIntegrityAlgorithms() -> java.util.Set[int]: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addDhGroup(self, int: int) -> 'ChildSaProposal.Builder': ...
        def addEncryptionAlgorithm(self, int: int, int2: int) -> 'ChildSaProposal.Builder': ...
        def addIntegrityAlgorithm(self, int: int) -> 'ChildSaProposal.Builder': ...
        def build(self) -> 'ChildSaProposal': ...

class IkeDerAsn1DnIdentification(IkeIdentification):
    derAsn1Dn: javax.security.auth.x500.X500Principal = ...
    def __init__(self, x500Principal: javax.security.auth.x500.X500Principal): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeFqdnIdentification(IkeIdentification):
    fqdn: str = ...
    def __init__(self, string: str): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeIpv4AddrIdentification(IkeIdentification):
    ipv4Address: java.net.Inet4Address = ...
    def __init__(self, inet4Address: java.net.Inet4Address): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeIpv6AddrIdentification(IkeIdentification):
    ipv6Address: java.net.Inet6Address = ...
    def __init__(self, inet6Address: java.net.Inet6Address): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeKeyIdIdentification(IkeIdentification):
    keyId: typing.MutableSequence[int] = ...
    def __init__(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeRfc822AddrIdentification(IkeIdentification):
    rfc822Name: str = ...
    def __init__(self, string: str): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class IkeSaProposal(SaProposal):
    def equals(self, object: typing.Any) -> bool: ...
    def getPseudorandomFunctions(self) -> java.util.List[int]: ...
    @staticmethod
    def getSupportedEncryptionAlgorithms() -> java.util.Set[int]: ...
    @staticmethod
    def getSupportedIntegrityAlgorithms() -> java.util.Set[int]: ...
    @staticmethod
    def getSupportedPseudorandomFunctions() -> java.util.Set[int]: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addDhGroup(self, int: int) -> 'IkeSaProposal.Builder': ...
        def addEncryptionAlgorithm(self, int: int, int2: int) -> 'IkeSaProposal.Builder': ...
        def addIntegrityAlgorithm(self, int: int) -> 'IkeSaProposal.Builder': ...
        def addPseudorandomFunction(self, int: int) -> 'IkeSaProposal.Builder': ...
        def build(self) -> 'IkeSaProposal': ...

class TransportModeChildSessionParams(ChildSessionParams):
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, transportModeChildSessionParams: 'TransportModeChildSessionParams'): ...
        def addChildSaProposal(self, childSaProposal: ChildSaProposal) -> 'TransportModeChildSessionParams.Builder': ...
        def addInboundTrafficSelectors(self, ikeTrafficSelector: IkeTrafficSelector) -> 'TransportModeChildSessionParams.Builder': ...
        def addOutboundTrafficSelectors(self, ikeTrafficSelector: IkeTrafficSelector) -> 'TransportModeChildSessionParams.Builder': ...
        def build(self) -> 'TransportModeChildSessionParams': ...
        def setLifetimeSeconds(self, int: int, int2: int) -> 'TransportModeChildSessionParams.Builder': ...

class IkeSessionParams:
    IKE_DPD_DELAY_SEC_DISABLED: typing.ClassVar[int] = ...
    IKE_OPTION_ACCEPT_ANY_REMOTE_ID: typing.ClassVar[int] = ...
    IKE_OPTION_EAP_ONLY_AUTH: typing.ClassVar[int] = ...
    IKE_OPTION_FORCE_PORT_4500: typing.ClassVar[int] = ...
    IKE_OPTION_INITIAL_CONTACT: typing.ClassVar[int] = ...
    IKE_OPTION_MOBIKE: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDpdDelaySeconds(self) -> int: ...
    def getHardLifetimeSeconds(self) -> int: ...
    def getIkeOptions(self) -> java.util.Set[int]: ...
    def getIkeSaProposals(self) -> java.util.List[IkeSaProposal]: ...
    def getLocalAuthConfig(self) -> 'IkeSessionParams.IkeAuthConfig': ...
    def getLocalIdentification(self) -> IkeIdentification: ...
    def getNattKeepAliveDelaySeconds(self) -> int: ...
    def getNetwork(self) -> android.net.Network: ...
    def getRemoteAuthConfig(self) -> 'IkeSessionParams.IkeAuthConfig': ...
    def getRemoteIdentification(self) -> IkeIdentification: ...
    def getRetransmissionTimeoutsMillis(self) -> typing.MutableSequence[int]: ...
    def getServerHostname(self) -> str: ...
    def getSoftLifetimeSeconds(self) -> int: ...
    def hasIkeOption(self, int: int) -> bool: ...
    def hashCode(self) -> int: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, ikeSessionParams: 'IkeSessionParams'): ...
        def addIkeOption(self, int: int) -> 'IkeSessionParams.Builder': ...
        def addIkeSaProposal(self, ikeSaProposal: IkeSaProposal) -> 'IkeSessionParams.Builder': ...
        def build(self) -> 'IkeSessionParams': ...
        def removeIkeOption(self, int: int) -> 'IkeSessionParams.Builder': ...
        @typing.overload
        def setAuthDigitalSignature(self, x509Certificate: java.security.cert.X509Certificate, x509Certificate2: java.security.cert.X509Certificate, privateKey: java.security.PrivateKey) -> 'IkeSessionParams.Builder': ...
        @typing.overload
        def setAuthDigitalSignature(self, x509Certificate: java.security.cert.X509Certificate, x509Certificate2: java.security.cert.X509Certificate, list: java.util.List[java.security.cert.X509Certificate], privateKey: java.security.PrivateKey) -> 'IkeSessionParams.Builder': ...
        def setAuthEap(self, x509Certificate: java.security.cert.X509Certificate, eapSessionConfig: android.net.eap.EapSessionConfig) -> 'IkeSessionParams.Builder': ...
        def setAuthPsk(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'IkeSessionParams.Builder': ...
        def setDpdDelaySeconds(self, int: int) -> 'IkeSessionParams.Builder': ...
        def setLifetimeSeconds(self, int: int, int2: int) -> 'IkeSessionParams.Builder': ...
        def setLocalIdentification(self, ikeIdentification: IkeIdentification) -> 'IkeSessionParams.Builder': ...
        def setNattKeepAliveDelaySeconds(self, int: int) -> 'IkeSessionParams.Builder': ...
        def setNetwork(self, network: android.net.Network) -> 'IkeSessionParams.Builder': ...
        def setRemoteIdentification(self, ikeIdentification: IkeIdentification) -> 'IkeSessionParams.Builder': ...
        def setRetransmissionTimeoutsMillis(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'IkeSessionParams.Builder': ...
        def setServerHostname(self, string: str) -> 'IkeSessionParams.Builder': ...
    class IkeAuthConfig:
        def equals(self, object: typing.Any) -> bool: ...
        def hashCode(self) -> int: ...
    class IkeAuthDigitalSignLocalConfig(android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getClientEndCertificate(self) -> java.security.cert.X509Certificate: ...
        def getIntermediateCertificates(self) -> java.util.List[java.security.cert.X509Certificate]: ...
        def getPrivateKey(self) -> java.security.PrivateKey: ...
        def hashCode(self) -> int: ...
    class IkeAuthDigitalSignRemoteConfig(android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getRemoteCaCert(self) -> java.security.cert.X509Certificate: ...
        def hashCode(self) -> int: ...
    class IkeAuthEapConfig(android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getEapConfig(self) -> android.net.eap.EapSessionConfig: ...
        def hashCode(self) -> int: ...
    class IkeAuthPskConfig(android.net.ipsec.ike.IkeSessionParams.IkeAuthConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getPsk(self) -> typing.MutableSequence[int]: ...
        def hashCode(self) -> int: ...

class TunnelModeChildSessionParams(ChildSessionParams):
    def equals(self, object: typing.Any) -> bool: ...
    def getConfigurationRequests(self) -> java.util.List['TunnelModeChildSessionParams.TunnelModeChildConfigRequest']: ...
    def hashCode(self) -> int: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, tunnelModeChildSessionParams: 'TunnelModeChildSessionParams'): ...
        def addChildSaProposal(self, childSaProposal: ChildSaProposal) -> 'TunnelModeChildSessionParams.Builder': ...
        def addInboundTrafficSelectors(self, ikeTrafficSelector: IkeTrafficSelector) -> 'TunnelModeChildSessionParams.Builder': ...
        @typing.overload
        def addInternalAddressRequest(self, int: int) -> 'TunnelModeChildSessionParams.Builder': ...
        @typing.overload
        def addInternalAddressRequest(self, inet4Address: java.net.Inet4Address) -> 'TunnelModeChildSessionParams.Builder': ...
        @typing.overload
        def addInternalAddressRequest(self, inet6Address: java.net.Inet6Address, int: int) -> 'TunnelModeChildSessionParams.Builder': ...
        def addInternalDhcpServerRequest(self, int: int) -> 'TunnelModeChildSessionParams.Builder': ...
        def addInternalDnsServerRequest(self, int: int) -> 'TunnelModeChildSessionParams.Builder': ...
        def addOutboundTrafficSelectors(self, ikeTrafficSelector: IkeTrafficSelector) -> 'TunnelModeChildSessionParams.Builder': ...
        def build(self) -> 'TunnelModeChildSessionParams': ...
        def setLifetimeSeconds(self, int: int, int2: int) -> 'TunnelModeChildSessionParams.Builder': ...
    class ConfigRequestIpv4Address(android.net.ipsec.ike.TunnelModeChildSessionParams.TunnelModeChildConfigRequest):
        def getAddress(self) -> java.net.Inet4Address: ...
    class ConfigRequestIpv4DhcpServer(android.net.ipsec.ike.TunnelModeChildSessionParams.TunnelModeChildConfigRequest): ...
    class ConfigRequestIpv4DnsServer(android.net.ipsec.ike.TunnelModeChildSessionParams.TunnelModeChildConfigRequest): ...
    class ConfigRequestIpv4Netmask(android.net.ipsec.ike.TunnelModeChildSessionParams.TunnelModeChildConfigRequest): ...
    class ConfigRequestIpv6Address(android.net.ipsec.ike.TunnelModeChildSessionParams.TunnelModeChildConfigRequest):
        def getAddress(self) -> java.net.Inet6Address: ...
        def getPrefixLength(self) -> int: ...
    class ConfigRequestIpv6DnsServer(android.net.ipsec.ike.TunnelModeChildSessionParams.TunnelModeChildConfigRequest): ...
    class TunnelModeChildConfigRequest: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.ipsec.ike")``.

    ChildSaProposal: typing.Type[ChildSaProposal]
    ChildSessionCallback: typing.Type[ChildSessionCallback]
    ChildSessionConfiguration: typing.Type[ChildSessionConfiguration]
    ChildSessionParams: typing.Type[ChildSessionParams]
    IkeDerAsn1DnIdentification: typing.Type[IkeDerAsn1DnIdentification]
    IkeFqdnIdentification: typing.Type[IkeFqdnIdentification]
    IkeIdentification: typing.Type[IkeIdentification]
    IkeIpv4AddrIdentification: typing.Type[IkeIpv4AddrIdentification]
    IkeIpv6AddrIdentification: typing.Type[IkeIpv6AddrIdentification]
    IkeKeyIdIdentification: typing.Type[IkeKeyIdIdentification]
    IkeRfc822AddrIdentification: typing.Type[IkeRfc822AddrIdentification]
    IkeSaProposal: typing.Type[IkeSaProposal]
    IkeSession: typing.Type[IkeSession]
    IkeSessionCallback: typing.Type[IkeSessionCallback]
    IkeSessionConfiguration: typing.Type[IkeSessionConfiguration]
    IkeSessionConnectionInfo: typing.Type[IkeSessionConnectionInfo]
    IkeSessionParams: typing.Type[IkeSessionParams]
    IkeTrafficSelector: typing.Type[IkeTrafficSelector]
    IkeTunnelConnectionParams: typing.Type[IkeTunnelConnectionParams]
    SaProposal: typing.Type[SaProposal]
    TransportModeChildSessionParams: typing.Type[TransportModeChildSessionParams]
    TunnelModeChildSessionParams: typing.Type[TunnelModeChildSessionParams]
    exceptions: android.net.ipsec.ike.exceptions.__module_protocol__
