
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.net
import android.os
import java.util
import typing



class PdfPageGotoLinkContent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List[android.graphics.RectF], destination: 'PdfPageGotoLinkContent.Destination'): ...
    def describeContents(self) -> int: ...
    def getBounds(self) -> java.util.List[android.graphics.RectF]: ...
    def getDestination(self) -> 'PdfPageGotoLinkContent.Destination': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Destination(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def __init__(self, int: int, float: float, float2: float, float3: float): ...
        def describeContents(self) -> int: ...
        def getPageNumber(self) -> int: ...
        def getXCoordinate(self) -> float: ...
        def getYCoordinate(self) -> float: ...
        def getZoom(self) -> float: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PdfPageImageContent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str): ...
    def describeContents(self) -> int: ...
    def getAltText(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PdfPageLinkContent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List[android.graphics.RectF], uri: android.net.Uri): ...
    def describeContents(self) -> int: ...
    def getBounds(self) -> java.util.List[android.graphics.RectF]: ...
    def getUri(self) -> android.net.Uri: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PdfPageTextContent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, list: java.util.List[android.graphics.RectF]): ...
    def describeContents(self) -> int: ...
    def getBounds(self) -> java.util.List[android.graphics.RectF]: ...
    def getText(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.graphics.pdf.content")``.

    PdfPageGotoLinkContent: typing.Type[PdfPageGotoLinkContent]
    PdfPageImageContent: typing.Type[PdfPageImageContent]
    PdfPageLinkContent: typing.Type[PdfPageLinkContent]
    PdfPageTextContent: typing.Type[PdfPageTextContent]
