
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.os
import android.util
import android.view
import typing



class InlineContentView(android.view.ViewGroup):
    def getSurfaceControl(self) -> android.view.SurfaceControl: ...
    def isZOrderedOnTop(self) -> bool: ...
    def onLayout(self, boolean: bool, int: int, int2: int, int3: int, int4: int) -> None: ...
    def setClipBounds(self, rect: android.graphics.Rect) -> None: ...
    def setSurfaceControlCallback(self, surfaceControlCallback: 'InlineContentView.SurfaceControlCallback') -> None: ...
    def setZOrderedOnTop(self, boolean: bool) -> bool: ...
    class SurfaceControlCallback:
        def onCreated(self, surfaceControl: android.view.SurfaceControl) -> None: ...
        def onDestroyed(self, surfaceControl: android.view.SurfaceControl) -> None: ...

class InlinePresentationSpec(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMaxSize(self) -> android.util.Size: ...
    def getMinSize(self) -> android.util.Size: ...
    def getStyle(self) -> android.os.Bundle: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, size: android.util.Size, size2: android.util.Size): ...
        def build(self) -> 'InlinePresentationSpec': ...
        def setStyle(self, bundle: android.os.Bundle) -> 'InlinePresentationSpec.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.widget.inline")``.

    InlineContentView: typing.Type[InlineContentView]
    InlinePresentationSpec: typing.Type[InlinePresentationSpec]
