
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.location
import android.net
import android.net.wifi
import android.net.wifi.aware
import android.os
import android.util
import java.util
import java.util.concurrent
import jpype
import typing



class CivicLocationKeys:
    ADDITIONAL_CODE: typing.ClassVar[int] = ...
    APT: typing.ClassVar[int] = ...
    BOROUGH: typing.ClassVar[int] = ...
    BRANCH_ROAD_NAME: typing.ClassVar[int] = ...
    BUILDING: typing.ClassVar[int] = ...
    CITY: typing.ClassVar[int] = ...
    COUNTY: typing.ClassVar[int] = ...
    DESK: typing.ClassVar[int] = ...
    FLOOR: typing.ClassVar[int] = ...
    GROUP_OF_STREETS: typing.ClassVar[int] = ...
    HNO: typing.ClassVar[int] = ...
    HNS: typing.ClassVar[int] = ...
    LANGUAGE: typing.ClassVar[int] = ...
    LMK: typing.ClassVar[int] = ...
    LOC: typing.ClassVar[int] = ...
    NAM: typing.ClassVar[int] = ...
    NEIGHBORHOOD: typing.ClassVar[int] = ...
    PCN: typing.ClassVar[int] = ...
    POD: typing.ClassVar[int] = ...
    POSTAL_CODE: typing.ClassVar[int] = ...
    PO_BOX: typing.ClassVar[int] = ...
    PRD: typing.ClassVar[int] = ...
    PRIMARY_ROAD_NAME: typing.ClassVar[int] = ...
    ROAD_SECTION: typing.ClassVar[int] = ...
    ROOM: typing.ClassVar[int] = ...
    SCRIPT: typing.ClassVar[int] = ...
    STATE: typing.ClassVar[int] = ...
    STREET_NAME_POST_MODIFIER: typing.ClassVar[int] = ...
    STREET_NAME_PRE_MODIFIER: typing.ClassVar[int] = ...
    STS: typing.ClassVar[int] = ...
    SUBBRANCH_ROAD_NAME: typing.ClassVar[int] = ...
    TYPE_OF_PLACE: typing.ClassVar[int] = ...

class RangingRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def getDefaultRttBurstSize() -> int: ...
    @staticmethod
    def getMaxPeers() -> int: ...
    @staticmethod
    def getMaxRttBurstSize() -> int: ...
    @staticmethod
    def getMinRttBurstSize() -> int: ...
    def getRttBurstSize(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addAccessPoint(self, scanResult: android.net.wifi.ScanResult) -> 'RangingRequest.Builder': ...
        def addAccessPoints(self, list: java.util.List[android.net.wifi.ScanResult]) -> 'RangingRequest.Builder': ...
        def addNon80211mcCapableAccessPoint(self, scanResult: android.net.wifi.ScanResult) -> 'RangingRequest.Builder': ...
        def addNon80211mcCapableAccessPoints(self, list: java.util.List[android.net.wifi.ScanResult]) -> 'RangingRequest.Builder': ...
        def addResponder(self, responderConfig: 'ResponderConfig') -> 'RangingRequest.Builder': ...
        def addResponders(self, list: java.util.List['ResponderConfig']) -> 'RangingRequest.Builder': ...
        @typing.overload
        def addWifiAwarePeer(self, macAddress: android.net.MacAddress) -> 'RangingRequest.Builder': ...
        @typing.overload
        def addWifiAwarePeer(self, peerHandle: android.net.wifi.aware.PeerHandle) -> 'RangingRequest.Builder': ...
        def build(self) -> 'RangingRequest': ...
        def setRttBurstSize(self, int: int) -> 'RangingRequest.Builder': ...

class RangingResult(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    STATUS_FAIL: typing.ClassVar[int] = ...
    STATUS_RESPONDER_DOES_NOT_SUPPORT_IEEE80211MC: typing.ClassVar[int] = ...
    STATUS_SUCCESS: typing.ClassVar[int] = ...
    UNSPECIFIED: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def get80211azInitiatorTxLtfRepetitionsCount(self) -> int: ...
    def get80211azNumberOfRxSpatialStreams(self) -> int: ...
    def get80211azNumberOfTxSpatialStreams(self) -> int: ...
    def get80211azResponderTxLtfRepetitionsCount(self) -> int: ...
    def getDistanceMm(self) -> int: ...
    def getDistanceStdDevMm(self) -> int: ...
    def getLci(self) -> typing.MutableSequence[int]: ...
    def getLcr(self) -> typing.MutableSequence[int]: ...
    def getMacAddress(self) -> android.net.MacAddress: ...
    def getMaxTimeBetweenNtbMeasurementsMicros(self) -> int: ...
    def getMeasurementBandwidth(self) -> int: ...
    def getMeasurementChannelFrequencyMHz(self) -> int: ...
    def getMinTimeBetweenNtbMeasurementsMicros(self) -> int: ...
    def getNumAttemptedMeasurements(self) -> int: ...
    def getNumSuccessfulMeasurements(self) -> int: ...
    def getPeerHandle(self) -> android.net.wifi.aware.PeerHandle: ...
    def getRangingTimestampMillis(self) -> int: ...
    def getRssi(self) -> int: ...
    def getStatus(self) -> int: ...
    def getUnverifiedResponderLocation(self) -> 'ResponderLocation': ...
    def hashCode(self) -> int: ...
    def is80211azNtbMeasurement(self) -> bool: ...
    def is80211mcMeasurement(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'RangingResult': ...
        def set80211azInitiatorTxLtfRepetitionsCount(self, int: int) -> 'RangingResult.Builder': ...
        def set80211azNtbMeasurement(self, boolean: bool) -> 'RangingResult.Builder': ...
        def set80211azNumberOfRxSpatialStreams(self, int: int) -> 'RangingResult.Builder': ...
        def set80211azNumberOfTxSpatialStreams(self, int: int) -> 'RangingResult.Builder': ...
        def set80211azResponderTxLtfRepetitionsCount(self, int: int) -> 'RangingResult.Builder': ...
        def set80211mcMeasurement(self, boolean: bool) -> 'RangingResult.Builder': ...
        def setDistanceMm(self, int: int) -> 'RangingResult.Builder': ...
        def setDistanceStdDevMm(self, int: int) -> 'RangingResult.Builder': ...
        def setLci(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'RangingResult.Builder': ...
        def setLcr(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'RangingResult.Builder': ...
        def setMacAddress(self, macAddress: android.net.MacAddress) -> 'RangingResult.Builder': ...
        def setMaxTimeBetweenNtbMeasurementsMicros(self, long: int) -> 'RangingResult.Builder': ...
        def setMeasurementBandwidth(self, int: int) -> 'RangingResult.Builder': ...
        def setMeasurementChannelFrequencyMHz(self, int: int) -> 'RangingResult.Builder': ...
        def setMinTimeBetweenNtbMeasurementsMicros(self, long: int) -> 'RangingResult.Builder': ...
        def setNumAttemptedMeasurements(self, int: int) -> 'RangingResult.Builder': ...
        def setNumSuccessfulMeasurements(self, int: int) -> 'RangingResult.Builder': ...
        def setPeerHandle(self, peerHandle: android.net.wifi.aware.PeerHandle) -> 'RangingResult.Builder': ...
        def setRangingTimestampMillis(self, long: int) -> 'RangingResult.Builder': ...
        def setRssi(self, int: int) -> 'RangingResult.Builder': ...
        def setStatus(self, int: int) -> 'RangingResult.Builder': ...
        def setUnverifiedResponderLocation(self, responderLocation: 'ResponderLocation') -> 'RangingResult.Builder': ...

class RangingResultCallback:
    STATUS_CODE_FAIL: typing.ClassVar[int] = ...
    STATUS_CODE_FAIL_RTT_NOT_AVAILABLE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onRangingFailure(self, int: int) -> None: ...
    def onRangingResults(self, list: java.util.List[RangingResult]) -> None: ...

class ResponderConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RESPONDER_AP: typing.ClassVar[int] = ...
    RESPONDER_STA: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromScanResult(scanResult: android.net.wifi.ScanResult) -> 'ResponderConfig': ...
    def getCenterFreq0Mhz(self) -> int: ...
    def getCenterFreq1Mhz(self) -> int: ...
    def getChannelWidth(self) -> int: ...
    def getFrequencyMhz(self) -> int: ...
    def getMacAddress(self) -> android.net.MacAddress: ...
    def getPreamble(self) -> int: ...
    def getResponderType(self) -> int: ...
    def hashCode(self) -> int: ...
    def is80211azNtbSupported(self) -> bool: ...
    def is80211mcSupported(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'ResponderConfig': ...
        def set80211azNtbSupported(self, boolean: bool) -> 'ResponderConfig.Builder': ...
        def set80211mcSupported(self, boolean: bool) -> 'ResponderConfig.Builder': ...
        def setCenterFreq0Mhz(self, int: int) -> 'ResponderConfig.Builder': ...
        def setCenterFreq1Mhz(self, int: int) -> 'ResponderConfig.Builder': ...
        def setChannelWidth(self, int: int) -> 'ResponderConfig.Builder': ...
        def setFrequencyMhz(self, int: int) -> 'ResponderConfig.Builder': ...
        def setMacAddress(self, macAddress: android.net.MacAddress) -> 'ResponderConfig.Builder': ...
        def setPreamble(self, int: int) -> 'ResponderConfig.Builder': ...
        def setResponderType(self, int: int) -> 'ResponderConfig.Builder': ...

class ResponderLocation(android.os.Parcelable):
    ALTITUDE_FLOORS: typing.ClassVar[int] = ...
    ALTITUDE_METERS: typing.ClassVar[int] = ...
    ALTITUDE_UNDEFINED: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DATUM_NAD83_MLLW: typing.ClassVar[int] = ...
    DATUM_NAD83_NAV88: typing.ClassVar[int] = ...
    DATUM_UNDEFINED: typing.ClassVar[int] = ...
    DATUM_WGS84: typing.ClassVar[int] = ...
    LCI_VERSION_1: typing.ClassVar[int] = ...
    LOCATION_FIXED: typing.ClassVar[int] = ...
    LOCATION_MOVEMENT_UNKNOWN: typing.ClassVar[int] = ...
    LOCATION_RESERVED: typing.ClassVar[int] = ...
    LOCATION_VARIABLE: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAltitude(self) -> float: ...
    def getAltitudeType(self) -> int: ...
    def getAltitudeUncertainty(self) -> float: ...
    def getColocatedBssids(self) -> java.util.List[android.net.MacAddress]: ...
    def getDatum(self) -> int: ...
    def getExpectedToMove(self) -> int: ...
    def getFloorNumber(self) -> float: ...
    def getHeightAboveFloorMeters(self) -> float: ...
    def getHeightAboveFloorUncertaintyMeters(self) -> float: ...
    def getLatitude(self) -> float: ...
    def getLatitudeUncertainty(self) -> float: ...
    def getLciVersion(self) -> int: ...
    def getLongitude(self) -> float: ...
    def getLongitudeUncertainty(self) -> float: ...
    def getMapImageMimeType(self) -> str: ...
    def getMapImageUri(self) -> android.net.Uri: ...
    def getRegisteredLocationAgreementIndication(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isLciSubelementValid(self) -> bool: ...
    def isZaxisSubelementValid(self) -> bool: ...
    def toCivicLocationAddress(self) -> android.location.Address: ...
    def toCivicLocationSparseArray(self) -> android.util.SparseArray[str]: ...
    def toLocation(self) -> android.location.Location: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiRttManager:
    ACTION_WIFI_RTT_STATE_CHANGED: typing.ClassVar[str] = ...
    CHARACTERISTICS_KEY_BOOLEAN_LCI: typing.ClassVar[str] = ...
    CHARACTERISTICS_KEY_BOOLEAN_LCR: typing.ClassVar[str] = ...
    CHARACTERISTICS_KEY_BOOLEAN_NTB_INITIATOR: typing.ClassVar[str] = ...
    CHARACTERISTICS_KEY_BOOLEAN_ONE_SIDED_RTT: typing.ClassVar[str] = ...
    CHARACTERISTICS_KEY_BOOLEAN_STA_RESPONDER: typing.ClassVar[str] = ...
    def getRttCharacteristics(self) -> android.os.Bundle: ...
    def isAvailable(self) -> bool: ...
    def startRanging(self, rangingRequest: RangingRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], rangingResultCallback: RangingResultCallback) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.wifi.rtt")``.

    CivicLocationKeys: typing.Type[CivicLocationKeys]
    RangingRequest: typing.Type[RangingRequest]
    RangingResult: typing.Type[RangingResult]
    RangingResultCallback: typing.Type[RangingResultCallback]
    ResponderConfig: typing.Type[ResponderConfig]
    ResponderLocation: typing.Type[ResponderLocation]
    WifiRttManager: typing.Type[WifiRttManager]
