
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import java.lang
import jpype
import typing



class Shape(java.lang.Cloneable):
    def __init__(self): ...
    def clone(self) -> 'Shape': ...
    def draw(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHeight(self) -> float: ...
    def getOutline(self, outline: android.graphics.Outline) -> None: ...
    def getWidth(self) -> float: ...
    def hasAlpha(self) -> bool: ...
    def hashCode(self) -> int: ...
    def resize(self, float: float, float2: float) -> None: ...

class PathShape(Shape):
    def __init__(self, path: android.graphics.Path, float: float, float2: float): ...
    def clone(self) -> 'PathShape': ...
    def draw(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class RectShape(Shape):
    def __init__(self): ...
    def clone(self) -> 'RectShape': ...
    def draw(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOutline(self, outline: android.graphics.Outline) -> None: ...
    def hashCode(self) -> int: ...

class ArcShape(RectShape):
    def __init__(self, float: float, float2: float): ...
    def clone(self) -> 'ArcShape': ...
    def draw(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOutline(self, outline: android.graphics.Outline) -> None: ...
    def getStartAngle(self) -> float: ...
    def getSweepAngle(self) -> float: ...
    def hashCode(self) -> int: ...

class OvalShape(RectShape):
    def __init__(self): ...
    def clone(self) -> 'OvalShape': ...
    def draw(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint) -> None: ...
    def getOutline(self, outline: android.graphics.Outline) -> None: ...

class RoundRectShape(RectShape):
    def __init__(self, floatArray: typing.Union[typing.List[float], jpype.JArray], rectF: android.graphics.RectF, floatArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    def clone(self) -> 'RoundRectShape': ...
    def draw(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getOutline(self, outline: android.graphics.Outline) -> None: ...
    def hashCode(self) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.graphics.drawable.shapes")``.

    ArcShape: typing.Type[ArcShape]
    OvalShape: typing.Type[OvalShape]
    PathShape: typing.Type[PathShape]
    RectShape: typing.Type[RectShape]
    RoundRectShape: typing.Type[RoundRectShape]
    Shape: typing.Type[Shape]
