
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import java.security.cert
import jpype
import typing



class EapInfo:
    def getEapMethodType(self) -> int: ...

class EapAkaInfo(EapInfo):
    def getReauthId(self) -> typing.MutableSequence[int]: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EapAkaInfo': ...
        def setReauthId(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'EapAkaInfo.Builder': ...

class EapSessionConfig:
    def equals(self, object: typing.Any) -> bool: ...
    def getEapAkaConfig(self) -> 'EapSessionConfig.EapAkaConfig': ...
    def getEapAkaPrimeConfig(self) -> 'EapSessionConfig.EapAkaPrimeConfig': ...
    def getEapIdentity(self) -> typing.MutableSequence[int]: ...
    def getEapMsChapV2Config(self) -> 'EapSessionConfig.EapMsChapV2Config': ...
    def getEapSimConfig(self) -> 'EapSessionConfig.EapSimConfig': ...
    def getEapTtlsConfig(self) -> 'EapSessionConfig.EapTtlsConfig': ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EapSessionConfig': ...
        @typing.overload
        def setEapAkaConfig(self, int: int, int2: int) -> 'EapSessionConfig.Builder': ...
        @typing.overload
        def setEapAkaConfig(self, int: int, int2: int, eapAkaOption: 'EapSessionConfig.EapAkaOption') -> 'EapSessionConfig.Builder': ...
        def setEapAkaPrimeConfig(self, int: int, int2: int, string: str, boolean: bool) -> 'EapSessionConfig.Builder': ...
        def setEapIdentity(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'EapSessionConfig.Builder': ...
        def setEapMsChapV2Config(self, string: str, string2: str) -> 'EapSessionConfig.Builder': ...
        def setEapSimConfig(self, int: int, int2: int) -> 'EapSessionConfig.Builder': ...
        def setEapTtlsConfig(self, x509Certificate: java.security.cert.X509Certificate, eapSessionConfig: 'EapSessionConfig') -> 'EapSessionConfig.Builder': ...
    class EapAkaConfig(android.net.eap.EapSessionConfig.EapMethodConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getAppType(self) -> int: ...
        def getEapAkaOption(self) -> 'EapSessionConfig.EapAkaOption': ...
        def getSubId(self) -> int: ...
        def hashCode(self) -> int: ...
    class EapAkaOption:
        def equals(self, object: typing.Any) -> bool: ...
        def getReauthId(self) -> typing.MutableSequence[int]: ...
        def hashCode(self) -> int: ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'EapSessionConfig.EapAkaOption': ...
            def setReauthId(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'EapSessionConfig.EapAkaOption.Builder': ...
    class EapAkaPrimeConfig(android.net.eap.EapSessionConfig.EapAkaConfig):
        def allowsMismatchedNetworkNames(self) -> bool: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getNetworkName(self) -> str: ...
        def hashCode(self) -> int: ...
    class EapMethodConfig:
        EAP_TYPE_AKA: typing.ClassVar[int] = ...
        EAP_TYPE_AKA_PRIME: typing.ClassVar[int] = ...
        EAP_TYPE_MSCHAP_V2: typing.ClassVar[int] = ...
        EAP_TYPE_SIM: typing.ClassVar[int] = ...
        EAP_TYPE_TTLS: typing.ClassVar[int] = ...
        def equals(self, object: typing.Any) -> bool: ...
        def getMethodType(self) -> int: ...
        def hashCode(self) -> int: ...
    class EapMsChapV2Config(android.net.eap.EapSessionConfig.EapMethodConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getPassword(self) -> str: ...
        def getUsername(self) -> str: ...
        def hashCode(self) -> int: ...
    class EapSimConfig(android.net.eap.EapSessionConfig.EapMethodConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getAppType(self) -> int: ...
        def getSubId(self) -> int: ...
        def hashCode(self) -> int: ...
    class EapTtlsConfig(android.net.eap.EapSessionConfig.EapMethodConfig):
        def equals(self, object: typing.Any) -> bool: ...
        def getInnerEapSessionConfig(self) -> 'EapSessionConfig': ...
        def getServerCaCert(self) -> java.security.cert.X509Certificate: ...
        def hashCode(self) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.eap")``.

    EapAkaInfo: typing.Type[EapAkaInfo]
    EapInfo: typing.Type[EapInfo]
    EapSessionConfig: typing.Type[EapSessionConfig]
