
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.app
import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.graphics.text
import android.net
import android.os
import android.text
import android.view
import java.lang
import java.util
import jpype
import typing



class CharacterStyle:
    def __init__(self): ...
    def getUnderlying(self) -> 'CharacterStyle': ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    @staticmethod
    def wrap(characterStyle: 'CharacterStyle') -> 'CharacterStyle': ...

class EasyEditSpan(android.text.ParcelableSpan):
    EXTRA_TEXT_CHANGED_TYPE: typing.ClassVar[str] = ...
    TEXT_DELETED: typing.ClassVar[int] = ...
    TEXT_MODIFIED: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pendingIntent: android.app.PendingIntent): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LineBreakConfigSpan(android.text.ParcelableSpan):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, lineBreakConfig: android.graphics.text.LineBreakConfig): ...
    @staticmethod
    def createNoBreakSpan() -> 'LineBreakConfigSpan': ...
    @staticmethod
    def createNoHyphenationSpan() -> 'LineBreakConfigSpan': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLineBreakConfig(self) -> android.graphics.text.LineBreakConfig: ...
    def getSpanTypeId(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ParagraphStyle: ...

class UpdateAppearance: ...

class BackgroundColorSpan(CharacterStyle, UpdateAppearance, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int): ...
    def describeContents(self) -> int: ...
    def getBackgroundColor(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ClickableSpan(CharacterStyle, UpdateAppearance):
    def __init__(self): ...
    def onClick(self, view: android.view.View) -> None: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...

class ForegroundColorSpan(CharacterStyle, UpdateAppearance, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int): ...
    def describeContents(self) -> int: ...
    def getForegroundColor(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class MaskFilterSpan(CharacterStyle, UpdateAppearance):
    def __init__(self, maskFilter: android.graphics.MaskFilter): ...
    def getMaskFilter(self) -> android.graphics.MaskFilter: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...

class StrikethroughSpan(CharacterStyle, UpdateAppearance, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SuggestionRangeSpan(CharacterStyle, android.text.ParcelableSpan):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self): ...
    def describeContents(self) -> int: ...
    def getBackgroundColor(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def setBackgroundColor(self, int: int) -> None: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SuggestionSpan(CharacterStyle, android.text.ParcelableSpan):
    ACTION_SUGGESTION_PICKED: typing.ClassVar[str] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FLAG_AUTO_CORRECTION: typing.ClassVar[int] = ...
    FLAG_EASY_CORRECT: typing.ClassVar[int] = ...
    FLAG_GRAMMAR_ERROR: typing.ClassVar[int] = ...
    FLAG_MISSPELLED: typing.ClassVar[int] = ...
    SUGGESTIONS_MAX_SIZE: typing.ClassVar[int] = ...
    SUGGESTION_SPAN_PICKED_AFTER: typing.ClassVar[str] = ...
    SUGGESTION_SPAN_PICKED_BEFORE: typing.ClassVar[str] = ...
    SUGGESTION_SPAN_PICKED_HASHCODE: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, stringArray: typing.Union[typing.List[str], jpype.JArray], int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, locale: java.util.Locale, stringArray: typing.Union[typing.List[str], jpype.JArray], int: int, class_: typing.Type[typing.Any]): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale, stringArray: typing.Union[typing.List[str], jpype.JArray], int: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFlags(self) -> int: ...
    def getLocale(self) -> str: ...
    def getLocaleObject(self) -> java.util.Locale: ...
    def getSpanTypeId(self) -> int: ...
    def getSuggestions(self) -> typing.MutableSequence[str]: ...
    def getUnderlineColor(self) -> int: ...
    def hashCode(self) -> int: ...
    def setFlags(self, int: int) -> None: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UnderlineSpan(CharacterStyle, UpdateAppearance, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UpdateLayout(UpdateAppearance): ...

class WrapTogetherSpan(ParagraphStyle): ...

class MetricAffectingSpan(CharacterStyle, UpdateLayout):
    def __init__(self): ...
    def getUnderlying(self) -> 'MetricAffectingSpan': ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...

class URLSpan(ClickableSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, string: str): ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def getURL(self) -> str: ...
    def onClick(self, view: android.view.View) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AbsoluteSizeSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, boolean: bool): ...
    def describeContents(self) -> int: ...
    def getDip(self) -> bool: ...
    def getSize(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LocaleSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, localeList: android.os.LocaleList): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, locale: java.util.Locale): ...
    def describeContents(self) -> int: ...
    def getLocale(self) -> java.util.Locale: ...
    def getLocales(self) -> android.os.LocaleList: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class RelativeSizeSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, float: float): ...
    def describeContents(self) -> int: ...
    def getSizeChange(self) -> float: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ReplacementSpan(MetricAffectingSpan):
    def __init__(self): ...
    def draw(self, canvas: android.graphics.Canvas, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, float: float, int3: int, int4: int, int5: int, paint: android.graphics.Paint) -> None: ...
    def getContentDescription(self) -> java.lang.CharSequence: ...
    def getSize(self, paint: android.graphics.Paint, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> int: ...
    def setContentDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...

class ScaleXSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, float: float): ...
    def describeContents(self) -> int: ...
    def getScaleX(self) -> float: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StyleSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def getFontWeightAdjustment(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def getStyle(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SubscriptSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SuperscriptSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TextAppearanceSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, context: android.content.Context, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int, int2: int): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, string: str, int: int, int2: int, colorStateList: android.content.res.ColorStateList, colorStateList2: android.content.res.ColorStateList): ...
    def describeContents(self) -> int: ...
    def getFamily(self) -> str: ...
    def getFontFeatureSettings(self) -> str: ...
    def getFontVariationSettings(self) -> str: ...
    def getLetterSpacing(self) -> float: ...
    def getLinkTextColor(self) -> android.content.res.ColorStateList: ...
    def getShadowColor(self) -> int: ...
    def getShadowDx(self) -> float: ...
    def getShadowDy(self) -> float: ...
    def getShadowRadius(self) -> float: ...
    def getSpanTypeId(self) -> int: ...
    def getTextColor(self) -> android.content.res.ColorStateList: ...
    def getTextFontWeight(self) -> int: ...
    def getTextLocales(self) -> android.os.LocaleList: ...
    def getTextSize(self) -> int: ...
    def getTextStyle(self) -> int: ...
    def getTypeface(self) -> android.graphics.Typeface: ...
    def isElegantTextHeight(self) -> bool: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TypefaceSpan(MetricAffectingSpan, android.text.ParcelableSpan):
    @typing.overload
    def __init__(self, typeface: android.graphics.Typeface): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, string: str): ...
    def describeContents(self) -> int: ...
    def getFamily(self) -> str: ...
    def getSpanTypeId(self) -> int: ...
    def getTypeface(self) -> android.graphics.Typeface: ...
    def toString(self) -> str: ...
    def updateDrawState(self, textPaint: android.text.TextPaint) -> None: ...
    def updateMeasureState(self, textPaint: android.text.TextPaint) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DynamicDrawableSpan(ReplacementSpan):
    ALIGN_BASELINE: typing.ClassVar[int] = ...
    ALIGN_BOTTOM: typing.ClassVar[int] = ...
    ALIGN_CENTER: typing.ClassVar[int] = ...
    def __init__(self): ...
    def draw(self, canvas: android.graphics.Canvas, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, float: float, int3: int, int4: int, int5: int, paint: android.graphics.Paint) -> None: ...
    def getDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getSize(self, paint: android.graphics.Paint, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> int: ...
    def getVerticalAlignment(self) -> int: ...
    def toString(self) -> str: ...

class ImageSpan(DynamicDrawableSpan):
    @typing.overload
    def __init__(self, context: android.content.Context, bitmap: android.graphics.Bitmap): ...
    @typing.overload
    def __init__(self, context: android.content.Context, bitmap: android.graphics.Bitmap, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, uri: android.net.Uri): ...
    @typing.overload
    def __init__(self, context: android.content.Context, uri: android.net.Uri, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int): ...
    @typing.overload
    def __init__(self, context: android.content.Context, int: int, int2: int): ...
    @typing.overload
    def __init__(self, bitmap: android.graphics.Bitmap): ...
    @typing.overload
    def __init__(self, bitmap: android.graphics.Bitmap, int: int): ...
    @typing.overload
    def __init__(self, drawable: android.graphics.drawable.Drawable): ...
    @typing.overload
    def __init__(self, drawable: android.graphics.drawable.Drawable, int: int): ...
    @typing.overload
    def __init__(self, drawable: android.graphics.drawable.Drawable, string: str): ...
    @typing.overload
    def __init__(self, drawable: android.graphics.drawable.Drawable, string: str, int: int): ...
    def getDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getSource(self) -> str: ...
    def toString(self) -> str: ...

class AlignmentSpan(ParagraphStyle):
    def getAlignment(self) -> android.text.Layout.Alignment: ...
    class Standard(android.text.style.AlignmentSpan, android.text.ParcelableSpan):
        @typing.overload
        def __init__(self, parcel: android.os.Parcel): ...
        @typing.overload
        def __init__(self, alignment: android.text.Layout.Alignment): ...
        def describeContents(self) -> int: ...
        def getAlignment(self) -> android.text.Layout.Alignment: ...
        def getSpanTypeId(self) -> int: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BulletSpan(android.text.style.LeadingMarginSpan, android.text.ParcelableSpan):
    STANDARD_GAP_WIDTH: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    def describeContents(self) -> int: ...
    def drawLeadingMargin(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, boolean: bool, layout: android.text.Layout) -> None: ...
    def getBulletRadius(self) -> int: ...
    def getColor(self) -> int: ...
    def getGapWidth(self) -> int: ...
    def getLeadingMargin(self, boolean: bool) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DrawableMarginSpan(android.text.style.LeadingMarginSpan, android.text.style.LineHeightSpan):
    @typing.overload
    def __init__(self, drawable: android.graphics.drawable.Drawable): ...
    @typing.overload
    def __init__(self, drawable: android.graphics.drawable.Drawable, int: int): ...
    def chooseHeight(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...
    def drawLeadingMargin(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, boolean: bool, layout: android.text.Layout) -> None: ...
    def getDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getLeadingMargin(self, boolean: bool) -> int: ...
    def getPadding(self) -> int: ...
    def toString(self) -> str: ...

class IconMarginSpan(android.text.style.LeadingMarginSpan, android.text.style.LineHeightSpan):
    @typing.overload
    def __init__(self, bitmap: android.graphics.Bitmap): ...
    @typing.overload
    def __init__(self, bitmap: android.graphics.Bitmap, int: int): ...
    def chooseHeight(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...
    def drawLeadingMargin(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, boolean: bool, layout: android.text.Layout) -> None: ...
    def getBitmap(self) -> android.graphics.Bitmap: ...
    def getLeadingMargin(self, boolean: bool) -> int: ...
    def getPadding(self) -> int: ...
    def toString(self) -> str: ...

class LeadingMarginSpan(ParagraphStyle):
    def drawLeadingMargin(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, boolean: bool, layout: android.text.Layout) -> None: ...
    def getLeadingMargin(self, boolean: bool) -> int: ...
    class LeadingMarginSpan2(android.text.style.LeadingMarginSpan, WrapTogetherSpan):
        def getLeadingMarginLineCount(self) -> int: ...
    class Standard(android.text.style.LeadingMarginSpan, android.text.ParcelableSpan):
        @typing.overload
        def __init__(self, parcel: android.os.Parcel): ...
        @typing.overload
        def __init__(self, int: int): ...
        @typing.overload
        def __init__(self, int: int, int2: int): ...
        def describeContents(self) -> int: ...
        def drawLeadingMargin(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, boolean: bool, layout: android.text.Layout) -> None: ...
        def getLeadingMargin(self, boolean: bool) -> int: ...
        def getSpanTypeId(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LineBackgroundSpan(ParagraphStyle):
    def drawBackground(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, int8: int) -> None: ...
    class Standard(android.text.style.LineBackgroundSpan, android.text.ParcelableSpan):
        @typing.overload
        def __init__(self, parcel: android.os.Parcel): ...
        @typing.overload
        def __init__(self, int: int): ...
        def describeContents(self) -> int: ...
        def drawBackground(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, int8: int) -> None: ...
        def getColor(self) -> int: ...
        def getSpanTypeId(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class LineHeightSpan(ParagraphStyle, WrapTogetherSpan):
    def chooseHeight(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...
    class Standard(android.text.style.LineHeightSpan, android.text.ParcelableSpan):
        @typing.overload
        def __init__(self, parcel: android.os.Parcel): ...
        @typing.overload
        def __init__(self, int: int): ...
        def chooseHeight(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...
        def describeContents(self) -> int: ...
        def getHeight(self) -> int: ...
        def getSpanTypeId(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class WithDensity(android.text.style.LineHeightSpan):
        @typing.overload
        def chooseHeight(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt, textPaint: android.text.TextPaint) -> None: ...
        @typing.overload
        def chooseHeight(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int, int4: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...

class QuoteSpan(LeadingMarginSpan, android.text.ParcelableSpan):
    STANDARD_COLOR: typing.ClassVar[int] = ...
    STANDARD_GAP_WIDTH_PX: typing.ClassVar[int] = ...
    STANDARD_STRIPE_WIDTH_PX: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    def describeContents(self) -> int: ...
    def drawLeadingMargin(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, int: int, int2: int, int3: int, int4: int, int5: int, charSequence: typing.Union[java.lang.CharSequence, str], int6: int, int7: int, boolean: bool, layout: android.text.Layout) -> None: ...
    def getColor(self) -> int: ...
    def getGapWidth(self) -> int: ...
    def getLeadingMargin(self, boolean: bool) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def getStripeWidth(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TabStopSpan(ParagraphStyle):
    def getTabStop(self) -> int: ...
    class Standard(android.text.style.TabStopSpan):
        def __init__(self, int: int): ...
        def getTabStop(self) -> int: ...
        def toString(self) -> str: ...

_TtsSpan__Builder__C = typing.TypeVar('_TtsSpan__Builder__C', bound='TtsSpan.Builder')  # <C>
_TtsSpan__SemioticClassBuilder__C = typing.TypeVar('_TtsSpan__SemioticClassBuilder__C', bound='TtsSpan.SemioticClassBuilder')  # <C>
class TtsSpan(android.text.ParcelableSpan):
    ANIMACY_ANIMATE: typing.ClassVar[str] = ...
    ANIMACY_INANIMATE: typing.ClassVar[str] = ...
    ARG_ANIMACY: typing.ClassVar[str] = ...
    ARG_CASE: typing.ClassVar[str] = ...
    ARG_COUNTRY_CODE: typing.ClassVar[str] = ...
    ARG_CURRENCY: typing.ClassVar[str] = ...
    ARG_DAY: typing.ClassVar[str] = ...
    ARG_DENOMINATOR: typing.ClassVar[str] = ...
    ARG_DIGITS: typing.ClassVar[str] = ...
    ARG_DOMAIN: typing.ClassVar[str] = ...
    ARG_EXTENSION: typing.ClassVar[str] = ...
    ARG_FRACTIONAL_PART: typing.ClassVar[str] = ...
    ARG_FRAGMENT_ID: typing.ClassVar[str] = ...
    ARG_GENDER: typing.ClassVar[str] = ...
    ARG_HOURS: typing.ClassVar[str] = ...
    ARG_INTEGER_PART: typing.ClassVar[str] = ...
    ARG_MINUTES: typing.ClassVar[str] = ...
    ARG_MONTH: typing.ClassVar[str] = ...
    ARG_MULTIPLICITY: typing.ClassVar[str] = ...
    ARG_NUMBER: typing.ClassVar[str] = ...
    ARG_NUMBER_PARTS: typing.ClassVar[str] = ...
    ARG_NUMERATOR: typing.ClassVar[str] = ...
    ARG_PASSWORD: typing.ClassVar[str] = ...
    ARG_PATH: typing.ClassVar[str] = ...
    ARG_PORT: typing.ClassVar[str] = ...
    ARG_PROTOCOL: typing.ClassVar[str] = ...
    ARG_QUANTITY: typing.ClassVar[str] = ...
    ARG_QUERY_STRING: typing.ClassVar[str] = ...
    ARG_TEXT: typing.ClassVar[str] = ...
    ARG_UNIT: typing.ClassVar[str] = ...
    ARG_USERNAME: typing.ClassVar[str] = ...
    ARG_VERBATIM: typing.ClassVar[str] = ...
    ARG_WEEKDAY: typing.ClassVar[str] = ...
    ARG_YEAR: typing.ClassVar[str] = ...
    CASE_ABLATIVE: typing.ClassVar[str] = ...
    CASE_ACCUSATIVE: typing.ClassVar[str] = ...
    CASE_DATIVE: typing.ClassVar[str] = ...
    CASE_GENITIVE: typing.ClassVar[str] = ...
    CASE_INSTRUMENTAL: typing.ClassVar[str] = ...
    CASE_LOCATIVE: typing.ClassVar[str] = ...
    CASE_NOMINATIVE: typing.ClassVar[str] = ...
    CASE_VOCATIVE: typing.ClassVar[str] = ...
    GENDER_FEMALE: typing.ClassVar[str] = ...
    GENDER_MALE: typing.ClassVar[str] = ...
    GENDER_NEUTRAL: typing.ClassVar[str] = ...
    MONTH_APRIL: typing.ClassVar[int] = ...
    MONTH_AUGUST: typing.ClassVar[int] = ...
    MONTH_DECEMBER: typing.ClassVar[int] = ...
    MONTH_FEBRUARY: typing.ClassVar[int] = ...
    MONTH_JANUARY: typing.ClassVar[int] = ...
    MONTH_JULY: typing.ClassVar[int] = ...
    MONTH_JUNE: typing.ClassVar[int] = ...
    MONTH_MARCH: typing.ClassVar[int] = ...
    MONTH_MAY: typing.ClassVar[int] = ...
    MONTH_NOVEMBER: typing.ClassVar[int] = ...
    MONTH_OCTOBER: typing.ClassVar[int] = ...
    MONTH_SEPTEMBER: typing.ClassVar[int] = ...
    MULTIPLICITY_DUAL: typing.ClassVar[str] = ...
    MULTIPLICITY_PLURAL: typing.ClassVar[str] = ...
    MULTIPLICITY_SINGLE: typing.ClassVar[str] = ...
    TYPE_CARDINAL: typing.ClassVar[str] = ...
    TYPE_DATE: typing.ClassVar[str] = ...
    TYPE_DECIMAL: typing.ClassVar[str] = ...
    TYPE_DIGITS: typing.ClassVar[str] = ...
    TYPE_ELECTRONIC: typing.ClassVar[str] = ...
    TYPE_FRACTION: typing.ClassVar[str] = ...
    TYPE_MEASURE: typing.ClassVar[str] = ...
    TYPE_MONEY: typing.ClassVar[str] = ...
    TYPE_ORDINAL: typing.ClassVar[str] = ...
    TYPE_TELEPHONE: typing.ClassVar[str] = ...
    TYPE_TEXT: typing.ClassVar[str] = ...
    TYPE_TIME: typing.ClassVar[str] = ...
    TYPE_VERBATIM: typing.ClassVar[str] = ...
    WEEKDAY_FRIDAY: typing.ClassVar[int] = ...
    WEEKDAY_MONDAY: typing.ClassVar[int] = ...
    WEEKDAY_SATURDAY: typing.ClassVar[int] = ...
    WEEKDAY_SUNDAY: typing.ClassVar[int] = ...
    WEEKDAY_THURSDAY: typing.ClassVar[int] = ...
    WEEKDAY_TUESDAY: typing.ClassVar[int] = ...
    WEEKDAY_WEDNESDAY: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, string: str, persistableBundle: android.os.PersistableBundle): ...
    def describeContents(self) -> int: ...
    def getArgs(self) -> android.os.PersistableBundle: ...
    def getSpanTypeId(self) -> int: ...
    def getType(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder(typing.Generic[_TtsSpan__Builder__C]):
        def __init__(self, string: str): ...
        def build(self) -> 'TtsSpan': ...
        def setIntArgument(self, string: str, int: int) -> _TtsSpan__Builder__C: ...
        def setLongArgument(self, string: str, long: int) -> _TtsSpan__Builder__C: ...
        def setStringArgument(self, string: str, string2: str) -> _TtsSpan__Builder__C: ...
    class CardinalBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.CardinalBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        @typing.overload
        def __init__(self, long: int): ...
        @typing.overload
        def setNumber(self, string: str) -> 'TtsSpan.CardinalBuilder': ...
        @typing.overload
        def setNumber(self, long: int) -> 'TtsSpan.CardinalBuilder': ...
    class DateBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.DateBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, integer: int, integer2: int, integer3: int, integer4: int): ...
        def setDay(self, int: int) -> 'TtsSpan.DateBuilder': ...
        def setMonth(self, int: int) -> 'TtsSpan.DateBuilder': ...
        def setWeekday(self, int: int) -> 'TtsSpan.DateBuilder': ...
        def setYear(self, int: int) -> 'TtsSpan.DateBuilder': ...
    class DecimalBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.DecimalBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, double: float, int: int, int2: int): ...
        @typing.overload
        def __init__(self, string: str, string2: str): ...
        def setArgumentsFromDouble(self, double: float, int: int, int2: int) -> 'TtsSpan.DecimalBuilder': ...
        def setFractionalPart(self, string: str) -> 'TtsSpan.DecimalBuilder': ...
        @typing.overload
        def setIntegerPart(self, string: str) -> 'TtsSpan.DecimalBuilder': ...
        @typing.overload
        def setIntegerPart(self, long: int) -> 'TtsSpan.DecimalBuilder': ...
    class DigitsBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.DigitsBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def setDigits(self, string: str) -> 'TtsSpan.DigitsBuilder': ...
    class ElectronicBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.ElectronicBuilder']):
        def __init__(self): ...
        def setDomain(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setEmailArguments(self, string: str, string2: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setFragmentId(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setPassword(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setPath(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setPort(self, int: int) -> 'TtsSpan.ElectronicBuilder': ...
        def setProtocol(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setQueryString(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
        def setUsername(self, string: str) -> 'TtsSpan.ElectronicBuilder': ...
    class FractionBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.FractionBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, long: int, long2: int, long3: int): ...
        @typing.overload
        def setDenominator(self, string: str) -> 'TtsSpan.FractionBuilder': ...
        @typing.overload
        def setDenominator(self, long: int) -> 'TtsSpan.FractionBuilder': ...
        @typing.overload
        def setIntegerPart(self, string: str) -> 'TtsSpan.FractionBuilder': ...
        @typing.overload
        def setIntegerPart(self, long: int) -> 'TtsSpan.FractionBuilder': ...
        @typing.overload
        def setNumerator(self, string: str) -> 'TtsSpan.FractionBuilder': ...
        @typing.overload
        def setNumerator(self, long: int) -> 'TtsSpan.FractionBuilder': ...
    class MeasureBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.MeasureBuilder']):
        def __init__(self): ...
        @typing.overload
        def setDenominator(self, string: str) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setDenominator(self, long: int) -> 'TtsSpan.MeasureBuilder': ...
        def setFractionalPart(self, string: str) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setIntegerPart(self, string: str) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setIntegerPart(self, long: int) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setNumber(self, string: str) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setNumber(self, long: int) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setNumerator(self, string: str) -> 'TtsSpan.MeasureBuilder': ...
        @typing.overload
        def setNumerator(self, long: int) -> 'TtsSpan.MeasureBuilder': ...
        def setUnit(self, string: str) -> 'TtsSpan.MeasureBuilder': ...
    class MoneyBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.MoneyBuilder']):
        def __init__(self): ...
        def setCurrency(self, string: str) -> 'TtsSpan.MoneyBuilder': ...
        def setFractionalPart(self, string: str) -> 'TtsSpan.MoneyBuilder': ...
        @typing.overload
        def setIntegerPart(self, string: str) -> 'TtsSpan.MoneyBuilder': ...
        @typing.overload
        def setIntegerPart(self, long: int) -> 'TtsSpan.MoneyBuilder': ...
        def setQuantity(self, string: str) -> 'TtsSpan.MoneyBuilder': ...
    class OrdinalBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.OrdinalBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        @typing.overload
        def __init__(self, long: int): ...
        @typing.overload
        def setNumber(self, string: str) -> 'TtsSpan.OrdinalBuilder': ...
        @typing.overload
        def setNumber(self, long: int) -> 'TtsSpan.OrdinalBuilder': ...
    class SemioticClassBuilder(android.text.style.TtsSpan.Builder[_TtsSpan__SemioticClassBuilder__C], typing.Generic[_TtsSpan__SemioticClassBuilder__C]):
        def __init__(self, string: str): ...
        def setAnimacy(self, string: str) -> _TtsSpan__SemioticClassBuilder__C: ...
        def setCase(self, string: str) -> _TtsSpan__SemioticClassBuilder__C: ...
        def setGender(self, string: str) -> _TtsSpan__SemioticClassBuilder__C: ...
        def setMultiplicity(self, string: str) -> _TtsSpan__SemioticClassBuilder__C: ...
    class TelephoneBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.TelephoneBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def setCountryCode(self, string: str) -> 'TtsSpan.TelephoneBuilder': ...
        def setExtension(self, string: str) -> 'TtsSpan.TelephoneBuilder': ...
        def setNumberParts(self, string: str) -> 'TtsSpan.TelephoneBuilder': ...
    class TextBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.TextBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def setText(self, string: str) -> 'TtsSpan.TextBuilder': ...
    class TimeBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.TimeBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, int: int, int2: int): ...
        def setHours(self, int: int) -> 'TtsSpan.TimeBuilder': ...
        def setMinutes(self, int: int) -> 'TtsSpan.TimeBuilder': ...
    class VerbatimBuilder(android.text.style.TtsSpan.SemioticClassBuilder['TtsSpan.VerbatimBuilder']):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, string: str): ...
        def setVerbatim(self, string: str) -> 'TtsSpan.VerbatimBuilder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.text.style")``.

    AbsoluteSizeSpan: typing.Type[AbsoluteSizeSpan]
    AlignmentSpan: typing.Type[AlignmentSpan]
    BackgroundColorSpan: typing.Type[BackgroundColorSpan]
    BulletSpan: typing.Type[BulletSpan]
    CharacterStyle: typing.Type[CharacterStyle]
    ClickableSpan: typing.Type[ClickableSpan]
    DrawableMarginSpan: typing.Type[DrawableMarginSpan]
    DynamicDrawableSpan: typing.Type[DynamicDrawableSpan]
    EasyEditSpan: typing.Type[EasyEditSpan]
    ForegroundColorSpan: typing.Type[ForegroundColorSpan]
    IconMarginSpan: typing.Type[IconMarginSpan]
    ImageSpan: typing.Type[ImageSpan]
    LeadingMarginSpan: typing.Type[LeadingMarginSpan]
    LineBackgroundSpan: typing.Type[LineBackgroundSpan]
    LineBreakConfigSpan: typing.Type[LineBreakConfigSpan]
    LineHeightSpan: typing.Type[LineHeightSpan]
    LocaleSpan: typing.Type[LocaleSpan]
    MaskFilterSpan: typing.Type[MaskFilterSpan]
    MetricAffectingSpan: typing.Type[MetricAffectingSpan]
    ParagraphStyle: typing.Type[ParagraphStyle]
    QuoteSpan: typing.Type[QuoteSpan]
    RelativeSizeSpan: typing.Type[RelativeSizeSpan]
    ReplacementSpan: typing.Type[ReplacementSpan]
    ScaleXSpan: typing.Type[ScaleXSpan]
    StrikethroughSpan: typing.Type[StrikethroughSpan]
    StyleSpan: typing.Type[StyleSpan]
    SubscriptSpan: typing.Type[SubscriptSpan]
    SuggestionRangeSpan: typing.Type[SuggestionRangeSpan]
    SuggestionSpan: typing.Type[SuggestionSpan]
    SuperscriptSpan: typing.Type[SuperscriptSpan]
    TabStopSpan: typing.Type[TabStopSpan]
    TextAppearanceSpan: typing.Type[TextAppearanceSpan]
    TtsSpan: typing.Type[TtsSpan]
    TypefaceSpan: typing.Type[TypefaceSpan]
    URLSpan: typing.Type[URLSpan]
    UnderlineSpan: typing.Type[UnderlineSpan]
    UpdateAppearance: typing.Type[UpdateAppearance]
    UpdateLayout: typing.Type[UpdateLayout]
    WrapTogetherSpan: typing.Type[WrapTogetherSpan]
