
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.lang.ref
import java.net
import java.nio
import jpype
import typing



class ErrnoException(java.lang.Exception):
    errno: int = ...
    @typing.overload
    def __init__(self, string: str, int: int): ...
    @typing.overload
    def __init__(self, string: str, int: int, throwable: java.lang.Throwable): ...
    def getMessage(self) -> str: ...
    def rethrowAsIOException(self) -> java.io.IOException: ...
    def rethrowAsSocketException(self) -> java.net.SocketException: ...

class Int64Ref:
    value: int = ...
    def __init__(self, long: int): ...
    def toString(self) -> str: ...

class Os:
    @staticmethod
    def accept(fileDescriptor: java.io.FileDescriptor, inetSocketAddress: java.net.InetSocketAddress) -> java.io.FileDescriptor: ...
    @staticmethod
    def access(string: str, int: int) -> bool: ...
    @typing.overload
    @staticmethod
    def bind(fileDescriptor: java.io.FileDescriptor, inetAddress: java.net.InetAddress, int: int) -> None: ...
    @typing.overload
    @staticmethod
    def bind(fileDescriptor: java.io.FileDescriptor, socketAddress: java.net.SocketAddress) -> None: ...
    @staticmethod
    def chmod(string: str, int: int) -> None: ...
    @staticmethod
    def chown(string: str, int: int, int2: int) -> None: ...
    @staticmethod
    def close(fileDescriptor: java.io.FileDescriptor) -> None: ...
    @typing.overload
    @staticmethod
    def connect(fileDescriptor: java.io.FileDescriptor, inetAddress: java.net.InetAddress, int: int) -> None: ...
    @typing.overload
    @staticmethod
    def connect(fileDescriptor: java.io.FileDescriptor, socketAddress: java.net.SocketAddress) -> None: ...
    @staticmethod
    def dup(fileDescriptor: java.io.FileDescriptor) -> java.io.FileDescriptor: ...
    @staticmethod
    def dup2(fileDescriptor: java.io.FileDescriptor, int: int) -> java.io.FileDescriptor: ...
    @staticmethod
    def environ() -> typing.MutableSequence[str]: ...
    @staticmethod
    def execv(string: str, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    @staticmethod
    def execve(string: str, stringArray: typing.Union[typing.List[str], jpype.JArray], stringArray2: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    @staticmethod
    def fchmod(fileDescriptor: java.io.FileDescriptor, int: int) -> None: ...
    @staticmethod
    def fchown(fileDescriptor: java.io.FileDescriptor, int: int, int2: int) -> None: ...
    @staticmethod
    def fcntlInt(fileDescriptor: java.io.FileDescriptor, int: int, int2: int) -> int: ...
    @staticmethod
    def fdatasync(fileDescriptor: java.io.FileDescriptor) -> None: ...
    @staticmethod
    def fstat(fileDescriptor: java.io.FileDescriptor) -> 'StructStat': ...
    @staticmethod
    def fstatvfs(fileDescriptor: java.io.FileDescriptor) -> 'StructStatVfs': ...
    @staticmethod
    def fsync(fileDescriptor: java.io.FileDescriptor) -> None: ...
    @staticmethod
    def ftruncate(fileDescriptor: java.io.FileDescriptor, long: int) -> None: ...
    @staticmethod
    def gai_strerror(int: int) -> str: ...
    @staticmethod
    def getegid() -> int: ...
    @staticmethod
    def getenv(string: str) -> str: ...
    @staticmethod
    def geteuid() -> int: ...
    @staticmethod
    def getgid() -> int: ...
    @staticmethod
    def getpeername(fileDescriptor: java.io.FileDescriptor) -> java.net.SocketAddress: ...
    @staticmethod
    def getpid() -> int: ...
    @staticmethod
    def getppid() -> int: ...
    @staticmethod
    def getsockname(fileDescriptor: java.io.FileDescriptor) -> java.net.SocketAddress: ...
    @staticmethod
    def getsockoptTimeval(fileDescriptor: java.io.FileDescriptor, int: int, int2: int) -> 'StructTimeval': ...
    @staticmethod
    def gettid() -> int: ...
    @staticmethod
    def getuid() -> int: ...
    @staticmethod
    def getxattr(string: str, string2: str) -> typing.MutableSequence[int]: ...
    @staticmethod
    def if_indextoname(int: int) -> str: ...
    @staticmethod
    def if_nametoindex(string: str) -> int: ...
    @staticmethod
    def inet_pton(int: int, string: str) -> java.net.InetAddress: ...
    @staticmethod
    def isatty(fileDescriptor: java.io.FileDescriptor) -> bool: ...
    @staticmethod
    def kill(int: int, int2: int) -> None: ...
    @staticmethod
    def lchown(string: str, int: int, int2: int) -> None: ...
    @staticmethod
    def link(string: str, string2: str) -> None: ...
    @staticmethod
    def listen(fileDescriptor: java.io.FileDescriptor, int: int) -> None: ...
    @staticmethod
    def listxattr(string: str) -> typing.MutableSequence[str]: ...
    @staticmethod
    def lseek(fileDescriptor: java.io.FileDescriptor, long: int, int: int) -> int: ...
    @staticmethod
    def lstat(string: str) -> 'StructStat': ...
    @staticmethod
    def memfd_create(string: str, int: int) -> java.io.FileDescriptor: ...
    @staticmethod
    def mincore(long: int, long2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @staticmethod
    def mkdir(string: str, int: int) -> None: ...
    @staticmethod
    def mkfifo(string: str, int: int) -> None: ...
    @staticmethod
    def mlock(long: int, long2: int) -> None: ...
    @staticmethod
    def mmap(long: int, long2: int, int: int, int2: int, fileDescriptor: java.io.FileDescriptor, long3: int) -> int: ...
    @staticmethod
    def msync(long: int, long2: int, int: int) -> None: ...
    @staticmethod
    def munlock(long: int, long2: int) -> None: ...
    @staticmethod
    def munmap(long: int, long2: int) -> None: ...
    @staticmethod
    def open(string: str, int: int, int2: int) -> java.io.FileDescriptor: ...
    @staticmethod
    def pipe() -> typing.MutableSequence[java.io.FileDescriptor]: ...
    @staticmethod
    def poll(structPollfdArray: typing.Union[typing.List['StructPollfd'], jpype.JArray], int: int) -> int: ...
    @staticmethod
    def posix_fallocate(fileDescriptor: java.io.FileDescriptor, long: int, long2: int) -> None: ...
    @staticmethod
    def prctl(int: int, long: int, long2: int, long3: int, long4: int) -> int: ...
    @typing.overload
    @staticmethod
    def pread(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, long: int) -> int: ...
    @typing.overload
    @staticmethod
    def pread(fileDescriptor: java.io.FileDescriptor, byteBuffer: java.nio.ByteBuffer, long: int) -> int: ...
    @typing.overload
    @staticmethod
    def pwrite(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, long: int) -> int: ...
    @typing.overload
    @staticmethod
    def pwrite(fileDescriptor: java.io.FileDescriptor, byteBuffer: java.nio.ByteBuffer, long: int) -> int: ...
    @typing.overload
    @staticmethod
    def read(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    @typing.overload
    @staticmethod
    def read(fileDescriptor: java.io.FileDescriptor, byteBuffer: java.nio.ByteBuffer) -> int: ...
    @staticmethod
    def readlink(string: str) -> str: ...
    @staticmethod
    def readv(fileDescriptor: java.io.FileDescriptor, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]) -> int: ...
    @typing.overload
    @staticmethod
    def recvfrom(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, int3: int, inetSocketAddress: java.net.InetSocketAddress) -> int: ...
    @typing.overload
    @staticmethod
    def recvfrom(fileDescriptor: java.io.FileDescriptor, byteBuffer: java.nio.ByteBuffer, int: int, inetSocketAddress: java.net.InetSocketAddress) -> int: ...
    @staticmethod
    def recvmsg(fileDescriptor: java.io.FileDescriptor, structMsghdr: 'StructMsghdr', int: int) -> int: ...
    @staticmethod
    def remove(string: str) -> None: ...
    @staticmethod
    def removexattr(string: str, string2: str) -> None: ...
    @staticmethod
    def rename(string: str, string2: str) -> None: ...
    @staticmethod
    def sendfile(fileDescriptor: java.io.FileDescriptor, fileDescriptor2: java.io.FileDescriptor, int64Ref: Int64Ref, long: int) -> int: ...
    @staticmethod
    def sendmsg(fileDescriptor: java.io.FileDescriptor, structMsghdr: 'StructMsghdr', int: int) -> int: ...
    @typing.overload
    @staticmethod
    def sendto(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, int3: int, inetAddress: java.net.InetAddress, int4: int) -> int: ...
    @typing.overload
    @staticmethod
    def sendto(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, int3: int, socketAddress: java.net.SocketAddress) -> int: ...
    @typing.overload
    @staticmethod
    def sendto(fileDescriptor: java.io.FileDescriptor, byteBuffer: java.nio.ByteBuffer, int: int, inetAddress: java.net.InetAddress, int2: int) -> int: ...
    @staticmethod
    def setegid(int: int) -> None: ...
    @staticmethod
    def setenv(string: str, string2: str, boolean: bool) -> None: ...
    @staticmethod
    def seteuid(int: int) -> None: ...
    @staticmethod
    def setgid(int: int) -> None: ...
    @staticmethod
    def setsid() -> int: ...
    @staticmethod
    def setsockoptInt(fileDescriptor: java.io.FileDescriptor, int: int, int2: int, int3: int) -> None: ...
    @staticmethod
    def setsockoptTimeval(fileDescriptor: java.io.FileDescriptor, int: int, int2: int, structTimeval: 'StructTimeval') -> None: ...
    @staticmethod
    def setuid(int: int) -> None: ...
    @staticmethod
    def setxattr(string: str, string2: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int) -> None: ...
    @staticmethod
    def shutdown(fileDescriptor: java.io.FileDescriptor, int: int) -> None: ...
    @staticmethod
    def socket(int: int, int2: int, int3: int) -> java.io.FileDescriptor: ...
    @staticmethod
    def socketpair(int: int, int2: int, int3: int, fileDescriptor: java.io.FileDescriptor, fileDescriptor2: java.io.FileDescriptor) -> None: ...
    @staticmethod
    def stat(string: str) -> 'StructStat': ...
    @staticmethod
    def statvfs(string: str) -> 'StructStatVfs': ...
    @staticmethod
    def strerror(int: int) -> str: ...
    @staticmethod
    def strsignal(int: int) -> str: ...
    @staticmethod
    def symlink(string: str, string2: str) -> None: ...
    @staticmethod
    def sysconf(int: int) -> int: ...
    @staticmethod
    def tcdrain(fileDescriptor: java.io.FileDescriptor) -> None: ...
    @staticmethod
    def tcsendbreak(fileDescriptor: java.io.FileDescriptor, int: int) -> None: ...
    @staticmethod
    def umask(int: int) -> int: ...
    @staticmethod
    def uname() -> 'StructUtsname': ...
    @staticmethod
    def unsetenv(string: str) -> None: ...
    @typing.overload
    @staticmethod
    def write(fileDescriptor: java.io.FileDescriptor, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    @typing.overload
    @staticmethod
    def write(fileDescriptor: java.io.FileDescriptor, byteBuffer: java.nio.ByteBuffer) -> int: ...
    @staticmethod
    def writev(fileDescriptor: java.io.FileDescriptor, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray], intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]) -> int: ...

class OsConstants:
    AF_INET: typing.ClassVar[int] = ...
    AF_INET6: typing.ClassVar[int] = ...
    AF_NETLINK: typing.ClassVar[int] = ...
    AF_PACKET: typing.ClassVar[int] = ...
    AF_UNIX: typing.ClassVar[int] = ...
    AF_UNSPEC: typing.ClassVar[int] = ...
    AF_VSOCK: typing.ClassVar[int] = ...
    AI_ADDRCONFIG: typing.ClassVar[int] = ...
    AI_ALL: typing.ClassVar[int] = ...
    AI_CANONNAME: typing.ClassVar[int] = ...
    AI_NUMERICHOST: typing.ClassVar[int] = ...
    AI_NUMERICSERV: typing.ClassVar[int] = ...
    AI_PASSIVE: typing.ClassVar[int] = ...
    AI_V4MAPPED: typing.ClassVar[int] = ...
    ARPHRD_ETHER: typing.ClassVar[int] = ...
    CAP_AUDIT_CONTROL: typing.ClassVar[int] = ...
    CAP_AUDIT_WRITE: typing.ClassVar[int] = ...
    CAP_BLOCK_SUSPEND: typing.ClassVar[int] = ...
    CAP_CHOWN: typing.ClassVar[int] = ...
    CAP_DAC_OVERRIDE: typing.ClassVar[int] = ...
    CAP_DAC_READ_SEARCH: typing.ClassVar[int] = ...
    CAP_FOWNER: typing.ClassVar[int] = ...
    CAP_FSETID: typing.ClassVar[int] = ...
    CAP_IPC_LOCK: typing.ClassVar[int] = ...
    CAP_IPC_OWNER: typing.ClassVar[int] = ...
    CAP_KILL: typing.ClassVar[int] = ...
    CAP_LAST_CAP: typing.ClassVar[int] = ...
    CAP_LEASE: typing.ClassVar[int] = ...
    CAP_LINUX_IMMUTABLE: typing.ClassVar[int] = ...
    CAP_MAC_ADMIN: typing.ClassVar[int] = ...
    CAP_MAC_OVERRIDE: typing.ClassVar[int] = ...
    CAP_MKNOD: typing.ClassVar[int] = ...
    CAP_NET_ADMIN: typing.ClassVar[int] = ...
    CAP_NET_BIND_SERVICE: typing.ClassVar[int] = ...
    CAP_NET_BROADCAST: typing.ClassVar[int] = ...
    CAP_NET_RAW: typing.ClassVar[int] = ...
    CAP_SETFCAP: typing.ClassVar[int] = ...
    CAP_SETGID: typing.ClassVar[int] = ...
    CAP_SETPCAP: typing.ClassVar[int] = ...
    CAP_SETUID: typing.ClassVar[int] = ...
    CAP_SYSLOG: typing.ClassVar[int] = ...
    CAP_SYS_ADMIN: typing.ClassVar[int] = ...
    CAP_SYS_BOOT: typing.ClassVar[int] = ...
    CAP_SYS_CHROOT: typing.ClassVar[int] = ...
    CAP_SYS_MODULE: typing.ClassVar[int] = ...
    CAP_SYS_NICE: typing.ClassVar[int] = ...
    CAP_SYS_PACCT: typing.ClassVar[int] = ...
    CAP_SYS_PTRACE: typing.ClassVar[int] = ...
    CAP_SYS_RAWIO: typing.ClassVar[int] = ...
    CAP_SYS_RESOURCE: typing.ClassVar[int] = ...
    CAP_SYS_TIME: typing.ClassVar[int] = ...
    CAP_SYS_TTY_CONFIG: typing.ClassVar[int] = ...
    CAP_WAKE_ALARM: typing.ClassVar[int] = ...
    E2BIG: typing.ClassVar[int] = ...
    EACCES: typing.ClassVar[int] = ...
    EADDRINUSE: typing.ClassVar[int] = ...
    EADDRNOTAVAIL: typing.ClassVar[int] = ...
    EAFNOSUPPORT: typing.ClassVar[int] = ...
    EAGAIN: typing.ClassVar[int] = ...
    EAI_AGAIN: typing.ClassVar[int] = ...
    EAI_BADFLAGS: typing.ClassVar[int] = ...
    EAI_FAIL: typing.ClassVar[int] = ...
    EAI_FAMILY: typing.ClassVar[int] = ...
    EAI_MEMORY: typing.ClassVar[int] = ...
    EAI_NODATA: typing.ClassVar[int] = ...
    EAI_NONAME: typing.ClassVar[int] = ...
    EAI_OVERFLOW: typing.ClassVar[int] = ...
    EAI_SERVICE: typing.ClassVar[int] = ...
    EAI_SOCKTYPE: typing.ClassVar[int] = ...
    EAI_SYSTEM: typing.ClassVar[int] = ...
    EALREADY: typing.ClassVar[int] = ...
    EBADF: typing.ClassVar[int] = ...
    EBADMSG: typing.ClassVar[int] = ...
    EBUSY: typing.ClassVar[int] = ...
    ECANCELED: typing.ClassVar[int] = ...
    ECHILD: typing.ClassVar[int] = ...
    ECONNABORTED: typing.ClassVar[int] = ...
    ECONNREFUSED: typing.ClassVar[int] = ...
    ECONNRESET: typing.ClassVar[int] = ...
    EDEADLK: typing.ClassVar[int] = ...
    EDESTADDRREQ: typing.ClassVar[int] = ...
    EDOM: typing.ClassVar[int] = ...
    EDQUOT: typing.ClassVar[int] = ...
    EEXIST: typing.ClassVar[int] = ...
    EFAULT: typing.ClassVar[int] = ...
    EFBIG: typing.ClassVar[int] = ...
    EHOSTUNREACH: typing.ClassVar[int] = ...
    EIDRM: typing.ClassVar[int] = ...
    EILSEQ: typing.ClassVar[int] = ...
    EINPROGRESS: typing.ClassVar[int] = ...
    EINTR: typing.ClassVar[int] = ...
    EINVAL: typing.ClassVar[int] = ...
    EIO: typing.ClassVar[int] = ...
    EISCONN: typing.ClassVar[int] = ...
    EISDIR: typing.ClassVar[int] = ...
    ELOOP: typing.ClassVar[int] = ...
    EMFILE: typing.ClassVar[int] = ...
    EMLINK: typing.ClassVar[int] = ...
    EMSGSIZE: typing.ClassVar[int] = ...
    EMULTIHOP: typing.ClassVar[int] = ...
    ENAMETOOLONG: typing.ClassVar[int] = ...
    ENETDOWN: typing.ClassVar[int] = ...
    ENETRESET: typing.ClassVar[int] = ...
    ENETUNREACH: typing.ClassVar[int] = ...
    ENFILE: typing.ClassVar[int] = ...
    ENOBUFS: typing.ClassVar[int] = ...
    ENODATA: typing.ClassVar[int] = ...
    ENODEV: typing.ClassVar[int] = ...
    ENOENT: typing.ClassVar[int] = ...
    ENOEXEC: typing.ClassVar[int] = ...
    ENOLCK: typing.ClassVar[int] = ...
    ENOLINK: typing.ClassVar[int] = ...
    ENOMEM: typing.ClassVar[int] = ...
    ENOMSG: typing.ClassVar[int] = ...
    ENONET: typing.ClassVar[int] = ...
    ENOPROTOOPT: typing.ClassVar[int] = ...
    ENOSPC: typing.ClassVar[int] = ...
    ENOSR: typing.ClassVar[int] = ...
    ENOSTR: typing.ClassVar[int] = ...
    ENOSYS: typing.ClassVar[int] = ...
    ENOTCONN: typing.ClassVar[int] = ...
    ENOTDIR: typing.ClassVar[int] = ...
    ENOTEMPTY: typing.ClassVar[int] = ...
    ENOTSOCK: typing.ClassVar[int] = ...
    ENOTSUP: typing.ClassVar[int] = ...
    ENOTTY: typing.ClassVar[int] = ...
    ENXIO: typing.ClassVar[int] = ...
    EOPNOTSUPP: typing.ClassVar[int] = ...
    EOVERFLOW: typing.ClassVar[int] = ...
    EPERM: typing.ClassVar[int] = ...
    EPIPE: typing.ClassVar[int] = ...
    EPROTO: typing.ClassVar[int] = ...
    EPROTONOSUPPORT: typing.ClassVar[int] = ...
    EPROTOTYPE: typing.ClassVar[int] = ...
    ERANGE: typing.ClassVar[int] = ...
    EROFS: typing.ClassVar[int] = ...
    ESPIPE: typing.ClassVar[int] = ...
    ESRCH: typing.ClassVar[int] = ...
    ESTALE: typing.ClassVar[int] = ...
    ETH_P_ALL: typing.ClassVar[int] = ...
    ETH_P_ARP: typing.ClassVar[int] = ...
    ETH_P_IP: typing.ClassVar[int] = ...
    ETH_P_IPV6: typing.ClassVar[int] = ...
    ETIME: typing.ClassVar[int] = ...
    ETIMEDOUT: typing.ClassVar[int] = ...
    ETXTBSY: typing.ClassVar[int] = ...
    EXDEV: typing.ClassVar[int] = ...
    EXIT_FAILURE: typing.ClassVar[int] = ...
    EXIT_SUCCESS: typing.ClassVar[int] = ...
    FD_CLOEXEC: typing.ClassVar[int] = ...
    FIONREAD: typing.ClassVar[int] = ...
    F_DUPFD: typing.ClassVar[int] = ...
    F_DUPFD_CLOEXEC: typing.ClassVar[int] = ...
    F_GETFD: typing.ClassVar[int] = ...
    F_GETFL: typing.ClassVar[int] = ...
    F_GETLK: typing.ClassVar[int] = ...
    F_GETLK64: typing.ClassVar[int] = ...
    F_GETOWN: typing.ClassVar[int] = ...
    F_OK: typing.ClassVar[int] = ...
    F_RDLCK: typing.ClassVar[int] = ...
    F_SETFD: typing.ClassVar[int] = ...
    F_SETFL: typing.ClassVar[int] = ...
    F_SETLK: typing.ClassVar[int] = ...
    F_SETLK64: typing.ClassVar[int] = ...
    F_SETLKW: typing.ClassVar[int] = ...
    F_SETLKW64: typing.ClassVar[int] = ...
    F_SETOWN: typing.ClassVar[int] = ...
    F_UNLCK: typing.ClassVar[int] = ...
    F_WRLCK: typing.ClassVar[int] = ...
    ICMP6_ECHO_REPLY: typing.ClassVar[int] = ...
    ICMP6_ECHO_REQUEST: typing.ClassVar[int] = ...
    ICMP_ECHO: typing.ClassVar[int] = ...
    ICMP_ECHOREPLY: typing.ClassVar[int] = ...
    IFA_F_DADFAILED: typing.ClassVar[int] = ...
    IFA_F_DEPRECATED: typing.ClassVar[int] = ...
    IFA_F_HOMEADDRESS: typing.ClassVar[int] = ...
    IFA_F_MANAGETEMPADDR: typing.ClassVar[int] = ...
    IFA_F_NODAD: typing.ClassVar[int] = ...
    IFA_F_NOPREFIXROUTE: typing.ClassVar[int] = ...
    IFA_F_OPTIMISTIC: typing.ClassVar[int] = ...
    IFA_F_PERMANENT: typing.ClassVar[int] = ...
    IFA_F_SECONDARY: typing.ClassVar[int] = ...
    IFA_F_TEMPORARY: typing.ClassVar[int] = ...
    IFA_F_TENTATIVE: typing.ClassVar[int] = ...
    IFF_ALLMULTI: typing.ClassVar[int] = ...
    IFF_AUTOMEDIA: typing.ClassVar[int] = ...
    IFF_BROADCAST: typing.ClassVar[int] = ...
    IFF_DEBUG: typing.ClassVar[int] = ...
    IFF_DYNAMIC: typing.ClassVar[int] = ...
    IFF_LOOPBACK: typing.ClassVar[int] = ...
    IFF_MASTER: typing.ClassVar[int] = ...
    IFF_MULTICAST: typing.ClassVar[int] = ...
    IFF_NOARP: typing.ClassVar[int] = ...
    IFF_NOTRAILERS: typing.ClassVar[int] = ...
    IFF_POINTOPOINT: typing.ClassVar[int] = ...
    IFF_PORTSEL: typing.ClassVar[int] = ...
    IFF_PROMISC: typing.ClassVar[int] = ...
    IFF_RUNNING: typing.ClassVar[int] = ...
    IFF_SLAVE: typing.ClassVar[int] = ...
    IFF_UP: typing.ClassVar[int] = ...
    IPPROTO_ESP: typing.ClassVar[int] = ...
    IPPROTO_ICMP: typing.ClassVar[int] = ...
    IPPROTO_ICMPV6: typing.ClassVar[int] = ...
    IPPROTO_IP: typing.ClassVar[int] = ...
    IPPROTO_IPV6: typing.ClassVar[int] = ...
    IPPROTO_RAW: typing.ClassVar[int] = ...
    IPPROTO_TCP: typing.ClassVar[int] = ...
    IPPROTO_UDP: typing.ClassVar[int] = ...
    IPV6_CHECKSUM: typing.ClassVar[int] = ...
    IPV6_MULTICAST_HOPS: typing.ClassVar[int] = ...
    IPV6_MULTICAST_IF: typing.ClassVar[int] = ...
    IPV6_MULTICAST_LOOP: typing.ClassVar[int] = ...
    IPV6_PKTINFO: typing.ClassVar[int] = ...
    IPV6_RECVDSTOPTS: typing.ClassVar[int] = ...
    IPV6_RECVHOPLIMIT: typing.ClassVar[int] = ...
    IPV6_RECVHOPOPTS: typing.ClassVar[int] = ...
    IPV6_RECVPKTINFO: typing.ClassVar[int] = ...
    IPV6_RECVRTHDR: typing.ClassVar[int] = ...
    IPV6_RECVTCLASS: typing.ClassVar[int] = ...
    IPV6_TCLASS: typing.ClassVar[int] = ...
    IPV6_UNICAST_HOPS: typing.ClassVar[int] = ...
    IPV6_V6ONLY: typing.ClassVar[int] = ...
    IP_MULTICAST_IF: typing.ClassVar[int] = ...
    IP_MULTICAST_LOOP: typing.ClassVar[int] = ...
    IP_MULTICAST_TTL: typing.ClassVar[int] = ...
    IP_TOS: typing.ClassVar[int] = ...
    IP_TTL: typing.ClassVar[int] = ...
    MAP_ANONYMOUS: typing.ClassVar[int] = ...
    MAP_FIXED: typing.ClassVar[int] = ...
    MAP_PRIVATE: typing.ClassVar[int] = ...
    MAP_SHARED: typing.ClassVar[int] = ...
    MCAST_BLOCK_SOURCE: typing.ClassVar[int] = ...
    MCAST_JOIN_GROUP: typing.ClassVar[int] = ...
    MCAST_JOIN_SOURCE_GROUP: typing.ClassVar[int] = ...
    MCAST_LEAVE_GROUP: typing.ClassVar[int] = ...
    MCAST_LEAVE_SOURCE_GROUP: typing.ClassVar[int] = ...
    MCAST_UNBLOCK_SOURCE: typing.ClassVar[int] = ...
    MCL_CURRENT: typing.ClassVar[int] = ...
    MCL_FUTURE: typing.ClassVar[int] = ...
    MFD_CLOEXEC: typing.ClassVar[int] = ...
    MSG_CTRUNC: typing.ClassVar[int] = ...
    MSG_DONTROUTE: typing.ClassVar[int] = ...
    MSG_EOR: typing.ClassVar[int] = ...
    MSG_OOB: typing.ClassVar[int] = ...
    MSG_PEEK: typing.ClassVar[int] = ...
    MSG_TRUNC: typing.ClassVar[int] = ...
    MSG_WAITALL: typing.ClassVar[int] = ...
    MS_ASYNC: typing.ClassVar[int] = ...
    MS_INVALIDATE: typing.ClassVar[int] = ...
    MS_SYNC: typing.ClassVar[int] = ...
    NETLINK_INET_DIAG: typing.ClassVar[int] = ...
    NETLINK_NETFILTER: typing.ClassVar[int] = ...
    NETLINK_ROUTE: typing.ClassVar[int] = ...
    NETLINK_XFRM: typing.ClassVar[int] = ...
    NI_DGRAM: typing.ClassVar[int] = ...
    NI_NAMEREQD: typing.ClassVar[int] = ...
    NI_NOFQDN: typing.ClassVar[int] = ...
    NI_NUMERICHOST: typing.ClassVar[int] = ...
    NI_NUMERICSERV: typing.ClassVar[int] = ...
    O_ACCMODE: typing.ClassVar[int] = ...
    O_APPEND: typing.ClassVar[int] = ...
    O_CLOEXEC: typing.ClassVar[int] = ...
    O_CREAT: typing.ClassVar[int] = ...
    O_DSYNC: typing.ClassVar[int] = ...
    O_EXCL: typing.ClassVar[int] = ...
    O_NOCTTY: typing.ClassVar[int] = ...
    O_NOFOLLOW: typing.ClassVar[int] = ...
    O_NONBLOCK: typing.ClassVar[int] = ...
    O_RDONLY: typing.ClassVar[int] = ...
    O_RDWR: typing.ClassVar[int] = ...
    O_SYNC: typing.ClassVar[int] = ...
    O_TRUNC: typing.ClassVar[int] = ...
    O_WRONLY: typing.ClassVar[int] = ...
    PACKET_IGNORE_OUTGOING: typing.ClassVar[int] = ...
    POLLERR: typing.ClassVar[int] = ...
    POLLHUP: typing.ClassVar[int] = ...
    POLLIN: typing.ClassVar[int] = ...
    POLLNVAL: typing.ClassVar[int] = ...
    POLLOUT: typing.ClassVar[int] = ...
    POLLPRI: typing.ClassVar[int] = ...
    POLLRDBAND: typing.ClassVar[int] = ...
    POLLRDNORM: typing.ClassVar[int] = ...
    POLLWRBAND: typing.ClassVar[int] = ...
    POLLWRNORM: typing.ClassVar[int] = ...
    PROT_EXEC: typing.ClassVar[int] = ...
    PROT_NONE: typing.ClassVar[int] = ...
    PROT_READ: typing.ClassVar[int] = ...
    PROT_WRITE: typing.ClassVar[int] = ...
    PR_GET_DUMPABLE: typing.ClassVar[int] = ...
    PR_SET_DUMPABLE: typing.ClassVar[int] = ...
    PR_SET_NO_NEW_PRIVS: typing.ClassVar[int] = ...
    RTMGRP_NEIGH: typing.ClassVar[int] = ...
    RT_SCOPE_HOST: typing.ClassVar[int] = ...
    RT_SCOPE_LINK: typing.ClassVar[int] = ...
    RT_SCOPE_NOWHERE: typing.ClassVar[int] = ...
    RT_SCOPE_SITE: typing.ClassVar[int] = ...
    RT_SCOPE_UNIVERSE: typing.ClassVar[int] = ...
    R_OK: typing.ClassVar[int] = ...
    SEEK_CUR: typing.ClassVar[int] = ...
    SEEK_END: typing.ClassVar[int] = ...
    SEEK_SET: typing.ClassVar[int] = ...
    SHUT_RD: typing.ClassVar[int] = ...
    SHUT_RDWR: typing.ClassVar[int] = ...
    SHUT_WR: typing.ClassVar[int] = ...
    SIGABRT: typing.ClassVar[int] = ...
    SIGALRM: typing.ClassVar[int] = ...
    SIGBUS: typing.ClassVar[int] = ...
    SIGCHLD: typing.ClassVar[int] = ...
    SIGCONT: typing.ClassVar[int] = ...
    SIGFPE: typing.ClassVar[int] = ...
    SIGHUP: typing.ClassVar[int] = ...
    SIGILL: typing.ClassVar[int] = ...
    SIGINT: typing.ClassVar[int] = ...
    SIGIO: typing.ClassVar[int] = ...
    SIGKILL: typing.ClassVar[int] = ...
    SIGPIPE: typing.ClassVar[int] = ...
    SIGPROF: typing.ClassVar[int] = ...
    SIGPWR: typing.ClassVar[int] = ...
    SIGQUIT: typing.ClassVar[int] = ...
    SIGRTMAX: typing.ClassVar[int] = ...
    SIGRTMIN: typing.ClassVar[int] = ...
    SIGSEGV: typing.ClassVar[int] = ...
    SIGSTKFLT: typing.ClassVar[int] = ...
    SIGSTOP: typing.ClassVar[int] = ...
    SIGSYS: typing.ClassVar[int] = ...
    SIGTERM: typing.ClassVar[int] = ...
    SIGTRAP: typing.ClassVar[int] = ...
    SIGTSTP: typing.ClassVar[int] = ...
    SIGTTIN: typing.ClassVar[int] = ...
    SIGTTOU: typing.ClassVar[int] = ...
    SIGURG: typing.ClassVar[int] = ...
    SIGUSR1: typing.ClassVar[int] = ...
    SIGUSR2: typing.ClassVar[int] = ...
    SIGVTALRM: typing.ClassVar[int] = ...
    SIGWINCH: typing.ClassVar[int] = ...
    SIGXCPU: typing.ClassVar[int] = ...
    SIGXFSZ: typing.ClassVar[int] = ...
    SIOCGIFADDR: typing.ClassVar[int] = ...
    SIOCGIFBRDADDR: typing.ClassVar[int] = ...
    SIOCGIFDSTADDR: typing.ClassVar[int] = ...
    SIOCGIFNETMASK: typing.ClassVar[int] = ...
    SOCK_CLOEXEC: typing.ClassVar[int] = ...
    SOCK_DGRAM: typing.ClassVar[int] = ...
    SOCK_NONBLOCK: typing.ClassVar[int] = ...
    SOCK_RAW: typing.ClassVar[int] = ...
    SOCK_SEQPACKET: typing.ClassVar[int] = ...
    SOCK_STREAM: typing.ClassVar[int] = ...
    SOL_PACKET: typing.ClassVar[int] = ...
    SOL_SOCKET: typing.ClassVar[int] = ...
    SOL_UDP: typing.ClassVar[int] = ...
    SO_BINDTODEVICE: typing.ClassVar[int] = ...
    SO_BROADCAST: typing.ClassVar[int] = ...
    SO_DEBUG: typing.ClassVar[int] = ...
    SO_DONTROUTE: typing.ClassVar[int] = ...
    SO_ERROR: typing.ClassVar[int] = ...
    SO_KEEPALIVE: typing.ClassVar[int] = ...
    SO_LINGER: typing.ClassVar[int] = ...
    SO_OOBINLINE: typing.ClassVar[int] = ...
    SO_PASSCRED: typing.ClassVar[int] = ...
    SO_PEERCRED: typing.ClassVar[int] = ...
    SO_RCVBUF: typing.ClassVar[int] = ...
    SO_RCVLOWAT: typing.ClassVar[int] = ...
    SO_RCVTIMEO: typing.ClassVar[int] = ...
    SO_REUSEADDR: typing.ClassVar[int] = ...
    SO_SNDBUF: typing.ClassVar[int] = ...
    SO_SNDLOWAT: typing.ClassVar[int] = ...
    SO_SNDTIMEO: typing.ClassVar[int] = ...
    SO_TYPE: typing.ClassVar[int] = ...
    STDERR_FILENO: typing.ClassVar[int] = ...
    STDIN_FILENO: typing.ClassVar[int] = ...
    STDOUT_FILENO: typing.ClassVar[int] = ...
    ST_MANDLOCK: typing.ClassVar[int] = ...
    ST_NOATIME: typing.ClassVar[int] = ...
    ST_NODEV: typing.ClassVar[int] = ...
    ST_NODIRATIME: typing.ClassVar[int] = ...
    ST_NOEXEC: typing.ClassVar[int] = ...
    ST_NOSUID: typing.ClassVar[int] = ...
    ST_RDONLY: typing.ClassVar[int] = ...
    ST_RELATIME: typing.ClassVar[int] = ...
    ST_SYNCHRONOUS: typing.ClassVar[int] = ...
    S_IFBLK: typing.ClassVar[int] = ...
    S_IFCHR: typing.ClassVar[int] = ...
    S_IFDIR: typing.ClassVar[int] = ...
    S_IFIFO: typing.ClassVar[int] = ...
    S_IFLNK: typing.ClassVar[int] = ...
    S_IFMT: typing.ClassVar[int] = ...
    S_IFREG: typing.ClassVar[int] = ...
    S_IFSOCK: typing.ClassVar[int] = ...
    S_IRGRP: typing.ClassVar[int] = ...
    S_IROTH: typing.ClassVar[int] = ...
    S_IRUSR: typing.ClassVar[int] = ...
    S_IRWXG: typing.ClassVar[int] = ...
    S_IRWXO: typing.ClassVar[int] = ...
    S_IRWXU: typing.ClassVar[int] = ...
    S_ISGID: typing.ClassVar[int] = ...
    S_ISUID: typing.ClassVar[int] = ...
    S_ISVTX: typing.ClassVar[int] = ...
    S_IWGRP: typing.ClassVar[int] = ...
    S_IWOTH: typing.ClassVar[int] = ...
    S_IWUSR: typing.ClassVar[int] = ...
    S_IXGRP: typing.ClassVar[int] = ...
    S_IXOTH: typing.ClassVar[int] = ...
    S_IXUSR: typing.ClassVar[int] = ...
    TCP_NODELAY: typing.ClassVar[int] = ...
    TCP_USER_TIMEOUT: typing.ClassVar[int] = ...
    UDP_GRO: typing.ClassVar[int] = ...
    UDP_SEGMENT: typing.ClassVar[int] = ...
    VMADDR_CID_ANY: typing.ClassVar[int] = ...
    VMADDR_CID_HOST: typing.ClassVar[int] = ...
    VMADDR_CID_LOCAL: typing.ClassVar[int] = ...
    VMADDR_PORT_ANY: typing.ClassVar[int] = ...
    WCONTINUED: typing.ClassVar[int] = ...
    WEXITED: typing.ClassVar[int] = ...
    WNOHANG: typing.ClassVar[int] = ...
    WNOWAIT: typing.ClassVar[int] = ...
    WSTOPPED: typing.ClassVar[int] = ...
    WUNTRACED: typing.ClassVar[int] = ...
    W_OK: typing.ClassVar[int] = ...
    X_OK: typing.ClassVar[int] = ...
    _SC_2_CHAR_TERM: typing.ClassVar[int] = ...
    _SC_2_C_BIND: typing.ClassVar[int] = ...
    _SC_2_C_DEV: typing.ClassVar[int] = ...
    _SC_2_C_VERSION: typing.ClassVar[int] = ...
    _SC_2_FORT_DEV: typing.ClassVar[int] = ...
    _SC_2_FORT_RUN: typing.ClassVar[int] = ...
    _SC_2_LOCALEDEF: typing.ClassVar[int] = ...
    _SC_2_SW_DEV: typing.ClassVar[int] = ...
    _SC_2_UPE: typing.ClassVar[int] = ...
    _SC_2_VERSION: typing.ClassVar[int] = ...
    _SC_AIO_LISTIO_MAX: typing.ClassVar[int] = ...
    _SC_AIO_MAX: typing.ClassVar[int] = ...
    _SC_AIO_PRIO_DELTA_MAX: typing.ClassVar[int] = ...
    _SC_ARG_MAX: typing.ClassVar[int] = ...
    _SC_ASYNCHRONOUS_IO: typing.ClassVar[int] = ...
    _SC_ATEXIT_MAX: typing.ClassVar[int] = ...
    _SC_AVPHYS_PAGES: typing.ClassVar[int] = ...
    _SC_BC_BASE_MAX: typing.ClassVar[int] = ...
    _SC_BC_DIM_MAX: typing.ClassVar[int] = ...
    _SC_BC_SCALE_MAX: typing.ClassVar[int] = ...
    _SC_BC_STRING_MAX: typing.ClassVar[int] = ...
    _SC_CHILD_MAX: typing.ClassVar[int] = ...
    _SC_CLK_TCK: typing.ClassVar[int] = ...
    _SC_COLL_WEIGHTS_MAX: typing.ClassVar[int] = ...
    _SC_DELAYTIMER_MAX: typing.ClassVar[int] = ...
    _SC_EXPR_NEST_MAX: typing.ClassVar[int] = ...
    _SC_FSYNC: typing.ClassVar[int] = ...
    _SC_GETGR_R_SIZE_MAX: typing.ClassVar[int] = ...
    _SC_GETPW_R_SIZE_MAX: typing.ClassVar[int] = ...
    _SC_IOV_MAX: typing.ClassVar[int] = ...
    _SC_JOB_CONTROL: typing.ClassVar[int] = ...
    _SC_LINE_MAX: typing.ClassVar[int] = ...
    _SC_LOGIN_NAME_MAX: typing.ClassVar[int] = ...
    _SC_MAPPED_FILES: typing.ClassVar[int] = ...
    _SC_MEMLOCK: typing.ClassVar[int] = ...
    _SC_MEMLOCK_RANGE: typing.ClassVar[int] = ...
    _SC_MEMORY_PROTECTION: typing.ClassVar[int] = ...
    _SC_MESSAGE_PASSING: typing.ClassVar[int] = ...
    _SC_MQ_OPEN_MAX: typing.ClassVar[int] = ...
    _SC_MQ_PRIO_MAX: typing.ClassVar[int] = ...
    _SC_NGROUPS_MAX: typing.ClassVar[int] = ...
    _SC_NPROCESSORS_CONF: typing.ClassVar[int] = ...
    _SC_NPROCESSORS_ONLN: typing.ClassVar[int] = ...
    _SC_OPEN_MAX: typing.ClassVar[int] = ...
    _SC_PAGESIZE: typing.ClassVar[int] = ...
    _SC_PAGE_SIZE: typing.ClassVar[int] = ...
    _SC_PASS_MAX: typing.ClassVar[int] = ...
    _SC_PHYS_PAGES: typing.ClassVar[int] = ...
    _SC_PRIORITIZED_IO: typing.ClassVar[int] = ...
    _SC_PRIORITY_SCHEDULING: typing.ClassVar[int] = ...
    _SC_REALTIME_SIGNALS: typing.ClassVar[int] = ...
    _SC_RE_DUP_MAX: typing.ClassVar[int] = ...
    _SC_RTSIG_MAX: typing.ClassVar[int] = ...
    _SC_SAVED_IDS: typing.ClassVar[int] = ...
    _SC_SEMAPHORES: typing.ClassVar[int] = ...
    _SC_SEM_NSEMS_MAX: typing.ClassVar[int] = ...
    _SC_SEM_VALUE_MAX: typing.ClassVar[int] = ...
    _SC_SHARED_MEMORY_OBJECTS: typing.ClassVar[int] = ...
    _SC_SIGQUEUE_MAX: typing.ClassVar[int] = ...
    _SC_STREAM_MAX: typing.ClassVar[int] = ...
    _SC_SYNCHRONIZED_IO: typing.ClassVar[int] = ...
    _SC_THREADS: typing.ClassVar[int] = ...
    _SC_THREAD_ATTR_STACKADDR: typing.ClassVar[int] = ...
    _SC_THREAD_ATTR_STACKSIZE: typing.ClassVar[int] = ...
    _SC_THREAD_DESTRUCTOR_ITERATIONS: typing.ClassVar[int] = ...
    _SC_THREAD_KEYS_MAX: typing.ClassVar[int] = ...
    _SC_THREAD_PRIORITY_SCHEDULING: typing.ClassVar[int] = ...
    _SC_THREAD_PRIO_INHERIT: typing.ClassVar[int] = ...
    _SC_THREAD_PRIO_PROTECT: typing.ClassVar[int] = ...
    _SC_THREAD_SAFE_FUNCTIONS: typing.ClassVar[int] = ...
    _SC_THREAD_STACK_MIN: typing.ClassVar[int] = ...
    _SC_THREAD_THREADS_MAX: typing.ClassVar[int] = ...
    _SC_TIMERS: typing.ClassVar[int] = ...
    _SC_TIMER_MAX: typing.ClassVar[int] = ...
    _SC_TTY_NAME_MAX: typing.ClassVar[int] = ...
    _SC_TZNAME_MAX: typing.ClassVar[int] = ...
    _SC_VERSION: typing.ClassVar[int] = ...
    _SC_XBS5_ILP32_OFF32: typing.ClassVar[int] = ...
    _SC_XBS5_ILP32_OFFBIG: typing.ClassVar[int] = ...
    _SC_XBS5_LP64_OFF64: typing.ClassVar[int] = ...
    _SC_XBS5_LPBIG_OFFBIG: typing.ClassVar[int] = ...
    _SC_XOPEN_CRYPT: typing.ClassVar[int] = ...
    _SC_XOPEN_ENH_I18N: typing.ClassVar[int] = ...
    _SC_XOPEN_LEGACY: typing.ClassVar[int] = ...
    _SC_XOPEN_REALTIME: typing.ClassVar[int] = ...
    _SC_XOPEN_REALTIME_THREADS: typing.ClassVar[int] = ...
    _SC_XOPEN_SHM: typing.ClassVar[int] = ...
    _SC_XOPEN_UNIX: typing.ClassVar[int] = ...
    _SC_XOPEN_VERSION: typing.ClassVar[int] = ...
    _SC_XOPEN_XCU_VERSION: typing.ClassVar[int] = ...
    @staticmethod
    def S_ISBLK(int: int) -> bool: ...
    @staticmethod
    def S_ISCHR(int: int) -> bool: ...
    @staticmethod
    def S_ISDIR(int: int) -> bool: ...
    @staticmethod
    def S_ISFIFO(int: int) -> bool: ...
    @staticmethod
    def S_ISLNK(int: int) -> bool: ...
    @staticmethod
    def S_ISREG(int: int) -> bool: ...
    @staticmethod
    def S_ISSOCK(int: int) -> bool: ...
    @staticmethod
    def WCOREDUMP(int: int) -> bool: ...
    @staticmethod
    def WEXITSTATUS(int: int) -> int: ...
    @staticmethod
    def WIFEXITED(int: int) -> bool: ...
    @staticmethod
    def WIFSIGNALED(int: int) -> bool: ...
    @staticmethod
    def WIFSTOPPED(int: int) -> bool: ...
    @staticmethod
    def WSTOPSIG(int: int) -> int: ...
    @staticmethod
    def WTERMSIG(int: int) -> int: ...
    @staticmethod
    def errnoName(int: int) -> str: ...
    @staticmethod
    def gaiName(int: int) -> str: ...

class StructCmsghdr:
    cmsg_data: typing.MutableSequence[int] = ...
    cmsg_level: int = ...
    cmsg_type: int = ...
    @typing.overload
    def __init__(self, int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    @typing.overload
    def __init__(self, int: int, int2: int, short: int): ...

class StructMsghdr:
    msg_control: typing.MutableSequence[StructCmsghdr] = ...
    msg_flags: int = ...
    msg_iov: typing.MutableSequence[java.nio.ByteBuffer] = ...
    msg_name: java.net.SocketAddress = ...
    def __init__(self, socketAddress: java.net.SocketAddress, byteBufferArray: typing.Union[typing.List[java.nio.ByteBuffer], jpype.JArray], structCmsghdrArray: typing.Union[typing.List[StructCmsghdr], jpype.JArray], int: int): ...

class StructPollfd:
    events: int = ...
    fd: java.io.FileDescriptor = ...
    revents: int = ...
    userData: typing.Any = ...
    def __init__(self): ...
    def toString(self) -> str: ...

class StructStat:
    st_atim: 'StructTimespec' = ...
    st_atime: int = ...
    st_blksize: int = ...
    st_blocks: int = ...
    st_ctim: 'StructTimespec' = ...
    st_ctime: int = ...
    st_dev: int = ...
    st_gid: int = ...
    st_ino: int = ...
    st_mode: int = ...
    st_mtim: 'StructTimespec' = ...
    st_mtime: int = ...
    st_nlink: int = ...
    st_rdev: int = ...
    st_size: int = ...
    st_uid: int = ...
    @typing.overload
    def __init__(self, long: int, long2: int, int: int, long3: int, int2: int, int3: int, long4: int, long5: int, structTimespec: 'StructTimespec', structTimespec2: 'StructTimespec', structTimespec3: 'StructTimespec', long6: int, long7: int): ...
    @typing.overload
    def __init__(self, long: int, long2: int, int: int, long3: int, int2: int, int3: int, long4: int, long5: int, long6: int, long7: int, long8: int, long9: int, long10: int): ...
    def toString(self) -> str: ...

class StructStatVfs:
    f_bavail: int = ...
    f_bfree: int = ...
    f_blocks: int = ...
    f_bsize: int = ...
    f_favail: int = ...
    f_ffree: int = ...
    f_files: int = ...
    f_flag: int = ...
    f_frsize: int = ...
    f_fsid: int = ...
    f_namemax: int = ...
    def __init__(self, long: int, long2: int, long3: int, long4: int, long5: int, long6: int, long7: int, long8: int, long9: int, long10: int, long11: int): ...
    def toString(self) -> str: ...

class StructTimespec(java.lang.Comparable['StructTimespec']):
    tv_nsec: int = ...
    tv_sec: int = ...
    def __init__(self, long: int, long2: int): ...
    def compareTo(self, structTimespec: 'StructTimespec') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class StructTimeval:
    tv_sec: int = ...
    tv_usec: int = ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromMillis(long: int) -> 'StructTimeval': ...
    def hashCode(self) -> int: ...
    def toMillis(self) -> int: ...
    def toString(self) -> str: ...

class StructUtsname:
    machine: str = ...
    nodename: str = ...
    release: str = ...
    sysname: str = ...
    version: str = ...
    def __init__(self, string: str, string2: str, string3: str, string4: str, string5: str): ...
    def toString(self) -> str: ...

class SystemCleaner:
    @staticmethod
    def cleaner() -> java.lang.ref.Cleaner: ...

class VmSocketAddress(java.net.SocketAddress):
    def __init__(self, int: int, int2: int): ...
    def getSvmCid(self) -> int: ...
    def getSvmPort(self) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.system")``.

    ErrnoException: typing.Type[ErrnoException]
    Int64Ref: typing.Type[Int64Ref]
    Os: typing.Type[Os]
    OsConstants: typing.Type[OsConstants]
    StructCmsghdr: typing.Type[StructCmsghdr]
    StructMsghdr: typing.Type[StructMsghdr]
    StructPollfd: typing.Type[StructPollfd]
    StructStat: typing.Type[StructStat]
    StructStatVfs: typing.Type[StructStatVfs]
    StructTimespec: typing.Type[StructTimespec]
    StructTimeval: typing.Type[StructTimeval]
    StructUtsname: typing.Type[StructUtsname]
    SystemCleaner: typing.Type[SystemCleaner]
    VmSocketAddress: typing.Type[VmSocketAddress]
