
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.util
import typing



class DomainVerificationManager:
    def getDomainVerificationUserState(self, string: str) -> 'DomainVerificationUserState': ...

class DomainVerificationUserState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DOMAIN_STATE_NONE: typing.ClassVar[int] = ...
    DOMAIN_STATE_SELECTED: typing.ClassVar[int] = ...
    DOMAIN_STATE_VERIFIED: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHostToStateMap(self) -> java.util.Map[str, int]: ...
    def getPackageName(self) -> str: ...
    def getUser(self) -> android.os.UserHandle: ...
    def hashCode(self) -> int: ...
    def isLinkHandlingAllowed(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.content.pm.verify.domain")``.

    DomainVerificationManager: typing.Type[DomainVerificationManager]
    DomainVerificationUserState: typing.Type[DomainVerificationUserState]
