
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.net
import android.net.wifi
import android.net.wifi.p2p.nsd
import android.os
import java.lang
import java.net
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class WifiP2pConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV4_DHCP: typing.ClassVar[int] = ...
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV6_LINK_LOCAL: typing.ClassVar[int] = ...
    GROUP_OWNER_BAND_2GHZ: typing.ClassVar[int] = ...
    GROUP_OWNER_BAND_5GHZ: typing.ClassVar[int] = ...
    GROUP_OWNER_BAND_AUTO: typing.ClassVar[int] = ...
    GROUP_OWNER_INTENT_AUTO: typing.ClassVar[int] = ...
    GROUP_OWNER_INTENT_MAX: typing.ClassVar[int] = ...
    GROUP_OWNER_INTENT_MIN: typing.ClassVar[int] = ...
    deviceAddress: str = ...
    groupOwnerIntent: int = ...
    wps: android.net.wifi.WpsInfo = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiP2pConfig: 'WifiP2pConfig'): ...
    def describeContents(self) -> int: ...
    def getGroupClientIpProvisioningMode(self) -> int: ...
    def getGroupOwnerBand(self) -> int: ...
    def getNetworkId(self) -> int: ...
    def getNetworkName(self) -> str: ...
    def getPassphrase(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'WifiP2pConfig': ...
        def enablePersistentMode(self, boolean: bool) -> 'WifiP2pConfig.Builder': ...
        def setDeviceAddress(self, macAddress: android.net.MacAddress) -> 'WifiP2pConfig.Builder': ...
        def setGroupClientIpProvisioningMode(self, int: int) -> 'WifiP2pConfig.Builder': ...
        def setGroupOperatingBand(self, int: int) -> 'WifiP2pConfig.Builder': ...
        def setGroupOperatingFrequency(self, int: int) -> 'WifiP2pConfig.Builder': ...
        def setNetworkName(self, string: str) -> 'WifiP2pConfig.Builder': ...
        def setPassphrase(self, string: str) -> 'WifiP2pConfig.Builder': ...

class WifiP2pDevice(android.os.Parcelable):
    AVAILABLE: typing.ClassVar[int] = ...
    CONNECTED: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FAILED: typing.ClassVar[int] = ...
    INVITED: typing.ClassVar[int] = ...
    UNAVAILABLE: typing.ClassVar[int] = ...
    deviceAddress: str = ...
    deviceName: str = ...
    primaryDeviceType: str = ...
    secondaryDeviceType: str = ...
    status: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiP2pDevice: 'WifiP2pDevice'): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getIpAddress(self) -> java.net.InetAddress: ...
    def getVendorElements(self) -> java.util.List[android.net.wifi.ScanResult.InformationElement]: ...
    def getWfdInfo(self) -> 'WifiP2pWfdInfo': ...
    def hashCode(self) -> int: ...
    def isGroupOwner(self) -> bool: ...
    def isServiceDiscoveryCapable(self) -> bool: ...
    def toString(self) -> str: ...
    def update(self, wifiP2pDevice: 'WifiP2pDevice') -> None: ...
    def wpsDisplaySupported(self) -> bool: ...
    def wpsKeypadSupported(self) -> bool: ...
    def wpsPbcSupported(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiP2pDeviceList(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiP2pDeviceList: 'WifiP2pDeviceList'): ...
    def describeContents(self) -> int: ...
    def get(self, string: str) -> WifiP2pDevice: ...
    def getDeviceList(self) -> java.util.Collection[WifiP2pDevice]: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiP2pDiscoveryConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getFrequencyMhz(self) -> int: ...
    def getScanType(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int): ...
        def build(self) -> 'WifiP2pDiscoveryConfig': ...
        def setFrequencyMhz(self, int: int) -> 'WifiP2pDiscoveryConfig.Builder': ...

class WifiP2pGroup(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    NETWORK_ID_PERSISTENT: typing.ClassVar[int] = ...
    NETWORK_ID_TEMPORARY: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiP2pGroup: 'WifiP2pGroup'): ...
    def describeContents(self) -> int: ...
    def getClientList(self) -> java.util.Collection[WifiP2pDevice]: ...
    def getFrequency(self) -> int: ...
    def getInterface(self) -> str: ...
    def getNetworkId(self) -> int: ...
    def getNetworkName(self) -> str: ...
    def getOwner(self) -> WifiP2pDevice: ...
    def getPassphrase(self) -> str: ...
    def isGroupOwner(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiP2pInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    groupFormed: bool = ...
    groupOwnerAddress: java.net.InetAddress = ...
    isGroupOwner: bool = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiP2pInfo: 'WifiP2pInfo'): ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiP2pManager:
    ACTION_WIFI_P2P_LISTEN_STATE_CHANGED: typing.ClassVar[str] = ...
    ACTION_WIFI_P2P_REQUEST_RESPONSE_CHANGED: typing.ClassVar[str] = ...
    BUSY: typing.ClassVar[int] = ...
    CONNECTION_REQUEST_ACCEPT: typing.ClassVar[int] = ...
    CONNECTION_REQUEST_DEFER_SHOW_PIN_TO_SERVICE: typing.ClassVar[int] = ...
    CONNECTION_REQUEST_DEFER_TO_SERVICE: typing.ClassVar[int] = ...
    CONNECTION_REQUEST_REJECT: typing.ClassVar[int] = ...
    ERROR: typing.ClassVar[int] = ...
    EXTRA_DISCOVERY_STATE: typing.ClassVar[str] = ...
    EXTRA_LISTEN_STATE: typing.ClassVar[str] = ...
    EXTRA_NETWORK_INFO: typing.ClassVar[str] = ...
    EXTRA_P2P_DEVICE_LIST: typing.ClassVar[str] = ...
    EXTRA_REQUEST_CONFIG: typing.ClassVar[str] = ...
    EXTRA_REQUEST_RESPONSE: typing.ClassVar[str] = ...
    EXTRA_WIFI_P2P_DEVICE: typing.ClassVar[str] = ...
    EXTRA_WIFI_P2P_GROUP: typing.ClassVar[str] = ...
    EXTRA_WIFI_P2P_INFO: typing.ClassVar[str] = ...
    EXTRA_WIFI_STATE: typing.ClassVar[str] = ...
    GROUP_CREATION_FAILURE_REASON_CONNECTION_CANCELLED: typing.ClassVar[int] = ...
    GROUP_CREATION_FAILURE_REASON_GROUP_REMOVED: typing.ClassVar[int] = ...
    GROUP_CREATION_FAILURE_REASON_INVITATION_FAILED: typing.ClassVar[int] = ...
    GROUP_CREATION_FAILURE_REASON_PROVISION_DISCOVERY_FAILED: typing.ClassVar[int] = ...
    GROUP_CREATION_FAILURE_REASON_TIMED_OUT: typing.ClassVar[int] = ...
    GROUP_CREATION_FAILURE_REASON_USER_REJECTED: typing.ClassVar[int] = ...
    NO_SERVICE_REQUESTS: typing.ClassVar[int] = ...
    P2P_UNSUPPORTED: typing.ClassVar[int] = ...
    WIFI_P2P_CONNECTION_CHANGED_ACTION: typing.ClassVar[str] = ...
    WIFI_P2P_DISCOVERY_CHANGED_ACTION: typing.ClassVar[str] = ...
    WIFI_P2P_DISCOVERY_STARTED: typing.ClassVar[int] = ...
    WIFI_P2P_DISCOVERY_STOPPED: typing.ClassVar[int] = ...
    WIFI_P2P_LISTEN_STARTED: typing.ClassVar[int] = ...
    WIFI_P2P_LISTEN_STOPPED: typing.ClassVar[int] = ...
    WIFI_P2P_PEERS_CHANGED_ACTION: typing.ClassVar[str] = ...
    WIFI_P2P_SCAN_FULL: typing.ClassVar[int] = ...
    WIFI_P2P_SCAN_SINGLE_FREQ: typing.ClassVar[int] = ...
    WIFI_P2P_SCAN_SOCIAL: typing.ClassVar[int] = ...
    WIFI_P2P_STATE_CHANGED_ACTION: typing.ClassVar[str] = ...
    WIFI_P2P_STATE_DISABLED: typing.ClassVar[int] = ...
    WIFI_P2P_STATE_ENABLED: typing.ClassVar[int] = ...
    WIFI_P2P_THIS_DEVICE_CHANGED_ACTION: typing.ClassVar[str] = ...
    def addExternalApprover(self, channel: 'WifiP2pManager.Channel', macAddress: android.net.MacAddress, externalApproverRequestListener: 'WifiP2pManager.ExternalApproverRequestListener') -> None: ...
    def addLocalService(self, channel: 'WifiP2pManager.Channel', wifiP2pServiceInfo: android.net.wifi.p2p.nsd.WifiP2pServiceInfo, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def addServiceRequest(self, channel: 'WifiP2pManager.Channel', wifiP2pServiceRequest: android.net.wifi.p2p.nsd.WifiP2pServiceRequest, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def cancelConnect(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def clearLocalServices(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def clearServiceRequests(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def connect(self, channel: 'WifiP2pManager.Channel', wifiP2pConfig: WifiP2pConfig, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    @typing.overload
    def createGroup(self, channel: 'WifiP2pManager.Channel', wifiP2pConfig: WifiP2pConfig, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    @typing.overload
    def createGroup(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def discoverPeers(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def discoverPeersOnSocialChannels(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def discoverPeersOnSpecificFrequency(self, channel: 'WifiP2pManager.Channel', int: int, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def discoverServices(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def getListenState(self, channel: 'WifiP2pManager.Channel', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[int], typing.Callable[[int], None]]) -> None: ...
    @staticmethod
    def getP2pMaxAllowedVendorElementsLengthBytes() -> int: ...
    def initialize(self, context: android.content.Context, looper: android.os.Looper, channelListener: typing.Union['WifiP2pManager.ChannelListener', typing.Callable]) -> 'WifiP2pManager.Channel': ...
    def isChannelConstrainedDiscoverySupported(self) -> bool: ...
    def isGroupClientRemovalSupported(self) -> bool: ...
    def isGroupOwnerIPv6LinkLocalAddressProvided(self) -> bool: ...
    def isSetVendorElementsSupported(self) -> bool: ...
    def registerWifiP2pListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], wifiP2pListener: 'WifiP2pManager.WifiP2pListener') -> None: ...
    def removeClient(self, channel: 'WifiP2pManager.Channel', macAddress: android.net.MacAddress, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def removeExternalApprover(self, channel: 'WifiP2pManager.Channel', macAddress: android.net.MacAddress, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def removeGroup(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def removeLocalService(self, channel: 'WifiP2pManager.Channel', wifiP2pServiceInfo: android.net.wifi.p2p.nsd.WifiP2pServiceInfo, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def removeServiceRequest(self, channel: 'WifiP2pManager.Channel', wifiP2pServiceRequest: android.net.wifi.p2p.nsd.WifiP2pServiceRequest, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def requestConnectionInfo(self, channel: 'WifiP2pManager.Channel', connectionInfoListener: typing.Union['WifiP2pManager.ConnectionInfoListener', typing.Callable]) -> None: ...
    def requestDeviceInfo(self, channel: 'WifiP2pManager.Channel', deviceInfoListener: typing.Union['WifiP2pManager.DeviceInfoListener', typing.Callable]) -> None: ...
    def requestDiscoveryState(self, channel: 'WifiP2pManager.Channel', discoveryStateListener: typing.Union['WifiP2pManager.DiscoveryStateListener', typing.Callable]) -> None: ...
    def requestGroupInfo(self, channel: 'WifiP2pManager.Channel', groupInfoListener: typing.Union['WifiP2pManager.GroupInfoListener', typing.Callable]) -> None: ...
    def requestNetworkInfo(self, channel: 'WifiP2pManager.Channel', networkInfoListener: typing.Union['WifiP2pManager.NetworkInfoListener', typing.Callable]) -> None: ...
    def requestP2pState(self, channel: 'WifiP2pManager.Channel', p2pStateListener: typing.Union['WifiP2pManager.P2pStateListener', typing.Callable]) -> None: ...
    def requestPeers(self, channel: 'WifiP2pManager.Channel', peerListListener: typing.Union['WifiP2pManager.PeerListListener', typing.Callable]) -> None: ...
    @typing.overload
    def setConnectionRequestResult(self, channel: 'WifiP2pManager.Channel', macAddress: android.net.MacAddress, int: int, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    @typing.overload
    def setConnectionRequestResult(self, channel: 'WifiP2pManager.Channel', macAddress: android.net.MacAddress, int: int, string: str, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def setDnsSdResponseListeners(self, channel: 'WifiP2pManager.Channel', dnsSdServiceResponseListener: typing.Union['WifiP2pManager.DnsSdServiceResponseListener', typing.Callable], dnsSdTxtRecordListener: typing.Union['WifiP2pManager.DnsSdTxtRecordListener', typing.Callable]) -> None: ...
    def setServiceResponseListener(self, channel: 'WifiP2pManager.Channel', serviceResponseListener: typing.Union['WifiP2pManager.ServiceResponseListener', typing.Callable]) -> None: ...
    def setUpnpServiceResponseListener(self, channel: 'WifiP2pManager.Channel', upnpServiceResponseListener: typing.Union['WifiP2pManager.UpnpServiceResponseListener', typing.Callable]) -> None: ...
    def setVendorElements(self, channel: 'WifiP2pManager.Channel', list: java.util.List[android.net.wifi.ScanResult.InformationElement], actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def setWfdInfo(self, channel: 'WifiP2pManager.Channel', wifiP2pWfdInfo: 'WifiP2pWfdInfo', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def startListening(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def startPeerDiscovery(self, channel: 'WifiP2pManager.Channel', wifiP2pDiscoveryConfig: WifiP2pDiscoveryConfig, actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def stopListening(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def stopPeerDiscovery(self, channel: 'WifiP2pManager.Channel', actionListener: 'WifiP2pManager.ActionListener') -> None: ...
    def unregisterWifiP2pListener(self, wifiP2pListener: 'WifiP2pManager.WifiP2pListener') -> None: ...
    class ActionListener:
        def onFailure(self, int: int) -> None: ...
        def onSuccess(self) -> None: ...
    class Channel(java.lang.AutoCloseable):
        def close(self) -> None: ...
    class ChannelListener:
        def onChannelDisconnected(self) -> None: ...
    class ConnectionInfoListener:
        def onConnectionInfoAvailable(self, wifiP2pInfo: WifiP2pInfo) -> None: ...
    class DeviceInfoListener:
        def onDeviceInfoAvailable(self, wifiP2pDevice: WifiP2pDevice) -> None: ...
    class DiscoveryStateListener:
        def onDiscoveryStateAvailable(self, int: int) -> None: ...
    class DnsSdServiceResponseListener:
        def onDnsSdServiceAvailable(self, string: str, string2: str, wifiP2pDevice: WifiP2pDevice) -> None: ...
    class DnsSdTxtRecordListener:
        def onDnsSdTxtRecordAvailable(self, string: str, map: typing.Union[java.util.Map[str, str], typing.Mapping[str, str]], wifiP2pDevice: WifiP2pDevice) -> None: ...
    class ExternalApproverRequestListener:
        APPROVER_DETACH_REASON_CLOSE: typing.ClassVar[int] = ...
        APPROVER_DETACH_REASON_FAILURE: typing.ClassVar[int] = ...
        APPROVER_DETACH_REASON_REMOVE: typing.ClassVar[int] = ...
        APPROVER_DETACH_REASON_REPLACE: typing.ClassVar[int] = ...
        REQUEST_TYPE_INVITATION: typing.ClassVar[int] = ...
        REQUEST_TYPE_JOIN: typing.ClassVar[int] = ...
        REQUEST_TYPE_NEGOTIATION: typing.ClassVar[int] = ...
        def onAttached(self, macAddress: android.net.MacAddress) -> None: ...
        def onConnectionRequested(self, int: int, wifiP2pConfig: WifiP2pConfig, wifiP2pDevice: WifiP2pDevice) -> None: ...
        def onDetached(self, macAddress: android.net.MacAddress, int: int) -> None: ...
        def onPinGenerated(self, macAddress: android.net.MacAddress, string: str) -> None: ...
    class GroupInfoListener:
        def onGroupInfoAvailable(self, wifiP2pGroup: WifiP2pGroup) -> None: ...
    class NetworkInfoListener:
        def onNetworkInfoAvailable(self, networkInfo: android.net.NetworkInfo) -> None: ...
    class P2pStateListener:
        def onP2pStateAvailable(self, int: int) -> None: ...
    class PeerListListener:
        def onPeersAvailable(self, wifiP2pDeviceList: WifiP2pDeviceList) -> None: ...
    class ServiceResponseListener:
        def onServiceAvailable(self, int: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], wifiP2pDevice: WifiP2pDevice) -> None: ...
    class UpnpServiceResponseListener:
        def onUpnpServiceAvailable(self, list: java.util.List[str], wifiP2pDevice: WifiP2pDevice) -> None: ...
    class WifiP2pListener:
        def onDeviceConfigurationChanged(self, wifiP2pDevice: WifiP2pDevice) -> None: ...
        def onDiscoveryStateChanged(self, int: int) -> None: ...
        def onFrequencyChanged(self, wifiP2pInfo: WifiP2pInfo, wifiP2pGroup: WifiP2pGroup) -> None: ...
        def onGroupCreated(self, wifiP2pInfo: WifiP2pInfo, wifiP2pGroup: WifiP2pGroup) -> None: ...
        def onGroupCreating(self) -> None: ...
        def onGroupCreationFailed(self, int: int) -> None: ...
        def onGroupNegotiationRejectedByUser(self) -> None: ...
        def onGroupRemoved(self) -> None: ...
        def onListenStateChanged(self, int: int) -> None: ...
        def onP2pStateChanged(self, int: int) -> None: ...
        def onPeerClientDisconnected(self, wifiP2pInfo: WifiP2pInfo, wifiP2pGroup: WifiP2pGroup) -> None: ...
        def onPeerClientJoined(self, wifiP2pInfo: WifiP2pInfo, wifiP2pGroup: WifiP2pGroup) -> None: ...
        def onPeerListChanged(self, wifiP2pDeviceList: WifiP2pDeviceList) -> None: ...

class WifiP2pWfdInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DEVICE_INFO_AUDIO_ONLY_SUPPORT_AT_SOURCE: typing.ClassVar[int] = ...
    DEVICE_INFO_AUDIO_UNSUPPORTED_AT_PRIMARY_SINK: typing.ClassVar[int] = ...
    DEVICE_INFO_CONTENT_PROTECTION_SUPPORT: typing.ClassVar[int] = ...
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SINK: typing.ClassVar[int] = ...
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SOURCE: typing.ClassVar[int] = ...
    DEVICE_INFO_DEVICE_TYPE_MASK: typing.ClassVar[int] = ...
    DEVICE_INFO_PREFERRED_CONNECTIVITY_MASK: typing.ClassVar[int] = ...
    DEVICE_INFO_SESSION_AVAILABLE_MASK: typing.ClassVar[int] = ...
    DEVICE_INFO_TDLS_PERSISTENT_GROUP: typing.ClassVar[int] = ...
    DEVICE_INFO_TDLS_PERSISTENT_GROUP_REINVOKE: typing.ClassVar[int] = ...
    DEVICE_INFO_TIME_SYNCHRONIZATION_SUPPORT: typing.ClassVar[int] = ...
    DEVICE_INFO_WFD_SERVICE_DISCOVERY_SUPPORT: typing.ClassVar[int] = ...
    DEVICE_TYPE_PRIMARY_SINK: typing.ClassVar[int] = ...
    DEVICE_TYPE_SECONDARY_SINK: typing.ClassVar[int] = ...
    DEVICE_TYPE_SOURCE_OR_PRIMARY_SINK: typing.ClassVar[int] = ...
    DEVICE_TYPE_WFD_SOURCE: typing.ClassVar[int] = ...
    PREFERRED_CONNECTIVITY_P2P: typing.ClassVar[int] = ...
    PREFERRED_CONNECTIVITY_TDLS: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiP2pWfdInfo: 'WifiP2pWfdInfo'): ...
    def describeContents(self) -> int: ...
    def getControlPort(self) -> int: ...
    def getDeviceInfo(self) -> int: ...
    def getDeviceType(self) -> int: ...
    def getMaxThroughput(self) -> int: ...
    def getR2DeviceInfo(self) -> int: ...
    def getR2DeviceType(self) -> int: ...
    def isContentProtectionSupported(self) -> bool: ...
    def isCoupledSinkSupportedAtSink(self) -> bool: ...
    def isCoupledSinkSupportedAtSource(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isR2Supported(self) -> bool: ...
    def isSessionAvailable(self) -> bool: ...
    def setContentProtectionSupported(self, boolean: bool) -> None: ...
    def setControlPort(self, int: int) -> None: ...
    def setCoupledSinkSupportAtSink(self, boolean: bool) -> None: ...
    def setCoupledSinkSupportAtSource(self, boolean: bool) -> None: ...
    def setDeviceType(self, int: int) -> bool: ...
    def setEnabled(self, boolean: bool) -> None: ...
    def setMaxThroughput(self, int: int) -> None: ...
    def setR2DeviceType(self, int: int) -> bool: ...
    def setSessionAvailable(self, boolean: bool) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.wifi.p2p")``.

    WifiP2pConfig: typing.Type[WifiP2pConfig]
    WifiP2pDevice: typing.Type[WifiP2pDevice]
    WifiP2pDeviceList: typing.Type[WifiP2pDeviceList]
    WifiP2pDiscoveryConfig: typing.Type[WifiP2pDiscoveryConfig]
    WifiP2pGroup: typing.Type[WifiP2pGroup]
    WifiP2pInfo: typing.Type[WifiP2pInfo]
    WifiP2pManager: typing.Type[WifiP2pManager]
    WifiP2pWfdInfo: typing.Type[WifiP2pWfdInfo]
    nsd: android.net.wifi.p2p.nsd.__module_protocol__
