
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.os
import android.telephony
import java.lang
import java.util
import jpype
import typing



class GsmCellLocation(android.telephony.CellLocation):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, bundle: android.os.Bundle): ...
    def equals(self, object: typing.Any) -> bool: ...
    def fillInNotifierBundle(self, bundle: android.os.Bundle) -> None: ...
    def getCid(self) -> int: ...
    def getLac(self) -> int: ...
    def getPsc(self) -> int: ...
    def hashCode(self) -> int: ...
    def setLacAndCid(self, int: int, int2: int) -> None: ...
    def setStateInvalid(self) -> None: ...
    def toString(self) -> str: ...

class SmsManager:
    RESULT_ERROR_GENERIC_FAILURE: typing.ClassVar[int] = ...
    RESULT_ERROR_NO_SERVICE: typing.ClassVar[int] = ...
    RESULT_ERROR_NULL_PDU: typing.ClassVar[int] = ...
    RESULT_ERROR_RADIO_OFF: typing.ClassVar[int] = ...
    STATUS_ON_SIM_FREE: typing.ClassVar[int] = ...
    STATUS_ON_SIM_READ: typing.ClassVar[int] = ...
    STATUS_ON_SIM_SENT: typing.ClassVar[int] = ...
    STATUS_ON_SIM_UNREAD: typing.ClassVar[int] = ...
    STATUS_ON_SIM_UNSENT: typing.ClassVar[int] = ...
    def divideMessage(self, string: str) -> java.util.ArrayList[str]: ...
    @staticmethod
    def getDefault() -> 'SmsManager': ...
    def sendDataMessage(self, string: str, string2: str, short: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], pendingIntent: android.app.PendingIntent, pendingIntent2: android.app.PendingIntent) -> None: ...
    def sendMultipartTextMessage(self, string: str, string2: str, arrayList: java.util.ArrayList[str], arrayList2: java.util.ArrayList[android.app.PendingIntent], arrayList3: java.util.ArrayList[android.app.PendingIntent]) -> None: ...
    def sendTextMessage(self, string: str, string2: str, string3: str, pendingIntent: android.app.PendingIntent, pendingIntent2: android.app.PendingIntent) -> None: ...

class SmsMessage:
    ENCODING_16BIT: typing.ClassVar[int] = ...
    ENCODING_7BIT: typing.ClassVar[int] = ...
    ENCODING_8BIT: typing.ClassVar[int] = ...
    ENCODING_UNKNOWN: typing.ClassVar[int] = ...
    MAX_USER_DATA_BYTES: typing.ClassVar[int] = ...
    MAX_USER_DATA_SEPTETS: typing.ClassVar[int] = ...
    MAX_USER_DATA_SEPTETS_WITH_HEADER: typing.ClassVar[int] = ...
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def calculateLength(charSequence: typing.Union[java.lang.CharSequence, str], boolean: bool) -> typing.MutableSequence[int]: ...
    @typing.overload
    @staticmethod
    def calculateLength(string: str, boolean: bool) -> typing.MutableSequence[int]: ...
    @staticmethod
    def createFromPdu(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'SmsMessage': ...
    def getDisplayMessageBody(self) -> str: ...
    def getDisplayOriginatingAddress(self) -> str: ...
    def getEmailBody(self) -> str: ...
    def getEmailFrom(self) -> str: ...
    def getIndexOnSim(self) -> int: ...
    def getMessageBody(self) -> str: ...
    def getMessageClass(self) -> 'SmsMessage.MessageClass': ...
    def getOriginatingAddress(self) -> str: ...
    def getPdu(self) -> typing.MutableSequence[int]: ...
    def getProtocolIdentifier(self) -> int: ...
    def getPseudoSubject(self) -> str: ...
    def getServiceCenterAddress(self) -> str: ...
    def getStatus(self) -> int: ...
    def getStatusOnSim(self) -> int: ...
    @typing.overload
    @staticmethod
    def getSubmitPdu(string: str, string2: str, string3: str, boolean: bool) -> 'SmsMessage.SubmitPdu': ...
    @typing.overload
    @staticmethod
    def getSubmitPdu(string: str, string2: str, short: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], boolean: bool) -> 'SmsMessage.SubmitPdu': ...
    @staticmethod
    def getTPLayerLengthForPDU(string: str) -> int: ...
    def getTimestampMillis(self) -> int: ...
    def getUserData(self) -> typing.MutableSequence[int]: ...
    def isCphsMwiMessage(self) -> bool: ...
    def isEmail(self) -> bool: ...
    def isMWIClearMessage(self) -> bool: ...
    def isMWISetMessage(self) -> bool: ...
    def isMwiDontStore(self) -> bool: ...
    def isReplace(self) -> bool: ...
    def isReplyPathPresent(self) -> bool: ...
    def isStatusReportMessage(self) -> bool: ...
    class MessageClass(java.lang.Enum['SmsMessage.MessageClass']):
        UNKNOWN: typing.ClassVar['SmsMessage.MessageClass'] = ...
        CLASS_0: typing.ClassVar['SmsMessage.MessageClass'] = ...
        CLASS_1: typing.ClassVar['SmsMessage.MessageClass'] = ...
        CLASS_2: typing.ClassVar['SmsMessage.MessageClass'] = ...
        CLASS_3: typing.ClassVar['SmsMessage.MessageClass'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'SmsMessage.MessageClass': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['SmsMessage.MessageClass']: ...
    class SubmitPdu:
        encodedMessage: typing.MutableSequence[int] = ...
        encodedScAddress: typing.MutableSequence[int] = ...
        def __init__(self): ...
        def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.telephony.gsm")``.

    GsmCellLocation: typing.Type[GsmCellLocation]
    SmsManager: typing.Type[SmsManager]
    SmsMessage: typing.Type[SmsMessage]
