
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.net
import android.os
import java.net
import java.util
import java.util.concurrent
import typing



class DiscoveryRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getNetwork(self) -> android.net.Network: ...
    def getServiceType(self) -> str: ...
    def getSubtype(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str): ...
        def build(self) -> 'DiscoveryRequest': ...
        def setNetwork(self, network: android.net.Network) -> 'DiscoveryRequest.Builder': ...
        def setSubtype(self, string: str) -> 'DiscoveryRequest.Builder': ...

class NsdManager:
    ACTION_NSD_STATE_CHANGED: typing.ClassVar[str] = ...
    EXTRA_NSD_STATE: typing.ClassVar[str] = ...
    FAILURE_ALREADY_ACTIVE: typing.ClassVar[int] = ...
    FAILURE_BAD_PARAMETERS: typing.ClassVar[int] = ...
    FAILURE_INTERNAL_ERROR: typing.ClassVar[int] = ...
    FAILURE_MAX_LIMIT: typing.ClassVar[int] = ...
    FAILURE_OPERATION_NOT_RUNNING: typing.ClassVar[int] = ...
    NSD_STATE_DISABLED: typing.ClassVar[int] = ...
    NSD_STATE_ENABLED: typing.ClassVar[int] = ...
    PROTOCOL_DNS_SD: typing.ClassVar[int] = ...
    @typing.overload
    def discoverServices(self, discoveryRequest: DiscoveryRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], discoveryListener: 'NsdManager.DiscoveryListener') -> None: ...
    @typing.overload
    def discoverServices(self, string: str, int: int, network: android.net.Network, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], discoveryListener: 'NsdManager.DiscoveryListener') -> None: ...
    @typing.overload
    def discoverServices(self, string: str, int: int, networkRequest: android.net.NetworkRequest, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], discoveryListener: 'NsdManager.DiscoveryListener') -> None: ...
    @typing.overload
    def discoverServices(self, string: str, int: int, discoveryListener: 'NsdManager.DiscoveryListener') -> None: ...
    @typing.overload
    def registerService(self, nsdServiceInfo: 'NsdServiceInfo', int: int, registrationListener: 'NsdManager.RegistrationListener') -> None: ...
    @typing.overload
    def registerService(self, nsdServiceInfo: 'NsdServiceInfo', int: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], registrationListener: 'NsdManager.RegistrationListener') -> None: ...
    def registerServiceInfoCallback(self, nsdServiceInfo: 'NsdServiceInfo', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], serviceInfoCallback: 'NsdManager.ServiceInfoCallback') -> None: ...
    @typing.overload
    def resolveService(self, nsdServiceInfo: 'NsdServiceInfo', resolveListener: 'NsdManager.ResolveListener') -> None: ...
    @typing.overload
    def resolveService(self, nsdServiceInfo: 'NsdServiceInfo', executor: typing.Union[java.util.concurrent.Executor, typing.Callable], resolveListener: 'NsdManager.ResolveListener') -> None: ...
    def stopServiceDiscovery(self, discoveryListener: 'NsdManager.DiscoveryListener') -> None: ...
    def stopServiceResolution(self, resolveListener: 'NsdManager.ResolveListener') -> None: ...
    def unregisterService(self, registrationListener: 'NsdManager.RegistrationListener') -> None: ...
    def unregisterServiceInfoCallback(self, serviceInfoCallback: 'NsdManager.ServiceInfoCallback') -> None: ...
    class DiscoveryListener:
        def onDiscoveryStarted(self, string: str) -> None: ...
        def onDiscoveryStopped(self, string: str) -> None: ...
        def onServiceFound(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...
        def onServiceLost(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...
        def onStartDiscoveryFailed(self, string: str, int: int) -> None: ...
        def onStopDiscoveryFailed(self, string: str, int: int) -> None: ...
    class RegistrationListener:
        def onRegistrationFailed(self, nsdServiceInfo: 'NsdServiceInfo', int: int) -> None: ...
        def onServiceRegistered(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...
        def onServiceUnregistered(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...
        def onUnregistrationFailed(self, nsdServiceInfo: 'NsdServiceInfo', int: int) -> None: ...
    class ResolveListener:
        def onResolutionStopped(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...
        def onResolveFailed(self, nsdServiceInfo: 'NsdServiceInfo', int: int) -> None: ...
        def onServiceResolved(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...
        def onStopResolutionFailed(self, nsdServiceInfo: 'NsdServiceInfo', int: int) -> None: ...
    class ServiceInfoCallback:
        def onServiceInfoCallbackRegistrationFailed(self, int: int) -> None: ...
        def onServiceInfoCallbackUnregistered(self) -> None: ...
        def onServiceLost(self) -> None: ...
        def onServiceUpdated(self, nsdServiceInfo: 'NsdServiceInfo') -> None: ...

class NsdServiceInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self): ...
    def describeContents(self) -> int: ...
    def getAttributes(self) -> java.util.Map[str, typing.MutableSequence[int]]: ...
    def getHost(self) -> java.net.InetAddress: ...
    def getHostAddresses(self) -> java.util.List[java.net.InetAddress]: ...
    def getNetwork(self) -> android.net.Network: ...
    def getPort(self) -> int: ...
    def getServiceName(self) -> str: ...
    def getServiceType(self) -> str: ...
    def getSubtypes(self) -> java.util.Set[str]: ...
    def removeAttribute(self, string: str) -> None: ...
    def setAttribute(self, string: str, string2: str) -> None: ...
    def setHost(self, inetAddress: java.net.InetAddress) -> None: ...
    def setHostAddresses(self, list: java.util.List[java.net.InetAddress]) -> None: ...
    def setNetwork(self, network: android.net.Network) -> None: ...
    def setPort(self, int: int) -> None: ...
    def setServiceName(self, string: str) -> None: ...
    def setServiceType(self, string: str) -> None: ...
    def setSubtypes(self, set: java.util.Set[str]) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.nsd")``.

    DiscoveryRequest: typing.Type[DiscoveryRequest]
    NsdManager: typing.Type[NsdManager]
    NsdServiceInfo: typing.Type[NsdServiceInfo]
