
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.net
import android.net.wifi.aware
import android.net.wifi.hotspot2
import android.net.wifi.p2p
import android.net.wifi.rtt
import android.os
import java.lang
import java.net
import java.nio
import java.security
import java.security.cert
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class EasyConnectStatusCallback:
    EASY_CONNECT_EVENT_FAILURE_AUTHENTICATION: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_BUSY: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_CANNOT_FIND_NETWORK: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_CONFIGURATION: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_ENROLLEE_AUTHENTICATION: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_ENROLLEE_FAILED_TO_SCAN_NETWORK_CHANNEL: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_ENROLLEE_REJECTED_CONFIGURATION: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_GENERIC: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_INVALID_NETWORK: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_INVALID_URI: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_NOT_COMPATIBLE: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_NOT_SUPPORTED: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_TIMEOUT: typing.ClassVar[int] = ...
    EASY_CONNECT_EVENT_FAILURE_URI_GENERATION: typing.ClassVar[int] = ...

class MloLink(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    INVALID_MLO_LINK_ID: typing.ClassVar[int] = ...
    MLO_LINK_STATE_ACTIVE: typing.ClassVar[int] = ...
    MLO_LINK_STATE_IDLE: typing.ClassVar[int] = ...
    MLO_LINK_STATE_INVALID: typing.ClassVar[int] = ...
    MLO_LINK_STATE_UNASSOCIATED: typing.ClassVar[int] = ...
    def __init__(self): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getApMacAddress(self) -> android.net.MacAddress: ...
    def getBand(self) -> int: ...
    def getChannel(self) -> int: ...
    def getLinkId(self) -> int: ...
    def getRssi(self) -> int: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getStaMacAddress(self) -> android.net.MacAddress: ...
    def getState(self) -> int: ...
    def getTxLinkSpeedMbps(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ScanResult(android.os.Parcelable):
    BSSID: str = ...
    CHANNEL_WIDTH_160MHZ: typing.ClassVar[int] = ...
    CHANNEL_WIDTH_20MHZ: typing.ClassVar[int] = ...
    CHANNEL_WIDTH_320MHZ: typing.ClassVar[int] = ...
    CHANNEL_WIDTH_40MHZ: typing.ClassVar[int] = ...
    CHANNEL_WIDTH_80MHZ: typing.ClassVar[int] = ...
    CHANNEL_WIDTH_80MHZ_PLUS_MHZ: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PREAMBLE_EHT: typing.ClassVar[int] = ...
    PREAMBLE_HE: typing.ClassVar[int] = ...
    PREAMBLE_HT: typing.ClassVar[int] = ...
    PREAMBLE_LEGACY: typing.ClassVar[int] = ...
    PREAMBLE_VHT: typing.ClassVar[int] = ...
    SSID: str = ...
    UNSPECIFIED: typing.ClassVar[int] = ...
    WIFI_BAND_24_GHZ: typing.ClassVar[int] = ...
    WIFI_BAND_5_GHZ: typing.ClassVar[int] = ...
    WIFI_BAND_60_GHZ: typing.ClassVar[int] = ...
    WIFI_BAND_6_GHZ: typing.ClassVar[int] = ...
    WIFI_STANDARD_11AC: typing.ClassVar[int] = ...
    WIFI_STANDARD_11AD: typing.ClassVar[int] = ...
    WIFI_STANDARD_11AX: typing.ClassVar[int] = ...
    WIFI_STANDARD_11BE: typing.ClassVar[int] = ...
    WIFI_STANDARD_11N: typing.ClassVar[int] = ...
    WIFI_STANDARD_LEGACY: typing.ClassVar[int] = ...
    WIFI_STANDARD_UNKNOWN: typing.ClassVar[int] = ...
    capabilities: str = ...
    centerFreq0: int = ...
    centerFreq1: int = ...
    channelWidth: int = ...
    frequency: int = ...
    level: int = ...
    operatorFriendlyName: java.lang.CharSequence = ...
    timestamp: int = ...
    venueName: java.lang.CharSequence = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, scanResult: 'ScanResult'): ...
    @staticmethod
    def convertChannelToFrequencyMhzIfSupported(int: int, int2: int) -> int: ...
    @staticmethod
    def convertFrequencyMhzToChannelIfSupported(int: int) -> int: ...
    def describeContents(self) -> int: ...
    def getAffiliatedMloLinks(self) -> java.util.List[MloLink]: ...
    def getApMldMacAddress(self) -> android.net.MacAddress: ...
    def getApMloLinkId(self) -> int: ...
    def getInformationElements(self) -> java.util.List['ScanResult.InformationElement']: ...
    def getSecurityTypes(self) -> typing.MutableSequence[int]: ...
    def getWifiSsid(self) -> 'WifiSsid': ...
    def getWifiStandard(self) -> int: ...
    def is80211azNtbResponder(self) -> bool: ...
    def is80211mcResponder(self) -> bool: ...
    def isPasspointNetwork(self) -> bool: ...
    def isTwtResponder(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class InformationElement(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        @typing.overload
        def __init__(self, informationElement: 'ScanResult.InformationElement'): ...
        @typing.overload
        def __init__(self, int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getBytes(self) -> java.nio.ByteBuffer: ...
        def getId(self) -> int: ...
        def getIdExt(self) -> int: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SoftApConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SECURITY_TYPE_OPEN: typing.ClassVar[int] = ...
    SECURITY_TYPE_WPA2_PSK: typing.ClassVar[int] = ...
    SECURITY_TYPE_WPA3_OWE: typing.ClassVar[int] = ...
    SECURITY_TYPE_WPA3_OWE_TRANSITION: typing.ClassVar[int] = ...
    SECURITY_TYPE_WPA3_SAE: typing.ClassVar[int] = ...
    SECURITY_TYPE_WPA3_SAE_TRANSITION: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBssid(self) -> android.net.MacAddress: ...
    def getPassphrase(self) -> str: ...
    def getSecurityType(self) -> int: ...
    def getSsid(self) -> str: ...
    def getWifiSsid(self) -> 'WifiSsid': ...
    def hashCode(self) -> int: ...
    def isHiddenSsid(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SupplicantState(java.lang.Enum['SupplicantState'], android.os.Parcelable):
    DISCONNECTED: typing.ClassVar['SupplicantState'] = ...
    INTERFACE_DISABLED: typing.ClassVar['SupplicantState'] = ...
    INACTIVE: typing.ClassVar['SupplicantState'] = ...
    SCANNING: typing.ClassVar['SupplicantState'] = ...
    AUTHENTICATING: typing.ClassVar['SupplicantState'] = ...
    ASSOCIATING: typing.ClassVar['SupplicantState'] = ...
    ASSOCIATED: typing.ClassVar['SupplicantState'] = ...
    FOUR_WAY_HANDSHAKE: typing.ClassVar['SupplicantState'] = ...
    GROUP_HANDSHAKE: typing.ClassVar['SupplicantState'] = ...
    COMPLETED: typing.ClassVar['SupplicantState'] = ...
    DORMANT: typing.ClassVar['SupplicantState'] = ...
    UNINITIALIZED: typing.ClassVar['SupplicantState'] = ...
    INVALID: typing.ClassVar['SupplicantState'] = ...
    def describeContents(self) -> int: ...
    @staticmethod
    def isValidState(supplicantState: 'SupplicantState') -> bool: ...
    _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'SupplicantState': ...
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
    @staticmethod
    def values() -> typing.MutableSequence['SupplicantState']: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiAvailableChannel(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    OP_MODE_SAP: typing.ClassVar[int] = ...
    OP_MODE_STA: typing.ClassVar[int] = ...
    OP_MODE_TDLS: typing.ClassVar[int] = ...
    OP_MODE_WIFI_AWARE: typing.ClassVar[int] = ...
    OP_MODE_WIFI_DIRECT_CLI: typing.ClassVar[int] = ...
    OP_MODE_WIFI_DIRECT_GO: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getFrequencyMhz(self) -> int: ...
    def getOperationalModes(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiConfiguration(android.os.Parcelable):
    BSSID: str = ...
    FQDN: str = ...
    RANDOMIZATION_AUTO: typing.ClassVar[int] = ...
    RANDOMIZATION_NONE: typing.ClassVar[int] = ...
    RANDOMIZATION_NON_PERSISTENT: typing.ClassVar[int] = ...
    RANDOMIZATION_PERSISTENT: typing.ClassVar[int] = ...
    SECURITY_TYPE_DPP: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP_SUITE_B: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE_192_BIT: typing.ClassVar[int] = ...
    SECURITY_TYPE_OPEN: typing.ClassVar[int] = ...
    SECURITY_TYPE_OWE: typing.ClassVar[int] = ...
    SECURITY_TYPE_PSK: typing.ClassVar[int] = ...
    SECURITY_TYPE_SAE: typing.ClassVar[int] = ...
    SECURITY_TYPE_WAPI_CERT: typing.ClassVar[int] = ...
    SECURITY_TYPE_WAPI_PSK: typing.ClassVar[int] = ...
    SECURITY_TYPE_WEP: typing.ClassVar[int] = ...
    SSID: str = ...
    allowedAuthAlgorithms: java.util.BitSet = ...
    allowedGroupCiphers: java.util.BitSet = ...
    allowedGroupManagementCiphers: java.util.BitSet = ...
    allowedKeyManagement: java.util.BitSet = ...
    allowedPairwiseCiphers: java.util.BitSet = ...
    allowedProtocols: java.util.BitSet = ...
    allowedSuiteBCiphers: java.util.BitSet = ...
    enterpriseConfig: 'WifiEnterpriseConfig' = ...
    hiddenSSID: bool = ...
    isHomeProviderNetwork: bool = ...
    networkId: int = ...
    preSharedKey: str = ...
    priority: int = ...
    providerFriendlyName: str = ...
    roamingConsortiumIds: typing.MutableSequence[int] = ...
    status: int = ...
    wepKeys: typing.MutableSequence[str] = ...
    wepTxKeyIndex: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiConfiguration: 'WifiConfiguration'): ...
    def describeContents(self) -> int: ...
    def getHttpProxy(self) -> android.net.ProxyInfo: ...
    def getKey(self) -> str: ...
    def getMacRandomizationSetting(self) -> int: ...
    def getRandomizedMacAddress(self) -> android.net.MacAddress: ...
    def isDppConfigurator(self) -> bool: ...
    def isPasspoint(self) -> bool: ...
    def setHttpProxy(self, proxyInfo: android.net.ProxyInfo) -> None: ...
    def setIpConfiguration(self, ipConfiguration: android.net.IpConfiguration) -> None: ...
    def setMacRandomizationSetting(self, int: int) -> None: ...
    def setSecurityParams(self, int: int) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class AuthAlgorithm:
        LEAP: typing.ClassVar[int] = ...
        OPEN: typing.ClassVar[int] = ...
        SAE: typing.ClassVar[int] = ...
        SHARED: typing.ClassVar[int] = ...
        strings: typing.ClassVar[typing.MutableSequence[str]] = ...
        varName: typing.ClassVar[str] = ...
    class GroupCipher:
        CCMP: typing.ClassVar[int] = ...
        GCMP_128: typing.ClassVar[int] = ...
        GCMP_256: typing.ClassVar[int] = ...
        SMS4: typing.ClassVar[int] = ...
        TKIP: typing.ClassVar[int] = ...
        WEP104: typing.ClassVar[int] = ...
        WEP40: typing.ClassVar[int] = ...
        strings: typing.ClassVar[typing.MutableSequence[str]] = ...
        varName: typing.ClassVar[str] = ...
    class GroupMgmtCipher:
        BIP_CMAC_256: typing.ClassVar[int] = ...
        BIP_GMAC_128: typing.ClassVar[int] = ...
        BIP_GMAC_256: typing.ClassVar[int] = ...
    class KeyMgmt:
        DPP: typing.ClassVar[int] = ...
        FILS_SHA256: typing.ClassVar[int] = ...
        FILS_SHA384: typing.ClassVar[int] = ...
        FT_EAP: typing.ClassVar[int] = ...
        FT_PSK: typing.ClassVar[int] = ...
        IEEE8021X: typing.ClassVar[int] = ...
        NONE: typing.ClassVar[int] = ...
        OSEN: typing.ClassVar[int] = ...
        OWE: typing.ClassVar[int] = ...
        SAE: typing.ClassVar[int] = ...
        SUITE_B_192: typing.ClassVar[int] = ...
        WAPI_CERT: typing.ClassVar[int] = ...
        WAPI_PSK: typing.ClassVar[int] = ...
        WPA2_PSK: typing.ClassVar[int] = ...
        WPA_EAP: typing.ClassVar[int] = ...
        WPA_EAP_SHA256: typing.ClassVar[int] = ...
        WPA_PSK: typing.ClassVar[int] = ...
        WPA_PSK_SHA256: typing.ClassVar[int] = ...
        strings: typing.ClassVar[typing.MutableSequence[str]] = ...
        varName: typing.ClassVar[str] = ...
    class PairwiseCipher:
        CCMP: typing.ClassVar[int] = ...
        GCMP_128: typing.ClassVar[int] = ...
        GCMP_256: typing.ClassVar[int] = ...
        NONE: typing.ClassVar[int] = ...
        SMS4: typing.ClassVar[int] = ...
        TKIP: typing.ClassVar[int] = ...
        strings: typing.ClassVar[typing.MutableSequence[str]] = ...
        varName: typing.ClassVar[str] = ...
    class Protocol:
        RSN: typing.ClassVar[int] = ...
        WAPI: typing.ClassVar[int] = ...
        WPA: typing.ClassVar[int] = ...
        strings: typing.ClassVar[typing.MutableSequence[str]] = ...
        varName: typing.ClassVar[str] = ...
    class Status:
        CURRENT: typing.ClassVar[int] = ...
        DISABLED: typing.ClassVar[int] = ...
        ENABLED: typing.ClassVar[int] = ...
        strings: typing.ClassVar[typing.MutableSequence[str]] = ...

class WifiEnterpriseConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EXTRA_WAPI_AS_CERTIFICATE_DATA: typing.ClassVar[str] = ...
    EXTRA_WAPI_AS_CERTIFICATE_NAME: typing.ClassVar[str] = ...
    EXTRA_WAPI_USER_CERTIFICATE_DATA: typing.ClassVar[str] = ...
    EXTRA_WAPI_USER_CERTIFICATE_NAME: typing.ClassVar[str] = ...
    TLS_V1_0: typing.ClassVar[int] = ...
    TLS_V1_1: typing.ClassVar[int] = ...
    TLS_V1_2: typing.ClassVar[int] = ...
    TLS_V1_3: typing.ClassVar[int] = ...
    WAPI_AS_CERTIFICATE: typing.ClassVar[str] = ...
    WAPI_USER_CERTIFICATE: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wifiEnterpriseConfig: 'WifiEnterpriseConfig'): ...
    def describeContents(self) -> int: ...
    def enableTrustOnFirstUse(self, boolean: bool) -> None: ...
    def getAltSubjectMatch(self) -> str: ...
    def getAnonymousIdentity(self) -> str: ...
    def getCaCertificate(self) -> java.security.cert.X509Certificate: ...
    def getCaCertificates(self) -> typing.MutableSequence[java.security.cert.X509Certificate]: ...
    def getClientCertificate(self) -> java.security.cert.X509Certificate: ...
    def getClientCertificateChain(self) -> typing.MutableSequence[java.security.cert.X509Certificate]: ...
    def getClientKeyPairAlias(self) -> str: ...
    def getClientPrivateKey(self) -> java.security.PrivateKey: ...
    def getDecoratedIdentityPrefix(self) -> str: ...
    def getDomainSuffixMatch(self) -> str: ...
    def getEapMethod(self) -> int: ...
    def getIdentity(self) -> str: ...
    def getMinimumTlsVersion(self) -> int: ...
    def getPassword(self) -> str: ...
    def getPhase2Method(self) -> int: ...
    def getPlmn(self) -> str: ...
    def getRealm(self) -> str: ...
    def getSubjectMatch(self) -> str: ...
    def hasCaCertificate(self) -> bool: ...
    def isAuthenticationSimBased(self) -> bool: ...
    def isEapMethodServerCertUsed(self) -> bool: ...
    def isServerCertValidationEnabled(self) -> bool: ...
    def isTrustOnFirstUseEnabled(self) -> bool: ...
    def setAltSubjectMatch(self, string: str) -> None: ...
    def setAnonymousIdentity(self, string: str) -> None: ...
    def setCaCertificate(self, x509Certificate: java.security.cert.X509Certificate) -> None: ...
    def setCaCertificates(self, x509CertificateArray: typing.Union[typing.List[java.security.cert.X509Certificate], jpype.JArray]) -> None: ...
    def setClientKeyEntry(self, privateKey: java.security.PrivateKey, x509Certificate: java.security.cert.X509Certificate) -> None: ...
    def setClientKeyEntryWithCertificateChain(self, privateKey: java.security.PrivateKey, x509CertificateArray: typing.Union[typing.List[java.security.cert.X509Certificate], jpype.JArray]) -> None: ...
    def setClientKeyPairAlias(self, string: str) -> None: ...
    def setDecoratedIdentityPrefix(self, string: str) -> None: ...
    def setDomainSuffixMatch(self, string: str) -> None: ...
    def setEapMethod(self, int: int) -> None: ...
    def setIdentity(self, string: str) -> None: ...
    def setMinimumTlsVersion(self, int: int) -> None: ...
    def setPassword(self, string: str) -> None: ...
    def setPhase2Method(self, int: int) -> None: ...
    def setPlmn(self, string: str) -> None: ...
    def setRealm(self, string: str) -> None: ...
    def setSubjectMatch(self, string: str) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Eap:
        AKA: typing.ClassVar[int] = ...
        AKA_PRIME: typing.ClassVar[int] = ...
        NONE: typing.ClassVar[int] = ...
        PEAP: typing.ClassVar[int] = ...
        PWD: typing.ClassVar[int] = ...
        SIM: typing.ClassVar[int] = ...
        TLS: typing.ClassVar[int] = ...
        TTLS: typing.ClassVar[int] = ...
        UNAUTH_TLS: typing.ClassVar[int] = ...
        WAPI_CERT: typing.ClassVar[int] = ...
    class Phase2:
        AKA: typing.ClassVar[int] = ...
        AKA_PRIME: typing.ClassVar[int] = ...
        GTC: typing.ClassVar[int] = ...
        MSCHAP: typing.ClassVar[int] = ...
        MSCHAPV2: typing.ClassVar[int] = ...
        NONE: typing.ClassVar[int] = ...
        PAP: typing.ClassVar[int] = ...
        SIM: typing.ClassVar[int] = ...

class WifiInfo(android.net.TransportInfo, android.os.Parcelable):
    FREQUENCY_UNITS: typing.ClassVar[str] = ...
    LINK_SPEED_UNITS: typing.ClassVar[str] = ...
    LINK_SPEED_UNKNOWN: typing.ClassVar[int] = ...
    SECURITY_TYPE_DPP: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE: typing.ClassVar[int] = ...
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE_192_BIT: typing.ClassVar[int] = ...
    SECURITY_TYPE_OPEN: typing.ClassVar[int] = ...
    SECURITY_TYPE_OSEN: typing.ClassVar[int] = ...
    SECURITY_TYPE_OWE: typing.ClassVar[int] = ...
    SECURITY_TYPE_PASSPOINT_R1_R2: typing.ClassVar[int] = ...
    SECURITY_TYPE_PASSPOINT_R3: typing.ClassVar[int] = ...
    SECURITY_TYPE_PSK: typing.ClassVar[int] = ...
    SECURITY_TYPE_SAE: typing.ClassVar[int] = ...
    SECURITY_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    SECURITY_TYPE_WAPI_CERT: typing.ClassVar[int] = ...
    SECURITY_TYPE_WAPI_PSK: typing.ClassVar[int] = ...
    SECURITY_TYPE_WEP: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAffiliatedMloLinks(self) -> java.util.List[MloLink]: ...
    def getApMldMacAddress(self) -> android.net.MacAddress: ...
    def getApMloLinkId(self) -> int: ...
    def getApplicableRedactions(self) -> int: ...
    def getAssociatedMloLinks(self) -> java.util.List[MloLink]: ...
    def getBSSID(self) -> str: ...
    def getCurrentSecurityType(self) -> int: ...
    @staticmethod
    def getDetailedStateOf(supplicantState: SupplicantState) -> android.net.NetworkInfo.DetailedState: ...
    def getFrequency(self) -> int: ...
    def getHiddenSSID(self) -> bool: ...
    def getInformationElements(self) -> java.util.List[ScanResult.InformationElement]: ...
    def getIpAddress(self) -> int: ...
    def getLinkSpeed(self) -> int: ...
    def getMacAddress(self) -> str: ...
    def getMaxSupportedRxLinkSpeedMbps(self) -> int: ...
    def getMaxSupportedTxLinkSpeedMbps(self) -> int: ...
    def getNetworkId(self) -> int: ...
    def getPasspointFqdn(self) -> str: ...
    def getPasspointProviderFriendlyName(self) -> str: ...
    def getPasspointUniqueId(self) -> str: ...
    def getRssi(self) -> int: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getSSID(self) -> str: ...
    def getSubscriptionId(self) -> int: ...
    def getSupplicantState(self) -> SupplicantState: ...
    def getTxLinkSpeedMbps(self) -> int: ...
    def getWifiStandard(self) -> int: ...
    def hashCode(self) -> int: ...
    def isRestricted(self) -> bool: ...
    def makeCopy(self, long: int) -> 'WifiInfo': ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'WifiInfo': ...
        def setBssid(self, string: str) -> 'WifiInfo.Builder': ...
        def setCurrentSecurityType(self, int: int) -> 'WifiInfo.Builder': ...
        def setNetworkId(self, int: int) -> 'WifiInfo.Builder': ...
        def setRssi(self, int: int) -> 'WifiInfo.Builder': ...
        def setSsid(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'WifiInfo.Builder': ...
        def setSubscriptionId(self, int: int) -> 'WifiInfo.Builder': ...

class WifiManager:
    ACTION_PICK_WIFI_NETWORK: typing.ClassVar[str] = ...
    ACTION_REMOVE_SUGGESTION_DISCONNECT: typing.ClassVar[int] = ...
    ACTION_REMOVE_SUGGESTION_LINGER: typing.ClassVar[int] = ...
    ACTION_REQUEST_SCAN_ALWAYS_AVAILABLE: typing.ClassVar[str] = ...
    ACTION_WIFI_NETWORK_SUGGESTION_POST_CONNECTION: typing.ClassVar[str] = ...
    ACTION_WIFI_SCAN_AVAILABILITY_CHANGED: typing.ClassVar[str] = ...
    CHANNEL_DATA_KEY_FREQUENCY_MHZ: typing.ClassVar[str] = ...
    CHANNEL_DATA_KEY_NUM_AP: typing.ClassVar[str] = ...
    ERROR_AUTHENTICATING: typing.ClassVar[int] = ...
    EXTRA_BSSID: typing.ClassVar[str] = ...
    EXTRA_NETWORK_INFO: typing.ClassVar[str] = ...
    EXTRA_NETWORK_SUGGESTION: typing.ClassVar[str] = ...
    EXTRA_NEW_RSSI: typing.ClassVar[str] = ...
    EXTRA_NEW_STATE: typing.ClassVar[str] = ...
    EXTRA_PREVIOUS_WIFI_STATE: typing.ClassVar[str] = ...
    EXTRA_RESULTS_UPDATED: typing.ClassVar[str] = ...
    EXTRA_SCAN_AVAILABLE: typing.ClassVar[str] = ...
    EXTRA_SUPPLICANT_CONNECTED: typing.ClassVar[str] = ...
    EXTRA_SUPPLICANT_ERROR: typing.ClassVar[str] = ...
    EXTRA_WIFI_INFO: typing.ClassVar[str] = ...
    EXTRA_WIFI_STATE: typing.ClassVar[str] = ...
    FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_OPEN: typing.ClassVar[int] = ...
    FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_SECURE: typing.ClassVar[int] = ...
    NETWORK_IDS_CHANGED_ACTION: typing.ClassVar[str] = ...
    NETWORK_STATE_CHANGED_ACTION: typing.ClassVar[str] = ...
    ROAMING_MODE_AGGRESSIVE: typing.ClassVar[int] = ...
    ROAMING_MODE_NONE: typing.ClassVar[int] = ...
    ROAMING_MODE_NORMAL: typing.ClassVar[int] = ...
    RSSI_CHANGED_ACTION: typing.ClassVar[str] = ...
    SCAN_RESULTS_AVAILABLE_ACTION: typing.ClassVar[str] = ...
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_ASSOCIATION: typing.ClassVar[int] = ...
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_AUTHENTICATION: typing.ClassVar[int] = ...
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_IP_PROVISIONING: typing.ClassVar[int] = ...
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NOT_FOUND: typing.ClassVar[int] = ...
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NO_RESPONSE: typing.ClassVar[int] = ...
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_UNKNOWN: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_DUPLICATE: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_EXCEEDS_MAX_PER_APP: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_INVALID: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_NOT_ALLOWED: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_APP_DISALLOWED: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_INTERNAL: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_REMOVE_INVALID: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN: typing.ClassVar[int] = ...
    STATUS_NETWORK_SUGGESTIONS_SUCCESS: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_APPROVAL_APPROVED_BY_CARRIER_PRIVILEGE: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_APPROVAL_APPROVED_BY_USER: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_APPROVAL_PENDING: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_APPROVAL_REJECTED_BY_USER: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_APPROVAL_UNKNOWN: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_CONNECTION_FAILURE_ASSOCIATION: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_CONNECTION_FAILURE_AUTHENTICATION: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_CONNECTION_FAILURE_IP_PROVISIONING: typing.ClassVar[int] = ...
    STATUS_SUGGESTION_CONNECTION_FAILURE_UNKNOWN: typing.ClassVar[int] = ...
    SUPPLICANT_CONNECTION_CHANGE_ACTION: typing.ClassVar[str] = ...
    SUPPLICANT_STATE_CHANGED_ACTION: typing.ClassVar[str] = ...
    UNKNOWN_SSID: typing.ClassVar[str] = ...
    WIFI_INTERFACE_TYPE_AP: typing.ClassVar[int] = ...
    WIFI_INTERFACE_TYPE_AWARE: typing.ClassVar[int] = ...
    WIFI_INTERFACE_TYPE_DIRECT: typing.ClassVar[int] = ...
    WIFI_INTERFACE_TYPE_STA: typing.ClassVar[int] = ...
    WIFI_MODE_FULL: typing.ClassVar[int] = ...
    WIFI_MODE_FULL_HIGH_PERF: typing.ClassVar[int] = ...
    WIFI_MODE_FULL_LOW_LATENCY: typing.ClassVar[int] = ...
    WIFI_MODE_SCAN_ONLY: typing.ClassVar[int] = ...
    WIFI_MULTI_INTERNET_MODE_DBS_AP: typing.ClassVar[int] = ...
    WIFI_MULTI_INTERNET_MODE_DISABLED: typing.ClassVar[int] = ...
    WIFI_MULTI_INTERNET_MODE_MULTI_AP: typing.ClassVar[int] = ...
    WIFI_STATE_CHANGED_ACTION: typing.ClassVar[str] = ...
    WIFI_STATE_DISABLED: typing.ClassVar[int] = ...
    WIFI_STATE_DISABLING: typing.ClassVar[int] = ...
    WIFI_STATE_ENABLED: typing.ClassVar[int] = ...
    WIFI_STATE_ENABLING: typing.ClassVar[int] = ...
    WIFI_STATE_UNKNOWN: typing.ClassVar[int] = ...
    WPS_AUTH_FAILURE: typing.ClassVar[int] = ...
    WPS_OVERLAP_ERROR: typing.ClassVar[int] = ...
    WPS_TIMED_OUT: typing.ClassVar[int] = ...
    WPS_TKIP_ONLY_PROHIBITED: typing.ClassVar[int] = ...
    WPS_WEP_PROHIBITED: typing.ClassVar[int] = ...
    def addLocalOnlyConnectionFailureListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], localOnlyConnectionFailureListener: typing.Union['WifiManager.LocalOnlyConnectionFailureListener', typing.Callable]) -> None: ...
    def addNetwork(self, wifiConfiguration: WifiConfiguration) -> int: ...
    def addNetworkPrivileged(self, wifiConfiguration: WifiConfiguration) -> 'WifiManager.AddNetworkResult': ...
    def addNetworkSuggestions(self, list: java.util.List['WifiNetworkSuggestion']) -> int: ...
    def addOrUpdatePasspointConfiguration(self, passpointConfiguration: android.net.wifi.hotspot2.PasspointConfiguration) -> None: ...
    def addSuggestionConnectionStatusListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], suggestionConnectionStatusListener: typing.Union['WifiManager.SuggestionConnectionStatusListener', typing.Callable]) -> None: ...
    def addSuggestionUserApprovalStatusListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], suggestionUserApprovalStatusListener: typing.Union['WifiManager.SuggestionUserApprovalStatusListener', typing.Callable]) -> None: ...
    def allowAutojoinGlobal(self, boolean: bool) -> None: ...
    @typing.overload
    def calculateSignalLevel(self, int: int) -> int: ...
    @typing.overload
    @staticmethod
    def calculateSignalLevel(int: int, int2: int) -> int: ...
    def cancelWps(self, wpsCallback: 'WifiManager.WpsCallback') -> None: ...
    @staticmethod
    def compareSignalLevel(int: int, int2: int) -> int: ...
    def createMulticastLock(self, string: str) -> 'WifiManager.MulticastLock': ...
    @typing.overload
    def createWifiLock(self, int: int, string: str) -> 'WifiManager.WifiLock': ...
    @typing.overload
    def createWifiLock(self, string: str) -> 'WifiManager.WifiLock': ...
    def disableNetwork(self, int: int) -> bool: ...
    def disconnect(self) -> bool: ...
    def enableNetwork(self, int: int, boolean: bool) -> bool: ...
    def flushPasspointAnqpCache(self) -> None: ...
    def getAllowedChannels(self, int: int, int2: int) -> java.util.List[WifiAvailableChannel]: ...
    def getCallerConfiguredNetworks(self) -> java.util.List[WifiConfiguration]: ...
    def getChannelData(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[java.util.List[android.os.Bundle]], typing.Callable[[java.util.List[android.os.Bundle]], None]]) -> None: ...
    def getConfiguredNetworks(self) -> java.util.List[WifiConfiguration]: ...
    def getConnectionInfo(self) -> WifiInfo: ...
    def getDhcpInfo(self) -> android.net.DhcpInfo: ...
    def getMaxNumberOfChannelsPerNetworkSpecifierRequest(self) -> int: ...
    def getMaxNumberOfNetworkSuggestionsPerApp(self) -> int: ...
    def getMaxSignalLevel(self) -> int: ...
    def getMaxSupportedConcurrentTdlsSessions(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[int], typing.Callable[[int], None]]) -> None: ...
    def getNetworkSuggestions(self) -> java.util.List['WifiNetworkSuggestion']: ...
    def getNumberOfEnabledTdlsSessions(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[int], typing.Callable[[int], None]]) -> None: ...
    def getPasspointConfigurations(self) -> java.util.List[android.net.wifi.hotspot2.PasspointConfiguration]: ...
    def getPerSsidRoamingModes(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[typing.Union[java.util.Map[str, int], typing.Mapping[str, int]]], typing.Callable[[typing.Union[java.util.Map[str, int], typing.Mapping[str, int]]], None]]) -> None: ...
    def getScanResults(self) -> java.util.List[ScanResult]: ...
    def getStaConcurrencyForMultiInternetMode(self) -> int: ...
    def getUsableChannels(self, int: int, int2: int) -> java.util.List[WifiAvailableChannel]: ...
    def getWifiState(self) -> int: ...
    def is24GHzBandSupported(self) -> bool: ...
    def is5GHzBandSupported(self) -> bool: ...
    def is60GHzBandSupported(self) -> bool: ...
    def is6GHzBandSupported(self) -> bool: ...
    def isAggressiveRoamingModeSupported(self) -> bool: ...
    def isAutoWakeupEnabled(self) -> bool: ...
    def isBridgedApConcurrencySupported(self) -> bool: ...
    def isCarrierNetworkOffloadEnabled(self, int: int, boolean: bool) -> bool: ...
    def isD2dSupportedWhenInfraStaDisabled(self) -> bool: ...
    def isDecoratedIdentitySupported(self) -> bool: ...
    def isDeviceToApRttSupported(self) -> bool: ...
    def isDualBandSimultaneousSupported(self) -> bool: ...
    def isEasyConnectDppAkmSupported(self) -> bool: ...
    def isEasyConnectEnrolleeResponderModeSupported(self) -> bool: ...
    def isEasyConnectSupported(self) -> bool: ...
    def isEnhancedOpenSupported(self) -> bool: ...
    def isEnhancedPowerReportingSupported(self) -> bool: ...
    def isMakeBeforeBreakWifiSwitchingSupported(self) -> bool: ...
    def isP2pSupported(self) -> bool: ...
    def isPasspointTermsAndConditionsSupported(self) -> bool: ...
    def isPreferredNetworkOffloadSupported(self) -> bool: ...
    def isScanAlwaysAvailable(self) -> bool: ...
    def isScanThrottleEnabled(self) -> bool: ...
    def isStaApConcurrencySupported(self) -> bool: ...
    def isStaBridgedApConcurrencySupported(self) -> bool: ...
    def isStaConcurrencyForLocalOnlyConnectionsSupported(self) -> bool: ...
    def isStaConcurrencyForMultiInternetSupported(self) -> bool: ...
    def isTdlsOperationCurrentlyAvailable(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def isTdlsSupported(self) -> bool: ...
    def isTidToLinkMappingNegotiationSupported(self) -> bool: ...
    def isTlsMinimumVersionSupported(self) -> bool: ...
    def isTlsV13Supported(self) -> bool: ...
    def isTrustOnFirstUseSupported(self) -> bool: ...
    def isWapiSupported(self) -> bool: ...
    def isWepSupported(self) -> bool: ...
    def isWifiDisplayR2Supported(self) -> bool: ...
    def isWifiEnabled(self) -> bool: ...
    def isWifiPasspointEnabled(self) -> bool: ...
    def isWifiStandardSupported(self, int: int) -> bool: ...
    def isWpa3SaeH2eSupported(self) -> bool: ...
    def isWpa3SaePublicKeySupported(self) -> bool: ...
    def isWpa3SaeSupported(self) -> bool: ...
    def isWpa3SuiteBSupported(self) -> bool: ...
    def isWpaPersonalSupported(self) -> bool: ...
    def pingSupplicant(self) -> bool: ...
    def queryAutojoinGlobal(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def querySendDhcpHostnameRestriction(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], intConsumer: typing.Union[java.util.function.IntConsumer, typing.Callable]) -> None: ...
    def reassociate(self) -> bool: ...
    def reconnect(self) -> bool: ...
    def registerScanResultsCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], scanResultsCallback: 'WifiManager.ScanResultsCallback') -> None: ...
    def registerSubsystemRestartTrackingCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], subsystemRestartTrackingCallback: 'WifiManager.SubsystemRestartTrackingCallback') -> None: ...
    def removeLocalOnlyConnectionFailureListener(self, localOnlyConnectionFailureListener: typing.Union['WifiManager.LocalOnlyConnectionFailureListener', typing.Callable]) -> None: ...
    def removeNetwork(self, int: int) -> bool: ...
    @typing.overload
    def removeNetworkSuggestions(self, list: java.util.List['WifiNetworkSuggestion']) -> int: ...
    @typing.overload
    def removeNetworkSuggestions(self, list: java.util.List['WifiNetworkSuggestion'], int: int) -> int: ...
    def removeNonCallerConfiguredNetworks(self) -> bool: ...
    def removePasspointConfiguration(self, string: str) -> None: ...
    def removePerSsidRoamingMode(self, wifiSsid: 'WifiSsid') -> None: ...
    def removeSuggestionConnectionStatusListener(self, suggestionConnectionStatusListener: typing.Union['WifiManager.SuggestionConnectionStatusListener', typing.Callable]) -> None: ...
    def removeSuggestionUserApprovalStatusListener(self, suggestionUserApprovalStatusListener: typing.Union['WifiManager.SuggestionUserApprovalStatusListener', typing.Callable]) -> None: ...
    def reportCreateInterfaceImpact(self, int: int, boolean: bool, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], biConsumer: typing.Union[java.util.function.BiConsumer[bool, java.util.Set['WifiManager.InterfaceCreationImpact']], typing.Callable[[bool, java.util.Set['WifiManager.InterfaceCreationImpact']], None]]) -> None: ...
    def saveConfiguration(self) -> bool: ...
    def setPerSsidRoamingMode(self, wifiSsid: 'WifiSsid', int: int) -> None: ...
    def setSendDhcpHostnameRestriction(self, int: int) -> None: ...
    @typing.overload
    def setTdlsEnabled(self, inetAddress: java.net.InetAddress, boolean: bool) -> None: ...
    @typing.overload
    def setTdlsEnabled(self, inetAddress: java.net.InetAddress, boolean: bool, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    @typing.overload
    def setTdlsEnabledWithMacAddress(self, string: str, boolean: bool) -> None: ...
    @typing.overload
    def setTdlsEnabledWithMacAddress(self, string: str, boolean: bool, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[bool], typing.Callable[[bool], None]]) -> None: ...
    def setWifiEnabled(self, boolean: bool) -> bool: ...
    def startLocalOnlyHotspot(self, localOnlyHotspotCallback: 'WifiManager.LocalOnlyHotspotCallback', handler: android.os.Handler) -> None: ...
    def startScan(self) -> bool: ...
    def startWps(self, wpsInfo: 'WpsInfo', wpsCallback: 'WifiManager.WpsCallback') -> None: ...
    def unregisterScanResultsCallback(self, scanResultsCallback: 'WifiManager.ScanResultsCallback') -> None: ...
    def unregisterSubsystemRestartTrackingCallback(self, subsystemRestartTrackingCallback: 'WifiManager.SubsystemRestartTrackingCallback') -> None: ...
    def updateNetwork(self, wifiConfiguration: WifiConfiguration) -> int: ...
    def validateSoftApConfiguration(self, softApConfiguration: SoftApConfiguration) -> bool: ...
    class AddNetworkResult(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        STATUS_ADD_PASSPOINT_FAILURE: typing.ClassVar[int] = ...
        STATUS_ADD_WIFI_CONFIG_FAILURE: typing.ClassVar[int] = ...
        STATUS_FAILURE_UNKNOWN: typing.ClassVar[int] = ...
        STATUS_FAILURE_UPDATE_NETWORK_KEYS: typing.ClassVar[int] = ...
        STATUS_INVALID_CONFIGURATION: typing.ClassVar[int] = ...
        STATUS_INVALID_CONFIGURATION_ENTERPRISE: typing.ClassVar[int] = ...
        STATUS_NO_PERMISSION: typing.ClassVar[int] = ...
        STATUS_NO_PERMISSION_MODIFY_CONFIG: typing.ClassVar[int] = ...
        STATUS_NO_PERMISSION_MODIFY_MAC_RANDOMIZATION: typing.ClassVar[int] = ...
        STATUS_NO_PERMISSION_MODIFY_PROXY_SETTING: typing.ClassVar[int] = ...
        STATUS_SUCCESS: typing.ClassVar[int] = ...
        networkId: int = ...
        statusCode: int = ...
        def __init__(self, int: int, int2: int): ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class InterfaceCreationImpact:
        def __init__(self, int: int, set: java.util.Set[str]): ...
        def equals(self, object: typing.Any) -> bool: ...
        def getInterfaceType(self) -> int: ...
        def getPackages(self) -> java.util.Set[str]: ...
        def hashCode(self) -> int: ...
    class LocalOnlyConnectionFailureListener:
        def onConnectionFailed(self, wifiNetworkSpecifier: 'WifiNetworkSpecifier', int: int) -> None: ...
    class LocalOnlyHotspotCallback:
        ERROR_GENERIC: typing.ClassVar[int] = ...
        ERROR_INCOMPATIBLE_MODE: typing.ClassVar[int] = ...
        ERROR_NO_CHANNEL: typing.ClassVar[int] = ...
        ERROR_TETHERING_DISALLOWED: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onFailed(self, int: int) -> None: ...
        def onStarted(self, localOnlyHotspotReservation: 'WifiManager.LocalOnlyHotspotReservation') -> None: ...
        def onStopped(self) -> None: ...
    class LocalOnlyHotspotReservation(java.lang.AutoCloseable):
        def close(self) -> None: ...
        def getSoftApConfiguration(self) -> SoftApConfiguration: ...
        def getWifiConfiguration(self) -> WifiConfiguration: ...
    class MulticastLock:
        def acquire(self) -> None: ...
        def isHeld(self) -> bool: ...
        def release(self) -> None: ...
        def setReferenceCounted(self, boolean: bool) -> None: ...
        def toString(self) -> str: ...
    class ScanResultsCallback:
        def __init__(self): ...
        def onScanResultsAvailable(self) -> None: ...
    class SubsystemRestartTrackingCallback:
        def __init__(self): ...
        def onSubsystemRestarted(self) -> None: ...
        def onSubsystemRestarting(self) -> None: ...
    class SuggestionConnectionStatusListener:
        def onConnectionStatus(self, wifiNetworkSuggestion: 'WifiNetworkSuggestion', int: int) -> None: ...
    class SuggestionUserApprovalStatusListener:
        def onUserApprovalStatusChange(self, int: int) -> None: ...
    class WifiLock:
        def acquire(self) -> None: ...
        def isHeld(self) -> bool: ...
        def release(self) -> None: ...
        def setReferenceCounted(self, boolean: bool) -> None: ...
        def setWorkSource(self, workSource: android.os.WorkSource) -> None: ...
        def toString(self) -> str: ...
    class WpsCallback:
        def __init__(self): ...
        def onFailed(self, int: int) -> None: ...
        def onStarted(self, string: str) -> None: ...
        def onSucceeded(self) -> None: ...

class WifiNetworkSpecifier(android.net.NetworkSpecifier, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def canBeSatisfiedBy(self, networkSpecifier: android.net.NetworkSpecifier) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBand(self) -> int: ...
    def getPreferredChannelFrequenciesMhz(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    def redact(self) -> android.net.NetworkSpecifier: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'WifiNetworkSpecifier': ...
        def setBand(self, int: int) -> 'WifiNetworkSpecifier.Builder': ...
        def setBssid(self, macAddress: android.net.MacAddress) -> 'WifiNetworkSpecifier.Builder': ...
        def setBssidPattern(self, macAddress: android.net.MacAddress, macAddress2: android.net.MacAddress) -> 'WifiNetworkSpecifier.Builder': ...
        def setIsEnhancedOpen(self, boolean: bool) -> 'WifiNetworkSpecifier.Builder': ...
        def setIsHiddenSsid(self, boolean: bool) -> 'WifiNetworkSpecifier.Builder': ...
        def setPreferredChannelsFrequenciesMhz(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'WifiNetworkSpecifier.Builder': ...
        def setSsid(self, string: str) -> 'WifiNetworkSpecifier.Builder': ...
        def setSsidPattern(self, patternMatcher: android.os.PatternMatcher) -> 'WifiNetworkSpecifier.Builder': ...
        def setWpa2EnterpriseConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSpecifier.Builder': ...
        def setWpa2Passphrase(self, string: str) -> 'WifiNetworkSpecifier.Builder': ...
        def setWpa3Enterprise192BitModeConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSpecifier.Builder': ...
        def setWpa3EnterpriseConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSpecifier.Builder': ...
        def setWpa3EnterpriseStandardModeConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSpecifier.Builder': ...
        def setWpa3Passphrase(self, string: str) -> 'WifiNetworkSpecifier.Builder': ...

class WifiNetworkSuggestion(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RANDOMIZATION_NON_PERSISTENT: typing.ClassVar[int] = ...
    RANDOMIZATION_PERSISTENT: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getBssid(self) -> android.net.MacAddress: ...
    def getEnterpriseConfig(self) -> WifiEnterpriseConfig: ...
    def getMacRandomizationSetting(self) -> int: ...
    def getPassphrase(self) -> str: ...
    def getPasspointConfig(self) -> android.net.wifi.hotspot2.PasspointConfiguration: ...
    def getPriority(self) -> int: ...
    def getPriorityGroup(self) -> int: ...
    def getSsid(self) -> str: ...
    def getSubscriptionGroup(self) -> android.os.ParcelUuid: ...
    def getSubscriptionId(self) -> int: ...
    def getWifiSsid(self) -> 'WifiSsid': ...
    def hashCode(self) -> int: ...
    def isAppInteractionRequired(self) -> bool: ...
    def isCarrierMerged(self) -> bool: ...
    def isCredentialSharedWithUser(self) -> bool: ...
    def isEnhancedOpen(self) -> bool: ...
    def isHiddenSsid(self) -> bool: ...
    def isInitialAutojoinEnabled(self) -> bool: ...
    def isMetered(self) -> bool: ...
    def isRestricted(self) -> bool: ...
    def isUntrusted(self) -> bool: ...
    def isUserInteractionRequired(self) -> bool: ...
    def isWifi7Enabled(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'WifiNetworkSuggestion': ...
        def setBssid(self, macAddress: android.net.MacAddress) -> 'WifiNetworkSuggestion.Builder': ...
        def setCarrierMerged(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setCredentialSharedWithUser(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsAppInteractionRequired(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsEnhancedOpen(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsHiddenSsid(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsInitialAutojoinEnabled(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsMetered(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsUserInteractionRequired(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setIsWpa3SaeH2eOnlyModeEnabled(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setMacRandomizationSetting(self, int: int) -> 'WifiNetworkSuggestion.Builder': ...
        def setPasspointConfig(self, passpointConfiguration: android.net.wifi.hotspot2.PasspointConfiguration) -> 'WifiNetworkSuggestion.Builder': ...
        def setPriority(self, int: int) -> 'WifiNetworkSuggestion.Builder': ...
        def setPriorityGroup(self, int: int) -> 'WifiNetworkSuggestion.Builder': ...
        def setRestricted(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setSsid(self, string: str) -> 'WifiNetworkSuggestion.Builder': ...
        def setSubscriptionGroup(self, parcelUuid: android.os.ParcelUuid) -> 'WifiNetworkSuggestion.Builder': ...
        def setSubscriptionId(self, int: int) -> 'WifiNetworkSuggestion.Builder': ...
        def setUntrusted(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setWapiEnterpriseConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSuggestion.Builder': ...
        def setWapiPassphrase(self, string: str) -> 'WifiNetworkSuggestion.Builder': ...
        def setWifi7Enabled(self, boolean: bool) -> 'WifiNetworkSuggestion.Builder': ...
        def setWifiSsid(self, wifiSsid: 'WifiSsid') -> 'WifiNetworkSuggestion.Builder': ...
        def setWpa2EnterpriseConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSuggestion.Builder': ...
        def setWpa2Passphrase(self, string: str) -> 'WifiNetworkSuggestion.Builder': ...
        def setWpa3Enterprise192BitModeConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSuggestion.Builder': ...
        def setWpa3EnterpriseConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSuggestion.Builder': ...
        def setWpa3EnterpriseStandardModeConfig(self, wifiEnterpriseConfig: WifiEnterpriseConfig) -> 'WifiNetworkSuggestion.Builder': ...
        def setWpa3Passphrase(self, string: str) -> 'WifiNetworkSuggestion.Builder': ...

class WifiSsid(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromBytes(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'WifiSsid': ...
    def getBytes(self) -> typing.MutableSequence[int]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WpsInfo(android.os.Parcelable):
    BSSID: str = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    DISPLAY: typing.ClassVar[int] = ...
    INVALID: typing.ClassVar[int] = ...
    KEYPAD: typing.ClassVar[int] = ...
    LABEL: typing.ClassVar[int] = ...
    PBC: typing.ClassVar[int] = ...
    pin: str = ...
    setup: int = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, wpsInfo: 'WpsInfo'): ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.net.wifi")``.

    EasyConnectStatusCallback: typing.Type[EasyConnectStatusCallback]
    MloLink: typing.Type[MloLink]
    ScanResult: typing.Type[ScanResult]
    SoftApConfiguration: typing.Type[SoftApConfiguration]
    SupplicantState: typing.Type[SupplicantState]
    WifiAvailableChannel: typing.Type[WifiAvailableChannel]
    WifiConfiguration: typing.Type[WifiConfiguration]
    WifiEnterpriseConfig: typing.Type[WifiEnterpriseConfig]
    WifiInfo: typing.Type[WifiInfo]
    WifiManager: typing.Type[WifiManager]
    WifiNetworkSpecifier: typing.Type[WifiNetworkSpecifier]
    WifiNetworkSuggestion: typing.Type[WifiNetworkSuggestion]
    WifiSsid: typing.Type[WifiSsid]
    WpsInfo: typing.Type[WpsInfo]
    aware: android.net.wifi.aware.__module_protocol__
    hotspot2: android.net.wifi.hotspot2.__module_protocol__
    p2p: android.net.wifi.p2p.__module_protocol__
    rtt: android.net.wifi.rtt.__module_protocol__
