
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.graphics.drawable
import android.os
import android.print_
import java.lang
import java.util
import typing



class CustomPrinterIconCallback:
    def onCustomPrinterIconLoaded(self, icon: android.graphics.drawable.Icon) -> bool: ...

class PrintDocument:
    def getData(self) -> android.os.ParcelFileDescriptor: ...
    def getInfo(self) -> android.print_.PrintDocumentInfo: ...

class PrintJob:
    def block(self, string: str) -> bool: ...
    def cancel(self) -> bool: ...
    def complete(self) -> bool: ...
    def equals(self, object: typing.Any) -> bool: ...
    def fail(self, string: str) -> bool: ...
    def getAdvancedIntOption(self, string: str) -> int: ...
    def getAdvancedStringOption(self, string: str) -> str: ...
    def getDocument(self) -> PrintDocument: ...
    def getId(self) -> android.print_.PrintJobId: ...
    def getInfo(self) -> android.print_.PrintJobInfo: ...
    def getTag(self) -> str: ...
    def hasAdvancedOption(self, string: str) -> bool: ...
    def hashCode(self) -> int: ...
    def isBlocked(self) -> bool: ...
    def isCancelled(self) -> bool: ...
    def isCompleted(self) -> bool: ...
    def isFailed(self) -> bool: ...
    def isQueued(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def setProgress(self, float: float) -> None: ...
    @typing.overload
    def setStatus(self, int: int) -> None: ...
    @typing.overload
    def setStatus(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setTag(self, string: str) -> bool: ...
    def start(self) -> bool: ...

class PrintService(android.app.Service):
    EXTRA_CAN_SELECT_PRINTER: typing.ClassVar[str] = ...
    EXTRA_PRINTER_INFO: typing.ClassVar[str] = ...
    EXTRA_PRINT_DOCUMENT_INFO: typing.ClassVar[str] = ...
    EXTRA_PRINT_JOB_INFO: typing.ClassVar[str] = ...
    EXTRA_SELECT_PRINTER: typing.ClassVar[str] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def generatePrinterId(self, string: str) -> android.print_.PrinterId: ...
    def getActivePrintJobs(self) -> java.util.List[PrintJob]: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...

class PrinterDiscoverySession:
    def __init__(self): ...
    def addPrinters(self, list: java.util.List[android.print_.PrinterInfo]) -> None: ...
    def getPrinters(self) -> java.util.List[android.print_.PrinterInfo]: ...
    def getTrackedPrinters(self) -> java.util.List[android.print_.PrinterId]: ...
    def isDestroyed(self) -> bool: ...
    def isPrinterDiscoveryStarted(self) -> bool: ...
    def onDestroy(self) -> None: ...
    def onRequestCustomPrinterIcon(self, printerId: android.print_.PrinterId, cancellationSignal: android.os.CancellationSignal, customPrinterIconCallback: CustomPrinterIconCallback) -> None: ...
    def onStartPrinterDiscovery(self, list: java.util.List[android.print_.PrinterId]) -> None: ...
    def onStartPrinterStateTracking(self, printerId: android.print_.PrinterId) -> None: ...
    def onStopPrinterDiscovery(self) -> None: ...
    def onStopPrinterStateTracking(self, printerId: android.print_.PrinterId) -> None: ...
    def onValidatePrinters(self, list: java.util.List[android.print_.PrinterId]) -> None: ...
    def removePrinters(self, list: java.util.List[android.print_.PrinterId]) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.printservice")``.

    CustomPrinterIconCallback: typing.Type[CustomPrinterIconCallback]
    PrintDocument: typing.Type[PrintDocument]
    PrintJob: typing.Type[PrintJob]
    PrintService: typing.Type[PrintService]
    PrinterDiscoverySession: typing.Type[PrinterDiscoverySession]
