
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.graphics.pdf.content
import android.os
import java.util
import typing



class PageSelection(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, selectionBoundary: 'SelectionBoundary', selectionBoundary2: 'SelectionBoundary', list: java.util.List[android.graphics.pdf.content.PdfPageTextContent]): ...
    def describeContents(self) -> int: ...
    def getPage(self) -> int: ...
    def getSelectedTextContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageTextContent]: ...
    def getStart(self) -> 'SelectionBoundary': ...
    def getStop(self) -> 'SelectionBoundary': ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SelectionBoundary(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, point: android.graphics.Point): ...
    @typing.overload
    def __init__(self, int: int): ...
    def describeContents(self) -> int: ...
    def getIndex(self) -> int: ...
    def getIsRtl(self) -> bool: ...
    def getPoint(self) -> android.graphics.Point: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.graphics.pdf.models.selection")``.

    PageSelection: typing.Type[PageSelection]
    SelectionBoundary: typing.Type[SelectionBoundary]
