
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.app
import android.content
import android.content.pm
import android.graphics
import android.graphics.drawable
import android.media
import android.media.tv.interactive
import android.net
import android.os
import android.provider
import android.util
import android.view
import java.lang
import java.util
import jpype
import typing



class AdBuffer(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, string: str, sharedMemory: android.os.SharedMemory, int2: int, int3: int, long: int, int4: int): ...
    def describeContents(self) -> int: ...
    def getFlags(self) -> int: ...
    def getId(self) -> int: ...
    def getLength(self) -> int: ...
    def getMimeType(self) -> str: ...
    def getOffset(self) -> int: ...
    def getPresentationTimeUs(self) -> int: ...
    def getSharedMemory(self) -> android.os.SharedMemory: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AdRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    REQUEST_TYPE_START: typing.ClassVar[int] = ...
    REQUEST_TYPE_STOP: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int, int2: int, uri: android.net.Uri, long: int, long2: int, long3: int, bundle: android.os.Bundle): ...
    @typing.overload
    def __init__(self, int: int, int2: int, parcelFileDescriptor: android.os.ParcelFileDescriptor, long: int, long2: int, long3: int, string: str, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getEchoIntervalMillis(self) -> int: ...
    def getFileDescriptor(self) -> android.os.ParcelFileDescriptor: ...
    def getId(self) -> int: ...
    def getMediaFileType(self) -> str: ...
    def getMetadata(self) -> android.os.Bundle: ...
    def getRequestType(self) -> int: ...
    def getStartTimeMillis(self) -> int: ...
    def getStopTimeMillis(self) -> int: ...
    def getUri(self) -> android.net.Uri: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AdResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RESPONSE_TYPE_BUFFERING: typing.ClassVar[int] = ...
    RESPONSE_TYPE_ERROR: typing.ClassVar[int] = ...
    RESPONSE_TYPE_FINISHED: typing.ClassVar[int] = ...
    RESPONSE_TYPE_PLAYING: typing.ClassVar[int] = ...
    RESPONSE_TYPE_STOPPED: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int, long: int): ...
    def describeContents(self) -> int: ...
    def getElapsedTimeMillis(self) -> int: ...
    def getId(self) -> int: ...
    def getResponseType(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AitInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int): ...
    def describeContents(self) -> int: ...
    def getType(self) -> int: ...
    def getVersion(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BroadcastInfoRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    REQUEST_OPTION_AUTO_UPDATE: typing.ClassVar[int] = ...
    REQUEST_OPTION_REPEAT: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getOption(self) -> int: ...
    def getRequestId(self) -> int: ...
    def getType(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BroadcastInfoResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RESPONSE_RESULT_CANCEL: typing.ClassVar[int] = ...
    RESPONSE_RESULT_ERROR: typing.ClassVar[int] = ...
    RESPONSE_RESULT_OK: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getRequestId(self) -> int: ...
    def getResponseResult(self) -> int: ...
    def getSequence(self) -> int: ...
    def getType(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TvContentRating:
    UNRATED: typing.ClassVar['TvContentRating'] = ...
    def contains(self, tvContentRating: 'TvContentRating') -> bool: ...
    @staticmethod
    def createRating(string: str, string2: str, string3: str, *string4: str) -> 'TvContentRating': ...
    def equals(self, object: typing.Any) -> bool: ...
    def flattenToString(self) -> str: ...
    def getDomain(self) -> str: ...
    def getMainRating(self) -> str: ...
    def getRatingSystem(self) -> str: ...
    def getSubRatings(self) -> java.util.List[str]: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def unflattenFromString(string: str) -> 'TvContentRating': ...

class TvInputInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EXTRA_INPUT_ID: typing.ClassVar[str] = ...
    TYPE_COMPONENT: typing.ClassVar[int] = ...
    TYPE_COMPOSITE: typing.ClassVar[int] = ...
    TYPE_DISPLAY_PORT: typing.ClassVar[int] = ...
    TYPE_DVI: typing.ClassVar[int] = ...
    TYPE_HDMI: typing.ClassVar[int] = ...
    TYPE_OTHER: typing.ClassVar[int] = ...
    TYPE_SCART: typing.ClassVar[int] = ...
    TYPE_SVIDEO: typing.ClassVar[int] = ...
    TYPE_TUNER: typing.ClassVar[int] = ...
    TYPE_VGA: typing.ClassVar[int] = ...
    def canPauseRecording(self) -> bool: ...
    def canRecord(self) -> bool: ...
    def createSettingsIntent(self) -> android.content.Intent: ...
    def createSetupIntent(self) -> android.content.Intent: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExtras(self) -> android.os.Bundle: ...
    def getId(self) -> str: ...
    def getParentId(self) -> str: ...
    def getServiceInfo(self) -> android.content.pm.ServiceInfo: ...
    def getTunerCount(self) -> int: ...
    def getType(self) -> int: ...
    def hashCode(self) -> int: ...
    def isHidden(self, context: android.content.Context) -> bool: ...
    def isPassthroughInput(self) -> bool: ...
    def loadCustomLabel(self, context: android.content.Context) -> java.lang.CharSequence: ...
    def loadIcon(self, context: android.content.Context) -> android.graphics.drawable.Drawable: ...
    def loadLabel(self, context: android.content.Context) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, context: android.content.Context, componentName: android.content.ComponentName): ...
        def build(self) -> 'TvInputInfo': ...
        def setCanPauseRecording(self, boolean: bool) -> 'TvInputInfo.Builder': ...
        def setCanRecord(self, boolean: bool) -> 'TvInputInfo.Builder': ...
        def setExtras(self, bundle: android.os.Bundle) -> 'TvInputInfo.Builder': ...
        def setTunerCount(self, int: int) -> 'TvInputInfo.Builder': ...

class TvInputManager:
    ACTION_BLOCKED_RATINGS_CHANGED: typing.ClassVar[str] = ...
    ACTION_PARENTAL_CONTROLS_ENABLED_CHANGED: typing.ClassVar[str] = ...
    ACTION_QUERY_CONTENT_RATING_SYSTEMS: typing.ClassVar[str] = ...
    ACTION_SETUP_INPUTS: typing.ClassVar[str] = ...
    ACTION_VIEW_RECORDING_SCHEDULES: typing.ClassVar[str] = ...
    BROADCAST_INFO_STREAM_EVENT: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_COMMAND: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_DSMCC: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_PES: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_SECTION: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_TABLE: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_TIMELINE: typing.ClassVar[int] = ...
    BROADCAST_INFO_TYPE_TS: typing.ClassVar[int] = ...
    INPUT_STATE_CONNECTED: typing.ClassVar[int] = ...
    INPUT_STATE_CONNECTED_STANDBY: typing.ClassVar[int] = ...
    INPUT_STATE_DISCONNECTED: typing.ClassVar[int] = ...
    META_DATA_CONTENT_RATING_SYSTEMS: typing.ClassVar[str] = ...
    RECORDING_ERROR_INSUFFICIENT_SPACE: typing.ClassVar[int] = ...
    RECORDING_ERROR_RESOURCE_BUSY: typing.ClassVar[int] = ...
    RECORDING_ERROR_UNKNOWN: typing.ClassVar[int] = ...
    SIGNAL_STRENGTH_LOST: typing.ClassVar[int] = ...
    SIGNAL_STRENGTH_STRONG: typing.ClassVar[int] = ...
    SIGNAL_STRENGTH_WEAK: typing.ClassVar[int] = ...
    TIME_SHIFT_INVALID_TIME: typing.ClassVar[int] = ...
    TIME_SHIFT_MODE_AUTO: typing.ClassVar[int] = ...
    TIME_SHIFT_MODE_LOCAL: typing.ClassVar[int] = ...
    TIME_SHIFT_MODE_NETWORK: typing.ClassVar[int] = ...
    TIME_SHIFT_MODE_OFF: typing.ClassVar[int] = ...
    TIME_SHIFT_STATUS_AVAILABLE: typing.ClassVar[int] = ...
    TIME_SHIFT_STATUS_UNAVAILABLE: typing.ClassVar[int] = ...
    TIME_SHIFT_STATUS_UNKNOWN: typing.ClassVar[int] = ...
    TIME_SHIFT_STATUS_UNSUPPORTED: typing.ClassVar[int] = ...
    TV_MESSAGE_GROUP_ID_NONE: typing.ClassVar[int] = ...
    TV_MESSAGE_KEY_GROUP_ID: typing.ClassVar[str] = ...
    TV_MESSAGE_KEY_RAW_DATA: typing.ClassVar[str] = ...
    TV_MESSAGE_KEY_STREAM_ID: typing.ClassVar[str] = ...
    TV_MESSAGE_KEY_SUBTYPE: typing.ClassVar[str] = ...
    TV_MESSAGE_SUBTYPE_CC_608E: typing.ClassVar[str] = ...
    TV_MESSAGE_SUBTYPE_WATERMARKING_A335: typing.ClassVar[str] = ...
    TV_MESSAGE_TYPE_CLOSED_CAPTION: typing.ClassVar[int] = ...
    TV_MESSAGE_TYPE_OTHER: typing.ClassVar[int] = ...
    TV_MESSAGE_TYPE_WATERMARK: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_AUDIO_ONLY: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_BUFFERING: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_BLACKOUT: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_CARD_INVALID: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_CARD_MUTE: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_INSUFFICIENT_OUTPUT_PROTECTION: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_LICENSE_EXPIRED: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_NEED_ACTIVATION: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_NEED_PAIRING: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_NO_CARD: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_PVR_RECORDING_NOT_ALLOWED: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_REBOOTING: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_CAS_UNKNOWN: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_INSUFFICIENT_RESOURCE: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_NOT_CONNECTED: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_TUNING: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_UNKNOWN: typing.ClassVar[int] = ...
    VIDEO_UNAVAILABLE_REASON_WEAK_SIGNAL: typing.ClassVar[int] = ...
    def getBlockedRatings(self) -> java.util.List[TvContentRating]: ...
    def getInputState(self, string: str) -> int: ...
    def getTvInputInfo(self, string: str) -> TvInputInfo: ...
    def getTvInputList(self) -> java.util.List[TvInputInfo]: ...
    def isParentalControlsEnabled(self) -> bool: ...
    def isRatingBlocked(self, tvContentRating: TvContentRating) -> bool: ...
    def registerCallback(self, tvInputCallback: 'TvInputManager.TvInputCallback', handler: android.os.Handler) -> None: ...
    def unregisterCallback(self, tvInputCallback: 'TvInputManager.TvInputCallback') -> None: ...
    def updateTvInputInfo(self, tvInputInfo: TvInputInfo) -> None: ...
    class TvInputCallback:
        def __init__(self): ...
        def onInputAdded(self, string: str) -> None: ...
        def onInputRemoved(self, string: str) -> None: ...
        def onInputStateChanged(self, string: str, int: int) -> None: ...
        def onInputUpdated(self, string: str) -> None: ...
        def onTvInputInfoUpdated(self, tvInputInfo: TvInputInfo) -> None: ...

class TvRecordingClient:
    def __init__(self, context: android.content.Context, string: str, recordingCallback: 'TvRecordingClient.RecordingCallback', handler: android.os.Handler): ...
    @typing.overload
    def pauseRecording(self) -> None: ...
    @typing.overload
    def pauseRecording(self, bundle: android.os.Bundle) -> None: ...
    def release(self) -> None: ...
    @typing.overload
    def resumeRecording(self) -> None: ...
    @typing.overload
    def resumeRecording(self, bundle: android.os.Bundle) -> None: ...
    def sendAppPrivateCommand(self, string: str, bundle: android.os.Bundle) -> None: ...
    def setTvInteractiveAppView(self, tvInteractiveAppView: android.media.tv.interactive.TvInteractiveAppView, string: str) -> None: ...
    @typing.overload
    def startRecording(self, uri: android.net.Uri) -> None: ...
    @typing.overload
    def startRecording(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
    def stopRecording(self) -> None: ...
    @typing.overload
    def tune(self, string: str, uri: android.net.Uri) -> None: ...
    @typing.overload
    def tune(self, string: str, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
    class RecordingCallback:
        def __init__(self): ...
        def onConnectionFailed(self, string: str) -> None: ...
        def onDisconnected(self, string: str) -> None: ...
        def onError(self, int: int) -> None: ...
        def onRecordingStopped(self, uri: android.net.Uri) -> None: ...
        def onTuned(self, uri: android.net.Uri) -> None: ...

class TvRecordingInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    FRIDAY: typing.ClassVar[int] = ...
    MONDAY: typing.ClassVar[int] = ...
    RECORDING_ALL: typing.ClassVar[int] = ...
    RECORDING_IN_PROGRESS: typing.ClassVar[int] = ...
    RECORDING_SCHEDULED: typing.ClassVar[int] = ...
    SATURDAY: typing.ClassVar[int] = ...
    SUNDAY: typing.ClassVar[int] = ...
    THURSDAY: typing.ClassVar[int] = ...
    TUESDAY: typing.ClassVar[int] = ...
    WEDNESDAY: typing.ClassVar[int] = ...
    def __init__(self, string: str, long: int, long2: int, int: int, string2: str, string3: str, long3: int, long4: int, uri: android.net.Uri, uri2: android.net.Uri, list: java.util.List[TvContentRating], uri3: android.net.Uri, long5: int, long6: int): ...
    def describeContents(self) -> int: ...
    def getChannelUri(self) -> android.net.Uri: ...
    def getContentRatings(self) -> java.util.List[TvContentRating]: ...
    def getDescription(self) -> str: ...
    def getEndPaddingMillis(self) -> int: ...
    def getName(self) -> str: ...
    def getProgramUri(self) -> android.net.Uri: ...
    def getRecordingDurationMillis(self) -> int: ...
    def getRecordingId(self) -> str: ...
    def getRecordingStartTimeMillis(self) -> int: ...
    def getRecordingUri(self) -> android.net.Uri: ...
    def getRepeatDays(self) -> int: ...
    def getScheduledDurationMillis(self) -> int: ...
    def getScheduledStartTimeMillis(self) -> int: ...
    def getStartPaddingMillis(self) -> int: ...
    def setDescription(self, string: str) -> None: ...
    def setName(self, string: str) -> None: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TvTrackInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_AUDIO: typing.ClassVar[int] = ...
    TYPE_SUBTITLE: typing.ClassVar[int] = ...
    TYPE_VIDEO: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAudioChannelCount(self) -> int: ...
    def getAudioSampleRate(self) -> int: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getEncoding(self) -> str: ...
    def getExtra(self) -> android.os.Bundle: ...
    def getId(self) -> str: ...
    def getLanguage(self) -> str: ...
    def getType(self) -> int: ...
    def getVideoActiveFormatDescription(self) -> int: ...
    def getVideoFrameRate(self) -> float: ...
    def getVideoHeight(self) -> int: ...
    def getVideoPixelAspectRatio(self) -> float: ...
    def getVideoWidth(self) -> int: ...
    def hashCode(self) -> int: ...
    def isAudioDescription(self) -> bool: ...
    def isEncrypted(self) -> bool: ...
    def isHardOfHearing(self) -> bool: ...
    def isSpokenSubtitle(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, string: str): ...
        def build(self) -> 'TvTrackInfo': ...
        def setAudioChannelCount(self, int: int) -> 'TvTrackInfo.Builder': ...
        def setAudioDescription(self, boolean: bool) -> 'TvTrackInfo.Builder': ...
        def setAudioSampleRate(self, int: int) -> 'TvTrackInfo.Builder': ...
        def setDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'TvTrackInfo.Builder': ...
        def setEncoding(self, string: str) -> 'TvTrackInfo.Builder': ...
        def setEncrypted(self, boolean: bool) -> 'TvTrackInfo.Builder': ...
        def setExtra(self, bundle: android.os.Bundle) -> 'TvTrackInfo.Builder': ...
        def setHardOfHearing(self, boolean: bool) -> 'TvTrackInfo.Builder': ...
        def setLanguage(self, string: str) -> 'TvTrackInfo.Builder': ...
        def setSpokenSubtitle(self, boolean: bool) -> 'TvTrackInfo.Builder': ...
        def setVideoActiveFormatDescription(self, byte: int) -> 'TvTrackInfo.Builder': ...
        def setVideoFrameRate(self, float: float) -> 'TvTrackInfo.Builder': ...
        def setVideoHeight(self, int: int) -> 'TvTrackInfo.Builder': ...
        def setVideoPixelAspectRatio(self, float: float) -> 'TvTrackInfo.Builder': ...
        def setVideoWidth(self, int: int) -> 'TvTrackInfo.Builder': ...

class TvView(android.view.ViewGroup):
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, int: int): ...
    def dispatchGenericMotionEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def dispatchKeyEvent(self, keyEvent: android.view.KeyEvent) -> bool: ...
    def dispatchTouchEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def dispatchTrackballEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
    def dispatchUnhandledInputEvent(self, inputEvent: android.view.InputEvent) -> bool: ...
    def dispatchWindowFocusChanged(self, boolean: bool) -> None: ...
    def draw(self, canvas: android.graphics.Canvas) -> None: ...
    def gatherTransparentRegion(self, region: android.graphics.Region) -> bool: ...
    def getAudioPresentations(self) -> java.util.List[android.media.AudioPresentation]: ...
    def getSelectedTrack(self, int: int) -> str: ...
    def getTracks(self, int: int) -> java.util.List[TvTrackInfo]: ...
    def onUnhandledInputEvent(self, inputEvent: android.view.InputEvent) -> bool: ...
    def overrideTvAppAttributionSource(self, attributionSource: android.content.AttributionSource) -> None: ...
    def reset(self) -> None: ...
    def selectAudioPresentation(self, int: int, int2: int) -> None: ...
    def selectTrack(self, int: int, string: str) -> None: ...
    def sendAppPrivateCommand(self, string: str, bundle: android.os.Bundle) -> None: ...
    def setCallback(self, tvInputCallback: 'TvView.TvInputCallback') -> None: ...
    def setCaptionEnabled(self, boolean: bool) -> None: ...
    def setInteractiveAppNotificationEnabled(self, boolean: bool) -> None: ...
    def setOnUnhandledInputEventListener(self, onUnhandledInputEventListener: typing.Union['TvView.OnUnhandledInputEventListener', typing.Callable]) -> None: ...
    def setStreamVolume(self, float: float) -> None: ...
    def setTimeShiftPositionCallback(self, timeShiftPositionCallback: 'TvView.TimeShiftPositionCallback') -> None: ...
    def setTvMessageEnabled(self, int: int, boolean: bool) -> None: ...
    def setZOrderMediaOverlay(self, boolean: bool) -> None: ...
    def setZOrderOnTop(self, boolean: bool) -> None: ...
    def timeShiftPause(self) -> None: ...
    def timeShiftPlay(self, string: str, uri: android.net.Uri) -> None: ...
    def timeShiftResume(self) -> None: ...
    def timeShiftSeekTo(self, long: int) -> None: ...
    def timeShiftSetMode(self, int: int) -> None: ...
    def timeShiftSetPlaybackParams(self, playbackParams: android.media.PlaybackParams) -> None: ...
    @typing.overload
    def tune(self, string: str, uri: android.net.Uri) -> None: ...
    @typing.overload
    def tune(self, string: str, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
    class OnUnhandledInputEventListener:
        def onUnhandledInputEvent(self, inputEvent: android.view.InputEvent) -> bool: ...
    class TimeShiftPositionCallback:
        def __init__(self): ...
        def onTimeShiftCurrentPositionChanged(self, string: str, long: int) -> None: ...
        def onTimeShiftStartPositionChanged(self, string: str, long: int) -> None: ...
    class TvInputCallback:
        def __init__(self): ...
        def onAitInfoUpdated(self, string: str, aitInfo: AitInfo) -> None: ...
        def onAudioPresentationSelected(self, string: str, int: int, int2: int) -> None: ...
        def onAudioPresentationsChanged(self, string: str, list: java.util.List[android.media.AudioPresentation]) -> None: ...
        def onAvailableSpeeds(self, string: str, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
        def onChannelRetuned(self, string: str, uri: android.net.Uri) -> None: ...
        def onConnectionFailed(self, string: str) -> None: ...
        def onContentAllowed(self, string: str) -> None: ...
        def onContentBlocked(self, string: str, tvContentRating: TvContentRating) -> None: ...
        def onCueingMessageAvailability(self, string: str, boolean: bool) -> None: ...
        def onDisconnected(self, string: str) -> None: ...
        def onSignalStrengthUpdated(self, string: str, int: int) -> None: ...
        def onTimeShiftMode(self, string: str, int: int) -> None: ...
        def onTimeShiftStatusChanged(self, string: str, int: int) -> None: ...
        def onTrackSelected(self, string: str, int: int, string2: str) -> None: ...
        def onTracksChanged(self, string: str, list: java.util.List[TvTrackInfo]) -> None: ...
        def onTuned(self, string: str, uri: android.net.Uri) -> None: ...
        def onTvMessage(self, string: str, int: int, bundle: android.os.Bundle) -> None: ...
        def onVideoAvailable(self, string: str) -> None: ...
        def onVideoSizeChanged(self, string: str, int: int, int2: int) -> None: ...
        def onVideoUnavailable(self, string: str, int: int) -> None: ...

class CommandRequest(BroadcastInfoRequest, android.os.Parcelable):
    ARGUMENT_TYPE_JSON: typing.ClassVar[str] = ...
    ARGUMENT_TYPE_XML: typing.ClassVar[str] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, string: str, string2: str, string3: str, string4: str): ...
    def describeContents(self) -> int: ...
    def getArgumentType(self) -> str: ...
    def getArguments(self) -> str: ...
    def getName(self) -> str: ...
    def getNamespace(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CommandResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    RESPONSE_TYPE_JSON: typing.ClassVar[str] = ...
    RESPONSE_TYPE_XML: typing.ClassVar[str] = ...
    def __init__(self, int: int, int2: int, int3: int, string: str, string2: str): ...
    def describeContents(self) -> int: ...
    def getResponse(self) -> str: ...
    def getResponseType(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DsmccRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, uri: android.net.Uri): ...
    def describeContents(self) -> int: ...
    def getUri(self) -> android.net.Uri: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DsmccResponse(BroadcastInfoResponse, android.os.Parcelable):
    BIOP_MESSAGE_TYPE_DIRECTORY: typing.ClassVar[str] = ...
    BIOP_MESSAGE_TYPE_FILE: typing.ClassVar[str] = ...
    BIOP_MESSAGE_TYPE_SERVICE_GATEWAY: typing.ClassVar[str] = ...
    BIOP_MESSAGE_TYPE_STREAM: typing.ClassVar[str] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, parcelFileDescriptor: android.os.ParcelFileDescriptor): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, boolean: bool, list: java.util.List[str]): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, intArray: typing.Union[typing.List[int], jpype.JArray], stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    def describeContents(self) -> int: ...
    def getBiopMessageType(self) -> str: ...
    def getChildList(self) -> java.util.List[str]: ...
    def getFile(self) -> android.os.ParcelFileDescriptor: ...
    def getStreamEventIds(self) -> typing.MutableSequence[int]: ...
    def getStreamEventNames(self) -> typing.MutableSequence[str]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PesRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, int4: int): ...
    def describeContents(self) -> int: ...
    def getStreamId(self) -> int: ...
    def getTsPid(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PesResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, string: str): ...
    def describeContents(self) -> int: ...
    def getSharedFilterToken(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SectionRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int): ...
    def describeContents(self) -> int: ...
    def getTableId(self) -> int: ...
    def getTsPid(self) -> int: ...
    def getVersion(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SectionResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getSessionData(self) -> android.os.Bundle: ...
    def getSessionId(self) -> int: ...
    def getVersion(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StreamEventRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, uri: android.net.Uri, string: str): ...
    def describeContents(self) -> int: ...
    def getEventName(self) -> str: ...
    def getTargetUri(self) -> android.net.Uri: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StreamEventResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, int4: int, long: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]): ...
    def describeContents(self) -> int: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getEventId(self) -> int: ...
    def getNptMillis(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TableRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TABLE_NAME_BAT: typing.ClassVar[int] = ...
    TABLE_NAME_CAT: typing.ClassVar[int] = ...
    TABLE_NAME_EIT: typing.ClassVar[int] = ...
    TABLE_NAME_NIT: typing.ClassVar[int] = ...
    TABLE_NAME_PAT: typing.ClassVar[int] = ...
    TABLE_NAME_PMT: typing.ClassVar[int] = ...
    TABLE_NAME_SDT: typing.ClassVar[int] = ...
    TABLE_NAME_SIT: typing.ClassVar[int] = ...
    TABLE_NAME_TDT: typing.ClassVar[int] = ...
    TABLE_NAME_TOT: typing.ClassVar[int] = ...
    def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int): ...
    def describeContents(self) -> int: ...
    def getTableId(self) -> int: ...
    def getTableName(self) -> int: ...
    def getVersion(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TableResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, uri: android.net.Uri, int4: int, int5: int): ...
    def describeContents(self) -> int: ...
    def getSize(self) -> int: ...
    def getTableByteArray(self) -> typing.MutableSequence[int]: ...
    def getTableSharedMemory(self) -> android.os.SharedMemory: ...
    def getTableUri(self) -> android.net.Uri: ...
    def getVersion(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, int2: int, int3: int, int4: int, int5: int): ...
        def build(self) -> 'TableResponse': ...
        def setTableByteArray(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'TableResponse.Builder': ...
        def setTableSharedMemory(self, sharedMemory: android.os.SharedMemory) -> 'TableResponse.Builder': ...
        def setTableUri(self, uri: android.net.Uri) -> 'TableResponse.Builder': ...

class TimelineRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int): ...
    @typing.overload
    def __init__(self, int: int, int2: int, int3: int, string: str): ...
    def describeContents(self) -> int: ...
    def getIntervalMillis(self) -> int: ...
    def getSelector(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TimelineResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, string: str, int4: int, int5: int, long: int, long2: int): ...
    def describeContents(self) -> int: ...
    def getSelector(self) -> android.net.Uri: ...
    def getTicks(self) -> int: ...
    def getUnitsPerSecond(self) -> int: ...
    def getUnitsPerTick(self) -> int: ...
    def getWallClock(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TsRequest(BroadcastInfoRequest, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int): ...
    def describeContents(self) -> int: ...
    def getTsPid(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TsResponse(BroadcastInfoResponse, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, int: int, int2: int, int3: int, string: str): ...
    def describeContents(self) -> int: ...
    def getSharedFilterToken(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TvContract:
    ACTION_INITIALIZE_PROGRAMS: typing.ClassVar[str] = ...
    ACTION_PREVIEW_PROGRAM_ADDED_TO_WATCH_NEXT: typing.ClassVar[str] = ...
    ACTION_PREVIEW_PROGRAM_BROWSABLE_DISABLED: typing.ClassVar[str] = ...
    ACTION_REQUEST_CHANNEL_BROWSABLE: typing.ClassVar[str] = ...
    ACTION_WATCH_NEXT_PROGRAM_BROWSABLE_DISABLED: typing.ClassVar[str] = ...
    AUTHORITY: typing.ClassVar[str] = ...
    EXTRA_CHANNEL_ID: typing.ClassVar[str] = ...
    EXTRA_PREVIEW_PROGRAM_ID: typing.ClassVar[str] = ...
    EXTRA_WATCH_NEXT_PROGRAM_ID: typing.ClassVar[str] = ...
    @typing.overload
    @staticmethod
    def buildChannelLogoUri(uri: android.net.Uri) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildChannelLogoUri(long: int) -> android.net.Uri: ...
    @staticmethod
    def buildChannelUri(long: int) -> android.net.Uri: ...
    @staticmethod
    def buildChannelUriForPassthroughInput(string: str) -> android.net.Uri: ...
    @staticmethod
    def buildChannelsUriForInput(string: str) -> android.net.Uri: ...
    @staticmethod
    def buildInputId(componentName: android.content.ComponentName) -> str: ...
    @staticmethod
    def buildPreviewProgramUri(long: int) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildPreviewProgramsUriForChannel(uri: android.net.Uri) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildPreviewProgramsUriForChannel(long: int) -> android.net.Uri: ...
    @staticmethod
    def buildProgramUri(long: int) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildProgramsUriForChannel(uri: android.net.Uri) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildProgramsUriForChannel(uri: android.net.Uri, long: int, long2: int) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildProgramsUriForChannel(long: int) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def buildProgramsUriForChannel(long: int, long2: int, long3: int) -> android.net.Uri: ...
    @staticmethod
    def buildRecordedProgramUri(long: int) -> android.net.Uri: ...
    @staticmethod
    def buildWatchNextProgramUri(long: int) -> android.net.Uri: ...
    @staticmethod
    def isChannelUri(uri: android.net.Uri) -> bool: ...
    @staticmethod
    def isChannelUriForPassthroughInput(uri: android.net.Uri) -> bool: ...
    @staticmethod
    def isChannelUriForTunerInput(uri: android.net.Uri) -> bool: ...
    @staticmethod
    def isProgramUri(uri: android.net.Uri) -> bool: ...
    @staticmethod
    def isRecordedProgramUri(uri: android.net.Uri) -> bool: ...
    @staticmethod
    def requestChannelBrowsable(context: android.content.Context, long: int) -> None: ...
    class BaseTvColumns(android.provider.BaseColumns):
        COLUMN_PACKAGE_NAME: typing.ClassVar[str] = ...
    class Channels(android.media.tv.TvContract.BaseTvColumns):
        COLUMN_APP_LINK_COLOR: typing.ClassVar[str] = ...
        COLUMN_APP_LINK_ICON_URI: typing.ClassVar[str] = ...
        COLUMN_APP_LINK_INTENT_URI: typing.ClassVar[str] = ...
        COLUMN_APP_LINK_POSTER_ART_URI: typing.ClassVar[str] = ...
        COLUMN_APP_LINK_TEXT: typing.ClassVar[str] = ...
        COLUMN_BROADCAST_GENRE: typing.ClassVar[str] = ...
        COLUMN_BROWSABLE: typing.ClassVar[str] = ...
        COLUMN_CHANNEL_LIST_ID: typing.ClassVar[str] = ...
        COLUMN_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_DISPLAY_NAME: typing.ClassVar[str] = ...
        COLUMN_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_GLOBAL_CONTENT_ID: typing.ClassVar[str] = ...
        COLUMN_INPUT_ID: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_DATA: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG1: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG2: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG3: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG4: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_ID: typing.ClassVar[str] = ...
        COLUMN_LOCKED: typing.ClassVar[str] = ...
        COLUMN_NETWORK_AFFILIATION: typing.ClassVar[str] = ...
        COLUMN_ORIGINAL_NETWORK_ID: typing.ClassVar[str] = ...
        COLUMN_REMOTE_CONTROL_KEY_PRESET_NUMBER: typing.ClassVar[str] = ...
        COLUMN_SCRAMBLED: typing.ClassVar[str] = ...
        COLUMN_SEARCHABLE: typing.ClassVar[str] = ...
        COLUMN_SERVICE_ID: typing.ClassVar[str] = ...
        COLUMN_SERVICE_TYPE: typing.ClassVar[str] = ...
        COLUMN_TRANSIENT: typing.ClassVar[str] = ...
        COLUMN_TRANSPORT_STREAM_ID: typing.ClassVar[str] = ...
        COLUMN_TYPE: typing.ClassVar[str] = ...
        COLUMN_VERSION_NUMBER: typing.ClassVar[str] = ...
        COLUMN_VIDEO_FORMAT: typing.ClassVar[str] = ...
        COLUMN_VIDEO_RESOLUTION: typing.ClassVar[str] = ...
        CONTENT_ITEM_TYPE: typing.ClassVar[str] = ...
        CONTENT_TYPE: typing.ClassVar[str] = ...
        CONTENT_URI: typing.ClassVar[android.net.Uri] = ...
        SERVICE_TYPE_AUDIO: typing.ClassVar[str] = ...
        SERVICE_TYPE_AUDIO_VIDEO: typing.ClassVar[str] = ...
        SERVICE_TYPE_OTHER: typing.ClassVar[str] = ...
        TYPE_1SEG: typing.ClassVar[str] = ...
        TYPE_ATSC3_T: typing.ClassVar[str] = ...
        TYPE_ATSC_C: typing.ClassVar[str] = ...
        TYPE_ATSC_M_H: typing.ClassVar[str] = ...
        TYPE_ATSC_T: typing.ClassVar[str] = ...
        TYPE_CMMB: typing.ClassVar[str] = ...
        TYPE_DTMB: typing.ClassVar[str] = ...
        TYPE_DVB_C: typing.ClassVar[str] = ...
        TYPE_DVB_C2: typing.ClassVar[str] = ...
        TYPE_DVB_H: typing.ClassVar[str] = ...
        TYPE_DVB_S: typing.ClassVar[str] = ...
        TYPE_DVB_S2: typing.ClassVar[str] = ...
        TYPE_DVB_SH: typing.ClassVar[str] = ...
        TYPE_DVB_T: typing.ClassVar[str] = ...
        TYPE_DVB_T2: typing.ClassVar[str] = ...
        TYPE_ISDB_C: typing.ClassVar[str] = ...
        TYPE_ISDB_S: typing.ClassVar[str] = ...
        TYPE_ISDB_S3: typing.ClassVar[str] = ...
        TYPE_ISDB_T: typing.ClassVar[str] = ...
        TYPE_ISDB_TB: typing.ClassVar[str] = ...
        TYPE_NTSC: typing.ClassVar[str] = ...
        TYPE_OTHER: typing.ClassVar[str] = ...
        TYPE_PAL: typing.ClassVar[str] = ...
        TYPE_PREVIEW: typing.ClassVar[str] = ...
        TYPE_SECAM: typing.ClassVar[str] = ...
        TYPE_S_DMB: typing.ClassVar[str] = ...
        TYPE_T_DMB: typing.ClassVar[str] = ...
        VIDEO_FORMAT_1080I: typing.ClassVar[str] = ...
        VIDEO_FORMAT_1080P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_2160P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_240P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_360P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_4320P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_480I: typing.ClassVar[str] = ...
        VIDEO_FORMAT_480P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_576I: typing.ClassVar[str] = ...
        VIDEO_FORMAT_576P: typing.ClassVar[str] = ...
        VIDEO_FORMAT_720P: typing.ClassVar[str] = ...
        VIDEO_RESOLUTION_ED: typing.ClassVar[str] = ...
        VIDEO_RESOLUTION_FHD: typing.ClassVar[str] = ...
        VIDEO_RESOLUTION_HD: typing.ClassVar[str] = ...
        VIDEO_RESOLUTION_SD: typing.ClassVar[str] = ...
        VIDEO_RESOLUTION_UHD: typing.ClassVar[str] = ...
        @staticmethod
        def getVideoResolution(string: str) -> str: ...
        class Logo:
            CONTENT_DIRECTORY: typing.ClassVar[str] = ...
    class PreviewPrograms(android.media.tv.TvContract.BaseTvColumns):
        ASPECT_RATIO_16_9: typing.ClassVar[int] = ...
        ASPECT_RATIO_1_1: typing.ClassVar[int] = ...
        ASPECT_RATIO_2_3: typing.ClassVar[int] = ...
        ASPECT_RATIO_3_2: typing.ClassVar[int] = ...
        ASPECT_RATIO_4_3: typing.ClassVar[int] = ...
        AVAILABILITY_AVAILABLE: typing.ClassVar[int] = ...
        AVAILABILITY_FREE_WITH_SUBSCRIPTION: typing.ClassVar[int] = ...
        AVAILABILITY_PAID_CONTENT: typing.ClassVar[int] = ...
        COLUMN_AUDIO_LANGUAGE: typing.ClassVar[str] = ...
        COLUMN_AUTHOR: typing.ClassVar[str] = ...
        COLUMN_AVAILABILITY: typing.ClassVar[str] = ...
        COLUMN_BROWSABLE: typing.ClassVar[str] = ...
        COLUMN_CANONICAL_GENRE: typing.ClassVar[str] = ...
        COLUMN_CHANNEL_ID: typing.ClassVar[str] = ...
        COLUMN_CONTENT_ID: typing.ClassVar[str] = ...
        COLUMN_CONTENT_RATING: typing.ClassVar[str] = ...
        COLUMN_DURATION_MILLIS: typing.ClassVar[str] = ...
        COLUMN_END_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_EPISODE_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_EPISODE_TITLE: typing.ClassVar[str] = ...
        COLUMN_INTENT_URI: typing.ClassVar[str] = ...
        COLUMN_INTERACTION_COUNT: typing.ClassVar[str] = ...
        COLUMN_INTERACTION_TYPE: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_DATA: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG1: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG2: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG3: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG4: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_ID: typing.ClassVar[str] = ...
        COLUMN_ITEM_COUNT: typing.ClassVar[str] = ...
        COLUMN_LAST_PLAYBACK_POSITION_MILLIS: typing.ClassVar[str] = ...
        COLUMN_LIVE: typing.ClassVar[str] = ...
        COLUMN_LOGO_URI: typing.ClassVar[str] = ...
        COLUMN_LONG_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_OFFER_PRICE: typing.ClassVar[str] = ...
        COLUMN_POSTER_ART_ASPECT_RATIO: typing.ClassVar[str] = ...
        COLUMN_POSTER_ART_URI: typing.ClassVar[str] = ...
        COLUMN_PREVIEW_VIDEO_URI: typing.ClassVar[str] = ...
        COLUMN_RELEASE_DATE: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING_STYLE: typing.ClassVar[str] = ...
        COLUMN_SEARCHABLE: typing.ClassVar[str] = ...
        COLUMN_SEASON_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_SEASON_TITLE: typing.ClassVar[str] = ...
        COLUMN_SERIES_ID: typing.ClassVar[str] = ...
        COLUMN_SHORT_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_SPLIT_ID: typing.ClassVar[str] = ...
        COLUMN_STARTING_PRICE: typing.ClassVar[str] = ...
        COLUMN_START_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_THUMBNAIL_ASPECT_RATIO: typing.ClassVar[str] = ...
        COLUMN_THUMBNAIL_URI: typing.ClassVar[str] = ...
        COLUMN_TITLE: typing.ClassVar[str] = ...
        COLUMN_TRANSIENT: typing.ClassVar[str] = ...
        COLUMN_TYPE: typing.ClassVar[str] = ...
        COLUMN_VERSION_NUMBER: typing.ClassVar[str] = ...
        COLUMN_VIDEO_HEIGHT: typing.ClassVar[str] = ...
        COLUMN_VIDEO_WIDTH: typing.ClassVar[str] = ...
        COLUMN_WEIGHT: typing.ClassVar[str] = ...
        CONTENT_ITEM_TYPE: typing.ClassVar[str] = ...
        CONTENT_TYPE: typing.ClassVar[str] = ...
        CONTENT_URI: typing.ClassVar[android.net.Uri] = ...
        INTERACTION_TYPE_FANS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_FOLLOWERS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_LIKES: typing.ClassVar[int] = ...
        INTERACTION_TYPE_LISTENS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_THUMBS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_VIEWERS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_VIEWS: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_PERCENTAGE: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_STARS: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: typing.ClassVar[int] = ...
        TYPE_ALBUM: typing.ClassVar[int] = ...
        TYPE_ARTIST: typing.ClassVar[int] = ...
        TYPE_CHANNEL: typing.ClassVar[int] = ...
        TYPE_CLIP: typing.ClassVar[int] = ...
        TYPE_EVENT: typing.ClassVar[int] = ...
        TYPE_MOVIE: typing.ClassVar[int] = ...
        TYPE_PLAYLIST: typing.ClassVar[int] = ...
        TYPE_STATION: typing.ClassVar[int] = ...
        TYPE_TRACK: typing.ClassVar[int] = ...
        TYPE_TV_EPISODE: typing.ClassVar[int] = ...
        TYPE_TV_SEASON: typing.ClassVar[int] = ...
        TYPE_TV_SERIES: typing.ClassVar[int] = ...
    class Programs(android.media.tv.TvContract.BaseTvColumns):
        COLUMN_AUDIO_LANGUAGE: typing.ClassVar[str] = ...
        COLUMN_BROADCAST_GENRE: typing.ClassVar[str] = ...
        COLUMN_CANONICAL_GENRE: typing.ClassVar[str] = ...
        COLUMN_CHANNEL_ID: typing.ClassVar[str] = ...
        COLUMN_CONTENT_RATING: typing.ClassVar[str] = ...
        COLUMN_END_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_EPISODE_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_EPISODE_NUMBER: typing.ClassVar[str] = ...
        COLUMN_EPISODE_TITLE: typing.ClassVar[str] = ...
        COLUMN_EVENT_ID: typing.ClassVar[str] = ...
        COLUMN_GLOBAL_CONTENT_ID: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_DATA: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG1: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG2: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG3: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG4: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_ID: typing.ClassVar[str] = ...
        COLUMN_LONG_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_MULTI_SERIES_ID: typing.ClassVar[str] = ...
        COLUMN_POSTER_ART_URI: typing.ClassVar[str] = ...
        COLUMN_RECORDING_PROHIBITED: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING_STYLE: typing.ClassVar[str] = ...
        COLUMN_SCRAMBLED: typing.ClassVar[str] = ...
        COLUMN_SEARCHABLE: typing.ClassVar[str] = ...
        COLUMN_SEASON_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_SEASON_NUMBER: typing.ClassVar[str] = ...
        COLUMN_SEASON_TITLE: typing.ClassVar[str] = ...
        COLUMN_SERIES_ID: typing.ClassVar[str] = ...
        COLUMN_SHORT_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_SPLIT_ID: typing.ClassVar[str] = ...
        COLUMN_START_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_THUMBNAIL_URI: typing.ClassVar[str] = ...
        COLUMN_TITLE: typing.ClassVar[str] = ...
        COLUMN_VERSION_NUMBER: typing.ClassVar[str] = ...
        COLUMN_VIDEO_HEIGHT: typing.ClassVar[str] = ...
        COLUMN_VIDEO_WIDTH: typing.ClassVar[str] = ...
        CONTENT_ITEM_TYPE: typing.ClassVar[str] = ...
        CONTENT_TYPE: typing.ClassVar[str] = ...
        CONTENT_URI: typing.ClassVar[android.net.Uri] = ...
        REVIEW_RATING_STYLE_PERCENTAGE: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_STARS: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: typing.ClassVar[int] = ...
        class Genres:
            ANIMAL_WILDLIFE: typing.ClassVar[str] = ...
            ARTS: typing.ClassVar[str] = ...
            COMEDY: typing.ClassVar[str] = ...
            DRAMA: typing.ClassVar[str] = ...
            EDUCATION: typing.ClassVar[str] = ...
            ENTERTAINMENT: typing.ClassVar[str] = ...
            FAMILY_KIDS: typing.ClassVar[str] = ...
            GAMING: typing.ClassVar[str] = ...
            LIFE_STYLE: typing.ClassVar[str] = ...
            MOVIES: typing.ClassVar[str] = ...
            MUSIC: typing.ClassVar[str] = ...
            NEWS: typing.ClassVar[str] = ...
            PREMIER: typing.ClassVar[str] = ...
            SHOPPING: typing.ClassVar[str] = ...
            SPORTS: typing.ClassVar[str] = ...
            TECH_SCIENCE: typing.ClassVar[str] = ...
            TRAVEL: typing.ClassVar[str] = ...
            @staticmethod
            def decode(string: str) -> typing.MutableSequence[str]: ...
            @staticmethod
            def encode(*string: str) -> str: ...
            @staticmethod
            def isCanonical(string: str) -> bool: ...
    class RecordedPrograms(android.media.tv.TvContract.BaseTvColumns):
        COLUMN_AUDIO_LANGUAGE: typing.ClassVar[str] = ...
        COLUMN_BROADCAST_GENRE: typing.ClassVar[str] = ...
        COLUMN_CANONICAL_GENRE: typing.ClassVar[str] = ...
        COLUMN_CHANNEL_ID: typing.ClassVar[str] = ...
        COLUMN_CONTENT_RATING: typing.ClassVar[str] = ...
        COLUMN_END_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_EPISODE_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_EPISODE_TITLE: typing.ClassVar[str] = ...
        COLUMN_INPUT_ID: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_DATA: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG1: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG2: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG3: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG4: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_ID: typing.ClassVar[str] = ...
        COLUMN_LONG_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_MULTI_SERIES_ID: typing.ClassVar[str] = ...
        COLUMN_POSTER_ART_URI: typing.ClassVar[str] = ...
        COLUMN_RECORDING_DATA_BYTES: typing.ClassVar[str] = ...
        COLUMN_RECORDING_DATA_URI: typing.ClassVar[str] = ...
        COLUMN_RECORDING_DURATION_MILLIS: typing.ClassVar[str] = ...
        COLUMN_RECORDING_EXPIRE_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING_STYLE: typing.ClassVar[str] = ...
        COLUMN_SEARCHABLE: typing.ClassVar[str] = ...
        COLUMN_SEASON_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_SEASON_TITLE: typing.ClassVar[str] = ...
        COLUMN_SERIES_ID: typing.ClassVar[str] = ...
        COLUMN_SHORT_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_SPLIT_ID: typing.ClassVar[str] = ...
        COLUMN_START_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_THUMBNAIL_URI: typing.ClassVar[str] = ...
        COLUMN_TITLE: typing.ClassVar[str] = ...
        COLUMN_VERSION_NUMBER: typing.ClassVar[str] = ...
        COLUMN_VIDEO_HEIGHT: typing.ClassVar[str] = ...
        COLUMN_VIDEO_WIDTH: typing.ClassVar[str] = ...
        CONTENT_ITEM_TYPE: typing.ClassVar[str] = ...
        CONTENT_TYPE: typing.ClassVar[str] = ...
        CONTENT_URI: typing.ClassVar[android.net.Uri] = ...
        REVIEW_RATING_STYLE_PERCENTAGE: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_STARS: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: typing.ClassVar[int] = ...
    class WatchNextPrograms(android.media.tv.TvContract.BaseTvColumns):
        ASPECT_RATIO_16_9: typing.ClassVar[int] = ...
        ASPECT_RATIO_1_1: typing.ClassVar[int] = ...
        ASPECT_RATIO_2_3: typing.ClassVar[int] = ...
        ASPECT_RATIO_3_2: typing.ClassVar[int] = ...
        ASPECT_RATIO_4_3: typing.ClassVar[int] = ...
        AVAILABILITY_AVAILABLE: typing.ClassVar[int] = ...
        AVAILABILITY_FREE_WITH_SUBSCRIPTION: typing.ClassVar[int] = ...
        AVAILABILITY_PAID_CONTENT: typing.ClassVar[int] = ...
        COLUMN_AUDIO_LANGUAGE: typing.ClassVar[str] = ...
        COLUMN_AUTHOR: typing.ClassVar[str] = ...
        COLUMN_AVAILABILITY: typing.ClassVar[str] = ...
        COLUMN_BROWSABLE: typing.ClassVar[str] = ...
        COLUMN_CANONICAL_GENRE: typing.ClassVar[str] = ...
        COLUMN_CONTENT_ID: typing.ClassVar[str] = ...
        COLUMN_CONTENT_RATING: typing.ClassVar[str] = ...
        COLUMN_DURATION_MILLIS: typing.ClassVar[str] = ...
        COLUMN_END_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_EPISODE_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_EPISODE_TITLE: typing.ClassVar[str] = ...
        COLUMN_INTENT_URI: typing.ClassVar[str] = ...
        COLUMN_INTERACTION_COUNT: typing.ClassVar[str] = ...
        COLUMN_INTERACTION_TYPE: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_DATA: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG1: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG2: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG3: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_FLAG4: typing.ClassVar[str] = ...
        COLUMN_INTERNAL_PROVIDER_ID: typing.ClassVar[str] = ...
        COLUMN_ITEM_COUNT: typing.ClassVar[str] = ...
        COLUMN_LAST_ENGAGEMENT_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_LAST_PLAYBACK_POSITION_MILLIS: typing.ClassVar[str] = ...
        COLUMN_LIVE: typing.ClassVar[str] = ...
        COLUMN_LOGO_URI: typing.ClassVar[str] = ...
        COLUMN_LONG_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_OFFER_PRICE: typing.ClassVar[str] = ...
        COLUMN_POSTER_ART_ASPECT_RATIO: typing.ClassVar[str] = ...
        COLUMN_POSTER_ART_URI: typing.ClassVar[str] = ...
        COLUMN_PREVIEW_VIDEO_URI: typing.ClassVar[str] = ...
        COLUMN_RELEASE_DATE: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING: typing.ClassVar[str] = ...
        COLUMN_REVIEW_RATING_STYLE: typing.ClassVar[str] = ...
        COLUMN_SEARCHABLE: typing.ClassVar[str] = ...
        COLUMN_SEASON_DISPLAY_NUMBER: typing.ClassVar[str] = ...
        COLUMN_SEASON_TITLE: typing.ClassVar[str] = ...
        COLUMN_SERIES_ID: typing.ClassVar[str] = ...
        COLUMN_SHORT_DESCRIPTION: typing.ClassVar[str] = ...
        COLUMN_SPLIT_ID: typing.ClassVar[str] = ...
        COLUMN_STARTING_PRICE: typing.ClassVar[str] = ...
        COLUMN_START_TIME_UTC_MILLIS: typing.ClassVar[str] = ...
        COLUMN_THUMBNAIL_ASPECT_RATIO: typing.ClassVar[str] = ...
        COLUMN_THUMBNAIL_URI: typing.ClassVar[str] = ...
        COLUMN_TITLE: typing.ClassVar[str] = ...
        COLUMN_TRANSIENT: typing.ClassVar[str] = ...
        COLUMN_TYPE: typing.ClassVar[str] = ...
        COLUMN_VERSION_NUMBER: typing.ClassVar[str] = ...
        COLUMN_VIDEO_HEIGHT: typing.ClassVar[str] = ...
        COLUMN_VIDEO_WIDTH: typing.ClassVar[str] = ...
        COLUMN_WATCH_NEXT_TYPE: typing.ClassVar[str] = ...
        CONTENT_ITEM_TYPE: typing.ClassVar[str] = ...
        CONTENT_TYPE: typing.ClassVar[str] = ...
        CONTENT_URI: typing.ClassVar[android.net.Uri] = ...
        INTERACTION_TYPE_FANS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_FOLLOWERS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_LIKES: typing.ClassVar[int] = ...
        INTERACTION_TYPE_LISTENS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_THUMBS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_VIEWERS: typing.ClassVar[int] = ...
        INTERACTION_TYPE_VIEWS: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_PERCENTAGE: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_STARS: typing.ClassVar[int] = ...
        REVIEW_RATING_STYLE_THUMBS_UP_DOWN: typing.ClassVar[int] = ...
        TYPE_ALBUM: typing.ClassVar[int] = ...
        TYPE_ARTIST: typing.ClassVar[int] = ...
        TYPE_CHANNEL: typing.ClassVar[int] = ...
        TYPE_CLIP: typing.ClassVar[int] = ...
        TYPE_EVENT: typing.ClassVar[int] = ...
        TYPE_MOVIE: typing.ClassVar[int] = ...
        TYPE_PLAYLIST: typing.ClassVar[int] = ...
        TYPE_STATION: typing.ClassVar[int] = ...
        TYPE_TRACK: typing.ClassVar[int] = ...
        TYPE_TV_EPISODE: typing.ClassVar[int] = ...
        TYPE_TV_SEASON: typing.ClassVar[int] = ...
        TYPE_TV_SERIES: typing.ClassVar[int] = ...
        WATCH_NEXT_TYPE_CONTINUE: typing.ClassVar[int] = ...
        WATCH_NEXT_TYPE_NEW: typing.ClassVar[int] = ...
        WATCH_NEXT_TYPE_NEXT: typing.ClassVar[int] = ...
        WATCH_NEXT_TYPE_WATCHLIST: typing.ClassVar[int] = ...

class TvInputService(android.app.Service):
    PRIORITY_HINT_USE_CASE_TYPE_BACKGROUND: typing.ClassVar[int] = ...
    PRIORITY_HINT_USE_CASE_TYPE_LIVE: typing.ClassVar[int] = ...
    PRIORITY_HINT_USE_CASE_TYPE_PLAYBACK: typing.ClassVar[int] = ...
    PRIORITY_HINT_USE_CASE_TYPE_RECORD: typing.ClassVar[int] = ...
    PRIORITY_HINT_USE_CASE_TYPE_SCAN: typing.ClassVar[int] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    @typing.overload
    def onCreateRecordingSession(self, string: str) -> 'TvInputService.RecordingSession': ...
    @typing.overload
    def onCreateRecordingSession(self, string: str, string2: str) -> 'TvInputService.RecordingSession': ...
    @typing.overload
    def onCreateSession(self, string: str) -> 'TvInputService.Session': ...
    @typing.overload
    def onCreateSession(self, string: str, string2: str) -> 'TvInputService.Session': ...
    @typing.overload
    def onCreateSession(self, string: str, string2: str, attributionSource: android.content.AttributionSource) -> 'TvInputService.Session': ...
    class HardwareSession(android.media.tv.TvInputService.Session):
        def __init__(self, context: android.content.Context): ...
        def getHardwareInputId(self) -> str: ...
        def onHardwareVideoAvailable(self) -> None: ...
        def onHardwareVideoUnavailable(self, int: int) -> None: ...
        def onSetSurface(self, surface: android.view.Surface) -> bool: ...
    class RecordingSession:
        def __init__(self, context: android.content.Context): ...
        def notifyError(self, int: int) -> None: ...
        def notifyRecordingStopped(self, uri: android.net.Uri) -> None: ...
        def notifyTuned(self, uri: android.net.Uri) -> None: ...
        def onAppPrivateCommand(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onPauseRecording(self, bundle: android.os.Bundle) -> None: ...
        def onRelease(self) -> None: ...
        def onResumeRecording(self, bundle: android.os.Bundle) -> None: ...
        @typing.overload
        def onStartRecording(self, uri: android.net.Uri) -> None: ...
        @typing.overload
        def onStartRecording(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
        def onStopRecording(self) -> None: ...
        @typing.overload
        def onTune(self, uri: android.net.Uri) -> None: ...
        @typing.overload
        def onTune(self, uri: android.net.Uri, bundle: android.os.Bundle) -> None: ...
    class Session(android.view.KeyEvent.Callback):
        def __init__(self, context: android.content.Context): ...
        def layoutSurface(self, int: int, int2: int, int3: int, int4: int) -> None: ...
        def notifyAdBufferConsumed(self, adBuffer: AdBuffer) -> None: ...
        def notifyAdResponse(self, adResponse: AdResponse) -> None: ...
        def notifyAitInfoUpdated(self, aitInfo: AitInfo) -> None: ...
        def notifyAudioPresentationChanged(self, list: java.util.List[android.media.AudioPresentation]) -> None: ...
        def notifyAudioPresentationSelected(self, int: int, int2: int) -> None: ...
        def notifyAvailableSpeeds(self, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
        def notifyBroadcastInfoResponse(self, broadcastInfoResponse: BroadcastInfoResponse) -> None: ...
        def notifyChannelRetuned(self, uri: android.net.Uri) -> None: ...
        def notifyContentAllowed(self) -> None: ...
        def notifyContentBlocked(self, tvContentRating: TvContentRating) -> None: ...
        def notifyCueingMessageAvailability(self, boolean: bool) -> None: ...
        def notifySignalStrength(self, int: int) -> None: ...
        def notifyTimeShiftMode(self, int: int) -> None: ...
        def notifyTimeShiftStatusChanged(self, int: int) -> None: ...
        def notifyTrackSelected(self, int: int, string: str) -> None: ...
        def notifyTracksChanged(self, list: java.util.List[TvTrackInfo]) -> None: ...
        def notifyTuned(self, uri: android.net.Uri) -> None: ...
        def notifyTvMessage(self, int: int, bundle: android.os.Bundle) -> None: ...
        def notifyVideoAvailable(self) -> None: ...
        def notifyVideoUnavailable(self, int: int) -> None: ...
        def onAdBufferReady(self, adBuffer: AdBuffer) -> None: ...
        def onAppPrivateCommand(self, string: str, bundle: android.os.Bundle) -> None: ...
        def onCreateOverlayView(self) -> android.view.View: ...
        def onGenericMotionEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
        def onKeyDown(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
        def onKeyLongPress(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
        def onKeyMultiple(self, int: int, int2: int, keyEvent: android.view.KeyEvent) -> bool: ...
        def onKeyUp(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
        def onOverlayViewSizeChanged(self, int: int, int2: int) -> None: ...
        def onRelease(self) -> None: ...
        def onRemoveBroadcastInfo(self, int: int) -> None: ...
        def onRequestAd(self, adRequest: AdRequest) -> None: ...
        def onRequestBroadcastInfo(self, broadcastInfoRequest: BroadcastInfoRequest) -> None: ...
        def onSelectAudioPresentation(self, int: int, int2: int) -> bool: ...
        def onSelectTrack(self, int: int, string: str) -> bool: ...
        def onSetCaptionEnabled(self, boolean: bool) -> None: ...
        def onSetInteractiveAppNotificationEnabled(self, boolean: bool) -> None: ...
        def onSetStreamVolume(self, float: float) -> None: ...
        def onSetSurface(self, surface: android.view.Surface) -> bool: ...
        def onSetTvMessageEnabled(self, int: int, boolean: bool) -> None: ...
        def onSurfaceChanged(self, int: int, int2: int, int3: int) -> None: ...
        def onTimeShiftGetCurrentPosition(self) -> int: ...
        def onTimeShiftGetStartPosition(self) -> int: ...
        def onTimeShiftPause(self) -> None: ...
        def onTimeShiftPlay(self, uri: android.net.Uri) -> None: ...
        def onTimeShiftResume(self) -> None: ...
        def onTimeShiftSeekTo(self, long: int) -> None: ...
        def onTimeShiftSetMode(self, int: int) -> None: ...
        def onTimeShiftSetPlaybackParams(self, playbackParams: android.media.PlaybackParams) -> None: ...
        def onTouchEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
        def onTrackballEvent(self, motionEvent: android.view.MotionEvent) -> bool: ...
        @typing.overload
        def onTune(self, uri: android.net.Uri) -> bool: ...
        @typing.overload
        def onTune(self, uri: android.net.Uri, bundle: android.os.Bundle) -> bool: ...
        def onTvMessage(self, int: int, bundle: android.os.Bundle) -> None: ...
        def onUnblockContent(self, tvContentRating: TvContentRating) -> None: ...
        def setOverlayViewEnabled(self, boolean: bool) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.media.tv")``.

    AdBuffer: typing.Type[AdBuffer]
    AdRequest: typing.Type[AdRequest]
    AdResponse: typing.Type[AdResponse]
    AitInfo: typing.Type[AitInfo]
    BroadcastInfoRequest: typing.Type[BroadcastInfoRequest]
    BroadcastInfoResponse: typing.Type[BroadcastInfoResponse]
    CommandRequest: typing.Type[CommandRequest]
    CommandResponse: typing.Type[CommandResponse]
    DsmccRequest: typing.Type[DsmccRequest]
    DsmccResponse: typing.Type[DsmccResponse]
    PesRequest: typing.Type[PesRequest]
    PesResponse: typing.Type[PesResponse]
    SectionRequest: typing.Type[SectionRequest]
    SectionResponse: typing.Type[SectionResponse]
    StreamEventRequest: typing.Type[StreamEventRequest]
    StreamEventResponse: typing.Type[StreamEventResponse]
    TableRequest: typing.Type[TableRequest]
    TableResponse: typing.Type[TableResponse]
    TimelineRequest: typing.Type[TimelineRequest]
    TimelineResponse: typing.Type[TimelineResponse]
    TsRequest: typing.Type[TsRequest]
    TsResponse: typing.Type[TsResponse]
    TvContentRating: typing.Type[TvContentRating]
    TvContract: typing.Type[TvContract]
    TvInputInfo: typing.Type[TvInputInfo]
    TvInputManager: typing.Type[TvInputManager]
    TvInputService: typing.Type[TvInputService]
    TvRecordingClient: typing.Type[TvRecordingClient]
    TvRecordingInfo: typing.Type[TvRecordingInfo]
    TvTrackInfo: typing.Type[TvTrackInfo]
    TvView: typing.Type[TvView]
    interactive: android.media.tv.interactive.__module_protocol__
