
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.content.pm
import android.graphics
import android.graphics.drawable
import android.net
import android.net.wifi
import android.os
import android.security
import android.security.keystore
import android.telephony.data
import android.util
import java.lang
import java.net
import java.security
import java.security.cert
import java.time
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class DelegatedAdminReceiver(android.content.BroadcastReceiver):
    def __init__(self): ...
    def onChoosePrivateKeyAlias(self, context: android.content.Context, intent: android.content.Intent, int2: int, uri: android.net.Uri, string: str) -> str: ...
    def onNetworkLogsAvailable(self, context: android.content.Context, intent: android.content.Intent, long: int, int2: int) -> None: ...
    def onReceive(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onSecurityLogsAvailable(self, context: android.content.Context, intent: android.content.Intent) -> None: ...

class DeviceAdminInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    HEADLESS_DEVICE_OWNER_MODE_AFFILIATED: typing.ClassVar[int] = ...
    HEADLESS_DEVICE_OWNER_MODE_SINGLE_USER: typing.ClassVar[int] = ...
    HEADLESS_DEVICE_OWNER_MODE_UNSUPPORTED: typing.ClassVar[int] = ...
    USES_ENCRYPTED_STORAGE: typing.ClassVar[int] = ...
    USES_POLICY_DISABLE_CAMERA: typing.ClassVar[int] = ...
    USES_POLICY_DISABLE_KEYGUARD_FEATURES: typing.ClassVar[int] = ...
    USES_POLICY_EXPIRE_PASSWORD: typing.ClassVar[int] = ...
    USES_POLICY_FORCE_LOCK: typing.ClassVar[int] = ...
    USES_POLICY_LIMIT_PASSWORD: typing.ClassVar[int] = ...
    USES_POLICY_RESET_PASSWORD: typing.ClassVar[int] = ...
    USES_POLICY_WATCH_LOGIN: typing.ClassVar[int] = ...
    USES_POLICY_WIPE_DATA: typing.ClassVar[int] = ...
    def __init__(self, context: android.content.Context, resolveInfo: android.content.pm.ResolveInfo): ...
    def describeContents(self) -> int: ...
    def dump(self, printer: typing.Union[android.util.Printer, typing.Callable], string: str) -> None: ...
    def getActivityInfo(self) -> android.content.pm.ActivityInfo: ...
    def getComponent(self) -> android.content.ComponentName: ...
    def getHeadlessDeviceOwnerMode(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getReceiverName(self) -> str: ...
    def getTagForPolicy(self, int: int) -> str: ...
    def isVisible(self) -> bool: ...
    def loadDescription(self, packageManager: android.content.pm.PackageManager) -> java.lang.CharSequence: ...
    def loadIcon(self, packageManager: android.content.pm.PackageManager) -> android.graphics.drawable.Drawable: ...
    def loadLabel(self, packageManager: android.content.pm.PackageManager) -> java.lang.CharSequence: ...
    def supportsTransferOwnership(self) -> bool: ...
    def toString(self) -> str: ...
    def usesPolicy(self, int: int) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DeviceAdminReceiver(android.content.BroadcastReceiver):
    ACTION_CHOOSE_PRIVATE_KEY_ALIAS: typing.ClassVar[str] = ...
    ACTION_DEVICE_ADMIN_DISABLED: typing.ClassVar[str] = ...
    ACTION_DEVICE_ADMIN_DISABLE_REQUESTED: typing.ClassVar[str] = ...
    ACTION_DEVICE_ADMIN_ENABLED: typing.ClassVar[str] = ...
    ACTION_LOCK_TASK_ENTERING: typing.ClassVar[str] = ...
    ACTION_LOCK_TASK_EXITING: typing.ClassVar[str] = ...
    ACTION_NETWORK_LOGS_AVAILABLE: typing.ClassVar[str] = ...
    ACTION_PASSWORD_CHANGED: typing.ClassVar[str] = ...
    ACTION_PASSWORD_EXPIRING: typing.ClassVar[str] = ...
    ACTION_PASSWORD_FAILED: typing.ClassVar[str] = ...
    ACTION_PASSWORD_SUCCEEDED: typing.ClassVar[str] = ...
    ACTION_PROFILE_PROVISIONING_COMPLETE: typing.ClassVar[str] = ...
    ACTION_SECURITY_LOGS_AVAILABLE: typing.ClassVar[str] = ...
    BUGREPORT_FAILURE_FAILED_COMPLETING: typing.ClassVar[int] = ...
    BUGREPORT_FAILURE_FILE_NO_LONGER_AVAILABLE: typing.ClassVar[int] = ...
    DEVICE_ADMIN_META_DATA: typing.ClassVar[str] = ...
    EXTRA_DISABLE_WARNING: typing.ClassVar[str] = ...
    EXTRA_LOCK_TASK_PACKAGE: typing.ClassVar[str] = ...
    EXTRA_TRANSFER_OWNERSHIP_ADMIN_EXTRAS_BUNDLE: typing.ClassVar[str] = ...
    def __init__(self): ...
    def getManager(self, context: android.content.Context) -> 'DevicePolicyManager': ...
    def getWho(self, context: android.content.Context) -> android.content.ComponentName: ...
    def onBugreportFailed(self, context: android.content.Context, intent: android.content.Intent, int2: int) -> None: ...
    def onBugreportShared(self, context: android.content.Context, intent: android.content.Intent, string: str) -> None: ...
    def onBugreportSharingDeclined(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onChoosePrivateKeyAlias(self, context: android.content.Context, intent: android.content.Intent, int2: int, uri: android.net.Uri, string: str) -> str: ...
    def onComplianceAcknowledgementRequired(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onDisableRequested(self, context: android.content.Context, intent: android.content.Intent) -> java.lang.CharSequence: ...
    def onDisabled(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onEnabled(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onLockTaskModeEntering(self, context: android.content.Context, intent: android.content.Intent, string: str) -> None: ...
    def onLockTaskModeExiting(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onNetworkLogsAvailable(self, context: android.content.Context, intent: android.content.Intent, long: int, int2: int) -> None: ...
    def onOperationSafetyStateChanged(self, context: android.content.Context, int: int, boolean: bool) -> None: ...
    @typing.overload
    def onPasswordChanged(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    @typing.overload
    def onPasswordChanged(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    @typing.overload
    def onPasswordExpiring(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    @typing.overload
    def onPasswordExpiring(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    @typing.overload
    def onPasswordFailed(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    @typing.overload
    def onPasswordFailed(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    @typing.overload
    def onPasswordSucceeded(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    @typing.overload
    def onPasswordSucceeded(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    def onProfileProvisioningComplete(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onReadyForUserInitialization(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onReceive(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onSecurityLogsAvailable(self, context: android.content.Context, intent: android.content.Intent) -> None: ...
    def onSystemUpdatePending(self, context: android.content.Context, intent: android.content.Intent, long: int) -> None: ...
    def onTransferAffiliatedProfileOwnershipComplete(self, context: android.content.Context, userHandle: android.os.UserHandle) -> None: ...
    def onTransferOwnershipComplete(self, context: android.content.Context, persistableBundle: android.os.PersistableBundle) -> None: ...
    def onUserAdded(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    def onUserRemoved(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    def onUserStarted(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    def onUserStopped(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...
    def onUserSwitched(self, context: android.content.Context, intent: android.content.Intent, userHandle: android.os.UserHandle) -> None: ...

class DeviceAdminService(android.app.Service):
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...

class DevicePolicyIdentifiers:
    ACCOUNT_MANAGEMENT_DISABLED_POLICY: typing.ClassVar[str] = ...
    APPLICATION_HIDDEN_POLICY: typing.ClassVar[str] = ...
    APPLICATION_RESTRICTIONS_POLICY: typing.ClassVar[str] = ...
    AUTO_TIMEZONE_POLICY: typing.ClassVar[str] = ...
    AUTO_TIME_POLICY: typing.ClassVar[str] = ...
    BACKUP_SERVICE_POLICY: typing.ClassVar[str] = ...
    CAMERA_DISABLED_POLICY: typing.ClassVar[str] = ...
    CONTENT_PROTECTION_POLICY: typing.ClassVar[str] = ...
    KEYGUARD_DISABLED_FEATURES_POLICY: typing.ClassVar[str] = ...
    LOCK_TASK_POLICY: typing.ClassVar[str] = ...
    PACKAGES_SUSPENDED_POLICY: typing.ClassVar[str] = ...
    PACKAGE_UNINSTALL_BLOCKED_POLICY: typing.ClassVar[str] = ...
    PASSWORD_COMPLEXITY_POLICY: typing.ClassVar[str] = ...
    PERMISSION_GRANT_POLICY: typing.ClassVar[str] = ...
    PERSISTENT_PREFERRED_ACTIVITY_POLICY: typing.ClassVar[str] = ...
    RESET_PASSWORD_TOKEN_POLICY: typing.ClassVar[str] = ...
    SECURITY_LOGGING_POLICY: typing.ClassVar[str] = ...
    STATUS_BAR_DISABLED_POLICY: typing.ClassVar[str] = ...
    USB_DATA_SIGNALING_POLICY: typing.ClassVar[str] = ...
    USER_CONTROL_DISABLED_PACKAGES_POLICY: typing.ClassVar[str] = ...
    @staticmethod
    def getIdentifierForUserRestriction(string: str) -> str: ...

class DevicePolicyManager:
    ACTION_ADD_DEVICE_ADMIN: typing.ClassVar[str] = ...
    ACTION_ADMIN_POLICY_COMPLIANCE: typing.ClassVar[str] = ...
    ACTION_APPLICATION_DELEGATION_SCOPES_CHANGED: typing.ClassVar[str] = ...
    ACTION_CHECK_POLICY_COMPLIANCE: typing.ClassVar[str] = ...
    ACTION_DEVICE_ADMIN_SERVICE: typing.ClassVar[str] = ...
    ACTION_DEVICE_FINANCING_STATE_CHANGED: typing.ClassVar[str] = ...
    ACTION_DEVICE_OWNER_CHANGED: typing.ClassVar[str] = ...
    ACTION_DEVICE_POLICY_RESOURCE_UPDATED: typing.ClassVar[str] = ...
    ACTION_GET_PROVISIONING_MODE: typing.ClassVar[str] = ...
    ACTION_MANAGED_PROFILE_PROVISIONED: typing.ClassVar[str] = ...
    ACTION_PROFILE_OWNER_CHANGED: typing.ClassVar[str] = ...
    ACTION_PROVISIONING_SUCCESSFUL: typing.ClassVar[str] = ...
    ACTION_PROVISION_MANAGED_DEVICE: typing.ClassVar[str] = ...
    ACTION_PROVISION_MANAGED_PROFILE: typing.ClassVar[str] = ...
    ACTION_SET_NEW_PARENT_PROFILE_PASSWORD: typing.ClassVar[str] = ...
    ACTION_SET_NEW_PASSWORD: typing.ClassVar[str] = ...
    ACTION_START_ENCRYPTION: typing.ClassVar[str] = ...
    ACTION_SYSTEM_UPDATE_POLICY_CHANGED: typing.ClassVar[str] = ...
    CONTENT_PROTECTION_DISABLED: typing.ClassVar[int] = ...
    CONTENT_PROTECTION_ENABLED: typing.ClassVar[int] = ...
    CONTENT_PROTECTION_NOT_CONTROLLED_BY_POLICY: typing.ClassVar[int] = ...
    DELEGATION_APP_RESTRICTIONS: typing.ClassVar[str] = ...
    DELEGATION_BLOCK_UNINSTALL: typing.ClassVar[str] = ...
    DELEGATION_CERT_INSTALL: typing.ClassVar[str] = ...
    DELEGATION_CERT_SELECTION: typing.ClassVar[str] = ...
    DELEGATION_ENABLE_SYSTEM_APP: typing.ClassVar[str] = ...
    DELEGATION_INSTALL_EXISTING_PACKAGE: typing.ClassVar[str] = ...
    DELEGATION_KEEP_UNINSTALLED_PACKAGES: typing.ClassVar[str] = ...
    DELEGATION_NETWORK_LOGGING: typing.ClassVar[str] = ...
    DELEGATION_PACKAGE_ACCESS: typing.ClassVar[str] = ...
    DELEGATION_PERMISSION_GRANT: typing.ClassVar[str] = ...
    DELEGATION_SECURITY_LOGGING: typing.ClassVar[str] = ...
    ENCRYPTION_STATUS_ACTIVATING: typing.ClassVar[int] = ...
    ENCRYPTION_STATUS_ACTIVE: typing.ClassVar[int] = ...
    ENCRYPTION_STATUS_ACTIVE_DEFAULT_KEY: typing.ClassVar[int] = ...
    ENCRYPTION_STATUS_ACTIVE_PER_USER: typing.ClassVar[int] = ...
    ENCRYPTION_STATUS_INACTIVE: typing.ClassVar[int] = ...
    ENCRYPTION_STATUS_UNSUPPORTED: typing.ClassVar[int] = ...
    EXTRA_ADD_EXPLANATION: typing.ClassVar[str] = ...
    EXTRA_DELEGATION_SCOPES: typing.ClassVar[str] = ...
    EXTRA_DEVICE_ADMIN: typing.ClassVar[str] = ...
    EXTRA_DEVICE_PASSWORD_REQUIREMENT_ONLY: typing.ClassVar[str] = ...
    EXTRA_PASSWORD_COMPLEXITY: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_ACCOUNT_TO_MIGRATE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_ADMIN_EXTRAS_BUNDLE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_ALLOWED_PROVISIONING_MODES: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_ALLOW_OFFLINE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_COMPONENT_NAME: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_MINIMUM_VERSION_CODE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_COOKIE_HEADER: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_NAME: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DISCLAIMERS: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DISCLAIMER_CONTENT: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_DISCLAIMER_HEADER: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_EMAIL_ADDRESS: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_IMEI: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_KEEP_ACCOUNT_ON_MIGRATION: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_KEEP_SCREEN_ON: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_LEAVE_ALL_SYSTEM_APPS_ENABLED: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_LOCALE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_LOCAL_TIME: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_LOGO_URI: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_MAIN_COLOR: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_MODE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_SENSORS_PERMISSION_GRANT_OPT_OUT: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_SERIAL_NUMBER: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_SHOULD_LAUNCH_RESULT_INTENT: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_SKIP_EDUCATION_SCREENS: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_SKIP_ENCRYPTION: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_SKIP_USER_CONSENT: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_TIME_ZONE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_USE_MOBILE_DATA: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_ANONYMOUS_IDENTITY: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_CA_CERTIFICATE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_DOMAIN: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_EAP_METHOD: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_HIDDEN: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_IDENTITY: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_PAC_URL: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_PASSWORD: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_PHASE2_AUTH: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_PROXY_BYPASS: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_PROXY_HOST: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_PROXY_PORT: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_SECURITY_TYPE: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_SSID: typing.ClassVar[str] = ...
    EXTRA_PROVISIONING_WIFI_USER_CERTIFICATE: typing.ClassVar[str] = ...
    EXTRA_RESOURCE_IDS: typing.ClassVar[str] = ...
    EXTRA_RESOURCE_TYPE: typing.ClassVar[str] = ...
    EXTRA_RESOURCE_TYPE_DRAWABLE: typing.ClassVar[int] = ...
    EXTRA_RESOURCE_TYPE_STRING: typing.ClassVar[int] = ...
    EXTRA_RESULT_LAUNCH_INTENT: typing.ClassVar[str] = ...
    FLAG_EVICT_CREDENTIAL_ENCRYPTION_KEY: typing.ClassVar[int] = ...
    FLAG_MANAGED_CAN_ACCESS_PARENT: typing.ClassVar[int] = ...
    FLAG_PARENT_CAN_ACCESS_MANAGED: typing.ClassVar[int] = ...
    ID_TYPE_BASE_INFO: typing.ClassVar[int] = ...
    ID_TYPE_IMEI: typing.ClassVar[int] = ...
    ID_TYPE_INDIVIDUAL_ATTESTATION: typing.ClassVar[int] = ...
    ID_TYPE_MEID: typing.ClassVar[int] = ...
    ID_TYPE_SERIAL: typing.ClassVar[int] = ...
    INSTALLKEY_REQUEST_CREDENTIALS_ACCESS: typing.ClassVar[int] = ...
    INSTALLKEY_SET_USER_SELECTABLE: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_BIOMETRICS: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_FACE: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_FEATURES_ALL: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_FEATURES_NONE: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_FINGERPRINT: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_IRIS: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_REMOTE_INPUT: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_SECURE_CAMERA: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_SECURE_NOTIFICATIONS: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_SHORTCUTS_ALL: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_TRUST_AGENTS: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_UNREDACTED_NOTIFICATIONS: typing.ClassVar[int] = ...
    KEYGUARD_DISABLE_WIDGETS_ALL: typing.ClassVar[int] = ...
    LEAVE_ALL_SYSTEM_APPS_ENABLED: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_BLOCK_ACTIVITY_START_IN_TASK: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_GLOBAL_ACTIONS: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_HOME: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_KEYGUARD: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_NONE: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_NOTIFICATIONS: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_OVERVIEW: typing.ClassVar[int] = ...
    LOCK_TASK_FEATURE_SYSTEM_INFO: typing.ClassVar[int] = ...
    MAKE_USER_EPHEMERAL: typing.ClassVar[int] = ...
    MIME_TYPE_PROVISIONING_NFC: typing.ClassVar[str] = ...
    MTE_DISABLED: typing.ClassVar[int] = ...
    MTE_ENABLED: typing.ClassVar[int] = ...
    MTE_NOT_CONTROLLED_BY_POLICY: typing.ClassVar[int] = ...
    NEARBY_STREAMING_DISABLED: typing.ClassVar[int] = ...
    NEARBY_STREAMING_ENABLED: typing.ClassVar[int] = ...
    NEARBY_STREAMING_NOT_CONTROLLED_BY_POLICY: typing.ClassVar[int] = ...
    NEARBY_STREAMING_SAME_MANAGED_ACCOUNT_ONLY: typing.ClassVar[int] = ...
    OPERATION_SAFETY_REASON_DRIVING_DISTRACTION: typing.ClassVar[int] = ...
    PASSWORD_COMPLEXITY_HIGH: typing.ClassVar[int] = ...
    PASSWORD_COMPLEXITY_LOW: typing.ClassVar[int] = ...
    PASSWORD_COMPLEXITY_MEDIUM: typing.ClassVar[int] = ...
    PASSWORD_COMPLEXITY_NONE: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_ALPHABETIC: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_ALPHANUMERIC: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_BIOMETRIC_WEAK: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_COMPLEX: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_NUMERIC: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_NUMERIC_COMPLEX: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_SOMETHING: typing.ClassVar[int] = ...
    PASSWORD_QUALITY_UNSPECIFIED: typing.ClassVar[int] = ...
    PERMISSION_GRANT_STATE_DEFAULT: typing.ClassVar[int] = ...
    PERMISSION_GRANT_STATE_DENIED: typing.ClassVar[int] = ...
    PERMISSION_GRANT_STATE_GRANTED: typing.ClassVar[int] = ...
    PERMISSION_POLICY_AUTO_DENY: typing.ClassVar[int] = ...
    PERMISSION_POLICY_AUTO_GRANT: typing.ClassVar[int] = ...
    PERMISSION_POLICY_PROMPT: typing.ClassVar[int] = ...
    PERSONAL_APPS_NOT_SUSPENDED: typing.ClassVar[int] = ...
    PERSONAL_APPS_SUSPENDED_EXPLICITLY: typing.ClassVar[int] = ...
    PERSONAL_APPS_SUSPENDED_PROFILE_TIMEOUT: typing.ClassVar[int] = ...
    POLICY_DISABLE_CAMERA: typing.ClassVar[str] = ...
    POLICY_DISABLE_SCREEN_CAPTURE: typing.ClassVar[str] = ...
    PRIVATE_DNS_MODE_OFF: typing.ClassVar[int] = ...
    PRIVATE_DNS_MODE_OPPORTUNISTIC: typing.ClassVar[int] = ...
    PRIVATE_DNS_MODE_PROVIDER_HOSTNAME: typing.ClassVar[int] = ...
    PRIVATE_DNS_MODE_UNKNOWN: typing.ClassVar[int] = ...
    PRIVATE_DNS_SET_ERROR_FAILURE_SETTING: typing.ClassVar[int] = ...
    PRIVATE_DNS_SET_ERROR_HOST_NOT_SERVING: typing.ClassVar[int] = ...
    PRIVATE_DNS_SET_NO_ERROR: typing.ClassVar[int] = ...
    PROVISIONING_MODE_FULLY_MANAGED_DEVICE: typing.ClassVar[int] = ...
    PROVISIONING_MODE_MANAGED_PROFILE: typing.ClassVar[int] = ...
    PROVISIONING_MODE_MANAGED_PROFILE_ON_PERSONAL_DEVICE: typing.ClassVar[int] = ...
    RESET_PASSWORD_DO_NOT_ASK_CREDENTIALS_ON_BOOT: typing.ClassVar[int] = ...
    RESET_PASSWORD_REQUIRE_ENTRY: typing.ClassVar[int] = ...
    SKIP_SETUP_WIZARD: typing.ClassVar[int] = ...
    WIFI_SECURITY_ENTERPRISE_192: typing.ClassVar[int] = ...
    WIFI_SECURITY_ENTERPRISE_EAP: typing.ClassVar[int] = ...
    WIFI_SECURITY_OPEN: typing.ClassVar[int] = ...
    WIFI_SECURITY_PERSONAL: typing.ClassVar[int] = ...
    WIPE_EUICC: typing.ClassVar[int] = ...
    WIPE_EXTERNAL_STORAGE: typing.ClassVar[int] = ...
    WIPE_RESET_PROTECTION_DATA: typing.ClassVar[int] = ...
    WIPE_SILENTLY: typing.ClassVar[int] = ...
    def acknowledgeDeviceCompliant(self) -> None: ...
    def addCrossProfileIntentFilter(self, componentName: android.content.ComponentName, intentFilter: android.content.IntentFilter, int2: int) -> None: ...
    def addCrossProfileWidgetProvider(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def addOverrideApn(self, componentName: android.content.ComponentName, apnSetting: android.telephony.data.ApnSetting) -> int: ...
    def addPersistentPreferredActivity(self, componentName: android.content.ComponentName, intentFilter: android.content.IntentFilter, componentName2: android.content.ComponentName) -> None: ...
    def addUserRestriction(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def addUserRestrictionGlobally(self, string: str) -> None: ...
    @typing.overload
    def bindDeviceAdminServiceAsUser(self, componentName: android.content.ComponentName, intent: android.content.Intent, serviceConnection: android.content.ServiceConnection, bindServiceFlags: android.content.Context.BindServiceFlags, userHandle: android.os.UserHandle) -> bool: ...
    @typing.overload
    def bindDeviceAdminServiceAsUser(self, componentName: android.content.ComponentName, intent: android.content.Intent, serviceConnection: android.content.ServiceConnection, int2: int, userHandle: android.os.UserHandle) -> bool: ...
    def canAdminGrantSensorsPermissions(self) -> bool: ...
    def canUsbDataSignalingBeDisabled(self) -> bool: ...
    def clearApplicationUserData(self, componentName: android.content.ComponentName, string: str, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], onClearApplicationUserDataListener: typing.Union['DevicePolicyManager.OnClearApplicationUserDataListener', typing.Callable]) -> None: ...
    def clearCrossProfileIntentFilters(self, componentName: android.content.ComponentName) -> None: ...
    def clearDeviceOwnerApp(self, string: str) -> None: ...
    def clearPackagePersistentPreferredActivities(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def clearProfileOwner(self, componentName: android.content.ComponentName) -> None: ...
    def clearResetPasswordToken(self, componentName: android.content.ComponentName) -> bool: ...
    def clearUserRestriction(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def createAdminSupportIntent(self, string: str) -> android.content.Intent: ...
    def createAndManageUser(self, componentName: android.content.ComponentName, string: str, componentName2: android.content.ComponentName, persistableBundle: android.os.PersistableBundle, int: int) -> android.os.UserHandle: ...
    @typing.overload
    def enableSystemApp(self, componentName: android.content.ComponentName, intent: android.content.Intent) -> int: ...
    @typing.overload
    def enableSystemApp(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def generateKeyPair(self, componentName: android.content.ComponentName, string: str, keyGenParameterSpec: android.security.keystore.KeyGenParameterSpec, int: int) -> android.security.AttestedKeyPair: ...
    def getAccountTypesWithManagementDisabled(self) -> typing.MutableSequence[str]: ...
    def getActiveAdmins(self) -> java.util.List[android.content.ComponentName]: ...
    def getAffiliationIds(self, componentName: android.content.ComponentName) -> java.util.Set[str]: ...
    def getAlwaysOnVpnLockdownWhitelist(self, componentName: android.content.ComponentName) -> java.util.Set[str]: ...
    def getAlwaysOnVpnPackage(self, componentName: android.content.ComponentName) -> str: ...
    def getApplicationRestrictions(self, componentName: android.content.ComponentName, string: str) -> android.os.Bundle: ...
    def getApplicationRestrictionsManagingPackage(self, componentName: android.content.ComponentName) -> str: ...
    def getAutoTimeEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getAutoTimeRequired(self) -> bool: ...
    def getAutoTimeZoneEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getBindDeviceAdminTargetUsers(self, componentName: android.content.ComponentName) -> java.util.List[android.os.UserHandle]: ...
    def getBluetoothContactSharingDisabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getCameraDisabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getCertInstallerPackage(self, componentName: android.content.ComponentName) -> str: ...
    def getContentProtectionPolicy(self, componentName: android.content.ComponentName) -> int: ...
    def getCredentialManagerPolicy(self) -> 'PackagePolicy': ...
    def getCrossProfileCalendarPackages(self, componentName: android.content.ComponentName) -> java.util.Set[str]: ...
    def getCrossProfileCallerIdDisabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getCrossProfileContactsSearchDisabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getCrossProfilePackages(self, componentName: android.content.ComponentName) -> java.util.Set[str]: ...
    def getCrossProfileWidgetProviders(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getCurrentFailedPasswordAttempts(self) -> int: ...
    def getDelegatePackages(self, componentName: android.content.ComponentName, string: str) -> java.util.List[str]: ...
    def getDelegatedScopes(self, componentName: android.content.ComponentName, string: str) -> java.util.List[str]: ...
    def getDeviceOwnerLockScreenInfo(self) -> java.lang.CharSequence: ...
    def getDevicePolicyManagementRoleHolderPackage(self) -> str: ...
    def getEndUserSessionMessage(self, componentName: android.content.ComponentName) -> java.lang.CharSequence: ...
    def getEnrollmentSpecificId(self) -> str: ...
    def getFactoryResetProtectionPolicy(self, componentName: android.content.ComponentName) -> 'FactoryResetProtectionPolicy': ...
    def getGlobalPrivateDnsHost(self, componentName: android.content.ComponentName) -> str: ...
    def getGlobalPrivateDnsMode(self, componentName: android.content.ComponentName) -> int: ...
    def getInstalledCaCerts(self, componentName: android.content.ComponentName) -> java.util.List[typing.MutableSequence[int]]: ...
    def getKeepUninstalledPackages(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getKeyPairGrants(self, string: str) -> java.util.Map[int, java.util.Set[str]]: ...
    def getKeyguardDisabledFeatures(self, componentName: android.content.ComponentName) -> int: ...
    def getLockTaskFeatures(self, componentName: android.content.ComponentName) -> int: ...
    def getLockTaskPackages(self, componentName: android.content.ComponentName) -> typing.MutableSequence[str]: ...
    def getLongSupportMessage(self, componentName: android.content.ComponentName) -> java.lang.CharSequence: ...
    def getManagedProfileCallerIdAccessPolicy(self) -> 'PackagePolicy': ...
    def getManagedProfileContactsAccessPolicy(self) -> 'PackagePolicy': ...
    def getManagedProfileMaximumTimeOff(self, componentName: android.content.ComponentName) -> int: ...
    def getManagedSubscriptionsPolicy(self) -> 'ManagedSubscriptionsPolicy': ...
    def getMaximumFailedPasswordsForWipe(self, componentName: android.content.ComponentName) -> int: ...
    def getMaximumTimeToLock(self, componentName: android.content.ComponentName) -> int: ...
    def getMeteredDataDisabledPackages(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getMinimumRequiredWifiSecurityLevel(self) -> int: ...
    def getMtePolicy(self) -> int: ...
    def getNearbyAppStreamingPolicy(self) -> int: ...
    def getNearbyNotificationStreamingPolicy(self) -> int: ...
    def getOrganizationColor(self, componentName: android.content.ComponentName) -> int: ...
    def getOrganizationName(self, componentName: android.content.ComponentName) -> java.lang.CharSequence: ...
    def getOverrideApns(self, componentName: android.content.ComponentName) -> java.util.List[android.telephony.data.ApnSetting]: ...
    def getParentProfileInstance(self, componentName: android.content.ComponentName) -> 'DevicePolicyManager': ...
    def getPasswordComplexity(self) -> int: ...
    def getPasswordExpiration(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordExpirationTimeout(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordHistoryLength(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMaximumLength(self, int: int) -> int: ...
    def getPasswordMinimumLength(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMinimumLetters(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMinimumLowerCase(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMinimumNonLetter(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMinimumNumeric(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMinimumSymbols(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordMinimumUpperCase(self, componentName: android.content.ComponentName) -> int: ...
    def getPasswordQuality(self, componentName: android.content.ComponentName) -> int: ...
    def getPendingSystemUpdate(self, componentName: android.content.ComponentName) -> 'SystemUpdateInfo': ...
    def getPermissionGrantState(self, componentName: android.content.ComponentName, string: str, string2: str) -> int: ...
    def getPermissionPolicy(self, componentName: android.content.ComponentName) -> int: ...
    def getPermittedAccessibilityServices(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getPermittedCrossProfileNotificationListeners(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getPermittedInputMethods(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getPersonalAppsSuspendedReasons(self, componentName: android.content.ComponentName) -> int: ...
    def getPreferentialNetworkServiceConfigs(self) -> java.util.List['PreferentialNetworkServiceConfig']: ...
    def getRequiredPasswordComplexity(self) -> int: ...
    def getRequiredStrongAuthTimeout(self, componentName: android.content.ComponentName) -> int: ...
    def getResources(self) -> 'DevicePolicyResourcesManager': ...
    def getScreenCaptureDisabled(self, componentName: android.content.ComponentName) -> bool: ...
    def getSecondaryUsers(self, componentName: android.content.ComponentName) -> java.util.List[android.os.UserHandle]: ...
    def getShortSupportMessage(self, componentName: android.content.ComponentName) -> java.lang.CharSequence: ...
    def getStartUserSessionMessage(self, componentName: android.content.ComponentName) -> java.lang.CharSequence: ...
    def getStorageEncryption(self, componentName: android.content.ComponentName) -> bool: ...
    def getStorageEncryptionStatus(self) -> int: ...
    def getSubscriptionIds(self) -> java.util.Set[int]: ...
    def getSystemUpdatePolicy(self) -> 'SystemUpdatePolicy': ...
    def getTransferOwnershipBundle(self) -> android.os.PersistableBundle: ...
    def getTrustAgentConfiguration(self, componentName: android.content.ComponentName, componentName2: android.content.ComponentName) -> java.util.List[android.os.PersistableBundle]: ...
    def getUserControlDisabledPackages(self, componentName: android.content.ComponentName) -> java.util.List[str]: ...
    def getUserRestrictions(self, componentName: android.content.ComponentName) -> android.os.Bundle: ...
    def getUserRestrictionsGlobally(self) -> android.os.Bundle: ...
    def getWifiMacAddress(self, componentName: android.content.ComponentName) -> str: ...
    def getWifiSsidPolicy(self) -> 'WifiSsidPolicy': ...
    def grantKeyPairToApp(self, componentName: android.content.ComponentName, string: str, string2: str) -> bool: ...
    def grantKeyPairToWifiAuth(self, string: str) -> bool: ...
    def hasCaCertInstalled(self, componentName: android.content.ComponentName, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> bool: ...
    def hasGrantedPolicy(self, componentName: android.content.ComponentName, int: int) -> bool: ...
    def hasKeyPair(self, string: str) -> bool: ...
    def hasLockdownAdminConfiguredNetworks(self, componentName: android.content.ComponentName) -> bool: ...
    def installCaCert(self, componentName: android.content.ComponentName, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> bool: ...
    def installExistingPackage(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    @typing.overload
    def installKeyPair(self, componentName: android.content.ComponentName, privateKey: java.security.PrivateKey, certificate: java.security.cert.Certificate, string: str) -> bool: ...
    @typing.overload
    def installKeyPair(self, componentName: android.content.ComponentName, privateKey: java.security.PrivateKey, certificateArray: typing.Union[typing.List[java.security.cert.Certificate], jpype.JArray], string: str, boolean: bool) -> bool: ...
    @typing.overload
    def installKeyPair(self, componentName: android.content.ComponentName, privateKey: java.security.PrivateKey, certificateArray: typing.Union[typing.List[java.security.cert.Certificate], jpype.JArray], string: str, int: int) -> bool: ...
    def installSystemUpdate(self, componentName: android.content.ComponentName, uri: android.net.Uri, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], installSystemUpdateCallback: 'DevicePolicyManager.InstallSystemUpdateCallback') -> None: ...
    def isActivePasswordSufficient(self) -> bool: ...
    def isActivePasswordSufficientForDeviceRequirement(self) -> bool: ...
    def isAdminActive(self, componentName: android.content.ComponentName) -> bool: ...
    def isAffiliatedUser(self) -> bool: ...
    def isAlwaysOnVpnLockdownEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def isApplicationHidden(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def isBackupServiceEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def isCallerApplicationRestrictionsManagingPackage(self) -> bool: ...
    def isCommonCriteriaModeEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def isComplianceAcknowledgementRequired(self) -> bool: ...
    def isDeviceFinanced(self) -> bool: ...
    def isDeviceIdAttestationSupported(self) -> bool: ...
    def isDeviceOwnerApp(self, string: str) -> bool: ...
    def isEphemeralUser(self, componentName: android.content.ComponentName) -> bool: ...
    def isKeyPairGrantedToWifiAuth(self, string: str) -> bool: ...
    def isLockTaskPermitted(self, string: str) -> bool: ...
    def isLogoutEnabled(self) -> bool: ...
    def isManagedProfile(self, componentName: android.content.ComponentName) -> bool: ...
    def isMasterVolumeMuted(self, componentName: android.content.ComponentName) -> bool: ...
    @staticmethod
    def isMtePolicyEnforced() -> bool: ...
    def isNetworkLoggingEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def isOrganizationOwnedDeviceWithManagedProfile(self) -> bool: ...
    def isOverrideApnEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def isPackageSuspended(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def isPreferentialNetworkServiceEnabled(self) -> bool: ...
    def isProfileOwnerApp(self, string: str) -> bool: ...
    def isProvisioningAllowed(self, string: str) -> bool: ...
    def isResetPasswordTokenActive(self, componentName: android.content.ComponentName) -> bool: ...
    def isSafeOperation(self, int: int) -> bool: ...
    def isSecurityLoggingEnabled(self, componentName: android.content.ComponentName) -> bool: ...
    def isStatusBarDisabled(self) -> bool: ...
    def isUninstallBlocked(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def isUniqueDeviceAttestationSupported(self) -> bool: ...
    def isUsbDataSignalingEnabled(self) -> bool: ...
    def isUsingUnifiedPassword(self, componentName: android.content.ComponentName) -> bool: ...
    def listForegroundAffiliatedUsers(self) -> java.util.List[android.os.UserHandle]: ...
    @typing.overload
    def lockNow(self) -> None: ...
    @typing.overload
    def lockNow(self, int: int) -> None: ...
    def logoutUser(self, componentName: android.content.ComponentName) -> int: ...
    def reboot(self, componentName: android.content.ComponentName) -> None: ...
    def removeActiveAdmin(self, componentName: android.content.ComponentName) -> None: ...
    def removeCrossProfileWidgetProvider(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def removeKeyPair(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def removeOverrideApn(self, componentName: android.content.ComponentName, int: int) -> bool: ...
    def removeUser(self, componentName: android.content.ComponentName, userHandle: android.os.UserHandle) -> bool: ...
    def requestBugreport(self, componentName: android.content.ComponentName) -> bool: ...
    def resetPassword(self, string: str, int: int) -> bool: ...
    def resetPasswordWithToken(self, componentName: android.content.ComponentName, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int) -> bool: ...
    def retrieveNetworkLogs(self, componentName: android.content.ComponentName, long: int) -> java.util.List['NetworkEvent']: ...
    def retrievePreRebootSecurityLogs(self, componentName: android.content.ComponentName) -> java.util.List['SecurityLog.SecurityEvent']: ...
    def retrieveSecurityLogs(self, componentName: android.content.ComponentName) -> java.util.List['SecurityLog.SecurityEvent']: ...
    def revokeKeyPairFromApp(self, componentName: android.content.ComponentName, string: str, string2: str) -> bool: ...
    def revokeKeyPairFromWifiAuth(self, string: str) -> bool: ...
    def setAccountManagementDisabled(self, componentName: android.content.ComponentName, string: str, boolean: bool) -> None: ...
    def setAffiliationIds(self, componentName: android.content.ComponentName, set: java.util.Set[str]) -> None: ...
    @typing.overload
    def setAlwaysOnVpnPackage(self, componentName: android.content.ComponentName, string: str, boolean: bool) -> None: ...
    @typing.overload
    def setAlwaysOnVpnPackage(self, componentName: android.content.ComponentName, string: str, boolean: bool, set: java.util.Set[str]) -> None: ...
    def setApplicationHidden(self, componentName: android.content.ComponentName, string: str, boolean: bool) -> bool: ...
    def setApplicationRestrictions(self, componentName: android.content.ComponentName, string: str, bundle: android.os.Bundle) -> None: ...
    def setApplicationRestrictionsManagingPackage(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def setAutoTimeEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setAutoTimeRequired(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setAutoTimeZoneEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setBackupServiceEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setBluetoothContactSharingDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setCameraDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setCertInstallerPackage(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def setCommonCriteriaModeEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setConfiguredNetworksLockdownState(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setContentProtectionPolicy(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setCredentialManagerPolicy(self, packagePolicy: 'PackagePolicy') -> None: ...
    def setCrossProfileCalendarPackages(self, componentName: android.content.ComponentName, set: java.util.Set[str]) -> None: ...
    def setCrossProfileCallerIdDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setCrossProfileContactsSearchDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setCrossProfilePackages(self, componentName: android.content.ComponentName, set: java.util.Set[str]) -> None: ...
    def setDefaultDialerApplication(self, string: str) -> None: ...
    def setDefaultSmsApplication(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def setDelegatedScopes(self, componentName: android.content.ComponentName, string: str, list: java.util.List[str]) -> None: ...
    def setDeviceOwnerLockScreenInfo(self, componentName: android.content.ComponentName, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setEndUserSessionMessage(self, componentName: android.content.ComponentName, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setFactoryResetProtectionPolicy(self, componentName: android.content.ComponentName, factoryResetProtectionPolicy: 'FactoryResetProtectionPolicy') -> None: ...
    def setGlobalPrivateDnsModeOpportunistic(self, componentName: android.content.ComponentName) -> int: ...
    def setGlobalPrivateDnsModeSpecifiedHost(self, componentName: android.content.ComponentName, string: str) -> int: ...
    def setGlobalSetting(self, componentName: android.content.ComponentName, string: str, string2: str) -> None: ...
    def setKeepUninstalledPackages(self, componentName: android.content.ComponentName, list: java.util.List[str]) -> None: ...
    def setKeyPairCertificate(self, componentName: android.content.ComponentName, string: str, list: java.util.List[java.security.cert.Certificate], boolean: bool) -> bool: ...
    def setKeyguardDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> bool: ...
    def setKeyguardDisabledFeatures(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setLocationEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setLockTaskFeatures(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setLockTaskPackages(self, componentName: android.content.ComponentName, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def setLogoutEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setLongSupportMessage(self, componentName: android.content.ComponentName, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setManagedProfileCallerIdAccessPolicy(self, packagePolicy: 'PackagePolicy') -> None: ...
    def setManagedProfileContactsAccessPolicy(self, packagePolicy: 'PackagePolicy') -> None: ...
    def setManagedProfileMaximumTimeOff(self, componentName: android.content.ComponentName, long: int) -> None: ...
    def setManagedSubscriptionsPolicy(self, managedSubscriptionsPolicy: 'ManagedSubscriptionsPolicy') -> None: ...
    def setMasterVolumeMuted(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setMaximumFailedPasswordsForWipe(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setMaximumTimeToLock(self, componentName: android.content.ComponentName, long: int) -> None: ...
    def setMeteredDataDisabledPackages(self, componentName: android.content.ComponentName, list: java.util.List[str]) -> java.util.List[str]: ...
    def setMinimumRequiredWifiSecurityLevel(self, int: int) -> None: ...
    def setMtePolicy(self, int: int) -> None: ...
    def setNearbyAppStreamingPolicy(self, int: int) -> None: ...
    def setNearbyNotificationStreamingPolicy(self, int: int) -> None: ...
    def setNetworkLoggingEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setOrganizationColor(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setOrganizationId(self, string: str) -> None: ...
    def setOrganizationName(self, componentName: android.content.ComponentName, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setOverrideApnsEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setPackagesSuspended(self, componentName: android.content.ComponentName, stringArray: typing.Union[typing.List[str], jpype.JArray], boolean: bool) -> typing.MutableSequence[str]: ...
    def setPasswordExpirationTimeout(self, componentName: android.content.ComponentName, long: int) -> None: ...
    def setPasswordHistoryLength(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumLength(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumLetters(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumLowerCase(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumNonLetter(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumNumeric(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumSymbols(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordMinimumUpperCase(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPasswordQuality(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPermissionGrantState(self, componentName: android.content.ComponentName, string: str, string2: str, int: int) -> bool: ...
    def setPermissionPolicy(self, componentName: android.content.ComponentName, int: int) -> None: ...
    def setPermittedAccessibilityServices(self, componentName: android.content.ComponentName, list: java.util.List[str]) -> bool: ...
    def setPermittedCrossProfileNotificationListeners(self, componentName: android.content.ComponentName, list: java.util.List[str]) -> bool: ...
    def setPermittedInputMethods(self, componentName: android.content.ComponentName, list: java.util.List[str]) -> bool: ...
    def setPersonalAppsSuspended(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setPreferentialNetworkServiceConfigs(self, list: java.util.List['PreferentialNetworkServiceConfig']) -> None: ...
    def setPreferentialNetworkServiceEnabled(self, boolean: bool) -> None: ...
    def setProfileEnabled(self, componentName: android.content.ComponentName) -> None: ...
    def setProfileName(self, componentName: android.content.ComponentName, string: str) -> None: ...
    def setRecommendedGlobalProxy(self, componentName: android.content.ComponentName, proxyInfo: android.net.ProxyInfo) -> None: ...
    def setRequiredPasswordComplexity(self, int: int) -> None: ...
    def setRequiredStrongAuthTimeout(self, componentName: android.content.ComponentName, long: int) -> None: ...
    def setResetPasswordToken(self, componentName: android.content.ComponentName, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> bool: ...
    def setRestrictionsProvider(self, componentName: android.content.ComponentName, componentName2: android.content.ComponentName) -> None: ...
    def setScreenCaptureDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setSecureSetting(self, componentName: android.content.ComponentName, string: str, string2: str) -> None: ...
    def setSecurityLoggingEnabled(self, componentName: android.content.ComponentName, boolean: bool) -> None: ...
    def setShortSupportMessage(self, componentName: android.content.ComponentName, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setStartUserSessionMessage(self, componentName: android.content.ComponentName, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setStatusBarDisabled(self, componentName: android.content.ComponentName, boolean: bool) -> bool: ...
    def setStorageEncryption(self, componentName: android.content.ComponentName, boolean: bool) -> int: ...
    def setSystemSetting(self, componentName: android.content.ComponentName, string: str, string2: str) -> None: ...
    def setSystemUpdatePolicy(self, componentName: android.content.ComponentName, systemUpdatePolicy: 'SystemUpdatePolicy') -> None: ...
    def setTime(self, componentName: android.content.ComponentName, long: int) -> bool: ...
    def setTimeZone(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def setTrustAgentConfiguration(self, componentName: android.content.ComponentName, componentName2: android.content.ComponentName, persistableBundle: android.os.PersistableBundle) -> None: ...
    def setUninstallBlocked(self, componentName: android.content.ComponentName, string: str, boolean: bool) -> None: ...
    def setUsbDataSignalingEnabled(self, boolean: bool) -> None: ...
    def setUserControlDisabledPackages(self, componentName: android.content.ComponentName, list: java.util.List[str]) -> None: ...
    def setUserIcon(self, componentName: android.content.ComponentName, bitmap: android.graphics.Bitmap) -> None: ...
    def setWifiSsidPolicy(self, wifiSsidPolicy: 'WifiSsidPolicy') -> None: ...
    def startUserInBackground(self, componentName: android.content.ComponentName, userHandle: android.os.UserHandle) -> int: ...
    def stopUser(self, componentName: android.content.ComponentName, userHandle: android.os.UserHandle) -> int: ...
    def switchUser(self, componentName: android.content.ComponentName, userHandle: android.os.UserHandle) -> bool: ...
    def transferOwnership(self, componentName: android.content.ComponentName, componentName2: android.content.ComponentName, persistableBundle: android.os.PersistableBundle) -> None: ...
    def uninstallAllUserCaCerts(self, componentName: android.content.ComponentName) -> None: ...
    def uninstallCaCert(self, componentName: android.content.ComponentName, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def updateOverrideApn(self, componentName: android.content.ComponentName, int: int, apnSetting: android.telephony.data.ApnSetting) -> bool: ...
    @typing.overload
    def wipeData(self, int: int) -> None: ...
    @typing.overload
    def wipeData(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def wipeDevice(self, int: int) -> None: ...
    class InstallSystemUpdateCallback:
        UPDATE_ERROR_BATTERY_LOW: typing.ClassVar[int] = ...
        UPDATE_ERROR_FILE_NOT_FOUND: typing.ClassVar[int] = ...
        UPDATE_ERROR_INCORRECT_OS_VERSION: typing.ClassVar[int] = ...
        UPDATE_ERROR_UNKNOWN: typing.ClassVar[int] = ...
        UPDATE_ERROR_UPDATE_FILE_INVALID: typing.ClassVar[int] = ...
        def __init__(self): ...
        def onInstallUpdateError(self, int: int, string: str) -> None: ...
    class OnClearApplicationUserDataListener:
        def onApplicationUserDataCleared(self, string: str, boolean: bool) -> None: ...

class DevicePolicyResources:
    UNDEFINED: typing.ClassVar[str] = ...

class DevicePolicyResourcesManager:
    @typing.overload
    def getDrawable(self, string: str, string2: str, string3: str, supplier: typing.Union[java.util.function.Supplier[android.graphics.drawable.Drawable], typing.Callable[[], android.graphics.drawable.Drawable]]) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getDrawable(self, string: str, string2: str, supplier: typing.Union[java.util.function.Supplier[android.graphics.drawable.Drawable], typing.Callable[[], android.graphics.drawable.Drawable]]) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getDrawableAsIcon(self, string: str, string2: str, icon: android.graphics.drawable.Icon) -> android.graphics.drawable.Icon: ...
    @typing.overload
    def getDrawableAsIcon(self, string: str, string2: str, string3: str, icon: android.graphics.drawable.Icon) -> android.graphics.drawable.Icon: ...
    @typing.overload
    def getDrawableForDensity(self, string: str, string2: str, int: int, supplier: typing.Union[java.util.function.Supplier[android.graphics.drawable.Drawable], typing.Callable[[], android.graphics.drawable.Drawable]]) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getDrawableForDensity(self, string: str, string2: str, string3: str, int: int, supplier: typing.Union[java.util.function.Supplier[android.graphics.drawable.Drawable], typing.Callable[[], android.graphics.drawable.Drawable]]) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def getString(self, string: str, supplier: typing.Union[java.util.function.Supplier[str], typing.Callable[[], str]]) -> str: ...
    @typing.overload
    def getString(self, string: str, supplier: typing.Union[java.util.function.Supplier[str], typing.Callable[[], str]], *object: typing.Any) -> str: ...

class FactoryResetProtectionPolicy(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getFactoryResetProtectionAccounts(self) -> java.util.List[str]: ...
    def isFactoryResetProtectionEnabled(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'FactoryResetProtectionPolicy': ...
        def setFactoryResetProtectionAccounts(self, list: java.util.List[str]) -> 'FactoryResetProtectionPolicy.Builder': ...
        def setFactoryResetProtectionEnabled(self, boolean: bool) -> 'FactoryResetProtectionPolicy.Builder': ...

class FreezePeriod:
    def __init__(self, monthDay: java.time.MonthDay, monthDay2: java.time.MonthDay): ...
    def getEnd(self) -> java.time.MonthDay: ...
    def getStart(self) -> java.time.MonthDay: ...
    def toString(self) -> str: ...

class ManagedSubscriptionsPolicy(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_ALL_MANAGED_SUBSCRIPTIONS: typing.ClassVar[int] = ...
    TYPE_ALL_PERSONAL_SUBSCRIPTIONS: typing.ClassVar[int] = ...
    def __init__(self, int: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPolicyType(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class NetworkEvent(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getId(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getTimestamp(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PackagePolicy(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PACKAGE_POLICY_ALLOWLIST: typing.ClassVar[int] = ...
    PACKAGE_POLICY_ALLOWLIST_AND_SYSTEM: typing.ClassVar[int] = ...
    PACKAGE_POLICY_BLOCKLIST: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, set: java.util.Set[str]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPackageNames(self) -> java.util.Set[str]: ...
    def getPolicyType(self) -> int: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PolicyUpdateReceiver(android.content.BroadcastReceiver):
    ACTION_DEVICE_POLICY_CHANGED: typing.ClassVar[str] = ...
    ACTION_DEVICE_POLICY_SET_RESULT: typing.ClassVar[str] = ...
    EXTRA_ACCOUNT_TYPE: typing.ClassVar[str] = ...
    EXTRA_INTENT_FILTER: typing.ClassVar[str] = ...
    EXTRA_PACKAGE_NAME: typing.ClassVar[str] = ...
    EXTRA_PERMISSION_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onPolicyChanged(self, context: android.content.Context, string: str, bundle: android.os.Bundle, targetUser: 'TargetUser', policyUpdateResult: 'PolicyUpdateResult') -> None: ...
    def onPolicySetResult(self, context: android.content.Context, string: str, bundle: android.os.Bundle, targetUser: 'TargetUser', policyUpdateResult: 'PolicyUpdateResult') -> None: ...
    def onReceive(self, context: android.content.Context, intent: android.content.Intent) -> None: ...

class PolicyUpdateResult:
    RESULT_FAILURE_CONFLICTING_ADMIN_POLICY: typing.ClassVar[int] = ...
    RESULT_FAILURE_HARDWARE_LIMITATION: typing.ClassVar[int] = ...
    RESULT_FAILURE_STORAGE_LIMIT_REACHED: typing.ClassVar[int] = ...
    RESULT_FAILURE_UNKNOWN: typing.ClassVar[int] = ...
    RESULT_POLICY_CLEARED: typing.ClassVar[int] = ...
    RESULT_POLICY_SET: typing.ClassVar[int] = ...
    def __init__(self, int: int): ...
    def getResultCode(self) -> int: ...

class PreferentialNetworkServiceConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    PREFERENTIAL_NETWORK_ID_1: typing.ClassVar[int] = ...
    PREFERENTIAL_NETWORK_ID_2: typing.ClassVar[int] = ...
    PREFERENTIAL_NETWORK_ID_3: typing.ClassVar[int] = ...
    PREFERENTIAL_NETWORK_ID_4: typing.ClassVar[int] = ...
    PREFERENTIAL_NETWORK_ID_5: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExcludedUids(self) -> typing.MutableSequence[int]: ...
    def getIncludedUids(self) -> typing.MutableSequence[int]: ...
    def getNetworkId(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEnabled(self) -> bool: ...
    def isFallbackToDefaultConnectionAllowed(self) -> bool: ...
    def shouldBlockNonMatchingNetworks(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'PreferentialNetworkServiceConfig': ...
        def setEnabled(self, boolean: bool) -> 'PreferentialNetworkServiceConfig.Builder': ...
        def setExcludedUids(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'PreferentialNetworkServiceConfig.Builder': ...
        def setFallbackToDefaultConnectionAllowed(self, boolean: bool) -> 'PreferentialNetworkServiceConfig.Builder': ...
        def setIncludedUids(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'PreferentialNetworkServiceConfig.Builder': ...
        def setNetworkId(self, int: int) -> 'PreferentialNetworkServiceConfig.Builder': ...
        def setShouldBlockNonMatchingNetworks(self, boolean: bool) -> 'PreferentialNetworkServiceConfig.Builder': ...

class SecurityLog:
    LEVEL_ERROR: typing.ClassVar[int] = ...
    LEVEL_INFO: typing.ClassVar[int] = ...
    LEVEL_WARNING: typing.ClassVar[int] = ...
    TAG_ADB_SHELL_CMD: typing.ClassVar[int] = ...
    TAG_ADB_SHELL_INTERACTIVE: typing.ClassVar[int] = ...
    TAG_APP_PROCESS_START: typing.ClassVar[int] = ...
    TAG_BACKUP_SERVICE_TOGGLED: typing.ClassVar[int] = ...
    TAG_BLUETOOTH_CONNECTION: typing.ClassVar[int] = ...
    TAG_BLUETOOTH_DISCONNECTION: typing.ClassVar[int] = ...
    TAG_CAMERA_POLICY_SET: typing.ClassVar[int] = ...
    TAG_CERT_AUTHORITY_INSTALLED: typing.ClassVar[int] = ...
    TAG_CERT_AUTHORITY_REMOVED: typing.ClassVar[int] = ...
    TAG_CERT_VALIDATION_FAILURE: typing.ClassVar[int] = ...
    TAG_CRYPTO_SELF_TEST_COMPLETED: typing.ClassVar[int] = ...
    TAG_KEYGUARD_DISABLED_FEATURES_SET: typing.ClassVar[int] = ...
    TAG_KEYGUARD_DISMISSED: typing.ClassVar[int] = ...
    TAG_KEYGUARD_DISMISS_AUTH_ATTEMPT: typing.ClassVar[int] = ...
    TAG_KEYGUARD_SECURED: typing.ClassVar[int] = ...
    TAG_KEY_DESTRUCTION: typing.ClassVar[int] = ...
    TAG_KEY_GENERATED: typing.ClassVar[int] = ...
    TAG_KEY_IMPORT: typing.ClassVar[int] = ...
    TAG_KEY_INTEGRITY_VIOLATION: typing.ClassVar[int] = ...
    TAG_LOGGING_STARTED: typing.ClassVar[int] = ...
    TAG_LOGGING_STOPPED: typing.ClassVar[int] = ...
    TAG_LOG_BUFFER_SIZE_CRITICAL: typing.ClassVar[int] = ...
    TAG_MAX_PASSWORD_ATTEMPTS_SET: typing.ClassVar[int] = ...
    TAG_MAX_SCREEN_LOCK_TIMEOUT_SET: typing.ClassVar[int] = ...
    TAG_MEDIA_MOUNT: typing.ClassVar[int] = ...
    TAG_MEDIA_UNMOUNT: typing.ClassVar[int] = ...
    TAG_OS_SHUTDOWN: typing.ClassVar[int] = ...
    TAG_OS_STARTUP: typing.ClassVar[int] = ...
    TAG_PACKAGE_INSTALLED: typing.ClassVar[int] = ...
    TAG_PACKAGE_UNINSTALLED: typing.ClassVar[int] = ...
    TAG_PACKAGE_UPDATED: typing.ClassVar[int] = ...
    TAG_PASSWORD_CHANGED: typing.ClassVar[int] = ...
    TAG_PASSWORD_COMPLEXITY_REQUIRED: typing.ClassVar[int] = ...
    TAG_PASSWORD_COMPLEXITY_SET: typing.ClassVar[int] = ...
    TAG_PASSWORD_EXPIRATION_SET: typing.ClassVar[int] = ...
    TAG_PASSWORD_HISTORY_LENGTH_SET: typing.ClassVar[int] = ...
    TAG_REMOTE_LOCK: typing.ClassVar[int] = ...
    TAG_SYNC_RECV_FILE: typing.ClassVar[int] = ...
    TAG_SYNC_SEND_FILE: typing.ClassVar[int] = ...
    TAG_USER_RESTRICTION_ADDED: typing.ClassVar[int] = ...
    TAG_USER_RESTRICTION_REMOVED: typing.ClassVar[int] = ...
    TAG_WIFI_CONNECTION: typing.ClassVar[int] = ...
    TAG_WIFI_DISCONNECTION: typing.ClassVar[int] = ...
    TAG_WIPE_FAILURE: typing.ClassVar[int] = ...
    def __init__(self): ...
    class SecurityEvent(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getData(self) -> typing.Any: ...
        def getId(self) -> int: ...
        def getLogLevel(self) -> int: ...
        def getTag(self) -> int: ...
        def getTimeNanos(self) -> int: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SystemUpdateInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SECURITY_PATCH_STATE_FALSE: typing.ClassVar[int] = ...
    SECURITY_PATCH_STATE_TRUE: typing.ClassVar[int] = ...
    SECURITY_PATCH_STATE_UNKNOWN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getReceivedTime(self) -> int: ...
    def getSecurityPatchState(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class SystemUpdatePolicy(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_INSTALL_AUTOMATIC: typing.ClassVar[int] = ...
    TYPE_INSTALL_WINDOWED: typing.ClassVar[int] = ...
    TYPE_POSTPONE: typing.ClassVar[int] = ...
    @staticmethod
    def createAutomaticInstallPolicy() -> 'SystemUpdatePolicy': ...
    @staticmethod
    def createPostponeInstallPolicy() -> 'SystemUpdatePolicy': ...
    @staticmethod
    def createWindowedInstallPolicy(int: int, int2: int) -> 'SystemUpdatePolicy': ...
    def describeContents(self) -> int: ...
    def getFreezePeriods(self) -> java.util.List[FreezePeriod]: ...
    def getInstallWindowEnd(self) -> int: ...
    def getInstallWindowStart(self) -> int: ...
    def getPolicyType(self) -> int: ...
    def setFreezePeriods(self, list: java.util.List[FreezePeriod]) -> 'SystemUpdatePolicy': ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class ValidationFailedException(java.lang.IllegalArgumentException, android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        ERROR_COMBINED_FREEZE_PERIOD_TOO_CLOSE: typing.ClassVar[int] = ...
        ERROR_COMBINED_FREEZE_PERIOD_TOO_LONG: typing.ClassVar[int] = ...
        ERROR_DUPLICATE_OR_OVERLAP: typing.ClassVar[int] = ...
        ERROR_NEW_FREEZE_PERIOD_TOO_CLOSE: typing.ClassVar[int] = ...
        ERROR_NEW_FREEZE_PERIOD_TOO_LONG: typing.ClassVar[int] = ...
        ERROR_UNKNOWN: typing.ClassVar[int] = ...
        def describeContents(self) -> int: ...
        def getErrorCode(self) -> int: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class TargetUser:
    GLOBAL: typing.ClassVar['TargetUser'] = ...
    LOCAL_USER: typing.ClassVar['TargetUser'] = ...
    PARENT_USER: typing.ClassVar['TargetUser'] = ...
    UNKNOWN_USER: typing.ClassVar['TargetUser'] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...

class UnsafeStateException(java.lang.IllegalStateException, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getMessage(self) -> str: ...
    def getReasons(self) -> java.util.List[int]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WifiSsidPolicy(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    WIFI_SSID_POLICY_TYPE_ALLOWLIST: typing.ClassVar[int] = ...
    WIFI_SSID_POLICY_TYPE_DENYLIST: typing.ClassVar[int] = ...
    def __init__(self, int: int, set: java.util.Set[android.net.wifi.WifiSsid]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPolicyType(self) -> int: ...
    def getSsids(self) -> java.util.Set[android.net.wifi.WifiSsid]: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class ConnectEvent(NetworkEvent, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getInetAddress(self) -> java.net.InetAddress: ...
    def getPort(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DnsEvent(NetworkEvent, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getHostname(self) -> str: ...
    def getInetAddresses(self) -> java.util.List[java.net.InetAddress]: ...
    def getTotalResolvedAddressCount(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.admin")``.

    ConnectEvent: typing.Type[ConnectEvent]
    DelegatedAdminReceiver: typing.Type[DelegatedAdminReceiver]
    DeviceAdminInfo: typing.Type[DeviceAdminInfo]
    DeviceAdminReceiver: typing.Type[DeviceAdminReceiver]
    DeviceAdminService: typing.Type[DeviceAdminService]
    DevicePolicyIdentifiers: typing.Type[DevicePolicyIdentifiers]
    DevicePolicyManager: typing.Type[DevicePolicyManager]
    DevicePolicyResources: typing.Type[DevicePolicyResources]
    DevicePolicyResourcesManager: typing.Type[DevicePolicyResourcesManager]
    DnsEvent: typing.Type[DnsEvent]
    FactoryResetProtectionPolicy: typing.Type[FactoryResetProtectionPolicy]
    FreezePeriod: typing.Type[FreezePeriod]
    ManagedSubscriptionsPolicy: typing.Type[ManagedSubscriptionsPolicy]
    NetworkEvent: typing.Type[NetworkEvent]
    PackagePolicy: typing.Type[PackagePolicy]
    PolicyUpdateReceiver: typing.Type[PolicyUpdateReceiver]
    PolicyUpdateResult: typing.Type[PolicyUpdateResult]
    PreferentialNetworkServiceConfig: typing.Type[PreferentialNetworkServiceConfig]
    SecurityLog: typing.Type[SecurityLog]
    SystemUpdateInfo: typing.Type[SystemUpdateInfo]
    SystemUpdatePolicy: typing.Type[SystemUpdatePolicy]
    TargetUser: typing.Type[TargetUser]
    UnsafeStateException: typing.Type[UnsafeStateException]
    WifiSsidPolicy: typing.Type[WifiSsidPolicy]
