
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.graphics.pdf.content
import android.graphics.pdf.models
import android.graphics.pdf.models.selection
import android.os
import java.io
import java.lang
import java.util
import jpype
import typing



class LoadParams:
    def getPassword(self) -> str: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'LoadParams': ...
        def setPassword(self, string: str) -> 'LoadParams.Builder': ...

class PdfDocument:
    def __init__(self): ...
    def close(self) -> None: ...
    def finishPage(self, page: 'PdfDocument.Page') -> None: ...
    def getPages(self) -> java.util.List['PdfDocument.PageInfo']: ...
    def startPage(self, pageInfo: 'PdfDocument.PageInfo') -> 'PdfDocument.Page': ...
    def writeTo(self, outputStream: java.io.OutputStream) -> None: ...
    class Page:
        def getCanvas(self) -> android.graphics.Canvas: ...
        def getInfo(self) -> 'PdfDocument.PageInfo': ...
    class PageInfo:
        def getContentRect(self) -> android.graphics.Rect: ...
        def getPageHeight(self) -> int: ...
        def getPageNumber(self) -> int: ...
        def getPageWidth(self) -> int: ...
        class Builder:
            def __init__(self, int: int, int2: int, int3: int): ...
            def create(self) -> 'PdfDocument.PageInfo': ...
            def setContentRect(self, rect: android.graphics.Rect) -> 'PdfDocument.PageInfo.Builder': ...

class PdfRenderer(java.lang.AutoCloseable):
    DOCUMENT_LINEARIZED_TYPE_LINEARIZED: typing.ClassVar[int] = ...
    DOCUMENT_LINEARIZED_TYPE_NON_LINEARIZED: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_ACRO_FORM: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_NONE: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_XFA_FOREGROUND: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_XFA_FULL: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, parcelFileDescriptor: android.os.ParcelFileDescriptor): ...
    @typing.overload
    def __init__(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, loadParams: LoadParams): ...
    def close(self) -> None: ...
    def getDocumentLinearizationType(self) -> int: ...
    def getPageCount(self) -> int: ...
    def getPdfFormType(self) -> int: ...
    def openPage(self, int: int) -> 'PdfRenderer.Page': ...
    def shouldScaleForPrinting(self) -> bool: ...
    def write(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, boolean: bool) -> None: ...
    class Page(java.lang.AutoCloseable):
        RENDER_MODE_FOR_DISPLAY: typing.ClassVar[int] = ...
        RENDER_MODE_FOR_PRINT: typing.ClassVar[int] = ...
        def applyEdit(self, formEditRecord: android.graphics.pdf.models.FormEditRecord) -> java.util.List[android.graphics.Rect]: ...
        def close(self) -> None: ...
        def getFormWidgetInfoAtIndex(self, int: int) -> android.graphics.pdf.models.FormWidgetInfo: ...
        def getFormWidgetInfoAtPosition(self, int: int, int2: int) -> android.graphics.pdf.models.FormWidgetInfo: ...
        @typing.overload
        def getFormWidgetInfos(self) -> java.util.List[android.graphics.pdf.models.FormWidgetInfo]: ...
        @typing.overload
        def getFormWidgetInfos(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> java.util.List[android.graphics.pdf.models.FormWidgetInfo]: ...
        def getGotoLinks(self) -> java.util.List[android.graphics.pdf.content.PdfPageGotoLinkContent]: ...
        def getHeight(self) -> int: ...
        def getImageContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageImageContent]: ...
        def getIndex(self) -> int: ...
        def getLinkContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageLinkContent]: ...
        def getTextContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageTextContent]: ...
        def getWidth(self) -> int: ...
        @typing.overload
        def render(self, bitmap: android.graphics.Bitmap, rect: android.graphics.Rect, matrix: android.graphics.Matrix, renderParams: 'RenderParams') -> None: ...
        @typing.overload
        def render(self, bitmap: android.graphics.Bitmap, rect: android.graphics.Rect, matrix: android.graphics.Matrix, int: int) -> None: ...
        def searchText(self, string: str) -> java.util.List[android.graphics.pdf.models.PageMatchBounds]: ...
        def selectContent(self, selectionBoundary: android.graphics.pdf.models.selection.SelectionBoundary, selectionBoundary2: android.graphics.pdf.models.selection.SelectionBoundary) -> android.graphics.pdf.models.selection.PageSelection: ...

class PdfRendererPreV(java.lang.AutoCloseable):
    DOCUMENT_LINEARIZED_TYPE_LINEARIZED: typing.ClassVar[int] = ...
    DOCUMENT_LINEARIZED_TYPE_NON_LINEARIZED: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_ACRO_FORM: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_NONE: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_XFA_FOREGROUND: typing.ClassVar[int] = ...
    PDF_FORM_TYPE_XFA_FULL: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, parcelFileDescriptor: android.os.ParcelFileDescriptor): ...
    @typing.overload
    def __init__(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, loadParams: LoadParams): ...
    def close(self) -> None: ...
    def getDocumentLinearizationType(self) -> int: ...
    def getPageCount(self) -> int: ...
    def getPdfFormType(self) -> int: ...
    def openPage(self, int: int) -> 'PdfRendererPreV.Page': ...
    def write(self, parcelFileDescriptor: android.os.ParcelFileDescriptor, boolean: bool) -> None: ...
    class Page(java.lang.AutoCloseable):
        def applyEdit(self, formEditRecord: android.graphics.pdf.models.FormEditRecord) -> java.util.List[android.graphics.Rect]: ...
        def close(self) -> None: ...
        def getFormWidgetInfoAtIndex(self, int: int) -> android.graphics.pdf.models.FormWidgetInfo: ...
        def getFormWidgetInfoAtPosition(self, int: int, int2: int) -> android.graphics.pdf.models.FormWidgetInfo: ...
        @typing.overload
        def getFormWidgetInfos(self) -> java.util.List[android.graphics.pdf.models.FormWidgetInfo]: ...
        @typing.overload
        def getFormWidgetInfos(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> java.util.List[android.graphics.pdf.models.FormWidgetInfo]: ...
        def getGotoLinks(self) -> java.util.List[android.graphics.pdf.content.PdfPageGotoLinkContent]: ...
        def getHeight(self) -> int: ...
        def getImageContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageImageContent]: ...
        def getIndex(self) -> int: ...
        def getLinkContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageLinkContent]: ...
        def getTextContents(self) -> java.util.List[android.graphics.pdf.content.PdfPageTextContent]: ...
        def getWidth(self) -> int: ...
        def render(self, bitmap: android.graphics.Bitmap, rect: android.graphics.Rect, matrix: android.graphics.Matrix, renderParams: 'RenderParams') -> None: ...
        def searchText(self, string: str) -> java.util.List[android.graphics.pdf.models.PageMatchBounds]: ...
        def selectContent(self, selectionBoundary: android.graphics.pdf.models.selection.SelectionBoundary, selectionBoundary2: android.graphics.pdf.models.selection.SelectionBoundary) -> android.graphics.pdf.models.selection.PageSelection: ...

class RenderParams:
    FLAG_RENDER_HIGHLIGHT_ANNOTATIONS: typing.ClassVar[int] = ...
    FLAG_RENDER_TEXT_ANNOTATIONS: typing.ClassVar[int] = ...
    RENDER_MODE_FOR_DISPLAY: typing.ClassVar[int] = ...
    RENDER_MODE_FOR_PRINT: typing.ClassVar[int] = ...
    def getRenderFlags(self) -> int: ...
    def getRenderMode(self) -> int: ...
    class Builder:
        def __init__(self, int: int): ...
        def build(self) -> 'RenderParams': ...
        @typing.overload
        def setRenderFlags(self, int: int) -> 'RenderParams.Builder': ...
        @typing.overload
        def setRenderFlags(self, int: int, int2: int) -> 'RenderParams.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.graphics.pdf")``.

    LoadParams: typing.Type[LoadParams]
    PdfDocument: typing.Type[PdfDocument]
    PdfRenderer: typing.Type[PdfRenderer]
    PdfRendererPreV: typing.Type[PdfRendererPreV]
    RenderParams: typing.Type[RenderParams]
    content: android.graphics.pdf.content.__module_protocol__
    models: android.graphics.pdf.models.__module_protocol__
