
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.graphics
import android.graphics.pdf.models.selection
import android.os
import java.util
import jpype
import typing



class FormEditRecord(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EDIT_TYPE_CLICK: typing.ClassVar[int] = ...
    EDIT_TYPE_SET_INDICES: typing.ClassVar[int] = ...
    EDIT_TYPE_SET_TEXT: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getClickPoint(self) -> android.graphics.Point: ...
    def getPageNumber(self) -> int: ...
    def getSelectedIndices(self) -> typing.MutableSequence[int]: ...
    def getText(self) -> str: ...
    def getType(self) -> int: ...
    def getWidgetIndex(self) -> int: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, int2: int, int3: int): ...
        def build(self) -> 'FormEditRecord': ...
        def setClickPoint(self, point: android.graphics.Point) -> 'FormEditRecord.Builder': ...
        def setSelectedIndices(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'FormEditRecord.Builder': ...
        def setText(self, string: str) -> 'FormEditRecord.Builder': ...

class FormWidgetInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    WIDGET_TYPE_CHECKBOX: typing.ClassVar[int] = ...
    WIDGET_TYPE_COMBOBOX: typing.ClassVar[int] = ...
    WIDGET_TYPE_LISTBOX: typing.ClassVar[int] = ...
    WIDGET_TYPE_PUSHBUTTON: typing.ClassVar[int] = ...
    WIDGET_TYPE_RADIOBUTTON: typing.ClassVar[int] = ...
    WIDGET_TYPE_SIGNATURE: typing.ClassVar[int] = ...
    WIDGET_TYPE_TEXTFIELD: typing.ClassVar[int] = ...
    WIDGET_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAccessibilityLabel(self) -> str: ...
    def getFontSize(self) -> float: ...
    def getListItems(self) -> java.util.List['ListItem']: ...
    def getMaxLength(self) -> int: ...
    def getTextValue(self) -> str: ...
    def getWidgetIndex(self) -> int: ...
    def getWidgetRect(self) -> android.graphics.Rect: ...
    def getWidgetType(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEditableText(self) -> bool: ...
    def isMultiLineText(self) -> bool: ...
    def isMultiSelect(self) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, int2: int, rect: android.graphics.Rect, string: str, string2: str): ...
        def build(self) -> 'FormWidgetInfo': ...
        def setEditableText(self, boolean: bool) -> 'FormWidgetInfo.Builder': ...
        def setFontSize(self, float: float) -> 'FormWidgetInfo.Builder': ...
        def setListItems(self, list: java.util.List['ListItem']) -> 'FormWidgetInfo.Builder': ...
        def setMaxLength(self, int: int) -> 'FormWidgetInfo.Builder': ...
        def setMultiLineText(self, boolean: bool) -> 'FormWidgetInfo.Builder': ...
        def setMultiSelect(self, boolean: bool) -> 'FormWidgetInfo.Builder': ...
        def setReadOnly(self, boolean: bool) -> 'FormWidgetInfo.Builder': ...

class ListItem(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, boolean: bool): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getLabel(self) -> str: ...
    def hashCode(self) -> int: ...
    def isSelected(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PageMatchBounds(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, list: java.util.List[android.graphics.RectF], int: int): ...
    def describeContents(self) -> int: ...
    def getBounds(self) -> java.util.List[android.graphics.RectF]: ...
    def getTextStartIndex(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.graphics.pdf.models")``.

    FormEditRecord: typing.Type[FormEditRecord]
    FormWidgetInfo: typing.Type[FormWidgetInfo]
    ListItem: typing.Type[ListItem]
    PageMatchBounds: typing.Type[PageMatchBounds]
    selection: android.graphics.pdf.models.selection.__module_protocol__
