
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import typing



class RoleManager:
    ROLE_ASSISTANT: typing.ClassVar[str] = ...
    ROLE_BROWSER: typing.ClassVar[str] = ...
    ROLE_CALL_REDIRECTION: typing.ClassVar[str] = ...
    ROLE_CALL_SCREENING: typing.ClassVar[str] = ...
    ROLE_DIALER: typing.ClassVar[str] = ...
    ROLE_EMERGENCY: typing.ClassVar[str] = ...
    ROLE_HOME: typing.ClassVar[str] = ...
    ROLE_NOTES: typing.ClassVar[str] = ...
    ROLE_SMS: typing.ClassVar[str] = ...
    ROLE_WALLET: typing.ClassVar[str] = ...
    def createRequestRoleIntent(self, string: str) -> android.content.Intent: ...
    def isRoleAvailable(self, string: str) -> bool: ...
    def isRoleHeld(self, string: str) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.role")``.

    RoleManager: typing.Type[RoleManager]
