
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.nfc
import android.os
import java.lang
import java.util
import jpype
import typing



class CardEmulation:
    ACTION_CHANGE_DEFAULT: typing.ClassVar[str] = ...
    CATEGORY_OTHER: typing.ClassVar[str] = ...
    CATEGORY_PAYMENT: typing.ClassVar[str] = ...
    EXTRA_CATEGORY: typing.ClassVar[str] = ...
    EXTRA_SERVICE_COMPONENT: typing.ClassVar[str] = ...
    SELECTION_MODE_ALWAYS_ASK: typing.ClassVar[int] = ...
    SELECTION_MODE_ASK_IF_CONFLICT: typing.ClassVar[int] = ...
    SELECTION_MODE_PREFER_DEFAULT: typing.ClassVar[int] = ...
    def categoryAllowsForegroundPreference(self, string: str) -> bool: ...
    def getAidsForPreferredPaymentService(self) -> java.util.List[str]: ...
    def getAidsForService(self, componentName: android.content.ComponentName, string: str) -> java.util.List[str]: ...
    def getDescriptionForPreferredPaymentService(self) -> java.lang.CharSequence: ...
    @staticmethod
    def getInstance(nfcAdapter: android.nfc.NfcAdapter) -> 'CardEmulation': ...
    def getRouteDestinationForPreferredPaymentService(self) -> str: ...
    def getSelectionModeForCategory(self, string: str) -> int: ...
    def isDefaultServiceForAid(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def isDefaultServiceForCategory(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def registerAidsForService(self, componentName: android.content.ComponentName, string: str, list: java.util.List[str]) -> bool: ...
    def registerPollingLoopFilterForService(self, componentName: android.content.ComponentName, string: str, boolean: bool) -> bool: ...
    def registerPollingLoopPatternFilterForService(self, componentName: android.content.ComponentName, string: str, boolean: bool) -> bool: ...
    def removeAidsForService(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def removePollingLoopFilterForService(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def removePollingLoopPatternFilterForService(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def setOffHostForService(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def setPreferredService(self, activity: android.app.Activity, componentName: android.content.ComponentName) -> bool: ...
    def setShouldDefaultToObserveModeForService(self, componentName: android.content.ComponentName, boolean: bool) -> bool: ...
    def supportsAidPrefixRegistration(self) -> bool: ...
    def unsetOffHostForService(self, componentName: android.content.ComponentName) -> bool: ...
    def unsetPreferredService(self, activity: android.app.Activity) -> bool: ...

class HostApduService(android.app.Service):
    DEACTIVATION_DESELECTED: typing.ClassVar[int] = ...
    DEACTIVATION_LINK_LOSS: typing.ClassVar[int] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def notifyUnhandled(self) -> None: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onDeactivated(self, int: int) -> None: ...
    def processCommandApdu(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], bundle: android.os.Bundle) -> typing.MutableSequence[int]: ...
    def processPollingFrames(self, list: java.util.List['PollingFrame']) -> None: ...
    def sendResponseApdu(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class HostNfcFService(android.app.Service):
    DEACTIVATION_LINK_LOSS: typing.ClassVar[int] = ...
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onDeactivated(self, int: int) -> None: ...
    def processNfcFPacket(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], bundle: android.os.Bundle) -> typing.MutableSequence[int]: ...
    def sendResponsePacket(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...

class NfcFCardEmulation:
    def disableService(self, activity: android.app.Activity) -> bool: ...
    def enableService(self, activity: android.app.Activity, componentName: android.content.ComponentName) -> bool: ...
    @staticmethod
    def getInstance(nfcAdapter: android.nfc.NfcAdapter) -> 'NfcFCardEmulation': ...
    def getNfcid2ForService(self, componentName: android.content.ComponentName) -> str: ...
    def getSystemCodeForService(self, componentName: android.content.ComponentName) -> str: ...
    def registerSystemCodeForService(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def setNfcid2ForService(self, componentName: android.content.ComponentName, string: str) -> bool: ...
    def unregisterSystemCodeForService(self, componentName: android.content.ComponentName) -> bool: ...

class OffHostApduService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...

class PollingFrame(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    POLLING_LOOP_TYPE_A: typing.ClassVar[int] = ...
    POLLING_LOOP_TYPE_B: typing.ClassVar[int] = ...
    POLLING_LOOP_TYPE_F: typing.ClassVar[int] = ...
    POLLING_LOOP_TYPE_OFF: typing.ClassVar[int] = ...
    POLLING_LOOP_TYPE_ON: typing.ClassVar[int] = ...
    POLLING_LOOP_TYPE_UNKNOWN: typing.ClassVar[int] = ...
    def describeContents(self) -> int: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getTimestamp(self) -> int: ...
    def getTriggeredAutoTransact(self) -> bool: ...
    def getType(self) -> int: ...
    def getVendorSpecificGain(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.nfc.cardemulation")``.

    CardEmulation: typing.Type[CardEmulation]
    HostApduService: typing.Type[HostApduService]
    HostNfcFService: typing.Type[HostNfcFService]
    NfcFCardEmulation: typing.Type[NfcFCardEmulation]
    OffHostApduService: typing.Type[OffHostApduService]
    PollingFrame: typing.Type[PollingFrame]
