
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.animation
import android.content
import android.graphics
import android.util
import android.view
import java.lang
import java.util
import typing



class PathMotion:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def getPath(self, float: float, float2: float, float3: float, float4: float) -> android.graphics.Path: ...

class Scene:
    @typing.overload
    def __init__(self, viewGroup: android.view.ViewGroup): ...
    @typing.overload
    def __init__(self, viewGroup: android.view.ViewGroup, view2: android.view.View): ...
    @typing.overload
    def __init__(self, viewGroup: android.view.ViewGroup, viewGroup2: android.view.ViewGroup): ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    @staticmethod
    def getCurrentScene(viewGroup: android.view.ViewGroup) -> 'Scene': ...
    @staticmethod
    def getSceneForLayout(viewGroup: android.view.ViewGroup, int: int, context: android.content.Context) -> 'Scene': ...
    def getSceneRoot(self) -> android.view.ViewGroup: ...
    def setEnterAction(self, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> None: ...
    def setExitAction(self, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> None: ...

class Transition(java.lang.Cloneable):
    MATCH_ID: typing.ClassVar[int] = ...
    MATCH_INSTANCE: typing.ClassVar[int] = ...
    MATCH_ITEM_ID: typing.ClassVar[int] = ...
    MATCH_NAME: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def addListener(self, transitionListener: 'Transition.TransitionListener') -> 'Transition': ...
    @typing.overload
    def addTarget(self, view: android.view.View) -> 'Transition': ...
    @typing.overload
    def addTarget(self, int: int) -> 'Transition': ...
    @typing.overload
    def addTarget(self, class_: typing.Type) -> 'Transition': ...
    @typing.overload
    def addTarget(self, string: str) -> 'Transition': ...
    def canRemoveViews(self) -> bool: ...
    def captureEndValues(self, transitionValues: 'TransitionValues') -> None: ...
    def captureStartValues(self, transitionValues: 'TransitionValues') -> None: ...
    def clone(self) -> 'Transition': ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: 'TransitionValues', transitionValues2: 'TransitionValues') -> android.animation.Animator: ...
    @typing.overload
    def excludeChildren(self, view: android.view.View, boolean: bool) -> 'Transition': ...
    @typing.overload
    def excludeChildren(self, int: int, boolean: bool) -> 'Transition': ...
    @typing.overload
    def excludeChildren(self, class_: typing.Type, boolean: bool) -> 'Transition': ...
    @typing.overload
    def excludeTarget(self, view: android.view.View, boolean: bool) -> 'Transition': ...
    @typing.overload
    def excludeTarget(self, int: int, boolean: bool) -> 'Transition': ...
    @typing.overload
    def excludeTarget(self, class_: typing.Type, boolean: bool) -> 'Transition': ...
    @typing.overload
    def excludeTarget(self, string: str, boolean: bool) -> 'Transition': ...
    def getDuration(self) -> int: ...
    def getEpicenter(self) -> android.graphics.Rect: ...
    def getEpicenterCallback(self) -> 'Transition.EpicenterCallback': ...
    def getInterpolator(self) -> android.animation.TimeInterpolator: ...
    def getName(self) -> str: ...
    def getPathMotion(self) -> PathMotion: ...
    def getPropagation(self) -> 'TransitionPropagation': ...
    def getStartDelay(self) -> int: ...
    def getTargetIds(self) -> java.util.List[int]: ...
    def getTargetNames(self) -> java.util.List[str]: ...
    def getTargetTypes(self) -> java.util.List[typing.Type]: ...
    def getTargets(self) -> java.util.List[android.view.View]: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...
    def getTransitionValues(self, view: android.view.View, boolean: bool) -> 'TransitionValues': ...
    def isTransitionRequired(self, transitionValues: 'TransitionValues', transitionValues2: 'TransitionValues') -> bool: ...
    def removeListener(self, transitionListener: 'Transition.TransitionListener') -> 'Transition': ...
    @typing.overload
    def removeTarget(self, view: android.view.View) -> 'Transition': ...
    @typing.overload
    def removeTarget(self, int: int) -> 'Transition': ...
    @typing.overload
    def removeTarget(self, class_: typing.Type) -> 'Transition': ...
    @typing.overload
    def removeTarget(self, string: str) -> 'Transition': ...
    def setDuration(self, long: int) -> 'Transition': ...
    def setEpicenterCallback(self, epicenterCallback: 'Transition.EpicenterCallback') -> None: ...
    def setInterpolator(self, timeInterpolator: typing.Union[android.animation.TimeInterpolator, typing.Callable]) -> 'Transition': ...
    def setMatchOrder(self, *int: int) -> None: ...
    def setPathMotion(self, pathMotion: PathMotion) -> None: ...
    def setPropagation(self, transitionPropagation: 'TransitionPropagation') -> None: ...
    def setStartDelay(self, long: int) -> 'Transition': ...
    def toString(self) -> str: ...
    class EpicenterCallback:
        def __init__(self): ...
        def onGetEpicenter(self, transition: 'Transition') -> android.graphics.Rect: ...
    class TransitionListener:
        def onTransitionCancel(self, transition: 'Transition') -> None: ...
        def onTransitionEnd(self, transition: 'Transition') -> None: ...
        def onTransitionPause(self, transition: 'Transition') -> None: ...
        def onTransitionResume(self, transition: 'Transition') -> None: ...
        def onTransitionStart(self, transition: 'Transition') -> None: ...

class TransitionInflater:
    @staticmethod
    def from_(context: android.content.Context) -> 'TransitionInflater': ...
    def inflateTransition(self, int: int) -> Transition: ...
    def inflateTransitionManager(self, int: int, viewGroup: android.view.ViewGroup) -> 'TransitionManager': ...

class TransitionManager:
    def __init__(self): ...
    @typing.overload
    @staticmethod
    def beginDelayedTransition(viewGroup: android.view.ViewGroup) -> None: ...
    @typing.overload
    @staticmethod
    def beginDelayedTransition(viewGroup: android.view.ViewGroup, transition: Transition) -> None: ...
    @staticmethod
    def endTransitions(viewGroup: android.view.ViewGroup) -> None: ...
    @typing.overload
    @staticmethod
    def go(scene: Scene) -> None: ...
    @typing.overload
    @staticmethod
    def go(scene: Scene, transition: Transition) -> None: ...
    @typing.overload
    def setTransition(self, scene: Scene, scene2: Scene, transition: Transition) -> None: ...
    @typing.overload
    def setTransition(self, scene: Scene, transition: Transition) -> None: ...
    def transitionTo(self, scene: Scene) -> None: ...

class TransitionPropagation:
    def __init__(self): ...
    def captureValues(self, transitionValues: 'TransitionValues') -> None: ...
    def getPropagationProperties(self) -> typing.MutableSequence[str]: ...
    def getStartDelay(self, viewGroup: android.view.ViewGroup, transition: Transition, transitionValues: 'TransitionValues', transitionValues2: 'TransitionValues') -> int: ...

class TransitionValues:
    values: java.util.Map = ...
    view: android.view.View = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, view: android.view.View): ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ArcMotion(PathMotion):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def getMaximumAngle(self) -> float: ...
    def getMinimumHorizontalAngle(self) -> float: ...
    def getMinimumVerticalAngle(self) -> float: ...
    def getPath(self, float: float, float2: float, float3: float, float4: float) -> android.graphics.Path: ...
    def setMaximumAngle(self, float: float) -> None: ...
    def setMinimumHorizontalAngle(self, float: float) -> None: ...
    def setMinimumVerticalAngle(self, float: float) -> None: ...

class ChangeBounds(Transition):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def getResizeClip(self) -> bool: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...
    def setReparent(self, boolean: bool) -> None: ...
    def setResizeClip(self, boolean: bool) -> None: ...

class ChangeClipBounds(Transition):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...

class ChangeImageTransform(Transition):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...

class ChangeScroll(Transition):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...

class ChangeTransform(Transition):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def getReparent(self) -> bool: ...
    def getReparentWithOverlay(self) -> bool: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...
    def setReparent(self, boolean: bool) -> None: ...
    def setReparentWithOverlay(self, boolean: bool) -> None: ...

class PatternPathMotion(PathMotion):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, path: android.graphics.Path): ...
    def getPath(self, float: float, float2: float, float3: float, float4: float) -> android.graphics.Path: ...
    def getPatternPath(self) -> android.graphics.Path: ...
    def setPatternPath(self, path: android.graphics.Path) -> None: ...

class TransitionListenerAdapter(Transition.TransitionListener):
    def __init__(self): ...
    def onTransitionCancel(self, transition: Transition) -> None: ...
    def onTransitionEnd(self, transition: Transition) -> None: ...
    def onTransitionPause(self, transition: Transition) -> None: ...
    def onTransitionResume(self, transition: Transition) -> None: ...
    def onTransitionStart(self, transition: Transition) -> None: ...

class TransitionSet(Transition):
    ORDERING_SEQUENTIAL: typing.ClassVar[int] = ...
    ORDERING_TOGETHER: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def addListener(self, transitionListener: Transition.TransitionListener) -> 'TransitionSet': ...
    @typing.overload
    def addTarget(self, view: android.view.View) -> 'TransitionSet': ...
    @typing.overload
    def addTarget(self, int: int) -> 'TransitionSet': ...
    @typing.overload
    def addTarget(self, class_: typing.Type) -> 'TransitionSet': ...
    @typing.overload
    def addTarget(self, string: str) -> 'TransitionSet': ...
    def addTransition(self, transition: Transition) -> 'TransitionSet': ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def clone(self) -> 'TransitionSet': ...
    @typing.overload
    def excludeTarget(self, view: android.view.View, boolean: bool) -> Transition: ...
    @typing.overload
    def excludeTarget(self, int: int, boolean: bool) -> Transition: ...
    @typing.overload
    def excludeTarget(self, class_: typing.Type, boolean: bool) -> Transition: ...
    @typing.overload
    def excludeTarget(self, string: str, boolean: bool) -> Transition: ...
    def getOrdering(self) -> int: ...
    def getTransitionAt(self, int: int) -> Transition: ...
    def getTransitionCount(self) -> int: ...
    def removeListener(self, transitionListener: Transition.TransitionListener) -> 'TransitionSet': ...
    @typing.overload
    def removeTarget(self, view: android.view.View) -> 'TransitionSet': ...
    @typing.overload
    def removeTarget(self, int: int) -> 'TransitionSet': ...
    @typing.overload
    def removeTarget(self, class_: typing.Type) -> 'TransitionSet': ...
    @typing.overload
    def removeTarget(self, string: str) -> 'TransitionSet': ...
    def removeTransition(self, transition: Transition) -> 'TransitionSet': ...
    def setDuration(self, long: int) -> 'TransitionSet': ...
    def setEpicenterCallback(self, epicenterCallback: Transition.EpicenterCallback) -> None: ...
    def setInterpolator(self, timeInterpolator: typing.Union[android.animation.TimeInterpolator, typing.Callable]) -> 'TransitionSet': ...
    def setOrdering(self, int: int) -> 'TransitionSet': ...
    def setPathMotion(self, pathMotion: PathMotion) -> None: ...
    def setPropagation(self, transitionPropagation: TransitionPropagation) -> None: ...
    def setStartDelay(self, long: int) -> 'TransitionSet': ...

class Visibility(Transition):
    MODE_IN: typing.ClassVar[int] = ...
    MODE_OUT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def createAnimator(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def getMode(self) -> int: ...
    def getTransitionProperties(self) -> typing.MutableSequence[str]: ...
    def isTransitionRequired(self, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> bool: ...
    def isVisible(self, transitionValues: TransitionValues) -> bool: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    def setMode(self, int: int) -> None: ...

class VisibilityPropagation(TransitionPropagation):
    def __init__(self): ...
    def captureValues(self, transitionValues: TransitionValues) -> None: ...
    def getPropagationProperties(self) -> typing.MutableSequence[str]: ...
    def getViewVisibility(self, transitionValues: TransitionValues) -> int: ...
    def getViewX(self, transitionValues: TransitionValues) -> int: ...
    def getViewY(self, transitionValues: TransitionValues) -> int: ...

class AutoTransition(TransitionSet):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...

class CircularPropagation(VisibilityPropagation):
    def __init__(self): ...
    def getStartDelay(self, viewGroup: android.view.ViewGroup, transition: Transition, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> int: ...
    def setPropagationSpeed(self, float: float) -> None: ...

class Explode(Visibility):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...

class Fade(Visibility):
    IN: typing.ClassVar[int] = ...
    OUT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, int: int): ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...

class SidePropagation(VisibilityPropagation):
    def __init__(self): ...
    def getStartDelay(self, viewGroup: android.view.ViewGroup, transition: Transition, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> int: ...
    def setPropagationSpeed(self, float: float) -> None: ...
    def setSide(self, int: int) -> None: ...

class Slide(Visibility):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet): ...
    @typing.overload
    def __init__(self, int: int): ...
    def captureEndValues(self, transitionValues: TransitionValues) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues) -> None: ...
    def getSlideEdge(self) -> int: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onAppear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, view2: android.view.View, transitionValues: TransitionValues, transitionValues2: TransitionValues) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, viewGroup: android.view.ViewGroup, transitionValues: TransitionValues, int: int, transitionValues2: TransitionValues, int2: int) -> android.animation.Animator: ...
    def setSlideEdge(self, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.transition")``.

    ArcMotion: typing.Type[ArcMotion]
    AutoTransition: typing.Type[AutoTransition]
    ChangeBounds: typing.Type[ChangeBounds]
    ChangeClipBounds: typing.Type[ChangeClipBounds]
    ChangeImageTransform: typing.Type[ChangeImageTransform]
    ChangeScroll: typing.Type[ChangeScroll]
    ChangeTransform: typing.Type[ChangeTransform]
    CircularPropagation: typing.Type[CircularPropagation]
    Explode: typing.Type[Explode]
    Fade: typing.Type[Fade]
    PathMotion: typing.Type[PathMotion]
    PatternPathMotion: typing.Type[PatternPathMotion]
    Scene: typing.Type[Scene]
    SidePropagation: typing.Type[SidePropagation]
    Slide: typing.Type[Slide]
    Transition: typing.Type[Transition]
    TransitionInflater: typing.Type[TransitionInflater]
    TransitionListenerAdapter: typing.Type[TransitionListenerAdapter]
    TransitionManager: typing.Type[TransitionManager]
    TransitionPropagation: typing.Type[TransitionPropagation]
    TransitionSet: typing.Type[TransitionSet]
    TransitionValues: typing.Type[TransitionValues]
    Visibility: typing.Type[Visibility]
    VisibilityPropagation: typing.Type[VisibilityPropagation]
