
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.os
import java.nio
import java.util
import jpype
import typing



class UsbAccessory(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDescription(self) -> str: ...
    def getManufacturer(self) -> str: ...
    def getModel(self) -> str: ...
    def getSerial(self) -> str: ...
    def getUri(self) -> str: ...
    def getVersion(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UsbConfiguration(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getId(self) -> int: ...
    def getInterface(self, int: int) -> 'UsbInterface': ...
    def getInterfaceCount(self) -> int: ...
    def getMaxPower(self) -> int: ...
    def getName(self) -> str: ...
    def isRemoteWakeup(self) -> bool: ...
    def isSelfPowered(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UsbConstants:
    USB_CLASS_APP_SPEC: typing.ClassVar[int] = ...
    USB_CLASS_AUDIO: typing.ClassVar[int] = ...
    USB_CLASS_CDC_DATA: typing.ClassVar[int] = ...
    USB_CLASS_COMM: typing.ClassVar[int] = ...
    USB_CLASS_CONTENT_SEC: typing.ClassVar[int] = ...
    USB_CLASS_CSCID: typing.ClassVar[int] = ...
    USB_CLASS_HID: typing.ClassVar[int] = ...
    USB_CLASS_HUB: typing.ClassVar[int] = ...
    USB_CLASS_MASS_STORAGE: typing.ClassVar[int] = ...
    USB_CLASS_MISC: typing.ClassVar[int] = ...
    USB_CLASS_PER_INTERFACE: typing.ClassVar[int] = ...
    USB_CLASS_PHYSICA: typing.ClassVar[int] = ...
    USB_CLASS_PRINTER: typing.ClassVar[int] = ...
    USB_CLASS_STILL_IMAGE: typing.ClassVar[int] = ...
    USB_CLASS_VENDOR_SPEC: typing.ClassVar[int] = ...
    USB_CLASS_VIDEO: typing.ClassVar[int] = ...
    USB_CLASS_WIRELESS_CONTROLLER: typing.ClassVar[int] = ...
    USB_DIR_IN: typing.ClassVar[int] = ...
    USB_DIR_OUT: typing.ClassVar[int] = ...
    USB_ENDPOINT_DIR_MASK: typing.ClassVar[int] = ...
    USB_ENDPOINT_NUMBER_MASK: typing.ClassVar[int] = ...
    USB_ENDPOINT_XFERTYPE_MASK: typing.ClassVar[int] = ...
    USB_ENDPOINT_XFER_BULK: typing.ClassVar[int] = ...
    USB_ENDPOINT_XFER_CONTROL: typing.ClassVar[int] = ...
    USB_ENDPOINT_XFER_INT: typing.ClassVar[int] = ...
    USB_ENDPOINT_XFER_ISOC: typing.ClassVar[int] = ...
    USB_INTERFACE_SUBCLASS_BOOT: typing.ClassVar[int] = ...
    USB_SUBCLASS_VENDOR_SPEC: typing.ClassVar[int] = ...
    USB_TYPE_CLASS: typing.ClassVar[int] = ...
    USB_TYPE_MASK: typing.ClassVar[int] = ...
    USB_TYPE_RESERVED: typing.ClassVar[int] = ...
    USB_TYPE_STANDARD: typing.ClassVar[int] = ...
    USB_TYPE_VENDOR: typing.ClassVar[int] = ...
    def __init__(self): ...

class UsbDevice(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getConfiguration(self, int: int) -> UsbConfiguration: ...
    def getConfigurationCount(self) -> int: ...
    def getDeviceClass(self) -> int: ...
    @typing.overload
    def getDeviceId(self) -> int: ...
    @typing.overload
    @staticmethod
    def getDeviceId(string: str) -> int: ...
    @typing.overload
    def getDeviceName(self) -> str: ...
    @typing.overload
    @staticmethod
    def getDeviceName(int: int) -> str: ...
    def getDeviceProtocol(self) -> int: ...
    def getDeviceSubclass(self) -> int: ...
    def getInterface(self, int: int) -> 'UsbInterface': ...
    def getInterfaceCount(self) -> int: ...
    def getManufacturerName(self) -> str: ...
    def getProductId(self) -> int: ...
    def getProductName(self) -> str: ...
    def getSerialNumber(self) -> str: ...
    def getVendorId(self) -> int: ...
    def getVersion(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UsbDeviceConnection:
    @typing.overload
    def bulkTransfer(self, usbEndpoint: 'UsbEndpoint', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    @typing.overload
    def bulkTransfer(self, usbEndpoint: 'UsbEndpoint', byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, int3: int) -> int: ...
    def claimInterface(self, usbInterface: 'UsbInterface', boolean: bool) -> bool: ...
    def close(self) -> None: ...
    @typing.overload
    def controlTransfer(self, int: int, int2: int, int3: int, int4: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int5: int, int6: int) -> int: ...
    @typing.overload
    def controlTransfer(self, int: int, int2: int, int3: int, int4: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int5: int, int6: int, int7: int) -> int: ...
    def getFileDescriptor(self) -> int: ...
    def getRawDescriptors(self) -> typing.MutableSequence[int]: ...
    def getSerial(self) -> str: ...
    def releaseInterface(self, usbInterface: 'UsbInterface') -> bool: ...
    @typing.overload
    def requestWait(self) -> 'UsbRequest': ...
    @typing.overload
    def requestWait(self, long: int) -> 'UsbRequest': ...
    def setConfiguration(self, usbConfiguration: UsbConfiguration) -> bool: ...
    def setInterface(self, usbInterface: 'UsbInterface') -> bool: ...

class UsbEndpoint(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAddress(self) -> int: ...
    def getAttributes(self) -> int: ...
    def getDirection(self) -> int: ...
    def getEndpointNumber(self) -> int: ...
    def getInterval(self) -> int: ...
    def getMaxPacketSize(self) -> int: ...
    def getType(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UsbInterface(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getAlternateSetting(self) -> int: ...
    def getEndpoint(self, int: int) -> UsbEndpoint: ...
    def getEndpointCount(self) -> int: ...
    def getId(self) -> int: ...
    def getInterfaceClass(self) -> int: ...
    def getInterfaceProtocol(self) -> int: ...
    def getInterfaceSubclass(self) -> int: ...
    def getName(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UsbManager:
    ACTION_USB_ACCESSORY_ATTACHED: typing.ClassVar[str] = ...
    ACTION_USB_ACCESSORY_DETACHED: typing.ClassVar[str] = ...
    ACTION_USB_DEVICE_ATTACHED: typing.ClassVar[str] = ...
    ACTION_USB_DEVICE_DETACHED: typing.ClassVar[str] = ...
    EXTRA_ACCESSORY: typing.ClassVar[str] = ...
    EXTRA_DEVICE: typing.ClassVar[str] = ...
    EXTRA_PERMISSION_GRANTED: typing.ClassVar[str] = ...
    def getAccessoryList(self) -> typing.MutableSequence[UsbAccessory]: ...
    def getDeviceList(self) -> java.util.HashMap[str, UsbDevice]: ...
    @typing.overload
    def hasPermission(self, usbAccessory: UsbAccessory) -> bool: ...
    @typing.overload
    def hasPermission(self, usbDevice: UsbDevice) -> bool: ...
    def openAccessory(self, usbAccessory: UsbAccessory) -> android.os.ParcelFileDescriptor: ...
    def openDevice(self, usbDevice: UsbDevice) -> UsbDeviceConnection: ...
    @typing.overload
    def requestPermission(self, usbAccessory: UsbAccessory, pendingIntent: android.app.PendingIntent) -> None: ...
    @typing.overload
    def requestPermission(self, usbDevice: UsbDevice, pendingIntent: android.app.PendingIntent) -> None: ...

class UsbRequest:
    def __init__(self): ...
    def cancel(self) -> bool: ...
    def close(self) -> None: ...
    def getClientData(self) -> typing.Any: ...
    def getEndpoint(self) -> UsbEndpoint: ...
    def initialize(self, usbDeviceConnection: UsbDeviceConnection, usbEndpoint: UsbEndpoint) -> bool: ...
    @typing.overload
    def queue(self, byteBuffer: java.nio.ByteBuffer) -> bool: ...
    @typing.overload
    def queue(self, byteBuffer: java.nio.ByteBuffer, int: int) -> bool: ...
    def setClientData(self, object: typing.Any) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.hardware.usb")``.

    UsbAccessory: typing.Type[UsbAccessory]
    UsbConfiguration: typing.Type[UsbConfiguration]
    UsbConstants: typing.Type[UsbConstants]
    UsbDevice: typing.Type[UsbDevice]
    UsbDeviceConnection: typing.Type[UsbDeviceConnection]
    UsbEndpoint: typing.Type[UsbEndpoint]
    UsbInterface: typing.Type[UsbInterface]
    UsbManager: typing.Type[UsbManager]
    UsbRequest: typing.Type[UsbRequest]
