
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import android.view
import android.widget
import java.lang
import java.time
import typing



class BackEvent:
    EDGE_LEFT: typing.ClassVar[int] = ...
    EDGE_RIGHT: typing.ClassVar[int] = ...
    def __init__(self, float: float, float2: float, float3: float, int: int): ...
    def getProgress(self) -> float: ...
    def getSwipeEdge(self) -> int: ...
    def getTouchX(self) -> float: ...
    def getTouchY(self) -> float: ...
    def toString(self) -> str: ...

class InputTransferToken(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class OnBackInvokedCallback:
    def onBackInvoked(self) -> None: ...

class OnBackInvokedDispatcher:
    PRIORITY_DEFAULT: typing.ClassVar[int] = ...
    PRIORITY_OVERLAY: typing.ClassVar[int] = ...
    def registerOnBackInvokedCallback(self, int: int, onBackInvokedCallback: typing.Union[OnBackInvokedCallback, typing.Callable]) -> None: ...
    def unregisterOnBackInvokedCallback(self, onBackInvokedCallback: typing.Union[OnBackInvokedCallback, typing.Callable]) -> None: ...

class SplashScreen:
    SPLASH_SCREEN_STYLE_ICON: typing.ClassVar[int] = ...
    SPLASH_SCREEN_STYLE_SOLID_COLOR: typing.ClassVar[int] = ...
    def clearOnExitAnimationListener(self) -> None: ...
    def setOnExitAnimationListener(self, onExitAnimationListener: typing.Union['SplashScreen.OnExitAnimationListener', typing.Callable]) -> None: ...
    def setSplashScreenTheme(self, int: int) -> None: ...
    class OnExitAnimationListener:
        def onSplashScreenExit(self, splashScreenView: 'SplashScreenView') -> None: ...

class SplashScreenView(android.widget.FrameLayout):
    def getIconAnimationDuration(self) -> java.time.Duration: ...
    def getIconAnimationStart(self) -> java.time.Instant: ...
    def getIconView(self) -> android.view.View: ...
    def remove(self) -> None: ...
    def setAlpha(self, float: float) -> None: ...

class SurfaceSyncGroup:
    def __init__(self, string: str): ...
    @typing.overload
    def add(self, attachedSurfaceControl: android.view.AttachedSurfaceControl, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> bool: ...
    @typing.overload
    def add(self, surfacePackage: android.view.SurfaceControlViewHost.SurfacePackage, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> bool: ...
    def addTransaction(self, transaction: android.view.SurfaceControl.Transaction) -> None: ...
    def markSyncReady(self) -> None: ...

class TrustedPresentationThresholds(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, float: float, float2: float, int: int): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMinAlpha(self) -> float: ...
    def getMinFractionRendered(self) -> float: ...
    def getStabilityRequirementMillis(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class OnBackAnimationCallback(OnBackInvokedCallback):
    def onBackCancelled(self) -> None: ...
    def onBackProgressed(self, backEvent: BackEvent) -> None: ...
    def onBackStarted(self, backEvent: BackEvent) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.window")``.

    BackEvent: typing.Type[BackEvent]
    InputTransferToken: typing.Type[InputTransferToken]
    OnBackAnimationCallback: typing.Type[OnBackAnimationCallback]
    OnBackInvokedCallback: typing.Type[OnBackInvokedCallback]
    OnBackInvokedDispatcher: typing.Type[OnBackInvokedDispatcher]
    SplashScreen: typing.Type[SplashScreen]
    SplashScreenView: typing.Type[SplashScreenView]
    SurfaceSyncGroup: typing.Type[SurfaceSyncGroup]
    TrustedPresentationThresholds: typing.Type[TrustedPresentationThresholds]
