
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.content
import android.graphics
import android.graphics.drawable
import android.graphics.text
import android.icu.util
import android.os
import android.text.format
import android.text.method
import android.text.style
import android.text.util
import android.util
import android.view
import java.lang
import java.util
import java.util.regex
import jpype
import org.xml.sax
import typing



class AndroidCharacter:
    EAST_ASIAN_WIDTH_AMBIGUOUS: typing.ClassVar[int] = ...
    EAST_ASIAN_WIDTH_FULL_WIDTH: typing.ClassVar[int] = ...
    EAST_ASIAN_WIDTH_HALF_WIDTH: typing.ClassVar[int] = ...
    EAST_ASIAN_WIDTH_NARROW: typing.ClassVar[int] = ...
    EAST_ASIAN_WIDTH_NEUTRAL: typing.ClassVar[int] = ...
    EAST_ASIAN_WIDTH_WIDE: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def getDirectionalities(charArray: typing.Union[typing.List[str], jpype.JArray], byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int) -> None: ...
    @staticmethod
    def getEastAsianWidth(char: str) -> int: ...
    @staticmethod
    def getEastAsianWidths(charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @staticmethod
    def getMirror(char: str) -> str: ...
    @staticmethod
    def mirror(charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> bool: ...

class AutoText:
    @staticmethod
    def get(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, view: android.view.View) -> str: ...
    @staticmethod
    def getSize(view: android.view.View) -> int: ...

class BidiFormatter:
    @typing.overload
    @staticmethod
    def getInstance() -> 'BidiFormatter': ...
    @typing.overload
    @staticmethod
    def getInstance(boolean: bool) -> 'BidiFormatter': ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale) -> 'BidiFormatter': ...
    def getStereoReset(self) -> bool: ...
    @typing.overload
    def isRtl(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> bool: ...
    @typing.overload
    def isRtl(self, string: str) -> bool: ...
    def isRtlContext(self) -> bool: ...
    @typing.overload
    def unicodeWrap(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, charSequence: typing.Union[java.lang.CharSequence, str], textDirectionHeuristic: 'TextDirectionHeuristic') -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, charSequence: typing.Union[java.lang.CharSequence, str], textDirectionHeuristic: 'TextDirectionHeuristic', boolean: bool) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, charSequence: typing.Union[java.lang.CharSequence, str], boolean: bool) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, string: str) -> str: ...
    @typing.overload
    def unicodeWrap(self, string: str, textDirectionHeuristic: 'TextDirectionHeuristic') -> str: ...
    @typing.overload
    def unicodeWrap(self, string: str, textDirectionHeuristic: 'TextDirectionHeuristic', boolean: bool) -> str: ...
    @typing.overload
    def unicodeWrap(self, string: str, boolean: bool) -> str: ...
    class Builder:
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, boolean: bool): ...
        @typing.overload
        def __init__(self, locale: java.util.Locale): ...
        def build(self) -> 'BidiFormatter': ...
        def setTextDirectionHeuristic(self, textDirectionHeuristic: 'TextDirectionHeuristic') -> 'BidiFormatter.Builder': ...
        def stereoReset(self, boolean: bool) -> 'BidiFormatter.Builder': ...

class ClipboardManager:
    def __init__(self): ...
    def getText(self) -> java.lang.CharSequence: ...
    def hasText(self) -> bool: ...
    def setText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...

class EmojiConsistency:
    @staticmethod
    def getEmojiConsistencySet() -> java.util.Set[typing.MutableSequence[int]]: ...

class GetChars(java.lang.CharSequence):
    def getChars(self, int: int, int2: int, charArray: typing.Union[typing.List[str], jpype.JArray], int3: int) -> None: ...
    def toString(self) -> str: ...

class Highlights:
    def getPaint(self, int: int) -> android.graphics.Paint: ...
    def getRanges(self, int: int) -> typing.MutableSequence[int]: ...
    def getSize(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addRange(self, paint: android.graphics.Paint, int: int, int2: int) -> 'Highlights.Builder': ...
        def addRanges(self, paint: android.graphics.Paint, *int: int) -> 'Highlights.Builder': ...
        def build(self) -> 'Highlights': ...

class Html:
    FROM_HTML_MODE_COMPACT: typing.ClassVar[int] = ...
    FROM_HTML_MODE_LEGACY: typing.ClassVar[int] = ...
    FROM_HTML_OPTION_USE_CSS_COLORS: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_BLOCKQUOTE: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_DIV: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_HEADING: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST_ITEM: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_PARAGRAPH: typing.ClassVar[int] = ...
    TO_HTML_PARAGRAPH_LINES_CONSECUTIVE: typing.ClassVar[int] = ...
    TO_HTML_PARAGRAPH_LINES_INDIVIDUAL: typing.ClassVar[int] = ...
    @staticmethod
    def escapeHtml(charSequence: typing.Union[java.lang.CharSequence, str]) -> str: ...
    @typing.overload
    @staticmethod
    def fromHtml(string: str) -> 'Spanned': ...
    @typing.overload
    @staticmethod
    def fromHtml(string: str, imageGetter: typing.Union['Html.ImageGetter', typing.Callable], tagHandler: typing.Union['Html.TagHandler', typing.Callable]) -> 'Spanned': ...
    @typing.overload
    @staticmethod
    def fromHtml(string: str, int: int) -> 'Spanned': ...
    @typing.overload
    @staticmethod
    def fromHtml(string: str, int: int, imageGetter: typing.Union['Html.ImageGetter', typing.Callable], tagHandler: typing.Union['Html.TagHandler', typing.Callable]) -> 'Spanned': ...
    @typing.overload
    @staticmethod
    def toHtml(spanned: 'Spanned') -> str: ...
    @typing.overload
    @staticmethod
    def toHtml(spanned: 'Spanned', int: int) -> str: ...
    class ImageGetter:
        def getDrawable(self, string: str) -> android.graphics.drawable.Drawable: ...
    class TagHandler:
        def handleTag(self, boolean: bool, string: str, editable: 'Editable', xMLReader: org.xml.sax.XMLReader) -> None: ...

class InputType:
    TYPE_CLASS_DATETIME: typing.ClassVar[int] = ...
    TYPE_CLASS_NUMBER: typing.ClassVar[int] = ...
    TYPE_CLASS_PHONE: typing.ClassVar[int] = ...
    TYPE_CLASS_TEXT: typing.ClassVar[int] = ...
    TYPE_DATETIME_VARIATION_DATE: typing.ClassVar[int] = ...
    TYPE_DATETIME_VARIATION_NORMAL: typing.ClassVar[int] = ...
    TYPE_DATETIME_VARIATION_TIME: typing.ClassVar[int] = ...
    TYPE_MASK_CLASS: typing.ClassVar[int] = ...
    TYPE_MASK_FLAGS: typing.ClassVar[int] = ...
    TYPE_MASK_VARIATION: typing.ClassVar[int] = ...
    TYPE_NULL: typing.ClassVar[int] = ...
    TYPE_NUMBER_FLAG_DECIMAL: typing.ClassVar[int] = ...
    TYPE_NUMBER_FLAG_SIGNED: typing.ClassVar[int] = ...
    TYPE_NUMBER_VARIATION_NORMAL: typing.ClassVar[int] = ...
    TYPE_NUMBER_VARIATION_PASSWORD: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_AUTO_COMPLETE: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_AUTO_CORRECT: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_CAP_CHARACTERS: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_CAP_SENTENCES: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_CAP_WORDS: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_ENABLE_TEXT_CONVERSION_SUGGESTIONS: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_IME_MULTI_LINE: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_MULTI_LINE: typing.ClassVar[int] = ...
    TYPE_TEXT_FLAG_NO_SUGGESTIONS: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_EMAIL_ADDRESS: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_EMAIL_SUBJECT: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_FILTER: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_LONG_MESSAGE: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_NORMAL: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_PASSWORD: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_PERSON_NAME: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_PHONETIC: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_POSTAL_ADDRESS: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_SHORT_MESSAGE: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_URI: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_VISIBLE_PASSWORD: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_WEB_EDIT_TEXT: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS: typing.ClassVar[int] = ...
    TYPE_TEXT_VARIATION_WEB_PASSWORD: typing.ClassVar[int] = ...

class Layout:
    BREAK_STRATEGY_BALANCED: typing.ClassVar[int] = ...
    BREAK_STRATEGY_HIGH_QUALITY: typing.ClassVar[int] = ...
    BREAK_STRATEGY_SIMPLE: typing.ClassVar[int] = ...
    DEFAULT_LINESPACING_ADDITION: typing.ClassVar[float] = ...
    DEFAULT_LINESPACING_MULTIPLIER: typing.ClassVar[float] = ...
    DIR_LEFT_TO_RIGHT: typing.ClassVar[int] = ...
    DIR_RIGHT_TO_LEFT: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_FULL: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_FULL_FAST: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_NONE: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_NORMAL: typing.ClassVar[int] = ...
    HYPHENATION_FREQUENCY_NORMAL_FAST: typing.ClassVar[int] = ...
    INCLUSION_STRATEGY_ANY_OVERLAP: typing.ClassVar['Layout.TextInclusionStrategy'] = ...
    INCLUSION_STRATEGY_CONTAINS_ALL: typing.ClassVar['Layout.TextInclusionStrategy'] = ...
    INCLUSION_STRATEGY_CONTAINS_CENTER: typing.ClassVar['Layout.TextInclusionStrategy'] = ...
    JUSTIFICATION_MODE_INTER_CHARACTER: typing.ClassVar[int] = ...
    JUSTIFICATION_MODE_INTER_WORD: typing.ClassVar[int] = ...
    JUSTIFICATION_MODE_NONE: typing.ClassVar[int] = ...
    def computeDrawingBoundingBox(self) -> android.graphics.RectF: ...
    @typing.overload
    def draw(self, canvas: android.graphics.Canvas) -> None: ...
    @typing.overload
    def draw(self, canvas: android.graphics.Canvas, path: android.graphics.Path, paint: android.graphics.Paint, int: int) -> None: ...
    @typing.overload
    def draw(self, canvas: android.graphics.Canvas, list: java.util.List[android.graphics.Path], list2: java.util.List[android.graphics.Paint], path: android.graphics.Path, paint: android.graphics.Paint, int: int) -> None: ...
    def drawBackground(self, canvas: android.graphics.Canvas) -> None: ...
    def drawText(self, canvas: android.graphics.Canvas) -> None: ...
    def fillCharacterBounds(self, int: int, int2: int, floatArray: typing.Union[typing.List[float], jpype.JArray], int3: int) -> None: ...
    def getAlignment(self) -> 'Layout.Alignment': ...
    def getBottomPadding(self) -> int: ...
    def getBreakStrategy(self) -> int: ...
    def getCursorPath(self, int: int, path: android.graphics.Path, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    @staticmethod
    def getDesiredWidth(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: 'TextPaint') -> float: ...
    @typing.overload
    @staticmethod
    def getDesiredWidth(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, textPaint: 'TextPaint') -> float: ...
    def getEllipsisCount(self, int: int) -> int: ...
    def getEllipsisStart(self, int: int) -> int: ...
    def getEllipsize(self) -> 'TextUtils.TruncateAt': ...
    def getEllipsizedWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getHyphenationFrequency(self) -> int: ...
    def getJustificationMode(self) -> int: ...
    def getLeftIndents(self) -> typing.MutableSequence[int]: ...
    def getLineAscent(self, int: int) -> int: ...
    def getLineBaseline(self, int: int) -> int: ...
    @typing.overload
    def getLineBottom(self, int: int) -> int: ...
    @typing.overload
    def getLineBottom(self, int: int, boolean: bool) -> int: ...
    def getLineBounds(self, int: int, rect: android.graphics.Rect) -> int: ...
    def getLineBreakConfig(self) -> android.graphics.text.LineBreakConfig: ...
    def getLineContainsTab(self, int: int) -> bool: ...
    def getLineCount(self) -> int: ...
    def getLineDescent(self, int: int) -> int: ...
    def getLineDirections(self, int: int) -> 'Layout.Directions': ...
    def getLineEnd(self, int: int) -> int: ...
    def getLineForOffset(self, int: int) -> int: ...
    def getLineForVertical(self, int: int) -> int: ...
    def getLineLeft(self, int: int) -> float: ...
    def getLineLetterSpacingUnitCount(self, int: int, boolean: bool) -> int: ...
    def getLineMax(self, int: int) -> float: ...
    def getLineRight(self, int: int) -> float: ...
    def getLineSpacingAmount(self) -> float: ...
    def getLineSpacingMultiplier(self) -> float: ...
    def getLineStart(self, int: int) -> int: ...
    def getLineTop(self, int: int) -> int: ...
    def getLineVisibleEnd(self, int: int) -> int: ...
    def getLineWidth(self, int: int) -> float: ...
    def getMaxLines(self) -> int: ...
    def getMinimumFontMetrics(self) -> android.graphics.Paint.FontMetrics: ...
    def getOffsetForHorizontal(self, int: int, float: float) -> int: ...
    def getOffsetToLeftOf(self, int: int) -> int: ...
    def getOffsetToRightOf(self, int: int) -> int: ...
    def getPaint(self) -> 'TextPaint': ...
    def getParagraphAlignment(self, int: int) -> 'Layout.Alignment': ...
    def getParagraphDirection(self, int: int) -> int: ...
    def getParagraphLeft(self, int: int) -> int: ...
    def getParagraphRight(self, int: int) -> int: ...
    def getPrimaryHorizontal(self, int: int) -> float: ...
    def getRangeForRect(self, rectF: android.graphics.RectF, segmentFinder: 'SegmentFinder', textInclusionStrategy: typing.Union['Layout.TextInclusionStrategy', typing.Callable]) -> typing.MutableSequence[int]: ...
    def getRightIndents(self) -> typing.MutableSequence[int]: ...
    def getSecondaryHorizontal(self, int: int) -> float: ...
    def getSelectionPath(self, int: int, int2: int, path: android.graphics.Path) -> None: ...
    def getShiftDrawingOffsetForStartOverhang(self) -> bool: ...
    def getSpacingAdd(self) -> float: ...
    def getSpacingMultiplier(self) -> float: ...
    def getText(self) -> java.lang.CharSequence: ...
    def getTextDirectionHeuristic(self) -> 'TextDirectionHeuristic': ...
    def getTopPadding(self) -> int: ...
    def getUseBoundsForWidth(self) -> bool: ...
    def getWidth(self) -> int: ...
    def increaseWidthTo(self, int: int) -> None: ...
    def isFallbackLineSpacingEnabled(self) -> bool: ...
    def isFontPaddingIncluded(self) -> bool: ...
    def isRtlCharAt(self, int: int) -> bool: ...
    class Alignment(java.lang.Enum['Layout.Alignment']):
        ALIGN_NORMAL: typing.ClassVar['Layout.Alignment'] = ...
        ALIGN_OPPOSITE: typing.ClassVar['Layout.Alignment'] = ...
        ALIGN_CENTER: typing.ClassVar['Layout.Alignment'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Layout.Alignment': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['Layout.Alignment']: ...
    class Builder:
        def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, textPaint: 'TextPaint', int3: int): ...
        def build(self) -> 'Layout': ...
        def setAlignment(self, alignment: 'Layout.Alignment') -> 'Layout.Builder': ...
        def setBreakStrategy(self, int: int) -> 'Layout.Builder': ...
        def setEllipsize(self, truncateAt: 'TextUtils.TruncateAt') -> 'Layout.Builder': ...
        def setEllipsizedWidth(self, int: int) -> 'Layout.Builder': ...
        def setFallbackLineSpacingEnabled(self, boolean: bool) -> 'Layout.Builder': ...
        def setFontPaddingIncluded(self, boolean: bool) -> 'Layout.Builder': ...
        def setHyphenationFrequency(self, int: int) -> 'Layout.Builder': ...
        def setJustificationMode(self, int: int) -> 'Layout.Builder': ...
        def setLeftIndents(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'Layout.Builder': ...
        def setLineBreakConfig(self, lineBreakConfig: android.graphics.text.LineBreakConfig) -> 'Layout.Builder': ...
        def setLineSpacingAmount(self, float: float) -> 'Layout.Builder': ...
        def setLineSpacingMultiplier(self, float: float) -> 'Layout.Builder': ...
        def setMaxLines(self, int: int) -> 'Layout.Builder': ...
        def setMinimumFontMetrics(self, fontMetrics: android.graphics.Paint.FontMetrics) -> 'Layout.Builder': ...
        def setRightIndents(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'Layout.Builder': ...
        def setShiftDrawingOffsetForStartOverhang(self, boolean: bool) -> 'Layout.Builder': ...
        def setTextDirectionHeuristic(self, textDirectionHeuristic: 'TextDirectionHeuristic') -> 'Layout.Builder': ...
        def setUseBoundsForWidth(self, boolean: bool) -> 'Layout.Builder': ...
    class Directions: ...
    class TextInclusionStrategy:
        def isSegmentInside(self, rectF: android.graphics.RectF, rectF2: android.graphics.RectF) -> bool: ...

class ParcelableSpan(android.os.Parcelable):
    def getSpanTypeId(self) -> int: ...

class Selection:
    SELECTION_END: typing.ClassVar[typing.Any] = ...
    SELECTION_START: typing.ClassVar[typing.Any] = ...
    @staticmethod
    def extendDown(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def extendLeft(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def extendRight(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def extendSelection(spannable: 'Spannable', int: int) -> None: ...
    @staticmethod
    def extendToLeftEdge(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def extendToParagraphEnd(spannable: 'Spannable') -> bool: ...
    @staticmethod
    def extendToParagraphStart(spannable: 'Spannable') -> bool: ...
    @staticmethod
    def extendToRightEdge(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def extendUp(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def getSelectionEnd(charSequence: typing.Union[java.lang.CharSequence, str]) -> int: ...
    @staticmethod
    def getSelectionStart(charSequence: typing.Union[java.lang.CharSequence, str]) -> int: ...
    @staticmethod
    def moveDown(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveLeft(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveRight(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveToLeftEdge(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveToParagraphEnd(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveToParagraphStart(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveToRightEdge(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def moveUp(spannable: 'Spannable', layout: Layout) -> bool: ...
    @staticmethod
    def removeSelection(spannable: 'Spannable') -> None: ...
    @staticmethod
    def selectAll(spannable: 'Spannable') -> None: ...
    @typing.overload
    @staticmethod
    def setSelection(spannable: 'Spannable', int: int) -> None: ...
    @typing.overload
    @staticmethod
    def setSelection(spannable: 'Spannable', int: int, int2: int) -> None: ...

class Spanned(java.lang.CharSequence):
    SPAN_COMPOSING: typing.ClassVar[int] = ...
    SPAN_EXCLUSIVE_EXCLUSIVE: typing.ClassVar[int] = ...
    SPAN_EXCLUSIVE_INCLUSIVE: typing.ClassVar[int] = ...
    SPAN_INCLUSIVE_EXCLUSIVE: typing.ClassVar[int] = ...
    SPAN_INCLUSIVE_INCLUSIVE: typing.ClassVar[int] = ...
    SPAN_INTERMEDIATE: typing.ClassVar[int] = ...
    SPAN_MARK_MARK: typing.ClassVar[int] = ...
    SPAN_MARK_POINT: typing.ClassVar[int] = ...
    SPAN_PARAGRAPH: typing.ClassVar[int] = ...
    SPAN_POINT_MARK: typing.ClassVar[int] = ...
    SPAN_POINT_MARK_MASK: typing.ClassVar[int] = ...
    SPAN_POINT_POINT: typing.ClassVar[int] = ...
    SPAN_PRIORITY: typing.ClassVar[int] = ...
    SPAN_PRIORITY_SHIFT: typing.ClassVar[int] = ...
    SPAN_USER: typing.ClassVar[int] = ...
    SPAN_USER_SHIFT: typing.ClassVar[int] = ...
    def getSpanEnd(self, object: typing.Any) -> int: ...
    def getSpanFlags(self, object: typing.Any) -> int: ...
    def getSpanStart(self, object: typing.Any) -> int: ...
    _getSpans__T = typing.TypeVar('_getSpans__T')  # <T>
    def getSpans(self, int: int, int2: int, class_: typing.Type[_getSpans__T]) -> typing.MutableSequence[_getSpans__T]: ...
    def nextSpanTransition(self, int: int, int2: int, class_: typing.Type) -> int: ...
    def toString(self) -> str: ...

class TextDirectionHeuristic:
    @typing.overload
    def isRtl(self, charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> bool: ...
    @typing.overload
    def isRtl(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> bool: ...

class TextDirectionHeuristics:
    ANYRTL_LTR: typing.ClassVar[TextDirectionHeuristic] = ...
    FIRSTSTRONG_LTR: typing.ClassVar[TextDirectionHeuristic] = ...
    FIRSTSTRONG_RTL: typing.ClassVar[TextDirectionHeuristic] = ...
    LOCALE: typing.ClassVar[TextDirectionHeuristic] = ...
    LTR: typing.ClassVar[TextDirectionHeuristic] = ...
    RTL: typing.ClassVar[TextDirectionHeuristic] = ...
    def __init__(self): ...

class TextPaint(android.graphics.Paint):
    baselineShift: int = ...
    bgColor: int = ...
    density: float = ...
    drawableState: typing.MutableSequence[int] = ...
    linkColor: int = ...
    underlineColor: int = ...
    underlineThickness: float = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, paint: android.graphics.Paint): ...
    @typing.overload
    def __init__(self, int: int): ...
    def getUnderlineThickness(self) -> float: ...
    @typing.overload
    def set(self, paint: android.graphics.Paint) -> None: ...
    @typing.overload
    def set(self, textPaint: 'TextPaint') -> None: ...

class TextShaper:
    @staticmethod
    def shapeText(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, textDirectionHeuristic: TextDirectionHeuristic, textPaint: TextPaint, glyphsConsumer: typing.Union['TextShaper.GlyphsConsumer', typing.Callable]) -> None: ...
    class GlyphsConsumer:
        def accept(self, int: int, int2: int, positionedGlyphs: android.graphics.text.PositionedGlyphs, textPaint: TextPaint) -> None: ...

class AlteredCharSequence(java.lang.CharSequence, GetChars):
    def charAt(self, int: int) -> str: ...
    def getChars(self, int: int, int2: int, charArray: typing.Union[typing.List[str], jpype.JArray], int3: int) -> None: ...
    def length(self) -> int: ...
    @staticmethod
    def make(charSequence: typing.Union[java.lang.CharSequence, str], charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> 'AlteredCharSequence': ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...

class Annotation(ParcelableSpan):
    @typing.overload
    def __init__(self, parcel: android.os.Parcel): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    def describeContents(self) -> int: ...
    def getKey(self) -> str: ...
    def getSpanTypeId(self) -> int: ...
    def getValue(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DynamicLayout(Layout):
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, boolean: bool): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, boolean: bool): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int): ...
    def getBottomPadding(self) -> int: ...
    def getEllipsisCount(self, int: int) -> int: ...
    def getEllipsisStart(self, int: int) -> int: ...
    def getEllipsizedWidth(self) -> int: ...
    def getLineBreakConfig(self) -> android.graphics.text.LineBreakConfig: ...
    def getLineContainsTab(self, int: int) -> bool: ...
    def getLineCount(self) -> int: ...
    def getLineDescent(self, int: int) -> int: ...
    def getLineDirections(self, int: int) -> Layout.Directions: ...
    def getLineStart(self, int: int) -> int: ...
    def getLineTop(self, int: int) -> int: ...
    def getParagraphDirection(self, int: int) -> int: ...
    def getTopPadding(self) -> int: ...
    class Builder:
        def build(self) -> 'DynamicLayout': ...
        @staticmethod
        def obtain(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int) -> 'DynamicLayout.Builder': ...
        def setAlignment(self, alignment: Layout.Alignment) -> 'DynamicLayout.Builder': ...
        def setBreakStrategy(self, int: int) -> 'DynamicLayout.Builder': ...
        def setDisplayText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'DynamicLayout.Builder': ...
        def setEllipsize(self, truncateAt: 'TextUtils.TruncateAt') -> 'DynamicLayout.Builder': ...
        def setEllipsizedWidth(self, int: int) -> 'DynamicLayout.Builder': ...
        def setHyphenationFrequency(self, int: int) -> 'DynamicLayout.Builder': ...
        def setIncludePad(self, boolean: bool) -> 'DynamicLayout.Builder': ...
        def setJustificationMode(self, int: int) -> 'DynamicLayout.Builder': ...
        def setLineBreakConfig(self, lineBreakConfig: android.graphics.text.LineBreakConfig) -> 'DynamicLayout.Builder': ...
        def setLineSpacing(self, float: float, float2: float) -> 'DynamicLayout.Builder': ...
        def setMinimumFontMetrics(self, fontMetrics: android.graphics.Paint.FontMetrics) -> 'DynamicLayout.Builder': ...
        def setShiftDrawingOffsetForStartOverhang(self, boolean: bool) -> 'DynamicLayout.Builder': ...
        def setTextDirection(self, textDirectionHeuristic: TextDirectionHeuristic) -> 'DynamicLayout.Builder': ...
        def setUseBoundsForWidth(self, boolean: bool) -> 'DynamicLayout.Builder': ...
        def setUseLineSpacingFromFallbacks(self, boolean: bool) -> 'DynamicLayout.Builder': ...

class Spannable(Spanned):
    def removeSpan(self, object: typing.Any) -> None: ...
    def setSpan(self, object: typing.Any, int: int, int2: int, int3: int) -> None: ...
    def toString(self) -> str: ...
    class Factory:
        def __init__(self): ...
        @staticmethod
        def getInstance() -> 'Spannable.Factory': ...
        def newSpannable(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'Spannable': ...

class SpannedString(java.lang.CharSequence, GetChars, Spanned):
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str]): ...
    def charAt(self, int: int) -> str: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getChars(self, int: int, int2: int, charArray: typing.Union[typing.List[str], jpype.JArray], int3: int) -> None: ...
    def getSpanEnd(self, object: typing.Any) -> int: ...
    def getSpanFlags(self, object: typing.Any) -> int: ...
    def getSpanStart(self, object: typing.Any) -> int: ...
    _getSpans__T = typing.TypeVar('_getSpans__T')  # <T>
    def getSpans(self, int: int, int2: int, class_: typing.Type[_getSpans__T]) -> typing.MutableSequence[_getSpans__T]: ...
    def hashCode(self) -> int: ...
    def length(self) -> int: ...
    def nextSpanTransition(self, int: int, int2: int, class_: typing.Type) -> int: ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    @staticmethod
    def valueOf(charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SpannedString': ...

class StaticLayout(Layout):
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, boolean: bool): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, textPaint: TextPaint, int3: int, alignment: Layout.Alignment, float: float, float2: float, boolean: bool): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, textPaint: TextPaint, int3: int, alignment: Layout.Alignment, float: float, float2: float, boolean: bool, truncateAt: 'TextUtils.TruncateAt', int4: int): ...
    def computeDrawingBoundingBox(self) -> android.graphics.RectF: ...
    def getBottomPadding(self) -> int: ...
    def getEllipsisCount(self, int: int) -> int: ...
    def getEllipsisStart(self, int: int) -> int: ...
    def getLineContainsTab(self, int: int) -> bool: ...
    def getLineCount(self) -> int: ...
    def getLineDescent(self, int: int) -> int: ...
    def getLineDirections(self, int: int) -> Layout.Directions: ...
    def getLineForVertical(self, int: int) -> int: ...
    def getLineStart(self, int: int) -> int: ...
    def getLineTop(self, int: int) -> int: ...
    def getParagraphDirection(self, int: int) -> int: ...
    def getTopPadding(self) -> int: ...
    class Builder:
        def build(self) -> 'StaticLayout': ...
        @staticmethod
        def obtain(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, textPaint: TextPaint, int3: int) -> 'StaticLayout.Builder': ...
        def setAlignment(self, alignment: Layout.Alignment) -> 'StaticLayout.Builder': ...
        def setBreakStrategy(self, int: int) -> 'StaticLayout.Builder': ...
        def setEllipsize(self, truncateAt: 'TextUtils.TruncateAt') -> 'StaticLayout.Builder': ...
        def setEllipsizedWidth(self, int: int) -> 'StaticLayout.Builder': ...
        def setHyphenationFrequency(self, int: int) -> 'StaticLayout.Builder': ...
        def setIncludePad(self, boolean: bool) -> 'StaticLayout.Builder': ...
        def setIndents(self, intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray]) -> 'StaticLayout.Builder': ...
        def setJustificationMode(self, int: int) -> 'StaticLayout.Builder': ...
        def setLineBreakConfig(self, lineBreakConfig: android.graphics.text.LineBreakConfig) -> 'StaticLayout.Builder': ...
        def setLineSpacing(self, float: float, float2: float) -> 'StaticLayout.Builder': ...
        def setMaxLines(self, int: int) -> 'StaticLayout.Builder': ...
        def setMinimumFontMetrics(self, fontMetrics: android.graphics.Paint.FontMetrics) -> 'StaticLayout.Builder': ...
        def setShiftDrawingOffsetForStartOverhang(self, boolean: bool) -> 'StaticLayout.Builder': ...
        def setText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'StaticLayout.Builder': ...
        def setTextDirection(self, textDirectionHeuristic: TextDirectionHeuristic) -> 'StaticLayout.Builder': ...
        def setUseBoundsForWidth(self, boolean: bool) -> 'StaticLayout.Builder': ...
        def setUseLineSpacingFromFallbacks(self, boolean: bool) -> 'StaticLayout.Builder': ...

class Editable(java.lang.CharSequence, GetChars, Spannable, java.lang.Appendable):
    @typing.overload
    def append(self, char: str) -> 'Editable': ...
    @typing.overload
    def append(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'Editable': ...
    @typing.overload
    def append(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> 'Editable': ...
    def clear(self) -> None: ...
    def clearSpans(self) -> None: ...
    def delete(self, int: int, int2: int) -> 'Editable': ...
    def getFilters(self) -> typing.MutableSequence['InputFilter']: ...
    @typing.overload
    def insert(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'Editable': ...
    @typing.overload
    def insert(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str], int2: int, int3: int) -> 'Editable': ...
    @typing.overload
    def replace(self, int: int, int2: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'Editable': ...
    @typing.overload
    def replace(self, int: int, int2: int, charSequence: typing.Union[java.lang.CharSequence, str], int3: int, int4: int) -> 'Editable': ...
    def setFilters(self, inputFilterArray: typing.Union[typing.List['InputFilter'], jpype.JArray]) -> None: ...
    def toString(self) -> str: ...
    class Factory:
        def __init__(self): ...
        @staticmethod
        def getInstance() -> 'Editable.Factory': ...
        def newEditable(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'Editable': ...

class PrecomputedText(Spannable):
    def charAt(self, int: int) -> str: ...
    @staticmethod
    def create(charSequence: typing.Union[java.lang.CharSequence, str], params: 'PrecomputedText.Params') -> 'PrecomputedText': ...
    def getBounds(self, int: int, int2: int, rect: android.graphics.Rect) -> None: ...
    def getFontMetricsInt(self, int: int, int2: int, fontMetricsInt: android.graphics.Paint.FontMetricsInt) -> None: ...
    def getParagraphCount(self) -> int: ...
    def getParagraphEnd(self, int: int) -> int: ...
    def getParagraphStart(self, int: int) -> int: ...
    def getParams(self) -> 'PrecomputedText.Params': ...
    def getSpanEnd(self, object: typing.Any) -> int: ...
    def getSpanFlags(self, object: typing.Any) -> int: ...
    def getSpanStart(self, object: typing.Any) -> int: ...
    _getSpans__T = typing.TypeVar('_getSpans__T')  # <T>
    def getSpans(self, int: int, int2: int, class_: typing.Type[_getSpans__T]) -> typing.MutableSequence[_getSpans__T]: ...
    def getWidth(self, int: int, int2: int) -> float: ...
    def length(self) -> int: ...
    def nextSpanTransition(self, int: int, int2: int, class_: typing.Type) -> int: ...
    def removeSpan(self, object: typing.Any) -> None: ...
    def setSpan(self, object: typing.Any, int: int, int2: int, int3: int) -> None: ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    class Params:
        def equals(self, object: typing.Any) -> bool: ...
        def getBreakStrategy(self) -> int: ...
        def getHyphenationFrequency(self) -> int: ...
        def getLineBreakConfig(self) -> android.graphics.text.LineBreakConfig: ...
        def getTextDirection(self) -> TextDirectionHeuristic: ...
        def getTextPaint(self) -> TextPaint: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
        class Builder:
            @typing.overload
            def __init__(self, params: 'PrecomputedText.Params'): ...
            @typing.overload
            def __init__(self, textPaint: TextPaint): ...
            def build(self) -> 'PrecomputedText.Params': ...
            def setBreakStrategy(self, int: int) -> 'PrecomputedText.Params.Builder': ...
            def setHyphenationFrequency(self, int: int) -> 'PrecomputedText.Params.Builder': ...
            def setLineBreakConfig(self, lineBreakConfig: android.graphics.text.LineBreakConfig) -> 'PrecomputedText.Params.Builder': ...
            def setTextDirection(self, textDirectionHeuristic: TextDirectionHeuristic) -> 'PrecomputedText.Params.Builder': ...

class SpannableString(java.lang.CharSequence, GetChars, Spannable):
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str]): ...
    def charAt(self, int: int) -> str: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getChars(self, int: int, int2: int, charArray: typing.Union[typing.List[str], jpype.JArray], int3: int) -> None: ...
    def getSpanEnd(self, object: typing.Any) -> int: ...
    def getSpanFlags(self, object: typing.Any) -> int: ...
    def getSpanStart(self, object: typing.Any) -> int: ...
    _getSpans__T = typing.TypeVar('_getSpans__T')  # <T>
    def getSpans(self, int: int, int2: int, class_: typing.Type[_getSpans__T]) -> typing.MutableSequence[_getSpans__T]: ...
    def hashCode(self) -> int: ...
    def length(self) -> int: ...
    def nextSpanTransition(self, int: int, int2: int, class_: typing.Type) -> int: ...
    def removeSpan(self, object: typing.Any) -> None: ...
    def setSpan(self, object: typing.Any, int: int, int2: int, int3: int) -> None: ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    @staticmethod
    def valueOf(charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SpannableString': ...

class SpannableStringBuilder(java.lang.CharSequence, GetChars, Spannable, Editable, java.lang.Appendable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str]): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int): ...
    @typing.overload
    def append(self, char: str) -> 'SpannableStringBuilder': ...
    @typing.overload
    def append(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SpannableStringBuilder': ...
    @typing.overload
    def append(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> 'SpannableStringBuilder': ...
    @typing.overload
    def append(self, charSequence: typing.Union[java.lang.CharSequence, str], object: typing.Any, int: int) -> 'SpannableStringBuilder': ...
    def charAt(self, int: int) -> str: ...
    def clear(self) -> None: ...
    def clearSpans(self) -> None: ...
    def delete(self, int: int, int2: int) -> 'SpannableStringBuilder': ...
    def equals(self, object: typing.Any) -> bool: ...
    def getChars(self, int: int, int2: int, charArray: typing.Union[typing.List[str], jpype.JArray], int3: int) -> None: ...
    def getFilters(self) -> typing.MutableSequence['InputFilter']: ...
    def getSpanEnd(self, object: typing.Any) -> int: ...
    def getSpanFlags(self, object: typing.Any) -> int: ...
    def getSpanStart(self, object: typing.Any) -> int: ...
    _getSpans__T = typing.TypeVar('_getSpans__T')  # <T>
    def getSpans(self, int: int, int2: int, class_: typing.Type[_getSpans__T]) -> typing.MutableSequence[_getSpans__T]: ...
    def getTextRunCursor(self, int: int, int2: int, int3: int, int4: int, int5: int, paint: android.graphics.Paint) -> int: ...
    def getTextWatcherDepth(self) -> int: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def insert(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SpannableStringBuilder': ...
    @typing.overload
    def insert(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str], int2: int, int3: int) -> 'SpannableStringBuilder': ...
    def length(self) -> int: ...
    def nextSpanTransition(self, int: int, int2: int, class_: typing.Type) -> int: ...
    def removeSpan(self, object: typing.Any) -> None: ...
    @typing.overload
    def replace(self, int: int, int2: int, charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SpannableStringBuilder': ...
    @typing.overload
    def replace(self, int: int, int2: int, charSequence: typing.Union[java.lang.CharSequence, str], int3: int, int4: int) -> 'SpannableStringBuilder': ...
    def setFilters(self, inputFilterArray: typing.Union[typing.List['InputFilter'], jpype.JArray]) -> None: ...
    def setSpan(self, object: typing.Any, int: int, int2: int, int3: int) -> None: ...
    def subSequence(self, int: int, int2: int) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...
    @staticmethod
    def valueOf(charSequence: typing.Union[java.lang.CharSequence, str]) -> 'SpannableStringBuilder': ...

class BoringLayout(Layout, android.text.TextUtils.EllipsizeCallback):
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int): ...
    @typing.overload
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int, boolean2: bool): ...
    def computeDrawingBoundingBox(self) -> android.graphics.RectF: ...
    @typing.overload
    def draw(self, canvas: android.graphics.Canvas, path: android.graphics.Path, paint: android.graphics.Paint, int: int) -> None: ...
    @typing.overload
    def draw(self, canvas: android.graphics.Canvas) -> None: ...
    @typing.overload
    def draw(self, canvas: android.graphics.Canvas, list: java.util.List[android.graphics.Path], list2: java.util.List[android.graphics.Paint], path: android.graphics.Path, paint: android.graphics.Paint, int: int) -> None: ...
    def ellipsized(self, int: int, int2: int) -> None: ...
    def getBottomPadding(self) -> int: ...
    def getEllipsisCount(self, int: int) -> int: ...
    def getEllipsisStart(self, int: int) -> int: ...
    def getEllipsizedWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getLineContainsTab(self, int: int) -> bool: ...
    def getLineCount(self) -> int: ...
    def getLineDescent(self, int: int) -> int: ...
    def getLineDirections(self, int: int) -> Layout.Directions: ...
    def getLineMax(self, int: int) -> float: ...
    def getLineStart(self, int: int) -> int: ...
    def getLineTop(self, int: int) -> int: ...
    def getLineWidth(self, int: int) -> float: ...
    def getParagraphDirection(self, int: int) -> int: ...
    def getTopPadding(self) -> int: ...
    @typing.overload
    @staticmethod
    def isBoring(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint) -> 'BoringLayout.Metrics': ...
    @typing.overload
    @staticmethod
    def isBoring(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, metrics: 'BoringLayout.Metrics') -> 'BoringLayout.Metrics': ...
    @typing.overload
    @staticmethod
    def isBoring(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, textDirectionHeuristic: TextDirectionHeuristic, boolean: bool, metrics: 'BoringLayout.Metrics') -> 'BoringLayout.Metrics': ...
    def isFallbackLineSpacingEnabled(self) -> bool: ...
    @typing.overload
    @staticmethod
    def make(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, metrics: 'BoringLayout.Metrics', boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int, boolean2: bool) -> 'BoringLayout': ...
    @typing.overload
    @staticmethod
    def make(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool) -> 'BoringLayout': ...
    @typing.overload
    @staticmethod
    def make(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int) -> 'BoringLayout': ...
    @typing.overload
    def replaceOrMake(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, metrics: 'BoringLayout.Metrics', boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int, boolean2: bool) -> 'BoringLayout': ...
    @typing.overload
    def replaceOrMake(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool) -> 'BoringLayout': ...
    @typing.overload
    def replaceOrMake(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, int: int, alignment: Layout.Alignment, float: float, float2: float, metrics: 'BoringLayout.Metrics', boolean: bool, truncateAt: 'TextUtils.TruncateAt', int2: int) -> 'BoringLayout': ...
    class Metrics(android.graphics.Paint.FontMetricsInt):
        width: int = ...
        def __init__(self): ...
        def getDrawingBoundingBox(self) -> android.graphics.RectF: ...
        def toString(self) -> str: ...

class GraphemeClusterSegmentFinder(android.text.SegmentFinder):
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint): ...
    def nextEndBoundary(self, int: int) -> int: ...
    def nextStartBoundary(self, int: int) -> int: ...
    def previousEndBoundary(self, int: int) -> int: ...
    def previousStartBoundary(self, int: int) -> int: ...

class InputFilter:
    def filter(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, spanned: Spanned, int3: int, int4: int) -> java.lang.CharSequence: ...
    class AllCaps(android.text.InputFilter):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, locale: java.util.Locale): ...
        def filter(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, spanned: Spanned, int3: int, int4: int) -> java.lang.CharSequence: ...
    class LengthFilter(android.text.InputFilter):
        def __init__(self, int: int): ...
        def filter(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, spanned: Spanned, int3: int, int4: int) -> java.lang.CharSequence: ...
        def getMax(self) -> int: ...

class LoginFilter(InputFilter):
    def filter(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, spanned: Spanned, int3: int, int4: int) -> java.lang.CharSequence: ...
    def isAllowed(self, char: str) -> bool: ...
    def onInvalidCharacter(self, char: str) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    class PasswordFilterGMail(android.text.LoginFilter):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, boolean: bool): ...
        def isAllowed(self, char: str) -> bool: ...
    class UsernameFilterGMail(android.text.LoginFilter):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, boolean: bool): ...
        def isAllowed(self, char: str) -> bool: ...
    class UsernameFilterGeneric(android.text.LoginFilter):
        @typing.overload
        def __init__(self): ...
        @typing.overload
        def __init__(self, boolean: bool): ...
        def isAllowed(self, char: str) -> bool: ...

class NoCopySpan:
    class Concrete(android.text.NoCopySpan):
        def __init__(self): ...

class SegmentFinder:
    DONE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def nextEndBoundary(self, int: int) -> int: ...
    def nextStartBoundary(self, int: int) -> int: ...
    def previousEndBoundary(self, int: int) -> int: ...
    def previousStartBoundary(self, int: int) -> int: ...
    class PrescribedSegmentFinder(android.text.SegmentFinder):
        def __init__(self, intArray: typing.Union[typing.List[int], jpype.JArray]): ...
        def nextEndBoundary(self, int: int) -> int: ...
        def nextStartBoundary(self, int: int) -> int: ...
        def previousEndBoundary(self, int: int) -> int: ...
        def previousStartBoundary(self, int: int) -> int: ...

class SpanWatcher(NoCopySpan):
    def onSpanAdded(self, spannable: Spannable, object: typing.Any, int: int, int2: int) -> None: ...
    def onSpanChanged(self, spannable: Spannable, object: typing.Any, int: int, int2: int, int3: int, int4: int) -> None: ...
    def onSpanRemoved(self, spannable: Spannable, object: typing.Any, int: int, int2: int) -> None: ...

class TextUtils:
    CAP_MODE_CHARACTERS: typing.ClassVar[int] = ...
    CAP_MODE_SENTENCES: typing.ClassVar[int] = ...
    CAP_MODE_WORDS: typing.ClassVar[int] = ...
    CHAR_SEQUENCE_CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SAFE_STRING_FLAG_FIRST_LINE: typing.ClassVar[int] = ...
    SAFE_STRING_FLAG_SINGLE_LINE: typing.ClassVar[int] = ...
    SAFE_STRING_FLAG_TRIM: typing.ClassVar[int] = ...
    @staticmethod
    def commaEllipsize(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, float: float, string: str, string2: str) -> java.lang.CharSequence: ...
    @staticmethod
    def concat(*charSequence: typing.Union[java.lang.CharSequence, str]) -> java.lang.CharSequence: ...
    @staticmethod
    def copySpansFrom(spanned: Spanned, int: int, int2: int, class_: typing.Type, spannable: Spannable, int3: int) -> None: ...
    @staticmethod
    def dumpSpans(charSequence: typing.Union[java.lang.CharSequence, str], printer: typing.Union[android.util.Printer, typing.Callable], string: str) -> None: ...
    @typing.overload
    @staticmethod
    def ellipsize(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, float: float, truncateAt: 'TextUtils.TruncateAt') -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def ellipsize(charSequence: typing.Union[java.lang.CharSequence, str], textPaint: TextPaint, float: float, truncateAt: 'TextUtils.TruncateAt', boolean: bool, ellipsizeCallback: typing.Union['TextUtils.EllipsizeCallback', typing.Callable]) -> java.lang.CharSequence: ...
    @typing.overload
    def equals(self, object: typing.Any) -> bool: ...
    @typing.overload
    @staticmethod
    def equals(charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str]) -> bool: ...
    @staticmethod
    def expandTemplate(charSequence: typing.Union[java.lang.CharSequence, str], *charSequence2: typing.Union[java.lang.CharSequence, str]) -> java.lang.CharSequence: ...
    @staticmethod
    def getCapsMode(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> int: ...
    @staticmethod
    def getChars(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, charArray: typing.Union[typing.List[str], jpype.JArray], int3: int) -> None: ...
    @staticmethod
    def getLayoutDirectionFromLocale(locale: java.util.Locale) -> int: ...
    @staticmethod
    def getOffsetAfter(charSequence: typing.Union[java.lang.CharSequence, str], int: int) -> int: ...
    @staticmethod
    def getOffsetBefore(charSequence: typing.Union[java.lang.CharSequence, str], int: int) -> int: ...
    @staticmethod
    def getReverse(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> java.lang.CharSequence: ...
    @staticmethod
    def getTrimmedLength(charSequence: typing.Union[java.lang.CharSequence, str]) -> int: ...
    @staticmethod
    def htmlEncode(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def indexOf(charSequence: typing.Union[java.lang.CharSequence, str], char2: str) -> int: ...
    @typing.overload
    @staticmethod
    def indexOf(charSequence: typing.Union[java.lang.CharSequence, str], char2: str, int: int) -> int: ...
    @typing.overload
    @staticmethod
    def indexOf(charSequence: typing.Union[java.lang.CharSequence, str], char2: str, int: int, int2: int) -> int: ...
    @typing.overload
    @staticmethod
    def indexOf(charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str]) -> int: ...
    @typing.overload
    @staticmethod
    def indexOf(charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], int: int) -> int: ...
    @typing.overload
    @staticmethod
    def indexOf(charSequence: typing.Union[java.lang.CharSequence, str], charSequence2: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> int: ...
    @staticmethod
    def isDigitsOnly(charSequence: typing.Union[java.lang.CharSequence, str]) -> bool: ...
    @staticmethod
    def isEmpty(charSequence: typing.Union[java.lang.CharSequence, str]) -> bool: ...
    @typing.overload
    @staticmethod
    def isGraphic(char: str) -> bool: ...
    @typing.overload
    @staticmethod
    def isGraphic(charSequence: typing.Union[java.lang.CharSequence, str]) -> bool: ...
    @typing.overload
    @staticmethod
    def join(charSequence: typing.Union[java.lang.CharSequence, str], iterable: typing.Union[java.lang.Iterable, typing.Sequence, typing.Set, typing.Callable]) -> str: ...
    @typing.overload
    @staticmethod
    def join(charSequence: typing.Union[java.lang.CharSequence, str], objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> str: ...
    @typing.overload
    @staticmethod
    def lastIndexOf(charSequence: typing.Union[java.lang.CharSequence, str], char2: str) -> int: ...
    @typing.overload
    @staticmethod
    def lastIndexOf(charSequence: typing.Union[java.lang.CharSequence, str], char2: str, int: int) -> int: ...
    @typing.overload
    @staticmethod
    def lastIndexOf(charSequence: typing.Union[java.lang.CharSequence, str], char2: str, int: int, int2: int) -> int: ...
    @staticmethod
    def listEllipsize(context: android.content.Context, list: java.util.List[typing.Union[java.lang.CharSequence, str]], string: str, textPaint: TextPaint, float: float, int: int) -> java.lang.CharSequence: ...
    @staticmethod
    def makeSafeForPresentation(string: str, int: int, float: float, int2: int) -> java.lang.CharSequence: ...
    @staticmethod
    def regionMatches(charSequence: typing.Union[java.lang.CharSequence, str], int: int, charSequence2: typing.Union[java.lang.CharSequence, str], int2: int, int3: int) -> bool: ...
    @staticmethod
    def replace(charSequence: typing.Union[java.lang.CharSequence, str], stringArray: typing.Union[typing.List[str], jpype.JArray], charSequenceArray: typing.Union[typing.List[java.lang.CharSequence], jpype.JArray]) -> java.lang.CharSequence: ...
    @typing.overload
    @staticmethod
    def split(string: str, string2: str) -> typing.MutableSequence[str]: ...
    @typing.overload
    @staticmethod
    def split(string: str, pattern: java.util.regex.Pattern) -> typing.MutableSequence[str]: ...
    @staticmethod
    def stringOrSpannedString(charSequence: typing.Union[java.lang.CharSequence, str]) -> java.lang.CharSequence: ...
    @staticmethod
    def substring(charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int) -> str: ...
    @staticmethod
    def writeToParcel(charSequence: typing.Union[java.lang.CharSequence, str], parcel: android.os.Parcel, int: int) -> None: ...
    class EllipsizeCallback:
        def ellipsized(self, int: int, int2: int) -> None: ...
    class SimpleStringSplitter(android.text.TextUtils.StringSplitter, java.util.Iterator[str]):
        def __init__(self, char: str): ...
        def hasNext(self) -> bool: ...
        def iterator(self) -> java.util.Iterator[str]: ...
        def next(self) -> str: ...
        def remove(self) -> None: ...
        def setString(self, string: str) -> None: ...
    class StringSplitter(java.lang.Iterable[str]):
        def setString(self, string: str) -> None: ...
    class TruncateAt(java.lang.Enum['TextUtils.TruncateAt']):
        START: typing.ClassVar['TextUtils.TruncateAt'] = ...
        MIDDLE: typing.ClassVar['TextUtils.TruncateAt'] = ...
        END: typing.ClassVar['TextUtils.TruncateAt'] = ...
        MARQUEE: typing.ClassVar['TextUtils.TruncateAt'] = ...
        _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'TextUtils.TruncateAt': ...
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
        @staticmethod
        def values() -> typing.MutableSequence['TextUtils.TruncateAt']: ...

class TextWatcher(NoCopySpan):
    def afterTextChanged(self, editable: Editable) -> None: ...
    def beforeTextChanged(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int) -> None: ...
    def onTextChanged(self, charSequence: typing.Union[java.lang.CharSequence, str], int: int, int2: int, int3: int) -> None: ...

class WordSegmentFinder(SegmentFinder):
    def __init__(self, charSequence: typing.Union[java.lang.CharSequence, str], uLocale: android.icu.util.ULocale): ...
    def nextEndBoundary(self, int: int) -> int: ...
    def nextStartBoundary(self, int: int) -> int: ...
    def previousEndBoundary(self, int: int) -> int: ...
    def previousStartBoundary(self, int: int) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.text")``.

    AlteredCharSequence: typing.Type[AlteredCharSequence]
    AndroidCharacter: typing.Type[AndroidCharacter]
    Annotation: typing.Type[Annotation]
    AutoText: typing.Type[AutoText]
    BidiFormatter: typing.Type[BidiFormatter]
    BoringLayout: typing.Type[BoringLayout]
    ClipboardManager: typing.Type[ClipboardManager]
    DynamicLayout: typing.Type[DynamicLayout]
    Editable: typing.Type[Editable]
    EmojiConsistency: typing.Type[EmojiConsistency]
    GetChars: typing.Type[GetChars]
    GraphemeClusterSegmentFinder: typing.Type[GraphemeClusterSegmentFinder]
    Highlights: typing.Type[Highlights]
    Html: typing.Type[Html]
    InputFilter: typing.Type[InputFilter]
    InputType: typing.Type[InputType]
    Layout: typing.Type[Layout]
    LoginFilter: typing.Type[LoginFilter]
    NoCopySpan: typing.Type[NoCopySpan]
    ParcelableSpan: typing.Type[ParcelableSpan]
    PrecomputedText: typing.Type[PrecomputedText]
    SegmentFinder: typing.Type[SegmentFinder]
    Selection: typing.Type[Selection]
    SpanWatcher: typing.Type[SpanWatcher]
    Spannable: typing.Type[Spannable]
    SpannableString: typing.Type[SpannableString]
    SpannableStringBuilder: typing.Type[SpannableStringBuilder]
    Spanned: typing.Type[Spanned]
    SpannedString: typing.Type[SpannedString]
    StaticLayout: typing.Type[StaticLayout]
    TextDirectionHeuristic: typing.Type[TextDirectionHeuristic]
    TextDirectionHeuristics: typing.Type[TextDirectionHeuristics]
    TextPaint: typing.Type[TextPaint]
    TextShaper: typing.Type[TextShaper]
    TextUtils: typing.Type[TextUtils]
    TextWatcher: typing.Type[TextWatcher]
    WordSegmentFinder: typing.Type[WordSegmentFinder]
    format: android.text.format.__module_protocol__
    method: android.text.method.__module_protocol__
    style: android.text.style.__module_protocol__
    util: android.text.util.__module_protocol__
