
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.accessibilityservice
import android.content.pm
import android.graphics
import android.os
import android.util
import android.view
import java.lang
import java.time
import java.util
import java.util.concurrent
import typing



class AccessibilityEventSource:
    def sendAccessibilityEvent(self, int: int) -> None: ...
    def sendAccessibilityEventUnchecked(self, accessibilityEvent: 'AccessibilityEvent') -> None: ...

class AccessibilityManager:
    FLAG_CONTENT_CONTROLS: typing.ClassVar[int] = ...
    FLAG_CONTENT_ICONS: typing.ClassVar[int] = ...
    FLAG_CONTENT_TEXT: typing.ClassVar[int] = ...
    def addAccessibilityRequestPreparer(self, accessibilityRequestPreparer: 'AccessibilityRequestPreparer') -> None: ...
    @typing.overload
    def addAccessibilityServicesStateChangeListener(self, accessibilityServicesStateChangeListener: typing.Union['AccessibilityManager.AccessibilityServicesStateChangeListener', typing.Callable]) -> None: ...
    @typing.overload
    def addAccessibilityServicesStateChangeListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], accessibilityServicesStateChangeListener: typing.Union['AccessibilityManager.AccessibilityServicesStateChangeListener', typing.Callable]) -> None: ...
    @typing.overload
    def addAccessibilityStateChangeListener(self, accessibilityStateChangeListener: typing.Union['AccessibilityManager.AccessibilityStateChangeListener', typing.Callable]) -> bool: ...
    @typing.overload
    def addAccessibilityStateChangeListener(self, accessibilityStateChangeListener: typing.Union['AccessibilityManager.AccessibilityStateChangeListener', typing.Callable], handler: android.os.Handler) -> None: ...
    def addAudioDescriptionRequestedChangeListener(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], audioDescriptionRequestedChangeListener: typing.Union['AccessibilityManager.AudioDescriptionRequestedChangeListener', typing.Callable]) -> None: ...
    @typing.overload
    def addTouchExplorationStateChangeListener(self, touchExplorationStateChangeListener: typing.Union['AccessibilityManager.TouchExplorationStateChangeListener', typing.Callable]) -> bool: ...
    @typing.overload
    def addTouchExplorationStateChangeListener(self, touchExplorationStateChangeListener: typing.Union['AccessibilityManager.TouchExplorationStateChangeListener', typing.Callable], handler: android.os.Handler) -> None: ...
    def getAccessibilityFocusColor(self) -> int: ...
    def getAccessibilityFocusStrokeWidth(self) -> int: ...
    def getAccessibilityServiceList(self) -> java.util.List[android.content.pm.ServiceInfo]: ...
    def getEnabledAccessibilityServiceList(self, int: int) -> java.util.List[android.accessibilityservice.AccessibilityServiceInfo]: ...
    def getInstalledAccessibilityServiceList(self) -> java.util.List[android.accessibilityservice.AccessibilityServiceInfo]: ...
    def getRecommendedTimeoutMillis(self, int: int, int2: int) -> int: ...
    def interrupt(self) -> None: ...
    @staticmethod
    def isAccessibilityButtonSupported() -> bool: ...
    def isAudioDescriptionRequested(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isRequestFromAccessibilityTool(self) -> bool: ...
    def isTouchExplorationEnabled(self) -> bool: ...
    def removeAccessibilityRequestPreparer(self, accessibilityRequestPreparer: 'AccessibilityRequestPreparer') -> None: ...
    def removeAccessibilityServicesStateChangeListener(self, accessibilityServicesStateChangeListener: typing.Union['AccessibilityManager.AccessibilityServicesStateChangeListener', typing.Callable]) -> bool: ...
    def removeAccessibilityStateChangeListener(self, accessibilityStateChangeListener: typing.Union['AccessibilityManager.AccessibilityStateChangeListener', typing.Callable]) -> bool: ...
    def removeAudioDescriptionRequestedChangeListener(self, audioDescriptionRequestedChangeListener: typing.Union['AccessibilityManager.AudioDescriptionRequestedChangeListener', typing.Callable]) -> bool: ...
    def removeTouchExplorationStateChangeListener(self, touchExplorationStateChangeListener: typing.Union['AccessibilityManager.TouchExplorationStateChangeListener', typing.Callable]) -> bool: ...
    def sendAccessibilityEvent(self, accessibilityEvent: 'AccessibilityEvent') -> None: ...
    class AccessibilityServicesStateChangeListener:
        def onAccessibilityServicesStateChanged(self, accessibilityManager: 'AccessibilityManager') -> None: ...
    class AccessibilityStateChangeListener:
        def onAccessibilityStateChanged(self, boolean: bool) -> None: ...
    class AudioDescriptionRequestedChangeListener:
        def onAudioDescriptionRequestedChanged(self, boolean: bool) -> None: ...
    class TouchExplorationStateChangeListener:
        def onTouchExplorationStateChanged(self, boolean: bool) -> None: ...

class AccessibilityNodeInfo(android.os.Parcelable):
    ACTION_ACCESSIBILITY_FOCUS: typing.ClassVar[int] = ...
    ACTION_ARGUMENT_COLUMN_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_DIRECTION_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_EXTEND_SELECTION_BOOLEAN: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_HTML_ELEMENT_STRING: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_MOVEMENT_GRANULARITY_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_MOVE_WINDOW_X: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_MOVE_WINDOW_Y: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_PRESS_AND_HOLD_DURATION_MILLIS_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_PROGRESS_VALUE: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_ROW_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_SCROLL_AMOUNT_FLOAT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_SELECTION_END_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_SELECTION_START_INT: typing.ClassVar[str] = ...
    ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE: typing.ClassVar[str] = ...
    ACTION_CLEAR_ACCESSIBILITY_FOCUS: typing.ClassVar[int] = ...
    ACTION_CLEAR_FOCUS: typing.ClassVar[int] = ...
    ACTION_CLEAR_SELECTION: typing.ClassVar[int] = ...
    ACTION_CLICK: typing.ClassVar[int] = ...
    ACTION_COLLAPSE: typing.ClassVar[int] = ...
    ACTION_COPY: typing.ClassVar[int] = ...
    ACTION_CUT: typing.ClassVar[int] = ...
    ACTION_DISMISS: typing.ClassVar[int] = ...
    ACTION_EXPAND: typing.ClassVar[int] = ...
    ACTION_FOCUS: typing.ClassVar[int] = ...
    ACTION_LONG_CLICK: typing.ClassVar[int] = ...
    ACTION_NEXT_AT_MOVEMENT_GRANULARITY: typing.ClassVar[int] = ...
    ACTION_NEXT_HTML_ELEMENT: typing.ClassVar[int] = ...
    ACTION_PASTE: typing.ClassVar[int] = ...
    ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: typing.ClassVar[int] = ...
    ACTION_PREVIOUS_HTML_ELEMENT: typing.ClassVar[int] = ...
    ACTION_SCROLL_BACKWARD: typing.ClassVar[int] = ...
    ACTION_SCROLL_FORWARD: typing.ClassVar[int] = ...
    ACTION_SELECT: typing.ClassVar[int] = ...
    ACTION_SET_SELECTION: typing.ClassVar[int] = ...
    ACTION_SET_TEXT: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EXTRA_DATA_RENDERING_INFO_KEY: typing.ClassVar[str] = ...
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_ARG_LENGTH: typing.ClassVar[str] = ...
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_ARG_MAX_LENGTH: typing.ClassVar[int] = ...
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_ARG_START_INDEX: typing.ClassVar[str] = ...
    EXTRA_DATA_TEXT_CHARACTER_LOCATION_KEY: typing.ClassVar[str] = ...
    FLAG_PREFETCH_ANCESTORS: typing.ClassVar[int] = ...
    FLAG_PREFETCH_DESCENDANTS_BREADTH_FIRST: typing.ClassVar[int] = ...
    FLAG_PREFETCH_DESCENDANTS_DEPTH_FIRST: typing.ClassVar[int] = ...
    FLAG_PREFETCH_DESCENDANTS_HYBRID: typing.ClassVar[int] = ...
    FLAG_PREFETCH_SIBLINGS: typing.ClassVar[int] = ...
    FLAG_PREFETCH_UNINTERRUPTIBLE: typing.ClassVar[int] = ...
    FOCUS_ACCESSIBILITY: typing.ClassVar[int] = ...
    FOCUS_INPUT: typing.ClassVar[int] = ...
    MAX_NUMBER_OF_PREFETCHED_NODES: typing.ClassVar[int] = ...
    MOVEMENT_GRANULARITY_CHARACTER: typing.ClassVar[int] = ...
    MOVEMENT_GRANULARITY_LINE: typing.ClassVar[int] = ...
    MOVEMENT_GRANULARITY_PAGE: typing.ClassVar[int] = ...
    MOVEMENT_GRANULARITY_PARAGRAPH: typing.ClassVar[int] = ...
    MOVEMENT_GRANULARITY_WORD: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, view: android.view.View): ...
    @typing.overload
    def __init__(self, view: android.view.View, int: int): ...
    @typing.overload
    def __init__(self, accessibilityNodeInfo: 'AccessibilityNodeInfo'): ...
    @typing.overload
    def addAction(self, accessibilityAction: 'AccessibilityNodeInfo.AccessibilityAction') -> None: ...
    @typing.overload
    def addAction(self, int: int) -> None: ...
    @typing.overload
    def addChild(self, view: android.view.View) -> None: ...
    @typing.overload
    def addChild(self, view: android.view.View, int: int) -> None: ...
    def canOpenPopup(self) -> bool: ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def findAccessibilityNodeInfosByText(self, string: str) -> java.util.List['AccessibilityNodeInfo']: ...
    def findAccessibilityNodeInfosByViewId(self, string: str) -> java.util.List['AccessibilityNodeInfo']: ...
    def findFocus(self, int: int) -> 'AccessibilityNodeInfo': ...
    def focusSearch(self, int: int) -> 'AccessibilityNodeInfo': ...
    def getActionList(self) -> java.util.List['AccessibilityNodeInfo.AccessibilityAction']: ...
    def getActions(self) -> int: ...
    def getAvailableExtraData(self) -> java.util.List[str]: ...
    def getBoundsInParent(self, rect: android.graphics.Rect) -> None: ...
    def getBoundsInScreen(self, rect: android.graphics.Rect) -> None: ...
    def getBoundsInWindow(self, rect: android.graphics.Rect) -> None: ...
    @typing.overload
    def getChild(self, int: int) -> 'AccessibilityNodeInfo': ...
    @typing.overload
    def getChild(self, int: int, int2: int) -> 'AccessibilityNodeInfo': ...
    def getChildCount(self) -> int: ...
    def getClassName(self) -> java.lang.CharSequence: ...
    def getCollectionInfo(self) -> 'AccessibilityNodeInfo.CollectionInfo': ...
    def getCollectionItemInfo(self) -> 'AccessibilityNodeInfo.CollectionItemInfo': ...
    def getContainerTitle(self) -> java.lang.CharSequence: ...
    def getContentDescription(self) -> java.lang.CharSequence: ...
    def getDrawingOrder(self) -> int: ...
    def getError(self) -> java.lang.CharSequence: ...
    def getExtraRenderingInfo(self) -> 'AccessibilityNodeInfo.ExtraRenderingInfo': ...
    def getExtras(self) -> android.os.Bundle: ...
    def getHintText(self) -> java.lang.CharSequence: ...
    def getInputType(self) -> int: ...
    def getLabelFor(self) -> 'AccessibilityNodeInfo': ...
    def getLabeledBy(self) -> 'AccessibilityNodeInfo': ...
    def getLiveRegion(self) -> int: ...
    def getMaxTextLength(self) -> int: ...
    def getMinDurationBetweenContentChanges(self) -> java.time.Duration: ...
    def getMovementGranularities(self) -> int: ...
    def getPackageName(self) -> java.lang.CharSequence: ...
    def getPaneTitle(self) -> java.lang.CharSequence: ...
    @typing.overload
    def getParent(self) -> 'AccessibilityNodeInfo': ...
    @typing.overload
    def getParent(self, int: int) -> 'AccessibilityNodeInfo': ...
    def getRangeInfo(self) -> 'AccessibilityNodeInfo.RangeInfo': ...
    def getStateDescription(self) -> java.lang.CharSequence: ...
    def getText(self) -> java.lang.CharSequence: ...
    def getTextSelectionEnd(self) -> int: ...
    def getTextSelectionStart(self) -> int: ...
    def getTooltipText(self) -> java.lang.CharSequence: ...
    def getTouchDelegateInfo(self) -> 'AccessibilityNodeInfo.TouchDelegateInfo': ...
    def getTraversalAfter(self) -> 'AccessibilityNodeInfo': ...
    def getTraversalBefore(self) -> 'AccessibilityNodeInfo': ...
    def getUniqueId(self) -> str: ...
    def getViewIdResourceName(self) -> str: ...
    def getWindow(self) -> 'AccessibilityWindowInfo': ...
    def getWindowId(self) -> int: ...
    def hasRequestInitialAccessibilityFocus(self) -> bool: ...
    def hashCode(self) -> int: ...
    def isAccessibilityDataSensitive(self) -> bool: ...
    def isAccessibilityFocused(self) -> bool: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def isClickable(self) -> bool: ...
    def isContentInvalid(self) -> bool: ...
    def isContextClickable(self) -> bool: ...
    def isDismissable(self) -> bool: ...
    def isEditable(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isFocusable(self) -> bool: ...
    def isFocused(self) -> bool: ...
    def isGranularScrollingSupported(self) -> bool: ...
    def isHeading(self) -> bool: ...
    def isImportantForAccessibility(self) -> bool: ...
    def isLongClickable(self) -> bool: ...
    def isMultiLine(self) -> bool: ...
    def isPassword(self) -> bool: ...
    def isScreenReaderFocusable(self) -> bool: ...
    def isScrollable(self) -> bool: ...
    def isSelected(self) -> bool: ...
    def isShowingHintText(self) -> bool: ...
    def isTextEntryKey(self) -> bool: ...
    def isTextSelectable(self) -> bool: ...
    def isVisibleToUser(self) -> bool: ...
    @typing.overload
    @staticmethod
    def obtain() -> 'AccessibilityNodeInfo': ...
    @typing.overload
    @staticmethod
    def obtain(view: android.view.View) -> 'AccessibilityNodeInfo': ...
    @typing.overload
    @staticmethod
    def obtain(view: android.view.View, int: int) -> 'AccessibilityNodeInfo': ...
    @typing.overload
    @staticmethod
    def obtain(accessibilityNodeInfo: 'AccessibilityNodeInfo') -> 'AccessibilityNodeInfo': ...
    @typing.overload
    def performAction(self, int: int) -> bool: ...
    @typing.overload
    def performAction(self, int: int, bundle: android.os.Bundle) -> bool: ...
    def recycle(self) -> None: ...
    def refresh(self) -> bool: ...
    def refreshWithExtraData(self, string: str, bundle: android.os.Bundle) -> bool: ...
    @typing.overload
    def removeAction(self, accessibilityAction: 'AccessibilityNodeInfo.AccessibilityAction') -> bool: ...
    @typing.overload
    def removeAction(self, int: int) -> None: ...
    @typing.overload
    def removeChild(self, view: android.view.View) -> bool: ...
    @typing.overload
    def removeChild(self, view: android.view.View, int: int) -> bool: ...
    def setAccessibilityDataSensitive(self, boolean: bool) -> None: ...
    def setAccessibilityFocused(self, boolean: bool) -> None: ...
    def setAvailableExtraData(self, list: java.util.List[str]) -> None: ...
    def setBoundsInParent(self, rect: android.graphics.Rect) -> None: ...
    def setBoundsInScreen(self, rect: android.graphics.Rect) -> None: ...
    def setBoundsInWindow(self, rect: android.graphics.Rect) -> None: ...
    def setCanOpenPopup(self, boolean: bool) -> None: ...
    def setCheckable(self, boolean: bool) -> None: ...
    def setChecked(self, boolean: bool) -> None: ...
    def setClassName(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setClickable(self, boolean: bool) -> None: ...
    def setCollectionInfo(self, collectionInfo: 'AccessibilityNodeInfo.CollectionInfo') -> None: ...
    def setCollectionItemInfo(self, collectionItemInfo: 'AccessibilityNodeInfo.CollectionItemInfo') -> None: ...
    def setContainerTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setContentDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setContentInvalid(self, boolean: bool) -> None: ...
    def setContextClickable(self, boolean: bool) -> None: ...
    def setDismissable(self, boolean: bool) -> None: ...
    def setDrawingOrder(self, int: int) -> None: ...
    def setEditable(self, boolean: bool) -> None: ...
    def setEnabled(self, boolean: bool) -> None: ...
    def setError(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setFocusable(self, boolean: bool) -> None: ...
    def setFocused(self, boolean: bool) -> None: ...
    def setGranularScrollingSupported(self, boolean: bool) -> None: ...
    def setHeading(self, boolean: bool) -> None: ...
    def setHintText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setImportantForAccessibility(self, boolean: bool) -> None: ...
    def setInputType(self, int: int) -> None: ...
    @typing.overload
    def setLabelFor(self, view: android.view.View) -> None: ...
    @typing.overload
    def setLabelFor(self, view: android.view.View, int: int) -> None: ...
    @typing.overload
    def setLabeledBy(self, view: android.view.View) -> None: ...
    @typing.overload
    def setLabeledBy(self, view: android.view.View, int: int) -> None: ...
    def setLiveRegion(self, int: int) -> None: ...
    def setLongClickable(self, boolean: bool) -> None: ...
    def setMaxTextLength(self, int: int) -> None: ...
    def setMinDurationBetweenContentChanges(self, duration: java.time.Duration) -> None: ...
    def setMovementGranularities(self, int: int) -> None: ...
    def setMultiLine(self, boolean: bool) -> None: ...
    def setPackageName(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setPaneTitle(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def setParent(self, view: android.view.View) -> None: ...
    @typing.overload
    def setParent(self, view: android.view.View, int: int) -> None: ...
    def setPassword(self, boolean: bool) -> None: ...
    def setQueryFromAppProcessEnabled(self, view: android.view.View, boolean: bool) -> None: ...
    def setRangeInfo(self, rangeInfo: 'AccessibilityNodeInfo.RangeInfo') -> None: ...
    def setRequestInitialAccessibilityFocus(self, boolean: bool) -> None: ...
    def setScreenReaderFocusable(self, boolean: bool) -> None: ...
    def setScrollable(self, boolean: bool) -> None: ...
    def setSelected(self, boolean: bool) -> None: ...
    def setShowingHintText(self, boolean: bool) -> None: ...
    @typing.overload
    def setSource(self, view: android.view.View) -> None: ...
    @typing.overload
    def setSource(self, view: android.view.View, int: int) -> None: ...
    def setStateDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setTextEntryKey(self, boolean: bool) -> None: ...
    def setTextSelectable(self, boolean: bool) -> None: ...
    def setTextSelection(self, int: int, int2: int) -> None: ...
    def setTooltipText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setTouchDelegateInfo(self, touchDelegateInfo: 'AccessibilityNodeInfo.TouchDelegateInfo') -> None: ...
    @typing.overload
    def setTraversalAfter(self, view: android.view.View) -> None: ...
    @typing.overload
    def setTraversalAfter(self, view: android.view.View, int: int) -> None: ...
    @typing.overload
    def setTraversalBefore(self, view: android.view.View) -> None: ...
    @typing.overload
    def setTraversalBefore(self, view: android.view.View, int: int) -> None: ...
    def setUniqueId(self, string: str) -> None: ...
    def setViewIdResourceName(self, string: str) -> None: ...
    def setVisibleToUser(self, boolean: bool) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class AccessibilityAction(android.os.Parcelable):
        ACTION_ACCESSIBILITY_FOCUS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_CLEAR_ACCESSIBILITY_FOCUS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_CLEAR_FOCUS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_CLEAR_SELECTION: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_CLICK: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_COLLAPSE: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_CONTEXT_CLICK: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_COPY: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_CUT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_DISMISS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_DRAG_CANCEL: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_DRAG_DROP: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_DRAG_START: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_EXPAND: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_FOCUS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_HIDE_TOOLTIP: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_IME_ENTER: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_LONG_CLICK: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_MOVE_WINDOW: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_NEXT_AT_MOVEMENT_GRANULARITY: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_NEXT_HTML_ELEMENT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PAGE_DOWN: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PAGE_LEFT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PAGE_RIGHT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PAGE_UP: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PASTE: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PRESS_AND_HOLD: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_PREVIOUS_HTML_ELEMENT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_BACKWARD: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_DOWN: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_FORWARD: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_IN_DIRECTION: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_LEFT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_RIGHT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_TO_POSITION: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SCROLL_UP: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SELECT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SET_PROGRESS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SET_SELECTION: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SET_TEXT: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SHOW_ON_SCREEN: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SHOW_TEXT_SUGGESTIONS: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        ACTION_SHOW_TOOLTIP: typing.ClassVar['AccessibilityNodeInfo.AccessibilityAction'] = ...
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def __init__(self, int: int, charSequence: typing.Union[java.lang.CharSequence, str]): ...
        def describeContents(self) -> int: ...
        def equals(self, object: typing.Any) -> bool: ...
        def getId(self) -> int: ...
        def getLabel(self) -> java.lang.CharSequence: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class CollectionInfo:
        SELECTION_MODE_MULTIPLE: typing.ClassVar[int] = ...
        SELECTION_MODE_NONE: typing.ClassVar[int] = ...
        SELECTION_MODE_SINGLE: typing.ClassVar[int] = ...
        UNDEFINED: typing.ClassVar[int] = ...
        @typing.overload
        def __init__(self, int: int, int2: int, boolean: bool): ...
        @typing.overload
        def __init__(self, int: int, int2: int, boolean: bool, int3: int): ...
        def getColumnCount(self) -> int: ...
        def getImportantForAccessibilityItemCount(self) -> int: ...
        def getItemCount(self) -> int: ...
        def getRowCount(self) -> int: ...
        def getSelectionMode(self) -> int: ...
        def isHierarchical(self) -> bool: ...
        @typing.overload
        @staticmethod
        def obtain(int: int, int2: int, boolean: bool) -> 'AccessibilityNodeInfo.CollectionInfo': ...
        @typing.overload
        @staticmethod
        def obtain(int: int, int2: int, boolean: bool, int3: int) -> 'AccessibilityNodeInfo.CollectionInfo': ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'AccessibilityNodeInfo.CollectionInfo': ...
            def setColumnCount(self, int: int) -> 'AccessibilityNodeInfo.CollectionInfo.Builder': ...
            def setHierarchical(self, boolean: bool) -> 'AccessibilityNodeInfo.CollectionInfo.Builder': ...
            def setImportantForAccessibilityItemCount(self, int: int) -> 'AccessibilityNodeInfo.CollectionInfo.Builder': ...
            def setItemCount(self, int: int) -> 'AccessibilityNodeInfo.CollectionInfo.Builder': ...
            def setRowCount(self, int: int) -> 'AccessibilityNodeInfo.CollectionInfo.Builder': ...
            def setSelectionMode(self, int: int) -> 'AccessibilityNodeInfo.CollectionInfo.Builder': ...
    class CollectionItemInfo:
        @typing.overload
        def __init__(self, int: int, int2: int, int3: int, int4: int, boolean: bool): ...
        @typing.overload
        def __init__(self, int: int, int2: int, int3: int, int4: int, boolean: bool, boolean2: bool): ...
        def getColumnIndex(self) -> int: ...
        def getColumnSpan(self) -> int: ...
        def getColumnTitle(self) -> str: ...
        def getRowIndex(self) -> int: ...
        def getRowSpan(self) -> int: ...
        def getRowTitle(self) -> str: ...
        def isHeading(self) -> bool: ...
        def isSelected(self) -> bool: ...
        @typing.overload
        @staticmethod
        def obtain(int: int, int2: int, int3: int, int4: int, boolean: bool) -> 'AccessibilityNodeInfo.CollectionItemInfo': ...
        @typing.overload
        @staticmethod
        def obtain(int: int, int2: int, int3: int, int4: int, boolean: bool, boolean2: bool) -> 'AccessibilityNodeInfo.CollectionItemInfo': ...
        class Builder:
            def __init__(self): ...
            def build(self) -> 'AccessibilityNodeInfo.CollectionItemInfo': ...
            def setColumnIndex(self, int: int) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setColumnSpan(self, int: int) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setColumnTitle(self, string: str) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setHeading(self, boolean: bool) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setRowIndex(self, int: int) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setRowSpan(self, int: int) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setRowTitle(self, string: str) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
            def setSelected(self, boolean: bool) -> 'AccessibilityNodeInfo.CollectionItemInfo.Builder': ...
    class ExtraRenderingInfo:
        def getLayoutSize(self) -> android.util.Size: ...
        def getTextSizeInPx(self) -> float: ...
        def getTextSizeUnit(self) -> int: ...
    class RangeInfo:
        RANGE_TYPE_FLOAT: typing.ClassVar[int] = ...
        RANGE_TYPE_INT: typing.ClassVar[int] = ...
        RANGE_TYPE_PERCENT: typing.ClassVar[int] = ...
        def __init__(self, int: int, float: float, float2: float, float3: float): ...
        def getCurrent(self) -> float: ...
        def getMax(self) -> float: ...
        def getMin(self) -> float: ...
        def getType(self) -> int: ...
        @staticmethod
        def obtain(int: int, float: float, float2: float, float3: float) -> 'AccessibilityNodeInfo.RangeInfo': ...
    class TouchDelegateInfo(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
        def __init__(self, map: typing.Union[java.util.Map[android.graphics.Region, android.view.View], typing.Mapping[android.graphics.Region, android.view.View]]): ...
        def describeContents(self) -> int: ...
        def getRegionAt(self, int: int) -> android.graphics.Region: ...
        def getRegionCount(self) -> int: ...
        def getTargetForRegion(self, region: android.graphics.Region) -> 'AccessibilityNodeInfo': ...
        def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AccessibilityNodeProvider:
    HOST_VIEW_ID: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addExtraDataToAccessibilityNodeInfo(self, int: int, accessibilityNodeInfo: AccessibilityNodeInfo, string: str, bundle: android.os.Bundle) -> None: ...
    def createAccessibilityNodeInfo(self, int: int) -> AccessibilityNodeInfo: ...
    def findAccessibilityNodeInfosByText(self, string: str, int: int) -> java.util.List[AccessibilityNodeInfo]: ...
    def findFocus(self, int: int) -> AccessibilityNodeInfo: ...
    def performAction(self, int: int, int2: int, bundle: android.os.Bundle) -> bool: ...

class AccessibilityRecord:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, accessibilityRecord: 'AccessibilityRecord'): ...
    def getAddedCount(self) -> int: ...
    def getBeforeText(self) -> java.lang.CharSequence: ...
    def getClassName(self) -> java.lang.CharSequence: ...
    def getContentDescription(self) -> java.lang.CharSequence: ...
    def getCurrentItemIndex(self) -> int: ...
    def getDisplayId(self) -> int: ...
    def getFromIndex(self) -> int: ...
    def getItemCount(self) -> int: ...
    def getMaxScrollX(self) -> int: ...
    def getMaxScrollY(self) -> int: ...
    def getParcelableData(self) -> android.os.Parcelable: ...
    def getRemovedCount(self) -> int: ...
    def getScrollDeltaX(self) -> int: ...
    def getScrollDeltaY(self) -> int: ...
    def getScrollX(self) -> int: ...
    def getScrollY(self) -> int: ...
    @typing.overload
    def getSource(self) -> AccessibilityNodeInfo: ...
    @typing.overload
    def getSource(self, int: int) -> AccessibilityNodeInfo: ...
    def getText(self) -> java.util.List[java.lang.CharSequence]: ...
    def getToIndex(self) -> int: ...
    def getWindowId(self) -> int: ...
    def isChecked(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isFullScreen(self) -> bool: ...
    def isPassword(self) -> bool: ...
    def isScrollable(self) -> bool: ...
    @typing.overload
    @staticmethod
    def obtain() -> 'AccessibilityRecord': ...
    @typing.overload
    @staticmethod
    def obtain(accessibilityRecord: 'AccessibilityRecord') -> 'AccessibilityRecord': ...
    def recycle(self) -> None: ...
    def setAddedCount(self, int: int) -> None: ...
    def setBeforeText(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setChecked(self, boolean: bool) -> None: ...
    def setClassName(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setContentDescription(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setCurrentItemIndex(self, int: int) -> None: ...
    def setEnabled(self, boolean: bool) -> None: ...
    def setFromIndex(self, int: int) -> None: ...
    def setFullScreen(self, boolean: bool) -> None: ...
    def setItemCount(self, int: int) -> None: ...
    def setMaxScrollX(self, int: int) -> None: ...
    def setMaxScrollY(self, int: int) -> None: ...
    def setParcelableData(self, parcelable: android.os.Parcelable) -> None: ...
    def setPassword(self, boolean: bool) -> None: ...
    def setRemovedCount(self, int: int) -> None: ...
    def setScrollDeltaX(self, int: int) -> None: ...
    def setScrollDeltaY(self, int: int) -> None: ...
    def setScrollX(self, int: int) -> None: ...
    def setScrollY(self, int: int) -> None: ...
    def setScrollable(self, boolean: bool) -> None: ...
    @typing.overload
    def setSource(self, view: android.view.View) -> None: ...
    @typing.overload
    def setSource(self, view: android.view.View, int: int) -> None: ...
    def setToIndex(self, int: int) -> None: ...
    def toString(self) -> str: ...

class AccessibilityRequestPreparer:
    REQUEST_TYPE_EXTRA_DATA: typing.ClassVar[int] = ...
    def __init__(self, view: android.view.View, int: int): ...
    def getView(self) -> android.view.View: ...
    def onPrepareExtraData(self, int: int, string: str, bundle: android.os.Bundle, message: android.os.Message) -> None: ...

class AccessibilityWindowInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_ACCESSIBILITY_OVERLAY: typing.ClassVar[int] = ...
    TYPE_APPLICATION: typing.ClassVar[int] = ...
    TYPE_INPUT_METHOD: typing.ClassVar[int] = ...
    TYPE_MAGNIFICATION_OVERLAY: typing.ClassVar[int] = ...
    TYPE_SPLIT_SCREEN_DIVIDER: typing.ClassVar[int] = ...
    TYPE_SYSTEM: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, accessibilityWindowInfo: 'AccessibilityWindowInfo'): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAnchor(self) -> AccessibilityNodeInfo: ...
    def getBoundsInScreen(self, rect: android.graphics.Rect) -> None: ...
    def getChild(self, int: int) -> 'AccessibilityWindowInfo': ...
    def getChildCount(self) -> int: ...
    def getDisplayId(self) -> int: ...
    def getId(self) -> int: ...
    def getLayer(self) -> int: ...
    def getLocales(self) -> android.os.LocaleList: ...
    def getParent(self) -> 'AccessibilityWindowInfo': ...
    def getRegionInScreen(self, region: android.graphics.Region) -> None: ...
    @typing.overload
    def getRoot(self) -> AccessibilityNodeInfo: ...
    @typing.overload
    def getRoot(self, int: int) -> AccessibilityNodeInfo: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def getTransitionTimeMillis(self) -> int: ...
    def getType(self) -> int: ...
    def hashCode(self) -> int: ...
    def isAccessibilityFocused(self) -> bool: ...
    def isActive(self) -> bool: ...
    def isFocused(self) -> bool: ...
    def isInPictureInPictureMode(self) -> bool: ...
    @typing.overload
    @staticmethod
    def obtain() -> 'AccessibilityWindowInfo': ...
    @typing.overload
    @staticmethod
    def obtain(accessibilityWindowInfo: 'AccessibilityWindowInfo') -> 'AccessibilityWindowInfo': ...
    def recycle(self) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CaptioningManager:
    def addCaptioningChangeListener(self, captioningChangeListener: 'CaptioningManager.CaptioningChangeListener') -> None: ...
    def getFontScale(self) -> float: ...
    def getLocale(self) -> java.util.Locale: ...
    def getUserStyle(self) -> 'CaptioningManager.CaptionStyle': ...
    def isCallCaptioningEnabled(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isSystemAudioCaptioningEnabled(self) -> bool: ...
    def isSystemAudioCaptioningUiEnabled(self) -> bool: ...
    def removeCaptioningChangeListener(self, captioningChangeListener: 'CaptioningManager.CaptioningChangeListener') -> None: ...
    class CaptionStyle:
        EDGE_TYPE_DEPRESSED: typing.ClassVar[int] = ...
        EDGE_TYPE_DROP_SHADOW: typing.ClassVar[int] = ...
        EDGE_TYPE_NONE: typing.ClassVar[int] = ...
        EDGE_TYPE_OUTLINE: typing.ClassVar[int] = ...
        EDGE_TYPE_RAISED: typing.ClassVar[int] = ...
        EDGE_TYPE_UNSPECIFIED: typing.ClassVar[int] = ...
        backgroundColor: int = ...
        edgeColor: int = ...
        edgeType: int = ...
        foregroundColor: int = ...
        windowColor: int = ...
        def getTypeface(self) -> android.graphics.Typeface: ...
        def hasBackgroundColor(self) -> bool: ...
        def hasEdgeColor(self) -> bool: ...
        def hasEdgeType(self) -> bool: ...
        def hasForegroundColor(self) -> bool: ...
        def hasWindowColor(self) -> bool: ...
    class CaptioningChangeListener:
        def __init__(self): ...
        def onEnabledChanged(self, boolean: bool) -> None: ...
        def onFontScaleChanged(self, float: float) -> None: ...
        def onLocaleChanged(self, locale: java.util.Locale) -> None: ...
        def onSystemAudioCaptioningChanged(self, boolean: bool) -> None: ...
        def onSystemAudioCaptioningUiChanged(self, boolean: bool) -> None: ...
        def onUserStyleChanged(self, captionStyle: 'CaptioningManager.CaptionStyle') -> None: ...

class AccessibilityEvent(AccessibilityRecord, android.os.Parcelable):
    CONTENT_CHANGE_TYPE_CONTENT_DESCRIPTION: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_CONTENT_INVALID: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_DRAG_CANCELLED: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_DRAG_DROPPED: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_DRAG_STARTED: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_ENABLED: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_ERROR: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_PANE_APPEARED: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_PANE_DISAPPEARED: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_PANE_TITLE: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_STATE_DESCRIPTION: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_SUBTREE: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_TEXT: typing.ClassVar[int] = ...
    CONTENT_CHANGE_TYPE_UNDEFINED: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    INVALID_POSITION: typing.ClassVar[int] = ...
    MAX_TEXT_LENGTH: typing.ClassVar[int] = ...
    SPEECH_STATE_LISTENING_END: typing.ClassVar[int] = ...
    SPEECH_STATE_LISTENING_START: typing.ClassVar[int] = ...
    SPEECH_STATE_SPEAKING_END: typing.ClassVar[int] = ...
    SPEECH_STATE_SPEAKING_START: typing.ClassVar[int] = ...
    TYPES_ALL_MASK: typing.ClassVar[int] = ...
    TYPE_ANNOUNCEMENT: typing.ClassVar[int] = ...
    TYPE_ASSIST_READING_CONTEXT: typing.ClassVar[int] = ...
    TYPE_GESTURE_DETECTION_END: typing.ClassVar[int] = ...
    TYPE_GESTURE_DETECTION_START: typing.ClassVar[int] = ...
    TYPE_NOTIFICATION_STATE_CHANGED: typing.ClassVar[int] = ...
    TYPE_SPEECH_STATE_CHANGE: typing.ClassVar[int] = ...
    TYPE_TOUCH_EXPLORATION_GESTURE_END: typing.ClassVar[int] = ...
    TYPE_TOUCH_EXPLORATION_GESTURE_START: typing.ClassVar[int] = ...
    TYPE_TOUCH_INTERACTION_END: typing.ClassVar[int] = ...
    TYPE_TOUCH_INTERACTION_START: typing.ClassVar[int] = ...
    TYPE_VIEW_ACCESSIBILITY_FOCUSED: typing.ClassVar[int] = ...
    TYPE_VIEW_ACCESSIBILITY_FOCUS_CLEARED: typing.ClassVar[int] = ...
    TYPE_VIEW_CLICKED: typing.ClassVar[int] = ...
    TYPE_VIEW_CONTEXT_CLICKED: typing.ClassVar[int] = ...
    TYPE_VIEW_FOCUSED: typing.ClassVar[int] = ...
    TYPE_VIEW_HOVER_ENTER: typing.ClassVar[int] = ...
    TYPE_VIEW_HOVER_EXIT: typing.ClassVar[int] = ...
    TYPE_VIEW_LONG_CLICKED: typing.ClassVar[int] = ...
    TYPE_VIEW_SCROLLED: typing.ClassVar[int] = ...
    TYPE_VIEW_SELECTED: typing.ClassVar[int] = ...
    TYPE_VIEW_TARGETED_BY_SCROLL: typing.ClassVar[int] = ...
    TYPE_VIEW_TEXT_CHANGED: typing.ClassVar[int] = ...
    TYPE_VIEW_TEXT_SELECTION_CHANGED: typing.ClassVar[int] = ...
    TYPE_VIEW_TEXT_TRAVERSED_AT_MOVEMENT_GRANULARITY: typing.ClassVar[int] = ...
    TYPE_WINDOWS_CHANGED: typing.ClassVar[int] = ...
    TYPE_WINDOW_CONTENT_CHANGED: typing.ClassVar[int] = ...
    TYPE_WINDOW_STATE_CHANGED: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_ACCESSIBILITY_FOCUSED: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_ACTIVE: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_ADDED: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_BOUNDS: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_CHILDREN: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_FOCUSED: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_LAYER: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_PARENT: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_PIP: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_REMOVED: typing.ClassVar[int] = ...
    WINDOWS_CHANGE_TITLE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, accessibilityEvent: 'AccessibilityEvent'): ...
    @typing.overload
    def __init__(self, int: int): ...
    def appendRecord(self, accessibilityRecord: AccessibilityRecord) -> None: ...
    def describeContents(self) -> int: ...
    @staticmethod
    def eventTypeToString(int: int) -> str: ...
    def getAction(self) -> int: ...
    def getContentChangeTypes(self) -> int: ...
    def getEventTime(self) -> int: ...
    def getEventType(self) -> int: ...
    def getMovementGranularity(self) -> int: ...
    def getPackageName(self) -> java.lang.CharSequence: ...
    def getRecord(self, int: int) -> AccessibilityRecord: ...
    def getRecordCount(self) -> int: ...
    def getSpeechStateChangeTypes(self) -> int: ...
    def getWindowChanges(self) -> int: ...
    def initFromParcel(self, parcel: android.os.Parcel) -> None: ...
    def isAccessibilityDataSensitive(self) -> bool: ...
    @typing.overload
    @staticmethod
    def obtain() -> 'AccessibilityEvent': ...
    @typing.overload
    @staticmethod
    def obtain(accessibilityEvent: 'AccessibilityEvent') -> 'AccessibilityEvent': ...
    @typing.overload
    @staticmethod
    def obtain(int: int) -> 'AccessibilityEvent': ...
    @typing.overload
    @staticmethod
    def obtain() -> AccessibilityRecord: ...
    @typing.overload
    @staticmethod
    def obtain(accessibilityRecord: AccessibilityRecord) -> AccessibilityRecord: ...
    def recycle(self) -> None: ...
    def setAccessibilityDataSensitive(self, boolean: bool) -> None: ...
    def setAction(self, int: int) -> None: ...
    def setContentChangeTypes(self, int: int) -> None: ...
    def setEventTime(self, long: int) -> None: ...
    def setEventType(self, int: int) -> None: ...
    def setMovementGranularity(self, int: int) -> None: ...
    def setPackageName(self, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    def setSpeechStateChangeTypes(self, int: int) -> None: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.view.accessibility")``.

    AccessibilityEvent: typing.Type[AccessibilityEvent]
    AccessibilityEventSource: typing.Type[AccessibilityEventSource]
    AccessibilityManager: typing.Type[AccessibilityManager]
    AccessibilityNodeInfo: typing.Type[AccessibilityNodeInfo]
    AccessibilityNodeProvider: typing.Type[AccessibilityNodeProvider]
    AccessibilityRecord: typing.Type[AccessibilityRecord]
    AccessibilityRequestPreparer: typing.Type[AccessibilityRequestPreparer]
    AccessibilityWindowInfo: typing.Type[AccessibilityWindowInfo]
    CaptioningManager: typing.Type[CaptioningManager]
