
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.os
import android.service.credentials
import java.lang
import java.util
import java.util.concurrent
import typing



class ClearCredentialStateException(java.lang.Exception):
    TYPE_UNKNOWN: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    def getType(self) -> str: ...

class ClearCredentialStateRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getData(self) -> android.os.Bundle: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CreateCredentialException(java.lang.Exception):
    TYPE_INTERRUPTED: typing.ClassVar[str] = ...
    TYPE_NO_CREATE_OPTIONS: typing.ClassVar[str] = ...
    TYPE_UNKNOWN: typing.ClassVar[str] = ...
    TYPE_USER_CANCELED: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    def getType(self) -> str: ...

class CreateCredentialRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def alwaysSendAppInfoToProvider(self) -> bool: ...
    def describeContents(self) -> int: ...
    def getCandidateQueryData(self) -> android.os.Bundle: ...
    def getCredentialData(self) -> android.os.Bundle: ...
    def getOrigin(self) -> str: ...
    def getType(self) -> str: ...
    def isSystemProviderRequired(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str, bundle: android.os.Bundle, bundle2: android.os.Bundle): ...
        def build(self) -> 'CreateCredentialRequest': ...
        def setAlwaysSendAppInfoToProvider(self, boolean: bool) -> 'CreateCredentialRequest.Builder': ...
        def setIsSystemProviderRequired(self, boolean: bool) -> 'CreateCredentialRequest.Builder': ...
        def setOrigin(self, string: str) -> 'CreateCredentialRequest.Builder': ...

class CreateCredentialResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getData(self) -> android.os.Bundle: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class Credential(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    TYPE_PASSWORD_CREDENTIAL: typing.ClassVar[str] = ...
    def __init__(self, string: str, bundle: android.os.Bundle): ...
    def describeContents(self) -> int: ...
    def getData(self) -> android.os.Bundle: ...
    def getType(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CredentialDescription(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, string: str, set: java.util.Set[str], list: java.util.List[android.service.credentials.CredentialEntry]): ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getCredentialEntries(self) -> java.util.List[android.service.credentials.CredentialEntry]: ...
    def getSupportedElementKeys(self) -> java.util.Set[str]: ...
    def getType(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class CredentialManager:
    def clearCredentialState(self, clearCredentialStateRequest: ClearCredentialStateRequest, cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[None, ClearCredentialStateException], typing.Callable[[None], None]]) -> None: ...
    def createCredential(self, context: android.content.Context, createCredentialRequest: CreateCredentialRequest, cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[CreateCredentialResponse, CreateCredentialException], typing.Callable[[CreateCredentialResponse], None]]) -> None: ...
    @typing.overload
    def getCredential(self, context: android.content.Context, getCredentialRequest: 'GetCredentialRequest', cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['GetCredentialResponse', 'GetCredentialException'], typing.Callable[['GetCredentialResponse'], None]]) -> None: ...
    @typing.overload
    def getCredential(self, context: android.content.Context, pendingGetCredentialHandle: 'PrepareGetCredentialResponse.PendingGetCredentialHandle', cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['GetCredentialResponse', 'GetCredentialException'], typing.Callable[['GetCredentialResponse'], None]]) -> None: ...
    def isEnabledCredentialProviderService(self, componentName: android.content.ComponentName) -> bool: ...
    def prepareGetCredential(self, getCredentialRequest: 'GetCredentialRequest', cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['PrepareGetCredentialResponse', 'GetCredentialException'], typing.Callable[['PrepareGetCredentialResponse'], None]]) -> None: ...
    def registerCredentialDescription(self, registerCredentialDescriptionRequest: 'RegisterCredentialDescriptionRequest') -> None: ...
    def unregisterCredentialDescription(self, unregisterCredentialDescriptionRequest: 'UnregisterCredentialDescriptionRequest') -> None: ...

class CredentialOption(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    SUPPORTED_ELEMENT_KEYS: typing.ClassVar[str] = ...
    def describeContents(self) -> int: ...
    def getAllowedProviders(self) -> java.util.Set[android.content.ComponentName]: ...
    def getCandidateQueryData(self) -> android.os.Bundle: ...
    def getCredentialRetrievalData(self) -> android.os.Bundle: ...
    def getType(self) -> str: ...
    def isSystemProviderRequired(self) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, string: str, bundle: android.os.Bundle, bundle2: android.os.Bundle): ...
        def addAllowedProvider(self, componentName: android.content.ComponentName) -> 'CredentialOption.Builder': ...
        def build(self) -> 'CredentialOption': ...
        def setAllowedProviders(self, set: java.util.Set[android.content.ComponentName]) -> 'CredentialOption.Builder': ...
        def setIsSystemProviderRequired(self, boolean: bool) -> 'CredentialOption.Builder': ...

class GetCredentialException(java.lang.Exception):
    TYPE_INTERRUPTED: typing.ClassVar[str] = ...
    TYPE_NO_CREDENTIAL: typing.ClassVar[str] = ...
    TYPE_UNKNOWN: typing.ClassVar[str] = ...
    TYPE_USER_CANCELED: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str): ...
    @typing.overload
    def __init__(self, string: str, string2: str, throwable: java.lang.Throwable): ...
    @typing.overload
    def __init__(self, string: str, throwable: java.lang.Throwable): ...
    def getType(self) -> str: ...

class GetCredentialRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def alwaysSendAppInfoToProvider(self) -> bool: ...
    def describeContents(self) -> int: ...
    def getCredentialOptions(self) -> java.util.List[CredentialOption]: ...
    def getData(self) -> android.os.Bundle: ...
    def getOrigin(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, bundle: android.os.Bundle): ...
        def addCredentialOption(self, credentialOption: CredentialOption) -> 'GetCredentialRequest.Builder': ...
        def build(self) -> 'GetCredentialRequest': ...
        def setAlwaysSendAppInfoToProvider(self, boolean: bool) -> 'GetCredentialRequest.Builder': ...
        def setCredentialOptions(self, list: java.util.List[CredentialOption]) -> 'GetCredentialRequest.Builder': ...
        def setOrigin(self, string: str) -> 'GetCredentialRequest.Builder': ...

class GetCredentialResponse(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def __init__(self, credential: Credential): ...
    def describeContents(self) -> int: ...
    def getCredential(self) -> Credential: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class PrepareGetCredentialResponse:
    def getPendingGetCredentialHandle(self) -> 'PrepareGetCredentialResponse.PendingGetCredentialHandle': ...
    def hasAuthenticationResults(self) -> bool: ...
    def hasCredentialResults(self, string: str) -> bool: ...
    def hasRemoteResults(self) -> bool: ...
    class PendingGetCredentialHandle: ...

class RegisterCredentialDescriptionRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, credentialDescription: CredentialDescription): ...
    @typing.overload
    def __init__(self, set: java.util.Set[CredentialDescription]): ...
    def describeContents(self) -> int: ...
    def getCredentialDescriptions(self) -> java.util.Set[CredentialDescription]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class UnregisterCredentialDescriptionRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @typing.overload
    def __init__(self, credentialDescription: CredentialDescription): ...
    @typing.overload
    def __init__(self, set: java.util.Set[CredentialDescription]): ...
    def describeContents(self) -> int: ...
    def getCredentialDescriptions(self) -> java.util.Set[CredentialDescription]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.credentials")``.

    ClearCredentialStateException: typing.Type[ClearCredentialStateException]
    ClearCredentialStateRequest: typing.Type[ClearCredentialStateRequest]
    CreateCredentialException: typing.Type[CreateCredentialException]
    CreateCredentialRequest: typing.Type[CreateCredentialRequest]
    CreateCredentialResponse: typing.Type[CreateCredentialResponse]
    Credential: typing.Type[Credential]
    CredentialDescription: typing.Type[CredentialDescription]
    CredentialManager: typing.Type[CredentialManager]
    CredentialOption: typing.Type[CredentialOption]
    GetCredentialException: typing.Type[GetCredentialException]
    GetCredentialRequest: typing.Type[GetCredentialRequest]
    GetCredentialResponse: typing.Type[GetCredentialResponse]
    PrepareGetCredentialResponse: typing.Type[PrepareGetCredentialResponse]
    RegisterCredentialDescriptionRequest: typing.Type[RegisterCredentialDescriptionRequest]
    UnregisterCredentialDescriptionRequest: typing.Type[UnregisterCredentialDescriptionRequest]
