
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.os
import java.io
import java.lang
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class BlobHandle(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    @staticmethod
    def createWithSha256(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], charSequence: typing.Union[java.lang.CharSequence, str], long: int, string: str) -> 'BlobHandle': ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExpiryTimeMillis(self) -> int: ...
    def getLabel(self) -> java.lang.CharSequence: ...
    def getSha256Digest(self) -> typing.MutableSequence[int]: ...
    def getTag(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class BlobStoreManager:
    def abandonSession(self, long: int) -> None: ...
    @typing.overload
    def acquireLease(self, blobHandle: BlobHandle, int: int) -> None: ...
    @typing.overload
    def acquireLease(self, blobHandle: BlobHandle, int: int, long: int) -> None: ...
    @typing.overload
    def acquireLease(self, blobHandle: BlobHandle, charSequence: typing.Union[java.lang.CharSequence, str]) -> None: ...
    @typing.overload
    def acquireLease(self, blobHandle: BlobHandle, charSequence: typing.Union[java.lang.CharSequence, str], long: int) -> None: ...
    def createSession(self, blobHandle: BlobHandle) -> int: ...
    def getLeasedBlobs(self) -> java.util.List[BlobHandle]: ...
    def getRemainingLeaseQuotaBytes(self) -> int: ...
    def openBlob(self, blobHandle: BlobHandle) -> android.os.ParcelFileDescriptor: ...
    def openSession(self, long: int) -> 'BlobStoreManager.Session': ...
    def releaseLease(self, blobHandle: BlobHandle) -> None: ...
    class Session(java.io.Closeable):
        def abandon(self) -> None: ...
        def allowPackageAccess(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
        def allowPublicAccess(self) -> None: ...
        def allowSameSignatureAccess(self) -> None: ...
        def close(self) -> None: ...
        def commit(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[int], typing.Callable[[int], None]]) -> None: ...
        def getSize(self) -> int: ...
        def isPackageAccessAllowed(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> bool: ...
        def isPublicAccessAllowed(self) -> bool: ...
        def isSameSignatureAccessAllowed(self) -> bool: ...
        def openRead(self) -> android.os.ParcelFileDescriptor: ...
        def openWrite(self, long: int, long2: int) -> android.os.ParcelFileDescriptor: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.app.blob")``.

    BlobHandle: typing.Type[BlobHandle]
    BlobStoreManager: typing.Type[BlobStoreManager]
