
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android
import android.app
import android.app.assist
import android.content
import android.content.res
import android.graphics
import android.os
import android.view
import java.io
import java.lang
import java.util
import java.util.concurrent
import java.util.function
import jpype
import typing



class VisibleActivityInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getActivityId(self) -> 'VoiceInteractionSession.ActivityId': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class VoiceInteractionService(android.app.Service):
    SERVICE_INTERFACE: typing.ClassVar[str] = ...
    SERVICE_META_DATA: typing.ClassVar[str] = ...
    def __init__(self): ...
    def getDisabledShowContext(self) -> int: ...
    @staticmethod
    def isActiveService(context: android.content.Context, componentName: android.content.ComponentName) -> bool: ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onGetSupportedVoiceActions(self, set: java.util.Set[str]) -> java.util.Set[str]: ...
    def onLaunchVoiceAssistFromKeyguard(self) -> None: ...
    def onPrepareToShowSession(self, bundle: android.os.Bundle, int: int) -> None: ...
    def onReady(self) -> None: ...
    def onShowSessionFailed(self, bundle: android.os.Bundle) -> None: ...
    def onShutdown(self) -> None: ...
    def setDisabledShowContext(self, int: int) -> None: ...
    def setUiHints(self, bundle: android.os.Bundle) -> None: ...
    def showSession(self, bundle: android.os.Bundle, int: int) -> None: ...

class VoiceInteractionSessionService(android.app.Service):
    def __init__(self): ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onConfigurationChanged(self, configuration: android.content.res.Configuration) -> None: ...
    def onCreate(self) -> None: ...
    def onLowMemory(self) -> None: ...
    def onNewSession(self, bundle: android.os.Bundle) -> 'VoiceInteractionSession': ...
    def onTrimMemory(self, int: int) -> None: ...

class VoiceInteractionSession(android.view.KeyEvent.Callback, android.content.ComponentCallbacks2):
    KEY_FOREGROUND_ACTIVITIES: typing.ClassVar[str] = ...
    KEY_SHOW_SESSION_ID: typing.ClassVar[str] = ...
    SHOW_SOURCE_ACTIVITY: typing.ClassVar[int] = ...
    SHOW_SOURCE_APPLICATION: typing.ClassVar[int] = ...
    SHOW_SOURCE_ASSIST_GESTURE: typing.ClassVar[int] = ...
    SHOW_SOURCE_AUTOMOTIVE_SYSTEM_UI: typing.ClassVar[int] = ...
    SHOW_SOURCE_NOTIFICATION: typing.ClassVar[int] = ...
    SHOW_SOURCE_PUSH_TO_TALK: typing.ClassVar[int] = ...
    SHOW_WITH_ASSIST: typing.ClassVar[int] = ...
    SHOW_WITH_SCREENSHOT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context): ...
    @typing.overload
    def __init__(self, context: android.content.Context, handler: android.os.Handler): ...
    def closeSystemDialogs(self) -> None: ...
    def dump(self, string: str, fileDescriptor: java.io.FileDescriptor, printWriter: java.io.PrintWriter, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    def finish(self) -> None: ...
    def getContext(self) -> android.content.Context: ...
    def getDisabledShowContext(self) -> int: ...
    def getLayoutInflater(self) -> android.view.LayoutInflater: ...
    def getUserDisabledShowContext(self) -> int: ...
    def getWindow(self) -> android.app.Dialog: ...
    def hide(self) -> None: ...
    def onAssistStructureFailure(self, throwable: java.lang.Throwable) -> None: ...
    def onBackPressed(self) -> None: ...
    def onCancelRequest(self, request: 'VoiceInteractionSession.Request') -> None: ...
    def onCloseSystemDialogs(self) -> None: ...
    def onComputeInsets(self, insets: 'VoiceInteractionSession.Insets') -> None: ...
    def onConfigurationChanged(self, configuration: android.content.res.Configuration) -> None: ...
    def onCreate(self) -> None: ...
    def onCreateContentView(self) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onDirectActionsInvalidated(self, activityId: 'VoiceInteractionSession.ActivityId') -> None: ...
    def onGetSupportedCommands(self, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> typing.MutableSequence[bool]: ...
    @typing.overload
    def onHandleAssist(self, bundle: android.os.Bundle, assistStructure: android.app.assist.AssistStructure, assistContent: android.app.assist.AssistContent) -> None: ...
    @typing.overload
    def onHandleAssist(self, assistState: 'VoiceInteractionSession.AssistState') -> None: ...
    def onHandleAssistSecondary(self, bundle: android.os.Bundle, assistStructure: android.app.assist.AssistStructure, assistContent: android.app.assist.AssistContent, int: int, int2: int) -> None: ...
    def onHandleScreenshot(self, bitmap: android.graphics.Bitmap) -> None: ...
    def onHide(self) -> None: ...
    def onKeyDown(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyLongPress(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyMultiple(self, int: int, int2: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onKeyUp(self, int: int, keyEvent: android.view.KeyEvent) -> bool: ...
    def onLockscreenShown(self) -> None: ...
    def onLowMemory(self) -> None: ...
    def onPrepareShow(self, bundle: android.os.Bundle, int: int) -> None: ...
    def onRequestAbortVoice(self, abortVoiceRequest: 'VoiceInteractionSession.AbortVoiceRequest') -> None: ...
    def onRequestCommand(self, commandRequest: 'VoiceInteractionSession.CommandRequest') -> None: ...
    def onRequestCompleteVoice(self, completeVoiceRequest: 'VoiceInteractionSession.CompleteVoiceRequest') -> None: ...
    def onRequestConfirmation(self, confirmationRequest: 'VoiceInteractionSession.ConfirmationRequest') -> None: ...
    def onRequestPickOption(self, pickOptionRequest: 'VoiceInteractionSession.PickOptionRequest') -> None: ...
    def onShow(self, bundle: android.os.Bundle, int: int) -> None: ...
    def onTaskFinished(self, intent: android.content.Intent, int2: int) -> None: ...
    def onTaskStarted(self, intent: android.content.Intent, int2: int) -> None: ...
    def onTrimMemory(self, int: int) -> None: ...
    def performDirectAction(self, directAction: android.app.DirectAction, bundle: android.os.Bundle, cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[android.os.Bundle], typing.Callable[[android.os.Bundle], None]]) -> None: ...
    def registerVisibleActivityCallback(self, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], visibleActivityCallback: 'VoiceInteractionSession.VisibleActivityCallback') -> None: ...
    def requestDirectActions(self, activityId: 'VoiceInteractionSession.ActivityId', cancellationSignal: android.os.CancellationSignal, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], consumer: typing.Union[java.util.function.Consumer[java.util.List[android.app.DirectAction]], typing.Callable[[java.util.List[android.app.DirectAction]], None]]) -> None: ...
    def setContentView(self, view: android.view.View) -> None: ...
    def setDisabledShowContext(self, int: int) -> None: ...
    def setKeepAwake(self, boolean: bool) -> None: ...
    def setTheme(self, int: int) -> None: ...
    def setUiEnabled(self, boolean: bool) -> None: ...
    def show(self, bundle: android.os.Bundle, int: int) -> None: ...
    @typing.overload
    def startAssistantActivity(self, intent: android.content.Intent) -> None: ...
    @typing.overload
    def startAssistantActivity(self, intent: android.content.Intent, bundle: android.os.Bundle) -> None: ...
    def startVoiceActivity(self, intent: android.content.Intent) -> None: ...
    def unregisterVisibleActivityCallback(self, visibleActivityCallback: 'VoiceInteractionSession.VisibleActivityCallback') -> None: ...
    class AbortVoiceRequest(android.service.voice.VoiceInteractionSession.Request):
        def getMessage(self) -> java.lang.CharSequence: ...
        def getVoicePrompt(self) -> android.app.VoiceInteractor.Prompt: ...
        def sendAbortResult(self, bundle: android.os.Bundle) -> None: ...
    class ActivityId:
        def equals(self, object: typing.Any) -> bool: ...
        def hashCode(self) -> int: ...
    class AssistState:
        def getActivityId(self) -> 'VoiceInteractionSession.ActivityId': ...
        def getAssistContent(self) -> android.app.assist.AssistContent: ...
        def getAssistData(self) -> android.os.Bundle: ...
        def getAssistStructure(self) -> android.app.assist.AssistStructure: ...
        def getCount(self) -> int: ...
        def getIndex(self) -> int: ...
        def isFocused(self) -> bool: ...
    class CommandRequest(android.service.voice.VoiceInteractionSession.Request):
        def getCommand(self) -> str: ...
        def sendIntermediateResult(self, bundle: android.os.Bundle) -> None: ...
        def sendResult(self, bundle: android.os.Bundle) -> None: ...
    class CompleteVoiceRequest(android.service.voice.VoiceInteractionSession.Request):
        def getMessage(self) -> java.lang.CharSequence: ...
        def getVoicePrompt(self) -> android.app.VoiceInteractor.Prompt: ...
        def sendCompleteResult(self, bundle: android.os.Bundle) -> None: ...
    class ConfirmationRequest(android.service.voice.VoiceInteractionSession.Request):
        def getPrompt(self) -> java.lang.CharSequence: ...
        def getVoicePrompt(self) -> android.app.VoiceInteractor.Prompt: ...
        def sendConfirmationResult(self, boolean: bool, bundle: android.os.Bundle) -> None: ...
    class Insets:
        TOUCHABLE_INSETS_CONTENT: typing.ClassVar[int] = ...
        TOUCHABLE_INSETS_FRAME: typing.ClassVar[int] = ...
        TOUCHABLE_INSETS_REGION: typing.ClassVar[int] = ...
        contentInsets: android.graphics.Rect = ...
        touchableInsets: int = ...
        touchableRegion: android.graphics.Region = ...
        def __init__(self): ...
    class PickOptionRequest(android.service.voice.VoiceInteractionSession.Request):
        def getOptions(self) -> typing.MutableSequence[android.app.VoiceInteractor.PickOptionRequest.Option]: ...
        def getPrompt(self) -> java.lang.CharSequence: ...
        def getVoicePrompt(self) -> android.app.VoiceInteractor.Prompt: ...
        def sendIntermediatePickOptionResult(self, optionArray: typing.Union[typing.List[android.app.VoiceInteractor.PickOptionRequest.Option], jpype.JArray], bundle: android.os.Bundle) -> None: ...
        def sendPickOptionResult(self, optionArray: typing.Union[typing.List[android.app.VoiceInteractor.PickOptionRequest.Option], jpype.JArray], bundle: android.os.Bundle) -> None: ...
    class Request:
        def cancel(self) -> None: ...
        def getCallingPackage(self) -> str: ...
        def getCallingUid(self) -> int: ...
        def getExtras(self) -> android.os.Bundle: ...
        def isActive(self) -> bool: ...
        def toString(self) -> str: ...
    class VisibleActivityCallback:
        def onInvisible(self, activityId: 'VoiceInteractionSession.ActivityId') -> None: ...
        def onVisible(self, visibleActivityInfo: VisibleActivityInfo) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.service.voice")``.

    VisibleActivityInfo: typing.Type[VisibleActivityInfo]
    VoiceInteractionService: typing.Type[VoiceInteractionService]
    VoiceInteractionSession: typing.Type[VoiceInteractionSession]
    VoiceInteractionSessionService: typing.Type[VoiceInteractionSessionService]
