
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.content
import android.net
import android.os
import java.lang
import java.util
import jpype
import typing



class DownloadProgressListener:
    def __init__(self): ...
    def onProgressUpdated(self, downloadRequest: 'DownloadRequest', fileInfo: 'FileInfo', int: int, int2: int, int3: int, int4: int) -> None: ...

class DownloadRequest(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getDestinationUri(self) -> android.net.Uri: ...
    def getFileServiceId(self) -> str: ...
    @staticmethod
    def getMaxAppIntentSize() -> int: ...
    @staticmethod
    def getMaxDestinationUriSize() -> int: ...
    def getSourceUri(self) -> android.net.Uri: ...
    def getSubscriptionId(self) -> int: ...
    def hashCode(self) -> int: ...
    def toByteArray(self) -> typing.MutableSequence[int]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, uri: android.net.Uri, uri2: android.net.Uri): ...
        def build(self) -> 'DownloadRequest': ...
        @staticmethod
        def fromDownloadRequest(downloadRequest: 'DownloadRequest') -> 'DownloadRequest.Builder': ...
        @staticmethod
        def fromSerializedRequest(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'DownloadRequest.Builder': ...
        def setAppIntent(self, intent: android.content.Intent) -> 'DownloadRequest.Builder': ...
        def setServiceInfo(self, fileServiceInfo: 'FileServiceInfo') -> 'DownloadRequest.Builder': ...
        def setSubscriptionId(self, int: int) -> 'DownloadRequest.Builder': ...

class DownloadStatusListener:
    def __init__(self): ...
    def onStatusUpdated(self, downloadRequest: DownloadRequest, fileInfo: 'FileInfo', int: int) -> None: ...

class FileInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMimeType(self) -> str: ...
    def getUri(self) -> android.net.Uri: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class GroupCall(java.lang.AutoCloseable):
    REASON_BY_USER_REQUEST: typing.ClassVar[int] = ...
    REASON_FREQUENCY_CONFLICT: typing.ClassVar[int] = ...
    REASON_LEFT_MBMS_BROADCAST_AREA: typing.ClassVar[int] = ...
    REASON_NONE: typing.ClassVar[int] = ...
    REASON_NOT_CONNECTED_TO_HOMECARRIER_LTE: typing.ClassVar[int] = ...
    REASON_OUT_OF_MEMORY: typing.ClassVar[int] = ...
    STATE_STALLED: typing.ClassVar[int] = ...
    STATE_STARTED: typing.ClassVar[int] = ...
    STATE_STOPPED: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def getTmgi(self) -> int: ...
    def updateGroupCall(self, list: java.util.List[int], list2: java.util.List[int]) -> None: ...

class GroupCallCallback:
    SIGNAL_STRENGTH_UNAVAILABLE: typing.ClassVar[int] = ...
    def onBroadcastSignalStrengthUpdated(self, int: int) -> None: ...
    def onError(self, int: int, string: str) -> None: ...
    def onGroupCallStateChanged(self, int: int, int2: int) -> None: ...

class MbmsDownloadReceiver(android.content.BroadcastReceiver):
    def __init__(self): ...
    def onReceive(self, context: android.content.Context, intent: android.content.Intent) -> None: ...

class MbmsDownloadSessionCallback:
    def __init__(self): ...
    def onError(self, int: int, string: str) -> None: ...
    def onFileServicesUpdated(self, list: java.util.List['FileServiceInfo']) -> None: ...
    def onMiddlewareReady(self) -> None: ...

class MbmsErrors:
    ERROR_MIDDLEWARE_LOST: typing.ClassVar[int] = ...
    ERROR_MIDDLEWARE_NOT_BOUND: typing.ClassVar[int] = ...
    ERROR_NO_UNIQUE_MIDDLEWARE: typing.ClassVar[int] = ...
    SUCCESS: typing.ClassVar[int] = ...
    UNKNOWN: typing.ClassVar[int] = ...
    class DownloadErrors:
        ERROR_CANNOT_CHANGE_TEMP_FILE_ROOT: typing.ClassVar[int] = ...
        ERROR_MALFORMED_SERVICE_ANNOUNCEMENT: typing.ClassVar[int] = ...
        ERROR_UNKNOWN_DOWNLOAD_REQUEST: typing.ClassVar[int] = ...
        ERROR_UNKNOWN_FILE_INFO: typing.ClassVar[int] = ...
    class GeneralErrors:
        ERROR_CARRIER_CHANGE_NOT_ALLOWED: typing.ClassVar[int] = ...
        ERROR_IN_E911: typing.ClassVar[int] = ...
        ERROR_MIDDLEWARE_NOT_YET_READY: typing.ClassVar[int] = ...
        ERROR_MIDDLEWARE_TEMPORARILY_UNAVAILABLE: typing.ClassVar[int] = ...
        ERROR_NOT_CONNECTED_TO_HOME_CARRIER_LTE: typing.ClassVar[int] = ...
        ERROR_OUT_OF_MEMORY: typing.ClassVar[int] = ...
        ERROR_UNABLE_TO_READ_SIM: typing.ClassVar[int] = ...
    class GroupCallErrors:
        ERROR_DUPLICATE_START_GROUP_CALL: typing.ClassVar[int] = ...
        ERROR_UNABLE_TO_START_SERVICE: typing.ClassVar[int] = ...
    class InitializationErrors:
        ERROR_APP_PERMISSIONS_NOT_GRANTED: typing.ClassVar[int] = ...
        ERROR_DUPLICATE_INITIALIZE: typing.ClassVar[int] = ...
        ERROR_UNABLE_TO_INITIALIZE: typing.ClassVar[int] = ...
    class StreamingErrors:
        ERROR_CONCURRENT_SERVICE_LIMIT_REACHED: typing.ClassVar[int] = ...
        ERROR_DUPLICATE_START_STREAM: typing.ClassVar[int] = ...
        ERROR_UNABLE_TO_START_SERVICE: typing.ClassVar[int] = ...

class MbmsGroupCallSessionCallback:
    def onAvailableSaisUpdated(self, list: java.util.List[int], list2: java.util.List[java.util.List[int]]) -> None: ...
    def onError(self, int: int, string: str) -> None: ...
    def onMiddlewareReady(self) -> None: ...
    def onServiceInterfaceAvailable(self, string: str, int: int) -> None: ...

class MbmsStreamingSessionCallback:
    def __init__(self): ...
    def onError(self, int: int, string: str) -> None: ...
    def onMiddlewareReady(self) -> None: ...
    def onStreamingServicesUpdated(self, list: java.util.List['StreamingServiceInfo']) -> None: ...

class ServiceInfo:
    def equals(self, object: typing.Any) -> bool: ...
    def getLocales(self) -> java.util.List[java.util.Locale]: ...
    def getNameForLocale(self, locale: java.util.Locale) -> java.lang.CharSequence: ...
    def getNamedContentLocales(self) -> java.util.Set[java.util.Locale]: ...
    def getServiceClassName(self) -> str: ...
    def getServiceId(self) -> str: ...
    def getSessionEndTime(self) -> java.util.Date: ...
    def getSessionStartTime(self) -> java.util.Date: ...
    def hashCode(self) -> int: ...

class StreamingService(java.lang.AutoCloseable):
    BROADCAST_METHOD: typing.ClassVar[int] = ...
    REASON_BY_USER_REQUEST: typing.ClassVar[int] = ...
    REASON_END_OF_SESSION: typing.ClassVar[int] = ...
    REASON_FREQUENCY_CONFLICT: typing.ClassVar[int] = ...
    REASON_LEFT_MBMS_BROADCAST_AREA: typing.ClassVar[int] = ...
    REASON_NONE: typing.ClassVar[int] = ...
    REASON_NOT_CONNECTED_TO_HOMECARRIER_LTE: typing.ClassVar[int] = ...
    REASON_OUT_OF_MEMORY: typing.ClassVar[int] = ...
    STATE_STALLED: typing.ClassVar[int] = ...
    STATE_STARTED: typing.ClassVar[int] = ...
    STATE_STOPPED: typing.ClassVar[int] = ...
    UNICAST_METHOD: typing.ClassVar[int] = ...
    def close(self) -> None: ...
    def getInfo(self) -> 'StreamingServiceInfo': ...
    def getPlaybackUri(self) -> android.net.Uri: ...

class StreamingServiceCallback:
    SIGNAL_STRENGTH_UNAVAILABLE: typing.ClassVar[int] = ...
    def __init__(self): ...
    def onBroadcastSignalStrengthUpdated(self, int: int) -> None: ...
    def onError(self, int: int, string: str) -> None: ...
    def onMediaDescriptionUpdated(self) -> None: ...
    def onStreamMethodUpdated(self, int: int) -> None: ...
    def onStreamStateUpdated(self, int: int, int2: int) -> None: ...

class FileServiceInfo(ServiceInfo, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getFiles(self) -> java.util.List[FileInfo]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class StreamingServiceInfo(ServiceInfo, android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.telephony.mbms")``.

    DownloadProgressListener: typing.Type[DownloadProgressListener]
    DownloadRequest: typing.Type[DownloadRequest]
    DownloadStatusListener: typing.Type[DownloadStatusListener]
    FileInfo: typing.Type[FileInfo]
    FileServiceInfo: typing.Type[FileServiceInfo]
    GroupCall: typing.Type[GroupCall]
    GroupCallCallback: typing.Type[GroupCallCallback]
    MbmsDownloadReceiver: typing.Type[MbmsDownloadReceiver]
    MbmsDownloadSessionCallback: typing.Type[MbmsDownloadSessionCallback]
    MbmsErrors: typing.Type[MbmsErrors]
    MbmsGroupCallSessionCallback: typing.Type[MbmsGroupCallSessionCallback]
    MbmsStreamingSessionCallback: typing.Type[MbmsStreamingSessionCallback]
    ServiceInfo: typing.Type[ServiceInfo]
    StreamingService: typing.Type[StreamingService]
    StreamingServiceCallback: typing.Type[StreamingServiceCallback]
    StreamingServiceInfo: typing.Type[StreamingServiceInfo]
