
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.app
import android.content
import android.net
import android.os
import android.view
import datetime
import java.lang
import java.time
import java.util
import java.util.concurrent
import jpype
import typing



class AppInfo(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def isInstalled(self) -> bool: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class DownloadCompletedInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getDownloadedContents(self) -> 'KeyValueStore': ...
    def hashCode(self) -> int: ...

class DownloadCompletedOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getRetainedKeys(self) -> java.util.List[str]: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addRetainedKey(self, string: str) -> 'DownloadCompletedOutput.Builder': ...
        def build(self) -> 'DownloadCompletedOutput': ...
        def setRetainedKeys(self, list: java.util.List[str]) -> 'DownloadCompletedOutput.Builder': ...

class EventInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getParameters(self) -> android.os.PersistableBundle: ...
    def getRequestLogRecord(self) -> 'RequestLogRecord': ...
    def hashCode(self) -> int: ...

class EventLogRecord(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getData(self) -> android.content.ContentValues: ...
    def getRequestLogRecord(self) -> 'RequestLogRecord': ...
    def getRowIndex(self) -> int: ...
    def getTime(self) -> java.time.Instant: ...
    def getType(self) -> int: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EventLogRecord': ...
        def setData(self, contentValues: android.content.ContentValues) -> 'EventLogRecord.Builder': ...
        def setRequestLogRecord(self, requestLogRecord: 'RequestLogRecord') -> 'EventLogRecord.Builder': ...
        def setRowIndex(self, int: int) -> 'EventLogRecord.Builder': ...
        def setType(self, int: int) -> 'EventLogRecord.Builder': ...

class EventOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getEventLogRecord(self) -> EventLogRecord: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EventOutput': ...
        def setEventLogRecord(self, eventLogRecord: EventLogRecord) -> 'EventOutput.Builder': ...

class EventUrlProvider:
    def createEventTrackingUrlWithRedirect(self, persistableBundle: android.os.PersistableBundle, uri: android.net.Uri) -> android.net.Uri: ...
    def createEventTrackingUrlWithResponse(self, persistableBundle: android.os.PersistableBundle, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], string: str) -> android.net.Uri: ...

class ExecuteInput:
    def getAppPackageName(self) -> str: ...
    def getAppParams(self) -> android.os.PersistableBundle: ...

class ExecuteOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getEventLogRecords(self) -> java.util.List[EventLogRecord]: ...
    def getOutputData(self) -> typing.MutableSequence[int]: ...
    def getRenderingConfig(self) -> 'RenderingConfig': ...
    def getRequestLogRecord(self) -> 'RequestLogRecord': ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addEventLogRecord(self, eventLogRecord: EventLogRecord) -> 'ExecuteOutput.Builder': ...
        def build(self) -> 'ExecuteOutput': ...
        def setEventLogRecords(self, list: java.util.List[EventLogRecord]) -> 'ExecuteOutput.Builder': ...
        def setOutputData(self, *byte: int) -> 'ExecuteOutput.Builder': ...
        def setRenderingConfig(self, renderingConfig: 'RenderingConfig') -> 'ExecuteOutput.Builder': ...
        def setRequestLogRecord(self, requestLogRecord: 'RequestLogRecord') -> 'ExecuteOutput.Builder': ...

class FederatedComputeInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getPopulationName(self) -> str: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'FederatedComputeInput': ...
        def setPopulationName(self, string: str) -> 'FederatedComputeInput.Builder': ...

class FederatedComputeScheduler:
    def cancel(self, federatedComputeInput: FederatedComputeInput) -> None: ...
    def schedule(self, params: 'FederatedComputeScheduler.Params', federatedComputeInput: FederatedComputeInput) -> None: ...
    class Params:
        def __init__(self, trainingInterval: 'TrainingInterval'): ...
        def getTrainingInterval(self) -> 'TrainingInterval': ...

class InferenceInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getBatchSize(self) -> int: ...
    def getExpectedOutputStructure(self) -> 'InferenceOutput': ...
    def getInputData(self) -> typing.MutableSequence[typing.Any]: ...
    def getParams(self) -> 'InferenceInput.Params': ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self, params: 'InferenceInput.Params', objectArray: typing.Union[typing.List[typing.Any], jpype.JArray], inferenceOutput: 'InferenceOutput'): ...
        def build(self) -> 'InferenceInput': ...
        def setBatchSize(self, int: int) -> 'InferenceInput.Builder': ...
        def setExpectedOutputStructure(self, inferenceOutput: 'InferenceOutput') -> 'InferenceInput.Builder': ...
        def setInputData(self, *object: typing.Any) -> 'InferenceInput.Builder': ...
        def setParams(self, params: 'InferenceInput.Params') -> 'InferenceInput.Builder': ...
    class Params:
        DELEGATE_CPU: typing.ClassVar[int] = ...
        MODEL_TYPE_TENSORFLOW_LITE: typing.ClassVar[int] = ...
        def equals(self, object: typing.Any) -> bool: ...
        def getDelegateType(self) -> int: ...
        def getKeyValueStore(self) -> 'KeyValueStore': ...
        def getModelKey(self) -> str: ...
        def getModelType(self) -> int: ...
        def getRecommendedNumThreads(self) -> int: ...
        def hashCode(self) -> int: ...
        class Builder:
            def __init__(self, keyValueStore: 'KeyValueStore', string: str): ...
            def build(self) -> 'InferenceInput.Params': ...
            def setDelegateType(self, int: int) -> 'InferenceInput.Params.Builder': ...
            def setKeyValueStore(self, keyValueStore: 'KeyValueStore') -> 'InferenceInput.Params.Builder': ...
            def setModelKey(self, string: str) -> 'InferenceInput.Params.Builder': ...
            def setModelType(self, int: int) -> 'InferenceInput.Params.Builder': ...
            def setRecommendedNumThreads(self, int: int) -> 'InferenceInput.Params.Builder': ...

class InferenceOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getDataOutputs(self) -> java.util.Map[int, typing.Any]: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addDataOutput(self, int: int, object: typing.Any) -> 'InferenceOutput.Builder': ...
        def build(self) -> 'InferenceOutput': ...
        def setDataOutputs(self, map: typing.Union[java.util.Map[int, typing.Any], typing.Mapping[int, typing.Any]]) -> 'InferenceOutput.Builder': ...

class IsolatedService(android.app.Service):
    def __init__(self): ...
    def getEventUrlProvider(self, requestToken: 'RequestToken') -> EventUrlProvider: ...
    def getFederatedComputeScheduler(self, requestToken: 'RequestToken') -> FederatedComputeScheduler: ...
    def getLocalData(self, requestToken: 'RequestToken') -> 'MutableKeyValueStore': ...
    def getLogReader(self, requestToken: 'RequestToken') -> 'LogReader': ...
    def getModelManager(self, requestToken: 'RequestToken') -> 'ModelManager': ...
    def getRemoteData(self, requestToken: 'RequestToken') -> 'KeyValueStore': ...
    def getUserData(self, requestToken: 'RequestToken') -> 'UserData': ...
    def onBind(self, intent: android.content.Intent) -> android.os.IBinder: ...
    def onCreate(self) -> None: ...
    def onRequest(self, requestToken: 'RequestToken') -> 'IsolatedWorker': ...

class IsolatedServiceException(java.lang.Exception):
    def __init__(self, int: int): ...

class IsolatedWorker:
    def onDownloadCompleted(self, downloadCompletedInput: DownloadCompletedInput, outcomeReceiver: typing.Union[android.os.OutcomeReceiver[DownloadCompletedOutput, IsolatedServiceException], typing.Callable[[DownloadCompletedOutput], None]]) -> None: ...
    def onEvent(self, eventInput: EventInput, outcomeReceiver: typing.Union[android.os.OutcomeReceiver[EventOutput, IsolatedServiceException], typing.Callable[[EventOutput], None]]) -> None: ...
    def onExecute(self, executeInput: ExecuteInput, outcomeReceiver: typing.Union[android.os.OutcomeReceiver[ExecuteOutput, IsolatedServiceException], typing.Callable[[ExecuteOutput], None]]) -> None: ...
    def onRender(self, renderInput: 'RenderInput', outcomeReceiver: typing.Union[android.os.OutcomeReceiver['RenderOutput', IsolatedServiceException], typing.Callable[['RenderOutput'], None]]) -> None: ...
    def onTrainingExamples(self, trainingExamplesInput: 'TrainingExamplesInput', outcomeReceiver: typing.Union[android.os.OutcomeReceiver['TrainingExamplesOutput', IsolatedServiceException], typing.Callable[['TrainingExamplesOutput'], None]]) -> None: ...
    def onWebTrigger(self, webTriggerInput: 'WebTriggerInput', outcomeReceiver: typing.Union[android.os.OutcomeReceiver['WebTriggerOutput', IsolatedServiceException], typing.Callable[['WebTriggerOutput'], None]]) -> None: ...

class KeyValueStore:
    def get(self, string: str) -> typing.MutableSequence[int]: ...
    def keySet(self) -> java.util.Set[str]: ...

class LogReader:
    def getJoinedEvents(self, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]) -> java.util.List[EventLogRecord]: ...
    def getRequests(self, instant: typing.Union[java.time.Instant, datetime.datetime], instant2: typing.Union[java.time.Instant, datetime.datetime]) -> java.util.List['RequestLogRecord']: ...

class ModelManager:
    def run(self, inferenceInput: InferenceInput, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[InferenceOutput, java.lang.Exception], typing.Callable[[InferenceOutput], None]]) -> None: ...

class OnDevicePersonalizationException(java.lang.Exception):
    ERROR_ISOLATED_SERVICE_FAILED: typing.ClassVar[int] = ...
    ERROR_PERSONALIZATION_DISABLED: typing.ClassVar[int] = ...
    def getErrorCode(self) -> int: ...

class OnDevicePersonalizationManager:
    def execute(self, componentName: android.content.ComponentName, persistableBundle: android.os.PersistableBundle, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver['OnDevicePersonalizationManager.ExecuteResult', java.lang.Exception], typing.Callable[['OnDevicePersonalizationManager.ExecuteResult'], None]]) -> None: ...
    def requestSurfacePackage(self, surfacePackageToken: 'SurfacePackageToken', iBinder: android.os.IBinder, int: int, int2: int, int3: int, executor: typing.Union[java.util.concurrent.Executor, typing.Callable], outcomeReceiver: typing.Union[android.os.OutcomeReceiver[android.view.SurfaceControlViewHost.SurfacePackage, java.lang.Exception], typing.Callable[[android.view.SurfaceControlViewHost.SurfacePackage], None]]) -> None: ...
    class ExecuteResult:
        def getOutputData(self) -> typing.MutableSequence[int]: ...
        def getSurfacePackageToken(self) -> 'SurfacePackageToken': ...

class RenderInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getHeight(self) -> int: ...
    def getRenderingConfig(self) -> 'RenderingConfig': ...
    def getWidth(self) -> int: ...
    def hashCode(self) -> int: ...

class RenderOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getContent(self) -> str: ...
    def getTemplateId(self) -> str: ...
    def getTemplateParams(self) -> android.os.PersistableBundle: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'RenderOutput': ...
        def setContent(self, string: str) -> 'RenderOutput.Builder': ...
        def setTemplateId(self, string: str) -> 'RenderOutput.Builder': ...
        def setTemplateParams(self, persistableBundle: android.os.PersistableBundle) -> 'RenderOutput.Builder': ...

class RenderingConfig(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getKeys(self) -> java.util.List[str]: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addKey(self, string: str) -> 'RenderingConfig.Builder': ...
        def build(self) -> 'RenderingConfig': ...
        def setKeys(self, list: java.util.List[str]) -> 'RenderingConfig.Builder': ...

class RequestLogRecord(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getRows(self) -> java.util.List[android.content.ContentValues]: ...
    def getTime(self) -> java.time.Instant: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def addRow(self, contentValues: android.content.ContentValues) -> 'RequestLogRecord.Builder': ...
        def build(self) -> 'RequestLogRecord': ...
        def setRows(self, list: java.util.List[android.content.ContentValues]) -> 'RequestLogRecord.Builder': ...

class RequestToken: ...

class SurfacePackageToken: ...

class TrainingExampleRecord(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def getResumptionToken(self) -> typing.MutableSequence[int]: ...
    def getTrainingExample(self) -> typing.MutableSequence[int]: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'TrainingExampleRecord': ...
        def setResumptionToken(self, *byte: int) -> 'TrainingExampleRecord.Builder': ...
        def setTrainingExample(self, *byte: int) -> 'TrainingExampleRecord.Builder': ...

class TrainingExamplesInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getPopulationName(self) -> str: ...
    def getResumptionToken(self) -> typing.MutableSequence[int]: ...
    def getTaskName(self) -> str: ...
    def hashCode(self) -> int: ...

class TrainingExamplesOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getTrainingExampleRecords(self) -> java.util.List[TrainingExampleRecord]: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addTrainingExampleRecord(self, trainingExampleRecord: TrainingExampleRecord) -> 'TrainingExamplesOutput.Builder': ...
        def build(self) -> 'TrainingExamplesOutput': ...
        def setTrainingExampleRecords(self, list: java.util.List[TrainingExampleRecord]) -> 'TrainingExamplesOutput.Builder': ...

class TrainingInterval:
    SCHEDULING_MODE_ONE_TIME: typing.ClassVar[int] = ...
    SCHEDULING_MODE_RECURRENT: typing.ClassVar[int] = ...
    def equals(self, object: typing.Any) -> bool: ...
    def getMinimumInterval(self) -> java.time.Duration: ...
    def getSchedulingMode(self) -> int: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'TrainingInterval': ...
        def setMinimumInterval(self, duration: java.time.Duration) -> 'TrainingInterval.Builder': ...
        def setSchedulingMode(self, int: int) -> 'TrainingInterval.Builder': ...

class UserData(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAppInfos(self) -> java.util.Map[str, AppInfo]: ...
    def getAvailableStorageBytes(self) -> int: ...
    def getBatteryPercentage(self) -> int: ...
    def getCarrier(self) -> str: ...
    def getDataNetworkType(self) -> int: ...
    def getNetworkCapabilities(self) -> android.net.NetworkCapabilities: ...
    def getOrientation(self) -> int: ...
    def getTimezoneUtcOffset(self) -> java.time.Duration: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class WebTriggerInput:
    def equals(self, object: typing.Any) -> bool: ...
    def getAppPackageName(self) -> str: ...
    def getData(self) -> typing.MutableSequence[int]: ...
    def getDestinationUrl(self) -> android.net.Uri: ...
    def hashCode(self) -> int: ...

class WebTriggerOutput:
    def equals(self, object: typing.Any) -> bool: ...
    def getEventLogRecords(self) -> java.util.List[EventLogRecord]: ...
    def getRequestLogRecord(self) -> RequestLogRecord: ...
    def hashCode(self) -> int: ...
    class Builder:
        def __init__(self): ...
        def addEventLogRecord(self, eventLogRecord: EventLogRecord) -> 'WebTriggerOutput.Builder': ...
        def build(self) -> 'WebTriggerOutput': ...
        def setEventLogRecords(self, list: java.util.List[EventLogRecord]) -> 'WebTriggerOutput.Builder': ...
        def setRequestLogRecord(self, requestLogRecord: RequestLogRecord) -> 'WebTriggerOutput.Builder': ...

class MutableKeyValueStore(KeyValueStore):
    def put(self, string: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> typing.MutableSequence[int]: ...
    def remove(self, string: str) -> typing.MutableSequence[int]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.adservices.ondevicepersonalization")``.

    AppInfo: typing.Type[AppInfo]
    DownloadCompletedInput: typing.Type[DownloadCompletedInput]
    DownloadCompletedOutput: typing.Type[DownloadCompletedOutput]
    EventInput: typing.Type[EventInput]
    EventLogRecord: typing.Type[EventLogRecord]
    EventOutput: typing.Type[EventOutput]
    EventUrlProvider: typing.Type[EventUrlProvider]
    ExecuteInput: typing.Type[ExecuteInput]
    ExecuteOutput: typing.Type[ExecuteOutput]
    FederatedComputeInput: typing.Type[FederatedComputeInput]
    FederatedComputeScheduler: typing.Type[FederatedComputeScheduler]
    InferenceInput: typing.Type[InferenceInput]
    InferenceOutput: typing.Type[InferenceOutput]
    IsolatedService: typing.Type[IsolatedService]
    IsolatedServiceException: typing.Type[IsolatedServiceException]
    IsolatedWorker: typing.Type[IsolatedWorker]
    KeyValueStore: typing.Type[KeyValueStore]
    LogReader: typing.Type[LogReader]
    ModelManager: typing.Type[ModelManager]
    MutableKeyValueStore: typing.Type[MutableKeyValueStore]
    OnDevicePersonalizationException: typing.Type[OnDevicePersonalizationException]
    OnDevicePersonalizationManager: typing.Type[OnDevicePersonalizationManager]
    RenderInput: typing.Type[RenderInput]
    RenderOutput: typing.Type[RenderOutput]
    RenderingConfig: typing.Type[RenderingConfig]
    RequestLogRecord: typing.Type[RequestLogRecord]
    RequestToken: typing.Type[RequestToken]
    SurfacePackageToken: typing.Type[SurfacePackageToken]
    TrainingExampleRecord: typing.Type[TrainingExampleRecord]
    TrainingExamplesInput: typing.Type[TrainingExamplesInput]
    TrainingExamplesOutput: typing.Type[TrainingExamplesOutput]
    TrainingInterval: typing.Type[TrainingInterval]
    UserData: typing.Type[UserData]
    WebTriggerInput: typing.Type[WebTriggerInput]
    WebTriggerOutput: typing.Type[WebTriggerOutput]
