
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import android.net
import android.os
import java.lang
import java.time
import java.util
import typing



class AdData(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdCounterKeys(self) -> java.util.Set[int]: ...
    def getAdFilters(self) -> 'AdFilters': ...
    def getAdRenderId(self) -> str: ...
    def getMetadata(self) -> str: ...
    def getRenderUri(self) -> android.net.Uri: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdData': ...
        def setAdCounterKeys(self, set: java.util.Set[int]) -> 'AdData.Builder': ...
        def setAdFilters(self, adFilters: 'AdFilters') -> 'AdData.Builder': ...
        def setAdRenderId(self, string: str) -> 'AdData.Builder': ...
        def setMetadata(self, string: str) -> 'AdData.Builder': ...
        def setRenderUri(self, uri: android.net.Uri) -> 'AdData.Builder': ...

class AdFilters(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAppInstallFilters(self) -> 'AppInstallFilters': ...
    def getFrequencyCapFilters(self) -> 'FrequencyCapFilters': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AdFilters': ...
        def setAppInstallFilters(self, appInstallFilters: 'AppInstallFilters') -> 'AdFilters.Builder': ...
        def setFrequencyCapFilters(self, frequencyCapFilters: 'FrequencyCapFilters') -> 'AdFilters.Builder': ...

class AdSelectionSignals(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    EMPTY: typing.ClassVar['AdSelectionSignals'] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromString(string: str) -> 'AdSelectionSignals': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

_AdServicesOutcomeReceiver__R = typing.TypeVar('_AdServicesOutcomeReceiver__R')  # <R>
_AdServicesOutcomeReceiver__E = typing.TypeVar('_AdServicesOutcomeReceiver__E', bound=java.lang.Throwable)  # <E>
class AdServicesOutcomeReceiver(typing.Generic[_AdServicesOutcomeReceiver__R, _AdServicesOutcomeReceiver__E]):
    def onError(self, e: _AdServicesOutcomeReceiver__E) -> None: ...
    def onResult(self, r: _AdServicesOutcomeReceiver__R) -> None: ...

class AdServicesPermissions:
    ACCESS_ADSERVICES_AD_ID: typing.ClassVar[str] = ...
    ACCESS_ADSERVICES_AD_SELECTION: typing.ClassVar[str] = ...
    ACCESS_ADSERVICES_ATTRIBUTION: typing.ClassVar[str] = ...
    ACCESS_ADSERVICES_CUSTOM_AUDIENCE: typing.ClassVar[str] = ...
    ACCESS_ADSERVICES_PROTECTED_SIGNALS: typing.ClassVar[str] = ...
    ACCESS_ADSERVICES_TOPICS: typing.ClassVar[str] = ...

class AdTechIdentifier(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromString(string: str) -> 'AdTechIdentifier': ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...

class AppInstallFilters(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getPackageNames(self) -> java.util.Set[str]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'AppInstallFilters': ...
        def setPackageNames(self, set: java.util.Set[str]) -> 'AppInstallFilters.Builder': ...

class FrequencyCapFilters(android.os.Parcelable):
    AD_EVENT_TYPE_CLICK: typing.ClassVar[int] = ...
    AD_EVENT_TYPE_IMPRESSION: typing.ClassVar[int] = ...
    AD_EVENT_TYPE_VIEW: typing.ClassVar[int] = ...
    AD_EVENT_TYPE_WIN: typing.ClassVar[int] = ...
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getKeyedFrequencyCapsForClickEvents(self) -> java.util.List['KeyedFrequencyCap']: ...
    def getKeyedFrequencyCapsForImpressionEvents(self) -> java.util.List['KeyedFrequencyCap']: ...
    def getKeyedFrequencyCapsForViewEvents(self) -> java.util.List['KeyedFrequencyCap']: ...
    def getKeyedFrequencyCapsForWinEvents(self) -> java.util.List['KeyedFrequencyCap']: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'FrequencyCapFilters': ...
        def setKeyedFrequencyCapsForClickEvents(self, list: java.util.List['KeyedFrequencyCap']) -> 'FrequencyCapFilters.Builder': ...
        def setKeyedFrequencyCapsForImpressionEvents(self, list: java.util.List['KeyedFrequencyCap']) -> 'FrequencyCapFilters.Builder': ...
        def setKeyedFrequencyCapsForViewEvents(self, list: java.util.List['KeyedFrequencyCap']) -> 'FrequencyCapFilters.Builder': ...
        def setKeyedFrequencyCapsForWinEvents(self, list: java.util.List['KeyedFrequencyCap']) -> 'FrequencyCapFilters.Builder': ...

class KeyedFrequencyCap(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator] = ...
    def describeContents(self) -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAdCounterKey(self) -> int: ...
    def getInterval(self) -> java.time.Duration: ...
    def getMaxCount(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, parcel: android.os.Parcel, int: int) -> None: ...
    class Builder:
        def __init__(self, int: int, int2: int, duration: java.time.Duration): ...
        def build(self) -> 'KeyedFrequencyCap': ...
        def setAdCounterKey(self, int: int) -> 'KeyedFrequencyCap.Builder': ...
        def setInterval(self, duration: java.time.Duration) -> 'KeyedFrequencyCap.Builder': ...
        def setMaxCount(self, int: int) -> 'KeyedFrequencyCap.Builder': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("android.adservices.common")``.

    AdData: typing.Type[AdData]
    AdFilters: typing.Type[AdFilters]
    AdSelectionSignals: typing.Type[AdSelectionSignals]
    AdServicesOutcomeReceiver: typing.Type[AdServicesOutcomeReceiver]
    AdServicesPermissions: typing.Type[AdServicesPermissions]
    AdTechIdentifier: typing.Type[AdTechIdentifier]
    AppInstallFilters: typing.Type[AppInstallFilters]
    FrequencyCapFilters: typing.Type[FrequencyCapFilters]
    KeyedFrequencyCap: typing.Type[KeyedFrequencyCap]
